-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMNBmNsYW5JZA5taXNzaW5nIGNsYW5JZAZhc3NlcnQFdGFibGUFY2xvbmUFdmFsdWUMc2V0U3RhcnRlZEF0BGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlBVJvZHV4DWNyZWF0ZVJlZHVjZXIAAgUCAAAAABZNBAEbAAAAAEcEAgAAAACAqQMAAakDAQCBAQMEAQAAAG8EAQCkAgMAAAAgQJ8CAwGkAgYAABRAgFIDAACfAgICTQMBGwAAAABNBAHMBwAAAGoEAgOCAgIACAMBAwIDAwQAACBAAwQDBQQAFECAAwYABgcBGAAAAAAAAAAAAAAAAAEAAAABAAAAAAEHAAAAAAYAAAECABajAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAgCnBgAAAJ8BAgJNAgHWBwAAAP8DAAAAAAAA4gQJAMAFCgAwBQRaCAAAAJ8CAwCCAgAACwMIBAAAAEADCQMKAwsEAABAQAMMAw0DBwUBCAYAAQABAAEYAAEAAAAAAAEAAAAAAgAAAAABAAD/AAEAAAAAAdhqxbjgfH356q6vLIQxZcfbxzskNLRN3GzMzjv3LoYqoMk2BTTBDjU=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Rodux).createReducer({}, {
	["setStartedAt"] = function(p2, p3)
		local v4 = p3.clanId ~= nil
		assert(v4, "missing clanId")
		local v5 = table.clone(p2)
		v5[p3.clanId] = p3.value
		return v5
	end
})
