-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMKBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplCFRBR19OQU1FDlJFR0VOX0RVUkFUSU9OBVBsYW5rAAEFAAABAgAZowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAoQYAAABNAgMYBwAAAJ8BAgJNAgEACAAAAOIDCwBvBAwAMAQDtAkAAACMBAUAMAQDJAoAAACfAgIAggIAAA0DAQQAAABAAwIDAwMEBAAAQEADBQMGAwcDCAMJBQIJCgMKAAEAARgAAQAAAAAAAQAAAAAAAAEAAAEAAAEAAP4AAQAAAAAA4qGDGGyFtmDQZemMGmGCbmM9koUV7rOvBC2YAXrv40B2ZTZGQNgMeA==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Std.TableUtils).requireValidIndexAndFreeze({
	["TAG_NAME"] = "Plank",
	["REGEN_DURATION"] = 5
})
