-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMSBmlwYWlycwZzY3JpcHQGUGFyZW50Bk1vZHVsZQtHZXRDaGlsZHJlbgVDbGFzcwNuZXcETmFtZQdyZXF1aXJlBVN0YXJ0BXRhYmxlBmluc2VydARpbml0BGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQNTdGQGQmluZGVyAAILAAEAAAAo/wAAAAAAAACkAQEAAAAAQKQEAwAAACBATQMEJAQAAABNAgNABQAAALwCAmgGAAAAnwICAJ8BAARRARYATQYFJQcAAAD7CAAATQcI7wgAAABNCAW6CQAAAKQJCwAAAKBAUgoGAJ8JAgCfBwACvAgHHAwAAACfCAIBnjQABQcAAABSCQAAUgoHAKQIDwAAONCAnwgDAW4B6f8CAACAggABABADAQQAAABAAwIEAAAgQAMDAwQDBQMGAwcDCAMJBAAAoEADCgMLAwwEADjQgAAGDQEYAAABAAAAAAAAAAAAAAAAAQABAAAAAAAAAAAAAQAAAQAAAAAAAPwABgcAAAAABAAAAQIAFaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DAKEGAAAATQIDfwcAAACfAQIC/wIBAAAAAADAAwgAEgABADADAhMJAAAAggICAAoDDgQAAABAAw8DEAMJBAAAQEADEQMSBgADDQEAAQABGAABAAAAAAABAAAAAAAAAgABAAAACQEAAAAAAQdExiHeGHt3NYCstXYU8+XyqR5IMVRdrurUxpflDJUWKeXBL1WXzxQ=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.Binder)
return {
	["init"] = function()
		-- upvalues: (copy) v_u_2
		local v3 = {}
		for _, v4 in ipairs(script.Parent.Module:GetChildren()) do
			local v5 = v4.Class
			local v6 = v_u_2.new(v4.Name, require(v5))
			v6:Start()
			table.insert(v3, v6)
		end
	end
}
