-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgOlAQdfdXBkYXRlBG1haWQJSGVhcnRiZWF0B0Nvbm5lY3QUdXBkYXRlUG9zaXRpb25UaHJlYWQIX3ByZXNzZWQIX2NvbGxlY3QNcHJlc3NDYWxsYmFjawlfcmVsZWFzZWQPcmVsZWFzZUNhbGxiYWNrBG1hdGgEY2VpbAZpcGFpcnMFV2FsbHMORmluZEZpcnN0Q2hpbGQOR2V0RGVzY2VuZGFudHMFRGVjYWwDSXNBD3JieGFzc2V0aWQ6Ly8lZAZmb3JtYXQHVGV4dHVyZQASd2hpbGVQcmVzc2VkVXBkYXRlA29iajRCUklFRkNBU0VfUFJFU1NfRFVSQVRJT05fQUNDVU1VTEFUSU9OX0FUVFJJQlVURV9OQU1FDEdldEF0dHJpYnV0ZRZnZXRDdXJyZW50QWNjdW11bGF0aW9uCVBhcnRpY2xlcwREdXN0B0VuYWJsZWQGUGxhbmtzCm9uRmluaXNoZWQCb3MFY2xvY2sKRGlzY29ubmVjdAxUcmFuc3BhcmVuY3kMR2V0Q29sbGVjdGVkEm9uQ29sbGVjdGVkQ2hhbmdlZB9nZXRQbGF5ZXJJc0luQW1idWxhbmNlU3RyZXRjaGVyC0xvY2FsUGxheWVyBUNodXRlCUdldExhbmRlZAtQcmltYXJ5UGFydARQYXJ0CVZhbGlkUm9vdANBZGQIR2l2ZVRhc2sRQk9STl9BVF9BVFRSX05BTUUPb25MYW5kZWRDaGFuZ2VkB3VubW91bnQKU3VyZmFjZUd1aQ5aSW5kZXhCZWhhdmlvcgxSZXNldE9uU3Bhd24NUGl4ZWxzUGVyU3R1ZAdBZG9ybmVlBEZhY2UERW51bQdTaWJsaW5nCE5vcm1hbElkBUZyb250B0Rpc3BsYXkLcHJvYnNGb2xkZXIFbW91bnQJUGxheWVyR3VpDEJyaWVmY2FzZUd1aQNuZXcMc2V0bWV0YXRhYmxlEG9ic2VydmVBdHRyaWJ1dGUPZ2V0T3BlbkR1cmF0aW9uJk5vIG9wZW5pbmcgZHVyYXRpb24gZm9yIHRoaXMgYnJpZWZjYXNlBmFzc2VydAROYW1lBVRpbWVkCER1cmF0aW9uBERpc3QIQ2FsbGJhY2sPUmVsZWFzZUNhbGxiYWNrD0dldEFjY3VtdWxhdGlvbhJXaGlsZVByZXNzZWRVcGRhdGUKT3BlbiBDcmF0ZRlHZXRDb2xsZWN0ZWRDaGFuZ2VkU2lnbmFsFkdldExhbmRlZENoYW5nZWRTaWduYWwDYWxsDHdhaXRGb3JDaGlsZBJSYXJpdHlQcm9ic0Rpc3BsYXkqQlJJRUZDQVNFX1JBUklUWV9QUk9CQUJJTElUSUVTX0ZPTERFUl9OQU1FB2FuZFRoZW4LR2l2ZVByb21pc2UTQ09MTEVDVF9SRU1PVEVfTkFNRQpGaXJlU2VydmVyEVBSRVNTX1JFTU9URV9OQU1FE1JFTEVBU0VfUkVNT1RFX05BTUUJd29ya3NwYWNlEEdldFNlcnZlclRpbWVOb3cLR2V0RHVyYXRpb24LR2V0Q0ZyYW1lQXQGQ0ZyYW1lBFNpemUBWQdQaXZvdFRvCXNldE9yaWdpbglTZXRPcmlnaW4JZ2V0T3JpZ2luCUdldE9yaWdpbglzZXRUYXJnZXQJU2V0VGFyZ2V0CWdldFRhcmdldAlHZXRUYXJnZXQPc2V0VGFyZ2V0Tm9ybWFsD1NldFRhcmdldE5vcm1hbA9nZXRUYXJnZXROb3JtYWwPR2V0VGFyZ2V0Tm9ybWFsCHNldFNwZWVkCFNldFNwZWVkCGdldFNwZWVkCEdldFNwZWVkCXNldEJvcm5BdAlTZXRCb3JuQXQJZ2V0Qm9ybkF0CUdldEJvcm5BdAlzZXRMYW5kZWQJU2V0TGFuZGVkCWdldExhbmRlZBZnZXRMYW5kZWRDaGFuZ2VkU2lnbmFsDXNldExhbmRlZFRpbWUNU2V0TGFuZGVkVGltZQ1nZXRMYW5kZWRUaW1lDUdldExhbmRlZFRpbWUWc2V0UmFyaXR5UHJvYmFiaWxpdGllcxZTZXRSYXJpdHlQcm9iYWJpbGl0aWVzFmdldFJhcml0eVByb2JhYmlsaXRpZXMWR2V0UmFyaXR5UHJvYmFiaWxpdGllcwxnZXRDb2xsZWN0ZWQMc2V0Q29sbGVjdGVkDFNldENvbGxlY3RlZBlnZXRDb2xsZWN0ZWRDaGFuZ2VkU2lnbmFsEXNwZWVkIG11c3QgYmUgPiAwCU1hZ25pdHVkZQ1nZXRQb3NpdGlvbkF0DUdldFBvc2l0aW9uQXQLZ2V0Q0ZyYW1lQXQEZ2FtZQdQbGF5ZXJzCkdldFNlcnZpY2UKUnVuU2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQdyZXF1aXJlA1N0ZAdQcm9taXNlBUF1ZGlvCkJhc2VPYmplY3QGQmluZGVyBVJvYWN0DWNyZWF0ZUVsZW1lbnQPUnhJbnN0YW5jZVV0aWxzAlVJBk1vZHVsZQxDaXJjbGVBY3Rpb24HQWlyRHJvcA9CcmllZmNhc2VDb25zdHMOQnJpZWZjYXNlVXRpbHMQQnJpZWZjYXNlRGlzcGxheQxBaXJEcm9wVXRpbHMHX19pbmRleAhUQUdfTkFNRQArAwACAAAABvsAAAD7AgEAvAAAAwAAAACfAAMBggABAAEDAQAvAAEYAAAAAAABMAAAAAAGAgIAAAARKwABAIIAAQD7AwAATQIDFgAAAAD7BAEATQME/QEAAADZBQAAEgIAABIAAAC8AwPHAgAAAJ8DAwIwAwLSAwAAAIIAAQAEAwIDAwMEAwUBACsAARgAAQIAAAAAAAAAAAAAAAAAAywAAAAABgIBAAAADfsCAABSBAAAUgUBALwCAvQAAAAAnwIEAQ4BBQD7AgAAvAICYwEAAACfAgIAggIAAIIAAQACAwYDBwA1CAEYAAAAAAAAAQEAAAAAAjYAAAAABgIBAAAAB/sCAABSBAAAUgUBALwCAt0AAAAAnwIEAYIAAQABAwkAOwoBGAAAAAAAAAE8AAAAAAwBAgAABwAAAQMIHgIq+wIAABwBAgAJAwABuwcDAqQCAgAABACAnwICAqQDBAAAADBA+wQBAG8GBQC8BAQDBgAAAJ8EAwK8BARHBwAAAJ8EAgCfAwAEUQMUAG8KCAC8CAf+CQAAAJ8IAwIOCA8A+wkAAIcICQIOCAkAbwgKAPsLAACHCgsCvAgIjQsAAACfCAMCMAgHTwwAAABlAAMAbwgNADAIB08MAAAAbgPr/wIAAICCAAEADgMLAwwEAAQAgAMNBAAAMEADDgMPAxADEQMSAxMDFAMVAxYAPhcBGAAAAQAAAAABAAAAAAAAAAAAAAABAAAAAAEAAAEAAAAAAAAAAAIAAPsACT8AAAAABAACAAAACvsBAABNAAETAAAAAPsDAQBNAgNYAQAAALwAABICAAAAnwADAIIAAAADAxgDGQMaAEsbARgAAAAAAAAAAAAATAAAAAADAAEAAAAZ+wAAAG8CAAC8AAADAQAAAJ8AAwJvAgIAvAAAAwEAAACfAAMCqQEAADABAPADAAAA+wAAAG8CAAC8AAADAQAAAJ8AAwJvAgQAvAAAAwEAAACfAAMCqQEAADABAPADAAAAggABAAUDHAMPAx0DHgMfAGMgARgAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAABZAAAAAAGAAMAAAAwpAACAAAEAICfAAEC+wIAACYBAAJvAgMAYAIgAAEAAABvAQMA+wIBALwCAhoEAAAAnwICAcYCAADeAgEA+wICAG8EBQC8AgIDBgAAAJ8CAwJvBAcAvAICAwYAAACfAgMCqQMAADADAvAIAAAA+wICAG8EBQC8AgIDBgAAAJ8CAwJvBAkAvAICAwYAAACfAgMCqQMAADADAvAIAAAAPgIBA/sDAgBvBQUAvAMDAwYAAACfAwMCMAID2QoAAACCAAEACwMhAyIEAAQAgAKamZmZmZnZPwMjAxwDDwMdAx4DHwMkAGoAARgHAAABAAEAAAEBAAAAAQD0AAAAAAAAAAAAAAABAAAAAAAAAAAAAAAOAQAAAAAAAAFkAAAAAAYABAAAADT7AAAAvAAAtgAAAACfAAICDgAuAPsAAQCpAQAAMAEA8AEAAAD7AAIAbwICALwAAAMDAAAAnwADAm8CBAC8AAADAwAAAJ8AAwKpAQEAMAEA8AEAAAD7AAIAbwICALwAAAMDAAAAnwADAm8CBQC8AAADAwAAAJ8AAwKpAQEAMAEA8AEAAADZAAAAEgICAKQBCAAAHGCAnwEBAsYCAAD7BAMATQME/QkAAADZBQEAEgABABIBAv8SAgIAvAMDxwoAAACfAwMCUgIDAMECAACCAAEACwMlAx4DHAMPAx0DHwMhAyIEABxggAMDAwQCBgddJgEYAAAAAAABAAAAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAEAAACAQAAAAAAAAAAAAAADV4AAAAABAADAAAAEfsBAABNAAHwAAAAAPsCAQBNAQLrAQAAAPsDAgBNAgMxAgAAAJ8BAgJWAgEA8QAEAAIAAAD7AwAAMAID8AAAAACCAAEAAwMeAycDKACFAQABGAAAAAEAAAAAAAABAgABAAAChgAAAAAGAAQAAAAfpAACAAAEAICfAAEC+wIAACYBAAKMAgEAYAIIAAEAAACMAQEA+wIBALwCAhoDAAAAnwICAcYCAADeAgEAPgIBBPsDAgArAwYA+wMDAG8FBQC8AwMDBgAAAJ8DAwLeAwIA+wMCAA4DBAD7AwIAWwQCBzAEA9kIAAAAggABAAkDIQMiBAAEAIADIwIAAAAAAADwPwMpAw8CAAAAAAAA6D8DJACUAQABGAAAAAEAAQAAAQEAAAABAAICAAEAAAAAAAIAAQAAAAKWAAAAAAYACAAAAFn7AAAAvAAABQAAAACfAAICDgBTAPsBAABNAAEWAQAAAMYBAAAwAQDSAgAAAPsAAQD7AwAATQIDEwMAAABNAQKbBAAAADABAEQFAAAA+wABAPsCAABNAQITAwAAADABAEkGAAAA+wEAAE0AARYBAAAA+wMCAE0CA18HAAAA+wMBAPsFAABNBAUTAwAAAJ8CAwC8AAD9CAAAAJ8AAAH7AAAA+wIDAPsFBABNBAUoCQAAALwCAhIKAAAAnwIDALwAAAMLAAAAnwAAAfsBAABNAAEWAQAAAPsDBQBNAgP9DAAAANkEAAASAgEAEgIGABICBwC8AgLHDQAAAJ8CAwC8AAD9CAAAAJ8AAAH7AAMAbwIOALwAAAMPAAAAnwADAqQBEgAARACBnwEBAsYCAAD7BAUATQME/QwAAADZBQEAEgABABIBAv8SAQD/EgIDALwDA8cNAAAAnwMDAlICAwDBAAAAggABABMDKgMCAwUDGAMrAywDLQMuAy8DMAMaAwEDAwMEAykDDwMhAyIEAEQAgQIJCnsxARgAAAAAAAEAAAAAAAIAAAAAAAAAAQAAAAAAAQAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAALAAAAAAEAAAIBAAAAAAAAAAAAAAAAE3wAAAAAAgACAAAABvsBAABNAAESAAAAAPsBAQCfAAIBggABAAEDMgC9AQABGAAAAAAAAb4AAAAACgEFAAAANBMBAAATAgAB+wMAAG8EAADiBQYApAYJAAgEcMAwBgV7AQAAAKkGAAAwBgWkAgAAAIwGEAAwBgV/AwAAADABBRQEAAAApAYMAAsocMAwBgUFBQAAAOIGDgD7BwAA+wgBAOIJEAAwAgkpDwAAAJ8HAwIwBwY8DQAAAJ8DBAL7BQIATQQF5BEAAABSBQMA+wgDAE0HCDESAAAATQYHmRMAAABvBxQAnwQEAvsGBABNBQYWFQAAANkHAAASAgIAEgAEALwFBf0WAAAAnwUDAYIAAQAXAzMDNAM1AzYDNwM4BQUBAgMEBQM5AzoECARwwAM7AzwECyhwwAM9BQENAz4FAQ8DPwMoA0ADQQMCAy8BDK4BAAEYAAABAAABAAAAAQAAAQAAAQABAAAAAQEAAAEA/wAA+QwAAAAAAAAAAAAAAQAAAAAAAAAAA68AAAAAEwEOAAAAlgH7AgAATQEC7wAAAABSAgAAnwECAvsEAQCePQEEBAAAAFIDAQCkAgIAAAAQQJ8CAwFNAgEWAwAAAPsFAgBNBAWCBAAAAFIFAAD7BwMATQYHKAUAAADZBwAAEgABABICBACfBAQAvAIC/QYAAACfAgAB2QIBABIAAQDZAwIAEgABANkEAwASAgUAEgAAANkFBAASAAEAEgIDAPsHBgBNBgdbBwAAAE0HARMIAAAAnwYCAoEBBgUJAAAAUggGAG8JCQCkBwsAAACgQJ8HAwHiBxQAbwgVADAIB7oMAAAAqQgBADAIB3ENAAAAMAYH5Q4AAACMCAoAMAgH4w8AAAAwAgdGEAAAADADB6YRAAAAMAUHpBIAAAAwBAeoEwAAANkIBQASAAEAEgAHABIAAAASAgQAUgkIAJ8JAQFNCQEWAwAAALwLAQUWAAAAnwsCAlINCAC8CwvHFwAAAJ8LAwC8CQn9BgAAAJ8JAAHZCQYAEgABABIABwASAgcAEgAAABICAwASAgQAEgIIABICCQBSCgkAnwoBAU0KARYDAAAAvAwBBhgAAACfDAICUg4JALwMDMcXAAAAnwwDALwKCv0GAAAAnwoAAU0KARYDAAAA+w0KAE0MDb0ZAAAA/w0AAAIAAAD7DwIATQ4P8xoAAABSDwAAbxAbAJ8OAwL7EAIATQ8Q8xoAAABSEAAA+xIDAE0REmkcAAAAnw8DAMUNDgABAAAAnwwCAtkOBwASAgsAEgIMABICDQASAgkAEgABALwMDLUdAAAAnwwDALwKCukeAAAAnwoAAYIBAgAfA0IDQwQAABBAAwIDRAMwAy8DRQMYA0YDRwQAAKBAA0gDSQNKA0sDTANNA04DTwUIDA0ODxAREhMDUANRAwQDUgNTA1QDVQNWA1cDWAgBAgMEBQgLDSJCARgAAAAAAAEAAAAAAAAGAAEAAAAAAAAAAAAA/wAACwAGAAMAAA0AAAQAAAAAAAEAAAAAAAACAQAAAQAAAQABAAABAAEAAQABAAMAAAAAGwABAAAAAAAAAAAAAAACAAAAAAAAAAAtAAEAAAAAAAAAAAAAAAIAAAAAAAABAAAAAAABAAAAAAAAAAAA/gMAAAAAAAAAAP0AABcjAAAAAAUBAQAAAA1NAQATAAAAAPsEAABNAwTKAQAAALwBAQMCAAAAnwEDArwBAWsDAAAAnwECAakBAQCCAQIABAMYA1kDDwNaAMQBBwEYAAAAAAAAAAAAAAABAMUAAAAABwMBAAAADk0DABMAAAAA+wYAAE0FBtkBAAAAvAMDAwIAAACfAwMCUgUCALwDA2sDAAAAnwMDAakDAQCCAwIABAMYA1sDDwNaAMgBBgEYAAAAAAAAAAAAAAAAAQDJAAAAAAcDAQAAAA5NAwATAAAAAPsGAABNBQYrAQAAALwDAwMCAAAAnwMDAlIFAgC8AwNrAwAAAJ8DAwGpAwEAggMCAAQDGANcAw8DWgDMAQkBGAAAAAAAAAAAAAAAAAEAzQAAAAAQAgAAAAArpAIBAAAAAEC8AgK3AgAAAJ8CAgImAwIBvAQAyQMAAACfBAICYAQCAAMAAABSAwQATQYAEwQAAABNBQabBQAAACsFAQCCAAEAUgcDALwFAPMGAAAAnwUDAk0GABMEAAAApAkJAAAgcICMCgAATQ8AEwQAAABNDg+bBQAAAE0NDi8LAAAATQwNeAwAAABbCwwKjAwAAJ8JBAIJCAUJvAYGwg0AAACfBgMBggABAA4DXQQAAABAA14DXwMYAysDYANhA0IEACBwgAIAAAAAAADgPwNiA2MDZADQAQEBGAAAAAAAAQEAAAMAAQMAAAAAAQMAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAHSAAAAAAUCAQAAAAj7AwAATQID7wAAAABNAwATAQAAAFIEAQCfAgMAggIAAAIDZQMYAOMBZgEYAAAAAAAAAADkAAAAAAMBAQAAAAf7AgAATQEC+wAAAABNAgATAQAAAJ8BAgCCAQAAAgNnAxgA5gFoARgAAAAAAAAA5wAAAAAFAgEAAAAI+wMAAE0CA/cAAAAATQMAEwEAAABSBAEAnwIDAIICAAACA2kDGADpAWoBGAAAAAAAAAAA6gAAAAADAQEAAAAH+wIAAE0BAvsAAAAATQIAEwEAAACfAQIAggEAAAIDawMYAOwBbAEYAAAAAAAAAO0AAAAABQIBAAAACPsDAABNAgNxAAAAAE0DABMBAAAAUgQBAJ8CAwCCAgAAAgNtAxgA7wFuARgAAAAAAAAAAPAAAAAAAwEBAAAAB/sCAABNAQJtAAAAAE0CABMBAAAAnwECAIIBAAACA28DGADyAXABGAAAAAAAAADzAAAAAAUCAQAAAAj7AwAATQIDFQAAAABNAwATAQAAAFIEAQCfAgMAggIAAAIDcQMYAPUBcgEYAAAAAAAAAAD2AAAAAAMBAQAAAAf7AgAATQECYQAAAABNAgATAQAAAJ8BAgCCAQAAAgNzAxgA+AF0ARgAAAAAAAAA+QAAAAAFAgEAAAAI+wMAAE0CAy8AAAAATQMAEwEAAABSBAEAnwIDAIICAAACA3UDGAD7AXYBGAAAAAAAAAAA/AAAAAADAQEAAAAH+wIAAE0BAiMAAAAATQIAEwEAAACfAQIAggEAAAIDdwMYAP4BeAEYAAAAAAAAAP8AAAAABQIBAAAACPsDAABNAgMxAAAAAE0DABMBAAAAUgQBAJ8CAwCCAgAAAgN5AxgAgQJ6ARgAAAAAAAAAAAIBAAAAAwEBAAAAB/sCAABNAQIlAAAAAE0CABMBAAAAnwECAIIBAAACA3sDGACEAioBGAAAAAAAAAAFAQAAAAMBAQAAAAf7AgAATQEC5gAAAABNAgATAQAAAJ8BAgCCAQAAAgN8AxgAhwJSARgAAAAAAAAACAEAAAAFAgEAAAAI+wMAAE0CA5gAAAAATQMAEwEAAABSBAEAnwIDAIICAAACA30DGACKAn4BGAAAAAAAAAAACwEAAAADAQEAAAAH+wIAAE0BAowAAAAATQIAEwEAAACfAQIAggEAAAIDfwMYAI0CgAEBGAAAAAAAAAAOAQAAAAUCAQAAAAj7AwAATQIDtAAAAABNAwATAQAAAFIEAQCfAgMAggIAAAIDgQEDGACQAoIBARgAAAAAAAAAABEBAAAAAwEBAAAAB/sCAABNAQK4AAAAAE0CABMBAAAAnwECAIIBAAACA4MBAxgAkwKEAQEYAAAAAAAAABQBAAAAAwEBAAAAB/sCAABNAQLWAAAAAE0CABMBAAAAnwECAIIBAAACA4UBAxgAlgIlARgAAAAAAAAAFwEAAAAFAgEAAAAI+wMAAE0CA8IAAAAATQMAEwEAAABSBAEAnwIDAIICAAACA4YBAxgAmQKHAQEYAAAAAAAAAAAaAQAAAAMBAQAAAAf7AgAATQECJQAAAABNAgATAQAAAJ8BAgCCAQAAAgOIAQMYAJwCUQEYAAAAAAAAAB0BAAAABwEAAAAAGbwBABsAAAAAnwECArwCAJsBAAAAnwICArwDAEECAAAAnwMCAowGAAC3BgIAAwAAAKkFAAGpBQEAgQEFBAMAAABvBgMApAQFAAAAQECfBAMBJgQCAU0FBKoGAAAA7AYFA4IGAgAHA2gDbAN0A4kBA0cEAABAQAOKAQCfAl8BGAAAAAEAAAEAAAEAAAAAAAAAAAAAAQEAAQAgAQAAAAoCAQAAABa8AgAbAAAAAJ8CAgIrAgEAggABALwDAJsBAAAAnwMCAisDAQCCAAEAvAQAyQIAAACfBAIC+wYAAE0FBssDAAAAUgYBAFIHAgBSCAMAUgkEAJ8FBQCCBQAABANoA2wDXwOLAQCoAowBARgAAAABAQIAAAEBAgAAAQAAAAAAAAAAKQEAAAAMAgEAAAAcvAIAGwAAAACfAgICKwIBAIIAAQC8AwCbAQAAAJ8DAgIrAwEAggABALwEAE0CAAAAnwQCAisEAQCCAAEAvAUAyQMAAACfBQIC+wcAAE0GB9MEAAAAUgcBAFIIAgBSCQMAUgoEAFILBQCfBgYAggYAAAUDaANsA3ADXwONAQC0AmABGAAAAAEBAgAAAQECAAABAQIAAAEAAAAAAAAAAAA1AQAAABcAAAECAPsBowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBAQAAAABAbwMEALwBARYDAAAAnwEDAqQCAQAAAABAbwQFALwCAhYDAAAAnwIDAqQDBwAAAGBATQUCoQgAAABNBAVyCQAAAJ8DAgKkBAcAAABgQE0GAqEIAAAATQUG0goAAACfBAICpAUHAAAAYEBNBwKhCAAAAE0GB0sLAAAAnwUCAqQGBwAAAGBATQgCoQgAAABNBwh/DAAAAJ8GAgKkBwcAAABgQE0IAiENAAAAnwcCAk0IB8oOAAAApAkHAAAAYEBNCwKhCAAAAE0KC1IPAAAAnwkCAqQKBwAAAGBATQwCQBEAAABNCwxcEAAAAJ8KAgJNCwrdEgAAAKQMBwAAAGBATQ4CgxMAAABNDQ49FAAAAJ8MAgKkDQcAAABgQE0PAoMTAAAATQ4PDxUAAACfDQICpA4HAAAAYEBNEQKDEwAAAE0QEVwQAAAATQ8QQBYAAACfDgICpA8HAAAAYEBNEQKDEwAAAE0QEQQXAAAAnw8CAv8QAAAGAAAAbxEYAG8SGQBvExoAbxQbAG8VHABvFh0AxRARBwEAAAD/EQYAAAAAADAREW4eAAAAnj0RBQUAAABSExEAUhQFAKQSIAAAAPBBnxIDAcASIQASAAUAEgARABIACQASAAwAEgABABIAEAASAA0AEgALABIADwASAAAAEgADABIACAASAA4AEgAHADASEe8iAAAAwBIjABIADAAwEhFjJAAAAMASJQASAAwAMBIR9CYAAADAEicAEgAMADASEd0oAAAAwBIpADASEQMqAAAAwBIrABIADQAwEhEPLAAAAMASLQASAA0AMBIRGy4AAADAEi8AEgANADASEZcwAAAAwBIxABIADQAwEhGbMgAAAMASMwASAA0AMBIRUTQAAADAEjUAEgANADASEU02AAAAwBI3ABIADQAwEhF1OAAAAMASOQASAA0AMBIRQToAAADAEjsAEgANADASEc88AAAAwBI9ABIADQAwEhHDPgAAAMASPwASAA0AMBIREUAAAADAEkEAEgANADASEQVCAAAAwBJDABIADQAwEhEGRAAAAMASRQASAA0AMBIRuEYAAADAEkcAEgANADASEaxIAAAAwBJJABIADQAwEhFUSgAAAMASSwASAA0AMBIRWEwAAADAEk0AEgANADASEbZOAAAAwBJPABIADQAwEhGiUAAAAMASUQASAA0AMBIRBVIAAADAElMAMBIRyVQAAADAElUAEgANADASEetWAAAAwBJXABIADQAwEhHzWAAAAE0SBu8iAAAATRMMtFkAAABSFBEAnxIDAIISAABaA44BBAAAAEADjwEDkAEDkQEDkgEDkwEEAABgQAOUAQOVAQOWAQOXAQOYAQOZAQOaAQObAQOcAQOdAQOeAQOfAQOgAQOhAQOiAQOjAQIAAHCiPDUBQgIAAKiyPDUBQgIAAPjOPDUBQgIAAODWPDUBQgIAALjlPDUBQgIAAKjvPDUBQgOkAQNDBAAA8EEGDgNCBg8DBwYQAwYGEQMJBhIDAQYTA2YGFANoBhUDagYWA2wGFwNuBhgDcAYZA3IGGgN0BhsDdgYcA3gGHQN6Bh4DKgYfA1IGIAN+BiEDgAEGIgOCAQYjA4QBBiQDJQYlA4cBBiYDUQYnA18GKAOMAQYpA2ADpQEcDg8QERITFBUWFxgZGhscHR4fICEiIyQlJicoKQEAAQYAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAQACAAAAAAAAAQAA9AAAAAEAAgAAAAAAAAEAAAAAAAABAAAAAAAAAAABAAAAAAAAAgABAQEBAQEAAAMAAQABAAAAAAAAAgAAAAAAAOsAAAAAAAAAAACiAAAABAAAAAQAAAAEAAATAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAkAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAkAAAAMAAAAEQAAAAAAAAEAAAAMAAAAFQAAANwAAAAAKrkmYMv56JzTi+IKX9QcBLvYEwvsBJvZiYDOTbM9+66hsk0El3L8iyw=

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players")
local v_u_2 = game:GetService("RunService")
local v3 = game:GetService("ReplicatedStorage")
local v_u_4 = require(v3.Std.Promise)
require(v3.Std.Audio)
local v_u_5 = require(v3.Std.BaseObject)
local v6 = require(v3.Std.Binder)
local v_u_7 = require(v3.Roact)
local v_u_8 = v_u_7.createElement
local v_u_9 = require(v3.Std.RxInstanceUtils)
local v_u_10 = require(v3.Module.UI).CircleAction
local v_u_11 = require(v3.AirDrop.BriefcaseConsts)
local v_u_12 = require(v3.AirDrop.BriefcaseUtils)
local v_u_13 = require(v3.AirDrop.UI.BriefcaseDisplay)
local v_u_14 = require(v3.AirDrop.AirDropUtils)
local v_u_15 = {
	9238451278,
	9238451797,
	9238452703,
	9238452956,
	9238453431,
	9238453749
}
local v_u_16 = {}
v_u_16.__index = v_u_16
setmetatable(v_u_16, v_u_5)
function v_u_16.new(p_u_17)
	-- upvalues: (copy) v_u_5, (copy) v_u_16, (copy) v_u_9, (copy) v_u_11, (copy) v_u_2, (copy) v_u_15, (copy) v_u_12, (copy) v_u_10, (copy) v_u_14, (copy) v_u_1, (copy) v_u_4, (copy) v_u_8, (copy) v_u_13, (copy) v_u_7
	local v_u_18 = v_u_5.new(p_u_17)
	local v19 = v_u_16
	setmetatable(v_u_18, v19)
	v_u_18.maid:GiveTask(v_u_9.observeAttribute(p_u_17, v_u_11.BORN_AT_ATTR_NAME, function(p_u_20, _)
		-- upvalues: (copy) v_u_18, (ref) v_u_2
		if p_u_20 then
			v_u_18.maid.updatePositionThread = v_u_2.Heartbeat:Connect(function()
				-- upvalues: (ref) v_u_18, (copy) p_u_20
				v_u_18:_update(p_u_20)
			end)
		end
	end))
	local function v25(p21)
		-- upvalues: (ref) v_u_15, (copy) p_u_17
		local v22 = p21 * #v_u_15
		local v23 = math.ceil(v22)
		for _, v24 in ipairs(p_u_17:FindFirstChild("Walls"):GetDescendants()) do
			if v24:IsA("Decal") then
				if v_u_15[v23] then
					v24.Texture = ("rbxassetid://%d"):format(v_u_15[v23])
				else
					v24.Texture = ""
				end
			end
		end
	end
	local function v26()
		-- upvalues: (copy) v_u_18, (ref) v_u_11
		return v_u_18.obj:GetAttribute(v_u_11.BRIEFCASE_PRESS_DURATION_ACCUMULATION_ATTRIBUTE_NAME)
	end
	local v27 = v_u_12.getOpenDuration(v_u_18.obj)
	assert(v27, "No opening duration for this briefcase")
	local v_u_32 = {
		["Name"] = "Open Crate",
		["Timed"] = true,
		["Duration"] = v27,
		["Dist"] = 10,
		["Callback"] = function(p28, p29)
			-- upvalues: (copy) v_u_18
			v_u_18:_pressed(p28, p29)
			if p29 then
				return v_u_18:_collect()
			end
		end,
		["ReleaseCallback"] = function(p30, p31)
			-- upvalues: (copy) v_u_18
			v_u_18:_released(p30, p31)
		end,
		["GetAccumulation"] = v26,
		["WhilePressedUpdate"] = v25
	}
	local function v37()
		-- upvalues: (copy) v_u_18, (copy) v_u_32, (copy) p_u_17, (ref) v_u_2
		if v_u_18:GetCollected() then
			v_u_32.Enabled = false
			p_u_17:FindFirstChild("Particles"):FindFirstChild("Dust").Enabled = true
			p_u_17:FindFirstChild("Particles"):FindFirstChild("Planks").Enabled = true
			local v_u_33 = os.clock()
			local v_u_34 = nil
			v_u_34 = v_u_2.Heartbeat:Connect(function()
				-- upvalues: (copy) v_u_33, (ref) v_u_34, (ref) p_u_17
				local v35 = os.clock() - v_u_33
				if v35 > 0.4 then
					v35 = 0.4
					v_u_34:Disconnect()
					v_u_34 = nil
					p_u_17:FindFirstChild("Particles"):FindFirstChild("Dust").Enabled = false
					p_u_17:FindFirstChild("Particles"):FindFirstChild("Planks").Enabled = false
				end
				local v36 = v35 / 0.4
				p_u_17:FindFirstChild("Particles").Transparency = v36
			end)
		end
	end
	v37()
	v_u_18.maid:GiveTask(v_u_18:GetCollectedChangedSignal():Connect(v37))
	local function v45()
		-- upvalues: (copy) v_u_18, (copy) v_u_32, (ref) v_u_10, (copy) p_u_17, (ref) v_u_11, (ref) v_u_2, (ref) v_u_14, (ref) v_u_1
		if v_u_18:GetLanded() then
			v_u_18.maid.updatePositionThread = nil
			v_u_32.Part = v_u_18.obj.PrimaryPart
			v_u_32.ValidRoot = v_u_18.obj
			v_u_18.maid:GiveTask(v_u_10.Add(v_u_32, v_u_18.obj))
			v_u_18:_update(p_u_17:GetAttribute(v_u_11.BORN_AT_ATTR_NAME))
			v_u_18.maid:GiveTask(v_u_2.Heartbeat:Connect(function()
				-- upvalues: (ref) v_u_32, (ref) v_u_14, (ref) v_u_1
				local v38 = v_u_32.Enabled
				local v39 = not v_u_14.getPlayerIsInAmbulanceStretcher(v_u_1.LocalPlayer)
				if v38 ~= v39 then
					v_u_32.Enabled = v39
				end
			end))
			local v_u_40 = p_u_17:FindFirstChild("Chute")
			local v_u_41 = os.clock()
			local v_u_42 = nil
			v_u_42 = v_u_2.Heartbeat:Connect(function()
				-- upvalues: (copy) v_u_41, (ref) v_u_42, (ref) v_u_40, (ref) p_u_17
				local v43 = os.clock() - v_u_41
				if v43 > 1 then
					v43 = 1
					v_u_42:Disconnect()
					v_u_42 = nil
				end
				local v44 = v43 / 1
				if not v_u_40 then
					v_u_40 = p_u_17:FindFirstChild("Chute")
				end
				if v_u_40 then
					v_u_40.Transparency = v44 * 0.75
				end
			end)
		end
	end
	v45()
	v_u_18.maid:GiveTask(v_u_18:GetLandedChangedSignal():Connect(v45))
	v_u_18.maid:GivePromise(v_u_4.all({ v_u_9.waitForChild(p_u_17, "RarityProbsDisplay"), v_u_9.waitForChild(p_u_17, v_u_11.BRIEFCASE_RARITY_PROBABILITIES_FOLDER_NAME) }):andThen(function(p46)
		-- upvalues: (ref) v_u_8, (ref) v_u_13, (ref) v_u_7, (ref) v_u_1, (copy) v_u_18
		local v47 = p46[1]
		local v48 = p46[2]
		local v49 = v_u_8
		local v50 = {
			["ZIndexBehavior"] = Enum.ZIndexBehavior.Sibling,
			["ResetOnSpawn"] = false,
			["PixelsPerStud"] = 16,
			["Adornee"] = v47,
			["Face"] = Enum.NormalId.Front
		}
		local v51 = {
			["Display"] = v_u_8(v_u_13, {
				["probsFolder"] = v48
			})
		}
		local v52 = v49("SurfaceGui", v50, v51)
		local v_u_53 = v_u_7.mount(v52, v_u_1.LocalPlayer.PlayerGui, "BriefcaseGui")
		v_u_18.maid:GiveTask(function()
			-- upvalues: (ref) v_u_7, (copy) v_u_53
			v_u_7.unmount(v_u_53)
		end)
	end))
	return v_u_18
end
function v_u_16._collect(p54)
	-- upvalues: (copy) v_u_11
	p54.obj:FindFirstChild(v_u_11.COLLECT_REMOTE_NAME):FireServer()
	return true
end
function v_u_16._pressed(p55, _, p56)
	-- upvalues: (copy) v_u_11
	p55.obj:FindFirstChild(v_u_11.PRESS_REMOTE_NAME):FireServer(p56)
	return true
end
function v_u_16._released(p57, _, p58)
	-- upvalues: (copy) v_u_11
	p57.obj:FindFirstChild(v_u_11.RELEASE_REMOTE_NAME):FireServer(p58)
	return true
end
function v_u_16._update(p59, p60)
	local v61 = workspace:GetServerTimeNow() - p60
	local v62 = p59:GetDuration()
	if v62 < v61 then
		v61 = v62
	end
	if p59.obj.PrimaryPart then
		local v63 = p59:GetCFrameAt(v61)
		p59.obj:PivotTo(v63 * CFrame.new(0, p59.obj.PrimaryPart.Size.Y * 0.5, 0))
	end
end
function v_u_16.SetOrigin(p64, p65)
	-- upvalues: (copy) v_u_12
	return v_u_12.setOrigin(p64.obj, p65)
end
function v_u_16.GetOrigin(p66)
	-- upvalues: (copy) v_u_12
	return v_u_12.getOrigin(p66.obj)
end
function v_u_16.SetTarget(p67, p68)
	-- upvalues: (copy) v_u_12
	return v_u_12.setTarget(p67.obj, p68)
end
function v_u_16.GetTarget(p69)
	-- upvalues: (copy) v_u_12
	return v_u_12.getTarget(p69.obj)
end
function v_u_16.SetTargetNormal(p70, p71)
	-- upvalues: (copy) v_u_12
	return v_u_12.setTargetNormal(p70.obj, p71)
end
function v_u_16.GetTargetNormal(p72)
	-- upvalues: (copy) v_u_12
	return v_u_12.getTargetNormal(p72.obj)
end
function v_u_16.SetSpeed(p73, p74)
	-- upvalues: (copy) v_u_12
	return v_u_12.setSpeed(p73.obj, p74)
end
function v_u_16.GetSpeed(p75)
	-- upvalues: (copy) v_u_12
	return v_u_12.getSpeed(p75.obj)
end
function v_u_16.SetBornAt(p76, p77)
	-- upvalues: (copy) v_u_12
	return v_u_12.setBornAt(p76.obj, p77)
end
function v_u_16.GetBornAt(p78)
	-- upvalues: (copy) v_u_12
	return v_u_12.getBornAt(p78.obj)
end
function v_u_16.SetLanded(p79, p80)
	-- upvalues: (copy) v_u_12
	return v_u_12.setLanded(p79.obj, p80)
end
function v_u_16.GetLanded(p81)
	-- upvalues: (copy) v_u_12
	return v_u_12.getLanded(p81.obj)
end
function v_u_16.GetLandedChangedSignal(p82)
	-- upvalues: (copy) v_u_12
	return v_u_12.getLandedChangedSignal(p82.obj)
end
function v_u_16.SetLandedTime(p83, p84)
	-- upvalues: (copy) v_u_12
	return v_u_12.setLandedTime(p83.obj, p84)
end
function v_u_16.GetLandedTime(p85)
	-- upvalues: (copy) v_u_12
	return v_u_12.getLandedTime(p85.obj)
end
function v_u_16.SetRarityProbabilities(p86, p87)
	-- upvalues: (copy) v_u_12
	return v_u_12.setRarityProbabilities(p86.obj, p87)
end
function v_u_16.GetRarityProbabilities(p88)
	-- upvalues: (copy) v_u_12
	return v_u_12.getRarityProbabilities(p88.obj)
end
function v_u_16.GetCollected(p89)
	-- upvalues: (copy) v_u_12
	return v_u_12.getCollected(p89.obj)
end
function v_u_16.SetCollected(p90, p91)
	-- upvalues: (copy) v_u_12
	return v_u_12.setCollected(p90.obj, p91)
end
function v_u_16.GetCollectedChangedSignal(p92)
	-- upvalues: (copy) v_u_12
	return v_u_12.getCollectedChangedSignal(p92.obj)
end
function v_u_16.GetDuration(p93)
	local v94 = p93:GetOrigin()
	local v95 = p93:GetTarget()
	local v96 = p93:GetSpeed()
	local v97 = v96 > 0
	assert(v97, "speed must be > 0")
	return (v95 - v94).Magnitude / v96
end
function v_u_16.GetPositionAt(p98, p99)
	-- upvalues: (copy) v_u_12
	local v100 = p98:GetOrigin()
	if v100 then
		local v101 = p98:GetTarget()
		if v101 then
			local v102 = p98:GetDuration()
			return v_u_12.getPositionAt(p99, v100, v101, v102)
		end
	end
end
function v_u_16.GetCFrameAt(p103, p104)
	-- upvalues: (copy) v_u_12
	local v105 = p103:GetOrigin()
	if v105 then
		local v106 = p103:GetTarget()
		if v106 then
			local v107 = p103:GetTargetNormal()
			if v107 then
				local v108 = p103:GetDuration()
				return v_u_12.getCFrameAt(p104, v105, v106, v107, v108)
			end
		end
	else
		return
	end
end
return v6.new(v_u_11.TAG_NAME, v_u_16)
