-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgO5AQZpcGFpcnMLR2V0Q2hpbGRyZW4IQmFzZVBhcnQDSXNBB0dldE1hc3MBeAF5AXoEbWF0aANzaW4GQ0ZyYW1lA25ldwNjb3MNRnJvbUF4aXNBbmdsZQdyZXF1aXJlDVBsYXllclNjcmlwdHMMUGxheWVyTW9kdWxlDFdhaXRGb3JDaGlsZARJbml0EUdldEFyZVRpcmVzUG9wcGVkBU1vZGVsBlZpc3VhbA5GaW5kRmlyc3RDaGlsZARCb2R5BVNtb2tlB0VuYWJsZWQMc2V0bWV0YXRhYmxlBkNvbmZpZwRNZXRhBE1haWQEbWFpZAR0aWNrBkJvcm5BdAtXYXRlckhlaWdodAhTa2VsZXRvbgRCYXNlCFBhcnRCYXNlC1ZlY3RvckZvcmNlBUZvcmNlEEFsaWduT3JpZW50YXRpb24KU2V0dXBTZWF0cwVldmVyeQdDb25uZWN0CEdpdmVUYXNrDVNwcmluZ0ZvcndhcmQLU3ByaW5nQWNjZWwNU3ByaW5nSGVhZGluZwVTZXR1cAVTZWF0cwZhc3NlcnQEUGFydAZEcml2ZXIEU2VhdBVDYW1lcmFNYXhab29tRGlzdGFuY2UGUGxheWVyEE1vdW50TG9jYWxDYW1lcmEJSm9pbnROZWNrC0pvaW50TmVja0MwAkMwCkpvaW50V2Fpc3QMSm9pbnRXYWlzdEMwEnNldEh1bWFub2lkRW5hYmxlZAhIdW1hbm9pZARFbnVtEUh1bWFub2lkU3RhdGVUeXBlB1J1bm5pbmcLQ2hhbmdlU3RhdGUKRm9yY2VGcm9udAdWZWN0b3IzD0hlYXJ0YmVhdERyaXZlcgVMb2NhbAlDaGFyYWN0ZXIETmVjawRIZWFkBVdhaXN0ClVwcGVyVG9yc28GU2VhdGVkCEdldFBpdm90FlNldHVwTG9jYWxEcml2ZXJJbnB1dHMTU3ByaW5nV2Fpc3RSb3RhdGlvbhJTcHJpbmdOZWNrUm90YXRpb24JSGVhcnRiZWF0C01vdW50UGxheWVyCE9jY3VwaWVkC1VubW91bnRTZWF0BlVwZGF0ZRVVcGRhdGVDaGFyYWN0ZXJKb2ludHMEV0FTRAxUb3VjaEVuYWJsZWQLR2V0Q29udHJvbHMNR2V0TW92ZVZlY3RvcgFYBWNsYW1wA2FicwdGb3J3YXJkB0hlYWRpbmcJU2V0VGFyZ2V0DlNwcmluZ0ZvcndhcmRwDlNwcmluZ0hlYWRpbmdwDFNwcmluZ0FjY2VscAtVcGRhdGVJbnB1dAVlcnJvcg9UT0RPOiBJbXBsZW1lbnQQVXBkYXRlVGhpcmRJbnB1dAVub2lzZQVTd2F5WAVTd2F5WQ1DYWxjdWxhdGVTd2F5GVRJUkVTX1BPUFBFRF9BVF9BVFRSX05BTUUMR2V0QXR0cmlidXRlBE5hbWUWZ2V0VmVoaWNsZUNvbWJhdENvbmZpZw9EaXNhYmxlRHVyYXRpb24Jd29ya3NwYWNlEEdldFNlcnZlclRpbWVOb3cEU2l6ZQFZAVoNUmF5Y2FzdFBhcmFtcxpGaWx0ZXJEZXNjZW5kYW50c0luc3RhbmNlcwpjb2xsaWRhYmxlCFBvc2l0aW9uCE1hdGVyaWFsBVdhdGVyCFZlbG9jaXR5E1ZlY3RvclRvT2JqZWN0U3BhY2UMU3BlZWRGb3J3YXJkC0ZyaWN0aW9uRndkDEFzc2VtYmx5TWFzcwtSb3RWZWxvY2l0eRBNYXhpbXVtVHVybkFuZ2xlDlR1cm5DdXJ2ZUNvZWZmBHNxcnQKTG9va1ZlY3RvcgRVbml0BkFuZ2xlcwFwDVVwZGF0ZVBoeXNpY3MNVXNlcklucHV0VHlwZQhLZXlib2FyZAdLZXlDb2RlCklucHV0QmVnYW4KSW5wdXRFbmRlZAhHYW1lcGFkMQtUaHVtYnN0aWNrMQhCdXR0b25SMghCdXR0b25MMgxJbnB1dENoYW5nZWQJb25QcmVzc2VkCm9uUmVsZWFzZWQDYWRkB3ByaW1hcnkIcHJpb3JpdHkKc2F0dXJhdGVUbwVpbWFnZQhrZXlDb2RlcxdyYnhhc3NldGlkOi8vNzg1ODc2NTY2MwFXF3JieGFzc2V0aWQ6Ly83ODU4NzY0MzczAVMHRGVzdHJveQ1DdXJyZW50Q2FtZXJhBGdhbWUHUGxheWVycwpHZXRTZXJ2aWNlC0xvY2FsUGxheWVyClJ1blNlcnZpY2UQVXNlcklucHV0U2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQxBY3Rpb25CdXR0b24TQWN0aW9uQnV0dG9uU2VydmljZQRHYW1lBEJvYXQKQm9hdENvbnN0cw1DaGFyYWN0ZXJVdGlsA1N0ZAhJbnRlcnZhbAdSYXljYXN0BlNwcmluZwdWZWhpY2xlDFZlaGljbGVVdGlscwtfX0NsYXNzTmFtZQdfX2luZGV4AUEBRAAgCgEBAAAAGIwBAACkAgEAAAAAQLwDAGgCAAAAnwMCAJ8CAARRAg0AbwkDALwHBv4EAAAAnwcDAg4HBAC8BwbHBQAAAJ8HAgJDAQEH+wcAAFIIBgCfBwICQwEBB24C8v8CAACAggECAAYDAQQAAABAAwIDAwMEAwUAFAUBGAABAAAAAAAAAQAAAAABAAAAAgAAAPwABhUAAAAADwEBAAAAJk0BAJkAAAAATQIAmAEAAABNAwCbAgAAAAkHAQEJCAICQwYHCAkHAwNDBQYHBAQFA28FBABgBRYABAAAAFsHBAO7GAcCpAYHAAAYUICfBgIC7AUGBKQGCgAAJICAjAcAAIwIAACMCQAACQoFAQkLBQIJDAUDWw4EA7sJDgKkDQwAACxQgJ8NAgKfBggAggYAAPsFAACCBQIADQMGAwcDCAIAAAAAAADgPwLxaOOItfjkPgMJAwoEABhQgAMLAwwEACSAgAMNBAAsUIAAIA4BGAAAAAAAAAEAAAAAAAEAAAEAAAAAAAEAAAAAAAAAAAAAAAAAAAIAIQAAAAAEAAIAAAAMpAABAAAAAED7AgEATQECuAIAAABvAwMAvAEB0wQAAACfAQMAnwAAAt4AAACCAAEABQMPBAAAAEADEAMRAxIALhMBGAAAAAAAAAAAAAAAAS8AAAAABAACAAAAGvsAAAC8AADqAAAAAJ8AAgL7AQEA8QASAAEAAAD7AgAATQECOwEAAABvAwIAvAEBAwMAAACfAQMCbwMEALwBAQMDAAAAnwEDAm8DBQC8AQEDAwAAAJ8BAwIwAAHwBgAAAN4AAQCCAAEABwMUAxUDFgMXAxgDGQMaAEUAARgAAAAAAQAAAQAAAAAAAAAAAAAAAAAAAQACAUYAAAAACQIDAAAAU/8CBQAAAAAA+wUAAJ49AgQFAAAAUgQCAKQDAQAAAABAnwMDATAAAtkCAAAAMAECVAMAAAD7BAEATQME7wQAAACfAwECMAMCdgUAAABNAwJ2BQAAADADAhYGAAAApAMIAAAAcECfAwECMAMCdAkAAACMAwAAMAMCeQoAAABNAwE7CwAAADADAjsLAAAATQQCOwsAAABNAwRGDAAAADADAkYMAAAATQMCRgwAAABvBQ0AvAMDAw4AAACfAwMCMAMCGw8AAABNBAIbDwAAAE0DBBcQAAAAMAMCLREAAABNBAIbDwAAAE0DBKUSAAAAMAMCpRIAAAC8AwL3EwAAAJ8DAgGpAwAATQQCFgYAAAD7BwIATQYHxBQAAABvBxUAnwYCAtkIAAASAAIAEgED/7wGBscWAAAAnwYDALwEBP0XAAAAnwQAAcEDAACCAgIAGAMbBAAAAEADHAMdAwwDHgMfAyAEAABwQAMhAyIDFQMjAyQDFwMlAyYDJwMoAykDKgKamZmZmZm5PwMrAywBAzEMARgAAAEAAAAAAAABAAEAAQAAAAAAAQAAAAEAAAAAAQAAAwAAAAEAAAAAAAEAAAAAAAAAAgAAAAAAAQAAAAAAAgAAAQEAAAAAAAAAAAAAAAAAAAAJADIAAAAABgEBAAAAH/sCAABNAQLvAAAAAIwCAACMAwAAjAQBAIwFCgCfAQUCMAEAQwEAAAD7AgAATQEC7wAAAACMAgAAjAMAAIwEAQCMBQUAnwEFAjABAPECAAAA+wIAAE0BAu8AAAAAjAIAAIwDAACMBAEAjAUUAJ8BBQIwAQDOAwAAAIIAAQAEAwwDLQMuAy8AUDABGAAAAAAAAAAAAAABAAAAAAAAAAAAAQAAAAAAAAAAAAFRAAAAAAYBAAAAAB9NAwB0AAAAAEcDAgAAAAAAqQIAAakCAQC7AQICpAECAAAAEECfAQIB/wEAAAEAAADiAgUATQUAOwYAAABNBAWUBwAAALsBBAKkAwIAAAAQQJ8DAgIwAwJEAwAAAKkDAQAwAwK5BAAAAMUBAgIBAAAAMAEAdAAAAACCAAEACAMxAzIEAAAQQAMzAzQFAgMEAxUDNQBVKQEYAAAAAAAAAAAAAAEAAQEAAAAAAAAAAAABAAAAAP0ABlYAAAAAAgACAAAABfsAAAD7AQEAMAEApAAAAACCAAEAAQM2AGIAARgAAAAAAWMAAAAABwIAAAAAFU0CAfkAAAAAuwECA1IEAgCkAwIAAAAQQJ8DAgFNAwKkAwAAAE0EAXYEAAAA2QYAABIAAgASAAMAvAQE/QUAAACfBAMBjAR4ADAEAqQDAAAAggABAAYDNwMyBAAAEEADNgMeAywBB144ARgAAAEAAAAAAQABAAAAAAAAAAQAAAFfAAAAAAMAAQAAABH7AQAATQABigAAAAD7AgAATQEClQEAAAAwAQDtAgAAAPsBAABNAAGtAwAAAPsCAABNAQJDBAAAADABAO0CAAAAggABAAUDOQM6AzsDPAM9AHcAARgAAAAAAAAAAAEAAAAAAAAAAXgAAAAAAwACAAAAEfsBAABNAAEZAAAAAPsCAQBNAQIBAQAAAKkCAQCfAAMB+wEBAE0AAQEBAAAApAIFAAQMIMC8AAAhBgAAAJ8AAwGCAAEABwM+Az8DQANBA0IEBAwgwANDAH4AARgAAAAAAAAAAAEAAAAAAAAAAX8AAAAAAgABAAAAFfsBAABNAAGlAAAAAKkBAAAwAQDwAQAAAPsBAABNAAHeAgAAAEcACgAAAAAA+wEAAE0AAd4CAAAATDYAAqQBBQAAEDCAnwEBAjABAC0GAAAAggABAAcDKAMaA0QDRQMMBAAQMIADJwCLAQABGAAAAAAAAAEAAAAAAQAAAAAAAAAABYwAAAAAAwACAAAAC/sBAABNAAE7AAAAAEcABgAAAAAA+wAAAPsCAQC8AAAFAQAAAJ8AAwGCAAEAAgMVA0YAmAEAARgAAAAAAAEAAAAAApkAAAAACgMEAAAAtgFHAQIAAAAAgKkEAAGpBAEAuwEEAqQDAQAAAABAnwMCAUcCAgAAAACAqQQAAakEAQC7AQQCpAMBAAAAAECfAwIB+wQAAPEBAgAEAAAAqQMAAakDAQAwAwK7AgAAAE0EAWkDAAAAuwEEAqQDAQAAAABAnwMCAjADAmkDAAAATQQCaQMAAABvBgQAvAQEAwUAAACfBAMATAEAAqQDAQAAAABAnwMAAjADAgEEAAAATQUCaQMAAABNBAUTBwAAAE0DBOQGAAAAMAMCiggAAABNBgJpAwAAAE0FBlUKAAAATQQFQAkAAAAwBAKtCwAAAE0GAooIAAAATQUG7QwAAAAwBQKVDQAAAE0GAq0LAAAATQUG7QwAAAAwBQJDDgAAAE0FAnYPAAAA2QcAABIAAgC8BQX9EAAAAJ8FAwH7BgEATQUGGREAAABNBgIBBAAAAKkHAACfBQMBTQUCAQQAAACkBxUAFEwgwbwFBSEWAAAAnwUDAU0FAnYPAAAA2QcBABICAQASAAIAvAUF/RAAAACfBQMBTQUCuRcAAAAOBU4ATQUApRgAAACpBgEAMAYF8BkAAABNBQClGAAAAE0GADsaAAAAvAYGUhsAAACfBgICMAYFhRwAAABNBQK7AgAAAA4FCABSBwIAvAUAgB0AAACfBQMBUgcCALwFAJkeAAAAnwUDAU0FAnYPAAAA2QcCABIAAAC8BQX9EAAAAJ8FAwH7BgIATQUG7x8AAABMNgACpAYhAAB8AIKfBgECTDYAAqQHIQAAfACCnwcBAm8IIgCMCRQAnwUFAjAFAhIjAAAA+wYCAE0FBu8fAAAATDYAAqQGIQAAfACCnwYBAkw2AAKkByEAAHwAgp8HAQJvCCIAjAkUAJ8FBQIwBQKDJAAAAE0FAnYPAAAA+wgDAE0HCP0lAAAA2QkDABIAAAASAAIAvAcHxyYAAACfBwMAvAUF/RAAAACfBQABggABACcDMgQAAABAA0cDSAM/AxcDSQNKAzkDSwNMAzwDOwM6Az0DHgMsAz4DQANBA00EFEwgwQNDAzQDKAMaAxUDTgMLAzgDTwMMA0UEAHwAggLNzMzMzMzsPwNQA1EDUgMrBAkKCwxoUwEYAAAAAAAAAAABAAAAAAAAAAEAAAAAAAACAAAAAAAAAAEAAAAAAAAAAAAAAAIAAAAAAAEAAQAAAAAAAQACAAAAAAABAAAAAAABAAAAAAAABQAAAAAAAAEAAAAAAAABAAAAAAAAAAUAAAEAAAAAAQAAAAAAAAAAAQAAAQAAAAEAAAADAAAAAAAACgAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAZpAAAAAAUCAAAAABZHAQIAAAAAgKkDAAGpAwEAuwEDAqQCAQAAAABAnwICAU0EAZYCAAAAKgQCAAEAAACpAwABqQMBALsBAwKkAgEAAAAAQJ8CAgHGAgAAMAIBuwMAAACCAAEABAMyBAAAAEADVANHAJ8BVQEYAAAAAAAAAAABAAAAAAAAAAAAAQAAAaAAAAAACQIBAAAAH00CARIAAAAAvAICJgEAAACfAgICTQMBrQIAAABNBQFDAwAAAPsGAABSBwIAnwYCAgkEBQYwBAPtBAAAAE0DAYMFAAAAvAMDJgEAAACfAwICTQQBigYAAABNBgGVBwAAAPsHAABSCAMAnwcCAgkFBgcwBQTtBAAAAIIAAQAIA1ADVgM8Az0DOwNRAzkDOgCkAVcBGAAAAAAAAQAAAAAAAAAAAAIAAAAAAQAAAAAAAAAAAAGlAAAAAAgBAgAAAEZNAwCOAAAAABMCAwBNBACOAAAAABMDBAImAQIDTQQAjgAAAAATAwQBTQUAjgAAAAATBAUDJgIDBPsEAABNAwR/AQAAAA4DFgD7AwEAvAMDfQIAAACfAwICvAMD/QMAAACfAwICTQUDeQQAAACMBv//jAcBAEwuAAKkBAcAABhQgJ8EBAI5BQQAuwIEA1IHBACkBgkAACBQgJ8GAgIJAgUGMAEA/QoAAAAwAgAxCwAAAE0DAEMMAAAAUgUBALwDA5cNAAAAnwMDAjADADQOAAAATQMAzg8AAABSBQIAvAMDlw0AAACfAwMCMAMAZBAAAABNAwDxEQAAAE0FAP0KAAAAvAMDlw0AAACfAwMCMAMAPhIAAACCAAEAEwNYA1kDWgNbA1wDCQNdBAAYUIADXgQAIFCAA18DYAMtA2EDYgMvA2MDLgNkALMBZQEYAAAAAAAAAAEAAAAAAAACAAAAAQAAAAAAAAEAAAAAAAAAAQAAAAAAAAIAAQACAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAAAAbQAAAAAAwEAAAAABaQBAQAAAABAbwICAJ8BAgGCAAEAAwNmBAAAAEADZwDEAWgBGAAAAAABxQAAAAAMAQAAAABApAIBAAAAAECfAgECTQMAdAIAAAAmAQIDbwMDAE0EAHQCAAAAQwIDBG8EBABNBQB0AgAAAEMDBAVbCQEGQwgJArsJCAKkBwkAACBwgJ8HAgJbBgcFbwkKAE0LADQMAAAA9QoLCwkICQqVBwgKCQUGB6QHDwAAOHCAUggBAFIJAgCfBwMCWwYHDUMEBQZNBgA0DAAAALsCBgKkBREAAEBwgJ8FAgL1BwsFCQYEBzAGAEsSAAAAWwoBFEMJCgO7GAkCpAgWAABUcICfCAICWwcIE6QJDwAAOHCAUgoBAFILAwCfCQMCWwgJBUMGBwj1CAsFCQcGCDAHAJIXAAAAggABABgDIAQAAABAAyECybCKN1i+/sACcY+lD3UE6cACmpmZmZmZuT8CmpmZmZmZ8T8DCQMNBAAgcIACAAAAAAAA4D8CAAAAAAAA8D8DYgKamZmZmZmpPwNpBAA4cIADXgQAQHCAA2oCmpmZmZmZ2T8CmpmZmZmZ6T8DCgQAVHCAA2sAxwFsARgAAAAAAAACAAAAAQAAAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAIAAAAAAAIAAAABAAAAAAAAAAAAAAAAAAEAAAAByAAAAAAIAQIAAAAfTQIAOwEAAAD7BQAATQQF+AIAAAC8AgISAwAAAJ8CAwKQAQIATQMAOwEAAABNAgO6BAAAAPsEAQBNAwTcBQAAAFIEAgCfAwICTQYDTwYAAABDBQEGpAYIAAAAcEC8Bga3CQAAAJ8GAgK3BgIABQAAAKkEAAGpBAEAggQCAAoCAAAAAAAAAAADFQNtA24DbwNwA3EDcgQAAHBAA3MA1QEUARgAAAAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAB1gAAAAAlAQEAABUAAAQIBR0BCActAQgPmgEBCCCKAgKqArwBAOoAAAAAnwECAk0CAHkBAAAATQUAGwIAAABNBAWFAwAAAIwGAABNCwAbAgAAAE0KCy8FAAAATQkKeAYAAAA5CAkAWwcIBE0LABsCAAAATQoLLwUAAABNCQp7BwAAAFsICQRMNgACpAUKAAAkgICfBQQCCQMEBaQEDAAAJLCAnwQBAv8FAAABAAAATQYAOw0AAADFBQYCAQAAADAFBH0OAAAA+wYAAE0FBpoPAAAAbwcQAEMGAwdvBxEAjAhkAFIJBACfBQUCxgYAAMYHAAAOBQQATQYFOxIAAABNBwUtEwAAAKQIFgAVTEDBmgcLAAgAAABNAgZ4BgAAADACAHkBAAAATQgApRcAAACpCQEAMAkI8BgAAABlAAUATQgApRcAAACpCQAAMAkI8BgAAABNCQN4BgAAANQJAgACAAAAqQgAAakIAQBNCgAbAgAAAE0JCoUDAAAATQ0AGwIAAABNDA2FGQAAALwKCewaAAAAnwoDAk0MAD4bAAAAjA0AAGANBgAMAAAATQwA2RwAAABNCwzMHQAAAGUABQBNDQDZHAAAAE0MDcwdAAAAWwsMBIwNAACMDgAATREAPhsAAAA5EBEACQ8QC0w2AAKkDAoAACSAgJ8MBAIOAQEAWwwMHisIAQBbDAwfTQ8A2RwAAABNDg+KIAAAAJANDh5NEgp5IgAAAFsREiGMEgAATRUKewcAAAAJFBUNTRcKewcAAABNGQp7BwAAALsCGQKkGCYAAJRAgp8YAgIJFhcYWxUWI0MTFBVMNgACpBAKAAAkgICfEAQCOQ8QAE0RABsCAAAATRARlScAAAAJDg8QTQ8ALSgAAABNFAAbAgAAAE0TFJUnAAAACRIME1sREilDEBEOMBAPLSgAAABNEgAbAgAAAE0REqoqAAAAvA8J7BoAAACfDwMCTRMPeAYAAAA5EhMAPhESBIwS//+MEwEATC4AAqQQLAAArECCnxAEAk0WCpsvAAAAORUWAD4UFS6MFf//jBYBAEwuAAKkEywAAKxAgp8TBAJbEhMtTRQAPhsAAABbExQwQxESE00SAJIxAAAAQxAQEk0SAEsyAAAAQxEREk0UAGQ0AAAAWxMUM00VANkcAAAATRQVVTUAAAAJEhMUTRUA2RwAAABNFBUaNwAAAJATFDZNFQp7BwAAADkUFQC7AhQDUhkUAKQYJgAAlECCnxgCAngXGDk+Fhc4jBcAAIwYAQBMLgACpBUsAACsQIKfFQQCuxkVA1IaFQCkGTsAAOhAgp8ZAgIJGBMZ9Rc2GG8YHgCMGQEATC4AAqQWLAAArECCnxYEAgkYFhJbFxgfTRgApRcAAACkHTwAACQwgG8ePQBNIgloPgAAAE0hInkiAAAAjCIAAE0kCWg+AAAATSMkewcAAABMNgACpCAKAAAkgICfIAQCTR8gBz8AAACfHQMCpB5BAAAAMYCMHwAAjCAAAFsiEDNbISJCnx4EAgkcHR6kHUEAAAAxgFsfETNbHh9DjB8AAIwgAACfHQQCCRscHaQcQQAAADGAjB0AAFIeFwCMHwAAnxwEAgkaGxxNGwmRRAAAAEMZGhswGRiFAwAAAIIAAQBFAxQDIgMlAwsCAAAAAAAA4D8DdAN1A3YDRQMMBAAkgIADdwQAJLCAAxUDeAN5BwAAAAAAAEhCAAAAAAAAAAAHAAAAgAAAgL8AAACAAAAAgAN6A3sDQAN8BBVMQMEDKAMaA30DfgNkAxwDfwKamZmZmZmpPwIAAAAAAADQPwOAAQIAAAAAAAAIQANcAvyp8dJNYlA/AwkDXgQAlECCA4EBAycCAAAAAAAAJEADggEDXQQArECCApqZmZmZmek/AgAAAAAAAFRAAwgCmpmZmZmZyT8DawNqAhgtRFT7IQlAA2MDgwECAAAAAAAA8D8DhAECAAAAAAAAiUACAAAAAAAAWUADhQEEAOhAggQAJDCABwAAAAAAAAAAAAAAAAAAAAADhgEDhwEDiAEEAAAxgAK4HoXrUbiePwJ7FK5H4XqUPwOJAQDcAYoBARgAAAACAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAABAAAAAAAAAAEAAAAAAAAAAAEAAQEAAQACAAAAAQABAAIAAAAAAAMAAAAAAgAAAAAABAAAAAEAAAAAAAACAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAQECAgMAAAAABQAAAQEAAAAAAAAAAAAAAAAA/QAAAAAEAAAAAAEAAAAAAAAAAAAAAgAAAAAAAAEAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAADAAABAAACAAAAAAAAAAEAAAAAAgAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAADAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAQAA/AAI3QAAAAAFAgAAAAAhRwECAAAAAICpAwABqQMBALsBAwKkAgEAAAAAQJ8CAgFNAgA7AgAAAEcCFQAAAAAATQIBuwMAAAAOAgoAvAIAcAQAAACfAgIBvAIAKQUAAACfAgIBvAIADwYAAACfAgIBZQADALwCAFgHAAAAnwICAVIEAQC8AgAbCAAAAJ8CAwGCAAEACQMyBAAAAEADFQNHA2UDbAOKAQNoA1cAqQJGARgAAAAAAAAAAAEAAAABAAABAAABAAABAAAAAgAAAgAAAAIqAQAAAAYCAgAAABgOAQIAqQIBAIICAgBNAgDCAAAAAKQDAwACABDAmgIPAAMAAAD7AwAATQQAswQAAACHAgMEDgIJAPsDAQBNAgOOBQAAAPsEAABNBQCzBAAAAIcDBAWMBAEAagQCA4IAAQAGA4sBA0ADjAEEAgAQwAONAQNYALgCjgEBGAABAAIAAAAAAAEAAAAAAQAAAAAAAAAAAzkBAAAABgICAAAAGA4BAgCpAgEAggICAE0CAMIAAAAApAMDAAIAEMCaAg8AAwAAAPsDAABNBACzBAAAAIcCAwQOAgkA+wMBAE0CA44FAAAA+wQAAE0FALMEAAAAhwMEBYwEAABqBAIDggABAAYDiwEDQAOMAQQCABDAA40BA1gAwwKPAQEYAAEAAgAAAAAAAQAAAAABAAAAAAAAAAADRAEAAAAIAQIAAABBTQEAwgAAAACkAgMAAgAQwJoBOwACAAAATQEAswQAAACkAgYABRAQwJoBHQACAAAATQIAOwcAAABNAwJ5CAAAAE0EAngJAAAA+wYAAE0FBo4KAAAAbwcLAGADBAAHAAAAOQcDAAQGBwwrBgEAjAYAAPYGBQH7BgAATQUGjgoAAABvBw0AYAcDAAMAAAAEBgMMKwYBAIwGAAD2BgUDggABAKQCDwAOEBDA8QEFAAIAAACkAhEAEBAQwJoBEQACAAAATQIAOwcAAABNAwJ7EgAAAPsFAABNBAWOCgAAAPsGAQCHBQYBbwcTAGAHAwADAAAABAYDFCsGAQCMBgAAagYEBYIAAQAVA4sBA0ADkAEEAgAQwAONAQORAQQFEBDAA3oDXAN1A1gCuB6F61G4zr8CAAAAAAAAAEACuB6F61G4zj8DkgEEDhAQwAOTAQQQEBDAA3YCmpmZmZmZqT8CAAAAAAAA4D8AzgKUAQEYAAAAAAAAAQABAAAAAQABAAAAAgAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAQABAAIAAAAAAAAAAAAAAANPAQAAAAIAAQAAAAb7AQAATQABjgAAAACMAQEA9gEAAIIAAQABA1gA5wKVAQEYAAAAAAABaAEAAAACAAEAAAAG+wEAAE0AAY4AAAAAjAEAAPYBAACCAAEAAQNYAOoClgEBGAAAAAAAAWsBAAAAAgABAAAABvsBAABNAAGOAAAAAIwBAQD2AQACggABAAEDWAD0ApUBARgAAAAAAAF1AQAAAAIAAQAAAAb7AQAATQABjgAAAACMAQAA9gEAAoIAAQABA1gA9wKWAQEYAAAAAAABeAEAAAALAgMAAACHAf8CAAAEAAAAjAMAAIwEAACMBQAAjAYAAMUCAwUBAAAAMAIAjgAAAADZAgAAEgIAABIAAABNAwF2AQAAAPsGAQBNBQaCAgAAAFIHAgC8BQXHAwAAAJ8FAwC8AwP9BAAAAJ8DAAHZAwEAEgIAABIAAABNBAF2AQAAAPsHAQBNBgevBQAAAFIIAwC8BgbHAwAAAJ8GAwC8BAT9BAAAAJ8EAAHZBAIAEgAAABICAABNBQF2AQAAAPsIAQBNBwjZBgAAAFIJBAC8BwfHAwAAAJ8HAwC8BQX9BAAAAJ8FAAFNBQF2AQAAAPsIAgBNBwi/BwAAAOIIDwCpCQEAMAkINQgAAACMCegDMAkI7QkAAACMCQAAMAkIEwoAAABvCRAAMAkIyQsAAAD/CQAAAQAAAKQKFAATSBDBxQkKAgEAAAAwCQgWDAAAANkJAwASAAAAMAkIVA0AAADZCQQAEgAAADAJCF4OAAAAnwcCALwFBf0EAAAAnwUAAU0FAXYBAAAA+wgCAE0HCL8HAAAA4ggPAKkJAQAwCQg1CAAAAIwJvAIwCQjtCQAAAIwJAAAwCQgTCgAAAG8JFQAwCQjJCwAAAP8JAAABAAAApAoXABZIEMHFCQoCAQAAADAJCBYMAAAA2QkFABIAAAAwCQhUDQAAANkJBgASAAAAMAkIXg4AAACfBwIAvAUF/QQAAACfBQABvAUAcBgAAACfBQIBggABABkDWAMeA44BAysDLAOPAQOUAQOXAQOYAQOZAQOaAQObAQOcAQOVAQOWAQUHCAkKCwwNDgOdAQNAA40BA54BBBNIEMEDnwEDoAEEFkgQwQNlBxYXGBkaGxy2Ak8BGAAAAAAAAAAAAAABAAAKAAAAAAAAAAAAAAABAAAKAAAAAAAAAAAAAAABAAARAAAAAAAAAAAAAAACAAAAAAABAAABAAABAAABAAABAAAAAAAAAAEAAAADAAAA9wAAAA0AAAAAAAEAAAEAAAEAAAEAAAEAAAAAAAAAAQAAAAMAAAD3AAAADwAAATcBAAAAAwEAAAAABk0BAHYAAAAAvAEBUAEAAACfAQIBggABAAIDHgOhAQD/AqEBARgAAAAAAAGAAQAAABcAAAECAMMBowAAAKQBAQAAAABATQABSAIAAACkAQQAAAAwQG8DBQC8AQEWBgAAAJ8BAwJNAgExBwAAAKQDBAAAADBAbwUIALwDAxYGAAAAnwMDAqQEBAAAADBAbwYJALwEBBYGAAAAnwQDAqQFBAAAADBAbwcKALwFBRYGAAAAnwUDAqQGDAAAALBATQgFlA0AAABNBwhiDgAAAJ8GAgKkBwwAAACwQE0KBb0PAAAATQkKOxAAAABNCAmfEQAAAJ8HAgKkCAwAAACwQE0KBb0PAAAATQkKwxIAAACfCAICpAkMAAAAsEBNCwWhEwAAAE0KC6wUAAAAnwkCAqQKDAAAALBATQwFoRMAAABNCwx2FQAAAJ8KAgKkCwwAAACwQE0NBaETAAAATQwNwhYAAACfCwICpAwMAAAAsEBNDgWhEwAAAE0NDiIXAAAAnwwCAqQNDAAAALBATQ8FjRgAAABNDg9tGQAAAJ8NAgLGDgAATDYAAqQPHAAAbKCBnw8BAsAQHQASABAApBEfAABs4IGfEQECwBIgABIAEQD/EwYAAAAAAG8UEAAwFBPlIQAAADATE24iAAAA2RQCABIBDv8SAAIAMBQTcyMAAADAFCQAEgATABIACgASAAkAMBQT7xsAAADAFCUAEgAMADAUE5kmAAAAwBQnADAUE/coAAAAwBQpADAUE4AqAAAAwBQrABIAAgASAAgAEgAMABIAAwAwFBMYLAAAAMAULQAwFBMzLgAAAMAULwASABIAMBQTGzAAAAD/FAMAAAAAAKQVNAAzyBDDjBYCAGoWFBWkFTYANcgQw4wWBABqFhQVpBU4ADfIEMOMFgEAahYUFaQVOgA5yBDDjBYDAGoWFBXZFQoAEgAEABIBDv8wFRNwOwAAAMAVPAAwFRNYPQAAAMAVPgAwFRMpPwAAAMAVQAASAAcAEgANADAVE+pBAAAAwBVCABIACwAwFRMPQwAAAMAVRAAwFRMFRQAAAMAVRgASABQAEgAEABIABgAwFROZRwAAAMAVSAAwFRNQSQAAAMEOAACCEwIASgNyBAAAAEADogEDowEEAAAwQAOkAQOlAQOmAQOnAQOoAQOpAQMPBAAAsEADqgEDqwEDrAEDrQEDrgEDrwEDsAEDsQEDHgOyAQOzAQO0AQO1AQNFAwwEAGyggQYAAwsEAGzggQYBA7YBA7cBAxMGBAYFAzAGBgMpBggDOAYNA1MGDgNVBg8DVwNAA40BA7gBBDPIEMMDuQEENcgQwwOSAQQ3yBDDA5MBBDnIEMMDZQYRA2gGEgNsBhMDFAYUA4oBBhUDRgYdA08GHgOhARIAAQIEBQYIDQ4PEBESExQVHR4BAAEFAAEAAAABAAAAAAABAAEAAAAAAAEAAAAAAAEAAAAAAAH5AAAAAAABAAAAAAAAAAABAAAAAAAAAQAAAAAAAAEAAPwAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAgAAAAIA+AAAAQALAAEAAAEAAQAAAAADAAAAAAAfAAAABQAACQDBCgAAAAAAADcAAAUAAAAHAAIAAAACAAAAAQAAAAEAAK0CAAAAABEAAAMAAA4AAAAABwAAAE0AAA0AAAAAAEkAMgMAAQAAAAcAAAAEAAAAEwAAAD8AAABTAAAAzgAAAAAfqlpNhBHOSR+YnicQajspV/ME2UcQR8BkbhMt+n2H9UYCnJMjHRIc4A==

-- Decompiled by Krnl

local _ = workspace.CurrentCamera
local v_u_1 = game:GetService("Players").LocalPlayer
local v_u_2 = game:GetService("RunService")
local v_u_3 = game:GetService("UserInputService")
local v4 = game:GetService("ReplicatedStorage")
local v_u_5 = require(v4.ActionButton.ActionButtonService)
local v_u_6 = require(v4.Game.Boat.BoatConsts)
local v_u_7 = require(v4.Game.CharacterUtil)
local v_u_8 = require(v4.Std.Interval)
local v_u_9 = require(v4.Std.Maid)
local v_u_10 = require(v4.Std.Raycast)
local v_u_11 = require(v4.Std.Spring)
local v_u_12 = require(v4.Vehicle.VehicleUtils)
local v_u_13 = nil
Vector3.new()
local function v_u_17(p14)
	-- upvalues: (copy) v_u_17
	local v15 = 0
	for _, v16 in ipairs(p14:GetChildren()) do
		if v16:IsA("BasePart") then
			v15 = v15 + v16:GetMass()
		end
		v15 = v15 + v_u_17(v16)
	end
	return v15
end
local v_u_18 = CFrame.new()
local function v_u_31(p19)
	-- upvalues: (copy) v_u_18
	local v20 = p19.x
	local v21 = p19.y
	local v22 = p19.z
	local v23 = (v20 * v20 + v21 * v21 + v22 * v22) ^ 0.5
	if v23 <= 0.00001 then
		return v_u_18
	end
	local v24 = v23 * 0.5
	local v25 = math.sin(v24) / v23
	local v26 = CFrame.new
	local v27 = v25 * v20
	local v28 = v25 * v21
	local v29 = v25 * v22
	local v30 = v23 * 0.5
	return v26(0, 0, 0, v27, v28, v29, (math.cos(v30)))
end
local v_u_32 = {
	["__ClassName"] = "Boat"
}
v_u_32.__index = v_u_32
function v_u_32.Init()
	-- upvalues: (ref) v_u_13, (copy) v_u_1
	v_u_13 = require(v_u_1.PlayerScripts:WaitForChild("PlayerModule"))
end
function v_u_32.new(p33, p34)
	-- upvalues: (copy) v_u_32, (copy) v_u_9, (copy) v_u_8
	local v_u_35 = {}
	local v36 = v_u_32
	setmetatable(v_u_35, v36)
	v_u_35.Config = p33
	v_u_35.Meta = p34
	v_u_35.Maid = v_u_9.new()
	v_u_35.maid = v_u_35.Maid
	v_u_35.BornAt = tick()
	v_u_35.WaterHeight = 0
	v_u_35.Model = p34.Model
	v_u_35.Skeleton = v_u_35.Model.Skeleton
	v_u_35.PartBase = v_u_35.Skeleton:FindFirstChild("Base")
	v_u_35.Force = v_u_35.PartBase.VectorForce
	v_u_35.AlignOrientation = v_u_35.PartBase.AlignOrientation
	v_u_35:SetupSeats()
	local v_u_37 = false
	v_u_35.maid:GiveTask(v_u_8.every(0.1):Connect(function()
		-- upvalues: (copy) v_u_35, (ref) v_u_37
		local v38 = v_u_35:GetAreTiresPopped()
		if v38 ~= v_u_37 then
			v_u_35.Model:FindFirstChild("Visual"):FindFirstChild("Body"):FindFirstChild("Smoke").Enabled = v38
		end
		v_u_37 = v38
	end))
	return v_u_35
end
function v_u_32.Setup(p39)
	-- upvalues: (copy) v_u_11
	p39.SpringForward = v_u_11.new(0, 0, 1, 10)
	p39.SpringAccel = v_u_11.new(0, 0, 1, 5)
	p39.SpringHeading = v_u_11.new(0, 0, 1, 20)
end
function v_u_32.SetupSeats(p40)
	local v41 = p40.Seats == nil
	assert(v41)
	local v42 = {}
	local v43 = {}
	local v44 = p40.Model.Seat
	v43.Part = assert(v44)
	v43.Driver = true
	__set_list(v42, 1, {v43})
	p40.Seats = v42
end
function v_u_32.MountLocalCamera(_, p45)
	local v_u_46 = p45.Player
	assert(v_u_46)
	local v_u_47 = v_u_46.CameraMaxZoomDistance
	p45.Maid:GiveTask(function()
		-- upvalues: (copy) v_u_46, (copy) v_u_47
		v_u_46.CameraMaxZoomDistance = v_u_47
	end)
	v_u_46.CameraMaxZoomDistance = 120
end
function v_u_32.MountPlayer(p_u_48, p49, p_u_50)
	-- upvalues: (copy) v_u_1, (copy) v_u_7, (copy) v_u_11, (copy) v_u_2
	local v51 = p49 ~= nil
	assert(v51)
	local v52 = p_u_50 ~= nil
	assert(v52)
	p_u_50.Local = p49 == v_u_1
	local v53 = p49.Character
	p_u_50.Character = assert(v53)
	local v54 = p_u_50.Character
	p_u_50.Humanoid = assert(v54:FindFirstChild("Humanoid"))
	p_u_50.JointNeck = p_u_50.Character.Head.Neck
	p_u_50.JointWaist = p_u_50.Character.UpperTorso.Waist
	p_u_50.JointNeckC0 = p_u_50.JointNeck.C0
	p_u_50.JointWaistC0 = p_u_50.JointWaist.C0
	p_u_50.Maid:GiveTask(function()
		-- upvalues: (copy) p_u_50
		p_u_50.JointNeck.C0 = p_u_50.JointNeckC0
		p_u_50.JointWaist.C0 = p_u_50.JointWaistC0
	end)
	v_u_7.setHumanoidEnabled(p_u_50.Humanoid, false)
	p_u_50.Humanoid:ChangeState(Enum.HumanoidStateType.Seated)
	p_u_50.Maid:GiveTask(function()
		-- upvalues: (ref) v_u_7, (copy) p_u_50
		v_u_7.setHumanoidEnabled(p_u_50.Humanoid, true)
		p_u_50.Humanoid:ChangeState(Enum.HumanoidStateType.Running)
	end)
	if p_u_50.Driver then
		p_u_48.AlignOrientation.Enabled = true
		p_u_48.AlignOrientation.CFrame = p_u_48.Model:GetPivot()
		if p_u_50.Local then
			p_u_48:MountLocalCamera(p_u_50)
			p_u_48:SetupLocalDriverInputs(p_u_50)
		end
		p_u_50.Maid:GiveTask(function()
			-- upvalues: (copy) p_u_48
			p_u_48.AlignOrientation.Enabled = false
			if p_u_48.ForceFront ~= nil then
				p_u_48.ForceFront.Force = Vector3.new()
			end
		end)
		p_u_50.SpringWaistRotation = v_u_11.new(Vector3.new(), Vector3.new(), 0.9, 20)
		p_u_50.SpringNeckRotation = v_u_11.new(Vector3.new(), Vector3.new(), 0.9, 20)
		p_u_50.Maid:GiveTask(v_u_2.Heartbeat:Connect(function()
			-- upvalues: (copy) p_u_48, (copy) p_u_50
			if p_u_48.Model ~= nil then
				p_u_48:HeartbeatDriver(p_u_50)
			end
		end))
	end
end
function v_u_32.UnmountSeat(_, p55)
	local v56 = p55 ~= nil
	assert(v56)
	local v57 = p55.Occupied == true
	assert(v57)
	p55.Local = nil
end
function v_u_32.UpdateCharacterJoints(_, p58)
	-- upvalues: (copy) v_u_31
	local v59 = p58.SpringWaistRotation:Update()
	p58.JointWaist.C0 = p58.JointWaistC0 * v_u_31(v59)
	local v60 = p58.SpringNeckRotation:Update()
	p58.JointNeck.C0 = p58.JointNeckC0 * v_u_31(v60)
end
local v_u_61 = {
	[Enum.KeyCode.A] = 2,
	[Enum.KeyCode.D] = 4,
	[Enum.KeyCode.ButtonR2] = 1,
	[Enum.KeyCode.ButtonL2] = 3
}
function v_u_32.UpdateInput(p62)
	-- upvalues: (copy) v_u_3, (ref) v_u_13
	local v63 = p62.WASD[1] - p62.WASD[3]
	local v64 = p62.WASD[2] - p62.WASD[4]
	if v_u_3.TouchEnabled then
		local v65 = v_u_13:GetControls():GetMoveVector().X
		local v66 = math.clamp(v65, -1, 1)
		v64 = -v66 * math.abs(v66)
	end
	p62.Forward = v63
	p62.Heading = v64
	p62.SpringForwardp = p62.SpringForward:SetTarget(v63)
	p62.SpringHeadingp = p62.SpringHeading:SetTarget(v64)
	p62.SpringAccelp = p62.SpringAccel:SetTarget(p62.Forward)
end
function v_u_32.UpdateThirdInput(_)
	error("TODO: Implement")
end
function v_u_32.CalculateSway(p67)
	local v68 = tick() - p67.BornAt
	local v69 = -125925.51356 + p67.BornAt
	local v70 = -51235.65816 + p67.BornAt
	local v71 = v68 * 1.1 + v69
	local v72 = math.cos(v71) * 0.1 * (0.5 * (1 - p67.SpringForwardp) + 0.5) + math.noise(v68, v69) * 0.05
	local v73 = p67.SpringForwardp
	local v74 = math.abs(v73)
	p67.SwayX = v72 * (1 - v74)
	local v75 = v68 * 0.8 + v70
	p67.SwayY = (math.sin(v75) * 0.4 + math.noise(v68, v70) * 0.1) * (1 - v74)
end
function v_u_32.GetAreTiresPopped(p76)
	-- upvalues: (copy) v_u_6, (copy) v_u_12
	local v77 = p76.Model:GetAttribute(v_u_6.TIRES_POPPED_AT_ATTR_NAME) or 0
	local v78 = p76.Model.Name
	return v77 + v_u_12.getVehicleCombatConfig(v78).DisableDuration > workspace:GetServerTimeNow()
end
function v_u_32.UpdatePhysics(p79)
	-- upvalues: (copy) v_u_10
	local v80 = p79:GetAreTiresPopped()
	local v81 = p79.WaterHeight
	local v82 = p79.PartBase.CFrame
	local v83 = -p79.PartBase.Size.Y * 0.5
	local v84 = p79.PartBase.Size.Z * 0.5
	local v85 = v82 * Vector3.new(0, v83, v84)
	local v86 = RaycastParams.new()
	v86.FilterDescendantsInstances = { p79.Model }
	local v87 = v_u_10.collidable(v85 + Vector3.new(0, 50, 0), Vector3.new(-0, -1, -0), 100, v86)
	local v88, v89
	if v87 then
		v88 = v87.Position
		v89 = v87.Material
	else
		v89 = nil
		v88 = nil
	end
	if v89 == Enum.Material.Water then
		v81 = v88.Y
		p79.WaterHeight = v81
		p79.AlignOrientation.Enabled = true
	else
		p79.AlignOrientation.Enabled = false
	end
	local v90 = v85.Y <= v81
	local v91 = p79.PartBase.CFrame
	local v92 = v91:VectorToObjectSpace(p79.PartBase.Velocity)
	local v93
	if p79.SpringAccelp > 0 then
		v93 = p79.Config.SpeedForward
	else
		v93 = p79.Config.SpeedForward * 0.5
	end
	local v94 = -p79.SpringAccelp * v93
	local v95 = Vector3.new(0, 0, v94)
	if v80 then
		v95 = v95 * 0.05
	end
	if not v90 then
		v95 = v95 * 0.25
	end
	local v96 = p79.Config.FrictionFwd or 0.05
	local v97 = v92.X * 3
	local v98 = v92.Z * v96
	local v99 = v92.Z
	local v100 = v92.Z
	local v101 = v98 + v99 * math.abs(v100) * 0.001
	local v102 = -Vector3.new(v97, 0, v101) * p79.PartBase.AssemblyMass
	p79.Force.Force = v95 * p79.PartBase.AssemblyMass * 10 + v102
	local v103 = -v91:VectorToObjectSpace(p79.PartBase.RotVelocity).Y / 0.5
	local v104 = math.clamp(v103, -1, 1)
	local v105 = -v92.z / 80
	local v106 = math.clamp(v105, -1, 1) * 0.8 + p79.SpringAccelp * 0.2
	local v107 = v104 + p79.SwayY
	local v108 = v106 + p79.SwayX
	local v109 = p79.SpringHeadingp * 3.141592653589793 * p79.Config.MaximumTurnAngle
	local v110 = p79.Config.TurnCurveCoeff or 1
	local v111 = -v92.Z
	local v112 = (math.abs(v111) - 100) / 800
	local v113 = math.clamp(v112, 0, 1)
	local v114 = 1 - v110 * math.sqrt(v113)
	local v115 = math.clamp(v114, 0.05, 1) * v109 * 0.25
	local v116 = p79.AlignOrientation
	local v117 = CFrame.new
	local v118 = v91.LookVector.X
	local v119 = v91.LookVector.Z
	v116.CFrame = v117(Vector3.new(0, 0, 0), Vector3.new(v118, 0, v119).Unit) * CFrame.Angles(0, 0, v107 * 3.141592653589793 * 0.03) * CFrame.Angles(v108 * 3.141592653589793 * 0.02, 0, 0) * CFrame.Angles(0, v115, 0) + v91.p
end
function v_u_32.HeartbeatDriver(p120, p121)
	local v122 = p121 ~= nil
	assert(v122)
	if p120.Model ~= nil then
		if p121.Local then
			p120:UpdateInput()
			p120:CalculateSway()
			p120:UpdatePhysics()
		else
			p120:UpdateThirdInput()
		end
		p120:UpdateCharacterJoints(p121)
	end
end
function v_u_32.SetupLocalDriverInputs(p_u_123, p124)
	-- upvalues: (copy) v_u_61, (copy) v_u_3, (copy) v_u_5
	p_u_123.WASD = {
		0,
		0,
		0,
		0
	}
	local function v127(p125, p126)
		-- upvalues: (ref) v_u_61, (copy) p_u_123
		if p126 then
			return true
		end
		if p125.UserInputType == Enum.UserInputType.Keyboard and v_u_61[p125.KeyCode] then
			p_u_123.WASD[v_u_61[p125.KeyCode]] = 1
		end
	end
	p124.Maid:GiveTask(v_u_3.InputBegan:Connect(v127))
	local function v130(p128, p129)
		-- upvalues: (ref) v_u_61, (copy) p_u_123
		if p129 then
			return true
		end
		if p128.UserInputType == Enum.UserInputType.Keyboard and v_u_61[p128.KeyCode] then
			p_u_123.WASD[v_u_61[p128.KeyCode]] = 0
		end
	end
	p124.Maid:GiveTask(v_u_3.InputEnded:Connect(v130))
	local function v136(p131)
		-- upvalues: (copy) p_u_123, (ref) v_u_61
		if p131.UserInputType == Enum.UserInputType.Gamepad1 then
			local v132 = p131.KeyCode
			if v132 == Enum.KeyCode.Thumbstick1 then
				local v133 = p131.Position
				local v134 = v133.X
				local _ = v133.Y
				p_u_123.WASD[2] = v134 < -0.24 and ((-v134) ^ 2 or 0) or 0
				p_u_123.WASD[4] = v134 > 0.24 and v134 ^ 2 or 0
				return
			end
			if v132 == Enum.KeyCode.ButtonR2 or v132 == Enum.KeyCode.ButtonL2 then
				local v135 = p131.Position.Z
				p_u_123.WASD[v_u_61[v132]] = v135 > 0.05 and v135 ^ 0.5 or 0
			end
		end
	end
	p124.Maid:GiveTask(v_u_3.InputChanged:Connect(v136))
	p124.Maid:GiveTask(v_u_5.add({
		["primary"] = true,
		["priority"] = 1000,
		["saturateTo"] = 0,
		["image"] = "rbxassetid://7858765663",
		["keyCodes"] = { Enum.KeyCode.W },
		["onPressed"] = function()
			-- upvalues: (copy) p_u_123
			p_u_123.WASD[1] = 1
		end,
		["onReleased"] = function()
			-- upvalues: (copy) p_u_123
			p_u_123.WASD[1] = 0
		end
	}))
	p124.Maid:GiveTask(v_u_5.add({
		["primary"] = true,
		["priority"] = 700,
		["saturateTo"] = 0,
		["image"] = "rbxassetid://7858764373",
		["keyCodes"] = { Enum.KeyCode.S },
		["onPressed"] = function()
			-- upvalues: (copy) p_u_123
			p_u_123.WASD[3] = 1
		end,
		["onReleased"] = function()
			-- upvalues: (copy) p_u_123
			p_u_123.WASD[3] = 0
		end
	}))
	p_u_123:UpdateInput()
end
function v_u_32.Destroy(p137)
	p137.Maid:Destroy()
end
return v_u_32
