-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMKBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplGVRJUkVTX1BPUFBFRF9BVF9BVFRSX05BTUURVElSRV9QT1BfRFVSQVRJT04TVmVoaWNsZVRpcmVzTGFzdFBvcAABBQAAAQIAGaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DAKEGAAAATQIDGAcAAACfAQICTQIBAAgAAADiAwsAbwQMADAEA/gJAAAAjAQPADAEA2EKAAAAnwICAIICAAANAwEEAAAAQAMCAwMDBAQAAEBAAwUDBgMHAwgDCQUCCQoDCgABAAEYAAEAAAAAAAEAAAAAAAABAAABAAABAAD+AAEAAAAAAE9mm+Uo+ZHefaLxcQu8xM2U2HN2PsEluZZWt5P2zNVihEc+GNmSdBg=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Std.TableUtils).requireValidIndexAndFreeze({
	["TIRES_POPPED_AT_ATTR_NAME"] = "VehicleTiresLastPop",
	["TIRE_POP_DURATION"] = 15
})
