-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNoBU1vZGVsBE5hbWUGYXNzZXJ0A25ldwxzZXRtZXRhdGFibGUFU2V0dXASTW90b3JTdGVlcmluZ1doZWVsDkZpbmRGaXJzdENoaWxkB1BoeXNpY3MFTW90b3ILTW90b3JFbmdpbmUKTW90b3JCbGFkZQhQYXJ0aWNsZQtNaXN0RW1pdHRlcgZWaXN1YWwMUGFydGljbGVNaXN0C1dha2VFbWl0dGVyDFBhcnRpY2xlV2FrZQlCbGFkZVNwaW4LT2JqZWN0TG9jYWwIUGFydEJhc2UGVm9sdW1lBkxvb3BlZAlEb05vdFBsYXkJSWRsZVNvdW5kCExvd1NvdW5kClNldHVwU2VhdHMFU2VhdHMEUGFydAlQYXNzZW5nZXIFdGFibGUGaW5zZXJ0C1JvdFZlbG9jaXR5AVkEbWF0aAVjbGFtcAdIZWFkaW5nCFZlbG9jaXR5BkNGcmFtZRNWZWN0b3JUb09iamVjdFNwYWNlAVoHRm9yd2FyZA1TcHJpbmdGb3J3YXJkCVNldFRhcmdldA5TcHJpbmdGb3J3YXJkcA1TcHJpbmdIZWFkaW5nDlNwcmluZ0hlYWRpbmdwEFVwZGF0ZVRoaXJkSW5wdXQPSGVhcnRiZWF0RHJpdmVyAkMwB0ludmVyc2UGQW5nbGVzAkMxA2FicxJTcHJpbmdOZWNrUm90YXRpb24HVmVjdG9yMxNTcHJpbmdXYWlzdFJvdGF0aW9uCU1hZ25pdHVkZQNleHANUGxheWJhY2tTcGVlZAdFbmFibGVkA0lLUAVQYXJ0MAhSaWdodEFybQdMZWZ0QXJtBEFybXMNU3RlcHBlZERyaXZlcgRTdG9wB0Rlc3Ryb3kLTW91bnRQbGF5ZXIGRHJpdmVyD0J1aWxkUGFja2V0QXJtcwlDaGFyYWN0ZXIETWFpZAdTdGVwcGVkB0Nvbm5lY3QIR2l2ZVRhc2sEUGxheQRGcmVxBUxvY2FsCEh1bWFub2lkCFJlc291cmNlDFNpdEFuaW1hdGlvbg1Mb2FkQW5pbWF0aW9uBGdhbWUKUnVuU2VydmljZQpHZXRTZXJ2aWNlEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUHUjE1SUt2MgZNb2R1bGUDU3RkBUF1ZGlvBnNjcmlwdAZQYXJlbnQEQm9hdAxTcGVlZEZvcndhcmQQTWF4aW11bVR1cm5BbmdsZQtGcmljdGlvbkZ3ZA5UdXJuQ3VydmVDb2VmZgdDcnVpc2VyClNwZWVkWWFjaHQLX19DbGFzc05hbWUHX19pbmRleAANCQEEAAAAe00CADsAAAAATQECugEAAAD7BAAAhwMEAbsBAwKkAgMAAAAgQJ8CAgL7BAEATQME7wQAAABSBAIAUgUAAJ8DAwL7BgIAnj0DBAYAAABSBQMApAQGAAAAUECfBAMBvAQDmQcAAACfBAIBTQQDOwAAAABvBggAvAQEAwkAAACfBAMCMAQDuQgAAABNBAM7AAAAAG8GCgC8BAQDCQAAAJ8EAwJvBgsAvAQEAwkAAACfBAMCDgQQAE0EAzsAAAAAbwYMALwEBAMJAAAAnwQDAjAEA8kMAAAATQQDOwAAAABvBg0AvAQEAwkAAACfBAMCMAQDUA0AAABNBwM7AAAAAE0GB9AQAAAATQUGFQ8AAABNBAU2DgAAADAEA5ARAAAATQcDOwAAAABNBgfQEAAAAE0FBpQSAAAATQQFNg4AAAAwBAPxEwAAAIwEAAAwBANRFAAAAPsFAwBNBAXRFQAAAE0FAxsWAAAAbwYXAOIHGwCMCAAAMAgHSxgAAACpCAEAMAgHtRkAAACpCAEAMAgHiBoAAACfBAQCMAQDlBwAAAD7BQMATQQF0RUAAABNBQMbFgAAAG8GHQDiBxsAjAgAADAIB0sYAAAAqQgBADAIB7UZAAAAqQgBADAIB4gaAAAAnwQEAjAEAz4eAAAAggMCAB8DAQMCAwMEAAAgQAMEAwUEAABQQAMGAwcDCAMJAwoDCwMMAw0DDgMPAxADEQMSAxMDFAMVAgAAgPQEmcNBAxYDFwMYBQMYGRoDGQIAAAA0BpnDQQMaAB0EARgAAAAAAgAAAAAAAQAAAAAAAQAAAAAAAAEAAAIAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAAAAAEAAAAAAAAAAAABAAABAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAIeAAAAAAMBAQAAAAb7AgAATQECmQAAAABSAgAAnwECAYIAAQABAwYAMgYBGAAAAAAAATMAAAAABwEBAAAAGPsCAABNAQL3AAAAAFICAACfAQIBTQIAdAEAAADiAwMATQYAOwQAAABNBQYxBQAAALsBBQKkBAcAAABgQJ8EAgIwBANEAgAAAJ40AgMDAAAApAEKAAAkgICfAQMBggABAAsDGwMcAx0FAQIDAQMeAwMEAABgQAMfAyAEACSAgAA1GwEYAAAAAAABAAABAAAAAAAAAAAAAAD/AAADNgAAAAAIAQAAAAA6TQIAGwAAAABNAQKqAQAAAE0EAXgDAAAAWwMEAowE//+MBQEATC4AAqQCBgAAFECAnwIEAjACADEHAAAATQMAGwAAAABNAgOFCAAAAE0EABsAAAAATQMEhQkAAABSBQIAvAMD7AoAAACfAwMCTQcDewwAAAA5BgcAPgUGC4wG//+MBwEATC4AAqQEBgAAFECAnwQEAjAEAP0NAAAATQQAQw4AAABNBgD9DQAAALwEBJcPAAAAnwQDAjAEADQQAAAATQQAzhEAAABNBgAxBwAAALwEBJcPAAAAnwQDAjAEAGQSAAAAggABABMDFQMhAgAAAAAAAABAAyIDIwMkBAAUQIADJQMmAycDKAIAAAAAAABUQAMpAyoDKwMsAy0DLgMvADswARgAAAAAAQAAAAAAAAAAAAABAAAAAQAAAAAAAAABAAAAAAAAAAAAAAACAAAAAAAAAAABAAAAAAAAAAABPQAAAAANAgEAAAD1AfsDAABNAgMFAAAAAFIDAABSBAEAnwIDAU0CALkBAAAADgIaAE0CALkBAAAATQYAuQEAAABNBQbtAgAAALwFBdoDAAAAnwUCAqQGBgAAFECAjAcAAIwIAABNCwBkCQAAAFsKCwhbCQoHnwYEAgkEBQZNBgC5AQAAAE0FBu0CAAAACQMEBTADAswKAAAATQIAyQsAAAAOAioATQIAyQsAAABNBwDJCwAAAE0GB+0CAAAAvAYG2gMAAACfBgICpAcGAAAUQIBNDAA0DgAAALsCDAKkCxEAAEDwgJ8LAgL1Cg0LWwkKCFsICQyMCQAAjAoAAJ8HBAIJBQYHpAYGAAAUQICMBwAATQsAZAkAAAA5CgsAWwkKCFsICQyMCQAAnwYEAgkEBQZNBgDJCwAAAE0FBu0CAAAACQMEBTADAswKAAAATQIAUBIAAAAOAiAATQMAURMAAABNBAA0DgAAAEMCAwQwAgBREwAAAE0CAFASAAAATQYAUBIAAABNBQbtAgAAALwFBdoDAAAAnwUCAqQGBgAAFECATQgAURMAAABbBwgUjAgAAIwJAACfBgQCCQQFBk0GAFASAAAATQUG7QIAAAAJAwQFMAMCzAoAAABNAgGDFQAAAG8IGABNCgD9GQAAALsCCgKkCREAAEDwgJ8JAgIJBwgJlQYHF3gFBhZNCAAxGwAAAFsHCAhbBgcajAcAAEw2AAKkBB4AAHTAgZ8EBAK8AgKXHwAAAJ8CAwFNAgESIAAAAG8HIQBNCQD9GQAAALsCCQKkCBEAAEDwgJ8IAgIJBgcIeAUGF4wGAABNCQBkCQAAAFsICQhbBwgiTDYAAqQEHgAAdMCBnwQEArwCApcfAAAAnwIDAU0EABsjAAAATQMEhSQAAABNAgOqJQAAAE0DAJQmAAAAOQcCAD4GByi7CwYCpAUqAACk8ICfBQICWwQFJzAEA0srAAAATQMAPiwAAAA5CAIAPgcIKLsLBwKkBioAAKTwgJ8GAgL1BQ0GWwQFJzAEA0srAAAATQMAPiwAAAA5BwIAPgYHKLsLBgKkBSoAAKTwgJ8FAgL1BA0FMAQDKC0AAACpAwAATQQANA4AAACMBQAAYAUGAAQAAACMBBQAtwQCAAIAAACpAwABqQMBAKkEAABNBQA0DgAAAIwGAABgBgYABQAAAIwFHgC3BQIAAgAAAKkEAAGpBAEATQYA8S4AAABNBQbwLwAAAPEFBQADAAAATQUA8S4AAAAwAwXwLwAAAE0GAJAwAAAATQUG8C8AAADxBQUABAAAAE0FAJAwAAAAMAQF8C8AAACCAAEAMQMxAwcDMgMzAycDNAQAFECAAjMzMzMzM9M/AhgtRFT7IQlAAy8DNQMLApqZmZmZmbk/AgAAAAAAAPA/Ay0DIwM2BABA8IADDAMTAgAAAAAAAOg/AzcC4PCcdi8btD8C4PCcdi8bxD8CUGnrMccozj8DKgKamZmZmZnJPwMlAzgDBAQAdMCBAywDOQJQaesxxyjOvwKamZmZmZmpPwMVAyYDOgMZAgAAAAAAAOA/AgAAAAAAAElAAzsEAKTwgAMWAxoDPAMSAz0DEABGMQEYAAAAAAAAAgAAAQAAAAAAAAAAAQAAAAAAAAAAAAEAAAAA/gAEAAABAAAAAAAAAAABAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAA/QAFAAABAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAD+AAUAAgAAAAAAAAAAAAEAAAAB/QAAAP8AAAcAAQAAAAAAAAAAAAAAAAAAAAAA/wAABQAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAIAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAABAAAAAgAAAAAAAQAAAAJHAAAAAAcCAQAACwAAAggGCQEIBg8BGE0CAQYAAAAATQQAuQEAAABNAwQ8AgAAAE0FA4UDAAAAbwYEAAkEBQYwBAKRBQAAAE0FA4UDAAAAbwYGAAkEBQYwBAJbBwAAAPsFAABNBAXMCAAAAFIFAgCfBAIBggABAAkDPgMHAz8DJweamRk/AAAAAAAAAD8AAAAAA0AHmpkZvwAAAAAAAAA/AAAAAANBA0IAdUMBGAAAAQAAAAEAAAAAAAEAAAAAAAMAAAAAAXcAAAAAAwACAAAAC/sBAABNAAE7AAAAAEcABgAAAAAA+wAAAPsCAQC8AAATAQAAAJ8AAwGCAAEAAgMBA0MAhQEAARgAAAAAAAEAAAAAAoYAAAAAAgABAAAAB/sBAABNAAGUAAAAALwAAPoBAAAAnwACAYIAAQACAxkDRACNAQABGAAAAAAAAAGOAAAAAAIAAQAAAAf7AQAATQABPgAAAAC8AAD6AQAAAJ8AAgGCAAEAAgMaA0QAkAEAARgAAAAAAAABkQAAAAACAAEAAAAN+wEAAE0AAfEAAAAAqQEAADABAPABAAAA+wEAAE0AAZACAAAAqQEAADABAPABAAAAggABAAMDEgM9AxAAlAEAARgAAAAAAAABAAAAAAABlQAAAAACAAEAAAAJ+wAAALwAAPoAAAAAnwACAfsAAAC8AABQAQAAAJ8AAgGCAAEAAgNEA0UAoAEAARgAAAAAAQAAAAGhAAAAAAkDBAAAAGf7BAAATQMEGAAAAABSBAAAUgUBAFIGAgCfAwQBTQMCuQEAAAAOA0UA+wQBAE0DBO8CAAAATQQCaQMAAACfAwICMAMCBgQAAABNBAJ2BQAAAPsHAgBNBgfZBgAAANkIAAASAAAAEgACALwGBscHAAAAnwYDALwEBP0IAAAAnwQAAU0EAJQJAAAAvAQE7goAAACfBAIBTQQAPgsAAAC8BATuCgAAAJ8EAgFNBAJ2BQAAANkGAQASAAAAvAQE/QgAAACfBAMBTQQCdgUAAADZBgIAEgAAALwEBP0IAAAAnwQDAU0EAnYFAAAA2QYDABIAAAC8BAT9CAAAAJ8EAwFNBAKDDAAAAIwFCgAwBQS1DQAAAE0EAhIOAAAAbwYPALwEBJcQAAAAnwQDAU0EAhIOAAAAjAUKADAFBLUNAAAATQMCuxEAAAAOAxQATQMCARIAAAD7BwMATQYHYhMAAABNBQYhFAAAALwDA5QVAAAAnwMDArwEA+4KAAAAnwQCAU0EAnYFAAAA2QYEABIAAwC8BAT9CAAAAJ8EAwGCAAEAFgNGA0cDSANJAz4DSgNLA0wDTQMZA04DGgM3A08DOQd82aC+AAAAAAAAAAAAAAAAAywDUANRA1IDUwNUBQYHCAkKf0YBGAAAAAAAAAABAAABAAAAAAABAAIAAAAAAAAAAAAAAAAABgAAAAABAAAAAAEAAAAAAAADAAAAAAAABAAAAAAAAAUAAAAAAQAAAAAAAQAAAAACAAABAAAAAAAAAAAAAQAAAQAAAAAAAAWAAAAAAAsAAAECAHSjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIGAAAAUEBNBAFACAAAAE0DBEoHAAAAnwICAqQDBgAAAFBATQUBoQkAAABNBAXSCgAAAJ8DAgKkBQwAAACwQE0EBSQNAAAApAUGAAAAUEBNBgQ7DgAAAJ8FAgL/BgIAAAAAAOIHEwCMCAsAMAgHzA8AAABvCBQAMAgHVRAAAABvCBUAMAgHihEAAACMCAEAMAgHGhIAAAAwBwaYFgAAAOIHEwCMCAsAMAgHzA8AAABvCBcAMAgHVRAAAACMCAAAMAgHihEAAACMCAEAMAgHGhIAAAAwBwZ+GAAAAP8HBQAAAAAAbwgWADAIB+UZAAAAMAcHbhoAAACePQcFBQAAAFIJBwBSCgUApAgcAAAAsEGfCAMBwAgdABIABgASAAUAEgAHABIAAwAwCAfvHgAAAMAIHwASAAUAMAgHmSAAAADACCEAEgAFADAIB/ciAAAAwAgjADAIB1gkAAAAwAglABIABQAwCAcFJgAAAMAIJwASAAIAMAgHEygAAADACCkAEgAFABIAAgASAAAAEgABADAIBxgqAAAAggcCACsDVQQAAABAA1YDVwNYA1kEAABQQANaA1sDXANdA14EAACwQANfA2ADYQNiA2MDZAUEDxAREgKamZmZmZm5PwJ7FK5H4XqkPwNlArgehetRuK4/A2YDZwNoAwUEAACwQQYAAwQGAQMGBgIDGwYDAzAGBAMxBgUDQwYLA0YHAAECAwQFCwEAARgAAQAAAAAAAQAAAAAAAQAAAAAAAAEAAAAAAAACAAAAAQAAAAACAAEBAAABAAABAAABAAD8AAYBAAABAAABAAABAAD8AAgAAQAAAQABAAAAAAAAAQAAAAAAABUAAAADAAAABgAACwAAAC8AAAAKAAAAAAAAKgEAAAAADI7Z5HUwXSRWvB2O4VHILCKpXo+EP0S76IrVHA2rdsJdwkxggPnkqYg=

-- Decompiled by Krnl

local v_u_1 = game:GetService("RunService")
local v_u_2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v_u_2.Module.R15IKv2)
local v_u_4 = require(v_u_2.Std.Audio)
local v5 = script.Parent
local v_u_6 = require(v5.Boat)
local v_u_7 = {
	["Cruiser"] = {
		["SpeedForward"] = 11,
		["MaximumTurnAngle"] = 0.1,
		["FrictionFwd"] = 0.04,
		["TurnCurveCoeff"] = 1
	},
	["SpeedYacht"] = {
		["SpeedForward"] = 11,
		["MaximumTurnAngle"] = 0.06,
		["FrictionFwd"] = 0,
		["TurnCurveCoeff"] = 1
	}
}
local v_u_8 = {
	["__ClassName"] = "Cruiser"
}
v_u_8.__index = v_u_8
setmetatable(v_u_8, v_u_6)
function v_u_8.new(p9)
	-- upvalues: (copy) v_u_7, (copy) v_u_6, (copy) v_u_8, (copy) v_u_4
	local v10 = v_u_7[p9.Model.Name]
	local v11 = assert(v10)
	local v12 = v_u_6.new(v11, p9)
	local v13 = v_u_8
	setmetatable(v12, v13)
	v12:Setup()
	v12.MotorSteeringWheel = v12.Model:FindFirstChild("MotorSteeringWheel")
	if v12.Model:FindFirstChild("Physics"):FindFirstChild("Motor") then
		v12.MotorEngine = v12.Model:FindFirstChild("MotorEngine")
		v12.MotorBlade = v12.Model:FindFirstChild("MotorBlade")
	end
	v12.ParticleMist = v12.Model.Visual.MistEmitter.Particle
	v12.ParticleWake = v12.Model.Visual.WakeEmitter.Particle
	v12.BladeSpin = 0
	v12.IdleSound = v_u_4.ObjectLocal(v12.PartBase, 657590761, {
		["Volume"] = 0,
		["Looped"] = true,
		["DoNotPlay"] = true
	})
	v12.LowSound = v_u_4.ObjectLocal(v12.PartBase, 657591400, {
		["Volume"] = 0,
		["Looped"] = true,
		["DoNotPlay"] = true
	})
	return v12
end
function v_u_8.Setup(p14)
	-- upvalues: (copy) v_u_6
	v_u_6.Setup(p14)
end
function v_u_8.SetupSeats(p15)
	-- upvalues: (copy) v_u_6
	v_u_6.SetupSeats(p15)
	local v16 = p15.Seats
	local v17 = {}
	local v18 = p15.Model.Passenger
	v17.Part = assert(v18)
	table.insert(v16, v17)
end
function v_u_8.UpdateThirdInput(p19)
	local v20 = p19.PartBase.RotVelocity.Y * 2
	p19.Heading = math.clamp(v20, -1, 1)
	local v21 = p19.PartBase.Velocity
	local v22 = -p19.PartBase.CFrame:VectorToObjectSpace(v21).Z / 80
	p19.Forward = math.clamp(v22, -1, 1)
	p19.SpringForwardp = p19.SpringForward:SetTarget(p19.Forward)
	p19.SpringHeadingp = p19.SpringHeading:SetTarget(p19.Heading)
end
function v_u_8.HeartbeatDriver(p23, p24)
	-- upvalues: (copy) v_u_6
	v_u_6.HeartbeatDriver(p23, p24)
	if p23.MotorSteeringWheel then
		p23.MotorSteeringWheel.C1 = p23.MotorSteeringWheel.C0:Inverse() * CFrame.Angles(0, 0, p23.SpringHeadingp * 3.141592653589793 * 0.3) * p23.MotorSteeringWheel.C0
	end
	if p23.MotorEngine then
		local v25 = p23.MotorEngine
		local v26 = p23.MotorEngine.C0:Inverse()
		local v27 = CFrame.Angles
		local v28 = p23.SpringForwardp
		v25.C1 = v26 * v27((1 - math.abs(v28)) * 3.141592653589793 * 0.1, 0, 0) * CFrame.Angles(0, -p23.SpringHeadingp * 3.141592653589793 * 0.1, 0) * p23.MotorEngine.C0
	end
	if p23.MotorBlade then
		p23.BladeSpin = p23.BladeSpin + p23.SpringForwardp
		p23.MotorBlade.C1 = p23.MotorBlade.C0:Inverse() * CFrame.Angles(p23.BladeSpin * 0.75, 0, 0) * p23.MotorBlade.C0
	end
	local v29 = p24.SpringNeckRotation
	local v30 = p23.Forward
	local v31 = 0.23561944901923448 * math.abs(v30) + 0.15707963267948966 - 0.07853981633974483
	local v32 = p23.Heading * 3.141592653589793 * 0.2
	v29:SetTarget((Vector3.new(v31, v32, 0)))
	local v33 = p24.SpringWaistRotation
	local v34 = p23.Forward
	local v35 = -0.23561944901923448 * math.abs(v34) - 0.15707963267948966
	local v36 = p23.SpringHeadingp * 3.141592653589793 * 0.05
	v33:SetTarget((Vector3.new(v35, 0, v36)))
	local v37 = p23.PartBase.Velocity.Magnitude
	local v38 = p23.IdleSound
	local v39 = -v37 / 50
	v38.Volume = math.exp(v39) * 0.5
	local v40 = p23.LowSound
	local v41 = -v37 / 50
	v40.Volume = (1 - math.exp(v41)) * 0.5
	local v42 = p23.LowSound
	local v43 = -v37 / 50
	v42.PlaybackSpeed = 1 - math.exp(v43)
	local v44
	if p23.SpringForwardp > 0 then
		v44 = v37 > 20
	else
		v44 = false
	end
	local v45
	if p23.SpringForwardp > 0 then
		v45 = v37 > 30
	else
		v45 = false
	end
	if p23.ParticleWake.Enabled ~= v44 then
		p23.ParticleWake.Enabled = v44
	end
	if p23.ParticleMist.Enabled ~= v45 then
		p23.ParticleMist.Enabled = v45
	end
end
function v_u_8.SteppedDriver(p46, p47)
	-- upvalues: (copy) v_u_3
	local v48 = p47.IKP
	local v49 = p46.MotorSteeringWheel.Part0
	v48.RightArm = v49.CFrame * Vector3.new(0.6, 0, 0.5)
	v48.LeftArm = v49.CFrame * Vector3.new(-0.6, 0, 0.5)
	v_u_3.Arms(v48)
end
function v_u_8.MountPlayer(p_u_50, p51, p_u_52)
	-- upvalues: (copy) v_u_6, (copy) v_u_3, (copy) v_u_1, (copy) v_u_2
	v_u_6.MountPlayer(p_u_50, p51, p_u_52)
	if p_u_52.Driver then
		p_u_52.IKP = v_u_3.BuildPacketArms(p_u_52.Character)
		p_u_52.Maid:GiveTask(v_u_1.Stepped:Connect(function()
			-- upvalues: (copy) p_u_50, (copy) p_u_52
			if p_u_50.Model ~= nil then
				p_u_50:SteppedDriver(p_u_52)
			end
		end))
		p_u_50.IdleSound:Play()
		p_u_50.LowSound:Play()
		p_u_52.Maid:GiveTask(function()
			-- upvalues: (copy) p_u_50
			p_u_50.IdleSound:Stop()
		end)
		p_u_52.Maid:GiveTask(function()
			-- upvalues: (copy) p_u_50
			p_u_50.LowSound:Stop()
		end)
		p_u_52.Maid:GiveTask(function()
			-- upvalues: (copy) p_u_50
			p_u_50.ParticleWake.Enabled = false
			p_u_50.ParticleMist.Enabled = false
		end)
		p_u_52.SpringNeckRotation.Freq = 10
		p_u_52.SpringWaistRotation:SetTarget(Vector3.new(-0.31415927, 0, 0))
		p_u_52.SpringWaistRotation.Freq = 10
	end
	if p_u_52.Local then
		local v_u_53 = p_u_52.Humanoid:LoadAnimation(v_u_2.Resource.SitAnimation)
		v_u_53:Play()
		p_u_52.Maid:GiveTask(function()
			-- upvalues: (copy) v_u_53
			v_u_53:Stop()
			v_u_53:Destroy()
		end)
	end
end
return v_u_8
