-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMqBnN0YXR1cwpUZXN0U3RhdHVzB1NraXBwZWQHU3VjY2VzcwE/CSVzWyVzXSAlcwNyZXAIcGxhbk5vZGUGcGhyYXNlBmZvcm1hdAV0YWJsZQZpbnNlcnQGaXBhaXJzCGNoaWxkcmVuCnJlcG9ydE5vZGUKcmVwb3J0Um9vdAZjb25jYXQBCgZyZXBvcnQNVGVzdCByZXN1bHRzOiAlZCBwYXNzZWQsICVkIGZhaWxlZCwgJWQgc2tpcHBlZAxzdWNjZXNzQ291bnQMZmFpbHVyZUNvdW50DHNraXBwZWRDb3VudAVwcmludCAlZCB0ZXN0IG5vZGVzIHJlcG9ydGVkIGZhaWx1cmVzLgZlcnJvcnMZRXJyb3JzIHJlcG9ydGVkIGJ5IHRlc3RzOgAFRXJyb3IEZ2FtZQtUZXN0U2VydmljZQpHZXRTZXJ2aWNlB3JlcXVpcmUGc2NyaXB0BlBhcmVudAhUZXN0RW51bQEgASsHRmFpbHVyZQEtAX4ABQ0DBAAABwAAAQMFKgJDUgMBACsDAgD/AwAAAAAAAFIBAwCQAgIATQMAzAEAAAD7BgAATQUG8QIAAABNBAX0AwAAAJoDAgAEAAAAggECAMYDAABNBADMAQAAAPsHAABNBgfxAgAAAE0FBpoEAAAA8QQVAAUAAAD7BgEATQcAzAEAAACHBQYHkAQFBW8FBgD7BwIAUgkCALwHBxYHAAAAnwcDAlIIBABNCgCOCAAAAE0JCk4JAAAAvAUFjQoAAACfBQUCUgMFAJ40AQUDAAAAUgUBAFIGAwCkBA0AADCwgJ8EAwGkBA8AAADgQE0FAO4QAAAAnwQCBFEEBQD7CQMAUgoIAFILAQCVDAIRnwkEAW4E+v8CAACAggECABICAAAAAAAAAAADAQMCAwMDBAMFAwYDBwMIAwkDCgMLAwwEADCwgAMNBAAA4EADDgIAAAAAAADwPwAWDwEYAAAAAAABAgAAAAAAAAAAAQMCAAAAAAAAAAABAAAAAAIBAAAAAAEBAAAA/QAAAAcAAAAAAAACAAAAAAABAAAAAP8ABBcAAAAACwEBAAAAEP8BAAAAAAAApAIBAAAAAEBNAwDuAgAAAJ8CAgRRAgUA+wcAAFIIBgBSCQEAjAoAAJ8HBAFuAvr/AgAAgIIBAgADAw0EAAAAQAMOADMQARgAAAIAAAAAAAEAAAAA/wAENAAAAAAFAQEAAAAJ+wEAAFICAACfAQICpAICAAAEAIBSAwEAbwQDAJ8CAwCCAgAABAMLAxEEAAQAgAMSAD0TARgAAAACAAAAAAA+AAAAAAoBAgAACwAAAgMEEwIDAyoCTv8BAAADAAAAbwIAAPsEAABSBQAAnwQCAqQFAwAACBCAUgYEAG8HBACfBQMCUgMFAG8EBQBNBgBCBgAAAE0HACAHAAAATQgAFQgAAAC8BASNCQAAAJ8EBQDFAQIAAQAAAKQCCwAAAKBApAMDAAAIEIBSBAEAbwUEAJ8DAwCfAgABTQIAIAcAAACMAwAAYAMKAAIAAACkAgsAAACgQG8DDABNBQAgBwAAALwDA40JAAAAnwMDAJ8CAAFNAwAjDQAAABwCAwCMAwAAYAMaAAIAAACkAgsAAACgQG8DDgCfAgIBpAILAAAAoEBvAw8AnwICAaQCEQAAAABBTQMAIw0AAACfAgIEUQIJAPsHAQBSCQYAvAcH3hIAAACfBwMBpAcLAAAAoEBvCA8AnwcCAW4C9v8CAACAggABABMDFAMLAxEEAAgQgAMSAxUDFgMXAxgDCgMZBAAAoEADGgMbAxwDHQMNBAAAAEEDHgBDEwEYBgAB+QAAAgAAAAAABwEAAQABAP0AAAAABwAAAAAAAAACAAAAAAEAAAAAAAAAAAMAAAAAAAEAAAABAAAAAgAAAAAAAQAAAAADAAAA/AAHPgAAAAAJAAABAgcAAAEDAhQCPKMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQKQFBwAAAGBATQQFJAgAAABNAwQkCAAAAE0CA74JAAAAnwECAm8CCgCMBAMAvAICFgsAAACfAgMC/wMDAAAAAABNBQHxDAAAAE0EBZoNAAAAbwUOAGoFAwRNBQHxDAAAAE0EBYcPAAAAbwUQAGoFAwRNBQHxDAAAAE0EBfQRAAAAbwUSAGoFAwT/BAEAAAAAAMAFEwASAAEAEgADABIAAgASAAUAwAYUABIABQDABxUAEgAGAMAIFgASAAYAEgAAADAIBFAXAAAAggQCABgDHwQAAABAAyADIQMiBAAAQEADIwQAAGBAAyQDJQMmAwcDAgMEAycDKAMpAwMDKgYABgEGAgYDAxMEAAECAwEAARgABwAAAAAAAgAAAAAAAAAAAAACAAAAAAEAAQAAAAAAAQAAAAAAAQAAAAAABAACAAAAAB0ACgAGAAAAAB4BAAAAAAQvpxng+II4MR1jc3Tp0+Jo915gTNzQsqeoC2nNU10QseB8Ln6i0zLD

-- Decompiled by Krnl

local v_u_1 = game:GetService("TestService")
local v_u_2 = require(script.Parent.Parent.TestEnum)
local v_u_3 = (" "):rep(3)
local v_u_4 = {
	[v_u_2.TestStatus.Success] = "+",
	[v_u_2.TestStatus.Failure] = "-",
	[v_u_2.TestStatus.Skipped] = "~"
}
local v5 = {}
local function v_u_14(p6, p7, p8)
	-- upvalues: (copy) v_u_2, (copy) v_u_4, (copy) v_u_3, (copy) v_u_14
	local v9 = p7 or {}
	local v10 = p8 or 0
	if p6.status == v_u_2.TestStatus.Skipped then
		return v9
	end
	local v11
	if p6.status == v_u_2.TestStatus.Success then
		v11 = nil
	else
		local v12 = v_u_4[p6.status] or "?"
		v11 = ("%s[%s] %s"):format(v_u_3:rep(v10), v12, p6.planNode.phrase)
	end
	table.insert(v9, v11)
	for _, v13 in ipairs(p6.children) do
		v_u_14(v13, v9, v10 + 1)
	end
	return v9
end
local function v_u_18(p15)
	-- upvalues: (copy) v_u_14
	local v16 = {}
	for _, v17 in ipairs(p15.children) do
		v_u_14(v17, v16, 0)
	end
	return v16
end
function v5.report(p19)
	-- upvalues: (copy) v_u_18, (copy) v_u_1
	local v20 = {}
	local v21 = v_u_18(p19)
	__set_list(v20, 1, {"Test results:", table.concat(v21, "\n"), ("%d passed, %d failed, %d skipped"):format(p19.successCount, p19.failureCount, p19.skippedCount)})
	print(table.concat(v20, "\n"))
	if p19.failureCount > 0 then
		print(("%d test nodes reported failures."):format(p19.failureCount))
	end
	if #p19.errors > 0 then
		print("Errors reported by tests:")
		print("")
		for _, v22 in ipairs(p19.errors) do
			v_u_1:Error(v22)
			print("")
		end
	end
end
return v5
