-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMRBmFzc2VydAxzZXRtZXRhdGFibGUFR3JhcGgETm9kZQNuZXcPX29uV2Fsa2VkU2lnbmFsEUdldE9uV2Fsa2VkU2lnbmFsB0hhc0VkZ2UERmlyZQZXYWxrVG8EZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUDU3RkBlNpZ25hbAdfX2luZGV4AAQGAgEAAAAYuwEAA1IDAACkAgEAAAAAQJ8CAgG7AQEDUgMBAKQCAQAAAABAnwICAf8CAgAAAAAA+wUAAJ49AgQFAAAAUgQCAKQDAwAAACBAnwMDATAAAjEEAAAAMAECDgUAAACCAgIABgMBBAAAAEADAgQAACBAAwMDBAAHBQEYAAAAAAABAAAAAAIAAQAAAAAAAAIAAQACCAAAAAADAQEAAAANTQEAfgAAAABHAQcAAAAAgPsCAABNAQLvAQAAAJ8BAQIwAQB+AAAAAE0BAH4AAAAAggECAAIDBgMFABMHARgAAAAAAQAAAAAAAgAAFAAAAAAGAgAAAAAduwEBA1IDAQCkAgEAAAAAQJ8CAgFNAgAxAgAAAE0EAA4DAAAAUgUBALwCAigEAAAAnwIEAg4CDQAwAQAOAwAAAE0CAH4FAAAADgIGAE0CAH4FAAAAUgQBALwCAt0GAAAAnwIDAakCAQCCAgIAqQIAAIICAgAHAwEEAAAAQAMDAwQDCAMGAwkAGQoBGAAAAAAAAQAAAAAAAAAAAQABAAABAAAAAAACAAIAGgAAAAAEAAABAgAeowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAoQYAAABNAgMfBwAAAJ8BAgL/AgMAAAAAADACAm4IAAAAwAMJABIAAgAwAwLvCgAAAMADCwASAAEAMAMCVwwAAADAAw0AMAMCXw4AAACCAgIADwMLBAAAAEADDAMNAw4EAABAQAMPAxADEQYAAwUGAQMHBgIDCgMAAQIBAAEYAAEAAAAAAAEAAAAAAAACAAEAAQAAAAwAAAAGAAAMAQAAAAADP2Arr7lHGSENpEE7CESkHxUf26nnHZKA0++aQYAeZ0EV14P5NWeHkQ==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.Signal)
local v_u_3 = {}
v_u_3.__index = v_u_3
function v_u_3.new(p4, p5)
	-- upvalues: (copy) v_u_3
	assert(p4)
	assert(p5)
	local v6 = {}
	local v7 = v_u_3
	setmetatable(v6, v7)
	v6.Graph = p4
	v6.Node = p5
	return v6
end
function v_u_3.GetOnWalkedSignal(p8)
	-- upvalues: (copy) v_u_2
	if p8._onWalkedSignal == nil then
		p8._onWalkedSignal = v_u_2.new()
	end
	return p8._onWalkedSignal
end
function v_u_3.WalkTo(p9, p10)
	assert(p10)
	if not p9.Graph:HasEdge(p9.Node, p10) then
		return false
	end
	p9.Node = p10
	if p9._onWalkedSignal then
		p9._onWalkedSignal:Fire(p10)
	end
	return true
end
return v_u_3
