-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgM9BGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzB1JvYmJlcnkNUm9iYmVyeUNvbnN0cxFDT0xPUl9UT19JTkZPX01BUBFMRVZFTF9UT19JTkZPX01BUBJIWVBFUkNIUk9NRV9QUkVGSVgMTEVWRUxfUFJFRklYH0hZUEVSQ0hST01FX05BTUVfQVRUUklCVVRFX05BTUUsTUFYX0xFVkVMX0hZUEVSQ0hST01FX1BBUlRJQ0xFX1JFU09VUkNFX05BTUUpSFlQRVJDSFJPTUVfTlVNQkVSX1BBUlRJQ0xFX1JFU09VUkNFX05BTUUhSFlQRVJTSElGVF9QQVJUSUNMRV9SRVNPVVJDRV9OQU1FHFJBSU5CT1dfQU5JTUFUSU9OX0NZQ0xFX1RJTUUdV0lMRENBUkRfSFlQRVJDSFJPTUVfSU1BR0VfSUQFR3JlZW4GWWVsbG93Bk9yYW5nZQNSZWQEUGluawZQdXJwbGUEQmx1ZQdEaWFtb25kDExldmVsVG9Db2xvcgdJbWFnZUlkCVJvYmJlcmllcwZDb2xvcjMHZnJvbVJHQgxFTlVNX1JPQkJFUlkEQkFOSwVCQU5LMg9UUkFJTl9QQVNTRU5HRVILVFJBSU5fQ0FSR08GTVVTRVVNBFRPTUILQ1JPV05fSkVXRUwLUE9XRVJfUExBTlQLQ0FSR09fUExBTkUHSkVXRUxSWQ1OdW1iZXJJbWFnZUlkGHJieGFzc2V0aWQ6Ly8xMDA4MDA3NTAwNxhyYnhhc3NldGlkOi8vMTAwODAwNzQ2NTcYcmJ4YXNzZXRpZDovLzEwMDgwMDc0MzI4GHJieGFzc2V0aWQ6Ly8xMDA4MDA0ODUxMRhyYnhhc3NldGlkOi8vMTAwODAwNzU5MDkFSHlwZXIDTHZsFkh5cGVyQ2hyb21lQXBwbGllZE5hbWUaSHlwZXJDaHJvbWVMZXZlbDVQYXJ0aWNsZXMgSHlwZXJDaHJvbWVOdW1iZXJQYXJ0aWNsZUVtaXR0ZXIXSHlwZXJTaGlmdEF1cmFQYXJ0aWNsZXMJTUFYX0xFVkVMBVNoaWZ0EENPTE9SX1NISUZUX05BTUUgUk9CQkVSWV9UT19IWVBFUkNIUk9NRV9DT0xPUl9NQVALUmVmbGVjdGFuY2UWSFlQRVJTSElGVF9SRUZMRUNUQU5DRRpyZXF1aXJlVmFsaWRJbmRleEFuZEZyZWV6ZQABDwAAAQAAnwSjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CAxgHAAAAnwECAqQCBQAAAEBATQQABAgAAABNAwRYCQAAAJ8CAgLiAxQA4gQdAOIFIQD/BgAABQAAAKQHJAAAjCCCjAgaAIwJZQCMCg0AnwcEAqQIJAAAjCCCjAkgAIwKfACMCxAAnwgEAqQJJAAAjCCCjAopAIwLnQCMDBQAnwkEAqQKJAAAjCCCjAs1AIwM0ACMDRkAnwoEAqQLJAAAjCCCjAxpAIwNMQGMDhkAnwsEAMUGBwABAAAAMAYFQB4AAABvBiUAMAYFlh8AAAD/BgAAAgAAAE0IApsmAAAATQcIgycAAABNCQKbJgAAAE0ICfYoAAAAxQYHAwEAAAAwBgVIIAAAADAFBJsVAAAA4gUhAP8GAAAFAAAApAckAACMIIKMCHQAjAlgAIwKAwCfBwQCpAgkAACMIIKMCZ8AjAqBAIwLBACfCAQCpAkkAACMIIKMCtwAjAuuAIwMBwCfCQQCpAokAACMIIKMC+8AjAzvAIwNCgCfCgQCpAskAACMIIKMDEABjA1FAYwOAACfCwQAxQYHAAEAAAAwBgVAHgAAAG8GKQAwBgWWHwAAAP8GAAACAAAATQgCmyYAAABNBwi2KgAAAE0JApsmAAAATQgJpysAAADFBgcDAQAAADAGBUggAAAAMAUEfRYAAADiBSEA/wYAAAUAAACkByQAAIwggowIdgCMCUMAjAoDAJ8HBAKkCCQAAIwggowJiwCMCk4AjAsDAJ8IBAKkCSQAAIwggowKvgCMC2wAjAwhAJ8JBAKkCiQAAIwggowL/QCMDIIAjA0IAJ8KBAKkCyQAAIwggowMKQKMDZsAjA4oAJ8LBADFBgcAAQAAADAGBUAeAAAAbwYsADAGBZYfAAAA/wYAAAEAAABNCAKbJgAAAE0HCEQtAAAAxQYHAgEAAAAwBgVIIAAAADAFBG4XAAAA4gUhAP8GAAAFAAAApAckAACMIIKMCGgAjAkUAIwKBACfBwQCpAgkAACMIIKMCYMAjAoWAIwLBACfCAQCpAkkAACMIIKMCrUAjAseAIwMBQCfCQQCpAokAACMIIKMC/8AjAwoAIwNAACfCgQCpAskAACMIIKMDJABjA0oAIwOAACfCwQAxQYHAAEAAAAwBgVAHgAAAG8GLgAwBgWWHwAAAP8GAAABAAAATQgCmyYAAABNBwirLwAAAMUGBwIBAAAAMAYFSCAAAAAwBQRvGAAAAOIFIQD/BgAABQAAAKQHJAAAjCCCjAhsAIwJCACMCkkAnwcEAqQIJAAAjCCCjAmCAIwKBgCMC1YAnwgEAqQJJAAAjCCCjAqdAIwLBwCMDGUAnwkEAqQKJAAAjCCCjAvYAIwMBgCMDYgAnwoEAqQLJAAAjCCCjAzEAYwNAACMDp0AnwsEAMUGBwABAAAAMAYFQB4AAABvBjAAMAYFlh8AAAD/BgAAAQAAAE0IApsmAAAATQcI8DEAAADFBgcCAQAAADAGBUggAAAAMAUE1xkAAADiBSEA/wYAAAUAAACkByQAAIwggowIPgCMCQUAjAp2AJ8HBAKkCCQAAIwggowJVACMCgAAjAuVAJ8IBAKkCSQAAIwggowKYwCMCwAAjAy5AJ8JBAKkCiQAAIwggowLdwCMDAAAjA3VAJ8KBAKkCyQAAIwggowMggCMDTIAjA7CAZ8LBADFBgcAAQAAADAGBUAeAAAAbwYyADAGBZYfAAAA/wYAAAEAAABNCAKbJgAAAE0HCBMzAAAAxQYHAgEAAAAwBgVIIAAAADAFBGcaAAAA4gUhAP8GAAAFAAAApAckAACMIIKMCAEAjAkiAIwKZQCfBwQCpAgkAACMIIKMCQIAjAomAIwLdACfCAQCpAkkAACMIIKMCgMAjAs0AIwMoACfCQQCpAokAACMIIKMCwcAjAxQAIwN/wCfCgQCpAskAACMIIKMDCIAjA08AIwOWAKfCwQAxQYHAAEAAAAwBgVAHgAAAG8GNAAwBgWWHwAAAP8GAAABAAAATQgCmyYAAABNBwjKNQAAAMUGBwIBAAAAMAYFSCAAAAAwBQTSGwAAAOIFIQD/BgAABQAAAKQHJAAAjCCCjAgJAIwJTACMCmgAnwcEAqQIJAAAjCCCjAkMAIwKYACMC4MAnwgEAqQJJAAAjCCCjAoPAIwLeACMDKAAnwkEAqQKJAAAjCCCjAsTAIwMnACMDdQAnwoEAqQLJAAAjCCCjAxEAIwN2gCMDscBnwsEAMUGBwABAAAAMAYFQB4AAABvBjYAMAYFlh8AAAD/BgAAAQAAAE0IApsmAAAATQcIbDcAAADFBgcCAQAAADAGBUggAAAAMAUEsRwAAAAwBAMjCgAAAP8EAAAFAAAA4gU5AG8GOgAwBgXSOAAAAOIGOQBvBzsAMAcG0jgAAADiBzkAbwg8ADAIB9I4AAAA4gg5AG8JPQAwCQjSOAAAAOIJOQBvCj4AMAoJ0jgAAADFBAUGAQAAADAEA+4LAAAAbwQ/ADAEA7AMAAAAbwRAADAEAxoNAAAAbwRBADAEA/4OAAAAbwRCADAEA4EPAAAAbwRDADAEA94QAAAAbwREADAEA4URAAAAjAQFADAEA4oSAAAAbwRFADAEA5wTAAAATQUD7gsAAAAcBAUAMAQDJEYAAABNBQOwDAAAAG8GRwBzBAUGMAQDpUgAAAD/BAAAAAAAADAEAxRJAAAATQYD7gsAAAATBQYDTQQFYkoAAAAwBANISwAAAE0EAyMKAAAAxgUAAMYGAABkBAoATQkISCAAAADGCgAAxgsAAGQJAwBNDgMUSQAAAGoHDg1uCfz/AgAAAG4E9f8CAAAATQQBAEwAAABSBQMAnwQCAIIEAABNAwEEAAAAQAMCAwMDBAQAAEBAAwUDBgMHAwgDCQMKAwsDDAMNAw4DDwMQAxEDEgUKCgsMDQ4PEBESEwMTAxQDFQMWAxcDGAMZAxoFCBUWFxgZGhscAxsDHAMdBQMeHyADHgMfBACMIIICAABwudTFAkIDIAMhAyICAACwz9TFAkIDIwMkAgAAKOTUxQJCAyUCAABQUdXFAkIDJgIAAEgF1cUCQgMnAgAAuBzVxQJCAygCAACwLdXFAkIDKQIAADBA1cUCQgMqAysFATgDLAMtAy4DLwMwAzEDMgMzAzQDNQM2AgAAOHYoAgZCAzcDOAM5AzoDOwM8Az0AAQABGAABAAAAAAABAAAAAAAAAQAAAAAAAAIBAQEAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAAD7AAcAAAEAAAAAAAAAAAAAAAAA9wALAQABAAAAAAABAAAAAAABAAAAAAABAAAAAAABAAAAAAAAAPsABwAAAQAAAAAAAAAAAAAAAAD3AAsBAAEAAAAAAAEAAAAAAAEAAAAAAAEAAAAAAAEAAAAAAAAA+wAHAAABAAAAAAAAAAAA9wALAQABAAAAAAABAAAAAAABAAAAAAABAAAAAAABAAAAAAAAAPsABwAAAQAAAAAAAAAAAPcACwEAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAAD7AAcAAAEAAAAAAAAAAAD3AAsBAAEAAAAAAAEAAAAAAAEAAAAAAAEAAAAAAAEAAAAAAAAA+wAHAAABAAAAAAAAAAAA9wALAQABAAAAAAABAAAAAAABAAAAAAABAAAAAAABAAAAAAAAAPsABwAAAQAAAAAAAAAAAPcACwEAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAAD7AAcAAAEAAAAAAAAAAAD3ALIAWgABAQAAAgEAAAIBAAACAQAAAgEAAAAA8gARAAABAAABAAACAAABAAABAAACAAABAAADAAAAAAEAAAAAAAEAAAABAAAAAAAAAQAAAAABAAAAAAEAAP8A/wAGAAAAAAEAAAAAAMIsO03SByyj8OhR2V97uFqM/0uS0dhDuoO1JszldMRiIiiA5CQ52RE=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v2 = require(v1.Std.TableUtils)
local v3 = require(v1.Robbery.RobberyConsts)
local v4 = {}
local v5 = {
	["Green"] = {
		["LevelToColor"] = {
			Color3.fromRGB(26, 101, 13),
			Color3.fromRGB(32, 124, 16),
			Color3.fromRGB(41, 157, 20),
			Color3.fromRGB(53, 208, 25),
			Color3.fromRGB(105, 305, 25)
		},
		["ImageId"] = 10078557998,
		["Robberies"] = { v3.ENUM_ROBBERY.BANK, v3.ENUM_ROBBERY.BANK2 }
	},
	["Yellow"] = {
		["LevelToColor"] = {
			Color3.fromRGB(116, 96, 3),
			Color3.fromRGB(159, 129, 4),
			Color3.fromRGB(220, 174, 7),
			Color3.fromRGB(239, 239, 10),
			Color3.fromRGB(320, 325, 0)
		},
		["ImageId"] = 10078558710,
		["Robberies"] = { v3.ENUM_ROBBERY.TRAIN_PASSENGER, v3.ENUM_ROBBERY.TRAIN_CARGO }
	},
	["Orange"] = {
		["LevelToColor"] = {
			Color3.fromRGB(118, 67, 3),
			Color3.fromRGB(139, 78, 3),
			Color3.fromRGB(190, 108, 33),
			Color3.fromRGB(253, 130, 8),
			Color3.fromRGB(553, 155, 40)
		},
		["ImageId"] = 10078559365,
		["Robberies"] = { v3.ENUM_ROBBERY.MUSEUM }
	},
	["Red"] = {
		["LevelToColor"] = {
			Color3.fromRGB(104, 20, 4),
			Color3.fromRGB(131, 22, 4),
			Color3.fromRGB(181, 30, 5),
			Color3.fromRGB(255, 40, 0),
			Color3.fromRGB(400, 40, 0)
		},
		["ImageId"] = 10078562858,
		["Robberies"] = { v3.ENUM_ROBBERY.TOMB }
	},
	["Pink"] = {
		["LevelToColor"] = {
			Color3.fromRGB(108, 8, 73),
			Color3.fromRGB(130, 6, 86),
			Color3.fromRGB(157, 7, 101),
			Color3.fromRGB(216, 6, 136),
			Color3.fromRGB(452, 0, 157)
		},
		["ImageId"] = 10078560425,
		["Robberies"] = { v3.ENUM_ROBBERY.CROWN_JEWEL }
	},
	["Purple"] = {
		["LevelToColor"] = {
			Color3.fromRGB(62, 5, 118),
			Color3.fromRGB(84, 0, 149),
			Color3.fromRGB(99, 0, 185),
			Color3.fromRGB(119, 0, 213),
			Color3.fromRGB(130, 50, 450)
		},
		["ImageId"] = 10078561175,
		["Robberies"] = { v3.ENUM_ROBBERY.POWER_PLANT }
	},
	["Blue"] = {
		["LevelToColor"] = {
			Color3.fromRGB(1, 34, 101),
			Color3.fromRGB(2, 38, 116),
			Color3.fromRGB(3, 52, 160),
			Color3.fromRGB(7, 80, 255),
			Color3.fromRGB(34, 60, 600)
		},
		["ImageId"] = 10078561718,
		["Robberies"] = { v3.ENUM_ROBBERY.CARGO_PLANE }
	},
	["Diamond"] = {
		["LevelToColor"] = {
			Color3.fromRGB(9, 76, 104),
			Color3.fromRGB(12, 96, 131),
			Color3.fromRGB(15, 120, 160),
			Color3.fromRGB(19, 156, 212),
			Color3.fromRGB(68, 218, 455)
		},
		["ImageId"] = 10078562310,
		["Robberies"] = { v3.ENUM_ROBBERY.JEWELRY }
	}
}
v4.COLOR_TO_INFO_MAP = v5
v4.LEVEL_TO_INFO_MAP = {
	{
		["NumberImageId"] = "rbxassetid://10080075007"
	},
	{
		["NumberImageId"] = "rbxassetid://10080074657"
	},
	{
		["NumberImageId"] = "rbxassetid://10080074328"
	},
	{
		["NumberImageId"] = "rbxassetid://10080048511"
	},
	{
		["NumberImageId"] = "rbxassetid://10080075909"
	}
}
v4.HYPERCHROME_PREFIX = "Hyper"
v4.LEVEL_PREFIX = "Lvl"
v4.HYPERCHROME_NAME_ATTRIBUTE_NAME = "HyperChromeAppliedName"
v4.MAX_LEVEL_HYPERCHROME_PARTICLE_RESOURCE_NAME = "HyperChromeLevel5Particles"
v4.HYPERCHROME_NUMBER_PARTICLE_RESOURCE_NAME = "HyperChromeNumberParticleEmitter"
v4.HYPERSHIFT_PARTICLE_RESOURCE_NAME = "HyperShiftAuraParticles"
v4.RAINBOW_ANIMATION_CYCLE_TIME = 5
v4.WILDCARD_HYPERCHROME_IMAGE_ID = 11815685831
v4.MAX_LEVEL = #v4.LEVEL_TO_INFO_MAP
v4.COLOR_SHIFT_NAME = v4.HYPERCHROME_PREFIX .. "Shift"
v4.ROBBERY_TO_HYPERCHROME_COLOR_MAP = {}
v4.HYPERSHIFT_REFLECTANCE = v4.LEVEL_TO_INFO_MAP[4].Reflectance
for v6, v7 in v4.COLOR_TO_INFO_MAP do
	for _, v8 in v7.Robberies do
		v4.ROBBERY_TO_HYPERCHROME_COLOR_MAP[v8] = v6
	end
end
return v2.requireValidIndexAndFreeze(v4)
