-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgPvAQV2YWx1ZQVwcm9wcwxkZWZhdWx0VmFsdWUIc2V0U3RhdGUEaW5pdAlvbkNoZWNrZWQFRnJhbWUWQmFja2dyb3VuZFRyYW5zcGFyZW5jeQRTaXplCFBvc2l0aW9uBHNpemUIcG9zaXRpb24FVmFsdWUFVGl0bGULbGF5b3V0T3JkZXIKY2hlY2tDb2xvcgxjb3JuZXJSYWRpdXMIZGlzYWJsZWQFVURpbTIDbmV3BXN0YXRlBWNvbG9yBFVEaW0JVGV4dExhYmVsC0FuY2hvclBvaW50BFRleHQERm9udApMaW5lSGVpZ2h0DlRleHRYQWxpZ25tZW50ClRleHRTY2FsZWQKVGV4dENvbG9yMwtMYXlvdXRPcmRlcglmcm9tU2NhbGULYXNwZWN0UmF0aW8McGFkZGluZ1JhdGlvB1ZlY3RvcjIFdGl0bGUERW51bQtMdWNraWVzdEd1eQRMZWZ0BkNvbG9yMwZyZW5kZXIKY2F0ZWdvcmllcwRuYW1lDmZsb29yRnVybml0dXJlDXdhbGxGdXJuaXR1cmUQY2VpbGluZ0Z1cm5pdHVyZQdkZWZlbnNlFHNldEZ1cm5pdHVyZUNhdGVnb3J5Bm1vZHVsZQtzZXRDYXRlZ29yeQxjYXRlZ29yeU5hbWUMc2VsZWN0ZWROYW1lBE5vbmUFcGFnZXMIcGFnZU5hbWUFdXBEb3QDdXNlD0Zsb29yIEZ1cm5pdHVyZQhIb21lSXRlbQ5XYWxsIEZ1cm5pdHVyZRFDZWlsaW5nIEZ1cm5pdHVyZQdEZWZlbnNlCXdhbGxDb2xvcgpXYWxsIENvbG9yCVdhbGxDb2xvcg9zZWNvbmRXYWxsQ29sb3IRU2Vjb25kIFdhbGwgQ29sb3IPU2Vjb25kV2FsbENvbG9yDWZsb29yTWF0ZXJpYWwORmxvb3IgTWF0ZXJpYWwNRmxvb3JNYXRlcmlhbApmbG9vckNvbG9yC0Zsb29yIENvbG9yCkZsb29yQ29sb3ILd2luZG93Q29sb3IMV2luZG93IENvbG9yC1dpbmRvd0NvbG9yCndpbmRvd1RpbnQLV2luZG93IFRpbnQKV2luZG93VGludA9jYXRlZ29yeU9uQ2xpY2sHYmdDb2xvcglpbnZlbnRvcnkJSU5WRU5UT1JZB2Zyb21SR0IFc3RvcmUFU1RPUkUIc2V0dGluZ3MIU0VUVElOR1MLcGFnZU9uQ2xpY2sRZW50cnlBbGxvd0ZyaWVuZHMURU5UUlk6IEFMTE9XIEZSSUVORFMOZW50cnlBbGxvd0NyZXcRRU5UUlk6IEFMTE9XIENSRVcOZW50cnlBbGxvd1RlYW0RRU5UUlk6IEFMTE9XIFRFQU0SZW50cnlBbGxvd0V2ZXJ5b25lFUVOVFJZOiBBTExPVyBFVkVSWU9ORQhyZXF1aXJlcxNlZGl0aW5nQWxsb3dGcmllbmRzFkVESVRJTkc6IEFMTE9XIEZSSUVORFMQZWRpdGluZ0FsbG93Q3JldxNFRElUSU5HOiBBTExPVyBDUkVXEGVkaXRpbmdBbGxvd1RlYW0TRURJVElORzogQUxMT1cgVEVBTRRlZGl0aW5nQWxsb3dFdmVyeW9uZRdFRElUSU5HOiBBTExPVyBFVkVSWU9ORQxzZXR0aW5nSXRlbXMHb25DbGljaxBhdHRlbXB0UGxhY2VJdGVtEmF0dGVtcHRQcmV2aWV3SXRlbQ9zZXRTYXZlZFNldHRpbmcQb25TZXR0aW5nQ2hhbmdlZAVwbGFjZQhwdXJjaGFzZRNhdHRlbXB0UHVyY2hhc2VJdGVtBmRlbGV0ZRFhdHRlbXB0RGVsZXRlSXRlbQRleGl0B3Zpc2libGUEaG9tZQpHZXRPd25lcklkC0xvY2FsUGxheWVyBlVzZXJJZAhzZWxlY3RlZBxzZWxlY3RlZFBhZ2UgbXVzdCBub3QgYmUgbmlsBmFzc2VydApwYWRkaW5nVG9wDXBhZGRpbmdCb3R0b20LcGFkZGluZ0xlZnQMcGFkZGluZ1JpZ2h0CWNvbXBvbmVudA9iYWNrZ3JvdW5kQ29sb3Igc2VsZWN0ZWRDYXRlZ29yeSBtdXN0IG5vdCBiZSBuaWwPc2VsZWN0ZWRCZ0NvbG9yBWl0ZW1zCWF2YWlsYWJsZQV0YWJsZQZpbnNlcnQLY2FuRmF2b3JpdGULYWNjZW50Q29sb3IOcXVhbnRpdHlQbGFjZWQFJWQvJWQGZm9ybWF0BSVkLyVzCW1heFBsYWNlZAh0b3N0cmluZwPiiJ4XY3JlYXRlSG9tZUl0ZW1JdGVtVGFibGUUZ2V0RnVsbE5hbWVGcm9tVGFibGULQ3JlYXRvck5hbWUIZXF1aXBwZWQPY3VzdG9tQ29tcG9uZW50C2NyZWF0b3JOYW1lCkZyZWRva2FPbmUFb3duZWQWYmFja2dyb3VuZFRyYW5zcGFyZW5jeQZDb3JuZXIJU2Nyb2xsaW5nBEhlbHAIVUlDb3JuZXIMQ29ybmVyUmFkaXVzGmV4cG9zZVBhZGRlZENvbnRhaW5lclByb3BzC3Jvd3NQZXJQYWdlCmNvbHNQZXJSb3cIbWV0YWRhdGEMaXRlbURlZmF1bHRzBkJ1dHRvbjJZb3UgZG9uJ3QgaGF2ZSBhbnkgb2YgdGhlc2UuLiBjaGVjayBvdXQgdGhlIHN0b3JlISxObyBtb3JlIGl0ZW1zIHRvIGJ1eS4uIGNoZWNrIHlvdXIgaW52ZW50b3J5IQthbmNob3JQb2ludAVTdG9yZQlJbnZlbnRvcnkNc2F2ZWRTZXR0aW5ncwNCVVkERVhJVAhTZXR0aW5ncxR2ZXJ0aWNhbFBhZGRpbmdSYXRpbxdVSUFzcGVjdFJhdGlvQ29uc3RyYWludAdTaWRlYmFyBEJvZHkGQm90dG9tC0FzcGVjdFJhdGlvBVBhZ2VzCkNhdGVnb3JpZXMESE9NRQdCYW5nZXJzCFVJU3Ryb2tlBUNvbG9yCVRoaWNrbmVzcwVJbm5lcgRDYXNoDUNhdGVnb3J5VGl0bGUNR3JpZENvbnRhaW5lcgNCYXIEY2FzaBJwcm9tcHRDYXNoUHVyY2hhc2UPQm9yZGVyU2l6ZVBpeGVsBlpJbmRleApzYXR1cmF0ZUJ5B0Nvcm5lcnMHQnV0dG9ucwR0eXBlA2tleQRnYW1lB1BsYXllcnMKR2V0U2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQdyZXF1aXJlA0FwcAlJdGVtVXRpbHMERXpVaQhDaGVja2JveAZzY3JpcHQGUGFyZW50D0J1dHRvbkNvbXBvbmVudAVSb2FjdA1jcmVhdGVFbGVtZW50D1BhZGRlZENvbnRhaW5lcgZHYXJhZ2UCVUkHQ2FzaEJhcg1DdXN0b21pemVJdGVtClJvYWN0Um9kdXgFU2FmZXMTcGFkZGVkU2Nyb2xsaW5nR3JpZANTdGQKQ29sb3JVdGlscwVUcmFkZQ1DcmVhdG9yVmFsdWVzF0NhdGVnb3J5QnV0dG9uQ29tcG9uZW50E1BhZ2VCdXR0b25Db21wb25lbnQNUHVyZUNvbXBvbmVudAtTZXR0aW5nSXRlbQZleHRlbmQJQ29tcG9uZW50B0hvbWVBcHAHY29ubmVjdAASBgEAAAAAC+IDAQBNBQAHAgAAAE0EBZYDAAAAMAQDzAAAAAC8AQAqBAAAAJ8BAwGCAAEABQMBBQEAAwIDAwMEAB4FARgAAQAAAAAA/wAAAx8AAAAABAEBAAAAFfsBAADiAwEAMAADzAAAAAC8AQEqAgAAAJ8BAwH7AwAATQIDBwMAAABNAQJgBAAAAA4BBwD7AwAATQIDBwMAAABNAQJgBAAAAFICAACfAQIBggABAAUDAQUBAAMEAwIDBgAsBgEYAAABAP8AAAMAAAAAAAEAAAAAAAACLQAAAAAQAQIAAACeAfsBAABvAgAA4gMEAIwEAQAwBAM6AQAAAE0FAAcFAAAATQQFDwYAAAAwBAMvAgAAAE0FAAcFAAAATQQF2wcAAAAwBAM7AwAAAOIECgD7BQAA+wYBAOIHEQCkCBQAAEwggYwJAQCMCgAAjAsBAIwMAACfCAUCMAgHDwYAAABNCQAYFQAAAE0ICcwLAAAAMAgHzAsAAADZCAAAEgAAADAIB2AMAAAAjAgBADAIByANAAAATQkABwUAAABNCAlEFgAAADAIBwwOAAAApAgYAABMcIGMCQAAjAoEAJ8IAwIwCAdvDwAAAE0JAAcFAAAATQgJghAAAAAwCAeCEAAAAJ8FAwIwBQTsCAAAAPsFAABvBhkA4gciAIwIAQAwCAc6AQAAAKQIJAAAjCCBTQ0ABwUAAABNDA2JJgAAANgLJQxNDgAHBQAAAE0NDignAAAATQ8ABwUAAABNDg+JJgAAAOwMDQ5DCgsM9QklCm8KKACfCAMCMAgHLwIAAACkCCoAAEyQgowJAABvCisAnwgDAjAIB+gaAAAApAgkAACMIIFNDAAHBQAAAE0LDIkmAAAA2AolC00NAAcFAAAATQwNKCcAAABNDgAHBQAAAE0NDokmAAAA7AsMDUMJCgtvCisAnwgDAjAIBzsDAAAATQkABwUAAABNCAmaLAAAADAIB/UbAAAApAgvAC5w0MIwCAc5HAAAAG8IMAAwCAeCHQAAAKQIMgAxeNDCMAgHex4AAACpCAEAMAgH3h8AAACkCDQAAEwwg4wJAQCMCgEAjAsBAJ8IBAIwCAdzIAAAAIwIAgAwCAcAIQAAAJ8FAwIwBQS6CQAAAJ8BBACCAQAANQMHAwgDCQMKBQMBAgMDAgMLAwwDDQMOBQIICQMBAwYDDwMQAxEDEgUHBgsMDQ4PEAMTAxQEAEwggQMVAxYDFwQATHCBAxgDGQMaAxsDHAMdAx4DHwMgBQsBAhoDGxwdHh8gIQMhBACMIIECAAAAAAAA8D8DIgMjApqZmZmZmek/AyQEAEyQggIAAAAAAADgPwMlAyYDJwQucNDCAmZmZmZmZuY/AygEMXjQwgMpBABMMIMBASMqARgAAAABAAABAAAAAAABAAAAAAABAQAAAQAAAAAAAAAAAQAAAAAAAQAAAAgAAAEAAAAAAAEAAAAAAAABAAAAAADyAAAQAAABAAABAAEAAAAAAAAAAAAAAAAAAAAB/gAABAAAAAAAAAEAAQAAAAAAAAAAAAAAAAAAAf4AAAQAAAAAAAEAAAABAAABAAAAAQAAAQAAAAAAAAABAADvAADrACQAAAAABwECAAAANfsDAABNAgPgAAAAAIcBAgBNAgFaAQAAAPACDQACAAAATQIBWgEAAADwAgkAAwAAAE0CAVoBAAAA8AIFAAQAAABNAgFaAQAAAPACCQAFAACA+wQAAE0DBAcGAAAATQIDdAcAAABSAwEAnwICAWUACgBNAgGgCAAAAA4CBwD7BAAATQMEBwYAAABNAgNECQAAAFIDAQCfAgIB+wIAAOIEDABNBQFaAQAAADAFBL4KAAAA+wYBAE0FBj8NAAAAMAUEOQsAAAC8AgIqDgAAAJ8CAwGCAAEADwMrAywDLQMuAy8DMAMCAzEDMgMzAzQDNQUCCgsDNgMEAI4BAAEYAAAAAAIAAAABAAAAAQAAAAEAAAACAAAAAAAAAAEAAAEAAAAAAAACAAEAAAABAAAAAP4AAASPAAAAAAcBAgAAABP7AwAATQIDzgAAAACHAQIA+wIAAOIEAwBNBQFaBAAAADAFBOkBAAAA+wYBAE0FBj8FAAAAMAUEOQIAAAC8AgIqBgAAAJ8CAwGCAAEABwM3AzgDNQUCAQIDLAM2AwQAsQEAARgAAAAAAQABAAAAAQAAAAD+AAAEsgAAAAANAQEAAACgAv8BAAAKAAAA4gIFAG8DBgAwAwJaAAAAAG8DBwAwAwKaAQAAAG8DCAAwAwKgAgAAAIwDAQAwAwIGAwAAAIwDAQAwAwK/BAAAAOIDBQBvBAkAMAQDWgAAAABvBAoAMAQDmgEAAABvBAgAMAQDoAIAAACMBAAAMAQDBgMAAACMBAEAMAQDvwQAAADiBAUAbwULADAFBFoAAAAAbwUMADAFBJoBAAAAbwUIADAFBKACAAAAjAX//zAFBAYDAAAAjAUBADAFBL8EAAAA4gUNAG8GDgAwBgVaAAAAAG8GDwAwBgWaAQAAAG8GCAAwBgWgAgAAAIwGAgAwBgW/BAAAAOIGEABvBxEAMAcGWgAAAABvBxIAMAcGmgEAAABvBxMAMAcGoAIAAADiBxAAbwgUADAIB1oAAAAAbwgVADAIB5oBAAAAbwgWADAIB6ACAAAA4ggQAG8JFwAwCQhaAAAAAG8JGAAwCQiaAQAAAG8JGQAwCQigAgAAAOIJEABvChoAMAoJWgAAAABvChsAMAoJmgEAAABvChwAMAoJoAIAAADiChAAbwsdADALCloAAAAAbwseADALCpoBAAAAbwsfADALCqACAAAA4gsQAG8MIAAwDAtaAAAAAG8MIQAwDAuaAQAAAG8MIgAwDAugAgAAAMUBAgsBAAAAMAEA4CMAAADZAgAAEgAAABICAAAwAgBcJAAAAP8CAAADAAAA4gMmAG8EJwAwBANaAAAAAG8EKAAwBAOaAQAAAKQEKwAAqJCCjAX/AIwGygCMBwsAnwQEAjAEA+glAAAA4gQmAG8FLAAwBQRaAAAAAG8FLQAwBQSaAQAAAKQFKwAAqJCCjAb/AIwHmwCMCBkAnwUEAjAFBOglAAAA4gUmAG8GLgAwBgVaAAAAAG8GLwAwBgWaAQAAAKQGKwAAqJCCjAf/AIwIcACMCRkAnwYEAjAGBeglAAAAxQIDBAEAAAAwAgDOMAAAANkCAQASAAAAEgIAADACAG4xAAAATQMA4CMAAAATAgMA4gU1AG8GJwAwBgXpMgAAAE0GAloAAAAAMAYFvjMAAAD7BwAATQYHPzYAAAAwBgU5NAAAALwDACo3AAAAnwMDAU0EAAc4AAAATQMEdDkAAABSBAIAnwMCAf8DAAAIAAAA4gQ6AG8FOwAwBQRaAAAAAG8FPAAwBQSaAQAAAOIFOgBvBj0AMAYFWgAAAABvBj4AMAYFmgEAAADiBjoAbwc/ADAHBloAAAAAbwdAADAHBpoBAAAA4gc6AG8IQQAwCAdaAAAAAG8IQgAwCAeaAQAAAOIIRABvCUUAMAkIWgAAAABvCUYAMAkImgEAAABvCTsAMAkIikMAAADiCUQAbwpHADAKCVoAAAAAbwpIADAKCZoBAAAAbwo9ADAKCYpDAAAA4gpEAG8LSQAwCwpaAAAAAG8LSgAwCwqaAQAAAG8LPwAwCwqKQwAAAOILRABvDEsAMAwLWgAAAABvDEwAMAwLmgEAAABvDEEAMAwLikMAAADFAwQJAQAAADADAKNNAAAAggABAE4DLAMlAzIDOQM6BQUAAQIDBAMtAzsDPAMuAz0DLwM+BQQAAQIEAzADPwUDAAECA0ADQQNCA0MDRANFA0YDRwNIA0kDSgNLA0wDTQNOA08DUANRAysDUgNTBQMAASUDVANVAykDVgQAqJCCA1cDWANZA1oDNwNbAzgDNAM1BQMyMzQDNgMEAwIDMQUCAAEDXANdA14DXwNgA2EDYgNjA2QFAwABQwNlA2YDZwNoA2kDagNrA2wDbQIDBFAFARgAAAEBAAABAAABAAABAAABAAACAQAAAQAAAQAAAQAAAQAAAgEAAAEAAAEAAAEAAAEAAAIBAAABAAABAAABAAACAQAAAQAAAQAAAgEAAAEAAAEAAAIBAAABAAABAAACAQAAAQAAAQAAAgEAAAEAAAEAAAIBAAABAAABAAAAAAMAAgAAAAASAAEBAAABAAABAAAAAAAAAAIBAAABAAABAAAAAAAAAAIBAAABAAABAAAAAAAAAAAA8gARAAAAAAgAAAEBAAABAAAAAQAAAAD9AAAFAAAAAAACAAEBAAABAAACAQAAAQAAAgEAAAEAAAIBAAABAAACAQAAAQAAAQAAAgEAAAEAAAEAAAIBAAABAAABAAACAQAAAQAAAQAAAADdACZRAAAAAAIAAgAAAAb7AQAATQABbgAAAAD7AQEAnwACAYIAAQABA1sAkgJuARgAAAAAAAETAQAAAAUAAgAAACj7AAAA4gIBAPsEAQBNAwRaAgAAADADAjkAAAAAvAAAKgMAAACfAAMB+wIAAE0BAhgEAAAATQAB6QUAAADwAAkABgAAgPsCAABNAQIHBwAAAE0AAYAIAAAA+wEBAJ8AAgGCAAEA+wIAAE0BAhgEAAAATQAB6QUAAADwAAgACQAAgPsCAABNAQIHBwAAAE0AAQAKAAAA+wEBAJ8AAgGCAAEACwM1BQEAAywDBAMVAzgDVAMCA28DVwNwAOACbgEYAAABAAAAAP8AAAQAAAAAAAADAAAAAAAAAAMAAAAAAAABAAAAAAAAAmEBAAAABAABAAAAGfsCAABNAQIYAAAAAE0AAekBAAAA8AAKAAIAAID7AAAA4gIDAG8DBAAwAwLpAQAAALwAACoFAAAAnwADAYIAAQD7AAAA4gIDAG8DAgAwAwLpAQAAALwAACoFAAAAnwADAYIAAQAGAxUDOANUBQEBA1cDBAC4A24BGAAAAAAAAAABAAEAAP8AAAAEAAEAAP8AAAS5AQAAAAQBAgAAABv7AwAATQIDBwAAAABNAQJlAQAAAPsDAQBNAgNaAgAAAFIDAACfAQMB+wMAAE0CAwcAAAAATQECEQMAAAAOAQoA+wMAAE0CAwcAAAAATQECEQMAAAD7AwEATQIDWgIAAABSAwAAnwEDAYIAAQAEAwIDcQMsA3IA0wMGARgAAAAAAAAAAAAAAQAAAAAAAQAAAAAAAAAAAALUAQAAAAMAAwAAADL7AQAATQABWgAAAADwAAkAAQAAgPsCAQBNAQIHAgAAAE0AAYADAAAA+wECAJ8AAgGCAAEA+wEAAE0AAVoAAAAA8AAJAAQAAID7AgEATQECBwIAAABNAAEVBQAAAPsBAgCfAAIBggABAPsBAABNAAFaAAAAAPAACAAGAACA+wIBAE0BAgcCAAAATQABxwcAAACfAAEBggABAPsBAABNAAFaAAAAAPAABwAIAACA+wIBAE0BAgcCAAAATQABAAgAAACfAAEBggABAAkDLANzAwIDbwN0A3UDdgN3A3gAtwRuARgAAAAAAAEAAAAAAAAAAQAAAAABAAAAAAAAAAEAAAAAAQAAAAAAAAEAAAAAAQAAAAAAAjgCAAAAKQENAAANAAACAxXdAgIDFfYCAuUMTQIABwAAAABNAQKgAQAAACsBAQCCAAEAqQEAAE0DAAcAAAAATQIDCgIAAABHAhEAAAAAAE0DAAcAAAAATQIDCgIAAAC8AgKJAwAAAJ8CAgL7BQAATQQFMQQAAABNAwTmBQAAAPECAgADAAAAqQEAAakBAQD/AgAAAAAAAMYDAABNBADOBgAAAMYFAADGBgAAZAQTAOIJCABNCwhaCQAAAE0NABgKAAAATQwN6QsAAADxCwIADAAAAKkKAAGpCgEAMAoJTQcAAABqCQIHhwoCB00JCk0HAAAADgkBAFIDCABuBOz/AgAAAEcDAgAAAACAqQUAAakFAQCBAQUEDAAAAG8GDACkBA4AAADQQJ8EAwH/BAAAAAAAAE0FAM4GAAAAxgYAAMYHAABkBUAAhwoCCE0LCVoJAAAA+wwBAPsNAgDiDhYApA8ZAABgcIGMEAEATRMAzgYAAAAcEhMA2BEaEp8PAwIwDw4PDwAAAKQPGQAAYHCBjBAAAHgSCBpNFADOBgAAABwTFADsERITnw8DAjAPDtsQAAAAbw8bADAPDhERAAAAbw8bADAPDswSAAAAbw8bADAPDt4TAAAAbw8bADAPDl4UAAAA+w8DADAPDugVAAAA4g8fAE0QCZocAAAAMBAPmhwAAABNEApNBwAAADAQD00HAAAATRAJ6CAAAAAwEA8OHQAAANkQAAASAAAAEgAIADAQD24eAAAAMA8OBwAAAACfDAMCagwEC24Fv/8CAAAA/wUAAAAAAADGBgAATQcA4CEAAADGCAAAxgkAAGQHEwDiDAgATQ4LWgkAAABNEAAYCgAAAE0PEL4iAAAA8Q4CAA8AAACpDQABqQ0BADANDE0HAAAAagwFCocNBQpNDA1NBwAAAA4MAQBSBgsAbgfs/wIAAABHBgIAAAAAgKkIAAGpCAEAgQEIBCMAAABvCSMApAcOAAAA0ECfBwMB4gclAE0IA+ggAAAAMAgHoCQAAABNCABcJgAAADAIB24eAAAAxggAAMYJAABNCwAYCgAAAE0KC+kLAAAA8AoHACcAAABNCwAYCgAAAE0KC+kLAAAA8AoEAigAAID/CgAAAAAAAE0OAAcAAAAATQsOGCkAAADGDAAAxg0AAGQLTgBNEQAYCgAAAE0QEekLAAAA8BAiACcAAIBNEgAHAAAAAE0REoAnAAAATRIPoCoAAACHEBESDhBAAE0TAAcAAAAATRITgCcAAABNEw+gKgAAAIcREhNNEg9aCQAAAIcQERIOEDUATRMABwAAAABNEhOAJwAAAE0TD6AqAAAAhxESE00SD1oJAAAAhxAREowRAADUECkAEQAAAGUAIABNEQAYCgAAAE0QEekLAAAA8BAbACgAAIBNEA+rKwAAAA4QHgBNEA+gKgAAAPAQFAAsAAAATRIABwAAAABNERKAJwAAAE0SD6AqAAAAhxAREg4QCwBNEwAHAAAAAE0SE4AnAAAATRMPoCoAAACHERITTRIPWgkAAACHEBESKxAHAJ40CgUPAAAAUhEKAFISDwCkEC8AALjQgp8QAwFuC7H/AgAAAOILMgCpDAAAMAwLJjAAAABNDAPoIAAAADAMC1oxAAAA/wwAAAAAAABSDQoAxg4AAMYPAABkDdMAxhIAAE0TEaAqAAAA8BNEACwAAIBNFgAHAAAAAE0VFoAnAAAATRYRoCoAAACHFBUWRxQMAAAAAABNFgAHAAAAAE0VFoAnAAAATRYRoCoAAACHFBUWTRURWgkAAACHExQVKxMBAIwTAABNFwAHAAAAAE0WF/k0AAAATRcRWgkAAACHFRYXkBQVM00WABgKAAAATRUW6QsAAADwFQkAJwAAgG8VNQAmFxMUUhgTALwVFY02AAAAnxUEAlISFQBlABgATRYAGAoAAABNFRbpCwAAAPAVEwAoAACAbxU3AFIXEwBNGREGOAAAAEcZCAAAAAAATRkRBjgAAAC7PxkCpBg6AAAAkEOfGAICZQABAG8YOwC8FRWNNgAAAJ8VBAJSEhUA+xQEAE0TFAQ8AAAATRQRWgkAAACfEwIC+xUEAE0UFZI9AAAAUhUTAJ8UAgL7FgUAhxUWFA4VBAD7FwUAhxYXFE0VFp4+AAAA4hZCANkXAQASAAAAEgARADAXFm4eAAAATRgRWgkAAABNGgAYCgAAAE0ZGjlDAAAA8RgCABkAAACpFwABqRcBADAXFk0HAAAATRoABwAAAABNGRouPwAAAE0aEaAqAAAAhxgZGk0ZEVoJAAAA8RgCABkAAACpFwABqRcBADAXFi4/AAAAUhcSAA4XHwD7FwEAbxhEAOIZSwCkGhkAAGBwgYwbAQCMHAEAnxoDAjAaGS9FAAAAjBoBADAaGTpGAAAAMBIZ9UcAAACkGk4AADTBhIwbAQCMHAEAjB0BAJ8aBAIwGhlzSAAAAKQaUQBQJPHEMBoZOUkAAACpGgEAMBoZ3koAAACfFwMCMBcWHkAAAAAwFRZ+QQAAAE0YABgKAAAATRcY6QsAAADwFx8AKAAAgE0XEaAqAAAA8BckACwAAABNGgAHAAAAAE0ZGoAnAAAATRoRoCoAAACHGBkaDhgOAE0bAAcAAAAATRobgCcAAABNGxGgKgAAAIcZGhtNGhFaCQAAAIcYGRpHGAMAAAAAAKkXAQBlAAEAxhcAADAXFuRSAAAAZQAJAE0YABgKAAAATRcY6QsAAADwFwQAJwAAgKkXAQAwFxbkUgAAAGoWDBCHGAwQTRcYTQcAAAAOFwEAUgkRAG4NLP8CAAAA+w0BAPsOAgDiD1QAjBAAADAQDxpTAAAApBBOAAA0wYRvEVUAbxJVAG8TVQCfEAQCMBAPDh0AAACkEBkAAGBwgYwRAQBvElYAnxADAjAQDw8PAAAApBAZAABgcIGMEQAAbxJXAJ8QAwIwEA/bEAAAAG8QGwAwEA8REQAAAIwQAAAwEA/MEgAAAIwQAAAwEA/eEwAAAIwQAAAwEA9eFAAAAOIQWwD7EQEAbxJcAOITXgCkFGAAADTxhYwVAACMFgQAnxQDAjAUE09dAAAAnxEDAjAREGpYAAAAqREAABwSCgCMEwAAYBMXABIAAAD7EQEA+xIGAOITZgCpFAEAMBQT6GEAAABvFGcAMBQTD2IAAACMFAgAMBQT02MAAAD7FAcAMBQT6BUAAAAwChMYKQAAADAME7dkAAAAMAsT3WUAAACfEQMCMBEQF1kAAACpEQAAHBIKAA0SbAAzAACA+xEBAPsSAgDiE2gAjBQBADAUExpTAAAA4hRrAPsVAQBvFkQA4hdLAKQYGQAAYHCBjBkBAG8abACfGAMCMBgXL0UAAACMGAEAMBgXOkYAAABNGgAYCgAAAE0ZGukLAAAA8BkDACcAAIBvGG0AZQABAG8YbgAwGBf1RwAAAKQYTgAANMGEjBkBAIwaAQCMGwEAnxgEAjAYF3NIAAAApBhRAFAk8cQwGBc5SQAAAKkYAQAwGBfeSgAAAJ8VAwIwFRS6aQAAAPsVAQD7FggA4hdxAKQYGQAAYHCBbxlyAG8aVQCfGAMCMBgXDw8AAACkGBkAAGBwgW8ZGwBvGhsAnxgDAjAYF9sQAAAApBh0AAA0MYdvGRsAbxobAJ8YAwIwGBcIbwAAAKQYYAAANPGFjBkAAIwaBACfGAMCMBgXb3AAAACkGHYAANTBhIwZ/wCMGpsAjBsZAJ8YBAIwGBcOHQAAAE0aABgKAAAATRka6QsAAADwGQMAJwAAgG8YdwBlAAEAbxh4ADAYF5ocAAAA2RgCABIAAAAwGBduHgAAAJ8VAwIwFRSsagAAAJ8RBAIwERAKWgAAAJ8NBAJSCA0AZQCVAE0LABgKAAAATQoL6QsAAADwCpAAeQAAgOIKewBNCwPoIAAAADALCkR6AAAA/wsAAAAAAABNDACjfAAAAMYNAADGDgAAZAwSAE0REIp9AAAADhEIAE0TAAcAAAAATRIT934AAABNExCKfQAAAIcREhMOEQcAnjQLBRAAAABSEgsAUhMQAKQRLwAAuNCCnxEDAW4M7f8CAAAA/wwAAAAAAABSDQsAxg4AAMYPAABkDRcA4hKCANkTAwASAAAAEgARADATEmB/AAAATRYABwAAAABNFRb3fgAAAE0WEVoJAAAAhxQVFioUAgABAAAAqRMAAakTAQAwExKWgAAAAFYTAQAwExKCgQAAAGoSDBBuDej/AgAAAPsNAQD7DgIA4g9UAIwQAAAwEA8aUwAAAKQQTgAANMGEbxFVAG8SVQBvE1UAnxAEAjAQDw4dAAAApBAZAABgcIGMEQEAbxJWAJ8QAwIwEA8PDwAAAKQQGQAAYHCBjBEAAG8SVwCfEAMCMBAP2xAAAABvEBsAMBAPEREAAACMEAAAMBAPzBIAAACMEAAAMBAP3hMAAACMEAAAMBAPXhQAAADiEIMA+xEBAG8SXADiE14ApBRgAAA08YWMFQAAjBYEAJ8UAwIwFBNPXQAAAJ8RAwIwERBqWAAAAPsRAQD7EgYA4hNmAKkUAQAwFBPoYQAAAIwUDAAwFBMPYgAAAIwUAQAwFBPTYwAAAPsUCQAwFBPoFQAAADALExgpAAAAMAwTt2QAAAAwChPdZQAAAJ8RAwIwERAXWQAAAJ8NBAJSCA0A/woAAAAAAAD/CwAAAAAAAE0NABgKAAAATQwN6QsAAADwDBMAKAAAgEcJEQAAAAAATQwJqysAAAAODA0A4g6EAG8PhQAwDw5aCQAAAG8PhgAwDw6aHAAAAJ40CwQOAAAAUg0LAKQMLwAAuNCCnwwDAeIOhABvD4cAMA8OWgkAAABvD4gAMA8OmhwAAACeNAsEDgAAAFINCwCkDC8AALjQgp8MAwFSDAsAxg0AAMYOAABkDD8ATREQWgkAAAD7EgEA+xMCAOIUFgCkFRkAAGBwgRwXCwDYFhoXjBcBAJ8VAwIwFRQPDwAAAKQVGQAAYHCBeBcPGhwYCwDsFhcYjBcAAJ8VAwIwFRTbEAAAAG8VGwAwFRQREQAAAG8VGwAwFRTMEgAAAG8VGwAwFRTeEwAAAG8VGwAwFRReFAAAAPsVCAAwFRToFQAAAOIViQCkFmAAADTxhYwXAACMGAQAnxYDAjAWFW9wAAAATRYQmhwAAAAwFhWaHAAAAE0WA+ggAAAAMBYVDh0AAADZFgQAEgAQABIAAAASAQn/MBYVbh4AAAAwFRQHAAAAAJ8SAwJqEgoRbgzA/wIAAADGDAAAxg0AAE0PABgKAAAATQ4P6QsAAADwDgcAKAAAAE0PABgKAAAATQ4P6QsAAADwDlYAJwAAgPsOAQD7DwIA4hCKAIwRAAAwERAaUwAAAKQRTgAANMGEbxJVAG8TVQBvFFUAnxEEAjAREA4dAAAApBEZAABgcIGMEgEAbxOLAJ8RAwIwERAPDwAAAKQRGQAAYHCBjBIAAG8TjACfEQMCMBEQ2xAAAACMEQAAMBEQEREAAACMEQAAMBEQ3hMAAACMEQAAMBEQXhQAAACMEQAAMBEQzBIAAADiEYMA+xIBAG8TXADiFF4ApBVgAAA08YWMFgAAjBcEAJ8VAwIwFRRPXQAAAJ8SAwIwEhFqWAAAAPsSAQD7EwYA4hSNAKkVAQAwFRToYQAAAIwVCAAwFRQPYgAAAIwVAQAwFRTTYwAAAPsVCgAwFRToFQAAAE0VAOAhAAAAMBUUGCkAAAAwBxTdZQAAADAFFLdkAAAAnxIDAjASERdZAAAAnw4EAlIMDgBNDQaaHAAAAGUABwBNDwAYCgAAAE0OD+kLAAAA8A4CAHkAAIBvDY4A+w4BAPsPAgDiEJEAbxGSADAREBpTAAAApBFOAAA0wYSMEgAAjBMAAIwUAACfEQQCMBEQDh0AAABNEgAHAAAAAE0REomPAAAAMBEQiY8AAABNEgAHAAAAAE0REsaQAAAAMBEQxpAAAACMEQAAMBEQEREAAACMEQAAMBEQzBIAAACMEQAAMBEQ3hMAAACMEQAAMBEQXhQAAADiEZcA+xIBAG8TkwDiFJkATRYABwAAAABNFRaJjwAAADAVFGmYAAAAnxIDAjASEYaTAAAA+xIBAG8TXADiFF4ApBVgAAA08YWMFgAAjBcEAJ8VAwIwFRRPXQAAAJ8SAwIwEhH0XAAAAPsSAQD7EwIA4hSaAIwVAQAwFRQaUwAAAKQVGQAAYHCBbxZXAIwXAQCfFQMCMBUUDw8AAABvFRsAMBUUXhQAAADiFZ0A+xYBAPsXAgDiGJ4AjBkBADAZGBpTAAAApBkZAABgcIGMGgEAbxtXAJ8ZAwIwGRgPDwAAAIwZAAAwGRgREQAAAIwZAAAwGRjeEwAAAIwZAAAwGRheFAAAAIwZAAAwGRjMEgAAAOIZnwD7GgEAbxtEAOIcowCMHQEAMB0cOkYAAACkHaQAADRxgW8epQCMHwAAbyClAIwhAACfHQUCMB0cL0UAAACkHaQAADRxgW8eGwCMHwAAbyAbAIwhAACfHQUCMB0cO6AAAACkHXQAADQxh28eGwBvHxsAnx0DAjAdHOihAAAAbx2mADAdHPVHAAAApB2oAKck8cQwHRw5SQAAAIwdAQAwHRyCogAAAKkdAQAwHRzeSgAAAKQddgAA1MGEjB7/AIwfygCMIAsAnx0EAjAdHHNIAAAA4h2qAPseAQBvH6kA4iCtAKQhTgAANMGEjCIAAIwjAACMJAAAnyEEAjAhIKSrAAAAjCEDADAhIBisAAAAnx4DAjAeHW2pAAAAnxoEAjAaGbppAAAAnxYEAjAWFbppAAAA+xYBAPsXAgDiGK4AjBkBADAZGBpTAAAApBkZAABgcIGMGgEAbxuvAJ8ZAwIwGRgPDwAAAKQZGQAAYHCBjBoAAG8bVwCfGQMCMBkY2xAAAACMGQAAMBkYEREAAACMGQAAMBkY3hMAAACMGQAAMBkYXhQAAACMGQAAMBkYzBIAAADiGbEA+xoBAPsbAgDiHLIAjB0BADAdHBpTAAAAbx0bADAdHN4TAAAAbx0bADAdHF4UAAAAbx0bADAdHBERAAAAbx0bADAdHMwSAAAAUh0EAJ8aBAIwGhkssAAAAJ8WBAIwFhXumwAAADAMFcCcAAAAnxIEAjASEQ2UAAAA+xIBAPsTAgDiFLMAjBUBADAVFBpTAAAApBUZAABgcIFvFrQAjBcBAJ8VAwIwFRQPDwAAAKQVGQAAYHCBbxZXAIwXAACfFQMCMBUU2xAAAABvFRsAMBUU3hMAAADiFbgA+xYBAPsXAgDiGJ4AjBkBADAZGBpTAAAApBkZAABgcIGMGgEAbxu5AJ8ZAwIwGRgPDwAAAIwZAAAwGRgREQAAAIwZAAAwGRjeEwAAAIwZAAAwGRheFAAAAG8ZGwAwGRjMEgAAAOIZuwD7GgEA+xsLAOIcvgCpHQEAMB0c6GEAAABNHgAHAAAAAE0dHp+8AAAAMB0cn7wAAABNHgAHAAAAAE0dHvS9AAAAMB0c9L0AAACfGgMCMBoZP7oAAACfFgQCMBYV/7UAAAD7FgEA+xcCAOIYigCMGQAAMBkYGlMAAABNGQPoIAAAADAZGA4dAAAApBkZAABgcIGMGgEAbxu5AJ8ZAwIwGRgPDwAAAKQZGQAAYHCBjBoAAG8buQCfGQMCMBkY2xAAAABvGRsAMBkYEREAAACMGQAAMBkY3hMAAACMGQAAMBkYXhQAAABvGRsAMBkYzBIAAADiGb8A+xoBAG8bXADiHF4ApB1gAAA08YWMHgAAjB8EAJ8dAwIwHRxPXQAAAJ8aAwIwGhlqWAAAAPsaAQD7GwIA4hxoAIwdAQAwHRwaUwAAAOIdnwD7HgEAbx9EAOIgwwCMIQEAMCEgOkYAAACMIQAAMCEgjsAAAACkIRkAAGBwgW8iGwBvIxsAnyEDAjAhIC9FAAAApCEZAABgcIGMIgAAbyMbAJ8hAwIwISA7oAAAAKQhdAAANDGHjCIAAG8jGwCfIQMCMCEg6KEAAAAwDSD1RwAAAKQhxQDEJPHEMCEgOUkAAABvIcYAMCEggqIAAACpIQEAMCEg3koAAACkIcgAxwTzxDAhIHvBAAAA+yIMAE0hIt7JAAAATSID6CAAAABvI8oAnyEDAjAhIHNIAAAAjCEEADAhIA3CAAAA4iGqAPsiAQBvI6kA4iStAKQlTgAANMGEjCYAAIwnAACMKAAAnyUEAjAlJKSrAAAAjCUBADAlJBisAAAAnyIDAjAiIW2pAAAAnx4EAjAeHbppAAAAnxoEAjAaGSywAAAAnxYEAjAWFTW2AAAAMAgVLrcAAACfEgQCMBIRZ5UAAACpEgAAHBMLAIwUAABgFE4AEwAAAPsSAQD7EwIA4hRUAG8VkgAwFRQaUwAAAKQVTgAANMGEjBYAAIwXAACMGAAAnxUEAjAVFA4dAAAApBUZAABgcIFvFssAbxdsAJ8VAwIwFRQPDwAAAKQVGQAAYHCBbxbMAIwXAQCfFQMCMBUU2xAAAACMFQEAMBUUEREAAACMFQAAMBUUzBIAAACMFQAAMBUU3hMAAACMFQAAMBUUXhQAAADiFc8A+xYBAG8XXADiGF4ApBlgAAA08YWMGgAAjBsEAJ8ZAwIwGRhPXQAAAJ8WAwIwFhXWzQAAAPsWAQD7FwIA4hjQAIwZAQAwGRgaUwAAAG8ZGwAwGRgREQAAAG8ZGwAwGRjMEgAAAG8ZGwAwGRjeEwAAAG8ZGwAwGRheFAAAAFIZCgCfFgQCMBYV084AAACfEgQCMBIRE5YAAACfDgQAwQkAAIIOAADRAQMCA3kDegN7A3wDfQM3A34FAQcDLAMVAzgDfwOAAQQAANBAAwsDDAOBAQOCAQODAQOEAQOFAQUIDxAREhMUFQADEwMhBABgcIECAAAAAAAA8D8CAAAAAAAA4D8DJQOGAQNuBQQcBx0eA1MDKwM0A4cBA4gBBQIkHgNSA1QDVwOJAQMyA4oBAzwDiwEDjAEEALjQggONAQOOAQUCMDECAAAAAAAAAAADjwEDkAEDkQEDkgEDkwEDlAEEAACQQwOVAQOWAQOXAQOYAQOZAQOaAQObAQUFHgc/QEEDNQMYAwkDCAMaAx8DGwMeBQZFRkdISUoDKQMUBAA0wYQDJgOcAQRQJPHEA50BA54BBQhTHQ8QERITFAKamZmZmZnJPwI0MzMzMzPrPwIzMzMzMzPDPwOfAQOgAQOhAQUDWFlaA6IBA6MBBQFdAxcEADTxhQOkAQOlAQOmAQOnAQOoAQUHYWJjFSlkZQIAAAAAAAAEQAUBUwMOA6kBBQJpagKamZmZmZm5PwOqAQOrAQOsAQMRBQcPEG9wHRweAjMzMzMzM9M/AyQEADQxhwNWBADUwYQDrQEDrgEDWQMWBQF6A20DZAOvAQMGAwMDEgUDf4ABgQEFAlhZBQIJHAN0A7ABA3gDsQEFBHAcHR4FCFMdDxARExQSAs3MzMzMzOQ/AmZmZmZmZtY/BQdhYmMVKWVkA7IBAyIDswEFCFMdjwGQARESExQCmpmZmZmZ6T8DtAEDtQEDtgEDtwEFBZMBXJQBlQGWAQO4AQUBmAEFA1MPFAO5AQO6AQUDaZsBnAEFBlMPERMUEgUBaQMKAxkDHAUJRkWgAaEBR0miAUpIBAA0cYECzczMzMzM7D8DuwEDvAEEpyTxxAO9AQUBqQEDvgEDvwEFAqsBrAEFB1MPEBETFBICmZmZmZmZyT8DwAEFAbABBQVTExQREgUEUw8QEwIzMzMzMzPrPwPBAQPCAQPDAQUDtQG2AbcBAjMzMzMzM7M/A8QBBQG6AQPFAQPGAQUDYbwBvQEFAliwAQPHAQMdA8gBBQxGwAFFoAGhAUdJogFKwQFIwgEDJwTEJPHEAmZmZmZmZuY/AygExwTzxAPJAQJmZmZmZmbmvwIAAAAAAADQPwIAAAAAAADYPwPKAQPLAQUCzQHOAQUFUxESExQFBgcICQroASoBCAAAAAAAAQIBAAAAAAABAAAAAAAAAQAAAAAAAAAABAABAQAAAAABAQAAAAAAAAAAAAAA/wMAAAAB+wAIAAAAAAAAAAAABgABAAAAAAEBAAAAAAEAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAEAAAEAAAEAAAEAAAEBAAAAAQAAAAEAAAABAAAAAPwA+AD+ABQAAQEAAAAAAQEAAAAAAAAAAAAAAP8DAAAAAfsACAAAAAAAAAAAAAEBAAAAAQAAAAMBAQAAAAAAAAAAAAAAAQABAAAAAAAAAgAAAAAAAwAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAABAAAAAC9AgAAAwAAAAIAAAAAAAAAAAAAAAAAAAAAAAAFAAAAAAAA6QAaAQAAAQAAAAIAAQAAAAEBAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAABAQAAAAAAAAACAAAAAAABAAAAAAAAAAEAAAAAAAEBAQAAAAAAAAAAAAAA/gAAAAYAAAAAAAEAAAAAAQAAAAAAAAEBAAAAAA8AAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAEAAAAAAQAAAAAAAAEAAAEAAQAAAAAAAAABAAAAAQAA+gAACAACAAAAAAABAAAABAAAAAAAAAABAAAAAAAAAAAAAAABAAH9AAAFAAAAAAABAAAC4gAAAAHAAEMAAAEAAAEAAAAAAAAAAQAAAAAAAAEAAAAAAAABAAABAAABAAABAAABAQAAAQAAAAAAAP8AAAMAAAAAAAAAAQAAAQAAAQAAAQAAAQABAAEA+QAACQAAAAAAAAEAAAEBAAABAAAAAAAAAQAAAQAAAAAAAQAB/gADAAAAAAAAAAEAAAABAAD4AAAKAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAEAAAD5AADzAADqAAA4AAAAAAABAQAAAAIAAQAAAAABAAAAAAAAAAAAAAEAAAAAAAD+AAUAAQAAAAEBAAAAAIAAAAAAAAAAAAAAAAABAAD4/wAMAAABAAABAAAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAQAAAQAAAQAAAQEAAAEAAAAAAAD/AAADAAABAAABAAABAAABAAABAAEAAQD5AADzAEAAAQACAAAAAAAAAAAAAAEBAAABAAAAAAD+AAAFAQAAAQAAAAAA/gAABAAAAAEAAAAAAQAAAAAAAAABAAAAAAAAAAABAAABAAABAAABAAABAAABAQAAAAAAAAEAAAABAAAAAQAAAAAA/AD4AP8AHAEBAAAAAAAAAAAAAAABAAABAAABAAAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAQCIAQAAAQAAAQEAAAEAAAAAAAD/AAADAAABAAABAAABAAABAAABAAAAAQABAPkAAPMAGAAAAQAAAAAAAQIAAAEAAAEAAAAAAAAAAQAAAAAAAQAAAAAAAQAAAQAAAQAAAQAAAQEAAAEAAAAAAP8AAAMAAAEAAAAAAAD/AAADAAABAAABAAAAAAAAAQAAAQEAAAEAAAEAAAAAAAABAAABAAABAAABAAABAQAAAQAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAEAAAABAAABAAABAAAAAAAAAAEBAAABAAAAAAAAAAEAAP4AAPUAAPgAABkAAAEAAAEAAAAAAAAB1AAAAAAAAQAAAQAAAQAAAQAAAQEAAAEAAAEAAAEAAAEAAAEAAAH6AAD3AAARANEAADEAAAEAAAEAAAAAAAABAAAAAAAAAQAAAQEAAAEAAAEAAAAAAAABAAABAAABAAABAAABAQAAAQAAAQAAAAAAAQAAAAAA/QAA+AAADgAAAQAAAgAAAAEAAAAAAAABAAAAAAAAAQAAAQAAAQAAAQAAAQEAAAEAAAAAAAD/AAADAAABAAABAQAAAQAAAQAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQABAAAAAQAAAQAAAQAAAAEAAAAAAAAAAAEAAAEBAAABAAAAAAAAAAEAAP4AAAIAAP0AAPIAACYAxgAAPAAAAAAAAAABAAABAAAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAQAAAQAAAQAAAQEAAAEAAAAAAAD/AAADAAABAAABAAABAAABAAABAAAB+gAA8wAAgwAA6QAAAEMAAAAfAAAAhgAAAHgAAAAsAAAA8P///wAEAgAAAAAi4gIIAE0DAAoAAAAAMAMCCgAAAABNAwCfAQAAADADAp8BAAAATQMAGAIAAAAwAwIYAgAAAE0DAKADAAAAMAMCoAMAAABNAwCABAAAADADAoAEAAAATQMALgUAAAAwAwIuBQAAAE0DAPkGAAAAMAMC+QYAAABNAwD3BwAAADADAvcHAAAAggICAAkDegPFAQOJAQN5A1QDmQEDjwEDrwEFCAABAgMEBQYHAPkFAAEYAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAPoCAAAABAEBAAAGAwAABQEED/sBAADiAgMAbwMEADADAnEAAAAATQMABgEAAAAwAwIGAQAAAE0DAL8CAAAAMAMCvwIAAACfAQIBggABAAUDzAEDOQM6BQMAAQIDMQCGBjEBGAAAAQAAAQAAAAEAAAD9BQcDAAAABAEBAAAGAwAABQEEC/sBAADiAgIAbwMDADADAnEAAAAATQMAoAEAAAAwAwKgAQAAAJ8BAgGCAAEABAPMAQMyBQIAAQMzAI0GMwEYAAABAAABAAAA/gQOAwAAAAUCAQAABwQAAAUCAw8L+wIAAOIDAwBvBAQAMAQDcQAAAAAwAANKAQAAADABA8wCAAAAnwICAYIAAQAFA8wBA80BAwEFAwABAgNxAJMGcQEYAAABAAABAAEA/QUUAwAAAAMBAAAAAA7iAQMA2QIAABIAAAAwAgF0AAAAANkCAQASAAAAMAIBRAEAAADZAgIAEgAAADACAWUCAAAAggECAAQDMQMzA3EFAwABAgMNDg+EBgABGAABAAAABwAAAAYAAAAABQMAAAAVAAABAgCiAaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQEAAAAAQG8DBAC8AQEWAwAAAJ8BAwKkAgYAAABQQE0EAcEHAAAATQMELggAAACfAgICpAMGAAAAUEBNBQEtCQAAAE0EBfAKAAAAnwMCAqQEBgAAAFBApAcMAAAAsEBNBgckDQAAAE0FBqMOAAAAnwQCAqQFBgAAAFBATQYBIQ8AAACfBQICTQYFyhAAAACkBwYAAABQQE0JAS0JAAAATQgJ1REAAACfBwICpAgGAAAAUEBNCwEoEgAAAE0KC1wTAAAATQkKnBQAAACfCAICpAkGAAAAUEBNDAEoEgAAAE0LDFwTAAAATQoLJBUAAACfCQICpAoGAAAAUEBNCwEtFgAAAJ8KAgKkCwYAAABQQE0OASIXAAAATQ0OXBMAAABNDA32GAAAAJ8LAgKkDAYAAABQQE0OAaEZAAAATQ0OMxoAAACfDAICpA0GAAAAUEBNDwG7GwAAAE0OD1McAAAAnw0CAqQOBgAAAFBApBEMAAAAsEBNEBEkDQAAAE0PEHgdAAAAnw4CAqQPBgAAAFBApBIMAAAAsEBNERIkDQAAAE0QEf4eAAAAnw8CAk0QBfgfAAAAbxIgALwQEJwhAAAAnxADAsARIgAwERATIwAAAMARJAASAAYAEgADADAREIAlAAAATREFiCYAAABvEycAvBERnCEAAACfEQMCwBIoABIABQAwEhETIwAAAMASKQASAAAAEgAGABIABwASAA8AEgACABIADQASAAsAEgAJABIABAASABAAEgAOABIACAASAAwAMBIRgCUAAABNEgrnKgAAAMATKwDAFCwAnxIDAlITEQCfEgIAghIAAC0DzgEEAAAAQAPPAQPQAQPRAQPSAQQAAFBAA9MBA9QBA9UBA9YBA9cBBAAAsEAD2AED2QED2gED2wED3AED3QED3gED3wED4AED4QED4gED4wED5AED5QED5gED5wED6AED6QED6gED6wED7AEGAAMFBgIDKgPtAQPuAQYFBgsD7wEGDAYQBgACBQsMEAEAAQEAAf8AAAAAAf8AAAAAAf8AAAAAAAAAAAAAAAAB/wAAAAAAAAAAAAAAAAH/Av4AAAAAAAAAAAAAAAAAAAH/AAAAAAAAAAAAAAAAAf8AAAAAAAAAAAAAAAAAAAH/AAAAAAAAAAAAAAAAAAAB/wAAAAAAAAAAAAAAAAAAAAAF+wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC/Ui3gABAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAABAAAAAAAAAAUAAAAAAAAALAAAAAAAAAAAAAAAAQAAAAAAAACYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABECAAAAAAAAAAAAACIAAAAAEWNJu4KpFHP4UY3RFrQn/bXvhjWtsZLeAaT8mqhJLAvgALMcadIB4KM=

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players")
local v2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v2.App.ItemUtils)
local v_u_4 = require(v2.EzUi.Checkbox)
local v_u_5 = require(script.Parent.ButtonComponent)
local v_u_6 = require(v2.Roact)
local v_u_7 = v_u_6.createElement
local v_u_8 = require(v2.EzUi.PaddedContainer)
local v_u_9 = require(v2.Garage.UI.CashBar)
local v_u_10 = require(v2.Garage.UI.CustomizeItem)
local v11 = require(v2.RoactRodux)
local v_u_12 = require(v2.Safes.UI.paddedScrollingGrid)
local v_u_13 = require(v2.Std.ColorUtils)
local v_u_14 = require(v2.Trade.CreatorValues)
local v_u_15 = require(script.Parent.CategoryButtonComponent)
local v_u_16 = require(script.Parent.PageButtonComponent)
local v_u_17 = v_u_6.PureComponent:extend("SettingItem")
function v_u_17.init(p18)
	p18:setState({
		["value"] = p18.props.defaultValue
	})
end
function v_u_17.render(p_u_19)
	-- upvalues: (copy) v_u_7, (copy) v_u_4
	local v20 = v_u_7
	local v21 = {
		["BackgroundTransparency"] = 1,
		["Size"] = p_u_19.props.size,
		["Position"] = p_u_19.props.position
	}
	local v23 = {
		["Value"] = v_u_7(v_u_4, {
			["size"] = UDim2.new(1, 0, 1, 0),
			["value"] = p_u_19.state.value,
			["onChecked"] = function(p22)
				-- upvalues: (copy) p_u_19
				p_u_19:setState({
					["value"] = p22
				})
				if p_u_19.props.onChecked then
					p_u_19.props.onChecked(p22)
				end
			end,
			["layoutOrder"] = 1,
			["checkColor"] = p_u_19.props.color,
			["cornerRadius"] = UDim.new(0, 4),
			["disabled"] = p_u_19.props.disabled
		}),
		["Title"] = v_u_7("TextLabel", {
			["BackgroundTransparency"] = 1,
			["Size"] = UDim2.fromScale(1 - (1 / p_u_19.props.aspectRatio + p_u_19.props.paddingRatio / p_u_19.props.aspectRatio), 0.8),
			["AnchorPoint"] = Vector2.new(0, 0.5),
			["Position"] = UDim2.fromScale(1 / p_u_19.props.aspectRatio + p_u_19.props.paddingRatio / p_u_19.props.aspectRatio, 0.5),
			["Text"] = p_u_19.props.title,
			["Font"] = Enum.Font.LuckiestGuy,
			["LineHeight"] = 0.7,
			["TextXAlignment"] = Enum.TextXAlignment.Left,
			["TextScaled"] = true,
			["TextColor3"] = Color3.new(1, 1, 1),
			["LayoutOrder"] = 2
		})
	}
	return v20("Frame", v21, v23)
end
local v24 = v_u_6.Component:extend("HomeApp")
function v24.init(p_u_25)
	-- upvalues: (copy) v_u_6
	p_u_25.categories = {
		{
			["name"] = "floorFurniture",
			["title"] = "Floor Furniture",
			["module"] = "HomeItem",
			["upDot"] = 1,
			["use"] = 1
		},
		{
			["name"] = "wallFurniture",
			["title"] = "Wall Furniture",
			["module"] = "HomeItem",
			["upDot"] = 0,
			["use"] = 1
		},
		{
			["name"] = "ceilingFurniture",
			["title"] = "Ceiling Furniture",
			["module"] = "HomeItem",
			["upDot"] = -1,
			["use"] = 1
		},
		{
			["name"] = "defense",
			["title"] = "Defense",
			["module"] = "HomeItem",
			["use"] = 2
		},
		{
			["name"] = "wallColor",
			["title"] = "Wall Color",
			["module"] = "WallColor"
		},
		{
			["name"] = "secondWallColor",
			["title"] = "Second Wall Color",
			["module"] = "SecondWallColor"
		},
		{
			["name"] = "floorMaterial",
			["title"] = "Floor Material",
			["module"] = "FloorMaterial"
		},
		{
			["name"] = "floorColor",
			["title"] = "Floor Color",
			["module"] = "FloorColor"
		},
		{
			["name"] = "windowColor",
			["title"] = "Window Color",
			["module"] = "WindowColor"
		},
		{
			["name"] = "windowTint",
			["title"] = "Window Tint",
			["module"] = "WindowTint"
		}
	}
	function p_u_25.categoryOnClick(p26)
		-- upvalues: (copy) p_u_25, (ref) v_u_6
		local v27 = p_u_25.categories[p26]
		if v27.name == "floorFurniture" or (v27.name == "wallFurniture" or (v27.name == "ceilingFurniture" or v27.name == "defense")) then
			p_u_25.props.setFurnitureCategory(v27)
		elseif v27.module then
			p_u_25.props.setCategory(v27)
		end
		p_u_25:setState({
			["categoryName"] = v27.name,
			["selectedName"] = v_u_6.None
		})
	end
	p_u_25.pages = {
		{
			["name"] = "inventory",
			["title"] = "INVENTORY",
			["bgColor"] = Color3.fromRGB(255, 202, 11)
		},
		{
			["name"] = "store",
			["title"] = "STORE",
			["bgColor"] = Color3.fromRGB(255, 155, 25)
		},
		{
			["name"] = "settings",
			["title"] = "SETTINGS",
			["bgColor"] = Color3.fromRGB(255, 112, 25)
		}
	}
	function p_u_25.pageOnClick(p28)
		-- upvalues: (copy) p_u_25, (ref) v_u_6
		p_u_25:setState({
			["pageName"] = p_u_25.pages[p28].name,
			["selectedName"] = v_u_6.None
		})
	end
	local v29 = p_u_25.categories[1]
	p_u_25:setState({
		["pageName"] = "inventory",
		["categoryName"] = v29.name,
		["selectedName"] = v_u_6.None
	})
	p_u_25.props.setFurnitureCategory(v29)
	p_u_25.settingItems = {
		{
			["name"] = "entryAllowFriends",
			["title"] = "ENTRY: ALLOW FRIENDS"
		},
		{
			["name"] = "entryAllowCrew",
			["title"] = "ENTRY: ALLOW CREW"
		},
		{
			["name"] = "entryAllowTeam",
			["title"] = "ENTRY: ALLOW TEAM"
		},
		{
			["name"] = "entryAllowEveryone",
			["title"] = "ENTRY: ALLOW EVERYONE"
		},
		{
			["name"] = "editingAllowFriends",
			["title"] = "EDITING: ALLOW FRIENDS",
			["requires"] = "entryAllowFriends"
		},
		{
			["name"] = "editingAllowCrew",
			["title"] = "EDITING: ALLOW CREW",
			["requires"] = "entryAllowCrew"
		},
		{
			["name"] = "editingAllowTeam",
			["title"] = "EDITING: ALLOW TEAM",
			["requires"] = "entryAllowTeam"
		},
		{
			["name"] = "editingAllowEveryone",
			["title"] = "EDITING: ALLOW EVERYONE",
			["requires"] = "entryAllowEveryone"
		}
	}
end
function v24.render(p_u_30)
	-- upvalues: (copy) v_u_1, (copy) v_u_7, (copy) v_u_8, (copy) v_u_16, (copy) v_u_3, (copy) v_u_14, (copy) v_u_12, (copy) v_u_10, (copy) v_u_5, (copy) v_u_17, (copy) v_u_15, (copy) v_u_9, (copy) v_u_13
	if not p_u_30.props.visible then
		return
	end
	local v31
	if p_u_30.props.home == nil then
		v31 = false
	else
		v31 = p_u_30.props.home:GetOwnerId() == v_u_1.LocalPlayer.UserId
	end
	local v32 = {}
	local v33 = nil
	for v34, v35 in p_u_30.pages do
		v32[v34] = {
			["selected"] = v35.name == p_u_30.state.pageName
		}
		if v32[v34].selected then
			v33 = v35
		end
	end
	local v36 = v33 ~= nil
	assert(v36, "selectedPage must not be nil")
	local v37 = {}
	for v_u_38, v39 in p_u_30.pages do
		local v40 = v32[v_u_38]
		v37[v39.name] = v_u_7(v_u_8, {
			["size"] = UDim2.fromScale(1, 1 / #p_u_30.pages),
			["position"] = UDim2.fromScale(0, (v_u_38 - 1) / #p_u_30.pages),
			["paddingTop"] = 0.5,
			["paddingBottom"] = 0.5,
			["paddingLeft"] = 0.5,
			["paddingRight"] = 0.5,
			["component"] = v_u_16,
			["props"] = {
				["title"] = v39.title,
				["selected"] = v40.selected,
				["backgroundColor"] = v39.bgColor,
				["onClick"] = function()
					-- upvalues: (copy) p_u_30, (copy) v_u_38
					p_u_30.pageOnClick(v_u_38)
				end
			}
		})
	end
	local v41 = {}
	local v42 = nil
	for v43, v44 in p_u_30.categories do
		v41[v43] = {
			["selected"] = v44.name == p_u_30.state.categoryName
		}
		if v41[v43].selected then
			v42 = v44
		end
	end
	local v45 = v42 ~= nil
	assert(v45, "selectedCategory must not be nil")
	local v46 = {
		["selectedBgColor"] = v33.bgColor,
		["onClick"] = p_u_30.categoryOnClick
	}
	local v47 = nil
	local v_u_48 = nil
	if p_u_30.state.pageName ~= "inventory" and p_u_30.state.pageName ~= "store" then
		if p_u_30.state.pageName == "settings" then
			local v49 = {
				["color"] = v33.bgColor
			}
			local v50 = {}
			for _, v51 in p_u_30.settingItems do
				if not v51.requires or p_u_30.props.savedSettings[v51.requires] then
					table.insert(v50, v51)
				end
			end
			local v52 = {}
			for v53, v_u_54 in v50 do
				v52[v53] = {
					["onChecked"] = function(p55)
						-- upvalues: (copy) p_u_30, (copy) v_u_54
						p_u_30.props.setSavedSetting(v_u_54.name, p55)
						if p_u_30.props.onSettingChanged then
							p_u_30.props.onSettingChanged(v_u_54.name, p55)
						end
					end,
					["defaultValue"] = p_u_30.props.savedSettings[v_u_54.name] == true,
					["disabled"] = not v31
				}
			end
			v47 = v_u_7(v_u_8, {
				["backgroundTransparency"] = 0,
				["backgroundColor"] = Color3.new(0.2, 0.2, 0.2),
				["size"] = UDim2.fromScale(1, 0.8500000000000001),
				["position"] = UDim2.fromScale(0, 0.15),
				["paddingTop"] = 0.5,
				["paddingBottom"] = 0,
				["paddingLeft"] = 0,
				["paddingRight"] = 0
			}, {
				["Corner"] = v_u_7("UICorner", {
					["CornerRadius"] = UDim.new(0, 4)
				}),
				["Scrolling"] = v_u_7(v_u_12, {
					["exposePaddedContainerProps"] = true,
					["rowsPerPage"] = 12,
					["colsPerRow"] = 1,
					["component"] = v_u_17,
					["items"] = v50,
					["metadata"] = v52,
					["itemDefaults"] = v49
				})
			})
		end
		::l90::
		local v56 = {}
		local v57 = {}
		if p_u_30.state.pageName == "store" and (v_u_48 ~= nil and v_u_48.available) then
			table.insert(v57, {
				["name"] = "purchase",
				["title"] = "BUY"
			})
		end
		table.insert(v57, {
			["name"] = "exit",
			["title"] = "EXIT"
		})
		for v58, v_u_59 in v57 do
			v56[v_u_59.name] = v_u_7(v_u_8, {
				["size"] = UDim2.fromScale(1 / #v57, 1),
				["position"] = UDim2.fromScale((v58 - 1) / #v57, 0),
				["paddingTop"] = 0.5,
				["paddingBottom"] = 0.5,
				["paddingLeft"] = 0.5,
				["paddingRight"] = 0.5,
				["component"] = v_u_5,
				["props"] = {
					["cornerRadius"] = UDim.new(0, 4),
					["title"] = v_u_59.title,
					["backgroundColor"] = v33.bgColor,
					["onClick"] = function()
						-- upvalues: (copy) v_u_59, (copy) p_u_30, (ref) v_u_48
						if v_u_59.name == "place" then
							p_u_30.props.attemptPlaceItem(v_u_48)
							return
						elseif v_u_59.name == "purchase" then
							p_u_30.props.attemptPurchaseItem(v_u_48)
							return
						elseif v_u_59.name == "delete" then
							p_u_30.props.attemptDeleteItem()
						elseif v_u_59.name == "exit" then
							p_u_30.props.exit()
						end
					end
				}
			})
		end
		local v60 = nil
		local v61 = nil
		if p_u_30.state.pageName == "store" or p_u_30.state.pageName == "inventory" then
			v60 = v_u_7(v_u_8, {
				["backgroundTransparency"] = 0,
				["backgroundColor"] = Color3.new(0.2, 0.2, 0.2),
				["size"] = UDim2.fromScale(1, 0.65),
				["position"] = UDim2.fromScale(0, 0.35),
				["paddingTop"] = 0,
				["paddingLeft"] = 0,
				["paddingRight"] = 0,
				["paddingBottom"] = 0
			}, {
				["Corner"] = v_u_7("UICorner", {
					["CornerRadius"] = UDim.new(0, 4)
				}),
				["Scrolling"] = v_u_7(v_u_12, {
					["exposePaddedContainerProps"] = true,
					["rowsPerPage"] = 8,
					["colsPerRow"] = 1,
					["component"] = v_u_15,
					["items"] = p_u_30.categories,
					["itemDefaults"] = v46,
					["metadata"] = v41
				})
			})
			v61 = v42.title
		elseif p_u_30.state.pageName == "settings" then
			v61 = "Settings"
		end
		local v62 = v_u_7
		local v63 = v_u_8
		local v64 = {
			["backgroundTransparency"] = 0.8,
			["backgroundColor"] = Color3.new(0, 0, 0),
			["aspectRatio"] = p_u_30.props.aspectRatio,
			["verticalPaddingRatio"] = p_u_30.props.verticalPaddingRatio,
			["paddingTop"] = 0,
			["paddingBottom"] = 0,
			["paddingLeft"] = 0,
			["paddingRight"] = 0
		}
		local v65 = {
			["UIAspectRatioConstraint"] = v_u_7("UIAspectRatioConstraint", {
				["AspectRatio"] = p_u_30.props.aspectRatio
			}),
			["UICorner"] = v_u_7("UICorner", {
				["CornerRadius"] = UDim.new(0, 4)
			}),
			["Sidebar"] = v_u_7(v_u_8, {
				["backgroundTransparency"] = 1,
				["size"] = UDim2.fromScale(0.15, 1),
				["paddingRight"] = 0.5
			}, {
				["Title"] = v_u_7(v_u_8, {
					["backgroundTransparency"] = 1,
					["size"] = UDim2.fromScale(1, 0.15),
					["paddingTop"] = 0,
					["paddingLeft"] = 0,
					["paddingRight"] = 0,
					["paddingBottom"] = 0
				}, {
					["Title"] = v_u_7("TextLabel", {
						["BackgroundTransparency"] = 1,
						["Size"] = UDim2.new(0.9, 0, 0.9, 0),
						["Position"] = UDim2.new(0.5, 0, 0.5, 0),
						["AnchorPoint"] = Vector2.new(0.5, 0.5),
						["Text"] = "HOME",
						["Font"] = Enum.Font.Bangers,
						["LineHeight"] = 1,
						["TextScaled"] = true,
						["TextColor3"] = Color3.fromRGB(255, 202, 11)
					}, {
						["UIStroke"] = v_u_7("UIStroke", {
							["Color"] = Color3.new(0, 0, 0),
							["Thickness"] = 3
						})
					})
				}),
				["Pages"] = v_u_7(v_u_8, {
					["backgroundTransparency"] = 1,
					["size"] = UDim2.fromScale(1, 0.19999999999999998),
					["position"] = UDim2.fromScale(0, 0.15),
					["paddingTop"] = 0,
					["paddingLeft"] = 0,
					["paddingRight"] = 0,
					["paddingBottom"] = 0
				}, {
					["Inner"] = v_u_7(v_u_8, {
						["backgroundTransparency"] = 1,
						["paddingLeft"] = 0.5,
						["paddingRight"] = 0.5,
						["paddingTop"] = 0.5,
						["paddingBottom"] = 0.5
					}, v37)
				}),
				["Categories"] = v60
			}),
			["Body"] = v_u_7(v_u_8, {
				["backgroundTransparency"] = 1,
				["size"] = UDim2.fromScale(0.85, 1),
				["position"] = UDim2.fromScale(0.15, 0),
				["paddingLeft"] = 0.5
			}, {
				["Cash"] = v_u_7(v_u_8, {
					["backgroundTransparency"] = 1,
					["size"] = UDim2.fromScale(1, 0.075),
					["paddingTop"] = 0,
					["paddingLeft"] = 0,
					["paddingRight"] = 0,
					["paddingBottom"] = 0.5
				}, {
					["Bar"] = v_u_7(v_u_9, {
						["exposePaddedContainerProps"] = true,
						["cash"] = p_u_30.props.cash,
						["promptCashPurchase"] = p_u_30.props.promptCashPurchase
					})
				}),
				["CategoryTitle"] = v_u_7(v_u_8, {
					["backgroundTransparency"] = 0,
					["backgroundColor"] = v33.bgColor,
					["size"] = UDim2.fromScale(1, 0.075),
					["position"] = UDim2.fromScale(0, 0.075),
					["paddingTop"] = 0.5,
					["paddingLeft"] = 0,
					["paddingRight"] = 0,
					["paddingBottom"] = 0.5
				}, {
					["Corner"] = v_u_7("UICorner", {
						["CornerRadius"] = UDim.new(0, 4)
					}),
					["Inner"] = v_u_7(v_u_8, {
						["backgroundTransparency"] = 1
					}, {
						["Title"] = v_u_7("TextLabel", {
							["BackgroundTransparency"] = 1,
							["BorderSizePixel"] = 0,
							["Size"] = UDim2.fromScale(0.5, 0.5),
							["Position"] = UDim2.fromScale(0, 0.5),
							["AnchorPoint"] = Vector2.new(0, 0.5),
							["Text"] = v61,
							["Font"] = Enum.Font.LuckiestGuy,
							["LineHeight"] = 0.7,
							["TextScaled"] = true,
							["TextXAlignment"] = Enum.TextXAlignment.Left,
							["TextColor3"] = v_u_13.saturateBy(v33.bgColor, -0.7),
							["ZIndex"] = 4
						}, {
							["UIStroke"] = v_u_7("UIStroke", {
								["Color"] = Color3.new(0, 0, 0),
								["Thickness"] = 1
							})
						})
					})
				}),
				["GridContainer"] = v47
			})
		}
		local v66
		if #v57 > 0 then
			v66 = v_u_7(v_u_8, {
				["backgroundTransparency"] = 0.8,
				["backgroundColor"] = Color3.new(0, 0, 0),
				["size"] = UDim2.fromScale(0.25, 0.1),
				["position"] = UDim2.fromScale(0.375, 1),
				["paddingTop"] = 1,
				["paddingBottom"] = 0,
				["paddingLeft"] = 0,
				["paddingRight"] = 0
			}, {
				["Corners"] = v_u_7("UICorner", {
					["CornerRadius"] = UDim.new(0, 4)
				}),
				["Buttons"] = v_u_7(v_u_8, {
					["backgroundTransparency"] = 1,
					["paddingTop"] = 0.5,
					["paddingBottom"] = 0.5,
					["paddingLeft"] = 0.5,
					["paddingRight"] = 0.5
				}, v56)
			})
		else
			v66 = false
		end
		v65.Bottom = v66
		return v62(v63, v64, v65)
	end
	local v67 = {}
	for _, v68 in p_u_30.props.items do
		if p_u_30.state.pageName == "inventory" then
			if p_u_30.props.inventory[v68.module] and (p_u_30.props.inventory[v68.module][v68.name] and p_u_30.props.inventory[v68.module][v68.name] > 0) then
				::l40::
				table.insert(v67, v68)
			end
		elseif p_u_30.state.pageName ~= "store" or v68.available and (v68.module == "HomeItem" or not (p_u_30.props.inventory[v68.module] and p_u_30.props.inventory[v68.module][v68.name])) then
			goto l40
		end
	end
	local v69 = {
		["canFavorite"] = false,
		["accentColor"] = v33.bgColor
	}
	local v70 = {}
	for v71, v_u_72 in v67 do
		local v73 = nil
		if v_u_72.module == "HomeItem" then
			local v74 = p_u_30.props.inventory[v_u_72.module] == nil and 0 or (p_u_30.props.inventory[v_u_72.module][v_u_72.name] or 0)
			local v75 = p_u_30.props.quantityPlaced[v_u_72.name] or 0
			if p_u_30.state.pageName == "inventory" then
				v73 = ("%d/%d"):format(v74 - v75, v74)
			elseif p_u_30.state.pageName == "store" then
				local v76 = "%d/%s"
				local v77
				if v_u_72.maxPlaced == nil then
					v77 = "\226\136\158"
				else
					local v78 = v_u_72.maxPlaced
					v77 = tostring(v78)
				end
				v73 = v76:format(v74, v77)
			end
		end
		local v79 = v_u_3.createHomeItemItemTable(v_u_72.name)
		local v80 = v_u_3.getFullNameFromTable(v79)
		local v81 = v_u_14[v80]
		if v81 then
			v81 = v_u_14[v80].CreatorName
		end
		local v82 = {
			["onClick"] = function()
				-- upvalues: (copy) p_u_30, (copy) v_u_72
				p_u_30:setState({
					["selectedName"] = v_u_72.name
				})
				if p_u_30.state.pageName == "inventory" then
					p_u_30.props.attemptPlaceItem(v_u_72)
				elseif p_u_30.state.pageName == "store" then
					p_u_30.props.attemptPreviewItem(v_u_72)
				end
			end,
			["selected"] = v_u_72.name == p_u_30.state.selectedName,
			["equipped"] = p_u_30.props.equipped[v_u_72.module] == v_u_72.name
		}
		if v73 then
			v73 = v_u_7("TextLabel", {
				["Size"] = UDim2.fromScale(1, 1),
				["BackgroundTransparency"] = 1,
				["Text"] = v73,
				["TextColor3"] = Color3.new(1, 1, 1),
				["Font"] = Enum.Font.FredokaOne,
				["TextScaled"] = true
			})
		end
		v82.customComponent = v73
		v82.creatorName = v81
		if p_u_30.state.pageName == "store" then
			if v_u_72.module ~= "HomeItem" then
				v82.owned = p_u_30.props.inventory[v_u_72.module] and p_u_30.props.inventory[v_u_72.module][v_u_72.name] ~= nil and true or nil
			end
		elseif p_u_30.state.pageName == "inventory" then
			v82.owned = true
		end
		v70[v71] = v82
		if v70[v71].selected then
			v_u_48 = v_u_72
		end
	end
	local v83 = v_u_7
	local v84 = v_u_8
	local v85 = {
		["backgroundTransparency"] = 0,
		["backgroundColor"] = Color3.new(0.2, 0.2, 0.2),
		["size"] = UDim2.fromScale(1, 0.8500000000000001),
		["position"] = UDim2.fromScale(0, 0.15),
		["paddingTop"] = 0.5,
		["paddingBottom"] = 0,
		["paddingLeft"] = 0,
		["paddingRight"] = 0
	}
	local v86 = {
		["Corner"] = v_u_7("UICorner", {
			["CornerRadius"] = UDim.new(0, 4)
		})
	}
	local v87
	if #v67 > 0 then
		v87 = v_u_7(v_u_12, {
			["exposePaddedContainerProps"] = true,
			["rowsPerPage"] = 2.5,
			["colsPerRow"] = 8,
			["component"] = v_u_10,
			["items"] = v67,
			["metadata"] = v70,
			["itemDefaults"] = v69
		})
	else
		v87 = false
	end
	v86.Scrolling = v87
	local v88
	if #v67 == 0 then
		v88 = v_u_7(v_u_8, {
			["backgroundTransparency"] = 1
		}, {
			["Title"] = v_u_7("TextLabel", {
				["Size"] = UDim2.fromScale(1, 0.1),
				["BackgroundTransparency"] = 1,
				["Text"] = p_u_30.state.pageName == "inventory" and "You don\'t have any of these.. check out the store!" or "No more items to buy.. check your inventory!",
				["TextColor3"] = Color3.new(1, 1, 1),
				["Font"] = Enum.Font.FredokaOne,
				["TextScaled"] = true
			}),
			["Button"] = v_u_7(v_u_5, {
				["size"] = UDim2.fromScale(0.3, 0.2),
				["position"] = UDim2.fromScale(0.5, 0.5),
				["anchorPoint"] = Vector2.new(0.5, 0.5),
				["cornerRadius"] = UDim.new(0, 4),
				["backgroundColor"] = Color3.fromRGB(255, 155, 25),
				["title"] = p_u_30.state.pageName == "inventory" and "Store" or "Inventory",
				["onClick"] = function()
					-- upvalues: (copy) p_u_30
					if p_u_30.state.pageName == "inventory" then
						p_u_30:setState({
							["pageName"] = "store"
						})
					else
						p_u_30:setState({
							["pageName"] = "inventory"
						})
					end
				end
			})
		})
	else
		v88 = false
	end
	v86.Help = v88
	v47 = v83(v84, v85, v86)
	goto l90
end
return v11.connect(function(p89, _)
	return {
		["home"] = p89.home,
		["cash"] = p89.cash,
		["items"] = p89.items,
		["visible"] = p89.visible,
		["inventory"] = p89.inventory,
		["equipped"] = p89.equipped,
		["quantityPlaced"] = p89.quantityPlaced,
		["savedSettings"] = p89.savedSettings
	}
end, function(p_u_90)
	return {
		["setFurnitureCategory"] = function(p91)
			-- upvalues: (copy) p_u_90
			p_u_90({
				["type"] = "setFurnitureCategory",
				["upDot"] = p91.upDot,
				["use"] = p91.use
			})
		end,
		["setCategory"] = function(p92)
			-- upvalues: (copy) p_u_90
			p_u_90({
				["type"] = "setCategory",
				["module"] = p92.module
			})
		end,
		["setSavedSetting"] = function(p93, p94)
			-- upvalues: (copy) p_u_90
			p_u_90({
				["type"] = "setSavedSetting",
				["key"] = p93,
				["value"] = p94
			})
		end
	}
end)(v24)
