-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMOBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplCFRBR19OQU1FEEZJUkVfUkVNT1RFX05BTUUSREFNQUdFX1JFTU9URV9OQU1FBkRBTUFHRQ1EYXJ0RGlzcGVuc2VyCERhcnRGaXJlCkRhcnREYW1hZ2UAAQUAAAECAB+jAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CAxgHAAAAnwECAk0CAQAIAAAA4gMNAG8EDgAwBAO0CQAAAG8EDwAwBAMACgAAAG8EEAAwBAPcCwAAAIwENwAwBAOADAAAAJ8CAgCCAgAAEQMBBAAAAEADAgMDAwQEAABAQAMFAwYDBwMIAwkDCgMLBQQJCgsMAwwDDQMOAAEAARgAAQAAAAAAAQAAAAAAAAEAAAEAAAIAAAEAAAIAAPoAAQAAAAAAfj7/KbljiJxM+pW9QhDmR9AYYzaNMQbU+UFE9hoOz32YAE/R25o/yw==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Std.TableUtils).requireValidIndexAndFreeze({
	["TAG_NAME"] = "DartDispenser",
	["FIRE_REMOTE_NAME"] = "DartFire",
	["DAMAGE_REMOTE_NAME"] = "DartDamage",
	["DAMAGE"] = 55
})
