-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNtBGdhbWUGRGVicmlzClRpbWVMZW5ndGgHQWRkSXRlbQhJbnN0YW5jZQNuZXcFU291bmQPcmJ4YXNzZXRpZDovLyVkBmZvcm1hdAdTb3VuZElkBlZvbHVtZQZQYXJlbnQEUGxheQVkZWxheQlQbGF5U291bmQGYXNzZXJ0DHNldG1ldGF0YWJsZQZMYXlvdXQLR2V0Q2hpbGRyZW4LTW9kZWxMYXlvdXQETWFpZApCb3JuQXRTeW5jBkxhc2Vycw5GaW5kRmlyc3RDaGlsZAtTZXR1cExhc2VycwpHZXROb3dTeW5jBmlwYWlycwZQZXJpb2QEbWF0aANjb3MEUGFydAZPcmlnaW4GVGFyZ2V0BGxlcnAGQ0ZyYW1lDFdhaXRGb3JDaGlsZAROYW1lBUxhc2VyCUxhc2VyV2FsbApMYXNlclRyYWNrA0VuZAV0YWJsZQZpbnNlcnQJSGVhcnRiZWF0B0Nvbm5lY3QIR2l2ZVRhc2sHRGVzdHJveQF6CGl6Z2pvZThpA3N1YgdyZXZlcnNlAAFvCkZpcmVTZXJ2ZXIGQWN0aW9uBVRpbWVkCER1cmF0aW9uBERpc3QIQ2FsbGJhY2sOUGxhY2UgRHluYW1pdGUDQWRkC0FkZEJhbmtEb29yC09iamVjdExvY2FsCkRpc2Nvbm5lY3QHUGxheWluZwZGYWRlVG8IdWY2Y3g1aXgEU3RvcAhhNDlveW82aBJPcGVuVG9wRmxvb3JSZW1vdGUGYWN0aW9uDkJ1dHRvbkRpc2FibGVkDEdldEF0dHJpYnV0ZQdFbmFibGVkBnVwZGF0ZQ1PcGVuIFNodXR0ZXJzGUdldEF0dHJpYnV0ZUNoYW5nZWRTaWduYWwFRXZlbnQCZW0XcmJ4YXNzZXRpZDovLzE4NDgyMDk0NjYGTG9vcGVkDFJvYmJlcnlNdXNpYwxTb3VuZFNlcnZpY2UKR2V0U2VydmljZQpTb3VuZEdyb3VwCVBsYXllckd1aQVwYWlycxNCYW5rRG9vckVzY2FwZVJvdXRlCUdldFRhZ2dlZBZHZXRJbnN0YW5jZUFkZGVkU2lnbmFsGEdldEluc3RhbmNlUmVtb3ZlZFNpZ25hbAZSZW1vdmUSQmFua1RvcEZsb29yQnV0dG9uBVN0YXJ0BEluaXQKUnVuU2VydmljZQdQbGF5ZXJzC0xvY2FsUGxheWVyEUNvbGxlY3Rpb25TZXJ2aWNlEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUDU3RkBkJpbmRlcgRUaW1lBk1vZHVsZQVBdWRpbwJVSQxDaXJjbGVBY3Rpb24HX19pbmRleAASBQABAAAADKQBAQAAAABATQABnQIAAAD7AgAA+wQAAE0DBNYDAAAAvAAAeAQAAACfAAQBggABAAUDAQQAAABAAwIDAwMEABYAARgAAAAAAAAAAAAAAAEXAAAAAAYCAAAABwAAAQMDBgIapAICAAAEAIBvAwMAnwICAm8DBABSBQEAvAMDjQUAAACfAwMCMAMCfAYAAABvAwcAMAMCSwgAAAAwAAIkCQAAALwDAu4KAAAAnwMCAaQDDAAAALBAjAQBANkFAAASAAIAnwMDAYIAAQANAwUDBgQABACAAwcDCAMJAwoCAAAAAAAA6D8DCwMMAw0DDgQAALBAAQAQDwEYAAAAAAEAAAAAAAABAAABAAEAAAEAAAAAAAMRAAAAAAcCAgAAAD1HAAIAAAAAgKkDAAGpAwEAuwEDAqQCAQAAAABAnwICAUcBAgAAAACAqQMAAakDAQC7AQMCpAIBAAAAAECfAgIB/wIDAAAAAAD7BQAAnj0CBAUAAABSBAIApAMDAAAAIECfAwMBTQQBNQQAAAC8BARoBQAAAJ8EAgITAwQARwMCAAAAAICpBQABqQUBALsBBQKkBAEAAAAAQJ8EAgEwAwIwBgAAAPsFAQBNBAXvBwAAAJ8EAQIwBAJ2CAAAADAAAqIJAAAATQQCMAYAAABvBgoAvAQEAwsAAACfBAMCDgQEAFIGAwC8BAKzDAAAAJ8EAwGCAgIADQMQBAAAAEADEQQAACBAAxIDEwMUAwYDFQMWAxcDGAMZAB0GARgAAAAAAAAAAAEAAAAAAAAAAgABAAAAAAAAAgAAAAAAAQAAAAAAAAABAAIAAAAAAAEAAgAAAAAAAAEAAAADHgAAAAANAAMAAAAm+wIAAE0BAjIAAAAAnwEBAvsDAQBNAgOiAQAAACYAAQKkAQMAAAAgQPsCAgCfAQIEUQEWAE0HBWoFAAAA2AYEBwkKAAa7CQoCpAkKAAAkgICfCQICWwgJB5UHCAZNCAVECwAAAE0JBUMMAAAATQsFLA0AAABSDAcAvAkJvw4AAACfCQQCMAkIhQ8AAABuAen/AgAAgIIAAQAQAxoDFgMbBAAAIEACGC1EVPshGUADHAIAAAAAAADgPwIAAAAAAADgvwMdAx4EACSAgAMfAyADIQMiAyMASAABGAAAAAAAAAAAAQAAAAABAAABAAAAAAAAAQAAAAAAAAAAAAAA/QAFSQAAAAAHAAEAAAAOpAABAAAAAED7AQAAnwACBFEABgBNBQREAgAAAE0GBEMDAAAAMAYFhQQAAABuAPn/AgAAgIIAAQAFAxsEAAAAQAMfAyADIwBQAAEYAAAAAAABAAAAAAD/AANRAAAAABACAgAAAF1vBAAAvAIB0wEAAACfAgMCuwECA1IEAgCkAwMAAAAgQJ8DAgH/AwAAAAAAAKQEBQAAAEBAvAUCaAYAAACfBQIAnwQABFEEMgBNCQi6BwAAAPAJCQAIAAAATQkIugcAAADwCQUACQAAAE0JCLoHAAAA8AknAAoAAICMCQIATQoIugcAAADwCgMACQAAgIwJBQBlAAUATQoIugcAAADwCgIACgAAgG8JCwBvDAwAjA0DALwKCNMBAAAAnwoEAuINEAAwCg1EDAAAAE0OCoURAAAAMA4NQw0AAABNDwgLEgAAAE0OD4URAAAAMA4NLA4AAAAwCQ1qDwAAAJ40AwQNAAAAUgwDAKQLFQAAUDCBnwsDAW4Ezf8CAACATQQAdhYAAAD7BwAATQYH/RcAAADZCAAAEgIBABIAAAASAAMAvAYGxxgAAACfBgMAvAQE/RkAAACfBAABTQQAdhYAAADZBgEAEgADALwEBP0ZAAAAnwQDAYIAAQAaAxcDJAMQBAAAIEADGwQAAEBAAxMDJQMmAycDKAIAAAAAAAAMQAMfAyADIQMcBQQMDQ4PAyMDKQMqAysEAFAwgQMVAywDLQMuAgMEMRkBGAAAAAABAAAAAAIAAQAAAAAAAAEAAAAAAAAAAAAAAAEBAAAAAQABAAAAAQIAAAAAAQEAAQAAAAEAAAAAAAEAAAAA/AAA9wARAAAAAAAAAAAAAAAAAAAIAAAAAAAABTMAAAAAAwEAAAAACU0BAHYAAAAAvAEBUAEAAACfAQIBxgEAADABAHYAAAAAggABAAIDFQMvAFYvARgAAAAAAAEAAAFXAAAAAA0CAgAABwAAAQMJBgIiDgEfAPsCAABvBQAAbwkBAIwLAgCMDAcAvAkJ8AIAAACfCQQCvAkJmwMAAACfCQICvAkJmwMAAACfCQICvAkJmwMAAACfCQICvAkJmwMAAACfCQICvAkJmwMAAACfCQICUgYJAG8HBABvCAUAcwQFCPsFAQC8AgJrBgAAAJ8CBAGpAgEAggICAAcDMAMxAzIDMwM0AzUDNgBcNwEYAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAF0AAAAABgECAAAAG9kBAAASAgAAEgAAAOICBgAwAAJEAAAAAG8DBwAwAwK6AQAAAKkDAQAwAwJxAgAAAIwDBQAwAwLlAwAAAIwDCAAwAwLjBAAAADABAkYFAAAA+wQBAE0DBF8IAAAAUgQCAFIFAACfAwMBggABAAkDHwMlAzgDOQM6AzsFBgABAgMEBQM8Az0BB1s+ARgAAAAGAQABAAABAAABAAABAAABAAIAAAAAAAFcAAAAAAMAAgAAAAf7AQAATQAB0QAAAAD7AQEAbwIBAJ8AAwGCAAEAAgM/AgAAgKGVdttBAIABAAEYAAAAAAAAAYEAAAAABgIGAAAAQPsEAABHBAIAAAAAAKkDAAGpAwEAuwEDAqQCAQAAAABAnwICAUcBAgAAAACAqQMAAakDAQC7AQMCpAIBAAAAAECfAgIB+wMBAE0CA+8CAAAAUgMAAFIEAQCfAgMC3gIAAPsDAgBNAgPRAwAAAPsDAwBvBAQAnwIDAaQCBgAAAFBAjAMBAMAEBwASAgIAEgIDAJ8CAwH7AgQARwIHAAAAAAD7AgQAvAICGggAAACfAgIBxgIAAN4CBAD7AwUATQIDTwkAAAAqAgUAAAAAgPsCBQC8AgLuCgAAAJ8CAgH7AwIATQIDBwsAAAD7AwUAjAQBAIwFBQCfAgQC3gIEAIIAAQAMAxAEAAAAQAMGAz8CAAAAE8Vi20EDDgQAAFBABgkDQANBAw0DQgEJekMBGAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAIAAAAAAAEAAAAAAAADAAABAAAAAQACAAAAAAEAAAACAAAAAAAAAAF7AAAAAAIAAQAAAAX7AAAAvAAA+gAAAACfAAIBggABAAEDRACVAQABGAAAAAABlgAAAAAFAAQAAAAd+wAAAEcABwAAAAAA+wAAALwAAFAAAAAAnwACAcYAAADeAAAA+wABAEcABwAAAAAA+wABALwAABoBAAAAnwACAcYAAADeAAEA+wECAE0AAQcCAAAA+wEDAIwCAACMAwUA2QQAABICAwCfAAUC3gABAIIAAQADAy8DQANCAQuMAUUBGAAAAAEAAAABAAIAAAEAAAABAAIAAAAAAAAAAAADjQAAAAAHAgIAAAAVDgESAPsDAABNAgPRAAAAAPsDAQBvBAEA4gUDAG8GBAAwBgVLAgAAAJ8CBAH7AgEAbwQFALwCAgMGAAAAnwIDArwCAmsHAAAAnwICAakCAQCCAgIACAM/AgAAiDdzywFCAwsFAQICAAAAAAAA4D8DRgMYAzYAogFHARgAAQAAAAAAAAAAAAEAAAAAAAAAAgCjAAAAAAUAAgAAAA37AAAA+wIBAG8EAAC8AgISAQAAAJ8CAwIqAgIAAQAAgKkBAAGpAQEAMAEA8AIAAACCAAEAAwNIA0kDSgCwAUsBGAAAAAAAAAAAAAAAAAGxAAAAAAoBAwAAADf7AgAATQEC7wAAAACfAQEC2QIAABICAQASAAAA4gMGADAAA0QBAAAAbwQHADAEA7oCAAAAqQQAADAEA3EDAAAAjAQIADAEA+MEAAAAMAIDRgUAAADZBAEAEgADABIAAABvCAgAvAYAEgkAAACfBgMCKgYCAAEAAICpBQABqQUBADAFA/AKAAAA+wgCAE0HCF8LAAAAUggDAFIJAACfBwMAvAUB/QwAAACfBQABbwkIALwHABYNAAAAnwcDAlIJBAC8BwfHDgAAAJ8HAwC8BQH9DAAAAJ8FAAGCAQIADwMGAx8DJQM4AzoDOwUFAQIDBAUDTANIA0kDSgM9Ay4DTQMtAg0OoAEAARgAAAAAAQAABwEAAQAAAQAAAQAAAQACAAABAAAAAAAAAAAAAwAAAAAAAAAAAQAAAAAAAAAAAAABoQAAAAALAQoAAABmTQEANgAAAABNAgDfAQAAAN4BAADeAgEApAEEAAAMIIBvAgUAnwECAm8CBgAwAgF8BwAAAKkCAQAwAgG1CAAAAIwCAAAwAgFLCQAAAKQDDAAAALBAbwUNALwDAxYOAAAAnwMDAk0CA8kKAAAAMAIB4Q8AAAD7AwIATQIDmRAAAAAwAgEkEQAAAMYCAADGAwAA2QQAABIBA/8SAgMAEgIEABICAgASAQL/EgABAPsFAQAwBAVBEgAAANkEAQASAQP/EgEC/xICBAASAAEA+wUBADAEBa4TAAAApAQVAAAAQEH7BQUAbwcWALwFBQUXAAAAnwUDAJ8EAAQXBAMA+wkGAFIKCACfCQIBbgT8/wIAAAD7BAUAbwYWALwEBF4YAAAAnwQDAvsGBgC8BATHGQAAAJ8EAwH7BAUAbwYWALwEBNwaAAAAnwQDAvsHBwBNBgdpGwAAALwEBMcZAAAAnwQDAfsFCABNBAXvAwAAAG8FHADABh0AEgIJABICBAASAgcAnwQDArwFBBweAAAAnwUCAcECAACCAAEAHwNOA08DBQMGBAAMIIADBwNQAwoDUQMLA1IDAQQAALBAA1MDVANVA1YDDANDA0UDVwQAAEBBA1gDWQNaAy0DWwNcA10GDwNeAwoMD2xfARgAAAAAAAACAAAAAQAAAQAAAQAAAQAAAAAAAAAAAAEAAAAAAgICAAAAAAAAAAAAEgAAAAAAAAAOAAAAAAAAAAABAAD/AAMAAAAAAAAAAAEAAAAAAAAAAAAAAgAAAAAAAAAAGAAAAQBtAAAAABMAAAECAG6jAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCTQIBMQUAAACkAwEAAAAAQG8FBgC8AwMWAwAAAJ8DAwKkBAEAAAAAQG8GBwC8BAQWAwAAAJ8EAwKkBQkAAACAQE0HBKEKAAAATQYHfwsAAACfBQICpAYJAAAAgEBNCAShCgAAAE0HCHYMAAAAnwYCAqQHCQAAAIBATQkEQA4AAABNCAlKDQAAAJ8HAgKkCAkAAACAQE0KBKEKAAAATQkK0g8AAACfCAICpAkJAAAAgEBNCwShCgAAAE0KC3YMAAAAnwkCAqQKCQAAAIBATQwEQA4AAABNCwxcEAAAAJ8KAgJNCwrdEQAAAMYMAADGDQAAwA4SAP8PAwAAAAAAMA8PbhMAAADAEBQAEgAPABIACQAwEA/vFQAAAMAQFgASAAAAEgAHADAQD7MXAAAAwBAYADAQD1AZAAAA2RAEABIBDP8SAAsA2REFABIBDP8SAQ3/EgACABIADwASAAgAEgADABIAEAASAAsAEgAFABIABgDiEhsAMBEScxoAAADBDAAAghICABwDAQQAAABAA2ADVANhA2IDYwNkA2UEAACAQANmA2cDFQNoA2kDagNrA2wGAQNtBgIDBgYFAxkGBgMvA18FARoGAQIFBggQAQABGAABAAAAAAABAAAAAAABAAEAAAAAAAEAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAQACCwABAAEAAAAAFAAAAAAlAAAFAAARAAAAAAAAAAAAAE8BAAAAAQAAAAARxWzNwoqga3f3qKdWjkD6G+2J8raxB+1OF32isAUi0NMd9z8Uwf3j6w==

-- Decompiled by Krnl

local v_u_1 = game:GetService("RunService")
local v_u_2 = game:GetService("Players").LocalPlayer
local v_u_3 = game:GetService("CollectionService")
local v4 = game:GetService("ReplicatedStorage")
local v_u_5 = require(v4.Std.Binder)
local v_u_6 = require(v4.Std.Maid)
local v_u_7 = require(v4.Module.Time)
local v_u_8 = require(v4.Std.Audio)
local v_u_9 = require(v4.Std.Maid)
local v_u_10 = require(v4.Module.UI).CircleAction
local v_u_11 = nil
local v_u_12 = nil
local v_u_13 = {}
v_u_13.__index = v_u_13
function v_u_13.new(p14, p15)
	-- upvalues: (copy) v_u_13, (copy) v_u_9
	local v16 = p14 ~= nil
	assert(v16)
	local v17 = p15 ~= nil
	assert(v17)
	local v18 = {}
	local v19 = v_u_13
	setmetatable(v18, v19)
	local v20 = p15.Layout:GetChildren()[1]
	local v21 = v20 ~= nil
	assert(v21)
	v18.ModelLayout = v20
	v18.Maid = v_u_9.new()
	v18.BornAtSync = p14
	if v18.ModelLayout:FindFirstChild("Lasers") then
		v18:SetupLasers(v20)
	end
	return v18
end
function v_u_13.SetupLasers(p_u_22, p23)
	-- upvalues: (copy) v_u_1, (copy) v_u_7
	local v24 = p23:WaitForChild("Lasers")
	assert(v24)
	local v_u_25 = {}
	for _, v26 in ipairs(v24:GetChildren()) do
		if v26.Name == "Laser" or (v26.Name == "LaserWall" or v26.Name == "LaserTrack") then
			local v27 = v26.Name == "LaserWall" and 5 or (v26.Name == "LaserTrack" and 3.5 or 2)
			local v28 = v26:WaitForChild("Part", 3)
			local v29 = {
				["Part"] = v28,
				["Origin"] = v28.CFrame,
				["Target"] = v26.End.CFrame,
				["Period"] = v27
			}
			table.insert(v_u_25, v29)
		end
	end
	p_u_22.Maid:GiveTask(v_u_1.Heartbeat:Connect(function()
		-- upvalues: (ref) v_u_7, (copy) p_u_22, (copy) v_u_25
		local v30 = v_u_7.GetNowSync() - p_u_22.BornAtSync
		for _, v31 in ipairs(v_u_25) do
			local v32 = v30 * (6.283185307179586 / v31.Period)
			local v33 = math.cos(v32) * -0.5 + 0.5
			v31.Part.CFrame = v31.Origin:lerp(v31.Target, v33)
		end
	end))
	p_u_22.Maid:GiveTask(function()
		-- upvalues: (copy) v_u_25
		for _, v34 in ipairs(v_u_25) do
			v34.Part.CFrame = v34.Origin
		end
	end)
end
function v_u_13.Destroy(p35)
	p35.Maid:Destroy()
	p35.Maid = nil
end
local function v_u_39(p_u_36)
	-- upvalues: (ref) v_u_11, (copy) v_u_10
	local v38 = {
		["Part"] = p_u_36,
		["Name"] = "Place Dynamite",
		["Timed"] = true,
		["Duration"] = 5,
		["Dist"] = 8,
		["Callback"] = function(_, p37)
			-- upvalues: (ref) v_u_11, (copy) p_u_36
			if p37 then
				v_u_11:FireServer("z" .. ("izgjoe8i"):sub(2, 7):reverse():reverse():reverse():reverse():reverse() .. "o", p_u_36)
			end
			return true
		end
	}
	v_u_10.Add(v38, p_u_36)
end
return {
	["Init"] = function(p40)
		-- upvalues: (ref) v_u_11, (ref) v_u_12, (copy) v_u_2, (copy) v_u_13, (copy) v_u_8, (copy) v_u_3, (copy) v_u_39, (copy) v_u_10, (copy) v_u_5, (copy) v_u_6
		local v41 = p40.Event
		local v42 = p40.em
		v_u_11 = v41
		v_u_12 = v42
		local v_u_43 = Instance.new("Sound")
		v_u_43.SoundId = "rbxassetid://1848209466"
		v_u_43.Looped = true
		v_u_43.Volume = 0
		v_u_43.SoundGroup = game:GetService("SoundService").RobberyMusic
		v_u_43.Parent = v_u_2.PlayerGui
		local v_u_44 = nil
		local v_u_45 = nil
		function v_u_12.uf6cx5ix(p46, p47)
			-- upvalues: (ref) v_u_45, (ref) v_u_13, (ref) v_u_8, (ref) v_u_2, (ref) v_u_44, (copy) v_u_43
			local v48 = v_u_45 == nil
			assert(v48)
			local v49 = p47 ~= nil
			assert(v49)
			v_u_45 = v_u_13.new(p46, p47)
			v_u_8.ObjectLocal(v_u_2, 1837831244)
			delay(1, function()
				-- upvalues: (ref) v_u_8, (ref) v_u_2
				v_u_8.ObjectLocal(v_u_2, 1843025542)
			end)
			if v_u_44 ~= nil then
				v_u_44:Disconnect()
				v_u_44 = nil
			end
			if v_u_43.Playing == false then
				v_u_43:Play()
			end
			v_u_44 = v_u_8.FadeTo(v_u_43, 1, 5)
		end
		function v_u_12.a49oyo6h()
			-- upvalues: (ref) v_u_45, (ref) v_u_44, (ref) v_u_8, (copy) v_u_43
			if v_u_45 ~= nil then
				v_u_45:Destroy()
				v_u_45 = nil
			end
			if v_u_44 ~= nil then
				v_u_44:Disconnect()
				v_u_44 = nil
			end
			v_u_44 = v_u_8.FadeTo(v_u_43, 0, 5, function()
				-- upvalues: (ref) v_u_43
				v_u_43:Stop()
			end)
		end
		for _, v50 in pairs(v_u_3:GetTagged("BankDoorEscapeRoute")) do
			v_u_39(v50)
		end
		v_u_3:GetInstanceAddedSignal("BankDoorEscapeRoute"):Connect(v_u_39)
		v_u_3:GetInstanceRemovedSignal("BankDoorEscapeRoute"):Connect(v_u_10.Remove)
		v_u_5.new("BankTopFloorButton", function(p_u_51)
			-- upvalues: (ref) v_u_6, (ref) v_u_8, (ref) v_u_10
			local v52 = v_u_6.new()
			local v_u_54 = {
				["Part"] = p_u_51,
				["Name"] = "Open Shutters",
				["Timed"] = false,
				["Dist"] = 8,
				["Callback"] = function(_, p53)
					-- upvalues: (ref) v_u_8, (copy) p_u_51
					if p53 then
						v_u_8.ObjectLocal(p_u_51, 9553471217, {
							["Volume"] = 0.5
						})
						p_u_51:FindFirstChild("OpenTopFloorRemote"):FireServer()
					end
					return true
				end,
				["Enabled"] = p_u_51:GetAttribute("ButtonDisabled") ~= true
			}
			v52:GiveTask(v_u_10.Add(v_u_54, p_u_51))
			v52:GiveTask(p_u_51:GetAttributeChangedSignal("ButtonDisabled"):Connect(function()
				-- upvalues: (copy) v_u_54, (copy) p_u_51
				v_u_54.Enabled = p_u_51:GetAttribute("ButtonDisabled") ~= true
			end))
			return v52
		end):Start()
	end
}
