-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMJBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplD01BWF9URVhUX0xFTkdUSBxSQUlOQk9XX0FOSU1BVElPTl9DWUNMRV9USU1FAAEFAAABAgAZowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAoQYAAABNAgMYBwAAAJ8BAgJNAgEACAAAAOIDCwCMBEAAMAQDDgkAAACMBAUAMAQDigoAAACfAgIAggIAAAwDAQQAAABAAwIDAwMEBAAAQEADBQMGAwcDCAMJBQIJCgABAAEYAAEAAAAAAAEAAAAAAAABAAABAAABAAD+AAEAAAAAAIssxb7QlfJ7ueivKtqQkEQwpsfQqC6m013BlRxqQ+lbhD5lGEwBlJo=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Std.TableUtils).requireValidIndexAndFreeze({
	["MAX_TEXT_LENGTH"] = 64,
	["RAINBOW_ANIMATION_CYCLE_TIME"] = 5
})
