-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMNBnNvcnRJZA5taXNzaW5nIHNvcnRJZAZhc3NlcnQOc2V0VHJhZGVTb3J0SWQEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUFUm9kdXgGR2FyYWdlCEVudW1Tb3J0DWNyZWF0ZVJlZHVjZXIGTmV3ZXN0AAIFAgAAAAAPTQQBpgAAAABHBAIAAAAAgKkDAAGpAwEAgQEDBAEAAABvBAEApAIDAAAAIECfAgMBTQIBpgAAAACCAgIABAMBAwIDAwQAACBAAAgEARgAAAAAAAAAAAAAAAABAAAJAAAAAAcAAAECAB2jAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAgCnBgAAAJ8BAgKkAgUAAABAQE0EACgHAAAATQMEHAgAAACfAgICTQMB1gkAAABNBAJ3CgAAAOIFDADABg0AMAYF2AsAAACfAwMAggMAAA4DBQQAAABAAwYDBwMIBAAAQEADCQMKAwsDDAMNAwQFAQsGAAEAAQABGAABAAAAAAABAAAAAAIAAAAAAAACAAAAAAEAAP8AAQAAAAAB/VjdZf+aJeTPnLfx8GVizZ600+5dY7mgui9bX/nFGmK2M2WZricIdQ==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v2 = require(v1.Rodux)
local v3 = require(v1.Garage.EnumSort)
return v2.createReducer(v3.Newest, {
	["setTradeSortId"] = function(_, p4)
		local v5 = p4.sortId ~= nil
		assert(v5, "missing sortId")
		return p4.sortId
	end
})
