-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMsD0FDQ0VMX0FUVFJfTkFNRQxHZXRBdHRyaWJ1dGUIZ2V0QWNjZWwMU2V0QXR0cmlidXRlCHNldEFjY2VsE0xJRkVfU1BBTl9BVFRSX05BTUULZ2V0TGlmZVNwYW4Lc2V0TGlmZVNwYW4dU0VFS19BRlRFUl9EVVJBVElPTl9BVFRSX05BTUUUZ2V0U2Vla0FmdGVyRHVyYXRpb24Uc2V0U2Vla0FmdGVyRHVyYXRpb24pTk9fSU1QUk9WRU1FTlRfRVhQTE9ERV9EVVJBVElPTl9BVFRSX05BTUUfZ2V0Tm9JbXByb3ZlbWVudEV4cGxvZGVEdXJhdGlvbh9zZXROb0ltcHJvdmVtZW50RXhwbG9kZUR1cmF0aW9uJENPTk5FQ1RfSElUX0FGVEVSX0RVUkFUSU9OX0FUVFJfTkFNRRpnZXRDb25uZWN0SGl0QWZ0ZXJEdXJhdGlvbhpzZXRDb25uZWN0SGl0QWZ0ZXJEdXJhdGlvbhdEUk9QX0RVUkFUSU9OX0FUVFJfTkFNRQ9nZXREcm9wRHVyYXRpb24Pc2V0RHJvcER1cmF0aW9uGUFQUExZSU5HX1RIUlVTVF9BVFRSX05BTUURZ2V0QXBwbHlpbmdUaHJ1c3QZR2V0QXR0cmlidXRlQ2hhbmdlZFNpZ25hbB5nZXRBcHBseWluZ1RocnVzdENoYW5nZWRTaWduYWwRc2V0QXBwbHlpbmdUaHJ1c3QUVEFSR0VUX1BPU19BVFRSX05BTUUMZ2V0VGFyZ2V0UG9zGWdldFRhcmdldFBvc0NoYW5nZWRTaWduYWwMc2V0VGFyZ2V0UG9zFkZPUldBUkRfRFJBR19BVFRSX05BTUUOZ2V0Rm9yd2FyZERyYWcOc2V0Rm9yd2FyZERyYWcWTEFURVJBTF9EUkFHX0FUVFJfTkFNRQ5nZXRMYXRlcmFsRHJhZw5zZXRMYXRlcmFsRHJhZx5BTElHTl9SRVNQT05TSVZFTkVTU19BVFRSX05BTUUWZ2V0QWxpZ25SZXNwb25zaXZlbmVzcxZzZXRBbGlnblJlc3BvbnNpdmVuZXNzBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlDlNlZWtpbmdNaXNzaWxlFFNlZWtpbmdNaXNzaWxlQ29uc3RzABkFAQEAAAAH+wQAAE0DBO0AAAAAvAEAEgEAAACfAQMAggEAAAIDAQMCAAUDARgAAAAAAAAABgAAAAAGAgEAAAAI+wUAAE0EBe0AAAAAUgUBALwCAC4BAAAAnwIEAYIAAQACAwEDBAAIBQEYAAAAAAAAAAEJAAAAAAUBAQAAAAf7BAAATQMExgAAAAC8AQASAQAAAJ8BAwCCAQAAAgMGAwIACwcBGAAAAAAAAAAMAAAAAAYCAQAAAAj7BQAATQQFxgAAAABSBQEAvAIALgEAAACfAgQBggABAAIDBgMEAA4IARgAAAAAAAAAAQ8AAAAABQEBAAAAB/sEAABNAwQSAAAAALwBABIBAAAAnwEDAIIBAAACAwkDAgARCgEYAAAAAAAAABIAAAAABgIBAAAACPsFAABNBAUSAAAAAFIFAQC8AgAuAQAAAJ8CBAGCAAEAAgMJAwQAFAsBGAAAAAAAAAABFQAAAAAFAQEAAAAH+wQAAE0DBMwAAAAAvAEAEgEAAACfAQMAggEAAAIDDAMCABcNARgAAAAAAAAAGAAAAAAGAgEAAAAI+wUAAE0EBcwAAAAAUgUBALwCAC4BAAAAnwIEAYIAAQACAwwDBAAaDgEYAAAAAAAAAAEbAAAAAAUBAQAAAAf7BAAATQMEXgAAAAC8AQASAQAAAJ8BAwCCAQAAAgMPAwIAHRABGAAAAAAAAAAeAAAAAAYCAQAAAAj7BQAATQQFXgAAAABSBQEAvAIALgEAAACfAgQBggABAAIDDwMEACARARgAAAAAAAAAASEAAAAABQEBAAAAB/sEAABNAwQcAAAAALwBABIBAAAAnwEDAIIBAAACAxIDAgAjEwEYAAAAAAAAACQAAAAABgIBAAAACPsFAABNBAUcAAAAAFIFAQC8AgAuAQAAAJ8CBAGCAAEAAgMSAwQAJhQBGAAAAAAAAAABJwAAAAAFAQEAAAAH+wQAAE0DBIEAAAAAvAEAEgEAAACfAQMAggEAAAIDFQMCACkWARgAAAAAAAAAKgAAAAAFAQEAAAAH+wQAAE0DBIEAAAAAvAEAFgEAAACfAQMAggEAAAIDFQMXACwYARgAAAAAAAAALQAAAAAGAgEAAAAI+wUAAE0EBYEAAAAAUgUBALwCAC4BAAAAnwIEAYIAAQACAxUDBAAvGQEYAAAAAAAAAAEwAAAAAAUBAQAAAAf7BAAATQMEyAAAAAC8AQASAQAAAJ8BAwCCAQAAAgMaAwIAMhsBGAAAAAAAAAAzAAAAAAUBAQAAAAf7BAAATQMEyAAAAAC8AQAWAQAAAJ8BAwCCAQAAAgMaAxcANRwBGAAAAAAAAAA2AAAAAAYCAQAAAAj7BQAATQQFyAAAAABSBQEAvAIALgEAAACfAgQBggABAAIDGgMEADgdARgAAAAAAAAAATkAAAAABQEBAAAAB/sEAABNAwRqAAAAALwBABIBAAAAnwEDAIIBAAACAx4DAgA7HwEYAAAAAAAAADwAAAAABgIBAAAACPsFAABNBAVqAAAAAFIFAQC8AgAuAQAAAJ8CBAGCAAEAAgMeAwQAPiABGAAAAAAAAAABPwAAAAAFAQEAAAAH+wQAAE0DBFwAAAAAvAEAEgEAAACfAQMAggEAAAIDIQMCAEEiARgAAAAAAAAAQgAAAAAGAgEAAAAI+wUAAE0EBVwAAAAAUgUBALwCAC4BAAAAnwIEAYIAAQACAyEDBABEIwEYAAAAAAAAAAFFAAAAAAUBAQAAAAf7BAAATQME3AAAAAC8AQASAQAAAJ8BAwCCAQAAAgMkAwIARyUBGAAAAAAAAABIAAAAAAYCAQAAAAj7BQAATQQF3AAAAABSBQEAvAIALgEAAACfAgQBggABAAIDJAMEAEomARgAAAAAAAAAAUsAAAAABAAAAQIAcaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DAKYGAAAATQID3gcAAACfAQIC/wIGAAAAAADAAwgAEgABADADAmAJAAAAwAMKABIAAQAwAwJsCwAAAMADDAASAAEAMAMCXA0AAADAAw4AEgABADADAlAPAAAAwAMQABIAAQAwAwLFEQAAAMADEgASAAEAMAMC8RMAAADAAxQAEgABADADAp4VAAAAwAMWABIAAQAwAwKiFwAAAMADGAASAAEAMAMCXBkAAADAAxoAEgABADADAigbAAAAwAMcABIAAQAwAwIJHQAAAMADHgASAAEAMAMCfR8AAADAAyAAEgABADADAm0hAAAAwAMiABIAAQAwAwIuIwAAAMADJAASAAEAMAMCcSUAAADAAyYAEgABADADAhMnAAAAwAMoABIAAQAwAwLqKQAAAMADKgASAAEAMAMCLysAAADAAywAEgABADADAuEtAAAAwAMuABIAAQAwAwLtLwAAAMADMAASAAEAMAMCyzEAAADAAzIAEgABADADAj8zAAAAwAM0ABIAAQAwAwLCNQAAAMADNgASAAEAMAMC9jcAAACCAgIAOAMnBAAAAEADKAMpAyoEAABAQAMrAywGAAMDBgEDBQYCAwcGAwMIBgQDCgYFAwsGBgMNBgcDDgYIAxAGCQMRBgoDEwYLAxQGDAMWBg0DGAYOAxkGDwMbBhADHAYRAx0GEgMfBhMDIAYUAyIGFQMjBhYDJQYXAyYYAAECAwQFBgcICQoLDA0ODxAREhMUFRYXAQABGAAAAAAAAAABAAAAAAAAAgABAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAQAAAAAYmtfNruLszumoE6c61bTj5Ny88R9ITC7BsjuP3AgYvUZmamMVIxU9Sw==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.SeekingMissile.SeekingMissileConsts)
return {
	["getAccel"] = function(p3)
		-- upvalues: (copy) v_u_2
		return p3:GetAttribute(v_u_2.ACCEL_ATTR_NAME)
	end,
	["setAccel"] = function(p4, p5)
		-- upvalues: (copy) v_u_2
		p4:SetAttribute(v_u_2.ACCEL_ATTR_NAME, p5)
	end,
	["getLifeSpan"] = function(p6)
		-- upvalues: (copy) v_u_2
		return p6:GetAttribute(v_u_2.LIFE_SPAN_ATTR_NAME)
	end,
	["setLifeSpan"] = function(p7, p8)
		-- upvalues: (copy) v_u_2
		p7:SetAttribute(v_u_2.LIFE_SPAN_ATTR_NAME, p8)
	end,
	["getSeekAfterDuration"] = function(p9)
		-- upvalues: (copy) v_u_2
		return p9:GetAttribute(v_u_2.SEEK_AFTER_DURATION_ATTR_NAME)
	end,
	["setSeekAfterDuration"] = function(p10, p11)
		-- upvalues: (copy) v_u_2
		p10:SetAttribute(v_u_2.SEEK_AFTER_DURATION_ATTR_NAME, p11)
	end,
	["getNoImprovementExplodeDuration"] = function(p12)
		-- upvalues: (copy) v_u_2
		return p12:GetAttribute(v_u_2.NO_IMPROVEMENT_EXPLODE_DURATION_ATTR_NAME)
	end,
	["setNoImprovementExplodeDuration"] = function(p13, p14)
		-- upvalues: (copy) v_u_2
		p13:SetAttribute(v_u_2.NO_IMPROVEMENT_EXPLODE_DURATION_ATTR_NAME, p14)
	end,
	["getConnectHitAfterDuration"] = function(p15)
		-- upvalues: (copy) v_u_2
		return p15:GetAttribute(v_u_2.CONNECT_HIT_AFTER_DURATION_ATTR_NAME)
	end,
	["setConnectHitAfterDuration"] = function(p16, p17)
		-- upvalues: (copy) v_u_2
		p16:SetAttribute(v_u_2.CONNECT_HIT_AFTER_DURATION_ATTR_NAME, p17)
	end,
	["getDropDuration"] = function(p18)
		-- upvalues: (copy) v_u_2
		return p18:GetAttribute(v_u_2.DROP_DURATION_ATTR_NAME)
	end,
	["setDropDuration"] = function(p19, p20)
		-- upvalues: (copy) v_u_2
		p19:SetAttribute(v_u_2.DROP_DURATION_ATTR_NAME, p20)
	end,
	["getApplyingThrust"] = function(p21)
		-- upvalues: (copy) v_u_2
		return p21:GetAttribute(v_u_2.APPLYING_THRUST_ATTR_NAME)
	end,
	["getApplyingThrustChangedSignal"] = function(p22)
		-- upvalues: (copy) v_u_2
		return p22:GetAttributeChangedSignal(v_u_2.APPLYING_THRUST_ATTR_NAME)
	end,
	["setApplyingThrust"] = function(p23, p24)
		-- upvalues: (copy) v_u_2
		p23:SetAttribute(v_u_2.APPLYING_THRUST_ATTR_NAME, p24)
	end,
	["getTargetPos"] = function(p25)
		-- upvalues: (copy) v_u_2
		return p25:GetAttribute(v_u_2.TARGET_POS_ATTR_NAME)
	end,
	["getTargetPosChangedSignal"] = function(p26)
		-- upvalues: (copy) v_u_2
		return p26:GetAttributeChangedSignal(v_u_2.TARGET_POS_ATTR_NAME)
	end,
	["setTargetPos"] = function(p27, p28)
		-- upvalues: (copy) v_u_2
		p27:SetAttribute(v_u_2.TARGET_POS_ATTR_NAME, p28)
	end,
	["getForwardDrag"] = function(p29)
		-- upvalues: (copy) v_u_2
		return p29:GetAttribute(v_u_2.FORWARD_DRAG_ATTR_NAME)
	end,
	["setForwardDrag"] = function(p30, p31)
		-- upvalues: (copy) v_u_2
		p30:SetAttribute(v_u_2.FORWARD_DRAG_ATTR_NAME, p31)
	end,
	["getLateralDrag"] = function(p32)
		-- upvalues: (copy) v_u_2
		return p32:GetAttribute(v_u_2.LATERAL_DRAG_ATTR_NAME)
	end,
	["setLateralDrag"] = function(p33, p34)
		-- upvalues: (copy) v_u_2
		p33:SetAttribute(v_u_2.LATERAL_DRAG_ATTR_NAME, p34)
	end,
	["getAlignResponsiveness"] = function(p35)
		-- upvalues: (copy) v_u_2
		return p35:GetAttribute(v_u_2.ALIGN_RESPONSIVENESS_ATTR_NAME)
	end,
	["setAlignResponsiveness"] = function(p36, p37)
		-- upvalues: (copy) v_u_2
		p36:SetAttribute(v_u_2.ALIGN_RESPONSIVENESS_ATTR_NAME, p37)
	end
}
