-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgM3FGFwcGx5aW5nVGhydXN0UmVtb3RlEmZsYWdBcHBseWluZ1RocnVzdApGaXJlU2VydmVyDWV4cGxvZGVSZW1vdGUKb25FeHBsb2RlZARGaXJlB3J1bk1haWQKRG9DbGVhbmluZw10YXJnZXRQYXJ0T2JqBVZhbHVlDGdldFRhcmdldFBvcwhHZXRPd25lcgRfcnVuBmhhbmRsZQRtYWlkB0NoYW5nZWQHQ29ubmVjdAhHaXZlVGFzaxlnZXRUYXJnZXRQb3NDaGFuZ2VkU2lnbmFsFUdldE93bmVyQ2hhbmdlZFNpZ25hbANuZXcMc2V0bWV0YXRhYmxlEGFsaWduT3JpZW50YXRpb24LdmVjdG9yRm9yY2UFX2luaXQXb25BcHBseWluZ1RocnVzdENoYW5nZWQNT25DbGllbnRFdmVudAdQcm9taXNlB2FuZFRoZW4LR2l2ZVByb21pc2UNU2V0VGFyZ2V0UGFydAxzZXRUYXJnZXRQb3MDb2JqDFNldFRhcmdldFBvcwRnYW1lEVJlcGxpY2F0ZWRTdG9yYWdlCkdldFNlcnZpY2UHcmVxdWlyZQNTdGQETWFpZApCYXNlT2JqZWN0Dk1hbmlmZXN0QmluZGVyDE5ldHdvcmtPd25lZBJOZXR3b3JrT3duZWRCaW5kZXIOU2Vla2luZ01pc3NpbGUUU2Vla2luZ01pc3NpbGVDb25zdHMUU2Vla2luZ01pc3NpbGVTaGFyZWQTU2Vla2luZ01pc3NpbGVVdGlscwdfX2luZGV4CFRBR19OQU1FFkFMSUdOX09SSUVOVEFUSU9OX05BTUURVkVDVE9SX0ZPUkNFX05BTUUUVEFSR0VUX1BBUlRfT0JKX05BTUUbQVBQTFlJTkdfVEhSVVNUX1JFTU9URV9OQU1FE0VYUExPREVfUkVNT1RFX05BTUUACQQAAgAAAAr7AQAATQABKAAAAAD7AwEATQIDogEAAAC8AABrAgAAAJ8AAwGCAAEAAwMBAwIDAwAaAAEYAAAAAAAAAAAAARwAAAAAAwABAQAACaMAAAD7AQAATQABBQAAAADdAgAAvAAAawEAAACfAAABggABAAIDBAMDAB4AARgAAwAAAAAAAAEeAAAAAAMAAQEAAAmjAAAA+wEAAE0AAbUAAAAA3QIAALwAAN0BAAAAnwAAAYIAAQACAwUDBgAjAAEYAAEAAAAAAAABIwAAAAAFAAYAAAAf+wEAAE0AAVQAAAAAvAAAUQEAAACfAAIB+wIBAE0BAqACAAAATQAB7AMAAAD7AgIATQECEwQAAAD7AgMAnwECAisAAgArAQEAggABAPsCBAC8AgLDBQAAAJ8CAgIrAgEAggABAPsEBQBNAwSdBgAAAPsEAACfAwIBggABAAcDBwMIAwkDCgMLAwwDDQAoDgEYAAAAAAAAAQAAAAABAAAAAAEAAQIAAAABAQIAAAAAASkAAAAABwEFAAAAUNkBAAASAgAAEgIBABICAgASAgMAEgAAABICBAD7AwAATQIDVAAAAAC8AgJRAQAAAJ8CAgH7BAEATQMEoAIAAABNAgPsAwAAAPsEAgBNAwQTBAAAAPsEAwCfAwICKwICACsDAQBlAAoAvAQAwwUAAACfBAICKwQBAGUABQD7BgQATQUGnQYAAAD7BgAAnwUCAfsDAABNAgMWBwAAAPsGAQBNBQagAgAAAE0EBYUIAAAAUgYBALwEBMcJAAAAnwQDALwCAv0KAAAAnwIAAfsDAABNAgMWBwAAAPsFAgBNBAXqCwAAAPsFAwCfBAICUgYBALwEBMcJAAAAnwQDALwCAv0KAAAAnwIAAfsDAABNAgMWBwAAALwEAPAMAAAAnwQCAlIGAQC8BATHCQAAAJ8EAwC8AgL9CgAAAJ8CAAGCAAEADQMHAwgDCQMKAwsDDAMNAw8DEAMRAxIDEwMUAQMnAAEYAAAAAAAAAAEAAAAAAAEAAAAAAQAAAAABAAECAAABAQIAAAAAAwAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAEoAAAAAAgCBgAAAGX7AwAATQID7wAAAABSAwAAnwICAvsFAQCePQIEBQAAAFIEAgCkAwIAAAAQQJ8DAwFNAwFFAwAAADADAkUDAAAATQMBNwQAAAAwAwI3BAAAAE0DAaAFAAAAMAMCoAUAAAD7BAIATQME7wAAAACfAwECMAMCVAYAAABNAwIWBwAAAE0FAlQGAAAAvAMD/QgAAACfAwMB+wQDAE0DBGQJAAAAUgQCAJ8DAgFNAwIWBwAAAE0FAr0KAAAA2QcAABIAAQASAAIAvAUFxwsAAACfBQMAvAMD/QgAAACfAwABTQMCFgcAAABNBQK1DAAAANkHAQASAAEAvAUFxwsAAACfBQMAvAMD/QgAAACfAwABTQMCFgcAAABNBgEFDQAAAE0FBowOAAAA2QcCABIAAgC8BQXHCwAAAJ8FAwC8AwP9CAAAAJ8DAAFNAwIWBwAAAPsFBABSBwAAvAUFcg8AAACfBQMC2QcDABIAAgASAAEAEgIFABIAAAASAgMAvAUFtRAAAACfBQMAvAMD6REAAACfAwABggICABIDFQMWBAAAEEADFwMYAwkDBwMPAxIDGQMaAxEDBQMEAxsDHAMdAx4EAAECBA4VARgAAAAAAAEAAAAAAAACAAAAAQAAAAEAAAACAAAAAAABAAAAAAAAAgAAAAABAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAABQAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAEw8AAAAAAwIAAAAABU0CAKAAAAAAMAEC7AEAAACCAAEAAgMJAwoAPB8BGAAAAAABPQAAAAAFAgEAAAAI+wMAAE0CAy8AAAAATQMAEwEAAABSBAEAnwIDAYIAAQACAyADIQA/IgEYAAAAAAAAAAFAAAAAAA0AAAECAG2jAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CA3YHAAAAnwECAqQCBQAAAEBATQQAoQYAAABNAwRLCAAAAJ8CAgKkAwUAAABAQE0EAIkJAAAAnwMCAqQEBQAAAEBATQYA1QoAAABNBQayCwAAAJ8EAgKkBQUAAABAQE0HAKYMAAAATQYH3g0AAACfBQICpAYFAAAAQEBNCACmDAAAAE0HCC0OAAAAnwYCAqQHBQAAAEBATQkApgwAAABNCAmbDwAAAJ8HAgL/CAMAAAAAADAICG4QAAAAnj0IBQIAAABSCggAUgsCAKQJEgAAABBBnwkDAcAJEwASAAIAEgAIABIAAQASAAYAEgAEABIABwAwCQjvFAAAAMAJFQAwCQiZFgAAAMAJFwASAAcAMAkIDxgAAABNCQPvFAAAAE0KBbQZAAAA4gsfAE0MBTIgAAAAMAwLRRoAAABNDAVhIQAAADAMCzcbAAAATQwFmCIAAAAwDAugHAAAAE0MBYYjAAAAMAwLKB0AAABNDAXkJAAAADAMCwUeAAAAUgwIAJ8JBACCCQAAJQMjBAAAAEADJAMlAyYEAABAQAMnAygDKQMqAysDLAMtAy4DLwMwAzEDFgQAABBBBgUDFQYGAx8GBwMiAzIDFwMYAwkDAQMEBQUaGxwdHgMzAzQDNQM2AzcDBQYHAQABGAAAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAIAAQABAAAAAAAAAgAAAAAAAAAALgAAAwAAAAQAAAAAAQAAAAEAAAABAAAAAQAAAAEAAAAB+gABAAAAAAiGy9lIvHJkjrQPs9yM7Wt3gPOyLkJZFzURr9V76/GWfqoc1qjzhf1t

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.Maid)
local v_u_3 = require(v1.Std.BaseObject)
local v4 = require(v1.ManifestBinder)
local v_u_5 = require(v1.NetworkOwned.NetworkOwnedBinder)
local v6 = require(v1.SeekingMissile.SeekingMissileConsts)
local v_u_7 = require(v1.SeekingMissile.SeekingMissileShared)
local v_u_8 = require(v1.SeekingMissile.SeekingMissileUtils)
local v_u_9 = {}
v_u_9.__index = v_u_9
setmetatable(v_u_9, v_u_3)
function v_u_9.new(p_u_10, p_u_11)
	-- upvalues: (copy) v_u_3, (copy) v_u_9, (copy) v_u_2, (copy) v_u_7, (copy) v_u_5, (copy) v_u_8
	local v_u_12 = v_u_3.new(p_u_10)
	local v13 = v_u_9
	setmetatable(v_u_12, v13)
	v_u_12.alignOrientation = p_u_11.alignOrientation
	v_u_12.vectorForce = p_u_11.vectorForce
	v_u_12.targetPartObj = p_u_11.targetPartObj
	v_u_12.runMaid = v_u_2.new()
	v_u_12.maid:GiveTask(v_u_12.runMaid)
	v_u_7._init(v_u_12)
	v_u_12.maid:GiveTask(v_u_12.onApplyingThrustChanged:Connect(function()
		-- upvalues: (copy) p_u_11, (copy) v_u_12
		p_u_11.applyingThrustRemote:FireServer(v_u_12.flagApplyingThrust)
	end))
	v_u_12.maid:GiveTask(v_u_12.onExploded:Connect(function(...)
		-- upvalues: (copy) p_u_11
		p_u_11.explodeRemote:FireServer(...)
	end))
	v_u_12.maid:GiveTask(p_u_11.explodeRemote.OnClientEvent:Connect(function(...)
		-- upvalues: (copy) v_u_12
		v_u_12.onExploded:Fire(...)
	end))
	v_u_12.maid:GivePromise(v_u_5:Promise(p_u_10):andThen(function(p_u_14)
		-- upvalues: (copy) v_u_12, (copy) p_u_11, (ref) v_u_8, (copy) p_u_10, (ref) v_u_7
		local function v15()
			-- upvalues: (ref) v_u_12, (ref) p_u_11, (ref) v_u_8, (ref) p_u_10, (copy) p_u_14, (ref) v_u_7
			v_u_12.runMaid:DoCleaning()
			if p_u_11.targetPartObj.Value or v_u_8.getTargetPos(p_u_10) then
				if p_u_14:GetOwner() then
					v_u_7._run(v_u_12)
				end
			else
				return
			end
		end
		v_u_12.runMaid:DoCleaning()
		if (p_u_11.targetPartObj.Value or v_u_8.getTargetPos(p_u_10)) and p_u_14:GetOwner() then
			v_u_7._run(v_u_12)
		end
		v_u_12.maid:GiveTask(p_u_11.targetPartObj.Changed:Connect(v15))
		v_u_12.maid:GiveTask(v_u_8.getTargetPosChangedSignal(p_u_10):Connect(v15))
		v_u_12.maid:GiveTask(p_u_14:GetOwnerChangedSignal():Connect(v15))
	end))
	return v_u_12
end
function v_u_9.SetTargetPart(p16, p17)
	p16.targetPartObj.Value = p17
end
function v_u_9.SetTargetPos(p18, p19)
	-- upvalues: (copy) v_u_8
	v_u_8.setTargetPos(p18.obj, p19)
end
return v4.new(v6.TAG_NAME, {
	["alignOrientation"] = v6.ALIGN_ORIENTATION_NAME,
	["vectorForce"] = v6.VECTOR_FORCE_NAME,
	["targetPartObj"] = v6.TARGET_PART_OBJ_NAME,
	["applyingThrustRemote"] = v6.APPLYING_THRUST_REMOTE_NAME,
	["explodeRemote"] = v6.EXPLODE_REMOTE_NAME
}, v_u_9)
