-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMOBmFzc2VydBFFTkFCTEVEX0FUVFJfTkFNRQxTZXRBdHRyaWJ1dGUKc2V0RW5hYmxlZBBSQURJVVNfQVRUUl9OQU1FCXNldFJhZGl1cwZ0eXBlb2YGbnVtYmVyDElEX0FUVFJfTkFNRQVzZXRJZAdyZXF1aXJlFFByb3hpbWl0eVNvdW5kQ29uc3RzBnNjcmlwdAZQYXJlbnQABAYCAQAAABhHAAIAAAAAgKkDAAGpAwEAuwEDAqQCAQAAAABAnwICAUcBAgAAAACAqQMAAakDAQC7AQMCpAIBAAAAAECfAgIB+wUAAE0EBacCAAAAUgUBALwCAC4DAAAAnwIEAYIAAQAEAwEEAAAAQAMCAwMABQQBGAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAQYAAAAABgIBAAAAGEcAAgAAAACAqQMAAakDAQC7AQMCpAIBAAAAAECfAgIBRwECAAAAAICpAwABqQMBALsBAwKkAgEAAAAAQJ8CAgH7BQAATQQFiQIAAABSBQEAvAIALgMAAACfAgQBggABAAQDAQQAAABAAwUDAwAKBgEYAAAAAAAAAAABAAAAAAAAAAEAAAAAAAABCwAAAAAGAgEAAAAdRwACAAAAAICpAwABqQMBALsBAwKkAgEAAAAAQJ8CAgG7LAEDUgUBAKQEAwAAACBAnwQCAvAEAgAEAAAAqQMAAakDAQC7AQMCpAIBAAAAAECfAgIB+wUAAE0EBcEFAAAAUgUBALwCAC4GAAAAnwIEAYIAAQAHAwEEAAAAQAMHBAAAIEADCAMJAwMADwoBGAAAAAAAAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAABEAAAAAAEAAABAgAZowAAAKQAAQAAAABApAMEAAAAMEBNAgMkBQAAAE0BApgCAAAAnwACAv8BAwAAAAAAwAIGABIAAAAwAgG+BwAAAMACCAASAAAAMAIBHgkAAADAAgoAEgAAADACAUILAAAAggECAAwDCwQAAABAAwwDDQQAADBAAw4GAAMEBgEDBgYCAwoDAAECAQABGAABAAAAAAAAAAACAAEAAAAFAAAABQAAAAUBAAAAAAP6EsZzG6zB/cjWrOetQyCZlTglShDOGTyjvyKxXHKOgmxzaPki2ylq

-- Decompiled by Krnl

local v_u_1 = require(script.Parent.ProximitySoundConsts)
return {
	["setEnabled"] = function(p2, p3)
		-- upvalues: (copy) v_u_1
		local v4 = p2 ~= nil
		assert(v4)
		local v5 = p3 ~= nil
		assert(v5)
		p2:SetAttribute(v_u_1.ENABLED_ATTR_NAME, p3)
	end,
	["setRadius"] = function(p6, p7)
		-- upvalues: (copy) v_u_1
		local v8 = p6 ~= nil
		assert(v8)
		local v9 = p7 ~= nil
		assert(v9)
		p6:SetAttribute(v_u_1.RADIUS_ATTR_NAME, p7)
	end,
	["setId"] = function(p10, p11)
		-- upvalues: (copy) v_u_1
		local v12 = p10 ~= nil
		assert(v12)
		local v13 = typeof(p11) == "number"
		assert(v13)
		p10:SetAttribute(v_u_1.ID_ATTR_NAME, p11)
	end
}
