-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMIBkNGcmFtZQNuZXcBWQFYAVoHVmVjdG9yMxFnZXRQbGFjZW1lbnRQcmlzbRBnZXRTdGFuZGluZ1ByaXNtAAMJAgAAAAAVpAMCAAAEAICMBAAATQgBeAUAAABbBwgElQYHA3gFBgOMBgAAnwMEAgkCAANNBAF5BgAAAG8FBwBNBgF7CAAAAEw2AAKkAwoAAASQgJ8DBAKCAgMACwMBAwIEAAQAgAKamZmZmZmpPwIAAAAAAADgPwMDAwQCmpmZmZmZyT8DBQMGBAAEkIAABAcBGAAAAAAAAAAAAAAAAQAAAAAAAAAAAQcAAAAACQIAAAAAFaQDAgAABACAjAQAAE0IAXgGAAAAWwcIBZUGBwR4BQYDjAYAAJ8DBAIJAgADTQQBeQcAAABvBQgATQYBewkAAABMNgACpAMLAAAEoICfAwQCggIDAAwDAQMCBAAEAIACmpmZmZmZqT8CAAAAAAAAHkACAAAAAAAA4D8DAwMEAjMzMzMzMy5AAwUDBgQABKCAAAwIARgAAAAAAAAAAAAAAAEAAAAAAAAAAAEPAAAAAAIAAAECAAqjAAAA/wACAAAAAADAAQAAMAEAwwEAAADAAQIAMAEALQMAAACCAAIABAYAAwcGAQMIAgABAQABGAABAAIAAAgAAAgBAAAAAAKsnJr+kh04op5Y8GrOi8gRC+GUVRAFJh3D7730C3AeodiKGJVOnOtb

-- Decompiled by Krnl

return {
	["getPlacementPrism"] = function(p1, p2)
		local v3 = p1 * CFrame.new(0, p2.Y * 0.5 + 0.05 - 0.05, 0)
		local v4 = p2.X
		local v5 = p2.Z
		return v3, Vector3.new(v4, 0.2, v5)
	end,
	["getStandingPrism"] = function(p6, p7)
		local v8 = p6 * CFrame.new(0, p7.Y * 0.5 + 7.5 - 0.05, 0)
		local v9 = p7.X
		local v10 = p7.Z
		return v8, Vector3.new(v9, 15.1, v10)
	end
}
