-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMYDHNldG1ldGF0YWJsZQNuZXcFX21haWQEX29iahFnZXRQbGFjZW1lbnRQcmlzbQZDRnJhbWUEU2l6ZRFHZXRQbGFjZW1lbnRQcmlzbRBnZXRTdGFuZGluZ1ByaXNtEEdldFN0YW5kaW5nUHJpc20GYXNzZXJ0B0Rlc3Ryb3kEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUDU3RkBE1haWQMU3VyZmFjZVV0aWxzBnNjcmlwdAZQYXJlbnQHX19pbmRleAdTdXJmYWNlC19fQ2xhc3NOYW1lAAUFAQIAAAAS/wECAAAAAAD7BAAAnj0BBAQAAABSAwEApAIBAAAAAECfAgMB+wMBAE0CA+8CAAAAnwIBAjACAcEDAAAAMAABbgQAAACCAQIABQMBBAAAAEADAgMDAwQACgIBGAAAAQAAAAAAAAIAAAAAAAEAAgsAAAAABQEBAAAADfsCAABNAQLDAAAAAE0DAG4BAAAATQIDhQIAAABNBABuAQAAAE0DBC8DAAAAnwEDAIIBAAAEAwUDBAMGAwcAEwgBGAAAAAAAAAAAAAAAAAAUAAAAAAUBAQAAAA37AgAATQECLQAAAABNAwBuAQAAAE0CA4UCAAAATQQAbgEAAABNAwQvAwAAAJ8BAwCCAQAABAMJAwQDBgMHABYKARgAAAAAAAAAAAAAAAAAFwAAAAAEAQAAAAARTQEAwQAAAABHAQIAAAAAgKkDAAGpAwEAuwEDAqQCAgAAABBAnwICAcYCAAAwAgDBAAAAALwCAVADAAAAnwICAYIAAQAEAwMDCwQAABBAAwwAGQwBGAAAAQAAAAAAAAABAAABAAABGgAAAAAGAAABAgAvowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAoQYAAABNAgN2BwAAAJ8BAgKkAgUAAABAQKQFCgAAAJBATQQFJAsAAABNAwQDCAAAAJ8CAgL/AwQAAAAAADADA24MAAAAbwQNADAEA+UOAAAAwAQPABIAAwASAAEAMAQD7xAAAADABBEAEgACADAEAyMSAAAAwAQTABIAAgAwBAMNFAAAAMAEFQAwBANQFgAAAIIDAgAXAw0EAAAAQAMOAw8DEAQAAEBAAxEDEgMTAxQEAACQQAMVAxYDFwMYBgADAgYBAwgGAgMKBgMDDAQAAQIDAQABGAABAAAAAAABAAAAAAAAAgAAAAAAAAAAAgABAAEAAAEAAAAACQAAAAMAAAADAAAHAQAAAAAEH1Olzzf3NK4tl89bOP0Y1J1Obr22+henapKkytk0i3FXc0/J71WgHA==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.Maid)
local v_u_3 = require(script.Parent.SurfaceUtils)
local v_u_4 = {}
v_u_4.__index = v_u_4
v_u_4.__ClassName = "Surface"
function v_u_4.new(p5)
	-- upvalues: (copy) v_u_4, (copy) v_u_2
	local v6 = {}
	local v7 = v_u_4
	setmetatable(v6, v7)
	v6._maid = v_u_2.new()
	v6._obj = p5
	return v6
end
function v_u_4.GetPlacementPrism(p8)
	-- upvalues: (copy) v_u_3
	return v_u_3.getPlacementPrism(p8._obj.CFrame, p8._obj.Size)
end
function v_u_4.GetStandingPrism(p9)
	-- upvalues: (copy) v_u_3
	return v_u_3.getStandingPrism(p9._obj.CFrame, p9._obj.Size)
end
function v_u_4.Destroy(p10)
	local v11 = p10._maid
	local v12 = v11 ~= nil
	assert(v12)
	p10._maid = nil
	v11:Destroy()
end
return v_u_4
