-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNbEHVwZGF0ZVNjcmVlblRleHQAC09iamVjdExvY2FsC0xvY2FsUGxheWVyCVBsYXllckd1aQZWb2x1bWUGY2FuY2VsBWRlbGF5B2FuZFRoZW4NT25DbGllbnRFdmVudAdDb25uZWN0A25ldwVfbWFpZARpbml0Cm51bUVudHJpZXMFcHJvcHMKZGF0YUZvbGRlcgtHZXRDaGlsZHJlbghzZXRTdGF0ZQZfZmV0Y2gKQ2hpbGRBZGRlZAhHaXZlVGFzawxDaGlsZFJlbW92ZWQIZGlkTW91bnQEdGltZQZpcGFpcnMEVGltZQxHZXRBdHRyaWJ1dGUGdHlwZW9mBm51bWJlchV0aW1lIHdhcyBub3QgYSBudW1iZXIGYXNzZXJ0BG1hdGgFZmxvb3IEbmFtZQZ1c2VySWQHbWVzc2FnZQVWYWx1ZQROYW1lCHRvbnVtYmVyDCVkOiUwMmQuJTAzZAZmb3JtYXQFdGFibGUGaW5zZXJ0BHNvcnQKU3VyZmFjZUd1aQxSZXNldE9uU3Bhd24OWkluZGV4QmVoYXZpb3IKU2l6aW5nTW9kZQ1QaXhlbHNQZXJTdHVkB0Fkb3JuZWUERW51bQdTaWJsaW5nFFN1cmZhY2VHdWlTaXppbmdNb2RlB2Fkb3JuZWUFQm9hcmQHZW50cmllcwZyZW5kZXIKRG9DbGVhbmluZwt3aWxsVW5tb3VudAd1bm1vdW50BW1vdW50CEJvYXJkR3VpDHNldG1ldGF0YWJsZRRvYnNlcnZlT25lQ2hpbGROYW1lZAZQYXJlbnQERGF0YQdEZXN0cm95BGdhbWUHUGxheWVycwpHZXRTZXJ2aWNlEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUFUm9hY3QNY3JlYXRlRWxlbWVudANTdGQETWFpZAZCaW5kZXIHUHJvbWlzZQVBdWRpbw9SeEluc3RhbmNlVXRpbHMJUmFjZVRyYWNrAlVJDFRyYWNrU2VydmljZQx3YWl0Rm9yQ2hpbGQTUmFjZVRyYWNrU2NyZWVuVGV4dA1QdXJlQ29tcG9uZW50BmV4dGVuZAdfX2luZGV4DlJhY2VUcmFja0JvYXJkBVN0YXJ0ABACAAEAAAAG+wEAAE0AAaMAAAAAbwEBAJ8AAgGCAAEAAgMBAwIAGQABGAAAAAAAARoAAAAABgEFAAAAJ/sCAABNAQKjAAAAAFICAACfAQIB+wIBAE0BAtEBAAAA+wQCAE0DBDECAAAATQIDmQMAAABvAwQA4gQGAG8FBwAwBQRLBQAAAJ8BBAH7AQMADgEGAPsBAwC8AQGBCAAAAJ8BAgHGAQAA3gEDAPsCBABNAQK+CQAAAIwCAwCfAQICwAMKABICAAC8AQG1CwAAAJ8BAwLeAQMAggABAAwDAQMDAwQDBQIAABBPNZz5QQMGBQEFApqZmZmZmek/AwcDCAYAAwkBABEAARgAAAAAAAEAAAAAAAAAAAAAAAAAAQABAAAAAQADAAAAAAAAAAAAAAMSAAAAAAUBBAAAAA7GAQAATQIAjAAAAADZBAAAEgIAABICAQASAgIAEgEB/xICAwC8AgLHAQAAAJ8CAwHBAQAAggABAAIDCgMLAQEPAAEYAAEAAAAAAAAAAAAADAAQAAAAAAMBAQAAAAf7AgAATQEC7wAAAACfAQECMAEAwQEAAACCAAEAAgMMAw0AIA4BGAAAAAAAAAEhAAAAAAcBAAAAAA/iAwEATQYABwIAAABNBQYSAwAAALwFBWgEAAAAnwUCAhwEBQAwBAMcAAAAALwBACoFAAAAnwEDAYIAAQAGAw8FAQADEAMRAxIDEwAjFAEYAAEAAAAAAAAAAAD/AAADJAAAAAACAAEAAAAF+wAAALwAAL0AAAAAnwACAYIAAQABAxQAKgABGAAAAAABKwAAAAACAAEAAAAF+wAAALwAAL0AAAAAnwACAYIAAQABAxQALQABGAAAAAABLgAAAAAGAQAAAAAkvAEAvQAAAACfAQIBTQEAwQEAAABNBQAHAgAAAE0EBRIDAAAATQMEawQAAADZBQAAEgAAALwDA8cFAAAAnwMDALwBAf0GAAAAnwEAAU0BAMEBAAAATQUABwIAAABNBAUSAwAAAE0DBL0HAAAA2QUBABIAAAC8AwPHBQAAAJ8DAwC8AQH9BgAAAJ8BAAGCAAEACAMUAw0DEAMRAxUDCwMWAxcCBQYoGAEYAAAAAQAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAADKQAAAAAFAgAAAAAJTQMAagAAAABNBAFqAAAAALcDAgAEAAAAqQIAAakCAQCCAgIAAQMZAEEAARgAAAAAAAAAAABCAAAAABMBAgAABwAAAQMORAJ4/wEAAAAAAACkAgEAAAAAQE0EAAcCAAAATQMEEgMAAAC8AwNoBAAAAJ8DAgCfAgAEUQJCAG8JBQC8BwYSBgAAAJ8HAwK7LAcDUgsHAKQKCAAAAHBAnwoCAvAKAgAJAAAAqQkAAakJAQCBAQkECgAAAG8KCgCkCAwAAACwQJ8IAwEhCgcOPgkKDbsMCQKkCBEAAEDwgJ8IAgIhCwcNPgoLErsMCgKkCREAAEDwgJ8JAgIhCwcSuwwLAqQKEQAAQPCAnwoCAuINFwBNDgbsGAAAADAODVoTAAAATQ8GuhkAAAC7Pg8CpA4bAAAAoEGfDgICMA4NhhQAAAAwBw1qFQAAAG8OHABSEAgAUhEJAFISCgC8Dg6NHQAAAJ8OBQIwDg2YFgAAAJ40AQQNAAAAUgwBAKQLIAAAfOCBnwsDAW4Cvf8CAACApAIiAACE4IFSAwEAwAQjAJ8CAwH7AgAAbwMkAOIEKgCpBQAAMAUEpCUAAACkBS0ALJiwwjAFBHsmAAAApAUvACi4sMIwBQRpJwAAAIwFUAAwBQR/KAAAAE0GAAcCAAAATQUGNDAAAAAwBQQUKQAAAOIFMgD7BgAA+wcBAOIINAAwAQg3MwAAAJ8GAwIwBgXzMQAAAJ8CBACCAgAANQMaBAAAAEADEAMRAxIDGwMcAx0EAABwQAMeAx8DIAQAALBAAgAAAAAATO1AAgAAAABAd0tBAyEDIgQAQPCAAgAAAAAAQI9AAyMDJAMZAyUFBBMUFRYDJgMnAygEAACgQQMpAyoDKwMsBAB84IEDLQQAhOCBBggDLgMvAzADMQMyAzMFBSUmJygpAzQDNQQsmLDCAzYEKLiwwgM3AzgFATEDOQUBMwEIMToBGAAAAQAAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAQAAAAAAAQAAAAAAAQAAAAACAQAAAAEAAAAAAAAAAQABAAAAAAAAAAAAAAD8AAD5AA4AAAAAAwAAAQAAAQAAAAEAAAABAAABAAAAAAABAQAAAQD/AAD5ADIAAAAAAwEAAAAABk0BAMEAAAAAvAEBUQEAAACfAQIBggABAAIDDQM7AFA8ARgAAAAAAAFRAAAAAAIAAgAAAAb7AQAATQABEgAAAAD7AQEAnwACAYIAAQABAz0AZgABGAAAAAAAAWcAAAAABwIFAAAAGvsDAABNAgPkAAAAAPsDAQD7BAIA4gUDAPsGAwAwBgU0AQAAADAABRICAAAAnwMDAvsGBABNBQYxBAAAAE0EBZkFAAAAbwUGAJ8CBALZBQAAEgIAABIAAgC8AwH9BwAAAJ8DAwGCAAEACAM+AzcDEQUCAQIDBAMFAz8DFgELXAABGAAAAAEAAAEAAAEA/gQAAAAAAfoIAAAAAAADXgAAAAAIAQcAAAAk/wEBAAAAAAD7BAAAnj0BBAQAAABSAwEApAIBAAAAAECfAgMB+wMBAE0CA+8CAAAAnwIBAjACAcEDAAAATQIBwQMAAAD7BQIATQQF6gQAAABNBgAkBQAAAE0FBiQFAAAAbwYGANkHAAASAgMAEgIEABICBQASAAAAEgIGAJ8EBAC8AgL9BwAAAJ8CAAGCAQIACANABAAAAEADDAMNA0EDQgNDAxYBDFcMARgAAAEAAAAAAAACAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAA9YAAAAAAMBAAAAAAZNAQDBAAAAALwBAVABAAAAnwECAYIAAQACAw0DRABtRAEYAAAAAAABbgAAAAAQAAABAgCGAaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQEAAAAAQG8DBAC8AQEWAwAAAJ8BAwKkAgYAAABQQE0DASEHAAAAnwICAk0DAsoIAAAApAQGAAAAUEBNBgGhCQAAAE0FBnYKAAAAnwQCAqQFBgAAAFBATQcBoQkAAABNBgd/CwAAAJ8FAgKkBgYAAABQQE0IAaEJAAAATQcIcgwAAACfBgICpAcGAAAAUEBNCQGhCQAAAE0ICdINAAAAnwcCAqQIBgAAAFBATQoBoQkAAABNCQpSDgAAAJ8IAgKkCQYAAABQQE0MAYQPAAAATQsMXBAAAABNCgvzEQAAAJ8JAgKkCgYAAABQQE0MAYQPAAAATQsMrRIAAACfCgICTQsI8xMAAABSDAEAbw0UAJ8LAwLADRUAEgAKABIABwASAAAAEgAGALwLC7UWAAAAnwsDAU0LAvgXAAAAbw0RALwLC5wYAAAAnwsDAsAMGQASAAQAMAwLExoAAADADBsAMAwLvRwAAADADB0AMAwLah4AAADADB8AEgADABIACQAwDAuAIAAAAMAMIQAwDAs0IgAAAP8MAwAAAAAAMAwMbiMAAADADSQAEgAMABIABAASAAgAEgACABIAAwASAAsAEgAAADANDO8lAAAAwA0mADANDFAnAAAATQ0F7yUAAABvDigAUg8MAJ8NAwK8Dg0cKQAAAJ8OAgGCAAEAKgNFBAAAAEADRgNHA0gDSQQAAFBAA0oDSwNMA00DTgNPA1ADUQNSA1MDOANUA1UDVgYCAwkDVwNYBgMDDgYEAxQGBwMYBgkDOgYKAzwDWQYNAwwGDgNEA1oDWwgCAwQHCQoNDgEAARgAAQAAAAAAAQAAAAAAAQAAAAABAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAgAAAAAAAAAAAgAAAAAAAAEAAAAAAAAAAAAAAAAQAAAAAAABAAAAAwAABQAACQAAAAAfAAAEAAEAAgAAAAAAAAAAABYAAAMAAAAAAQAAAQEAAAAADzWaDmff5PaGB15k87CR0dveFDqQilyEboTVi5vEqo1pLGwxWp1mBMA=

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players")
local v2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v2.Roact)
local v_u_4 = v_u_3.createElement
local v_u_5 = require(v2.Std.Maid)
local v6 = require(v2.Std.Binder)
local v_u_7 = require(v2.Std.Promise)
local v_u_8 = require(v2.Std.Audio)
local v_u_9 = require(v2.Std.RxInstanceUtils)
local v_u_10 = require(v2.RaceTrack.UI.Board)
local v_u_11 = require(v2.RaceTrack.TrackService)
v_u_9.waitForChild(v2, "RaceTrackScreenText"):andThen(function(p12)
	-- upvalues: (copy) v_u_11, (copy) v_u_8, (copy) v_u_1, (copy) v_u_7
	local v_u_13 = nil
	p12.OnClientEvent:Connect(function(p14)
		-- upvalues: (ref) v_u_11, (ref) v_u_8, (ref) v_u_1, (ref) v_u_13, (ref) v_u_7
		v_u_11.updateScreenText(p14)
		v_u_8.ObjectLocal(v_u_1.LocalPlayer.PlayerGui, 6874682609, {
			["Volume"] = 0.8
		})
		if v_u_13 then
			v_u_13:cancel()
			v_u_13 = nil
		end
		v_u_13 = v_u_7.delay(3):andThen(function()
			-- upvalues: (ref) v_u_11
			v_u_11.updateScreenText("")
		end)
	end)
end)
local v_u_15 = v_u_3.PureComponent:extend("Board")
function v_u_15.init(p16)
	-- upvalues: (copy) v_u_5
	p16._maid = v_u_5.new()
end
function v_u_15._fetch(p17)
	p17:setState({
		["numEntries"] = #p17.props.dataFolder:GetChildren()
	})
end
function v_u_15.didMount(p_u_18)
	p_u_18:_fetch()
	p_u_18._maid:GiveTask(p_u_18.props.dataFolder.ChildAdded:Connect(function()
		-- upvalues: (copy) p_u_18
		p_u_18:_fetch()
	end))
	p_u_18._maid:GiveTask(p_u_18.props.dataFolder.ChildRemoved:Connect(function()
		-- upvalues: (copy) p_u_18
		p_u_18:_fetch()
	end))
end
function v_u_15.render(p19)
	-- upvalues: (copy) v_u_4, (copy) v_u_10
	local v20 = {}
	for _, v21 in ipairs(p19.props.dataFolder:GetChildren()) do
		local v22 = v21:GetAttribute("Time")
		local v23 = typeof(v22) == "number"
		assert(v23, "time was not a number")
		local v24 = v22 % 3600000 / 60000
		local v25 = math.floor(v24)
		local v26 = v22 % 60000 / 1000
		local v27 = math.floor(v26)
		local v28 = v22 % 1000
		local v29 = math.floor(v28)
		local v30 = {
			["name"] = v21.Value
		}
		local v31 = v21.Name
		v30.userId = tonumber(v31)
		v30.time = v22
		v30.message = ("%d:%02d.%03d"):format(v25, v27, v29)
		table.insert(v20, v30)
	end
	table.sort(v20, function(p32, p33)
		return p32.time < p33.time
	end)
	return v_u_4("SurfaceGui", {
		["ResetOnSpawn"] = false,
		["ZIndexBehavior"] = Enum.ZIndexBehavior.Sibling,
		["SizingMode"] = Enum.SurfaceGuiSizingMode.PixelsPerStud,
		["PixelsPerStud"] = 80,
		["Adornee"] = p19.props.adornee
	}, {
		["Board"] = v_u_4(v_u_10, {
			["entries"] = v20
		})
	})
end
function v_u_15.willUnmount(p34)
	p34._maid:DoCleaning()
end
local v_u_35 = {}
v_u_35.__index = v_u_35
function v_u_35.new(p_u_36)
	-- upvalues: (copy) v_u_35, (copy) v_u_5, (copy) v_u_9, (copy) v_u_3, (copy) v_u_4, (copy) v_u_15, (copy) v_u_1
	local v37 = {}
	local v38 = v_u_35
	setmetatable(v37, v38)
	v37._maid = v_u_5.new()
	v37._maid:GiveTask(v_u_9.observeOneChildNamed(p_u_36.Parent.Parent, "Data", function(p39, p40)
		-- upvalues: (ref) v_u_3, (ref) v_u_4, (ref) v_u_15, (copy) p_u_36, (ref) v_u_1
		local v41 = {
			["adornee"] = p_u_36,
			["dataFolder"] = p39
		}
		local v_u_42 = v_u_3.mount(v_u_4(v_u_15, v41), v_u_1.LocalPlayer.PlayerGui, "BoardGui")
		p40:GiveTask(function()
			-- upvalues: (ref) v_u_3, (copy) v_u_42
			v_u_3.unmount(v_u_42)
		end)
	end))
	return v37
end
function v_u_35.Destroy(p43)
	p43._maid:Destroy()
end
v6.new("RaceTrackBoard", v_u_35):Start()
