-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMpD191cGRhdGVTcGlubmluZwNuZXcMc2V0bWV0YXRhYmxlCG1hbmlmZXN0BF9wb3MEX3ZlbARtYWlkEUVOQUJMRURfQVRUUl9OQU1FGUdldEF0dHJpYnV0ZUNoYW5nZWRTaWduYWwHQ29ubmVjdAhHaXZlVGFzawhfZmFkZU91dAppbm5lck1vZGVsA29iaghHZXRQaXZvdAZDRnJhbWUGQW5nbGVzB1Bpdm90VG8EbWF0aANhYnMIc3Bpbm5pbmcMR2V0QXR0cmlidXRlD0FDQ0VMX0FUVFJfTkFNRRJEUkFHX1BDVF9BVFRSX05BTUUJSGVhcnRiZWF0BGdhbWUKUnVuU2VydmljZQpHZXRTZXJ2aWNlEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUDU3RkCkJhc2VPYmplY3QFRG9vcjIKRG9vckNvbnN0cw5NYW5pZmVzdEJpbmRlcgZzY3JpcHQGUGFyZW50DVNwaW5uZXJDb25zdHMHX19pbmRleAhUQUdfTkFNRRBJTk5FUl9NT0RFTF9OQU1FAAUCAAEAAAAF+wAAALwAAMoAAAAAnwACAYIAAQABAwEAFgABGAAAAAABFwAAAAAJAgMAAAAr+wMAAE0CA+8AAAAAUgMAAJ8CAgL7BQEAnj0CBAUAAABSBAIApAMCAAAAEECfAwMBMAECSAMAAACMAwAAMAMCcwQAAACMAwAAMAMCKwUAAAC8AwLKBgAAAJ8DAgFNAwIWBwAAAPsIAgBNBwinCAAAALwFABYJAAAAnwUDAtkHAAASAAIAvAUFxwoAAACfBQMAvAMD/QsAAACfAwABqQMAADADAl8MAAAAggICAA0DAgMDBAAAEEADBAMFAwYDAQMHAwgDCQMKAwsDDAEADgIBGAAAAAAAAQAAAAAAAAIAAQAAAQAAAQAAAQAAAAAAAAAAAAAAAAAAAAMAAAIPAAAAAAkBAwAAAEv7AgAATQECXwAAAAArAQkA+wEAAE0CASsBAAAA+wUBAFsEBQIJAwQAQwICAzACASsBAAAA+wEAAE0CASsBAAAA+wQCAPUDAgQJAgIDMAIBKwEAAAD7AQAATQIBcwMAAAD7BQAATQQFKwEAAAAJAwQAQwICAzACAXMDAAAA+wMAAE0CA0gEAAAATQEC3gUAAAD7BQAATQQFEwYAAAC8BARSBwAAAJ8EAgKkBQoAACSAgIwGAAD7CAAATQcIcwMAAACMCAAAnwUEAgkDBAW8AQHCCwAAAJ8BAwH7AgAATQECXwAAAAAOARAA+wMAAE0CAysBAAAAuwICAqQBDgAANMCAnwECAm8CDwBgAQcAAgAAAPsCAABNAQIWEAAAAMYCAAAwAgFKEQAAAIIAAQASAwwDBgIAAAAAAADwPwMFAwQDDQMOAw8DEAMRBAAkgIADEgMTAxQEADTAgAKamZmZmZm5PwMHAxUAJQABGAAAAAABAAAAAAAAAAACAAAAAAAAAAEAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAQAAAAAAAiYAAAAACAECAAAANU0CABMAAAAA+wUAAE0EBacBAAAAvAICEgIAAACfAgMCKgICAAEAAACpAQABqQEBAA4BJABNAwATAAAAAPsGAABNBQbtBAAAALwDAxICAAAAnwMDApACAwNNBAATAAAAAPsHAABNBgd+BgAAALwEBBICAAAAnwQDApADBAWpBAAAMAQAXwcAAABNBAAWCAAAAPsGAQBNBQb9CQAAANkHAAASAAAAEgACABIAAwC8BQXHCgAAAJ8FAwIwBQRKCwAAAIIAAQCpAgEAMAIAXwcAAACCAAEADAMOAwgDFgIAAAAAAADwPwMXApqZmZmZmak/AxgDDAMHAxkDCgMVAQIdAQEYAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAEAAAAAAAAAAAMAAAEAAAAAAAAAAAAAAAAAAA0AAAIeAAAAAAsAAAECAEujAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIGAAAAUEBNBAGhBwAAAE0DBEsIAAAAnwICAqQDBgAAAFBATQUBpQkAAABNBAXfCgAAAJ8DAgKkBAYAAABQQE0FAYkLAAAAnwQCAqQFBgAAAFBApAgNAAAAwEBNBwgkDgAAAE0GB88PAAAAnwUCAv8GAwAAAAAAMAYGbhAAAACePQYFAgAAAFIIBgBSCQIApAcSAAAAEEGfBwMBwAcTABIAAgASAAYAEgAFADAHBu8UAAAAwAcVABIABQASAAAAMAcGyhYAAABNBwTvFAAAAE0IBbQXAAAA4gkZAE0KA0kaAAAAMAoJ3hgAAABSCgYAnwcEAIIHAAAbAxoEAAAAQAMbAxwDHQMeBAAAUEADHwMgAyEDIgMjAyQEAADAQAMlAyYDJwMDBAAAEEEGAQMCBgMDAQMoAw0FARgDKQIBAwEAARgAAQAAAAAAAQAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAIAAAAAAAAAAAIAAQABAAAAAAAAAgAAAAAADwAAAAAZAAAAAAEAAAAB/gABAAAAAATiWJeznFqzRtCc/SewhfDYZch5HIS2jguVsVR1YxaB726h9xmNpbw3

-- Decompiled by Krnl

local v_u_1 = game:GetService("RunService")
local v2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v2.Std.BaseObject)
local v4 = require(v2.Door2.DoorConsts)
local v5 = require(v2.ManifestBinder)
local v_u_6 = require(script.Parent.SpinnerConsts)
local v_u_7 = {}
v_u_7.__index = v_u_7
setmetatable(v_u_7, v_u_3)
function v_u_7.new(p8, p9)
	-- upvalues: (copy) v_u_3, (copy) v_u_7, (copy) v_u_6
	local v_u_10 = v_u_3.new(p8)
	local v11 = v_u_7
	setmetatable(v_u_10, v11)
	v_u_10.manifest = p9
	v_u_10._pos = 0
	v_u_10._vel = 0
	v_u_10:_updateSpinning()
	v_u_10.maid:GiveTask(p8:GetAttributeChangedSignal(v_u_6.ENABLED_ATTR_NAME):Connect(function()
		-- upvalues: (copy) v_u_10
		v_u_10:_updateSpinning()
	end))
	v_u_10._fadeOut = false
	return v_u_10
end
function v_u_7._updateSpinning(p_u_12)
	-- upvalues: (copy) v_u_6, (copy) v_u_1
	if p_u_12.obj:GetAttribute(v_u_6.ENABLED_ATTR_NAME) == true then
		local v_u_13 = p_u_12.obj:GetAttribute(v_u_6.ACCEL_ATTR_NAME) or 1
		local v_u_14 = p_u_12.obj:GetAttribute(v_u_6.DRAG_PCT_ATTR_NAME) or 0.05
		p_u_12._fadeOut = false
		p_u_12.maid.spinning = v_u_1.Heartbeat:Connect(function(p15)
			-- upvalues: (copy) p_u_12, (copy) v_u_13, (copy) v_u_14
			if not p_u_12._fadeOut then
				local v16 = p_u_12
				v16._vel = v16._vel + v_u_13 * 1 * p15
			end
			local v17 = p_u_12
			v17._vel = v17._vel * (1 - v_u_14)
			local v18 = p_u_12
			v18._pos = v18._pos + p_u_12._vel * p15
			p_u_12.manifest.innerModel:PivotTo(p_u_12.obj:GetPivot() * CFrame.Angles(0, p_u_12._pos, 0))
			if p_u_12._fadeOut then
				local v19 = p_u_12._vel
				if math.abs(v19) < 0.1 then
					p_u_12.maid.spinning = nil
				end
			end
		end)
	else
		p_u_12._fadeOut = true
	end
end
return v5.new(v_u_6.TAG_NAME, {
	["innerModel"] = v4.INNER_MODEL_NAME
}, v_u_7)
