-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMODGNhdGVnb3J5TmFtZRVtaXNzaW5nIGNhdGVnb3J5IE5hbWUGYXNzZXJ0C3NldENhdGVnb3J5B3NldFBhZ2UEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUFUm9kdXgEU2FsZQpTYWxlQ29uc3RzDWNyZWF0ZVJlZHVjZXINQ0FURUdPUllfTkFNRQADBQIAAAAAD00EAb4AAAAARwQCAAAAAICpAwABqQMBAIEBAwQBAAAAbwQBAKQCAwAAACBAnwIDAU0CAb4AAAAAggICAAQDAQMCAwMEAAAgQAAHBAEYAAAAAAAAAAAAAAAAAQABCAAAAAADAgAAAAAHTQIBvgAAAAAOAgMATQIBvgAAAACCAgIAggACAAEDAQAMBQEYAAAAAQAAAg0AAAAABwAAAQIAIKMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0CAKcGAAAAnwECAqQCBQAAAEBATQQA+AcAAABNAwQNCAAAAJ8CAgJNAwHWCQAAAE0EApgKAAAA4gUNAMAGDgAwBgVECwAAAMAGDwAwBgU4DAAAAJ8DAwCCAwAAEAMGBAAAAEADBwMIAwkEAABAQAMKAwsDDAMNAw4DBAMFBQILDAYABgECAAEBAAEYAAEAAAAAAAEAAAAAAQAAAAAAAAIAAAAAAQAABQAA+gABAAAAAAKD1tWgjyzPprESvzQyO+HjM/BBWxVaQLo31tiiVbBA5Xc7tuXdAyE3

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v2 = require(v1.Rodux)
local v3 = require(v1.Sale.SaleConsts)
return v2.createReducer(v3.CATEGORY_NAME, {
	["setCategory"] = function(_, p4)
		local v5 = p4.categoryName ~= nil
		assert(v5, "missing category Name")
		return p4.categoryName
	end,
	["setPage"] = function(p6, p7)
		if p7.categoryName then
			return p7.categoryName
		else
			return p6
		end
	end
})
