-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMRCGNhdGVnb3J5EG1pc3NpbmcgY2F0ZWdvcnkGYXNzZXJ0BG5hbWUMbWlzc2luZyBuYW1lCWZhdm9yaXRlZBFtaXNzaW5nIGZhdm9yaXRlZAVwYWlycxhzZXRDYXRlZ29yeUl0ZW1GYXZvcml0ZWQXbWlzc2luZyBmYXZvcml0ZWQgdGFibGUPc2V0RmF2b3JpdGVkUmF3BGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlBVJvZHV4DWNyZWF0ZVJlZHVjZXIAAwgCAAAAAEBNBAFrAAAAAEcEAgAAAACAqQMAAakDAQCBAQMEAQAAAG8EAQCkAgMAAAAgQJ8CAwFNBAFaBAAAAEcEAgAAAACAqQMAAakDAQCBAQMEBQAAAG8EBQCkAgMAAAAgQJ8CAwFNBAFQBgAAAEcEAgAAAACAqQMAAakDAQCBAQMEBwAAAG8EBwCkAgMAAAAgQJ8CAwH/AgAAAAAAAKQDCQAAAIBAUgQAAJ8DAgQXAwEAagcCBm4D/v8CAAAATQQBawAAAACHAwIEKwMFAE0DAWsAAAAA/wQAAAAAAABqBAIDTQQBawAAAACHAwIETQQBWgQAAABNBQFQBgAAAGoFAwSCAgIACgMBAwIDAwQAACBAAwQDBQMGAwcDCAQAAIBAAAYJARgAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAACAAEAAAAAAf8AAwAAAAEAAAAAAgAAAAAAAAABBwAAAAAFAgAAAAAPTQQBUAAAAABHBAIAAAAAgKkDAAGpAwEAgQEDBAEAAABvBAEApAIDAAAAIECfAgMBTQIBUAAAAACCAgIABAMGAwoDAwQAACBAABULARgAAAAAAAAAAAAAAAABAAAWAAAAAAYAAAECABmjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAgCnBgAAAJ8BAgJNAgHWBwAAAP8DAAAAAAAA4gQKAMAFCwAwBQR9CAAAAMAFDAAwBQRzCQAAAJ8CAwCCAgAADQMMBAAAAEADDQMOAw8EAABAQAMQAxEDCQMLBQIICQYABgECAAEBAAEYAAEAAAAAAAEAAAAAAgAAAAABAAAPAADwAAEAAAAAAupGEYLiBPjx2IJ7FqK6FwyGj8PNy7RqlA8uKulo2jmA3vbjQvbVUOk=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Rodux).createReducer({}, {
	["setCategoryItemFavorited"] = function(p2, p3)
		local v4 = p3.category ~= nil
		assert(v4, "missing category")
		local v5 = p3.name ~= nil
		assert(v5, "missing name")
		local v6 = p3.favorited ~= nil
		assert(v6, "missing favorited")
		local v7 = {}
		for v8, v9 in pairs(p2) do
			v7[v8] = v9
		end
		if not v7[p3.category] then
			v7[p3.category] = {}
		end
		v7[p3.category][p3.name] = p3.favorited
		return v7
	end,
	["setFavoritedRaw"] = function(_, p10)
		local v11 = p10.favorited ~= nil
		assert(v11, "missing favorited table")
		return p10.favorited
	end
})
