-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMOAmlkCm1pc3NpbmcgaWQGYXNzZXJ0B3NldFNvcnQEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUFUm9kdXgGc2NyaXB0BlBhcmVudAhFbnVtU29ydA1jcmVhdGVSZWR1Y2VyB1BvcHVsYXIAAgUCAAAAAA9NBAH0AAAAAEcEAgAAAACAqQMAAakDAQCBAQMEAQAAAG8EAQCkAgMAAAAgQJ8CAwFNAgH0AAAAAIICAgAEAwEDAgMDBAAAIEAACAQBGAAAAAAAAAAAAAAAAAEAAAkAAAAABwAAAQIAH6MAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0CAKcGAAAAnwECAqQCBQAAAEBApAUIAAAAcEBNBAUkCQAAAE0DBBwKAAAAnwICAk0DAdYLAAAATQQCSgwAAADiBQ4AwAYPADAGBdQNAAAAnwMDAIIDAAAQAwUEAAAAQAMGAwcDCAQAAEBAAwkDCgQAAHBAAwsDDAMNAw4DBAUBDQYAAQABAAEYAAEAAAAAAAEAAAAAAgAAAAAAAAAAAgAAAAABAAD/AAEAAAAAAR8AsaVwxfN6LcTbMY/x8F7oEjSXI06p5aMuTKkcCbKF38sV5J2qK0o=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v2 = require(v1.Rodux)
local v3 = require(script.Parent.EnumSort)
return v2.createReducer(v3.Popular, {
	["setSort"] = function(_, p4)
		local v5 = p4.id ~= nil
		assert(v5, "missing id")
		return p4.id
	end
})
