-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNKD2dldE5leHRTYWxlVGltZQ1vblNhbGVSZWZyZXNoBEZpcmUdaXNWZWhpY2xlQ3VzdG9taXphdGlvbkxpbWl0ZWQETm9uZQVQcmljZQpOb0dhcmFnZVVJH2NhblZlaGljbGVDdXN0b21pemF0aW9uR29PblNhbGUQaXNWZWhpY2xlTGltaXRlZA9FeGNsdWRlRnJvbVNhbGUSY2FuVmVoaWNsZUdvT25TYWxlB1BvaW50ZXIKU29ydE51bWJlcgV0YWJsZQRzb3J0EWdldE51bVNhbGVzUGFzc2VkBlJhbmRvbQNuZXcKTmV4dE51bWJlcg9hcHBseVNlZWRlZFNvcnQKQ0FURUdPUklFUw1DQVRFR09SWV9OQU1FFENPTE9SX0NBVEVHT1JZX1RZUEVTFlRFWFRVUkVfQ0FURUdPUllfVFlQRVMHcmVxdWlyZQRHYW1lBkdhcmFnZQlTdG9yZURhdGEORmluZEZpcnN0Q2hpbGQFSXRlbXMMQ2F0ZWdvcnlOYW1lBmluc2VydAROYW1lBWNsb25lGk5VTV9WRUhJQ0xFX0NVU1RPTUlaQVRJT05TH19nZXRPblNhbGVWZWhpY2xlQ3VzdG9taXphdGlvbnMETWFrZQxOVU1fVkVISUNMRVMSX2dldE9uU2FsZVZlaGljbGVzIl9jYWNoZWRPblNhbGVWZWhpY2xlQ3VzdG9taXphdGlvbnMlX2NhY2hlZE9uU2FsZVZlaGljbGVDdXN0b21pemF0aW9uc01hcBFnZXRUaW1lVG9OZXh0U2FsZQRtYXRoA21pbgR0YXNrBWRlbGF5KGNhY2hlT25TYWxlVmVoaWNsZUN1c3RvbWl6YXRpb25zSWZOZWVkZWQeZ2V0T25TYWxlVmVoaWNsZUN1c3RvbWl6YXRpb25zHGNhdGVnb3J5TmFtZSBtdXN0IG5vdCBiZSBuaWwGYXNzZXJ0GGl0ZW1OYW1lIG11c3Qgbm90IGJlIG5pbBxpc1ZlaGljbGVDdXN0b21pemF0aW9uT25TYWxlFV9jYWNoZWRPblNhbGVWZWhpY2xlcxhfY2FjaGVkT25TYWxlVmVoaWNsZXNNYXAbY2FjaGVPblNhbGVWZWhpY2xlc0lmTmVlZGVkEWdldE9uU2FsZVZlaGljbGVzG3ZlaGljbGVNYWtlIG11c3Qgbm90IGJlIG5pbA9pc1ZlaGljbGVPblNhbGUEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlC1ZlaGljbGVDb25mC1ZlaGljbGVEYXRhBFNhbGUKU2FsZUNvbnN0cwlTYWxlVXRpbHMLR2FyYWdlVXRpbHMJT3duZXJzaGlwD093bmVyc2hpcENvbnN0cwNTdGQGU2lnbmFsCEludGVydmFsBWV2ZXJ5B0Nvbm5lY3QAEQMAAwAAABD7AQAATQAB9gAAAACfAAEC+wIBAJUBAgFgAQgAAAAAAN4AAQD7AgIATQECQAIAAAC8AQHdAwAAAJ8BAgGCAAEABAMBAnsUrkfheoQ/AwIDAwASAAEYAAAAAAEAAAABAQAAAAAAAhMAAAAABAEBAAAAIvsDAABNAgOvAAAAAFIDAACfAgICVgECAA4BGgBNAgA/AQAAAFYBAgAOARYATQIAJAIAAAAOAg4AqQEAAE0CACQCAAAAbwMDAGACCgADAAAATQIAJAIAAACMAwAAtwMCAAIAAACpAQABqQEBAGUAAQCpAQAADgEDAE0CAOUEAAAAVgECAIIBAgAFAwQDBQMGAgAAAACAhC5BAwcAGwgBGAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAEAAAAcAAAAAAQBAQAAACb7AwAATQID6QAAAABSAwAAnwICAlYBAgAOAR4ATQIAPwEAAABWAQIADgEaAE0CACQCAAAADgIOAKkBAABNAgAkAgAAAG8DAwBgAgoAAwAAAE0CACQCAAAAjAMAALcDAgACAAAAqQEAAakBAQBlAAEAqQEAAA4BBwBNAgDlBAAAAFYBAgAOAQMATQIAzgUAAABWAQIAggECAAYDCQMFAwYCAAAAAICELkEDBwMKACELARgAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQAAACIAAAAABwIBAAAADU0EAEUAAAAA+wUAAIcDBAVNBQFFAAAAAPsGAACHBAUGtwMCAAQAAACpAgABqQIBAIICAgABAwwAKgABGAAAAAAAAAAAAAAAAAArAAAAAAUCAAAAAAlNAwAyAAAAAE0EATIAAAAAtwMCAAQAAACpAgABqQIBAIICAgABAw0ANAABGAAAAAAAAAAAADUAAAAACwIBAAAHBAAABQIPAx+kAgIAAAQAgFIDAADZBAAAEgABAJ8CAwH7AwAATQIDWAMAAACfAgECpAMGAAAUQIBSBAIAnwMCAlIEAADGBQAAxgYAAGQEBQC8CQOFBwAAAJ8JAgIwCQgyCAAAAG4E+v8CAAAApAQCAAAEAIBSBQAAwAYJAJ8EAwGCAAEACgMOAw8EAAQAgAMQAxEDEgQAFECAAxMDDQYEAgMEKBQBGAAAAAAAAAUAAAABAAAAAQAAAAEAAAAA/wADAAAAAAMqAAAAABAABgAAAKAB/wAAAAAAAAD/AQAAAAAAAPsFAABNAgX9AAAAAMYDAADGBAAAZAIxAPsIAQBNBwiYAQAAAPEGLQAHAAAA+wkCAE0ICTYCAAAAhwcIBisHJwD7CQIATQgJCQMAAACHBwgGKwciAKQHBQAAAEBA+wsDAE0KC70GAAAATQkKKAcAAABNCAkwCAAAAFIKBgC8CAgDCQAAAJ8IAwCfBwACTQgHOAoAAADGCQAAxgoAAGQICwDiDw0AMAYPXgsAAAAwDA9FDAAAAJ40AAQPAAAAUg4AAKQNEAAAPOCAnw0DAW4I9P8CAAAAqQgBAGoIAQZuAs7/AgAAAIwCAABSAwEAxgQAAMYFAABkAwEAlQICEW4D/v8CAAAA+wMEAFIEAABvBRIAnwMDAf8DAAAAAAAA/wQAAAAAAAD/BQAAAAAAAFIGAADGBwAAxggAAGQGSgBNCwpeCwAAAE0NCkUMAAAA+w8FAE0OD68TAAAAUg8NAJ8OAgJWDA4ADgwaAE0ODT8UAAAAVgwOAA4MFgBNDg0kFQAAAA4ODgCpDAAATQ4NJBUAAABvDxYAYA4KAA8AAABNDg0kFQAAAIwPAAC3DwIADgAAAKkMAAGpDAEAZQABAKkMAAAODAMATQ4N5RcAAABWDA4ADgweAIcMBQsrDBwApAwZAABg4IBNDQpFDAAAAJ8MAgIwCwxeCwAAAJ40AwUMAAAAUg4DAFIPDACkDRAAADzggJ8NAwGHDQQLKw0DAP8NAAAAAAAAag0EC4cNBAtNDwpFDAAAAE0OD7oSAAAAqQ8BAGoPDQ6pDQEAag0FCxwMAwD7DgEATQ0OfxoAAADUDQMADAAAAG4Gtf8CAAAAggMDABsDFQMWAxcDGAMZBAAAQEADGgMbAxwDHQMeAx8DDAUCCwwDDgMgBAA84IACAAAAAAAA8D8DIQMEAwUDBgIAAAAAgIQuQQMHAyIEAGDggAMjADgkARgdAAEAAgAAAAAAAQAAAAAFAAAAAAQAAAAABAAAAAAAAAAAAAAAAAABAAAAAAEBAAEAAAAA/gAA/wAGAOsAFwEAAAAB/wAEAAAAAwABAAEAAQAAAAEAAQC8AAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAABAAAAQQACAAAAAAEAAQAAAAAAAAEAAQAAAgAAAAAAAAEAAgAAAAAA8wARHAAAAAAMAAQAAABc/wAAAAAAAAD7AQAAxgIAAMYDAABkAQkA4ggBADAFCEUAAAAAnjQABAgAAABSBwAApAYEAAAMIICfBgMBbgH2/wIAAAD7AQEAUgIAAG8DBQCfAQMB/wEAAAAAAAD/AgAAAAAAAFIDAADGBAAAxgUAAGQDPABNCQdFAAAAAPsLAgBNCgvpBgAAAFILCQCfCgICVggKAA4IHgBNCgk/BwAAAFYICgAOCBoATQoJJAgAAAAOCg4AqQgAAE0KCSQIAAAAbwsJAGAKCgALAAAATQoJJAgAAACMCwAAtwsCAAoAAACpCAABqQgBAGUAAQCpCAAADggHAE0KCeUKAAAAVggKAA4IAwBNCgnOCwAAAFYICgAOCA4ATQoHRQAAAACeNAEECgAAAFIJAQCkCAQAAAwggJ8IAwFNCQdFAAAAAE0ICa0FAAAAqQkBAGoJAggcCAEA+woDAE0JCoAMAAAA1AkDAAgAAABuA8P/AgAAAIIBAwANAwwFAQADDgMgBAAMIIADJQMJAwUDBgIAAAAAgIQuQQMHAwoDJgBxJwEYUAACAAAAAQEAAAAA/wAA/wAFAAAAAwABAAEAAAABAKMAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAWgAAAAAAAAABAAAAAAACAAAAAAD7AAkiAAAAAAIAAQAAAAn7AAAAxgEAADABADAAAAAA+wAAAMYBAAAwAQDJAQAAAIIAAQACAygDKQCQAQABGAAAAAABAAAAAZEAAAAABQADAAAAH/sBAABNAAEwAAAAAEcAGgAAAACA+wAAAPsBAAD7AgEAnwIBAzACADAAAAAAMAMByQEAAACMATwA+wQCAE0DBCcDAAAAnwMBAngCAwKeEwEDAgAAAKQABgAAFECAnwADAqQBCQAAIHCAUgIAAMADCgASAgAAnwEDAYIAAQALAygDKQIAAAAAAADwPwMqAysDLAQAFECAAy0DLgQAIHCABggBCIsBLwEYAAAAAAABAAEA/wAAAAIAAAAAAAAAAAAAAQAAAAAABYwAAAAAAgACAAAABvsAAACfAAEB+wEBAE0AATAAAAAAggACAAEDKACWATABGAAAAQAAAJcAAAAABwICAAAHBAAABQIDAydHAAIAAAAAgKkDAAGpAwEAgQEDBAAAAABvBAAApAICAAAAEECfAgMBRwECAAAAAICpAwABqQMBAIEBAwQDAAAAbwQDAKQCAgAAABBAnwIDAfsCAACfAgEBqQIAAPsFAQBNBAXJBAAAAIcDBABHAwoAAAAAAPsGAQBNBQbJBAAAAIcEBQCHAwQBKgMCAAEAAACpAgABqQIBAIICAgAFAzEDMgQAABBAAzMDKQCaATQBGAAAAAAAAAAAAAABAAAAAAAAAAAAAQABAAAAAAAAAQAAAAAAAAAAAJsAAAAAAgABAAAACfsAAADGAQAAMAEAggAAAAD7AAAAxgEAADABAH0BAAAAggABAAIDNQM2AKcBAAEYAAAAAAEAAAABqAAAAAAFAAMAAAAf+wEAAE0AAYIAAAAARwAaAAAAAID7AAAA+wEAAPsCAQCfAgEDMAIAggAAAAAwAwF9AQAAAIwBPAD7BAIATQMEJwMAAACfAwECeAIDAp4TAQMCAAAApAAGAAAUQICfAAMCpAEJAAAgcIBSAgAAwAMKABICAACfAQMBggABAAsDNQM2AgAAAAAAAPA/AyoDKwMsBAAUQIADLQMuBAAgcIAGDAEMowE3ARgAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAFpAAAAAACAAIAAAAG+wAAAJ8AAQH7AQEATQABggAAAACCAAIAAQM1AK0BOAEYAAABAAAArgAAAAAFAQIAAAYDAAAFAQMVRwACAAAAAICpAgABqQIBAIEBAgQAAAAAbwMAAKQBAgAAABBAnwEDAfsBAACfAQEB+wQBAE0DBH0DAAAAhwIDACoCAgABAAAAqQEAAakBAQCCAQIABAM5AzIEAAAQQAM2ALEBOgEYAAAAAAAAAAAAAAEAAQAAAAAAAAAAsgAAAAASAAABAgCUAaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0EAL0GAAAATQMEKAcAAABNAgNnCAAAAJ8BAgKkAgUAAABAQE0FAL0GAAAATQQFKAcAAABNAwRVCQAAAJ8CAgKkAwUAAABAQE0FAPgKAAAATQQFDQsAAACfAwICpAQFAAAAQEBNBgD4CgAAAE0FBmYMAAAAnwQCAqQFBQAAAEBATQcAKAcAAABNBgdBDQAAAJ8FAgKkBgUAAABAQE0IAJAOAAAATQcIrA8AAACfBgICpAcFAAAAQEBNCQChEAAAAE0ICR8RAAAAnwcCAqQIBQAAAEBATQoAoRAAAABNCQqsEgAAAJ8IAgL/CQUAAAAAAE0KB+8TAAAAnwoBAjAKCUAUAAAATQoE9hUAAACfCgECTQsIxBYAAACMDAEAnwsCAtkNAAASAAQAEgEK/xIACQC8CwvHFwAAAJ8LAwHBCgAAwAoYABIABQDACxkAEgAFAMAMGgASAAQAwA0bABIAAQASAAMAEgAGABIAAAASAAwAEgAFAMAOHAASAAIAEgAMABIABQASAAMAxg8AADAPCTAdAAAAxg8AADAPCckeAAAAwA8fABIACQASAA0AEgAEAMAQIAASAA8AEgAJADAQCZAhAAAAwBAiABIADwASAAkAMBAJ7iMAAADGEAAAMBAJgiQAAADGEAAAMBAJfSUAAADAECYAEgAJABIADgASAAQAwBEnABIAEAASAAkAMBEJCygAAADAESkAEgAQABIACQAwEQlZKgAAAIIJAgArAzsEAAAAQAM8Az0DGQQAAEBAAxoDGwM+Az8DQANBA0IDQwNEA0UDRgNHA0gDEgMCAwEDSQNKBgEGAgYFBgYGBwMoAykGCQYKAzAGCwM0AzUDNgYNBg4DOAYPAzoMAAECBQYHCQoLDQ4PAQABGAABAAAAAAABAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAADAAIAAAAAAgAAAQAAAAAAAAAAAAAACQAGAAcAEAAAAAAAADkAAAAAGAAAAQAAAQAAAAsAAAAABAAAAAAHAAABAAABAAAACgAAAAAEAAAAAAYBAAAAABCCvhYLg05oELB6fJ/BNW1o9AtSdZo0ifcCYirk4k1V6O/VmczlvPBZ

-- Decompiled by Krnl

local v_u_1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v_u_1.Game.Garage.VehicleConf)
local v_u_3 = require(v_u_1.Game.Garage.VehicleData)
local v_u_4 = require(v_u_1.Sale.SaleConsts)
local v_u_5 = require(v_u_1.Sale.SaleUtils)
local v_u_6 = require(v_u_1.Garage.GarageUtils)
local v_u_7 = require(v_u_1.Ownership.OwnershipConsts)
local v8 = require(v_u_1.Std.Signal)
local v9 = require(v_u_1.Std.Interval)
local v_u_10 = {
	["onSaleRefresh"] = v8.new()
}
local v_u_11 = v_u_5.getNextSaleTime()
v9.every(1):Connect(function()
	-- upvalues: (copy) v_u_5, (ref) v_u_11, (copy) v_u_10
	local v12 = v_u_5.getNextSaleTime()
	if v_u_11 + 0.01 < v12 then
		v_u_11 = v12
		v_u_10.onSaleRefresh:Fire()
	end
end)
local function v_u_22(p13, p_u_14)
	-- upvalues: (copy) v_u_5
	table.sort(p13, function(p15, p16)
		-- upvalues: (copy) p_u_14
		return p15.Pointer[p_u_14] < p16.Pointer[p_u_14]
	end)
	local v17 = v_u_5.getNumSalesPassed()
	local v18 = Random.new(v17)
	for _, v19 in p13 do
		v19.SortNumber = v18:NextNumber()
	end
	table.sort(p13, function(p20, p21)
		return p20.SortNumber < p21.SortNumber
	end)
end
local function v_u_36()
	-- upvalues: (copy) v_u_2, (copy) v_u_4, (copy) v_u_7, (copy) v_u_1, (copy) v_u_22, (copy) v_u_6
	local v23 = {}
	local v24 = {}
	for _, v25 in v_u_2.CATEGORIES do
		if v25 ~= v_u_4.CATEGORY_NAME and not (v_u_7.COLOR_CATEGORY_TYPES[v25] or v_u_7.TEXTURE_CATEGORY_TYPES[v25]) then
			for _, v26 in require(v_u_1.Game.Garage.StoreData:FindFirstChild(v25)).Items do
				table.insert(v23, {
					["CategoryName"] = v25,
					["Pointer"] = v26
				})
			end
			v24[v25] = true
		end
	end
	local v27 = 0
	for _, _ in v24 do
		v27 = v27 + 1
	end
	v_u_22(v23, "Name")
	local v28 = {}
	local v29 = {}
	local v30 = {}
	for _, v31 in v23 do
		local v32 = v31.CategoryName
		local v33 = v31.Pointer
		local v34 = not (v_u_6.isVehicleCustomizationLimited(v33) or v33.None)
		if v34 then
			if v33.Price and v33.Price < 1000000 then
				v34 = v33.Price > 0
			else
				v34 = false
			end
			if v34 then
				v34 = not v33.NoGarageUI
			end
		end
		if v34 and not v28[v32] then
			local v35 = table.clone(v31.Pointer)
			v35.CategoryName = v32
			table.insert(v29, v35)
			if not v30[v32] then
				v30[v32] = {}
			end
			v30[v32][v31.Pointer.Name] = true
			v28[v32] = true
		end
		if #v29 >= v_u_4.NUM_VEHICLE_CUSTOMIZATIONS then
			break
		end
	end
	return v29, v30
end
local function v_u_46()
	-- upvalues: (copy) v_u_3, (copy) v_u_22, (copy) v_u_6, (copy) v_u_4
	local v37 = {}
	for _, v38 in v_u_3 do
		table.insert(v37, {
			["Pointer"] = v38
		})
	end
	v_u_22(v37, "Make")
	local v39 = {}
	local v40 = {}
	for _, v41 in v37 do
		local v42 = v41.Pointer
		local v43 = not (v_u_6.isVehicleLimited(v42) or v42.None)
		if v43 then
			local v44
			if v42.Price and v42.Price < 1000000 then
				v44 = v42.Price > 0
			else
				v44 = false
			end
			v43 = v44 and not v42.NoGarageUI
			if v43 then
				v43 = not v42.ExcludeFromSale
			end
		end
		if v43 then
			local v45 = v41.Pointer
			table.insert(v39, v45)
			v40[v41.Pointer.Make] = true
		end
		if #v39 >= v_u_4.NUM_VEHICLES then
			break
		end
	end
	return v39, v40
end
v_u_10._cachedOnSaleVehicleCustomizations = nil
v_u_10._cachedOnSaleVehicleCustomizationsMap = nil
local function v_u_53()
	-- upvalues: (copy) v_u_10, (copy) v_u_36, (copy) v_u_5
	if v_u_10._cachedOnSaleVehicleCustomizations == nil then
		local v47 = v_u_10
		local v48 = v_u_10
		local v49, v50 = v_u_36()
		v47._cachedOnSaleVehicleCustomizations = v49
		v48._cachedOnSaleVehicleCustomizationsMap = v50
		local v51 = v_u_5.getTimeToNextSale() - 1
		local v52 = math.min(60, v51)
		task.delay(v52, function()
			-- upvalues: (ref) v_u_10
			v_u_10._cachedOnSaleVehicleCustomizations = nil
			v_u_10._cachedOnSaleVehicleCustomizationsMap = nil
		end)
	end
end
function v_u_10.getOnSaleVehicleCustomizations()
	-- upvalues: (copy) v_u_53, (copy) v_u_10
	v_u_53()
	return v_u_10._cachedOnSaleVehicleCustomizations
end
function v_u_10.isVehicleCustomizationOnSale(p54, p55)
	-- upvalues: (copy) v_u_53, (copy) v_u_10
	local v56 = p54 ~= nil
	assert(v56, "categoryName must not be nil")
	local v57 = p55 ~= nil
	assert(v57, "itemName must not be nil")
	v_u_53()
	local v58
	if v_u_10._cachedOnSaleVehicleCustomizationsMap[p54] == nil then
		v58 = false
	else
		v58 = v_u_10._cachedOnSaleVehicleCustomizationsMap[p54][p55] == true
	end
	return v58
end
v_u_10._cachedOnSaleVehicles = nil
v_u_10._cachedOnSaleVehiclesMap = nil
local function v_u_65()
	-- upvalues: (copy) v_u_10, (copy) v_u_46, (copy) v_u_5
	if v_u_10._cachedOnSaleVehicles == nil then
		local v59 = v_u_10
		local v60 = v_u_10
		local v61, v62 = v_u_46()
		v59._cachedOnSaleVehicles = v61
		v60._cachedOnSaleVehiclesMap = v62
		local v63 = v_u_5.getTimeToNextSale() - 1
		local v64 = math.min(60, v63)
		task.delay(v64, function()
			-- upvalues: (ref) v_u_10
			v_u_10._cachedOnSaleVehicles = nil
			v_u_10._cachedOnSaleVehiclesMap = nil
		end)
	end
end
function v_u_10.getOnSaleVehicles()
	-- upvalues: (copy) v_u_65, (copy) v_u_10
	v_u_65()
	return v_u_10._cachedOnSaleVehicles
end
function v_u_10.isVehicleOnSale(p66)
	-- upvalues: (copy) v_u_65, (copy) v_u_10
	local v67 = p66 ~= nil
	assert(v67, "vehicleMake must not be nil")
	v_u_65()
	return v_u_10._cachedOnSaleVehiclesMap[p66] == true
end
return v_u_10
