-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMWBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzBHllYXIFbW9udGgDZGF5BGhvdXIIRGF0ZVRpbWURZnJvbVVuaXZlcnNhbFRpbWUNVW5peFRpbWVzdGFtcBpyZXF1aXJlVmFsaWRJbmRleEFuZEZyZWV6ZRpGSVJTVF9TQUxFX1NUQVJUX1RJTUVTVEFNUBVTQUxFX0RVUkFUSU9OX1NFQ09ORFMaTlVNX1ZFSElDTEVfQ1VTVE9NSVpBVElPTlMmVkVISUNMRV9DVVNUT01JWkFUSU9OX1BSSUNFX01VTFRJUExJRVIMTlVNX1ZFSElDTEVTGFZFSElDTEVfUFJJQ0VfTVVMVElQTElFUg1DQVRFR09SWV9OQU1FCEZlYXR1cmVkAAEKAAABAgBCowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAoQYAAABNAgMYBwAAAJ8BAgLiAgwAjAPnBzADAhoIAAAAjAMHADADAisJAAAAjAMbADADAsoKAAAAjAMRADADAmYLAAAApAQPAAA40IBNBQIaCAAAAE0GAisJAAAATQcCygoAAABNCQJmCwAAAHgICRCfBAUCTQMEtxEAAABNBAEAEgAAAOIFGgAwAwWCEwAAAG8GGwAwBgWQFAAAAIwGBgAwBgV/FQAAAG8GHAAwBgW5FgAAAIwGAQAwBgWAFwAAAG8GHQAwBgUOGAAAAG8GHgAwBgWYGQAAAJ8EAgCCBAAAHwMBBAAAAEADAgMDAwQEAABAQAMFAwYDBwMIAwkDCgUECAkKCwMLAwwEADjQgAIAAAAAAAAQwAMNAw4DDwMQAxEDEgMTAxQDFQUHExQVFhcYGQIAAAAAAHUiQQIAAAAAAADoPwLNzMzMzMzsPwMWAAEAARgAAQAAAAAAAQAAAAAAAAMBAAABAAABAAABAAACAAEAAQABAAEAAPwFAAEAAAEAAQAAAQAAAQAAAQAAAQAAAQAA+QABAAAAAABDcJCEUDqcanG0+hC+OcuiccLG2ZaQQ0P8xYugwp5ZMFVECDGWuFFB

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v2 = require(v1.Std.TableUtils)
local v3 = {
	["year"] = 2023,
	["month"] = 7,
	["day"] = 27,
	["hour"] = 17
}
local v4 = {
	["FIRST_SALE_START_TIMESTAMP"] = DateTime.fromUniversalTime(v3.year, v3.month, v3.day, v3.hour - -4).UnixTimestamp,
	["SALE_DURATION_SECONDS"] = 604800,
	["NUM_VEHICLE_CUSTOMIZATIONS"] = 6,
	["VEHICLE_CUSTOMIZATION_PRICE_MULTIPLIER"] = 0.75,
	["NUM_VEHICLES"] = 1,
	["VEHICLE_PRICE_MULTIPLIER"] = 0.9,
	["CATEGORY_NAME"] = "Featured"
}
return v2.requireValidIndexAndFreeze(v4)
