-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMUCXdvcmtzcGFjZRBHZXRTZXJ2ZXJUaW1lTm93GkZJUlNUX1NBTEVfU1RBUlRfVElNRVNUQU1QFVNBTEVfRFVSQVRJT05fU0VDT05EUwRtYXRoBWZsb29yEWdldE51bVNhbGVzUGFzc2VkD2dldE5leHRTYWxlVGltZRFnZXRUaW1lVG9OZXh0U2FsZQNtYXgPJWRkICVkaCAlZG0gJWRzBmZvcm1hdAslZGggJWRtICVkcwclZG0gJWRzAyVkcw9mb3JtYXRSZW1haW5pbmcHcmVxdWlyZQZzY3JpcHQGUGFyZW50ClNhbGVDb25zdHMABQYAAQAAABKkAAEAAAAAQLwAALcCAAAAnwACAvsFAABNBAWCAwAAACYDAAT7BQAATQQFkAQAAADsAgMEuwwCAqQBBwAAGFCAnwECAoIBAgAIAwEEAAAAQAMCAwMDBAMFAwYEABhQgAAEBwEYAAAAAAABAAAAAAAAAAAAAAAABQAAAAAHAAIAAAAO+wEAAE0AAVgAAAAAnwABAvsDAQBNAgOCAQAAAJUEAAL7BgEATQUGkAMAAAAJAwQFQwECA4IBAgAEAwcDAwIAAAAAAADwPwMEAAgIARgAAAAAAQAAAQAAAAAAAQkAAAAAAwABAAAAC/sBAABNAAH2AAAAAJ8AAQKkAQIAAAAQQLwBAbcDAAAAnwECAiYCAAGCAgIABAMIAwEEAAAQQAMCAA4JARgAAAAAAQAAAAABAA8AAAAACwEAAAATAAAEAwUmAgMFMQIDBTsCAwVBAkWMAgAAnhICBAAAAABSAwAApAECAAAEAICfAQMCUgABAD4CAAO7DAICpAEFAAAQAICfAQICIQQAAz4DBAa7DAMCpAIFAAAQAICfAgICIQUABj4EBQe7DAQCpAMFAAAQAICfAwICIQUAB7sMBQKkBAUAABAAgJ8EAgKMBQAAYAUKAAEAAABvBQgAUgcBAFIIAgBSCQMAUgoEALwFBY0JAAAAnwUGAIIFAACMBQAAYAUJAAIAAABvBQoAUgcCAFIIAwBSCQQAvAUFjQkAAACfBQUAggUAAIwFAABgBQgAAwAAAG8FCwBSBwMAUggEALwFBY0JAAAAnwUEAIIFAABvBQwAUgcEALwFBY0JAAAAnwUDAIIFAAANAwUDCgQABACAAgAAAAAAGPVAAwYEABAAgAIAAAAAACCsQAIAAAAAAABOQAMLAwwDDQMOAw8AExABGAAAAAAAAAAAAgAAAAABAAAAAAABAAAAAAABAAAAAAIAAAEAAAAAAAAAAAEAAAEAAAAAAAAAAQAAAQAAAAAAAAIAAAAAABQAAAAABAAAAQIAHaMAAACkAAEAAAAAQKQDAwAAACBATQIDJAQAAABNAQINBQAAAJ8AAgL/AQMAAAAAAMACBgASAAAAMAIBWAcAAADAAggAEgABABIAAAAwAgH2CQAAAMACCgASAAEAMAIBJwsAAADAAgwAMAIB8Q0AAACCAQIADgMRBAAAAEADEgQAACBAAxMDFAYAAwcGAQMIBgIDCQYDAxAEAAECAwEAARgAAQAAAAAAAAAAAQABAAAABAAAAAAGAAAABQAAEwEAAAAABIlwXJa0EAuQu7Q2Au4mcLGwF9APHZQml1nKeCGEfa2zCYAou4h7uco=

-- Decompiled by Krnl

local v_u_1 = require(script.Parent.SaleConsts)
local v_u_14 = {
	["getNumSalesPassed"] = function()
		-- upvalues: (copy) v_u_1
		local v2 = (workspace:GetServerTimeNow() - v_u_1.FIRST_SALE_START_TIMESTAMP) / v_u_1.SALE_DURATION_SECONDS
		return math.floor(v2)
	end,
	["getNextSaleTime"] = function()
		-- upvalues: (copy) v_u_14, (copy) v_u_1
		local v3 = v_u_14.getNumSalesPassed()
		return v_u_1.FIRST_SALE_START_TIMESTAMP + (v3 + 1) * v_u_1.SALE_DURATION_SECONDS
	end,
	["getTimeToNextSale"] = function()
		-- upvalues: (copy) v_u_14
		return v_u_14.getNextSaleTime() - workspace:GetServerTimeNow()
	end,
	["formatRemaining"] = function(p4)
		local v5 = math.max(0, p4)
		local v6 = v5 / 86400
		local v7 = math.floor(v6)
		local v8 = v5 % 86400 / 3600
		local v9 = math.floor(v8)
		local v10 = v5 % 3600 / 60
		local v11 = math.floor(v10)
		local v12 = v5 % 60
		local v13 = math.floor(v12)
		if v7 > 0 then
			return ("%dd %dh %dm %ds"):format(v7, v9, v11, v13)
		elseif v9 > 0 then
			return ("%dh %dm %ds"):format(v9, v11, v13)
		elseif v11 > 0 then
			return ("%dm %ds"):format(v11, v13)
		else
			return ("%ds"):format(v13)
		end
	end
}
return v_u_14
