-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMgD21hcENhdGVnb3J5RGF0YQVlcnJvch9ObyBkYXRhIGV4aXN0cyBmb3IgY2F0ZWdvcnk6ICVzBmZvcm1hdA9nZXRDYXRlZ29yeURhdGEHYWxsRGF0YQpnZXRBbGxEYXRhCXRha2VzQW1tbwxkb2VzVGFrZUFtbW8JZ2V0Q29uZmlnCURhbWFnZUZ1bgZEYW1hZ2UGYXNzZXJ0CWdldERhbWFnZQdNYWdTaXplFmdldE1heFRvdGFsQW1tb0Zvckl0ZW0EZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUDQXBwDUl0ZW1EYXRhVXRpbHMERGF0YQZzY3JpcHQGUGFyZW50BmlwYWlycwtHZXRDaGlsZHJlbgROYW1lBXBhaXJzBXRhYmxlBmluc2VydANGb3IABgYBAQAABwAAAQMDCQIO+wMAAE0CA0gAAAAAhwECACsBCACkAgIAAAAQQG8DAwBSBQAAvAMDjQQAAACfAwMAnwIAAYIBAgAFAwEDAgQAABBAAwMDBAAYBQEYAAAAAAEBAAAAAAAAAAIZAAAAAAIAAQAAAAT7AQAATQABPgAAAACCAAIAAQMGAB8HARgAAAAAIAAAAAAEAQEAAAAF+wMAAE0CA9gAAAAAhwECAIIBAgABAwgAIgkBGAAAAAAAIwAAAAAGAgEAAAcEAAAFAgMCGvsDAABNAgNRAAAAAFIDAACfAgICKwICAMYDAACCAwIAxgMAAE0EAnIBAAAADgQGAE0EAnIBAAAAUgUBAJ8EAgJSAwQAggMCAE0FAg8CAAAAuwEFAqQEBAAAADBAnwQCAlIDBACCAwIABQMKAwsDDAMNBAAAMEAAJQ4BGAAAAAAAAQEAAgEAAAEAAAAAAAIAAAAAAAACJgAAAAADAQIAAAAQ+wIAAE0BApIAAAAAUgIAAJ8BAgIOAQgA+wIBAE0BAlEBAAAAUgIAAJ8BAgJNAgH3AgAAAIICAgDGAQAAggECAAMDCQMKAw8AMhABGAAAAAAAAAEAAAAAAQAAAgAzAAAAABEAAAEAAGqjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwDBBgAAAE0CAzkHAAAAnwECAqQECgAAAJBATQMEJAsAAABNAgPGCAAAAP8DBAAAAAAA/wQAAAAAAAAwBANIDAAAAP8EAAAAAAAAMAQDPg0AAAD/BAAAAAAAADAEA9gOAAAApAQQAAAA8EC8BQJoEQAAAJ8FAgCfBAAEUQQJAE0JA0gMAAAATQoIuhIAAACkCwUAAABAQFIMCACfCwICagsJCm4E9v8CAACApAQUAAAAMEFNBQNIDAAAAJ8EAgQXBBgApAkQAAAA8EBSCggAnwkCBFEJEQBNDwM+DQAAAJ40DwQNAAAAUhANAKQOFwAAWFCBnw4DAU0ODRgYAAAADg4GAE0OA9gOAAAATQ8NGBgAAACpEAEAahAOD24J7v8CAACAbgTn/wIAAADABBkAEgADADAEA8UaAAAAwAQbABIAAwAwBAP8HAAAAMAEHQASAAMAMAQDkh4AAADABB8AEgABADAEA08gAAAAwAQhABIAAwASAAEAMAQDhCIAAACCAwIAIwMRBAAAAEADEgMTAxQEAABAQAMVAxYDFwMYBAAAkEADGQMBAwYDCAMaBAAA8EADGwMcAx0EAAAwQQMeAx8EAFhQgQMgBgADBQYBAwcGAgMJBgMDDgYEAxAFAAECAwQBAAEYAAEAAAAAAAEAAAAAAAABAAAAAAACAAEAAAABAAAAAQAAAAIAAAAAAAABAAAAAAAAAAD/AAMAAAAAAAEAAAAAAQAAAAAAAAACAAABAAAAAAD8AP8ACgAAAAcAAAADAAAAAwAAAA0AAAAABwEAAAAABSlyFTgNNRYTG7Z/rFRB7QgcXE1HOOMyuH7P0cX9gBFPY0ePGb32If4=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.App.ItemDataUtils)
local v3 = script.Parent.Data
local v_u_4 = {
	["mapCategoryData"] = {},
	["allData"] = {},
	["takesAmmo"] = {}
}
for _, v5 in ipairs(v3:GetChildren()) do
	v_u_4.mapCategoryData[v5.Name] = require(v5)
end
for _, v6 in pairs(v_u_4.mapCategoryData) do
	for _, v7 in ipairs(v6) do
		local v8 = v_u_4.allData
		table.insert(v8, v7)
		if v7.For then
			v_u_4.takesAmmo[v7.For] = true
		end
	end
end
function v_u_4.getCategoryData(p9)
	-- upvalues: (copy) v_u_4
	local v10 = v_u_4.mapCategoryData[p9]
	if not v10 then
		error(("No data exists for category: %s"):format(p9))
	end
	return v10
end
function v_u_4.getAllData()
	-- upvalues: (copy) v_u_4
	return v_u_4.allData
end
function v_u_4.doesTakeAmmo(p11)
	-- upvalues: (copy) v_u_4
	return v_u_4.takesAmmo[p11]
end
function v_u_4.getDamage(p12, p13)
	-- upvalues: (copy) v_u_2
	local v14 = v_u_2.getConfig(p12)
	if not v14 then
		return nil
	end
	if v14.DamageFun then
		return v14.DamageFun(p13)
	end
	local v15 = v14.Damage
	return assert(v15)
end
function v_u_4.getMaxTotalAmmoForItem(p16)
	-- upvalues: (copy) v_u_4, (copy) v_u_2
	if v_u_4.doesTakeAmmo(p16) then
		return v_u_2.getConfig(p16).MagSize
	else
		return nil
	end
end
return v_u_4
