-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMJBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplEElURU1TX1ZBTFVFX05BTUUFSXRlbXMAAQUAAAECABajAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CAxgHAAAAnwECAk0CAQAIAAAA4gMKAG8ECwAwBANoCQAAAJ8CAgCCAgAADAMBBAAAAEADAgMDAwQEAABAQAMFAwYDBwMIBQEJAwkAAQABGAABAAAAAAABAAAAAAAAAQAAAQAA/wABAAAAAADBZb5K2waqNPOh1N4o/yfUAXYNf8sJmaIm3VnA8WVE5LxnmsUXhlYQ

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Std.TableUtils).requireValidIndexAndFreeze({
	["ITEMS_VALUE_NAME"] = "Items"
})
