-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMjBVVEaW0yA25ldxNBYnNvbHV0ZUNvbnRlbnRTaXplAVgKQ2FudmFzU2l6ZQxzZXRtZXRhdGFibGUFX21haWQMUHJlc2V0U2xpZGVyBUNsb25lBlNsaWRlcgROYW1lDF9zbGlkZXJGcmFtZQhHaXZlVGFzawxVSUxpc3RMYXlvdXQYR2V0UHJvcGVydHlDaGFuZ2VkU2lnbmFsB0Nvbm5lY3QJX2xpc3RJdGVtDkdldExheW91dE9yZGVyDlNldExheW91dE9yZGVyCVNldFBhcmVudAV0YWJsZQZpbnNlcnQHQWRkSXRlbQZQYXJlbnQGaXBhaXJzB0Rlc3Ryb3kEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUDU3RkBE1haWQIUmVzb3VyY2UHR3VuU2hvcAdfX2luZGV4AAYHAAIAAAAQ+wAAAKQBAgAABACAjAIAAPsGAQBNBQbGBAAAAE0EBXkFAAAAlQMEA4wEAQCMBQAAnwEFAjABAM8GAAAAggABAAcDAQMCBAAEAIACAAAAAAAANEADAwMEAwUAFwABGAAAAAAAAAAAAAAAAAAAAAEZAAAAAAkAAwAAADb/AAMAAAAAAPsDAACePQAEAwAAAFICAACkAQEAAAAAQJ8BAwH7AgEATQEC7wIAAACfAQECMAEAwQMAAAD7AgIATQECowQAAAC8AgE6BQAAAJ8CAgJvAwYAMAMCugcAAAAwAgDZCAAAAE0DAMEDAAAAUgUCALwDA/0JAAAAnwMDAU0DAjQKAAAATQQAwQMAAABvCAsAvAYDlAwAAACfBgMC2QgAABIAAgASAAMAvAYGxw0AAACfBgMAvAQE/QkAAACfBAAB/wQAAAAAAAAwBAAaDgAAAIIAAgAPAwYEAAAAQAMCAwcDCAMJAwoDCwMMAw0DDgMDAw8DEAMRAQAJAgEYAAABAAAAAAAAAgAAAAAAAgAAAQAAAQAAAQACAAAAAAACAAEAAAAAAAAAAAAAAAAAAAUAAAACCgAAAAAHAgAAAAAjjAIAAE0EABoAAAAAHAMEAIwEAABgBAsAAwAAAE0EABoAAAAATQYAGgAAAAAcBQYAhwMEBbwDAyMBAAAAnwMCAlICAwCVBQICvAMBPwMAAACfAwMBTQUA2QQAAAC8AwEZBQAAAJ8DAwFNBAAaAAAAAJ40BAQBAAAAUgUBAKQDCAAAHGCAnwMDAYIAAQAJAxEDEgIAAAAAAADwPwMTAwwDFAMVAxYEABxggAAgFwEYAAEAAAAAAAEAAAAAAAAAAAACAAAAAQAAAAABAAAAAAAAAAEhAAAAAAMCAAAAAAVNAgDZAAAAADABAiQBAAAAggABAAIDDAMYACkUARgAAAAAASoAAAAACAEAAAAAFKQBAQAAAABATQIAGgIAAACfAQIEUQEDALwGBVADAAAAnwYCAW4B/P8CAACATQEAwQQAAAC8AQFQAwAAAJ8BAgHGAQAAMAEAwQQAAACCAAEABQMZBAAAAEADEQMaAwcALBoBGAAAAAAAAAEAAP8AAwAAAAABAAABLQAAAAAFAAABAgAmowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAoQYAAABNAgN2BwAAAJ8BAgJNAwBiCAAAAE0CAwYJAAAA/wMEAAAAAAAwAwNuCgAAAMAECwASAAMAEgABABIAAgAwBAPvDAAAAMAEDQAwBAN4DgAAAMAEDwAwBAMZEAAAAMAEEQAwBANQEgAAAIIDAgATAxsEAAAAQAMcAx0DHgQAAEBAAx8DIAMhAyIDIwYBAwIGAgMXBgMDFAYEAxoEAQIDBAEAARgAAQAAAAAAAQAAAAAAAAIAAAACAAEAAQAAAAAAFwAACQAAAwAABwEAAAAABZGY8OsWeyBro1yafx1U8mjL6nDO12o/FrsYtcP7vddgKR3no3iTZFo=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.Maid)
local v_u_3 = v1.Resource.GunShop
local v_u_4 = {}
v_u_4.__index = v_u_4
function v_u_4.new()
	-- upvalues: (copy) v_u_4, (copy) v_u_2, (copy) v_u_3
	local v5 = {}
	local v6 = v_u_4
	setmetatable(v5, v6)
	v5._maid = v_u_2.new()
	local v_u_7 = v_u_3.PresetSlider:Clone()
	v_u_7.Name = "Slider"
	v5._sliderFrame = v_u_7
	v5._maid:GiveTask(v_u_7)
	local v_u_8 = v_u_7.UIListLayout
	v5._maid:GiveTask(v_u_8:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function()
		-- upvalues: (copy) v_u_7, (copy) v_u_8
		v_u_7.CanvasSize = UDim2.new(0, v_u_8.AbsoluteContentSize.X + 20, 1, 0)
	end))
	v5._listItem = {}
	return v5
end
function v_u_4.AddItem(p9, p10)
	p10:SetLayoutOrder((#p9._listItem <= 0 and 0 or p9._listItem[#p9._listItem]:GetLayoutOrder()) + 1)
	p10:SetParent(p9._sliderFrame)
	local v11 = p9._listItem
	table.insert(v11, p10)
end
function v_u_4.SetParent(p12, p13)
	p12._sliderFrame.Parent = p13
end
function v_u_4.Destroy(p14)
	for _, v15 in ipairs(p14._listItem) do
		v15:Destroy()
	end
	p14._maid:Destroy()
	p14._maid = nil
end
return v_u_4
