-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgO1AQ9zZWxlY3RJZkdhbWVwYWQPU2VsZWN0SWZHYW1lcGFkFF9wcml6ZVB1cmNoYXNlUmVtb3RlB3JlcXVpcmUMU2Vhc29uU3lzdGVtBnNjcmlwdAZQYXJlbnQQQ29udHJhY3RVSVN5c3RlbQRHYW1lCENvbnRyYWN0ClN0YXJ0ZXJHdWkJU2Vhc29uR3VpDkZpbmRGaXJzdENoaWxkCVBsYXllckd1aQNndWkMX3NlYXNvblN0YXRlCkJhY2tncm91bmQFVGl0bGUFRnJhbWUQU2Vhc29uTnVtV2VsY29tZRRXZWxjb21lIHRvIFNFQVNPTiAlZApTRUFTT05fTlVNBmZvcm1hdARUZXh0CVRleHRMYWJlbAtTZWFzb25UaXRsZQxTRUFTT05fVElUTEUDbmV3EUdldE9uT3BlbmVkU2lnbmFsBV9vcGVuB0Nvbm5lY3QRR2V0T25DbG9zZWRTaWduYWwGX2Nsb3NlB193aW5kb3cUZ2V0Q2VudGVyV2luZG93R3JvdXADQWRkGlBSSVpFX1BVUkNIQVNFX1JFTU9URV9OQU1FB2FuZFRoZW4Ed2FybgVjYXRjaAtCb251c0F3YXJkcxRTRUFTT05fQk9OVVNfRU5BQkxFRAdWaXNpYmxlBGluaXQFVGltZXILU0VBU09OIEVORFMESGVscA9TRUFTT05fU1VCVElUTEUGQm90dG9tCUNvbnRhaW5lcgxSZXZpZXdCdXR0b24JQ09OVFJBQ1RTC0JVWUlORyBFTkRTDEJVWV9TVUJUSVRMRQtDT01JTkcgU09PTg1QT1NUX1NVQlRJVExFBWVycm9yGEludmFsaWQgc2Vhc29uIHN0YXRlOiAlZA9fdXBkYXRlU2Vhc29uVWkQZ2V0UmVtYWluaW5nVGltZQxpc0J1eUVuYWJsZWQTZ2V0UmVtYWluaW5nQnV5VGltZQ9mb3JtYXRSZW1haW5pbmcEVGltZQRCb2R5BExpbmUQTUFYX1JFV0FSRF9MRVZFTAQlMDJkBlJld2FyZANCdXkTRGFpbHlFeHBSZWZyZXNoSGVscBFnZXRRdWFudGl6ZWRCbG9jaxJEQUlMWV9FWFBfRFVSQVRJT04ZREFJTFlfRVhQX0RVUkFUSU9OX09GRlNFVD1EYWlseSBYUCByZWxvYWRzIGluIDxmb250IGNvbG9yPSJyZ2IoMjU1LCAyMDcsIDApIj4lczwvZm9udD4hCXdvcmtzcGFjZRBHZXRTZXJ2ZXJUaW1lTm93D191cGRhdGVEZWFkbGluZQdFbmFibGVkDnVwZGF0ZVByb2dyZXNzC09iamVjdExvY2FsBWNsb3NlBG9wZW4IaXNTdHVkaW8nU2Vhc29uIGlzIG92ZXIhIFdhaXQgdW50aWwgbmV4dCBzZWFzb24uFWdldEZpcnN0UHJvZHVjdEJ5VHlwZQpTZWFzb25QYXNzBmFzc2VydBdkb2VzUGxheWVyT3duU2Vhc29uUGFzcwJJZBVQcm9tcHRQcm9kdWN0UHVyY2hhc2UFUHJpY2UFT3duZWQRc2V0T3duc1NlYXNvblBhc3MFUm9idXgIdG9zdHJpbmcLdXBkYXRlUHJpY2UFX21haWQNaXNTbWFsbFNjcmVlbgVVRGltMghQb3NpdGlvbghHaXZlVGFzawVldmVyeRdnZXRPbkxldmVsQ2hhbmdlZFNpZ25hbBVnZXRPbkV4cENoYW5nZWRTaWduYWwYZ2V0U2Vhc29uUGFzc093bmVkU2lnbmFsEE1vdXNlQnV0dG9uMURvd24NU0VBU09OICVkOiAlcxFob29rR2lmdENvbnRhaW5lcg1HaWZ0Q29udGFpbmVyBUNsb3NlEU9uUHJvZHVjdHNGZXRjaGVkE2dldENsaWVudExldmVsQXdhcmQESWNvbg9yYnhhc3NldGlkOi8vJWQHaW1hZ2VJZAVJbWFnZRBOVU1fQk9OVVNfQVdBUkRTE2dldENsaWVudEJvbnVzQXdhcmQJQm9udXMlMDJkBERlc2MIVE9QICVkJSUIc2NvcmVMdGUOQ0hFQ0sgTEFURVIuLi4QU2Vhc29uQm9udXNTY29yZQ9ZT1U6IFRPUCAlLjJmJSUFVmFsdWUFU2NvcmUHRGVzdHJveQRPcGVuCnlpZWxkTGV2ZWwIeWllbGRFeHALc2V0UHJvZ3Jlc3MEU2l6ZQFYBVNjYWxlBFVEaW0GT2Zmc2V0AVkVc2V0UHJvZ3Jlc3NGcmFtZVNjYWxlDU1BWF9EQUlMWV9FWFAZTUFYX0RBSUxZX0VYUF9TRUFTT05fUEFTUxBnZXRTZWFzb25FeHBNdWx0C0xvY2FsUGxheWVyFERBSUxZX0VYUF9WQUxVRV9OQU1FFWNhbGN1bGF0ZUV4cE5leHRMZXZlbBVjYWxjdWxhdGVMZXZlbEZyb21FeHATY2FsY3VsYXRlRXhwT2ZMZXZlbAJCZwlQcm9ncmVzczEJUHJvZ3Jlc3MyBGdhbWUHUGxheWVycwpHZXRTZXJ2aWNlEk1hcmtldHBsYWNlU2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQNTdGQFQXVkaW8Md2FpdEZvckNoaWxkCFNldHRpbmdzCFJlc291cmNlBE1haWQMTm90aWZpY2F0aW9uCEludGVydmFsC0xldmVsU3lzdGVtBkxldmVsMgpMZXZlbFV0aWxzBldpbmRvdwZNb2R1bGUIR2FtZVV0aWwDQXBwCFJ1blV0aWxzBEV6VWkHRXpVdGlscwVVdGlscw1Db250cmFjdFV0aWxzC0xldmVsQ29uc3RzBlNlYXNvbg1TZWFzb25VSVV0aWxzDFNlYXNvbkNvbnN0cwtTZWFzb25VdGlscwAUAwEBAAAABvsCAABNAQIEAAAAAFICAACfAQIBggABAAEDAQAdAgEYAAAAAAABHgAAAAACAQEAAAAE+wEAADAAAQYAAAAAggABAAEDAwA3AAEYAAAAATgAAAAABwAJAAAHAAABAwI0ApgBpAABAAAAAECkAwQAAAAwQE0CAyQFAAAATQECSwIAAACfAAIC3gAAAKQAAQAAAABA+wQCAE0DBL0HAAAATQIDYAgAAABNAQJKBgAAAJ8AAgLeAAEA+wECAE0AAQsJAAAAbwIKALwAAAMLAAAAnwADAvsCAwBNAQKZDAAAADABACQFAAAA+wEEADAAAX8NAAAA+wEEAIwC//8wAgFSDgAAAE0EAO0PAAAATQMEuhAAAABNAgOdEQAAAE0BAgsSAAAAbwITAPsFBQBNBAXGFAAAALwCAo0VAAAAnwIDAjACAfUWAAAATQUA7Q8AAABNBAW6EAAAAE0DBJ0RAAAATQIDCxIAAABNAQKaFwAAAE0GAO0PAAAATQUGuhAAAABNBAWdEQAAAE0DBAsSAAAATQID9RYAAAAwAgH1FgAAAE0EAO0PAAAATQMEuhAAAABNAgOdEQAAAE0BAmIYAAAA+wMFAE0CAw4ZAAAAMAIB9RYAAAD7AgYATQEC7xoAAACfAQECvAIBLBsAAACfAgIC+wUEAE0EBUAcAAAAvAICxx0AAACfAgMBvAIBdR4AAACfAgIC+wUEAE0EBVUfAAAAvAICxx0AAACfAgMB+wIEADABAqcgAAAA+wMHAE0CA+AhAAAAnwIBAlIEAQC8AgJfIgAAAJ8CAwH7AggA+wMCAPsFBQBNBAXaIwAAAIwFHgCfAgQC2QQAABICAAC8AgK1JAAAAJ8CAwKkBCYAAABQQrwCAhknAAAAnwIDAU0DAO0PAAAATQIDtCgAAAD7BAUATQMEBykAAAAwAwKAKgAAAIIAAQArAwQEAAAAQAMFAwYEAAAwQAMHAwgDCQMKAwsDDAMNAw4DDwMQAxEDEgMTAxQDFQMWAxcDGAMZAxoDGwMcAx0DHgMfAyADIQMiAyMDJAMlAyYDJwQAAFBCAygDKQMqAysBASIsARgAAAAAAAAAAAAAAQAAAAAAAAAAAAACAAAAAAAAAQAAAAABAAACAAAAAgAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAIAAAABAAAAAAAAAAABAAAAAAAAAAABAAABAAAAAAAAAAIAAAAAAAABAAAAAAMAAAAAAgAAAAAAAAAAASMAAAAABwECAAAHAAABAwNwAnX7AQAAMAABUgAAAAD7AgAATQECfwEAAAANACEAAgAAgE0EAe0DAAAATQMEPAQAAABNAgO6BQAAAG8DBgAwAwL1BwAAAE0DAe0DAAAATQIDCggAAAD7BAEATQMEOQkAAAAwAwL1BwAAAE0GAe0DAAAATQUGEwoAAABNBAVvCwAAAE0DBLkMAAAATQIDmg0AAABvAw4AMAMC9QcAAACCAAEADQAhAA8AAIBNBAHtAwAAAE0DBDwEAAAATQIDugUAAABvAxAAMAMC9QcAAABNAwHtAwAAAE0CAwoIAAAA+wQBAE0DBJwRAAAAMAMC9QcAAABNBgHtAwAAAE0FBhMKAAAATQQFbwsAAABNAwS5DAAAAE0CA5oNAAAAbwMSADADAvUHAAAAggABAA0AIQATAACATQQB7QMAAABNAwQ8BAAAAE0CA7oFAAAAbwMGADADAvUHAAAATQMB7QMAAABNAgMKCAAAAPsEAQBNAwQgFAAAADADAvUHAAAATQYB7QMAAABNBQYTCgAAAE0EBW8LAAAATQMEuQwAAABNAgOaDQAAAG8DEgAwAwL1BwAAAIIAAQCkAhYAAABQQW8DFwBSBQAAvAMDjRgAAACfAwMAnwIAAYIAAQAZAxADDwIAAAAAAAAAAAMRAy0DEgMuAxgDLwMwAzEDMgMzAxkDNAIAAAAAAADwPwM1AzYDNwIAAAAAAAAAQAM4AzkEAABQQQM6AxcAPjsBGAAAAAEAAAEAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAAAAAAABAAEAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAQABAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAAAAAAAAAAIAAAAAAAAAAj8AAAAADgAFAAALAAACAwtSAgMIewKBAfsBAABNAAF/AAAAAPsCAQBNAQKcAQAAAJ8BAQKMAwAAtwECAAMAAACpAgABqQIBAPsEAQBNAwSxAgAAAJ8DAQIOAxIA+wUBAE0EBfwDAAAAnwQBAvsGAQBNBQbxBAAAAFIGBACfBQICTQgA7QUAAABNBwg8BgAAAE0GB0oHAAAAMAUG9QgAAABlAA0A+wUBAE0EBfEEAAAAUgUBAJ8EAgJNBwDtBQAAAE0GBzwGAAAATQUGSgcAAAAwBAX1CAAAACsCAwArAwIAjAQAAGUABAAOAwIAjAQBAGUAAQCMBAIA+wYAAE0FBlIJAAAA8QUGAAQAAAD7BgAATQUG1AoAAABSBgQAnwUCAU0IAO0FAAAATQcIZwsAAABNBgfpDAAAAE0FBm8NAAAAjAgCAPsJAgBNBgmPDgAAAIwHAQCoBhIAbwsPAFINCAC8CwuNEAAAAJ8LAwC8CQUDEQAAAJ8JAAJNCgk/EgAAAG8MEwC8CgoDEQAAAJ8KAwIOCgIAMAMKgBQAAACLBu7/TQcA7QUAAABNBgciFQAAAPsIAwBNBwjIFgAAAPsJBABNCAkeFwAAAPsKBABNCQr4GAAAAJ8HAwJvCBkA+wsBAE0KC/EEAAAApAwbAAAAoEG8DAy3HAAAAJ8MAgImCwcMnwoCALwICI0QAAAAnwgAAjAIBvUIAAAAggABAB0DDwM8Az0DPgM/AxEDLQNAAxgDEAM7A0EDQgMyA0MDRAMXAw0DRQNGAysDRwNIA0kDSgNLA0wEAACgQQNNAFFOARgAAAABAAAAAQAAAAABAAAAAgEAAAABAAAAAAEAAAAAAAAAAAMAAAAAAQAAAAAAAAAGAAAAAAAAAAIAAAAAAQAAAAADAAAAAAAAAAEAAAAAAAEAAAAAAAAAAQAAAAAAAQEA/AkAAAAFAAAAAAAAAAAAAQEAAAAAAAAAAAD/AAAAAANSAAAAAAIAAQAAAAX7AAAAqQEAADABAPAAAAAAggABAAEDTwCNAQABGAAAAAABjgAAAAADAQIAAAAK+wEAAPEAAgABAAAAggABAPsCAQBNAQIuAAAAAPsCAACfAQIBggABAAEDUACXAQABGAAAAAECAAAAAAGYAAAAAAMABQAAABn7AQAATQABnAAAAACfAAECjAEAAGAAAgABAAAAggABAPsBAQBNAAHRAQAAAPsCAgBNAQKZAgAAAG8CAwCfAAMB+wEDAE0AAYMEAAAAnwABAfsBBABNAAF2BQAAAJ8AAQGCAAEABgM8A1EDDgIAAGAyn772QQNSA1MAngEAARgAAAAAAAAAAQIAAAAAAAAAAQAAAAEAAAABnwAAAAAFAAgAAAA4+wEAAE0AAeoAAAAAnwABAisAEAD7AQEATQABnAEAAACfAAECjAEAAH0ACgABAAAA+wECAE0AAe8CAAAA4gEEAG8CBQAwAgH1AwAAAJ8AAgGCAAEA+wEDAE0AAdEGAAAA+wIEAE0BApkHAAAAbwIIAJ8AAwH7AQUATQABRwkAAABvAQoAnwACAkcAAgAAAACAqQIAAakCAQC7AQICpAEMAAAAsECfAQIB+wIGAE0BApcNAAAA+wIEAJ8BAgIrAQcA+wEHAPsDBABNBACUDgAAALwBAWkPAAAAnwEEAYIAAQAQA1QDPAMcAxgFAQMDVQNRAw4CAABgMp++9kEDVgNXA1gEAACwQANZA1oDWwCtAQABGAAAAAAAAAAAAAAAAAEAAAAAAAAAAQIAAAAAAAAAAQAAAAABAAAAAAAAAAEAAAAAAAEAAAAAAAACrgAAAAAGAAEAAAAr+wUAAE0EBe0AAAAATQMEEwEAAABNAgNvAgAAAE0BAm0DAAAATQABHwQAAACpAQAAMAEAgAUAAAD7BQAATQQF7QAAAABNAwQTAQAAAE0CA28CAAAATQECbQMAAABNAAEkBgAAAKkBAAAwAQCABQAAAPsFAABNBAXtAAAAAE0DBBMBAAAATQIDbwIAAABNAQJtAwAAAE0AAYQHAAAAqQEBADABAIAFAAAAggABAAgDEQMxAzIDVwNGAysDXANdALwBXgEYAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAb0AAAAABwECAAAAL/sBAADxAAIAAQAAAIIAAQD7BgEATQUG7QAAAABNBAUTAQAAAE0DBG8CAAAATQIDbQMAAABNAQIfBAAAAKkCAAAwAgGABQAAAPsGAQBNBQbtAAAAAE0EBRMBAAAATQMEbwIAAABNAgNtAwAAAE0BAiQGAAAAqQIAADACAYAFAAAA+wYBAE0FBu0AAAAATQQFEwEAAABNAwRvAgAAAE0CA20DAAAATQEChAcAAACpAgEAMAIBgAUAAACCAAEACAMRAzEDMgNXA0YDKwNcA10AxAEAARgIAAAB9wAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAACr0AAAAABwACAAAAHfsBAABNAAFHAAAAAG8BAQCfAAICDgAWAE0BANMCAAAADgETAPsGAQBNBQbtAwAAAE0EBRMEAAAATQMEbwUAAABNAgNtAQAAAE0BAiQGAAAATQMA0wIAAAC7PwMCpAIIAAAAcECfAgICMAIB9QkAAACCAAEACgNWA1cDXwMRAzEDMgNcA2AEAABwQAMYAM8BYQEYAAAAAAABAQAAAQAAAAAAAAAAAAAAAAAAAAAAAAPQAAAAABAAEQAAJgAABwMDrwECAwvcAgIDC+kCAgMMggMCAwyNAwIDDJgDAgMIrQMCugP7AwAATQIDwQAAAABHAgIAAAAAAKkBAAGpAQEAuwEBAqQAAgAAABBAnwACAfsBAQBNAAHvAwAAAJ8AAQL7AQAAMAABwQAAAAD7AgAATQECfwQAAAD7AwIATQIDeQUAAACfAgECDgIOAE0DAe0GAAAATQIDtAcAAACkAwkAAAyAgG8ECgCMBQAAjAYAAIwHAgCfAwUCMAMCOwsAAABlAA0ATQMB7QYAAABNAgO0BwAAAKQDCQAADICAbwQMAIwFAACMBgAAjAcCAJ8DBQIwAwI7CwAAAKkCAQAwAgHwDQAAANkEAAASAAEAvAIA/Q4AAACfAgMB+wUDAE0EBcQPAAAAjAUBAJ8EAgL7BwAATQYHCxAAAAC8BATHEQAAAJ8EAwC8AgD9DgAAAJ8CAAH7AwAATQIDCxAAAACfAgEB+wMAAE0CAy4SAAAA+wMEAJ8CAgH7BQUATQQFORMAAACfBAEC+wcAAE0GBy4SAAAAvAQExxEAAACfBAMAvAIA/Q4AAACfAgAB+wUFAE0EBSsUAAAAnwQBAvsHAABNBgcuEgAAALwEBMcRAAAAnwQDALwCAP0OAAAAnwIAAfsFBgBNBAW8FQAAAJ8EAQLABhYAEgIEABICAAC8BATHEQAAAJ8EAwC8AgD9DgAAAJ8CAAFNCAHtBgAAAE0HCBMXAAAATQYHbxgAAABNBQa5GQAAAE0EBWEaAAAA2QYCABICBwASAggAEgIEABICAAASAgkAvAQExxEAAACfBAMAvAIA/Q4AAACfAgABTQUB7QYAAABNBAUTFwAAAE0DBG8YAAAATQIDuRkAAAD7BAoATQMEBBsAAABSBAIAnwMCAU0GAe0GAAAATQUGExcAAABNBAVvGAAAAE0DBG0cAAAATQIDuh0AAABvAx4A+wYLAE0FBsYfAAAA+wcLAE0GBw4gAAAAvAMDjSEAAACfAwQCMAMC9SIAAABNCAHtBgAAAE0HCBMXAAAATQYHbxgAAABNBQZtHAAAAE0EBWEaAAAA2QYDABICDAASAgcAEgINABICCAASAgQAEgIOABICBgASAg8AvAQExxEAAACfBAMAvAIA/Q4AAACfAgAB+wMQAE0CA9kjAAAATQQB7QYAAABNAwQBJAAAAFIEAACfAgMB2QIEABIAAQD7BAYATQMElyUAAAD7BAQAnwMCAg4DKABNBwHtBgAAAE0GBxMXAAAATQUGbxgAAABNBAVtHAAAAE0DBB8mAAAAqQQAADAEA4AnAAAATQcB7QYAAABNBgcTFwAAAE0FBm8YAAAATQQFbRwAAABNAwQkKAAAAKkEAAAwBAOAJwAAAE0HAe0GAAAATQYHExcAAABNBQZvGAAAAE0EBW0cAAAATQMEhCkAAACpBAEAMAQDgCcAAABlAA0A+wYGAE0FBrwVAAAAnwUBAtkHBQASAgQAEgABALwFBccRAAAAnwUDALwDAP0OAAAAnwMAAU0HAe0GAAAATQYHYyoAAABNBQZhGgAAAPsIAABNBwiDKwAAALwFBccRAAAAnwUDALwDAP0OAAAAnwMAAdkDBgASAg4AEgABAPsFDgBNBAVHLAAAAG8FHACfBAICDgQVAE0FBNMtAAAADgUSAE0JAe0GAAAATQgJExcAAABNBwhvGAAAAE0GB20cAAAATQUGJCgAAABNBwTTLQAAALs/BwKkBi8AAADgQp8GAgIwBgX1IgAAAPsFDgBNBAUvMAAAAFIGAwC8BATHEQAAAJ8EAwFNBwHtBgAAAE0GB2cxAAAATQUG6TIAAABNBAVvGAAAAIwHAgD7CAsATQUIjzMAAACMBgEAqAUaAPsJBgBNCAnyNAAAAFIJBwCfCAICbws1AFINBwC8CwuNIQAAAJ8LAwC8CQQDNgAAAJ8JAAJNCwk/NwAAAE0KC644AAAAbws5AE0NCLY6AAAAvAsLjSEAAACfCwMCMAsKqTsAAACLBeb/TQcB7QYAAABNBge0BwAAAE0FBm8YAAAAjAgBAPsJCwBNBglsPAAAAIwHAQCoBiMA+woGAE0JCu09AAAAUgoIAJ8JAgJvDD4AUg4IALwMDI0hAAAAnwwDALwKBQM2AAAAnwoAAk0LCq44AAAAbww5AE0OCbY6AAAAvAwMjSEAAACfDAMCMAwLqTsAAABNCwp3PwAAAG8MQABNDwkTQgAAAFsOD0G8DAyNIQAAAJ8MAwIwDAv1IgAAAIsG3f/7BwsATQYHB0MAAAAOBhcAbwZEAPsHBABvCUUAvAcHAzYAAACfBwMCDgcIAG8IRgBNCwfsRwAAAFsKC0G8CAiNIQAAAJ8IAwJSBggATQoB7QYAAABNCQq0BwAAAE0ICSJIAAAAMAYI9SIAAACCAAEASQNiA1gEAAAQQAMcAw8DYwMRAykDZAQADICAAjMzMzMzM8O/A2UCKVyPwvUo8D8DTwNmA2cDTgMfA1ADaANpA2oGBgMxAzIDMwNrAwEDVwMSA2wDFgMbAxcDGANtA24DWQNGAysDXANdA28DUgNWA18DYAQAAOBCA3ADQQNCA0MDcQNEAw0DRQNyA3MDdAN1A3YDdwN4A3kDegIAAAAAAABZQAN7AyoDfAN9A34DfwOAAQcFBgcICQoLfh4BGGEAAAAAAAAAAAAAAQAAAAEAAAIAAAIAAAAAAgAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAwAAAQAAAAAEAAAAAAAAAAAAAAAAAAEAAAACAAAAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAJAAAAAAAAAHcAAAAAiwAAAAAAAAAAAAABAAABAAD+AAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANAAAAAAAAAAACAAUAAAAAAPwAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAFAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAwAAAQAAAAABAQAAAQAAAAAAAAAAAAAAAAAAAAAABQAAAAAAAAMAAAAAAAAAAQAAAAAAAQAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAP0GAAAAAAABAAAAAAABAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAEAAAAAAAAAAAAA/AcAAAABAQAAAAABAQAAAAAAAAACAAAAAAAAAAIeAAAAAAQAAQAAABb7AwAATQIDwQAAAABHAgIAAAAAgKkBAAGpAQEAuwEBAqQAAgAAABBAnwACAfsBAABNAAHBAAAAAPsBAADGAgAAMAIBwQAAAAC8AQBQAwAAAJ8BAgGCAAEABANiA1gEAAAQQAOBAQD0ASEBGAAAAAAAAAAAAAAAAQAAAQAAAAEAAAH1AAAAAAIAAQAAAAf7AQAATQABpwAAAAC8AAAWAQAAAJ8AAgGCAAEAAgMiA4IBAPoBUwEYAAAAAAAAAfsAAAAAAgABAAAAB/sBAABNAAGnAAAAALwAAGMBAAAAnwACAYIAAQACAyIDbwD9AVIBGAAAAAAAAAH+AAAAAAYBAwAAABT7AQAAmgARAAEAAAD7AgEATQECRAAAAABSAgAAnwECAvsDAQBNAgP8AQAAAFIDAACfAgIC+wQCAE0DBD8CAAAAUgQBAFIFAgCfAwMBggABAAMDgwEDhAEDhQEAgAJQARgAAAABAAAAAAEAAAAAAQAAAAAAAgEBAAAADgMBAAAIBQAABQMHAoJLTQMAJAAAAABHAwIAAAAAgIIAAQBNBgMvAQAAAE0FBnkCAAAATQQFhAMAAAB4BwQF2AgFBAkGBwg+BQYEeAgBBfsMAABNCwyPBgAAAHgKCwUJCQQK7AcICUMGBwUOAhwAeAkCBfsNAABNDA2PBgAAAHgLDAUJCgQL7AgJCkMHCAUmBgYHpAgJAAAgcICkCQsAACCggFIKBwBNDQA7DAAAAE0MDXkCAAAATQsMcA0AAACfCQMCTQsAOwwAAABNCgt4DgAAAJ8IAwIwCAA7DAAAAKQHCQAAIHCApAgLAAAgoIBSCQYATQwALwEAAABNCwx5AgAAAE0KC3ANAAAAnwgDAk0KAC8BAAAATQkKeA4AAACfBwMCMAcALwEAAACpBwEAMAcAgA8AAACCAAEAEAMHA4YBA4cBA4gBAgAAAAAAAABAAgAAAAAAAPA/A0MDZAMcBAAgcIADiQEEACCggANlA4oBA4sBAysAhwKMAQEYAAABAAECAAAAAAACAAAAAQAAAAAAAAABAQAAAAAAAAABAQAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAABAAABCAEAAAAPAgkAAABw+wMAAE0CA/4AAAAA+wQBAE0DBJcBAAAA+wQCAJ8DAgIOAwMA+wMAAE0CA40CAAAA+wQDAE0DBLgDAAAAnwMBAgkCAgP7BAQATQMEMQQAAAD7BgAATQUGVAUAAAC8AwMDBgAAAJ8DAwIOAwMATQQD7AcAAAAmAgIE+wUDAE0EBZwIAAAAnwQBAowFAABgBAIABQAAAIwCAAD7BQUATQQFjwkAAAB9BAUAAAAAAPsEBQBNAASPCQAAAIwBAAD7BQYATQQFfwoAAAD7CAcATQcI3AsAAABSCAAAnwcCAuwGAQdDBQAG+wcHAE0GB1IMAAAA+woHAE0JCuANAAAAUgoAAJ8JAgJDCAkBQwcIAp8GAgP7CQUATQgJjwkAAAB9CAUABgAAAPsIBQBNBgiPCQAAAIwHAAD7CwcATQoL3AsAAABSCwYAnwoCAuwJBwpDCAYJ+wkIAE0OBO0OAAAATQ0OZw8AAABNDA3pEAAAAE0LDK4RAAAATQoLnBIAAABSCwUAnwkDAfsJCABNDgTtDgAAAE0NDmcPAAAATQwN6RAAAABNCwyuEQAAAE0KC9gTAAAAUgsIAFIMBQCfCQQBggABABQDjQEDWQOOAQOPAQOQAQORAQMNA38DPANDAw8DkgEDkwEDlAEDEQNBA0IDlQEDlgEDlwEAmAKFAQEYAAAAAQAAAAAAAQAAAgAAAAABAAAAAAAAAAABAQAAAgAAAAAAAAEDAAAAAAEAAAECAAAEAAAAAAAAAgAAAAAAAAAAAAABAAAAAAEAAAECAAAAAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAARkBAAAAHAAAAQIA+AGjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCTQEAMQQAAACkAgEAAAAAQG8EBQC8AgIWAwAAAJ8CAwKkAwEAAAAAQG8FBgC8AwMWAwAAAJ8DAwKkBAgAAABwQE0GA6EJAAAATQUG0goAAACfBAICpAUIAAAAcEBNBwOhCQAAAE0GB/MLAAAAnwUCAqQGCAAAAHBATQgDYg0AAABNBwjKDAAAAJ8GAgKkBwgAAABwQE0JA6EJAAAATQgJdg4AAACfBwICpAgIAAAAcEBNCgO9EAAAAE0JCkkPAAAAnwgCAqQJCAAAAHBATQsDoQkAAABNCgusEQAAAJ8JAgKkCggAAABwQE0NA70QAAAATQwN6RMAAABNCwzsEgAAAJ8KAgKkCwgAAABwQE0OA70QAAAATQ0O6RMAAABNDA3wFAAAAJ8LAgKkDAgAAABwQE0PA0AWAAAATQ4PZRUAAABNDQ5lFQAAAJ8MAgKkDQgAAABwQE0PA70QAAAATQ4PPRcAAACfDQICpA4IAAAAcEBNEAPBGAAAAE0PEEIZAAAAnw4CAqQPCAAAAHBATREDLRoAAABNEBHCGwAAAJ8PAgKkEAgAAABwQE0SAy0aAAAATRESoRwAAACfEAICpBEIAAAAcEBNFAO9EAAAAE0TFGAdAAAATRITqB4AAACfEQICpBIIAAAAcEBNFQO9EAAAAE0UFekTAAAATRMUth8AAACfEgICpBMIAAAAcEBNFgO9EAAAAE0VFoYgAAAATRQVNyEAAACfEwICpBQIAAAAcECkFyQAAAAwQk0WFyQlAAAATRUWvCIAAACfFAICpBUIAAAAcECkGCQAAAAwQk0XGCQlAAAATRYX8iYAAACfFQICxhYAAMYXAADAGCcAEgAPAP8ZBQAAAAAA2RoBABIBFv8SARf/EgADABIAAQASABkAEgAUABIADAASAA0AEgAFADAaGRMoAAAAwBopABIAGQASABQAMBoZ1CoAAADAGisAEgAZABIAFQASABQAEgARABIAEgAwGhkLLAAAANkaBAASABkAEgAHABIAEAASAAkAEgABABIACgASARb/EgAVABIABAASARf/EgAPABIAFAASAA4AEgAIABIABgASAAIAEgATADAaGUAtAAAAwBouABIAGQAwGhlVLwAAAMAaMAASABkAMBoZdjEAAADAGjIAEgAZADAaGYMzAAAAwBo0ABIAAQASAAsAEgAZADAaGS41AAAAwBo2ABIAFADZGwoAEgASABIBFv8SAAEAEgAVABIAAAASABQAEgAZABIACwASABoAMBsZPzcAAADBFgAAghkCADgDmAEEAAAAQAOZAQOaAQOQAQObAQOcAQMEBAAAcEADnQEDngEDnwEDoAEDoQEDogEDowEDCQOkAQOlAQOmAQOnAQOoAQOpAQOqAQOrAQOsAQOtAQOuAQOvAQMKA7ABA7EBA7IBA7MBA7QBAwYEAAAwQgMHA7UBBgADLAYDAzsGBANOAx4GDQMhBg4DUwYPA1IGEANQBhEDhQELAAIDBAwNDg8QERIBAAEGAAEAAAAAAAEAAQAAAAAAAQAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAfUAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAH4AAAAAAAAAAIAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAECAgAEAAEAAAAAAAAAAAAAABwAAAAAEwAAAAAAwwAtAAAAAAAAAAAAAAAAAAAAAAAAAHYAAAAGAAAAAwAAAAMAAAAAAAcAEQAAAAAAAAAAAAAAIQABAAAACwAAAAgAAAA9AAAAABOsk+eB8Kz5rJ5XjRVlBofOLORpBNPBtlC3kd8zlXmx97qi8fRPFqqX

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players")
local v_u_2 = v_u_1.LocalPlayer
local v_u_3 = game:GetService("MarketplaceService")
local v_u_4 = game:GetService("ReplicatedStorage")
local v_u_5 = require(v_u_4.Std.Audio)
local v_u_6 = require(v_u_4.Std.waitForChild)
local v_u_7 = require(v_u_4.Resource.Settings)
local v_u_8 = require(v_u_4.Std.Maid)
local v_u_9 = require(v_u_4.Game.Notification)
local v_u_10 = require(v_u_4.Std.Interval)
local v_u_11 = require(v_u_4.Game.Level2.LevelSystem)
local v_u_12 = require(v_u_4.Game.Level2.LevelUtils)
local v_u_13 = require(v_u_4.Module.Window.Window)
local v_u_14 = require(v_u_4.Game.GameUtil)
local v_u_15 = require(v_u_4.App.RunUtils)
local v_u_16 = require(v_u_4.EzUi.EzUtils)
local v_u_17 = require(v_u_4.EzUi.Utils)
local v_u_18 = require(v_u_4.Game.Contract.ContractUtils)
local v_u_19 = require(v_u_4.Game.Level2.LevelConsts)
local v_u_20 = require(v_u_4.Game.Season.SeasonUIUtils)
local v_u_21 = require(script.Parent.SeasonConsts)
local v_u_22 = require(script.Parent.SeasonUtils)
local v_u_23 = nil
local v_u_24 = nil
local v_u_72 = {
	["init"] = function()
		-- upvalues: (ref) v_u_23, (ref) v_u_24, (copy) v_u_4, (copy) v_u_2, (copy) v_u_72, (copy) v_u_21, (copy) v_u_13, (copy) v_u_14, (copy) v_u_6
		v_u_23 = require(script.Parent.SeasonSystem)
		v_u_24 = require(v_u_4.Game.Contract.ContractUISystem)
		local v25 = v_u_4.StarterGui:FindFirstChild("SeasonGui")
		v25.Parent = v_u_2.PlayerGui
		v_u_72.gui = v25
		v_u_72._seasonState = -1
		v25.Background.Title.Frame.SeasonNumWelcome.Text = ("Welcome to SEASON %d"):format(v_u_21.SEASON_NUM)
		v25.Background.Title.Frame.SeasonNumWelcome.TextLabel.Text = v25.Background.Title.Frame.SeasonNumWelcome.Text
		v25.Background.Title.Frame.SeasonTitle.Text = v_u_21.SEASON_TITLE
		local v26 = v_u_13.new()
		v26:GetOnOpenedSignal():Connect(v_u_72._open)
		v26:GetOnClosedSignal():Connect(v_u_72._close)
		v_u_72._window = v26
		v_u_14.getCenterWindowGroup():Add(v26)
		v_u_6(v_u_4, v_u_21.PRIZE_PURCHASE_REMOTE_NAME, 30):andThen(function(p27)
			-- upvalues: (ref) v_u_23
			v_u_23._prizePurchaseRemote = p27
		end):catch(warn)
		v25.Background.BonusAwards.Visible = v_u_21.SEASON_BONUS_ENABLED
	end,
	["_updateSeasonUi"] = function(p28)
		-- upvalues: (copy) v_u_72, (copy) v_u_21
		v_u_72._seasonState = p28
		local v29 = v_u_72.gui
		if p28 == 0 then
			v29.Background.Timer.Title.Text = "SEASON ENDS"
			v29.Background.Help.Text = v_u_21.SEASON_SUBTITLE
			v29.Background.Bottom.Container.ReviewButton.TextLabel.Text = "CONTRACTS"
			return
		elseif p28 == 1 then
			v29.Background.Timer.Title.Text = "BUYING ENDS"
			v29.Background.Help.Text = v_u_21.BUY_SUBTITLE
			v29.Background.Bottom.Container.ReviewButton.TextLabel.Text = "COMING SOON"
			return
		elseif p28 == 2 then
			v29.Background.Timer.Title.Text = "SEASON ENDS"
			v29.Background.Help.Text = v_u_21.POST_SUBTITLE
			v29.Background.Bottom.Container.ReviewButton.TextLabel.Text = "COMING SOON"
		else
			error(("Invalid season state: %d"):format(p28))
		end
	end,
	["_updateDeadline"] = function()
		-- upvalues: (copy) v_u_72, (copy) v_u_22, (copy) v_u_21, (copy) v_u_18, (copy) v_u_19
		local v30 = v_u_72.gui
		local v31 = v_u_22.getRemainingTime()
		local v32 = v31 < 0
		local v33 = v_u_22.isBuyEnabled()
		if v33 then
			local v34 = v_u_22.getRemainingBuyTime()
			local v35 = v_u_22.formatRemaining(v34)
			v30.Background.Timer.Time.Text = v35
		else
			local v36 = v_u_22.formatRemaining(v31)
			v30.Background.Timer.Time.Text = v36
		end
		local v37 = (v32 or v33) and (v33 and 1 or 2) or 0
		if v_u_72._seasonState ~= v37 then
			v_u_72._updateSeasonUi(v37)
		end
		local v38 = v30.Background.Body.Line.Container
		for v39 = 2, v_u_21.MAX_REWARD_LEVEL do
			local v40 = v38:FindFirstChild(("%02d"):format(v39)).Reward:FindFirstChild("Buy")
			if v40 then
				v40.Visible = v33
			end
		end
		local v41 = v30.Background.DailyExpRefreshHelp
		local v42 = v_u_18.getQuantizedBlock(v_u_19.DAILY_EXP_DURATION, v_u_19.DAILY_EXP_DURATION_OFFSET)
		v41.Text = ("Daily XP reloads in <font color=\"rgb(255, 207, 0)\">%s</font>!"):format(v_u_22.formatRemaining(v42 - workspace:GetServerTimeNow()))
	end,
	["_open"] = function()
		-- upvalues: (copy) v_u_72, (copy) v_u_8, (copy) v_u_17, (copy) v_u_10, (copy) v_u_2, (copy) v_u_11, (ref) v_u_23, (copy) v_u_22, (copy) v_u_5, (ref) v_u_24, (copy) v_u_16, (copy) v_u_21, (copy) v_u_15, (copy) v_u_9, (copy) v_u_7, (copy) v_u_3, (copy) v_u_20
		local v43 = v_u_72._maid == nil
		assert(v43)
		local v44 = v_u_8.new()
		v_u_72._maid = v44
		local v_u_45 = v_u_72.gui
		if v_u_17.isSmallScreen() then
			v_u_45.Background.BonusAwards.Position = UDim2.new(-0.15, 0, 0, 2)
		else
			v_u_45.Background.BonusAwards.Position = UDim2.new(1.01, 0, 0, 2)
		end
		v_u_45.Enabled = true
		v44:GiveTask(function()
			-- upvalues: (copy) v_u_45
			v_u_45.Enabled = false
		end)
		v44:GiveTask(v_u_10.every(1):Connect(v_u_72._updateDeadline))
		v_u_72._updateDeadline()
		v_u_72.updateProgress(v_u_2)
		v44:GiveTask(v_u_11.getOnLevelChangedSignal():Connect(v_u_72.updateProgress))
		v44:GiveTask(v_u_11.getOnExpChangedSignal():Connect(v_u_72.updateProgress))
		v44:GiveTask(v_u_23.getSeasonPassOwnedSignal():Connect(function(p46)
			-- upvalues: (ref) v_u_2, (ref) v_u_72
			if p46 == v_u_2 then
				v_u_72.updateProgress(v_u_2)
			end
		end))
		v44:GiveTask(v_u_45.Background.Bottom.Container.ReviewButton.MouseButton1Down:Connect(function()
			-- upvalues: (ref) v_u_22, (ref) v_u_5, (ref) v_u_2, (ref) v_u_72, (ref) v_u_24
			if v_u_22.getRemainingTime() >= 0 then
				v_u_5.ObjectLocal(v_u_2.PlayerGui, 6105461542)
				v_u_72.close()
				v_u_24.open()
			end
		end))
		local v47 = v_u_45.Background.Bottom.Container.ReviewButton
		v_u_16.selectIfGamepad(v47)
		v_u_45.Background.Bottom.Container.SeasonPass.Title.Text = ("SEASON %d: %s"):format(v_u_21.SEASON_NUM, v_u_21.SEASON_TITLE)
		v44:GiveTask(v_u_45.Background.Bottom.Container.SeasonPass.MouseButton1Down:Connect(function()
			-- upvalues: (ref) v_u_15, (ref) v_u_22, (ref) v_u_9, (ref) v_u_5, (ref) v_u_2, (ref) v_u_7, (ref) v_u_23, (ref) v_u_3
			if v_u_15.isStudio() or v_u_22.getRemainingTime() > 0 then
				v_u_5.ObjectLocal(v_u_2.PlayerGui, 6105461542)
				local v48 = v_u_7.getFirstProductByType("SeasonPass")
				local v49 = v48 ~= nil
				assert(v49)
				if not v_u_23.doesPlayerOwnSeasonPass(v_u_2) then
					v_u_3:PromptProductPurchase(v_u_2, v48.Id)
				end
			else
				v_u_9.new({
					["Text"] = "Season is over! Wait until next season."
				})
			end
		end))
		v_u_20.hookGiftContainer(v_u_45.Background.GiftContainer, v44)
		if v_u_23.doesPlayerOwnSeasonPass(v_u_2) then
			v_u_45.Background.Bottom.Container.SeasonPass.Buy.Visible = false
			v_u_45.Background.Bottom.Container.SeasonPass.Price.Visible = false
			v_u_45.Background.Bottom.Container.SeasonPass.Owned.Visible = true
		else
			v44:GiveTask(v_u_23.getSeasonPassOwnedSignal():Connect(function(p50)
				-- upvalues: (ref) v_u_2, (copy) v_u_45
				if p50 == v_u_2 then
					v_u_45.Background.Bottom.Container.SeasonPass.Buy.Visible = false
					v_u_45.Background.Bottom.Container.SeasonPass.Price.Visible = false
					v_u_45.Background.Bottom.Container.SeasonPass.Owned.Visible = true
				end
			end))
		end
		v44:GiveTask(v_u_45.Background.Close.MouseButton1Down:Connect(v_u_72.close))
		local function v54()
			-- upvalues: (ref) v_u_7, (copy) v_u_45
			local v51 = v_u_7.getFirstProductByType("SeasonPass")
			if v51 and v51.Robux then
				local v52 = v_u_45.Background.Bottom.Container.SeasonPass.Price
				local v53 = v51.Robux
				v52.Text = tostring(v53)
			end
		end
		local v55 = v_u_7.getFirstProductByType("SeasonPass")
		if v55 and v55.Robux then
			local v56 = v_u_45.Background.Bottom.Container.SeasonPass.Price
			local v57 = v55.Robux
			v56.Text = tostring(v57)
		end
		v_u_7.OnProductsFetched:Connect(v54)
		local v58 = v_u_45.Background.Body.Line.Container
		for v59 = 2, v_u_21.MAX_REWARD_LEVEL do
			local v60 = v_u_23.getClientLevelAward(v59)
			v58:FindFirstChild(("%02d"):format(v59)).Reward.Icon.Image = ("rbxassetid://%d"):format(v60.imageId)
		end
		local v61 = v_u_45.Background.BonusAwards.Container
		for v62 = 1, v_u_21.NUM_BONUS_AWARDS do
			local v63 = v_u_23.getClientBonusAward(v62)
			local v64 = v61:FindFirstChild(("Bonus%02d"):format(v62))
			v64.Icon.Image = ("rbxassetid://%d"):format(v63.imageId)
			v64.Desc.Text = ("TOP %d%%"):format(v63.scoreLte * 100)
		end
		if v_u_21.SEASON_BONUS_ENABLED then
			local v65 = v_u_2:FindFirstChild("SeasonBonusScore")
			local v66 = not v65 and "CHECK LATER..." or ("YOU: TOP %.2f%%"):format(v65.Value * 100)
			v_u_45.Background.BonusAwards.Score.Text = v66
		end
	end,
	["_close"] = function()
		-- upvalues: (copy) v_u_72
		local v67 = v_u_72._maid ~= nil
		assert(v67)
		local v68 = v_u_72._maid
		v_u_72._maid = nil
		v68:Destroy()
	end,
	["open"] = function()
		-- upvalues: (copy) v_u_72
		v_u_72._window:Open()
	end,
	["close"] = function()
		-- upvalues: (copy) v_u_72
		v_u_72._window:Close()
	end,
	["updateProgress"] = function(p69)
		-- upvalues: (copy) v_u_2, (copy) v_u_12, (copy) v_u_72
		if p69 == v_u_2 then
			local v70 = v_u_12.yieldLevel(p69)
			local v71 = v_u_12.yieldExp(p69)
			v_u_72.setProgress(v70, v71)
		end
	end
}
local function v_u_81(p73, p74, p75)
	-- upvalues: (copy) v_u_21
	local v76 = p73.Parent
	if v76 ~= nil then
		local v77 = v76.Size.X.Scale
		local v78 = (v77 - 1) * (1 / v77) / 2
		local v79 = (p74 - 1) / (v77 * (v_u_21.MAX_REWARD_LEVEL - 1)) + v78
		if p75 then
			local v80 = (p75 - 1) / (v77 * (v_u_21.MAX_REWARD_LEVEL - 1)) + v78
			v79 = v79 - v80
			p73.Position = UDim2.new(UDim.new(v80, p73.Position.X.Offset), p73.Position.Y)
		end
		p73.Size = UDim2.new(UDim.new(v79, p73.Size.X.Offset), p73.Size.Y)
		p73.Visible = true
	end
end
function v_u_72.setProgress(p82, p83)
	-- upvalues: (copy) v_u_19, (ref) v_u_23, (copy) v_u_2, (copy) v_u_22, (copy) v_u_1, (copy) v_u_21, (copy) v_u_72, (copy) v_u_12, (copy) v_u_81
	local v84 = v_u_19.MAX_DAILY_EXP
	if v_u_23.doesPlayerOwnSeasonPass(v_u_2) then
		v84 = v_u_19.MAX_DAILY_EXP_SEASON_PASS
	end
	local v85 = v84 * v_u_22.getSeasonExpMult()
	local v86 = v_u_1.LocalPlayer:FindFirstChild(v_u_19.DAILY_EXP_VALUE_NAME)
	if v86 then
		v85 = v85 - v86.Value
	end
	local v87 = v_u_22.getRemainingTime() < 0 and 0 or v85
	if v_u_21.MAX_REWARD_LEVEL <= p82 then
		p82 = v_u_21.MAX_REWARD_LEVEL
		p83 = 0
	end
	local v88 = v_u_72.gui
	local v89 = p82 + p83 / v_u_12.calculateExpNextLevel(p82)
	local v90, v91 = v_u_12.calculateLevelFromExp(v_u_12.calculateExpOfLevel(p82) + p83 + v87)
	if v_u_21.MAX_REWARD_LEVEL <= v90 then
		v90 = v_u_21.MAX_REWARD_LEVEL
		v91 = 0
	end
	local v92 = v90 + v91 / v_u_12.calculateExpNextLevel(v90)
	v_u_81(v88.Background.Body.Line.Bg.Progress1, v89)
	v_u_81(v88.Background.Body.Line.Bg.Progress2, v92, v89)
end
return v_u_72
