-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMwCERhdGVUaW1lA25vdw1Vbml4VGltZXN0YW1wD1NFQVNPTl9FTkRfVU5JWBBnZXRSZW1haW5pbmdUaW1lDEJVWV9FTkRfVU5JWBNnZXRSZW1haW5pbmdCdXlUaW1lF0FVVE9NQVRFX1NFQVNPTl9YUF9NVUxUGVNFQVNPTl9YUF9NVUxUX1NUQVJUX1VOSVgOU0VBU09OX1hQX01VTFQQZ2V0U2Vhc29uRXhwTXVsdAxpc0J1eUVuYWJsZWQERW51bQhJbmZvVHlwZQdQcm9kdWN0DkdldFByb2R1Y3RJbmZvDFByaWNlSW5Sb2J1eAdyZXNvbHZlBWRlZmVyD2dldFByb2R1Y3RQcmljZQR0eXBlBXRhYmxlBmFzc2VydApKU09ORW5jb2RlFnNlcmlhbGl6ZUxldmVsc0F3YXJkZWQGc3RyaW5nCkpTT05EZWNvZGUYZGVzZXJpYWxpemVMZXZlbHNBd2FyZGVkBG1hdGgDbWF4BWZsb29yByVkZCAlZGgGZm9ybWF0ByVkaCAlZG0HJWRtICVkcwMlZHMPZm9ybWF0UmVtYWluaW5nBGdhbWULSHR0cFNlcnZpY2UKR2V0U2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQdyZXF1aXJlA1N0ZAdQcm9taXNlEk1hcmtldHBsYWNlU2VydmljZQxTZWFzb25Db25zdHMGc2NyaXB0BlBhcmVudAAKBAABAAAACqQBAgAABACAnwEBAk0AAbcDAAAA+wMAAE0CA6gEAAAAJgECAIIBAgAFAwEDAgQABACAAwMDBAAJBQEYAAAAAAABAAAAAQoAAAAABAABAAAACqQBAgAABACAnwEBAk0AAbcDAAAA+wMAAE0CAxIEAAAAJgECAIIBAgAFAwEDAgQABACAAwMDBgAOBwEYAAAAAAABAAAAAQ8AAAAAAwABAAAAGPsBAABNAAFLAAAAAA4AEACkAQMAAAgQgJ8BAQJNAAG3BAAAAPsCAABNAQKiBQAAAGABBQAAAAAA+wIAAE0BAr8GAAAAggECAIwBAQCCAQIA+wEAAE0AAb8GAAAAggACAAcDCAMBAwIEAAgQgAMDAwkDCgATCwEYAAAAAAEAAAAAAQAAAAABAAAAAgADAAAAFgAAAAADAAEAAAASqQAAAPsCAABNAQKcAAAAAJ8BAQKMAgAAYAEKAAIAAAD7AgAATQEC/AEAAACfAQECjAIAANQCAgABAAAAqQAAAakAAQCCAAIAAgMFAwcAIQwBGAAAAAAAAAAAAAAAAAAAAAAAACIAAAAABQEDAAAAEPsBAAD7AwEApAQDAAIEAMC8AQF1BAAAAJ8BBAJNAgEbBQAAAPsDAgD7BAEAagIDBFIDAABSBAIAnwMCAYIAAQAGAw0DDgMPBAIEAMADEAMRACkAARgAAAAAAAAAAQABAAABAAABKgAAAAAEAQMAAAAT+wIAAIcBAgAOAQcA+wIBAE0BAh0AAAAA+wMAAIcCAwCfAQIAggEAAPsCAQBNAQJoAQAAANkCAAASAgIAEgAAABICAACfAQIAggEAAAIDEgMTAQQlFAEYAAAAAQAAAAAAAAIAAAAAAAAAACYAAAAABQEBAAAAE7soAANSBAAApAMBAAAAAECfAwIC8AMCAAIAAACpAgABqQIBALsBAgKkAQQAAAAwQJ8BAgH7AQAAUgMAALwBAZ4FAAAAnwEDAIIBAAAGAxUEAAAAQAMWAxcEAAAwQAMYADAZARgAAAAAAAAAAAAAAAAAAQAAAAAAMQAAAAAFAQEAAAATuygAA1IEAACkAwEAAAAAQJ8DAgLwAwIAAgAAAKkCAAGpAgEAuwECAqQBBAAAADBAnwECAfsBAABSAwAAvAEBywUAAACfAQMAggEAAAYDFQQAAABAAxoDFwQAADBAAxsANBwBGAAAAAAAAAAAAAAAAAABAAAAAAA1AAAAAAkBAAAAEwAABAMFJAIDBS4CAwU4AgMFPgJCjAIAAJ4SAgQAAAAAUgMAAKQBAgAABACAnwEDAlIAAQA+AgADuwwCAqQBBQAAEACAnwECAiEEAAM+AwQGuwwDAqQCBQAAEACAnwICAiEFAAY+BAUHuwwEAqQDBQAAEACAnwMCAiEFAAe7DAUCpAQFAAAQAICfBAICjAUAAGAFCAABAAAAbwUIAFIHAQBSCAIAvAUFjQkAAACfBQQAggUAAIwFAABgBQgAAgAAAG8FCgBSBwIAUggDALwFBY0JAAAAnwUEAIIFAACMBQAAYAUIAAMAAABvBQsAUgcDAFIIBAC8BQWNCQAAAJ8FBACCBQAAbwUMAFIHBAC8BQWNCQAAAJ8FAwCCBQAADQMdAx4EAAQAgAIAAAAAABj1QAMfBAAQAIACAAAAAAAgrEACAAAAAAAATkADIAMhAyIDIwMkADglARgAAAAAAAAAAAIAAAAAAQAAAAAAAQAAAAAAAQAAAAACAAABAAAAAAAAAQAAAQAAAAAAAAEAAAEAAAAAAAACAAAAAAA5AAAAAAgAAAECAEmjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIGAAAAUEBNBAGhBwAAAE0DBHIIAAAAnwICAqQDAQAAAABAbwUJALwDAxYDAAAAnwMDAqQEBgAAAFBApAcMAAAAsEBNBgckDQAAAE0FBrwKAAAAnwQCAv8FBAAAAAAAwAYOABIABAAwBgWcDwAAAMAGEAASAAQAMAYF/BEAAADABhIAEgAEADAGBbgTAAAAwAYUABIABQAwBgWxFQAAAP8GAAAAAAAAwAcWABIABgASAAIAEgADADAHBdQXAAAAwAcYABIAAAAwBwWyGQAAAMAHGgASAAAAMAcFchsAAADABxwAMAcF8R0AAACCBQIAHgMmBAAAAEADJwMoAykDKgQAAFBAAysDLAMtAy4DLwQAALBAAzAGAAMFBgEDBwYCAwsGAwMMBgUDFAYGAxkGBwMcBggDJQgAAQIDBQYHCAEAARgAAQAAAAAAAQAAAAAAAQAAAAAAAAEAAAAAAAEAAAAAAAAAAAIAAQAAAAUAAAAFAAAADgAAAAMAAQAAAAAACwAAAAQAAAAEAAASAQAAAAAJP49B1Ebm1OANSytAjH6U/PiJ6Tk75RdQx4Nu0ok+Ew0DPwCGdHE1Xg==

-- Decompiled by Krnl

local v_u_1 = game:GetService("HttpService")
local v2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v2.Std.Promise)
local v_u_4 = game:GetService("MarketplaceService")
local v_u_5 = require(script.Parent.SeasonConsts)
local v_u_9 = {
	["getRemainingTime"] = function()
		-- upvalues: (copy) v_u_5
		local v6 = DateTime.now().UnixTimestamp
		return v_u_5.SEASON_END_UNIX - v6
	end,
	["getRemainingBuyTime"] = function()
		-- upvalues: (copy) v_u_5
		local v7 = DateTime.now().UnixTimestamp
		return v_u_5.BUY_END_UNIX - v7
	end,
	["getSeasonExpMult"] = function()
		-- upvalues: (copy) v_u_5
		if v_u_5.AUTOMATE_SEASON_XP_MULT then
			return DateTime.now().UnixTimestamp <= v_u_5.SEASON_XP_MULT_START_UNIX and 1 or v_u_5.SEASON_XP_MULT
		else
			return v_u_5.SEASON_XP_MULT
		end
	end,
	["isBuyEnabled"] = function()
		-- upvalues: (copy) v_u_9
		local v8
		if v_u_9.getRemainingTime() < 0 then
			v8 = v_u_9.getRemainingBuyTime() >= 0
		else
			v8 = false
		end
		return v8
	end
}
local v_u_10 = {}
function v_u_9.getProductPrice(p_u_11)
	-- upvalues: (copy) v_u_10, (copy) v_u_3, (copy) v_u_4
	if v_u_10[p_u_11] then
		return v_u_3.resolve(v_u_10[p_u_11])
	else
		return v_u_3.defer(function(p12)
			-- upvalues: (ref) v_u_4, (copy) p_u_11, (ref) v_u_10
			local v13 = v_u_4:GetProductInfo(p_u_11, Enum.InfoType.Product).PriceInRobux
			v_u_10[p_u_11] = v13
			p12(v13)
		end)
	end
end
function v_u_9.serializeLevelsAwarded(p14)
	-- upvalues: (copy) v_u_1
	local v15 = type(p14) == "table"
	assert(v15)
	return v_u_1:JSONEncode(p14)
end
function v_u_9.deserializeLevelsAwarded(p16)
	-- upvalues: (copy) v_u_1
	local v17 = type(p16) == "string"
	assert(v17)
	return v_u_1:JSONDecode(p16)
end
function v_u_9.formatRemaining(p18)
	local v19 = math.max(0, p18)
	local v20 = v19 / 86400
	local v21 = math.floor(v20)
	local v22 = v19 % 86400 / 3600
	local v23 = math.floor(v22)
	local v24 = v19 % 3600 / 60
	local v25 = math.floor(v24)
	local v26 = v19 % 60
	local v27 = math.floor(v26)
	if v21 > 0 then
		return ("%dd %dh"):format(v21, v23)
	elseif v23 > 0 then
		return ("%dh %dm"):format(v23, v25)
	elseif v25 > 0 then
		return ("%dm %ds"):format(v25, v27)
	else
		return ("%ds"):format(v27)
	end
end
return v_u_9
