-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMJBU1vZGVsClNlY29uZEJvZHkORmluZEZpcnN0Q2hpbGQETWFrZQRUYW5rClRoZVJhdHRsZXIFTUNMMzYJTUNMMzZGUkVFBVNsb29wAAIGAQAAAAAlTQEAOwAAAAArAQEAggABAG8EAQCpBQEAvAIBAwIAAACfAgQCKwIaAKkCAQBNAwCtAwAAAPADFgAEAAAAqQIBAE0DAK0DAAAA8AMRAAUAAACpAgEATQMArQMAAADwAwwABgAAAKkCAQBNAwCtAwAAAPADBwAHAAAATQMArQMAAADwAwIACAAAAKkCAAGpAgEAggICAAkDAQMCAwMDBAMFAwYDBwMIAwkAAgABGAAAAQECAAAAAAAAAQAAAAABAAAAAAEAAAAAAQAAAAEAAAAAAAADAAAAAAEAAAECAAOjAAAAwAAAAIIAAgABBgABAAEAARgAAQABAAAAAAEqJT7chLsYhBjhVEiCFvJ6qaub/x3BfI+T252uKaC/YfSsoLNW+aLb

-- Decompiled by Krnl

return function(p1)
	local v2 = p1.Model
	if v2 then
		return v2:FindFirstChild("SecondBody", true) or ((p1.Make == "Tank" or (p1.Make == "TheRattler" or (p1.Make == "MCL36" or p1.Make == "MCL36FREE"))) and true or p1.Make == "Sloop")
	end
end
