-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMTBU1vZGVsA0lzQQhCYXNlUGFydAZhc3NlcnQMQ2lyY2xlQWN0aW9uBkhhc1RhZxBDaXJjbGVBY3Rpb25EaXN0DFNldEF0dHJpYnV0ZQdzZXREaXN0FENpcmNsZUFjdGlvbkR1cmF0aW9uC3NldER1cmF0aW9uEENpcmNsZUFjdGlvblRleHQHc2V0VGV4dBRDaXJjbGVBY3Rpb25EaXNhYmxlZAtzZXREaXNhYmxlZAxHZXRBdHRyaWJ1dGULZ2V0RGlzYWJsZWQLUHJpbWFyeVBhcnQKZ2V0VGFnUGFydAAHBgIAAAAHBAAABQIHDxtvBQAAvAMA/gEAAACfAwMCKwMEAG8FAgC8AwD+AQAAAJ8DAwK7AQMCpAIEAAAAMECfAgIBbwUFALwDAN4GAAAAnwMDAEwBAAKkAgQAAAAwQJ8CAAFvBAcAUgUBALwCAC4IAAAAnwIEAYIAAQAJAwEDAgMDAwQEAAAwQAMFAwYDBwMIAAMJARgAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAEEAAAAAAYCAAAABwQAAAUCBw8bbwUAALwDAP4BAAAAnwMDAisDBABvBQIAvAMA/gEAAACfAwMCuwEDAqQCBAAAADBAnwICAW8FBQC8AwDeBgAAAJ8DAwBMAQACpAIEAAAAMECfAgABbwQHAFIFAQC8AgAuCAAAAJ8CBAGCAAEACQMBAwIDAwMEBAAAMEADBQMGAwoDCAAICwEYAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAABCQAAAAAGAgAAAAcEAAAFAgcPG28FAAC8AwD+AQAAAJ8DAwIrAwQAbwUCALwDAP4BAAAAnwMDArsBAwKkAgQAAAAwQJ8CAgFvBQUAvAMA3gYAAACfAwMATAEAAqQCBAAAADBAnwIAAW8EBwBSBQEAvAIALggAAACfAgQBggABAAkDAQMCAwMDBAQAADBAAwUDBgMMAwgADQ0BGAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAQ4AAAAABgIAAAAHBAAABQIHDxtvBQAAvAMA/gEAAACfAwMCKwMEAG8FAgC8AwD+AQAAAJ8DAwK7AQMCpAIEAAAAMECfAgIBbwUFALwDAN4GAAAAnwMDAEwBAAKkAgQAAAAwQJ8CAAFvBAcAUgUBALwCAC4IAAAAnwIEAYIAAQAJAwEDAgMDAwQEAAAwQAMFAwYDDgMIABIPARgAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAETAAAAAAUBAAAABgMAAAUBBx5vBAAAvAIA/gEAAACfAgMCKwIEAG8EAgC8AgD+AQAAAJ8CAwK7AQICpAEEAAAAMECfAQIBbwQFALwCAN4GAAAAnwIDAEwBAAKkAQQAAAAwQJ8BAAFvBAcAvAIAEggAAACfAgMCKgICAAEAAACpAQABqQEBAIIBAgAJAwEDAgMDAwQEAAAwQAMFAwYDDgMQABcRARgAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAYAAAAAAYBAAAABgMAAAUBByhvBAAAvAIA/gEAAACfAgMCKwIEAG8EAgC8AgD+AQAAAJ8CAwK7AQICpAEEAAAAMECfAQIBbwQFALwCAN4GAAAAnwIDAEwBAAKkAQQAAAAwQJ8BAAHGAQAAbwQAALwCAP4BAAAAnwIDAg4CAwBNAQCbBwAAAIIBAgBvBQIAvAMA/gEAAACfAwMATAEAAqQCBAAAADBAnwIAAVIBAACCAQIACAMBAwIDAwMEBAAAMEADBQMGAxIAHBMBGAAAAAAAAAAAAAAAAAABAAAAAAAAAAEBAAAAAAEAAAIAAAAAAAAAAQIdAAAAAAIAAAECABajAAAA/wAEAAAAAADAAQAAMAEAPAEAAADAAQIAMAEAlQMAAADAAQQAMAEAZQUAAADAAQYAMAEAqQcAAADAAQgAMAEA3QkAAADAAQoAMAEAugsAAACCAAIADAYAAwkGAQMLBgIDDQYDAw8GBAMRBgUDEwYAAQIDBAUBAAEYAAEAAQAABQAABQAABQAABQAABQAADAEAAAAABgwPAzeXQ+GSPstpo+C4eHnFwMFAXqJUVTPksR61+ZtoTOKzCIoGJuk=

-- Decompiled by Krnl

return {
	["setDist"] = function(p1, p2)
		local v3 = p1:IsA("Model") or p1:IsA("BasePart")
		assert(v3)
		assert(p1:HasTag("CircleAction"))
		p1:SetAttribute("CircleActionDist", p2)
	end,
	["setDuration"] = function(p4, p5)
		local v6 = p4:IsA("Model") or p4:IsA("BasePart")
		assert(v6)
		assert(p4:HasTag("CircleAction"))
		p4:SetAttribute("CircleActionDuration", p5)
	end,
	["setText"] = function(p7, p8)
		local v9 = p7:IsA("Model") or p7:IsA("BasePart")
		assert(v9)
		assert(p7:HasTag("CircleAction"))
		p7:SetAttribute("CircleActionText", p8)
	end,
	["setDisabled"] = function(p10, p11)
		local v12 = p10:IsA("Model") or p10:IsA("BasePart")
		assert(v12)
		assert(p10:HasTag("CircleAction"))
		p10:SetAttribute("CircleActionDisabled", p11)
	end,
	["getDisabled"] = function(p13)
		local v14 = p13:IsA("Model") or p13:IsA("BasePart")
		assert(v14)
		assert(p13:HasTag("CircleAction"))
		return p13:GetAttribute("CircleActionDisabled") == true
	end,
	["getTagPart"] = function(p15)
		local v16 = p15:IsA("Model") or p15:IsA("BasePart")
		assert(v16)
		assert(p15:HasTag("CircleAction"))
		if p15:IsA("Model") then
			return p15.PrimaryPart
		end
		assert(p15:IsA("BasePart"))
		return p15
	end
}
