-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMrFENpcmNsZUFjdGlvbkRpc2FibGVkDEdldEF0dHJpYnV0ZQdFbmFibGVkFENpcmNsZUFjdGlvbkR1cmF0aW9uCER1cmF0aW9uBVRpbWVkCmdldFRhZ1BhcnQFTW9kZWwDSXNBCVZhbGlkUm9vdARQYXJ0EENpcmNsZUFjdGlvblRleHQETmFtZRBDaXJjbGVBY3Rpb25EaXN0BERpc3QMcHJlVXBkYXRlRnVuCkZpcmVTZXJ2ZXINcHJlc3NDYWxsYmFjawNuZXcMc2V0bWV0YXRhYmxlD09uUHJlc3NlZFJlbW90ZQxXYWl0Rm9yQ2hpbGQIQ2FsbGJhY2sMUHJlVXBkYXRlRnVuD1ByZVVwZGF0ZVBlcmlvZBFbIyMjIE1JU1NJTkcgIyMjXQRtYWlkDENpcmNsZUFjdGlvbgNBZGQIR2l2ZVRhc2sEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUGc2NyaXB0BlBhcmVudBFDaXJjbGVBY3Rpb25VdGlscwNTdGQKQmFzZU9iamVjdAZCaW5kZXIGTW9kdWxlAlVJB19faW5kZXgABAYBAgAAAEH7AwAAbwUAALwDAxIBAAAAnwMDAioDAgABAAAAqQIAAakCAQBWAQIAMAEA8AIAAAD7AgAAbwQEALwCAhIBAAAAnwIDApABAgMwAQDlBQAAAE0CAOUFAAAAbwMGALcDAgACAAAAqQEAAakBAQAwAQBxBwAAAPsCAQBNAQK6CAAAAPsCAACfAQIC+wIAAG8ECQC8AgL+CgAAAJ8CAwIOAgMA+wIAADACAEkLAAAAMAEARAwAAAD7AgAAbwQNALwCAhIBAAAAnwIDAisCAwD7AwAATQIDug4AAAAwAgC6DgAAAPsDAABvBRAAvAMDEgEAAACfAwMCkAIDDzACAOMRAAAAggABABIDAQMCAwMCAAAAAAAAAAADBAMFAvyp8dJNYlA/AwYDBwMIAwkDCgMLAwwDDQIAAAAAAAAkQAMOAw8AExABGAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAgAAAAABAAAAAAABAAACAAEAAAAAAAAAAAAAAQAAAAAAAAABFAAAAAAFAgEAAAAG+wIAAFIEAQC8AgJrAAAAAJ8CAwGCAAEAAQMRACASARgAAAAAAAEhAAAAAAsBBAAAADf7AgAATQEC7wAAAABSAgAAnwECAvsEAQCePQEEBAAAAFIDAQCkAgIAAAAQQJ8CAwFvBAMAvAIA0wQAAACfAgMC2QMAABIAAAASAgIA2QQBABIAAgDiBQwAbwYNADAGBboFAAAAqQYAADAGBXEGAAAAjAYAADAGBeMHAAAAMAQFRggAAACpBgEAMAYF8AkAAAAwAwWjCgAAAG8GDgAwBgVECwAAAE0GARYPAAAA+woDAE0JCt0QAAAATQgJXxEAAABSCQUAUgoAAJ8IAwC8Bgb9EgAAAJ8GAAGCAQIAEwMTAxQEAAAQQAMVAxYDDQMGAw8DFwMDAxgDGQUHBQYHCAkKCwMaApqZmZmZmck/AxsDHAMdAx4CAAENEwEYAAAAAAABAAAAAAAAAgAAAAIAAA0AAwEAAAEAAAEAAAEAAQAAAQABAAADAAAAAAAAAAAAAAAAAg4AAAAACQAAAQIAPaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQKQEBwAAAGBATQMEJAgAAABNAgP3CQAAAJ8BAgKkAgUAAABAQE0EAKEKAAAATQMESwsAAACfAgICpAMFAAAAQEBNBQChCgAAAE0EBX8MAAAAnwMCAqQEBQAAAEBATQYAQA0AAABNBQZcDgAAAJ8EAgL/BQIAAAAAADAFBW4PAAAAnj0FBQIAAABSBwUAUggCAKQGEQAAAABBnwYDAcAGEgASAAIAEgAFABIAAQASAAQAMAYF7xMAAABNBgPvEwAAAG8HFABSCAUAnwYDAIIGAAAVAx8EAAAAQAMgAyEDIgQAAEBAAyMEAABgQAMkAyUDJgMnAygDKQMqAysDFAQAAABBBgIDEwMcAQIBAAEYAAEAAAAAAAEAAAAAAAAAAAEAAAAAAAABAAAAAAAAAgAAAAAAAAIAAQABAAAAAAAAAgAAAAAAACUAAAAAAAEAAAAAAzkWPSqDd3HeC9JXvunA+sSHNWDcJGoUqIR4bLoOClPXEkymDp5l1OU=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(script.Parent.CircleActionUtils)
local v_u_3 = require(v1.Std.BaseObject)
local v4 = require(v1.Std.Binder)
local v_u_5 = require(v1.Module.UI)
local v_u_6 = {}
v_u_6.__index = v_u_6
setmetatable(v_u_6, v_u_3)
function v_u_6.new(p_u_7)
	-- upvalues: (copy) v_u_3, (copy) v_u_6, (copy) v_u_2, (copy) v_u_5
	local v8 = v_u_3.new(p_u_7)
	local v9 = v_u_6
	setmetatable(v8, v9)
	local v_u_10 = p_u_7:WaitForChild("OnPressedRemote")
	local v14 = {
		["Name"] = "[### MISSING ###]",
		["Timed"] = false,
		["Dist"] = 0,
		["Callback"] = function(_, p11)
			-- upvalues: (copy) v_u_10
			v_u_10:FireServer(p11)
		end,
		["Enabled"] = true,
		["PreUpdateFun"] = function(p12)
			-- upvalues: (copy) p_u_7, (ref) v_u_2
			p12.Enabled = p_u_7:GetAttribute("CircleActionDisabled") ~= true
			p12.Duration = p_u_7:GetAttribute("CircleActionDuration") or 0
			p12.Timed = p12.Duration > 0.001
			local v13 = v_u_2.getTagPart(p_u_7)
			if p_u_7:IsA("Model") then
				p12.ValidRoot = p_u_7
			end
			p12.Part = v13
			p12.Name = p_u_7:GetAttribute("CircleActionText") or p_u_7.Name
			p12.Dist = p_u_7:GetAttribute("CircleActionDist") or 10
		end,
		["PreUpdatePeriod"] = 0.2
	}
	v8.maid:GiveTask(v_u_5.CircleAction.Add(v14, p_u_7))
	return v8
end
return v4.new("CircleAction", v_u_6)
