-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNKAm9zBWNsb2NrBkNGcmFtZQZBbmdsZXMEbWF0aANzaW4DbmV3C0JvdW5kaW5nQm94BFNpemUJTWFnbml0dWRlE3VwZGF0ZVZlaGljbGVDYW1lcmEGaXBhaXJzBE1ha2UVZ2V0VmVoaWNsZURhdGFGb3JNYWtlC0dldEluc3RhbmNlBFR5cGUIZ2V0TW9kZWwISXRlbVR5cGUQbWlzc2luZyBJdGVtVHlwZQZhc3NlcnQfVkVISUNMRV9DVVNUT01JWkFUSU9OX0lURU1fVFlQRQxDYXRlZ29yeU5hbWURR2V0Q2F0ZWdvcnlCeU5hbWUISXRlbU5hbWUNR2V0SXRlbUJ5TmFtZQZ0eXBlb2YFdGFibGUEd2FybhVNaXNzaW5nIHZlaEN1c3QgZm9yOiABLwdnZXRJbnN0B1ZlaEN1c3QOZ2V0SW5zdENvbXBhcmUGVXBkYXRlDHVwZGF0ZUNhbWVyYRFWRUhJQ0xFX0lURU1fVFlQRQdWZWhpY2xlE0hPTUVfSVRFTV9JVEVNX1RZUEUPZ2V0VXBkYXRlQ2FtZXJhCEhvbWVJdGVtE0lURU1fU0tJTl9JVEVNX1RZUEUIU2tpbk5hbWUISXRlbVNraW4OU0FGRV9JVEVNX1RZUEUIVHlwZUVudW0NcmJ4YXNzZXRpZDovLwdJbWFnZUlkCHRvc3RyaW5nBWltYWdlBFNhZmUUQ09OU1VNQUJMRV9JVEVNX1RZUEUKQ29uc3VtYWJsZQVlcnJvchJJbnZhbGlkIEl0ZW1UeXBlOiAEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUKUGxheWVyRGF0YRBQbGF5ZXJEYXRhQ29uc3RzBEdhbWUGR2FyYWdlCVN0b3JlRGF0YQJVSQ9JdGVtU2tpblVJVXRpbHMESG9tZQ9Ib21lSXRlbVVJVXRpbHMWZ2V0RGVmYXVsdFZlaGljbGVNb2RlbAtWZWhpY2xlRGF0YQVTYWZlcwtTYWZlc0NvbnN0cwlTQUZFX0RBVEELQ29uc3VtYWJsZXMPQ29uc3VtYWJsZXNEYXRhAAgMAgAAAAAnpAMDAAAIEICfAwECPgIDAKQFBgAAFECAjAYAACEHAgeMCAAAnwUEAqQGBgAAFECAWwoCCrsYCgKkCQ0AADCwgJ8JAgJbCAkJeAcICIwIAACMCQAAnwYEAgkEBQakBQ8AADhAgIwGAACMBwAATQsBbxEAAABNCgsvEgAAAE0JCqoTAAAAWwgJEJ8FBAIJAwQFMAMAhQQAAACCAAEAFAIAAAAAAAAAQAMBAwIEAAgQgAMDAwQEABRAgAIYLURU+yEZQAIzMzMzMzPTPwIAAAAAAADQPwIAAAAAAADgPwMFAwYEADCwgAMHBAA4QIACmpmZmZmZ6T8DCAMJAwoADQsBGAAAAAABAAAAAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAP4AAw4AAAAABwEBAAAADaQBAQAAAABA+wIAAJ8BAgRRAQUATQYFrQIAAACaBgIAAAAAAIIFAgBuAfr/AgAAgIIAAQADAwwEAAAAQAMNABQOARgAAAAAAAEAAAAB/gAFFQAAAAACAAIAAAAG+wEAAE0AAVEAAAAA+wEBAJ8AAgCCAAAAAQMPACkAARgAAAAAAAAqAAAAAAQAAwAAAAf7AAAA+wEBAPsDAgBNAgMRAAAAAJ8AAwCCAAAAAQMQADEAARgAAAAAAAAAMgAAAAACAAIAAAAG+wEAAE0AASIAAAAA+wEBAJ8AAgCCAAAAAQMRADgAARgAAAAAAAA5AAAAAAIAAgAAAAb7AQAATQABIgAAAAD7AQEAnwACAIIAAAABAxEAPwABGAAAAAAAAEAAAAAADAEJAAAA4QFNAgAyAAAAAIEBAgQBAAAAbwMBAKQBAwAAACBAnwEDAf8BAwAAAAAATQIAMgAAAAD7BAAATQMEMQQAAACaAjEAAwAAAE0CAF4FAAAA+wQBAE0DBAYGAAAAUgQCAJ8DAgJNBAABBwAAAPsGAQBNBQahCAAAAFIGAgBSBwQAnwUDAg4FBwC7LAUDUgcFAKQGCgAAAJBAnwYCAvAGCgALAAAApAYNAAAAwEBvCA4AUgkCAG8KDwBSCwQAcwcIC58GAgGCAAEA2QYAABIAAwASAAUAMAYBQRAAAABvBxEAUggCAFIJBABzBgcJMAYB+BIAAABNBgMmEwAAADAGAREUAAAAggECAE0CADIAAAAA+wQAAE0DBLgVAAAAmgIgAAMAAABNAgCtFgAAAKQEGAAAAHBB+wUCAJ8EAgRRBAYATQkIrRYAAACaCQMAAgAAAFIDCABlAAMAbgT5/wIAAIDGAwAA2QQBABICAwASAAIAEgADADAEAUEQAAAAbwUZAFIGAgBzBAUGMAQB+BIAAAD7BAQAMAQBERQAAACCAQIATQIAMgAAAAD7BAAATQME3BoAAACaAhQAAwAAAE0CAAEHAAAA2QMCABICBQASAAIAMAMBQRAAAAD7BAUATQMEbBsAAACfAwECMAMBERQAAABvBBwAUgUCAHMDBAUwAwH4EgAAAIIBAgBNAgAyAAAAAPsEAABNAwSEHQAAAJoCFAADAAAATQIAtR4AAADZAwMAEgIGABIAAgAwAwFBEAAAAPsEBgBNAwRsGwAAAJ8DAQIwAwERFAAAAG8EHwBSBQIAcwMEBTADAfgSAAAAggECAE0CADIAAAAA+wQAAE0DBE4gAAAAmgIZAAMAAABNAgCKIQAAAPsEBwCHAwQCbwUiAE0HA5YjAAAAuz8HAqQGJQAAAEBCnwYCAnMEBQYwBAHJJgAAAG8FJwC7PwIDUgcCAKQGJQAAAEBCnwYCAnMEBQYwBAH4EgAAAIIBAgBNAgAyAAAAAPsEAABNAwSnKAAAAJoCFQADAAAATQIAAQcAAAD7BAgAhwMEAm8FIgBNBwOWIwAAALs/BwKkBiUAAABAQp8GAgJzBAUGMAQBySYAAABvBSkAUgYCAHMEBQYwBAH4EgAAAIIBAgCkAisAAACgQm8ELABNBgAyAAAAALs/BgKkBSUAAABAQp8FAgJzAwQFnwICAYIBAgAtAxIDEwMUBAAAIEADFQMWAxcDGAMZAxoEAACQQAMbAxwEAADAQAMdAx4DHwMgAyEDIgMjAyQDDQMMBAAAcEEDJQMmAycDKAMpAyoDKwMsAy0DLgMvAzAEAABAQgMxAzIDMwM0AzUEAACgQgM2BAIDBAUcAAEYCAAAAAAAAAACAAEAAAAAAAABAAEAAAAAAQABAAAAAAABAAAAAAAAAAEAAAAAAAAAAQIAAAAAAwAAAAAAAQAAAAABAAAAAAAAAQDmAAAAAAEAAAABAP4AABwAAAAAAAMAAAAAAQAAAAEAAAAAAAABAAEAAAAAAwAAAAAAAQAAAAAAAQAAAAAAAAEAAQAAAAADAAAAAAABAAAAAAABAAAAAAAAAQABAAEAAAAAAAAAAAABAAAAAAAAAAAAAQAAAAAAAAEAAQABAAAAAAAAAAAAAQAAAAAAAgAAAAAAAAAAAAACFQAAAAANAAABAgBZowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMA9gYAAABNAgOvBwAAAJ8BAgKkAgUAAABAQE0FAL0IAAAATQQFKAkAAABNAwQwCgAAAJ8CAgKkAwUAAABAQE0HAL0IAAAATQYH4QsAAABNBQZcDAAAAE0EBQYNAAAAnwMCAqQEBQAAAEBATQcAag4AAABNBgfpDwAAAE0FBmYQAAAAnwQCAqQFBQAAAEBATQcAvQgAAABNBgd2EQAAAJ8FAgKkBgUAAABAQE0JAL0IAAAATQgJKAkAAABNBwhVEgAAAJ8GAgKkBwUAAABAQE0JACITAAAATQgJcxQAAACfBwICTQgHHRUAAACkCQUAAABAQE0LAMgWAAAATQoLCBcAAACfCQICwAoYAMALGQASAAYAwAwaABIAAQASAAIAEgAGABIABQASAAoAEgAEABIAAwASAAgAEgAJAIIMAgAbAzcEAAAAQAM4AzkDOgQAAEBAAzsDPAM9Az4DPwMrA0ADQQNCAygDQwNEA0UDRgNHA0gDSQNKBgAGAQYGAwABBgEAARgAAQAAAAAAAQAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAEAAAAAAAABAAEAAAAAAAACBwAIAAAAAAAAAAAAAAEAAAAABx0fKalxZYzfL9tDPWDKW0ctg3/v9VFJZqYaewFJyzmeyNT1ArWSHQg=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.PlayerData.PlayerDataConsts)
local v_u_3 = require(v1.Game.Garage.StoreData)
local v_u_4 = require(v1.Game.ItemSkin.UI.ItemSkinUIUtils)
local v_u_5 = require(v1.Home.HomeItem.HomeItemUIUtils)
local v_u_6 = require(v1.Game.getDefaultVehicleModel)
local v_u_7 = require(v1.Game.Garage.VehicleData)
local v_u_8 = require(v1.Safes.SafesConsts).SAFE_DATA
local v_u_9 = require(v1.Consumables.ConsumablesData)
local function v_u_16(p10, p11)
	local v12 = os.clock() / 2
	local v13 = CFrame.Angles(0, v12 % 6.283185307179586, 0)
	local v14 = CFrame.Angles
	local v15 = v12 * 0.5
	p10.CFrame = v13 * v14(math.sin(v15) * 0.25 - 0.3, 0, 0) * CFrame.new(0, 0, p11.BoundingBox.Size.Magnitude * 0.8)
end
return function(p17)
	-- upvalues: (copy) v_u_2, (copy) v_u_3, (copy) v_u_7, (copy) v_u_6, (copy) v_u_16, (copy) v_u_5, (copy) v_u_4, (copy) v_u_8, (copy) v_u_9
	local v18 = p17.ItemType
	assert(v18, "missing ItemType")
	local v19 = {}
	if p17.ItemType == v_u_2.VEHICLE_CUSTOMIZATION_ITEM_TYPE then
		local v20 = p17.CategoryName
		local v_u_21 = v_u_3.GetCategoryByName(v20)
		local v22 = p17.ItemName
		local v_u_23 = v_u_3.GetItemByName(v20, v22)
		if v_u_23 and typeof(v_u_23) == "table" then
			function v19.getInst()
				-- upvalues: (copy) v_u_21, (copy) v_u_23
				return v_u_21.GetInstance(v_u_23)
			end
			v19.getInstCompare = "VehCust" .. v20 .. v22
			v19.updateCamera = v_u_21.Update
			return v19
		end
		warn("Missing vehCust for: " .. v20 .. "/" .. v22)
		return
	end
	if p17.ItemType ~= v_u_2.VEHICLE_ITEM_TYPE then
		if p17.ItemType == v_u_2.HOME_ITEM_ITEM_TYPE then
			local v_u_24 = p17.ItemName
			function v19.getInst()
				-- upvalues: (ref) v_u_5, (copy) v_u_24
				return v_u_5.getModel(v_u_24)
			end
			v19.updateCamera = v_u_5.getUpdateCamera()
			v19.getInstCompare = "HomeItem" .. v_u_24
			return v19
		end
		if p17.ItemType == v_u_2.ITEM_SKIN_ITEM_TYPE then
			local v_u_25 = p17.SkinName
			function v19.getInst()
				-- upvalues: (ref) v_u_4, (copy) v_u_25
				return v_u_4.getModel(v_u_25)
			end
			v19.updateCamera = v_u_4.getUpdateCamera()
			v19.getInstCompare = "ItemSkin" .. v_u_25
			return v19
		end
		if p17.ItemType == v_u_2.SAFE_ITEM_TYPE then
			local v26 = p17.TypeEnum
			local v27 = v_u_8[v26].ImageId
			v19.image = "rbxassetid://" .. tostring(v27)
			v19.getInstCompare = "Safe" .. tostring(v26)
			return v19
		end
		if p17.ItemType ~= v_u_2.CONSUMABLE_ITEM_TYPE then
			local v28 = error
			local v29 = p17.ItemType
			v28("Invalid ItemType: " .. tostring(v29))
			return v19
		end
		local v30 = p17.ItemName
		local v31 = v_u_9[v30].ImageId
		v19.image = "rbxassetid://" .. tostring(v31)
		v19.getInstCompare = "Consumable" .. v30
		return v19
	end
	local v_u_32 = p17.Make
	for _, v_u_34 in ipairs(v_u_7) do
		if v_u_34.Make == v_u_32 then
			::l11::
			function v19.getInst()
				-- upvalues: (ref) v_u_6, (copy) v_u_32, (copy) v_u_34
				return v_u_6(v_u_32, v_u_34.Type)
			end
			v19.getInstCompare = "Vehicle" .. v_u_32
			v19.updateCamera = v_u_16
			return v19
		end
	end
	local v_u_34 = nil
	goto l11
end
