-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgOcAgVlcnJvcjtMdWFFbmNvZGU6IEluY29ycmVjdCB0eXBlIGZvciBgJXNgOiBgJXNgIGV4cGVjdGVkLCBnb3QgYCVzYAIsIAlDaGVja1R5cGUBIgxbJXpcIgEtH38t/10PU2VyaWFsaXplU3RyaW5nAAglXSg9KiklXQE9Ay0tWwFbAV0MQ29tbWVudEJsb2NrC0ZpbmRTZXJ2aWNlCUNsYXNzTmFtZQlJc1NlcnZpY2UETmFtZQZQYXJlbnQMOkdldFNlcnZpY2UoASkYXltBLVphLXpfXVtBLVphLXowLTlfXSokAS4EZ2FtZQl3b3Jrc3BhY2UURXZhbHVhdGVJbnN0YW5jZVBhdGgIVHlwZUNhc2UEQXJnc0YoZnVuY3Rpb24odiwgcCkgZm9yIHBuLCBwdiBpbiBuZXh0LCBwIGRvIHZbcG5dID0gcHYgZW5kIHJldHVybiB2IGVuZCkoBXRhYmxlBlBhcmFtcwltYXRoLmh1Z2UKLW1hdGguaHVnZQUlLjE0Zyh7LS1bW0x1YUVuY29kZTogRHVwbGljYXRlIHJlZmVyZW5jZSVzXV19DCAob2YgcGFyZW50KQhQcmV0dGlmeQtJbmRlbnRDb3VudAtfU3RhY2tMZXZlbA5fVmlzaXRlZFRhYmxlcwNuaWxkZnVuY3Rpb24oKSAtLVtbTHVhRW5jb2RlOiBgb3B0aW9ucy5GdW5jdGlvbnNSZXR1cm5SYXdgIGZhbHNlOyBjYW4ndCBzZXJpYWxpemUgZnVuY3Rpb25zXV0gcmV0dXJuIGVuZAFYC0VudW0uQXhpcy5YAVkLRW51bS5BeGlzLlkBWgtFbnVtLkF4aXMuWglBeGVzLm5ldygPQnJpY2tDb2xvci5uZXcoBnN0cmluZwZOdW1iZXILQ0ZyYW1lLm5ldygKY29tcG9uZW50cw1TZWFyY2hLZXl3b3JkCE1pblByaWNlCE1heFByaWNlCFNvcnRUeXBlDkNhdGVnb3J5RmlsdGVyC0J1bmRsZVR5cGVzCkFzc2V0VHlwZXMZQ2F0YWxvZ1NlYXJjaFBhcmFtcy5uZXcoKQtDb2xvcjMubmV3KAFSAUcBQhJDb2xvclNlcXVlbmNlLm5ldygJS2V5cG9pbnRzGkNvbG9yU2VxdWVuY2VLZXlwb2ludC5uZXcoBFRpbWUFVmFsdWUbRGF0ZVRpbWUuZnJvbVVuaXhUaW1lc3RhbXAoDVVuaXhUaW1lc3RhbXAcRG9ja1dpZGdldFBsdWdpbkd1aUluZm8ubmV3KARFbnVtEEluaXRpYWxEb2NrU3RhdGUWSW5pdGlhbERvY2tTdGF0ZTooJXcrKRRJbml0aWFsRW5hYmxlZDooJXcrKQExKUluaXRpYWxFbmFibGVkU2hvdWxkT3ZlcnJpZGVSZXN0b3JlOigldyspE0Zsb2F0aW5nWFNpemU6KCV3KykTRmxvYXRpbmdZU2l6ZTooJXcrKQ5NaW5XaWR0aDooJXcrKQ9NaW5IZWlnaHQ6KCV3KykFRW51bS4DVG9wEUVudW0uTm9ybWFsSWQuVG9wBkJvdHRvbRRFbnVtLk5vcm1hbElkLkJvdHRvbQRMZWZ0EkVudW0uTm9ybWFsSWQuTGVmdAVSaWdodBNFbnVtLk5vcm1hbElkLlJpZ2h0BEJhY2sSRW51bS5Ob3JtYWxJZC5CYWNrBUZyb250E0VudW0uTm9ybWFsSWQuRnJvbnQKRmFjZXMubmV3KBJGbG9hdEN1cnZlS2V5Lm5ldygNSW50ZXJwb2xhdGlvbglGb250Lm5ldygGRmFtaWx5BldlaWdodAVTdHlsZQ1JbnN0YW5jZS5uZXcoEE51bWJlclJhbmdlLm5ldygDTWluA01heBNOdW1iZXJTZXF1ZW5jZS5uZXcoG051bWJlclNlcXVlbmNlS2V5cG9pbnQubmV3KAhFbnZlbG9wZRpGaWx0ZXJEZXNjZW5kYW50c0luc3RhbmNlcwpGaWx0ZXJUeXBlCE1heFBhcnRzDkNvbGxpc2lvbkdyb3VwEVJlc3BlY3RDYW5Db2xsaWRlE092ZXJsYXBQYXJhbXMubmV3KCkRUGF0aFdheXBvaW50Lm5ldygIUG9zaXRpb24GQWN0aW9uBUxhYmVsF1BoeXNpY2FsUHJvcGVydGllcy5uZXcoB0RlbnNpdHkIRnJpY3Rpb24KRWxhc3RpY2l0eQ5GcmljdGlvbldlaWdodBBFbGFzdGljaXR5V2VpZ2h0DFJhbmRvbS5uZXcoKQhSYXkubmV3KAZPcmlnaW4JRGlyZWN0aW9uC0lnbm9yZVdhdGVyE1JheWNhc3RQYXJhbXMubmV3KCkJUmVjdC5uZXcoBkNGcmFtZQRTaXplDFJlZ2lvbjMubmV3KANuZXcRUmVnaW9uM2ludDE2Lm5ldygOVHdlZW5JbmZvLm5ldygLRWFzaW5nU3R5bGUPRWFzaW5nRGlyZWN0aW9uC1JlcGVhdENvdW50CFJldmVyc2VzCURlbGF5VGltZRVSb3RhdGlvbkN1cnZlS2V5Lm5ldygJVURpbS5uZXcoBVNjYWxlBk9mZnNldApVRGltMi5uZXcoDFZlY3RvcjIubmV3KBFWZWN0b3IyaW50MTYubmV3KAxWZWN0b3IzLm5ldygRVmVjdG9yM2ludDE2Lm5ldygObmV3cHJveHkodHJ1ZSkKbmV3cHJveHkoKQppbnB1dFRhYmxlB29wdGlvbnMQb3B0aW9ucy5QcmV0dGlmeQdib29sZWFuDlByZXR0eVByaW50aW5nFm9wdGlvbnMuUHJldHR5UHJpbnRpbmcTb3B0aW9ucy5JbmRlbnRDb3VudAZudW1iZXIOT3V0cHV0V2FybmluZ3MWb3B0aW9ucy5PdXRwdXRXYXJuaW5ncwpTdGFja0xpbWl0Em9wdGlvbnMuU3RhY2tMaW1pdBJGdW5jdGlvbnNSZXR1cm5SYXcab3B0aW9ucy5GdW5jdGlvbnNSZXR1cm5SYXcQVXNlSW5zdGFuY2VQYXRocxhvcHRpb25zLlVzZUluc3RhbmNlUGF0aHMTb3B0aW9ucy5fU3RhY2tMZXZlbCZ7LS1bW0x1YUVuY29kZTogU3RhY2sgbGV2ZWwgbGltaXQgb2YgYAxgIHJlYWNoZWRdXX0BCgEsASAIZnVuY3Rpb24EQXhlcwpCcmlja0NvbG9yE0NhdGFsb2dTZWFyY2hQYXJhbXMGQ29sb3IzDUNvbG9yU2VxdWVuY2UVQ29sb3JTZXF1ZW5jZUtleXBvaW50CERhdGVUaW1lF0RvY2tXaWRnZXRQbHVnaW5HdWlJbmZvCEVudW1JdGVtBUVudW1zBUZhY2VzDUZsb2F0Q3VydmVLZXkERm9udAhJbnN0YW5jZQtOdW1iZXJSYW5nZQ5OdW1iZXJTZXF1ZW5jZRZOdW1iZXJTZXF1ZW5jZUtleXBvaW50DU92ZXJsYXBQYXJhbXMMUGF0aFdheXBvaW50ElBoeXNpY2FsUHJvcGVydGllcwZSYW5kb20DUmF5DVJheWNhc3RQYXJhbXMEUmVjdAdSZWdpb24zDFJlZ2lvbjNpbnQxNglUd2VlbkluZm8QUm90YXRpb25DdXJ2ZUtleQRVRGltBVVEaW0yB1ZlY3RvcjIMVmVjdG9yMmludDE2B1ZlY3RvcjMMVmVjdG9yM2ludDE2CHVzZXJkYXRhBFslc10DID0gM0x1YUVuY29kZTogRmFpbGVkIHRvIGVuY29kZSAlcyBvZiBEYXRhVHlwZSBgJXNgOiAlcwNrZXkFdmFsdWUJa2V5L3ZhbHVlHShGYWlsZWQgdG8gZ2V0IGVycm9yIG1lc3NhZ2UpAXsBfQlMdWFFbmNvZGUGaXBhaXJzBG5leHQFcGNhbGwEbWF0aAh0b3N0cmluZwh0b251bWJlcgxnZXRtZXRhdGFibGUGZm9ybWF0BGNoYXIEZ3N1YgVtYXRjaANyZXADc3ViBmdtYXRjaARmaW5kBmNvbmNhdAVjbG9uZQZpbnNlcnQEaHVnZQZ0eXBlb2YEdHlwZQNhbmQFYnJlYWsCZG8EZWxzZQZlbHNlaWYDZW5kBWZhbHNlA2ZvcgJpZgJpbgVsb2NhbANub3QCb3IGcmVwZWF0BnJldHVybgR0aGVuBHRydWUFdW50aWwFd2hpbGUIY29udGludWUGX19tb2RlAWsMc2V0bWV0YXRhYmxlAlwiAlxcAVwCXGEBBwJcYgEIAlx0AQkCXG4CXHYBCwJcZgEMAlxyAQ0ANwcCAQAAAAr7AgAAUgMAAJ8CAgRRAgMAmgYCAAEAAACCBQIAbgL8/wIAAICCAAEAAABFAAEYAAAAAAEAAf4ABkYAAAAABwEBAAAACv8BAAAAAAAA+wIAAFIDAADGBAAAFwIBAGoGAQVuAv7/AgAAAIIBAgAAAFEAARgAAAIAAAAB/wAEUgAAAAALAgQBAAAcowIAAP8CAAAAAAAA3QMAAMUCAwABAAAA+wMAAFIEAACfAwIC+wQBAFIFAgBSBgMAnwQDAisEDQCkBAEAAAAAQPsFAgBvBgIAUgcBAPsIAwBSCQIAbwoDAJ8IAwJSCQMAnwUFAowGAACfBAMBggACAAQDAQQAAABAAwIDAwBdBAEYAAEAAAAAAQAAAgAAAAABAAEBAQEAAAAB/Ab5C10AAAAACQECAAAACm8CAAD7BQAAUgYAAG8HAQD7CAEAnwUEAlIDBQBvBAAAcwECBIIBAgACAwUDBgCMAQcBGAAAAAAAAAAAAACPAAAAAAoBAQAAABhvAQAA+wIAAFIDAABvBAEAnwIDBGQCBwAcBwUAHAgBAH0IBAAHAAAAUgcFAG8IAgBzAQcIbgL4/wEAAABvAwMAUgQBAG8FBABSBgAAbwcFAFIIAQBvCQUAcwIDCYICAgAGAwgDCQMKAwsDDAMNAJQBDgEYAAEAAAAAAQAAAAEAAP4ABgAAAAAAAAAAlQAAAAAFAQIAAAAO+wEAAPsDAQBNAgNFAAAAAPsDAQBNBADbAQAAAJ8BBAMOAQMADgICAKkDAQCCAwIAqQMAAIIDAgACAw8DEACkAREBGAAAAAAAAAAAAgABAAMApwAAAAALAgcAAABLkAEBAE0CALoBAAAATQMA2wIAAABNBAAkAwAAAPsFAACaBBgABQAAAPsGAQD7CAAATQcIRQQAAAD7CAAATQkA2wIAAACfBgQDDgYDAA4HAgCpBQEAZQABAKkFAAAOBQkAbwUFAPsJAgBSCgMAnwkCAlIGCQBvBwYAUggBAHMBBQhlABUA+wYDAIcFBgIrBQoA+wUEAFIGAgBvBwcAnwUDAg4FBQBvBQgAUgYCAFIHAQBzAQUHZQAIAG8FCQD7CQIAUgoCAJ8JAgJSBgkAbwcKAFIIAQBzAQUIKwQBAIIAAQD7BQAAmgQFAAUAAABvBQsAUgYBAHMBBQaCAQIA+wUFAJoEBQAFAAAAbwUMAFIGAQBzAQUGggECAPsFBgBSBgQAUgcBAJ8FAwCCBQAADQMIAxIDEAMTAw8DFAMVAxYDFwMMAw0DGAMZALABGgEYCgIAAQABAAIAAPAAAAAAAAAAAgABAAMADQAAAAAAAAAAAQAAAAAAAAADAAAAAAIAAAAAAAAABQEBAAABAAABAQAAAQAAAQMAAAAApwAAAAAFAgEAAAAG+wMAAIcCAwBSAwEAqQQAAJ8CAwKCAgIAAACuAhsBGAAAAAAAATABAAAADQAGAQAAHqMAAAD/AAAAAAAAAPsBAAD/AgAAAAAAAN0EAADFAgQAAQAAAMYDAAAXAQwA+wYBAFIHAAD7CQIAUgoFAJ8JAgL7CwMAhwoLCVILBQCpDAAAnwoDAlIICgCfBgMBbgHz/wIAAAD7AQQAUgIAAPsDBQCfAQMAggEAAAAAtQIcARgFAQACAAAAAAAAAAEAAAAA9wAAAAABCP8ABAAAAAAwAQAAAA0CAwAAABRvAwAA+wYAAP8HAAACAAAAUggAAPsLAQBNCgtLAQAAAFILAQCpDAAAnwoDAlIJCgDFBwgDAQAAAPsIAgCfBgMCUgQGAG8FAgBzAgMFggICAAMDHQMeAxUAwAIfARgRAQAAAO4AAAAAAAEAABEAAAEAADABAAAABQIDAAAAGg4BCQD7AgAAmgAHAAIAAAD7AwAAlQIDAN4CAADGAgAAqQMBAIICAwD7AgEAmgADAAIAAABvAgEAggICAPsDAQA5AgMAmgADAAIAAABvAgIAggICAPsCAgBvAwMAUgQAAJ8CAwCCAgAABAIAAAAAAADwPwMgAyEDIgDGAgABGAAAAAACAAABAAAFAAABAAEAAAABAAQAAAAASQEAAAAFAgMAAAAQDgELAPsDAACHAgMAKwIIAPsCAQBSAwAAbwQAAJ8CAwIOAgMAUgIAAKkDAQCCAgMA+wICAFIDAACfAgIAggIAAAEDFgDbAgABGAAAAAAAAAAAAAIAAAMAAABcAQAAAAcCCQAAADD7AwAAhwIDAA4CCgD7AwEAbwQAAPsGAgCaAAMABgAAAG8FAQBlAAEAbwUCAJ8DAwCCAwAA+wMAAKkEAQBqBAMA+wIDAPsDBACfAgICDgEAAPsDBQAwAwIBAwAAAA4BBgD7BAUAKwQCAPsDBgArAwMAjAMBAGUAAQD7AwYAMAMCHwQAAAAOAQIAjAMBAGUAAgD7BAcAlQMEBTADAnYGAAAA+wMAADADAqAHAAAA+wMIAFIEAABSBQIAnwMDAIIDAAAIAyMDJAMIAyUDJgIAAAAAAADwPwMnAygA5AIAARgAAAEBAQEAAAAAAP4ABgAABAAAAwAAAAQAAAAAAAAAAAADAAAAAAAAAQAAAwAAAABnAQAAAAMBAQAAAAW7PwACUgIAAPsBAACfAQICggECAAAAhAMAARgAAAAAAIUBAAAAAgEAAAAAAm8BAACCAQIAAQMpAIgDAAEYAACJAQAAAAIBAQAAAAf7AQAADgEDAFIBAACfAQEAggEAAG8BAACCAQIAAQMqAIwDAAEYAAABAAAEAJABAAAACwEEAAAAJP8BAAAAAAAA/wIDAAAAAABNAwB5AAAAADADAgkBAAAATQMAeAIAAAAwAwK7AwAAAE0DAHsEAAAAMAMC0gUAAAD7AwAAUgQCAMYFAAAXAwUADgcEAPsIAQBSCQEAUgoGAJ8IAwFuA/r/AgAAAG8EBgD7BwIAUggBAPsJAwCfBwMCUgUHAG8GBwBzAwQGggMCAAgDKwMsAy0DLgMvAzADMQMVAJoDAAEYAAABAAEAAAABAAAAAQAAAAMAAAABAQAAAP4ABgAAAAAAAAAAmwEAAAAIAQIAAAATbwIAAPsDAAAOAwkATQQAugEAAAD7BgEATQUGQQIAAABSBgQAqQcAAJ8FAwJSAwUAcwECAysBBABNAgAAAwAAAG8DBABzAQIDggECAAUDMgMSAzMDNAMVAKsDAAEYfgAAAACCAAAAAAABAAB9AAAAADABAAAACAEBAAAACm8CAAD7BQAAvAYAfgEAAACfBgIAnwUAAlIDBQBvBAIAcwECBIIBAgADAzUDNgMVALEDAAEYAAAAAAAAAAAAALIBAAAADQEDAAAAMeICBwBNAwBfAAAAADADAl8AAAAATQMAvQEAAAAwAwK9AQAAAE0DAGsCAAAAMAMCawIAAABNAwD3AwAAADADAvcDAAAATQMAzAQAAAAwAwLMBAAAAE0DAJAFAAAAMAMCkAUAAABNAwAuBgAAADADAi4GAAAAbwMIAPsGAAD/BwAAAgAAAG8ICQD7CwEATQoLSwoAAABSCwIAqQwAAJ8KAwJSCQoAxQcIAwEAAAD7CAIAnwYDAlIEBgBvBQsAcwEDBYIBAgAMAzcDOAM5AzoDOwM8Az0FBwABAgMEBQYDHQM+Ax4DFQC1AwABGIYBAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAhAEAAADuAAAAAAABAAARAAABAAAwAQAAAAcBAQAAAAtvAgAA+wMAAE0EAHMBAAAATQUAZgIAAABNBgBjAwAAAJ8DBAJzAQIDggECAAQDPwNAA0EDQgDBAwABGAAAAAAAAAAAAAAAwwEAAAAJAQEAAAANbwIAAE0FAMIBAAAA+wcAAE0GB0sCAAAAUgcFAKkIAACfBgMCUgMGAG8EAwBzAQIEggECAAQDQwNEAx4DFQDGAwABGJcAAGkAAAAAAAGWAAAwAQAAAAgBAQAAAAtvAgAA+wUAAE0GAEoBAAAATQcA7AIAAACfBQMCUgMFAG8EAwBzAQIEggECAAQDRQNGA0cDFQDKAwABGAAAAAAAAAAAAAAAywEAAAAFAQAAAAAGbwIAAE0DALcBAAAAbwQCAHMBAgSCAQIAAwNIA0kDFQDPAwABGAAAAAAAANEBAAAAEQEEAAAAPrs/AAJSAgAA+wEAAJ8BAgJvAwAA+wYBAKQIAwAACBCA+wkCAFIKAQBvCwQAnwkDAocHCAn7CQIAUgoBAG8LBQCfCQMC8AkCAAYAAACpCAABqQgBAPsKAgBSCwEAbwwHAJ8KAwLwCgIABgAAAKkJAAGpCQEA+wsCAFIMAQBvDQgAnwsDAEw+AAH7CgMAnwoAAvsMAgBSDQEAbw4JAJ8MAwBMPgAB+wsDAJ8LAAL7DQIAUg4BAG8PCgCfDQMATD4AAfsMAwCfDAAC+w4CAFIPAQBvEAsAnw4DAEw+AAH7DQMAnw0AAp8GCAJSBAYAbwUMAHMCAwWCAgIADQNKA0sDTAQACBCAA00DTgNPA1ADUQNSA1MDVAMVANYDAAEYAAAAAAIBAgAAAAAAAAIAAAAAAAAAAQAAAAAAAAACAAAAAAAAAQAAAAAAAAIAAAAAAAABAAAAAAAA9QANAADYAQAAAAUBAQAAAAdvAgAAuz8AAlIEAAD7AwAAnwMCAnMBAgOCAQIAAQNVAOwDAAEYAAAAAAAAAO0BAAAAAwEBAAAABbs/AAJSAgAA+wEAAJ8BAgKCAQIAAADxAwABGAAAAAAA8gEAAAACAQAAAAACbwEAAIIBAgABA0sA9gMAARgAAPcBAAAACwEEAAAAMP8BAAAAAAAA/wIEAAAAAABNAwCYAAAAADADAo4BAAAATQMAEwIAAAAwAwKNAwAAAE0DAMYEAAAAMAMCEwUAAABNAwAFBgAAADADAt4HAAAATQMARwgAAAAwAwJ5CQAAAE0DABoKAAAAMAMCgwsAAAD7AwAAUgQCAMYFAAAXAwUADgcEAPsIAQBSCQEAUgoGAJ8IAwFuA/r/AgAAAG8EDAD7BwIAUggBAPsJAwCfBwMCUgUHAG8GDQBzAwQGggMCAA4DVgNXA1gDWQNaA1sDXANdA14DXwNgA2EDYgMVAPoDAAEYAAABAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAMAAAABAQAAAP4ABgAAAAAAAAAA+wEAAAAJAQEAAAANbwIAAPsFAABNBgBKAQAAAE0HAOwCAAAATQgARwMAAACfBQQCUgMFAG8EBABzAQIEggECAAUDYwNGA0cDZAMVAI4EAAEYAAAAAAAAAAAAAAAAAA8CAAAACQEBAAAADW8CAAD7BQAATQYA3AEAAABNBwCrAgAAAE0IALoDAAAAnwUEAlIDBQBvBAQAcwECBIIBAgAFA2UDZgNnA2gDFQCSBAABGAAAAAAAAAAAAAAAAAATAgAAAA4BBQAAAC77AQAADgEFAPsBAQBSAgAAnwECAg4BAQCCAQIAbwIAAPsDAgBvBgEATQkA2wIAAAD7CwMATQoLQQMAAABSCwkAqQwAAJ8KAwJSBwoAbwgEAHMFBghvBgUA+wcEAFIIBQBvCQYAnwcDBGQHBwAcDAoAHA0GAH0NBAAMAAAAUgwKAG8NBwBzBgwNbgf4/wEAAABvBwgAUggGAG8JCQBSCgUAbwsKAFIMBgBvDQoAcwQHDXMBAgSCAQIACwMpA2kDEAMzAxUDCAMJAwoDCwMMAw0AmAQAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGQIAAAAAAAABAAAAAAAAAAAAAAABAAAAAQAAAAYAAAABAAAAAQAAAAAAAAAAAAAADP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAPMAAAAAAAAAcf7//wEAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAP7///8AAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAQEAAAALbwIAAPsFAABNBgDYAQAAAE0HALQCAAAAnwUDAlIDBQBvBAMAcwECBIIBAgAEA2oDawNsAxUApwQAARgAAAAAAAAAAAAAACgCAAAACQEBAAAADW8CAABNBQDCAQAAAPsHAABNBgdLAgAAAFIHBQCpCAAAnwYDAlIDBgBvBAMAcwECBIIBAgAEA20DRAMeAxUAqwQAARj8AAAEAAAAAAAB+wAAMAEAAAAJAQEAAAANbwIAAPsFAABNBgBKAQAAAE0HAOwCAAAATQgAEAMAAACfBQQCUgMFAG8EBABzAQIEggECAAUDbgNGA0cDbwMVAK8EAAEYAAAAAAAAAAAAAAAAADACAAAADQEDAAAAKeICBQBNAwB9AAAAADADAn0AAAAATQMAVwEAAAAwAwJXAQAAAE0DALoCAAAAMAMCugIAAABNAwAUAwAAADADAhQDAAAATQMAUgQAAAAwAwJSBAAAAG8DBgD7BgAA/wcAAAIAAABvCAcA+wsBAE0KC0sIAAAAUgsCAKkMAACfCgMCUgkKAMUHCAMBAAAA+wgCAJ8GAwJSBAYAbwUJAHMBAwWCAQIACgNwA3EDcgNzA3QFBQABAgMEAx0DdQMeAxUAswQAAQMAAQAAAAEAAP4BAAAAAQAA9QEAAAAIAQARAO4AAAAAAAAAABEAAAEA7jQCAAACAAAAC////+////8BAAAAEgAAAAAJAQEAAAANbwIAAPsFAABNBgA7AQAAAE0HAAICAAAATQgAwwMAAACfBQQCUgMFAG8EBABzAQIEggECAAUDdgN3A3gDeQMVAL0EAAEYAAAAAAAAAAAAAAAAAD4CAAAACwEBAAAAEW8CAAD7BQAATQYA2AEAAABNBwAQAgAAAE0IABgDAAAATQkAiQQAAABNCgD2BQAAAJ8FBgJSAwUAbwQGAHMBAgSCAQIABwN6A3sDfAN9A34DfwMVAMEEAAEYAAEAAAAAAAAAAAAAAAABAABCAgAAAAEAAAAAAAJvAAAAggACAAEDgAEAxwQAARgAAEgCAAAACAEBAAAAC28CAAD7BQAATQYAQwEAAABNBwBhAgAAAJ8FAwJSAwUAbwQDAHMBAgSCAQIABAOBAQOCAQODAQMVAMsEAAEYAAAAAAAAAAAAAABMAgAAAA0BAwAAACniAgUATQMAfQAAAAAwAwJ9AAAAAE0DAFcBAAAAMAMCVwEAAABNAwBjAgAAADADAmMCAAAATQMAFAMAAAAwAwIUAwAAAE0DAFIEAAAAMAMCUgQAAABvAwYA+wYAAP8HAAACAAAAbwgHAPsLAQBNCgtLCAAAAFILAgCpDAAAnwoDAlIJCgDFBwgDAQAAAPsIAgCfBgMCUgQGAG8FCQBzAQMFggECAAoDcANxA4QBA3MDdAUFAAECAwQDHQOFAQMeAxUAzwQAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFACAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAOz+//8BAAAAAAAAAAAAAAAAAAAA7v///wAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAEQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAgBAQAAAAtvAgAA+wUAAE0GANgBAAAATQcAtAIAAACfBQMCUgMFAG8EAwBzAQIEggECAAQDhgEDawNsAxUA2QQAARgAAAAAAAAAAAAAAFoCAAAADAEBAAAAFk0BAIUAAAAATQIALwEAAABvBAIA+wcAAKQJBAAADACAOQsCAD4KCwWfCQICCQgBCaQKBAAADACAPgsCBZ8KAgIJCQEKnwcDAlIFBwBvBgYAcwMEBoIDAgAHA4cBA4gBA4kBA4oBBAAMAIACAAAAAAAAAEADFQDgBAABGAAAAQACAQEAAAAAAAEAAAAA/gAEAABhAgAAAAgBAQAAAAtvAgAA+wUAAE0GANgBAAAATQcAtAIAAACfBQMCUgMFAG8EAwBzAQIEggECAAQDiwEDawNsAxUA7AQAARgAAAAAAAAAAAAAAG0CAAAADAEBAAAAE28CAAD7BQAATQYASgEAAABNBwBpAgAAAE0IAC8DAAAATQkAUAQAAABNCgCVBQAAAE0LAFsGAAAAnwUHAlIDBQBvBAcAcwECBIIBAgAIA4wBA0YDjQEDjgEDjwEDkAEDkQEDFQDwBAABGAABAQABAAEAAQABAAEA+gAIAABxAgAAAAkBAQAAAA1vAgAA+wUAAE0GAEoBAAAATQcA7AIAAABNCABHAwAAAJ8FBAJSAwUAbwQEAHMBAgSCAQIABQOSAQNGA0cDZAMVAP4EAAEYAAAAAAAAAAAAAAAAAH8CAAAACAEBAAAAC28CAAD7BQAATQYAhAEAAABNBwBwAgAAAJ8FAwJSAwUAbwQDAHMBAgSCAQIABAOTAQOUAQOVAQMVAIIFAAEYAAAAAAAAAAAAAACDAgAAAAsBAQAAABdvAgAA+wUAAE0HAHkBAAAATQYHhAIAAABNCAB5AQAAAE0HCHADAAAATQkAeAQAAABNCAmEAgAAAE0KAHgEAAAATQkKcAMAAACfBQUCUgMFAG8EBQBzAQIEggECAAYDlgEDKwOUAQOVAQMtAxUAhgUAARgAAQMAAAABAAAAAQAAAAEAAAD6AAgAAIcCAAAACAEBAAAAC28CAAD7BQAATQYAeQEAAABNBwB4AgAAAJ8FAwJSAwUAbwQDAHMBAgSCAQIABAOXAQMrAy0DFQCTBQABGAAAAAAAAAAAAAAAlAIAAAAIAQEAAAALbwIAAPsFAABNBgB5AQAAAE0HAHgCAAAAnwUDAlIDBQBvBAMAcwECBIIBAgAEA5gBAysDLQMVAJcFAAEYAAAAAAAAAAAAAACYAgAAAAkBAQAAAA1vAgAA+wUAAE0GAHkBAAAATQcAeAIAAABNCAB7AwAAAJ8FBAJSAwUAbwQEAHMBAgSCAQIABQOZAQMrAy0DLwMVAJsFAAEYAAAAAAAAAAAAAAAAAJwCAAAACQEBAAAADW8CAAD7BQAATQYAeQEAAABNBwB4AgAAAE0IAHsDAAAAnwUEAlIDBQBvBAQAcwECBIIBAgAFA5oBAysDLQMvAxUAnwUAARgAAAAAAAAAAAAAAAAAoAIAAAADAQEAAAAJuzwAAlICAAD7AQAAnwECAg4BAgBvAQAAggECAG8BAQCCAQIAAgObAQOcAQCkBQABGAAAAAAAAQACAKUCAAAAKwIUAAAAlAT7AgAAUgMAAG8EAABvBQEAnwIEAfsCAABSAwEAbwQCAG8FAQBvBgMAnwIFAQ4BPwD7AgAATQMBAQQAAABvBAUAbwUGAG8GAwCfAgUB+wIAAE0DATwHAAAAbwQIAG8FBgBvBgMAnwIFAfsCAABNAwEfCQAAAG8ECgBvBQsAbwYDAJ8CBQH7AgAATQMB5AwAAABvBA0AbwUGAG8GAwCfAgUB+wIAAE0DAZ4OAAAAbwQPAG8FCwBvBgMAnwIFAfsCAABNAwGuEAAAAG8EEQBvBQYAbwYDAJ8CBQH7AgAATQMBWhIAAABvBBMAbwUGAG8GAwCfAgUB+wIAAE0DAXYUAAAAbwQVAG8FCwBvBgMAnwIFAfsCAABNAwGgFgAAAG8EFQBvBQEAbwYDAJ8CBQFSAgEAKwICAP8CAAAAAAAAUgECAE0DAQEEAAAARwMFAAAAAIBNAwE8BwAAAEcDAQAAAACATQMBAQQAAABHAwQAAAAAAE0CAQEEAAAAKwIFAE0CATwHAAAADgICAE0CATwHAAAATQMBHwkAAAArAwQADgICAIwDBABlAAEAjAMAAE0FAeQMAAAARwUDAAAAAICpBAEAZQACAE0EAeQMAAAATQYBng4AAACQBQYXTQcBrhAAAABHBwEAAAAAgE0GAa4QAAAATQgBWhIAAABHCAMAAAAAgKkHAQBlAAIATQcBWhIAAABNCQF2FAAAAJAICRhNCQGgFgAAACsJBAD/CQEAAAAAAKkKAQBqCgkAfQUHAAgAAABvCxkAUgwFAG8NGgBzCgsNwQEAAIIKAgAOAgIAbwobAGUAAQBvChwADgICAG8LHQBlAAEAbwseAA4CAgBvDB8AZQABAG8MHAD7DQEAbw4fAFIPAwCfDQMCDgIFAPsOAQBSDw0AUhAIAJ8OAwIrDgEAUg4NAFINDgAcDw0AjBAAAGAQCAAPAAAA+w4CAFIPDQCMEAEAORIDAHgREhifDgQCKw4BAG8OHACMDwEA/xAAAAAAAADZEQAAEgAQANkSAQASAgMAEgIEABICBQASABAAEgIGABIACwDZEwIAEgIGABIAEAASAAsA2RQDABIBD/8SAgcAEgIIADAUEGALAAAA2RQEABICCQASAgoAEgILADAUEEEgAAAA2RQFABIACQASAggAEgAAABICDAASAQH/EgACABIAAwASAAgAEgINADAUEEsBAAAAwBQhABICDgAwFBA+BgAAAMAUIgAwFBDJAwAAANkUCAASAAYAMBQQaCMAAADZFAkAEgIDABICBAASAgYAEgALADAUEH0kAAAA2RQKABIAAgASABAAMBQQ+iUAAADZFAsAEgASADAUEIUmAAAA2RQMABICBgASABAAEgALADAUEBonAAAA2RQNABIAEgAwFBCaKAAAANkUDgASABAAMBQQ5SkAAADZFA8AEgASADAUEH4qAAAAwBQrADAUEIosAAAA2RQRABICDgASABIAEgIKABICDwAwFBAALQAAAMAULgASAg4AMBQQnS8AAADAFDAAEgIOADAUEHUxAAAAwBQyADAUEFszAAAA2RQVABICAwASAgQAEgIGABIACwAwFBBeNAAAANkUFgASABIAMBQQMTUAAADZFBcAEgASADAUEDk2AAAA2RQYABIABwASAhAAEgAMABIAEAASAhEAMBQQ9DcAAADZFBkAEgASADAUELA4AAAA2RQaABIAEAAwFBCTOQAAANkUGwASABIAMBQQuToAAADZFBwAEgIGABIAEAASAAsAMBQQHzsAAADZFB0AEgASADAUEOY8AAAA2RQeABIAEgAwFBCyPQAAAMAUPgAwFBBuPwAAANkUIAASABIAMBQQuEAAAADZFCEAEgIGABIAEAASAAsAMBQQSkEAAADZFCIAEgASADAUEPlCAAAA2RQjABIAEgAwFBBhQwAAANkUJAASABIAMBQQ20QAAADZFCUAEgASADAUEExFAAAA2RQmABIAEgAwFBCqRgAAANkUJwASABIAMBQQD0cAAADZFCgAEgASADAUEEpIAAAA2RQpABIAEgAwFBC7SQAAANkUKgASABIAMBQQW0oAAADZFCsAEgASADAUEE9LAAAA2RQsABIAEgAwFBDRTAAAAMAUTQASAhIAMBQQqk4AAABvERwA+xIDAFITAADGFAAAFxJ1APsXBQBSGBUAnxcCAvsYBQBSGRYAnxgCAocZEBcOGW0AhxkQGA4ZawAOAgQAUhoKAFIbDQBzGRobKxkBAG8ZHACpGgAA+xsTAIccEBdSHRUAqR4BAJ8bBAT7HhMAhx8QGFIgFgCpIQAAnx4EAw4bGAAOHhcADh8WAA4cDgAOHQIAUiEcACshBQD7IwgAbyRPAFIlHACfIwMCUiEjAA4CAgBvIlAAZQABAG8iUQBzICEiKyABAG8gHABSIRkAUiIgAFIjHwBzGSEjqRoBAGUAMAAOBC8A+yAIAG8hUgArGwIAbyJTAGUABAArHgIAbyJUAGUAAQBvIlUAUiMYACsbBAD7JAsAUiUcAJ8kAgIrJAYAKx4EAPskCwBSJR8AnyQCAiskAQBvJFYAnyAFAlIhGQBvIxwA+yQRAFIlIABvJlcAnyQDBGQkBwAcKScAHCojAH0qBAApAAAAUiknAG8qUQBzIykqbiT4/wEAAABvJFgAUiUjAG8mWQBSJyAAbyhaAFIpIwBvKloAcyIkKnMZISL7IAMAUiEAAFIiFQCfIAMCDiAFAA4aCABSIBkAbyEeAHMZICFlAAQAUiAZAFIhCgBSIg4AcxkgIlIgEQBSIRkAcxEgIW4Siv8CAAAAbxJbAFITEQBvFFwAcxESFMEBAACCEQIAXQOdAQMeA54BAykDJQOfAQOgAQOhAQOiAQMmA6MBA6QBA6UBA6YBA6cBA6gBA6kBA6oBA6sBA6wBAycDrQEDKAIAAAAAAEB/QAIAAAAAAADwPwOuAQOvAQOwAQMIAwMDsQEDsgEDMwYNBg4DswEDtAEDtQEDhwEDtgEDtwEDuAEDuQEGFwO6AQO7AQYZA0sGGgO8AQYbA70BA74BA78BA8ABA8EBA8IBA8MBA8QBA8UBA8YBA8cBBiYDyAEDyQEDygEDywEDzAEDzQEDzgEDzwED0AED0QED0gED0wED1AED1QEGNAPWAQPXAQPYAQMKA9kBA9oBA9sBA9wBA90BAwkDCwMMAw0D3gED3wEuBwgJCgsMDQ4PEBESExQVFhcYGRobHB0eHyAhIiMkJSYnKCkqKywtLi8wMTIzNO0B4AEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAABAAAAAAAAAADAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEQAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABQAAAAAAAAAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYAAAAAAAAAAAAAAAAAAAAFAAAAAAAAAAAAAAAAAAAABQAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAADgAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAADQAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAKAAAAAgAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAUAAAAAAAAAAAAAAAMAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAADAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAwAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAA+v///wkAAAC+/f//AQAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAA/v///wAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/AgAAAAAAAAAAAAAAAAAAAAAAAAIAAAABAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAMv///8AAAAAOQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAACoAAAEAAM4BowAAAKQAAQAAAABApAEDAAAAIECkAgUAAABAQKQDBwAAAGBApAQJAAAAgECkBQsAAACgQKQGDQAAAMBApAcPAAAA4ECkCBEAAAAAQaQJEwAAACBBpAoVAAAAQEFNCwKNFgAAAE0MApgXAAAATQ0CzBgAAABNDgLnGQAAAE0PAhYaAAAATRAC8BsAAABNEQKIHAAAAE0SAFYdAAAATRMAGh4AAABNFADaHwAAAE0VAJMgAAAATRYHVyEAAACkFyMAAAAgQisXAgCkFyUAAABAQsYYAAD/GQAAFgAAAG8aJgBvGycAbxwoAG8dKQBvHioAbx8rAG8gLABvIS0AbyIuAG8jLwBvJDAAbyUxAG8mMgBvJzMAbyg0AG8pNQDFGRoRAQAAAG8aNgBvGzcAbxw4AG8dOQBvHjoAbx87AMUZGgcRAAAA/xsAAAAAAADiHD0Abx0+ADAdHOM8AAAAnj0bAxwAAACkGkAAAADwQ58aAwJSGBoAUhoDAFIbGQDGHAAAFxoCAKkfAQBqHxgebhr9/wIAAABSGRIAKxkCAMAZQQASAAEAUhIZAFIZFAArGQIAwBlCABIAAwBSFBkA2RkCABIAFwASARL/EgALABIAEwDGGgAA/xsFAAAAAABvHEMAMBwbQ0QAAABvHEUAMBwbfUYAAABvHEcAMBwbJkgAAABvHEkAMBwbKUoAAABvHEsAMBwbKEwAAABvHE0AMBwbK04AAABvHE8AMBwbKlAAAABvHFEAMBwbLVIAAABvHFMAMBwbLFQAAACMHgAAjBz/AIwdAQCoHBAAUh8MAFIgHgCfHwIChyAbHysgCgCMICAAtx4EACAAAACMIH4AYCAFAB4AAABvIUYAUiIeAHMgISJqIBsfixzw/8AaVQASAA0AEgAbAMAbVgASABEAxhwAAMAdVwASAAQAEgAFANkcBgASAAUAEgAEABIBGv8SARj/EgAOABIABgASARz/2R0HABIAGQASAA8AEgAQABIAAwASABUAEgAXABIAEwASABYAEgALABIBGP8SAA4AEgEa/xIBFP8SAB0AEgAIABIACQASARz/EgARABIACgASAAQAwRIAAIIdAgBYAx4EAAAAQAPhAQQAACBAAzMEAABAQAPiAQQAAGBAA+MBBAAAgEADGAQAAKBAAxkEAADAQAPkAQQAAOBAA+UBBAAAAEED5gEEAAAgQQPnAQQAAEBBA+gBA+kBA+oBA+sBA+wBA+0BA+4BA+8BA/ABA/EBA/IBA/MBA/QBBAAAIEID9QEEAABAQgP2AQP3AQP4AQP5AQP6AQP7AQP8AQP9AQOzAQP+AQP/AQOAAgMpA4ECA4ICA4MCA4QCA4UCA4YCA4cCA4gCA4kCA4oCBQE8A4sCA4wCBAAA8EMGAAYBA40CAwUDjgIDjwIDkAIDkQIDkgIDkwIDlAIDlQIDlgIDsAEDlwIDmAIDmQIDmgIDmwIDnAIGAwYEBgUIAAECAwQFBjUBAAECAAgAAPgAAAAAAAAAAAAAAAAAAAAAAAAC/gEAAf4BAAH+AQAB/gIAAf0BAAH+AgAD+wAAAAACAAH9AQEB/QEBAf0BAQH9AQEB/QABAf4BAQD+BAAA/AAAAAAAAAAAAgAA/gEA/wAGAAH5AAsA9QAADPQAAAAABAAB+wABAP8CAAD+AAAB/wABAP8BAAD/AAAB/wAEAPwAAQD/AgAA/gAAAAABAAAD/AgA+AgADesAAAz0AAAAAAAAPcMAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAACAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAgAAAAIAAAACAAAAAwAAAAIAAAAFAAAABQAAAAQAAAAEAAAABAAAAAQAAAADAAAAAwAAAAIAAAAEAAAAAAAAAAAAAAACAAAAAAAAAAcAAAAMAAAADAAAABUAAAAFAAAAAQAAAAMAAAABAAAAAQAAAAIAAAABAAAABAAAAAEAAAACAAAAAAAAAP3///8IAAAAGAAAAAwAAAAAAAAAPQAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAADbdcKu2CLjZiO+0wSL+ea29t+hrCZwr6KR9U4P/Hc1BB3OAoPQ9gIt0

-- Decompiled by Krnl

local v1 = table
local v_u_2 = ipairs
local v3 = string
local v_u_4 = next
local v_u_5 = pcall
local v_u_6 = game
local v_u_7 = workspace
local v8 = math
local v_u_9 = tostring
local v_u_10 = tonumber
local v_u_11 = getmetatable
local v_u_12 = v3.format
local v13 = v3.char
local v_u_14 = v3.gsub
local v_u_15 = v3.match
local v_u_16 = v3.rep
local v_u_17 = v3.sub
local v_u_18 = v3.gmatch
local v19 = v1.find
local v_u_20 = v1.concat
local v21 = v1.clone
local v_u_22 = v1.insert
local v_u_23 = v8.huge
local v_u_24 = typeof or type
local v_u_25 = setmetatable({}, {
	["__mode"] = "k"
})
for _, v26 in v_u_4, {
	"and",
	"break",
	"do",
	"else",
	"elseif",
	"end",
	"false",
	"for",
	"function",
	"if",
	"in",
	"local",
	"nil",
	"not",
	"or",
	"repeat",
	"return",
	"then",
	"true",
	"until",
	"while",
	"continue"
} do
	v_u_25[v26] = true
end
local v_u_31 = v19 or function(p27, p28)
	-- upvalues: (copy) v_u_2
	for v29, v30 in v_u_2(p27) do
		if v30 == p28 then
			return v29
		end
	end
end
local v_u_32 = {
	["\""] = "\\\"",
	["\\"] = "\\\\",
	["\7"] = "\\a",
	["\8"] = "\\b",
	["\t"] = "\\t",
	["\n"] = "\\n",
	["\11"] = "\\v",
	["\f"] = "\\f",
	["\r"] = "\\r"
}
local v_u_37 = v21 or function(p33)
	-- upvalues: (copy) v_u_4
	local v34 = {}
	for v35, v36 in v_u_4, p33 do
		v34[v35] = v36
	end
	return v34
end
local function v_u_42(p38, p39, ...)
	-- upvalues: (copy) v_u_24, (ref) v_u_31, (copy) v_u_12, (copy) v_u_20
	local v40 = { ... }
	local v41 = v_u_24(p38)
	if not v_u_31(v40, v41) then
		error(v_u_12("LuaEncode: Incorrect type for `%s`: `%s` expected, got `%s`", p39, v_u_20(v40, ", "), v41), 0)
	end
	return p38
end
for v43 = 0, 255 do
	local v44 = v13(v43)
	if not v_u_32[v44] and (v43 < 32 or v43 > 126) then
		v_u_32[v44] = "\\" .. v43
	end
end
local function v_u_46(p45)
	-- upvalues: (copy) v_u_14, (copy) v_u_32
	return "\"" .. v_u_14(p45, "[%z\\\"\1-\31\127-\255]", v_u_32) .. "\""
end
local function v_u_56(p47, p48)
	-- upvalues: (copy) v_u_6, (copy) v_u_5, (ref) v_u_46, (ref) v_u_25, (copy) v_u_15, (copy) v_u_7, (ref) v_u_56
	local v49 = p48 or ""
	local v50 = p47.Name
	local v51 = p47.ClassName
	local v52 = p47.Parent
	local v53
	if v52 == v_u_6 then
		local v54, v55 = v_u_5(v_u_6.FindService, v_u_6, p47.ClassName)
		if v54 and v55 and true or false then
			v53 = ":GetService(" .. v_u_46(v51) .. ")" .. v49
			::l8::
			if v52 then
				if v52 == v_u_6 then
					return "game" .. v53
				elseif v52 == v_u_7 then
					return "workspace" .. v53
				else
					return v_u_56(v52, v53)
				end
			else
				return
			end
		end
	end
	if v_u_25[v50] or not v_u_15(v50, "^[A-Za-z_][A-Za-z0-9_]*$") then
		v53 = "[" .. v_u_46(v50) .. "]" .. v49
	else
		v53 = "." .. v50 .. v49
	end
	goto l8
end
local function v_u_162(p_u_57, p58)
	-- upvalues: (copy) v_u_42, (copy) v_u_16, (copy) v_u_17, (copy) v_u_4, (copy) v_u_22, (copy) v_u_24, (copy) v_u_20, (copy) v_u_23, (copy) v_u_12, (ref) v_u_25, (copy) v_u_15, (ref) v_u_46, (ref) v_u_37, (copy) v_u_162, (copy) v_u_9, (copy) v_u_10, (ref) v_u_56, (copy) v_u_18, (copy) v_u_11, (copy) v_u_5
	v_u_42(p_u_57, "inputTable", "table")
	v_u_42(p58, "options", "table", "nil")
	if p58 then
		v_u_42(p58.Prettify, "options.Prettify", "boolean", "nil")
		v_u_42(p58.PrettyPrinting, "options.PrettyPrinting", "boolean", "nil")
		v_u_42(p58.IndentCount, "options.IndentCount", "number", "nil")
		v_u_42(p58.OutputWarnings, "options.OutputWarnings", "boolean", "nil")
		v_u_42(p58.StackLimit, "options.StackLimit", "number", "nil")
		v_u_42(p58.FunctionsReturnRaw, "options.FunctionsReturnRaw", "boolean", "nil")
		v_u_42(p58.UseInstancePaths, "options.UseInstancePaths", "boolean", "nil")
		v_u_42(p58._StackLevel, "options._StackLevel", "number", "nil")
		v_u_42(p58._VisitedTables, "options._StackLevel", "table", "nil")
	end
	local v_u_59 = p58 or {}
	if v_u_59.Prettify == nil then
		local _ = v_u_59.PrettyPrinting == nil
	end
	local v_u_60 = ((v_u_59.Prettify == nil or not v_u_59.Prettify) and true or false) and v_u_59.PrettyPrinting
	if v_u_60 then
		v_u_60 = v_u_59.PrettyPrinting
	end
	local v_u_61 = v_u_59.IndentCount or (v_u_60 and 4 or 0)
	local v62 = v_u_59.OutputWarnings == nil and true or v_u_59.OutputWarnings
	local v63 = v_u_59.StackLimit or 500
	local _ = v_u_59.FunctionsReturnRaw == nil
	local v_u_64 = v_u_59.FunctionsReturnRaw
	local v_u_65 = v_u_59.UseInstancePaths == nil and true or v_u_59.UseInstancePaths
	local v_u_66 = v_u_59._StackLevel or 1
	local v_u_67 = v_u_59._VisitedTables or {
		[p_u_57] = true
	}
	if v63 <= v_u_66 then
		return "{--[[LuaEncode: Stack level limit of `" .. v63 .. "` reached]]}"
	end
	local v68 = v_u_60 and "\n" or ""
	local v_u_69 = v_u_60 and ", " or ","
	local v_u_70 = v_u_60 and " " or ""
	local v71 = v_u_16(" ", v_u_61)
	if v_u_60 then
		v71 = v_u_16(v71, v_u_66) or v71
	end
	local v72 = #v71 > 0 and (v_u_17(v71, 1, -v_u_61 - 1) or "") or ""
	local v_u_73 = 1
	local v_u_74 = {}
	local function v_u_77(...)
		-- upvalues: (ref) v_u_4, (ref) v_u_22, (ref) v_u_24, (copy) v_u_74, (ref) v_u_20, (copy) v_u_69
		local v75 = {}
		for _, v76 in v_u_4, { ... } do
			v_u_22(v75, (v_u_74[v_u_24(v76)](v76, false)))
		end
		return v_u_20(v75, v_u_69)
	end
	function v_u_74.number(p78, p79)
		-- upvalues: (ref) v_u_73, (ref) v_u_23, (ref) v_u_12
		if not p79 or p78 ~= v_u_73 then
			return p78 == v_u_23 and "math.huge" or (p78 == -v_u_23 and "-math.huge" or v_u_12("%.14g", p78))
		end
		v_u_73 = v_u_73 + 1
		return nil, true
	end
	function v_u_74.string(p80, p81)
		-- upvalues: (ref) v_u_25, (ref) v_u_15, (ref) v_u_46
		if p81 and (not v_u_25[p80] and v_u_15(p80, "^[A-Za-z_][A-Za-z0-9_]*$")) then
			return p80, true
		else
			return v_u_46(p80)
		end
	end
	function v_u_74.table(p82, p83)
		-- upvalues: (copy) v_u_67, (ref) v_u_12, (copy) p_u_57, (ref) v_u_37, (ref) v_u_59, (copy) v_u_60, (copy) v_u_61, (copy) v_u_66, (ref) v_u_162
		if v_u_67[p82] then
			return v_u_12("{--[[LuaEncode: Duplicate reference%s]]}", p82 == p_u_57 and " (of parent)" or "")
		end
		v_u_67[p82] = true
		local v84 = v_u_37(v_u_59)
		v84.Prettify = v_u_60
		local v85
		if p83 then
			v85 = not v_u_60 and v_u_61 or 1
		else
			v85 = v_u_61
		end
		v84.IndentCount = v85
		v84._StackLevel = p83 and 1 or v_u_66 + 1
		v84._VisitedTables = v_u_67
		return v_u_162(p82, v84)
	end
	function v_u_74.boolean(p86)
		-- upvalues: (ref) v_u_9
		return v_u_9(p86)
	end
	v_u_74["nil"] = function(_)
		return "nil"
	end
	v_u_74["function"] = function(p87)
		-- upvalues: (copy) v_u_64
		return not v_u_64 and "function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can\'t serialize functions]] return end" or p87()
	end
	function v_u_74.Axes(p88)
		-- upvalues: (ref) v_u_4, (ref) v_u_22, (ref) v_u_20, (copy) v_u_69
		local v89 = {}
		for v90, v91 in v_u_4, {
			["Enum.Axis.X"] = p88.X,
			["Enum.Axis.Y"] = p88.Y,
			["Enum.Axis.Z"] = p88.Z
		} do
			if v91 then
				v_u_22(v89, v90)
			end
		end
		return "Axes.new(" .. v_u_20(v89, v_u_69) .. ")"
	end
	function v_u_74.BrickColor(p92)
		-- upvalues: (copy) v_u_60, (copy) v_u_74
		local v93 = "BrickColor.new("
		local v94 = v_u_60
		if v94 then
			local v95 = p92.Name
			v94 = v_u_74.string(v95, false)
		end
		return v93 .. v94 or p92.Number .. ")"
	end
	function v_u_74.CFrame(p96)
		-- upvalues: (copy) v_u_77
		return "CFrame.new(" .. v_u_77(p96:components()) .. ")"
	end
	function v_u_74.CatalogSearchParams(p97)
		-- upvalues: (ref) v_u_20, (copy) v_u_74, (copy) v_u_69
		local v98 = {
			["SearchKeyword"] = p97.SearchKeyword,
			["MinPrice"] = p97.MinPrice,
			["MaxPrice"] = p97.MaxPrice,
			["SortType"] = p97.SortType,
			["CategoryFilter"] = p97.CategoryFilter,
			["BundleTypes"] = p97.BundleTypes,
			["AssetTypes"] = p97.AssetTypes
		}
		return "(function(v, p) for pn, pv in next, p do v[pn] = pv end return v end)(" .. v_u_20({ "CatalogSearchParams.new()", (v_u_74.table(v98, false)) }, v_u_69) .. ")"
	end
	function v_u_74.Color3(p99)
		-- upvalues: (copy) v_u_77
		return "Color3.new(" .. v_u_77(p99.R, p99.G, p99.B)
	end
	function v_u_74.ColorSequence(p100)
		-- upvalues: (copy) v_u_74
		local v101 = p100.Keypoints
		return "ColorSequence.new(" .. v_u_74.table(v101, false) .. ")"
	end
	function v_u_74.ColorSequenceKeypoint(p102)
		-- upvalues: (copy) v_u_77
		return "ColorSequenceKeypoint.new(" .. v_u_77(p102.Time, p102.Value) .. ")"
	end
	function v_u_74.DateTime(p103)
		return "DateTime.fromUnixTimestamp(" .. p103.UnixTimestamp .. ")"
	end
	function v_u_74.DockWidgetPluginGuiInfo(p104)
		-- upvalues: (ref) v_u_9, (copy) v_u_77, (ref) v_u_15, (ref) v_u_10
		local v105 = v_u_9(p104)
		return "DockWidgetPluginGuiInfo.new(" .. v_u_77(Enum.InitialDockState[v_u_15(v105, "InitialDockState:(%w+)")], v_u_15(v105, "InitialEnabled:(%w+)") == "1", v_u_15(v105, "InitialEnabledShouldOverrideRestore:(%w+)") == "1", v_u_10(v_u_15(v105, "FloatingXSize:(%w+)")), v_u_10(v_u_15(v105, "FloatingYSize:(%w+)")), v_u_10(v_u_15(v105, "MinWidth:(%w+)")), (v_u_10(v_u_15(v105, "MinHeight:(%w+)")))) .. ")"
	end
	function v_u_74.Enum(p106)
		-- upvalues: (ref) v_u_9
		return "Enum." .. v_u_9(p106)
	end
	function v_u_74.EnumItem(p107)
		-- upvalues: (ref) v_u_9
		return v_u_9(p107)
	end
	function v_u_74.Enums(_)
		return "Enum"
	end
	function v_u_74.Faces(p108)
		-- upvalues: (ref) v_u_4, (ref) v_u_22, (ref) v_u_20, (copy) v_u_69
		local v109 = {}
		for v110, v111 in v_u_4, {
			["Enum.NormalId.Top"] = p108.Top,
			["Enum.NormalId.Bottom"] = p108.Bottom,
			["Enum.NormalId.Left"] = p108.Left,
			["Enum.NormalId.Right"] = p108.Right,
			["Enum.NormalId.Back"] = p108.Back,
			["Enum.NormalId.Front"] = p108.Front
		} do
			if v111 then
				v_u_22(v109, v110)
			end
		end
		return "Faces.new(" .. v_u_20(v109, v_u_69) .. ")"
	end
	function v_u_74.FloatCurveKey(p112)
		-- upvalues: (copy) v_u_77
		return "FloatCurveKey.new(" .. v_u_77(p112.Time, p112.Value, p112.Interpolation) .. ")"
	end
	function v_u_74.Font(p113)
		-- upvalues: (copy) v_u_77
		return "Font.new(" .. v_u_77(p113.Family, p113.Weight, p113.Style) .. ")"
	end
	function v_u_74.Instance(p114)
		-- upvalues: (copy) v_u_65, (ref) v_u_56, (copy) v_u_70, (copy) v_u_74, (ref) v_u_18
		local v115 = v_u_65 and v_u_56(p114)
		if v115 then
			return v115
		end
		local v116 = v_u_70
		local v117 = p114.ClassName
		local v118 = "Instance.new(" .. v_u_74.string(v117, false) .. ")"
		local v119 = ""
		local v120 = "nil"
		for v121 in v_u_18(v118, "%](=*)%]") do
			if #v121 >= #v119 then
				v119 = v121 .. "="
			end
		end
		return v120 .. v116 .. "--[" .. v119 .. "[" .. v118 .. "]" .. v119 .. "]"
	end
	function v_u_74.NumberRange(p122)
		-- upvalues: (copy) v_u_77
		return "NumberRange.new(" .. v_u_77(p122.Min, p122.Max) .. ")"
	end
	function v_u_74.NumberSequence(p123)
		-- upvalues: (copy) v_u_74
		local v124 = p123.Keypoints
		return "NumberSequence.new(" .. v_u_74.table(v124, false) .. ")"
	end
	function v_u_74.NumberSequenceKeypoint(p125)
		-- upvalues: (copy) v_u_77
		return "NumberSequenceKeypoint.new(" .. v_u_77(p125.Time, p125.Value, p125.Envelope) .. ")"
	end
	function v_u_74.OverlapParams(p126)
		-- upvalues: (ref) v_u_20, (copy) v_u_74, (copy) v_u_69
		local v127 = {
			["FilterDescendantsInstances"] = p126.FilterDescendantsInstances,
			["FilterType"] = p126.FilterType,
			["MaxParts"] = p126.MaxParts,
			["CollisionGroup"] = p126.CollisionGroup,
			["RespectCanCollide"] = p126.RespectCanCollide
		}
		return "(function(v, p) for pn, pv in next, p do v[pn] = pv end return v end)(" .. v_u_20({ "OverlapParams.new()", (v_u_74.table(v127, false)) }, v_u_69) .. ")"
	end
	function v_u_74.PathWaypoint(p128)
		-- upvalues: (copy) v_u_77
		return "PathWaypoint.new(" .. v_u_77(p128.Position, p128.Action, p128.Label) .. ")"
	end
	function v_u_74.PhysicalProperties(p129)
		-- upvalues: (copy) v_u_77
		return "PhysicalProperties.new(" .. v_u_77(p129.Density, p129.Friction, p129.Elasticity, p129.FrictionWeight, p129.ElasticityWeight) .. ")"
	end
	function v_u_74.Random()
		return "Random.new()"
	end
	function v_u_74.Ray(p130)
		-- upvalues: (copy) v_u_77
		return "Ray.new(" .. v_u_77(p130.Origin, p130.Direction) .. ")"
	end
	function v_u_74.RaycastParams(p131)
		-- upvalues: (ref) v_u_20, (copy) v_u_74, (copy) v_u_69
		local v132 = {
			["FilterDescendantsInstances"] = p131.FilterDescendantsInstances,
			["FilterType"] = p131.FilterType,
			["IgnoreWater"] = p131.IgnoreWater,
			["CollisionGroup"] = p131.CollisionGroup,
			["RespectCanCollide"] = p131.RespectCanCollide
		}
		return "(function(v, p) for pn, pv in next, p do v[pn] = pv end return v end)(" .. v_u_20({ "RaycastParams.new()", (v_u_74.table(v132, false)) }, v_u_69) .. ")"
	end
	function v_u_74.Rect(p133)
		-- upvalues: (copy) v_u_77
		return "Rect.new(" .. v_u_77(p133.Min, p133.Max) .. ")"
	end
	function v_u_74.Region3(p134)
		-- upvalues: (copy) v_u_77
		local v135 = p134.CFrame
		local v136 = p134.Size
		return "Region3.new(" .. v_u_77(v135 * CFrame.new(-v136 / 2), v135 * CFrame.new(v136 / 2)) .. ")"
	end
	function v_u_74.Region3int16(p137)
		-- upvalues: (copy) v_u_77
		return "Region3int16.new(" .. v_u_77(p137.Min, p137.Max) .. ")"
	end
	function v_u_74.TweenInfo(p138)
		-- upvalues: (copy) v_u_77
		return "TweenInfo.new(" .. v_u_77(p138.Time, p138.EasingStyle, p138.EasingDirection, p138.RepeatCount, p138.Reverses, p138.DelayTime) .. ")"
	end
	function v_u_74.RotationCurveKey(p139)
		-- upvalues: (copy) v_u_77
		return "RotationCurveKey.new(" .. v_u_77(p139.Time, p139.Value, p139.Interpolation) .. ")"
	end
	function v_u_74.UDim(p140)
		-- upvalues: (copy) v_u_77
		return "UDim.new(" .. v_u_77(p140.Scale, p140.Offset) .. ")"
	end
	function v_u_74.UDim2(p141)
		-- upvalues: (copy) v_u_77
		return "UDim2.new(" .. v_u_77(p141.X.Scale, p141.X.Offset, p141.Y.Scale, p141.Y.Offset) .. ")"
	end
	function v_u_74.Vector2(p142)
		-- upvalues: (copy) v_u_77
		return "Vector2.new(" .. v_u_77(p142.X, p142.Y) .. ")"
	end
	function v_u_74.Vector2int16(p143)
		-- upvalues: (copy) v_u_77
		return "Vector2int16.new(" .. v_u_77(p143.X, p143.Y) .. ")"
	end
	function v_u_74.Vector3(p144)
		-- upvalues: (copy) v_u_77
		return "Vector3.new(" .. v_u_77(p144.X, p144.Y, p144.Z) .. ")"
	end
	function v_u_74.Vector3int16(p145)
		-- upvalues: (copy) v_u_77
		return "Vector3int16.new(" .. v_u_77(p145.X, p145.Y, p145.Z) .. ")"
	end
	function v_u_74.userdata(p146)
		-- upvalues: (ref) v_u_11
		return v_u_11(p146) and "newproxy(true)" or "newproxy()"
	end
	local v147 = ""
	for v148, v149 in v_u_4, p_u_57 do
		local v150 = v_u_24(v148)
		local v151 = v_u_24(v149)
		if v_u_74[v150] and v_u_74[v151] then
			local v152 = v_u_60 and (v68 .. v71 or "") or ""
			local v153 = false
			local v154, v155, v156 = v_u_5(v_u_74[v150], v148, true)
			local v157, v158 = v_u_5(v_u_74[v151], v149, false)
			if v154 and (v157 and v158) then
				v152 = v152 .. (v155 and ((v156 and v155 and v155 or v_u_12("[%s]", v155)) .. (v_u_60 and " = " or "=") or "") or "") .. v158
				v153 = true
			elseif v62 then
				local v159 = v_u_12("LuaEncode: Failed to encode %s of DataType `%s`: %s", v154 and (v157 and "key/value" or "value") or "key", v151, not v154 and v_u_46(v155) or (not v157 and v_u_46(v158) or "(Failed to get error message)"))
				local v160 = ""
				for v161 in v_u_18(v159, "%](=*)%]") do
					if #v161 >= #v160 then
						v160 = v161 .. "="
					end
				end
				v152 = v152 .. "--[" .. v160 .. "[" .. v159 .. "]" .. v160 .. "]"
			end
			if v_u_4(p_u_57, v148) then
				if v153 then
					v152 = v152 .. ","
				end
			else
				v152 = v152 .. v68 .. v72
			end
			v147 = v147 .. v152
		end
	end
	return "{" .. v147 .. "}"
end
return v_u_162
