-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMvDU9uQ2xpZW50RXZlbnQLYWRkV2F5cG9pbnQHQ29ubmVjdBRyZW1vdmVXYXlwb2ludEJ5TmFtZRhBRERfV0FZUE9JTlRfUkVNT1RFX05BTUUHYW5kVGhlbhtSRU1PVkVfV0FZUE9JTlRfUkVNT1RFX05BTUUEaW5pdAV0YWJsZQRmaW5kBnBvaW50cwZyZW1vdmUNdHJpZ2dlclVwZGF0ZQRGaXJlBHBhcnQLR2V0RnVsbE5hbWUJX2RlYnVnU3RyBmluc2VydANhZGQHY2lyY2xlcwlhZGRDaXJjbGUEbmFtZQVtZXJnZQR0eXBlCGRpc3BhdGNoBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApEaWN0aW9uYXJ5BlNpZ25hbAVSb2FjdAx3YWl0Rm9yQ2hpbGQDQXBwDU1pbmltYXBDb25zdHMFc3RvcmUNY3JlYXRlQmluZGluZwZDb2xvcjMDbmV3Dm1hcEltYWdlQ29sb3IzFHVwZGF0ZU1hcEltYWdlQ29sb3IzEG1hcFdvcmxkUG9zaXRpb24WbWFwVXBkYXRlV29ybGRQb3NpdGlvbgRVbml0EW1hcFdvcmxkRGlyZWN0aW9uF21hcFVwZGF0ZVdvcmxkRGlyZWN0aW9uAAsFAQEAAAAJTQEAjAAAAAD7BAAATQME9gEAAAC8AQHHAgAAAJ8BAwGCAAEAAwMBAwIDAwAVAAEYAAAAAAAAAAABFgAAAAAFAQEAAAAJTQEAjAAAAAD7BAAATQMEwAEAAAC8AQHHAgAAAJ8BAwGCAAEAAwMBAwQDAwAYAAEYAAAAAAAAAAABGQAAAAAEAAQAAAAX+wAAAPsBAQD7AwIATQIDGwAAAACfAAMCwAIBABICAwC8AAC1AgAAAJ8AAwH7AAAA+wEBAPsDAgBNAgMGAwAAAJ8AAwLAAgQAEgIDALwAALUCAAAAnwADAYIAAQAFAwUGAAMGAwcGAQIAARQIARgAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAxUAAAAABAACAAAAFaQAAgAABACA+wIAAE0BAg0DAAAA+wIBAJ8AAwKkAQUAABAAgPsDAABNAgMNAwAAAFIDAACfAQMB+wIAAE0BAg8GAAAAvAEB3QcAAACfAQIBggABAAgDCQMKBAAEAIADCwMMBAAQAIADDQMOACIAARgAAAAAAAAAAQAAAAAAAAEAAAAAAAEjAAAAAAQBAQAAAB1NAQAkAAAAAA4BBwBNAQAkAAAAALwBAbIBAAAAnwECAjABANgCAAAA+wMAAE0CAw0DAAAAnjQCBAAAAABSAwAApAEGAAAUQICfAQMB+wIAAE0BAg8HAAAAvAEB3QgAAACfAQIB2QEAABICAAASAAAAggECAAkDDwMQAxEDCwMJAxIEABRAgAMNAw4BAxwTARgAAAABAAAAAAAAAgAAAAAAAAAAAQAAAAAAAQAAAB0AAAAABAACAAAAFaQAAgAABACA+wIAAE0BAtgDAAAA+wIBAJ8AAwKkAQUAABAAgPsDAABNAgPYAwAAAFIDAACfAQMB+wIAAE0BAg8GAAAAvAEB3QcAAACfAQIBggABAAgDCQMKBAAEAIADFAMMBAAQAIADDQMOACwAARgAAAAAAAAAAQAAAAAAAAEAAAAAAAEtAAAAAAQBAQAAABP7AwAATQID2AAAAACeNAIEAAAAAFIDAACkAQMAAAgQgJ8BAwH7AgAATQECDwQAAAC8AQHdBQAAAJ8BAgHZAQAAEgIAABIAAACCAQIABgMUAwkDEgQACBCAAw0DDgEFKRUBGAAAAAAAAAAAAAEAAAAAAAEAAAAqAAAAAAMAAgAAAAj7AQAATQABwAAAAAD7AgEATQECWgEAAACfAAIAggAAAAIDBAMWADcAARgAAAAAAAAAADgAAAAABgEDAAAAEfsBAAD7BAEATQMEHwAAAADiBAIAbwUDADAFBHEBAAAAUgUAAJ8DAwC8AQFMBAAAAJ8BAAHZAQAAEgICABIAAACCAQIABQMXAxgFAQEDAgMZAQcyAgEYAAAAAAABAAAB/gAAAAQAAAAzAAAAAAUBAQAAAAv7AQAA4gMCAG8EAwAwBANxAAAAADAAA1oBAAAAvAEBTAQAAACfAQMBggABAAUDGAMWBQIAAQMEAxkAOwQBGAAAAQAAAQD+AAAEPAAAAAANAAABAgcAAAEICkkCd6MAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DAKEGAAAATQIDqQcAAACfAQICpAIFAAAAQEBNBAChBgAAAE0DBB8IAAAAnwICAqQDBQAAAEBATQQAIQkAAACfAwICpAQFAAAAQEBNBgChBgAAAE0FBvMKAAAAnwQCAqQFBQAAAEBATQcAwQsAAABNBgfWDAAAAJ8FAgKkBgUAAABAQE0IAMELAAAATQcIfg0AAACfBgIC/wcFAAAAAABNCAMxDgAAAKQJEQAAQPCAjAoBAIwLAQCMDAEAnwkEAJ8IAAMwCAfuEgAAADAJB8sTAAAATQgDMQ4AAABvCRQAnwgCAzAIB1MVAAAAMAkHXhYAAABNCAMxDgAAAG8KFwBNCQoHGAAAAJ8IAgMwCAcWGQAAADAJB7waAAAA/wgAAAAAAAAwCAcNGwAAAP8IAAAAAAAAMAgH2BwAAABNCALvEAAAAJ8IAQIwCAcPHQAAAMAIHgASAAQAEgAAABIABQASAAcAMAgHEx8AAADACCAAEgAHADAIB78hAAAAwAgiABIABwAwCAftIwAAAMAIJAASAAYAEgABABIABwAwCAf2JQAAAMAIJgASAAYAMAgHwCcAAACCBwIAKAMaBAAAAEADGwMcAx0EAABAQAMeAx8DIAMhAyIDIwMkAyUDJgMnAygEAEDwgAMpAyoHAAAAAAAAAAAAAAAAAAAAAAMrAywHAACAPwAAAAAAAIA/AAAAAAMtAy4DLwMLAxQDDQYCAwgGBAMTBgYDFQYIAwIGCQMEBQIEBggJAQABGAABAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAQAAAAAAAAIAAAAAAAABAAAAAAAAAgABAAAAAAAAAAAAAAAAAQAAAAAAAAACAAAAAAD/AAAAAgAAAAEAAAABAAAAAAIAAAAAAAAIAAAADQAAAAkAAAAAAAkAAAAGAQAAAAAK3hA+At77m3/s1FSWW0cxkwPmSXRujwN0/5M1gvKOOgBRGVpdnLngJQ==

-- Decompiled by Krnl

local v_u_1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v_u_1.Std.Dictionary)
local v3 = require(v_u_1.Std.Signal)
local v4 = require(v_u_1.Roact)
local v_u_5 = require(v_u_1.Std.waitForChild)
local v_u_6 = require(v_u_1.App.MinimapConsts)
local v_u_7 = require(v_u_1.App.store)
local v_u_8 = {}
local v9, v10 = v4.createBinding(Color3.new(1, 1, 1))
v_u_8.mapImageColor3 = v9
v_u_8.updateMapImageColor3 = v10
local v11, v12 = v4.createBinding(Vector3.new(0, 0, 0))
v_u_8.mapWorldPosition = v11
v_u_8.mapUpdateWorldPosition = v12
local v13, v14 = v4.createBinding((Vector3.new(1, 0, 1)).Unit)
v_u_8.mapWorldDirection = v13
v_u_8.mapUpdateWorldDirection = v14
v_u_8.points = {}
v_u_8.circles = {}
v_u_8.triggerUpdate = v3.new()
function v_u_8.init()
	-- upvalues: (copy) v_u_5, (copy) v_u_1, (copy) v_u_6, (copy) v_u_8
	v_u_5(v_u_1, v_u_6.ADD_WAYPOINT_REMOTE_NAME):andThen(function(p15)
		-- upvalues: (ref) v_u_8
		p15.OnClientEvent:Connect(v_u_8.addWaypoint)
	end)
	v_u_5(v_u_1, v_u_6.REMOVE_WAYPOINT_REMOTE_NAME):andThen(function(p16)
		-- upvalues: (ref) v_u_8
		p16.OnClientEvent:Connect(v_u_8.removeWaypointByName)
	end)
end
function v_u_8.add(p_u_17)
	-- upvalues: (copy) v_u_8
	if p_u_17.part then
		p_u_17._debugStr = p_u_17.part:GetFullName()
	end
	local v18 = v_u_8.points
	table.insert(v18, p_u_17)
	v_u_8.triggerUpdate:Fire()
	return function()
		-- upvalues: (ref) v_u_8, (copy) p_u_17
		local v19 = table.find(v_u_8.points, p_u_17)
		table.remove(v_u_8.points, v19)
		v_u_8.triggerUpdate:Fire()
	end
end
function v_u_8.addCircle(p_u_20)
	-- upvalues: (copy) v_u_8
	local v21 = v_u_8.circles
	table.insert(v21, p_u_20)
	v_u_8.triggerUpdate:Fire()
	return function()
		-- upvalues: (ref) v_u_8, (copy) p_u_20
		local v22 = table.find(v_u_8.circles, p_u_20)
		table.remove(v_u_8.circles, v22)
		v_u_8.triggerUpdate:Fire()
	end
end
function v_u_8.addWaypoint(p_u_23)
	-- upvalues: (copy) v_u_7, (copy) v_u_2, (copy) v_u_8
	v_u_7:dispatch(v_u_2.merge({
		["type"] = "addWaypoint"
	}, p_u_23))
	return function()
		-- upvalues: (ref) v_u_8, (copy) p_u_23
		return v_u_8.removeWaypointByName(p_u_23.name)
	end
end
function v_u_8.removeWaypointByName(p24)
	-- upvalues: (copy) v_u_7
	v_u_7:dispatch({
		["type"] = "removeWaypointByName",
		["name"] = p24
	})
end
return v_u_8
