-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMcBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplB0RlZmF1bHQJVm9pY2VDaGF0BEhhbmcKTUFJTl9XT1JMRAtUUkFERV9XT1JMRARQUk9EAlFBA0RFVgZTVFVESU83ZW52IHdhcyBhbHJlYWR5IHBvcHVsYXRlZCBmb3IgdGhpcyBwbGFjZUlkLi4gZHVwbGljYXRlPwZhc3NlcnQdRU5WX1RPX1dPUkxEX1RPX1BMQUNFX0lEU19NQVATUExBQ0VfSURfVE9fRU5WX01BUBVQTEFDRV9JRF9UT19XT1JMRF9NQVAaUExBQ0VfSURfVE9fUExBQ0VfVFlQRV9NQVAPTUFJTl9XT1JMRF9OQU1FEFRSQURFX1dPUkxEX05BTUUJUFJPRF9OQU1FB1FBX05BTUUIREVWX05BTUULU1RVRElPX05BTUUAARgAAAEAAMgBowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAoQYAAABNAgMYBwAAAJ8BAgJNAgEACAAAAP8DAwAAAAAATQQBAAgAAAD/BQIAAAAAAOIGDABvBw0AMAcGOgkAAABvBw4AMAcGhgoAAABvBw8AMAcGsgsAAAAwBgXtEAAAAOIGEQBvBxIAMAcGOgkAAAAwBgV5EwAAAJ8EAgIwBAO6FAAAAE0EAQAIAAAA/wUCAAAAAADiBgwAbwcVADAHBjoJAAAAbwcWADAHBoYKAAAAbwcXADAHBrILAAAAMAYF7RAAAADiBhEAbwcYADAHBjoJAAAAMAYFeRMAAACfBAICMAQDUhkAAABNBAEACAAAAP8FAgAAAAAA4gYMAG8HGgAwBwY6CQAAAIwHAQAwBwaGCgAAAG8HGwAwBwayCwAAADAGBe0QAAAA4gYRAG8HHAAwBwY6CQAAADAGBXkTAAAAnwQCAjAEA6odAAAATQQBAAgAAAD/BQIAAAAAAOIGDABvBx4AMAcGOgkAAACMBwIAMAcGhgoAAACMBwMAMAcGsgsAAAAwBgXtEAAAAOIGEQCMBwQAMAcGOgkAAAAwBgV5EwAAAJ8EAgIwBAPqHwAAAJ8CAgL/AwAAAAAAAP8EAAAAAAAA/wUAAAAAAABSBgIAxgcAAMYIAABkBhoAUgsKAMYMAADGDQAAZAsUAFIQDwDGEQAAxhIAAGQQDgCHFwMURxcCAAAAAACpFgABqRYBAIEBFgQgAAAAbxcgAKQVIgAAABBCnxUDAWoJAxRqDgQUahMFFG4Q8f8CAAAAbgvr/wIAAABuBuX/AgAAAE0GAQAIAAAA4gctADACB/cjAAAATQgBAAgAAABSCQMAnwgCAjAIB0ckAAAATQgBAAgAAABSCQQAnwgCAjAIB5YlAAAATQgBAAgAAABSCQUAnwgCAjAIB6smAAAAbwgQADAIB+MnAAAAbwgTADAIB68oAAAAbwgUADAIB8EpAAAAbwgZADAIB5wqAAAAbwgdADAIB8ErAAAAbwgfADAIB+0sAAAAnwYCAIIGAAAuAwEEAAAAQAMCAwMDBAQAAEBAAwUDBgMHAwgDCQMKBQMJCgsCAACAKuUVwkECAAAMOoMCEEICAAAQP4MCEEIDCwUBCQIAAGAB8TcCQgMMAw0CAABgjH0n80ECAABcQIcCEEICAAC4jH0CEEICAACgZvE3AkIDDgIAAEA+fLL5QQIAANxVjAIQQgIAAEDe8TcCQgMPAgAAgJQGH8VBAxADEQMSBAAAEEIDEwMUAxUDFgMXAxgDGQMaAxsDHAUKIyQlJicoKSorLAABAAEYAAEAAAAAAAEAAAAAAAAMAAAAAQAAAAEAAAAAAAAAAAAAAAEAAAAAAP4AAAQAAAABAAAAAAAAAAAAAAABAAAAAAD+AAAEAAAAAQAAAAAAAAAAAAAAAQAAAAAA/gAABAAAAAEAAAAAAAAAAAAAAAEAAAAAAP4AAPMSAAEAAQABAAAAAQAAAAEAAAABAAAAAAAAAAAAAAEBAfwA/wD/AAoAAAEAAgAAAAAAAgAAAAAAAgAAAAAAAQAAAQAAAQAAAQAAAQAAAQAA8wABAAAAAAB2RbIZTdQyskSB2I2D3uS0K/fvs/ZM5EreQak9NF295KJSKRS7XNKw

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v2 = require(v1.Std.TableUtils)
local v3 = v2.requireValidIndexAndFreeze({
	["PROD"] = v2.requireValidIndexAndFreeze({
		["MAIN_WORLD"] = {
			["Default"] = 606849621,
			["VoiceChat"] = 17190407811,
			["Hang"] = 17190408132
		},
		["TRADE_WORLD"] = {
			["Default"] = 9780994092
		}
	}),
	["QA"] = v2.requireValidIndexAndFreeze({
		["MAIN_WORLD"] = {
			["Default"] = 5141682374,
			["VoiceChat"] = 17190473751,
			["Hang"] = 17190314798
		},
		["TRADE_WORLD"] = {
			["Default"] = 9780997332
		}
	}),
	["DEV"] = v2.requireValidIndexAndFreeze({
		["MAIN_WORLD"] = {
			["Default"] = 6898041828,
			["VoiceChat"] = 1,
			["Hang"] = 17190557047
		},
		["TRADE_WORLD"] = {
			["Default"] = 9781001160
		}
	}),
	["STUDIO"] = v2.requireValidIndexAndFreeze({
		["MAIN_WORLD"] = {
			["Default"] = 708709673,
			["VoiceChat"] = 2,
			["Hang"] = 3
		},
		["TRADE_WORLD"] = {
			["Default"] = 4
		}
	})
})
local v4 = {}
local v5 = {}
local v6 = {}
for v7, v8 in v3 do
	for v9, v10 in v8 do
		for v11, v12 in v10 do
			local v13 = v4[v12] == nil
			assert(v13, "env was already populated for this placeId.. duplicate?")
			v4[v12] = v7
			v5[v12] = v9
			v6[v12] = v11
		end
	end
end
return v2.requireValidIndexAndFreeze({
	["ENV_TO_WORLD_TO_PLACE_IDS_MAP"] = v3,
	["PLACE_ID_TO_ENV_MAP"] = v2.requireValidIndexAndFreeze(v4),
	["PLACE_ID_TO_WORLD_MAP"] = v2.requireValidIndexAndFreeze(v5),
	["PLACE_ID_TO_PLACE_TYPE_MAP"] = v2.requireValidIndexAndFreeze(v6),
	["MAIN_WORLD_NAME"] = "MAIN_WORLD",
	["TRADE_WORLD_NAME"] = "TRADE_WORLD",
	["PROD_NAME"] = "PROD",
	["QA_NAME"] = "QA",
	["DEV_NAME"] = "DEV",
	["STUDIO_NAME"] = "STUDIO"
})
