-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMvBkNGcmFtZQ1mcm9tQXhpc0FuZ2xlBGF4aXMGYW5nbGUwBm9yaWdpbg9jb21wdXRlUG9zaXRpb24TcmFuZG9tUG9pbnRPbkNpcmNsZQF4AXkHVmVjdG9yMwNuZXcFQ3Jvc3MEbWF0aAZyYW5kb20GY3JlYXRlE3JhbmRvbVBvaW50T25TcGhlcmUEdGFzawR3YWl0Am9zBWNsb2NrBGxpc3QGYm9ybkF0DGxhc3RQb3NpdGlvbgZ0cmFjZXIERHJhdwhsaWZldGltZQV0YWJsZQZyZW1vdmUHRGVzdHJveQVldmVyeQdDb25uZWN0CUhlYXJ0YmVhdARpbml0BkNvbG9yMwhTZXRDb2xvcgxTZXRUaGlja25lc3MGaW5zZXJ0BGdhbWUKUnVuU2VydmljZQpHZXRTZXJ2aWNlEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUDU3RkCEludGVydmFsBEdhbWUGVHJhY2VyCUdlb21VdGlscwAGBwIAAAAADKQDAgAABACATQQAZwMAAABNBgBNBAAAAEMFAQafAwMCTQQAIwUAAAAJAgMEggICAAYDAQMCBAAEAIADAwMEAwUACAYBGAAAAAAAAAAAAAAAAAkAAAAADAACAAAHAAABCAENATD7AQAATQABtAAAAACfAAECTQIAmQIAAACMAwAATQQAmAMAAABMNgACpAEGAAAUQICfAQQCWwABAW8DBwC8AQC7CAAAAJ8BAwKkBA0AADCwgJ8EAQJbAwQKlQIDCYwFAQCMAwQAjAQBAKgDFAD7BwEATQYHdg4AAAD7CgAATQkKjBAAAACfCQECWwgJD0MHAAhSCAEApAsNAAAwsICfCwECWwoLEUMJAgqfBgQBpAYUAABMIIGfBgEBiwPs/4IAAQAVAwcCAAAAAACIs0ADCAMJAwoDCwQAFECABwAAAAAAAIA/AAAAAAAAAAADDAIAAAAAAADwPwIAAAAAAADgPwMNAw4EADCwgAMPAgAAAAAAAElAAxACmpmZmZmZyT8DEQMSBABMIIEADwABGAAAAAABAAAAAAAAAAAAAQAAAAEAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAABAAD+BBQAAAAADAABAAAARqQAAgAABACAnwABAvsFAABNBAULAwAAABwDBACMAQEAjAL//6gBOwD7BgAATQUGCwMAAACHBAUDTQYElAQAAAAmBQAGTQYEaQUAAAArBgwApAcIAAAcYIBNCARnCQAAAIwKAABNCwRNCgAAAEMJCgufBwMCTQgEIwsAAAAJBgcIpAgIAAAcYIBNCQRnCQAAAE0LBE0KAAAAQwoFC58IAwJNCQQjCwAAAAkHCAkwBwRpBQAAAE0IBGsMAAAAUgoGAFILBwC8CAjUDQAAAJ8IBAFNCATrDgAAAGAIDQAFAAAApAgRAABA8ID7CgAATQkKCwMAAABSCgMAnwgDAU0IBGsMAAAAvAgIUBIAAACfCAIBiwHF/4IAAQATAxMDFAQABACAAxUDFgMXAwEDAgQAHGCAAwMDBAMFAxgDGQMaAxsDHAQAQPCAAx0AHQABGBUAAAEAAAAAAAABAAAAAgAAAQAB5QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfAAEAAAAAAAABAAAAAQAAAAAAAAEAAAAA8xAJAAAAAAMABAAAABT7AQAATQABxAAAAACMAQoAnwACAsACAQASAgEAEgICALwAAMcCAAAAnwADAfsBAwBNAAH9AwAAAMACBAASAgIAvAAAxwIAAACfAAMBggABAAUDHgYBAx8DIAYCAgECDiEBGAAAAAAAAAAAAAAADgAAAAAAAAATDwAAAAAKAwIAAAAu+wQAAE0DBO8AAAAAnwMBAqQGAgAAABCAjAcBAIwIAQCMCQEAnwYEALwEAz8DAAAAnwQAAYwGAQC8BANtBAAAAJ8EAwH7BgEATQUGCwUAAADiBgwApAcPAAA40ICfBwECMAcGlAYAAAAwAwZrBwAAADAABiMIAAAAMAEGZwkAAAAwAgbrCgAAAKQIEwAASBCBnwgBAlsHCBAwBwZNCwAAAJ40BQMGAAAApAQWAABUQIGfBAMBggABABcDCwMiBAAAEIADIwMkAxUDFgMYAwUDAwMaAwQFBgYHCAkKCwMTAxQEADjQgAIYLURU+yEJQAMNAw4EAEgQgQMbAyUEAFRAgQAxDwEYAAAAAAEAAAAAAAAAAAEAAAABAAAAAQAAAAABAAEAAQABAAEAAAAAAAAA+gAACDIAAAAACAAAAQIANqMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQEAAAAAQG8DBAC8AQEWAwAAAJ8BAwKkAgYAAABQQE0EAaEHAAAATQMErAgAAACfAgICpAMGAAAAUEBNBQG9CQAAAE0EBUsKAAAAnwMCAqQEBgAAAFBATQYBoQcAAABNBQY8CwAAAJ8EAgLABQwA/wYDAAAAAAD/BwAAAAAAADAHBgsNAAAAwAcOABIAAgASAAQAEgAGABIAAAAwBwYTDwAAAMAHEAASAAMAEgAGADAHBnYRAAAAggYCABIDJgQAAABAAycDKAMpAyoEAABQQAMrAywDLQMuAy8GAAMVBgMDIQYEAw8DAAMEAQABGAABAAAAAAABAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAACBAABAAAAAQAAAAAAACMAAAAADQEAAAAABcx7Y0MKbkay/r8J12UudopzVKLfJELAm9ufm1WWLQyGhPI++y9vHCM=

-- Decompiled by Krnl

local v_u_1 = game:GetService("RunService")
local v2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v2.Std.Interval)
local v_u_4 = require(v2.Game.Tracer)
local v_u_5 = require(v2.Std.GeomUtils)
local v_u_24 = {
	["list"] = {},
	["init"] = function()
		-- upvalues: (copy) v_u_3, (copy) v_u_5, (copy) v_u_24, (copy) v_u_1
		v_u_3.every(10):Connect(function()
			-- upvalues: (ref) v_u_5, (ref) v_u_24
			local v6 = v_u_5.randomPointOnCircle()
			local v7 = v6.x
			local v8 = v6.y
			local v9 = Vector3.new(v7, 0, v8) * 5000
			local v10 = v9:Cross(Vector3.new(0, 1, 0))
			local v11 = math.random() * 0.5 + 1
			for _ = 1, 4 do
				v_u_24.create(v9 + v_u_5.randomPointOnSphere() * 50, v10, v11 + math.random() * 0.2)
				task.wait()
			end
		end)
		v_u_1.Heartbeat:Connect(function()
			-- upvalues: (ref) v_u_24
			local v12 = os.clock()
			for v13 = #v_u_24.list, 1, -1 do
				local v14 = v_u_24.list[v13]
				local v15 = v12 - v14.bornAt
				local v16 = v14.lastPosition or CFrame.fromAxisAngle(v14.axis, 0 + v14.angle0) * v14.origin
				local v17 = CFrame.fromAxisAngle(v14.axis, v15 + v14.angle0) * v14.origin
				v14.lastPosition = v17
				v14.tracer:Draw(v16, v17)
				if v14.lifetime < v15 then
					table.remove(v_u_24.list, v13)
					v14.tracer:Destroy()
				end
			end
		end)
	end,
	["create"] = function(p18, p19, p20)
		-- upvalues: (copy) v_u_4, (copy) v_u_24
		local v21 = v_u_4.new()
		v21:SetColor(Color3.new(1, 1, 1))
		v21:SetThickness(1)
		local v22 = v_u_24.list
		local v23 = {
			["bornAt"] = os.clock(),
			["tracer"] = v21,
			["origin"] = p18,
			["axis"] = p19,
			["lifetime"] = p20,
			["angle0"] = math.random() * 3.141592653589793
		}
		table.insert(v22, v23)
	end
}
return v_u_24
