-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMfA25ldwxzZXRtZXRhdGFibGUFU2V0dXALT2JqZWN0TG9jYWwDVGlwBkNvbmZpZwVTb3VuZB9ndW5fc2VtaV9hdXRvX3JpZmxlX2RyeV9maXJlXzAxBlZvbHVtZQVQaXRjaARtYXRoBnJhbmRvbRtndW5fc2VtaV9hdXRvX3JpZmxlX3Nob3RfMDEKU2hvb3RTb3VuZCZndW5fc2VtaV9hdXRvX3JpZmxlX21hZ2F6aW5lX3VubG9hZF8wMRJSb2xsT2ZmTWF4RGlzdGFuY2UTUmVsb2FkRHJvcEFtbW9Tb3VuZCRndW5fc2VtaV9hdXRvX3JpZmxlX21hZ2F6aW5lX2xvYWRfMDEVUmVsb2FkUmVmaWxsQW1tb1NvdW5kBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZAVBdWRpbwZzY3JpcHQGUGFyZW50A0d1bgRBSzQ3C19fQ2xhc3NOYW1lB19faW5kZXgABQcDAgAAABP7BAAATQME7wAAAABSBAAAUgUBAFIGAgCfAwQC+wYBAJ49AwQGAAAAUgUDAKQEAgAAABBAnwQDAVIGAgC8BAOZAwAAAJ8EAwGCAwIABAMBAwIEAAAQQAMDAAwBARgAAAAAAAAAAQAAAAAAAAEAAAACDQAAAAALAgEAAAAyDgEaAPsDAABNAgPRAAAAAE0DALEBAAAATQYA2QIAAABNBQZuAwAAAE0EBeMEAAAA4gUHAG8GCAAwBgVLBQAAAIwIAQCkCg0AADCwgJ8KAQJbCQoKQwcICXgGBwkwBgUABgAAAJ8CBAGCAAEA+wMAAE0CA9EAAAAATQMAsQEAAABNBgDZAgAAAE0FBm4DAAAATQQF7Q4AAADiBQ8AjAgBAKQKDQAAMLCAnwoBAlsJCgpDBwgJeAYHCTAGBQAGAAAAnwIEAYIAAQAQAwQDBQMGAwcDCAMJAwoFAgUGApqZmZmZmdk/ApqZmZmZmak/ApqZmZmZmbk/AwsDDAQAMLCAAw0FAQYAEw4BGAABAAABAAEAAAAAAAEAAAAAAAAAAAAAAAD9AAYAAAEAAQAAAAAAAQAAAAAAAAAAAP0GFAAAAAAGAQEAAAAR+wIAAE0BAtEAAAAATQIAsQEAAABNBQDZAgAAAE0EBW4DAAAATQMEHgQAAADiBAYAjAWBADAFBCoFAAAAnwEEAYIAAQAHAwQDBQMGAwcDDwMQBQEFACIRARgAAAAAAAAAAAAAAAABAAD/AyMAAAAABgEBAAAAEfsCAABNAQLRAAAAAE0CALEBAAAATQUA2QIAAABNBAVuAwAAAE0DBP8EAAAA4gQGAIwFgQAwBQQqBQAAAJ8BBAGCAAEABwMEAwUDBgMHAxIDEAUBBQAnEwEYAAAAAAAAAAAAAAAAAQAA/wMoAAAAAAgAAAECADejAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CA9IHAAAAnwECAqQDCQAAAIBATQIDJAoAAACkAwUAAABAQE0EAg0LAAAAnwMCAv8EBAAAAAAAbwUMADAFBOUNAAAAMAQEbg4AAACePQQFAwAAAFIGBABSBwMApAUQAAAA8ECfBQMBwAURABIAAwASAAQAMAUE7xIAAADABRMAEgABADAFBLkUAAAAwAUVABIAAQAwBQS9FgAAAMAFFwASAAEAMAUEeRgAAACCBAIAGQMUBAAAAEADFQMWAxcEAABAQAMYAxkDGgQAAIBAAxsDHAMdAx4DHwMCBAAA8EAGAAMBBgEDDgYCAxEGAwMTBAABAgMBAAEYAAEAAAAAAAEAAAAAAAACAAAAAQAAAAACAAEAAAEAAQAAAAAAAAEAAAAABwAAAA8AAAAFAAAABgEAAAAABHtyuydV11nbSbbRs2PiEVrRGY175ifgupjYOwcd2h/5HfT2mg6lZN8=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.Audio)
local v3 = script.Parent
local v_u_4 = require(v3.Gun)
local v_u_5 = {
	["__ClassName"] = "AK47"
}
v_u_5.__index = v_u_5
setmetatable(v_u_5, v_u_4)
function v_u_5.new(p6, p7, p8)
	-- upvalues: (copy) v_u_4, (copy) v_u_5
	local v9 = v_u_4.new(p6, p7, p8)
	local v10 = v_u_5
	setmetatable(v9, v10)
	v9:Setup(p8)
	return v9
end
function v_u_5.ShootSound(p11, p12)
	-- upvalues: (copy) v_u_2
	if p12 then
		v_u_2.ObjectLocal(p11.Tip, p11.Config.Sound.gun_semi_auto_rifle_dry_fire_01, {
			["Volume"] = 0.4,
			["Pitch"] = 1 + math.random() * 0.1 - 0.05
		})
	else
		v_u_2.ObjectLocal(p11.Tip, p11.Config.Sound.gun_semi_auto_rifle_shot_01, {
			["Pitch"] = 1 + math.random() * 0.1 - 0.05
		})
	end
end
function v_u_5.ReloadDropAmmoSound(p13)
	-- upvalues: (copy) v_u_2
	v_u_2.ObjectLocal(p13.Tip, p13.Config.Sound.gun_semi_auto_rifle_magazine_unload_01, {
		["RollOffMaxDistance"] = 129
	})
end
function v_u_5.ReloadRefillAmmoSound(p14)
	-- upvalues: (copy) v_u_2
	v_u_2.ObjectLocal(p14.Tip, p14.Config.Sound.gun_semi_auto_rifle_magazine_load_01, {
		["RollOffMaxDistance"] = 129
	})
end
return v_u_5
