-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgOGAQRtYXRoBnJhbmRvbQdWZWN0b3IzA25ldwRVbml0DFJhbmRvbVZlY3RvchFfdXBkYXRlSGVhdFJlbW90ZQVNb2RlbAhfZ2V0VGlwcwVMb2NhbBRvYnNlcnZlT25lQ2hpbGROYW1lZBBVcGRhdGVIZWF0UmVtb3RlCEdpdmVUYXNrD29ic2VydmVQcm9wZXJ0eQVWYWx1ZQxzZXRtZXRhdGFibGUETWFpZAxWZWhpY2xlTW9kZWwHcHJpbWFyeQpzYXR1cmF0ZVRvCHByaW9yaXR5F1Nob290QWN0aW9uQnV0dG9uQ29uZmlnBVNldHVwFURlZmF1bHREaXNhYmxlQ2FtTG9jawpBdHRhY2htZW50A0lzQQ5GaW5kRmlyc3RDaGlsZApUdXJyZXRUaXBzBmZpbHRlcgtHZXRDaGlsZHJlbgRUaXBzCUNoYXJhY3RlcgVJdGVtcwl3b3Jrc3BhY2UKSWdub3JlTGlzdA1CdWxsZXRFbWl0dGVyEV91cGRhdGVJZ25vcmVMaXN0DVJlbmRlclN0ZXBwZWQHU3RlcHBlZAlMYXN0U2hvb3QQTGFzdFBsYXllckltcGFjdBhTcHJpbmdUaGlyZE1vdXNlUG9zaXRpb24MU3ByaW5nQ2FtZXJhClNwcmluZ1NwaW4JU3BpblRvdGFsCU1vdXNlRG93bghUaXBJbmRleBJTZXR1cEJ1bGxldEVtaXR0ZXIKU2V0dXBTaG9vdBNVcGRhdGVNb3VzZVBvc2l0aW9uB0Nvbm5lY3QEdGljax1CdWxsZXRFbWl0dGVyT25Mb2NhbEhpdFBsYXllcglTZXRUYXJnZXQbVHJhbnNmb3JtTG9jYWxNb3VzZVBvc2l0aW9uD1VwZGF0ZUFybUpvaW50cwZVcGRhdGUGQ0ZyYW1lAXgBeQxVcGRhdGVDYW1lcmEDVGlwDVdvcmxkUG9zaXRpb24LV29ybGRDRnJhbWUKTG9va1ZlY3RvcgZDb25maWcLQnVsbGV0U3BlZWQERW1pdAtQcmltYXJ5UGFydAhQb3NpdGlvbgFwCU1hZ25pdHVkZQVjbGFtcApBY2NlbGVyYXRlBVNob290FFNob290Q2hlY2tDb25kaXRpb25zBVNvdW5kBlZvbHVtZQdNYXhIZWF0BEhlYXQMR2V0QXR0cmlidXRlDVVzZXJJbnB1dFR5cGUERW51bQxNb3VzZUJ1dHRvbjEKSW5wdXRFbmRlZA1fYXR0ZW1wdFNob290BlR1cnJldAtDb2xvck5vcm1hbAlDb2xvckhlYXQETGVycAVDb2xvcgxTZXRBdHRyaWJ1dGUNQW5pbWF0ZUJhcnJlbApMYXN0VXBkYXRlCUhlYXJ0YmVhdAhHYW1lcGFkMQdLZXlDb2RlB0J1dHRvblgISW5zdGFuY2UXcmJ4YXNzZXRpZDovLzIxOTgzOTAzOTEHU291bmRJZAZMb29wZWQGUGFyZW50BFBsYXkTQnJvYWRjYXN0SW5wdXRCZWdhbgpJbnB1dEJlZ2FuB0Rlc3Ryb3kFZGVsYXkTQnJvYWRjYXN0SW5wdXRFbmRlZApGaXJlU2VydmVyB1VuZXF1aXAEZ2FtZQpSdW5TZXJ2aWNlCkdldFNlcnZpY2URUmVwbGljYXRlZFN0b3JhZ2UHcmVxdWlyZQNTdGQFQXVkaW8HUjE1SUt2MgZNb2R1bGUGU3ByaW5nD1J4SW5zdGFuY2VVdGlscxJJbnZlbnRvcnlJdGVtVXRpbHMJSW52ZW50b3J5ClRhYmxlVXRpbHMNQ3VycmVudENhbWVyYQZzY3JpcHQDR3VuCUNhclR1cnJldAtfX0NsYXNzTmFtZQdfX2luZGV4BlJlbG9hZAlBcHBseVNraW4KU2NvcGVCZWdpbgAaBwAAAAAHAAABCAETAhakBAQAAAwggJ8EAQJbAwQBeAIDAKQFBAAADCCAnwUBAlsEBQF4AwQApAYEAAAMIICfBgECWwUGAXgEBQBMNgACpAEHAAAYUICfAQQCTQABBwgAAACCAAIACQIAAAAAAADwPwIAAAAAAAAAQAMBAwIEAAwggAMDAwQEABhQgAMFAA8GARgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAACAQEAAAAE+wEAADAAATQAAAAAggABAAEDBwAwAAEYAAAAATEAAAAACAICAAAAGfsCAAAwAAI7AAAAACsAAQCCAAEA+wIAALwCAqQBAAAAnwICAfsDAABNAgO7AgAAAA4CCwD7BQEATQQF6gMAAABSBQAAbwYEANkHAAASAgAAnwQEALwCAf0FAAAAnwIAAYIAAQAGAwgDCQMKAwsDDAMNAQElAAEYAAAAAQECAAAAAQAAAAIAAAEBAQD9/wAACiYAAAAACAICAAAADysAAQCCAAEA+wUAAE0EBUgAAAAAUgUAAG8GAQDZBwAAEgIBABICAACfBAQAvAIB/QIAAACfAgABggABAAMDDgMPAw0BAiAAARgAAQMAAAAAAAAAAP8AABQhAAAAAAoDAwAAAC77BAAATQME7wAAAABSBAAAUgUBAJ8DAwL7BgEAnj0DBAYAAABSBQMApAQCAAAAEECfBAMBTQQDdgMAAAD7BwIATQYH6gQAAABSBwEAbwgFANkJAAASAgIAEgADAJ8GBAC8BAT9BgAAAJ8EAAHiBAoAqQUAADAFBDUHAAAAjAVkADAFBBMIAAAAjAX0ATAFBO0JAAAAMAQDcgsAAAC8BAOZDAAAAJ8EAgG8BAO+DQAAAJ8EAgGCAwIADgMEAxAEAAAQQAMRAwsDEgMNAxMDFAMVBQMHCAkDFgMXAxgBAxcEARgAAAAAAAABAAAAAAAAAgABAAABAQEAAP3/AAAgAQAAAQAAAQAA/QAGAAABAAACGQAAAAAEAQAAAAAFbwMAALwBAP4BAAAAnwEDAIIBAAACAxkDGgBTAAEYAAAAAABUAAAAAAYBAQAAAB1NAQA7AAAAACsBAQCCAAEATQEAOwAAAABvAwAAvAEBAwEAAACfAQMCKwEBAIIAAQBvBAIAvAIBAwEAAACfAgMCKwIBAIIAAQD7BAAATQME+wMAAAC8BAJoBAAAAJ8EAgLABQUAnwMDAjADAJcGAAAAggABAAcDCAMbAxwDHQMeBgUDHwEFRwkBGAAAAAECAAAAAAABAQIAAAABAQIAAAAAAAAAAAADSAAAAAAGAQAAAAAY/wEAAAMAAABNAgBpAAAAAE0DADsBAAAApAUEAAAAMEBNBAU4AgAAAMUBAgQBAAAAMAEAygUAAABNAQBnBgAAAA4BBgBNAQBnBgAAAE0CAMoFAAAAMAIBygUAAACCAAEABwMgAwgDIQMiBAAAMEADIwMkAFclARgAAAAAAAAAAAAAAAAAAAEAAAEAAAAAAAJYAAAAAAIAAQAAAAX7AAAAvAAAzwAAAACfAAIBggABAAEDJgB4AAEYAAAAAAF5AAAAAAIAAQAAAAX7AAAAvAAA2QAAAACfAAIBggABAAEDJwB7AAEYAAAAAAF8AAAAAAYBAgAAAGq8AQD0AAAAAJ8BAgGMAQAAMAEAIQEAAACMAQAAMAEAigIAAAD7AgAATQEC7wMAAABMNgACpAIFAAAMQICfAgECTDYAAqQDBQAADECAnwMBAm8EBgCMBR4AnwEFAjABAD8HAAAATQEAuwgAAAAOARAA+wIAAE0BAu8DAAAATDYAAqQCBQAADECAnwIBAkw2AAKkAwUAAAxAgJ8DAQJvBAkAjAUsAZ8BBQIwAQC1CgAAAPsCAABNAQLvAwAAAIwCAACMAwAAbwQJAIwFBwCfAQUCMAEASAsAAACMAQAAMAEArAwAAACpAQAAMAEAzQ0AAABNAQCXDgAAACsBBAD/AQAAAAAAADABAJcOAAAAjAEBADABAK4PAAAAvAEAShAAAACfAQIBvAEA/REAAACfAQIBvAEAlRIAAACfAQIBTQEAdhMAAAD7BAEATQMEzxQAAADZBQAAEgAAALwDA8cVAAAAnwMDALwBAf0WAAAAnwEAAU0BAHYTAAAA+wQBAE0DBNkXAAAA2QUBABIAAAC8AwPHFQAAAJ8DAwC8AQH9FgAAAJ8BAAGCAAEAGAMlAygDKQMEAwMEAAxAgALNzMzMzMzsPwMqAwoCMzMzMzMz4z8DKwMsAy0DLgMfAy8DMAMxAzIDEQMmAzMDDQMnAggJXRcBGAAAAAIAAAEAAAIAAAAAAAAAAAAAAAAAAAACAAABAAAAAAAAAAAAAAAAAAEAAwAAAAAAAAAAAAEAAAEAAAIAAAEAAAACAAABAAACAAACAAACAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAANeAAAAAAUBAQEAABOjAQAApAEBAAAAAECfAQECTQMAigIAAAAmAgEDbwMDAGADCQACAAAAMAEAigIAAAD7AwAATQIDcgQAAABSAwAA3QQAAJ8CAAGCAAEABQM0BAAAAEADKQKamZmZmZm5PwM1AH81ARgAAwAAAQAAAAAAAQABAAAAAAACfwAAAAAFAgAAAAAHTQIAPwAAAABSBAEAvAIClwEAAACfAgMAggIAAAIDKgM2AIkBNwEYAAAAAAAAAIoAAAAAAQEAAAAAAYIAAQAAAIwBOAEYAIwAAAAACAEBAAAAFk0BALUAAAAAvAEBJgEAAACfAQIC+wIAAE0DAoUCAAAApAQEAAAMIIBNBgGZBgAAAFsFBgVNBwGYBwAAAFsGBwWMBwAAnwQEAgkDAwQwAwKFAgAAAIIAAQAIAysDOQM6AwQEAAwggAIAAAAAAAAQQAM7AzwAjQE9ARgAAAAAAAEAAAAAAAAAAAAAAAAAAAABjgAAAAADAQAAAAAKvAEAlQAAAACfAQIBTQEAuwEAAAAOAQMAvAEAcQIAAACfAQIBggABAAMDMgMKAz0AkQEmARgAAAABAAABAAACkgAAAAAOAQEAAAcAAAEICFUCXbwBAPQAAAAAnwECAU0CAJcBAAAATQMArgIAAACHAQIDKwEEALwCAKQDAAAAnwICAYIAAQAwAQCxBAAAAE0CAGcFAAAATQQB4AYAAABNBgHrBwAAAE0FBmgIAAAATQcA2QkAAABNBgelCgAAALwCAlYLAAAAnwIFAU0EAK4CAAAATQYAlwEAAAAcBQYAzwMEBZUCAwwwAgCuAgAAAE0CALsNAAAADgIyAE0GADsOAAAATQUGmw8AAABNBAU7EAAAAPsHAABNBgeFEQAAAE0FBpESAAAAJgMEBU0CA6oTAAAA2AQUAm8FFQCMBgEATC4AAqQDGAAAXGCBnwMEAlICAwBNAwC1GQAAAKQLHQAAcGCBnwsBAlsKCxt4CQoMpAwdAABwYIGfDAECWwsMG3gKCwykDR0AAHBggZ8NAQJbDA0beAsMDEw2AAKkCCAAAHzggZ8IBAJNBwgHIQAAAAkGBwJbBQYavAMDnSIAAACfAwMBggABACMDJQMfAy8DCQM+AyQDPwNAA0EDQgNDA0QCAAAAAAAA8D8DCgMIA0UDRgM6A0cDSAIAAAAAAAA0QAKamZmZmZm5PwMBA0kEAFxggQMrAgAAAAAAAElAAgAAAAAAAABAAwIEAHBggQMDAwQEAHzggQMFA0oAlwFLARiIAAACAAAAAAEBAAABAwABAAAAAAAAAAAAAAAAAAABAAAAAAAAAAACAAABAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQBpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJcAAAIQAAAAAAIBAAAAAAKpAQEAggECAAAAqgFMARgAAKsAAAAADAMAAAAAek0DADsAAAAAKwMBAIIAAQCkAwIAAAAQQJ8DAQJNBABuAwAAAA4EBQBNBABuAwAAAFsFAgQwBQRLBQAAAE0FANkGAAAATQQFBwcAAABNBQA7AAAAAG8HCAC8BQUSCQAAAJ8FAwJvBgoAfQYiAAIAAABgBSAABAAAAE0HACELAAAAJgYDB4wJCgCMCx4ACQoLAkMICQrYBwwIYAceAAYAAABDBQUBfQQKAAUAAACVBQUN4ggPAKQJEgAROADBMAkIwg4AAAC8BgCvEwAAAJ8GAwEwAwAhCwAAAE0GALsUAAAADgYMALwGACYVAAAAnwYCAWUACACMBgAAYAYCAAUAAAAmBQUBjAYAAGAFAgAGAAAAjAUAAIwJAAA0LgUFCQQAAFIIBQBSCgQApAcYAABcYIGfBwQC7AYHBE0HADsAAAAAbwkAALwHBwMZAAAAnwcDAg4HHQBNCAA7AAAAAE0HCDsAAAAAbwkaALwHBwMZAAAAnwcDAg4HFABNCQA7AAAAAE0ICTsAAAAATQcIshoAAABNCQDZBgAAAE0ICeUbAAAATQsA2QYAAABNCgtQHAAAAFILBgC8CAhfHQAAAJ8IBAIwCAekHgAAAE0GADsAAAAAbwgIAFIJBQC8BgYuHwAAAJ8GBAGCAAEAIAMIAzQEAAAQQANNAgAAAAAAAOA/A04DQgNPA1ADUQIzMzMzMzPjPwMoAgAAAAAAAPA/AgAAAAAAAAhAA1IFAQ4DUwNUBBE4AMEDVQMKA1YDAQNJBABcYIEDGwNXA1gDWQNaA1sDXACtAV0BGAAAAAECAAACAAABAAAAAAIAAAABAAAAAAABAAAAAAEAAAAAAAAAAAABAQABAgAAAAAAAAADAAIAAAEAAAAEAAABAgAAAQQAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAABrgAAAAAKAQAAAAAiTQEAOwAAAAArAQEAggABAKQBAgAAABBAnwEBAk0DAAQDAAAAygIDASYDAQIwAQAEAwAAAE0EAEgEAAAAvAQEJgUAAACfBAICTQYArAYAAAAJBwMEQwUGB28GBwBgBgIABQAAAHgFBQcwBQCsBgAAAFIIAwBSCQQAvAYAwAgAAACfBgQBggABAAkDCAM0BAAAEEADXgMsAzkDLQIYLURU+yEZQANdANkBJwEYAAAAAQMAAAEAAAEBAAIAAAAAAQAAAAEAAAECAAIAAAAAAdoAAAAAAQEAAAAAAYIAAQAAAO4BXwEYAO4AAAAACAMAAAAAUg4CAgCpAwAAggMCAKkDAQBNBAHCAAAAAKQFAwACABDA8QQQAAUAAACpAwAATQQBwgAAAACkBQUABAAQwJoECQAFAAAATQQBswYAAACkBQgABxgQwPEEAgAFAAAAqQMAAakDAQAOAzcATQQAOwkAAABvBgoAvAQEEgsAAACfBAMCTQYA2QwAAABNBQYHDQAAAGAEJQAFAAAATQUASA4AAACMBwEAvAUFlw8AAACfBQMBqQUBADAFAM0QAAAATQUAbhEAAAArBRgApAUUAABMIIFvBhEAnwUCAm8GFQAwBgV8FgAAAIwGAAAwBgVLFwAAAKkGAQAwBgW1GAAAAE0HADsJAAAATQYHmxkAAAAwBgUkGgAAALwGBe4bAAAAnwYCATAFAG4RAAAATQUAuxwAAAAOBQQAUgcBALwFAAodAAAAnwUDAYIAAQAeA1IDUwNUBAIAEMADYAQEABDAA2EDYgQHGBDAAwgDUANRA0IDTwMsAzYDLgNNA2MDBAQATCCBA2QDZQNOA2YDRQNnA2gDCgNpAO8BagEYAAEAAwAAAAAAAAEAAAAAAAAAAAAAAAAAAAIBAAAAAAABAAAAAAABAAAAAAABAAABAAABAAAAAQAAAQAAAQAAAQAAAAAAAQAAAQADAAABAAAAA/AAAAAAAgABAAAAE/sBAABNAAFuAAAAAA4ADgD7AQAATQABzQEAAAArAAoA+wEAAE0AAW4AAAAAvAAAUAIAAACfAAIB+wAAAMYBAAAwAQBuAAAAAIIAAQADA00DLgNrAJYCAAEYAAAAAAAAAAABAAAAAAABAAAAAhcBAAAABwMAAAAAMQ4CAgCpAwAAggMCAKkDAQBNBAHCAAAAAKQFAwACABDA8QQQAAUAAACpAwAATQQBwgAAAACkBQUABAAQwJoECQAFAAAATQQBswYAAACkBQgABxgQwPEEAgAFAAAAqQMAAakDAQAOAxYATQQASAkAAACMBgAAvAQElwoAAACfBAMBqQQAADAEAM0LAAAApAQNAAAAwEBvBQ4A2QYAABIAAACfBAMBTQQAuw8AAAAOBAQAUgYBALwEALkQAAAAnwQDAYIAAQARA1IDUwNUBAIAEMADYAQEABDAA2EDYgQHGBDAAywDNgMuA2wEAADAQAIAAAAAAADgPwMKA20BFosCVQEYAAEAAwAAAAAAAAEAAAAAAAAAAAAAAAAAAAIBAAAAAAABAAABAAAAAAAGAAABAAAAAwwBAAAABgEAAAAAOU0BALsAAAAADgEOAE0BADQBAAAADgELAE0BADQBAAAATQMAOwIAAABvBQMAvAMDEgQAAACfAwMAvAEBawUAAACfAQABTQEAOwIAAABvAwIAvAEBAwYAAACfAQMCDgEVAE0CADsCAAAATQECOwIAAABvAwcAvAEBAwYAAACfAQMCDgEMAE0DADsCAAAATQIDOwIAAABNAQKyBwAAAE0DANkIAAAATQID5QkAAAAwAgGkCgAAAE0BAG4LAAAADgEIAE0BAG4LAAAAvAEBUAwAAACfAQIBxgEAADABAG4LAAAAggABAA0DCgMHAwgDUANRA24DGwNXA0IDWANbA00DawChAm8BGAAAAAEAAAEAAAAAAAAAAAAAAwAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAAAAAMAAAEAAAAAAQAAAiIBAAAAEAAAAQIAmQGjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIGAAAAUEBNBAGhBwAAAE0DBNIIAAAAnwICAqQDBgAAAFBATQUBQAoAAABNBAVKCQAAAJ8DAgKkBAYAAABQQE0GAaEHAAAATQUGIgsAAACfBAICpAUGAAAAUEBNBwGhBwAAAE0GB1IMAAAAnwUCAqQGBgAAAFBATQgBYA4AAABNBwh3DQAAAJ8GAgKkBwYAAABQQE0JAaEHAAAATQgJGA8AAACfBwICpAkRAAAAAEFNCAlIEgAAAKQKFAAAADBBTQkKJBUAAACkCgYAAABQQE0LCQ0WAAAAnwoCAsALFwD/DAYAAAAAAG8NGAAwDQzlGQAAADAMDG4aAAAAnj0MBQoAAABSDgwAUg8KAKQNHAAAALBBnw0DAcANHQASAAoAEgAMABIABQAwDQzvHgAAAMANHwASAAcAMA0MpCAAAADADSEAMA0M9CIAAADADSMAEgAEABIAAAAwDQyZJAAAAMANJQASAAoAMA0MciYAAACpDQAAMA0MNycAAADADSgAMA0MgSkAAADADSoAMA0MYysAAADADSwAEgAIADANDHEtAAAAwA0uADANDM8vAAAAwA0wABIACAAwDQzoMQAAAMANMgAwDQypMwAAAMANNAAwDQzANQAAAMANNgAwDQzZNwAAAKkNAAAwDQzpOAAAAKkNAAAwDQwkOQAAAMANOgAwDQz9OwAAAMANPAAwDQyCPQAAAMANPgAwDQyvPwAAAMANQAAwDQy4QQAAAIIMAgBCA3AEAAAAQANxA3IDcwN0BAAAUEADdQN2A3cDeAN5A3oDewN8A30DIgQAAABBA34DfwQAADBBA2cDgAEGAAOBAQOCAQODAQMQBAAAsEEGBAMEBgYDCQYHAyUGCgMXBgsDNQOEAQYMAzcGDQM4Bg4DPQYPAyYGEANLBhEDTAYSA10GEwMnA4UBA4YBBhQDXwYVA2oGFwNVBhgDbxIABAYHCgsMDQ4PEBESExQVFxgBAAEHAAEAAAAAAAEAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAACAAAAAQAAAAACBAABAAABAAEAAAAAAAABAAAAAAAwAAAAEAAABgAAAAAiAAAACQAAAQAAAwAAAQAAAAQAAAYAAAATAABXAAAsAAATAAABAAABAAABAAAcAAAWAAARAQAAAKwAAAAAGUJgR5eN3JQhcKQtA68vArOngcKahUZlZig/dty5J3/58s4C0kzMcO0=

-- Decompiled by Krnl

local v_u_1 = game:GetService("RunService")
local v2 = game:GetService("ReplicatedStorage")
require(v2.Std.Audio)
require(v2.Module.R15IKv2)
local v_u_3 = require(v2.Std.Spring)
local v_u_4 = require(v2.Std.RxInstanceUtils)
require(v2.Inventory.InventoryItemUtils)
local v_u_5 = require(v2.Std.TableUtils)
local v_u_6 = workspace.CurrentCamera
local v7 = script.Parent
local v_u_8 = require(v7.Gun)
local v_u_9 = {
	["__ClassName"] = "CarTurret"
}
v_u_9.__index = v_u_9
setmetatable(v_u_9, v_u_8)
function v_u_9.new(p10, p11, _)
	-- upvalues: (copy) v_u_8, (copy) v_u_9, (copy) v_u_4
	local v_u_12 = v_u_8.new(p10, p11)
	local v13 = v_u_9
	setmetatable(v_u_12, v13)
	v_u_12.Maid:GiveTask(v_u_4.observeOneChildNamed(p11, "VehicleModel", function(p14, p15)
		-- upvalues: (ref) v_u_4, (copy) v_u_12
		if p14 then
			p15:GiveTask(v_u_4.observeProperty(p14, "Value", function(p16, p17)
				-- upvalues: (ref) v_u_12, (ref) v_u_4
				v_u_12.Model = p16
				if p16 then
					v_u_12:_getTips()
					if v_u_12.Local then
						p17:GiveTask(v_u_4.observeOneChildNamed(p16, "UpdateHeatRemote", function(p18)
							-- upvalues: (ref) v_u_12
							v_u_12._updateHeatRemote = p18
						end))
					end
				end
			end))
		end
	end))
	v_u_12.ShootActionButtonConfig = {
		["primary"] = false,
		["saturateTo"] = 100,
		["priority"] = 500
	}
	v_u_12:Setup()
	v_u_12:DefaultDisableCamLock()
	return v_u_12
end
function v_u_9._getTips(p19)
	-- upvalues: (copy) v_u_5
	if p19.Model then
		local v20 = p19.Model:FindFirstChild("Model")
		if v20 then
			local v21 = v20:FindFirstChild("TurretTips")
			if v21 then
				p19.Tips = v_u_5.filter(v21:GetChildren(), function(p22)
					return p22:IsA("Attachment")
				end)
			end
		else
			return
		end
	else
		return
	end
end
function v_u_9._updateIgnoreList(p23)
	p23.IgnoreList = { p23.Character, p23.Model, workspace.Items }
	if p23.BulletEmitter then
		p23.BulletEmitter.IgnoreList = p23.IgnoreList
	end
end
function v_u_9.Setup(p_u_24)
	-- upvalues: (copy) v_u_3, (copy) v_u_1
	p_u_24:_updateIgnoreList()
	p_u_24.LastShoot = 0
	p_u_24.LastPlayerImpact = 0
	p_u_24.SpringThirdMousePosition = v_u_3.new(Vector3.new(), Vector3.new(), 0.9, 30)
	if p_u_24.Local then
		p_u_24.SpringCamera = v_u_3.new(Vector3.new(), Vector3.new(), 0.6, 300)
	end
	p_u_24.SpringSpin = v_u_3.new(0, 0, 0.6, 7)
	p_u_24.SpinTotal = 0
	p_u_24.MouseDown = false
	if not p_u_24.Tips then
		p_u_24.Tips = {}
	end
	p_u_24.TipIndex = 1
	p_u_24:SetupBulletEmitter()
	p_u_24:SetupShoot()
	p_u_24:UpdateMousePosition()
	p_u_24.Maid:GiveTask(v_u_1.RenderStepped:Connect(function()
		-- upvalues: (copy) p_u_24
		p_u_24:RenderStepped()
	end))
	p_u_24.Maid:GiveTask(v_u_1.Stepped:Connect(function()
		-- upvalues: (copy) p_u_24
		p_u_24:Stepped()
	end))
end
function v_u_9.BulletEmitterOnLocalHitPlayer(p25, ...)
	-- upvalues: (copy) v_u_8
	local v26 = tick()
	if v26 - p25.LastPlayerImpact > 0.1 then
		p25.LastPlayerImpact = v26
		v_u_8.BulletEmitterOnLocalHitPlayer(p25, ...)
	end
end
v_u_9.Reload = false
function v_u_9.TransformLocalMousePosition(p27, p28)
	return p27.SpringThirdMousePosition:SetTarget(p28)
end
function v_u_9.UpdateArmJoints(_) end
function v_u_9.UpdateCamera(p29)
	-- upvalues: (copy) v_u_6
	local v30 = p29.SpringCamera:Update()
	local v31 = v_u_6
	v31.CFrame = v31.CFrame * CFrame.new(v30.x * 4, v30.y * 4, 0)
end
function v_u_9.RenderStepped(p32)
	p32:UpdateMousePosition()
	if p32.Local then
		p32:UpdateCamera()
	end
end
function v_u_9.Shoot(p33)
	-- upvalues: (copy) v_u_6
	p33:_updateIgnoreList()
	local v34 = p33.Tips[p33.TipIndex]
	if v34 then
		p33.Tip = v34
		p33.BulletEmitter:Emit(v34.WorldPosition, v34.WorldCFrame.LookVector, p33.Config.BulletSpeed)
		p33.TipIndex = p33.TipIndex % #p33.Tips + 1
		if p33.Local then
			local v35 = 20 / (p33.Model.PrimaryPart.Position - v_u_6.CFrame.p).Magnitude
			local v36 = math.clamp(v35, 0.1, 1)
			local v37 = p33.SpringCamera
			local v38 = math.random() * 2 - 1
			local v39 = math.random() * 2 - 1
			local v40 = math.random() * 2 - 1
			v37:Accelerate(Vector3.new(v38, v39, v40).Unit * v36 * 50)
		end
	else
		p33:_getTips()
	end
end
function v_u_9.ShootCheckConditions(_)
	return true
end
function v_u_9.AnimateBarrel(p41, p42, p43)
	if p41.Model then
		local v44 = tick()
		if p41.Sound then
			p41.Sound.Volume = p43 * 0.5
		end
		local v45 = p41.Config.MaxHeat
		local v46 = p41.Model:GetAttribute("Heat")
		if p43 >= 0.6 and v46 < v45 then
			if v44 - p41.LastShoot > 1 / (10 + 30 * p43) then
				v46 = v46 + p42
				if v45 <= v46 then
					v46 = v46 + 3
					p41:InputEnded({
						["UserInputType"] = Enum.UserInputType.MouseButton1
					})
				end
				p41.LastShoot = v44
				if p41.Local then
					p41:_attemptShoot()
				end
			end
		else
			if v46 > 0 then
				v46 = v46 - p42
			end
			v46 = v46 < 0 and 0 or v46
		end
		local v47 = math.clamp(v46, 0, v45) / v45
		if p41.Model:FindFirstChild("Model") and p41.Model.Model:FindFirstChild("Turret") then
			p41.Model.Model.Turret.Color = p41.Config.ColorNormal:Lerp(p41.Config.ColorHeat, v47)
		end
		p41.Model:SetAttribute("Heat", v46)
	end
end
function v_u_9.Stepped(p48)
	if p48.Model then
		local v49 = tick()
		local v50 = v49 - (p48.LastUpdate or v49)
		p48.LastUpdate = v49
		local v51 = p48.SpringSpin:Update()
		local v52 = p48.SpinTotal + v50 * v51
		if v52 > 6.283185307179586 then
			v52 = v52 - 6.283185307179586
		end
		p48.SpinTotal = v52
		p48:AnimateBarrel(v50, v51)
	end
end
v_u_9.ApplySkin = false
v_u_9.ScopeBegin = false
function v_u_9.Heartbeat(_) end
function v_u_9.InputBegan(p53, p54, p55)
	if p55 then
		return false
	end
	local v56
	if p54.UserInputType == Enum.UserInputType.MouseButton1 then
		v56 = true
	elseif p54.UserInputType == Enum.UserInputType.Gamepad1 then
		v56 = p54.KeyCode == Enum.KeyCode.ButtonX
	else
		v56 = false
	end
	if v56 then
		if p53.Model:GetAttribute("Heat") < p53.Config.MaxHeat then
			p53.SpringSpin:SetTarget(1)
			p53.MouseDown = true
			if not p53.Sound then
				local v57 = Instance.new("Sound")
				v57.SoundId = "rbxassetid://2198390391"
				v57.Volume = 0
				v57.Looped = true
				v57.Parent = p53.Model.PrimaryPart
				v57:Play()
				p53.Sound = v57
			end
		end
		if p53.Local then
			p53:BroadcastInputBegan(p54)
		end
	end
end
function v_u_9.InputEnded(p_u_58, p59, p60)
	if p60 then
		return false
	end
	local v61
	if p59.UserInputType == Enum.UserInputType.MouseButton1 then
		v61 = true
	elseif p59.UserInputType == Enum.UserInputType.Gamepad1 then
		v61 = p59.KeyCode == Enum.KeyCode.ButtonX
	else
		v61 = false
	end
	if v61 then
		p_u_58.SpringSpin:SetTarget(0)
		p_u_58.MouseDown = false
		delay(0.5, function()
			-- upvalues: (copy) p_u_58
			if p_u_58.Sound and not p_u_58.MouseDown then
				p_u_58.Sound:Destroy()
				p_u_58.Sound = nil
			end
		end)
		if p_u_58.Local then
			p_u_58:BroadcastInputEnded(p59)
		end
	end
end
function v_u_9.Unequip(p62)
	if p62.Local and p62._updateHeatRemote then
		p62._updateHeatRemote:FireServer(p62.Model:GetAttribute("Heat"))
	end
	if p62.Model:FindFirstChild("Model") and p62.Model.Model:FindFirstChild("Turret") then
		p62.Model.Model.Turret.Color = p62.Config.ColorNormal
	end
	if p62.Sound then
		p62.Sound:Destroy()
		p62.Sound = nil
	end
end
return v_u_9
