-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMhD29uUmVxdWVzdFByb21wdARGaXJlA25ldwxzZXRtZXRhdGFibGUVRGVmYXVsdERpc2FibGVDYW1Mb2NrBUxvY2FsBE1haWQIR2l2ZVRhc2sSR2V0TGVmdEFybVBvc2l0aW9uCklucHV0QmVnYW4KSW5wdXRFbmRlZARnYW1lEVJlcGxpY2F0ZWRTdG9yYWdlCkdldFNlcnZpY2UHcmVxdWlyZQRDQ1RWC0NDVFZTZXJ2aWNlBnNjcmlwdAZQYXJlbnQFQmFzaWMDSGlwElJpZ2h0V3Jpc3RSb3RhdGlvbhFMZWZ0V3Jpc3RSb3RhdGlvbgdTcHJpbmdzCkl0ZW1PZmZzZXQMSXRlbVJvdGF0aW9uDE5lY2tSb3RhdGlvbg1XYWlzdFJvdGF0aW9uB1ZlY3RvcjMGQ0ZyYW1lBk1vdGlvbgtfX0NsYXNzTmFtZQdfX2luZGV4AAYDAAEAAAAI+wEAAE0AAYwAAAAAqQIAALwAAN0BAAAAnwADAYIAAQACAwEDAgAiAAEYAAAAAAAAAAEjAAAAAAgDBAAAACX7BAAATQME7wAAAABSBAAAUgUBAPsGAQBSBwIAnwMFAvsGAgCePQMEBgAAAFIFAwCkBAIAAAAQQJ8EAwG8BAO+AwAAAJ8EAgFNBAO7BAAAAA4EDwD7BQMATQQFjAUAAACpBgEAqQcBALwEBN0GAAAAnwQEAU0EA3YHAAAAwAYIABICAwC8BAT9CQAAAJ8EAwGCAwIACgMDAwQEAAAQQAMFAwYDAQMCAwcGAAMIAQAaAwEYAAAAAAAAAAABAAAAAAAAAgAAAgAAAQAAAAAAAAABAAAAAAAABRsAAAAAAgEAAAAAAsYBAACCAQIAAAApCQEYAAAqAAAAAAcDAQAAAAj7BAAATQMEggAAAABSBAAAUgUBAFIGAgCfAwQBggABAAEDCgAsCgEYAAAAAAAAAAEtAAAAAAEBAAAAAAGCAAEAAAAvCwEYAC8AAAAACQAAAQIAYaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DAI8GAAAATQIDdwcAAACfAQICpAMJAAAAgEBNAgMkCgAAAKQDBQAAAEBATQQCywsAAACfAwIC/wQBAAAAAADiBQ8A4gYRAOIHFgBvCBcAMAgHgBIAAABMNgACpAgaAABkgIGfCAECMAgH5RMAAABMNgACpAgaAABkgIGfCAECMAgHjRQAAABMNgACpAgaAABkgIGfCAECMAgHXxUAAAAwBwaYEAAAADAGBb0MAAAApAYcAABksIGfBgECMAYFDg0AAACkBhwAAGSwgZ8GAQIwBgWFDgAAADAFBJcdAAAA/wUEAAAAAABvBgYAMAYF5R4AAAAwBQVuHwAAAJ49BQUDAAAAUgcFAFIIAwCkBiEAAAAAQp8GAwHABiIAEgADABIABAASAAUAEgABADAGBe8ZAAAAwAYjADAGBZMkAAAAwAYlABIAAwAwBgWCJgAAAMAGJwAwBgWvKAAAAIIFAgApAwwEAAAAQAMNAw4DDwQAAEBAAxADEQMSBAAAgEADEwMUAxUDFgMXBQMMDQ4DGAUBEAMZAxoDGwMcBQQSExQVB2ZmZj+amRk/AADAvwAAAAADHQMDBABkgIEDHgQAZLCBAx8DIAMhAwQEAAAAQgYBBgIDCQYDAwoGBAMLBAECAwQBAAEYAAEAAAAAAAEAAAAAAAABAAAAAQAAAAACAAEBAQEAAAEAAAAAAAEAAAAAAAEAAAAAAPwA/wAJAAAAAAEAAAAA9QAOAAEAAAEAAQAAAAAAAAEAAAAAAAAPAAADAAAAAwAAAgEAAAAABbRXofVYinx3hpPLYfRkfCFLUC6CRnemaSoR8WgxOQHqzAcooeYrCLE=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.CCTV.CCTVService)
local v3 = script.Parent
local v_u_4 = require(v3.Basic)
local v_u_5 = {}
local v6 = {}
local v7 = {
	["Springs"] = {
		["ItemOffset"] = Vector3.new(0.9, 0.6, -1.5),
		["ItemRotation"] = Vector3.new(),
		["NeckRotation"] = Vector3.new(),
		["WaistRotation"] = Vector3.new()
	}
}
v6.Hip = v7
v6.RightWristRotation = CFrame.new()
v6.LeftWristRotation = CFrame.new()
v_u_5.Motion = v6
local v_u_8 = {
	["__ClassName"] = "CCTV"
}
v_u_8.__index = v_u_8
setmetatable(v_u_8, v_u_4)
function v_u_8.new(p9, p10, p11)
	-- upvalues: (copy) v_u_4, (copy) v_u_5, (copy) v_u_8, (copy) v_u_2
	local v12 = v_u_4.new(p9, p10, v_u_5, p11)
	local v13 = v_u_8
	setmetatable(v12, v13)
	v12:DefaultDisableCamLock()
	if v12.Local then
		v_u_2.onRequestPrompt:Fire(true, true)
		v12.Maid:GiveTask(function()
			-- upvalues: (ref) v_u_2
			v_u_2.onRequestPrompt:Fire(false)
		end)
	end
	return v12
end
function v_u_8.GetLeftArmPosition(_)
	return nil
end
function v_u_8.InputBegan(p14, p15, p16)
	-- upvalues: (copy) v_u_4
	v_u_4.InputBegan(p14, p15, p16)
end
function v_u_8.InputEnded(_) end
return v_u_8
