-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMrA25ldwxzZXRtZXRhdGFibGUHRW5hYmxlZBBTcHJpbmdJdGVtT2Zmc2V0CVNldFRhcmdldBJHZXRMZWZ0QXJtUG9zaXRpb24FTW9kZWwFTGlnaHQERW51bQhNYXRlcmlhbAROZW9uB1BsYXN0aWMOR2V0RGVzY2VuZGFudHMJU3BvdExpZ2h0A0lzQQZUb2dnbGUNVXNlcklucHV0VHlwZQxNb3VzZUJ1dHRvbjEIR2FtZXBhZDEHS2V5Q29kZQhCdXR0b25SMgVMb2NhbBNCcm9hZGNhc3RJbnB1dEJlZ2FuCklucHV0QmVnYW4KSW5wdXRFbmRlZAZzY3JpcHQGUGFyZW50B3JlcXVpcmUFQmFzaWMDSGlwElJpZ2h0V3Jpc3RSb3RhdGlvbhFMZWZ0V3Jpc3RSb3RhdGlvbgdTcHJpbmdzCkl0ZW1PZmZzZXQMSXRlbVJvdGF0aW9uDE5lY2tSb3RhdGlvbg1XYWlzdFJvdGF0aW9uB1ZlY3RvcjMGQ0ZyYW1lBk1vdGlvbgpGbGFzaGxpZ2h0C19fQ2xhc3NOYW1lB19faW5kZXgABggDAwAAABn7BAAATQME7wAAAABSBAAAUgUBAPsGAQBSBwIAnwMFAvsGAgCePQMEBgAAAFIFAwCkBAIAAAAQQJ8EAwGpBAAAMAQD8AMAAABNBAMdBAAAAG8GBQC8BASXBgAAAJ8EAwGCAwIABwMBAwIEAAAQQAMDAwQHAACAP5qZGT8AAMC/AAAAAAMFABgBARgAAAAAAAAAAAEAAAAAAAACAAABAAAAAAACGQAAAAACAQAAAAACxgEAAIIBAgAAACEGARgAACIAAAAACgEAAAAAJ00CAPAAAAAAVgECADABAPAAAAAATQEAOwEAAABNAwE7AQAAAE0CAw8CAAAATQQA8AAAAAAOBAMApAMGAAUQMMArAwIApAMIAAcQMMAwAwItBAAAAE0CATsBAAAAvAICRwkAAACfAgIEZAIJAG8JCgC8Bwb+CwAAAJ8HAwIOBwQATQcA8AAAAAAwBwbwAAAAAG4C9v8CAAAAggABAAwDAwMHAwgDCQMKAwsEBRAwwAMMBAcQMMADDQMOAw8AJBABGAAAAAAAAQABAAAAAAAAAAAAAAAAAAEAAAAAAAEAAAAAAQAAAP4ABSUAAAAACAMBAAAAKakDAQBNBAHCAAAAAKQFAwACABDA8QQQAAUAAACpAwAATQQBwgAAAACkBQUABAAQwJoECQAFAAAATQQBswYAAACkBQgABxgQwPEEAgAFAAAAqQMAAakDAQAOAwoAvAQArAkAAACfBAIBTQQAuwoAAAAOBAQAUgYBALwEAAoLAAAAnwQDAfsFAABNBAWCDAAAAFIFAABSBgEAUgcCAJ8EBAGCAAEADQMRAwkDEgQCABDAAxMEBAAQwAMUAxUEBxgQwAMQAxYDFwMYAC4YARgAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAgEAAAEAAAEAAAADAAAAAAAAATAAAAAAAQEAAAAAAYIAAQAAADsZARgAOwAAAAAHAAABAgBWowAAAKQBAQAAAABATQABJAIAAACkAQQAAAAwQE0CAMsFAAAAnwECAv8CAQAAAAAA4gMJAOIECwDiBRAAbwYRADAGBYAMAAAATDYAAqQGFAAATCCBnwYBAjAGBeUNAAAATDYAAqQGFAAATCCBnwYBAjAGBY0OAAAATDYAAqQGFAAATCCBnwYBAjAGBV8PAAAAMAUEmAoAAAAwBAO9BgAAAKQEFgAATFCBnwQBAjAEAw4HAAAApAQWAABMUIGfBAECMAQDhQgAAAAwAwKXFwAAAP8DBAAAAAAAbwQYADAEA+UZAAAAMAMDbhoAAACePQMFAQAAAFIFAwBSBgEApAQcAAAAsEGfBAMBwAQdABIAAQASAAIAEgADADAEA+8TAAAAwAQeADAEA5MfAAAAwAQgADAEA6whAAAAwAQiABIAAQAwBAOCIwAAAMAEJAAwBAOvJQAAAIIDAgAmAxoEAAAAQAMbAxwEAAAwQAMdAx4DHwMgBQMGBwgDIQUBCgMiAyMDJAMlBQQMDQ4PBzMzMz8AAAC/AAAAAAAAAAADJgMBBABMIIEDJwQATFCBAygDKQMqAysDAgQAALBBBgAGAQMGBgIDEAYDAxgGBAMZBQABAgMEAQABGAABAAAAAQAAAAACAAEBAQEAAAEAAAAAAAEAAAAAAAEAAAAAAPwA/wAJAAAAAAEAAAAA9QAOAAEAAAEAAQAAAAAAAAEAAAAAAAkAAAMAAAoAAAANAAACAQAAAAAF2PDYC66YE93qNLKf3NJo5euRahhbU2+5VXWfiDLZp9hnBbLYccRAIA==

-- Decompiled by Krnl

local v1 = script.Parent
local v_u_2 = require(v1.Basic)
local v_u_3 = {}
local v4 = {}
local v5 = {
	["Springs"] = {
		["ItemOffset"] = Vector3.new(0.7, -0.5, 0),
		["ItemRotation"] = Vector3.new(),
		["NeckRotation"] = Vector3.new(),
		["WaistRotation"] = Vector3.new()
	}
}
v4.Hip = v5
v4.RightWristRotation = CFrame.new()
v4.LeftWristRotation = CFrame.new()
v_u_3.Motion = v4
local v_u_6 = {
	["__ClassName"] = "Flashlight"
}
v_u_6.__index = v_u_6
setmetatable(v_u_6, v_u_2)
function v_u_6.new(p7, p8, p9)
	-- upvalues: (copy) v_u_2, (copy) v_u_3, (copy) v_u_6
	local v10 = v_u_2.new(p7, p8, v_u_3, p9)
	local v11 = v_u_6
	setmetatable(v10, v11)
	v10.Enabled = false
	v10.SpringItemOffset:SetTarget(Vector3.new(1, 0.6, -1.5))
	return v10
end
function v_u_6.GetLeftArmPosition(_)
	return nil
end
function v_u_6.Toggle(p12)
	p12.Enabled = not p12.Enabled
	local v13 = p12.Model
	v13.Model.Light.Material = p12.Enabled and Enum.Material.Neon or Enum.Material.Plastic
	for _, v14 in v13.Model:GetDescendants() do
		if v14:IsA("SpotLight") then
			v14.Enabled = p12.Enabled
		end
	end
end
function v_u_6.InputBegan(p15, p16, p17)
	-- upvalues: (copy) v_u_2
	local v18
	if p16.UserInputType == Enum.UserInputType.MouseButton1 then
		v18 = true
	elseif p16.UserInputType == Enum.UserInputType.Gamepad1 then
		v18 = p16.KeyCode == Enum.KeyCode.ButtonR2
	else
		v18 = false
	end
	if v18 then
		p15:Toggle()
		if p15.Local then
			p15:BroadcastInputBegan(p16)
		end
	end
	v_u_2.InputBegan(p15, p16, p17)
end
function v_u_6.InputEnded(_) end
return v_u_6
