-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgPBAQRtYXRoBnJhbmRvbQdWZWN0b3IzA25ldwRVbml0DFJhbmRvbVZlY3RvcgxFYXNlX091dEJhY2sORWFzZV9Jbk91dFF1YWQMc2V0bWV0YXRhYmxlBG1haWQORm9yY2VmaWVsZE1lc2gIUmVzb3VyY2UFQ2xvbmUEU2l6ZRJNZXNoUGFydEZvcmNlZmllbGQISW5zdGFuY2UEUGFydAhBbmNob3JlZApDYW5Db2xsaWRlBkNvbG9yMwdmcm9tUkdCBUNvbG9yDFRyYW5zcGFyZW5jeQRFbnVtCFBhcnRUeXBlBEJhbGwFU2hhcGUKVG9wU3VyZmFjZQ1Cb3R0b21TdXJmYWNlCVBhcnRTaGVsbAZSQURJVVMGUmFkaXVzBUxvY2FsAm9zBWNsb2NrA21pbgZVcGRhdGUGQ0ZyYW1lCkdldEVsYXBzZWQKRGlzY29ubmVjdApiYXNlODVVVUlECXdvcmtzcGFjZRBHZXRTZXJ2ZXJUaW1lTm93BEdyb3cBdwAJdTRnZHJvbGVoA3N1YgdyZXZlcnNlCXJpY3l0ZXE4cgJ6MQpGaXJlU2VydmVyEkhpdFRhcmdldFdpdGhTcGVlZAZQYXJlbnQdQ2FsY3VsYXRlTmV4dEluc3RhbnRDb2xsaXNpb24UZ2V0SXNQb3NpdGlvbkFsbG93ZWQJSGVhcnRiZWF0B0Nvbm5lY3QNQXR0ZW1wdExhdW5jaAhQb3NpdGlvbgZBbmdsZXMHU2V0U2l6ZQZTaHJpbmsLTG9jYWxQbGF5ZXIEZHJhdw9pc1ZlaGljbGVEYW1hZ2USZGlkUG9wVmVoaWNsZVRpcmVzEU1pblNoaWVsZER1cmF0aW9uBHRhc2sFZGVsYXkKc2hyaW5rVGFzaw9TVEFSVElOR19IRUFMVEgJVHdlZW5JbmZvC0Vhc2luZ1N0eWxlBkxpbmVhcg9FYXNpbmdEaXJlY3Rpb24CSW4GQ3JlYXRlFnRyYW5zcGFyZW5jeUhpdEZsaWNrZXIEUGxheQphZnRlclR3ZWVuCEdpdmVUYXNrA2FkZAdEZXN0cm95DEZvcmNlZmllbGRJZApGb3JjZWZpZWxkGUhFQUxUSF9VUERBVEVfUkVNT1RFX05BTUUORmluZEZpcnN0Q2hpbGQNT25DbGllbnRFdmVudBFNYXhTaGllbGREdXJhdGlvbgtPYmplY3RMb2NhbAZMb29wZWQLTWF4RGlzdGFuY2UGVm9sdW1lC2lzU2hyaW5raW5nCnJlbW92ZUJ5SWQGYXNzZXJ0CHdlbG9ydHoxBUV2ZW50AmVtBEluaXQHU3RlcHBlZA1SZW5kZXJTdGVwcGVkB2dldEF0dHISaW52ZW50b3J5SXRlbVZhbHVlEU5leHRTaG9vdFBvc3NpYmxlBkNlbnRlcgZDb25maWcJTGFzdFNob290B3NldEF0dHIMU3ByaW5nQ2FtZXJhD0J1aWxkUGFja2V0QXJtcwlDaGFyYWN0ZXICSUsKU2V0dXBNb2RlbBNBdHRhY2hNb2RlbFRvUGxheWVyBE1haWQGUmVsb2FkGVN0YXJ0UmVsb2FkUHJvZ3Jlc3NDaXJjbGUFZXZlcnkFTW9kZWwHZ2V0TmFtZQpJdGVtU3lzdGVtBk1vZGVscwVlcnJvciJDb3VsZCBub3QgZmluZCBtb2RlbCBmb3IgaXRlbSBgJXNgBmZvcm1hdAhTa2VsZXRvbglXZWxkQWxsVG8FTW90b3IKVXBwZXJUb3JzbwpCbGFua01vdG9yBUl0ZW1zAkMxAXAIUmlnaHRBcm0EQXJtcwlMZWZ0V3Jpc3QJVHJhbnNmb3JtClJpZ2h0V3Jpc3QMVG91Y2hFbmFibGVkDFZpZXdwb3J0U2l6ZRdNb2JpbGVNb3VzZUhlaWdodFNjYWxhcgFYAVkQR2V0TW91c2VMb2NhdGlvbgF4AXkSVmlld3BvcnRQb2ludFRvUmF5A1JheQZPcmlnaW4JRGlyZWN0aW9uG0ZpbmRQYXJ0T25SYXlXaXRoSWdub3JlTGlzdANUaXAKQWNjZWxlcmF0ZQpTaG9vdEJlZ2luDVVzZXJJbnB1dFR5cGUMTW91c2VCdXR0b24xCEdhbWVwYWQxB0tleUNvZGUIQnV0dG9uUjIKSW5wdXRCZWdhbgpJbnB1dEVuZGVkDUN1cnJlbnRDYW1lcmEEZ2FtZQdQbGF5ZXJzCkdldFNlcnZpY2UKUnVuU2VydmljZRBVc2VySW5wdXRTZXJ2aWNlEVJlcGxpY2F0ZWRTdG9yYWdlDFR3ZWVuU2VydmljZQdyZXF1aXJlEEZvcmNlZmllbGRDb25zdHMaU2ltdWxhdGVkUGh5c2ljc1Byb2plY3RpbGUGTW9kdWxlEUZvcmNlZmllbGRTZXJ2aWNlBEdhbWUNRGlzcGxheURhbWFnZQdSMTVJS3YyA1N0ZAVKb2ludAVBdWRpbwZTcHJpbmcSSW52ZW50b3J5SXRlbVV0aWxzCUludmVudG9yeQhJbnRlcnZhbAZTdHJpbmcGc2NyaXB0BEl0ZW0SRm9yY2VmaWVsZExhdW5jaGVyCkl0ZW1Db25maWcHX19pbmRleAtfX0NsYXNzTmFtZQAhBwAAAAAHAAABCAETAhakBAQAAAwggJ8EAQJbAwQBeAIDAKQFBAAADCCAnwUBAlsEBQF4AwQApAYEAAAMIICfBgECWwUGAXgEBQBMNgACpAEHAAAYUICfAQQCTQABBwgAAACCAAIACQIAAAAAAADwPwIAAAAAAAAAQAMBAwIEAAwggAMDAwQEABhQgAMFABkGARgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGgAAAAAJAQAAAAAMjAIBAHgFAAB4BgAACQQFBowH//9DBgcAbwgBAAkHCABDBQYHCQMEBUMBAgOCAQIAAgIAAAAAAADwPwJhcTjzqzn7PwAcBwEYAAAAAAAAAAAAAAAAHgAAAAAGAQAAAAANbwIAAGAABQACAAAAjAMCAAkCAwAJAQIAKwEFAIwEAgB4BQACCQMEBQkCAwD1AQECggECAAMCAAAAAAAA4D8CAAAAAAAA8L8CAAAAAAAAAEAAIAgBGAAAAAAAAAAAAAAAAAAhAAAAAAgBBAAABgMAAAUBAUf/AgQAAAAAAPsDAACePQIDAwAAAKQBAQAAAABAnwEDAvsDAQBNAgPvAgAAAJ8CAQIwAgEWAwAAAPsEAgBNAwRiBQAAAE0CAxEEAAAAvAICOgYAAACfAgICbwMHADADAi8IAAAAMAIBAQkAAACkAwsAAAiggG8EDACfAwICqQQBADAEA0UNAAAAqQQAADAEA9MOAAAApAQRAABA8ICMBf8AjAYAAIwH/wCfBAQCMAQDpBIAAABvBBMAMAQD2RQAAACkBBgAF1hQwTAEA34ZAAAAjAQAAIwFAAAwBAMfGgAAADAFAxIbAAAAbwQHADAEAy8IAAAAMAMBNRwAAAD7BQMATQQFyx0AAAAwBAFxHgAAADAAAbsfAAAAggECACADCQQAAABAAwQDCgMLAwwDDQcAAAAAAAAAAAAAAAAAAAAAAw4DDwMQBAAIoIADEQMSAxMDFAMVBABA8IADFgJmZmZmZmbmPwMXAxgDGQMaBBdYUMEDGwMcAx0DHgMfAyADIQAtBAEYAAAAAAAAAAABAAAAAAABAAAAAAAAAAEAAAEAAQAAAAEAAAEAAAEAAAAAAAAAAQAAAQAAAAEAAAAAAAEAAAEAAQAAAAABAAEuAAAAABYABwAADwAAAwgFJgEDElMCAxJfAnakAAIAAAQAgJ8AAQL7BAAAJgMABFsCAwOBEwIEBAAAAG8DBACkAQcAABhQgJ8BAwL7AgEAvAICJggAAACfAgID+wUCAE0EBTUJAAAANDYBBgEBAABSBgEAUgcBAFIIAQCkBQwAACyggJ8FBAIwBQQvDQAAAIwGAAD7CAIATQcIcQ4AAACMCAAATDYAAqQFDAAALKCAnwUEAiYEAgX7BgIATQUGNQkAAACkBhAAACzwgFIHBACfBgICMAYFhQ8AAAD7BQEAvAUFbBEAAACfBQIC+wYDALcGAgAFAAAADgM9APsFBAC8BQUaEgAAAJ8FAgH7BgUATQUGIhMAAACMBgoAnwUCAqQGFQAAAEBBvAYGtxYAAACfBgIC+wcCAFIJBABSCgUAUgsGALwHB2AXAAAAnwcFAfsHBgBvChgAbwsZAG8SGgCMFAUAjBUIALwSEvAbAAAAnxIEArwSEpscAAAAnxICAlIMEgBvDRkAbw4ZAG8SHQCMFAUAjBUFALwSEvAbAAAAnxIEArwSEpscAAAAnxICArwSEpscAAAAnxICArwSEpscAAAAnxICAlIPEgBvEBkAbxEeAHMJChFSCgQAUgsFAFIMBgC8BwdrHwAAAJ8HBgGCAAEAIAMiAyMEAAQAgAIAAAAAAAAUQAIAAAAAAADwPwMBAyQEABhQgAMlAx4DAwMEBAAsoIADDgMgAyYEACzwgAMnAygDKQMqBAAAQEEDKwMsAy0DLgMvAzADMQMyAzMDNABNAAEYAAAAAQAAAAAAAAAAAgAAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAABAAAAAQAAAAABAAAAAAEAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAk4AAAAADAMFAAAAM/sEAABNAwTvAAAAAFIEAQCfAwICUgYCAIwHSwCpCAAAvAQDbgEAAACfBAUBTQQANQIAAACkBQQAAAAwQDAFBCQFAAAAbwYGALwEA48HAAAAnwQDA/sHAQBNBgdKCAAAAFIHBACfBgICKwYCAKkHAACCBwIApAcLAAAokICfBwECxggAAPsKAgBNCQr9DAAAANkLAAASAAcAEgADABIAAAASAAUAEgEI/xICAwASAgQAvAkJxw0AAACfCQMCUggJAKkJAQDBCAAAggkCAA4DBAM1Ax4DKgQAADBAAzYCERERERERoT8DNwM4AyIDIwQAKJCAAzkDOgEEQTsBGAAAAAAAAQAAAAAAAQAAAAAAAQAAAAEAAAAAAQEAAwAAAQEAAAAAAAAAAAAAAAAAABEAAEIAAAAAEAIAAAAHAAABCAc4AUuMAwEAeAYBAHgHAQAJBQYHjAj//0MHCAFvCQEACQgJAUMGBwgJBAUGQwIDBE0DAHECAAAACQYCA1sFBgMJBwIDWwYHAwkIAgNbBwgDTDYAAqQEBgAAFECAnwQEAqQHCAAAFHCATQgAOwkAAACfBwICpAgLAAAocICMCQAAbwwNAGABBQAMAAAAjA0CAAkMDQEJCwwBKwsFAIwOAgB4DwEDCQ0ODwkMDQH1Cw4MWwoLDIwLAACfCAQCCQYHCIwIAABNCgBxAgAAAAkJAgqMCgAATDYAAqQHBgAAFECAnwcEAkMFBgdNBgA1DwAAAFsHBBAwBwYvEQAAAE0GADUPAAAAMAUGhQcAAABNBgABEgAAADAEBi8RAAAATQYAARIAAAAwBQaFBwAAAIIAAQATAgAAAAAAAPA/AmFxOPOrOfs/AyACAAAAAAAAAEADAwMEBAAUQIADJgQAFHCAAzwDPQQAKHCAAhgtRFT7IQlAAgAAAAAAAOA/AgAAAAAAAPC/Ax4CMzMzMzMz8T8DDgMPAGA+ARgAAAAAAAAAAAAAAEQAAQAAAAAAAAAAAAEAAAAAAAAAvQAAAAAAAAAAAAAAAEMAAAEAAAAAAAAAAAABAAAAAAEAAAABAAAAAQAAAAEeAAAAAAYBAwAAABOkAQIAAAQAgJ8BAQL7BAAAJgMBBFsCAwP7AwEAUgUCALwDA6wEAAAAnwMDAYwDAQBgAwUAAgAAAPsDAgC8AwMaBQAAAJ8DAgGCAAEABgMiAyMEAAQAgAIAAAAAAAAAQAM+AygAcgABGAAAAAEAAAEAAAAAAQAAAQAAAAJzAAAAAAIAAQAAAAX7AAAAvAAAxAAAAACfAAIBggABAAEDPwCcAQABGAAAAAABnQAAAAACAAIAAAAH+wEAAE0AATUAAAAA+wEBADABANkBAAAAggABAAIDHgMXAKwBAAEYAAAAAAAAAa0AAAAADQMJAAAAggH7AwAA8QECAAMAAACCAAEA+wQBAE0DBDEAAAAA8QMFAAAAAAD7BAIATQMEuwEAAAAOAxUAjAQAANQCAgAEAAAAqQMAAakDAQD7BQMATQQFtAIAAABSBQEA+wcCAE0GBzUDAAAA+wgEACYHCALiCAYAqQkBADAJCFkEAAAAMAMIaAUAAACfBAUB3gIEAIwDAAB9AiQAAwAAAKQDCAAAAHBAvAMDtwkAAACfAwIC+wUFACYEAwX7BgYATQUGzAoAAAB9BQYABAAAAPsEAgC8BATECwAAAJ8EAgGCAAEA+wYGAE0FBswKAAAA+wcFACYGAwcmBAUG+wYCAE0FBhYMAAAApAYPAAA40IBSBwQA2QgAABICAgCfBgMCMAYFIBAAAACMAgAA+wQHAE0DBOIRAAAA7AQCA28GEgBvCBMA9QkUBAkHCAlDBQYHpAYXAABYUIFvBxgApAgcABtokMGkCR8AHnSQwYwKAACpCwEAnwYGAvsHCAD7CgIATQkKNQMAAABSCgYA4gshAHgMBSIwDAvZIAAAALwHB5YjAAAAnwcFAvsJAgBNCAkWDAAAADAHCDEkAAAA+wkCAE0ICTUDAAAAMAUI2SAAAAC8CAfuJQAAAJ8IAgH7CQIATQgJFgwAAACkCQ8AADjQgG8KGADZCwEAEgICABIABQCfCQMCMAkIUyYAAACCAAEAJwNAAyEDQQMeA0IDQwUCBAUDKgQAAHBAAysDRAM/AwoDRQNGBAA40IADRwNIAmZmZmZmZuY/ApyZmZmZmck/AgAAAAAAAPA/A0kDBAQAWFCBApqZmZmZmbk/AxgDSgNLBBtokMEDTANNBB50kMEDFwUBIAIzMzMzMzPTPwNOA08DUANRAggJhwEAARgAAAABAgAAAAAAAAAAAQAAAAABAAABAQAAAQABAAAAAAD8BwEAAAEAAAAAAQAAAAAAAAEAAAABAgAAAAAAAQAAAAAAAAAAAAAFAgAAAQEAAAAAAgAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAQAAAAABAAABAAAAAAAAAAAAAAADiAAAAAACAAEAAAAF+wAAALwAAMQAAAAAnwACAYIAAQABAz8AsgEAARgAAAAAAbMAAAAADgQJAAAHAAABCAkwAYQBMAEAOwAAAABNBAA1AQAAAKQFAwAAACBAMAUEJAQAAABNBAABBQAAAKQFAwAAACBAMAUEJAQAAACkBAgAABxggJ8EAQLGBQAA+wcAAE0GB/0JAAAA2QgAABIABAASAAAAEgEF/7wGBscKAAAAnwYDAlIFBgBNBgAWCwAAAFIIBQC8Bgb9DAAAAJ8GAwH7BwEATQYHvw0AAABNCAA7AAAAAIwKAABNCwBxDgAAAIwMAABMNgACpAkRAABA8ICfCQQCQwcICU0IAHEOAAAAUgkCAJ8GBAIrBgUAvAcAUBIAAACfBwIBwQUAAIIAAQAwAgAoEwAAAPsIAgBNBwh6FAAAAPsKAwBNCQplFQAAALwHBwMWAAAAnwcDAvsJAwBNCAniFwAAAE0JABYLAAAATQsHjBgAAADZDQEAEgACABICBAASAAAAEgIFABIBCP8SAAMAEgIGABICAwASAgcAvAsLxwoAAACfCwMAvAkJ/QwAAACfCQABTQkAFgsAAACkCxsAAGiQgfsNBgBNDA1FHAAAANkNAgASAAAAnwsDALwJCf0MAAAAnwkAAfsKCABNCQrRHQAAAE0KADUBAAAAbwseAJ8JAwH7CggATQkK0R0AAABNCgA1AQAAAG8LHwDiDCMAqQ0BADANDLUgAAAAjA2AADANDJkhAAAAbw0kADANDEsiAAAAnwkEAcEFAACCAAEAJQM8Ax4DKgQAACBAAzYDDwMiAyMEABxggAM5AzoDCgNSA1MDIAMDAwQEAEDwgANUA1UDVgNXA1gDSANZA0UDRgQAaJCBA1oDWwIAAOBSuDzuQQIAAACIhd8AQgNcA10DXgUDICEiApqZmZmZmck/AwcKC2ssARgAAAIAAAAAAAEAAAAAAAEAAAEBAAAAAAAAAAAAAAgAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAEBAAABAAMAAwAAAAAAAAAAAQAAAQAAAAAAAAAAAAAAAAAAAAAAAAArAAAAAAAAAAAAAAAAAwAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQBsAAAAAAYBAgAAABOkAQIAAAQAgJ8BAQL7BAAAJgMBBFsCAwP7AwEA9QUEArwDA6wFAAAAnwMDAYwDAQBgAwUAAgAAAPsDAQC8AwNQBgAAAJ8DAgGCAAEABwMiAyMEAAQAgAIAAAAAAAAAQAIAAAAAAADwPwM+A1QAvgEAARgAAAABAAABAAAAAAEAAAEAAAACvwAAAAAHAQIAAAAmTQEAsgAAAAAOAQEAggABAKkBAQAwAQCyAAAAAKQBAwAACBCAnwEBAk0CABYEAAAA+wUAAE0EBf0FAAAA2QYAABIAAQASAAAAvAQExwYAAACfBAMAvAIC/QcAAACfAgAB+wQBAE0DBBsIAAAATQQAKAkAAACfAwIATAEAAqQCCwAAAKBAnwIAAcYCAAAwAgAoCQAAAIIAAQAMA18DIgMjBAAIEIADCgM5AzoDUgNgA1UDYQQAAKBAAQ24AT8BGAAAAAECAAABAAABAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAABAAABuQAAAAADAQAAAAAXTQEANQAAAAC8AQFQAQAAAJ8BAgHGAQAAMAEANQAAAABNAQABAgAAALwBAVABAAAAnwECAcYBAAAwAQABAgAAAE0BABYDAAAAvAEBUAEAAACfAQIBxgAAAIIAAQAEAx4DVAMPAwoAyQFUARgAAAAAAAEAAAEAAAAAAQAAAQAAAAABAsoAAAAACgQBAAAAFbsBAANSBQAApAQBAAAAAECfBAIBuwEBA1IFAQCkBAEAAAAAQJ8EAgH7BQAATQQF7wIAAACfBAECUgcBAFIIAgBSCQMAvAUEYAMAAACfBQUBggABAAQDYQQAAABAAwQDLADaAWIBGAAAAAAAAQAAAAABAAAAAQAAAAAAAdsAAAAAAwECAAAACk0BADYAAAAA3gEAAE0BAN8BAAAAwAICABICAQAwAgFrAwAAAIIAAQAEA2MDZAYQA2IBENcBZQEYAAAAAQABAAAABtgAAAAAAgABAAAABfsAAAC8AADZAAAAAJ8AAgGCAAEAAQNmAPYBAAEYAAAAAAH3AAAAAAIAAQAAAAX7AAAAvAAAzwAAAACfAAIBggABAAEDZwD5AQABGAAAAAAB+gAAAAAFAAQAAAAe+wIAAE0BAlsBAAAA+wMBAE0CA/8CAAAAbwMDAJ8BAwKQAAEApAIGAAAUQICfAgECtwICAAAAAACpAQABqQEBAPsCAgDxAQsAAgAAAN4BAgArAQgA+wMDAE0CA9EHAAAA+wQBAE0DBOoIAAAAbwQJAJ8CAwGCAAEACgIAAAAAAAAAAANoA2kDagMiAyMEABRAgANbA2sCAAA47OAJD0IAiwIAARgAAAAAAAAAAAABAAAAAAAAAQAAAQIBAAAAAAAAAAMMAQAAABIDCQAAAKAB+wQAAE0DBO8AAAAAUgQAAFIFAgCfAwMC+wYBAJ49AwQGAAAAUgUDAKQEAgAAABBAnwQDAfsEAgAwBAPZAwAAADABA/8EAAAA+wUDAE0EBVsFAAAATQUD/wQAAABvBgYAnwQDAisECAD7BgMATQUGVwcAAABNBgP/BAAAAG8HBgCMCAAAnwUEAU0FA7sIAAAADgUQAPsGBABNBQbvAAAAAEw2AAKkBgoAAACQgJ8GAQJMNgACpAcKAAAAkICfBwECbwgLAIwJRgCfBQUCMAUDtQwAAAD7BgUATQUG7w0AAABNBgNpDgAAAJ8FAgIwBQMCDwAAALwFAzwQAAAAnwUCAbwFAyQRAAAAnwUCAU0FA3YSAAAA+wgGAE0HCNkTAAAA2QkAABIAAwC8BwfHFAAAAJ8HAwC8BQX9FQAAAJ8FAAFNBQN2EgAAAPsIBgBNBwjPFgAAANkJAQASAAMAvAcHxxQAAACfBwMAvAUF/RUAAACfBQABTQUDuwgAAAAOBT8A+wcDAE0GB1sFAAAATQcD/wQAAABvCBgAnwYDApAFBhekBhsAAGiQgZ8GAQJgBhwABQAAACYHBQZNDAPZAwAAAE0LDDccAAAATQ0D2QMAAABNDA1FHQAAAEMKCwykDBsAAGiQgZ8MAQJNEAPZAwAAAE0PEDccAAAATRED2QMAAABNEBFFHQAAAEMODxAmDQ4HJgsMDbwIA4UeAAAAnwgEAbcGAgAFAAAAqQcAAakHAQBNCAN2EgAAAPsLBwBNCgvEHwAAAG8LIACfCgIC2QwCABICAwASAAMAEgEH/xICCAC8CgrHFAAAAJ8KAwC8CAj9FQAAAJ8IAAHBBwAAggMCACEDBAMJBAAAEEADbANpA2gDbQNuAyEDAwQAAJCAAjMzMzMzM+M/A28DcANxA3IDcwN0A3UDZgM6A1IDZwIAAAAAAAAAAANqAyIDIwQAaJCBA3YDWgN3A3gCAAAAAAAA4D8DEhMU4QEEARgAAAAAAAABAAAAAAAAAgAAAQACAAAAAAAAAQEAAAAAAAAAAwAAAQAAAAAAAAAAAAAAAAABAAMAAAAAAAAAAQAAAQAAAgAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAEAAABAAAAAAAAAAEAAAEAAQMAAAAAAAAAAAEAAAAAAAAAAAAAAAAA/gAABgAAAAIAAAAAAAAAAAAAAAAAAAAAAAAN4gAAAAACAAEAAAAL+wEAAE0AATsAAAAAvAAAUAEAAACfAAIB+wAAAMYBAAAwAQA7AAAAAIIAAQACA3kDVACoAgABGAAAAAAAAAEAAAABKQEAAAAHAQMAAAcAAAEDBBcCNfsCAABNAQK2AAAAAE0CAP8BAAAAnwECAvsFAQBNBAViAgAAAE0DBPADAAAATQID+AQAAABSBAEAvAICAwUAAACfAgMCRwIJAAAAAICkAwcAAABgQG8ECABSBgEAvAQEjQkAAACfBAMAnwMAAbwDAjoKAAAAnwMCAlICAwAwAgA7CwAAAE0EAkYNAAAATQME6gwAAAAwAwDqDAAAAPsFAgBNBAV/DgAAAFIFAgBSBgMAnwQDAU0EAHYPAAAA2QYAABIAAAC8BAT9EAAAAJ8EAwGCAAEAEQN6A2kDDAN7A3wDWAN9BAAAYEADfgN/Aw0DeQNrA4ABA4EBA3UDUgEWmgJzARgAAAAAAAACAAAAAAAAAAAAAAEAAQAAAAAAAAACAAAAAQACAAAAAQABAAAAAAACAAAAAAAABBsBAAAAAgABAAAAC/sBAABNAAHWAAAAALwAAFABAAAAnwACAfsAAADGAQAAMAEA1gAAAACCAAEAAgOCAQNUALYCAAEYAAAAAAAAAQAAAAE3AQAAAAgBAQAAACtNAQBVAAAAAE0CAOoBAAAATQMBhQIAAAAwAwKFAgAAAPsDAABNAgOBAwAAAE0DAOoBAAAAUgQBAJ8CAwJNAwA7BAAAAKQFBwAAAGBATQQFOAUAAAAwBAMkCAAAADACANYJAAAATQMA1gkAAACkBAsAACgggG8FDACMBgAAbwcNAJ8EBAIwBAPMDgAAAE0DAHYPAAAA2QUAABIAAAC8AwP9EAAAAJ8DAwGCAAEAEQODAQNrAyYDhAEDeQOFAQMqBAAAYEADNgOCAQMEBAAoIIACMzMzMzMz8z8CAAAAAAAA+L8DhgEDdQNSARitAnQBGAAAAQAAAAAAAQAAAAAAAAEAAAAAAAAAAQACAAAAAAAAAAAAAgAAAAAAAAQuAQAAAAgBAQAABwAAAQgFEQEbTQEAuwAAAAAOARcATQEAtQEAAAC8AQEmAgAAAJ8BAgL7BQAATQQFhQMAAABNAgSRBAAAAPsFAABNBAWFAwAAAG8FBQAJAwQF+wQAAKQFBwAAGDCAUgYCAEMHAwGfBQMCMAUEhQMAAACCAAEACAMhA28DJQMmA4cBBwAAAAAAAAAAAAAAwAAAAAADBAQAGDCAALsCZwEYAAAAAQAAAAABAAAAAAAAAAAAAQAAAAAAAAACPAEAAAAFAQEAAAcAAAEIBAcBHk0BAAIAAAAATQQA6gEAAABNAwSFAgAAAG8EAwAJAgMEMAIBkQQAAAD7AwAATQIDzAUAAABSAwEAnwICAU0CAfwGAAAApAMIAAAcIICfAwECMAMCIQkAAABNAgFtCgAAAKQDCAAAHCCAnwMBAjADAiEJAAAAggABAAsDcgNrAyYHAAAAAAAAAADNzEw+AAAAAAOIAQOJAQOKAQMEBAAcIIADiwEDjAEAwgJmARgAAAEAAAAAAAAAAgAAAAABAAAAAAAAAQAAAAAAAAFDAQAAAAgBAgAAACDGAQAA+wMAAE0CA38AAAAADgIVAPsDAQBNAgOwAQAAAE0FANkDAAAATQQFowQAAACQAwQCTQYCeQUAAABbBQYCTQcCeAYAAAAJBgcDjAcAAEw2AAKkBAkAACBwgJ8EBAJSAQQAggECAPsCAAC8AgIGCgAAAJ8CAgJSAQIAggECAAsDjQEDjgECAAAAAAAA4D8DbAOPAQOQAQORAQMDAwQEACBwgAOSAQDKApIBARgAAQAAAAEAAAEAAAAAAQAAAAAAAAAAAAAAAAIAAAAAAksBAAAAFAEEAAAHAAABCA5YAowBvAEABgAAAACfAQIC+wIAAE0EAZkBAAAATQUBmAIAAAC8AgJGAwAAAJ8CBAKkAwUAAABAQKQFCAAAHGCATQYCQwkAAABNCAJhCwAAAFsHCAqfBQMC/wYAAAIAAABNBwBpDAAAAE0IADsNAAAAxQYHAwEAAAC8AwNHDgAAAJ8DBAOkBREAAEDwgJ8FAQL7CAEATQcIWxMAAABNCAD/FAAAAG8JFQCfBwMCkAYHEmAFCQAGAAAA+wgCAE0HCNEWAAAATQgA6hcAAABvCRgAnwcDAYIAAQBNBwA7DQAAAE0JB0YaAAAATQgJsRkAAABNCQg7GwAAAPsLAgBNCgvRFgAAAFILCABvDBwAnwoDAU0KALUdAAAApBEjAACIEIKfEQECWxARIHgPEB+kEiMAAIgQgp8SAQJbERIgeBARH6QTIwAAiBCCnxMBAlsSEyB4ERIfTDYAAqQOJQAAHECCnw4EAk0NDgcmAAAAWwwNHrwKCp0nAAAAnwoDAfsLAwBNCgvvBwAAAE0LALsoAAAAnwoCAlINCQBSDgQAvAsK6CkAAACfCwQCTQ0A2SoAAABNDA03KwAAAEMGBQwOCwUATQ0A2SoAAABNDA1FLAAAAEMGBgxNEADZKgAAAE0PEDcrAAAATREA2SoAAABNEBFFLAAAAEMODxCkDxEAAEDwgJ8PAQC8DACFLQAAAJ8MAAH7DQEATQwNVy4AAABNDQD/FAAAAG8OFQBSDwYAnwwEAYIAAQAvA5IBA5MBA5QBA5UBAyoEAABAQAOWAQMEBAAcYIADlwECAAAAAAAAaUADmAEDcQN5A5kBAyIDIwQAQPCAAgAAAAAAAAAAA2gDaQNqA1sDawIAACDYtzzuQQOaAQOAAQM8AgAAqPa4BA9CA28CAAAAAAAAPkACAAAAAAAA8D8CAAAAAAAAAEADAQMCBACIEIIDAwQAHECCAwUDmwEDIQM7A2wDdgNaA3cDbgDVApwBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFcBAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAABQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAALD+//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAQAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAgDAQAAACKpAwEATQQBwgAAAACkBQMAAgAQwPEEEAAFAAAAqQMAAE0EAcIAAAAApAUFAAQAEMCaBAkABQAAAE0EAbMGAAAApAUIAAcYEMDxBAIABQAAAKkDAAGpAwEADgMDALwEANYJAAAAnwQCAfsFAABNBAWCCgAAAFIFAABSBgEAUgcCAJ8EBAGCAAEACwOdAQMYA54BBAIAEMADnwEEBAAQwAOgAQOhAQQHGBDAA5wBA6IBAPcCogEBGAAAAAAAAAABAAAAAAAAAAAAAAAAAAACAQAAAgAAAAAAAAF5AQAAAAEBAAAAAAGCAAEAAACBA6MBARgAgQEAAAAeAAABAgD9AaMAAACkAQEAAAAAQE0AAUgCAAAApAEEAAAAMEBvAwUAvAEBFgYAAACfAQMCpAIEAAAAMEBvBAcAvAICFgYAAACfAgMCpAMEAAAAMEBvBQgAvAMDFgYAAACfAwMCpAQEAAAAMEBvBgkAvAQEFgYAAACfBAMCpAUEAAAAMEBvBwoAvAUFFgYAAACfBQMCpAYMAAAAsEBNCAR6DQAAAE0HCJAOAAAAnwYCAqQHDAAAALBATQkEQBAAAABNCAlWDwAAAJ8HAgKkCAwAAACwQE0KBHoNAAAATQkKOhEAAACfCAICpAkMAAAAsEBNCwS9EgAAAE0KC5YTAAAAnwkCAqQKDAAAALBATQwEQBAAAABNCwxKFAAAAJ8KAgKkCwwAAACwQE0NBKEVAAAATQwNDBYAAACfCwICpAwMAAAAsEBNDgShFQAAAE0NDtIXAAAAnwwCAqQNDAAAALBATQ8EoRUAAABNDg8iGAAAAJ8NAgKkDgwAAACwQE0QBGAaAAAATQ8QdxkAAACfDgICpA8MAAAAsEBNEQShFQAAAE0QEXYbAAAAnw8CAqQQDAAAALBATRIEoRUAAABNERKsHAAAAJ8QAgKkEQwAAACwQE0TBKEVAAAATRIToR0AAACfEQICpBMfAAAA4EFNEhMkIAAAAKQTDAAAALBATRQSyiEAAACfEwICwBQiAMAVIwDAFiQAxhcAAKQYDAAAALBATRsEvRIAAABNGhssJgAAAE0ZGi4lAAAAnxgCAv8ZBAAAAAAAMBkZbicAAADAGigAEgAZABIADwASAAQAEgAGADAaGe8pAAAA2RoEABIABwASAAgAEgACABIAEQASARf/MBoZ6CoAAADAGisAMBoZrCwAAADAGi0AEgACABIACAASAAQAEgAGABIAAQASAAkAEgAYABIABQASAAwAMBoZYC4AAADAGi8AEgACABIACAAwGhnEMAAAAMAaMQAwGhlQMgAAAP8aBQAAAAAAbxslADAbGuUzAAAAMBoabicAAACePRoFEwAAAFIcGgBSHRMApBs1AAAAQEOfGwMB2RsJABIBF/8SABkAMBsaczYAAADAGzcAEgATABIAGgASABgAEgAOABIADQASAAoAEgACABIAEAASAAwAMBsa7ykAAADAGzgAEgAOABIABAASAAsAMBsaPDkAAADAGzoAEgALADAbGiQ7AAAAwBs8ABIAAAAwGxrPPQAAAMAbPgASAAoAMBsa2T8AAADAG0AAEgADABIAAAAwGxoGQQAAAMAbQgASAAAAEgAOABIADAASABkAMBsa1kMAAADAG0QAEgATADAbGoJFAAAAwBtGADAbGq9HAAAAwRcAAIIaAgBIAyoEAAAAQAOkAQOlAQQAADBAA6YBA6cBA6gBA6kBA6oBA6sBA6wBBAAAsEADVgOtAQOuAQOvAQOwAQOxAQOyAQOzAQO0AQO1AQO2AQO3AQO4AQO5AQN1A7oBA7sBA7wBBAAA4EEDNgO9AQYABgEGAgO+AQO/AQPAAQYDAwQDOwYGAz4GDAMsBg4DPwYPA1QDwQEDCQQAAEBDA2UGFQYXA3MGGQN0BhoDZwYbA2YGHAOSAQYdA5wBBh4DogEGHwOjARMAAQIDBQYMDg8RFRcZGhscHR4fAQABBgACAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAH0AAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAgAAAAEAAAAA9gMEBAIAAAAAAAAAAAUAAQABAAAAAAAAFAAAAAAAAAAfAAALAAAAAAAAAAAAAABNAAAAABEAAAoAAQAAAQABAEMAAAAAAQAAAAAKAAAAAAAAAAAAAAA5AAAAAAATAAAADgAAAAcAAAAIAAAAAAsAAAAAAAAiAAAACgAAAQABAAAADAAAAAwAAAC9AAAAACAaOVxF2b82Dij9NtF9YEk7PDnVRAsmnTvyyDIo66bYlGrH2VVx5nuy

-- Decompiled by Krnl

local v_u_1 = workspace.CurrentCamera
local v_u_2 = game:GetService("Players")
local v_u_3 = game:GetService("RunService")
local v_u_4 = game:GetService("UserInputService")
local v_u_5 = game:GetService("ReplicatedStorage")
local v_u_6 = game:GetService("TweenService")
local v_u_7 = require(v_u_5.Forcefield.ForcefieldConsts)
local v_u_8 = require(v_u_5.Module.SimulatedPhysicsProjectile)
local v_u_9 = require(v_u_5.Forcefield.ForcefieldService)
local v_u_10 = require(v_u_5.Game.DisplayDamage)
local v_u_11 = require(v_u_5.Module.R15IKv2)
local v_u_12 = require(v_u_5.Std.Joint)
local v_u_13 = require(v_u_5.Std.Audio)
local v_u_14 = require(v_u_5.Std.Spring)
local v_u_15 = require(v_u_5.Inventory.InventoryItemUtils)
local v_u_16 = require(v_u_5.Std.Maid)
local v_u_17 = require(v_u_5.Std.Interval)
local v_u_18 = require(v_u_5.Std.String)
local v19 = script.Parent
local v_u_20 = require(v19.Item)
local v_u_21 = nil
local v_u_22 = require(v_u_5.Game.ItemConfig.ForcefieldLauncher)
local v_u_23 = {}
v_u_23.__index = v_u_23
function v_u_23.new(p24)
	-- upvalues: (copy) v_u_23, (copy) v_u_16, (copy) v_u_5, (copy) v_u_7
	local v25 = v_u_23
	local v26 = setmetatable({}, v25)
	v26.maid = v_u_16.new()
	local v27 = v_u_5.Resource.ForcefieldMesh:Clone()
	v27.Size = Vector3.new(0, 0, 0)
	v26.MeshPartForcefield = v27
	local v28 = Instance.new("Part")
	v28.Anchored = true
	v28.CanCollide = false
	v28.Color = Color3.fromRGB(255, 0, 255)
	v28.Transparency = 0.7
	v28.Shape = Enum.PartType.Ball
	v28.TopSurface = 0
	v28.BottomSurface = 0
	v28.Size = Vector3.new(0, 0, 0)
	v26.PartShell = v28
	v26.Radius = v_u_7.RADIUS
	v26.Local = p24
	return v26
end
function v_u_23.AttemptLaunch(p_u_29, p30, p31)
	-- upvalues: (copy) v_u_8, (copy) v_u_9, (copy) v_u_3, (copy) v_u_18, (ref) v_u_21
	local v_u_32 = v_u_8.new(p30)
	v_u_32:HitTargetWithSpeed(p31, 75, false)
	p_u_29.PartShell.Parent = workspace
	local v33, v_u_34 = v_u_32:CalculateNextInstantCollision(0.03333333333333333)
	if not v_u_9.getIsPositionAllowed(v33) then
		return false
	end
	local v_u_35 = os.clock()
	local v_u_36 = nil
	v_u_36 = v_u_3.Heartbeat:Connect(function()
		-- upvalues: (copy) v_u_35, (copy) v_u_32, (copy) p_u_29, (copy) v_u_34, (ref) v_u_36, (ref) v_u_18, (ref) v_u_21
		local v37 = (os.clock() - v_u_35) * 5
		local v38 = math.min(v37, 1)
		local v39, v40 = v_u_32:Update()
		p_u_29.PartShell.Size = Vector3.new(v38, v38, v38)
		local v41 = p_u_29.Radius
		local v42 = v39 - Vector3.new(0, v41, 0)
		p_u_29.PartShell.CFrame = CFrame.new(v42)
		if v_u_34 < v_u_32:GetElapsed() or v40 then
			v_u_36:Disconnect()
			local v43 = v_u_18.base85UUID(10)
			local v44 = workspace:GetServerTimeNow()
			p_u_29:Grow(v42, v43, v44)
			v_u_21:FireServer("w" .. "" .. ("u4gdroleh"):sub(5, 8):reverse() .. "" .. "" .. ("ricyteq8r"):sub(5, 5):reverse():reverse():reverse() .. "z1", v42, v43, v44)
		end
	end)
	return true
end
function v_u_23.SetSize(p45, p46)
	local v47 = 1 + (p46 - 1) * (p46 - 1) * (-1 + p46 + 1.70158 * p46)
	local v48 = p45.Radius
	local v49 = v47 * v48 * 2
	local v50 = v47 * v48 * 2
	local v51 = v47 * v48 * 2
	local v52 = Vector3.new(v49, v50, v51)
	local v53 = CFrame.new(p45.Position) * CFrame.Angles(0, (p46 < 0.5 and 2 * p46 * p46 or -1 - 2 * (p46 - 2) * p46) * 3.141592653589793, 0)
	local v54 = v47 * p45.Radius
	local v55 = v53 + Vector3.new(0, v54, 0)
	p45.PartShell.Size = v52 * 1.075
	p45.PartShell.CFrame = v55
	p45.MeshPartForcefield.Size = v52
	p45.MeshPartForcefield.CFrame = v55
end
function v_u_23.Grow(p_u_56, p57, p_u_58, p_u_59)
	-- upvalues: (copy) v_u_3, (copy) v_u_9, (copy) v_u_5, (copy) v_u_7, (copy) v_u_2, (copy) v_u_10, (copy) v_u_22, (copy) v_u_6, (copy) v_u_13
	p_u_56.Position = p57
	p_u_56.PartShell.Parent = workspace
	p_u_56.MeshPartForcefield.Parent = workspace
	local v_u_60 = os.clock()
	local v_u_61 = nil
	v_u_61 = v_u_3.Heartbeat:Connect(function(_)
		-- upvalues: (copy) v_u_60, (copy) p_u_56, (ref) v_u_61
		local v62 = (os.clock() - v_u_60) * 2
		p_u_56:SetSize(v62)
		if v62 > 1 then
			v_u_61:Disconnect()
		end
	end)
	p_u_56.maid:GiveTask(v_u_61)
	local v63 = v_u_9.add
	local v64 = p_u_56.Position
	local v65 = p_u_56.Radius
	if v63(v64 + Vector3.new(0, v65, 0), p_u_56.Radius, p_u_58) then
		p_u_56.ForcefieldId = p_u_58
		local v66 = v_u_5.Forcefield:FindFirstChild(v_u_7.HEALTH_UPDATE_REMOTE_NAME)
		local v_u_67 = v_u_7.STARTING_HEALTH
		p_u_56.maid:GiveTask(v66.OnClientEvent:Connect(function(p68, p69, p70)
			-- upvalues: (copy) p_u_58, (ref) v_u_2, (copy) p_u_56, (ref) v_u_10, (ref) v_u_67, (copy) p_u_59, (ref) v_u_22, (ref) v_u_7, (ref) v_u_6
			if p69 == p_u_58 then
				if v_u_2.LocalPlayer == p68 or p_u_56.Local then
					local v71 = p70 <= 0
					v_u_10.draw(p69, p_u_56.PartShell, v_u_67 - p70, {
						["isVehicleDamage"] = true,
						["didPopVehicleTires"] = v71
					})
				end
				v_u_67 = p70
				if p70 <= 0 then
					local v72 = workspace:GetServerTimeNow()
					if v72 - p_u_59 >= v_u_22.MinShieldDuration then
						p_u_56:Shrink()
						return
					end
					local v73 = v_u_22.MinShieldDuration - (v72 - p_u_59)
					p_u_56.maid.shrinkTask = task.delay(v73, function()
						-- upvalues: (ref) p_u_56
						p_u_56:Shrink()
					end)
					p70 = 0
				end
				local v_u_74 = 0.7 + 0.20000000000000007 * (1 - p70 / v_u_7.STARTING_HEALTH)
				local v75 = TweenInfo.new(0.1, Enum.EasingStyle.Linear, Enum.EasingDirection.In, 0, true)
				local v76 = v_u_6:Create(p_u_56.PartShell, v75, {
					["Transparency"] = v_u_74 - 0.3
				})
				p_u_56.maid.transparencyHitFlicker = v76
				p_u_56.PartShell.Transparency = v_u_74
				v76:Play()
				p_u_56.maid.afterTween = task.delay(0.1, function()
					-- upvalues: (ref) p_u_56, (copy) v_u_74
					p_u_56.PartShell.Transparency = v_u_74
				end)
			end
		end))
		p_u_56.maid:GiveTask(task.delay(v_u_22.MaxShieldDuration, function()
			-- upvalues: (copy) p_u_56
			p_u_56:Shrink()
		end))
		v_u_13.ObjectLocal(p_u_56.PartShell, 4058366615)
		v_u_13.ObjectLocal(p_u_56.PartShell, 9058693376, {
			["Looped"] = true,
			["MaxDistance"] = 128,
			["Volume"] = 0.2
		})
	else
		p_u_56:Destroy()
	end
end
function v_u_23.Shrink(p_u_77)
	-- upvalues: (copy) v_u_3, (copy) v_u_9
	if not p_u_77.isShrinking then
		p_u_77.isShrinking = true
		local v_u_78 = os.clock()
		p_u_77.maid:GiveTask(v_u_3.Heartbeat:Connect(function(_)
			-- upvalues: (copy) v_u_78, (copy) p_u_77
			local v79 = (os.clock() - v_u_78) * 2
			p_u_77:SetSize(1 - v79)
			if v79 > 1 then
				p_u_77:Destroy()
			end
		end))
		local v80 = v_u_9.removeById
		local v81 = p_u_77.ForcefieldId
		assert(v80(v81))
		p_u_77.ForcefieldId = nil
	end
end
function v_u_23.Destroy(p82)
	p82.PartShell:Destroy()
	p82.PartShell = nil
	p82.MeshPartForcefield:Destroy()
	p82.MeshPartForcefield = nil
	p82.maid:Destroy()
end
local v_u_83 = {
	["__ClassName"] = "ForcefieldLauncher"
}
v_u_83.__index = v_u_83
setmetatable(v_u_83, v_u_20)
function v_u_83.Init(p84)
	-- upvalues: (ref) v_u_21, (copy) v_u_23
	v_u_21 = p84.Event
	function p84.em.welortz1(p85, p86, p87, p88)
		-- upvalues: (ref) v_u_23
		assert(p85)
		assert(p86)
		v_u_23.new():Grow(p86, p87, p88)
	end
end
function v_u_83.new(p89, p90, p91)
	-- upvalues: (copy) v_u_20, (copy) v_u_83, (copy) v_u_22, (copy) v_u_15, (copy) v_u_14, (copy) v_u_11, (copy) v_u_3, (copy) v_u_17, (copy) v_u_13
	local v_u_92 = v_u_20.new(p89, p91)
	local v93 = v_u_83
	setmetatable(v_u_92, v93)
	v_u_92.Config = v_u_22
	v_u_92.inventoryItemValue = p90
	if not v_u_15.getAttr(v_u_92.inventoryItemValue, "LastShoot") then
		v_u_15.setAttr(v_u_92.inventoryItemValue, "LastShoot", 0)
	end
	if v_u_92.Local then
		v_u_92.SpringCamera = v_u_14.new(Vector3.new(), Vector3.new(), 0.6, 70)
	end
	v_u_92.IK = v_u_11.BuildPacketArms(v_u_92.Character)
	v_u_92:SetupModel()
	v_u_92:AttachModelToPlayer()
	v_u_92.Maid:GiveTask(v_u_3.Stepped:Connect(function()
		-- upvalues: (copy) v_u_92
		v_u_92:Stepped()
	end))
	v_u_92.Maid:GiveTask(v_u_3.RenderStepped:Connect(function()
		-- upvalues: (copy) v_u_92
		v_u_92:RenderStepped()
	end))
	if v_u_92.Local then
		local v94 = v_u_15.getAttr(v_u_92.inventoryItemValue, "NextShootPossible") or 0
		local v95 = os.clock()
		if v95 < v94 then
			local v96 = v94 - v95
			v_u_92:StartReloadProgressCircle(v_u_92.Config.Reload + v_u_92.Config.MaxShieldDuration, os.clock() - (v_u_92.Config.Reload + v_u_92.Config.MaxShieldDuration - v96))
		end
		local v_u_97 = v95 < v94
		v_u_92.Maid:GiveTask(v_u_17.every(0.5):Connect(function()
			-- upvalues: (ref) v_u_15, (copy) v_u_92, (ref) v_u_97, (ref) v_u_13
			local v98 = (v_u_15.getAttr(v_u_92.inventoryItemValue, "NextShootPossible") or 0) > os.clock()
			if v98 ~= v_u_97 then
				v_u_97 = v98
				if not v98 then
					v_u_13.ObjectLocal(v_u_92.Center, 16663715207)
				end
			end
		end))
	end
	return v_u_92
end
function v_u_83.SetupModel(p_u_99)
	-- upvalues: (copy) v_u_15, (copy) v_u_5, (copy) v_u_12
	local v100 = v_u_15.getName(p_u_99.inventoryItemValue)
	local v101 = v_u_5.Resource.ItemSystem.Models:FindFirstChild(v100)
	if v101 == nil then
		error(("Could not find model for item `%s`"):format(v100))
	end
	local v102 = v101:Clone()
	p_u_99.Model = v102
	local v103 = v102.Skeleton.Center
	p_u_99.Center = v103
	v_u_12.WeldAllTo(v102, v103)
	p_u_99.Maid:GiveTask(function()
		-- upvalues: (copy) p_u_99
		p_u_99.Model:Destroy()
		p_u_99.Model = nil
	end)
end
function v_u_83.AttachModelToPlayer(p_u_104)
	-- upvalues: (copy) v_u_12
	local v105 = p_u_104.UpperTorso
	p_u_104.Center.CFrame = v105.CFrame
	local v106 = v_u_12.BlankMotor(p_u_104.Center, v105)
	p_u_104.Model.Parent = workspace.Items
	p_u_104.Motor = v106
	p_u_104.Motor.C1 = CFrame.new(1.2, 0, -1.5)
	p_u_104.Maid:GiveTask(function()
		-- upvalues: (copy) p_u_104
		p_u_104.Motor:Destroy()
		p_u_104.Motor = nil
	end)
end
function v_u_83.RenderStepped(p107)
	-- upvalues: (copy) v_u_1
	if p107.Local then
		local v108 = p107.SpringCamera:Update()
		local v109 = v_u_1.CFrame.p
		local v110 = v_u_1.CFrame * Vector3.new(0, 0, -2)
		v_u_1.CFrame = CFrame.new(v109, v110 + v108)
	end
end
function v_u_83.Stepped(p111)
	-- upvalues: (copy) v_u_11
	local v112 = p111.IK
	v112.RightArm = p111.Center.CFrame * Vector3.new(0, 0, 0.2)
	v_u_11.Arms(v112)
	v112.LeftWrist.Transform = CFrame.new()
	v112.RightWrist.Transform = CFrame.new()
end
function v_u_83.GetMouseLocation(p113)
	-- upvalues: (copy) v_u_4, (copy) v_u_1
	if not v_u_4.TouchEnabled then
		return v_u_4:GetMouseLocation()
	end
	local v114 = v_u_1.ViewportSize
	local v115 = p113.Config.MobileMouseHeightScalar or 0.5
	local v116 = v114.X * 0.5
	local v117 = v114.Y * v115
	return Vector3.new(v116, v117, 0)
end
function v_u_83.ShootBegin(p118)
	-- upvalues: (copy) v_u_1, (copy) v_u_15, (copy) v_u_13, (copy) v_u_23
	local v119 = p118:GetMouseLocation()
	local v120 = v_u_1:ViewportPointToRay(v119.x, v119.y)
	local _, v121 = workspace:FindPartOnRayWithIgnoreList(Ray.new(v120.Origin, v120.Direction * 200), { p118.Character, p118.Model })
	local v122 = os.clock()
	if v122 < (v_u_15.getAttr(p118.inventoryItemValue, "NextShootPossible") or 0) then
		v_u_13.ObjectLocal(p118.Center, 4058365633)
	else
		local v123 = p118.Model.Skeleton.Tip
		local v124 = v123.Position
		v_u_13.ObjectLocal(v123, 16652902101)
		local v125 = p118.SpringCamera
		local v126 = math.random() * 2 - 1
		local v127 = math.random() * 2 - 1
		local v128 = math.random() * 2 - 1
		v125:Accelerate(Vector3.new(v126, v127, v128).Unit * 30)
		local v129 = v_u_23.new(p118.Local):AttemptLaunch(v124, v121)
		local v130 = v122 + p118.Config.Reload
		if v129 then
			v130 = v130 + p118.Config.MaxShieldDuration
		end
		p118:StartReloadProgressCircle(p118.Config.Reload + p118.Config.MaxShieldDuration, os.clock())
		v_u_15.setAttr(p118.inventoryItemValue, "NextShootPossible", v130)
	end
end
function v_u_83.InputBegan(p131, p132, p133)
	-- upvalues: (copy) v_u_20
	local v134
	if p132.UserInputType == Enum.UserInputType.MouseButton1 then
		v134 = true
	elseif p132.UserInputType == Enum.UserInputType.Gamepad1 then
		v134 = p132.KeyCode == Enum.KeyCode.ButtonR2
	else
		v134 = false
	end
	if v134 then
		p131:ShootBegin()
	end
	v_u_20.InputBegan(p131, p132, p133)
end
function v_u_83.InputEnded(_) end
return v_u_83
