-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgOIAQRtYXRoBnJhbmRvbQdWZWN0b3IzA25ldwRVbml0DFJhbmRvbVZlY3RvcgF4AXoBWQl3b3Jrc3BhY2UHR3Jhdml0eQRhdGFuA21pbgNjb3MDc2luG0NhbGN1bGF0ZVByb2plY3RpbGVWZWxvY2l0eQxzZXRtZXRhdGFibGUFU2V0dXAKU2hvb3RQcm94eQ1TZXR1cEFybVdlbGRzAklLBU1vZGVsBEJhc2UIUG9zaXRpb24IUmlnaHRBcm0GQ29uZmlnBk1vdGlvbg9SaWdodEVsYm93QW5nbGUKUmlnaHRBbmdsZQtVcGRhdGVBcm1JSwlUaXBPZmZzZXQIU2V0dXBUaXAHRW5hYmxlZAhTa2VsZXRvbgtCb3VuZGluZ0JveA1CdWxsZXRFbWl0dGVyB0J1bGxldHMERW1pdAhJbnN0YW5jZQRQYXJ0BFNpemUKQ2FuQ29sbGlkZQhBbmNob3JlZAxUcmFuc3BhcmVuY3kGUGFyZW50CUV4cGxvc2lvbghSZXNvdXJjZQpJdGVtU3lzdGVtC1Byb2plY3RpbGVzBUNsb25lBkRlYnJpcwVTbW9rZQxMYW5kaW5nU21va2UFZGVsYXkITGlmZXRpbWUDTWF4BGdhbWUHQWRkSXRlbQtPYmplY3RMb2NhbAVTb3VuZBJleHBsb3Npb25fbGFyZ2VfMDIGVm9sdW1lC0VtaXR0ZXJTaXplBUxvY2FsEmludmVudG9yeUl0ZW1WYWx1ZRJEQU1BR0VfUkVNT1RFX05BTUUORmluZEZpcnN0Q2hpbGQKRmlyZVNlcnZlcg5HcmVuYWRlRXhwbG9kZQhWZWxvY2l0eQdEZXN0cm95B0dyZW5hZGUGTW9kZWxzIUl0ZW0gbW9kZWwgZm9yICVzIGRvZXMgbm90IGV4aXN0LgZmb3JtYXQGYXNzZXJ0BkhhbmRsZQRXZWxkBUl0ZW1zC1ByaW1hcnlQYXJ0BkNGcmFtZRRTZXRQcmltYXJ5UGFydENGcmFtZRJQaHlzaWNhbFByb3BlcnRpZXMYQ3VzdG9tUGh5c2ljYWxQcm9wZXJ0aWVzEVNIT09UX1JFTU9URV9OQU1FDEdyZW5hZGVUaHJvdx1CdWxsZXRFbWl0dGVyT25Mb2NhbEhpdFBsYXllcglEZXN0cm95ZWQIU2hvb3RFbmQUU2hvb3RDaGVja0NvbmRpdGlvbnMNRGVjcmVtZW50QW1tbxNTZXROZXh0U2hvdFBvc3NpYmxlBHRpY2sNR3JlbmFkZUhlbGRBdBBTcHJpbmdJdGVtT2Zmc2V0BVJhaXNlB1NwcmluZ3MKSXRlbU9mZnNldAlTZXRUYXJnZXQSU3ByaW5nSXRlbVJvdGF0aW9uDEl0ZW1Sb3RhdGlvbhJTcHJpbmdOZWNrUm90YXRpb24MTmVja1JvdGF0aW9uEENsZWFyQWxsQ2hpbGRyZW4IRnVzZVRpbWUTQnJvYWRjYXN0SW5wdXRCZWdhbgpTaG9vdEJlZ2luA0hpcAZMYXVuY2gKUmVsb2FkVGltZQ1Nb3VzZVBvc2l0aW9uE0Jyb2FkY2FzdElucHV0RW5kZWQKU2hvb3RPdGhlchZndW5fcGlzdG9sX2RyeV9maXJlXzAxBVBpdGNoClNob290U291bmQRUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZAVBdWRpbwdSMTVJS3YyBk1vZHVsZQVKb2ludBJJbnZlbnRvcnlJdGVtVXRpbHMJSW52ZW50b3J5D0d1blN5c3RlbUNvbnN0cwRHYW1lBnNjcmlwdANHdW4LX19DbGFzc05hbWUHX19pbmRleAlBcHBseVNraW4KU2NvcGVCZWdpbghTY29wZUVuZAZSZWxvYWQAFgcAAAAABwAAAQgBEwIWpAQEAAAMIICfBAECWwMEAXgCAwCkBQQAAAwggJ8FAQJbBAUBeAMEAKQGBAAADCCAnwYBAlsFBgF4BAUATDYAAqQBBwAAGFCAnwEEAk0AAQcIAAAAggACAAkCAAAAAAAA8D8CAAAAAAAAAEADAQMCBAAMIIADAwMEBAAYUIADBQAMBgEYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAAAEQMAAAAAYiYDAQBNCAOZAQAAAE0JA5kBAAAACQcICU0JA5sCAAAATQoDmwIAAAAJCAkKQwYHCAQEBgBNBQN4AwAAAG8GBACkCAYAAABQQE0HCCUHAAAACQsCAgkKCwIJCQoCCQ0HBAkMDQSMEAIACQ8QBQkODwIJDQ4CQwsMDQkKBwsmCAkKjAkAAH0JGgAIAAAABAkIAAkNAgJDDA0JCQ0HBOwLDA27BgsCpAoKAAAkgICfCgICCQ4CAiYNDgkJDgcE7AwNDrsGDAKkCwoAACSAgJ8LAgKeEwoFCwAAAFINCgBSDgsApAwMAAAsgICfDAMCUgYMAE0NA5kBAAAACQwCDewLDAS7CQYDUg0GAKQMDgAANICAnwwCAgkKCwy7GAYDUg0GAKQMEAAAPICAnwwCAgkLAgxNDwObAgAAAAkOAg/sDQ4EuwkGA1IPBgCkDg4AADSAgJ8OAgIJDA0OTDYAAqQJEwAASBCBnwkEArsJBgNSDQYApAwOAAA0gICfDAICCQsCDOwKBAuCCQMAFAIAAAAAAADgPwMHAwgDCQIYLURU+yHpPwMKBAAAUEADCwMBAwwEACSAgAMNBAAsgIADDgQANICAAw8EADyAgAMDAwQEAEgQgQASEAEYAAEAAAAAAAAAAAAAAAAAAQEAAAABAAAAAAAAAAAAAAABAAABAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAATAAAAAAcDAgAAABb7BAAATQME7wAAAABSBAAAUgUBAFIGAgCfAwQC+wYBAJ49AwQGAAAAUgUDAKQEAgAAABBAnwQDAVIGAgC8BAOZAwAAAJ8EAwGMBAEAMAQD1wQAAACCAwIABQMEAxEEAAAQQAMSAxMAJgQBGAAAAAAAAAABAAAAAAAAAQAAAAIAAAInAAAAAAEBAAAAAAGCAAEAAAAyFAEYADIAAAAABgEAAAAAFU0BAAIAAAAATQIAOwEAAABNBQI7AQAAAE0EBS4CAAAATQMEOwMAAAAwAwGRBAAAAE0FANkFAAAATQQFlwYAAABNAwSgBwAAADADAfsIAAAAggABAAkDFQMWAxcDGAMZAxoDGwMcAx0AMx4BGAAAAQABAAAAAAAAAAEAAAAAAAAAATQAAAAAAgEAAAAAB0w2AAKkAQIAAAQAgJ8BAQIwAQA7AwAAAIIAAQAEAwMDBAQABACAAx8AOSABGAAAAAAAAAE6AAAAAAIAAQAAAAX7AAAAqQEAADABAPAAAAAAggABAAEDIQBiAAEYAAAAAAFjAAAAAA0CAwAABwAAAQgHIgK/AU0EAUYAAAAATQMEbwEAAABNAgM7AgAAAE0EAGcDAAAATQMERQQAAAAOAyIAjAUBAIwDHgCMBAEAqAMeAKQKCQAAIHCAnwoBAlsJCgZ4CAkFpAsJAAAgcICfCwECWwoLBngJCgWkDAkAACBwgJ8MAQJbCwwGeAoLBUw2AAKkBwwAACyggJ8HBAJNBgcHDQAAAE0HAGcDAAAAUgkCAFIKBgCMC5ABvAcHVg4AAACfBwUBiwPi/6QDEAAALPCAbwQRAJ8DAgJvBBIAMAQDLxMAAACpBAAAMAQD0xQAAACpBAEAMAQDRRUAAACMBAEAMAQD2RYAAAAwAgM7AgAAAKQEGAAAAHBBMAQDJBkAAAD7CAAATQcIYhsAAABNBgfwHAAAAE0FBg8dAAAATQQFlhoAAAC8BAQ6HgAAAJ8EAgIwAwQkGQAAAIwHBAC8BQRWDgAAAJ8FAwH7CQAATQgJYhsAAABNBwjwHAAAAE0GBw8dAAAATQUGnR8AAAC8BQU6HgAAAJ8FAgIwAwUkGQAAAIwIMgC8BgVWDgAAAJ8GAwH7CgAATQkKYhsAAABNCAnwHAAAAE0HCA8dAAAATQYHJSAAAAC8BgY6HgAAAJ8GAgIwAwYkGQAAAIwJAwC8BwZWDgAAAJ8HAwH7CwAATQoLYhsAAABNCQrwHAAAAE0ICQ8dAAAATQcIEiEAAAC8Bwc6HgAAAJ8HAgKpCAEAMAgH8CIAAAAwAwckGQAAAKQIJAAAADBCTQsHyyYAAABNCgu0JwAAAPUJJQrZCgAAEgAHAJ8IAwGkCSkAAACAQk0ICZ0fAAAAUgoDAIwLBQC8CAh4KgAAAJ8IBAH7CQEATQgJ0SsAAABSCQMATQwA2SwAAABNCwxuLQAAAE0KC+IuAAAA4gswAIwMAQAwDAtLLwAAAJ8IBAKMCRQAMAkIgzEAAABNCQC7MgAAAA4JDABNCQD/MwAAAPsMAgBNCwzcNAAAALwJCQM1AAAAnwkDAlIMAgC8CglrNgAAAJ8KAwGCAAEANwMiAyMDGAMkAyUCAAAAAAAA8D8CAAAAAAAAAEADAQMCBAAgcIADAwMEBAAsoIADBQMmAycEACzwgAMoB83MzD3NzMw9zczMPQAAAAADKQMqAysDLAMKBAAAcEEDLQMuAy8DMAMxAzIDMwM0AzUDIQM2BAAAMEICAAAAAAAAFEADNwM4AzkEAACAQgM6AzsDGgM8Az0DPgUBLwM/A0ADQQNCA0MDRAEGPEUBGDAAAAAAAAUAAAAAAQAAAMoAAAAAAAAAAAAAAAAAAAAAAAAAADkAAAAAAAAA/QcAAAABAAABAAABAAABAAABAAEAAAACAAAAAAAAAAAAAAABAAEAAAACAAAAAAAAAAAAAAABAAEAAAACAAAAAAAAAAAAAAABAAEAAAACAAAAAAAAAAAAAAABAAABAAIAAAAAAAAAAAADAAAAAAAAAAACAAAAAAAAAAAAAAAAAAABAAACAAABAAAAAAAAAAEAAAACDQAAAAACAAEAAAAF+wAAAKkBAQAwAQDTAAAAAIIAAQABAyoAhAEAARgAAAAAAYUAAAAACQADAAAHAAABCAMkAir7AAAA+wEBAPsCAgCfAAMB+wICAE0BAjsBAAAATQABLgAAAACpAQEAMAEA0wIAAAD7AgIATQECOwEAAABNAAEuAAAAAKQGCAAAHGCAnwYBAlsFBgV4BAUEpAcIAAAcYICfBwECWwYHBXgFBgSkCAgAABxggJ8IAQJbBwgFeAYHBEw2AAKkAwsAACiQgJ8DBAJNAgMHDAAAAFsBAgMwAQCFDQAAAIIAAQAOAxcDFgMqAgAAAAAAAElAAgAAAAAAAPA/AgAAAAAAAABAAwEDAgQAHGCAAwMDBAQAKJCAAwUDRgCHAQABGHwAAAACAAAAAAAAAAEAAAAAgQAAAAAAAAAAAAAAAAAAAAAAAAAAAH8AAQ0AAAAAAgABAAAABfsAAAC8AABQAAAAAJ8AAgGCAAEAAQNHAI4BAAEYAAAAAAGPAAAAAA0DBQAABwAAAQMFCwKWAfsIAABNBwhiAQAAAE0GB/ACAAAATQUG+AMAAABNBAVPAAAAAG8FBABvBwAAvAUFjQUAAACfBQMATAEAAqQDBwAAAGBAnwMAArwEAzoIAAAAnwQCAlIDBABNBQM7CgAAAE0EBewJAAAAvAQEUAsAAACfBAIB+wUBAE0EBeoMAAAATQYDOwoAAABNBQYuDQAAAE0HA0YPAAAATQYHbw4AAACfBAMBTQUDOwoAAABNBAUuDQAAAKkFAAAwBQRFEAAAAE0FA0YPAAAATQQFbw4AAACpBQAAMAUERRAAAACkBRMAAAAgQU0EBTgRAAAAMAQDJBQAAABNBQNGDwAAAE0EBW8OAAAAMAQDmxUAAABNBAObFQAAAPsFAgBNCQA7CgAAAE0ICUYPAAAATQcIbw4AAABNBgc7FgAAAFIHAQCMCGQAnwUEAjAFBIUXAAAApAgaAABkgIFMNgACpAkcAABksIGfCQECTQoEhRcAAACfCAMCTQwAOwoAAABNCwxGDwAAAE0KC28OAAAATQkKOxYAAABDBwgJvAUDZh0AAACfBQMBpAUfAABk4IFvBiAAbwchAG8IIgCMCRQAjAoBAJ8FBgIwBQQ2IwAAAKQFJQAAAEBCjAYAANkHAAASAAQAnwUDAaQFJQAAAEBCUgYCANkHAQASAgMAEgAAABIBA/+fBQMBpAUlAAAAQEKVBgIm2QcCABIBA/+fBQMBTQUAuycAAAAOBQsATQUA/ygAAAD7CAQATQcInikAAAC8BQUDKgAAAJ8FAwK8BgVrKwAAAJ8GAgHBAwAAggABACwDSAMvAzADSQNKA0sDTAQAAGBAAzIDTQMWA0cDTgMXAyMDIgMrA08DCgQAACBBAy0DUAMYA0YDUQMEBABkgIEDAwQAZLCBA1IDUwQAZOCBAmZmZmZmZuY/As3MzMzMzOw/AgAAAAAAAOA/A1QDNgQAAEBCAgAAAAAAAABAA0ADQQNVA0MDRAMICQpvVgEYAQAAAAAAAAAAAQAAAAD+AAAABAAAAAEAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAQAAAAAAAAIAAAAAAAEAAAAAAAEAAgAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAgAAAAAAAwAAAAAAAAAHAAAAAAAEAAABAAAAAAAAAAEAAAIAcQAAAAABAQAAAAABggABAAAAlwFXARgAlwAAAAACAAEAAAAF+wAAALwAAFAAAAAAnwACAYIAAQABA0cArgEAARgAAAAAAa8AAAAAAwADAAAAE/sBAABNAAElAAAAAA4AAQCCAAEA+wEAAE0AAdcBAAAA+wEBAPEAAwABAAAAqQAAAIIAAgD7AAAA+wICALwAAA4CAAAAnwADAYIAAQADA1gDEwNZALQBAAEYAAAAAAECAAAAAAABAAIAAAAAAbUAAAAADAIAAAAHAAABCAZsApMBvAIAqQAAAACfAgICKwICAKkCAACCAgIAvAIApQEAAACfAgIBvAIA9AIAAACfAgIBpAIEAAAAMECfAgECMAIAfgUAAABNAwDXBwAAAJUCAwYwAgDXBwAAAE0DAB0IAAAATQkA2QkAAABNCAmXCgAAAE0HCPQLAAAATQYHmAwAAABNBQaADQAAALwDA5cOAAAAnwMDAU0DAAAPAAAATQkA2QkAAABNCAmXCgAAAE0HCPQLAAAATQYHmAwAAABNBQblEAAAALwDA5cOAAAAnwMDAU0DAIMRAAAATQkA2QkAAABNCAmXCgAAAE0HCPQLAAAATQYHmAwAAABNBQaNEgAAALwDA5cOAAAAnwMDAU0FADsUAAAATQQFOxQAAABNAwTsEwAAALwDAzoVAAAAnwMCArwEA6EWAAAAnwQCAakEAQAwBAPTFwAAAKkEAAAwBANFGAAAAKQEGgAAAJBBMAQDJBsAAACkCSAAAHzggZ8JAQJbCAkdeAcIBqQKIAAAfOCBnwoBAlsJCh14CAkGpAsgAAB84IGfCwECWwoLHXgJCgZMNgACpAYjAACIEIKfBgQCTQUGByQAAABbBAUcMAQDhSUAAACkBCcAAABgQowFBQDZBgAAEgADAJ8EAwFNBgA7FAAAAE0FBjsUAAAATQQF7BMAAACMBQEAMAUE2SgAAACkBCcAAABgQk0GANkJAAAATQUGzCkAAADZBgEAEgAAABIAAgASAAEAnwQDAU0EALsqAAAADgQEAFIGAQC8BAAKKwAAAJ8EAwGCAAEALANaA1sDXANdBAAAMEADXgIAAAAAAADwPwMTA18DGgMbA2ADYQNiA2MDZANlA2YDZwNNAxYDMgNoAyoDKwMKBAAAkEEDLQIAAAAAAABJQAIAAAAAAAAAQAMBAwIEAHzggQMDAwQEAIgQggMFA0YDNgQAAGBCAywDaQNAA2oCDQ6YAWsBGIwAAAABAAMAAAEAAAIAAAAAAQAAAQACAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAACAAAAAAAAAAABAAABAAABAAABAAAAYQAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAQAAAAAABAAAAAAAAAAAAgAAAAAAAAAAAAAKAAABAAAAAg0AAAAACAABAAAANPsBAABNAAEdAAAAAPsHAABNBgfZAQAAAE0FBpcCAAAATQQFvQMAAABNAwSYBAAAAE0CA4AFAAAAvAAAlwYAAACfAAMB+wEAAE0AAQAHAAAA+wcAAE0GB9kBAAAATQUGlwIAAABNBAW9AwAAAE0DBJgEAAAATQID5QgAAAC8AACXBgAAAJ8AAwH7AQAATQABgwkAAAD7BwAATQYH2QEAAABNBQaXAgAAAE0EBb0DAAAATQMEmAQAAABNAgONCgAAALwAAJcGAAAAnwADAYIAAQALA18DGgMbA2wDYQNiA2MDZANlA2YDZwDMAQABGAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAHNAAAAAAMAAgAAABf7AQAATQABJQAAAAAOAAIAqQAAAIIAAgD7AgEATQECOwEAAABNAAEuAgAAAIwBAAAwAQDZAwAAAPsCAQBNAQI7AQAAAE0AAewEAAAAjAEAADABANkDAAAAggABAAUDWAMWAxcDLANNANYBAAEYAAAAAAEAAwAAAAAAAAABAAAAAAAAAAHXAAAAAAoCAAAAAG5NAgB+AAAAACsCAgCpAgAAggICAE0EANkBAAAATQMEzAIAAACkBQQAAAAwQJ8FAQJNBgB+AAAAACYEBQYmAgMExgMAADADAH4AAAAATQMAHQUAAABNCQDZAQAAAE0ICZcGAAAATQcIZAcAAABNBgeYCAAAAE0FBoAJAAAAvAMDlwoAAACfAwMBTQMAAAsAAABNCQDZAQAAAE0ICZcGAAAATQcIZAcAAABNBgeYCAAAAE0FBuUMAAAAvAMDlwoAAACfAwMBTQMAgw0AAABNCQDZAQAAAE0ICZcGAAAATQcIZAcAAABNBgeYCAAAAE0FBo0OAAAAvAMDlwoAAACfAwMBpAMQAAAA8EBvBBEA2QUAABIAAACfAwMBTQMAOxIAAABNBQM7EgAAAE0EBS4TAAAAjAUBADAFBNkUAAAATQUDOxIAAABNBAXsFQAAAIwFAQAwBQTZFAAAAKQEEAAAAPBATQYA2QEAAABNBQa8FgAAANkGAQASAAAAEgADAJ8EAwFNBgDHFwAAAFIHAgC8BAB+GAAAAJ8EBAFNBAC7GQAAAA4EBABSBgEAvAQAuRoAAACfBAMBggABABsDXgMaA2kDXQQAADBAA18DGwNtA2EDYgNjA2QDZQNmA2cDNgQAAPBAApqZmZmZmck/AxYDFwMsA00DbgNvA1YDQANwAhARwgFZARgAAAABAAIAAAAAAAAAAAAAAQAAAgAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAQAAAAAABgABAAAAAAAAAQAAAAAAAAIAAAAAAAAAAAAJAAAAAAABAAABAAAAAsMAAAAAAQEAAAAAAYIAAQAAAOQBcQEYAOQAAAAACwIBAAAAHw4BHQD7AwAATQID0QAAAABNBQA7AgAAAE0EBUYDAAAATQMEbwEAAABNBgDZBAAAAE0FBm4FAAAATQQF5gYAAADiBQkAbwYKADAGBUsHAAAAjAgBAKQKDwAAONCAnwoBAlsJCgxDBwgJeAYHCzAGBQAIAAAAnwIEAYIAAQAQAzsDIwMWAyIDGgM8A3IDPgNzBQIHCAIzMzMzMzPjPwKamZmZmZmpPwKamZmZmZm5PwMBAwIEADjQgADlAXQBGAABAAABAAAAAAABAAAAAAABAAAAAAAAAAAAAAAA/QbmAAAAAA4AAAECAHyjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CA9IHAAAAnwECAqQCBQAAAEBATQQAQAkAAABNAwRKCAAAAJ8CAgKkAwUAAABAQE0FAKEGAAAATQQFDAoAAACfAwICpAQFAAAAQEBNBgBgDAAAAE0FBncLAAAAnwQCAqQFBQAAAEBATQgAvQ4AAABNBwjwDwAAAE0GB0kNAAAAnwUCAqQHEQAAAABBTQYHJBIAAACkBwUAAABAQE0IBg0TAAAAnwcCAsAIFADACRUA/woFAAAAAABvCxYAMAsK5RcAAAAwCgpuGAAAAJ49CgUHAAAAUgwKAFINBwCkCxoAAACQQZ8LAwHACxsAEgAHABIACgAwCwrvHAAAAMALHQAwCwp0HgAAAMALHwAwCwq2IAAAAMALIQAwCwroIgAAAMALIwASAAAAEgABABIABQDADCQAEgAAABIAAwASAAkAEgALABIABQAwDAp+JQAAAMAMJgAwDApyJwAAAMAMKAAwDArWKQAAAMAMKgAwDAoOKwAAAMAMLAAwDAqNLQAAAMAMLgASAAEAMAwKuS8AAACpDAAAMAwK6TAAAACpDAAAMAwKJDEAAACpDAAAMAwK8jIAAACpDAAAMAwKNzMAAACCCgIANAM5BAAAAEADdQN2A3cEAABAQAN4A3kDegN7A3wDfQN+A38DgAEDMAOBAQQAAABBAy0DggEGAAYBA0gDgwEDhAEDEQQAAJBBBgIDBAYDAxQGBAMeBgUDIAYHBgsDVgYMA1cGDwNrBhIDWQYTA3EGFAN0A4UBA4YBA4cBA4gBDQABAgMEBQcLDA8SExQBAAEYAAEAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAAACAAAAAQAAAAACBhAAAQAAAQABAAAAAAAAAQAAAAAMAAABAAAGAAADAAAAMwAAAAAAAAAoAAABAAAqAAAiAAABAAAACQAAAQAAAQAAAQAAAgEAAAAAFWeibFw6oi06VWYGyGr+5fQXKtOiYIMGx+SzEAtCWIcoTt6ci9J6Ifs=

-- Decompiled by Krnl

local v_u_1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v_u_1.Std.Audio)
require(v_u_1.Module.R15IKv2)
local v_u_3 = require(v_u_1.Std.Joint)
require(v_u_1.Inventory.InventoryItemUtils)
local v_u_4 = require(v_u_1.Game.ItemSystem.GunSystemConsts)
local v5 = script.Parent
local v_u_6 = require(v5.Gun)
local function v_u_24(p7, p8, p9)
	local v10 = p8 - p7
	local v11 = (v10.x * v10.x + v10.z * v10.z) ^ 0.5
	local v12 = v10.Y
	local v13 = workspace.Gravity
	local v14 = p9 * p9 * p9 * p9 - v13 * (v13 * v11 * v11 + 2 * v12 * p9 * p9)
	local v15
	if v14 >= 0 then
		local v16 = v14 ^ 0.5
		local v17 = (p9 * p9 + v16) / (v13 * v11)
		local v18 = math.atan(v17)
		local v19 = (p9 * p9 - v16) / (v13 * v11)
		local v20 = math.atan(v19)
		v15 = math.min(v18, v20)
	else
		v15 = 0.7853981633974483
	end
	local v21 = p9 * v10.x / v11 * math.cos(v15)
	local v22 = p9 * math.sin(v15)
	local v23 = p9 * v10.z / v11 * math.cos(v15)
	return Vector3.new(v21, v22, v23), v11 / (p9 * math.cos(v15))
end
local v_u_25 = {
	["__ClassName"] = "Grenade"
}
v_u_25.__index = v_u_25
setmetatable(v_u_25, v_u_6)
function v_u_25.new(p26, p27, p28)
	-- upvalues: (copy) v_u_6, (copy) v_u_25
	local v29 = v_u_6.new(p26, p27, p28)
	local v30 = v_u_25
	setmetatable(v29, v30)
	v29:Setup(p28)
	v29.ShootProxy = 1
	return v29
end
function v_u_25.SetupArmWelds(_) end
function v_u_25.UpdateArmIK(p31)
	local v32 = p31.IK
	v32.RightArm = p31.Model.Model.Base.Position
	v32.RightAngle = p31.Config.Motion.RightElbowAngle
end
function v_u_25.SetupTip(p33)
	p33.TipOffset = Vector3.new()
end
local function v_u_46(p34, p35)
	-- upvalues: (copy) v_u_1, (copy) v_u_2, (copy) v_u_4
	local v36 = p35.Skeleton.BoundingBox.Position
	if p34.BulletEmitter.Bullets then
		for _ = 1, 30 do
			local v37 = math.random() * 2 - 1
			local v38 = math.random() * 2 - 1
			local v39 = math.random() * 2 - 1
			local v40 = Vector3.new(v37, v38, v39).Unit
			p34.BulletEmitter:Emit(v36, v40, 400)
		end
	end
	local v41 = Instance.new("Part")
	v41.Size = Vector3.new(0.1, 0.1, 0.1)
	v41.CanCollide = false
	v41.Anchored = true
	v41.Transparency = 1
	v41.Position = v36
	v41.Parent = workspace
	local v42 = v_u_1.Resource.ItemSystem.Projectiles.Explosion:Clone()
	v42.Parent = v41
	v42:Emit(4)
	local v43 = v_u_1.Resource.ItemSystem.Projectiles.Debris:Clone()
	v43.Parent = v41
	v43:Emit(50)
	local v44 = v_u_1.Resource.ItemSystem.Projectiles.Smoke:Clone()
	v44.Parent = v41
	v44:Emit(3)
	local v_u_45 = v_u_1.Resource.ItemSystem.Projectiles.LandingSmoke:Clone()
	v_u_45.Enabled = true
	v_u_45.Parent = v41
	delay(5 - v_u_45.Lifetime.Max, function()
		-- upvalues: (copy) v_u_45
		v_u_45.Enabled = false
	end)
	game.Debris:AddItem(v41, 5)
	v_u_2.ObjectLocal(v41, p34.Config.Sound.explosion_large_02, {
		["Volume"] = 1
	}).EmitterSize = 20
	if p34.Local then
		p34.inventoryItemValue:FindFirstChild(v_u_4.DAMAGE_REMOTE_NAME):FireServer(v36)
	end
end
function v_u_25.GrenadeThrow(p_u_47, p48, p49)
	-- upvalues: (copy) v_u_1, (copy) v_u_3, (copy) v_u_24, (copy) v_u_46, (copy) v_u_4
	local v50 = v_u_1.Resource.ItemSystem.Models.Grenade
	local v_u_51 = assert(v50, ("Item model for %s does not exist."):format("Grenade")):Clone()
	v_u_51.Model.Handle:Destroy()
	v_u_3.Weld(v_u_51.Model.Base, v_u_51.Skeleton.BoundingBox)
	v_u_51.Model.Base.Anchored = false
	v_u_51.Skeleton.BoundingBox.Anchored = false
	v_u_51.Parent = workspace.Items
	v_u_51.PrimaryPart = v_u_51.Skeleton.BoundingBox
	local v_u_52 = v_u_51.PrimaryPart
	v_u_52.Velocity = v_u_24(p_u_47.Model.Skeleton.BoundingBox.Position, p48, 100)
	v_u_51:SetPrimaryPartCFrame(CFrame.new(Vector3.new(), v_u_52.Velocity) + p_u_47.Model.Skeleton.BoundingBox.Position)
	v_u_52.CustomPhysicalProperties = PhysicalProperties.new(0.7, 0.9, 0.5, 20, 1)
	delay(0, function()
		-- upvalues: (copy) v_u_52
		v_u_52.CanCollide = true
	end)
	delay(p49, function()
		-- upvalues: (ref) v_u_46, (copy) p_u_47, (ref) v_u_51
		v_u_46(p_u_47, v_u_51)
		v_u_51.Model.Base.CanCollide = true
		local v53 = v_u_51.Model.Base
		local v54 = math.random() * 2 - 1
		local v55 = math.random() * 2 - 1
		local v56 = math.random() * 2 - 1
		v53.Velocity = Vector3.new(v54, v55, v56).Unit * 50
	end)
	delay(p49 + 2, function()
		-- upvalues: (ref) v_u_51
		v_u_51:Destroy()
	end)
	if p_u_47.Local then
		p_u_47.inventoryItemValue:FindFirstChild(v_u_4.SHOOT_REMOTE_NAME):FireServer()
	end
end
function v_u_25.BulletEmitterOnLocalHitPlayer(_) end
function v_u_25.ShootBegin(p_u_57, p_u_58)
	if not p_u_57:ShootCheckConditions() then
		return false
	end
	p_u_57:DecrementAmmo()
	p_u_57:SetNextShotPossible()
	p_u_57.GrenadeHeldAt = tick()
	local v_u_59 = p_u_57.ShootProxy + 1
	p_u_57.ShootProxy = v_u_59
	p_u_57.SpringItemOffset:SetTarget(p_u_57.Config.Motion.Raise.Springs.ItemOffset)
	p_u_57.SpringItemRotation:SetTarget(p_u_57.Config.Motion.Raise.Springs.ItemRotation)
	p_u_57.SpringNeckRotation:SetTarget(p_u_57.Config.Motion.Raise.Springs.NeckRotation)
	local v_u_60 = p_u_57.Model.Model.Handle:Clone()
	v_u_60:ClearAllChildren()
	v_u_60.CanCollide = true
	v_u_60.Anchored = false
	v_u_60.Parent = workspace
	local v61 = math.random() * 2 - 1
	local v62 = math.random() * 2 - 1
	local v63 = math.random() * 2 - 1
	v_u_60.Velocity = Vector3.new(v61, v62, v63).Unit * 50
	delay(5, function()
		-- upvalues: (copy) v_u_60
		v_u_60:Destroy()
	end)
	p_u_57.Model.Model.Handle.Transparency = 1
	delay(p_u_57.Config.FuseTime, function()
		-- upvalues: (copy) p_u_57, (copy) v_u_59, (copy) p_u_58
		if not p_u_57.Destroyed then
			if p_u_57.ShootProxy ~= v_u_59 then
				return false
			end
			p_u_57:ShootEnd(p_u_58)
		end
	end)
	if p_u_57.Local then
		p_u_57:BroadcastInputBegan(p_u_58)
	end
end
function v_u_25.ShootEnd(p_u_64, p65)
	if not p_u_64.GrenadeHeldAt then
		return false
	end
	local v66 = p_u_64.Config.FuseTime - (tick() - p_u_64.GrenadeHeldAt)
	p_u_64.GrenadeHeldAt = nil
	p_u_64.SpringItemOffset:SetTarget(p_u_64.Config.Motion.Launch.Springs.ItemOffset)
	p_u_64.SpringItemRotation:SetTarget(p_u_64.Config.Motion.Launch.Springs.ItemRotation)
	p_u_64.SpringNeckRotation:SetTarget(p_u_64.Config.Motion.Launch.Springs.NeckRotation)
	delay(0.2, function()
		-- upvalues: (copy) p_u_64
		p_u_64.SpringItemOffset:SetTarget(p_u_64.Config.Motion.Hip.Springs.ItemOffset)
		p_u_64.SpringItemRotation:SetTarget(p_u_64.Config.Motion.Hip.Springs.ItemRotation)
		p_u_64.SpringNeckRotation:SetTarget(p_u_64.Config.Motion.Hip.Springs.NeckRotation)
	end)
	local v_u_67 = p_u_64.Model
	v_u_67.Model.Base.Transparency = 1
	v_u_67.Model.Handle.Transparency = 1
	delay(p_u_64.Config.ReloadTime, function()
		-- upvalues: (copy) p_u_64, (copy) v_u_67
		if p_u_64.Destroyed then
			return false
		end
		v_u_67.Model.Base.Transparency = 0
		v_u_67.Model.Handle.Transparency = 0
	end)
	p_u_64:GrenadeThrow(p_u_64.MousePosition, v66)
	if p_u_64.Local then
		p_u_64:BroadcastInputEnded(p65)
	end
end
function v_u_25.ShootOther(_) end
function v_u_25.ShootSound(p68, p69)
	-- upvalues: (copy) v_u_2
	if p69 then
		v_u_2.ObjectLocal(p68.Model.Skeleton.BoundingBox, p68.Config.Sound.gun_pistol_dry_fire_01, {
			["Volume"] = 0.6,
			["Pitch"] = 1 + math.random() * 0.1 - 0.05
		})
	end
end
v_u_25.ApplySkin = false
v_u_25.ScopeBegin = false
v_u_25.ScopeEnd = false
v_u_25.Reload = false
return v_u_25
