-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMSA25ldwxzZXRtZXRhdGFibGUQU3ByaW5nSXRlbU9mZnNldAlTZXRUYXJnZXQKSW5wdXRCZWdhbgpJbnB1dEVuZGVkBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQZzY3JpcHQGUGFyZW50B3JlcXVpcmUFQmFzaWMER2FtZQpJdGVtQ29uZmlnCUhhbmRjdWZmcwtfX0NsYXNzTmFtZQdfX2luZGV4AAQIAwMAAAAW+wQAAE0DBO8AAAAAUgQAAFIFAQD7BgEAUgcCAJ8DBQL7BgIAnj0DBAYAAABSBQMApAQCAAAAEECfBAMBTQQDHQMAAABvBgQAvAQElwUAAACfBAMBggMCAAYDAQMCBAAAEEADAwcAAAAAmpmZPgAAgL8AAAAAAwQADAEBGAAAAAAAAAAAAQAAAAAAAAIAAAAAAAINAAAAAAQBAQEAAAijAQAA+wIAAE0BAoIAAAAAUgIAAN0DAACfAQABggABAAEDBQAUBQEYAAEAAAAAAAEUAAAAAAEBAAAAAAGCAAEAAAAXBgEYABcAAAAACAAAAQIANaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAgUAAABAQE0BAiQGAAAApAIIAAAAcEBNAwHLCQAAAJ8CAgKkAwgAAABwQE0GAL0KAAAATQUGLAsAAABNBAXYDAAAAJ8DAgL/BAQAAAAAAG8FDAAwBQTlDQAAADAEBG4OAAAAnj0EBQIAAABSBgQAUgcCAKQFEAAAAPBAnwUDAcAFEQASAAIAEgADABIABAAwBQTvEgAAAMAFEwASAAIAMAUEghQAAADABRUAMAUErxYAAACCBAIAFwMHBAAAAEADCAMJAwoEAABAQAMLAwwEAABwQAMNAw4DDwMQAxEDEgMCBAAA8EAGAAMBBgEDBQYCAwYDAAECAQABGAABAAAAAAABAAAAAQAAAAACAAAAAAAAAAACAAEAAAEAAQAAAAAAAAEAAAAAAAgAAAADAAACAQAAAAAD3uyQoY3M07/sKPo1H2vx0qk6FkMsZb6wG85ZuOKRFiuvK1WY+W4YNg==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v2 = script.Parent
local v_u_3 = require(v2.Basic)
local v_u_4 = require(v1.Game.ItemConfig.Handcuffs)
local v_u_5 = {
	["__ClassName"] = "Handcuffs"
}
v_u_5.__index = v_u_5
setmetatable(v_u_5, v_u_3)
function v_u_5.new(p6, p7, p8)
	-- upvalues: (copy) v_u_3, (copy) v_u_4, (copy) v_u_5
	local v9 = v_u_3.new(p6, p7, v_u_4, p8)
	local v10 = v_u_5
	setmetatable(v9, v10)
	v9.SpringItemOffset:SetTarget(Vector3.new(0, 0.3, -1))
	return v9
end
function v_u_5.InputBegan(p11, ...)
	-- upvalues: (copy) v_u_3
	v_u_3.InputBegan(p11, ...)
end
function v_u_5.InputEnded(_) end
return v_u_5
