-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNYBlVwZGF0ZQlTZXRBY3RpdmUISXNKdWljZWQEdGFzawR3YWl0B0Rlc3Ryb3kPV2Fsa1NwZWVkU3ByaW5nCkFjY2VsZXJhdGUDbmV3BV9tYWlkCUhlYXJ0YmVhdAdDb25uZWN0CEdpdmVUYXNrBWRlbGF5CHg2NDJsc3hlBUV2ZW50AmVtBEluaXQMc2V0bWV0YXRhYmxlFURlZmF1bHREaXNhYmxlQ2FtTG9jawJJSwVNb2RlbAhSaWdodEFybQhTa2VsZXRvbghQb3NpdGlvbgZDb25maWcGTW90aW9uD1JpZ2h0RWxib3dBbmdsZQpSaWdodEFuZ2xlC1VwZGF0ZUFybUlLEFNwcmluZ0l0ZW1PZmZzZXQDSGlwB1NwcmluZ3MKSXRlbU9mZnNldAlTZXRUYXJnZXQSU3ByaW5nSXRlbVJvdGF0aW9uDEl0ZW1Sb3RhdGlvbgVMb2NhbAR0aWNrDExhc3RDb25zdW1lZAF4AAZ6NnMwaHgDc3ViB3JldmVyc2UDbjRqA2kyegp1OHh4c2x3OTh4AWUKRmlyZVNlcnZlcg1Vc2VySW5wdXRUeXBlBEVudW0MTW91c2VCdXR0b24xCEdhbWVwYWQxB0tleUNvZGUIQnV0dG9uUjIDRWF0C09iamVjdExvY2FsCUNoYXJhY3RlcgtQcmltYXJ5UGFydAZWb2x1bWUTQnJvYWRjYXN0SW5wdXRCZWdhbgpJbnB1dEJlZ2FuCklucHV0RW5kZWQGc2NyaXB0BlBhcmVudAdyZXF1aXJlBUJhc2ljBGdhbWUKUnVuU2VydmljZQpHZXRTZXJ2aWNlEVJlcGxpY2F0ZWRTdG9yYWdlEVNob2Nrd2F2ZVNjcmVlbkZ4BEdhbWUNQ2hhcmFjdGVyVXRpbAdSMTVJS3YyBk1vZHVsZQNTdGQFQXVkaW8SUmlnaHRXcmlzdFJvdGF0aW9uEUxlZnRXcmlzdFJvdGF0aW9uDE5lY2tSb3RhdGlvbg1XYWlzdFJvdGF0aW9uB1ZlY3RvcjMGQ0ZyYW1lBUp1aWNlC19fQ2xhc3NOYW1lB19faW5kZXgACgIAAQAAAAX7AAAAvAAAJgAAAACfAAIBggABAAEDAQAxAAEYAAAAAAEyAAAAAAMAAgAAABL7AAAAqQIAALwAAFkAAAAAnwADAfsAAQCpAQAAMAEAlAEAAACkAAQAAAwggIwBBQCfAAIB+wAAALwAAFAFAAAAnwACAYIAAQAGAwIDAwMEAwUEAAwggAMGADUAARgAAAAAAAEAAAABAAAAAQAAAAE2AAAAAAYAAwAAACj7AAAAqQEBADABAJQAAAAA+wEAAE0AAdwBAAAAjAIUALwAAJ0CAAAAnwADAfsBAQBNAAHvAwAAAJ8AAQJNAQDBBAAAAPsEAgBNAwT9BQAAANkFAAASAAAAvAMDxwYAAACfAwMAvAEB/QcAAACfAQABqQMBALwBAFkIAAAAnwEDAaQBCwAAKJCAjAIDANkDAQASAAAAEgIAAJ8BAwGCAAEADAMDAwcDCAMJAwoDCwMMAw0DAgMEAw4EACiQgAIAAS0PARgAAAAAAQAAAAAAAAEAAAABAAAAAAAAAAAAAAAAAwAAAAEAAAAAAAAGLgAAAAADAQQAAAAMTQEANgAAAADeAQAATQEA3wEAAADAAgIAEgIBABICAgASAgMAMAIB4AMAAACCAAEABAMQAxEGAgMPAQIoEgEYAAAAAQADAAAAAAAPKQAAAAAIAwMAAAAT+wQAAE0DBO8AAAAAUgQAAFIFAQD7BgEAUgcCAJ8DBQL7BgIAnj0DBAYAAABSBQMApAQCAAAAEECfBAMBvAQDvgMAAACfBAIBggMCAAQDCQMTBAAAEEADFAA9CQEYAAAAAAAAAAABAAAAAAAAAgAAAj4AAAAABgEAAAAAFU0BAAIAAAAATQIAOwEAAABNBQJGAwAAAE0EBZECAAAATQMEOwQAAAAwAwGRAgAAAE0FANkFAAAATQQFlwYAAABNAwSgBwAAADADAfsIAAAAggABAAkDFQMWAxcDGAMZAxoDGwMcAx0ARR4BGAAAAQABAAAAAAAAAAEAAAAAAAAAAUYAAAAAFwACAAATAAAEAxM8AgMTTgIDE2YCAxNyAoYB+wEAAE0AAR0AAAAA+wcAAE0GB9kBAAAATQUGlwIAAABNBAW9AwAAAE0DBJgEAAAATQIDgAUAAAC8AACXBgAAAJ8AAwH7AQAATQABAAcAAAD7BwAATQYH2QEAAABNBQaXAgAAAE0EBb0DAAAATQMEmAQAAABNAgPlCAAAALwAAJcGAAAAnwADAfsBAABNAAG7CQAAAA4AXwCkAAsAAACgQJ8AAQL7AwAATQID/A0AAACQAQIM+wIAADAAAvwNAAAAJgIAAYwDBQBgAgMAAwAAAKkCAACCAgIA+wIBAG8FDgBvBg8AbxMQAIwVAgCMFgIAvBMT8BEAAACfEwQCvBMTmxIAAACfEwICvBMTmxIAAACfEwICvBMTmxIAAACfEwICUgcTAG8IDwBvCQ8AbxMTAIwVAgCMFgIAvBMT8BEAAACfEwQCvBMTmxIAAACfEwICvBMTmxIAAACfEwICvBMTmxIAAACfEwICvBMTmxIAAACfEwICvBMTmxIAAACfEwICUgoTAG8LDwBvDA8AbxMUAIwVAgCMFgIAvBMT8BEAAACfEwQCvBMTmxIAAACfEwICUg0TAG8ODwBvDw8AbxMVAIwVBACMFgYAvBMT8BEAAACfEwQCvBMTmxIAAACfEwICvBMTmxIAAACfEwICvBMTmxIAAACfEwICUhATAG8RDwBvEhYAcwQFErwCAmsXAAAAnwIDAYIAAQAYAx8DGgMbAyADIQMiAyMDJAMlAyYDJwQAAKBAAgAAAAAAAAAAAygDKQMqAysDLAMtAy4DLwMwAzEDMgBVAAEYAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAEAAAABAAABAAAAAQAAAQAAAAEAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJWAAAAAAsDAwAAAFipAwEATQQBwgAAAACkBQMAAgAQwPEEEAAFAAAAqQMAAE0EAcIAAAAApAUFAAQAEMCaBAkABQAAAE0EAbMGAAAApAUIAAcYEMDxBAIABQAAAKkDAAGpAwEADgM5AE0EAB0JAAAATQoA2QoAAABNCQqXCwAAAE0ICewMAAAATQcImA0AAABNBgeADgAAALwEBJcPAAAAnwQDAU0EAAAQAAAATQoA2QoAAABNCQqXCwAAAE0ICewMAAAATQcImA0AAABNBgflEQAAALwEBJcPAAAAnwQDAfsFAABNBAXREgAAAE0GAGkTAAAATQUGmxQAAABvBhUA4gcXAG8IGAAwCAdLFgAAAJ8EBAGkBBoAAACQQW8FGADZBgAAEgAAABICAQCfBAMBTQQAuxsAAAAOBAQAUgYBALwEAAocAAAAnwQDAfsFAgBNBAWCHQAAAFIFAABSBgEAUgcCAJ8EBAGCAAEAHgMzAzQDNQQCABDAAzYEBAAQwAM3AzgEBxgQwAMfAxoDGwM5AyEDIgMjAyQDJQM6AzsDPAIAAHAK2tv6QQM9BQEWAjMzMzMzM9M/Aw4EAACQQQMmAz4DPwEGSz8BGAAAAAAAAAABAAAAAAAAAAAAAAAAAAADAQAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAANAAABAAAAAwAAAAAAAAFNAAAAAAEBAAAAAAGCAAEAAABoQAEYAGgAAAAADgAAAQIAngGjAAAApAEBAAAAAEBNAAEkAgAAAKQBBAAAADBATQIAywUAAACfAQICpAIHAAAAYEBvBAgAvAICFgkAAACfAgMCpAMHAAAAYEBvBQoAvAMDFgkAAACfAwMCpAQEAAAAMEBNBgO9DAAAAE0FBiMLAAAAnwQCAqQFBAAAADBATQcDvQwAAABNBgfDDQAAAJ8FAgKkBgQAAAAwQE0IA0APAAAATQcISg4AAACfBgICpAcEAAAAMEBNCQOhEAAAAE0ICdIRAAAAnwcCAv8IAQAAAAAA4gkWAOIKGADiCx0AbwweADAMC4AZAAAATDYAAqQMIQAAgPCBnwwBAjAMC+UaAAAATDYAAqQMIQAAgPCBnwwBAjAMC40bAAAATDYAAqQMIQAAgPCBnwwBAjAMC18cAAAAMAsKmBcAAAAwCgm9EgAAAOIKGADiCx0AbwwiADAMC4AZAAAAbwwjADAMC+UaAAAATDYAAqQMIQAAgPCBnwwBAjAMC40bAAAATDYAAqQMIQAAgPCBnwwBAjAMC18cAAAAMAsKmBcAAAAwCgnsEwAAAKQKJQAAgECCnwoBAjAKCQ4UAAAApAolAACAQIKfCgECMAoJhRUAAAAwCQiXJgAAAMYJAAD/CgQAAAAAAG8LJwAwCwrlKAAAADAKCm4pAAAAnj0KBQEAAABSDAoAUg0BAKQLKwAAAKBCnwsDAdkLAAASAQn/EgAFABIABAASAAIAMAsKcywAAADACy0AEgABABIACAASAAoAMAsK7yAAAADACy4AMAsKti8AAADZCwMAEgAHABIBCf8SAAEAMAsKgjAAAADACzEAMAsKrzIAAADBCQAAggoCADMDQQQAAABAA0IDQwQAADBAA0QDRQQAAGBAA0YDRwNIA0kDSgNLA0wDTQNOA08DIAM5A1ADUQUEEhMUFQMhBQEXAyIDJQNSA1MFBBkaGxwHAAAAP83MTD8AAMC/AAAAAANUAwkEAIDwgQcAAAAAzcxMPwAAwL8AAAAABzpGcT8AAAAAAAAAAAAAAAADVQQAgECCAxsDVgNXA1gDEwQAAKBCAxIGBAYFAx4DPwYIA0AFAwQFBwgBAAEYAAEAAAABAAAAAAEAAAAAAAEAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAACAAEBAQEAAAEAAAAAAAEAAAAAAAEAAAAAAPwA/wAIAQEAAAEAAAEAAAAAAAEAAAAAAPwA/wAJAAAAAAEAAAAA7QAWAgABAAABAAEAAAAAAAABAAAAAAAAFQAAAAAACAAABgAAAAAAHQAAAgABAAAAAAmqGUmjvrRrN5jdIzdxsEwl2VvO57U0bkje6zB03HwvjCp2AKzKVavm

-- Decompiled by Krnl

local v1 = script.Parent
local v_u_2 = require(v1.Basic)
local v_u_3 = game:GetService("RunService")
local v4 = game:GetService("ReplicatedStorage")
local v_u_5 = require(v4.Game.ShockwaveScreenFx)
local v_u_6 = require(v4.Game.CharacterUtil)
require(v4.Module.R15IKv2)
local v_u_7 = require(v4.Std.Audio)
local v_u_8 = {}
local v9 = {}
local v10 = {
	["Springs"] = {
		["ItemOffset"] = Vector3.new(0.5, 0.8, -1.5),
		["ItemRotation"] = Vector3.new(),
		["NeckRotation"] = Vector3.new(),
		["WaistRotation"] = Vector3.new()
	}
}
v9.Hip = v10
local v11 = {
	["Springs"] = {
		["ItemOffset"] = Vector3.new(0, 0.8, -1.5),
		["ItemRotation"] = Vector3.new(0.9424778, 0, 0),
		["NeckRotation"] = Vector3.new(),
		["WaistRotation"] = Vector3.new()
	}
}
v9.Eat = v11
v9.RightWristRotation = CFrame.new()
v9.LeftWristRotation = CFrame.new()
v_u_8.Motion = v9
local v_u_12 = nil
local v_u_13 = {
	["__ClassName"] = "Juice"
}
v_u_13.__index = v_u_13
setmetatable(v_u_13, v_u_2)
function v_u_13.Init(p14)
	-- upvalues: (ref) v_u_12, (copy) v_u_6, (copy) v_u_5, (copy) v_u_3
	v_u_12 = p14.Event
	function p14.em.x642lsxe()
		-- upvalues: (ref) v_u_6, (ref) v_u_5, (ref) v_u_3
		v_u_6.IsJuiced = true
		v_u_6.WalkSpeedSpring:Accelerate(20)
		local v_u_15 = v_u_5.new()
		v_u_15._maid:GiveTask(v_u_3.Heartbeat:Connect(function()
			-- upvalues: (copy) v_u_15
			v_u_15:Update()
		end))
		v_u_15:SetActive(true)
		task.delay(3, function()
			-- upvalues: (copy) v_u_15, (ref) v_u_6
			v_u_15:SetActive(false)
			v_u_6.IsJuiced = false
			task.wait(5)
			v_u_15:Destroy()
		end)
	end
end
function v_u_13.new(p16, p17, p18)
	-- upvalues: (copy) v_u_2, (copy) v_u_8, (copy) v_u_13
	local v19 = v_u_2.new(p16, p17, v_u_8, p18)
	local v20 = v_u_13
	setmetatable(v19, v20)
	v19:DefaultDisableCamLock()
	return v19
end
function v_u_13.UpdateArmIK(p21)
	local v22 = p21.IK
	v22.RightArm = p21.Model.Skeleton.RightArm.Position
	v22.RightAngle = p21.Config.Motion.RightElbowAngle
end
function v_u_13.InputBegan(p_u_23, p24, p25)
	-- upvalues: (copy) v_u_7, (ref) v_u_12, (copy) v_u_2
	local v26
	if p24.UserInputType == Enum.UserInputType.MouseButton1 then
		v26 = true
	elseif p24.UserInputType == Enum.UserInputType.Gamepad1 then
		v26 = p24.KeyCode == Enum.KeyCode.ButtonR2
	else
		v26 = false
	end
	if v26 then
		p_u_23.SpringItemOffset:SetTarget(p_u_23.Config.Motion.Eat.Springs.ItemOffset)
		p_u_23.SpringItemRotation:SetTarget(p_u_23.Config.Motion.Eat.Springs.ItemRotation)
		v_u_7.ObjectLocal(p_u_23.Character.PrimaryPart, 7209853095, {
			["Volume"] = 0.3
		})
		delay(0.3, function()
			-- upvalues: (copy) p_u_23, (ref) v_u_12
			p_u_23.SpringItemOffset:SetTarget(p_u_23.Config.Motion.Hip.Springs.ItemOffset)
			p_u_23.SpringItemRotation:SetTarget(p_u_23.Config.Motion.Hip.Springs.ItemRotation)
			if p_u_23.Local then
				local v27 = tick()
				local v28 = p_u_23.LastConsumed or 0
				p_u_23.LastConsumed = v27
				if v27 - v28 < 5 then
					return false
				end
				v_u_12:FireServer("x" .. "" .. ("z6s0hx"):sub(2, 2):reverse():reverse():reverse() .. "" .. "" .. ("n4j"):sub(2, 2):reverse():reverse():reverse():reverse():reverse() .. "" .. "" .. ("i2z"):sub(2, 2):reverse() .. "" .. "" .. ("u8xxslw98x"):sub(4, 6):reverse():reverse():reverse() .. "e")
			end
		end)
		if p_u_23.Local then
			p_u_23:BroadcastInputBegan(p24)
		end
	end
	v_u_2.InputBegan(p_u_23, p24, p25)
end
function v_u_13.InputEnded(_) end
return v_u_13
