-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgN9AXgBeQF6BG1hdGgDc2luBkNGcmFtZQNuZXcDY29zDUZyb21BeGlzQW5nbGUJSm9pbnROZWNrC0pvaW50TmVja0MwAkMwCkpvaW50V2Fpc3QMSm9pbnRXYWlzdEMwDHNldG1ldGF0YWJsZQZDb25maWcSaW52ZW50b3J5SXRlbVZhbHVlBE1haWQIR2l2ZVRhc2sPQnVpbGRQYWNrZXRBcm1zCUNoYXJhY3RlcgJJSwtJc0VxdWlwcGluZwpTZXR1cE1vZGVsE0F0dGFjaE1vZGVsVG9QbGF5ZXIMU2V0dXBTcHJpbmdzBUVxdWlwCUhlYXJ0YmVhdAdTdGVwcGVkB2dldE5hbWUMZ2V0RXF1aXBUaW1lDkdVTl9FUVVJUF9USU1FFWdldFNob3VsZEFkZEVxdWlwVGltZRlTdGFydFJlbG9hZFByb2dyZXNzQ2lyY2xlBG1haWQEdGFzawVkZWxheQdDb25uZWN0BUxvY2FsEFNwcmluZ0l0ZW1PZmZzZXQERGFtcARGcmVxBk1vdGlvbgNIaXAHU3ByaW5ncwpJdGVtT2Zmc2V0CVNldFRhcmdldAdWZWN0b3IzElNwcmluZ0l0ZW1Sb3RhdGlvbgxJdGVtUm90YXRpb24SU3ByaW5nTmVja1JvdGF0aW9uDE5lY2tSb3RhdGlvbhNTcHJpbmdXYWlzdFJvdGF0aW9uDVdhaXN0Um90YXRpb24FTW9kZWwHRGVzdHJveQhSZXNvdXJjZQpJdGVtU3lzdGVtBk1vZGVscw5GaW5kRmlyc3RDaGlsZAVlcnJvciJDb3VsZCBub3QgZmluZCBtb2RlbCBmb3IgaXRlbSBgJXNgBmZvcm1hdAVDbG9uZQZDZW50ZXIIU2tlbGV0b24JV2VsZEFsbFRvBU1vdG9yClVwcGVyVG9yc28KQmxhbmtNb3RvcgVJdGVtcwl3b3Jrc3BhY2UGUGFyZW50D1RPRE86IEltcGxlbWVudApTd2luZ0x1bmdlC1N3aW5nU3dvb3NoBlVwZGF0ZQJDMQhSaWdodEFybQRBcm1zCUxlZnRXcmlzdAlUcmFuc2Zvcm0KUmlnaHRXcmlzdAZBbmdsZXMHTGFzdFVzZQxHZXRBdHRyaWJ1dGULX2dldExhc3RVc2UQR2V0U2VydmVyVGltZU5vdwpSZWxvYWRUaW1lDFNldEF0dHJpYnV0ZQ9zZXRMYXN0U2hvdFRpbWUGUGxheWVyBnJhbmRvbRNCcm9hZGNhc3RJbnB1dEJlZ2FuBVN3aW5nClNob290QmVnaW4NVXNlcklucHV0VHlwZQRFbnVtDE1vdXNlQnV0dG9uMQhHYW1lcGFkMQdLZXlDb2RlCEJ1dHRvblIyCklucHV0QmVnYW4KSW5wdXRFbmRlZARnYW1lClJ1blNlcnZpY2UKR2V0U2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQdyZXF1aXJlBEdhbWUHR3VuU2hvcAhHdW5VdGlscw9HdW5TeXN0ZW1Db25zdHMDU3RkBUpvaW50BlNwcmluZwdSMTVJS3YyBk1vZHVsZRJJbnZlbnRvcnlJdGVtVXRpbHMJSW52ZW50b3J5BnNjcmlwdARJdGVtBU1lbGVlC19fQ2xhc3NOYW1lB19faW5kZXgAFg8BAQAAACZNAQCZAAAAAE0CAJgBAAAATQMAmwIAAAAJBwEBCQgCAkMGBwgJBwMDQwUGBwQEBQNvBQQAYAUWAAQAAABbBwQDuxgHAqQGBwAAGFCAnwYCAuwFBgSkBgoAACSAgIwHAACMCAAAjAkAAAkKBQEJCwUCCQwFA1sOBAO7CQ4CpA0MAAAsUICfDQICnwYIAIIGAAD7BQAAggUCAA0DAQMCAwMCAAAAAAAA4D8C8WjjiLX45D4DBAMFBAAYUIADBgMHBAAkgIADCAQALFCAAA8JARgAAAAAAAABAAAAAAABAAABAAAAAAABAAAAAAAAAAAAAAAAAAACABAAAAAAAwABAAAAEfsBAABNAAGKAAAAAPsCAABNAQKVAQAAADABAO0CAAAA+wEAAE0AAa0DAAAA+wIAAE0BAkMEAAAAMAEA7QIAAACCAAEABQMKAwsDDAMNAw4AKQABGAAAAAAAAAAAAQAAAAAAAAABKgAAAAAIBAMAAAA9+wUAAE0EBe8AAAAAUgUAAFIGAwCfBAMC+wcBAJ49BAQHAAAAUgYEAKQFAgAAABBAnwUDATACBNkDAAAAMAEE/wQAAABNBgSKBQAAAE0FBu0GAAAAMAUElQcAAABNBgStCAAAAE0FBu0GAAAAMAUEQwkAAABNBQR2CgAAANkHAAASAAQAvAUF/QsAAACfBQMB+wYCAE0FBu8MAAAATQYEaQ0AAACfBQICMAUEAg4AAACpBQAAMAUEgw8AAAC8BQQ8EAAAAJ8FAgG8BQQkEQAAAJ8FAgFSBwMAvAUErhIAAACfBQMBvAUEzBMAAACfBQIBggQCABQDBwMPBAAAEEADEAMRAwoDDAMLAw0DDgMSAxMDFAMVAxYDFwMYAxkDGgMbAQEgBwEYAAAAAAAAAQAAAAAAAAIAAQACAAAAAAABAAAAAAABAAAAAAAABQAAAAAAAAABAAACAAABAAABAAAAAQAAAiEAAAAAAgABAAAABfsAAACpAQAAMAEAgwAAAACCAAEAAQMXAD8AARgAAAAAAUAAAAAAAgABAAAABfsAAAC8AAD9AAAAAJ8AAgGCAAEAAQMcAEQAARgAAAAAAUUAAAAAAgABAAAABfsAAAC8AADZAAAAAJ8AAgGCAAEAAQMdAEcAARgAAAAAAUgAAAAACQEEAAAARfsCAABNAQK2AAAAAE0CAP8BAAAAnwECAvsDAQBNAgPuAgAAAFIDAQCfAgICKwIDAPsDAgBNAgN5AwAAAPsEAQBNAwQvBAAAAFIEAACfAwICDgMVAIwEAABgBBMAAgAAAKkEAQAwBACDBQAAAFIGAgC8BACFBgAAAJ8EAwFNBAAWBwAAAKQGCgAAJICAUgcCANkIAAASAAAAnwYDALwEBP0LAAAAnwQAAU0EAHYMAAAA+wcDAE0GB/0NAAAA2QgBABIAAAC8BgbHDgAAAJ8GAwC8BAT9CwAAAJ8EAAFNBAB2DAAAAPsHAwBNBgfZDwAAANkIAgASAAAAvAYGxw4AAACfBgMAvAQE/QsAAACfBAABggABABADHgMRAx8DIAMhAxcDIgMjAyQDJQQAJICAAxMDEgMcAyYDHQMDBAU4GwEYAAAAAAAAAQAAAAAAAAAAAQAAAAABAAAAAQAAAQAAAAEAAAAAAAAAAAAABQAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAADOQAAAAAJAgEAAADtAU0CALsAAAAADgIiAA4BIQBNAgEdAQAAAA4CHgBNAgEdAQAAADACAB0BAAAATQIAHQEAAABvAwIAMAMCiAMAAABNAgAdAQAAAIwDCAAwAwK1BAAAAE0CAB0BAAAATQgA2QUAAABNBwiXBgAAAE0GB70HAAAATQUGmAgAAABNBAWACQAAALwCApcKAAAAnwIDAWUAFgD7AwAATQID7wsAAABNBwDZBQAAAE0GB5cGAAAATQUGvQcAAABNBAWYCAAAAE0DBIAJAAAATDYAAqQEDQAALMCAnwQBAm8FAgCMBggAnwIFAjACAB0BAAAATQIAuwAAAAAOAiIADgEhAE0CAQAOAAAADgIeAE0CAQAOAAAAMAIAAA4AAABNAgAADgAAAG8DAgAwAwKIAwAAAE0CAAAOAAAAjAMIADADArUEAAAATQIAAA4AAABNCADZBQAAAE0HCJcGAAAATQYHvQcAAABNBQaYCAAAAE0EBeUPAAAAvAIClwoAAACfAgMBZQAWAPsDAABNAgPvCwAAAE0HANkFAAAATQYHlwYAAABNBQa9BwAAAE0EBZgIAAAATQME5Q8AAABMNgACpAQNAAAswICfBAECbwUCAIwGCACfAgUCMAIAAA4AAABNAgC7AAAAAA4CIgAOASEATQIBgxAAAAAOAh4ATQIBgxAAAAAwAgCDEAAAAE0CAIMQAAAAbwMCADADAogDAAAATQIAgxAAAACMAwgAMAMCtQQAAABNAgCDEAAAAE0IANkFAAAATQcIlwYAAABNBge9BwAAAE0FBpgIAAAATQQFjREAAAC8AgKXCgAAAJ8CAwFlABYA+wMAAE0CA+8LAAAATQcA2QUAAABNBgeXBgAAAE0FBr0HAAAATQQFmAgAAABNAwSNEQAAAEw2AAKkBA0AACzAgJ8EAQJvBQIAjAYIAJ8CBQIwAgCDEAAAAE0CALsAAAAADgIiAA4BIQBNAgESEgAAAA4CHgBNAgESEgAAADACABISAAAATQIAEhIAAABvAwIAMAMCiAMAAABNAgASEgAAAIwDCAAwAwK1BAAAAE0CABISAAAATQgA2QUAAABNBwiXBgAAAE0GB70HAAAATQUGmAgAAABNBAVfEwAAALwCApcKAAAAnwIDAYIAAQD7AwAATQID7wsAAABNBwDZBQAAAE0GB5cGAAAATQUGvQcAAABNBAWYCAAAAE0DBF8TAAAATDYAAqQEDQAALMCAnwQBAm8FAgCMBggAnwIFAjACABISAAAAggABABQDJwMoAjMzMzMzM+s/AykDKgMQAysDLAMtAy4DLwMHAzAEACzAgAMxAzIDMwM0AzUDNgBLGgEYAAAAAAAAAAEAAAABAAAAAAEAAAAAAQAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAQAAAAEAAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAABAAAAAQAAAAABAAAAAAEAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAEAAAABAAAAAAEAAAAAAQAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAACTgAAAAACAAEAAAAL+wEAAE0AATsAAAAAvAAAUAEAAACfAAIB+wAAAMYBAAAwAQA7AAAAAIIAAQACAzcDOACAAQABGAAAAAAAAAEAAAABgQAAAAAHAQMAAAcAAAEDBBcCNfsCAABNAQK2AAAAAE0CAP8BAAAAnwECAvsFAQBNBAViAgAAAE0DBPADAAAATQID+AQAAABSBAEAvAICAwUAAACfAgMCRwIJAAAAAICkAwcAAABgQG8ECABSBgEAvAQEjQkAAACfBAMAnwMAAbwDAjoKAAAAnwMCAlICAwAwAgA7CwAAAE0EAkYNAAAATQME6gwAAAAwAwDqDAAAAPsFAgBNBAV/DgAAAFIFAgBSBgMAnwQDAU0EAHYPAAAA2QYAABIAAAC8BAT9EAAAAJ8EAwGCAAEAEQMeAxEDOQM6AzsDPAM9BAAAYEADPgM/A0ADNwNBA0IDQwMSAxMBCHMYARgAAAAAAAABAAAAAAAAAAAAAAEAAQAAAAAAAAACAAAAAQACAAAAAQABAAAAAAACAAAAAAAABHQAAAAAAgABAAAAC/sBAABNAAHWAAAAALwAAFABAAAAnwACAfsAAADGAQAAMAEA1gAAAACCAAEAAgNEAzgAjAEAARgAAAAAAAABAAAAAY0AAAAABgEBAAAAIU0BAFUAAAAATQIA6gEAAABNAwGFAgAAADADAoUCAAAA+wMAAE0CA4EDAAAATQMA6gEAAABSBAEAnwIDAk0DADsEAAAApAUHAAAAYEBNBAU4BQAAADAEAyQIAAAAMAIA1gkAAABNAwB2CgAAANkFAAASAAAAvAMD/QsAAACfAwMBggABAAwDRQNBAwYDRgM3A0cDSAQAAGBAA0kDRAMSAxMBCoUBGQEYAAABAAAAAAABAAAAAAAAAQAAAAAAAAABAAIAAAAAAAAEhgAAAAADAQAAAAAFpAEBAAAAAEBvAgIAnwECAYIAAQADAz0EAAAAQANKAJEBSwEYAAAAAAGSAAAAAAMBAAAAAAWkAQEAAAAAQG8CAgCfAQIBggABAAMDPQQAAABAA0oAlAFMARgAAAAAAZUAAAAADAEBAAAAQU0BAB0AAAAAvAEBJgEAAACfAQICTQIAAAIAAAC8AgImAQAAAJ8CAgL7AwAAUgQCAJ8DAgJNBADWAwAAAKQIBgAAFECAUgkBAJ8IAgIJBwgDpAgGAAAUQIBvCQcAjAoBAG8LCACfCAQCCQYHCE0IAK0JAAAATQcIzAoAAAAJBQYHMAUEzAoAAABNBAASCwAAALwEBCYBAAAAnwQCAk0FAK0JAAAATQcAQwwAAAD7CAAAUgkEAJ8IAgIJBgcIMAYF7Q0AAABNBQCDDgAAALwFBSYBAAAAnwUCAk0GAIoPAAAATQgAlRAAAAD7CQAAUgoFAJ8JAgIJBwgJMAcG7Q0AAACCAAEAEQMoA00DMQNEAwYDBwQAFECAApqZmZmZmfk/AgAAAAAAAPi/Aw0DTgM1Aw4DDAMzAwoDCwCXARwBGAAAAAAAAQAAAAABAAABAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAEAAAAAAAAAAAACAAAAAAEAAAAAAAAAAAABmAAAAAAHAQEAAAcAAAEIBAcBIU0BAAIAAAAATQQA6gEAAABNAwSFAgAAAG8EAwAJAgMEMAIBkQQAAAD7AwAATQIDzAUAAABSAwEAnwICAU0CAfwGAAAApAMIAAAcIICfAwECMAMCIQkAAABNAgFtCgAAAKQDDAAALCCAjAQAAG8FDQCMBgAAnwMEAjADAiEJAAAAggABAA4DFgNBAwYHAAAAAAAAAADNzEw+AAAAAANPA1ADUQMHBAAcIIADUgNTA1QEACwggAIzMzMzMzPTvwCjAR0BGAAAAQAAAAAAAAACAAAAAAEAAAAAAAABAAAAAAAAAAAAAaQAAAAABQEAAAAACE0CADsBAAAAbwQCALwCAhIDAAAAnwIDApABAgCCAQIABAIAAAAAAAAAAAM3A1UDVgCrAVcBGAAAAAAAAAAArAAAAAAHAgEAAAA5TQIAgwAAAAAOAgIAqQIAAIICAgCkAgIAAAAQQLwCArcDAAAAnwICArwEAC0EAAAAnwQCAiYDAgRNBQDZBQAAAE0EBbwGAAAAYAMDAAQAAACpAwAAggMCAE0DADsHAAAAbwUIAFIGAgC8AwMuCQAAAJ8DBAH7BAAATQME9goAAABNBAD5CwAAAFIFAgCfAwMBpAMOAAA0wICfAwECbwQPAGAEBQADAAAAvAMA2xAAAACfAwIBZQADALwDAM4RAAAAnwMCAU0DALsSAAAADgMEAFIFAQC8AwAKEwAAAJ8DAwGCAAEAFAMXA0gEAAAQQANYA1cDEANZAzcDVQNaA1sDXAMEA10EADTAgAKamZmZmZnpPwNLA0wDJwNeAK4BXwEYAAAAAQACAAAAAAEAAAAAAAAAAAABAAIAAAAAAAABAAAAAAAAAQAAAAAAAQAAAAIAAAIAAAEAAAACrwAAAAAFAgAAAAAFUgQBALwCAGEAAAAAnwIDAYIAAQABA18AwQFgARgAAAAAAcIAAAAACAMBAAAAI6kDAQBNBAHCAAAAAKQFAwACABDA8QQQAAUAAACpAwAATQQBwgAAAACkBQUABAAQwJoECQAFAAAATQQBswYAAACkBQgABxgQwPEEAgAFAAAAqQMAAakDAQAOAwQAUgYBALwEANYJAAAAnwQDAfsFAABNBAWCCgAAAFIFAABSBgEAUgcCAJ8EBAGCAAEACwNhA2IDYwQCABDAA2QEBAAQwANlA2YEBxgQwANgA2cAxAFnARgAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAgEAAAACAAAAAAAAAcYAAAAAAwMAAAAAAYIAAQAAAM4BaAEYAM4AAAAAEAAAAQIAkgGjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIGAAAAUEBNBQG9BwAAAE0EBQYIAAAATQMEWQkAAACfAgICpAMGAAAAUEBNBgG9BwAAAE0FBvAKAAAATQQFSQsAAACfAwICpAQGAAAAUEBNBgGhDAAAAE0FBgwNAAAAnwQCAqQFBgAAAFBATQcBoQwAAABNBgciDgAAAJ8FAgKkBgYAAABQQE0IAUAQAAAATQcISg8AAACfBgICpAcGAAAAUEBNCQFgEgAAAE0ICXcRAAAAnwcCAqQJFAAAADBBTQgJJBUAAACkCQYAAABQQE0KCMoWAAAAnwkCAqQKGQAAYHCBnwoBAsALGgASAAoA/wwFAAAAAABvDRsAMA0M5RwAAAAwDAxuHQAAAJ49DAUJAAAAUg4MAFIPCQCkDR8AAADgQZ8NAwHADSAAEgAJABIADAASAAYAMA0M7xgAAADADSEAEgAHABIAAgASAAMAEgAAADANDMwiAAAAwA0jABIABQAwDQyuJAAAAMANJQASAAcAEgABABIABAAwDQw8JgAAAMANJwASAAQAMA0MJCgAAADADSkAMA0M2yoAAADADSsAMA0MziwAAADADS0AEgALADANDP0uAAAAwA0vABIABgAwDQzZMAAAAMANMQAwDQwtMgAAAMANMwASAAIAMA0MYTQAAADADTUAMA0M1jYAAADADTcAEgAJADANDII4AAAAwA05ADANDK86AAAAggwCADsDaQQAAABAA2oDawNsA20EAABQQANuA28DcAM6A3EDcgNzA3QDdQN2A3cDeAN5BAAAMEEDSQN6AwYDBwQAYHCBBgADewN8A30DDwQAAOBBBgIGBgMbBgcDGgYJAxgGCwMZBgwDSwYNA0wGDgMcBg8DHQYQA1cGEQNfBhIDYAYTA2cGFANoDwACBgcJCwwNDg8QERITFAEAARgAAQAAAAAAAQAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAIAAAABAAAAAAIAAAEADQABAAABAAEAAAAAAAABAAAAAAAYAAAAAAAAEwAAACgAAAAAABIAAAAMAAADAAADAAAADAAAAAgAAAMAAAATAAADAAAACgAAAgEAAAAAFY9r9J9L5m5eva+eC9NwR5bDPmNFahkhtPSnicZSHt5tg3RKXwklilE=

-- Decompiled by Krnl

local v_u_1 = game:GetService("RunService")
local v_u_2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v_u_2.Game.GunShop.GunUtils)
local v_u_4 = require(v_u_2.Game.ItemSystem.GunSystemConsts)
local v_u_5 = require(v_u_2.Std.Joint)
local v_u_6 = require(v_u_2.Std.Spring)
local v_u_7 = require(v_u_2.Module.R15IKv2)
local v_u_8 = require(v_u_2.Inventory.InventoryItemUtils)
local v9 = script.Parent
local v_u_10 = require(v9.Item)
local v_u_11 = CFrame.new()
local function v_u_24(p12)
	-- upvalues: (copy) v_u_11
	local v13 = p12.x
	local v14 = p12.y
	local v15 = p12.z
	local v16 = (v13 * v13 + v14 * v14 + v15 * v15) ^ 0.5
	if v16 <= 0.00001 then
		return v_u_11
	end
	local v17 = v16 * 0.5
	local v18 = math.sin(v17) / v16
	local v19 = CFrame.new
	local v20 = v18 * v13
	local v21 = v18 * v14
	local v22 = v18 * v15
	local v23 = v16 * 0.5
	return v19(0, 0, 0, v20, v21, v22, (math.cos(v23)))
end
local v_u_25 = {
	["__ClassName"] = "Melee"
}
v_u_25.__index = v_u_25
setmetatable(v_u_25, v_u_10)
function v_u_25.new(p26, p27, p28, p29)
	-- upvalues: (copy) v_u_10, (copy) v_u_25, (copy) v_u_7
	local v_u_30 = v_u_10.new(p26, p29)
	local v31 = v_u_25
	setmetatable(v_u_30, v31)
	v_u_30.Config = p28
	v_u_30.inventoryItemValue = p27
	v_u_30.JointNeckC0 = v_u_30.JointNeck.C0
	v_u_30.JointWaistC0 = v_u_30.JointWaist.C0
	v_u_30.Maid:GiveTask(function()
		-- upvalues: (copy) v_u_30
		v_u_30.JointNeck.C0 = v_u_30.JointNeckC0
		v_u_30.JointWaist.C0 = v_u_30.JointWaistC0
	end)
	v_u_30.IK = v_u_7.BuildPacketArms(v_u_30.Character)
	v_u_30.IsEquipping = false
	v_u_30:SetupModel()
	v_u_30:AttachModelToPlayer()
	v_u_30:SetupSprings(p29)
	v_u_30:Equip()
	return v_u_30
end
function v_u_25.Equip(p_u_32)
	-- upvalues: (copy) v_u_8, (copy) v_u_3, (copy) v_u_4, (copy) v_u_1
	local v33 = v_u_8.getName(p_u_32.inventoryItemValue)
	local v34 = v_u_3.getEquipTime(v33) or v_u_4.GUN_EQUIP_TIME
	if v_u_3.getShouldAddEquipTime(p_u_32) and v34 > 0 then
		p_u_32.IsEquipping = true
		p_u_32:StartReloadProgressCircle(v34)
		p_u_32.maid:GiveTask(task.delay(v34, function()
			-- upvalues: (copy) p_u_32
			p_u_32.IsEquipping = false
		end))
	end
	p_u_32.Maid:GiveTask(v_u_1.Heartbeat:Connect(function()
		-- upvalues: (copy) p_u_32
		p_u_32:Heartbeat()
	end))
	p_u_32.Maid:GiveTask(v_u_1.Stepped:Connect(function()
		-- upvalues: (copy) p_u_32
		p_u_32:Stepped()
	end))
end
function v_u_25.SetupSprings(p35, p36)
	-- upvalues: (copy) v_u_6
	if p35.Local and (p36 and p36.SpringItemOffset) then
		p35.SpringItemOffset = p36.SpringItemOffset
		p35.SpringItemOffset.Damp = 0.85
		p35.SpringItemOffset.Freq = 8
		p35.SpringItemOffset:SetTarget(p35.Config.Motion.Hip.Springs.ItemOffset)
	else
		p35.SpringItemOffset = v_u_6.new(p35.Config.Motion.Hip.Springs.ItemOffset, Vector3.new(), 0.85, 8)
	end
	if p35.Local and (p36 and p36.SpringItemRotation) then
		p35.SpringItemRotation = p36.SpringItemRotation
		p35.SpringItemRotation.Damp = 0.85
		p35.SpringItemRotation.Freq = 8
		p35.SpringItemRotation:SetTarget(p35.Config.Motion.Hip.Springs.ItemRotation)
	else
		p35.SpringItemRotation = v_u_6.new(p35.Config.Motion.Hip.Springs.ItemRotation, Vector3.new(), 0.85, 8)
	end
	if p35.Local and (p36 and p36.SpringNeckRotation) then
		p35.SpringNeckRotation = p36.SpringNeckRotation
		p35.SpringNeckRotation.Damp = 0.85
		p35.SpringNeckRotation.Freq = 8
		p35.SpringNeckRotation:SetTarget(p35.Config.Motion.Hip.Springs.NeckRotation)
	else
		p35.SpringNeckRotation = v_u_6.new(p35.Config.Motion.Hip.Springs.NeckRotation, Vector3.new(), 0.85, 8)
	end
	if p35.Local and (p36 and p36.SpringWaistRotation) then
		p35.SpringWaistRotation = p36.SpringWaistRotation
		p35.SpringWaistRotation.Damp = 0.85
		p35.SpringWaistRotation.Freq = 8
		p35.SpringWaistRotation:SetTarget(p35.Config.Motion.Hip.Springs.WaistRotation)
	else
		p35.SpringWaistRotation = v_u_6.new(p35.Config.Motion.Hip.Springs.WaistRotation, Vector3.new(), 0.85, 8)
	end
end
function v_u_25.SetupModel(p_u_37)
	-- upvalues: (copy) v_u_8, (copy) v_u_2, (copy) v_u_5
	local v38 = v_u_8.getName(p_u_37.inventoryItemValue)
	local v39 = v_u_2.Resource.ItemSystem.Models:FindFirstChild(v38)
	if v39 == nil then
		error(("Could not find model for item `%s`"):format(v38))
	end
	local v40 = v39:Clone()
	p_u_37.Model = v40
	local v41 = v40.Skeleton.Center
	p_u_37.Center = v41
	v_u_5.WeldAllTo(v40, v41)
	p_u_37.Maid:GiveTask(function()
		-- upvalues: (copy) p_u_37
		p_u_37.Model:Destroy()
		p_u_37.Model = nil
	end)
end
function v_u_25.AttachModelToPlayer(p_u_42)
	-- upvalues: (copy) v_u_5
	local v43 = p_u_42.UpperTorso
	p_u_42.Center.CFrame = v43.CFrame
	local v44 = v_u_5.BlankMotor(p_u_42.Center, v43)
	p_u_42.Model.Parent = workspace.Items
	p_u_42.Motor = v44
	p_u_42.Maid:GiveTask(function()
		-- upvalues: (copy) p_u_42
		p_u_42.Motor:Destroy()
		p_u_42.Motor = nil
	end)
end
function v_u_25.SwingLunge(_)
	error("TODO: Implement")
end
function v_u_25.SwingSwoosh(_)
	error("TODO: Implement")
end
function v_u_25.Heartbeat(p45)
	-- upvalues: (copy) v_u_24
	local v46 = p45.SpringItemOffset:Update()
	local v47 = v_u_24((p45.SpringItemRotation:Update()))
	p45.Motor.C1 = CFrame.new(v46) * v47 * CFrame.new(1.6, 1, -1.5) * p45.JointWaist.C1
	local v48 = p45.SpringWaistRotation:Update()
	p45.JointWaist.C0 = p45.JointWaistC0 * v_u_24(v48)
	local v49 = p45.SpringNeckRotation:Update()
	p45.JointNeck.C0 = p45.JointNeckC0 * v_u_24(v49)
end
function v_u_25.Stepped(p50)
	-- upvalues: (copy) v_u_7
	local v51 = p50.IK
	v51.RightArm = p50.Center.CFrame * Vector3.new(0, 0, 0.2)
	v_u_7.Arms(v51)
	v51.LeftWrist.Transform = CFrame.new()
	v51.RightWrist.Transform = CFrame.Angles(0, -0.3, 0)
end
function v_u_25._getLastUse(p52)
	return p52.Model:GetAttribute("LastUse") or 0
end
function v_u_25.Swing(p53, p54)
	-- upvalues: (copy) v_u_3
	if p53.IsEquipping then
		return false
	end
	local v55 = workspace:GetServerTimeNow()
	if v55 - p53:_getLastUse() < p53.Config.ReloadTime then
		return false
	end
	p53.Model:SetAttribute("LastUse", v55)
	v_u_3.setLastShotTime(p53.Player, v55)
	if math.random() > 0.8 then
		p53:SwingLunge()
	else
		p53:SwingSwoosh()
	end
	if p53.Local then
		p53:BroadcastInputBegan(p54)
	end
end
function v_u_25.ShootBegin(p56, p57)
	p56:Swing(p57)
end
function v_u_25.InputBegan(p58, p59, p60)
	-- upvalues: (copy) v_u_10
	local v61
	if p59.UserInputType == Enum.UserInputType.MouseButton1 then
		v61 = true
	elseif p59.UserInputType == Enum.UserInputType.Gamepad1 then
		v61 = p59.KeyCode == Enum.KeyCode.ButtonR2
	else
		v61 = false
	end
	if v61 then
		p58:ShootBegin(p59)
	end
	v_u_10.InputBegan(p58, p59, p60)
end
function v_u_25.InputEnded(_, _, _) end
return v_u_25
