-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMrA25ldwxzZXRtZXRhdGFibGUJQXBwbHlTa2luBVNldHVwElNldHVwQnVsbGV0RW1pdHRlcg1CdWxsZXRFbWl0dGVyBkNvbG9yMwdmcm9tUkdCBUNvbG9yC09iamVjdExvY2FsA1RpcAZDb25maWcFU291bmQLYnVsbGV0X2Nhc2UGVm9sdW1lBVBpdGNoBG1hdGgGcmFuZG9tBXNob290BWRlbGF5ClNob290U291bmQUUmVsb2FkRHJvcEFtbW9WaXN1YWwWUmVsb2FkUmVmaWxsQW1tb1Zpc3VhbAtyZWxvYWRfb3BlbhJSb2xsT2ZmTWF4RGlzdGFuY2UTUmVsb2FkRHJvcEFtbW9Tb3VuZA1idWxsZXRfaW5zZXJ0BHdhaXQMcmVsb2FkX2Nsb3NlDWN5bGluZGVyX3NwaW4VUmVsb2FkUmVmaWxsQW1tb1NvdW5kBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZAVBdWRpbwZzY3JpcHQGUGFyZW50A0d1bgxOZXJmUmV2b2x2ZXILX19DbGFzc05hbWUHX19pbmRleAAJBwMCAAAAFvsEAABNAwTvAAAAAFIEAABSBQEAUgYCAJ8DBAL7BgEAnj0DBAYAAABSBQMApAQCAAAAEECfBAMBqQQAADAEA+kDAAAAUgYCALwEA5kEAAAAnwQDAYIDAgAFAwEDAgQAABBAAwMDBAAMAQEYAAAAAAAAAAEAAAAAAAABAAABAAAAAg0AAAAABgEBAAAAEPsCAABNAQJKAAAAAFICAACfAQIBTQEAZwEAAACkAgQAAAwggIwDMgCMBP8AjAUyAJ8CBAIwAgGkBQAAAIIAAQAGAwUDBgMHAwgEAAwggAMJABQFARgAAAAAAAEAAAAAAAAAAAABFQAAAAAJAAIAAAAc+wEAAE0AAdEAAAAA+wIBAE0BArEBAAAA+wUBAE0EBdkCAAAATQMEbgMAAABNAgO3BAAAAOIDBwBvBAgAMAQDSwUAAACMBgEApAgNAAAwsICfCAECWwcICkMFBgd4BAUJMAQDAAYAAACfAAQBggABAA4DCgMLAwwDDQMOAw8DEAUCBQYCmpmZmZmZ2T8CmpmZmZmZqT8CmpmZmZmZuT8DEQMSBAAwsIAAGwABGAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAA/QUcAAAAAAcCAQAAABkrARcA+wMAAE0CA9EAAAAATQMAsQEAAABNBgDZAgAAAE0FBm4DAAAATQQFyAQAAADiBQYAjAYBADAGBQAFAAAAnwIEAaQCCAAAAHBAbwMJANkEAAASAgAAEgAAAJ8CAwGCAAEACgMKAwsDDAMNAxMDEAUBBQMUBAAAcEACmpmZmZmZuT8BAhgVARgAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAIGQAAAAABAQAAAAABggABAAAAJBYBGAAkAAAAAAEBAAAAAAGCAAEAAAAlFwEYACUAAAAABgEBAAAAEfsCAABNAQLRAAAAAE0CALEBAAAATQUA2QIAAABNBAVuAwAAAE0DBP8EAAAA4gQGAIwFgQAwBQQqBQAAAJ8BBAGCAAEABwMKAwsDDAMNAxgDGQUBBQAmGgEYAAAAAAAAAAAAAAAAAQAA/wMnAAAAAAkBAQAAAD6MAwEAjAEEAIwCAQCoARUA+wUAAE0EBdEAAAAATQUAsQEAAABNCADZAgAAAE0HCG4DAAAATQYHnAQAAADiBwYAjAiBADAIByoFAAAAnwQEAaQECAAAAHBAbwUJAJ8EAgGLAev/+wIAAE0BAtEAAAAATQIAsQEAAABNBQDZAgAAAE0EBW4DAAAATQMETgoAAADiBAYAjAWBADAFBCoFAAAAnwEEAaQBCAAAAHBAbwIJAJ8BAgH7AgAATQEC0QAAAABNAgCxAQAAAE0FANkCAAAATQQFbgMAAABNAwTPCwAAAOIEBgCMBYEAMAUEKgUAAACfAQQBggABAAwDCgMLAwwDDQMbAxkFAQUDHAQAAHBAApqZmZmZmck/Ax0DHgArHwEYAAAAAAEAAAAAAAAAAAAAAAEAAP8DAAAA/AYAAAAAAAAAAAAAAAEAAP8DAAAAAQAAAAAAAAAAAAAAAQAA/wMsAAAAAAgAAAECAEGjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CA9IHAAAAnwECAqQDCQAAAIBATQIDJAoAAACkAwUAAABAQE0EAg0LAAAAnwMCAv8EBQAAAAAAbwUMADAFBOUNAAAAMAQEbg4AAACePQQFAwAAAFIGBABSBwMApAUQAAAA8ECfBQMBwAURABIAAwASAAQAMAUE7xIAAADABRMAEgADADAFBEoUAAAAwAUVABIAAQAwBQS5FgAAAMAFFwAwBQR/GAAAAMAFGQAwBQQCGgAAAMAFGwASAAEAMAUEvRwAAADABR0AEgABADAFBHkeAAAAggQCAB8DIAQAAABAAyEDIgMjBAAAQEADJAMlAyYEAACAQAMnAygDKQMqAysDAgQAAPBABgADAQYBAwUGAwMVBgQDFgYFAxcGBgMaBgcDHwcAAQMEBQYHAQABGAABAAAAAAABAAAAAAAAAgAAAAEAAAAAAgABAAABAAEAAAAAAAABAAAAAAgAAAAEAAAADAAAAQAAAQAAAAUAAAAQAQAAAAAIeMnsxuqXsxxKDYZSIOHBzA+BmrYNNZOl4us3miXE3GxDAOVbrnH3tQ==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.Audio)
local v3 = script.Parent
local v_u_4 = require(v3.Gun)
local v_u_5 = {
	["__ClassName"] = "NerfRevolver"
}
v_u_5.__index = v_u_5
setmetatable(v_u_5, v_u_4)
function v_u_5.new(p6, p7, p8)
	-- upvalues: (copy) v_u_4, (copy) v_u_5
	local v9 = v_u_4.new(p6, p7, p8)
	local v10 = v_u_5
	setmetatable(v9, v10)
	v9.ApplySkin = false
	v9:Setup(p8)
	return v9
end
function v_u_5.SetupBulletEmitter(p11)
	-- upvalues: (copy) v_u_4
	v_u_4.SetupBulletEmitter(p11)
	p11.BulletEmitter.Color = Color3.fromRGB(50, 255, 50)
end
function v_u_5.ShootSound(p_u_12, p13)
	-- upvalues: (copy) v_u_2
	if not p13 then
		v_u_2.ObjectLocal(p_u_12.Tip, p_u_12.Config.Sound.shoot, {
			["Pitch"] = 1
		})
		delay(0.1, function()
			-- upvalues: (ref) v_u_2, (copy) p_u_12
			v_u_2.ObjectLocal(p_u_12.Tip, p_u_12.Config.Sound.bullet_case, {
				["Volume"] = 0.4,
				["Pitch"] = 1 + math.random() * 0.1 - 0.05
			})
		end)
	end
end
function v_u_5.ReloadDropAmmoVisual(_) end
function v_u_5.ReloadRefillAmmoVisual(_) end
function v_u_5.ReloadDropAmmoSound(p14)
	-- upvalues: (copy) v_u_2
	v_u_2.ObjectLocal(p14.Tip, p14.Config.Sound.reload_open, {
		["RollOffMaxDistance"] = 129
	})
end
function v_u_5.ReloadRefillAmmoSound(p15)
	-- upvalues: (copy) v_u_2
	for _ = 1, 4 do
		v_u_2.ObjectLocal(p15.Tip, p15.Config.Sound.bullet_insert, {
			["RollOffMaxDistance"] = 129
		})
		wait(0.2)
	end
	v_u_2.ObjectLocal(p15.Tip, p15.Config.Sound.reload_close, {
		["RollOffMaxDistance"] = 129
	})
	wait(0.2)
	v_u_2.ObjectLocal(p15.Tip, p15.Config.Sound.cylinder_spin, {
		["RollOffMaxDistance"] = 129
	})
end
return v_u_5
