-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNAA25ldwxzZXRtZXRhdGFibGUIX2hhc1NXQVQFU2V0dXAGUGxheWVyC0Rpc3BsYXlOYW1lE2RvZXNQbGF5ZXJPd25DYWNoZWQMRW51bUdhbWVwYXNzBFNXQVQKU2V0dXBNb2RlbApQaXN0b2xTV0FUBU1vZGVsC0JvdW5kaW5nQm94BVNsaWRlBk1vdGlvbgVNb3RvcghBbmNob3JlZAdWZWN0b3IzCk1vdG9yU2xpZGULU3ByaW5nU2xpZGURVXBkYXRlSXRlbVNwcmluZ3MGVXBkYXRlDVNsaWRlUG9zaXRpb24QVXBkYXRlSXRlbUpvaW50cwZDRnJhbWUCQzELT2JqZWN0TG9jYWwDVGlwBkNvbmZpZwVTb3VuZBhndW5fcGlzdG9sX3NsaWRlX2Zhc3RfMDEGVm9sdW1lBVBpdGNoBG1hdGgGcmFuZG9tFHBpc3RvbF9zaG90X3NpbGVuY2VkEmd1bl9waXN0b2xfc2hvdF8wNAVkZWxheQpBY2NlbGVyYXRlClNob290U291bmQYZ3VuX3Bpc3RvbF9yZW1vdmVfbWFnXzAxElJvbGxPZmZNYXhEaXN0YW5jZRNSZWxvYWREcm9wQW1tb1NvdW5kGGd1bl9waXN0b2xfaW5zZXJ0X21hZ18wMQR3YWl0FVJlbG9hZFJlZmlsbEFtbW9Tb3VuZARnYW1lEVJlcGxpY2F0ZWRTdG9yYWdlCkdldFNlcnZpY2UHcmVxdWlyZQNTdGQFQXVkaW8FSm9pbnQGU3ByaW5nDUdhbWVwYXNzVXRpbHMER2FtZQhHYW1lcGFzcw5HYW1lcGFzc1N5c3RlbQZzY3JpcHQGUGFyZW50A0d1bgZQaXN0b2wLX19DbGFzc05hbWUHX19pbmRleAAJBwMCAAAAFvsEAABNAwTvAAAAAFIEAABSBQEAUgYCAJ8DBAL7BgEAnj0DBAYAAABSBQMApAQCAAAAEECfBAMBqQQAADAEA6MDAAAAUgYCALwEA5kEAAAAnwQDAYIDAgAFAwEDAgQAABBAAwMDBAAQAQEYAAAAAAAAAAEAAAAAAAABAAABAAAAAhEAAAAACgEFAAAAR00BAPkAAAAADgEbAE0CAPkAAAAATQECVwEAAAAOARYA+wIAAE0BAr0CAAAATQIA+QAAAAD7BQEATQQFjQMAAABNAwQyBAAAAJ8BAwIOAQoAqQEBADABAKMFAAAA+wICAE0BAjwGAAAAUgIAAG8DBwCfAQMBZQAFAPsCAgBNAQI8BgAAAFICAACfAQIBTQEAOwgAAABNAgBvCQAAAE0EAZcLAAAATQMExQoAAAD7BQMATQQF1gwAAABSBQMAUgYCAJ8EAwKpBQAAMAUDRQ0AAAD7BgQATQUG7w4AAABMNgACpAYQAAA48ICfBgECTDYAAqQHEAAAOPCAnwcBAm8IEQCMCSgAnwUFAjAEALMSAAAAMAUAvBMAAACCAAEAFAMFAwYDBwMIAwkDAwMKAwsDDAMNAw4DDwMQAxEDAQMSBAA48IACzczMzMzM7D8DEwMUABgKARgAAAABAAAAAAEAAAAAAAAAAAAAAAIAAAEAAAAAAAACAAAAAAMAAQABAAAAAQAAAAAAAQAAAQAAAAAAAAAAAAAAAAACAAEAARoAAAAAAwEBAAAADfsCAABNAQLAAAAAAFICAACfAQIBTQEAvAEAAAC8AQEmAgAAAJ8BAgIwAQDEAwAAAIIAAQAEAxUDFAMWAxcALhUBGAAAAAAAAQAAAAABAAEvAAAAAAQBAQAAAA/7AgAATQECiwAAAABSAgAAnwECAU0BALMBAAAApAIEAAAMIIBNAwDEBQAAAJ8CAgIwAgHMBgAAAIIAAQAHAxgDEwMZAwEEAAwggAMXAxoAMxgBGAAAAAAAAQAAAAAAAAAAATQAAAAACQACAAAAHPsBAABNAAHRAAAAAPsCAQBNAQKxAQAAAPsFAQBNBAXZAgAAAE0DBG4DAAAATQIDhAQAAADiAwcAbwQIADAEA0sFAAAAjAYBAKQIDQAAMLCAnwgBAlsHCApDBQYHeAQFCTAEAwAGAAAAnwAEAYIAAQAOAxsDHAMdAx4DHwMgAyEFAgUGAjMzMzMzM9M/ApqZmZmZmak/ApqZmZmZmbk/AyIDIwQAMLCAAD4AARgAAAABAAABAAAAAAAAAQAAAAAAAAAAAAAAAP0FPwAAAAAHAgEAAAAzKwExAE0CAKMAAAAADgIRAPsDAABNAgPRAQAAAE0DALECAAAATQYA2QMAAABNBQZuBAAAAE0EBQkFAAAA4gUHAIwGAQAwBgUABgAAAJ8CBAFlABAA+wMAAE0CA9EBAAAATQMAsQIAAABNBgDZAwAAAE0FBm4EAAAATQQFTQgAAADiBQcAjAYBADAGBQAGAAAAnwIEAaQCCgAAAJBAbwMLANkEAAASAgAAEgAAAJ8CAwFNAgC8DAAAAG8EDQC8AgKdDgAAAJ8CAwGCAAEADwMDAxsDHAMdAx4DJAMhBQEGAyUDJgQAAJBAApqZmZmZmbk/AxQHAAAAAAAAAAAAAPBBAAAAAAMnAQQ3KAEYAAEAAAEAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAHAAAAAAACOAAAAAAGAQEAAAAR+wIAAE0BAtEAAAAATQIAsQEAAABNBQDZAgAAAE0EBW4DAAAATQMEYgQAAADiBAYAjAWBADAFBCoFAAAAnwEEAYIAAQAHAxsDHAMdAx4DKQMqBQEFAEgrARgAAAAAAAAAAAAAAAABAAD/A0kAAAAABgEBAAAAKfsCAABNAQLRAAAAAE0CALEBAAAATQUA2QIAAABNBAVuAwAAAE0DBMkEAAAA4gQGAIwFgQAwBQQqBQAAAJ8BBAGkAQgAAABwQG8CCQCfAQIB+wIAAE0BAtEAAAAATQIAsQEAAABNBQDZAgAAAE0EBW4DAAAATQMEhAoAAADiBAYAjAWBADAFBCoFAAAAnwEEAaQBCAAAAHBAbwILAJ8BAgGCAAEADAMbAxwDHQMeAywDKgUBBQMtBAAAcEACmpmZmZmZ2T8DHwKamZmZmZm5PwBNLgEYAAAAAAAAAAAAAAAAAQAA/wMAAAABAAAAAAAAAAAAAAABAAD/AwAAAAFOAAAAAAwAAAECAGejAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CA9IHAAAAnwECAqQCBQAAAEBATQQAoQYAAABNAwQMCAAAAJ8CAgKkAwUAAABAQE0FAKEGAAAATQQFIgkAAACfAwICpAQFAAAAQEBNBwC9CwAAAE0GB70MAAAATQUGPgoAAACfBAICpAUFAAAAQEBNCAC9CwAAAE0HCL0MAAAATQYHjg0AAACfBQICpAcPAAAA4EBNBgckEAAAAKQHBQAAAEBATQgGDREAAACfBwIC/wgFAAAAAABvCRIAMAkI5RMAAAAwCAhuFAAAAJ49CAUHAAAAUgoIAFILBwCkCRYAAABQQZ8JAwHACRcAEgAHABIACAAwCQjvGAAAAMAJGQASAAUAEgAEABIABwASAAIAEgADADAJCDwaAAAAwAkbABIABwAwCQjAHAAAAMAJHQASAAcAMAkIix4AAADACR8AEgABADAJCLkgAAAAwAkhABIAAQAwCQi9IgAAAMAJIwASAAEAMAkIeSQAAACCCAIAJQMvBAAAAEADMAMxAzIEAABAQAMzAzQDNQM2AzcDOAM5AzoDOwQAAOBAAzwDPQM+Az8DQAMCBAAAUEEGAAMBBgEDCgYCAxUGAwMYBgUDKAYGAysGBwMuBwABAgMFBgcBAAEYAAEAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAIAAAABAAAAAAIAAQAAAQABAAAAAAAAAQAAAAAIAAAAAAAAABYAAAAFAAAABAAAABEAAAAFAAAACwEAAAAACEXagzIlQ4PRdx7pppVqlzLG2ZSp5JqaAT7uNUhdi3qwenmqbSVmfiU=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.Audio)
local v_u_3 = require(v1.Std.Joint)
local v_u_4 = require(v1.Std.Spring)
local v_u_5 = require(v1.Game.Gamepass.GamepassUtils)
local v_u_6 = require(v1.Game.Gamepass.GamepassSystem)
local v7 = script.Parent
local v_u_8 = require(v7.Gun)
local v_u_9 = {
	["__ClassName"] = "Pistol"
}
v_u_9.__index = v_u_9
setmetatable(v_u_9, v_u_8)
function v_u_9.new(p10, p11, p12)
	-- upvalues: (copy) v_u_8, (copy) v_u_9
	local v13 = v_u_8.new(p10, p11, p12)
	local v14 = v_u_9
	setmetatable(v13, v14)
	v13._hasSWAT = false
	v13:Setup(p12)
	return v13
end
function v_u_9.SetupModel(p15)
	-- upvalues: (copy) v_u_6, (copy) v_u_5, (copy) v_u_8, (copy) v_u_3, (copy) v_u_4
	if p15.Player and (p15.Player.DisplayName and v_u_6.doesPlayerOwnCached(p15.Player, v_u_5.EnumGamepass.SWAT)) then
		p15._hasSWAT = true
		v_u_8.SetupModel(p15, "PistolSWAT")
	else
		v_u_8.SetupModel(p15)
	end
	local v16 = p15.Model
	local v17 = p15.BoundingBox
	local v18 = v16.Motion.Slide
	local v19 = v_u_3.Motor(v18, v17)
	v18.Anchored = false
	local v20 = v_u_4.new(Vector3.new(), Vector3.new(), 0.9, 40)
	p15.MotorSlide = v19
	p15.SpringSlide = v20
end
function v_u_9.UpdateItemSprings(p21)
	-- upvalues: (copy) v_u_8
	v_u_8.UpdateItemSprings(p21)
	p21.SlidePosition = p21.SpringSlide:Update()
end
function v_u_9.UpdateItemJoints(p22)
	-- upvalues: (copy) v_u_8
	v_u_8.UpdateItemJoints(p22)
	p22.MotorSlide.C1 = CFrame.new(p22.SlidePosition)
end
function v_u_9.ShootSound(p_u_23, p24)
	-- upvalues: (copy) v_u_2
	if not p24 then
		if p_u_23._hasSWAT then
			v_u_2.ObjectLocal(p_u_23.Tip, p_u_23.Config.Sound.pistol_shot_silenced, {
				["Pitch"] = 1
			})
		else
			v_u_2.ObjectLocal(p_u_23.Tip, p_u_23.Config.Sound.gun_pistol_shot_04, {
				["Pitch"] = 1
			})
		end
		delay(0.1, function()
			-- upvalues: (ref) v_u_2, (copy) p_u_23
			v_u_2.ObjectLocal(p_u_23.Tip, p_u_23.Config.Sound.gun_pistol_slide_fast_01, {
				["Volume"] = 0.3,
				["Pitch"] = 1 + math.random() * 0.1 - 0.05
			})
		end)
		p_u_23.SpringSlide:Accelerate(Vector3.new(0, 0, 30))
	end
end
function v_u_9.ReloadDropAmmoSound(p25)
	-- upvalues: (copy) v_u_2
	v_u_2.ObjectLocal(p25.Tip, p25.Config.Sound.gun_pistol_remove_mag_01, {
		["RollOffMaxDistance"] = 129
	})
end
function v_u_9.ReloadRefillAmmoSound(p26)
	-- upvalues: (copy) v_u_2
	v_u_2.ObjectLocal(p26.Tip, p26.Config.Sound.gun_pistol_insert_mag_01, {
		["RollOffMaxDistance"] = 129
	})
	wait(0.4)
	v_u_2.ObjectLocal(p26.Tip, p26.Config.Sound.gun_pistol_slide_fast_01, {
		["RollOffMaxDistance"] = 129
	})
	wait(0.1)
end
return v_u_9
