-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMZBEluaXQDbmV3DHNldG1ldGF0YWJsZQVTZXR1cApTZXR1cE1vZGVsC09iamVjdExvY2FsA1RpcAZWb2x1bWUMVGltZVBvc2l0aW9uClNob290U291bmQEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUGc2NyaXB0BlBhcmVudANHdW4ER2FtZQRJdGVtCVBsYXNtYUd1bgNTdGQFQXVkaW8NUGxhc21hU2hvdGd1bgtfX0NsYXNzTmFtZQdfX2luZGV4AAUBAQAAAAABggABAAAACwEBGAALAAAAAAcDAgAAABP7BAAATQME7wAAAABSBAAAUgUBAFIGAgCfAwQC+wYBAJ49AwQGAAAAUgUDAKQEAgAAABBAnwQDAVIGAgC8BAOZAwAAAJ8EAwGCAwIABAMCAwMEAAAQQAMEAAwCARgAAAAAAAAAAQAAAAAAAAEAAAABDQAAAAADAQEAAAAG+wIAAE0BAjwAAAAAUgIAAJ8BAgGCAAEAAQMFABIFARgAAAAAAAETAAAAAAcCAQAAABArAQ4A+wMAAE0CA9EAAAAATQMAsQEAAABvBAIA4gUFAG8GBgAwBgVLAwAAAG8GBwAwBgXGBAAAAJ8CBAGCAAEACAMGAwcCAAAwwtoAEEIDCAMJBQIDBAJmZmZmZmbWPwKamZmZmZmpPwAVCgEYAAEAAAAAAAABAAABAAD+BRYAAAAACAAAAQIAP6MAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQKQEBwAAAGBATQMEJAgAAABNAgMNCQAAAJ8BAgKkAgUAAABAQE0FAL0KAAAATQQFygsAAABNAwSgDAAAAJ8CAgKkAwUAAABAQE0FAKENAAAATQQF0g4AAACfAwIC/wQEAAAAAABvBQ8AMAUE5RAAAAAwBARuEQAAAJ49BAUCAAAAUgYEAFIHAgCkBRMAAAAgQZ8FAwHABRQAMAUEcxUAAADABRYAEgACABIABAAwBQTvFwAAAMAFGAASAAEAMAUEPBkAAADABRoAEgADADAFBLkbAAAAggQCABwDCwQAAABAAwwDDQMOBAAAQEADDwQAAGBAAxADEQMSAxMDFAMVAxYDFwMYAxkDAwQAACBBBgADAQYBAwIGAgMFBgMDCgQAAQIDAQABGAABAAAAAAABAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAgABAAABAAEAAAAAAAABAAABAAAAAAYAAAADAAAACAEAAAAABMHb2T+5LhvD8x+zq77IwD4/u7M7zEUwuWt/aVn0katVeTew7A/YHgY=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(script.Parent.Gun)
local v_u_3 = require(v1.Game.Item.PlasmaGun)
local v_u_4 = require(v1.Std.Audio)
local v_u_5 = {
	["__ClassName"] = "PlasmaShotgun"
}
v_u_5.__index = v_u_5
setmetatable(v_u_5, v_u_3)
function v_u_5.Init(_) end
function v_u_5.new(p6, p7, p8)
	-- upvalues: (copy) v_u_3, (copy) v_u_5
	local v9 = v_u_3.new(p6, p7, p8)
	local v10 = v_u_5
	setmetatable(v9, v10)
	v9:Setup(p8)
	return v9
end
function v_u_5.SetupModel(p11)
	-- upvalues: (copy) v_u_2
	v_u_2.SetupModel(p11)
end
function v_u_5.ShootSound(p12, p13)
	-- upvalues: (copy) v_u_4
	if not p13 then
		v_u_4.ObjectLocal(p12.Tip, 17183453324, {
			["Volume"] = 0.35,
			["TimePosition"] = 0.05
		})
	end
end
return v_u_5
