-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgOBAQRtYXRoBnJhbmRvbQdWZWN0b3IzA25ldwRVbml0DFJhbmRvbVZlY3RvchFfdXBkYXRlSGVhdFJlbW90ZQVNb2RlbAhfZ2V0VGlwcwVMb2NhbBRvYnNlcnZlT25lQ2hpbGROYW1lZBBVcGRhdGVIZWF0UmVtb3RlCEdpdmVUYXNrD29ic2VydmVQcm9wZXJ0eQVWYWx1ZQxzZXRtZXRhdGFibGUETWFpZApQbGFuZU1vZGVsB3ByaW1hcnkKc2F0dXJhdGVUbwhwcmlvcml0eRdTaG9vdEFjdGlvbkJ1dHRvbkNvbmZpZwVTZXR1cBVEZWZhdWx0RGlzYWJsZUNhbUxvY2sETmFtZQpNYWNoaW5lR3VuDkZpbmRGaXJzdENoaWxkC0JsYWNrQ2hyb21lBmZpbHRlcgtHZXRDaGlsZHJlbgRUaXBzCUNoYXJhY3RlcgVJdGVtcwl3b3Jrc3BhY2UKSWdub3JlTGlzdA1CdWxsZXRFbWl0dGVyEV91cGRhdGVJZ25vcmVMaXN0DVJlbmRlclN0ZXBwZWQHU3RlcHBlZAlMYXN0U2hvb3QQTGFzdFBsYXllckltcGFjdBhTcHJpbmdUaGlyZE1vdXNlUG9zaXRpb24MU3ByaW5nQ2FtZXJhClNwcmluZ1NwaW4JU3BpblRvdGFsCU1vdXNlRG93bghUaXBJbmRleBJTZXR1cEJ1bGxldEVtaXR0ZXIKU2V0dXBTaG9vdBNVcGRhdGVNb3VzZVBvc2l0aW9uB0Nvbm5lY3QEdGljax1CdWxsZXRFbWl0dGVyT25Mb2NhbEhpdFBsYXllcglTZXRUYXJnZXQbVHJhbnNmb3JtTG9jYWxNb3VzZVBvc2l0aW9uD1VwZGF0ZUFybUpvaW50cwZVcGRhdGUGQ0ZyYW1lAXgBeQxVcGRhdGVDYW1lcmEDVGlwDVdvcmxkUG9zaXRpb24LV29ybGRDRnJhbWUKTG9va1ZlY3RvcgZDb25maWcLQnVsbGV0U3BlZWQERW1pdAtQcmltYXJ5UGFydAhQb3NpdGlvbgFwCU1hZ25pdHVkZQVjbGFtcApBY2NlbGVyYXRlBVNob290FFNob290Q2hlY2tDb25kaXRpb25zBVNvdW5kBlZvbHVtZQdNYXhIZWF0BEhlYXQMR2V0QXR0cmlidXRlDVVzZXJJbnB1dFR5cGUERW51bQxNb3VzZUJ1dHRvbjEKSW5wdXRFbmRlZA1fYXR0ZW1wdFNob290DFNldEF0dHJpYnV0ZQ1BbmltYXRlQmFycmVsCkxhc3RVcGRhdGUJSGVhcnRiZWF0CEdhbWVwYWQxB0tleUNvZGUHQnV0dG9uWAhJbnN0YW5jZRdyYnhhc3NldGlkOi8vMjE5ODM5MDM5MQdTb3VuZElkBkxvb3BlZAZQYXJlbnQEUGxheRNCcm9hZGNhc3RJbnB1dEJlZ2FuCklucHV0QmVnYW4HRGVzdHJveQVkZWxheRNCcm9hZGNhc3RJbnB1dEVuZGVkCkZpcmVTZXJ2ZXIHVW5lcXVpcARnYW1lClJ1blNlcnZpY2UKR2V0U2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQdyZXF1aXJlA1N0ZAVBdWRpbwdSMTVJS3YyBk1vZHVsZQZTcHJpbmcPUnhJbnN0YW5jZVV0aWxzEkludmVudG9yeUl0ZW1VdGlscwlJbnZlbnRvcnkKVGFibGVVdGlscw1DdXJyZW50Q2FtZXJhBnNjcmlwdANHdW4LU3R1bnRUdXJyZXQLX19DbGFzc05hbWUHX19pbmRleAZSZWxvYWQJQXBwbHlTa2luClNjb3BlQmVnaW4AGgcAAAAABwAAAQgBEwIWpAQEAAAMIICfBAECWwMEAXgCAwCkBQQAAAwggJ8FAQJbBAUBeAMEAKQGBAAADCCAnwYBAlsFBgF4BAUATDYAAqQBBwAAGFCAnwEEAk0AAQcIAAAAggACAAkCAAAAAAAA8D8CAAAAAAAAAEADAQMCBAAMIIADAwMEBAAYUIADBQAPBgEYAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAgEBAAAABPsBAAAwAAE0AAAAAIIAAQABAwcAMAABGAAAAAExAAAAAAgCAgAAABn7AgAAMAACOwAAAAArAAEAggABAPsCAAC8AgKkAQAAAJ8CAgH7AwAATQIDuwIAAAAOAgsA+wUBAE0EBeoDAAAAUgUAAG8GBADZBwAAEgIAAJ8EBAC8AgH9BQAAAJ8CAAGCAAEABgMIAwkDCgMLAwwDDQEBJQABGAAAAAEBAgAAAAEAAAACAAABAQEA/f8AAAomAAAAAAgCAgAAAA8rAAEAggABAPsFAABNBAVIAAAAAFIFAABvBgEA2QcAABICAQASAgAAnwQEALwCAf0CAAAAnwIAAYIAAQADAw4DDwMNAQIgAAEYAAEDAAAAAAAAAAD/AAAUIQAAAAAKAwMAAAAu+wQAAE0DBO8AAAAAUgQAAFIFAQCfAwMC+wYBAJ49AwQGAAAAUgUDAKQEAgAAABBAnwQDAU0EA3YDAAAA+wcCAE0GB+oEAAAAUgcBAG8IBQDZCQAAEgICABIAAwCfBgQAvAQE/QYAAACfBAAB4gQKAKkFAAAwBQQ1BwAAAIwFZAAwBQQTCAAAAIwF9AEwBQTtCQAAADAEA3ILAAAAvAQDmQwAAACfBAIBvAQDvg0AAACfBAIBggMCAA4DBAMQBAAAEEADEQMLAxIDDQMTAxQDFQUDBwgJAxYDFwMYAQMXBAEYAAAAAAAAAQAAAAAAAAIAAQAAAQEBAAD9/wAAIAEAAAEAAAEAAP0ABgAAAQAAAhkAAAAAAwEAAAAAB00CALoAAAAA8AICAAEAAACpAQABqQEBAIIBAgACAxkDGgBTAAEYAAAAAAAAAFQAAAAABgEBAAAAHU0BADsAAAAAKwEBAIIAAQBNAQA7AAAAAG8DAAC8AQEDAQAAAJ8BAwIrAQEAggABAG8EAgC8AgEDAQAAAJ8CAwIrAgEAggABAPsEAABNAwT7AwAAALwEAmgEAAAAnwQCAsAFBQCfAwMCMAMAlwYAAACCAAEABwMIAxsDHAMdAx4GBQMfAQVHCQEYAAAAAQIAAAAAAAEBAgAAAAEBAgAAAAAAAAAAAANIAAAAAAYBAAAAABj/AQAAAwAAAE0CAGkAAAAATQMAOwEAAACkBQQAAAAwQE0EBTgCAAAAxQECBAEAAAAwAQDKBQAAAE0BAGcGAAAADgEGAE0BAGcGAAAATQIAygUAAAAwAgHKBQAAAIIAAQAHAyADCAMhAyIEAAAwQAMjAyQAVyUBGAAAAAAAAAAAAAAAAAAAAQAAAQAAAAAAAlgAAAAAAgABAAAABfsAAAC8AADPAAAAAJ8AAgGCAAEAAQMmAHgAARgAAAAAAXkAAAAAAgABAAAABfsAAAC8AADZAAAAAJ8AAgGCAAEAAQMnAHsAARgAAAAAAXwAAAAABgECAAAAarwBAPQAAAAAnwECAYwBAAAwAQAhAQAAAIwBAAAwAQCKAgAAAPsCAABNAQLvAwAAAEw2AAKkAgUAAAxAgJ8CAQJMNgACpAMFAAAMQICfAwECbwQGAIwFHgCfAQUCMAEAPwcAAABNAQC7CAAAAA4BEAD7AgAATQEC7wMAAABMNgACpAIFAAAMQICfAgECTDYAAqQDBQAADECAnwMBAm8ECQCMBSwBnwEFAjABALUKAAAA+wIAAE0BAu8DAAAAjAIAAIwDAABvBAkAjAUHAJ8BBQIwAQBICwAAAIwBAAAwAQCsDAAAAKkBAAAwAQDNDQAAAE0BAJcOAAAAKwEEAP8BAAAAAAAAMAEAlw4AAACMAQEAMAEArg8AAAC8AQBKEAAAAJ8BAgG8AQD9EQAAAJ8BAgG8AQCVEgAAAJ8BAgFNAQB2EwAAAPsEAQBNAwTPFAAAANkFAAASAAAAvAMDxxUAAACfAwMAvAEB/RYAAACfAQABTQEAdhMAAAD7BAEATQME2RcAAADZBQEAEgAAALwDA8cVAAAAnwMDALwBAf0WAAAAnwEAAYIAAQAYAyUDKAMpAwQDAwQADECAAs3MzMzMzOw/AyoDCgIzMzMzMzPjPwMrAywDLQMuAx8DLwMwAzEDMgMRAyYDMwMNAycCCAldFwEYAAAAAgAAAQAAAgAAAAAAAAAAAAAAAAAAAAIAAAEAAAAAAAAAAAAAAAAAAQADAAAAAAAAAAAAAQAAAQAAAgAAAQAAAAIAAAEAAAIAAAIAAAIAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAA14AAAAABQEBAQAAE6MBAACkAQEAAAAAQJ8BAQJNAwCKAgAAACYCAQNvAwMAYAMJAAIAAAAwAQCKAgAAAPsDAABNAgNyBAAAAFIDAADdBAAAnwIAAYIAAQAFAzQEAAAAQAMpApqZmZmZmbk/AzUAfzUBGAADAAABAAAAAAABAAEAAAAAAAJ/AAAAAAUCAAAAAAdNAgA/AAAAAFIEAQC8AgKXAQAAAJ8CAwCCAgAAAgMqAzYAiQE3ARgAAAAAAAAAigAAAAABAQAAAAABggABAAAAjAE4ARgAjAAAAAAIAQEAAAAWTQEAtQAAAAC8AQEmAQAAAJ8BAgL7AgAATQMChQIAAACkBAQAAAwggE0GAZkGAAAAWwUGBU0HAZgHAAAAWwYHBYwHAACfBAQCCQMDBDADAoUCAAAAggABAAgDKwM5AzoDBAQADCCAAgAAAAAAABBAAzsDPACNAT0BGAAAAAAAAQAAAAAAAAAAAAAAAAAAAAGOAAAAAAMBAAAAAAq8AQCVAAAAAJ8BAgFNAQC7AQAAAA4BAwC8AQBxAgAAAJ8BAgGCAAEAAwMyAwoDPQCRASYBGAAAAAEAAAEAAAKSAAAAAA4BAQAABwAAAQgIVQJdvAEA9AAAAACfAQIBTQIAlwEAAABNAwCuAgAAAIcBAgMrAQQAvAIApAMAAACfAgIBggABADABALEEAAAATQIAZwUAAABNBAHgBgAAAE0GAesHAAAATQUGaAgAAABNBwDZCQAAAE0GB6UKAAAAvAICVgsAAACfAgUBTQQArgIAAABNBgCXAQAAABwFBgDPAwQFlQIDDDACAK4CAAAATQIAuw0AAAAOAjIATQYAOw4AAABNBQabDwAAAE0EBTsQAAAA+wcAAE0GB4URAAAATQUGkRIAAAAmAwQFTQIDqhMAAADYBBQCbwUVAIwGAQBMLgACpAMYAABcYIGfAwQCUgIDAE0DALUZAAAApAsdAABwYIGfCwECWwoLG3gJCgykDB0AAHBggZ8MAQJbCwwbeAoLDKQNHQAAcGCBnw0BAlsMDRt4CwwMTDYAAqQIIAAAfOCBnwgEAk0HCAchAAAACQYHAlsFBhq8AwOdIgAAAJ8DAwGCAAEAIwMlAx8DLwMJAz4DJAM/A0ADQQNCA0MDRAIAAAAAAADwPwMKAwgDRQNGAzoDRwNIAgAAAAAAADRAApqZmZmZmbk/AwEDSQQAXGCBAysCAAAAAAAASUACAAAAAAAAAEADAgQAcGCBAwMDBAQAfOCBAwUDSgCXAUsBGIgAAAIAAAAAAQEAAAEDAAEAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAIAAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAABAGkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlwAAAhAAAAAAAgEAAAAAAqkBAQCCAQIAAACqAUwBGAAAqwAAAAAMAwAAAABWTQMAOwAAAAArAwEAggABAKQDAgAAABBAnwMBAk0EAG4DAAAADgQFAE0EAG4DAAAAWwUCBDAFBEsFAAAATQUA2QYAAABNBAUHBwAAAE0FADsAAAAAbwcIALwFBRIJAAAAnwUDAm8GCgB9BiIAAgAAAGAFIAAEAAAATQcAIQsAAAAmBgMHjAkKAIwLHgAJCgsCQwgJCtgHDAhgBx4ABgAAAEMFBQF9BAoABQAAAJUFBQ3iCA8ApAkSABE4AMEwCQjCDgAAALwGAK8TAAAAnwYDATADACELAAAATQYAuxQAAAAOBgwAvAYAJhUAAACfBgIBZQAIAIwGAABgBgIABQAAACYFBQGMBgAAYAUCAAYAAACMBQAAjAkAADQuBQUJBAAAUggFAFIKBACkBxgAAFxggZ8HBALsBgcETQYAOwAAAABvCAgAUgkFALwGBi4ZAAAAnwYEAYIAAQAaAwgDNAQAABBAA00CAAAAAAAA4D8DTgNCA08DUANRAjMzMzMzM+M/AygCAAAAAAAA8D8CAAAAAAAACEADUgUBDgNTA1QEETgAwQNVAwoDVgMBA0kEAFxggQNXAK0BWAEYAAAAAQIAAAIAAAEAAAAAAgAAAAEAAAAAAAEAAAAAAQAAAAAAAAAAAAEBAAECAAAAAAAAAAMAAgAAAQAAAAQAAAECAAABBAAAAAAAAAAABAAAAAAAAAGuAAAAAAoBAAAAACJNAQA7AAAAACsBAQCCAAEApAECAAAAEECfAQECTQMABAMAAADKAgMBJgMBAjABAAQDAAAATQQASAQAAAC8BAQmBQAAAJ8EAgJNBgCsBgAAAAkHAwRDBQYHbwYHAGAGAgAFAAAAeAUFBzAFAKwGAAAAUggDAFIJBAC8BgDACAAAAJ8GBAGCAAEACQMIAzQEAAAQQANZAywDOQMtAhgtRFT7IRlAA1gA1gEnARgAAAABAwAAAQAAAQEAAgAAAAABAAAAAQAAAQIAAgAAAAAB1wAAAAABAQAAAAABggABAAAA6wFaARgA6wAAAAAIAwAAAABSDgICAKkDAACCAwIAqQMBAE0EAcIAAAAApAUDAAIAEMDxBBAABQAAAKkDAABNBAHCAAAAAKQFBQAEABDAmgQJAAUAAABNBAGzBgAAAKQFCAAHGBDA8QQCAAUAAACpAwABqQMBAA4DNwBNBAA7CQAAAG8GCgC8BAQSCwAAAJ8EAwJNBgDZDAAAAE0FBgcNAAAAYAQlAAUAAABNBQBIDgAAAIwHAQC8BQWXDwAAAJ8FAwGpBQEAMAUAzRAAAABNBQBuEQAAACsFGACkBRQAAEwggW8GEQCfBQICbwYVADAGBXwWAAAAjAYAADAGBUsXAAAAqQYBADAGBbUYAAAATQcAOwkAAABNBgebGQAAADAGBSQaAAAAvAYF7hsAAACfBgIBMAUAbhEAAABNBQC7HAAAAA4FBABSBwEAvAUACh0AAACfBQMBggABAB4DUgNTA1QEAgAQwANbBAQAEMADXANdBAcYEMADCANQA1EDQgNPAywDNgMuA00DXgMEBABMIIEDXwNgA04DYQNFA2IDYwMKA2QA7AFlARgAAQADAAAAAAAAAQAAAAAAAAAAAAAAAAAAAgEAAAAAAAEAAAAAAAEAAAAAAAEAAAEAAAEAAAABAAABAAABAAABAAAAAAABAAABAAMAAAEAAAAD7QAAAAACAAEAAAAT+wEAAE0AAW4AAAAADgAOAPsBAABNAAHNAQAAACsACgD7AQAATQABbgAAAAC8AABQAgAAAJ8AAgH7AAAAxgEAADABAG4AAAAAggABAAMDTQMuA2YAkwIAARgAAAAAAAAAAAEAAAAAAAEAAAACFAEAAAAHAwAAAAAxDgICAKkDAACCAwIAqQMBAE0EAcIAAAAApAUDAAIAEMDxBBAABQAAAKkDAABNBAHCAAAAAKQFBQAEABDAmgQJAAUAAABNBAGzBgAAAKQFCAAHGBDA8QQCAAUAAACpAwABqQMBAA4DFgBNBABICQAAAIwGAAC8BASXCgAAAJ8EAwGpBAAAMAQAzQsAAACkBA0AAADAQG8FDgDZBgAAEgAAAJ8EAwFNBAC7DwAAAA4EBABSBgEAvAQAuRAAAACfBAMBggABABEDUgNTA1QEAgAQwANbBAQAEMADXANdBAcYEMADLAM2Ay4DZwQAAMBAAgAAAAAAAOA/AwoDaAEWiAJVARgAAQADAAAAAAAAAQAAAAAAAAAAAAAAAAAAAgEAAAAAAAEAAAEAAAAAAAYAAAEAAAADCQEAAAAGAQAAAAAdTQEAuwAAAAAOAQ4ATQEANAEAAAAOAQsATQEANAEAAABNAwA7AgAAAG8FAwC8AwMSBAAAAJ8DAwC8AQFrBQAAAJ8BAAFNAQBuBgAAAA4BCABNAQBuBgAAALwBAVAHAAAAnwECAcYBAAAwAQBuBgAAAIIAAQAIAwoDBwMIA1ADUQNpA00DZgCeAmoBGAAAAAEAAAEAAAAAAAAAAAAAAwAAAQAAAAABAAACHwEAAAAQAAABAgCZAaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQEAAAAAQG8DBAC8AQEWAwAAAJ8BAwKkAgYAAABQQE0EAaEHAAAATQME0ggAAACfAgICpAMGAAAAUEBNBQFACgAAAE0EBUoJAAAAnwMCAqQEBgAAAFBATQYBoQcAAABNBQYiCwAAAJ8EAgKkBQYAAABQQE0HAaEHAAAATQYHUgwAAACfBQICpAYGAAAAUEBNCAFgDgAAAE0HCHcNAAAAnwYCAqQHBgAAAFBATQkBoQcAAABNCAkYDwAAAJ8HAgKkCREAAAAAQU0ICUgSAAAApAoUAAAAMEFNCQokFQAAAKQKBgAAAFBATQsJDRYAAACfCgICwAsXAP8MBgAAAAAAbw0YADANDOUZAAAAMAwMbhoAAACePQwFCgAAAFIODABSDwoApA0cAAAAsEGfDQMBwA0dABIACgASAAwAEgAFADANDO8eAAAAwA0fABIABwAwDQykIAAAAMANIQAwDQz0IgAAAMANIwASAAQAEgAAADANDJkkAAAAwA0lABIACgAwDQxyJgAAAKkNAAAwDQw3JwAAAMANKAAwDQyBKQAAAMANKgAwDQxjKwAAAMANLAASAAgAMA0McS0AAADADS4AMA0Mzy8AAADADTAAEgAIADANDOgxAAAAwA0yADANDKkzAAAAwA00ADANDMA1AAAAwA02ADANDNk3AAAAqQ0AADANDOk4AAAAqQ0AADANDCQ5AAAAwA06ADANDP07AAAAwA08ADANDII9AAAAwA0+ADANDK8/AAAAwA1AADANDLhBAAAAggwCAEIDawQAAABAA2wDbQNuA28EAABQQANwA3EDcgNzA3QDdQN2A3cDeAMiBAAAAEEDeQN6BAAAMEEDYgN7BgADfAN9A34DEAQAALBBBgQDBAYGAwkGBwMlBgoDFwYLAzUDfwYMAzcGDQM4Bg4DPQYPAyYGEANLBhEDTAYSA1gGEwMnA4ABA4EBBhQDWgYVA2UGFwNVBhgDahIABAYHCgsMDQ4PEBESExQVFxgBAAEHAAEAAAAAAAEAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAACAAAAAQAAAAACBAABAAABAAEAAAAAAAABAAAAAAAwAAAAEAAABgAAAAAiAAAACQAAAQAAAwAAAQAAAAQAAAYAAAATAABXAAApAAATAAABAAABAAABAAAcAAAWAAAMAQAAAKwAAAAAGTiHcEKN/h8dCkMa1p47eoXibl0eOuT89k/7jn9t365b1MGV7RFr1To=

-- Decompiled by Krnl

local v_u_1 = game:GetService("RunService")
local v2 = game:GetService("ReplicatedStorage")
require(v2.Std.Audio)
require(v2.Module.R15IKv2)
local v_u_3 = require(v2.Std.Spring)
local v_u_4 = require(v2.Std.RxInstanceUtils)
require(v2.Inventory.InventoryItemUtils)
local v_u_5 = require(v2.Std.TableUtils)
local v_u_6 = workspace.CurrentCamera
local v7 = script.Parent
local v_u_8 = require(v7.Gun)
local v_u_9 = {
	["__ClassName"] = "StuntTurret"
}
v_u_9.__index = v_u_9
setmetatable(v_u_9, v_u_8)
function v_u_9.new(p10, p11, _)
	-- upvalues: (copy) v_u_8, (copy) v_u_9, (copy) v_u_4
	local v_u_12 = v_u_8.new(p10, p11)
	local v13 = v_u_9
	setmetatable(v_u_12, v13)
	v_u_12.Maid:GiveTask(v_u_4.observeOneChildNamed(p11, "PlaneModel", function(p14, p15)
		-- upvalues: (ref) v_u_4, (copy) v_u_12
		if p14 then
			p15:GiveTask(v_u_4.observeProperty(p14, "Value", function(p16, p17)
				-- upvalues: (ref) v_u_12, (ref) v_u_4
				v_u_12.Model = p16
				if p16 then
					v_u_12:_getTips()
					if v_u_12.Local then
						p17:GiveTask(v_u_4.observeOneChildNamed(p16, "UpdateHeatRemote", function(p18)
							-- upvalues: (ref) v_u_12
							v_u_12._updateHeatRemote = p18
						end))
					end
				end
			end))
		end
	end))
	v_u_12.ShootActionButtonConfig = {
		["primary"] = false,
		["saturateTo"] = 100,
		["priority"] = 500
	}
	v_u_12:Setup()
	v_u_12:DefaultDisableCamLock()
	return v_u_12
end
function v_u_9._getTips(p19)
	-- upvalues: (copy) v_u_5
	if p19.Model then
		local v20 = p19.Model:FindFirstChild("Model")
		if v20 then
			local v21 = v20:FindFirstChild("BlackChrome")
			if v21 then
				p19.Tips = v_u_5.filter(v21:GetChildren(), function(p22)
					return p22.Name == "MachineGun"
				end)
			end
		else
			return
		end
	else
		return
	end
end
function v_u_9._updateIgnoreList(p23)
	p23.IgnoreList = { p23.Character, p23.Model, workspace.Items }
	if p23.BulletEmitter then
		p23.BulletEmitter.IgnoreList = p23.IgnoreList
	end
end
function v_u_9.Setup(p_u_24)
	-- upvalues: (copy) v_u_3, (copy) v_u_1
	p_u_24:_updateIgnoreList()
	p_u_24.LastShoot = 0
	p_u_24.LastPlayerImpact = 0
	p_u_24.SpringThirdMousePosition = v_u_3.new(Vector3.new(), Vector3.new(), 0.9, 30)
	if p_u_24.Local then
		p_u_24.SpringCamera = v_u_3.new(Vector3.new(), Vector3.new(), 0.6, 300)
	end
	p_u_24.SpringSpin = v_u_3.new(0, 0, 0.6, 7)
	p_u_24.SpinTotal = 0
	p_u_24.MouseDown = false
	if not p_u_24.Tips then
		p_u_24.Tips = {}
	end
	p_u_24.TipIndex = 1
	p_u_24:SetupBulletEmitter()
	p_u_24:SetupShoot()
	p_u_24:UpdateMousePosition()
	p_u_24.Maid:GiveTask(v_u_1.RenderStepped:Connect(function()
		-- upvalues: (copy) p_u_24
		p_u_24:RenderStepped()
	end))
	p_u_24.Maid:GiveTask(v_u_1.Stepped:Connect(function()
		-- upvalues: (copy) p_u_24
		p_u_24:Stepped()
	end))
end
function v_u_9.BulletEmitterOnLocalHitPlayer(p25, ...)
	-- upvalues: (copy) v_u_8
	local v26 = tick()
	if v26 - p25.LastPlayerImpact > 0.1 then
		p25.LastPlayerImpact = v26
		v_u_8.BulletEmitterOnLocalHitPlayer(p25, ...)
	end
end
v_u_9.Reload = false
function v_u_9.TransformLocalMousePosition(p27, p28)
	return p27.SpringThirdMousePosition:SetTarget(p28)
end
function v_u_9.UpdateArmJoints(_) end
function v_u_9.UpdateCamera(p29)
	-- upvalues: (copy) v_u_6
	local v30 = p29.SpringCamera:Update()
	local v31 = v_u_6
	v31.CFrame = v31.CFrame * CFrame.new(v30.x * 4, v30.y * 4, 0)
end
function v_u_9.RenderStepped(p32)
	p32:UpdateMousePosition()
	if p32.Local then
		p32:UpdateCamera()
	end
end
function v_u_9.Shoot(p33)
	-- upvalues: (copy) v_u_6
	p33:_updateIgnoreList()
	local v34 = p33.Tips[p33.TipIndex]
	if v34 then
		p33.Tip = v34
		p33.BulletEmitter:Emit(v34.WorldPosition, v34.WorldCFrame.LookVector, p33.Config.BulletSpeed)
		p33.TipIndex = p33.TipIndex % #p33.Tips + 1
		if p33.Local then
			local v35 = 20 / (p33.Model.PrimaryPart.Position - v_u_6.CFrame.p).Magnitude
			local v36 = math.clamp(v35, 0.1, 1)
			local v37 = p33.SpringCamera
			local v38 = math.random() * 2 - 1
			local v39 = math.random() * 2 - 1
			local v40 = math.random() * 2 - 1
			v37:Accelerate(Vector3.new(v38, v39, v40).Unit * v36 * 50)
		end
	else
		p33:_getTips()
	end
end
function v_u_9.ShootCheckConditions(_)
	return true
end
function v_u_9.AnimateBarrel(p41, p42, p43)
	if p41.Model then
		local v44 = tick()
		if p41.Sound then
			p41.Sound.Volume = p43 * 0.5
		end
		local v45 = p41.Config.MaxHeat
		local v46 = p41.Model:GetAttribute("Heat")
		if p43 >= 0.6 and v46 < v45 then
			if v44 - p41.LastShoot > 1 / (10 + 30 * p43) then
				v46 = v46 + p42
				if v45 <= v46 then
					v46 = v46 + 3
					p41:InputEnded({
						["UserInputType"] = Enum.UserInputType.MouseButton1
					})
				end
				p41.LastShoot = v44
				if p41.Local then
					p41:_attemptShoot()
				end
			end
		else
			if v46 > 0 then
				v46 = v46 - p42
			end
			v46 = v46 < 0 and 0 or v46
		end
		local _ = math.clamp(v46, 0, v45) / v45
		p41.Model:SetAttribute("Heat", v46)
	end
end
function v_u_9.Stepped(p47)
	if p47.Model then
		local v48 = tick()
		local v49 = v48 - (p47.LastUpdate or v48)
		p47.LastUpdate = v48
		local v50 = p47.SpringSpin:Update()
		local v51 = p47.SpinTotal + v49 * v50
		if v51 > 6.283185307179586 then
			v51 = v51 - 6.283185307179586
		end
		p47.SpinTotal = v51
		p47:AnimateBarrel(v49, v50)
	end
end
v_u_9.ApplySkin = false
v_u_9.ScopeBegin = false
function v_u_9.Heartbeat(_) end
function v_u_9.InputBegan(p52, p53, p54)
	if p54 then
		return false
	end
	local v55
	if p53.UserInputType == Enum.UserInputType.MouseButton1 then
		v55 = true
	elseif p53.UserInputType == Enum.UserInputType.Gamepad1 then
		v55 = p53.KeyCode == Enum.KeyCode.ButtonX
	else
		v55 = false
	end
	if v55 then
		if p52.Model:GetAttribute("Heat") < p52.Config.MaxHeat then
			p52.SpringSpin:SetTarget(1)
			p52.MouseDown = true
			if not p52.Sound then
				local v56 = Instance.new("Sound")
				v56.SoundId = "rbxassetid://2198390391"
				v56.Volume = 0
				v56.Looped = true
				v56.Parent = p52.Model.PrimaryPart
				v56:Play()
				p52.Sound = v56
			end
		end
		if p52.Local then
			p52:BroadcastInputBegan(p53)
		end
	end
end
function v_u_9.InputEnded(p_u_57, p58, p59)
	if p59 then
		return false
	end
	local v60
	if p58.UserInputType == Enum.UserInputType.MouseButton1 then
		v60 = true
	elseif p58.UserInputType == Enum.UserInputType.Gamepad1 then
		v60 = p58.KeyCode == Enum.KeyCode.ButtonX
	else
		v60 = false
	end
	if v60 then
		p_u_57.SpringSpin:SetTarget(0)
		p_u_57.MouseDown = false
		delay(0.5, function()
			-- upvalues: (copy) p_u_57
			if p_u_57.Sound and not p_u_57.MouseDown then
				p_u_57.Sound:Destroy()
				p_u_57.Sound = nil
			end
		end)
		if p_u_57.Local then
			p_u_57:BroadcastInputEnded(p58)
		end
	end
end
function v_u_9.Unequip(p61)
	if p61.Local and p61._updateHeatRemote then
		p61._updateHeatRemote:FireServer(p61.Model:GetAttribute("Heat"))
	end
	if p61.Sound then
		p61.Sound:Destroy()
		p61.Sound = nil
	end
end
return v_u_9
