-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgM/BUV2ZW50BEluaXQDbmV3DHNldG1ldGF0YWJsZQ9UcmFpbExlbmd0aFRpbWUTU3ByaW5nV2Fpc3RSb3RhdGlvbgpBY2NlbGVyYXRlEFNwcmluZ0l0ZW1PZmZzZXQFTG9jYWwPV2Fsa1NwZWVkU3ByaW5nAW4KbGdsd296aW8wMQNzdWIHcmV2ZXJzZQACdmkKRmlyZVNlcnZlcgZDb25maWcGTW90aW9uA0hpcAdTcHJpbmdzCkl0ZW1PZmZzZXQJU2V0VGFyZ2V0ElNwcmluZ0l0ZW1Sb3RhdGlvbgxJdGVtUm90YXRpb24LT2JqZWN0TG9jYWwGQ2VudGVyBVNvdW5kC3N3b3JkX2x1bmdlDFRpbWVQb3NpdGlvbgZWb2x1bWUFZGVsYXkKU3dpbmdMdW5nZQxzd29yZF9zd29vc2gSU3ByaW5nTmVja1JvdGF0aW9uCWtrbHdvemduMANndmkLU3dpbmdTd29vc2gJd29ya3NwYWNlEEdldFNlcnZlclRpbWVOb3cLX2dldExhc3RVc2UFTW9kZWwFVHJhaWwHRW5hYmxlZAdTdGVwcGVkBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZAVBdWRpbw1DaGFyYWN0ZXJVdGlsBEdhbWUGc2NyaXB0BlBhcmVudAVNZWxlZQxOZWNrUm90YXRpb24NV2Fpc3RSb3RhdGlvbgdWZWN0b3IzClJlbG9hZFRpbWUFU3dvcmQLX19DbGFzc05hbWUHX19pbmRleAAIAgEBAAAABE0BADYAAAAA3gEAAIIAAQABAwEAIAIBGAAAAAEhAAAAAAgDAwAAABP7BAAATQME7wAAAABSBAAAUgUBAPsGAQBSBwIAnwMFAvsGAgCePQMEBgAAAFIFAwCkBAIAAAAQQJ8EAwGMBAAAMAQDWwMAAACCAwIABAMDAwQEAAAQQAMFACMDARgAAAAAAAAAAAEAAAAAAAACAAACJAAAAAALAAMAAAcAAAEDBx4CM/sBAABNAAESAAAAAG8CAQC8AACdAgAAAJ8AAwH7AQAATQABHQMAAABvAgQAvAAAnQIAAACfAAMB+wEAAE0AAbsFAAAADgAgAPsBAQBNAAHcBgAAAIwCIwC8AACdAgAAAJ8AAwH7AAIAbwMHAG8HCACMCQIAjAoGALwHB/AJAAAAnwcEArwHB5sKAAAAnwcCArwHB5sKAAAAnwcCArwHB5sKAAAAnwcCAlIEBwBvBQsAbwYMAHMCAwaMAwIAvAAAaw0AAACfAAQBggABAA4DBgfbD8nA5MsWQQAAAAAAAAAAAwcDCAcAAAAAAAAAAAAA8MEAAAAAAwkDCgMLAwwDDQMOAw8DEAMRAC8AARgAAAAAAAAAAQAAAAAAAAIAAAABAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIwAAAAAAgAAQAAACP7AQAATQABHQAAAAD7BwAATQYH2QEAAABNBQaXAgAAAE0EBb0DAAAATQMEmAQAAABNAgOABQAAALwAAJcGAAAAnwADAfsBAABNAAEABwAAAPsHAABNBgfZAQAAAE0FBpcCAAAATQQFvQMAAABNAwSYBAAAAE0CA+UIAAAAvAAAlwYAAACfAAMBggABAAkDCAMSAxMDFAMVAxYDFwMYAxkAOAABGAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAABOQAAAAAGAQMAAAAx+wIAAE0BAtEAAAAATQIA6gEAAABNBQDZAgAAAE0EBW4DAAAATQMEHQQAAADiBAcAbwUIADAFBMYFAAAAbwUJADAFBEsGAAAAnwEEAU0BAB0KAAAAbwMLALwBAZcMAAAAnwEDAU0BAAANAAAAbwMOALwBAZcMAAAAnwEDAaQBEAAAAPBAbwIRANkDAAASAAAAEgIBABICAgCfAQMBpAEQAAAA8EBvAhIA2QMBABIAAACfAQMBbwESADABAFsTAAAAggABABQDGgMbAxIDHAMdAx4DHwUCBQYCmpmZmZmZuT8CMzMzMzMz0z8DCAcAAAAAAAAAQAAAAD8AAAAAAxcDGAer9LS/AAAAAAAAAAAAAAAAAyAEAADwQAIAAAAAAADQPwLNzMzMzMzcPwMFAgIDKyEBGAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAABAAAAAAABAAAAAAAAAAkAAAAAAAQAAAEsAAAAAA0BAgAABwAAAQMJNAJP+wIAAE0BAtEAAAAATQIA6gEAAABNBQDZAgAAAE0EBW4DAAAATQMEJwQAAADiBAYAbwUHADAFBEsFAAAAnwEEAU0BAB0IAAAAbwMJALwBAZ0KAAAAnwEDAU0BAAALAAAAbwMMALwBAZ0KAAAAnwEDAU0BABINAAAAbwMOALwBAZ0KAAAAnwEDAU0BAIMPAAAAbwMQALwBAZ0KAAAAnwEDAW8BEQAwAQBbEgAAAE0BALsTAAAADgEgAPsBAQBvBBQAbwUVAG8JFgCMCwMAjAwGALwJCfAXAAAAnwkEArwJCZsYAAAAnwkCArwJCZsYAAAAnwkCArwJCZsYAAAAnwkCArwJCZsYAAAAnwkCArwJCZsYAAAAnwkCAlIGCQBvBxUAbwgZAHMDBAiMBAEAvAEBaxoAAACfAQQBggABABsDGgMbAxIDHAMiAx8FAQUCAAAAAAAA6D8DCAcAACBBAADwQQAAoEAAAAAAAwcDGAfSU/vB3X68QQAAAAAAAAAAAwYH2w9JwNJTe0EAAAAAAAAAAAMjB3zZoD/bD0nAAAAAAAAAAAACmpmZmZmZuT8DBQMJAwsDDwMkAw0DDgMlAxEAPiYBGAAAAAAAAAAAAAAAAAAAAAABAAAAAAABAAAAAAABAAAAAAABAAAAAAACAAACAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI/AAAAAAcBAQAAAB2kAQEAAAAAQLwBAbcCAAAAnwECArwCAC0DAAAAnwICAk0FADsEAAAATQQFuQUAAABNAwS5BQAAACYFAQJNBgBbBgAAALcFAgAGAAAAqQQAAakEAQAwBAPwBwAAAPsEAABNAwTZCAAAAFIEAACfAwIBggABAAkDJwQAAABAAygDKQMqAysDBQMsAy0ASy0BGAAAAAAAAQAAAQAAAAAAAAAAAAAAAAAAAQAAAAABTAAAAAALAAABAgBuowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAoQYAAABNAgPSBwAAAJ8BAgKkAgUAAABAQE0EAL0JAAAATQMEwwgAAACfAgICpAQLAAAAoEBNAwQkDAAAAKQEBQAAAEBATQUDMg0AAACfBAIC/wUDAAAAAADiBg8A4gcRAOIIFgBvCRcAMAkIgBIAAABvCRgAMAkI5RMAAABMNgACpAkbAABokIGfCQECMAkIjRQAAABvCRwAMAkIXxUAAAAwCAeYEAAAADAHBr0OAAAAMAYFlx0AAADiBiAAbwchADAHBiceAAAAbwciADAHBh0fAAAAMAYFbiMAAABvBiQAMAYFvCUAAADGBgAA/wcEAAAAAABvCCYAMAgH5ScAAAAwBwduKAAAAJ49BwUEAAAAUgkHAFIKBACkCCoAAACQQp8IAwHZCAAAEgEG/zAIB3MrAAAAwAgsABIABAASAAUAEgAHADAIB+8aAAAA2QgCABIAAQASAAIAEgEG/zAIB9stAAAA2QgDABIAAQASAQb/MAgHzi4AAADACC8AEgAEADAIB9kwAAAAwQYAAIIHAgAxAy4EAAAAQAMvAzADMQQAAEBAAzIDMwM0AzUDNgQAAKBAAzcDOAMUBQEOAxUFARADFgMZAzkDOgUEEhMUFQcAAAAAAAAAPwAAAAAAAAAAB/sEQT4AAAAAfNkgvgAAAAADOwMDBABokIEHfNkgvgAAAAAAAAAAAAAAAAMTAyIDHQUCHh8CAABAa6ob7EECAAAg4Kob7EEDHAIAAAAAAADgPwM8Az0DPgM/AwQEAACQQgMCBgEDIQMmBgYDLQUAAQQFBgEAARgAAQAAAAAAAQAAAAAAAAEAAAAAAAACAAAAAQAAAAACAAEBAQEAAAEAAAEAAAAAAAEAAPwA/wD/AAoBAAABAAD+AAQAAAICAAEAAAEAAQAAAAAAAAEAAAADAAAAAAAIAAAAAAATAAAAAA0AAAAHAAEAAAAAB6JZt5stIdpekJ3dD/1txk412qf3gvFdWwqk8Y9wWCvfYCruy3BuoDU=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.Audio)
local v_u_3 = require(v1.Game.CharacterUtil)
local v4 = script.Parent
local v_u_5 = require(v4.Melee)
local v_u_6 = {}
local v7 = {}
local v8 = {
	["Springs"] = {
		["ItemOffset"] = Vector3.new(0, 0.5, 0),
		["ItemRotation"] = Vector3.new(0.18849556, 0, -0.15707964),
		["NeckRotation"] = Vector3.new(),
		["WaistRotation"] = Vector3.new(-0.15707964, 0, 0)
	}
}
v7.Hip = v8
v_u_6.Motion = v7
v_u_6.Sound = {
	["sword_swoosh"] = 3772601178,
	["sword_lunge"] = 3772602113
}
v_u_6.ReloadTime = 0.5
local v_u_9 = nil
local v_u_10 = {
	["__ClassName"] = "Sword"
}
v_u_10.__index = v_u_10
setmetatable(v_u_10, v_u_5)
function v_u_10.Init(p11)
	-- upvalues: (ref) v_u_9
	v_u_9 = p11.Event
end
function v_u_10.new(p12, p13, p14)
	-- upvalues: (copy) v_u_5, (copy) v_u_6, (copy) v_u_10
	local v15 = v_u_5.new(p12, p13, v_u_6, p14)
	local v16 = v_u_10
	setmetatable(v15, v16)
	v15.TrailLengthTime = 0
	return v15
end
function v_u_10.SwingLunge(p_u_17)
	-- upvalues: (copy) v_u_2, (copy) v_u_3, (ref) v_u_9
	v_u_2.ObjectLocal(p_u_17.Center, p_u_17.Config.Sound.sword_lunge, {
		["TimePosition"] = 0.1,
		["Volume"] = 0.3
	})
	p_u_17.SpringItemOffset:SetTarget(Vector3.new(0, 2, 0.5))
	p_u_17.SpringItemRotation:SetTarget(Vector3.new(-1.4137167, 0, 0))
	delay(0.25, function()
		-- upvalues: (copy) p_u_17, (ref) v_u_3, (ref) v_u_9
		p_u_17.SpringWaistRotation:Accelerate(Vector3.new(-6.2831855, 9.424778, 0))
		p_u_17.SpringItemOffset:Accelerate(Vector3.new(0, 0, -30))
		if p_u_17.Local then
			v_u_3.WalkSpeedSpring:Accelerate(35)
			v_u_9:FireServer("n" .. ("lglwozio01"):sub(2, 6):reverse():reverse():reverse() .. "vi", 2)
		end
	end)
	delay(0.45, function()
		-- upvalues: (copy) p_u_17
		p_u_17.SpringItemOffset:SetTarget(p_u_17.Config.Motion.Hip.Springs.ItemOffset)
		p_u_17.SpringItemRotation:SetTarget(p_u_17.Config.Motion.Hip.Springs.ItemRotation)
	end)
	p_u_17.TrailLengthTime = 0.45
end
function v_u_10.SwingSwoosh(p18)
	-- upvalues: (copy) v_u_2, (ref) v_u_9
	v_u_2.ObjectLocal(p18.Center, p18.Config.Sound.sword_swoosh, {
		["Volume"] = 0.75
	})
	p18.SpringItemOffset:Accelerate(Vector3.new(10, 30, 5))
	p18.SpringItemRotation:Accelerate(Vector3.new(-31.415928, 23.561945, 0))
	p18.SpringWaistRotation:Accelerate(Vector3.new(-3.1415927, 15.707964, 0))
	p18.SpringNeckRotation:Accelerate(Vector3.new(1.2566371, -3.1415927, 0))
	p18.TrailLengthTime = 0.1
	if p18.Local then
		v_u_9:FireServer("n" .. "" .. ("kklwozgn0"):sub(3, 6):reverse():reverse():reverse():reverse():reverse() .. "gvi", 1)
	end
end
function v_u_10.Stepped(p19)
	-- upvalues: (copy) v_u_5
	local v20 = workspace:GetServerTimeNow()
	local v21 = p19:_getLastUse()
	p19.Model.Trail.Trail.Enabled = v20 - v21 < p19.TrailLengthTime
	v_u_5.Stepped(p19)
end
return v_u_10
