-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgOaAQRtYXRoBnJhbmRvbQdWZWN0b3IzA25ldwRVbml0DFJhbmRvbVZlY3RvcgtCYXJyZWxNb3Rvcg1WZXJ0aWNhbE1vdG9yD0hvcml6b250YWxNb3RvcgxGbGFyZUVtaXR0ZXIUb2JzZXJ2ZU9uZUNoaWxkTmFtZWQPUGFydGljbGVFbWl0dGVyCEdpdmVUYXNrC0dldENoaWxkcmVuBFRpcHMPb2JzZXJ2ZUNoaWxkcmVuEV91cGRhdGVIZWF0UmVtb3RlBU1vZGVsBUZsYXJlBUxvY2FsBE1haWQQVXBkYXRlSGVhdFJlbW90ZQ9vYnNlcnZlUHJvcGVydHkFVmFsdWUMc2V0bWV0YXRhYmxlC1R1cnJldFZhbHVlBVNldHVwFURlZmF1bHREaXNhYmxlQ2FtTG9jaw1SZW5kZXJTdGVwcGVkB1N0ZXBwZWQJQ2hhcmFjdGVyBUl0ZW1zCXdvcmtzcGFjZQpJZ25vcmVMaXN0CUxhc3RTaG9vdBBMYXN0UGxheWVySW1wYWN0GFNwcmluZ1RoaXJkTW91c2VQb3NpdGlvbgxTcHJpbmdDYW1lcmEKU3ByaW5nU3BpbglTcGluVG90YWwJTW91c2VEb3duCFRpcEluZGV4ElNldHVwQnVsbGV0RW1pdHRlcg5TZXR1cENyb3NzSGFpcgpTZXR1cFNob290D0J1aWxkUGFja2V0QXJtcwJJSxNVcGRhdGVNb3VzZVBvc2l0aW9uB0Nvbm5lY3QEdGljax1CdWxsZXRFbWl0dGVyT25Mb2NhbEhpdFBsYXllcglTZXRUYXJnZXQbVHJhbnNmb3JtTG9jYWxNb3VzZVBvc2l0aW9uCFJpZ2h0QXJtCFBvc2l0aW9uB0xlZnRBcm0EQXJtcw9VcGRhdGVBcm1Kb2ludHMCb3MFY2xvY2sRX2xhc3RDYW1lcmFVcGRhdGUGVXBkYXRlBkNGcmFtZQZBbmdsZXMBWAFZDFVwZGF0ZUNhbWVyYQ9VcGRhdGVDcm9zc0hhaXIDVGlwDUJ1bGxldEVtaXR0ZXIKbG9va1ZlY3RvcgZDb25maWcLQnVsbGV0U3BlZWQERW1pdAlDcm9zc0hhaXIGU3ByaW5nCkFjY2VsZXJhdGUEQmFjawFwCU1hZ25pdHVkZQVjbGFtcAVTaG9vdBRTaG9vdENoZWNrQ29uZGl0aW9ucwVTb3VuZAZWb2x1bWUHTWF4SGVhdARIZWF0DEdldEF0dHJpYnV0ZQdFbmFibGVkDVVzZXJJbnB1dFR5cGUERW51bQxNb3VzZUJ1dHRvbjEKSW5wdXRFbmRlZA1fYXR0ZW1wdFNob290BkJhcnJlbAtDb2xvck5vcm1hbAlDb2xvckhlYXQETGVycAVDb2xvcgxTZXRBdHRyaWJ1dGUNQW5pbWF0ZUJhcnJlbApMYXN0VXBkYXRlDU1vdXNlUG9zaXRpb24EUm9vdBJQb2ludFRvT2JqZWN0U3BhY2UBeAF5AXoEYXRhbgNjb3MDc2luBUF4aXNWCkpvaW50V2Fpc3QJVHJhbnNmb3JtCUpvaW50TmVjawJDMQlIZWFydGJlYXQIR2FtZXBhZDEHS2V5Q29kZQhCdXR0b25SMghJbnN0YW5jZRdyYnhhc3NldGlkOi8vMjE5ODM5MDM5MQdTb3VuZElkBkxvb3BlZAZQYXJlbnQEUGxheRNCcm9hZGNhc3RJbnB1dEJlZ2FuCklucHV0QmVnYW4HRGVzdHJveQVkZWxheRNCcm9hZGNhc3RJbnB1dEVuZGVkDkZpbmRGaXJzdENoaWxkCkZpcmVTZXJ2ZXIHVW5lcXVpcARnYW1lClJ1blNlcnZpY2UKR2V0U2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQdyZXF1aXJlA1N0ZAVBdWRpbwdSMTVJS3YyBk1vZHVsZQ9SeEluc3RhbmNlVXRpbHMSSW52ZW50b3J5SXRlbVV0aWxzCUludmVudG9yeQ1DdXJyZW50Q2FtZXJhBnNjcmlwdANHdW4GVHVycmV0C19fQ2xhc3NOYW1lB19faW5kZXgJQXBwbHlTa2luBlJlbG9hZAAeBwAAAAAHAAABCAETAhakBAQAAAwggJ8EAQJbAwQBeAIDAKQFBAAADCCAnwUBAlsEBQF4AwQApAYEAAAMIICfBgECWwUGAXgEBQBMNgACpAEHAAAYUICfAQQCTQABBwgAAACCAAIACQIAAAAAAADwPwIAAAAAAAAAQAMBAwIEAAwggAMDAwQEABhQgAMFAA4GARgAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAAAACAQEAAAAE+wEAADAAAaIAAAAAggABAAEDBwAhAAEYAAAAASIAAAAAAgEBAAAABPsBAAAwAAFAAAAAAIIAAQABAwgAJgABGAAAAAEnAAAAAAIBAQAAAAT7AQAAMAAB+QAAAACCAAEAAQMJACsAARgAAAABLAAAAAACAQEAAAAE+wEAADAAAVkAAAAAggABAAEDCgAyAAEYAAAAATMAAAAACAICAAAADPsFAABNBAXqAAAAAFIFAABvBgEA2QcAABICAQCfBAQAvAIB/QIAAACfAgABggABAAMDCwMMAw0BBDAAARgBAAAAAAAAAP8AAAUxAAAAAAMAAgAAAAj7AAAA+wEBALwBAWgAAAAAnwECAjABAJcBAAAAggABAAIDDgMPADoAARgAAAAAAAAAATsAAAAABwICAAAADPsFAABNBAX3AAAAAFIFAADZBgAAEgIBABIAAACfBAMAvAIB/QEAAACfAgABggABAAIDEAMNAQY5AAEYAAAAAAAAAAAAAAADOgAAAAACAQEAAAAE+wEAADAAATQAAAAAggABAAEDEQBEAAEYAAAAAUUAAAAACAICAAAAT/sCAAAwAAI7AAAAAPsFAQBNBAXqAQAAAFIFAABvBgIA2QcAABICAACfBAQAvAIB/QMAAACfAgAB+wUBAE0EBeoBAAAAUgUAAG8GBADZBwEAEgIAAJ8EBAC8AgH9AwAAAJ8CAAH7BQEATQQF6gEAAABSBQAAbwYFANkHAgASAgAAnwQEALwCAf0DAAAAnwIAAfsFAQBNBAXqAQAAAFIFAABvBgYA2QcDABICAQASAgAAnwQEALwCAf0DAAAAnwIAAfsFAQBNBAXqAQAAAFIFAABvBgcA2QcEABICAQASAgAAnwQEALwCAf0DAAAAnwIAAfsDAABNAgO7CAAAAA4CDgD7AwAATQIDdgkAAAD7BQEATQQF6gEAAABSBQAAbwYKANkHBQASAgAAnwQEALwCAv0DAAAAnwIAAYIAAQALAxIDCwMHAw0DCAMJAxMDDwMUAxUDFgYBAgMFBwgeAAEYAAAAAgAAAAAAAAD/AAAGAAAAAAAAAP8AAAYAAAAAAAAA/wAABgAAAAAAAAAA/wAACgAAAAAAAAAA/wAABwAAAAEAAAEAAAEBAQD9/wAACh8AAAAACAICAAAADfsFAABNBAVIAAAAAFIFAABvBgEA2QcAABICAQASAgAAnwQEALwCAf0CAAAAnwIAAYIAAQADAxcDGAMNAQkcAAEYAQAAAAAAAAAA/wAALx0AAAAACgMDAAAAIvsEAABNAwTvAAAAAFIEAABSBQEAnwMDAvsGAQCePQMEBgAAAFIFAwCkBAIAAAAQQJ8EAwFNBAN2AwAAAPsHAgBNBgfqBAAAAFIHAQBvCAUA2QkAABICAgASAAMAnwYEALwEBP0GAAAAnwQAAbwEA5kHAAAAnwQCAbwEA74IAAAAnwQCAYIDAgAJAwQDGQQAABBAAxUDCwMaAw0DGwMcAQoWBAEYAAAAAAAAAQAAAAAAAAIAAQAAAAAAAAAA/wAANAAAAQAAAhgAAAAABAEBAAAABvsBAABSAwAAvAEBzwAAAACfAQMBggABAAEDHQB0AAEYAAAAAAABdQAAAAACAAEAAAAF+wAAALwAANkAAAAAnwACAYIAAQABAx4AdwABGAAAAAABeAAAAAAGAQMAAACDAf8BAAADAAAATQIAaQAAAABNAwA7AQAAAKQFBAAAADBATQQFOAIAAADFAQIEAQAAADABAMoFAAAAjAEAADABACEGAAAAjAEAADABAIoHAAAA+wIAAE0BAu8IAAAATDYAAqQCCgAAIJCAnwIBAkw2AAKkAwoAACCQgJ8DAQJvBAsAjAUeAJ8BBQIwAQA/DAAAAE0BALsNAAAADgEQAPsCAABNAQLvCAAAAEw2AAKkAgoAACCQgJ8CAQJMNgACpAMKAAAgkICfAwECbwQOAIwFSwCfAQUCMAEAtQ8AAAD7AgAATQEC7wgAAACMAgAAjAMAAG8EDgCMBQcAnwEFAjABAEgQAAAAjAEAADABAKwRAAAAqQEAADABAM0SAAAATQEAlxMAAAArAQQA/wEAAAAAAAAwAQCXEwAAAIwBAQAwAQCuFAAAALwBAEoVAAAAnwECAU0BALsNAAAADgEDALwBAJ4WAAAAnwECAbwBAP0XAAAAnwECAfsCAQBNAQLvGAAAAE0CAGkAAAAAnwECAjABAAIZAAAAvAEAlRoAAACfAQIBTQEAdhsAAAD7BAIATQMEzxwAAADZBQAAEgAAALwDA8cdAAAAnwMDALwBAf0eAAAAnwEAAU0BAHYbAAAA+wQCAE0DBNkfAAAA2QUBABIAAAC8AwPHHQAAAJ8DAwC8AQH9HgAAAJ8BAAGCAAEAIAMfAxIDIAMhBAAAMEADIgMjAyQDBAMDBAAgkIACzczMzMzM7D8DJQMUAjMzMzMzM+M/AyYDJwMoAykDDwMqAysDLAMtAy4DLwMwAxUDHQMxAw0DHgIMDVQbARgAAAAAAAAAAAAAAAAAAAIAAAEAAAIAAAAAAAAAAAAAAAAAAAACAAACAAAAAAAAAAAAAAAAAAEAAwAAAAAAAAAAAAEAAAEAAAIAAAEAAAACAAABAAACAAABAAACAAACAAAAAAAAAAEAAAIAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAABlUAAAAABQEBAQAAE6MBAACkAQEAAAAAQJ8BAQJNAwCKAgAAACYCAQNvAwMAYAMJAAIAAAAwAQCKAgAAAPsDAABNAgNyBAAAAFIDAADdBAAAnwIAAYIAAQAFAzIEAAAAQAMkApqZmZmZmbk/AzMAgAEzARgAAwAAAQAAAAAAAQABAAAAAAACgAAAAAAFAgAAAAAHTQIAPwAAAABSBAEAvAIClwEAAACfAgMAggIAAAIDJQM0AIkBNQEYAAAAAAAAAIoAAAAABQEBAAAAFk0BAAIAAAAATQIAOwEAAABNBAKRAgAAAE0DBDsDAAAAMAMBkQIAAABNBAJbBAAAAE0DBDsDAAAAMAMBWwQAAAD7BAAATQMEzAUAAABSBAEAnwMCAYIAAQAGAy8DEgM2AzcDOAM5AIwBOgEYAAABAAEAAAAAAAEAAAAAAAQAAAAAA40AAAAADQEBAAAAKKQBAgAABACAnwEBAk0DADEDAAAAygIDASYDAQIwAQAxAwAAAE0EALUEAAAAvAQEJgUAAACfBAIC+wUAAE0GBYUGAAAApAgIAAAcYICMCQAATQwEeQoAAAAJCwwDWwoLCYwLAACfCAQCpAkIAAAcYIBNDAR4CwAAAAkLDANbCgsJjAsAAIwMAACfCQQCCQcICQkGBgcwBgWFBgAAAIIAAQAMAzsDPAQABACAAz0DJgM+Az8DQAQAHGCAAgAAAAAAAE5AA0EDQgCYAUMBGAAAAAEAAAEBAAIAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGZAAAAAAQCAAAABwQAAAUCBAINvAIAlQAAAACfAgIBTQIAuwEAAAAOAgYAvAIAuAIAAACfAgIBvAIAcQMAAACfAgIBggABAAQDMAMUA0QDQwChAR0BGAAAAAEAAAEAAAEAAAKlAAAAAA8BAQAABwAAAQgJVQJeTQIAlwAAAABNAwCuAQAAAIcBAgMwAQCxAgAAAE0CAGcDAAAATQQBOwQAAABNBgGFBQAAAE0FBkgGAAAATQcA2QcAAABNBgelCAAAALwCAlYJAAAAnwIFAU0EAK4BAAAATQYAlwAAAAAcBQYAzwMEBZUCAwowAgCuAQAAAE0CALsLAAAADgI7AE0DAGwMAAAATQIDIg0AAACMBMgAvAICnQ4AAACfAgMBTQYAOw8AAABNBQZHEAAAAE0EBTsEAAAA+wcAAE0GB4UFAAAATQUGkREAAAAmAwQFTQIDqhIAAADYBBMCbwUUAIwGAQBMLgACpAMXAABYUIGfAwQCUgIDAE0DALUYAAAApAwdAABwUIGfDAECWwsMG3gKCwqkDR0AAHBQgZ8NAQJbDA0beAsMCqQOHQAAcFCBnw4BAlsNDht4DA0KTDYAAqQJIAAAfOCBnwkEAk0ICQchAAAACQcIAlsGBxpbBQYZvAMDnQ4AAACfAwMBggABACIDDwMqA0UDRgM3Az8DRwNIA0kDSgIAAAAAAADwPwMUA0sDTANNAxIDTgNPA1ACAAAAAAAANEACmpmZmZmZuT8DAQNRBABYUIEDJgIAAAAAAAAuQAIzMzMzMzPDPwIAAAAAAAAAQAMCBABwUIEDAwMEBAB84IEDBQCrAVIBGJ0AAAAAAgABAAAAAAAAAAAAAAAAAAABAAAAAAAAAAACAAABAAAAAAAAAAIAAAAAAAAAAAAAAAAAAQAAAAAAAAABAFgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKgAAAIPAAAAAAIBAAAAAAKpAQEAggECAAAAugFTARgAALsAAAAADAMAAAAAe00DADsAAAAAKwMBAIIAAQCkAwIAAAAQQJ8DAQJNBABuAwAAAA4EBABNBABuAwAAADACBEsEAAAATQUA2QUAAABNBAUHBgAAAE0FADsAAAAAbwcHALwFBRIIAAAAnwUDAm8GCQB9BiwAAgAAAGAFKgAEAAAATQcAWQoAAABNBgfwCwAAACsGBQBNBgBZCgAAAKkHAQAwBwbwCwAAAE0HACEMAAAAJgYDB4wJCgCMCx4ACQoLAkMICQrYBw0IYAcoAAYAAABDBQUBfQQKAAUAAACVBQUO4ggQAKQJEwASPBDBMAkIwg8AAAC8BgCvFAAAAJ8GAwEwAwAhDAAAAE0GALsVAAAADgYWALwGACYWAAAAnwYCAWUAEgBNBwBZCgAAAE0GB/ALAAAADgYFAE0GAFkKAAAAqQcAADAHBvALAAAAjAYAAGAGAgAFAAAAJgUFAYwGAABgBQIABgAAAIwFAACMCQAANC4FBQkEAABSCAUAUgoEAKQHGQAAYHCBnwcEAuwGBwRNCAA7AAAAAE0HCHkaAAAATQkA2QUAAABNCAnlGwAAAE0LANkFAAAATQoLUBwAAABSCwYAvAgIXx0AAACfCAQCMAgHpB4AAABNBgA7AAAAAG8IBwBSCQUAvAYGLh8AAACfBgQBggABACADEgMyBAAAEEADVANVA0gDVgNXA1gCMzMzMzMz4z8DCgNZAyMCAAAAAAAA8D8CAAAAAAAACEADWgUBDwNbA1wEEjwQwQNdAxQDXgMBA1EEAGBwgQNfA2ADYQNiA2MDZAC9AWUBGAAAAAECAAACAAABAAAAAgAAAAEAAAAAAAEAAAAAAQAAAAABAAAAAAIAAAAAAAAAAAABAQABAgAAAAAAAAADAAIAAAEAAAAEAAAAAAEAAAAAAgAAAQIAAAEEAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAb4AAAAAFQEAAAAA5QFNAQA7AAAAACsBAQCCAAEATQEA+QEAAAArAQEAggABAE0BAKICAAAAKwEBAIIAAQBNAQBAAwAAACsBAQCCAAEApAEFAAAAQECfAQECTQMABAYAAADKAgMBJgMBAjABAAQGAAAATQQAxwcAAABNBwA7AAAAAE0GB3QIAAAATQUGhQkAAABSBwQAvAUFxgoAAACfBQMCTQYFmQsAAABNBwWYDAAAAE0IBZsNAAAAjAoAAGAIBwAKAAAA7AoGCLsGCgKkCRAAADzggJ8JAgIrCQcAOQwGAOwLDAi7BgsCpAoQAAA84ICfCgIC9QkRCrsJCQNSDQkApAwTAABI4ICfDAICUgoMALsYCQNSDAkApAsVAABQ4ICfCwICCQ0GCgkOCAsmDA0OCQ0ICgkOBgtDCA0OUgYMAE0QADsAAAAATQ8QSBYAAABNDg87FwAAAE0NDngYAAAAJgwHDU0QADsAAAAATQ8QdAgAAABNDg87FwAAAE0NDngYAAAAQwcMDYwNAABgCAgADQAAADkOBwDsDQ4IuwYNAqQMEAAAPOCAnwwCAisMBQDsDQcIuwYNAqQMEAAAPOCAnwwCApUPCREhDg8Zbw8aAG8QGwBMLgACpA0dAABw4ICfDQQCeAkNEW8PHgBvEB8ANC4MBA8QAABSDgwApA0dAABw4ICfDQQCUgwNAE0NAK0gAAAATREArSAAAABNEBEhIQAAAKQRIwAAiJCAjBIAADkUCQBbExQkjBQAAJ8RBAIJDxARpBAjAACIkIA5EgwAWxESJIwSAACMEwAAnxAEAgkODxAwDg0hIQAAAE0NAIolAAAATREAiiUAAABNEBEhIQAAAKQRIwAAiJCAjBIAAFsTCSaMFAAAnxEEAgkPEBGkECMAAIiQgFsRDCaMEgAAjBMAAJ8QBAIJDg8QMA4NISEAAABNDQBIJwAAALwNDSYoAAAAnw0CAk0PAKwpAAAACRADDUMODxBvDxkAYA8CAA4AAAB4Dg4ZMA4ArCkAAABNDwCiAgAAAKQQIwAAiJCAjBEAAIwSAACMFPD/CRMUDp8QBAIwEA/MKgAAAE0PAEADAAAApBAjAACIkIBSEQwAjBIAAIwTAACfEAQCMBAPzCoAAABNDwD5AQAAAKQQIwAAiJCAjBEAAFISCQCMEwAAnxAEAjAQD8wqAAAAvA8AYysAAACfDwIBUhEDAFISDQC8DwDALAAAAJ8PBAGCAAEALQMSAwkDBwMIAzIEAABAQANmA2cDaAM/A2kDagNrA2wDAQNtBAA84IACGC1EVPshCUADbgQASOCAA28EAFDggANwAzcDQgIYLURU+yEZQALSITN/fNkCQAJeOFUpemoPQANRBABw4IACUGnrMcco3r8C4PCcdi8b5D8DcQNyA0AEAIiQgAIAAAAAAADgPwNzAgAAAAAAAABAAycDPgMoA3QDOgNlAOsBHgEYAAAAAQIAAAECAAABAgAAAQMAAAEAAAEBAAIAAQAAAAAAAAAAAAEAAAAAAAIAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAADAAAAAAAAAAABAAAAAAAAAAACAAAAAAABAAAAAAAAAAEAAAAAAAAA/gADAAAAAAABAAAAAAAAAQAAAAAAAP4ABAAAAAABAAAAAQAAAQIAAgAAAAAAAAAAAAABAAAAAAAAAAAAAQAAAAAAAAAAAAIAAAEAAAAAAewAAAAAAQEAAAAAAYIAAQAAAKECdQEYACEBAAAACAMAAAAAT6kDAQBNBAHCAAAAAKQFAwACABDA8QQQAAUAAACpAwAATQQBwgAAAACkBQUABAAQwJoECQAFAAAATQQBswYAAACkBQgABxgQwPEEAgAFAAAAqQMAAakDAQAOAzcATQQAOwkAAABvBgoAvAQEEgsAAACfBAMCTQYA2QwAAABNBQYHDQAAAGAEJQAFAAAATQUASA4AAACMBwEAvAUFlw8AAACfBQMBqQUBADAFAM0QAAAATQUAbhEAAAArBRgApAUUAABMIIFvBhEAnwUCAm8GFQAwBgV8FgAAAIwGAAAwBgVLFwAAAKkGAQAwBgW1GAAAAE0HADsJAAAATQYHeRkAAAAwBgUkGgAAALwGBe4bAAAAnwYCATAFAG4RAAAATQUAuxwAAAAOBQQAUgcBALwFAAodAAAAnwUDAYIAAQAeA1oDWwNcBAIAEMADdgQEABDAA3cDeAQHGBDAAxIDVwNYA0gDVgMnAzQDKQNUA3kDBAQATCCBA3oDewNVA3wDXwN9A34DFAN/AKICgAEBGAAAAAAAAAABAAAAAAAAAAAAAAAAAAACAQAAAAAAAQAAAAAAAQAAAAAAAQAAAQAAAQAAAAEAAAEAAAEAAAEAAAAAAAEAAAEAAwAAAQAAAAMkAQAAAAIAAQAAABP7AQAATQABbgAAAAAOAA4A+wEAAE0AAc0BAAAAKwAKAPsBAABNAAFuAAAAALwAAFACAAAAnwACAfsAAADGAQAAMAEAbgAAAACCAAEAAwNUAykDgQEAwwIAARgAAAAAAAAAAAEAAAAAAAEAAAACRAEAAAAHAwAAAAAuqQMBAE0EAcIAAAAApAUDAAIAEMDxBBAABQAAAKkDAABNBAHCAAAAAKQFBQAEABDAmgQJAAUAAABNBAGzBgAAAKQFCAAHGBDA8QQCAAUAAACpAwABqQMBAA4DFgBNBABICQAAAIwGAAC8BASXCgAAAJ8EAwGpBAAAMAQAzQsAAACkBA0AAADAQG8FDgDZBgAAEgAAAJ8EAwFNBAC7DwAAAA4EBABSBgEAvAQAuRAAAACfBAMBggABABEDWgNbA1wEAgAQwAN2BAQAEMADdwN4BAcYEMADJwM0AykDggEEAADAQAIAAAAAAADgPwMUA4MBARq7Al0BGAAAAAAAAAABAAAAAAAAAAAAAAAAAAACAQAAAAAAAQAAAQAAAAAABgAAAQAAAAM9AQAAAAYBAAAAADlNAQBZAAAAAA4BBQBNAQBZAAAAAKkCAAAwAgHwAQAAAE0BADsCAAAADgERAE0BADsCAAAAbwMDALwBAQMEAAAAnwEDAg4BCgBNAgA7AgAAAE0BAnkDAAAATQMA2QUAAABNAgPlBgAAADACAaQHAAAATQEAuwgAAAAOAQ4ATQEANAkAAAAOAQsATQEANAkAAABNAwA7AgAAAG8FCgC8AwMSCwAAAJ8DAwC8AQFrDAAAAJ8BAAFNAQBuDQAAAA4BCABNAQBuDQAAALwBAVAOAAAAnwECAcYBAAAwAQBuDQAAAIIAAQAPAwoDWQMSA18DhAEDSANgA2MDFAMRA1cDWAOFAQNUA4EBAM4ChgEBGAAAAAEAAAAABAAAAAAAAAAAAAEAAAAAAAAAAAACAAABAAABAAAAAAAAAAAAAAMAAAEAAAAAAQAAAk8BAAAADwAAAQIAigGjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIGAAAAUEBNBAGhBwAAAE0DBNIIAAAAnwICAqQDBgAAAFBATQUBQAoAAABNBAVKCQAAAJ8DAgKkBAYAAABQQE0GAaEHAAAATQUGIgsAAACfBAICpAUGAAAAUEBNBwGhBwAAAE0GB1IMAAAAnwUCAqQGBgAAAFBATQgBYA4AAABNBwh3DQAAAJ8GAgKkCBAAAADwQE0HCEgRAAAApAkTAAAAIEFNCAkkFAAAAKQJBgAAAFBATQoIDRUAAACfCQICwAoWAP8LBgAAAAAAbwwXADAMC+UYAAAAMAsLbhkAAACePQsFCQAAAFINCwBSDgkApAwbAAAAoEGfDAMBwAwcABIACQASAAsAEgAFADAMC+8dAAAAwAweABIABAASAAMAEgAAADAMC5kfAAAAqQwAADAMC+kgAAAAqQwAADAMCzchAAAAwAwiABIACQAwDAtyIwAAAMAMJAAwDAuBJQAAAMAMJgASAAMAMAwLYycAAADADCgAEgAHADAMC3EpAAAAwAwqADAMC88rAAAAwAwsABIABwAwDAvoLQAAAMAMLgAwDAupLwAAAMAMMAAwDAvAMQAAAMAMMgAwDAvZMwAAAMAMNAAwDAv9NQAAAMAMNgAwDAuCNwAAAMAMOAAwDAuvOQAAAMAMOgAwDAu4OwAAAIILAgA8A4cBBAAAAEADiAEDiQEDigEDiwEEAABQQAOMAQONAQOOAQOPAQNMA5ABA5EBA5IBAyEEAADwQAOTAQOUAQQAACBBA30DlQEGAAOWAQOXAQOYAQMZBAAAoEEGCwMEBg4DGwOZAQOaAQYPAzMGEAM1BhEDOgYSA0MGEwMdBhQDUgYVA1MGFgNlBhcDHgYYA3UGGQOAAQYbA10GHAOGARAACw4PEBESExQVFhcYGRscAQABBQABAAAAAAABAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAA+wABAAAAAAAAAQAAAAAAAAEAAAACAAAAAQAAAAACBAD0AAABAAEAAAAAAAABAAAAAAA+AAAAAAAqAAABAAABAJMACQAAAwAAAAwAAAAJAAAKAAAADwAAAwAALgAANgAAXwAAGQAAEwAAFAEAAAAFAAAADQAAAG0AAACiAAAAAB0x+ggAdOrN8gM+YpRCEsh3JpdZ20+jYi8eF6TqwedtKO0xBPOW5oID

-- Decompiled by Krnl

local v_u_1 = game:GetService("RunService")
local v2 = game:GetService("ReplicatedStorage")
require(v2.Std.Audio)
local v_u_3 = require(v2.Module.R15IKv2)
local v_u_4 = require(v2.Std.Spring)
local v_u_5 = require(v2.Std.RxInstanceUtils)
require(v2.Inventory.InventoryItemUtils)
local v_u_6 = workspace.CurrentCamera
local v7 = script.Parent
local v_u_8 = require(v7.Gun)
local v_u_9 = {
	["__ClassName"] = "Turret"
}
v_u_9.__index = v_u_9
setmetatable(v_u_9, v_u_8)
function v_u_9.new(p10, p11, _)
	-- upvalues: (copy) v_u_8, (copy) v_u_9, (copy) v_u_5
	local v_u_12 = v_u_8.new(p10, p11)
	local v13 = v_u_9
	setmetatable(v_u_12, v13)
	v_u_12.Maid:GiveTask(v_u_5.observeOneChildNamed(p11, "TurretValue", function(p14, p15)
		-- upvalues: (ref) v_u_5, (copy) v_u_12
		p15:GiveTask(v_u_5.observeProperty(p14, "Value", function(p16, p17)
			-- upvalues: (ref) v_u_12, (ref) v_u_5
			v_u_12.Model = p16
			p17:GiveTask(v_u_5.observeOneChildNamed(p16, "BarrelMotor", function(p18)
				-- upvalues: (ref) v_u_12
				v_u_12.BarrelMotor = p18
			end))
			p17:GiveTask(v_u_5.observeOneChildNamed(p16, "VerticalMotor", function(p19)
				-- upvalues: (ref) v_u_12
				v_u_12.VerticalMotor = p19
			end))
			p17:GiveTask(v_u_5.observeOneChildNamed(p16, "HorizontalMotor", function(p20)
				-- upvalues: (ref) v_u_12
				v_u_12.HorizontalMotor = p20
			end))
			p17:GiveTask(v_u_5.observeOneChildNamed(p16, "Flare", function(p21, p22)
				-- upvalues: (ref) v_u_5, (ref) v_u_12
				p22:GiveTask(v_u_5.observeOneChildNamed(p21, "ParticleEmitter", function(p23)
					-- upvalues: (ref) v_u_12
					v_u_12.FlareEmitter = p23
				end))
			end))
			p17:GiveTask(v_u_5.observeOneChildNamed(p16, "Tips", function(p_u_24, p25)
				-- upvalues: (ref) v_u_5, (ref) v_u_12
				p25:GiveTask(v_u_5.observeChildren(p_u_24, function()
					-- upvalues: (ref) v_u_12, (copy) p_u_24
					v_u_12.Tips = p_u_24:GetChildren()
				end))
			end))
			if v_u_12.Local then
				v_u_12.Maid:GiveTask(v_u_5.observeOneChildNamed(p16, "UpdateHeatRemote", function(p26)
					-- upvalues: (ref) v_u_12
					v_u_12._updateHeatRemote = p26
				end))
			end
		end))
	end))
	v_u_12:Setup()
	v_u_12:DefaultDisableCamLock()
	return v_u_12
end
function v_u_9.Setup(p_u_27)
	-- upvalues: (copy) v_u_4, (copy) v_u_3, (copy) v_u_1
	p_u_27.IgnoreList = { p_u_27.Character, p_u_27.Model, workspace.Items }
	p_u_27.LastShoot = 0
	p_u_27.LastPlayerImpact = 0
	p_u_27.SpringThirdMousePosition = v_u_4.new(Vector3.new(), Vector3.new(), 0.9, 30)
	if p_u_27.Local then
		p_u_27.SpringCamera = v_u_4.new(Vector3.new(), Vector3.new(), 0.6, 75)
	end
	p_u_27.SpringSpin = v_u_4.new(0, 0, 0.6, 7)
	p_u_27.SpinTotal = 0
	p_u_27.MouseDown = false
	if not p_u_27.Tips then
		p_u_27.Tips = {}
	end
	p_u_27.TipIndex = 1
	p_u_27:SetupBulletEmitter()
	if p_u_27.Local then
		p_u_27:SetupCrossHair()
	end
	p_u_27:SetupShoot()
	p_u_27.IK = v_u_3.BuildPacketArms(p_u_27.Character)
	p_u_27:UpdateMousePosition()
	p_u_27.Maid:GiveTask(v_u_1.RenderStepped:Connect(function(p28)
		-- upvalues: (copy) p_u_27
		p_u_27:RenderStepped(p28)
	end))
	p_u_27.Maid:GiveTask(v_u_1.Stepped:Connect(function()
		-- upvalues: (copy) p_u_27
		p_u_27:Stepped()
	end))
end
v_u_9.ApplySkin = false
v_u_9.Reload = false
function v_u_9.BulletEmitterOnLocalHitPlayer(p29, ...)
	-- upvalues: (copy) v_u_8
	local v30 = tick()
	if v30 - p29.LastPlayerImpact > 0.1 then
		p29.LastPlayerImpact = v30
		v_u_8.BulletEmitterOnLocalHitPlayer(p29, ...)
	end
end
function v_u_9.TransformLocalMousePosition(p31, p32)
	return p31.SpringThirdMousePosition:SetTarget(p32)
end
function v_u_9.UpdateArmJoints(p33)
	-- upvalues: (copy) v_u_3
	local v34 = p33.IK
	local v35 = p33.Model
	v34.RightArm = v35.RightArm.Position
	v34.LeftArm = v35.LeftArm.Position
	v_u_3.Arms(v34)
end
function v_u_9.UpdateCamera(p36)
	-- upvalues: (copy) v_u_6
	local v37 = os.clock()
	local v38 = v37 - (p36._lastCameraUpdate or v37)
	p36._lastCameraUpdate = v37
	local v39 = p36.SpringCamera:Update()
	local v40 = v_u_6
	v40.CFrame = v40.CFrame * (CFrame.Angles(0, v39.X * v38 * 60, 0) * CFrame.Angles(v39.Y * v38 * 60, 0, 0))
end
function v_u_9.RenderStepped(p41, _)
	p41:UpdateMousePosition()
	if p41.Local then
		p41:UpdateCrossHair()
		p41:UpdateCamera()
	end
end
function v_u_9.Shoot(p42)
	-- upvalues: (copy) v_u_6
	local v43 = p42.Tips[p42.TipIndex]
	p42.Tip = v43
	p42.BulletEmitter:Emit(v43.Position, v43.CFrame.lookVector, p42.Config.BulletSpeed)
	p42.TipIndex = p42.TipIndex % #p42.Tips + 1
	if p42.Local then
		p42.CrossHair.Spring:Accelerate(200)
		local v44 = 20 / (p42.Model.Back.Position - v_u_6.CFrame.p).Magnitude
		local v45 = math.clamp(v44, 0.1, 1)
		local v46 = p42.SpringCamera
		local v47 = math.random() * 2 - 1
		local v48 = math.random() * 2 - 1
		local v49 = math.random() * 2 - 1
		v46:Accelerate(Vector3.new(v47, v48, v49).Unit * v45 * 0.15 * 15)
	end
end
function v_u_9.ShootCheckConditions(_)
	return true
end
function v_u_9.AnimateBarrel(p50, p51, p52)
	if p50.Model then
		local v53 = tick()
		if p50.Sound then
			p50.Sound.Volume = p52
		end
		local v54 = p50.Config.MaxHeat
		local v55 = p50.Model:GetAttribute("Heat")
		if p52 >= 0.6 and v55 < v54 then
			if not p50.FlareEmitter.Enabled then
				p50.FlareEmitter.Enabled = true
			end
			if v53 - p50.LastShoot > 1 / (10 + 30 * p52) then
				v55 = v55 + p51
				if v54 <= v55 then
					v55 = v55 + 3
					p50:InputEnded({
						["UserInputType"] = Enum.UserInputType.MouseButton1
					})
				end
				p50.LastShoot = v53
				if p50.Local then
					p50:_attemptShoot()
				end
			end
		else
			if p50.FlareEmitter.Enabled then
				p50.FlareEmitter.Enabled = false
			end
			if v55 > 0 then
				v55 = v55 - p51
			end
			v55 = v55 < 0 and 0 or v55
		end
		local v56 = math.clamp(v55, 0, v54) / v54
		p50.Model.Barrel.Color = p50.Config.ColorNormal:Lerp(p50.Config.ColorHeat, v56)
		p50.Model:SetAttribute("Heat", v55)
	end
end
function v_u_9.Stepped(p57)
	if not p57.Model then
		return
	end
	if not p57.HorizontalMotor then
		return
	end
	if not p57.BarrelMotor then
		return
	end
	if not p57.VerticalMotor then
		return
	end
	local v58 = tick()
	local v59 = v58 - (p57.LastUpdate or v58)
	p57.LastUpdate = v58
	local v60 = p57.MousePosition
	local v61 = p57.Model.Root.CFrame:PointToObjectSpace(v60)
	local v62 = v61.x
	local v63 = v61.y
	local v64 = v61.z
	if v64 < 0 then
		local v65 = v62 / v64
		v79 = math.atan(v65)
		if v79 then
			::l11::
			local v66 = math.cos(v79)
			local v67 = math.sin(v79)
			local _ = v62 * v66 - v64 * v67
			local v68 = v64 * v66 + v62 * v67
			local v69 = v63 - p57.Model.AxisV.Position.Y + p57.Model.Root.Position.Y
			if v68 < 0 then
				local v70 = -v69 / v68
				v77 = math.atan(v70)
				if v77 then
					::l14::
					local v71 = (v79 + 3.141592653589793) % 6.283185307179586
					local v72 = math.clamp(v71, 2.356194490192345, 3.9269908169872414) - 3.141592653589793
					local v73 = math.clamp(v77, -0.47123889803846897, 0.6283185307179586)
					p57.JointWaist.Transform = p57.JointWaist.Transform * CFrame.Angles(0, -v72 * 0.5, 0) * CFrame.Angles(-v73 * 0.5, 0, 0)
					p57.JointNeck.Transform = p57.JointNeck.Transform * CFrame.Angles(0, v72 * 2, 0) * CFrame.Angles(v73 * 2, 0, 0)
					local v74 = p57.SpringSpin:Update()
					local v75 = p57.SpinTotal + v59 * v74
					if v75 > 6.283185307179586 then
						v75 = v75 - 6.283185307179586
					end
					p57.SpinTotal = v75
					p57.BarrelMotor.C1 = CFrame.Angles(0, 0, -16 * v75)
					p57.VerticalMotor.C1 = CFrame.Angles(v73, 0, 0)
					p57.HorizontalMotor.C1 = CFrame.Angles(0, v72, 0)
					p57:UpdateArmJoints()
					p57:AnimateBarrel(v59, v74)
					return
				end
			end
			local v76 = v69 / v68
			local v77 = math.atan(v76)
			goto l14
		end
	end
	local v78 = -v62 / v64
	local v79 = 3.141592653589793 - math.atan(v78)
	goto l11
end
function v_u_9.Heartbeat(_) end
function v_u_9.InputBegan(p80, p81, _)
	local v82
	if p81.UserInputType == Enum.UserInputType.MouseButton1 then
		v82 = true
	elseif p81.UserInputType == Enum.UserInputType.Gamepad1 then
		v82 = p81.KeyCode == Enum.KeyCode.ButtonR2
	else
		v82 = false
	end
	if v82 then
		if p80.Model:GetAttribute("Heat") < p80.Config.MaxHeat then
			p80.SpringSpin:SetTarget(1)
			p80.MouseDown = true
			if not p80.Sound then
				local v83 = Instance.new("Sound")
				v83.SoundId = "rbxassetid://2198390391"
				v83.Volume = 0
				v83.Looped = true
				v83.Parent = p80.Model.Barrel
				v83:Play()
				p80.Sound = v83
			end
		end
		if p80.Local then
			p80:BroadcastInputBegan(p81)
		end
	end
end
function v_u_9.InputEnded(p_u_84, p85, _)
	local v86
	if p85.UserInputType == Enum.UserInputType.MouseButton1 then
		v86 = true
	elseif p85.UserInputType == Enum.UserInputType.Gamepad1 then
		v86 = p85.KeyCode == Enum.KeyCode.ButtonR2
	else
		v86 = false
	end
	if v86 then
		p_u_84.SpringSpin:SetTarget(0)
		p_u_84.MouseDown = false
		delay(0.5, function()
			-- upvalues: (copy) p_u_84
			if p_u_84.Sound and not p_u_84.MouseDown then
				p_u_84.Sound:Destroy()
				p_u_84.Sound = nil
			end
		end)
		if p_u_84.Local then
			p_u_84:BroadcastInputEnded(p85)
		end
	end
end
function v_u_9.Unequip(p87)
	if p87.FlareEmitter then
		p87.FlareEmitter.Enabled = false
	end
	if p87.Model and p87.Model:FindFirstChild("Barrel") then
		p87.Model.Barrel.Color = p87.Config.ColorNormal
	end
	if p87.Local and p87._updateHeatRemote then
		p87._updateHeatRemote:FireServer(p87.Model:GetAttribute("Heat"))
	end
	if p87.Sound then
		p87.Sound:Destroy()
		p87.Sound = nil
	end
end
return v_u_9
