-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMfA25ldwxzZXRtZXRhdGFibGUFU2V0dXALT2JqZWN0TG9jYWwDVGlwBkNvbmZpZwVTb3VuZApkcnlfZmlyZTAxBlZvbHVtZQVQaXRjaARtYXRoBnJhbmRvbQdzaG90XzAxClNob290U291bmQmZ3VuX3NlbWlfYXV0b19yaWZsZV9tYWdhemluZV91bmxvYWRfMDESUm9sbE9mZk1heERpc3RhbmNlE1JlbG9hZERyb3BBbW1vU291bmQkZ3VuX3NlbWlfYXV0b19yaWZsZV9tYWdhemluZV9sb2FkXzAxFVJlbG9hZFJlZmlsbEFtbW9Tb3VuZARnYW1lEVJlcGxpY2F0ZWRTdG9yYWdlCkdldFNlcnZpY2UHcmVxdWlyZQNTdGQFQXVkaW8Gc2NyaXB0BlBhcmVudANHdW4DVXppC19fQ2xhc3NOYW1lB19faW5kZXgABQcDAgAAABP7BAAATQME7wAAAABSBAAAUgUBAFIGAgCfAwQC+wYBAJ49AwQGAAAAUgUDAKQEAgAAABBAnwQDAVIGAgC8BAOZAwAAAJ8EAwGCAwIABAMBAwIEAAAQQAMDAAwBARgAAAAAAAAAAQAAAAAAAAEAAAACDQAAAAALAgEAAAAyDgEaAPsDAABNAgPRAAAAAE0DALEBAAAATQYA2QIAAABNBQZuAwAAAE0EBekEAAAA4gUHAG8GCAAwBgVLBQAAAIwIAQCkCg0AADCwgJ8KAQJbCQoKQwcICXgGBwkwBgUABgAAAJ8CBAGCAAEA+wMAAE0CA9EAAAAATQMAsQEAAABNBgDZAgAAAE0FBm4DAAAATQQFiA4AAADiBQ8AjAgBAKQKDQAAMLCAnwoBAlsJCgpDBwgJeAYHCTAGBQAGAAAAnwIEAYIAAQAQAwQDBQMGAwcDCAMJAwoFAgUGApqZmZmZmdk/ApqZmZmZmak/ApqZmZmZmbk/AwsDDAQAMLCAAw0FAQYAEw4BGAABAAABAAEAAAAAAAEAAAAAAAAAAAAAAAD9AAYAAAAAAAAAAAAAAAAAAAAAAAAAAAACFAAAAAAGAQEAAAAR+wIAAE0BAtEAAAAATQIAsQEAAABNBQDZAgAAAE0EBW4DAAAATQMEHgQAAADiBAYAjAWBADAFBCoFAAAAnwEEAYIAAQAHAwQDBQMGAwcDDwMQBQEFAB4RARgAAAAAAAAAAAAAAAABAAD/Ax8AAAAABgEBAAAAEfsCAABNAQLRAAAAAE0CALEBAAAATQUA2QIAAABNBAVuAwAAAE0DBP8EAAAA4gQGAIwFgQAwBQQqBQAAAJ8BBAGCAAEABwMEAwUDBgMHAxIDEAUBBQAjEwEYAAAAAAAAAAAAAAAAAQAA/wMkAAAAAAgAAAECADejAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CA9IHAAAAnwECAqQDCQAAAIBATQIDJAoAAACkAwUAAABAQE0EAg0LAAAAnwMCAv8EBAAAAAAAbwUMADAFBOUNAAAAMAQEbg4AAACePQQFAwAAAFIGBABSBwMApAUQAAAA8ECfBQMBwAURABIAAwASAAQAMAUE7xIAAADABRMAEgABADAFBLkUAAAAwAUVABIAAQAwBQS9FgAAAMAFFwASAAEAMAUEeRgAAACCBAIAGQMUBAAAAEADFQMWAxcEAABAQAMYAxkDGgQAAIBAAxsDHAMdAx4DHwMCBAAA8EAGAAMBBgEDDgYCAxEGAwMTBAABAgMBAAEYAAEAAAAAAAEAAAAAAAACAAAAAQAAAAACAAEAAAEAAQAAAAAAAAEAAAAABwAAAAsAAAAFAAAABgEAAAAABKutguXaM69MmWnocVjm6OFV1jzjjve0j+CJwumq4VS6EJjbcYgHHvM=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.Audio)
local v3 = script.Parent
local v_u_4 = require(v3.Gun)
local v_u_5 = {
	["__ClassName"] = "Uzi"
}
v_u_5.__index = v_u_5
setmetatable(v_u_5, v_u_4)
function v_u_5.new(p6, p7, p8)
	-- upvalues: (copy) v_u_4, (copy) v_u_5
	local v9 = v_u_4.new(p6, p7, p8)
	local v10 = v_u_5
	setmetatable(v9, v10)
	v9:Setup(p8)
	return v9
end
function v_u_5.ShootSound(p11, p12)
	-- upvalues: (copy) v_u_2
	if p12 then
		v_u_2.ObjectLocal(p11.Tip, p11.Config.Sound.dry_fire01, {
			["Volume"] = 0.4,
			["Pitch"] = 1 + math.random() * 0.1 - 0.05
		})
	else
		v_u_2.ObjectLocal(p11.Tip, p11.Config.Sound.shot_01, {
			["Pitch"] = 1 + math.random() * 0.1 - 0.05
		})
	end
end
function v_u_5.ReloadDropAmmoSound(p13)
	-- upvalues: (copy) v_u_2
	v_u_2.ObjectLocal(p13.Tip, p13.Config.Sound.gun_semi_auto_rifle_magazine_unload_01, {
		["RollOffMaxDistance"] = 129
	})
end
function v_u_5.ReloadRefillAmmoSound(p14)
	-- upvalues: (copy) v_u_2
	v_u_2.ObjectLocal(p14.Tip, p14.Config.Sound.gun_semi_auto_rifle_magazine_load_01, {
		["RollOffMaxDistance"] = 129
	})
end
return v_u_5
