-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMLBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplCFRBR19OQU1FHENVUlJFTlRfSU5WRU5UT1JZX1ZBTFVFX05BTUUJSW52ZW50b3J5EEN1cnJlbnRJbnZlbnRvcnkAAQUAAAECABmjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CAxgHAAAAnwECAk0CAQAIAAAA4gMLAG8EDAAwBAO0CQAAAG8EDQAwBAMLCgAAAJ8CAgCCAgAADgMBBAAAAEADAgMDAwQEAABAQAMFAwYDBwMIAwkFAgkKAwoDCwABAAEYAAEAAAAAAAEAAAAAAAABAAABAAABAAD+AAEAAAAAAJEYM5z8/2RMo9xZCG5D5UYacUbvfa+whCY+5CVZC8NJlbpDXqXauvQ=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Std.TableUtils).requireValidIndexAndFreeze({
	["TAG_NAME"] = "Inventory",
	["CURRENT_INVENTORY_VALUE_NAME"] = "CurrentInventory"
})
