-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgM7C3NldEVxdWlwcGVkA29iag1BdHRlbXB0U2VsZWN0DU9uQ2xpZW50RXZlbnQHQ29ubmVjdAhHaXZlVGFzaxJFUVVJUFBFRF9BVFRSX05BTUUMR2V0QXR0cmlidXRlGEVRVUlQUEVEX0xPQ0FMX0FUVFJfTkFNRQxTZXRBdHRyaWJ1dGUGdXBkYXRlDHNldG1ldGF0YWJsZQNuZXcFX21haWQPb25BdHRlbXB0U2VsZWN0DW9uQXR0ZW1wdERyb3AUb2JzZXJ2ZU9uZUNoaWxkTmFtZWQRRVFVSVBfUkVNT1RFX05BTUUZR2V0QXR0cmlidXRlQ2hhbmdlZFNpZ25hbBBfb3ZlcnJpZGRlbk93bmVyB2dldE5hbWUHR2V0TmFtZQZQYXJlbnQDR2V0BGdhbWUHUGxheWVycwpHZXRTZXJ2aWNlCEdldE93bmVyB3Jlc29sdmUHUHJvbWlzZQxQcm9taXNlT3duZXIHZ2V0QXR0cgdHZXRBdHRyB3NldEF0dHIHU2V0QXR0cgtnZXRFcXVpcHBlZAtHZXRFcXVpcHBlZAtTZXRFcXVpcHBlZBFnZXRFcXVpcHBlZFNpZ25hbBFHZXRFcXVpcHBlZFNpZ25hbA1taXNzaW5nIHZhbHVlBmFzc2VydA5GaW5kRmlyc3RDaGlsZApGaXJlU2VydmVyEkF0dGVtcHRTZXRFcXVpcHBlZARGaXJlC0F0dGVtcHREcm9wB0Rlc3Ryb3kRUmVwbGljYXRlZFN0b3JhZ2UHcmVxdWlyZQNTdGQETWFpZAZTaWduYWwPUnhJbnN0YW5jZVV0aWxzE0ludmVudG9yeUl0ZW1Db25zdHMGc2NyaXB0EkludmVudG9yeUl0ZW1VdGlscxhJbnZlbnRvcnlJdGVtT3duZXJCaW5kZXIHX19pbmRleAASAwACAAAACfsBAABNAAEZAAAAAPsCAQBNAQITAQAAAKkCAACfAAMBggABAAIDAQMCABoAARgAAAAAAAAAAAEbAAAAAAIAAQAAAAX7AAAAvAAAuQAAAACfAAIBggABAAEDAwAkAAEYAAAAAAElAAAAAAcCAQAAAAtNBACMAAAAANkGAAASAgAAvAQExwEAAACfBAMAvAIB/QIAAACfAgABggABAAMDBAMFAwYBASMAARgAAAAAAAAAAAAAAyQAAAAABgACAAAAG/sBAAD7BAEATQMEbwEAAAC8AQESAgAAAJ8BAwKQAAEA+wIAAPsFAQBNBAUeAwAAALwCAhICAAAAnwIDApABAgBgAQkAAAAAAPsBAAD7BAEATQMEHgMAAABSBAAAvAEBLgQAAACfAQQBggABAAUCAAAAAAAAAAADBwMIAwkDCgArCwEYAAAAAAAAAAABAAAAAAAAAAAAAQAAAAAAAAACLQAAAAAJAQYAAABv/wEEAAAAAAD7BAAAnj0BBAQAAABSAwEApAIBAAAAAECfAgMBMAABEwIAAAD7AwEATQID7wMAAACfAgECMAIBwQQAAAD7AwIATQID7wMAAACfAgECMAIB2QUAAABNAgHBBAAAAE0EAdkFAAAAvAIC/QYAAACfAgMB+wMCAE0CA+8DAAAAnwIBAjACAeQHAAAATQIBwQQAAABNBAHkBwAAALwCAv0GAAAAnwIDAU0CAcEEAAAA2QQAABICAwASAAEAvAIC/QYAAACfAgMBTQIBwQQAAAD7BQQATQQF6ggAAABSBQAA+wcFAE0GBx8JAAAA2QcBABIAAQCfBAQAvAIC/QYAAACfAgAB2QICABIAAAASAgUATQMBwQQAAAD7CAUATQcIbwoAAAC8BQAWCwAAAJ8FAwJSBwIAvAUFxwwAAACfBQMAvAMD/QYAAACfAwAB+wcFAE0GB28KAAAAvAQAEg4AAACfBAMCkAMEDfsIBQBNBwgeDwAAALwFABIOAAAAnwUDApAEBQ1gBAgAAwAAAPsHBQBNBgceDwAAAFIHAwC8BAAuEAAAAJ8EBAHGAwAAMAMBwhEAAACCAQIAEgMMBAAAAEADAgMNAw4DDwMGAxADEQMSAwcDEwMFAgAAAAAAAAAAAwgDCQMKAxQDAAIDDw0BGAAAAQAAAAAAAAIAAQAAAAAAAQAAAAAAAQAAAAAAAAEAAAAAAAEAAAAAAAACAAAAAAAAAAUAAQAAAQEAAAEA/f8AAAwAAAcAAAAAAAAAAAAAAAAAAPsAAAAAAAABAAAAAAAAAAABAAAAAAAABgAAAhAAAAAAAwEBAAAAB/sCAABNAQK2AAAAAE0CABMBAAAAnwECAIIBAAACAxUDAgA5FgEYAAAAAAAAADoAAAAABwEBAAAAG00DABMAAAAATQIDJAEAAABNAQIkAQAAACsBAQCCAAEA+wIAAFIEAQC8AgJ/AgAAAJ8CAwIOAgEAggICAE0DASQBAAAApAQEAAAAMEBvBgUAvAQEFgYAAACfBAMCmgMCAAQAAACCAQIAggABAAcDAgMXAxgDGQQAADBAAxoDGwA8HAEYAAAAAAAAAQEDAAAAAAEBAwAAAAAAAAAAAAECPQAAAAAGAQIAAAAeTQMAEwAAAABNAgMkAQAAAE0BAiQBAAAAKwEBAIIAAQBNAgEkAQAAAKQDAwAAACBAbwUEALwDAxYFAAAAnwMDApoCBwADAAAA+wMAAE0CAx0GAAAAUgMBAJ8CAgCCAgAA+wIBAFIEAQC8AgJyBwAAAJ8CAwCCAgAACAMCAxcDGQQAACBAAxoDGwMdAx4ASx8BGAAAAAAAAAEBAgAAAAAAAAAAAAEAAAAAAAIAAAAAAEwAAAAABAEBAQAACaMBAAD7AgAATQECWwAAAABNAgATAQAAAN0DAACfAQAAggEAAAIDIAMCAFUhARgAAQAAAAAAAABVAAAAAAQBAQEAAAmjAQAA+wIAAE0BAlcAAAAATQIAEwEAAADdAwAAnwEAAYIAAQACAyIDAgBYIwEYAAEAAAAAAAABWAAAAAAEAQEBAAAJowEAAPsCAABNAQINAAAAAE0CABMBAAAA3QMAAJ8BAACCAQAAAgMkAwIAWyUBGAABAAAAAAAAAFsAAAAABAEBAQAACaMBAAD7AgAATQECGQAAAABNAgATAQAAAN0DAACfAQABggABAAIDAQMCAF4mARgAAQAAAAAAAAFeAAAAAAMBAQAAAAf7AgAATQECfwAAAABNAgATAQAAAJ8BAgCCAQAAAgMnAwIAYSgBGAAAAAAAAABiAAAAAAYCAgAAAB5HAQIAAAAAgKkDAAGpAwEAgQEDBAAAAABvBAAApAICAAAAEECfAgMB+wMAAE0CAxkDAAAATQMAEwQAAABSBAEAnwIDAU0CABMEAAAA+wUBAE0EBR8FAAAAvAICAwYAAACfAgMCUgUBALwDAmsHAAAAnwMDAYIAAQAIAykDKgQAABBAAwEDAgMSAysDLABkLQEYAAAAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAEAAAABZQAAAAADAQAAAAAGTQEA2QAAAAC8AQHdAQAAAJ8BAgGCAAEAAgMPAy4AagMBGAAAAAAAAWsAAAAAAwEAAAAABk0BAOQAAAAAvAEB3QEAAACfAQIBggABAAIDEAMuAG0vARgAAAAAAAFuAAAAAAQBAAAAAA1NAQDBAAAAALwBAVABAAAAnwECAYE9AAUCAAAAUgIAAG8DAgCkAQQAAAAwQJ8BAwGCAAEABQMOAzAAAwwEAAAwQABwMAEYAAAAAAABAAAAAAAAAXEAAAAACwAAAQIAe6MAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DAKEGAAAATQIDdgcAAACfAQICpAIFAAAAQEBNBAChBgAAAE0DBB8IAAAAnwICAqQDBQAAAEBATQUAoQYAAABNBAVyCQAAAJ8DAgKkBAUAAABAQE0GAKEGAAAATQUGUgoAAACfBAICpAUFAAAAQECkCA0AAADAQE0HCCQOAAAATQYH9gsAAACfBQICpAYFAAAAQECkCQ0AAADAQE0ICSQOAAAATQcIdw8AAACfBgICpAcFAAAAQECkCg0AAADAQE0JCiQOAAAATQgJBBAAAACfBwIC/wgFAAAAAAAwCAhuEQAAAMAJEgASAAgAEgABABIAAgASAAYAEgAEABIABQAwCQjvEwAAAMAJFAASAAYAMAkIVhUAAADACRYAEgAHADAJCMMXAAAAwAkYABIAAwASAAcAMAkI4RkAAADACRoAEgAGADAJCHsbAAAAwAkcABIABgAwCQh3HQAAAMAJHgASAAYAMAkILR8AAADACSAAEgAGADAJCDkhAAAAwAkiABIABgAwCQifIwAAAMAJJAASAAYAEgAFADAJCK8lAAAAwAkmADAJCLknAAAAwAkoADAJCMopAAAAwAkqADAJCFArAAAAgggCACwDGQQAAABAAzEDGwMyBAAAQEADMwM0AzUDHgM2AzcDOAQAAMBAAxcDOQM6AzsGBAMNBgUDFgYGAxwGBwMfBggDIQYJAyMGCgMlBgsDJgYMAygGDQMtBg4DAwYPAy8GEAMwDQQFBgcICQoLDA0ODxABAAEYAAEAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAACAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAAACAAEAAgAAAAAAAAAAKgAAAAMAAAAPAAAAAAoAAAADAAAAAwAAAAMAAAADAAAAAwAAAAAGAAADAAADAAAFAQAAAAARYPxPibWEHfVSOCUd/2ZtgpLQu5HoQm0l2AhLlN2rNEKKSvPPcvRk5g==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.Maid)
local v_u_3 = require(v1.Std.Signal)
local v_u_4 = require(v1.Std.Promise)
local v_u_5 = require(v1.Std.RxInstanceUtils)
local v_u_6 = require(script.Parent.InventoryItemConsts)
local v_u_7 = require(script.Parent.InventoryItemUtils)
local v_u_8 = require(script.Parent.InventoryItemOwnerBinder)
local v_u_9 = {}
v_u_9.__index = v_u_9
function v_u_9.new(p_u_10)
	-- upvalues: (copy) v_u_9, (copy) v_u_2, (copy) v_u_3, (copy) v_u_7, (copy) v_u_5, (copy) v_u_6
	local v_u_11 = {}
	local v12 = v_u_9
	setmetatable(v_u_11, v12)
	v_u_11.obj = p_u_10
	v_u_11._maid = v_u_2.new()
	v_u_11.onAttemptSelect = v_u_3.new()
	v_u_11._maid:GiveTask(v_u_11.onAttemptSelect)
	v_u_11.onAttemptDrop = v_u_3.new()
	v_u_11._maid:GiveTask(v_u_11.onAttemptDrop)
	v_u_11._maid:GiveTask(function()
		-- upvalues: (ref) v_u_7, (copy) v_u_11
		v_u_7.setEquipped(v_u_11.obj, false)
	end)
	v_u_11._maid:GiveTask(v_u_5.observeOneChildNamed(p_u_10, v_u_6.EQUIP_REMOTE_NAME, function(p13, p14)
		-- upvalues: (copy) v_u_11
		p14:GiveTask(p13.OnClientEvent:Connect(function()
			-- upvalues: (ref) v_u_11
			v_u_11:AttemptSelect()
		end))
	end))
	local function v16()
		-- upvalues: (copy) p_u_10, (ref) v_u_6
		local v15 = p_u_10:GetAttribute(v_u_6.EQUIPPED_ATTR_NAME) or 0
		if (p_u_10:GetAttribute(v_u_6.EQUIPPED_LOCAL_ATTR_NAME) or 0) < v15 then
			p_u_10:SetAttribute(v_u_6.EQUIPPED_LOCAL_ATTR_NAME, v15)
		end
	end
	v_u_11._maid:GiveTask(p_u_10:GetAttributeChangedSignal(v_u_6.EQUIPPED_ATTR_NAME):Connect(v16))
	local v17 = p_u_10:GetAttribute(v_u_6.EQUIPPED_ATTR_NAME) or 0
	if (p_u_10:GetAttribute(v_u_6.EQUIPPED_LOCAL_ATTR_NAME) or 0) < v17 then
		p_u_10:SetAttribute(v_u_6.EQUIPPED_LOCAL_ATTR_NAME, v17)
	end
	v_u_11._overriddenOwner = nil
	return v_u_11
end
function v_u_9.GetName(p18)
	-- upvalues: (copy) v_u_7
	return v_u_7.getName(p18.obj)
end
function v_u_9.GetOwner(p19)
	-- upvalues: (copy) v_u_8
	local v20 = p19.obj.Parent.Parent
	if v20 then
		local v21 = v_u_8:Get(v20)
		if v21 then
			return v21
		end
		if v20.Parent == game:GetService("Players") then
			return v20
		end
	end
end
function v_u_9.PromiseOwner(p22)
	-- upvalues: (copy) v_u_4, (copy) v_u_8
	local v23 = p22.obj.Parent.Parent
	if v23 then
		if v23.Parent == game:GetService("Players") then
			return v_u_4.resolve(v23)
		else
			return v_u_8:Promise(v23)
		end
	else
		return
	end
end
function v_u_9.GetAttr(p24, ...)
	-- upvalues: (copy) v_u_7
	return v_u_7.getAttr(p24.obj, ...)
end
function v_u_9.SetAttr(p25, ...)
	-- upvalues: (copy) v_u_7
	v_u_7.setAttr(p25.obj, ...)
end
function v_u_9.GetEquipped(p26, ...)
	-- upvalues: (copy) v_u_7
	return v_u_7.getEquipped(p26.obj, ...)
end
function v_u_9.SetEquipped(p27, ...)
	-- upvalues: (copy) v_u_7
	v_u_7.setEquipped(p27.obj, ...)
end
function v_u_9.GetEquippedSignal(p28)
	-- upvalues: (copy) v_u_7
	return v_u_7.getEquippedSignal(p28.obj)
end
function v_u_9.AttemptSetEquipped(p29, p30)
	-- upvalues: (copy) v_u_7, (copy) v_u_6
	local v31 = p30 ~= nil
	assert(v31, "missing value")
	v_u_7.setEquipped(p29.obj, p30)
	p29.obj:FindFirstChild(v_u_6.EQUIP_REMOTE_NAME):FireServer(p30)
end
function v_u_9.AttemptSelect(p32)
	p32.onAttemptSelect:Fire()
end
function v_u_9.AttemptDrop(p33)
	p33.onAttemptDrop:Fire()
end
function v_u_9.Destroy(p34)
	p34._maid:Destroy()
	setmetatable(p34, nil)
end
return v_u_9
