-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMrCElzU2VydmVyEkVRVUlQUEVEX0FUVFJfTkFNRQhnZXRPd25lcgtMb2NhbFBsYXllchhFUVVJUFBFRF9MT0NBTF9BVFRSX05BTUUTZ2V0RXF1aXBwZWRBdHRyTmFtZQhUQUdfTkFNRQZIYXNUYWcycHJvdmlkZWQgaW52ZW50b3J5SXRlbVZhbHVlIGlzIG5vdCBhIEludmVudG9yeUl0ZW0GYXNzZXJ0DEdldEF0dHJpYnV0ZQtnZXRFcXVpcHBlZAZ0eXBlb2YHYm9vbGVhbhd2YWx1ZSBtdXN0IGJlIGEgYm9vbGVhbgxTZXRBdHRyaWJ1dGULc2V0RXF1aXBwZWQZR2V0QXR0cmlidXRlQ2hhbmdlZFNpZ25hbBFnZXRFcXVpcHBlZFNpZ25hbBBMT0NLRURfQVRUUl9OQU1FCWdldExvY2tlZAlzZXRMb2NrZWQSUFJJT1JJVFlfQVRUUl9OQU1FC2dldFByaW9yaXR5Bm51bWJlchZ2YWx1ZSBtdXN0IGJlIGEgbnVtYmVyC3NldFByaW9yaXR5BE5hbWUHZ2V0TmFtZQZzdHJpbmcWdmFsdWUgbXVzdCBiZSBhIHN0cmluZwdzZXROYW1lB2dldEF0dHIHc2V0QXR0cgZQYXJlbnQEZ2FtZQdQbGF5ZXJzCkdldFNlcnZpY2URQ29sbGVjdGlvblNlcnZpY2UKUnVuU2VydmljZQdyZXF1aXJlE0ludmVudG9yeUl0ZW1Db25zdHMGc2NyaXB0AA4EAQQAAAAb+wEAALwBAQsAAAAAnwECAg4BBAD7AgEATQECbwEAAACCAQIA+wICAE0BAiMCAAAAUgIAAJ8BAgL7AwMATQIDMQMAAADxAQUAAgAAAPsDAQBNAgNvAQAAAIICAgD7AwEATQIDHgQAAACCAgIABQMBAwIDAwMEAwUACQYBGAAAAAAAAQAAAAIAAAAAAQAAAAABAAAAAgAAAAoAAAAACAEFAAAAMvsCAABSBAAA+wYBAE0FBrQAAAAAvAIC3gEAAACfAgQCgQECBAIAAABvAwIApAEEAAAAMECfAQMB+wUCALwFBQsGAAAAnwUCAg4FBAD7BQEATQQFbwcAAABlABEA+wYDAE0FBiMIAAAAUgYAAJ8FAgL7BwQATQYHMQkAAADxBQUABgAAAPsGAQBNBAZvBwAAAGUAAwD7BgEATQQGHgoAAAC8AgASCwAAAJ8CAwKQAQIFIQMBDA0DAgANAAAAqQIAAakCAQCCAgIADgMHAwgDCQMKBAAAMEACAAAAAAAAAAADAQMCAwMDBAMFAwsCAAAAAAAAAEACAAAAAAAA8D8AEwwBGAsAAAAAAAAAAAAA/wAA9gAAAAABAAAAAgAAAAABAAAAAAEAAAACAAAHAAAAAgAAAAAACgAAAAAMAgUAAABi+wMAAFIFAAD7BwEATQYHtAAAAAC8AwPeAQAAAJ8DBAKBAQMEAgAAAG8EAgCkAgQAAAAwQJ8CAwG7LAEDUgUBAKQEBgAAAFBAnwQCAvAEAgAHAAAAqQMAAakDAQCBAQMECAAAAG8ECACkAgQAAAAwQJ8CAwH7BgIAvAYGCwoAAACfBgICDgYEAPsGAQBNBQZvCwAAAGUAEQD7BwMATQYHIwwAAABSBwAAnwYCAvsIBABNBwgxDQAAAPEGBQAHAAAA+wcBAE0FB28LAAAAZQADAPsHAQBNBQceDgAAALwDABIPAAAAnwMDApACAwkOAQIAjAMBAGUAAQCMAwAAIQYCECYFBgOVBAUQQwUCBPsJAgC8CQkLCgAAAJ8JAgIOCQQA+wkBAE0ICW8LAAAAZQARAPsKAwBNCQojDAAAAFIKAACfCQIC+wsEAE0KCzENAAAA8QkFAAoAAAD7CgEATQgKbwsAAABlAAMA+woBAE0ICh4OAAAAUgkFALwGAC4RAAAAnwYEAYIAAQASAwcDCAMJAwoEAAAwQAMNBAAAUEADDgMPAgAAAAAAAAAAAwEDAgMDAwQDBQMLAgAAAAAAAABAAxAAHBEBGBQAAAAAAAAAAAAA/wAABAAAAAAAAAAAAAAAAAAA6QAAAAABAAAAAgAAAAABAAAAAAEAAAACAAASAAAAAgAAAAIAAALhAAAAAAEAAAACAAAAAAEAAAAAAQAAAAIAABkAAAABCgAAAAAHAQUAAAAs+wIAAFIEAAD7BgEATQUGtAAAAAC8AgLeAQAAAJ8CBAKBAQIEAgAAAG8DAgCkAQQAAAAwQJ8BAwH7BAIAvAQECwUAAACfBAICDgQEAPsEAQBNAwRvBgAAAGUAEQD7BQMATQQFIwcAAABSBQAAnwQCAvsGBABNBQYxCAAAAPEEBQAFAAAA+wUBAE0DBW8GAAAAZQADAPsFAQBNAwUeCQAAALwBABYKAAAAnwEDAIIBAAALAwcDCAMJAwoEAAAwQAMBAwIDAwMEAwUDEgAsEwEYJAAAAAAAAAAAAAD/AADdAAAAAAEAAAACAAAAAAEAAAAAAQAAAAIAACAAAAAKAAAAAAcBAgAAABX7AgAAUgQAAPsGAQBNBQa0AAAAALwCAt4BAAAAnwIEAoEBAgQCAAAAbwMCAKQBBAAAADBAnwEDAfsEAQBNAwRGBQAAALwBABIGAAAAnwEDAIIBAAAHAwcDCAMJAwoEAAAwQAMUAwsAMxUBGAEAAAAAAAAAAAAA/wAABAAAAAAAADQAAAAACAICAAAAJfsDAABSBQAA+wcBAE0GB7QAAAAAvAMD3gEAAACfAwQCgQEDBAIAAABvBAIApAIEAAAAMECfAgMBuywBA1IFAQCkBAYAAABQQJ8EAgLwBAIABwAAAKkDAAGpAwEAgQEDBAgAAABvBAgApAIEAAAAMECfAgMB+wUBAE0EBUYJAAAAUgUBALwCAC4KAAAAnwIEAYIAAQALAwcDCAMJAwoEAAAwQAMNBAAAUEADDgMPAxQDEAA6FgEYAQAAAAAAAAAAAAD/AAAEAAAAAAAAAAAAAAAAAAABAAAAAAAAATsAAAAABwECAAAAFfsCAABSBAAA+wYBAE0FBrQAAAAAvAIC3gEAAACfAgQCgQECBAIAAABvAwIApAEEAAAAMECfAQMB+wQBAE0DBFkFAAAAvAEAEgYAAACfAQMAggEAAAcDBwMIAwkDCgQAADBAAxcDCwBCGAEYAQAAAAAAAAAAAAD/AAAEAAAAAAAAQwAAAAAIAgIAAAAl+wMAAFIFAAD7BwEATQYHtAAAAAC8AwPeAQAAAJ8DBAKBAQMEAgAAAG8EAgCkAgQAAAAwQJ8CAwG7LAEDUgUBAKQEBgAAAFBAnwQCAvAEAgAHAAAAqQMAAakDAQCBAQMECAAAAG8ECACkAgQAAAAwQJ8CAwH7BQEATQQFWQkAAABSBQEAvAIALgoAAACfAgQBggABAAsDBwMIAwkDCgQAADBAAw0EAABQQAMZAxoDFwMQAEkbARgBAAAAAAAAAAAAAP8AAAQAAAAAAAAAAAAAAAAAAAEAAAAAAAABSgAAAAAHAQIAAAAR+wIAAFIEAAD7BgEATQUGtAAAAAC8AgLeAQAAAJ8CBAKBAQIEAgAAAG8DAgCkAQQAAAAwQJ8BAwFNAQC6BQAAAIIBAgAGAwcDCAMJAwoEAAAwQAMcAFEdARgBAAAAAAAAAAAAAP8AAAQAAFIAAAAACAICAAAAIPsDAABSBQAA+wcBAE0GB7QAAAAAvAMD3gEAAACfAwQCgQEDBAIAAABvBAIApAIEAAAAMECfAgMBuywBA1IFAQCkBAYAAABQQJ8EAgLwBAIABwAAAKkDAAGpAwEAgQEDBAgAAABvBAgApAIEAAAAMECfAgMBMAEAugkAAACCAAEACgMHAwgDCQMKBAAAMEADDQQAAFBAAx4DHwMcAFggARgBAAAAAAAAAAAAAP8AAAQAAAAAAAAAAAAAAAAAAAEAAVkAAAAABQIAAAAABVIEAQC8AgASAAAAAJ8CAwCCAgAAAQMLAGAhARgAAAAAAGEAAAAABwMAAAAABlIFAQBSBgIAvAMALgAAAACfAwQBggABAAEDEABjIgEYAAAAAAABZAAAAAAHAQIAAAAf+wIAAFIEAAD7BgEATQUGtAAAAAC8AgLeAQAAAJ8CBAKBAQIEAgAAAG8DAgCkAQQAAAAwQJ8BAwFNAgAkBQAAAE0BAiQFAAAATQIBJAUAAACkAwcAAABgQG8FCAC8AwMWCQAAAJ8DAwLxAgMAAwAAAMYCAACCAgIAggECAAoDBwMIAwkDCgQAADBAAyMDJAQAAGBAAyUDJgBmAwEYAQAAAAAAAAAAAAD/AAAEAAAAAQAAAAAAAAAAAAEAAmcAAAAABwAAAQIAZaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQEAAAAAQG8DBAC8AQEWAwAAAJ8BAwKkAgEAAAAAQG8EBQC8AgIWAwAAAJ8CAwKkAwcAAABgQKQGCgAAAJBATQUGJAsAAABNBAX2CAAAAJ8DAgL/BAUAAAAAAMAFDAASAAIAEgADABIABAASAAEAwAYNABIAAAASAAMAEgACABIABAASAAEAMAYEDQ4AAADABg8AEgAAABIAAwASAAIAEgAEABIAAQAwBgQZEAAAAMAGEQASAAAAEgADABIAAgASAAQAEgABADAGBH8SAAAAwAYTABIAAAASAAMAMAYEEhQAAADABhUAEgAAABIAAwAwBgQuFgAAAMAGFwASAAAAEgADADAGBIAYAAAAwAYZABIAAAASAAMAMAYEtBoAAADABhsAEgAAABIAAwAwBgS2HAAAAMAGHQASAAAAEgADADAGBLoeAAAAwAYfADAGBFsgAAAAwAYhADAGBFciAAAAwAYjABIAAAASAAMAMAYEIyQAAACCBAIAJQMkBAAAAEADJwMmAyUDKAMpBAAAYEADKgMrBAAAkEADIwYABgEDDAYCAxEGAwMTBgQDFQYFAxYGBgMYBgcDGwYIAx0GCQMgBgoDIQYLAyIGDAMDDQABAgMEBQYHCAkKCwwBAAEYAAEAAAAAAAEAAAAAAAEAAAAAAAEAAAAAAAAAAAIAAgAAAAAKAAAAAAAAAAkAAAAAAAAAEAAAAAAAAAAHAAAAAAcAAAAACAAAAAAHAAAAAAgAAAAABwAAAAAIAAADAAADAAAAAAwBAAAAAA3b3zbiAH2bZ+kbXHZfma2Q1Ucj+BPRAWa/zQ0aTExzd0ZAqlTlxJQo

-- Decompiled by Krnl

local v_u_1 = game:GetService("CollectionService")
local v_u_2 = game:GetService("Players")
local v_u_3 = game:GetService("RunService")
local v_u_4 = require(script.Parent.InventoryItemConsts)
local v_u_45 = {
	["getEquipped"] = function(p5)
		-- upvalues: (copy) v_u_1, (copy) v_u_4, (copy) v_u_3, (copy) v_u_45, (copy) v_u_2
		local v6 = v_u_1:HasTag(p5, v_u_4.TAG_NAME)
		assert(v6, "provided inventoryItemValue is not a InventoryItem")
		local v7
		if v_u_3:IsServer() then
			v7 = v_u_4.EQUIPPED_ATTR_NAME
		elseif v_u_45.getOwner(p5) == v_u_2.LocalPlayer then
			v7 = v_u_4.EQUIPPED_LOCAL_ATTR_NAME
		else
			v7 = v_u_4.EQUIPPED_ATTR_NAME
		end
		return (p5:GetAttribute(v7) or 0) % 2 == 1
	end,
	["setEquipped"] = function(p8, p9)
		-- upvalues: (copy) v_u_1, (copy) v_u_4, (copy) v_u_3, (copy) v_u_45, (copy) v_u_2
		local v10 = v_u_1:HasTag(p8, v_u_4.TAG_NAME)
		assert(v10, "provided inventoryItemValue is not a InventoryItem")
		local v11 = typeof(p9) == "boolean"
		assert(v11, "value must be a boolean")
		local v12
		if v_u_3:IsServer() then
			v12 = v_u_4.EQUIPPED_ATTR_NAME
		elseif v_u_45.getOwner(p8) == v_u_2.LocalPlayer then
			v12 = v_u_4.EQUIPPED_LOCAL_ATTR_NAME
		else
			v12 = v_u_4.EQUIPPED_ATTR_NAME
		end
		local v13 = p8:GetAttribute(v12) or 0
		local v14 = v13 + (v13 % 2 - (p9 and 1 or 0) + 2)
		local v15
		if v_u_3:IsServer() then
			v15 = v_u_4.EQUIPPED_ATTR_NAME
		elseif v_u_45.getOwner(p8) == v_u_2.LocalPlayer then
			v15 = v_u_4.EQUIPPED_LOCAL_ATTR_NAME
		else
			v15 = v_u_4.EQUIPPED_ATTR_NAME
		end
		p8:SetAttribute(v15, v14)
	end,
	["getEquippedSignal"] = function(p16)
		-- upvalues: (copy) v_u_1, (copy) v_u_4, (copy) v_u_3, (copy) v_u_45, (copy) v_u_2
		local v17 = v_u_1:HasTag(p16, v_u_4.TAG_NAME)
		assert(v17, "provided inventoryItemValue is not a InventoryItem")
		local v18
		if v_u_3:IsServer() then
			v18 = v_u_4.EQUIPPED_ATTR_NAME
		elseif v_u_45.getOwner(p16) == v_u_2.LocalPlayer then
			v18 = v_u_4.EQUIPPED_LOCAL_ATTR_NAME
		else
			v18 = v_u_4.EQUIPPED_ATTR_NAME
		end
		return p16:GetAttributeChangedSignal(v18)
	end,
	["getLocked"] = function(p19)
		-- upvalues: (copy) v_u_1, (copy) v_u_4
		local v20 = v_u_1:HasTag(p19, v_u_4.TAG_NAME)
		assert(v20, "provided inventoryItemValue is not a InventoryItem")
		return p19:GetAttribute(v_u_4.LOCKED_ATTR_NAME)
	end,
	["setLocked"] = function(p21, p22)
		-- upvalues: (copy) v_u_1, (copy) v_u_4
		local v23 = v_u_1:HasTag(p21, v_u_4.TAG_NAME)
		assert(v23, "provided inventoryItemValue is not a InventoryItem")
		local v24 = typeof(p22) == "boolean"
		assert(v24, "value must be a boolean")
		p21:SetAttribute(v_u_4.LOCKED_ATTR_NAME, p22)
	end,
	["getPriority"] = function(p25)
		-- upvalues: (copy) v_u_1, (copy) v_u_4
		local v26 = v_u_1:HasTag(p25, v_u_4.TAG_NAME)
		assert(v26, "provided inventoryItemValue is not a InventoryItem")
		return p25:GetAttribute(v_u_4.PRIORITY_ATTR_NAME)
	end,
	["setPriority"] = function(p27, p28)
		-- upvalues: (copy) v_u_1, (copy) v_u_4
		local v29 = v_u_1:HasTag(p27, v_u_4.TAG_NAME)
		assert(v29, "provided inventoryItemValue is not a InventoryItem")
		local v30 = typeof(p28) == "number"
		assert(v30, "value must be a number")
		p27:SetAttribute(v_u_4.PRIORITY_ATTR_NAME, p28)
	end,
	["getName"] = function(p31)
		-- upvalues: (copy) v_u_1, (copy) v_u_4
		local v32 = v_u_1:HasTag(p31, v_u_4.TAG_NAME)
		assert(v32, "provided inventoryItemValue is not a InventoryItem")
		return p31.Name
	end,
	["setName"] = function(p33, p34)
		-- upvalues: (copy) v_u_1, (copy) v_u_4
		local v35 = v_u_1:HasTag(p33, v_u_4.TAG_NAME)
		assert(v35, "provided inventoryItemValue is not a InventoryItem")
		local v36 = typeof(p34) == "string"
		assert(v36, "value must be a string")
		p33.Name = p34
	end,
	["getAttr"] = function(p37, p38)
		return p37:GetAttribute(p38)
	end,
	["setAttr"] = function(p39, p40, p41)
		p39:SetAttribute(p40, p41)
	end,
	["getOwner"] = function(p42)
		-- upvalues: (copy) v_u_1, (copy) v_u_4
		local v43 = v_u_1:HasTag(p42, v_u_4.TAG_NAME)
		assert(v43, "provided inventoryItemValue is not a InventoryItem")
		local v44 = p42.Parent.Parent
		if v44.Parent == game:GetService("Players") then
			return v44
		else
			return nil
		end
	end
}
return v_u_45
