-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMwClN0YXJ0ZXJHdWkPUG9saWNlUmVwb3J0R3VpDkZpbmRGaXJzdENoaWxkCVBsYXllckd1aQZQYXJlbnQDR3VpBEluaXQESGlkZQRNYWlkBklzT3BlbgNuZXcJQ29udGFpbmVyA1RvcARMaXN0BmlwYWlycwVUaXRsZQZhc3NlcnQGQW1vdW50BHR5cGUGbnVtYmVyCFN1YlRpdGxlBlByZXNldAVDbG9uZQtMYXlvdXRPcmRlcgRUZXh0C0Zvcm1hdE1vbmV5B1Zpc2libGUIR2l2ZVRhc2sGQm90dG9tA1N1bQMrJXMGZm9ybWF0BUNsb3NlEE1vdXNlQnV0dG9uMURvd24HQ29ubmVjdAdFbmFibGVkBWRlbGF5B0Rpc3BsYXkHRGVzdHJveQRnYW1lB1BsYXllcnMKR2V0U2VydmljZQtMb2NhbFBsYXllchFSZXBsaWNhdGVkU3RvcmFnZQdyZXF1aXJlA1N0ZARNYXRoBk1vZHVsZQAHAwADAAAAEPsBAABNAAELAAAAAG8CAQC8AAADAgAAAJ8AAwL7AgEATQECmQMAAAAwAQAkBAAAAPsBAgAwAAEfBQAAAIIAAQAGAwEDAgMDAwQDBQMGAAkHARgAAAAAAAAAAQAAAAACAAABCgAAAAACAAEAAAAF+wEAAE0AAc8AAAAAnwABAYIAAQABAwgANAABGAAAAAABNQAAAAADAAIAAAAL+wAAAPsCAQBNAQJ2AAAAAJoABQABAAAA+wEBAE0AAc8BAAAAnwABAYIAAQACAwkDCAA6AAEYAAAAAAAAAQAAAAI7AAAAABEBAwAABwAAAQMGdgKUAfsCAABNAQIxAAAAAJ8BAQIOAQQA+wIAAE0BAs8BAAAAnwEBAfsCAABNAQIfAgAAAPsDAQBNAgPvAwAAAJ8CAQL7AwAAMAIDdgQAAACMAwAATQYBbwUAAABNBQaYBgAAAE0EBesHAAAApAUJAAAAgEBSBgAAnwUCBFEFRwBNCwm6CgAAALsBCwKkCgwAAACwQJ8KAgJNDAkrDQAAALsBDAKkCwwAAACwQJ8LAgK7KAsDUg8LAKQODwAAAOBAnw4CAvAOAgAQAAAAqQ0AAakNAQC7AQ0CpAwMAAAAsECfDAIBTQwJqREAAABNDQS1EgAAALwNDToTAAAAnw0CAjAIDQAUAAAAMAQNJBUAAABNDg26CgAAADAKDvUWAAAATQ4NKw0AAAD7EAIATQ8QDBcAAABSEAsAnw8CAjAPDvUWAAAARwwFAAAAAABNDg2pEQAAADAMDvUWAAAATQ4NqREAAABHDAIAAAAAgKkPAAGpDwEAMA8OgBgAAACpDgEAMA4NgBgAAABSEA0AvA4C/RkAAACfDgMBQwMDC24FuP8CAACATQgBbwUAAABNBwgTGgAAAE0GB28FAAAATQUGGhsAAABvBhwA+wkCAE0ICQwXAAAAUgkDAJ8IAgC8BgaNHQAAAJ8GAAIwBgX1FgAAAE0JAW8FAAAATQgJYx4AAABNBwhhHwAAAMAJIAASAgAAvAcHxyEAAACfBwMAvAUC/RkAAACfBQABqQUBADAFAfAiAAAApAUkAAAAMEKMBgUA2QcBABIAAgASAgAAnwUDAYIAAQAlAwoDCAMGAwsDCQMMAw0DDgMPBAAAgEADEAMRBAAAsEADEgMTBAAA4EADFAMVAxYDFwMYAwUDGQMaAxsDHAMdAx4DHwMgAyEDIgYBAyMDJAMlBAAAMEICAQIQJgEYAAAAAAABAAAAAgAAAQAAAAEAAAICAAAAAAABAAAAAAEAAAAAAAEAAAAAAAEAAAAAAAAAAAAAAAABAAIAAAAAAQABAAIAAAABAAAAAAAAAAABAAEAAAACAAAAAAAAAAEAAAIAAAAC7AAXAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAEAAACAAAAAAAABREAAAAAAwABAAAAFvsBAABNAAEfAAAAAPsCAABNAQIxAQAAAJ8BAQIOAQ0A+wIAAE0BAnYCAAAAvAEBUAMAAACfAQIB+wEAAMYCAAAwAgF2AgAAAKkBAAAwAQDwBAAAAIIAAQAFAwYDCgMJAycDJABACAEYAAAAAQAAAAABAAAAAAABAAAAAgAAAkEAAAAAAwABAAAACPsCAABNAQJ2AAAAAEcBAgAAAACAqQAAAakAAQCCAAIAAQMJAEkKARgAAAAAAAAAAEoAAAAABwAAAQIANKMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwJNAQAxBAAAAKQCAQAAAABAbwQFALwCAhYDAAAAnwIDAqQDBwAAAGBATQUCoQgAAABNBAV2CQAAAJ8DAgKkBAcAAABgQE0GAkALAAAATQUGjAoAAACfBAIC/wUEAAAAAADABgwAEgACABIAAQASAAUAMAYFcw0AAADABg4AEgAFABIAAwASAAQAMAYFPA8AAADABhAAEgAFADAGBc8RAAAAwAYSABIABQAwBgUxEwAAAIIFAgAUAygEAAAAQAMpAyoDKwMsAy0EAABgQAMuAwkDLwMwBgADBwYDAyYGBAMIBgUDCgQAAwQFAQABGAABAAAAAAABAAEAAAAAAAEAAAAAAAABAAAAAAAAAgABAAAAAAAHAAAAAAAwAAAACQAAAAMBAAAAAAbEw0wUYZKSlvYHJoBpfhjrLv5sZ/Usqmp498/+w3qR7pvge26y5ED2

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players").LocalPlayer
local v_u_2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v_u_2.Std.Maid)
local v_u_4 = require(v_u_2.Module.Math)
local v_u_21 = {
	["Init"] = function()
		-- upvalues: (copy) v_u_2, (copy) v_u_1, (copy) v_u_21
		local v5 = v_u_2.StarterGui:FindFirstChild("PoliceReportGui")
		v5.Parent = v_u_1.PlayerGui
		v_u_21.Gui = v5
	end,
	["Display"] = function(p6)
		-- upvalues: (copy) v_u_21, (copy) v_u_3, (copy) v_u_4
		if v_u_21.IsOpen() then
			v_u_21.Hide()
		end
		local v7 = v_u_21.Gui
		local v_u_8 = v_u_3.new()
		v_u_21.Maid = v_u_8
		local v9 = v7.Container.Top.List
		local v10 = 0
		for v11, v12 in ipairs(p6) do
			local v13 = v12.Title
			local v14 = assert(v13)
			local v15 = v12.Amount
			local v16 = assert(v15)
			local v17 = type(v16) == "number"
			assert(v17)
			local v18 = v12.SubTitle
			local v19 = v9.Preset:Clone()
			v19.LayoutOrder = v11
			v19.Parent = v9
			v19.Title.Text = v14
			v19.Amount.Text = v_u_4.FormatMoney(v16)
			if v18 ~= nil then
				v19.SubTitle.Text = v18
			end
			v19.SubTitle.Visible = v18 ~= nil
			v19.Visible = true
			v_u_8:GiveTask(v19)
			v10 = v10 + v16
		end
		v7.Container.Bottom.Container.Sum.Text = ("+%s"):format(v_u_4.FormatMoney(v10))
		v_u_8:GiveTask(v7.Container.Close.MouseButton1Down:Connect(function()
			-- upvalues: (ref) v_u_21
			v_u_21.Hide()
		end))
		v7.Enabled = true
		delay(5, function()
			-- upvalues: (copy) v_u_8, (ref) v_u_21
			if v_u_8 == v_u_21.Maid then
				v_u_21.Hide()
			end
		end)
	end,
	["Hide"] = function()
		-- upvalues: (copy) v_u_21
		local v20 = v_u_21.Gui
		if v_u_21.IsOpen() then
			v_u_21.Maid:Destroy()
			v_u_21.Maid = nil
			v20.Enabled = false
		end
	end,
	["IsOpen"] = function()
		-- upvalues: (copy) v_u_21
		return v_u_21.Maid ~= nil
	end
}
return v_u_21
