-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNUClRleHRCdXR0b24PQm9yZGVyU2l6ZVBpeGVsBkNvbG9yMwNuZXcMQm9yZGVyQ29sb3IzFkJhY2tncm91bmRUcmFuc3BhcmVuY3kFY29sb3IQQmFja2dyb3VuZENvbG9yMwRzaXplBFNpemUIcG9zaXRpb24IUG9zaXRpb24ABFRleHQKU2VsZWN0YWJsZQVFdmVudAlBY3RpdmF0ZWQJb25DbGlja2VkBVRpdGxlCVRleHRMYWJlbAtBbmNob3JQb2ludARGb250CkxpbmVIZWlnaHQKVGV4dFNjYWxlZA5UZXh0WEFsaWdubWVudA5UZXh0WUFsaWdubWVudApUZXh0Q29sb3IzBlpJbmRleAVVRGltMgdWZWN0b3IyBXRpdGxlBEVudW0LTHVja2llc3RHdXkGQ2VudGVyB2Zyb21SR0IGYnV0dG9uBGNvZGUIc2V0U3RhdGUEaW5pdAVwcm9wcwVzdGF0ZQh0b3N0cmluZwhvblN1Ym1pdAV0YWJsZQZpbnNlcnQFQ2xlYXIFRW50ZXIFRnJhbWULYW5jaG9yUG9pbnQLQXNwZWN0UmF0aW8FQ2xvc2UEQ29kZQdCdXR0b25zF1VJQXNwZWN0UmF0aW9Db25zdHJhaW50C0ltYWdlQnV0dG9uF3JieGFzc2V0aWQ6Ly80OTMzMTQzNzgxBUltYWdlEE1vdXNlQnV0dG9uMURvd24Mb25DbGlja0Nsb3NlCFVJU3Ryb2tlBUNvbG9yCVRoaWNrbmVzcwdFbmFibGVkBmFjdGl2ZQRHcmlkDWNyZWF0ZUVsZW1lbnQLYXNwZWN0UmF0aW8McGFkZGluZ1JhdGlvC3Jvd3NQZXJQYWdlCmNvbHNQZXJSb3cJY29tcG9uZW50BWl0ZW1zBnJlbmRlcghkaWRNb3VudARnYW1lEVJlcGxpY2F0ZWRTdG9yYWdlCkdldFNlcnZpY2UHcmVxdWlyZQRFelVpBVJvYWN0DVB1cmVDb21wb25lbnQGS2V5cGFkBmV4dGVuZAxkZWZhdWx0UHJvcHMACQ0BAgAAAHz7AQAAbwIAAP8DBQAAAAAAjAQBADAEA44BAAAApAQEAAAMIIBvBQUAbwYFAG8HBQCfBAQCMAQDNAYAAACMBAAAMAQDOgcAAABNBABECAAAACsEBgCkBAQAAAwggG8FCQBvBgkAbwcJAJ8EBAIwBAOfCgAAAE0EAA8LAAAAMAQDLwwAAABNBADbDQAAADAEAzsOAAAAbwQPADAEA/UQAAAAqQQBADAEAyQRAAAA+wYBAE0FBjYSAAAATQQFHhMAAABNBQAiFAAAAGoFAwTiBBYA+wUAAG8GFwDiByAAjAgBADAIBzoHAAAAjAgAADAIB44BAAAApAgiAAAMEIJvCSMAjAoAAIwLAQCMDAAAnwgFAjAIBy8MAAAApAgiAAAMEIJvCSQAjAoAAG8LJACMDAAAnwgFAjAIBzsOAAAApAgmAAAMUIJvCSQAbwokAJ8IAwIwCAfoGAAAAE0IAJonAAAAMAgH9RAAAACkCCoAKWSAwjAIBzkZAAAAbwgrADAIB4IaAAAAqQgBADAIB94bAAAApAgtACxwgMIwCAd7HAAAAKQILgAsdIDCMAgHHR0AAACkCDAAALwggIwJ/wCMCv8AjAv/AJ8IBAIwCAdzHgAAAIwICgAwCAcNHwAAAJ8FAwIwBQS6FQAAAJ8BBACCAQAAMQMBAwIDAwMEBAAMIIACMzMzMzMz0z8DBQMGAwcCmpmZmZmZuT8DCAMJAwoDCwMMAw0DDgMPAxADEQMSAxMFARUDFAMVAxYDFwMYAxkDGgMbAxwFDQcBDA4YEBkaGxwdHh8DHQQADBCCAs3MzMzMzOw/AgAAAAAAAOA/Ax4EAAxQggMfAyADIQQpZIDCAmZmZmZmZuY/AyIELHCAwgQsdIDCAyMEALwggAAHJAEYAAAAAAEAAAEAAAAAAAAAAQAAAQAAAAAAAAAAAAABAAAAAQAAAAEAAAEAAAEAAAAAAAAAAQEAAAEAAAEAAAEAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAABAAAAAQAAAAEAAAEAAAEAAAABAAAAAQAAAAAAAAABAADzAAD1AAgAAAAABQEAAAAACOIDAQBvBAIAMAQDIwAAAAC8AQAqAwAAAJ8BAwGCAAEABAMlBQEAAw0DJgArJwEYAAEAAP8AAAMsAAAAAAgAAgAAACD7AgAATQECBwAAAABNAAEiAQAAAA4ABwD7AgAATQECBwAAAABNAAEiAQAAAPsBAQCfAAIB+wAAAOICAwD7BwAATQYHGAQAAABNBAYjAgAAAPsGAQC7PwYCpAUGAAAAUECfBQICcwMEBTADAiMCAAAAvAAAKgcAAACfAAMBggABAAgDKAMSAyUFAQIDKQMqBAAAUEADJgA1EgEYAAAAAAAAAQAAAAAAAAIAAQAAAAAAAAAAAAAAAP8AAAM2AAAAAAQAAQAAABb7AgAATQECBwAAAABNAAEiAQAAAA4ABwD7AgAATQECBwAAAABNAAEiAQAAAIwB/v+fAAIB+wAAAOICAwBvAwQAMAMCIwIAAAC8AAAqBQAAAJ8AAwGCAAEABgMoAxIDJQUBAgMNAyYAQhIBGAAAAAAAAAEAAAAAAAACAAEAAP8AAANDAAAAAAgAAQAAACD7AgAATQECBwAAAABNAAEiAQAAAA4ABwD7AgAATQECBwAAAABNAAEiAQAAAIwBAACfAAIB+wAAAOICAwD7BwAATQYHGAQAAABNBAYjAgAAAIwGAAC7PwYCpAUGAAAAUECfBQICcwMEBTADAiMCAAAAvAAAKgcAAACfAAMBggABAAgDKAMSAyUFAQIDKQMqBAAAUEADJgBNEgEYAAAAAAAAAQAAAAAAAAIAAQAAAAAAAAAAAAAAAP8AAANOAAAAAAUAAQAAACj7AgAATQECGAAAAABNAAEjAQAAAPsDAABNAgMHAgAAAE0BAiIDAAAADgEHAPsDAABNAgMHAgAAAE0BAiIDAAAAjAL//58BAgH7AwAATQIDBwIAAABNAQIGBAAAAA4BBwD7AwAATQIDBwIAAABNAQIGBAAAAFICAACfAQIB+wEAAOIDBQBvBAYAMAQDIwEAAAC8AQEqBwAAAJ8BAwGCAAEACAMpAyUDKAMSAysFAQEDDQMmAFkSARgAAAAAAAEAAAAAAAEAAAAAAAACAAAAAAABAAAAAAAAAgABAAD/AAADWgAAAAAVAQQAAADlA/8BAAAAAAAAjAQBAIwCCQCMAwEAqAIUAOIHAgC7PwQDUgkEAKQIBAAAADBAnwgCAjAIB5oAAAAA2QgAABIAAAASAAQAMAgHIgEAAACeNAEEBwAAAFIGAQCkBQcAABhQgJ8FAwGLAuz/4gQJAG8FCgAwBQSaAAAAAKQFDQAAMLCAjAbrAIwHPACMCAAAnwUEAjAFBEQIAAAA2QUBABIAAAAwBQQiAQAAAJ40AQQEAAAAUgMBAKQCBwAAGFCAnwIDAeIEAgCMBgAAuz8GAqQFBAAAADBAnwUCAjAFBJoAAAAA2QUCABIAAAAwBQQiAQAAAJ40AQQEAAAAUgMBAKQCBwAAGFCAnwIDAeIECQBvBQ4AMAUEmgAAAACkBQ0AADCwgIwGGQCMB8gAjAg1AJ8FBAIwBQRECAAAANkFAwASAAAAMAUEIgEAAACeNAEEBAAAAFIDAQCkAgcAABhQgJ8CAwH7AgAAbwMPAOIEFgCMBQAAMAUEOhAAAACkBRgAAFywgG8GGQBvBxkAbwgZAJ8FBAIwBQSfEQAAAIwFAAAwBQSOEgAAAE0GAAcaAAAATQUGDxsAAAAwBQQvEwAAAE0GAAcaAAAATQUG2xwAAAAwBQQ7FAAAAE0GAAcaAAAATQUGCB0AAAAwBQToFQAAAOIFIwD7BgAAbwckAOIIJQBvCSYAMAkIaR4AAACfBgMCMAYFaR4AAAD7BgAAbwcnAP8IBAAAAAAAjAkBADAJCDoQAAAAbwkoADAJCKkpAAAApAkrAABcoIJvCiwAbwssAJ8JAwIwCQjoFQAAAIwJAwAwCQgNLQAAAKQJLwAAXOCCjAoAAIwLAACMDAAAnwkEAjAJCDsUAAAApAkvAABc4IJvCjAAjAsAAG8MMACMDQAAnwkFAjAJCC8TAAAAqQkBADAJCCQxAAAA+wsBAE0KCzYyAAAATQkKYTMAAABNCwAHGgAAAE0KC/80AAAAagoICeIJJQD7CgAAbwskAOIMJQCMDQEAMA0MaR4AAACfCgMCMAoJaR4AAACfBgQCMAYFYx8AAAD7BgAAbwcPAOIINQCMCQEAMAkIOhAAAACkCS8AAFzggowKAQCMCwAAbww2AIwNAACfCQUCMAkILxMAAACkCS8AAFzggowKAACMCwAAbww3AIwNAACfCQUCMAkIOxQAAADiCTgA+woAAG8LOQDiDEEAjA0BADANDDoQAAAAjA0AADANDI4SAAAApA0vAABc4IJvDkIAjA8AAG8QQwCMEQAAnw0FAjANDC8TAAAApA0vAABc4IJvDiwAjA8AAG8QLACMEQAAnw0FAjANDDsUAAAApA0rAABcoIJvDiwAbw8sAJ8NAwIwDQzoFQAAAE0OABhEAAAATQ0OI0UAAAAwDQz1OgAAAKQNSABH7GDEMA0MOTsAAABvDUMAMA0MgjwAAACpDQEAMA0M3j0AAACkDUoASfhgxDANDHs+AAAApA1LAEn8YMQwDQwdPwAAAKQNDQAAMLCAjA7/AIwP/wCMEP8Anw0EAjANDHNAAAAAjA0KADANDA0tAAAAnwoDAjAKCbohAAAAnwYEAjAGBQMgAAAA+wYAAG8HDwDiCDUAjAkBADAJCDoQAAAApAkvAABc4IKMCgEAjAsAAIwMAQCMDQAAnwkFAjAJCC8TAAAApAkvAABc4IKMCgAAjAsAAIwMAACMDQAAnwkFAjAJCDsUAAAA4glMAPsKAABvCyQA4gwlAIwNCgAwDQxpHgAAAJ8KAwIwCglpHgAAAPsKAABvCzkA4gxBAIwNAQAwDQw6EAAAAIwNAAAwDQyOEgAAAKQNLwAAXOCCbw5CAIwPAABvEEMAjBEAAJ8NBQIwDQwvEwAAAKQNLwAAXOCCbw4sAIwPAABvECwAjBEAAJ8NBQIwDQw7FAAAAKQNKwAAXKCCbw4sAG8PLACfDQMCMA0M6BUAAABNDwAHGgAAAE0OD5oAAAAAkA0OTTANDPU6AAAApA1IAEfsYMQwDQw5OwAAAG8NQwAwDQyCPAAAAKkNAQAwDQzePQAAAKQNSgBJ+GDEMA0Mez4AAACkDUsASfxgxDANDB0/AAAApA0NAAAwsICMDv8AjA//AIwQ/wCfDQQCMA0Mc0AAAACMDQoAMA0MDS0AAADiDU8A+w4AAG8PTgDiEFMApBEYAABcsIBvElQAbxNUAG8UVACfEQQCMBEQpFAAAACMEQIAMBEQGFEAAABNEgAHGgAAAE0REuNVAAAAMBEQ8FIAAACfDgMCMA4NbU4AAACfCgQCMAoJuiEAAACfBgQCMAYFuiEAAAD7BgAAbwcPAOIINQCMCQEAMAkIOhAAAACkCS8AAFzggowKAQCMCwAAbwwmAIwNAACfCQUCMAkILxMAAACkCS8AAFzggowKAACMCwAAbww2AIwNAACfCQUCMAkIOxQAAADiCVcA+wsBAE0KC8pYAAAA+wsCAOIMXwCMDQEAMA0MiVkAAACMDWQAMA0MKFoAAACMDQQAMA0MD1sAAACMDQMAMA0M01wAAAD7DQMAMA0M6F0AAAAwAQwYXgAAAJ8KAwIwCgkHVgAAAJ8GBAIwBgXTIgAAAJ8CBACCAgAAYAMfAxIFAgABAyoEAAAwQAMsAy0EABhQgAMHBQMACAEDLgMDAyMEADCwgAMvAzADBgMIAwIDCgMMAxUFBhAREhMUFQMEBABcsIACmpmZmZmZyT8DKAMJAwsDMQMyAzMDNAMTAzUFBR4fICEiAzYFAR4Cqqqqqqqq6j8DNwM4AzkDHgQAXKCCAgAAAAAAAOA/AxwDHQQAXOCCApqZmZmZmak/Aw8DEAM6AzsFAxATFAJVVVVVVVW1PwJVVVVVVVXtPwUBIQMUAw4DFgMXAxgDGQMaAxsFDRASExQVOjs8PT4/QC0CzczMzMzM7D8CZmZmZmZm5j8DKQMlAyADIQRH7GDEAyIESfhgxARJ/GDEBQIeIQMNAzwFAU4DPQM+Az8FA1BRUgKamZmZmZm5PwNAA0EFAVYDQgNDA0QDRQNGA0cDSAUGWVpbXF1eBAIDBAUwSQEYAAABAAAAAQEAAAAAAAABAAAAAAAAAP4AAP8NAQAAAQAAAAAAAAABAAAAAAAA/QAADAEAAAAAAAABAAAAAAAA/gAACwEAAAEAAAAAAAAAAQAAAAAAAP0AABEAAAEAAAEAAAAAAAAAAQAAAgAAAAAAAQAAAAAAAQAAAAAAAQEAAAEAAP8AAAMAAAABAAABAAABAAAAAAAAAQAAAQAAAAAAAAABAAAAAAAAAAABAAABAAAAAAAAAAAAAQEAAAEAAP8AAPYAAA4AAAEAAAEAAAAAAAAAAAEAAAAAAAAAAAEBAAABAAABAAABAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAQAAAAAAAQAAAAEAAAEAAAEAAAABAAAAAQAAAAAAAAABAADzAAD7AAAVAAABAAABAAAAAAAAAAABAAAAAAAAAAABAQAAAQAA/wAAAwAAAQAAAQAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAQAAAQAAAQAAAAEAAAABAAAAAAAAAAEAAAEBAAABAAAAAAAAAAEAAAEAAAAAAP0AAPEAAPgAAB4AAAEAAAEAAAAAAAAAAAEAAAAAAAAAAAEBAAAAAAEAAAEAAAEAAAEAAAEAAAEA+gAA+wAAswAxAAAAAAUBAAAAAAjiAwEAbwQCADAEAyMAAAAAvAEAKgMAAACfAQMBggABAAQDJQUBAAMNAyYAxAFKARgAAQAA/wAAA8UAAAAADAAAAQIAQqMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DAC0GAAAATQIDBwcAAACfAQICpAIFAAAAQEBNAwAhCAAAAJ8CAgJNAwLKCQAAAMAECgASAAMAEgACAE0FAvgLAAAAbwcMALwFBZwNAAAAnwUDAuIGEQCkBxQAAEwggW8IFQBvCRUAnwcDAjAHBggOAAAApAcXAABMYIFvCBUAjAkAAG8KFQCMCwAAnwcFAjAHBtsPAAAAbwcMADAHBpoQAAAAMAYFkhgAAADABhkAMAYFExoAAADABhsAEgADABIAAgASAAEAEgAEADAGBYAcAAAAwAYdADAGBWoeAAAAggUCAB8DSwQAAABAA0wDTQNOBAAAQEADTwNBA1ADQgYAA1EDUgNTAzEDCwMfBQMODxADHgMEBABMIIECAAAAAAAA4D8DHQQATGCBA1QGAQMnBgYDSQYHA0oEAAEGBwEAARgAAQAAAAAAAQAAAAAAAAEAAAAAAQACAAAeAAAAAAABAQAAAAAAAAEAAAAAAAAAAAEAAP0ABQAABQAAAAAAAJQAAAUBAAAAAAj+3NOGRgmJpMwYuRL12iq8ZL93I/4nvK2Q5d1XbFY3LSYqFpB3z+Iw

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.EzUi.Grid)
local v_u_3 = require(v1.Roact)
local v_u_4 = v_u_3.createElement
local function v_u_6(p5)
	-- upvalues: (copy) v_u_4, (copy) v_u_3
	return v_u_4("TextButton", {
		["BorderSizePixel"] = 1,
		["BorderColor3"] = Color3.new(0.3, 0.3, 0.3),
		["BackgroundTransparency"] = 0,
		["BackgroundColor3"] = p5.color or Color3.new(0.1, 0.1, 0.1),
		["Size"] = p5.size,
		["Position"] = p5.position,
		["Text"] = "",
		["Selectable"] = true,
		[v_u_3.Event.Activated] = p5.onClicked
	}, {
		["Title"] = v_u_4("TextLabel", {
			["BackgroundTransparency"] = 1,
			["BorderSizePixel"] = 0,
			["Size"] = UDim2.new(0.9, 0, 1, 0),
			["Position"] = UDim2.new(0.5, 0, 0.5, 0),
			["AnchorPoint"] = Vector2.new(0.5, 0.5),
			["Text"] = p5.title,
			["Font"] = Enum.Font.LuckiestGuy,
			["LineHeight"] = 0.7,
			["TextScaled"] = true,
			["TextXAlignment"] = Enum.TextXAlignment.Center,
			["TextYAlignment"] = Enum.TextYAlignment.Center,
			["TextColor3"] = Color3.fromRGB(255, 255, 255),
			["ZIndex"] = 10
		})
	})
end
local v7 = v_u_3.PureComponent:extend("Keypad")
v7.defaultProps = {
	["anchorPoint"] = Vector2.new(0.5, 0.5),
	["position"] = UDim2.new(0.5, 0, 0.5, 0),
	["title"] = "Keypad"
}
function v7.init(p8)
	p8:setState({
		["code"] = ""
	})
end
function v7.render(p_u_9)
	-- upvalues: (copy) v_u_4, (copy) v_u_3, (copy) v_u_2, (copy) v_u_6
	local v10 = {}
	for v_u_11 = 1, 9 do
		local v15 = {
			["title"] = tostring(v_u_11),
			["onClicked"] = function()
				-- upvalues: (copy) p_u_9, (copy) v_u_11
				if p_u_9.props.onClicked then
					p_u_9.props.onClicked(v_u_11)
				end
				local v12 = p_u_9
				local v13 = {}
				local v14 = v_u_11
				v13.code = p_u_9.state.code .. tostring(v14)
				v12:setState(v13)
			end
		}
		table.insert(v10, v15)
	end
	local v16 = {
		["title"] = "Clear",
		["color"] = Color3.fromRGB(235, 60, 0),
		["onClicked"] = function()
			-- upvalues: (copy) p_u_9
			if p_u_9.props.onClicked then
				p_u_9.props.onClicked(-2)
			end
			p_u_9:setState({
				["code"] = ""
			})
		end
	}
	table.insert(v10, v16)
	local v17 = {
		["title"] = tostring(0),
		["onClicked"] = function()
			-- upvalues: (copy) p_u_9
			if p_u_9.props.onClicked then
				p_u_9.props.onClicked(0)
			end
			p_u_9:setState({
				["code"] = p_u_9.state.code .. tostring(0)
			})
		end
	}
	table.insert(v10, v17)
	local v19 = {
		["title"] = "Enter",
		["color"] = Color3.fromRGB(25, 200, 53),
		["onClicked"] = function()
			-- upvalues: (copy) p_u_9
			local v18 = p_u_9.state.code
			if p_u_9.props.onClicked then
				p_u_9.props.onClicked(-1)
			end
			if p_u_9.props.onSubmit then
				p_u_9.props.onSubmit(v18)
			end
			p_u_9:setState({
				["code"] = ""
			})
		end
	}
	table.insert(v10, v19)
	local v20 = v_u_4
	local v21 = {
		["BackgroundTransparency"] = 0,
		["BackgroundColor3"] = Color3.new(0.2, 0.2, 0.2),
		["BorderSizePixel"] = 0,
		["Size"] = p_u_9.props.size,
		["Position"] = p_u_9.props.position,
		["AnchorPoint"] = p_u_9.props.anchorPoint
	}
	local v22 = {
		["AspectRatio"] = v_u_4("UIAspectRatioConstraint", {
			["AspectRatio"] = 0.8333333333333333
		})
	}
	local v23 = v_u_4
	local v24 = {
		["BackgroundTransparency"] = 1,
		["Image"] = "rbxassetid://4933143781",
		["AnchorPoint"] = Vector2.new(0.5, 0.5),
		["ZIndex"] = 3,
		["Position"] = UDim2.new(0, 0, 0),
		["Size"] = UDim2.new(0.05, 0, 0.05, 0),
		["Selectable"] = true,
		[v_u_3.Event.MouseButton1Down] = p_u_9.props.onClickClose
	}
	local v25 = {
		["AspectRatio"] = v_u_4("UIAspectRatioConstraint", {
			["AspectRatio"] = 1
		})
	}
	v22.Close = v23("ImageButton", v24, v25)
	local v26 = v_u_4
	local v27 = {
		["BackgroundTransparency"] = 1,
		["Size"] = UDim2.new(1, 0, 0.08333333333333333, 0),
		["Position"] = UDim2.new(0, 0, 0.9166666666666666, 0)
	}
	local v28 = {
		["Title"] = v_u_4("TextLabel", {
			["BackgroundTransparency"] = 1,
			["BorderSizePixel"] = 0,
			["Size"] = UDim2.new(0.9, 0, 0.7, 0),
			["Position"] = UDim2.new(0.5, 0, 0.5, 0),
			["AnchorPoint"] = Vector2.new(0.5, 0.5),
			["Text"] = p_u_9.state.code,
			["Font"] = Enum.Font.LuckiestGuy,
			["LineHeight"] = 0.7,
			["TextScaled"] = true,
			["TextXAlignment"] = Enum.TextXAlignment.Center,
			["TextYAlignment"] = Enum.TextYAlignment.Center,
			["TextColor3"] = Color3.fromRGB(255, 255, 255),
			["ZIndex"] = 10
		})
	}
	v22.Code = v26("Frame", v27, v28)
	local v29 = v_u_4
	local v30 = {
		["BackgroundTransparency"] = 1,
		["Size"] = UDim2.new(1, 0, 1, 0),
		["Position"] = UDim2.new(0, 0, 0, 0)
	}
	local v31 = {
		["AspectRatio"] = v_u_4("UIAspectRatioConstraint", {
			["AspectRatio"] = 10
		})
	}
	local v32 = v_u_4
	local v33 = {
		["BackgroundTransparency"] = 1,
		["BorderSizePixel"] = 0,
		["Size"] = UDim2.new(0.9, 0, 0.7, 0),
		["Position"] = UDim2.new(0.5, 0, 0.5, 0),
		["AnchorPoint"] = Vector2.new(0.5, 0.5),
		["Text"] = p_u_9.props.title or "",
		["Font"] = Enum.Font.LuckiestGuy,
		["LineHeight"] = 0.7,
		["TextScaled"] = true,
		["TextXAlignment"] = Enum.TextXAlignment.Center,
		["TextYAlignment"] = Enum.TextYAlignment.Center,
		["TextColor3"] = Color3.fromRGB(255, 255, 255),
		["ZIndex"] = 10
	}
	local v34 = {
		["UIStroke"] = v_u_4("UIStroke", {
			["Color"] = Color3.new(0.1, 0.1, 0.1),
			["Thickness"] = 2,
			["Enabled"] = p_u_9.props.active
		})
	}
	v31.Title = v32("TextLabel", v33, v34)
	v22.Title = v29("Frame", v30, v31)
	local v35 = v_u_4
	local v36 = {
		["BackgroundTransparency"] = 1,
		["Size"] = UDim2.new(1, 0, 0.8333333333333333, 0),
		["Position"] = UDim2.new(0, 0, 0.08333333333333333, 0)
	}
	local v37 = {}
	local v38 = {
		["aspectRatio"] = 1,
		["paddingRatio"] = 100,
		["rowsPerPage"] = 4,
		["colsPerRow"] = 3,
		["component"] = v_u_6,
		["items"] = v10
	}
	v37.Grid = v_u_3.createElement(v_u_2, v38)
	v22.Buttons = v35("Frame", v36, v37)
	return v20("Frame", v21, v22)
end
function v7.didMount(p39)
	p39:setState({
		["code"] = ""
	})
end
return v7
