-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMiBGluaXQFcHJpbnQRY2xpY2tlZCBjb250cmFjdHMHb25DbGljawRuYW1lB2ltYWdlSWQKVGVhbVN3aXRjaAVjb3VudAlDb250cmFjdHMGR2FyYWdlBlNlYXNvbg1jcmVhdGVFbGVtZW50B2J1dHRvbnMEc2l6ZQthbmNob3JQb2ludAhwb3NpdGlvbgVVRGltMgNuZXcHVmVjdG9yMgZyZW5kZXILd2lsbFVubW91bnQHdW5tb3VudAlDb21wb25lbnQDQXBwBmV4dGVuZAdyZXF1aXJlDVNpZGViYXJIb2xkZXIGc2NyaXB0BlBhcmVudAVtb3VudARnYW1lEVJlcGxpY2F0ZWRTdG9yYWdlCkdldFNlcnZpY2UFUm9hY3QABwEBAAAAAAGCAAEAAAAIAQEYAAgAAAAABAEAAAAABqQBAQAAAABAbwICAFIDAACfAQMBggABAAMDAgQAAABAAwMAEwQBGAAAAAAAARQAAAAACgECAAAASP8BAAAEAAAA4gICAG8DAwAwAwJaAAAAAG8DBAAwAwK2AQAAAOIDBwBvBAgAMAQDWgAAAABvBAkAMAQDtgEAAACMBAMAMAQDGgUAAADABAoAMAQDbgYAAADiBAIAbwULADAFBFoAAAAAbwUMADAFBLYBAAAA4gUCAG8GDQAwBgVaAAAAAG8GCQAwBgW2AQAAAMUBAgUBAAAA+wMAAE0CA8oOAAAA+wMBAOIEEwAwAQTzDwAAAKQFFgAAVECBbwYXAIwHAACMCAEAjAkAAJ8FBQIwBQQPEAAAAKQFGQAAVICBjAYAAIwHAQCfBQMCMAUECBEAAACkBRYAAFRAgYwGAACMBwAAbwgaAIwJAACfBQUCMAUE2xIAAACfAgMAggIAABsDBQMGBQIAAQMHAgAAsFCrTPJBAwgDBAUEAAEFBgMJAgAA0L7c2PZBBgEDCgIAAOAmq0zyQQMLAwwDDQMOAw8DEAUEDxAREgMRAxIEAFRAgQKamZmZmZnJPwMTBABUgIECAAAAAAAA4D8BAQkUARgAAAEBAAABAAACAQAAAQAAAQAAAQAABAEAAAEAAAIBAAABAAAAAAMAAAAAAQABAAAAAAAAAAABAAAAAAAAAQAAAAAAAAAA/AAKAAAAAAEBAAAAAAGCAAEAAAAnFQEYACcAAAAAAgACAAAABvsBAABNAAESAAAAAPsBAQCfAAIBggABAAEDFgAqAAEYAAAAAAABKwAAAAAGAQEAAAAp+wIAAE0BAogAAAAAbwMBALwBAZwCAAAAnwEDAqQCBAAAADBApAUHAAAAYEBNBAUkCAAAAE0DBGgFAAAAnwICAsADCQAwAwETCgAAANkDAQASAgAAEgACADADAYALAAAAwAMMADADATQNAAAA+wQAAE0DBOQOAAAA+wUAAE0EBcoPAAAAUgUBAJ8EAgJSBQAAnwMDAtkEAwASAgAAEgADAIIEAgAQAxcDGAMZAxoEAAAwQAMbAxwEAABgQAMdBgADAQMUBgMDFQMeAwwEAAIDBAUAARgAAAAAAAAAAQAAAAAAAAAAAQAAAQAAAAAeAAACAAAAAAAAAAAAAQAAAAYAAAAAAwAAAQIAD6MAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0CACEGAAAAnwECAsACBwASAAEAggICAAgDHwQAAABAAyADIQMaBAAAQEADIgYFAQUBAAEYAAEAAAAAAAEAAAAAAgAAAQAAAAAGnT2eooAJ5tWv+fQ28ijfJ+mVAXecZroPXTVI9rpw1AOxw0xO3lKVDQ==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Roact)
return function(p3)
	-- upvalues: (copy) v_u_2
	local v4 = v_u_2.Component:extend("App")
	local v_u_5 = require(script.Parent.SidebarHolder)
	function v4.init(_) end
	function v4.render(_)
		-- upvalues: (ref) v_u_2, (copy) v_u_5
		return v_u_2.createElement(v_u_5, {
			["buttons"] = {
				{
					["name"] = "TeamSwitch",
					["imageId"] = 4912231691
				},
				{
					["name"] = "Contracts",
					["imageId"] = 6132976621,
					["count"] = 3,
					["onClick"] = function(p6)
						print("clicked contracts", p6)
					end
				},
				{
					["name"] = "Garage",
					["imageId"] = 4912231022
				},
				{
					["name"] = "Season",
					["imageId"] = 6132976621
				}
			},
			["size"] = UDim2.new(0.2, 0, 1, 0),
			["anchorPoint"] = Vector2.new(0, 1),
			["position"] = UDim2.new(0, 0, 0.5, 0)
		})
	end
	function v4.willUnmount(_) end
	local v_u_7 = v_u_2.mount(v_u_2.createElement(v4), p3)
	return function()
		-- upvalues: (ref) v_u_2, (copy) v_u_7
		v_u_2.unmount(v_u_7)
	end
end
