-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMHBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlB0ZyaWVuZHMORnJpZW5kc1NlcnZpY2UEaW5pdAABBAAAAQIAEqMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DABgGAAAATQIDyQcAAACfAQICTQIBEwgAAACfAgEBggABAAkDAQQAAABAAwIDAwMEBAAAQEADBQMGAwcAAQABGAABAAAAAAABAAAAAAAAAQAAAQEAAAAAAH1LtLV1y+hWT4/eISUaW8MVQnAiQySOKuYAhJConZnIv64iYDEnR2M=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
require(v1.Friends.FriendsService).init()
