-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNWBlVzZXJJZAhJc1NlcnZlcgNtYXAKR2V0UGxheWVycwV0YWJsZQRmaW5kC0xvY2FsUGxheWVyBHdhcm5RT05MWSBTSE9XTiBGT1IgQUxFWDogW0Rvb3IyXSBOb3QgcmVjb21tZW5kZWQgdG8gaGF2ZSBub24tYmFzZXBhcnQgaW4gRG9vciBtb2RlbDogCUNsYXNzTmFtZQMgQCALR2V0RnVsbE5hbWULUHJpbWFyeVBhcnQFZXJyb3IeTWlzc2luZyBQcmltYXJ5UGFydCBmb3IgZG9vcjogCEluc3RhbmNlA25ldwRQYXJ0BFNpemUIQW5jaG9yZWQGQ0ZyYW1lCkNhbkNvbGxpZGUMVHJhbnNwYXJlbmN5BU1vZGVsEElOTkVSX01PREVMX05BTUUETmFtZQZpcGFpcnMLR2V0Q2hpbGRyZW4IQmFzZVBhcnQDSXNBBHRhc2sFZGVsYXkGUGFyZW50CVdlbGRBbGxUbwpCbGFua01vdG9yDk1PVE9SX09CSl9OQU1FBXNldHVwDk9QRU5fQVRUUl9OQU1FDEdldEF0dHJpYnV0ZQdnZXRPcGVuBmFzc2VydAxTZXRBdHRyaWJ1dGUHc2V0T3BlbhJQQ1RfT1BFTl9BVFRSX05BTUUKZ2V0UGN0T3Blbg9taXNzaW5nIHBjdE9wZW4Kc2V0UGN0T3BlbhlHZXRBdHRyaWJ1dGVDaGFuZ2VkU2lnbmFsGGdldERvb3JPcGVuQ2hhbmdlZFNpZ25hbBJEVVJBVElPTl9BVFRSX05BTUULZ2V0RHVyYXRpb24Lc2V0RHVyYXRpb24WU0hPVUxEX1NXSU5HX0FUVFJfTkFNRQ5nZXRTaG91bGRTd2luZw5zZXRTaG91bGRTd2luZxNNQVhfQU5HTEVfQVRUUl9OQU1FC2dldE1heEFuZ2xlC3NldE1heEFuZ2xlDkZpbmRGaXJzdENoaWxkDWdldElubmVyTW9kZWwRcHJvbWlzZUlubmVyTW9kZWwGQW5nbGVzAkMxB1Bpdm90VG8Lc2V0VmFsdWVSYXcIc2V0VmFsdWUdRlJFRVpFX1NFUlZFUl9TVEFURV9BVFRSX05BTUUWc2V0RnJlZXplU3RhdGVPblNlcnZlcgZ0eXBlb2YIRW51bUl0ZW0aRUFTSU5HX0RJUkVDVElPTl9BVFRSX05BTUUSc2V0RWFzaW5nRGlyZWN0aW9uFkVBU0lOR19TVFlMRV9BVFRSX05BTUUOc2V0RWFzaW5nU3R5bGUHcmVxdWlyZQZzY3JpcHQKRG9vckNvbnN0cwRnYW1lEVJlcGxpY2F0ZWRTdG9yYWdlCkdldFNlcnZpY2UKUnVuU2VydmljZQNTdGQFSm9pbnQMd2FpdEZvckNoaWxkClRhYmxlVXRpbHMHUGxheWVycwAWAgEAAAAAA00BAOYAAAAAggECAAEDAQAfAAEYAAAAIAAAAAAIAAQAAAA7qQAAAPsBAAC8AQELAAAAAJ8BAgIOARcA+wIBAE0BApABAAAA+wICALwCAqsCAAAAnwICAsADAwCfAQMCpAIGAAAUQIBSAwEAbwQHAJ8CAwIrAgYApAIGAAAUQIBSAwEAbwQIAJ8CAwIOAhEAqQABAGUADwD7AwIATQIDMQkAAABNAQLmCgAAAA0BCAAHAAAA+wMCAE0CAzEJAAAATQEC5goAAAANAQIACAAAgKkAAQAOAA0ApAEMAAAAsEBvAw0A+wcDAE0EB9sOAAAAbwUPAPsGAwC8BgayEAAAAJ8GAgJzAgMGnwECAYIAAQARAwIDAwMEBgADBQMGBAAUQIACAAAAAJbmPkECAAAAQMqueEEDBwMBAwgEAACwQAMJAwoDCwMMAQAaAAEYAAMAAAAAAQAAAAAAAAAAAwAAAAAAAAAAAAAAAQADAAAAAAAAAAAAAAAAAAEDAQABAQAAAQEAAAAA/AcbAAAAAA0CBQAABwQAAAUCBw9jTQIAmwAAAAArAggApAMCAAAAEEBvBQMAvAYAsgQAAACfBgICcwQFBp8DAgGkAwcAABhQgG8ECACfAwICbwQJADAEAy8KAAAAqQQBADAEA0ULAAAATQQChQwAAAAwBAOFDAAAAKkEAAAwBAPTDQAAAIwEAQAwBAPZDgAAAKQEBwAAGFCAbwUPAJ8EAgIwAgSbAAAAAPsGAABNBQZJEAAAADAFBLoRAAAApAUTAAAAIEG8BgBoFAAAAJ8GAgCfBQAEUQUVAG8MFQC8Cgn+FgAAAJ8KAwIrCg4AbwwPALwKCf4WAAAAnwoDAisKCQCkChkAAGBwgYwLAwDZDAAAEgIBABICAgASAgMAEgAJAJ8KAwEwBAkkGgAAAG4F6v8CAACAMAAEJBoAAAAwAAMkGgAAADADAJsAAAAADgETAPsGBABNBQZ/GwAAAFIGBABSBwIAnwUDAfsGBABNBQaBHAAAAFIGAgBSBwMAnwUDAvsHAABNBgehHQAAADAGBboRAAAAMAMFJBoAAACCBAIAHgMNAw4EAAAQQAMPAwwDEAMRBAAYUIADEgcAAIA/AACAPwAAgD8AAAAAAxMDFAMVAxYDFwMYAxkDGgMbBAAAIEEDHAMdAx4DHwMgBABgcIEDIQMiAyMDJAEBCiUBGAAAAQEAAAAAAAAAAgAAAAEAAAEAAAEAAAABAAABAAABAAAAAQABAAAAAAEAAAAAAAABAAAAAAAAAAAAAQAAAAAAAAAAGgDkAB4AAQABAAIBAAAAAAABAAAAAAABAAAAAAEAAwsAAAAABQEBAAAAB/sEAABNAwSvAAAAALwBABIBAAAAnwEDAIIBAAACAyYDJwBDKAEYAAAAAAAAAEQAAAAABgIBAAAAEEcBAgAAAACAqQMAAakDAQC7AQMCpAIBAAAAAECfAgIB+wUAAE0EBa8CAAAAUgUBALwCAC4DAAAAnwIEAYIAAQAEAykEAAAAQAMmAyoARisBGAAAAAAAAAAAAQAAAAAAAAFHAAAAAAUBAQAAAAf7BAAATQMEwQAAAAC8AQASAQAAAJ8BAwCCAQAAAgMsAycASi0BGAAAAAAAAABLAAAAAAYCAQAAABJHAQIAAAAAgKkDAAGpAwEAgQEDBAAAAABvBAAApAICAAAAEECfAgMB+wUAAE0EBcEDAAAAUgUBALwCAC4EAAAAnwIEAYIAAQAFAy4DKQQAABBAAywDKgBNLwEYAAAAAAAAAAAAAAEAAAAAAAABTgAAAAAFAQEAAAAH+wQAAE0DBK8AAAAAvAEAFgEAAACfAQMAggEAAAIDJgMwAFExARgAAAAAAAAAUgAAAAAFAQEAAAAH+wQAAE0DBGcAAAAAvAEAEgEAAACfAQMAggEAAAIDMgMnAFQzARgAAAAAAAAAVQAAAAAGAgEAAAAQRwECAAAAAICpAwABqQMBALsBAwKkAgEAAAAAQJ8CAgH7BQAATQQFZwIAAABSBQEAvAIALgMAAACfAgQBggABAAQDKQQAAABAAzIDKgBXNAEYAAAAAAAAAAABAAAAAAAAAVgAAAAABQEBAAAAB/sEAABNAwQBAAAAALwBABIBAAAAnwEDAIIBAAACAzUDJwBbNgEYAAAAAAAAAFwAAAAABgIBAAAAEEcBAgAAAACAqQMAAakDAQC7AQMCpAIBAAAAAECfAgIB+wUAAE0EBQECAAAAUgUBALwCAC4DAAAAnwIEAYIAAQAEAykEAAAAQAM1AyoAXjcBGAAAAAAAAAAAAQAAAAAAAAFfAAAAAAUBAQAAAAf7BAAATQMEMgAAAAC8AQASAQAAAJ8BAwCCAQAAAgM4AycAYjkBGAAAAAAAAABjAAAAAAYCAQAAABBHAQIAAAAAgKkDAAGpAwEAuwEDAqQCAQAAAABAnwICAfsFAABNBAUyAgAAAFIFAQC8AgAuAwAAAJ8CBAGCAAEABAMpBAAAAEADOAMqAGU6ARgAAAAAAAAAAAEAAAAAAAABZgAAAAAFAQEAAAAH+wQAAE0DBEkAAAAAvAEAAwEAAACfAQMAggEAAAIDGQM7AGk8ARgAAAAAAAAAagAAAAAFAQIAAAAI+wEAAFICAAD7BAEATQMESQAAAACMBAoAnwEEAIIBAAABAxkAbD0BGAAAAAAAAAAAbQAAAAAKBQAAAAAcxgUAAA4DCACkBgIAAAQAgIwHAABSCAQAjAkAAJ8GBAJSBQYAZQAHAKQGBAAADACAUgcEAIwIAACMCQAAnwYEAlIFBgAOAgMAMAUCzAUAAACCAAEATQkAhQAAAAAJCAkFvAYBwgYAAACfBgMBggABAAcDFQM+BAAEAIADEQQADACAAz8DQABvQQEYAAEBAAAAAAAAAAIAAAAAAAACAQAAAgAAAAAAAnAAAAAADAICAAAAHk0CAJsAAAAA+wYAAE0FBkkBAAAAvAMAAwIAAACfAwMC+wcAAE0GBwEDAAAAvAQAEgQAAACfBAMC+wgAAE0HCKEFAAAAvAUCAwIAAACfBQMC+wcBAE0GB3IGAAAAUgcCAFIIAwBSCQUAUgoEAFILAQCfBgYBggABAAcDDQMZAzsDNQMnAyQDQQB8QgEYAAABAAAAAAABAAAAAAABAAAAAAACAAAAAAAAAAABfQAAAAAGAgEAAAAI+wUAAE0EBd0AAAAAUgUBALwCAC4BAAAAnwIEAYIAAQACA0MDKgCEAUQBGAAAAAAAAAABhQAAAAAGAgEAAAAeRwACAAAAAICpAwABqQMBALsBAwKkAgEAAAAAQJ8CAgG7LAEDUgUBAKQEAwAAACBAnwQCAvAEAgAEAAAAqQMAAakDAQC7AQMCpAIBAAAAAECfAgIB+wUAAE0EBXQFAAAATQUBugYAAAC8AgAuBwAAAJ8CBAGCAAEACAMpBAAAAEADRQQAACBAA0YDRwMaAyoAhwFIARgAAAAAAAAAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAGIAAAAAAYCAQAAAB5HAAIAAAAAgKkDAAGpAwEAuwEDAqQCAQAAAABAnwICAbssAQNSBQEApAQDAAAAIECfBAIC8AQCAAQAAACpAwABqQMBALsBAwKkAgEAAAAAQJ8CAgH7BQAATQQFBQUAAABNBQG6BgAAALwCAC4HAAAAnwIEAYIAAQAIAykEAAAAQANFBAAAIEADRgNJAxoDKgCMAUoBGAAAAAAAAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAY0AAAAACQAAAQIAhQGjAAAApAABAAAAAECkAwMAAAAgQE0CAyQEAAAATQEC3wUAAACfAAICpAEHAAAAYEBvAwgAvAEBFgkAAACfAQMCpAIHAAAAYEBvBAoAvAICFgkAAACfAgMCpAMBAAAAAEBNBQGhCwAAAE0EBQwMAAAAnwMCAqQEAQAAAABATQYBoQsAAABNBQbzDQAAAJ8EAgKkBQEAAAAAQE0HAaELAAAATQYHGA4AAACfBQICpAYHAAAAYEBvCA8AvAYGFgkAAACfBgMC/wcGAAAAAADACBAAEgAAABIAAgASAAUAEgAGABIAAwAwCAf5EQAAAMAIEgASAAAAMAgHOhMAAADACBQAEgAAADAIBy4VAAAAwAgWABIAAAAwCAemFwAAAMAIGAASAAAAMAgHuhkAAADACBoAEgAAADAIB48bAAAAwAgcABIAAAAwCAfpHQAAAMAIHgASAAAAMAgHlR8AAADACCAAEgAAADAIB84hAAAAwAgiABIAAAAwCAfaIwAAAMAIJAASAAAAMAgHMiUAAADACCYAEgAAADAIByYnAAAAwAgoABIAAAAwCAeOKQAAAMAIKgASAAQAEgAAADAIB3krAAAAwAgsADAIB3ItAAAAwAguABIAAAASAAcAMAgH3y8AAADACDAAEgAAADAIB4gxAAAAwAgyABIAAAAwCAcPMwAAAMAINAASAAAAMAgHPjUAAACCBwIANgNLBAAAAEADTAQAACBAAyEDTQNOBAAAYEADTwNQA1EDUgNTA1QDVQNWBgIDJQYDAygGBAMrBgUDLQYGAy8GBwMxBggDMwYJAzQGCgM2BgsDNwYMAzkGDQM6Bg4DPAYPAz0GEANBBhEDQgYSA0QGEwNIBhQDShMCAwQFBgcICQoLDA0ODxAREhMUAQABGAAAAAAAAAAAAAABAAAAAAABAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAACAAEAAAAAAAAAOQAAAAMAAAAEAAAAAwAAAAQAAAADAAAAAwAAAAQAAAADAAAABAAAAAMAAAAEAAAAAwAAAAADAAANAAAAAAgAAAADAAAABQAAAAUBAAAAABWGUj9EvZBN57SWVdA9nh8ed5cBmwHAvhr92Q1Dsv9Ruqj1WdpeeIg+

-- Decompiled by Krnl

local v_u_1 = require(script.Parent.DoorConsts)
local v2 = game:GetService("ReplicatedStorage")
local v_u_3 = game:GetService("RunService")
local v_u_4 = require(v2.Std.Joint)
local v_u_5 = require(v2.Std.waitForChild)
local v_u_6 = require(v2.Std.TableUtils)
local v_u_7 = game:GetService("Players")
local v_u_64 = {
	["setup"] = function(p8, p9)
		-- upvalues: (copy) v_u_1, (copy) v_u_3, (copy) v_u_6, (copy) v_u_7, (copy) v_u_4
		local v10 = p8.PrimaryPart
		if not v10 then
			error("Missing PrimaryPart for door: " .. p8:GetFullName())
		end
		local v11 = Instance.new("Part")
		v11.Size = Vector3.new(1, 1, 1)
		v11.Anchored = true
		v11.CFrame = v10.CFrame
		v11.CanCollide = false
		v11.Transparency = 1
		local v12 = Instance.new("Model")
		v12.PrimaryPart = v10
		v12.Name = v_u_1.INNER_MODEL_NAME
		for _, v_u_13 in ipairs(p8:GetChildren()) do
			if not (v_u_13:IsA("BasePart") or v_u_13:IsA("Model")) then
				task.delay(3, function()
					-- upvalues: (ref) v_u_3, (ref) v_u_6, (ref) v_u_7, (copy) v_u_13
					local v14 = false
					local v15
					if v_u_3:IsServer() then
						local v17 = v_u_6.map(v_u_7:GetPlayers(), function(p16)
							return p16.UserId
						end)
						v15 = (table.find(v17, 2025110) or table.find(v17, 25881764)) and true or v14
					else
						v15 = (v_u_7.LocalPlayer.UserId == 2025110 or v_u_7.LocalPlayer.UserId == 25881764) and true or v14
					end
					if v15 then
						warn("ONLY SHOWN FOR ALEX: [Door2] Not recommended to have non-basepart in Door model: " .. v_u_13.ClassName .. " @ " .. v_u_13:GetFullName())
					end
				end)
			end
			v_u_13.Parent = v12
		end
		v12.Parent = p8
		v11.Parent = p8
		p8.PrimaryPart = v11
		if p9 then
			v_u_4.WeldAllTo(v12, v10)
			local v18 = v_u_4.BlankMotor(v10, v11)
			v18.Name = v_u_1.MOTOR_OBJ_NAME
			v18.Parent = v11
		end
		return v12
	end,
	["getOpen"] = function(p19)
		-- upvalues: (copy) v_u_1
		return p19:GetAttribute(v_u_1.OPEN_ATTR_NAME)
	end,
	["setOpen"] = function(p20, p21)
		-- upvalues: (copy) v_u_1
		local v22 = p21 ~= nil
		assert(v22)
		p20:SetAttribute(v_u_1.OPEN_ATTR_NAME, p21)
	end,
	["getPctOpen"] = function(p23)
		-- upvalues: (copy) v_u_1
		return p23:GetAttribute(v_u_1.PCT_OPEN_ATTR_NAME)
	end,
	["setPctOpen"] = function(p24, p25)
		-- upvalues: (copy) v_u_1
		local v26 = p25 ~= nil
		assert(v26, "missing pctOpen")
		p24:SetAttribute(v_u_1.PCT_OPEN_ATTR_NAME, p25)
	end,
	["getDoorOpenChangedSignal"] = function(p27)
		-- upvalues: (copy) v_u_1
		return p27:GetAttributeChangedSignal(v_u_1.OPEN_ATTR_NAME)
	end,
	["getDuration"] = function(p28)
		-- upvalues: (copy) v_u_1
		return p28:GetAttribute(v_u_1.DURATION_ATTR_NAME)
	end,
	["setDuration"] = function(p29, p30)
		-- upvalues: (copy) v_u_1
		local v31 = p30 ~= nil
		assert(v31)
		p29:SetAttribute(v_u_1.DURATION_ATTR_NAME, p30)
	end,
	["getShouldSwing"] = function(p32)
		-- upvalues: (copy) v_u_1
		return p32:GetAttribute(v_u_1.SHOULD_SWING_ATTR_NAME)
	end,
	["setShouldSwing"] = function(p33, p34)
		-- upvalues: (copy) v_u_1
		local v35 = p34 ~= nil
		assert(v35)
		p33:SetAttribute(v_u_1.SHOULD_SWING_ATTR_NAME, p34)
	end,
	["getMaxAngle"] = function(p36)
		-- upvalues: (copy) v_u_1
		return p36:GetAttribute(v_u_1.MAX_ANGLE_ATTR_NAME)
	end,
	["setMaxAngle"] = function(p37, p38)
		-- upvalues: (copy) v_u_1
		local v39 = p38 ~= nil
		assert(v39)
		p37:SetAttribute(v_u_1.MAX_ANGLE_ATTR_NAME, p38)
	end,
	["getInnerModel"] = function(p40)
		-- upvalues: (copy) v_u_1
		return p40:FindFirstChild(v_u_1.INNER_MODEL_NAME)
	end,
	["promiseInnerModel"] = function(p41)
		-- upvalues: (copy) v_u_5, (copy) v_u_1
		return v_u_5(p41, v_u_1.INNER_MODEL_NAME, 10)
	end,
	["setValueRaw"] = function(p42, p43, p44, p45, p46)
		local v47
		if p45 then
			v47 = CFrame.Angles(0, p46, 0)
		else
			v47 = CFrame.new(p46, 0, 0)
		end
		if p44 then
			p44.C1 = v47
		else
			p43:PivotTo(p42.CFrame * v47)
		end
	end,
	["setValue"] = function(p48, p49)
		-- upvalues: (copy) v_u_1, (copy) v_u_64
		local v50 = p48.PrimaryPart
		local v51 = p48:FindFirstChild(v_u_1.INNER_MODEL_NAME)
		local v52 = p48:GetAttribute(v_u_1.SHOULD_SWING_ATTR_NAME)
		local v53 = v50:FindFirstChild(v_u_1.MOTOR_OBJ_NAME)
		v_u_64.setValueRaw(v50, v51, v53, v52, p49)
	end,
	["setFreezeStateOnServer"] = function(p54, p55)
		-- upvalues: (copy) v_u_1
		p54:SetAttribute(v_u_1.FREEZE_SERVER_STATE_ATTR_NAME, p55)
	end,
	["setEasingDirection"] = function(p56, p57)
		-- upvalues: (copy) v_u_1
		local v58 = p56 ~= nil
		assert(v58)
		local v59 = typeof(p57) == "EnumItem"
		assert(v59)
		p56:SetAttribute(v_u_1.EASING_DIRECTION_ATTR_NAME, p57.Name)
	end,
	["setEasingStyle"] = function(p60, p61)
		-- upvalues: (copy) v_u_1
		local v62 = p60 ~= nil
		assert(v62)
		local v63 = typeof(p61) == "EnumItem"
		assert(v63)
		p60:SetAttribute(v_u_1.EASING_STYLE_ATTR_NAME, p61.Name)
	end
}
return v_u_64
