-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMhBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplCFRBR19OQU1FEElOTkVSX01PREVMX05BTUUOT1BFTl9BVFRSX05BTUUSUENUX09QRU5fQVRUUl9OQU1FEkRVUkFUSU9OX0FUVFJfTkFNRRNNQVhfQU5HTEVfQVRUUl9OQU1FFlNIT1VMRF9TV0lOR19BVFRSX05BTUUaRUFTSU5HX0RJUkVDVElPTl9BVFRSX05BTUUWRUFTSU5HX1NUWUxFX0FUVFJfTkFNRR1GUkVFWkVfU0VSVkVSX1NUQVRFX0FUVFJfTkFNRRVTSE9VTERfV0VMRF9BVFRSX05BTUUOTU9UT1JfT0JKX05BTUUdRE9PUl9QTEFZRVJfUkVHSU9OX1ZBTFVFX05BTUUFRG9vcjIKSW5uZXJNb2RlbAhEb29yT3BlbgtEb29yUGN0T3BlbgxEb29yRHVyYXRpb24MRG9vck1heEFuZ2xlD0Rvb3JTaG91bGRTd2luZxNEb29yRWFzaW5nRGlyZWN0aW9uD0Rvb3JFYXNpbmdTdHlsZRVEb29yRnJlZXplU2VydmVyU3RhdGUORG9vclNob3VsZFdlbGQJRG9vck1vdG9yEERvb3JQbGF5ZXJSZWdpb24AAQUAAAECADqjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CAxgHAAAAnwECAk0CAQAIAAAA4gMWAG8EFwAwBAO0CQAAAG8EGAAwBANJCgAAAG8EGQAwBAOvCwAAAG8EGgAwBAPBDAAAAG8EGwAwBANnDQAAAG8EHAAwBAMyDgAAAG8EHQAwBAMBDwAAAG8EHgAwBAN0EAAAAG8EHwAwBAMFEQAAAG8EIAAwBAPdEgAAAG8EIQAwBAMdEwAAAG8EIgAwBAOhFAAAAG8EIwAwBAMhFQAAAJ8CAgCCAgAAJAMBBAAAAEADAgMDAwQEAABAQAMFAwYDBwMIAwkDCgMLAwwDDQMOAw8DEAMRAxIDEwMUBQ0JCgsMDQ4PEBESExQVAxUDFgMXAxgDGQMaAxsDHAMdAx4DHwMgAyEAAQABGAAAAAAAAAABAAAAAAAAAQAAAQAAAQAAAgAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAgAA8QABAAAAAADYBLV/+asliurA3+tf0s3oNqbfE8da7lJbuh8GqGymUUxj9MZOfzLr

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Std.TableUtils).requireValidIndexAndFreeze({
	["TAG_NAME"] = "Door2",
	["INNER_MODEL_NAME"] = "InnerModel",
	["OPEN_ATTR_NAME"] = "DoorOpen",
	["PCT_OPEN_ATTR_NAME"] = "DoorPctOpen",
	["DURATION_ATTR_NAME"] = "DoorDuration",
	["MAX_ANGLE_ATTR_NAME"] = "DoorMaxAngle",
	["SHOULD_SWING_ATTR_NAME"] = "DoorShouldSwing",
	["EASING_DIRECTION_ATTR_NAME"] = "DoorEasingDirection",
	["EASING_STYLE_ATTR_NAME"] = "DoorEasingStyle",
	["FREEZE_SERVER_STATE_ATTR_NAME"] = "DoorFreezeServerState",
	["SHOULD_WELD_ATTR_NAME"] = "DoorShouldWeld",
	["MOTOR_OBJ_NAME"] = "DoorMotor",
	["DOOR_PLAYER_REGION_VALUE_NAME"] = "DoorPlayerRegion"
})
