-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgM2Dk9QRU5fQVRUUl9OQU1FDEdldEF0dHJpYnV0ZQtfdXBkYXRlRW5kShJQQ1RfT1BFTl9BVFRSX05BTUUGX2xhc3RKD29ic2VydmVQcm9wZXJ0eQppbm5lck1vZGVsC1ByaW1hcnlQYXJ0CEdpdmVUYXNrDHNldG1ldGF0YWJsZQNuZXcFX21haWQPX3VwZGF0ZUNhbGxiYWNrGUdldEF0dHJpYnV0ZUNoYW5nZWRTaWduYWwHQ29ubmVjdBNNQVhfQU5HTEVfQVRUUl9OQU1FEVNldFVwZGF0ZUNhbGxiYWNrAm9zBWNsb2NrCEdldFZhbHVlCl9sYXN0VmFsdWUJX2FuaW1hdG9yC3NldFZhbHVlUmF3BG1hdGgDYWJzEElOTkVSX01PREVMX05BTUUORmluZEZpcnN0Q2hpbGQSRFVSQVRJT05fQVRUUl9OQU1FFlNIT1VMRF9TV0lOR19BVFRSX05BTUUOTU9UT1JfT0JKX05BTUUERW51bQ9FYXNpbmdEaXJlY3Rpb24aRUFTSU5HX0RJUkVDVElPTl9BVFRSX05BTUULRWFzaW5nU3R5bGUWRUFTSU5HX1NUWUxFX0FUVFJfTkFNRQRTaXplAVgJSGVhcnRiZWF0CHNldFZhbHVlB0Rlc3Ryb3kEZ2FtZQxUd2VlblNlcnZpY2UKR2V0U2VydmljZQpSdW5TZXJ2aWNlEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUDU3RkBE1haWQPUnhJbnN0YW5jZVV0aWxzBnNjcmlwdAZQYXJlbnQKRG9vckNvbnN0cwlEb29yVXRpbHMHX19pbmRleAAMBQADAAAAE/sBAAD7BAEATQMErwAAAAC8AQESAQAAAJ8BAwIqAQMAAQAAgIwAAQBlAAEAjAAAAPsBAgD7AwAAUgQAALwBAZsCAAAAnwEEAYIAAQADAwEDAgMDABMAARgAAAAAAAAAAAAAAAABAAAAAAABFAAAAAAGAAMAAAAc+wAAAPsDAQBNAgPBAAAAALwAABIBAAAAnwADAkcADQAAAACA+wIAAPsFAQBNBAWvAgAAALwCAhIBAAAAnwIDAg4CAgCMAQEAZQABAIwBAABSAAEA+wECAPsDAABSBAAAvAEBmwMAAACfAQQBggABAAQDBAMCAwEDAwAXAAEYAAAAAAAAAAEAAQAAAAAAAAAAAAAAAgAAAAAAARgAAAAABQADAAAADvsAAAD7AwEATQIDwQAAAAC8AAASAQAAAJ8AAwL7AQIA+wMAAFIEAAC8AQGbAgAAAJ8BBAGCAAEAAwMEAwIDAwAeAAEYAAAAAAAAAAEAAAAAAAEfAAAAAAcBAwAAACEOAB8A+wEAAPsEAQBNAwTBAAAAALwBARIBAAAAnwEDAkcBDQAAAACA+wMAAPsGAQBNBQavAgAAALwDAxIBAAAAnwMDAg4DAgCMAgEAZQABAIwCAABSAQIA+wICADABArQDAAAA+wICAPsEAABSBQEAqQYBALwCApsEAAAAnwIFAYIAAQAFAwQDAgMBAwUDAwAmAAEYAAEAAAAAAAABAAEAAAAAAAAAAAAAAAIAAAEAAAAAAAACJwAAAAAIAgUAAAARDgAPAPsFAABNBAVIAAAAAPsGAQBNBQbeAQAAAG8GAgDZBwAAEgICABICAwASAgQAnwQEALwCAf0DAAAAnwIAAYIAAQAEAwYDBwMIAwkBAyMAARgAAgAAAAAAAAAAAAAA/wAADSQAAAAACQIEAAAAWv8CAwAAAAAA+wUAAJ49AgQFAAAAUgQCAKQDAQAAAABAnwMDAfsEAQBNAwTvAgAAAJ8DAQIwAwLBAwAAAMYDAAAwAwJ+BAAAAE0DAsEDAAAA+wgCAE0HCK8FAAAAvAUAFgYAAACfBQMC2QcAABIAAAASAgIAEgACALwFBccHAAAAnwUDALwDA/0IAAAAnwMAAU0DAsEDAAAA+wgCAE0HCDIJAAAAvAUAFgYAAACfBQMC2QcBABIAAAASAgIAEgACALwFBccHAAAAnwUDALwDA/0IAAAAnwMAAU0DAsEDAAAA+wgCAE0HCMEKAAAAvAUAFgYAAACfBQMC2QcCABIAAAASAgIAEgACALwFBccHAAAAnwUDALwDA/0IAAAAnwMAAU0DAsEDAAAA+wYDAE0FBkgLAAAAUgYAAG8HDADZCAMAEgIDABIAAQASAAAAEgICABIAAgCfBQQAvAMD/QgAAACfAwABggICAA0DCgQAAABAAwsDDAMNAwEDDgMPAwkDEAMEAwYDCAQAAQIEDQsBGAAAAQAAAAAAAAIAAAAAAAEAAAEAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAAEQ4AAAAAAgACAAAADvsBAABNAAF+AAAAAPsBAQCaAAcAAQAAAPsAAADGAQAAMAEAfgAAAACpAAEAggACAKkAAACCAAIAAQMNADgAARgAAAAAAAABAAAAAQACADkAAAAAAwIAAAAABjABAH4AAAAA2QIAABIAAAASAAEAggICAAEDDQEGNhEBGAAAAQAAADcAAAAADAAOAAAAP6QAAgAABACAnwABAvsDAAAmAgAD+wMBAOwBAgP7AgIAUgQBAPsFAwD7BgQAvAIC8wMAAACfAgUC+wQFACYDAgTeAgUA+wUGAE0EBQkEAAAA+wcHAAkGBwNDBQQG+wcAACYGAAf7BwEAfQcIAAYAAAD7BQgA+wcGAE0GB8EFAAAAxgcAADAHBucGAAAA+wYGADAFBgkEAAAA+wcJAE0GB3IHAAAA+wcKAPsICwD7CQwA+woNAFILBQCfBgYB+wcGAE0GB34IAAAADgYLAPsHBgBNBgd+CAAAAFIHBQD7CgcA7AkFCrsCCQKkCAsAACiQgJ8IAgKfBgMBggABAAwDEgMTBAAEAIADFAMVAwwDFgMXAw0DGAMZBAAokIAAWgABGAAAAAEAAAABAAAAAAAAAQABAgAAAQAAAQAAAAABAgAAAAAAAgAAAgAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAlsAAAAAFgQEAAAAfPsHAABNBgdJAAAAALwEAQMBAAAAnwQDAk0FAZsCAAAA+wkAAE0ICWcDAAAAvAYBEgQAAACfBgMC+woAAE0JCgEFAAAAvAcBEgQAAACfBwMC+wsAAE0KCzIGAAAAvAgBEgQAAACfCAMC+wwAAE0LDKEHAAAAvAkFAwEAAACfCQMCpAsKAAAkgID7DwAATQ4PdAsAAAC8DAESBAAAAJ8MAwKHCgsMpAwNAAAwgID7EAAATQ8QBQ4AAAC8DQESBAAAAJ8NAwKHCwwNxgwAAA4HAgBSDAgAZQAGAE0OBJsCAAAATQ0OLw8AAABNDA15EAAAAAkNAgwrAy4ATQ8ACREAAAAmDg0PuwIOA1ISDgCkERQAAEwggZ8RAgK7AgwDUhMMAKQSFAAATCCBnxICAuwQERIJDxAGpBAXAABYUIGfEAECjBEAAE0SAMEYAAAA+xQBAE0TFP0ZAAAA2RUAABIAEAASAA8AEgICABIACwASAAoAEgER/xIAAAASAA4AEgANABICAwASAAUAEgAEABIACQASAAcAvBMTxxoAAACfEwMCMBMS5xsAAADBEQAAggABADANAAkRAAAA+w8DAE0OD98cAAAAUg8BAFIQDQCfDgMBTQ4Afh0AAAAODgQATQ4Afh0AAABSDw0Anw4CAYIAAQAeAxoDGwMIAxwDAgMdAxADHgMfAyAEACSAgAMhAyIEADCAgAMjAyQDJQMVAxgDGQQATCCBAxIDEwQAWFCBAwwDJgMPAxYDJwMNAQhAAwEYAAAAAAAAAQABAAAAAAABAAAAAAABAAAAAAABAAAAAAACAAAAAAAAAAABAAAAAAAAAAACAQEAAgAAAAAAAwIBAAABAAAAAAAAAAAAAAACAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFgACAAAAAAABAAABAAAAA0EAAAAABAEAAAAAEE0BAMEAAAAAvAEBUAEAAACfAQIBxgEAADABAMEAAAAAgT0ABQIAAABSAgAAbwMCAKQBBAAAADBAnwEDAYIAAQAFAwwDKAADCgQAADBAAHgoARgAAAAAAAEAAAEAAAAAAAABeQAAAAAKAAABAgBMowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBAQAAAABAbwMEALwBARYDAAAAnwEDAqQCAQAAAABAbwQFALwCAhYDAAAAnwIDAqQDBwAAAGBATQUCoQgAAABNBAV2CQAAAJ8DAgKkBAcAAABgQE0GAqEIAAAATQUGUgoAAACfBAICpAUHAAAAYECkCAwAAACwQE0HCCQNAAAATQYH3w4AAACfBQICpAYHAAAAYECkCQwAAACwQE0ICSQNAAAATQcIvA8AAACfBgIC/wcEAAAAAAAwBwduEAAAAMAIEQASAAcAEgADABIABQASAAQAMAgH7xIAAADACBMAMAgHyBQAAADACBUAEgAFABIAAQASAAAAEgAGADAIB5sWAAAAwAgXADAIB1AYAAAAggcCABkDKQQAAABAAyoDKwMsAy0DLgQAAGBAAy8DMAMxAzIEAACwQAMzAzQDNQM2BgUDCwYHAxEGCQMDBgoDKAQFBwkKAQABGAAAAAAAAAABAAAAAAABAAAAAAABAAAAAAAAAQAAAAAAAAIAAAAAAAAAAAEAAAAAAAAAAAIAAQACAAAAAAAAKQAACgAAAAAAADgAAAYBAAAAAAuflD6XCh4i2a1QVAPXptWSC18tCUzVMthuYJzh8fX76EC1C18K/cxW

-- Decompiled by Krnl

local v_u_1 = game:GetService("TweenService")
local v_u_2 = game:GetService("RunService")
local v3 = game:GetService("ReplicatedStorage")
local v_u_4 = require(v3.Std.Maid)
local v_u_5 = require(v3.Std.RxInstanceUtils)
local v_u_6 = require(script.Parent.DoorConsts)
local v_u_7 = require(script.Parent.DoorUtils)
local v_u_8 = {}
v_u_8.__index = v_u_8
function v_u_8.new(p_u_9, p_u_10)
	-- upvalues: (copy) v_u_8, (copy) v_u_4, (copy) v_u_6, (copy) v_u_5
	local v_u_11 = {}
	local v12 = v_u_8
	setmetatable(v_u_11, v12)
	v_u_11._maid = v_u_4.new()
	v_u_11._updateCallback = nil
	v_u_11._maid:GiveTask(p_u_9:GetAttributeChangedSignal(v_u_6.OPEN_ATTR_NAME):Connect(function()
		-- upvalues: (copy) p_u_9, (ref) v_u_6, (copy) v_u_11
		v_u_11:_updateEndJ(p_u_9, p_u_9:GetAttribute(v_u_6.OPEN_ATTR_NAME) == true and 1 or 0)
	end))
	v_u_11._maid:GiveTask(p_u_9:GetAttributeChangedSignal(v_u_6.MAX_ANGLE_ATTR_NAME):Connect(function()
		-- upvalues: (copy) p_u_9, (ref) v_u_6, (copy) v_u_11
		local v13 = p_u_9:GetAttribute(v_u_6.PCT_OPEN_ATTR_NAME)
		v_u_11:_updateEndJ(p_u_9, v13 == nil and (p_u_9:GetAttribute(v_u_6.OPEN_ATTR_NAME) and 1 or 0) or v13)
	end))
	v_u_11._maid:GiveTask(p_u_9:GetAttributeChangedSignal(v_u_6.PCT_OPEN_ATTR_NAME):Connect(function()
		-- upvalues: (copy) p_u_9, (ref) v_u_6, (copy) v_u_11
		v_u_11:_updateEndJ(p_u_9, (p_u_9:GetAttribute(v_u_6.PCT_OPEN_ATTR_NAME)))
	end))
	v_u_11._maid:GiveTask(v_u_5.observeProperty(p_u_9, "PrimaryPart", function(p14, p15)
		-- upvalues: (ref) v_u_5, (copy) p_u_10, (copy) p_u_9, (ref) v_u_6, (copy) v_u_11
		if p14 then
			p15:GiveTask(v_u_5.observeProperty(p_u_10.innerModel, "PrimaryPart", function(p16)
				-- upvalues: (ref) p_u_9, (ref) v_u_6, (ref) v_u_11
				if p16 then
					local v17 = p_u_9:GetAttribute(v_u_6.PCT_OPEN_ATTR_NAME)
					local v18 = v17 == nil and (p_u_9:GetAttribute(v_u_6.OPEN_ATTR_NAME) and 1 or 0) or v17
					v_u_11._lastJ = v18
					v_u_11:_updateEndJ(p_u_9, v18, true)
				end
			end))
		end
	end))
	return v_u_11
end
function v_u_8.SetUpdateCallback(p_u_19, p_u_20)
	p_u_19._updateCallback = p_u_20
	return function()
		-- upvalues: (copy) p_u_19, (copy) p_u_20
		if p_u_19._updateCallback ~= p_u_20 then
			return false
		end
		p_u_19._updateCallback = nil
		return true
	end
end
function v_u_8._updateEndJ(p_u_21, p22, p23, p24)
	-- upvalues: (copy) v_u_6, (copy) v_u_2, (copy) v_u_1, (copy) v_u_7
	local v_u_25 = p22:FindFirstChild(v_u_6.INNER_MODEL_NAME)
	local v_u_26 = p22.PrimaryPart
	local v27 = p22:GetAttribute(v_u_6.DURATION_ATTR_NAME)
	local v_u_28 = p22:GetAttribute(v_u_6.SHOULD_SWING_ATTR_NAME)
	local v29 = p22:GetAttribute(v_u_6.MAX_ANGLE_ATTR_NAME)
	local v_u_30 = v_u_26:FindFirstChild(v_u_6.MOTOR_OBJ_NAME)
	local v_u_31 = Enum.EasingDirection[p22:GetAttribute(v_u_6.EASING_DIRECTION_ATTR_NAME)]
	local v_u_32 = Enum.EasingStyle[p22:GetAttribute(v_u_6.EASING_STYLE_ATTR_NAME)]
	if not v_u_28 then
		v29 = v_u_25.PrimaryPart.Size.X
	end
	local v_u_33 = p23 * v29
	if p24 then
		p_u_21._lastValue = v_u_33
		v_u_7.setValue(p22, v_u_33)
		if p_u_21._updateCallback then
			p_u_21._updateCallback(v_u_33)
		end
	else
		local v_u_34 = v_u_33 - p_u_21._lastValue
		local v_u_35 = math.abs(v_u_34) / math.abs(v29) * v27
		local v_u_36 = os.clock()
		local v_u_37 = 0
		p_u_21._maid._animator = v_u_2.Heartbeat:Connect(function()
			-- upvalues: (copy) v_u_36, (copy) v_u_35, (ref) v_u_1, (copy) v_u_32, (copy) v_u_31, (ref) v_u_37, (copy) p_u_21, (copy) v_u_34, (copy) v_u_33, (ref) v_u_7, (copy) v_u_26, (copy) v_u_25, (copy) v_u_30, (copy) v_u_28
			local v38 = os.clock()
			local v39 = v_u_1:GetValue((v38 - v_u_36) / v_u_35, v_u_32, v_u_31)
			local v40 = v39 - v_u_37
			v_u_37 = v39
			local v41 = p_u_21._lastValue + v_u_34 * v40
			if v_u_35 <= v38 - v_u_36 then
				v41 = v_u_33
				p_u_21._maid._animator = nil
			end
			p_u_21._lastValue = v41
			v_u_7.setValueRaw(v_u_26, v_u_25, v_u_30, v_u_28, v41)
			if p_u_21._updateCallback then
				local v42 = p_u_21._updateCallback
				local v43 = v41 / v_u_34
				v42(v41, (math.abs(v43)))
			end
		end)
	end
end
function v_u_8.Destroy(p44)
	p44._maid:Destroy()
	p44._maid = nil
	setmetatable(p44, nil)
end
return v_u_8
