-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNdDE9uTW91c2VFbnRlcgRGaXJlDE9uTW91c2VMZWF2ZQxPbk1vdXNlQ2xpY2sMc2V0bWV0YXRhYmxlBUFscGhhA25ldwRNYWlkCExpc3RJdGVtDlZpZXdwb3J0VXBkYXRlCEdpdmVUYXNrCEluc3RhbmNlCkltYWdlTGFiZWwFVURpbTIEU2l6ZQtMYXlvdXRPcmRlchdyYnhhc3NldGlkOi8vNTkyNTg3OTY2OQVJbWFnZQRFbnVtCVNjYWxlVHlwZQVTbGljZQRSZWN0C1NsaWNlQ2VudGVyFkJhY2tncm91bmRUcmFuc3BhcmVuY3kGQ29sb3IzEEJhY2tncm91bmRDb2xvcjMJQ29udGFpbmVyF1VJQXNwZWN0UmF0aW9Db25zdHJhaW50C0FzcGVjdFJhdGlvCkFzcGVjdFR5cGUTU2NhbGVXaXRoUGFyZW50U2l6ZQxEb21pbmFudEF4aXMFV2lkdGgGUGFyZW50BUZyYW1lBkFjdGl2ZRBDbGlwc0Rlc2NlbmRhbnRzCFBvc2l0aW9uEF9jb250YWluZXJCb3R0b20MVUlMaXN0TGF5b3V0CVNvcnRPcmRlcg1GaWxsRGlyZWN0aW9uCkhvcml6b250YWwPbVNjcm9sbGluZ0ZyYW1lB1ZlY3RvcjILQW5jaG9yUG9pbnQXcmJ4YXNzZXRpZDovLzU4MzQyOTk5NzYKU2VsZWN0YWJsZQ1WaWV3cG9ydEZyYW1lDkxpZ2h0RGlyZWN0aW9uCkxpZ2h0Q29sb3IHQW1iaWVudA9Cb3JkZXJTaXplUGl4ZWwGQ2FtZXJhDUN1cnJlbnRDYW1lcmEGYXNzZXJ0BEluc3QFdGFibGUGaW5zZXJ0Ck1vdXNlRW50ZXIHQ29ubmVjdApNb3VzZUxlYXZlB09uQ2xpY2sJQmluZElucHV0CVZpZXdwb3J0cwxFYXNlX091dFF1YWQSR2V0Q29udGFpbmVyQm90dG9tE0Fic29sdXRlQ29udGVudFNpemUBWAlTZXRQYXJlbnQLSW1hZ2VCdXR0b24XcmJ4YXNzZXRpZDovLzQ5MzMxNDM3ODEQTW91c2VCdXR0b24xRG93bhBPbk1vdXNlQ2xpY2tCYWNrDUFkZEJhY2tCdXR0b24EdGljawpMYXN0VXBkYXRlEEFic29sdXRlUG9zaXRpb24MQWJzb2x1dGVTaXplBG1hdGgDbWluBlVwZGF0ZQdEZXN0cm95BGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZAZTaWduYWwOU2Nyb2xsaW5nRnJhbWUGTW9kdWxlCXdvcmtzcGFjZQdfX2luZGV4AAsEAAMAAAAJ+wEAAE0AASQAAAAA+wIBAPsDAgC8AADdAQAAAJ8ABAGCAAEAAgMBAwIAngEBARgAAAAAAAAAAAGfAAAAAAQAAwAAAAn7AQAATQAB5wAAAAD7AgEA+wMCALwAAN0BAAAAnwAEAYIAAQACAwMDAgCiAQMBGAAAAAAAAAAAAaMAAAAABAADAAAACfsBAABNAAFiAAAAAPsCAQD7AwIAvAAA3QEAAACfAAQBggABAAIDBAMCAKcBBAEYAAAAAAAAAAABqAAAAAAhBAQAAAC9A/8FBQAAAAAA+wYAAJ49BQMGAAAApAQBAAAAAECfBAMCjAUAADAFBBYCAAAA+wYBAE0FBu8DAAAAnwUBAjAFBHYEAAAAMAAEtQUAAAAwAwQ5BgAAAPsGAgBNBQbvAwAAAJ8FAQIwBQQkBwAAAE0FBHYEAAAATQcEJAcAAAC8BQX9CAAAAJ8FAwH7BgIATQUG7wMAAACfBQECMAUE5wkAAABNBQR2BAAAAE0HBOcJAAAAvAUF/QgAAACfBQMB+wYCAE0FBu8DAAAAnwUBAjAFBGIKAAAATQUEdgQAAABNBwRiCgAAALwFBf0IAAAAnwUDAaQFDAAADLCAbwYNAJ8FAgKkBg8AAAzggG8HEACMCAAAjAkBAIwKAACfBgUCMAYFLxEAAACMBgEAMAYFABIAAABvBhMAMAYFqRQAAACkBhgAF1hQwTAGBdEWAAAApAYaAAAMkIGMBx4AjAgeAIwJZACMCmQAnwYFAjAGBc8bAAAAjAYBADAGBTocAAAApAYeAAAM0IGMBwEAjAgBAIwJAQCfBgQCMAYFnx8AAAAwBQRvIAAAAKQGDAAADLCAbwchAJ8GAgJvByIAMAcGaSMAAACkByYAJZBQwTAHBv0kAAAApAcpACicUMEwBwbmJwAAADAFBiQqAAAApAcMAAAMsIBvCCsAnwcCAowIAQAwCAc6HAAAAKQIDwAADOCAjAkBAIwKAABvCywAjAwAAJ8IBQIwCAcvEQAAAKkIAQAwCAeDLQAAAKkIAQAwCAezLgAAADAFByQqAAAApAgMAAAMsIBvCSsAnwgCAowJAQAwCQg6HAAAAKQJDwAADOCAjAoBAIwLAABvDC8AjA0AAJ8JBQIwCQgvEQAAAKQJDwAADOCAjAoAAIwLAABvDCwAjA0AAJ8JBQIwCQg7MAAAAKkJAAAwCQizLgAAADAFCCQqAAAAMAgE0zEAAACkCQwAAAywgG8KKwCfCQICpAoPAAAM4ICMCwEAjAwAAIwNAQCMDgAAnwoFAjAKCS8RAAAAjAoBADAKCTocAAAAMAcJJCoAAACkCgwAAAywgG8LMgCfCgICpAs0ABLMUMEwCwq5MwAAAKQLNwA21FDBMAsKUTUAAAAwCQokKgAAADAKBDQyAAAA+wwDAE0LDO8DAAAAUgwJAKkNAQCfCwMCMAsEWTgAAAD/DAAAAAAAAIwPAQAcDQAAjA4BAKgN2ACHEAAPpBEMAAAMsIBvEisAnxECAjAPEQASAAAApBIPAAAM4ICMEwEAjBQAAIwVAQCMFgAAnxIFAjASES8RAAAAjBIBADASETocAAAAMAkRJCoAAACkEgwAAAywgG8TIQCfEgICbxM5ADATEmkjAAAApBMmACWQUMEwExL9JAAAAKQTKQAonFDBMBMS5icAAAAwERIkKgAAAKQTDAAADLCAbxQNAJ8TAgKkFDsAAAygg28VPABvFjwAnxQDAjAUE+g9AAAApBQPAAAM4IBNFQQWAgAAAIwWAABNFwQWAgAAAJ8UBAIwFBMvEQAAAKQUDwAADOCAbxU8AIwWAABvFzwAjBgAAJ8UBQIwFBM7MAAAAIwUAQAwFBM6HAAAAG8UPgAwFBOpFAAAAKkUAQAwFBMkPwAAADAREyQqAAAApBQMAAAMsIBvFUAAnxQCAm8VQQAwFRSnQgAAAKQVHgAADNCBjBYBAIwXAQCMGAEAnxUEAjAVFGVDAAAApBUeAAAM0IGMFgEAjBcBAIwYAQCfFQQCMBUUOkQAAACMFQEAMBUUOhwAAACMFQAAMBUUjkUAAACkFQ8AAAzggG8WRgCMFwAAbxhHAIwZAACfFQUCMBUUOzAAAACkFQ8AAAzggG8WSACMFwAAbxhJAIwZAACfFQUCMBUULxEAAAAwExQkKgAAAKQVDAAADLCAbxZKAJ8VAgIwFBUkKgAAADAVFEhLAAAAUhYCAFIXEACfFgICuwEWA1IYFgCkF00AAADARJ8XAgEwFBYkKgAAAP8XAwAAAAAAMBMXnSsAAAAwFheKTgAAADAVF1lKAAAAUhgBAFIZEABSGhcAnxgDAZ40DAUXAAAAUhkMAFIaFwCkGFEAAEDxhJ8YAwFSGAMAUhkVAFIaFgCfGAMB2RgAABIABAASABAAEgAXAE0ZBHYEAAAATRsRFFIAAABSHRgAvBsbx1MAAACfGwMAvBkZ/QgAAACfGQAB2RkBABIABAASABAAEgAXAE0aBHYEAAAATRwR3VQAAABSHhkAvBwcx1MAAACfHAMAvBoa/QgAAACfGgAB2RoCABIABAASABAAEgAXAE0bBHYEAAAAUh8RAOIgVgAwGiBOVQAAALwdC4dXAAAAnx0EALwbG/0IAAAAnxsAAYsNKP8wDAT1WAAAAIIEAgBZAwUEAAAAQAMGAwcDCAMJAwoDAQMLAwMDBAMMBAAMsIADDQMOBAAM4IACMzMzMzMz4z8DDwMQAxEDEgMTAxQDFQQXWFDBAxYEAAyQgQMXAxgDGQQADNCBAxoDGwMcApqZmZmZmQ5AAx0DHgMfBCWQUMEDIAMhBCicUMEDIgMjAjMzMzMzM+s/AyQDJQIzMzMzMzPDPwMmAycDKAMpBBLMUMEDKgMrBDbUUMEDLAIAAAAAAADoPwMtBAAMoIMCAAAAAAAA4D8DLgMvAzADMQcAAIA/AACAvwAAgD8AAAAAAzIDMwM0AzUCmpmZmZmZqT8CNDMzMzMzoz8CzczMzMzM7D8CmpmZmZmZ7T8DNgM3AzgEAADARAM5AzoDOwQAQPGEAzwDPQM+Az8FAVUDQANBAwABAhMHARgAAAAAAAAAAAIAAAIAAAAAAAEAAgABAAAAAAABAAAAAAAAAQAAAAAAAQAAAAAAAAEAAAAAAAEAAAAAAAAUAAAAAQAAAAAAAAAAAQAAAQAAAQAAAAEAAAAAAAAAAAEAAAEAAAAAAAAAAQACAAAAAQAAAQAAAAEAAAABAAIAAAABAAABAAAAAAAAAAABAAABAAABAAIAAAABAAABAAAAAAAAAAABAAAAAAAAAAABAAABAAEAAgAAAAIAAAAAAAAAAAEAAAEAAgAAAAEAAAABAAAAAQABAAIAAAAAAAMAAgABAAAAAQIAAAABAAEAAAAAAAAAAAEAAAEAAwAAAAEAAAEAAAABAAAAAQACAAAAAQAAAAAAAAEAAAAAAAAAAAABAAAAAAAAAAABAAABAAABAAABAAIAAAABAAABAAAAAAAAAAEAAAAAAAAAAQAAAQAAAQAAAAAAAAAAAQAAAAAAAAAAAQACAAAAAQACAAIAAAEAAAAAAQACAAEAAQABAAEAAAABAAAAAAAAAQAAAAYAAAADAAAAAAAAAAAAAAEAAAADAAAAAAAAAAAAAAIAAAADAAAAAAAAAAAAAAC8RgACFAAAAAAEAQAAAAAEeAMAADkCAwAJAQIAggECAAECAAAAAAAAAEAAsAFCARgAAAAAsQAAAAACAQAAAAADTQEA0wAAAACCAQIAAQMnALMBQwEYAAAAtQAAAAAJAgAAAAAXTQIAbwAAAAAwAQIkAQAAAE0DADQCAAAATQIDxgMAAABNBAA0AgAAAE0DBCQBAAAApAQGAAAUQICMBQAATQYCeQcAAACMBwEAjAgAAJ8EBQIwBAMvCAAAAIIAAQAJAxsDIgMoA0QDDgMHBAAUQIADRQMPALcBRgEYAAAAAAEAAAABAAAAAAAAAAAAAAAAAAG4AAAAAAcBAAAAACWkAQIAAAQAgG8CAwCfAQICjAIBADACAToEAAAAbwIFADACAakGAAAApAIIAAAEcICMAwAAjAQUAIwFAACMBhQAnwIFAjACAS8JAAAApAIIAAAEcICMAwAAjAT6/4wFAACMBvr/nwIFAjACATsKAAAATQIAbwsAAAAwAgEkDAAAAE0CAWENAAAAMAIADg4AAACCAAEADwMMAwcEAAQAgANHAxgDSAMSAw4EAARwgAMPAyYDGwMiA0kDSgC8AUsBGAAAAAABAAABAAABAAAAAAAAAAABAAAAAAAAAAABAAAAAgAAAAG9AAAAABQBAAAAAGykAQEAAAAAQJ8BAQJNAwAEAgAAAMoCAwEmAwECMAEABAIAAABNBAD1AwAAAE0FABYEAAAAjAYBAGAFCwAGAAAATQYAFgQAAAAcCgQAWwkKBtgIBQkJBwMIQwUGBzAFABYEAAAAZQADAIwFAQAwBQAWBAAAABwGBADYBQUGTQgAbwcAAABNBwh1CAAAAE0GB3kJAAAATQoAbwcAAABNCQpxCgAAAE0ICXkJAAAAQwcGCIwKAQAcCAQAjAkBAKgIOwCHCwQKTQ0AFgQAAAB4DwoFHBEEAJUSBQUJEBES7A4PECYMDQ6MDgAAYA4JAAwAAADsDgwFgRMOBAUAAABvDwUApA0NAAAwsICfDQMCKw0BAIwNAABNDgudDgAAAKQPEQAAQPCAbxESAAkQEQ2MEQAAbxMSAAkSEw2MEwAAnw8FAjAPDi8TAAAATRALnQ4AAABNDxB1CAAAAE0OD3kJAAAATRILnQ4AAABNERJxCgAAAE0QEXkJAAAAQw8OEGAGCgAPAAAAYA4IAAcAAABNEAA5FAAAAE0RC1kVAAAATRILihYAAACfEAMBiwjF/4IAAQAXA0wEAAAAQANNA0EDBgIAAAAAAADwPwKamZmZmZm5PwMbA04DRQNPA1ADUQQAMLCAAyMDDgMHBABA8IACzczMzMzM7D8DDwMKAzYDOQDGAVIBGAAAAAEAAAEBAAIAAQAAAAABAAAAAAAAAAAAAgAAAgABAAAAAAABAAAAAAAAAQAAAAECAAAAAAAAAAEAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAACAAAAAAABAAAAAAAAAgAAAAEAAAAAAAD0D8cAAAAACAEAAAAAIE0BAPUAAAAAjAQBABwCAQCMAwEAqAIHAIcFAQRNBgWdAQAAALwGBlACAAAAnwYCAYsC+f9NAgBZAwAAALwCAlACAAAAnwICAU0CAG8EAAAAvAICUAIAAACfAgIBTQIAdgUAAAC8AgJQAgAAAJ8CAgHGAgAAMAIAdgUAAACCAAEABgNBAyMDUwMsAxsDCADlAVMBGAAAAQAAAAEBAAAAAP4EAAAAAAEAAAAAAQAAAAABAAAB5gAAAAAIAAABAgA8owAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAoQYAAABNAgMfBwAAAJ8BAgKkAgUAAABAQE0EAKEGAAAATQMEdggAAACfAgICpAMFAAAAQEBNBQBACgAAAE0EBf4JAAAAnwMCAqQFDAAAALBATQQFSA0AAAD/BQQAAAAAADAFBW4OAAAAwAYPABIABQASAAIAEgABABIAAwAwBgXvEAAAAMAGEQDABxIAMAcFjRMAAADABxQAMAcFGRUAAADABxYAMAcFwRcAAADABxgAMAcFJhkAAADABxoAMAcFUBsAAACCBQIAHANUBAAAAEADVQNWA1cEAABAQANYA1kDCANaA1sDXAQAALBAAzcDXQYDAwcGBAYFA0MGBgNGBgcDSwYIA1IGCQNTBwMEBQYHCAkBAAEYAAoAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAACAAEAAQAAAAAAAJ0DAAAEAAAFAAAKAAAfAAAMAQAAAAAKSRleEGX+OjV73TSEgugELq63J3LNok8Rz3TWZvNILXIM5Su1RWuIrg==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.Signal)
local v_u_3 = require(v1.Std.Maid)
local v_u_4 = require(v1.Module.ScrollingFrame)
local _ = workspace.CurrentCamera
local v_u_5 = {}
v_u_5.__index = v_u_5
function v_u_5.new(p6, p7, p8, p9)
	-- upvalues: (copy) v_u_5, (copy) v_u_3, (copy) v_u_2, (copy) v_u_4
	local v10 = v_u_5
	local v_u_11 = setmetatable({}, v10)
	v_u_11.Alpha = 0
	v_u_11.Maid = v_u_3.new()
	v_u_11.ListItem = p6
	v_u_11.ViewportUpdate = p9
	v_u_11.OnMouseEnter = v_u_2.new()
	v_u_11.Maid:GiveTask(v_u_11.OnMouseEnter)
	v_u_11.OnMouseLeave = v_u_2.new()
	v_u_11.Maid:GiveTask(v_u_11.OnMouseLeave)
	v_u_11.OnMouseClick = v_u_2.new()
	v_u_11.Maid:GiveTask(v_u_11.OnMouseClick)
	local v12 = Instance.new("ImageLabel")
	v12.Size = UDim2.new(0.6, 0, 1, 0)
	v12.LayoutOrder = 1
	v12.Image = "rbxassetid://5925879669"
	v12.ScaleType = Enum.ScaleType.Slice
	v12.SliceCenter = Rect.new(30, 30, 100, 100)
	v12.BackgroundTransparency = 1
	v12.BackgroundColor3 = Color3.new(1, 1, 1)
	v_u_11.Container = v12
	local v13 = Instance.new("UIAspectRatioConstraint")
	v13.AspectRatio = 3.825
	v13.AspectType = Enum.AspectType.ScaleWithParentSize
	v13.DominantAxis = Enum.DominantAxis.Width
	v13.Parent = v12
	local v14 = Instance.new("Frame")
	v14.BackgroundTransparency = 1
	v14.Size = UDim2.new(1, 0, 0.85, 0)
	v14.Active = true
	v14.ClipsDescendants = true
	v14.Parent = v12
	local v15 = Instance.new("Frame")
	v15.BackgroundTransparency = 1
	v15.Size = UDim2.new(1, 0, 0.15, 0)
	v15.Position = UDim2.new(0, 0, 0.85, 0)
	v15.ClipsDescendants = false
	v15.Parent = v12
	v_u_11._containerBottom = v15
	local v16 = Instance.new("Frame")
	v16.Size = UDim2.new(1, 0, 1, 0)
	v16.BackgroundTransparency = 1
	v16.Parent = v14
	local v17 = Instance.new("UIListLayout")
	v17.SortOrder = Enum.SortOrder.LayoutOrder
	v17.FillDirection = Enum.FillDirection.Horizontal
	v17.Parent = v16
	v_u_11.UIListLayout = v17
	local v18 = v_u_4.new(v16, true)
	v_u_11.mScrollingFrame = v18
	local v19 = {}
	for v20 = 1, #p6 do
		local v_u_21 = p6[v20]
		local v22 = Instance.new("Frame")
		v22.LayoutOrder = v20
		v22.Size = UDim2.new(1, 0, 1, 0)
		v22.BackgroundTransparency = 1
		v22.Parent = v16
		local v23 = Instance.new("UIAspectRatioConstraint")
		v23.AspectRatio = 0.75
		v23.AspectType = Enum.AspectType.ScaleWithParentSize
		v23.DominantAxis = Enum.DominantAxis.Width
		v23.Parent = v22
		local v24 = Instance.new("ImageLabel")
		v24.AnchorPoint = Vector2.new(0.5, 0.5)
		v24.Size = UDim2.new(v_u_11.Alpha, 0, v_u_11.Alpha)
		v24.Position = UDim2.new(0.5, 0, 0.5, 0)
		v24.BackgroundTransparency = 1
		v24.Image = "rbxassetid://5834299976"
		v24.Selectable = true
		v24.Parent = v22
		local v25 = Instance.new("ViewportFrame")
		v25.LightDirection = Vector3.new(1, -1, 1)
		v25.LightColor = Color3.new(1, 1, 1)
		v25.Ambient = Color3.new(1, 1, 1)
		v25.BackgroundTransparency = 1
		v25.BorderSizePixel = 0
		v25.Position = UDim2.new(0.05, 0, 0.037500000000000006, 0)
		v25.Size = UDim2.new(0.9, 0, 0.925, 0)
		v25.Parent = v24
		local v26 = Instance.new("Camera")
		v26.Parent = v25
		v25.CurrentCamera = v26
		local v27 = p8(v_u_21)
		assert(v27)
		v27.Parent = v25
		local v_u_28 = {
			["Frame"] = v24,
			["Inst"] = v27,
			["Camera"] = v26
		}
		p7(v_u_21, v_u_28)
		table.insert(v19, v_u_28)
		p9(v26, v27)
		v_u_11.Maid:GiveTask(v22.MouseEnter:Connect(function()
			-- upvalues: (copy) v_u_11, (copy) v_u_21, (copy) v_u_28
			v_u_11.OnMouseEnter:Fire(v_u_21, v_u_28)
		end))
		v_u_11.Maid:GiveTask(v22.MouseLeave:Connect(function()
			-- upvalues: (copy) v_u_11, (copy) v_u_21, (copy) v_u_28
			v_u_11.OnMouseLeave:Fire(v_u_21, v_u_28)
		end))
		v_u_11.Maid:GiveTask(v18:BindInput(v22, {
			["OnClick"] = function()
				-- upvalues: (copy) v_u_11, (copy) v_u_21, (copy) v_u_28
				v_u_11.OnMouseClick:Fire(v_u_21, v_u_28)
			end
		}))
	end
	v_u_11.Viewports = v19
	return v_u_11
end
function v_u_5.GetContainerBottom(p29)
	return p29._containerBottom
end
function v_u_5.SetParent(p30, p31)
	p30.Container.Parent = p31
	local v32 = p30.UIListLayout.AbsoluteContentSize
	p30.UIListLayout.Parent.Size = UDim2.new(0, v32.X, 1, 0)
end
function v_u_5.AddBackButton(p33)
	local v34 = Instance.new("ImageButton")
	v34.BackgroundTransparency = 1
	v34.Image = "rbxassetid://4933143781"
	v34.Size = UDim2.new(0, 20, 0, 20)
	v34.Position = UDim2.new(0, -6, 0, -6)
	v34.Parent = p33.Container
	p33.OnMouseClickBack = v34.MouseButton1Down
end
function v_u_5.Update(p35)
	local v36 = tick()
	local v37 = v36 - (p35.LastUpdate or v36)
	p35.LastUpdate = v36
	local v38 = p35.Viewports
	if p35.Alpha < 1 then
		p35.Alpha = p35.Alpha + v37 * (1 / (#v38 * 0.1))
	else
		p35.Alpha = 1
	end
	local v39 = 1 / #v38
	local v40 = p35.Container.AbsolutePosition.X
	local v41 = v40 + p35.Container.AbsoluteSize.X
	for v42 = 1, #v38 do
		local v43 = v38[v42]
		local v44 = p35.Alpha - (v42 - 1) / (#v38 * (v39 + 1))
		local v45
		if v44 > 0 then
			local v46 = v44 / v39
			v45 = math.min(v46, 1) or 0
		else
			v45 = 0
		end
		v43.Frame.Size = UDim2.new(0.9 * v45, 0, 0.9 * v45, 0)
		local v47 = v43.Frame.AbsolutePosition.X
		if v40 < v47 + v43.Frame.AbsoluteSize.X and v47 < v41 then
			p35.ViewportUpdate(v43.Camera, v43.Inst)
		end
	end
end
function v_u_5.Destroy(p48)
	local v49 = p48.Viewports
	for v50 = 1, #v49 do
		v49[v50].Frame:Destroy()
	end
	p48.mScrollingFrame:Destroy()
	p48.Container:Destroy()
	p48.Maid:Destroy()
	p48.Maid = nil
end
return v_u_5
