-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMfBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplFElOVEVSQUNUX1JFTU9URV9OQU1FE0lURU1fTkFNRV9BVFRSX05BTUUJV0hJVEVMSVNUDkludGVyYWN0UmVtb3RlCEl0ZW1OYW1lBVN3b3JkCkJpbm9jdWxhcnMKRmxhc2hsaWdodAZHbGlkZXIEQUs0NxJGb3JjZWZpZWxkTGF1bmNoZXIGU25pcGVyCUZsaW50bG9jawVSaWZsZQ5Sb2NrZXRMYXVuY2hlcgdTaG90Z3VuA1V6aQxQbGFzbWFQaXN0b2wNUGxhc21hU2hvdGd1bghSZXZvbHZlcgZQaXN0b2wMU21va2VHcmVuYWRlAkM0B0dyZW5hZGUAAQYAAAECAFajAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CAxgHAAAAnwECAk0CAQAIAAAA4gMMAG8EDQAwBAOtCQAAAG8EDgAwBAMDCgAAAP8EBgAAAAAAqQUBADAFBKUPAAAAqQUBADAFBBwQAAAAqQUBADAFBIYRAAAAqQUBADAFBGMSAAAAqQUBADAFBGUTAAAAqQUBADAFBC4UAAAAqQUBADAFBOYVAAAAqQUBADAFBE8WAAAAqQUBADAFBK0XAAAAqQUBADAFBNMYAAAAqQUBADAFBOEZAAAAqQUBADAFBHgaAAAAqQUBADAFBHQbAAAAqQUBADAFBGMcAAAAqQUBADAFBM4dAAAAqQUBADAFBJceAAAAqQUBADAFBJcfAAAAqQUBADAFBFYgAAAAqQUBADAFBE8hAAAAMAQDtwsAAACfAgIAggIAACIDAQQAAABAAwIDAwMEBAAAQEADBQMGAwcDCAMJAwoFAwkKCwMLAwwDDQMOAw8DEAMRAxIDEwMUAxUDFgMXAxgDGQMaAxsDHAMdAx4DHwABAAEYAAEAAAAAAAEAAAAAAAABAAABAAABAAACAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAO0A/AABAAAAAADFhiKWtGYlLfdCSAIHNki8RqDUS2Nu8tJh+zRlYh4BKhSjGHotuPMJ

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v2 = {
	["INTERACT_REMOTE_NAME"] = "InteractRemote",
	["ITEM_NAME_ATTR_NAME"] = "ItemName",
	["WHITELIST"] = {
		["Sword"] = true,
		["Binoculars"] = true,
		["Flashlight"] = true,
		["Glider"] = true,
		["AK47"] = true,
		["ForcefieldLauncher"] = true,
		["Sniper"] = true,
		["Flintlock"] = true,
		["Rifle"] = true,
		["RocketLauncher"] = true,
		["Shotgun"] = true,
		["Uzi"] = true,
		["PlasmaPistol"] = true,
		["PlasmaShotgun"] = true,
		["Revolver"] = true,
		["Pistol"] = true,
		["SmokeGrenade"] = true,
		["C4"] = true,
		["Grenade"] = true
	}
}
return require(v1.Std.TableUtils).requireValidIndexAndFreeze(v2)
