-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMUBGluaXQNY3JlYXRlRWxlbWVudARzaXplBVVEaW0yA25ldwZyZW5kZXILd2lsbFVubW91bnQHdW5tb3VudAlDb21wb25lbnQDQXBwBmV4dGVuZAdyZXF1aXJlCVRyYWRlQ2hhdAZzY3JpcHQGUGFyZW50BW1vdW50BGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQVSb2FjdAAGAQEAAAAAAYIAAQAAAAgBARgACAAAAAAJAQIAAAAQ+wIAAE0BAsoAAAAA+wIBAOIDAgCkBAUAABAwgIwFAQCMBgAAjAcBAIwIAACfBAUCMAQDDwEAAACfAQMAggEAAAYDAgMDBQEBAwQDBQQAEDCAAAkGARgAAAAAAAEAAAAAAAAAAP8ACgAAAAABAQAAAAABggABAAAADgcBGAAOAAAAAAIAAgAAAAb7AQAATQABEgAAAAD7AQEAnwACAYIAAQABAwgAEQABGAAAAAAAARIAAAAABgEBAAAAKfsCAABNAQKIAAAAAG8DAQC8AQGcAgAAAJ8BAwKkAgQAAAAwQKQFBwAAAGBATQQFJAgAAABNAwQKBQAAAJ8CAgLAAwkAMAMBEwoAAADZAwEAEgIAABIAAgAwAwGACwAAAMADDAAwAwE0DQAAAPsEAABNAwTkDgAAAPsFAABNBAXKDwAAAFIFAQCfBAICUgUAAJ8DAwLZBAMAEgIAABIAAwCCBAIAEAMJAwoDCwMMBAAAMEADDQMOBAAAYEADDwYAAwEDBgYCAwcDEAMCBAABAgMFAAEYAAAAAAAAAAEAAAAAAAAAAAEAAAEAAAAABQAAAgAAAAAAAAAAAAEAAAAGAAAAAAMAAAECAA+jAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAgAhBgAAAJ8BAgLAAgcAEgABAIICAgAIAxEEAAAAQAMSAxMDDAQAAEBAAxQGBAEEAQABGAABAAAAAAABAAAAAAIAAAEAAAAABa35Nw+5AWYknz1dmy34J/CS2gL8eYY0B5hWYciNeXcAzEhTdhQ6Flo=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Roact)
return function(p3)
	-- upvalues: (copy) v_u_2
	local v4 = v_u_2.Component:extend("App")
	local v_u_5 = require(script.Parent.TradeChat)
	function v4.init(_) end
	function v4.render(_)
		-- upvalues: (ref) v_u_2, (copy) v_u_5
		return v_u_2.createElement(v_u_5, {
			["size"] = UDim2.new(1, 0, 1, 0)
		})
	end
	function v4.willUnmount(_) end
	local v_u_6 = v_u_2.mount(v_u_2.createElement(v4), p3)
	return function()
		-- upvalues: (ref) v_u_2, (copy) v_u_6
		v_u_2.unmount(v_u_6)
	end
end
