-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgOPAQtMb2NhbFBsYXllcglQbGF5ZXJHdWkLT2JqZWN0TG9jYWwGVm9sdW1lCHBsYXlUaWNrBHR5cGUFdmFsdWUbc2V0VHJhZGVJbnZlbnRvcnlTZWFyY2hUZXh0AAhkaXNwYXRjaA5zZWxlY3RlZFBsYXllchJzZXRJbnZlbnRvcnlQbGF5ZXIecmVzZXRJbnZlbnRvcnlVc2VyRWRpdGVkVmFsdWVzBXByb3BzEHNldEludmVudG9yeU9wZW4LdHJhZGVBY3RpdmUQaW52ZW50b3J5UGxheWVycwVzdGF0ZQ5pbnZlbnRvcnlJdGVtcwZpcGFpcnMIdHJhZGVyTWUKb2ZmZXJJdGVtcwJpZBRhZGRUcmFkZXJNZU9mZmVySXRlbRdyZW1vdmVUcmFkZXJNZU9mZmVySXRlbQ5fdXBkYXRlTXlPZmZlch5yZW1vdmVUcmFkZXJNZU9mZmVySXRlbUJ5SW5kZXgIY2F0ZWdvcnkIc2V0U3RhdGUMb25DbGlja1JlYWR5Dm9uQ2xpY2tVbnJlYWR5G0FDQ0VQVF9PRkZFUklOR19SRU1PVEVfTkFNRQ5GaW5kRmlyc3RDaGlsZApGaXJlU2VydmVyHERFQ0xJTkVfT0ZGRVJJTkdfUkVNT1RFX05BTUUZRVhJVF9PRkZFUklOR19SRU1PVEVfTkFNRQNuZXcKYWN0aXZlTWFpZA1nZXRDYXRlZ29yaWVzCmNhdGVnb3JpZXMaX2dldEZpbHRlcmVkSW52ZW50b3J5SXRlbXMUb25DbGlja0V4aXRJbnZlbnRvcnkPcHJvbXB0SW52ZW50b3J5FG9uQ2xpY2tJbnZlbnRvcnlJdGVtD29uQ2xpY2tDYXRlZ29yeQ1vbkNsaWNrQWNjZXB0Dm9uQ2xpY2tEZWNsaW5lC29uQ2xpY2tFeGl0DW9uQ2FyZEZsaXBwZWQWb25DbGlja0ludmVudG9yeVBsYXllcgRpbml0BXJlYWR5Dl9nZXRNZU9mZmVySWRzG1VQREFURV9PRkZFUklOR19SRU1PVEVfTkFNRRNtaXNzaW5nIGlkIGl0ZW1Qcm9wBmFzc2VydANtYXAYdHJhZGVJbnZlbnRvcnlTZWFyY2hUZXh0DnRyYWRlSW52ZW50b3J5F2hhc0Rlc2lyZWRWYWx1ZXNTaGFsbG93BW1hdGNoBnN0cmluZwRmaW5kBXRpdGxlBWxvd2VyBXRhYmxlBmluc2VydARzb3J0EGdldFRyYWRlU29ydEZ1bmMJdHJhZGVTb3J0BlVzZXJJZAtEaXNwbGF5TmFtZQphbGxQbGF5ZXJzCnRyYWRlclRoZW0GdXNlcklkHF9nZXRGaWx0ZXJlZEludmVudG9yeVBsYXllcnMSdHJhZGVJbnZlbnRvcnlPcGVuCHNlbGVjdGVkBHNpemUIcG9zaXRpb24LYW5jaG9yUG9pbnQFaXRlbXMMaXRlbU1ldGFkYXRhC29uQ2xpY2tJdGVtDG9uU2VsZWN0U29ydAZzb3J0SWQIc2hvd0NoYXQRdHJhZGVDaGF0TWVzc2FnZXMJdHJhZGVJbmZvA21zZxBkZWJ1Z1Byb2JhYmlsaXR5HlAoeW91IGJldHRlcikgW2RlYnVnXSA9ICUuMWYlJQZmb3JtYXQLaW5mb01lc3NhZ2UGcmVuZGVyCkRvQ2xlYW5pbmcOcmVzZXRUcmFkZUluZm8IcHVzaEhpZGUIR2l2ZVRhc2sJZGlkVXBkYXRlDXRyYWRlQ2F0ZWdvcnkOdXBkYXRlVHJhZGVyTWUEaXRlbQVpbmRleAZOZXdlc3QHUG9wdWxhcgxBbHBoYWJldGljYWwOc2V0VHJhZGVTb3J0SWQVc2V0VHJhZGVJbnZlbnRvcnlPcGVuBGluZm8Mc2V0VHJhZGVJbmZvBGdhbWUHUGxheWVycwpHZXRTZXJ2aWNlEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUDU3RkBUF1ZGlvBE1haWQKVGFibGVVdGlscwVSb2FjdApSb2FjdFJvZHV4DWNyZWF0ZUVsZW1lbnQFVHJhZGUKVHJhZGVVdGlscwtUcmFkZUNvbnN0cwxBY3Rpb25CdXR0b24TQWN0aW9uQnV0dG9uU2VydmljZQZHYXJhZ2UJU29ydFV0aWxzCEVudW1Tb3J0BnNjcmlwdAZQYXJlbnQOVHJhZGVJbnZlbnRvcnkNVHJhZGVPZmZlcmluZwNBcHAFc3RvcmUNUHVyZUNvbXBvbmVudAZleHRlbmQFVURpbTIHVmVjdG9yMgxkZWZhdWx0UHJvcHMHY29ubmVjdAAiBQACAAAAFfsCAABNAQIxAAAAAE0AAZkBAAAADgAOAPsBAQBNAAHRAgAAAPsDAABNAgMxAAAAAE0BApkBAAAAbwIDAOIDBQBvBAYAMAQDSwQAAACfAAQBggABAAcDAQMCAwMCAABgMp++9kEDBAUBBAIzMzMzMzPDPwAUBQEYAAAAAAAAAQAAAAAAAAAAAAAAAAACFQAAAAAFAAIAAAAZ+wAAAOICAgBvAwMAMAMCcQAAAABvAwQAMAMCzAEAAAC8AABMBQAAAJ8AAwH7AAAA4gIHAG8DCAAwAwJxAAAAAPsEAQBNAwQxCQAAADADAksGAAAAvAAATAUAAACfAAMBggABAAoDBgMHBQIAAQMIAwkDCgMLBQIABgMMAwEAIA0BGAAAAQAAAQAA/gAABAABAAABAAAAAP4AAAQhAAAAAAMAAgAAAAr7AAAAnwABAfsCAQBNAQIHAAAAAE0AAX8BAAAAqQEAAJ8AAgGCAAEAAgMOAw8AMgABGAAAAQAAAAAAAAEzAAAAAAUAAwAAABz7AgAATQECMQAAAABNAAGZAQAAAA4ADgD7AQEATQAB0QIAAAD7AwAATQIDMQAAAABNAQKZAQAAAG8CAwDiAwUAbwQGADAEA0sEAAAAnwAEAfsCAgBNAQIHBwAAAE0AAX8IAAAAqQEBAJ8AAgGCAAEACQMBAwIDAwIAAGAyn772QQMEBQEEAjMzMzMzM8M/Aw4DDwA2AAEYAAAAAAAAAQAAAAAAAAAAAAAAAAAiAAAAAAAAARUAAAAACgEDAAAAYPsDAABNAgMHAAAAAE0BAh4BAAAAKwEBAIIAAQD7BAAATQMEBwAAAABNAgP7AgAAAE0BAksDAAAA+wMBAE0CAzEEAAAA8QECAAIAAACCAAEA+wQAAE0DBBgFAAAATQIDawYAAACHAQIAqQIAAKQDCAAAAHBA+wgAAE0HCAcAAAAATQYHRAkAAABNBAZACgAAAJ8DAgRRAwgATQgH9AsAAABNCQH0CwAAAJoIAwAJAAAAqQIBAGUAAgBuA/f/AgAAgCsCCAD7BQAATQQFBwAAAABNAwTYDAAAAFIEAQCfAwIBZQAHAPsFAABNBAUHAAAAAE0DBG4NAAAAUgQBAJ8DAgH7BQAATQQFBwAAAABNAwR/DgAAAKkEAACfAwIB+wMAALwDA9APAAAAnwMCAfsFAQBNBAUxBAAAAE0DBJkQAAAADgMOAPsEAgBNAwTREQAAAPsGAQBNBQYxBAAAAE0EBZkQAAAAbwUSAOIGFABvBxUAMAcGSxMAAACfAwQBggABABYDDgMQAxEDCwMBAxIDEwMUBAAAcEADFQMWAxcDGAMZAw8DGgMCAwMCAABgMp++9kEDBAUBEwIzMzMzMzPDPwA6AAEYJgAAAAAAAQIAAAAAAAAAAAAAAAECAAAAAAABAQAAAAAAAAAAAAABAAAAAAABAf0ABgEAAAAAAAAAAgAAAAAAAAIAAAAAAAABAAAAxgAAAAAAAQAAAAAAAAAAAAAAAAA7FQAAAAAEAQEAAAAN+wMAAE0CAwcAAAAATQECEgEAAABSAgAAnwECAfsBAACpAwAAvAEB0AIAAACfAQMBggABAAMDDgMbAxoAUgABGAAAAAAAAAABAAAAAAFTAAAAAAYBAwAAADD7AwAATQIDMQAAAABNAQKZAQAAAA4BDgD7AgEATQEC0QIAAAD7BAAATQMEMQAAAABNAgOZAQAAAG8DAwDiBAUAbwUGADAFBEsEAAAAnwEEAfsBAgDiAwgAMAADawcAAAC8AQEqCQAAAJ8BAwH7AwAATQIDMQAAAABNAQKZAQAAAA4BDgD7AgEATQEC0QIAAAD7BAAATQMEMQAAAABNAgOZAQAAAG8DAwDiBAUAbwUKADAFBEsEAAAAnwEEAYIAAQALAwEDAgMDAgAAYDKfvvZBAwQFAQQCAAAAAAAA0D8DHAUBBwMdAjMzMzMzM8M/AFYAARhCAAAAAAABAAAAAAAAAAAAAAAAAAIAAQD/AAC7AAAAAAABAAAAAAAAAAAAAAAAAEgVAAAAAAUAAwAAACD7AgAATQECBwAAAABNAAFqAQAAAJ8AAQH7AAAAqQIBALwAANACAAAAnwADAfsCAQBNAQIxAwAAAE0AAZkEAAAADgAOAPsBAgBNAAHRBQAAAPsDAQBNAgMxAwAAAE0BApkEAAAAbwIGAOIDCABvBAkAMAQDSwcAAACfAAQBggABAAoDDgMeAxoDAQMCAwMCAABgMp++9kEDBAUBBwIzMzMzMzPDPwBgAAEYTAAAAAAAAQAAAACzAAAAAAABAAAAAAAAAAAAAAAAAE4VAAAAAAUAAwAAACD7AgAATQECBwAAAABNAAH5AQAAAJ8AAQH7AAAAqQIAALwAANACAAAAnwADAfsCAQBNAQIxAwAAAE0AAZkEAAAADgAOAPsBAgBNAAHRBQAAAPsDAQBNAgMxAwAAAE0BApkEAAAAbwIGAOIDCABvBAkAMAQDSwcAAACfAAQBggABAAoDDgMfAxoDAQMCAwMCAABgMp++9kEDBAUBBwIzMzMzMzPDPwBlAAEYUQAAAAAAAQAAAACuAAAAAAABAAAAAAAAAAAAAAAAAFMVAAAAAAYABAAAAB/7AAAA+wMBAE0CA/QAAAAAvAAAAwEAAACfAAMCvAEAawIAAACfAQIB+wMCAE0CAzEDAAAATQECmQQAAAAOAQ4A+wIDAE0BAtEFAAAA+wQCAE0DBDEDAAAATQIDmQQAAABvAwYA4gQIAG8FCQAwBQRLBwAAAJ8BBAGCAAEACgMgAyEDIgMBAwIDAwIAAGAyn772QQMEBQEHAjMzMzMzM8M/AGoAARhWAAAAAAAAAQAAqQAAAAAAAQAAAAAAAAAAAAAAAABZFQAAAAAGAAQAAAAf+wAAAPsDAQBNAgM/AAAAALwAAAMBAAAAnwADArwBAGsCAAAAnwECAfsDAgBNAgMxAwAAAE0BApkEAAAADgEOAPsCAwBNAQLRBQAAAPsEAgBNAwQxAwAAAE0CA5kEAAAAbwMGAOIECABvBQkAMAUESwcAAACfAQQBggABAAoDIwMhAyIDAQMCAwMCAABgMp++9kEDBAUBBwIzMzMzMzPDPwBwAAEYXAAAAAAAAAEAAKMAAAAAAAEAAAAAAAAAAAAAAAAAXxUAAAAABgAEAAAAH/sAAAD7AwEATQIDmwAAAAC8AAADAQAAAJ8AAwK8AQBrAgAAAJ8BAgH7AwIATQIDMQMAAABNAQKZBAAAAA4BDgD7AgMATQEC0QUAAAD7BAIATQMEMQMAAABNAgOZBAAAAG8DBgDiBAgAbwUJADAFBEsHAAAAnwEEAYIAAQAKAyQDIQMiAwEDAgMDAgAAYDKfvvZBAwQFAQcCMzMzMzMzwz8AdgABGGIAAAAAAAABAACdAAAAAAABAAAAAAAAAAAAAAAAAGUVAAAAAAUAAgAAABX7AgAATQECMQAAAABNAAGZAQAAAA4ADgD7AQEATQAB0QIAAAD7AwAATQIDMQAAAABNAQKZAQAAAG8CAwDiAwUAbwQGADAEA0sEAAAAnwAEAYIAAQAHAwEDAgMDAgAAiJ0IVwJCAwQFAQQCMzMzMzMzwz8AfAABGAAAAAAAAAEAAAAAAAAAAAAAAAAAAn0AAAAABgEDAAAAH/sBAADiAwIAbwQDADAEA3EAAAAAMAADSwEAAAC8AQFMBAAAAJ8BAwH7AwEATQIDMQUAAABNAQKZBgAAAA4BDgD7AgIATQEC0QcAAAD7BAEATQMEMQUAAABNAgOZBgAAAG8DCADiBAoAbwULADAFBEsJAAAAnwEEAYIAAQAMAwYDCwUCAAEDDAMKAwEDAgMDAgAAYDKfvvZBAwQFAQkCMzMzMzMzwz8AgQEAARhtAAEAAAEA/gAAkwAAAAAAAQAAAAAAAAAAAAAAAABxFQAAAAAGAQgAAABi+wIAAE0BAu8AAAAAnwEBAjABAP0BAAAA+wIBAE0BAg4CAAAAnwEBAjABAOADAAAA4gMGALwEAPQHAAAAnwQCAjAEA2sEAAAATQUA4AMAAAATBAUAMAQDawUAAAC8AQAqCAAAAJ8BAwHZAQAAEgICABIAAAAwAQCGCQAAANkBAQASAgMAEgIEABIAAAAwAQDKCgAAANkBAgASAAAAEgIDABICBAAwAQBSCwAAANkBAwASAAAAMAEAEgwAAADZAQQAEgIDABICBAASAAAAMAEAsw0AAADZAQUAEgAAABICAwASAgQAMAEAag4AAADZAQYAEgAAABICAwASAgQAMAEA+Q8AAADAARAAEgIFABICBgASAgMAEgIEADABAIgRAAAAwAESABICBQASAgYAEgIDABICBAAwAQCHEwAAAMABFAASAgUAEgIGABICAwASAgQAMAEAjhUAAADAARYAEgIDABICBAAwAQBmFwAAAMABGAASAgcAEgIDABICBAAwAQBLGQAAAIIAAQAaAyUDJgMnAygDEwMcBQIEBQMpAx0DKgMrAywDGwMtAx4DHwYJAy4GCgMvBgsDMAYMAzEGDQMyDAIDBAUGBwgJCgsMDSozARgAAAAAAAACAAAAAAABAQAAAAABAAAAAP4AAAQAAAAABAAAAAAABAAAAAAAGAAAAAQAAAAAAAoAAAAAAAUAAAAAAAUAAAAAAAAGAAAAAAAABgAAAAAAAAYAAAAABQAAAAAABysAAAAACAICAAAAGUcBBwAAAACATQMABwAAAABNAgNEAQAAAE0BAs8CAAAAvAIAXAMAAACfAgIC+wMAAPsGAQBNBQZfBAAAALwDAwMFAAAAnwMDAg4DBQBSBgEAUgcCALwEA2sGAAAAnwQEAYIAAQAHAw4DFQM0AzUDNgMhAyIAiQEaARgAAAEAAAAAAAIAAAEAAAAAAAABAQAAAAACigAAAAAEAQAAAAAJTQIA9AAAAACBAQIEAQAAAG8DAQCkAQMAAAAgQJ8BAwKCAQIABAMXAzcDOAQAACBAAJQBAAEYAAAAAAAAAAABlQAAAAAFAQEAAAAM+wIAAE0BApAAAAAATQQABwEAAABNAwREAgAAAE0CA0ADAAAAwAMEAJ8BAwKCAQIABQM5Aw4DFQMWBhABEJMBNQEYAAAAAAAAAAAAAAAElAAAAAANAQIAAABB/wEAAAAAAABNAwAHAAAAAE0CA5ABAAAApAMDAAAAIEBNBgAHAAAAAE0EBuEEAAAAnwMCBFEDJAD7CQAATQgJswUAAABSCQcATQwAGAYAAABNCwxrBwAAAE0KC+cIAAAAnwgDAg4IGAAOAhAA8AIPAAkAAACkCAwAACyggE0JB5oNAAAAvAkJ7w4AAACfCQICvAoC7w4AAACfCgICxgsAAKkMAQCfCAUCDggHAJ40AQUHAAAAUgkBAFIKBwCkCBEAAEDwgJ8IAwFuA9v/AgAAgKQDEwAASPCAUgQBAPsGAQBNBQYJFAAAAE0HAAcAAAAATQYHQhUAAACfBQIAnwMAAYIBAgAWAw4DOgMUBAAAIEADOwM8AxIDHAM9AwkDPgM/BAAsoIADQANBA0IDQwQAQPCAA0QEAEjwgANFA0YAmgEpARgAAAEAAAACAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAMAAAAAAAAAAAAAAAAAAgAAAAAAAPkACwAAAAAAAAAAAAAAAZsAAAAABgIBAAAAH00CAOYAAAAA+wUAAE0EBTEBAAAATQME5gAAAACaAgMAAwAAAKkCAQCCAgIATQIB5gAAAAD7BQAATQQFMQEAAABNAwTmAAAAAJoCAwADAAAAqQIAAIICAgBNAwBXAgAAAE0EAVcCAAAAtwMCAAQAAACpAgABqQIBAIICAgADA0cDAQNIAK0BAAEYAAAAAAAAAAAAAQACAAAAAAAAAAABAAMAAAAAAAAAAK8AAAAACwEBAAAASaQBAgAABACATQQABwMAAABNAwT7BAAAAE0CA3QFAAAAwAMGABICAACfAQMBTQIABwMAAABNAQIeBwAAACsBBQBNAgAHAwAAAE0BAvsEAAAAggECAOIBCAD/AgAAAAAAADACAXQFAAAATQYABwMAAABNBQb7BAAAAE0CBXQFAAAAxgMAAMYEAABkAhsATQcG5gkAAABNCgAHAwAAAE0JCi0KAAAATQgJhgsAAADxBwoACAAAAE0HBuYJAAAA+woAAE0JCjEMAAAATQgJ5gkAAACaBwkACAAAAE0IAXQFAAAAnjQIBAYAAABSCQYApAcOAAA0AICfBwMBbgLk/wIAAABNBAAHAwAAAE0DBPsEAAAATQIDSw8AAAAwAgFLDwAAAIIBAgAQA0IDRAQABACAAw4DEQNJBhMDEAUBBQNHA0oDSwMBA0MEADQAgAMLAROsAUwBGAAAAAAAAAAAAAAACwAAAAABAAAAAAIAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAA/gAFAAAAAAAAAAGtAAAAAAwBAwAACAAAAQMEtQECiwL/AQAAAAAAAKQCAQAAAABATQYABwIAAABNBQZEAwAAAE0DBUAEAAAAnwICBFECBABNBwb0BQAAAKkIAQBqCAEHbgL7/wIAAIBNAwAHAgAAAE0CA64GAAAADgJ2AP8CAAAAAAAApAMBAAAAAEBNBgAYBwAAAE0EBmsIAAAAnwMCBFEDEAD/CAEAAAAAAE0KB/QFAAAAhwkBCg4JAwCpCQEAMAkITQkAAACeNAIFCAAAAFIKAgBSCwgApAkMAAAsoICfCQMBbgPv/wIAAID7AwAA+wQBAOIFHgBNBwAHAgAAAE0GBw8NAAAAMAYFDw0AAABNBwAHAgAAAE0GB9sOAAAAMAYF2w4AAABNBwAHAgAAAE0GBwgPAAAAMAYFCA8AAABNBgDgEAAAADAGBeAQAAAATQcAGAcAAABNBgdrEQAAADAGBWsRAAAATQcAGAcAAABNBgdrCAAAADAGBRgSAAAAMAIFhxMAAABNBgCGHwAAADAGBY4UAAAATQYAUiAAAAAwBgVaFQAAAE0GALMWAAAAMAYFsxYAAABNBgBmFwAAADAGBWYXAAAATQcABwIAAABNBgeAGAAAADAGBYAYAAAAvAYADCEAAACfBgICMAYF+xkAAABNBgBLGgAAADAGBUsaAAAATQcABwIAAABNBgdCIgAAADAGBaYbAAAATQcABwIAAABNBgceIwAAADAGBVccAAAATQcABwIAAABNBgfTHQAAADAGBdMdAAAAnwMDAIIDAABNAwAHAgAAAE0CAx4jAAAADgJ4AG8CJABNBAAHAgAAAE0DBJMlAAAADgMhAE0FAAcCAAAATQQFkyUAAABNAwQFJgAAAA4DBwBNBAAHAgAAAE0DBJMlAAAATQIDBSYAAABlABMATQUABwIAAABNBAWTJQAAAE0DBMcnAAAADgMMAE0FAAcCAAAATQQFkyUAAABNAwTHJwAAAG8EKABbBgMpvAQEjSoAAACfBAMCUgIEAPsDAAD7BAIA4gUzAE0HAAcCAAAATQYHDw0AAAAwBgUPDQAAAE0HAAcCAAAATQYH2w4AAAAwBgXbDgAAAE0HAAcCAAAATQYHCA8AAAAwBgUIDwAAAE0HAAcCAAAATQYHRAMAAAAwBgVEAwAAAE0HAAcCAAAATQYHLSsAAAAwBgUtKwAAAE0GAMosAAAAMAYFyiwAAABNBgASNAAAADAGBW4tAAAATQYAai4AAAAwBgVqLgAAAE0GAPkvAAAAMAYF+S8AAABNBgCIMAAAADAGBYgwAAAATQYAhzEAAAAwBgWHMQAAAE0GAI4UAAAAMAYFjhQAAABNBgBmFwAAADAGBWYXAAAAMAIFSzIAAABNBwAHAgAAAE0GBx4jAAAAMAYFVxwAAABNBwAHAgAAAE0GB9MdAAAAMAYF0x0AAACfAwMAggMAAIIAAQA1AxQEAAAAQAMOAxUDFgMXA00DEgMTA04DQgNDBAAsoIADTwNQA1EDKAMcA1IDUwMwA1QDLQMxA1UDEQMyA1YDVwNYBRENDg8QERITFBUWFxgZGhscHQMqAywDTANGAxADCQNZA1oDWwNcAgAAAAAAAFlAA10DSgMrAxkDHgMfAy4DLwNeBRANDg8DKywtLi8wMRQXMhwdAxsAxAFfARgAAAEAAAAAAAAAAAABAAAA/wADAAAAAAEAAQAAAAAAAAABAAEAAAABAAACAAAAAAAA+wAIAAABAAAAAAABAAAAAAABAAAAAAACAAAAAQAAAAAAAQAAAAAAAQABAAAAAQAAAAEAAAABAAAAAQAAAAAAAQAAAAABAAAAAQAAAAAAAQAAAAAAAQAAAAAA7gAUAAAAAAEBAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAEAAAAAAAQAAAEAAAAAAAEAAAAAAAEAAAAAAAIAAAAAAAEAAAAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQABAAAAAAABAAAAAADvABTFAAAAAAgDAgAAAG1NBAAYAAAAAE0DBGsBAAAATQQCawEAAACaAxkABAAAAE0EAAcCAAAATQME4QMAAABNBAHhAwAAAJoDEQAEAAAATQQABwIAAABNAwSQBAAAAE0EAZAEAAAAmgMJAAQAAABNBAAHAgAAAE0DBEIFAAAATQQBQgUAAADxAwoABAAAAOIFBwC8BgD0CAAAAJ8GAgIwBgVrBgAAALwDACoJAAAAnwMDAU0EAAcCAAAATQMEHgoAAABNBAEeCgAAAPEDLQAEAAAATQQABwIAAABNAwQeCgAAACsDGQBNAwD9CwAAALwDA1EMAAAAnwMCAeIFDQBNBwDgDgAAABMGBwAwBgVrAQAAALwDACoJAAAAnwMDAU0EAAcCAAAATQMEfw8AAACpBAAAnwMCAU0EAAcCAAAATQMESxAAAACfAwEBTQQABwIAAABNAwQeCgAAAA4DCQBNAwD9CwAAAPsGAABNBQaPEQAAAJ8FAQC8AwP9EgAAAJ8DAAFNBAAHAgAAAE0DBK4TAAAADgMKAE0EAAcCAAAATQMErhMAAABNBAGuEwAAAPEDAwAEAAAA+wMBAJ8DAQGCAAEAFAMSAxwDDgM7AzoDRgMTBQEGAykDHQMQAyYDYAUBAQMoAw8DYQNiA2MDTQCHAmQBGAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAgEAAAAA/wAABAAAAAAAAAADAAAAAAEAAAAAAQEAAAAA/wAAAwAAAAAAAQAAAAACAAAAAAEAAAAAAAAAAAQAAAAAAAAAAAAAAAABAAIJAQAAAAQCAAAAAC7iAgsATQMARAAAAAAwAwJEAAAAAE0DAC0BAAAAMAMCLQEAAABNAwDhAgAAADADAuECAAAATQMAkAMAAAAwAwKQAwAAAE0DAOgEAAAAMAMC6AQAAABNAwAeBQAAADADAh4FAAAATQMAQgYAAAAwAwJCBgAAAE0DAK4HAAAAMAMCrgcAAABNAwCTCAAAADADApMIAAAATQMA+wkAAAAwAwL7CQAAAE0DANMKAAAAMAMC0woAAACCAgIADAMVA0oDOwM6A2UDEANGA00DWQMRA1gFCwABAgMEBQYHCAkKAKYCAAEYAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAACcBAAAABAEBAAAACvsBAADiAgIAbwMDADADAnEAAAAAqQMBADADAs8BAAAAnwECAYIAAQAEAwYDNAUCAAEDZgC2Ah4BGAAAAQAAAQAA/gQ3AQAAAAMAAQAAAAr7AAAA4gECAG8CAwAwAgFxAAAAAKkCAAAwAgHPAQAAAJ8AAgGCAAEABAMGAzQFAgABA2YAvAIfARgAAAEAAAEAAP4EPQEAAAAEAQEAAAAJ+wEAAOICAgBvAwMAMAMCcQAAAAAwAALqAQAAAJ8BAgGCAAEABAMGA2cFAgABAxgAwgIYARgAAAEAAAEA/gRDAQAAAAQBAQAAAAn7AQAA4gICAG8DAwAwAwJxAAAAADAAAuoBAAAAnwECAYIAAQAEAwYDZwUCAAEDGQDIAhkBGAAAAQAAAQD+BEkBAAAABAEBAAAACfsBAADiAgIAbwMDADADAnEAAAAAMAACAgEAAACfAQIBggABAAQDBgNoBQIAAQMbAM4CGwEYAAABAAABAP4ETwEAAAAGAQQAAAA4+wMAAE0CAzEAAAAATQECmQEAAAAOAQ4A+wIBAE0BAtECAAAA+wQAAE0DBDEAAAAATQIDmQEAAABvAwMA4gQFAG8FBgAwBQRLBAAAAJ8BBAHGAQAA+wMCAE0CA3cHAAAAmgAFAAIAAAD7AgIATQECSggAAABlABEA+wMCAE0CA0oIAAAAmgAFAAIAAAD7AgIATQECGwkAAABlAAgA+wMCAE0CAxsJAAAAmgAEAAIAAAD7AgIATQECdwcAAAD7AgMA4gMMAG8EDQAwBANxCgAAADABA6YLAAAAnwICAYIAAQAOAwEDAgMDAgAAYDKfvvZBAwQFAQQCMzMzMzMzwz8DaQNqA2sDBgNWBQIKCwNsANQCVQECAAAAAAAAAQD/AAAAAAAAAAAAAAAAAQAA/wABAP8AAQD/AAAB/wAAAf8AAAAAAAAC/gEAAAEA/gQVAAAAAAAAAAEAAAAAAAAAAAAAAEEBAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAACAAAAAAAAAAAEAQEAAAAJ+wEAAOICAgBvAwMAMAMCcQAAAAAwAALMAQAAAJ8BAgGCAAEABAMGAwcFAgABA20A5AIPARgAAAEAAAEA/gRlAQAAAAMAAQAAAAr7AAAA4gECAG8CAwAwAgFxAAAAAMYCAAAwAgGaAQAAAJ8AAgGCAAEABAMGA24FAgABA28A6gJhARgAAAEAAAEAAP4EawEAAAADAQMAAAAl4gEIANkCAAASAAAAMAIBagAAAADZAgEAEgAAADACAfkBAAAA2QICABIAAAAwAgHYAgAAANkCAwASAAAAMAIBbgMAAADZAgQAEgAAADACARIEAAAA2QIFABICAAASAgEAEgICABIAAAAwAgGABQAAANkCBgASAAAAMAIBfwYAAADZAgcAEgAAADACAUsHAAAAggECAAkDHgMfAxgDGQMbA1UDDwNhBQgAAQIDBAUGBwgYGRobHB0eH7QCAAEYAAEAAAAGAAAABgAAAAYAAAAGAAAABgAAAAAAABAAAAAGAAAAADUBAAAAGAAAAQIAxQGjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIGAAAAUEBNBAGhBwAAAE0DBNIIAAAAnwICAqQDBgAAAFBATQUBoQcAAABNBAV2CQAAAJ8DAgKkBAYAAABQQE0GAaEHAAAATQUGGAoAAACfBAICpAUGAAAAUEBNBgEhCwAAAJ8FAgKkBgYAAABQQE0HAS0MAAAAnwYCAk0HBcoNAAAApAgGAAAAUEBNCgG7DgAAAE0JChEPAAAAnwgCAqQJBgAAAFBATQsBuw4AAABNCguREAAAAJ8JAgKkCgYAAABQQE0MAZQRAAAATQsMYhIAAACfCgICpAsGAAAAUEBNDQEoEwAAAE0MDfgUAAAAnwsCAqQMBgAAAFBATQ4BKBMAAABNDQ4cFQAAAJ8MAgKkDQYAAABQQKQQFwAAAGBBTQ8QJBgAAABNDg8BGQAAAJ8NAgKkDgYAAABQQKQRFwAAAGBBTRARJBgAAABNDxDiGgAAAJ8OAgKkDwYAAABQQE0RAcEbAAAATRARfhwAAACfDwICwBAdABIAAAASAAIATREF+B4AAABvEw4AvBERnB8AAACfEQMC4hIjAKQTJgAAlECCjBQBAIwVAACMFgEAjBcAAJ8TBQIwExIPIAAAAKQTJgAAlECCbxQnAIwVAABvFicAjBcAAJ8TBQIwExLbIQAAAKQTKQAAlICCbxQnAG8VJwCfEwMCMBMSCCIAAAAwEhGSKgAAAMASKwASAA8AEgAAAMATLAASAAMAEgAIABIAEgASAAAAEgACABIAAQASAAkAEgAPADATERMtAAAAwBMuABIAAQASAAkAMBMR0C8AAADAEzAAEgAEADATEVwxAAAAwBMyABIABAASAAsAMBMR9DMAAADAEzQAEgAAADATEQw1AAAAwBM2ABIABwASAA0AEgAOADATEYA3AAAAwBM4ABIACgASABIAMBMRjjkAAABNEwbnOgAAAMAUOwDAFTwAEgAAABIAAgASAAwAnxMDAlIUEQCfEwIAghMAAD0DcAQAAABAA3EDcgNzA3QEAABQQAN1A3YDdwN4A3kDegN7A3wDfQN+A38DgAEDgQEDggEDgwEDhAEEAABgQQOFAQOGAQOHAQOIAQOJAQYAA4oBA4sBA08DUANRBQMgISIDjAEDJQQAlECCAgAAAAAAAOA/A40BBACUgIIDjgEGAQYOAzMGDwMaBhEDNQYSAykGFANMBhUDXwYWA2QDjwEGFwYgCwABDg8REhQVFhcgAQABBQABAAAAAAABAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAA+wABAAAAAAEAAAAAAQABAAAAAAAAAQAAAAAAAAEAAAD6AAABAAAAAAAAAgAAAAAAAAEAAAAAAAAAAAEAAAAAAPsAAAEAAAAAAAACAAAGAAAAAAABAQAAAAAAAAAAAQAA9gAAAAAAAQAAAAAAAP0ABQAACgAAAAAAAAAAAABfAACSAAoAAAAHAAAAABIAAAAYAAAAAABDAAAAAB8AAA4AAGPySwAAAQAAAAUAAAAGAAAABQAAAAoAAABuAAAAnQAAAAAh7XfBKRwYse3fs6u9i9oxCsg4r86R9jWDuAOwKx22sDUWHu5DmnVnDw==

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players")
local v_u_2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v_u_2.Std.Audio)
local v_u_4 = require(v_u_2.Std.Maid)
local v_u_5 = require(v_u_2.Std.TableUtils)
local v6 = require(v_u_2.Roact)
local v7 = require(v_u_2.RoactRodux)
local v_u_8 = v6.createElement
local v_u_9 = require(v_u_2.Trade.TradeUtils)
local v_u_10 = require(v_u_2.Trade.TradeConsts)
local v_u_11 = require(v_u_2.ActionButton.ActionButtonService)
local v_u_12 = require(v_u_2.Garage.SortUtils)
local v_u_13 = require(v_u_2.Garage.EnumSort)
local v_u_14 = require(script.Parent.TradeInventory)
local v_u_15 = require(script.Parent.TradeOffering)
local v_u_16 = require(v_u_2.App.store)
local v17 = v6.PureComponent:extend("Trade")
v17.defaultProps = {
	["size"] = UDim2.new(1, 0, 1, 0),
	["position"] = UDim2.new(0.5, 0, 0.5, 0),
	["anchorPoint"] = Vector2.new(0.5, 0.5)
}
local function v_u_18()
	-- upvalues: (copy) v_u_16, (copy) v_u_1
	v_u_16:dispatch({
		["type"] = "setTradeInventorySearchText",
		["value"] = ""
	})
	v_u_16:dispatch({
		["type"] = "setInventoryPlayer",
		["selectedPlayer"] = v_u_1.LocalPlayer
	})
end
function v17.init(p_u_19)
	-- upvalues: (copy) v_u_4, (copy) v_u_9, (copy) v_u_18, (copy) v_u_1, (copy) v_u_3, (copy) v_u_2, (copy) v_u_10, (copy) v_u_16
	p_u_19.activeMaid = v_u_4.new()
	p_u_19.categories = v_u_9.getCategories()
	p_u_19:setState({
		["inventoryItems"] = p_u_19:_getFilteredInventoryItems(),
		["category"] = p_u_19.categories[1]
	})
	function p_u_19.onClickExitInventory()
		-- upvalues: (ref) v_u_18, (copy) p_u_19
		v_u_18()
		p_u_19.props.setInventoryOpen(false)
	end
	function p_u_19.promptInventory()
		-- upvalues: (ref) v_u_1, (ref) v_u_3, (copy) p_u_19
		if v_u_1.LocalPlayer.PlayerGui then
			v_u_3.ObjectLocal(v_u_1.LocalPlayer.PlayerGui, 6105461542, {
				["Volume"] = 0.15
			})
		end
		p_u_19.props.setInventoryOpen(true)
	end
	function p_u_19.onClickInventoryItem(p20)
		-- upvalues: (copy) p_u_19, (ref) v_u_1, (ref) v_u_3
		if not p_u_19.props.tradeActive then
			return
		end
		if p_u_19.props.inventoryPlayers.selectedPlayer ~= v_u_1.LocalPlayer then
			return
		end
		local v21 = p_u_19.state.inventoryItems[p20]
		local v22 = false
		for _, v23 in ipairs(p_u_19.props.traderMe.offerItems) do
			if v23.id == v21.id then
				v22 = true
				break
			end
		end
		if v22 then
			p_u_19.props.removeTraderMeOfferItem(v21)
		else
			p_u_19.props.addTraderMeOfferItem(v21)
		end
		p_u_19.props.setInventoryOpen(false)
		p_u_19:_updateMyOffer()
		if v_u_1.LocalPlayer.PlayerGui then
			v_u_3.ObjectLocal(v_u_1.LocalPlayer.PlayerGui, 6105461542, {
				["Volume"] = 0.15
			})
		end
	end
	function p_u_19.removeTraderMeOfferItemByIndex(p24)
		-- upvalues: (copy) p_u_19
		p_u_19.props.removeTraderMeOfferItemByIndex(p24)
		p_u_19:_updateMyOffer(false)
	end
	function p_u_19.onClickCategory(p25)
		-- upvalues: (ref) v_u_1, (ref) v_u_3, (copy) p_u_19
		if v_u_1.LocalPlayer.PlayerGui then
			v_u_3.ObjectLocal(v_u_1.LocalPlayer.PlayerGui, 6105461542, {
				["Volume"] = 0.25
			})
		end
		p_u_19:setState({
			["category"] = p25
		})
		if v_u_1.LocalPlayer.PlayerGui then
			v_u_3.ObjectLocal(v_u_1.LocalPlayer.PlayerGui, 6105461542, {
				["Volume"] = 0.15
			})
		end
	end
	function p_u_19.onClickReady()
		-- upvalues: (copy) p_u_19, (ref) v_u_1, (ref) v_u_3
		p_u_19.props.onClickReady()
		p_u_19:_updateMyOffer(true)
		if v_u_1.LocalPlayer.PlayerGui then
			v_u_3.ObjectLocal(v_u_1.LocalPlayer.PlayerGui, 6105461542, {
				["Volume"] = 0.15
			})
		end
	end
	function p_u_19.onClickUnready()
		-- upvalues: (copy) p_u_19, (ref) v_u_1, (ref) v_u_3
		p_u_19.props.onClickUnready()
		p_u_19:_updateMyOffer(false)
		if v_u_1.LocalPlayer.PlayerGui then
			v_u_3.ObjectLocal(v_u_1.LocalPlayer.PlayerGui, 6105461542, {
				["Volume"] = 0.15
			})
		end
	end
	function p_u_19.onClickAccept()
		-- upvalues: (ref) v_u_2, (ref) v_u_10, (ref) v_u_1, (ref) v_u_3
		v_u_2:FindFirstChild(v_u_10.ACCEPT_OFFERING_REMOTE_NAME):FireServer()
		if v_u_1.LocalPlayer.PlayerGui then
			v_u_3.ObjectLocal(v_u_1.LocalPlayer.PlayerGui, 6105461542, {
				["Volume"] = 0.15
			})
		end
	end
	function p_u_19.onClickDecline()
		-- upvalues: (ref) v_u_2, (ref) v_u_10, (ref) v_u_1, (ref) v_u_3
		v_u_2:FindFirstChild(v_u_10.DECLINE_OFFERING_REMOTE_NAME):FireServer()
		if v_u_1.LocalPlayer.PlayerGui then
			v_u_3.ObjectLocal(v_u_1.LocalPlayer.PlayerGui, 6105461542, {
				["Volume"] = 0.15
			})
		end
	end
	function p_u_19.onClickExit()
		-- upvalues: (ref) v_u_2, (ref) v_u_10, (ref) v_u_1, (ref) v_u_3
		v_u_2:FindFirstChild(v_u_10.EXIT_OFFERING_REMOTE_NAME):FireServer()
		if v_u_1.LocalPlayer.PlayerGui then
			v_u_3.ObjectLocal(v_u_1.LocalPlayer.PlayerGui, 6105461542, {
				["Volume"] = 0.15
			})
		end
	end
	function p_u_19.onCardFlipped()
		-- upvalues: (ref) v_u_1, (ref) v_u_3
		if v_u_1.LocalPlayer.PlayerGui then
			v_u_3.ObjectLocal(v_u_1.LocalPlayer.PlayerGui, 9846199217, {
				["Volume"] = 0.15
			})
		end
	end
	function p_u_19.onClickInventoryPlayer(p26)
		-- upvalues: (ref) v_u_16, (ref) v_u_1, (ref) v_u_3
		v_u_16:dispatch({
			["type"] = "setInventoryPlayer",
			["selectedPlayer"] = p26
		})
		if v_u_1.LocalPlayer.PlayerGui then
			v_u_3.ObjectLocal(v_u_1.LocalPlayer.PlayerGui, 6105461542, {
				["Volume"] = 0.15
			})
		end
	end
end
function v17._updateMyOffer(p27, p28)
	-- upvalues: (copy) v_u_2, (copy) v_u_10
	if p28 == nil then
		p28 = p27.props.traderMe.ready
	end
	local v29 = p27:_getMeOfferIds()
	local v30 = v_u_2:FindFirstChild(v_u_10.UPDATE_OFFERING_REMOTE_NAME)
	if v30 then
		v30:FireServer(p28, v29)
	end
end
function v17._getMeOfferIds(p31)
	-- upvalues: (copy) v_u_5
	return v_u_5.map(p31.props.traderMe.offerItems, function(p32)
		local v33 = p32.id
		return assert(v33, "missing id itemProp")
	end)
end
function v17._getFilteredInventoryItems(p34)
	-- upvalues: (copy) v_u_5, (copy) v_u_12
	local v35 = p34.props.tradeInventorySearchText
	local v36 = {}
	for _, v37 in ipairs(p34.props.tradeInventory) do
		if v_u_5.hasDesiredValuesShallow(v37, p34.state.category.match) and (not v35 or (v35 == "" or string.find(v37.title:lower(), v35:lower(), nil, true))) then
			table.insert(v36, v37)
		end
	end
	table.sort(v36, v_u_12.getTradeSortFunc(p34.props.tradeSort))
	return v36
end
function v17._getFilteredInventoryPlayers(p38)
	-- upvalues: (copy) v_u_1
	table.sort(p38.props.inventoryPlayers.allPlayers, function(p39, p40)
		-- upvalues: (ref) v_u_1
		if p39.UserId == v_u_1.LocalPlayer.UserId then
			return true
		elseif p40.UserId == v_u_1.LocalPlayer.UserId then
			return false
		else
			return p39.DisplayName < p40.DisplayName
		end
	end)
	if not p38.props.tradeActive then
		return p38.props.inventoryPlayers
	end
	local v41 = {
		["allPlayers"] = {}
	}
	for _, v42 in p38.props.inventoryPlayers.allPlayers do
		if v42.UserId == p38.props.traderThem.userId or v42.UserId == v_u_1.LocalPlayer.UserId then
			local v43 = v41.allPlayers
			table.insert(v43, v42)
		end
	end
	v41.selectedPlayer = p38.props.inventoryPlayers.selectedPlayer
	return v41
end
function v17.render(p44)
	-- upvalues: (copy) v_u_8, (copy) v_u_14, (copy) v_u_15
	local v45 = {}
	for _, v46 in ipairs(p44.props.traderMe.offerItems) do
		v45[v46.id] = true
	end
	if p44.props.tradeInventoryOpen then
		local v47 = {}
		for _, v48 in ipairs(p44.state.inventoryItems) do
			local v49 = {}
			if v45[v48.id] then
				v49.selected = true
			end
			table.insert(v47, v49)
		end
		return v_u_8(v_u_14, {
			["size"] = p44.props.size,
			["position"] = p44.props.position,
			["anchorPoint"] = p44.props.anchorPoint,
			["categories"] = p44.categories,
			["category"] = p44.state.category,
			["items"] = p44.state.inventoryItems,
			["itemMetadata"] = v47,
			["onClickExit"] = p44.onClickExitInventory,
			["onClickItem"] = p44.onClickInventoryItem,
			["onClickCategory"] = p44.onClickCategory,
			["onCardFlipped"] = p44.onCardFlipped,
			["onSelectSort"] = p44.props.onSelectSort,
			["inventoryPlayers"] = p44:_getFilteredInventoryPlayers(),
			["onClickInventoryPlayer"] = p44.onClickInventoryPlayer,
			["sortId"] = p44.props.tradeSort,
			["showChat"] = p44.props.tradeActive,
			["tradeChatMessages"] = p44.props.tradeChatMessages
		})
	end
	if p44.props.tradeActive then
		local v50 = ""
		if p44.props.tradeInfo then
			if p44.props.tradeInfo.msg then
				v50 = p44.props.tradeInfo.msg
			elseif p44.props.tradeInfo.debugProbability then
				v50 = ("P(you better) [debug] = %.1f%%"):format(p44.props.tradeInfo.debugProbability * 100)
			end
		end
		return v_u_8(v_u_15, {
			["size"] = p44.props.size,
			["position"] = p44.props.position,
			["anchorPoint"] = p44.props.anchorPoint,
			["traderMe"] = p44.props.traderMe,
			["traderThem"] = p44.props.traderThem,
			["promptInventory"] = p44.promptInventory,
			["removeTraderMeOfferItem"] = p44.removeTraderMeOfferItemByIndex,
			["onClickReady"] = p44.onClickReady,
			["onClickUnready"] = p44.onClickUnready,
			["onClickAccept"] = p44.onClickAccept,
			["onClickDecline"] = p44.onClickDecline,
			["onClickExit"] = p44.onClickExit,
			["onCardFlipped"] = p44.onCardFlipped,
			["infoMessage"] = v50,
			["showChat"] = p44.props.tradeActive,
			["tradeChatMessages"] = p44.props.tradeChatMessages
		})
	end
end
function v17.didUpdate(p51, p52, p53)
	-- upvalues: (copy) v_u_11, (copy) v_u_18
	if p51.state.category ~= p53.category or (p51.props.tradeInventory ~= p52.tradeInventory or (p51.props.tradeInventorySearchText ~= p52.tradeInventorySearchText or p51.props.tradeSort ~= p52.tradeSort)) then
		p51:setState({
			["inventoryItems"] = p51:_getFilteredInventoryItems()
		})
	end
	if p51.props.tradeActive ~= p52.tradeActive then
		if not p51.props.tradeActive then
			p51.activeMaid:DoCleaning()
			p51:setState({
				["category"] = p51.categories[1]
			})
			p51.props.setInventoryOpen(false)
			p51.props.resetTradeInfo()
		end
		if p51.props.tradeActive then
			p51.activeMaid:GiveTask(v_u_11.pushHide())
		end
	end
	if p51.props.tradeInventoryOpen and p51.props.tradeInventoryOpen ~= p52.tradeInventoryOpen then
		v_u_18()
	end
end
return v7.connect(function(p54, _)
	return {
		["traderMe"] = p54.traderMe,
		["traderThem"] = p54.traderThem,
		["tradeInventory"] = p54.tradeInventory,
		["tradeInventorySearchText"] = p54.tradeInventorySearchText,
		["tradeCategory"] = p54.tradeCategory,
		["tradeActive"] = p54.tradeActive,
		["tradeSort"] = p54.tradeSort,
		["tradeInventoryOpen"] = p54.tradeInventoryOpen,
		["tradeInfo"] = p54.tradeInfo,
		["inventoryPlayers"] = p54.inventoryPlayers,
		["tradeChatMessages"] = p54.tradeChatMessages
	}
end, function(p_u_55)
	-- upvalues: (copy) v_u_1, (copy) v_u_3, (copy) v_u_13
	return {
		["onClickReady"] = function(_)
			-- upvalues: (copy) p_u_55
			p_u_55({
				["type"] = "updateTraderMe",
				["ready"] = true
			})
		end,
		["onClickUnready"] = function()
			-- upvalues: (copy) p_u_55
			p_u_55({
				["type"] = "updateTraderMe",
				["ready"] = false
			})
		end,
		["addTraderMeOfferItem"] = function(p56)
			-- upvalues: (copy) p_u_55
			p_u_55({
				["type"] = "addTraderMeOfferItem",
				["item"] = p56
			})
		end,
		["removeTraderMeOfferItem"] = function(p57)
			-- upvalues: (copy) p_u_55
			p_u_55({
				["type"] = "removeTraderMeOfferItem",
				["item"] = p57
			})
		end,
		["removeTraderMeOfferItemByIndex"] = function(p58)
			-- upvalues: (copy) p_u_55
			p_u_55({
				["type"] = "removeTraderMeOfferItemByIndex",
				["index"] = p58
			})
		end,
		["onSelectSort"] = function(p59)
			-- upvalues: (ref) v_u_1, (ref) v_u_3, (ref) v_u_13, (copy) p_u_55
			if v_u_1.LocalPlayer.PlayerGui then
				v_u_3.ObjectLocal(v_u_1.LocalPlayer.PlayerGui, 6105461542, {
					["Volume"] = 0.15
				})
			end
			local v60 = nil
			if p59 == v_u_13.Newest then
				v60 = v_u_13.Popular
			elseif p59 == v_u_13.Popular then
				v60 = v_u_13.Alphabetical
			elseif p59 == v_u_13.Alphabetical then
				v60 = v_u_13.Newest
			end
			p_u_55({
				["type"] = "setTradeSortId",
				["sortId"] = v60
			})
		end,
		["setInventoryOpen"] = function(p61)
			-- upvalues: (copy) p_u_55
			p_u_55({
				["type"] = "setTradeInventoryOpen",
				["value"] = p61
			})
		end,
		["resetTradeInfo"] = function()
			-- upvalues: (copy) p_u_55
			p_u_55({
				["type"] = "setTradeInfo",
				["info"] = nil
			})
		end
	}
end)(v17)
