-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNAC0xvY2FsUGxheWVyCVBsYXllckd1aQtPYmplY3RMb2NhbAZWb2x1bWUIcGxheVRpY2sFcHJvcHMQdHJhZGVJbml0aWF0aW9ucxBhY2NlcHRJbml0aWF0aW9uBnVzZXJJZA1yZW1vdmVCeUluZGV4JERFQ0xJTkVfVFJBREVfSU5JVElBVElPTl9SRU1PVEVfTkFNRQ5GaW5kRmlyc3RDaGlsZApGaXJlU2VydmVyCG9uQWNjZXB0CW9uRGVjbGluZQRpbml0FW1heGltdW1JdGVtc0Rpc3BsYXllZAthc3BlY3RSYXRpbwRtYXRoA21pbghwb3NpdGlvbgtkaXNwbGF5TmFtZQxpc1RyYWRpbmdWSVADb2JqBWluZGV4BVVEaW0yA25ldwRuYW1lBUZyYW1lFkJhY2tncm91bmRUcmFuc3BhcmVuY3kEU2l6ZQhQb3NpdGlvbgtBbmNob3JQb2ludARzaXplC2FuY2hvclBvaW50BW1lcmdlC0FzcGVjdFJhdGlvF1VJQXNwZWN0UmF0aW9Db25zdHJhaW50BnJlbmRlcgR0eXBlHXRyYWRlSW5pdGlhdGlvbnNSZW1vdmVCeUluZGV4BGdhbWUHUGxheWVycwpHZXRTZXJ2aWNlEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUDU3RkBUF1ZGlvClJvYWN0Um9kdXgERXpVaQpEaWN0aW9uYXJ5BVJvYWN0DWNyZWF0ZUVsZW1lbnQFVHJhZGULVHJhZGVDb25zdHMGc2NyaXB0BlBhcmVudA9UcmFkZUluaXRpYXRpb24MVHJhZGVTZXJ2aWNlDVB1cmVDb21wb25lbnQQVHJhZGVJbml0aWF0aW9ucwZleHRlbmQMZGVmYXVsdFByb3BzB2Nvbm5lY3QACQUAAgAAABX7AgAATQECMQAAAABNAAGZAQAAAA4ADgD7AQEATQAB0QIAAAD7AwAATQIDMQAAAABNAQKZAQAAAG8CAwDiAwUAbwQGADAEA0sEAAAAnwAEAYIAAQAHAwEDAgMDAgAAYDKfvvZBAwQFAQQCMzMzMzMzwz8ADgUBGAAAAAAAAAEAAAAAAAAAAAAAAAAAAg8AAAAABwEEAAAAKPsEAABNAwQHAAAAAE0CA5UBAAAAhwECAPsDAQBNAgOlAgAAAE0DAYYDAAAAnwICAfsEAABNAwQHAAAAAE0CAywEAAAAUgMAAJ8CAgH7BAIATQMEMQUAAABNAgOZBgAAAA4CDgD7AwMATQID0QcAAAD7BQIATQQFMQUAAABNAwSZBgAAAG8ECADiBQoAbwYLADAGBUsJAAAAnwIEAYIAAQAMAwYDBwMIAwkDCgMBAwIDAwIAAGAyn772QQMEBQEJAjMzMzMzM8M/ABwAARgOAAAAAAABAAAAAAABAAAAAAAA8AAAAAAAAQAAAAAAAAAAAAAAAAARDwAAAAAIAQUAAAAu+wQAAE0DBAcAAAAATQIDlQEAAACHAQIA+wIBAPsFAgBNBAWoAgAAALwCAgMDAAAAnwIDAk0FAYYEAAAAvAMCawUAAACfAwMB+wUAAE0EBQcAAAAATQMELAYAAABSBAAAnwMCAfsFAwBNBAUxBwAAAE0DBJkIAAAADgMOAPsEBABNAwTRCQAAAPsGAwBNBQYxBwAAAE0EBZkIAAAAbwUKAOIGDABvBw0AMAcGSwsAAACfAwQBggABAA4DBgMHAwsDDAMJAw0DCgMBAwIDAwIAAGAyn772QQMEBQELAjMzMzMzM8M/ACIAARgUAAAAAAABAAAAAAAAAQAAAAABAAAAAAAA6QAAAAAAAQAAAAAAAAAAAAAAAAAYDwAAAAACAQUAAAAQ2QEAABIAAAASAgAAEgIBABICAgAwAQAqAAAAANkBAQASAAAAEgIDABICBAASAgEAEgICADABAC0BAAAAggABAAIDDgMPAgECGxABGAAAAAAAAAAGAAAAAAAAAAccAAAAABYBAwAAAJMBTQYABwEAAABNBQaHAgAAANgEAAVNCAAHAQAAAE0HCIcCAAAA2AYDB9gFAAYmAwQF2AIAA00EAAcBAAAATQMEiQQAAAAJAQIDTQQABwEAAABNAwSHAgAAAE0FAAcBAAAATQQFiQQAAAAJAgME/wMAAAAAAABNBgAHAQAAAE0FBpUFAAAAHAQFAIwHAQBNCwAHAQAAAE0KC4cCAAAAnhMEBAoAAABSCQQApAgIAAAcYICfCAMCUgUIAIwGAQCoBTcAJgkEB5UICQBNCwAHAQAAAE0KC5UFAAAAhwkKCPsKAAD7CwEA4gwQADABDIkEAAAApA0TAABIEIGMDgAAjA8AAIwRAQAmFQcEeBQVAOwTFAJNFQAHAQAAAE0UFYkEAAAACRITFEMQERKMEQAAnw0FAjANDNsJAAAATQ0JWhQAAAAwDQx3CgAAAE0NCRsLAAAAMA0MGwsAAABNDQkTDAAAADANDBMMAAAAMAgMAg0AAABNDQAqDgAAADANDCoOAAAATQ0ALQ8AAAAwDQwtDwAAAJ8KAwJqCgMHiwXJ//sFAABvBhUA4gcaAIwIAQAwCAc6FgAAAE0JAAcBAAAATQgJDxsAAAAwCAcvFwAAAE0JAAcBAAAATQgJ2wkAAAAwCAc7GAAAAE0JAAcBAAAATQgJCBwAAAAwCAfoGQAAAPsJAgBNCAkfHQAAAOIJHwD7CgAAbwsgAOIMHwBNDgAHAQAAAE0NDokEAAAAMA0MaR4AAACfCgMCMAoJaR4AAABSCgMAnwgDAJ8FAACCBQAAIQIAAAAAAADwPwMGAxECAAAAAAAAcEADEgMHAxMDFAQAHGCAAxUDFgMXAxgDGQMOAw8FCAQJCgsMDQ4PAxoDGwQASBCBAxwDHQMeAx8DIAMhBQQWFxgZAyIDIwMkAyUFAR4DJgAqJwEYAAAAAAAAAAAAAAAAAAEAAAAAAQAAAAAAAAAAAQABAAAAAAEAAAAAAAAAAAAAAAAAAQABAAAAAAMAAAEAAQABAQEAAAAAAAAAAAAB/AAABgAAAAEAAAABAAAAAQABAAAAAQAAAPMA+xUBAQEAAAEAAAAAAAEAAAAAAAEAAAAAAAIAAAABAAABAAAAAAD/AAAD/PgALQAAAAAEAgAAAAAG4gIBAE0DAJUAAAAAMAMClQAAAACCAgIAAgMHBQEAAFYAARgAAQAAAABXAAAAAAQBAQAAAAn7AQAA4gICAG8DAwAwAwJxAAAAADAAAgIBAAAAnwECAYIAAQAEAygDGQUCAAEDKQBcCgEYAAABAAABAP4EXQAAAAADAQAAAAAG4gEBANkCAAASAAAAMAIBLAAAAACCAQIAAgMKBQEAAQZaAAEYAAEAAAAAWwAAAAASAAABAgB4owAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBAQAAAABAbwMEALwBARYDAAAAnwEDAqQCBgAAAFBATQQBoQcAAABNAwTSCAAAAJ8CAgKkAwYAAABQQE0EAS0JAAAAnwMCAqQEBgAAAFBATQYBLQoAAABNBQapCwAAAJ8EAgKkBQYAAABQQE0GASEMAAAAnwUCAk0GBcoNAAAApAcGAAAAUEBNCQG7DgAAAE0ICZEPAAAAnwcCAqQIBgAAAFBApAsRAAAAAEFNCgskEgAAAE0JCv0TAAAAnwgCAqQJBgAAAFBATQsBuw4AAABNCgsJFAAAAJ8JAgLAChUAEgAAABIAAgBNCwX4FgAAAG8NFwC8CwucGAAAAJ8LAwLiDB0ApA0gAAB84IGMDgEAjA8AAIwQAQCMEQAAnw0FAjANDA8ZAAAApA0gAAB84IGMDgAAjA8AAIwQAACMEQAAnw0FAjANDNsaAAAAbw0hADANDIkbAAAAjA0EADANDIccAAAAMAwLkiIAAADADCMAEgAJABIAAAASAAIAEgABABIABwAwDAsTJAAAAMAMJQASAAYAEgAIABIABAAwDAuAJgAAAE0MA+cnAAAAwA0oAMAOKQCfDAMCUg0LAJ8MAgCCDAAAKgMqBAAAAEADKwMsAy0DLgQAAFBAAy8DMAMxAzIDMwM0AzUDNgM3AzgEAAAAQQM5AzoDOwYAAzwDPQM+AyIDFQMSAxEFBBkaGxwDGgMbBAB84IECAAAAAAAA9D8DPwYDAxAGBAMnA0AGBQYHBQADBAUHAQABGAABAAAAAAABAAAAAAABAAAAAAAAAQAAAAABAAAAAAAAAQAAAAABAAIAAAAAAAABAAAAAAAAAAABAAAAAAAAAgAABgAAAAAAAQEAAAAAAAAAAAEAAAAAAAAAAAEAAAEAAPwABgAAAAAAAAAPAAAAAAAsAAAE/A0AAAEAAAAACAmcWng7WA1BO1gw7G9XWz1SskEVTxkKANjbeEwmm8VMhnPmJ7IIARU=

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players")
local v_u_2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v_u_2.Std.Audio)
local v4 = require(v_u_2.RoactRodux)
local v_u_5 = require(v_u_2.EzUi.Dictionary)
local v6 = require(v_u_2.Roact)
local v_u_7 = v6.createElement
local v_u_8 = require(v_u_2.Trade.TradeConsts)
local v_u_9 = require(script.Parent.TradeInitiation)
local v_u_10 = require(v_u_2.Trade.TradeService)
local v11 = v6.PureComponent:extend("TradeInitiations")
v11.defaultProps = {
	["size"] = UDim2.new(1, 0, 1, 0),
	["position"] = UDim2.new(0, 0, 0, 0),
	["aspectRatio"] = 1.25,
	["maximumItemsDisplayed"] = 4
}
function v11.init(p_u_12)
	-- upvalues: (copy) v_u_10, (copy) v_u_1, (copy) v_u_3, (copy) v_u_2, (copy) v_u_8
	function p_u_12.onAccept(p13)
		-- upvalues: (copy) p_u_12, (ref) v_u_10, (ref) v_u_1, (ref) v_u_3
		local v14 = p_u_12.props.tradeInitiations[p13]
		v_u_10.acceptInitiation(v14.userId)
		p_u_12.props.removeByIndex(p13)
		if v_u_1.LocalPlayer.PlayerGui then
			v_u_3.ObjectLocal(v_u_1.LocalPlayer.PlayerGui, 6105461542, {
				["Volume"] = 0.15
			})
		end
	end
	function p_u_12.onDecline(p15)
		-- upvalues: (copy) p_u_12, (ref) v_u_2, (ref) v_u_8, (ref) v_u_1, (ref) v_u_3
		local v16 = p_u_12.props.tradeInitiations[p15]
		v_u_2:FindFirstChild(v_u_8.DECLINE_TRADE_INITIATION_REMOTE_NAME):FireServer(v16.userId)
		p_u_12.props.removeByIndex(p15)
		if v_u_1.LocalPlayer.PlayerGui then
			v_u_3.ObjectLocal(v_u_1.LocalPlayer.PlayerGui, 6105461542, {
				["Volume"] = 0.15
			})
		end
	end
end
function v11.render(p17)
	-- upvalues: (copy) v_u_7, (copy) v_u_9, (copy) v_u_5
	local v18 = 1 / (1 / p17.props.maximumItemsDisplayed - 1 / (256 / p17.props.maximumItemsDisplayed)) * p17.props.aspectRatio
	local v19 = p17.props.maximumItemsDisplayed * p17.props.aspectRatio
	local v20 = #p17.props.tradeInitiations
	local v21 = p17.props.maximumItemsDisplayed
	local v22 = {}
	for v23 = 1, math.min(v20, v21) do
		local v24 = v20 - v23 + 1
		local v25 = p17.props.tradeInitiations[v24]
		v22[v23] = v_u_7(v_u_9, {
			["aspectRatio"] = v18,
			["position"] = UDim2.new(0, 0, 1 + (v23 - v20 - 1) / v19 * p17.props.aspectRatio, 0),
			["displayName"] = v25.name,
			["isTradingVIP"] = v25.isTradingVIP,
			["obj"] = v25.obj,
			["index"] = v24,
			["onAccept"] = p17.onAccept,
			["onDecline"] = p17.onDecline
		})
	end
	local v26 = v_u_7
	local v27 = {
		["BackgroundTransparency"] = 1,
		["Size"] = p17.props.size,
		["Position"] = p17.props.position,
		["AnchorPoint"] = p17.props.anchorPoint
	}
	local v28 = v_u_5.merge
	local v29 = {
		["AspectRatio"] = v_u_7("UIAspectRatioConstraint", {
			["AspectRatio"] = p17.props.aspectRatio
		})
	}
	return v26("Frame", v27, v28(v29, v22))
end
return v4.connect(function(p30, _)
	return {
		["tradeInitiations"] = p30.tradeInitiations
	}
end, function(p_u_31)
	return {
		["removeByIndex"] = function(p32)
			-- upvalues: (copy) p_u_31
			p_u_31({
				["type"] = "tradeInitiationsRemoveByIndex",
				["index"] = p32
			})
		end
	}
end)(v11)
