-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNLBXByb3BzCGRpc2FibGVkB29uQ2xpY2sFaG92ZXIIc2V0U3RhdGUHcHJlc3NlZAtvbkFjdGl2YXRlZAxvbk1vdXNlRW50ZXIMb25Nb3VzZUxlYXZlC29uTW91c2VEb3duCW9uTW91c2VVcARpbml0D2JhY2tncm91bmRDb2xvcgpicmlnaHRlbkJ5BXN0YXRlClRleHRCdXR0b24PQXV0b0J1dHRvbkNvbG9yC2xheW91dE9yZGVyC0xheW91dE9yZGVyEEJhY2tncm91bmRDb2xvcjMEc2l6ZQRTaXplCHBvc2l0aW9uCFBvc2l0aW9uAARUZXh0D0JvcmRlclNpemVQaXhlbAVFdmVudAlBY3RpdmF0ZWQKTW91c2VFbnRlcgpNb3VzZUxlYXZlD1NlbGVjdGlvbkdhaW5lZA1TZWxlY3Rpb25Mb3N0EE1vdXNlQnV0dG9uMURvd24OTW91c2VCdXR0b24xVXALQXNwZWN0UmF0aW8IVUlDb3JuZXIFVGl0bGULYXNwZWN0UmF0aW8XVUlBc3BlY3RSYXRpb0NvbnN0cmFpbnQMQ29ybmVyUmFkaXVzBFVEaW0DbmV3C2Nvcm5lclNjYWxlC2Nvcm5lclBpeGVsBUZyYW1lFkJhY2tncm91bmRUcmFuc3BhcmVuY3kGQ29sb3IzBVVEaW0yCVRleHRMYWJlbAtBbmNob3JQb2ludApUZXh0Q29sb3IzDlRleHRYQWxpZ25tZW50BEZvbnQKTGluZUhlaWdodApUZXh0U2NhbGVkB1ZlY3RvcjIEdGV4dARFbnVtBkNlbnRlcgdCYW5nZXJzBnJlbmRlcgRnYW1lEVJlcGxpY2F0ZWRTdG9yYWdlCkdldFNlcnZpY2UHcmVxdWlyZQNTdGQKQ29sb3JVdGlscwVSb2FjdA1jcmVhdGVFbGVtZW50DVB1cmVDb21wb25lbnQLVHJhZGVCdXR0b24GZXh0ZW5kBkJ1dHRvbgxkZWZhdWx0UHJvcHMACAMAAQAAABP7AgAATQECBwAAAABNAAGCAQAAACsADAD7AgAATQECBwAAAABNAAFuAgAAAA4ABgD7AgAATQECBwAAAABNAAFuAgAAAJ8AAQGCAAEAAwMBAwIDAwAUAAEYAAAAAAAAAQAAAAAAAQAAAAAAAxUAAAAABAABAAAACfsAAADiAgEAqQMBADADArAAAAAAvAAAKgIAAACfAAMBggABAAMDBAUBAAMFABsAARgAAAEAAP8AAAMcAAAAAAQAAQAAAAn7AAAA4gIBAKkDAAAwAwKwAAAAALwAACoCAAAAnwADAYIAAQADAwQFAQADBQAgAAEYAAABAAD/AAADIQAAAAAEAAEAAAAJ+wAAAOICAQCpAwEAMAMC7wAAAAC8AAAqAgAAAJ8AAwGCAAEAAwMGBQEAAwUAJQABGAAAAQAA/wAAAyYAAAAABAABAAAACfsAAADiAgEAqQMAADADAu8AAAAAvAAAKgIAAACfAAMBggABAAMDBgUBAAMFACoAARgAAAEAAP8AAAMrAAAAAAIBAAAAABXZAQAAEgAAADABAJIAAAAA2QEBABIAAAAwAQAEAQAAANkBAgASAAAAMAEAhwIAAADZAQMAEgAAADABAAwDAAAA2QEEABIAAAAwAQCHBAAAAIIAAQAFAwcDCAMJAwoDCwUAAQIDBBMMARgAAAAABwAAAAUAAAAFAAAABQAAAAUUAAAAABIBAwAAAJcCTQIABwAAAABNAQIOAQAAAE0DAAcAAAAATQIDggIAAAAOAgsA+wMAAE0CA5wDAAAATQQABwAAAABNAwQOAQAAAG8EBACfAgMCUgECAGUAHwBNAwAYBQAAAE0CA+8GAAAADgILAPsDAABNAgOcAwAAAE0EAAcAAAAATQMEDgEAAABvBAcAnwIDAlIBAgBlAA8ATQMAGAUAAABNAgOwCAAAAA4CCgD7AwAATQIDnAMAAABNBAAHAAAAAE0DBA4BAAAAbwQJAJ8CAwJSAQIA+wIBAG8DCgD/BAUAAAAAAKkFAAAwBQTXCwAAAE0GAAcAAAAATQUGIAwAAAAwBQQADQAAADABBJ8OAAAATQYABwAAAABNBQYPDwAAADAFBC8QAAAATQYABwAAAABNBQbbEQAAADAFBDsSAAAAbwUTADAFBPUUAAAAjAUAADAFBI4VAAAA+wcCAE0GBzYWAAAATQUGHhcAAABNBgCSGAAAAGoGBAX7BwIATQYHNhYAAABNBQYUGQAAAE0GAAQaAAAAagYEBfsHAgBNBgc2FgAAAE0FBt0bAAAATQYAhxwAAABqBgQF+wcCAE0GBzYWAAAATQUG2x0AAABNBgAEGgAAAGoGBAX7BwIATQYHNhYAAABNBQZIHgAAAE0GAIccAAAAagYEBfsHAgBNBgc2FgAAAE0FBmEfAAAATQYADCAAAABqBgQF+wcCAE0GBzYWAAAATQUGMiEAAABNBgCHIgAAAGoGBAXiBSYATQgABwAAAABNBwiJJwAAAA4HCwD7BgEAbwcoAOIIKQBNCgAHAAAAAE0JCoknAAAAMAkIaSMAAACfBgMCKwYBAMYGAAAwBgVpIwAAAPsGAQBvByQA4ggrAKQJLgAAtMCCTQsABwAAAABNCguxLwAAAE0MAAcAAAAATQsM8zAAAACfCQMCMAkITyoAAACfBgMCMAYF9CQAAAD7BgEAbwcxAOIIMwCMCQEAMAkIOjIAAACkCTUAALRAg4wKAQCMCwAAjAwAAJ8JBAIwCQifDgAAAKQJNwAAtGCDjAoBAIwLAACMDAEAjA0AAJ8JBQIwCQgvEAAAAKQJNwAAtGCDjAoAAIwLAACMDAAAjA0AAJ8JBQIwCQg7EgAAAOIJOAD7CgEAbws5AOIMQACMDQEAMA0MOjIAAACkDTcAALRgg4wOAQCMDwAAjBABAIwRAACfDQUCMA0MLxAAAACkDTcAALRgg28OQQCMDwAAbxBBAIwRAACfDQUCMA0MOxIAAACkDUMAALQghG8OQQBvD0EAnw0DAjANDOg6AAAApA01AAC0QIOMDgEAjA8BAIwQAQCfDQQCMA0MczsAAABNDgAHAAAAAE0NDtVEAAAAMA0M9RQAAACkDUcARvBQxDANDHs8AAAApA1JAEj0UMQwDQw5PQAAAIwNAQAwDQyCPgAAAKkNAQAwDQzePwAAAJ8KAwIwCgn1FAAAAJ8GBAIwBgW6JQAAAJ8CBACCAgAASgMBAw0DAgMOAgAAAAAAAOC/Aw8DBgKamZmZmZnJvwMEAjMzMzMzM8O/AxADEQMSAxMDFAMVAxYDFwMYAxkDGgMbAxwDHQMHAx4DCAMfAwkDIAMhAyIDCgMjAwsDJAMlAyYFAyMkJQMnAygFASMDKQUBKgMqAysEALTAggMsAy0DLgMvBQQyDhASAzAEALRAgwMxBAC0YIMFARQDMgMzAzQDNQM2AzcDOAUKMhASOjsUPD0+PwIAAAAAAADgPwM5BAC0IIQDOgM7AzwERvBQxAM9BEj0UMQAMD4BGAAAAAABAAAAAAEAAAAAAAAAAAAAAQAAAAABAAAAAAAAAAAAAAEAAAAAAQAAAAAAAAAAAAIAAAABAAABAAAAAAABAAEAAAAAAAEAAAAAAAEAAAEAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQEAAAAAAAAAAQAAAAAA/wAC/gADAAABAAAAAAAAAAAAAAAA/wAAAwAAAQAAAQAAAAAAAAABAAAAAAAAAAABAAAAAAAAAAABAQAAAQAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAQAAAAAAAQAAAAEAAAABAAABAAD2AAD6AADqADEAAAAACwAAAQIAVKMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DAKEGAAAATQIDMwcAAACfAQICpAIFAAAAQEBNAwAhCAAAAJ8CAgJNAwLKCQAAAE0EAvgKAAAAbwYLALwEBJwMAAAAnwQDAuIFFgCMBgEAMAYFIA0AAACkBhkAAGBwgW8HGgBvCBoAbwkaAJ8GBAIwBgUODgAAAG8GGwAwBgXVDwAAAKkGAAAwBgWCEAAAAIwGBAAwBgWJEQAAAKQGHQAAYMCBjAcBAIwIAACMCQEAjAoAAJ8GBQIwBgUPEgAAAKQGHQAAYMCBjAcAAIwIAACMCQAAjAoAAJ8GBQIwBgXbEwAAAIwGBAAwBgXzFAAAAIwGAAAwBgWxFQAAADAFBJIeAAAAwAUfADAFBBMgAAAAwAUhABIAAQASAAMAEgACADAFBIAiAAAAggQCACMDPwQAAABAA0ADQQNCBAAAQEADQwNEA0UDRgNHA0gDSQMSAw0DOgMCAycDFQMXAy0DLAUJDQ4PEBESExQVAzADKwQAYHCBApqZmZmZmbk/A0oDMQQAYMCBA0sGBQMMBgYDPgIFBgEAARgAAQAAAAAAAQAAAAAAAAEAAAAAAQACAAAAAAABAQAAAQAAAAAAAAABAAABAAABAAABAAAAAAAAAAABAAAAAAAAAAABAAABAAD3AAsAAB0AAAAAADQBAAAAAAcQQHclYuxY0SKEHbHLnfLv7P4VOaxlxN6ctyUVyJWQgJCW6t4YnAde

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.ColorUtils)
local v_u_3 = require(v1.Roact)
local v_u_4 = v_u_3.createElement
local v5 = v_u_3.PureComponent:extend("TradeButton")
v5.defaultProps = {
	["layoutOrder"] = 1,
	["backgroundColor"] = Color3.new(0.1, 0.1, 0.1),
	["text"] = "Button",
	["disabled"] = false,
	["aspectRatio"] = 4,
	["size"] = UDim2.new(1, 0, 1, 0),
	["position"] = UDim2.new(0, 0, 0, 0),
	["cornerPixel"] = 4,
	["cornerScale"] = 0
}
function v5.init(p_u_6)
	function p_u_6.onActivated()
		-- upvalues: (copy) p_u_6
		if not p_u_6.props.disabled and p_u_6.props.onClick then
			p_u_6.props.onClick()
		end
	end
	function p_u_6.onMouseEnter()
		-- upvalues: (copy) p_u_6
		p_u_6:setState({
			["hover"] = true
		})
	end
	function p_u_6.onMouseLeave()
		-- upvalues: (copy) p_u_6
		p_u_6:setState({
			["hover"] = false
		})
	end
	function p_u_6.onMouseDown()
		-- upvalues: (copy) p_u_6
		p_u_6:setState({
			["pressed"] = true
		})
	end
	function p_u_6.onMouseUp()
		-- upvalues: (copy) p_u_6
		p_u_6:setState({
			["pressed"] = false
		})
	end
end
function v5.render(p7)
	-- upvalues: (copy) v_u_2, (copy) v_u_4, (copy) v_u_3
	local v8 = p7.props.backgroundColor
	if p7.props.disabled then
		v8 = v_u_2.brightenBy(p7.props.backgroundColor, -0.5)
	elseif p7.state.pressed then
		v8 = v_u_2.brightenBy(p7.props.backgroundColor, -0.2)
	elseif p7.state.hover then
		v8 = v_u_2.brightenBy(p7.props.backgroundColor, -0.15)
	end
	local v9 = v_u_4
	local v10 = "TextButton"
	local v11 = {
		["AutoButtonColor"] = false,
		["LayoutOrder"] = p7.props.layoutOrder,
		["BackgroundColor3"] = v8,
		["Size"] = p7.props.size,
		["Position"] = p7.props.position,
		["Text"] = "",
		["BorderSizePixel"] = 0,
		[v_u_3.Event.Activated] = p7.onActivated,
		[v_u_3.Event.MouseEnter] = p7.onMouseEnter,
		[v_u_3.Event.MouseLeave] = p7.onMouseLeave,
		[v_u_3.Event.SelectionGained] = p7.onMouseEnter,
		[v_u_3.Event.SelectionLost] = p7.onMouseLeave,
		[v_u_3.Event.MouseButton1Down] = p7.onMouseDown,
		[v_u_3.Event.MouseButton1Up] = p7.onMouseUp
	}
	local v12 = {}
	local v13
	if p7.props.aspectRatio then
		v13 = v_u_4("UIAspectRatioConstraint", {
			["AspectRatio"] = p7.props.aspectRatio
		}) or nil
	else
		v13 = nil
	end
	v12.AspectRatio = v13
	v12.UICorner = v_u_4("UICorner", {
		["CornerRadius"] = UDim.new(p7.props.cornerScale, p7.props.cornerPixel)
	})
	v12.Title = v_u_4("Frame", {
		["BackgroundTransparency"] = 1,
		["BackgroundColor3"] = Color3.new(1, 0, 0),
		["Size"] = UDim2.new(1, 0, 1, 0),
		["Position"] = UDim2.new(0, 0, 0, 0)
	}, {
		["Text"] = v_u_4("TextLabel", {
			["BackgroundTransparency"] = 1,
			["Size"] = UDim2.new(1, 0, 1, 0),
			["Position"] = UDim2.new(0.5, 0, 0.5, 0),
			["AnchorPoint"] = Vector2.new(0.5, 0.5),
			["TextColor3"] = Color3.new(1, 1, 1),
			["Text"] = p7.props.text,
			["TextXAlignment"] = Enum.TextXAlignment.Center,
			["Font"] = Enum.Font.Bangers,
			["LineHeight"] = 1,
			["TextScaled"] = true
		})
	})
	return v9(v10, v11, v12)
end
return v5
