-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNgB19sb2FkZWQEd2Fybi1CaW5kZXIgJXEgaXMgbm90IGxvYWRlZC4gQ2FsbCA6U3RhcnQoKSBvbiBpdCEIX3RhZ05hbWUGZm9ybWF0DHNldG1ldGF0YWJsZQNuZXcFX21haWQFZXJyb3InQmFkIGFyZ3VtZW50ICd0YWdOYW1lJywgZXhwZWN0ZWQgc3RyaW5nNkJhZCBhcmd1bWVudCAnY29uc3RydWN0b3InLCBleHBlY3RlZCB0YWJsZSBvciBmdW5jdGlvbgxfY29uc3RydWN0b3IMX2luc3RUb0NsYXNzDF9hbGxDbGFzc1NldA9fcGVuZGluZ0luc3RTZXQKX2xpc3RlbmVycwVfYXJncwVkZWxheQR0eXBlBXRhYmxlCUNsYXNzTmFtZQZCaW5kZXIIaXNCaW5kZXIISXNDbGllbnQFTW9kZWwDSXNBEk1vZGVsU3RyZWFtaW5nTW9kZQRFbnVtB0RlZmF1bHQGQXRvbWljFXNldE1vZGVsU3RyZWFtaW5nTW9kZQRfYWRkB19yZW1vdmUFcGFpcnMJR2V0VGFnZ2VkBHRhc2sFc3Bhd24WR2V0SW5zdGFuY2VBZGRlZFNpZ25hbAdDb25uZWN0CEdpdmVUYXNrGEdldEluc3RhbmNlUmVtb3ZlZFNpZ25hbAVTdGFydAZHZXRUYWcOR2V0Q29uc3RydWN0b3IEbmV4dA9PYnNlcnZlSW5zdGFuY2URX2NsYXNzQWRkZWRTaWduYWwTR2V0Q2xhc3NBZGRlZFNpZ25hbBRfY2xhc3NSZW1vdmluZ1NpZ25hbBZHZXRDbGFzc1JlbW92aW5nU2lnbmFsBkdldEFsbAlHZXRBbGxTZXRfW0JpbmRlci5CaW5kXSAtIEJpbmRpbmdzICclcycgZG9uZSBvbiB0aGUgY2xpZW50ISBXaWxsIGJlIGRpc3J1cHRlZCB1cG9uIHNlcnZlciByZXBsaWNhdGlvbiEgJXMFZGVidWcJdHJhY2ViYWNrBkFkZFRhZwNHZXQEQmluZAZ0eXBlb2YISW5zdGFuY2UJQmFkIGluc3QnBmFzc2VydGFbQmluZGVyLkJpbmRdIC0gVW5iaW5kaW5nICclcycgZG9uZSBvbiB0aGUgY2xpZW50ISBNaWdodCBiZSBkaXNydXB0ZWQgdXBvbiBzZXJ2ZXIgcmVwbGljYXRpb24hICVzCVJlbW92ZVRhZwZVbmJpbmRLW0JpbmRlci5CaW5kQ2xpZW50XSAtIEJpbmRpbmdzICclcycgZG9uZSBvbiB0aGUgc2VydmVyISBXaWxsIGJlIHJlcGxpY2F0ZWQhCkJpbmRDbGllbnQIQmFkIGluc3QMVW5iaW5kQ2xpZW50IkFyZ3VtZW50ICdpbnN0JyBpcyBub3QgYW4gSW5zdGFuY2UHUHJvbWlzZVZbQmluZGVyLl9hZGRdIC0gUmVlbnRlcmVkIGFkZC4gU3RpbGwgbG9hZGluZywgcHJvYmFibHkgY2F1c2VkIGJ5IGVycm9yIGluIGNvbnN0cnVjdG9yLghmdW5jdGlvbgZ1bnBhY2sGQ3JlYXRlSFtCaW5kZXIuX2FkZF0gLSBGYWlsZWQgdG8gbG9hZCBpbnN0YW5jZSAlcSBvZiAlcSwgcmVtb3ZlZCB3aGlsZSBsb2FkaW5nIQtHZXRGdWxsTmFtZQh0b3N0cmluZwdEZXN0cm95MFtCaW5kZXIuX2FkZF0gLSBCYWQgY2xhc3MgY29uc3RydWN0ZWQgZm9yIHRhZyAlcQlPdmVyd3JvdGUERmlyZUpbQmluZGVyLl9yZW1vdmVdIC0gQ2xhc3MgJXEgbm8gbG9uZ2VyIGhhcyBkZXN0cm95LCBzb21ldGhpbmcgZGVzdHJveWVkIGl0IRBGYWlsZWQgdG8gcmVtb3ZlCkRvQ2xlYW5pbmcEZ2FtZQpSdW5TZXJ2aWNlCkdldFNlcnZpY2URQ29sbGVjdGlvblNlcnZpY2UHcmVxdWlyZQZzY3JpcHQGUGFyZW50BE1haWQGU2lnbmFsEXByb21pc2VCb3VuZENsYXNzB19faW5kZXgAGQUAAQAABwAAAQMBCgIP+wEAAE0AAc0AAAAAKwAKAKQAAgAAABBAbwEDAPsEAABNAwT/BAAAALwBAY0FAAAAnwEDAJ8AAAGCAAEABgMBAwIEAAAQQAMDAwQDBQA5AAEYAAAAAAEAAAAAAAAAAAACOgAAAAAGAgIBAAcEAAAFAgMPPaMCAAD/AwQAAAAAAPsEAACePQMDBAAAAKQCAQAAAABAnwIDAvsEAQBNAwTvAgAAAJ8DAQIwAwLBAwAAAFIDAAArAwQApAMFAAAAQEBvBAYAnwMCAjADAv8HAAAAUgMBACsDBACkAwUAAABAQG8ECACfAwICMAMCrwkAAAD/AwAAAAAAADADAr4KAAAA/wMAAAAAAAAwAwI+CwAAAP8DAAAAAAAAMAMCGAwAAAD/AwAAAAAAADADAhoNAAAA/wMAAAAAAADdBAAAxQMEAAEAAAAwAwINDgAAAKQDEAAAAPBAjAQFANkFAAASAAIAnwMDAYICAgARAwYEAAAAQAMHAwgDCQQAAEBAAwoDBAMLAwwDDQMOAw8DEAMRAxIEAADwQAEAKwcBGAABAAAAAAAAAAIAAAAAAAEAAAAAAAAAAQAAAAAAAAACAAAAAQAAAAEAAAACAAAAAQAAAAAAAAIAAAAAAAYrAAAAAAQBAAAAAA+pAQAAuygAA1IDAACkAgEAAAAAQJ8CAgLwAgcAAgAAgE0CANsDAAAA8AICAAQAAACpAQABqQEBAIIBAgAFAxMEAAAAQAMUAxUDFgBFFwEYAAAAAAAAAAAAAAAAAAAARgAAAAAEAQEAAAAV+wEAALwBAQQAAAAAnwECAisBDwBvAwEAvAEA/gIAAACfAQMCDgEKAE0BAP8DAAAApAIGAAUMQMCaAQUAAgAAAKQBCAAHDEDAMAEA/wMAAACCAAEACQMYAxkDGgMbAxwDHQQFDEDAAx4EBwxAwABJHwEYAAAAAAABAAAAAAEAAAAAAAEAAAAESwAAAAAEAQIAAAAa+wEAALwBAQQAAAAAnwECAisBDwBvAwEAvAEA/gIAAACfAQMCDgEKAE0BAP8DAAAApAIGAAUMQMCaAQUAAgAAAKQBCAAHDEDAMAEA/wMAAAD7AQEAUgMAALwBAZUJAAAAnwEDAYIAAQAKAxgDGQMaAxsDHAMdBAUMQMADHgQHDEDAAyAAYAABGAAAAAAAAQAAAAABAAAAAAABAAAAFAAAAAABSwAAAAAEAQEAAAAG+wEAAFIDAAC8AQGXAAAAAJ8BAwGCAAEAAQMhAGQAARgAAAAAAAFlAAAAAAoBAgAAAFBNAQDNAAAAAA4BAQCCAAEAqQEBADABAM0AAAAApAECAAAAEED7AgAATQQA/wMAAAC8AgIFBAAAAJ8CAwCfAQAEFwEbAPsGAQC8BgYEBQAAAJ8GAgIrBg8AbwgGALwGBf4HAAAAnwYDAg4GCgBNBgX/CAAAAKQHCwAKIJDAmgYFAAcAAACkBg0ADCCQwDAGBf8IAAAApAYQAAA84IBNBwCVEQAAAFIIAABSCQUAnwYEAW4B5P8CAAAATQEAwRIAAAD7AwAATQUA/wMAAAC8AwNeEwAAAJ8DAwLZBQAAEgIBABIAAAC8AwPHFAAAAJ8DAwC8AQH9FQAAAJ8BAAFNAQDBEgAAAPsDAABNBQD/AwAAALwDA9wWAAAAnwMDAtkFAQASAAAAvAMDxxQAAACfAwMAvAEB/RUAAACfAQABggABABcDAQMiBAAAEEADBAMjAxgDGQMaAxsDHAMdBAogkMADHgQMIJDAAyQDJQQAPOCAAyADCAMmAycDKAMpAgQFVSoBGAsAAAECAAACAAAAAAAAAAAA8AAAAAABAAAAAAEAAAAAAAEAAAAPAAAAAAAA/gAFAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAADSwAAAAACAQAAAAADTQEA/wAAAACCAQIAAQMEAGorARgAAABrAAAAAAIBAAAAAANNAQCvAAAAAIIBAgABAwwAbywBGAAAAHAAAAAABAADAAAAH/sCAABNAQIaAAAAAPsCAQCHAAECKwABAIIAAQD7AgAATQECGgAAAAD7AgEAhwABAvsBAgDGAgAAagIAAaQAAgAAABBA+wMAAE0CAxoAAAAA+wMBAIcBAgOfAAICKwAGAPsBAABNAAEaAAAAAPsBAQDGAgAAagIAAYIAAQADAxADLQQAABBAAHgAARgAAAAAAAABAwAAAAAAAAABAAAAAAAAAAABAAAAAAACeQAAAAAGAwAAAAATTQMAGgAAAABNBQAaAAAAAIcEBQErBAIA/wQAAAAAAABqBAMBTQQAGgAAAACHAwQBqQQBAGoEAwLZAwAAEgAAABIAAQASAAIAggMCAAEDEAEJdC4BGAAAAAAAAAAAAAEAAAAAAgAAAAB1AAAAAAQBAQAAABZNAQDlAAAAAA4BAwBNAQDlAAAAAIIBAgD7AgAATQEC7wEAAACfAQECMAEA5QAAAABNAQDBAgAAAE0DAOUAAAAAvAEB/QMAAACfAQMBTQEA5QAAAACCAQIABAMvAwcDCAMoAJEBMAEYAAAAAQAAAwAAAAAAAQAAAAAAAAEAAJIAAAAABAEBAAAAFk0BAEwAAAAADgEDAE0BAEwAAAAAggECAPsCAABNAQLvAQAAAJ8BAQIwAQBMAAAAAE0BAMECAAAATQMATAAAAAC8AQH9AwAAAJ8BAwFNAQBMAAAAAIIBAgAEAzEDBwMIAygAnAEyARgAAAABAAADAAAAAAABAAAAAAAAAgAAnQAAAAAJAQAAAAAO/wEAAAAAAACkAgEAAAAAQE0DAD4CAAAAnwICBBcCAwAcCAEAlQcIA2oFAQduAvz/AgAAAIIBAgAEAyIEAAAAQAMOAgAAAAAAAPA/ALYBMwEYAAABAAAAAAABAAD/AAO3AAAAAAIBAAAAAANNAQA+AAAAAIIBAgABAw4AzgE0ARgAAADPAAAAAAcCAgAABwAAAQMDDQId+wIAALwCAgQAAAAAnwICAg4CDACkAgIAAAAQQG8DAwBNBQD/BAAAAKQGBwAAGFCAnwYBALwDA40IAAAAnwMAAJ8CAAH7AgEAUgQBAE0FAP8EAAAAvAICRQkAAACfAgQBUgQBALwCAH8KAAAAnwIDAIICAAALAxgDAgQAABBAAzUDBAM2AzcEABhQgAMFAzgDOQDWAToBGAAAAAAAAQABAQABAAD+AAD/CAAAAAAAAAEAAAAA1wAAAAAHAgIAAAcAAAEDAxwCKLssAQNSBQEApAQBAAAAAECfBAIC8AQCAAIAAACpAwABqQMBAIEBAwQDAAAAbwQDAKQCBQAAAEBAnwIDAfsCAAC8AgIEBgAAAJ8CAgIOAgwApAIIAAAAcEBvAwkATQUA/woAAACkBg0AADCwgJ8GAQC8AwONDgAAAJ8DAACfAgAB+wIBAFIEAQBNBQD/CgAAALwCAhcPAAAAnwIEAYIAAQAQAzsEAAAAQAM8Az0DPgQAAEBAAxgDAgQAAHBAAz8DBAM2AzcEADCwgAMFA0AA5QFBARgAAAAAAAAAAAAAAAAAAAACAAAAAAEAAQEAAQAA/gAA/wgAAAAAAAAB5gAAAAAGAgIAAAcAAAEDAwoCGvsCAAC8AgIEAAAAAJ8CAgIrAgkApAICAAAAEEBvAwMATQUA/wQAAAC8AwONBQAAAJ8DAwCfAgAB+wIBAFIEAQBNBQD/BAAAALwCAkUGAAAAnwIEAVIEAQC8AgB/BwAAAJ8CAwCCAgAACAMYAwIEAAAQQANCAwQDBQM4AzkA9wFDARgAAAAAAAEAAAAAAAAAAAMAAAAAAAABAAAAAPgAAAAABgIBAAAAF7ssAQNSBQEApAQBAAAAAECfBAIC8AQCAAIAAACpAwABqQMBAIEBAwQDAAAAbwQDAKQCBQAAAEBAnwIDAfsCAABSBAEATQUA/wYAAAC8AgIXBwAAAJ8CBAGCAAEACAM7BAAAAEADPANEAz4EAABAQAMEA0AAgQJFARgAAAAAAAAAAAAAAAAAAAABAAAAAAAAAQIBAAAABgIAAAAAE7ssAQNSBQEApAQBAAAAAECfBAIC8AQCAAIAAACpAwABqQMBAIEBAwQDAAAAbwQDAKQCBQAAAEBAnwIDAU0DAL4GAAAAhwIDAYICAgAHAzsEAAAAQAM8A0YDPgQAAEBAAw0AhwI5ARgAAAAAAAAAAAAAAAAAAAABAAAACAEAAAAGAgEAAAAUuywBA1IFAQCkBAEAAAAAQJ8EAgLwBAIAAgAAAKkDAAGpAwEAgQEDBAMAAABvBAMApAIFAAAAQECfAgMB+wIAAFIDAABSBAEAnwIDAIICAAAGAzsEAAAAQAM8A0YDPgQAAEBAAIwCRwEYAAAAAAAAAAAAAAAAAAAAAQAAAAANAQAAAAwCAAAADAAAAgMEdQIDBJIBAsYBuywBA1IFAQCkBAEAAAAAQJ8EAgLwBAIAAgAAAKkDAAGpAwEAgQEDBAMAAABvBAMApAIFAAAAQECfAgMBTQMAvgYAAACHAgMBDgIBAIIAAQBNAwAYBwAAAIcCAwEqAgYAAQAAgKQCCQAAAIBAbwMKAJ8CAgGCAAEATQIAGAcAAACpAwEAagMCAcYCAABNBACvCwAAALsoBAKkAw0AAADAQJ8DAgLwAw0ADgAAgE0DAK8LAAAAUgQBAE0GAA0PAAAAuzUGAqQFEQAAAABBnwUCAJ8DAAJSAgMAZQAgAE0EAK8LAAAATQMElhIAAAAOAw4ATQMArwsAAABSBQEATQcADQ8AAAC7NQcCpAYRAAAAAEGfBgIAvAMDlhIAAACfAwACUgIDAGUADQBNBACvCwAAAE0DBO8TAAAAUgQBAE0GAA0PAAAAuzUGAqQFEQAAAABBnwUCAJ8DAAJSAgMATQQAGAcAAACHAwQBKgMfAAEAAACkAwkAAACAQG8EFAC8BgGyFQAAAJ8GAgJNCgCvCwAAALsoCgKkCQ0AAADAQJ8JAgLwCQYAFgAAgE0JAK8LAAAATQgJ2xcAAAArCAIATQgArwsAAAC7PwgCpAcZAAAAgEGfBwICvAQEjRoAAACfBAQAnwMAAYIAAQBNAwAYBwAAAMYEAABqBAMBuygCA1IEAgCkAw0AAADAQJ8DAgLwAwkAFgAAgE0EAlAbAAAAuygEAqQDDQAAAMBAnwMCAvADCwAOAAAApAMJAAAAgEBvBBwATQYA/x0AAAC8BASNGgAAAJ8EAwCfAwABggABAE0GAL4GAAAAhwUGAUcFAgAAAAAAqQQAAakEAQCBAQQEHgAAAG8FHgCkAwUAAABAQJ8DAwFNAwA+HwAAAKkEAQBqBAMCTQMAvgYAAABqAgMBTQQAGiAAAACHAwQBDgMMAKQEIgAAABBCUgUDAJ8EAgQXBAUApAklAACQMIJSCgcAUgsCAJ8JAwFuBPr/AgAAAE0EAOUmAAAADgQHAE0EAOUmAAAAUgYCAFIHAQC8BATdJwAAAJ8EBAGCAAEAKAM7BAAAAEADPANGAz4EAABAQAMNAw8DAgQAAIBAA0gDDAMTBAAAwEADSQMRA0oEAAAAQQNLAwcDTANNAxQDFQNOBAAAgEEDBQNPA1ADBANRAw4DEAMiBAAAEEIDJAMlBACQMIIDLwNSAJECIAEYAAAAAAAAAAAAAAAAAAAAAgAAAAIDAAAAAAEAAAABAwAAAAIBAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAQAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAwAAAAADAAEBAAABAAAAAAAAAAAAAAAAAAAAAAAA/gAA/wYDAAAAAgAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAQMAAAAAAAAAAAAAAAADAAAAAQAAAwAAAQEAAAAAAQAAAAD/AAUAAAEAAAAAAAACEgEAAAAMAgAAAAcAAAEDBTwCQU0CABgAAAAAxgMAAGoDAgFNAwC+AQAAAIcCAwFHAgIAAAAAgIIAAQBNAwBMAgAAAA4DBwBNAwBMAgAAAFIFAgBSBgEAvAMD3QMAAACfAwQBTQMAvgEAAADGBAAAagQDAU0DAD4EAAAAxgQAAGoEAwJNBAAaBQAAAIcDBAEOAwwApAQHAAAAYEBSBQMAnwQCBBcEBQCkCQoAACSAgFIKBwDGCwAAnwkDAW4E+v8CAAAATQQCUAsAAAAOBAQAvAQCUAsAAACfBAIBggABAKQEDQAAAMBAbwUOAE0IAP8PAAAAuz8IAqQHEQAAAABBnwcCArwFBY0SAAAAnwUDAJ8EAAGCAAEAEwMPAw0DMQNSAw4DEAMiBAAAYEADJAMlBAAkgIADTwMCBAAAwEADUwMEA04EAAAAQQMFAM8CIQEYAAAAAAIAAAEAAQQAAAEAAAAAAAAEAAAAAQAAAAMAAAEBAAAAAAEAAAAA/wAGAAABAAAAAgABAQAAAAAA/wAA/wZQAQAAAAcBAAAAACakAQEAAAAAQE0CAL4CAAAAnwECA0cCGgAAAAAAUgUBALwDAJcDAAAAnwMDAU0GAL4CAAAAhwUGAUcFAgAAAAAAqQQAAakEAQCBAQQEBAAAAG8FBACkAwYAAABQQJ8DAwGkAwEAAAAAQE0EAL4CAAAAnwMCA1IBAwBSAgQASADl/00DAMEHAAAAvAMDUQgAAACfAwIBggABAAkDLQQAAABAAw0DIQNUAz4EAABQQAMIA1UA9QJPARgAAAAAAAEAAQAAAAEAAAAAAAAAAAAAAAACAAAAAAAA/AgAAAAAAXYBAAAACAAAAQIAd6MAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQEAAAAAQG8DBAC8AQEWAwAAAJ8BAwKkAgYAAABQQKQFCAAAAHBATQQFJAkAAABNAwR2CgAAAJ8CAgKkAwYAAABQQKQGCAAAAHBATQUGJAkAAABNBAUfCwAAAJ8DAgKkBAYAAABQQKQGCAAAAHBATQUGNQwAAACfBAIC/wUGAAAAAAAwBQVuDQAAAG8GDgAwBgXbDwAAAMAGEAASAAUAEgACADAGBe8RAAAAwAYSADAGBW0TAAAAwAYUABIAAADABxUAEgABABIAAAAwBwUcFgAAAMAHFwAwBwW3GAAAAMAHGQAwBwXTGgAAAMAHGwAwBwXMHAAAAMAHHQASAAMAMAcFBx4AAADABx8AEgADADAHBWcgAAAAwAchADAHBdAiAAAAwAcjADAHBX8kAAAAwAclABIAAAASAAEAMAcFiiYAAADABycAEgAAABIAAQAwBwXMKAAAAMAHKQASAAAAEgABADAHBUwqAAAAwAcrABIAAQAwBwXWLAAAAMAHLQAwBwV/LgAAAMAHLwASAAQAMAcFcjAAAADABzEAMAcFlTIAAADABzMAMAcFlzQAAADABzUAMAcFUDYAAACCBQIANwNWBAAAAEADVwNYA1kDWgQAAFBAA1sEAABwQANcA10DXgNfA2ADFgMVBgEDBwYCAxcGAwYGAyoGBwMrBggDLAYKAy4GCwMwBgwDMgYNAzMGDgM0Bg8DOgYQA0EGEQNDBhIDRQYTAzkGFANHBhUDIAYWAyEGFwNPFAECAwYHCAoLDA0ODxAREhMUFRYXAQABBQAEAAAAAAABAAAAAAACAAAAAAAAAAABAAAAAAAAAAAB9wAAAAAAGAABAAEAAAcAAAAAGgAABAAMAAAAABUAAAWbAAUAAB0AAAALAAAAGgAAGAAACAAAAAAPAAAAABIAAHgACgAAAAYAAAUAAAAFAAA+AAAmAAANAQAAAAkAAABlAAAAiAAAAAAY2qMDwjdTt9joZ2lWgiZq2Yl42XlyEwHcyfPeg3hNo5py/KXrZBZD9Q==

-- Decompiled by Krnl

local v_u_1 = game:GetService("RunService")
local v_u_2 = game:GetService("CollectionService")
local v_u_3 = require(script.Parent.Maid)
local v_u_4 = require(script.Parent.Signal)
local v_u_5 = require(script.promiseBoundClass)
local v_u_6 = {}
v_u_6.__index = v_u_6
v_u_6.ClassName = "Binder"
function v_u_6.new(p7, p8, ...)
	-- upvalues: (copy) v_u_6, (copy) v_u_3
	local v9 = v_u_6
	local v_u_10 = setmetatable({}, v9)
	v_u_10._maid = v_u_3.new()
	v_u_10._tagName = p7 or error("Bad argument \'tagName\', expected string")
	v_u_10._constructor = p8 or error("Bad argument \'constructor\', expected table or function")
	v_u_10._instToClass = {}
	v_u_10._allClassSet = {}
	v_u_10._pendingInstSet = {}
	v_u_10._listeners = {}
	v_u_10._args = { ... }
	delay(5, function()
		-- upvalues: (copy) v_u_10
		if not v_u_10._loaded then
			warn(("Binder %q is not loaded. Call :Start() on it!"):format(v_u_10._tagName))
		end
	end)
	return v_u_10
end
function v_u_6.isBinder(p11)
	local v12
	if type(p11) == "table" then
		v12 = p11.ClassName == "Binder"
	else
		v12 = false
	end
	return v12
end
function v_u_6.Start(p_u_13)
	-- upvalues: (copy) v_u_2, (copy) v_u_1
	if not p_u_13._loaded then
		p_u_13._loaded = true
		for _, v14 in pairs(v_u_2:GetTagged(p_u_13._tagName)) do
			if not v_u_1:IsClient() and (v14:IsA("Model") and v14.ModelStreamingMode == Enum.ModelStreamingMode.Default) then
				v14.ModelStreamingMode = Enum.ModelStreamingMode.Atomic
			end
			task.spawn(p_u_13._add, p_u_13, v14)
		end
		p_u_13._maid:GiveTask(v_u_2:GetInstanceAddedSignal(p_u_13._tagName):Connect(function(p15)
			-- upvalues: (ref) v_u_1, (copy) p_u_13
			if not v_u_1:IsClient() and (p15:IsA("Model") and p15.ModelStreamingMode == Enum.ModelStreamingMode.Default) then
				p15.ModelStreamingMode = Enum.ModelStreamingMode.Atomic
			end
			p_u_13:_add(p15)
		end))
		p_u_13._maid:GiveTask(v_u_2:GetInstanceRemovedSignal(p_u_13._tagName):Connect(function(p16)
			-- upvalues: (copy) p_u_13
			p_u_13:_remove(p16)
		end))
	end
end
function v_u_6.GetTag(p17)
	return p17._tagName
end
function v_u_6.GetConstructor(p18)
	return p18._constructor
end
function v_u_6.ObserveInstance(p_u_19, p_u_20, p_u_21)
	p_u_19._listeners[p_u_20] = p_u_19._listeners[p_u_20] or {}
	p_u_19._listeners[p_u_20][p_u_21] = true
	return function()
		-- upvalues: (copy) p_u_19, (copy) p_u_20, (copy) p_u_21
		if p_u_19._listeners[p_u_20] then
			p_u_19._listeners[p_u_20][p_u_21] = nil
			if not next(p_u_19._listeners[p_u_20]) then
				p_u_19._listeners[p_u_20] = nil
			end
		end
	end
end
function v_u_6.GetClassAddedSignal(p22)
	-- upvalues: (copy) v_u_4
	if p22._classAddedSignal then
		return p22._classAddedSignal
	end
	p22._classAddedSignal = v_u_4.new()
	p22._maid:GiveTask(p22._classAddedSignal)
	return p22._classAddedSignal
end
function v_u_6.GetClassRemovingSignal(p23)
	-- upvalues: (copy) v_u_4
	if p23._classRemovingSignal then
		return p23._classRemovingSignal
	end
	p23._classRemovingSignal = v_u_4.new()
	p23._maid:GiveTask(p23._classRemovingSignal)
	return p23._classRemovingSignal
end
function v_u_6.GetAll(p24)
	local v25 = {}
	for v26, _ in pairs(p24._allClassSet) do
		v25[#v25 + 1] = v26
	end
	return v25
end
function v_u_6.GetAllSet(p27)
	return p27._allClassSet
end
function v_u_6.Bind(p28, p29)
	-- upvalues: (copy) v_u_1, (copy) v_u_2
	if v_u_1:IsClient() then
		warn(("[Binder.Bind] - Bindings \'%s\' done on the client! Will be disrupted upon server replication! %s"):format(p28._tagName, debug.traceback()))
	end
	v_u_2:AddTag(p29, p28._tagName)
	return p28:Get(p29)
end
function v_u_6.Unbind(p30, p31)
	-- upvalues: (copy) v_u_1, (copy) v_u_2
	local v32 = typeof(p31) == "Instance"
	assert(v32, "Bad inst\'")
	if v_u_1:IsClient() then
		warn(("[Binder.Bind] - Unbinding \'%s\' done on the client! Might be disrupted upon server replication! %s"):format(p30._tagName, debug.traceback()))
	end
	v_u_2:RemoveTag(p31, p30._tagName)
end
function v_u_6.BindClient(p33, p34)
	-- upvalues: (copy) v_u_1, (copy) v_u_2
	if not v_u_1:IsClient() then
		warn(("[Binder.BindClient] - Bindings \'%s\' done on the server! Will be replicated!"):format(p33._tagName))
	end
	v_u_2:AddTag(p34, p33._tagName)
	return p33:Get(p34)
end
function v_u_6.UnbindClient(p35, p36)
	-- upvalues: (copy) v_u_2
	local v37 = typeof(p36) == "Instance"
	assert(v37, "Bad inst")
	v_u_2:RemoveTag(p36, p35._tagName)
end
function v_u_6.Get(p38, p39)
	local v40 = typeof(p39) == "Instance"
	assert(v40, "Argument \'inst\' is not an Instance")
	return p38._instToClass[p39]
end
function v_u_6.Promise(p41, p42)
	-- upvalues: (copy) v_u_5
	local v43 = typeof(p42) == "Instance"
	assert(v43, "Argument \'inst\' is not an Instance")
	return v_u_5(p41, p42)
end
function v_u_6._add(p44, p45)
	local v46 = typeof(p45) == "Instance"
	assert(v46, "Argument \'inst\' is not an Instance")
	if p44._instToClass[p45] then
		return
	elseif p44._pendingInstSet[p45] == true then
		warn("[Binder._add] - Reentered add. Still loading, probably caused by error in constructor.")
		return
	else
		p44._pendingInstSet[p45] = true
		local v47 = p44._constructor
		local v48
		if type(v47) == "function" then
			local v49 = p44._constructor
			local v50 = p44._args
			v48 = v49(p45, unpack(v50))
		elseif p44._constructor.Create then
			local v51 = p44._constructor
			local v52 = p44._args
			v48 = v51:Create(p45, unpack(v52))
		else
			local v53 = p44._constructor.new
			local v54 = p44._args
			v48 = v53(p45, unpack(v54))
		end
		if p44._pendingInstSet[p45] == true then
			p44._pendingInstSet[p45] = nil
			if type(v48) == "table" then
				local v55 = v48.Destroy
				if type(v55) == "function" then
					local v56 = p44._instToClass[p45] == nil
					assert(v56, "Overwrote")
					p44._allClassSet[v48] = true
					p44._instToClass[p45] = v48
					local v57 = p44._listeners[p45]
					if v57 then
						for v58, _ in pairs(v57) do
							task.spawn(v58, v48)
						end
					end
					if p44._classAddedSignal then
						p44._classAddedSignal:Fire(v48, p45)
					end
					return
				end
			end
			warn(("[Binder._add] - Bad class constructed for tag %q"):format(p44._tagName))
		else
			local v59 = warn
			local v60 = p45:GetFullName()
			local v61 = p44._constructor
			local v62 = type(v61) == "table" and p44._constructor.ClassName or p44._constructor
			v59(("[Binder._add] - Failed to load instance %q of %q, removed while loading!"):format(v60, (tostring(v62))))
		end
	end
end
function v_u_6._remove(p63, p64)
	p63._pendingInstSet[p64] = nil
	local v65 = p63._instToClass[p64]
	if v65 == nil then
		return
	else
		if p63._classRemovingSignal then
			p63._classRemovingSignal:Fire(v65, p64)
		end
		p63._instToClass[p64] = nil
		p63._allClassSet[v65] = nil
		local v66 = p63._listeners[p64]
		if v66 then
			for v67, _ in pairs(v66) do
				task.spawn(v67, nil)
			end
		end
		if v65.Destroy then
			v65:Destroy()
		else
			local v68 = warn
			local v69 = p63._tagName
			v68(("[Binder._remove] - Class %q no longer has destroy, something destroyed it!"):format((tostring(v69))))
		end
	end
end
function v_u_6.Destroy(p70)
	local v71, v72 = next(p70._instToClass)
	while v72 ~= nil do
		p70:_remove(v71)
		local v73 = p70._instToClass[v71] == nil
		assert(v73, "Failed to remove")
		v71, v72 = next(p70._instToClass)
	end
	p70._maid:DoCleaning()
end
return v_u_6
