-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMaBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplEExFVkVMX1ZBTFVFX05BTUUORVhQX1ZBTFVFX05BTUUJTUFYX0xFVkVMC0VYUF9ST0JCRVJZCkVYUF9BUlJFU1QIRVhQX0tJTEwSREFJTFlfRVhQX0RVUkFUSU9OGURBSUxZX0VYUF9EVVJBVElPTl9PRkZTRVQUREFJTFlfRVhQX1ZBTFVFX05BTUUNTUFYX0RBSUxZX0VYUBlNQVhfREFJTFlfRVhQX1NFQVNPTl9QQVNTFEFWR19FWFBfUEVSX0NPTlRSQUNUClRPVEFMX0RBWVMRQ09OVFJBQ1RTX1BFUl9EQVkKRUZGSUNJRU5DWQdDVVJWRV9LBUxldmVsA0V4cA5EYWlseUV4cEVhcm5lZAABBQAAAQIAQ6MAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DAKEGAAAATQIDGAcAAACfAQICTQIBAAgAAADiAxkAbwQaADAEAw0JAAAAbwQbADAEA2sKAAAAjARjADAEAyQLAAAAjAQUADAEA9IMAAAAjAQPADAEA8gNAAAAjAQKADAEAwQOAAAAbwQcADAEAx4PAAAAbwQdADAEA/gQAAAAbwQeADAEA1QRAAAAjARQADAEA/4SAAAAjAR4ADAEA40TAAAAjAQqADAEA1EUAAAAjAQ8ADAEA1UVAAAAbwQfADAEA6AWAAAAbwQgADAEAwQXAAAAbwQhADAEAz0YAAAAnwICAIICAAAiAwEEAAAAQAMCAwMDBAQAAEBAAwUDBgMHAwgDCQMKAwsDDAMNAw4DDwMQAxEDEgMTAxQDFQMWAxcFEAkKCwwNDg8QERITFBUWFxgDGAMZAgAAAAAAGPVAAgAAAAAA2uZAAxoCkiRJkiRJ4j8CMzMzMzMz4z8CMzMzMzMz8z8AAQABGAABAAAAAAABAAAAAAAADgAAAQAAAQAAAgAAAgAAAQAAAQAAAgAAAQAAAgAAAQAAAQAAAgAAAgAAAgAAAgAAAwAA5gABAAAAAACw5i74UzRB5oIiRGyP4q1Od4IfcOBe+oox1526u1Z1bC5owI/N0Z0m

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Std.TableUtils).requireValidIndexAndFreeze({
	["LEVEL_VALUE_NAME"] = "Level",
	["EXP_VALUE_NAME"] = "Exp",
	["MAX_LEVEL"] = 99,
	["EXP_ROBBERY"] = 20,
	["EXP_ARREST"] = 15,
	["EXP_KILL"] = 10,
	["DAILY_EXP_DURATION"] = 86400,
	["DAILY_EXP_DURATION_OFFSET"] = 46800,
	["DAILY_EXP_VALUE_NAME"] = "DailyExpEarned",
	["MAX_DAILY_EXP"] = 80,
	["MAX_DAILY_EXP_SEASON_PASS"] = 120,
	["AVG_EXP_PER_CONTRACT"] = 42,
	["TOTAL_DAYS"] = 60,
	["CONTRACTS_PER_DAY"] = 0.5714285714285714,
	["EFFICIENCY"] = 0.6,
	["CURVE_K"] = 1.2
})
