-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNXDnVwZGF0ZVByb2dyZXNzClN0YXJ0ZXJHdWkJTGV2ZWxHdWkyDkZpbmRGaXJzdENoaWxkCVBsYXllckd1aQZQYXJlbnQDZ3VpBmhpZGRlbgdFbmFibGVkF2dldE9uTGV2ZWxDaGFuZ2VkU2lnbmFsB0Nvbm5lY3QVZ2V0T25FeHBDaGFuZ2VkU2lnbmFsCkJhY2tncm91bmQEQm9keQlTZWFzb25OdW0JU0VBU09OICVkClNFQVNPTl9OVU0GZm9ybWF0BFRleHQKSW5mb0J1dHRvbhBNb3VzZUJ1dHRvbjFEb3duCnRvZ2dsZUluZm8YZ2V0U2Vhc29uUGFzc093bmVkU2lnbmFsBGluaXQLT2JqZWN0TG9jYWwbSEFTX1NFRU5fUkVXQVJEU19WQUxVRV9OQU1FB193aW5kb3cGSXNPcGVuBWNsb3NlBVZhbHVlEGdldFJlbWFpbmluZ1RpbWUEb3BlbghnZXRMZXZlbAZnZXRFeHALc2V0UHJvZ3Jlc3MFVURpbTIJZnJvbVNjYWxlBFNpemUIUG9zaXRpb24BWAVTY2FsZQNuZXcERW51bQ9FYXNpbmdEaXJlY3Rpb24DT3V0C0Vhc2luZ1N0eWxlBFF1YWQJVHdlZW5TaXplHHR3ZWVuRnJhbWVGcm9tTGFzdEZyYWNUb0ZyYWMVY2FsY3VsYXRlRXhwTmV4dExldmVsCFByb2dyZXNzDVByb2dyZXNzRGFpbHkFTGV2ZWwITEVWRUwgJWQLRXhwUHJvZ3Jlc3MFJWQvJWQNTUFYX0RBSUxZX0VYUBdkb2VzUGxheWVyT3duU2Vhc29uUGFzcxlNQVhfREFJTFlfRVhQX1NFQVNPTl9QQVNTEGdldFNlYXNvbkV4cE11bHQLTG9jYWxQbGF5ZXIUREFJTFlfRVhQX1ZBTFVFX05BTUUFSGVscDEHVmlzaWJsZQRtYXRoA21pbg1Ud2VlblBvc2l0aW9uCmhpZGVUb3BiYXIEZ2FtZQdQbGF5ZXJzCkdldFNlcnZpY2URUmVwbGljYXRlZFN0b3JhZ2UHcmVxdWlyZQNTdGQFQXVkaW8MU2Vhc29uQ29uc3RzBEdhbWUGU2Vhc29uDlNlYXNvblVJU3lzdGVtC1NlYXNvblV0aWxzEENvbnRyYWN0VUlTeXN0ZW0IQ29udHJhY3QMU2Vhc29uU3lzdGVtC0xldmVsU3lzdGVtBnNjcmlwdAtMZXZlbENvbnN0cwpMZXZlbFV0aWxzAAgDAQIAAAAK+wEAAPEAAgABAAAAggABAPsCAQBNAQIuAAAAAPsCAACfAQIBggABAAEDAQAmAAEYAAAAAQIAAAAAAScAAAAABgAGAAAHAAABAwI4AmL7AQAATQABCwAAAABvAgEAvAAAAwIAAACfAAMC+wIBAE0BApkDAAAAMAEAJAQAAAD7AQIAMAABfwUAAAD7AwIATQIDlgYAAABWAQIAMAEA8AcAAAD7AgIATQECLggAAAD7AgEAnwECAfsCAwBNAQI5CQAAAJ8BAQL7BAIATQMELggAAAC8AQHHCgAAAJ8BAwH7AgMATQECKwsAAACfAQEC+wQCAE0DBC4IAAAAvAEBxwoAAACfAQMBTQMA7QwAAABNAgNnDQAAAE0BAlAOAAAAbwIPAPsFBABNBAXGEAAAALwCAo0RAAAAnwIDAjACAfUSAAAATQQA7QwAAABNAwRnDQAAAE0CA6ETAAAATQECYRQAAAD7BAIATQMETxUAAAC8AQHHCgAAAJ8BAwFNAwDtDAAAAE0CA2cNAAAATQECYRQAAAD7BAIATQMETxUAAAC8AQHHCgAAAJ8BAwH7AgUATQECvBYAAACfAQECwAMXABICAQASAgIAvAEBxwoAAACfAQMBggABABgDAgMDAwQDBQMGAwcDCAMJAwEDCgMLAwwDDQMOAw8DEAMRAxIDEwMUAxUDFgMXBgABABMYARgAAAAAAAAAAQAAAAABAAABAAAAAAACAAAAAAEAAAAAAAAAAAABAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAHAAAAAAAAAAAABhQAAAAABAAGAAAAN/sBAABNAAHRAAAAAPsCAQBNAQKZAQAAAG8CAgCfAAMB+wABAPsDAgBNAgPYAwAAALwAAAMEAAAAnwADAvsCAwBNAQKnBQAAALwBATEGAAAAnwECAg4BBQD7AgMATQECgwcAAACfAQEBggABAPsCBABNAQKnBQAAALwBATEGAAAAnwECAg4BBQD7AgQATQECgwcAAACfAQEBggABAPsBBABNAgDsCAAAAA4CBwD7AwUATQIDnAkAAACfAgECjAMAAH0CAgADAAAA+wEDAE0CAXYKAAAAnwIBAYIAAQALAxkDBQIAAGAyn772QQMaAwQDGwMcAx0DHgMfAyAALRYBGAAAAAAAAAAAAQAAAAAAAAMAAAAAAAABAAAAAAEAAAAAAAABAAAAAAIBAAAAAAAAAAAAAQIAAAIuAAAAAAYBAwAAABb7AQAAmgATAAEAAAD7AgEATQEC4gAAAABSAgAAnwECAvsDAQBNAgP7AQAAAFIDAACfAgICDgEHAA4CBgD7BAIATQMEPwIAAABSBAEAUgUCAJ8DAwGCAAEAAwMhAyIDIwA+AQEYAAAAAQAAAAABAAAAAAEAAQAAAAAAAz8AAAAADQMAAAAIBQAABQMHAgEsDgIOAKQDAgAABACAjAQAAIwFAQCfAwMCMAMALwMAAACkAwIAAAQAgIwEAACMBQAAnwMDAjADADsEAAAATQUALwMAAABNBAV5BQAAAE0DBIQGAAAAYAMDAAEAAAAmBAEDKwQBAFIEAQA+BQQHpAgJAAAgAIBSCQEAjAoAAIwLAQCMDAAAnwgFAqQJDQAMLKDApAoQAA84oMBSCwUAqQwBALwGANQRAAAAnwYHAYIFAgASAyQDJQQABACAAyYDJwMoAykCAAAAAAAA8D8DKgQAIACAAysDLAMtBAwsoMADLgMvBA84oMADMABHMQEYAAEAAAAAAAABAAAAAAAAAgAAAAAAAQAAAAACAQAAAAAAAAAAAAAAAAAAAAFIAAAAABICBwAACwAAAgMJYgIDCXAC2wH7AwAATQID3AAAAABSAwAAnwICAuwDAQL7BQEATQQFfwEAAABNCgTtAgAAAE0JCmcDAAAATQgJ5AQAAABNBwgvBQAAAE0GB3kGAAAATQUGhAcAAABgAygABQAAAE0IBO0CAAAATQcIZwMAAABNBgfkBAAAAKQHCgAAJICAjAgAAIwJAQCfBwMCMAcGLwUAAABNCATtAgAAAE0HCGcDAAAATQYH5AsAAACkBwoAACSAgIwIAACMCQEAnwcDAjAHBi8FAAAATQgE7QIAAABNBwhnAwAAAE0GB+QLAAAApAcKAAAkgICMCAAAjAkAAJ8HAwIwBwY7DAAAAGAFAwADAAAAJgYDBSsGAQBSBgMAPgcGDU0KBO0CAAAATQkKZwMAAABNCAnkBAAAAKQKDwAAOICAUgsDAIwMAACMDQEAjA4AAJ8KBQKkCxMAEkQAwaQMFgAVUADBUg0HAKkOAQC8CAjUFwAAAJ8IBwFNCgTtAgAAAE0JCmcDAAAATQgJbRgAAABvCRkAUgsAALwJCY0aAAAAnwkDAjAJCPUbAAAATQoE7QIAAABNCQpnAwAAAE0ICYEcAAAAbwkdAFILAQBSDAIAvAkJjRoAAACfCQQCMAkI9RsAAAD7CQIATQgJ/h4AAAD7CgMATQkKlx8AAAD7CgQAnwkCAg4JAwD7CQIATQgJjSAAAAD7CgUATQkKuCEAAACfCQECCQgICfsKBQBNCQqcIgAAAJ8JAQKMCgAAYAkCAAoAAACMCAAA+woGAE0JCjEjAAAA+wwCAE0LDFQkAAAAvAkJAyUAAACfCQMCDgkDAE0KCewmAAAAJggICk0MBO0CAAAATQsMZwMAAABNCgsBJwAAAG8MKAC3DAIACAAAAKkLAAGpCwEAMAsKgCkAAACMCwEAQw0BCOwMDQKeEwsDDAAAAKQKLAAArKCCnwoDAk0NBO0CAAAATQwNZwMAAABNCwzkCwAAAKQNDwAAOICAJg4KA4wPAACMEAEAjBEAAJ8NBQKkDhMAEkQAwaQPFgAVUADBUhAHAKkRAQC8CwvUFwAAAJ8LBwFNDQTtAgAAAE0MDWcDAAAATQsM5AsAAACkDQoAACSAgFIOAwCMDwAAnw0DAqQOEwASRADBpA8WABVQAMFSEAcAqREBALwLCz0tAAAAnwsHAYIAAQAuAzIDBwMNAw4DMwMmAygDKQMkAyUEACSAgAM0AycCAAAAAAAA8D8DKgQAOICAAysDLAMtBBJEAMEDLgMvBBVQAMEDMAM1AzYDEgMTAzcDOAM5AzoDOwM8Ax8DPQM+AwQDHgM/Avyp8dJNYlA/A0ADQQNCBACsoIIDQwBTIwEYAAAAAAABAQAAAQAAAAAAAAAAAAAAAQABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAACAAAAAAIBAAAAAAABAAAAAAAAAQABAAEB+wAACAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAgAAAQAAAAAAAQAAAgAAAAABAAAAAAAAAQIAAAAAAAAAAAEBAAACAAAAAAAAAAAAAAAAAgAAAAAAAAABAAAAAAABAAAAAAAAAQABAAEB+wAABwAAAAAAAQAAAAABAAEAAQH7AAAHVAAAAAAEAAEAAAAS+wAAAKkBAQAwAQCWAAAAAPsBAABNAAF/AQAAAA4ACQD7AQAATQABfwEAAAD7AwAATQIDlgAAAABWAQIAMAEA8AIAAACCAAEAAwMIAwcDCQCJAUQBGAAAAAABAAAAAQAAAAAAAAAAAooAAAAADwAAAQIAjgGjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCTQEAMQQAAACkAgEAAAAAQG8EBQC8AgIWAwAAAJ8CAwKkAwcAAABgQE0FAqEIAAAATQQF0gkAAACfAwICpAQHAAAAYEBNBwK9CwAAAE0GB4YMAAAATQUGvAoAAACfBAICpAUHAAAAYEBNCAK9CwAAAE0HCIYMAAAATQYHrA0AAACfBQICpAYHAAAAYEBNCQK9CwAAAE0ICYYMAAAATQcI8g4AAACfBgICpAcHAAAAYEBNCgK9CwAAAE0JCmAQAAAATQgJSg8AAACfBwICpAgHAAAAYEBNCwK9CwAAAE0KC4YMAAAATQkKSxEAAACfCAICpAkHAAAAYECkDBQAAAAwQU0LDCQVAAAATQoL7BIAAACfCQICpAoHAAAAYECkDRQAAAAwQU0MDSQVAAAATQsMthYAAACfCgICpAsHAAAAYECkDhQAAAAwQU0NDiQVAAAATQwN8BcAAACfCwIC/wwEAAAAAADGDQAAMA0MfxgAAACpDQAAMA0MlhkAAADADRoAEgACABIAAQASAAwAEgAJABIABAASAAgAMA0MExsAAADADRwAEgADABIAAQASAAQAEgAFABIABwASAAYAMA0MTx0AAADADR4AEgABABIACwASAAwAMA0MLh8AAADADSAAwA4hABIACwASAAwAEgAKABIACAASAAEAEgAGABIAAAAwDgw/IgAAAMAOIwASAAwAMA4MlyQAAACCDAIAJQNFBAAAAEADRgNHAz0DSANJBAAAYEADSgNLA0wDTQNOA08DUANRA1IDUwNUA1UEAAAwQQMGA1YDVwMHAwgGAQMYBgIDFgYDAwEGBAYFAyMGBgNEBgECAwQFBgEAARgAAQAAAAAAAQABAAAAAAABAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAgAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAgABAAABAAABAAAAAAAAAAAaAAAAAAAAAAARAAAAAAAJDAAAAAAAAAAAADYAAAAHAQAAAAAHr7uRsoFhV9ydf/smEez0CmZjDMyyP05fJBtcygbAbBA4RXqAZBPzpA==

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players")
local v_u_2 = v_u_1.LocalPlayer
local v_u_3 = game:GetService("ReplicatedStorage")
local v_u_4 = require(v_u_3.Std.Audio)
local v_u_5 = require(v_u_3.Game.Season.SeasonConsts)
local v_u_6 = require(v_u_3.Game.Season.SeasonUISystem)
local v_u_7 = require(v_u_3.Game.Season.SeasonUtils)
local v_u_8 = require(v_u_3.Game.Contract.ContractUISystem)
local v_u_9 = require(v_u_3.Game.Season.SeasonSystem)
local v_u_10 = require(script.Parent.LevelSystem)
local v_u_11 = require(script.Parent.LevelConsts)
local v_u_12 = require(script.Parent.LevelUtils)
local v_u_34 = {
	["gui"] = nil,
	["hidden"] = false,
	["init"] = function()
		-- upvalues: (copy) v_u_3, (copy) v_u_2, (copy) v_u_34, (copy) v_u_10, (copy) v_u_5, (copy) v_u_9
		local v13 = v_u_3.StarterGui:FindFirstChild("LevelGui2")
		v13.Parent = v_u_2.PlayerGui
		v_u_34.gui = v13
		v13.Enabled = not v_u_34.hidden
		v_u_34.updateProgress(v_u_2)
		v_u_10.getOnLevelChangedSignal():Connect(v_u_34.updateProgress)
		v_u_10.getOnExpChangedSignal():Connect(v_u_34.updateProgress)
		v13.Background.Body.SeasonNum.Text = ("SEASON %d"):format(v_u_5.SEASON_NUM)
		v13.Background.Body.InfoButton.MouseButton1Down:Connect(v_u_34.toggleInfo)
		v13.Background.Body.MouseButton1Down:Connect(v_u_34.toggleInfo)
		v_u_9.getSeasonPassOwnedSignal():Connect(function(p14)
			-- upvalues: (ref) v_u_2, (ref) v_u_34
			if p14 == v_u_2 then
				v_u_34.updateProgress(v_u_2)
			end
		end)
	end,
	["toggleInfo"] = function()
		-- upvalues: (copy) v_u_4, (copy) v_u_2, (copy) v_u_5, (copy) v_u_6, (copy) v_u_8, (copy) v_u_7
		v_u_4.ObjectLocal(v_u_2.PlayerGui, 6105461542)
		local v15 = v_u_2:FindFirstChild(v_u_5.HAS_SEEN_REWARDS_VALUE_NAME)
		if v_u_6._window:IsOpen() then
			v_u_6.close()
			return
		elseif v_u_8._window:IsOpen() then
			v_u_8.close()
		else
			local v16 = v_u_8
			if not v15.Value or v_u_7.getRemainingTime() <= 0 then
				v16 = v_u_6
			end
			v16.open()
		end
	end,
	["updateProgress"] = function(p17)
		-- upvalues: (copy) v_u_2, (copy) v_u_12, (copy) v_u_34
		if p17 == v_u_2 then
			local v18 = v_u_12.getLevel(p17)
			local v19 = v_u_12.getExp(p17)
			if v18 and v19 then
				v_u_34.setProgress(v18, v19)
			end
		end
	end,
	["setProgress"] = function(p20, p21)
		-- upvalues: (copy) v_u_12, (copy) v_u_34, (copy) v_u_11, (copy) v_u_9, (copy) v_u_2, (copy) v_u_7, (copy) v_u_1
		local v22 = v_u_12.calculateExpNextLevel(p20)
		local v23 = p21 / v22
		local v24 = v_u_34.gui
		local v25 = v24.Background.Body.Progress.Size.X.Scale
		if v23 < v25 then
			v24.Background.Body.Progress.Size = UDim2.fromScale(0, 1)
			v24.Background.Body.ProgressDaily.Size = UDim2.fromScale(0, 1)
			v24.Background.Body.ProgressDaily.Position = UDim2.fromScale(0, 0)
		end
		local v26
		if v25 < v23 then
			v26 = v23 - v25 or v23
		else
			v26 = v23
		end
		local v27 = v26 / 1
		v24.Background.Body.Progress:TweenSize(UDim2.new(v23, 0, 1, 0), Enum.EasingDirection.Out, Enum.EasingStyle.Quad, v27, true)
		v24.Background.Body.Level.Text = ("LEVEL %d"):format(p20)
		v24.Background.Body.ExpProgress.Text = ("%d/%d"):format(p21, v22)
		local v28 = v_u_11.MAX_DAILY_EXP
		if v_u_9.doesPlayerOwnSeasonPass(v_u_2) then
			v28 = v_u_11.MAX_DAILY_EXP_SEASON_PASS
		end
		local v29 = v28 * v_u_7.getSeasonExpMult()
		local v30 = v_u_7.getRemainingTime() < 0 and 0 or v29
		local v31 = v_u_1.LocalPlayer:FindFirstChild(v_u_11.DAILY_EXP_VALUE_NAME)
		if v31 then
			v30 = v30 - v31.Value
		end
		v24.Background.Body.Help1.Visible = v30 > 0.001
		local v32 = (p21 + v30) / v22
		local v33 = math.min(1, v32)
		v24.Background.Body.ProgressDaily:TweenSize(UDim2.new(v33 - v23, 0, 1, 0), Enum.EasingDirection.Out, Enum.EasingStyle.Quad, v27, true)
		v24.Background.Body.ProgressDaily:TweenPosition(UDim2.fromScale(v23, 0), Enum.EasingDirection.Out, Enum.EasingStyle.Quad, v27, true)
	end,
	["hideTopbar"] = function()
		-- upvalues: (copy) v_u_34
		v_u_34.hidden = true
		if v_u_34.gui then
			v_u_34.gui.Enabled = not v_u_34.hidden
		end
	end
}
return v_u_34
