-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMMBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplCFRBR19OQU1FDlJBTktfQVRUUl9OQU1FEFVQREFURV9GUkVRVUVOQ1kLVG9wQ3Jld0ZsYWcIQ3Jld1JhbmsAAQUAAAECAByjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CAxgHAAAAnwECAk0CAQAIAAAA4gMMAG8EDQAwBAO0CQAAAG8EDgAwBAPHCgAAAIwEHgAwBAOkCwAAAJ8CAgCCAgAADwMBBAAAAEADAgMDAwQEAABAQAMFAwYDBwMIAwkDCgUDCQoLAwsDDAABAAEYAAEAAAAAAAEAAAAAAAABAAABAAABAAABAAD9AAEAAAAAAEgdZOkIz1kketkOfWNZ9mYEZepm1bVRlyNW972gKZxh/a0c8lhJIRs=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Std.TableUtils).requireValidIndexAndFreeze({
	["TAG_NAME"] = "TopCrewFlag",
	["RANK_ATTR_NAME"] = "CrewRank",
	["UPDATE_FREQUENCY"] = 30
})
