-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMMBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplCFRBR19OQU1FDlJBTktfQVRUUl9OQU1FEFVQREFURV9GUkVRVUVOQ1kPVG9wQ3Jld0J1aWxkaW5nCENyZXdSYW5rAAEFAAABAgAcowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAoQYAAABNAgMYBwAAAJ8BAgJNAgEACAAAAOIDDABvBA0AMAQDtAkAAABvBA4AMAQDxwoAAACMBB4AMAQDpAsAAACfAgIAggIAAA8DAQQAAABAAwIDAwMEBAAAQEADBQMGAwcDCAMJAwoFAwkKCwMLAwwAAQABGAABAAAAAAABAAAAAAAAAQAAAQAAAQAAAQAA/QABAAAAAAD8SV6l+xLSRc6NNDHBIHS7vq9LER+3g6ZuYGk4p/yMC9oCpbjeoUmP

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Std.TableUtils).requireValidIndexAndFreeze({
	["TAG_NAME"] = "TopCrewBuilding",
	["RANK_ATTR_NAME"] = "CrewRank",
	["UPDATE_FREQUENCY"] = 30
})
