-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMlBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlB1JvYmJlcnkNUm9iYmVyeUNvbnN0cwNTdGQKVGFibGVVdGlscxpyZXF1aXJlVmFsaWRJbmRleEFuZEZyZWV6ZQpNQVhfQk9VTlRZG1JPQURTUElLRV9CT1VOVFlfUEVSQ0VOVEFHRTJERUZBVUxUX0NSSU1JTkFMX01PTkVZX0VBUk5FRF9UT19CT1VOVFlfUFJPUE9SVElPTjtST0JCRVJZX0NSSU1JTkFMX01PTkVZX0VBUk5FRF9UT19CT1VOVFlfUFJPUE9SVElPTl9PVkVSUklERR1ST0JCRVJZX1RPX01JTklNVU1fQk9VTlRZX01BUBlNVVNFVU1fQVNTSVNUX0JPVU5UWV9NVUxUElBPTElDRV9LSUxMX0JPVU5UWSJTTUFMTF9WSVBfU0VSVkVSX0JPVU5UWV9NVUxUSVBMSUVSGVNNQUxMX1ZJUF9TRVJWRVJfTUFYX1NJWkUpQVZFUkFHRV9CT1VOVFlfU1RFUF9TSVpFX0ZPUl9OT1RJRklDQVRJT04dTk9USUZJQ0FUSU9OX0NPT0xET1dOX1NFQ09ORFMMRU5VTV9ST0JCRVJZC01PTkVZX1RSVUNLC1RSQUlOX0NBUkdPD1RSQUlOX1BBU1NFTkdFUgpDQVJHT19TSElQC1NUT1JFX0RPTlVUCVNUT1JFX0dBUwtDQVJHT19QTEFORQtQT1dFUl9QTEFOVAdKRVdFTFJZBk1VU0VVTQRCQU5LBFRPTUILQ1JPV05fSkVXRUwHTUFOU0lPTgVCQU5LMgdPSUxfUklHAAEIAAABAgCjAaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DAAQGAAAATQIDWAcAAACfAQICpAIFAAAAQEBNBAChCAAAAE0DBBgJAAAAnwICAk0DAgAKAAAA4gQWAIwFIE4wBQQdCwAAAG8FFwAwBQRrDAAAAG8FGAAwBQRlDQAAAP8FAQAAAAAATQcBmxkAAABNBge6GgAAAIwHAABqBwUGMAUEEQ4AAAD/BQUAAAAAAE0HAZsZAAAATQYHpxsAAACMByADagcFBk0HAZsZAAAATQYHthwAAACMByADagcFBk0HAZsZAAAATQYHxB0AAACMByADagcFBk0HAZsZAAAATQYHtR4AAACMB/QBagcFBk0HAZsZAAAATQYHAx8AAACMB/QBagcFBk0HAZsZAAAATQYHyiAAAACMB9wFagcFBk0HAZsZAAAATQYHEyEAAACMB+gDagcFBk0HAZsZAAAATQYHuhoAAACMBwAAagcFBk0HAZsZAAAATQYHbCIAAACMB+gDagcFBk0HAZsZAAAATQYHRCMAAACMB+IEagcFBk0HAZsZAAAATQYHgyQAAACMB9wFagcFBk0HAZsZAAAATQYHqyUAAACMB9wFagcFBk0HAZsZAAAATQYH8CYAAACMB9wFagcFBk0HAZsZAAAATQYHPCcAAACMB9AHagcFBk0HAZsZAAAATQYH9igAAACMB9wFagcFBk0HAZsZAAAATQYHfykAAACMB9YGagcFBjAFBIsPAAAAbwUXADAFBDQQAAAAjAX6ADAFBLIRAAAAbwUXADAFBCISAAAAjAUKADAFBE8TAAAAjAWgDzAFBCEUAAAAjAU8ADAFBCMVAAAAnwMCAIIDAAAqAwEEAAAAQAMCAwMDBAQAAEBAAwUDBgMHAwgDCQMKAwsDDAMNAw4DDwMQAxEDEgMTAxQFCwsMDQ4PEBESExQVApqZmZmZmbk/AjMzMzMzM9M/AxUDFgMXAxgDGQMaAxsDHAMdAx4DHwMgAyEDIgMjAyQDJQABAAEYAAEAAAAAAAEAAAAAAAABAAAAAAAAAQAAAQAAAQAAAQAAAQABAAAAAAD/AAMAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAA8AASAAABAAABAAABAAABAAABAADiAAEAAAAAABh5Fl5VsWKsKr18ygwp3XkURc4RHmDwAO4TFAuL3PTtHi02yUvJE+g=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v2 = require(v1.Robbery.RobberyConsts)
local v3 = require(v1.Std.TableUtils).requireValidIndexAndFreeze
local v4 = {
	["MAX_BOUNTY"] = 20000,
	["ROADSPIKE_BOUNTY_PERCENTAGE"] = 0.1,
	["DEFAULT_CRIMINAL_MONEY_EARNED_TO_BOUNTY_PROPORTION"] = 0.3,
	["ROBBERY_CRIMINAL_MONEY_EARNED_TO_BOUNTY_PROPORTION_OVERRIDE"] = {
		[v2.ENUM_ROBBERY.MONEY_TRUCK] = 0
	},
	["ROBBERY_TO_MINIMUM_BOUNTY_MAP"] = {
		[v2.ENUM_ROBBERY.TRAIN_CARGO] = 800,
		[v2.ENUM_ROBBERY.TRAIN_PASSENGER] = 800,
		[v2.ENUM_ROBBERY.CARGO_SHIP] = 800,
		[v2.ENUM_ROBBERY.STORE_DONUT] = 500,
		[v2.ENUM_ROBBERY.STORE_GAS] = 500,
		[v2.ENUM_ROBBERY.CARGO_PLANE] = 1500,
		[v2.ENUM_ROBBERY.POWER_PLANT] = 1000,
		[v2.ENUM_ROBBERY.MONEY_TRUCK] = 0,
		[v2.ENUM_ROBBERY.JEWELRY] = 1000,
		[v2.ENUM_ROBBERY.MUSEUM] = 1250,
		[v2.ENUM_ROBBERY.BANK] = 1500,
		[v2.ENUM_ROBBERY.TOMB] = 1500,
		[v2.ENUM_ROBBERY.CROWN_JEWEL] = 1500,
		[v2.ENUM_ROBBERY.MANSION] = 2000,
		[v2.ENUM_ROBBERY.BANK2] = 1500,
		[v2.ENUM_ROBBERY.OIL_RIG] = 1750
	},
	["MUSEUM_ASSIST_BOUNTY_MULT"] = 0.1,
	["POLICE_KILL_BOUNTY"] = 250,
	["SMALL_VIP_SERVER_BOUNTY_MULTIPLIER"] = 0.1,
	["SMALL_VIP_SERVER_MAX_SIZE"] = 10,
	["AVERAGE_BOUNTY_STEP_SIZE_FOR_NOTIFICATION"] = 4000,
	["NOTIFICATION_COOLDOWN_SECONDS"] = 60
}
return v3(v4)
