-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNKBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzBkVudW1lcgNBcHAIUnVuVXRpbHMacmVxdWlyZVZhbGlkSW5kZXhBbmRGcmVlemUOTWFuc2lvblJvYmJlcnkIVEFHX05BTUUOUk9CQkVSWV9SRVdBUkQNUm9iYmVyeVN0YXR1cxhST0JCRVJZX1NUQVRVU19BVFRSX05BTUUXTUFYX1BMQVlFUlNfSU5fRUxFVkFUT1IUTnVtUGxheWVyc0luRWxldmF0b3IhTlVNX1BMQVlFUlNfSU5fRUxFVkFUT1JfQVRUUl9OQU1FEUVsZXZhdG9yQ291bnRkb3duIEVMRVZBVE9SX0NPVU5URE9XTl9JTlNUQU5DRV9OQU1FCGlzU3R1ZGlvF0VMRVZBVE9SX0NPVU5URE9XTl9USU1FEElzRWxldmF0b3JNb3ZpbmccSVNfRUxFVkFUT1JfTU9WSU5HX0FUVFJfTkFNRQpCb3NzTW9kZWxzF0JPU1NfTU9ERUxTX0ZPTERFUl9OQU1FB1NoaWVsZHMZU0hJRUxEX01PREVMU19GT0xERVJfTkFNRQ5NQVhfU0hJRUxEU19VUBJNSU5fU0hJRUxEX1VQX1RJTUUSTUFYX1NISUVMRF9VUF9USU1FFFNISUVMRF9DT09MRE9XTl9USU1FDlNoaWVsZExhc3REb3duH1NISUVMRF9MQVNUX0RPV05fVElNRV9BVFRSX05BTUUPSW5Sb2JiZXJ5Rm9sZGVyFklOX1JPQkJFUllfRk9MREVSX05BTUUMR3VhcmRzRm9sZGVyEkdVQVJEU19GT0xERVJfTkFNRR5NYW5zaW9uUm9iYmVyeVByb2dyZXNzaW9uU3RhdGUbUFJPR1JFU1NJT05fU1RBVEVfQVRUUl9OQU1FBE5vbmUMV2FpdEZvckVudGVyG1BsYXllcnNFbnRlcmVkSW50cm9DdXRzY2VuZQ1XYWl0Rm9yRGFtYWdlC0ZpcnN0R3VhcmRzDEJvc3NNb3ZlbWVudBJSdW5Bd2F5RW5kQ3V0c2NlbmURUFJPR1JFU1NJT05fU1RBVEUjTWFuc2lvblJvYmJlcnlMYXN0UHJvZ3Jlc3Npb25Cb3JuQXQiTEFTVF9QUk9HUkVTU0lPTl9CT1JOX0FUX0FUVFJfTkFNRQ9DSEFSX1BFUl9TRUNPTkQvREVMQVlfQkVGT1JFX1JFTU9WSU5HX1BMQVlFUl9GUk9NX0lOVklURV9SRUZVTkQkREFNQUdFX1FVRVVFX1NJWkVfRk9SX0JPU1NfVEFSR0VUSU5HFk1hbnNpb25JbnZpdGVzVG9SZWZ1bmQhT05fSk9JTl9NQU5TSU9OX0lOVklURV9SRUZVTkRfS0VZE01hbnNpb25Sb2JiZXJ5RXhpdHMaRVhJVF9URUxFUE9SVFNfRk9MREVSX05BTUUQRW50cmFuY2VFbGV2YXRvchZFTlRSQU5DRV9FTEVWQVRPUl9OQU1FD0Fycml2YWxFbGV2YXRvchVBUlJJVkFMX0VMRVZBVE9SX05BTUULQk9TU19IRUFMVEgOTGFzdENsb3NlZFRpbWUaTEFTVF9DTE9TRURfVElNRV9BVFRSX05BTUUaTUlOX1RJTUVfQkVUV0VFTl9ST0JCRVJJRVMOVElNRU9VVF9QRVJJT0QkVElNRV9BRlRFUl9CT1NTX0tJTExfQkVGT1JFX1RFTEVQT1JUFU5QQ19XQUxLX1NQRUVEX0RFQlVGRhFOUENfSEVBTFRIX0RFQlVGRhRCT1NTX0FUVEFDS19JTlRFUlZBTBRCb3NzUm9vbVBsYXllclNwYXducyNCT1NTX1JPT01fUExBWUVSX1NQQVdOU19GT0xERVJfTkFNRRNBdHRlbXB0RXhpdEVsZXZhdG9yIUFUVEVNUFRfRVhJVF9FTEVWQVRPUl9SRU1PVEVfTkFNRQABDwAAAQIAtQGjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CAxgHAAAAnwECAqQCBQAAAEBATQQAoQYAAABNAwRXCAAAAJ8CAgKkAwUAAABAQE0FAMEJAAAATQQFQgoAAACfAwICTQQBAAsAAAD/BQcAAAAAAG8GDAAwBgW0DQAAAIwGyDIwBgUtDgAAAG8GDwAwBgWlEAAAAIwGAwAwBgV1EQAAAG8GEgAwBgW/EwAAAG8GFAAwBgVZFQAAAE0HA+oWAAAAnwcBAg4HAgCMBgIAZQABAIwGDwAwBgV7FwAAAG8GGAAwBgVDGQAAAG8GGgAwBgVFGwAAAG8GHAAwBgUwHQAAAE0HA+oWAAAAnwcBAg4HAgCMBgEAZQABAIwGAwAwBgW7HgAAAG8GHwAwBgUyIAAAAIwGBgAwBgVTIQAAAIwGAwAwBgXOIgAAAG8GIwAwBgVxJAAAAG8GJQAwBgVyJgAAAG8GJwAwBgU3KAAAAG8GKQAwBgUKKgAAAFIGAgD/BwAABwAAAG8IKwBvCSwAbwotAG8LLgBvDC8Abw0wAG8OMQDFBwgIAQAAAJ8GAgIwBgWUMgAAAG8GMwAwBgXGNAAAAE0HA+oWAAAAnwcBAg4HAgCMBmQAZQABAIwGMgAwBgUcNQAAAIwGDwAwBgWONgAAAIwGDwAwBgWvNwAAAG8GOAAwBgXoOQAAAG8GOgAwBgW3OwAAAG8GPAAwBgUoPQAAAG8GPgAwBgX6PwAAAE0HA+oWAAAAnwcBAg4HAgCMBsgAZQABAIwGSA0wBgVrQAAAAG8GQQAwBgXbQgAAAIwGLAEwBgU3QwAAAIwGsAQwBgVPRAAAAIwGPAAwBgW/RQAAAG8GHwAwBgVkRgAAAG8GRwAwBgUySAAAAIwGBwAwBgXbSQAAAG8GSgAwBgVVSwAAAG8GTAAwBgWkTQAAAJ8EAgCCBAAATgMBBAAAAEADAgMDAwQEAABAQAMFAwYDBwMIAwkDCgMLAwwDDQMOAw8DEAMRAxIDEwMUAxUDFgMXAxgDGQMaAxsDHAMdAgAAAAAAAOA/Ax4DHwMgAyEDIgMjAyQDJQMmAycDKAMpAyoDKwMsAy0DLgMvAzADMQMyAzMDNAM1AzYDNwM4AzkDOgM7AzwDPQM+Az8DQANBA0IDQwNEApqZmZmZmek/A0UDRgNHA0gDSQNKAAEAARgAAQAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAgAAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAAAAAAAAAEAAAEAAAEAAAEAAAAAAAAAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEBAQEBAQEAAPkAAAkAAAEAAAAAAAAAAAIAAAEAAAEAAAEAAAEAAAEAAAIAAAAAAAAAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAANEAAQAAAAAAl0pQEBqvh/6ljjqEtlDIiJUJNwkphJuTCCkUNekPS3+6NhMk5My6cw==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v2 = require(v1.Std.TableUtils)
local v3 = require(v1.Std.Enumer)
local v4 = require(v1.App.RunUtils)
return v2.requireValidIndexAndFreeze({
	["TAG_NAME"] = "MansionRobbery",
	["ROBBERY_REWARD"] = 13000,
	["ROBBERY_STATUS_ATTR_NAME"] = "RobberyStatus",
	["MAX_PLAYERS_IN_ELEVATOR"] = 3,
	["NUM_PLAYERS_IN_ELEVATOR_ATTR_NAME"] = "NumPlayersInElevator",
	["ELEVATOR_COUNTDOWN_INSTANCE_NAME"] = "ElevatorCountdown",
	["ELEVATOR_COUNTDOWN_TIME"] = v4.isStudio() and 2 or 15,
	["IS_ELEVATOR_MOVING_ATTR_NAME"] = "IsElevatorMoving",
	["BOSS_MODELS_FOLDER_NAME"] = "BossModels",
	["SHIELD_MODELS_FOLDER_NAME"] = "Shields",
	["MAX_SHIELDS_UP"] = v4.isStudio() and 1 or 3,
	["MIN_SHIELD_UP_TIME"] = 0.5,
	["MAX_SHIELD_UP_TIME"] = 6,
	["SHIELD_COOLDOWN_TIME"] = 3,
	["SHIELD_LAST_DOWN_TIME_ATTR_NAME"] = "ShieldLastDown",
	["IN_ROBBERY_FOLDER_NAME"] = "InRobberyFolder",
	["GUARDS_FOLDER_NAME"] = "GuardsFolder",
	["PROGRESSION_STATE_ATTR_NAME"] = "MansionRobberyProgressionState",
	["PROGRESSION_STATE"] = v3({
		"None",
		"WaitForEnter",
		"PlayersEnteredIntroCutscene",
		"WaitForDamage",
		"FirstGuards",
		"BossMovement",
		"RunAwayEndCutscene"
	}),
	["LAST_PROGRESSION_BORN_AT_ATTR_NAME"] = "MansionRobberyLastProgressionBornAt",
	["CHAR_PER_SECOND"] = v4.isStudio() and 100 or 50,
	["DELAY_BEFORE_REMOVING_PLAYER_FROM_INVITE_REFUND"] = 15,
	["DAMAGE_QUEUE_SIZE_FOR_BOSS_TARGETING"] = 15,
	["ON_JOIN_MANSION_INVITE_REFUND_KEY"] = "MansionInvitesToRefund",
	["EXIT_TELEPORTS_FOLDER_NAME"] = "MansionRobberyExits",
	["ENTRANCE_ELEVATOR_NAME"] = "EntranceElevator",
	["ARRIVAL_ELEVATOR_NAME"] = "ArrivalElevator",
	["BOSS_HEALTH"] = v4.isStudio() and 200 or 3400,
	["LAST_CLOSED_TIME_ATTR_NAME"] = "LastClosedTime",
	["MIN_TIME_BETWEEN_ROBBERIES"] = 300,
	["TIMEOUT_PERIOD"] = 1200,
	["TIME_AFTER_BOSS_KILL_BEFORE_TELEPORT"] = 60,
	["NPC_WALK_SPEED_DEBUFF"] = 0.5,
	["NPC_HEALTH_DEBUFF"] = 0.8,
	["BOSS_ATTACK_INTERVAL"] = 7,
	["BOSS_ROOM_PLAYER_SPAWNS_FOLDER_NAME"] = "BossRoomPlayerSpawns",
	["ATTEMPT_EXIT_ELEVATOR_REMOTE_NAME"] = "AttemptExitElevator"
})
