-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMQBmV4cGVjdAJvZhFNb3VzZUJ1dHRvbjFDbGljawJ0bwVlcXVhbAlIb3N0RXZlbnQHVG91Y2hlZAVuZXZlcgdyZXF1aXJlBnNjcmlwdAZQYXJlbnQEVHlwZQVFdmVudAJpdCdzaG91bGQgeWllbGQgZXZlbnQgb2JqZWN0cyB3aGVuIGluZGV4ZWQvc2hvdWxkIHlpZWxkIHRoZSBzYW1lIG9iamVjdCB3aGVuIGluZGV4ZWQgYWdhaW4ABAYAAgAAACWkAgEAAAAAQPsEAABNAwS8AgAAAPsFAQBNBAXaAwAAAJ8DAgCfAgACTQECkgQAAABNAAF7BQAAAPsCAABNAQIqBgAAAJ8AAgGkAgEAAAAAQPsEAABNAwS8AgAAAPsFAQBNBAUsBwAAAJ8DAgCfAgACTQECkgQAAABNAAF7BQAAAPsCAABNAQIqBgAAAJ8AAgGCAAEACAMBBAAAAEADAgMDAwQDBQMGAwcABgABGAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAEHAAAAAAgAAQAAACD7AQAATQAB2gAAAAD7AgAATQEC2gAAAAD7AwAATQIDLAEAAACkBQMAAAAgQFIGAACfBQICTQQFkgQAAABNAwR7BQAAAFIEAQCfAwIBpAYDAAAAIEBSBwAAnwYCAk0FBjUGAAAATQQFkgQAAABNAwR7BQAAAFIEAgCfAwIBggABAAcDAwMHAwEEAAAgQAMEAwUDCAALAAEYAAAAAQAAAQAAAgAAAAAAAAAAAAEAAAAAAAAAAAAAAAEMAAAAAAUAAAAAACKkAAEAAAAAQKQEAwAAACBATQMEJAQAAABNAgMkBAAAAE0BAhEFAAAAnwACAqQBAQAAAABApAQDAAAAIEBNAwQkBAAAAE0CAzYGAAAAnwECAqQCCAAAAHBAbwMJANkEAAASAAAAEgABAJ8CAwGkAggAAABwQG8DCgDZBAEAEgABAJ8CAwGCAAEACwMJBAAAAEADCgQAACBAAwsDDAMNAw4EAABwQAMPAxACAAEBAAEYAAAAAAAAAAAAAAACAAAAAAAAAAACAAAAAAAABQAAAAAACAIAAAAAAQAAAQIAA6MAAADAAAAAggACAAEGAgECAQABGAAAAAEAAAAAA18qKzk15yzRbe5BreFD9UJ7t4PSsKeNeQ3+2UpwvHGpc10f4JE3FFM=

-- Decompiled by Krnl

return function()
	local v_u_1 = require(script.Parent.Parent.Type)
	local v_u_2 = require(script.Parent.Event)
	it("should yield event objects when indexed", function()
		-- upvalues: (copy) v_u_1, (copy) v_u_2
		expect(v_u_1.of(v_u_2.MouseButton1Click)).to.equal(v_u_1.HostEvent)
		expect(v_u_1.of(v_u_2.Touched)).to.equal(v_u_1.HostEvent)
	end)
	it("should yield the same object when indexed again", function()
		-- upvalues: (copy) v_u_2
		local v3 = v_u_2.MouseButton1Click
		local v4 = v_u_2.MouseButton1Click
		local v5 = v_u_2.Touched
		expect(v3).to.equal(v4)
		expect(v3).never.to.equal(v5)
	end)
end
