-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMoAWYNY3JlYXRlQmluZGluZwlwY3RDbG9zZWQPdXBkYXRlUGN0Q2xvc2VkA25ldwRtYWlkBGluaXQCb3MFY2xvY2sERW51bQtFYXNpbmdTdHlsZQRRdWFkD0Vhc2luZ0RpcmVjdGlvbgVJbk91dAhHZXRWYWx1ZQlIZWFydGJlYXQHQ29ubmVjdAhHaXZlVGFzawhkaWRNb3VudApEb0NsZWFuaW5nC3dpbGxVbm1vdW50DWNyZWF0ZUVsZW1lbnQGcmVuZGVyB3VubW91bnQJQ29tcG9uZW50A0FwcAZleHRlbmQHcmVxdWlyZQdFeWVsaWRzBnNjcmlwdAZQYXJlbnQFbW91bnQEZ2FtZQxUd2VlblNlcnZpY2UKR2V0U2VydmljZQpSdW5TZXJ2aWNlEVJlcGxpY2F0ZWRTdG9yYWdlBVJvYWN0A1N0ZARNYWlkAAkDAQAAAAYDAAAFAQIKPgIAASEBAgBvAgIAYAEDAAIAAAAhAQAAggECACECAAD1AQACggECAAMCAAAAAAAA8D8CAAAAAAAAAEACAAAAAAAA4D8ACAEBGAAAAAAAAQACAAAJAAAAAAMBAgAAABD7AgAATQECMQAAAACMAgEAnwECAzABALUBAAAAMAIAagIAAAD7AgEATQEC7wMAAACfAQECMAEAFgQAAACCAAEABQMCAwMDBAMFAwYAEgcBGAAAAAAAAAAAAAEAAAAAAAETAAAAAAgAAgAAABukAAIAAAQAgJ8AAQI+AwAEIQIDA28DBQBgAgMAAwAAACEBAANlAAMAIQIAA/UBAwJlAAAA+wMAAE0CA2oGAAAA+wMBAFIFAQCkBgoACSBwwKQHDQAMLHDAvAMD8w4AAACfAwUAnwIAAYIAAQAPAwgDCQQABACAAgAAAAAAAPA/AgAAAAAAAABAAgAAAAAAAOA/AwQDCgMLAwwECSBwwAMNAw4EDCxwwAMPABcAARgPAADxAAAAAAEAAgAADgAAAAAAAAAAAAAAAAEJAAAAAAYBAgAAAA9NAQAWAAAAAPsEAABNAwT9AQAAANkFAAASAAAAEgIBALwDA8cCAAAAnwMDALwBAf0DAAAAnwEAAYIAAQAEAwYDEAMRAxIBAhYTARgAAAAAAAAAAAAAAAAAAAUXAAAAAAMBAAAAAAZNAQAWAAAAALwBAVEBAAAAnwECAYIAAQACAwYDFAAdFQEYAAAAAAABHgAAAAAFAQIAAAAL+wIAAE0BAsoAAAAA+wIBAOIDAgBNBAC1AQAAADAEA7UBAAAAnwEDAIIBAAADAxYDAwUBAQAgFwEYAAAAAAABAAAA/wAhAAAAAAIAAgAAAAb7AQAATQABEgAAAAD7AQEAnwACAYIAAQABAxgAJwABGAAAAAAAASgAAAAABgEEAAAAMPsCAABNAQKIAAAAAG8DAQC8AQGcAgAAAJ8BAwKkAgQAAAAwQKQFBwAAAGBATQQFJAgAAABNAwSnBQAAAJ8CAgLAAwkAEgIAABICAQAwAwETCgAAAMADCwASAgIAEgIDADADAWoMAAAAwAMNADADATQOAAAA2QMDABICAAASAAIAMAMBgA8AAAD7BAAATQME5BAAAAD7BQAATQQFyhEAAABSBQEAnwQCAlIFAACfAwMC2QQEABICAAASAAMAggQCABIDGQMaAxsDHAQAADBAAx0DHgQAAGBAAx8GAQMHBgMDEwYEAxUDFwMgAxYFAQMEBQYPAAEYAAAAAAAAAAEAAAAAAAAAAAEAAAAABAAAAAAHAAADAAAAAAYAAAAAAAAAAAABAAAAEAAAAAAHAAABAgAmowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBAQAAAABAbwMEALwBARYDAAAAnwEDAqQCAQAAAABAbwQFALwCAhYDAAAAnwIDAqQDBwAAAGBATQQCIQgAAACfAwICpAQHAAAAYEBNBgKhCQAAAE0FBnYKAAAAnwQCAsAFCwDABgwAEgADABIABAASAAEAEgAAAIIGAgANAyEEAAAAQAMiAyMDJAMlAxwEAABgQAMmAycDKAYABgcCAAcBAAEYAAEAAAAAAAEAAAAAAAEAAAAAAAEAAAAAAQAAAAAAAAIHAAAAAAABAAAAAAh+2atd1XpHAkwdwcljsSYL6/ljlgbIynBdBBPkrNzhCws5J++Bz3dV

-- Decompiled by Krnl

local v_u_1 = game:GetService("TweenService")
local v_u_2 = game:GetService("RunService")
local v3 = game:GetService("ReplicatedStorage")
local v_u_4 = require(v3.Roact)
local v_u_5 = require(v3.Std.Maid)
return function(p6)
	-- upvalues: (copy) v_u_4, (copy) v_u_5, (copy) v_u_2, (copy) v_u_1
	local v7 = v_u_4.Component:extend("App")
	local v_u_8 = require(script.Parent.Eyelids)
	function v7.init(p9)
		-- upvalues: (ref) v_u_4, (ref) v_u_5
		local v10, v11 = v_u_4.createBinding(1)
		p9.pctClosed = v10
		p9.updatePctClosed = v11
		p9.maid = v_u_5.new()
	end
	function v7.didMount(p_u_12)
		-- upvalues: (ref) v_u_2, (ref) v_u_1
		p_u_12.maid:GiveTask(v_u_2.Heartbeat:Connect(function()
			-- upvalues: (copy) p_u_12, (ref) v_u_1
			local v13 = os.clock()
			local v14
			if v13 / 2 % 1 < 0.5 then
				v14 = v13 % 1
			else
				v14 = 1 - v13 % 1
			end
			p_u_12.updatePctClosed(v_u_1:GetValue(v14, Enum.EasingStyle.Quad, Enum.EasingDirection.InOut))
		end))
	end
	function v7.willUnmount(p15)
		p15.maid:DoCleaning()
	end
	function v7.render(p16)
		-- upvalues: (ref) v_u_4, (copy) v_u_8
		return v_u_4.createElement(v_u_8, {
			["pctClosed"] = p16.pctClosed
		})
	end
	local v_u_17 = v_u_4.mount(v_u_4.createElement(v7), p6)
	return function()
		-- upvalues: (ref) v_u_4, (copy) v_u_17
		v_u_4.unmount(v_u_17)
	end
end
