-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMeA25ldwRtYWlkBGluaXQJcGN0Q2xvc2VkBXByb3BzB0V5ZWxpZHMEdGV4dA1jaGFyUGVyU2Vjb25kDGRpYWxvZ3VlVGV4dAhTdWJ0aXRsZQ5jcmVhdGVGcmFnbWVudAZyZW5kZXIIZGlkTW91bnQKRG9DbGVhbmluZwt3aWxsVW5tb3VudARnYW1lEVJlcGxpY2F0ZWRTdG9yYWdlCkdldFNlcnZpY2UHcmVxdWlyZQNTdGQETWFpZApSb2FjdFJvZHV4BVJvYWN0DWNyZWF0ZUVsZW1lbnQGc2NyaXB0BlBhcmVudA1QdXJlQ29tcG9uZW50A0FwcAZleHRlbmQHY29ubmVjdAAGAwEBAAAAB/sCAABNAQLvAAAAAJ8BAQIwAQAWAQAAAIIAAQACAwEDAgAMAwEYAAAAAAAAAQ0AAAAABwEEAAAAJv8BAgAAAAAA+wIAAPsDAQDiBAEATQYABwIAAABNBQa1AAAAADAFBLUAAAAAnwIDAjACAacDAAAA+wIAAPsDAgDiBAYATQYABwIAAABNBQYpBwAAADAFBNUEAAAATQYABwIAAABNBQajBQAAADAFBKMFAAAAnwIDAjACAfEIAAAA+wMDAE0CAzYJAAAAUgMBAJ8CAgCCAgAACgMEBQEAAwUDBgMHAwgFAgQFAwkDCgMLAA8MARgAAAEAAAEAAAAAAP8AAAMAAAEAAAAAAAEAAAAAAP4AAAQAAAAAABAAAAAAAQEAAAAAAYIAAQAAABoNARgAGgAAAAADAQAAAAAGTQEAFgAAAAC8AQFRAQAAAJ8BAgGCAAEAAgMCAw4AGw8BGAAAAAAAARwAAAAABAIAAAAABuICAQBNAwApAAAAADADAikAAAAAggICAAIDCQUBAAAeAAEYAAEAAAAAHwAAAAAKAAABAgBKowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAoQYAAABNAgN2BwAAAJ8BAgKkAgUAAABAQE0DAC0IAAAAnwICAqQDBQAAAEBATQQAIQkAAACfAwICTQQDygoAAACkBQUAAABAQKQIDAAAALBATQcIJA0AAABNBgenDgAAAJ8FAgKkBgUAAABAQKQJDAAAALBATQgJJA0AAABNBwjxDwAAAJ8GAgJNBwP4EAAAAG8JEQC8BwecEgAAAJ8HAwLACBMAEgABADAIBxMUAAAAwAgVABIABAASAAUAEgAGABIAAwAwCAeAFgAAAMAIFwAwCAdqGAAAAMAIGQAwCAc0GgAAAE0IAucbAAAAwAkcAJ8IAgJSCQcAnwgCAIIIAAAdAxAEAAAAQAMRAxIDEwQAAEBAAxQDFQMWAxcDGAMZBAAAsEADGgMGAwoDGwMcAx0GAAMDBgEDDAYCAw0GAwMPAx4GBAUAAQIDBAEAARgAAQAAAAAAAQAAAAAAAAEAAAAAAQAAAAABAAIAAAAAAAAAAAEAAAAAAAAAAAIAAAAAAAEAAAADAAAAAAAACwAAAQAAAwAAAAQAAAEAAAAABefNK8vasLHs1QlBX9vcEcIaD3c4h/Vhyw5fim+PFGay+e6GHWsBx+8=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.Maid)
local v3 = require(v1.RoactRodux)
local v_u_4 = require(v1.Roact)
local v_u_5 = v_u_4.createElement
local v_u_6 = require(script.Parent.Eyelids)
local v_u_7 = require(script.Parent.Subtitle)
local v8 = v_u_4.PureComponent:extend("App")
function v8.init(p9)
	-- upvalues: (copy) v_u_2
	p9.maid = v_u_2.new()
end
function v8.render(p10)
	-- upvalues: (copy) v_u_5, (copy) v_u_6, (copy) v_u_7, (copy) v_u_4
	local v11 = {
		["Eyelids"] = v_u_5(v_u_6, {
			["pctClosed"] = p10.props.pctClosed
		}),
		["Subtitle"] = v_u_5(v_u_7, {
			["text"] = p10.props.dialogueText,
			["charPerSecond"] = p10.props.charPerSecond
		})
	}
	return v_u_4.createFragment(v11)
end
function v8.didMount(_) end
function v8.willUnmount(p12)
	p12.maid:DoCleaning()
end
return v3.connect(function(p13, _)
	return {
		["dialogueText"] = p13.dialogueText
	}
end)(v8)
