-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMPAWEBYgZleHBlY3QCdG8FZXF1YWwFbmV2ZXIFdGhyb3cHcmVxdWlyZQZzY3JpcHQGUGFyZW50D2NvbWJpbmVSZWR1Y2VycwJpdC9zaG91bGQgaW52b2tlIGVhY2ggc3ViLXJlZHVjZXIgZm9yIGV2ZXJ5IGFjdGlvbjdzaG91bGQgYXNzaWduIGVhY2ggc3ViLXJlZHVjZXIncyB2YWx1ZSB0byB0aGUgbmV3IHN0YXRlInNob3VsZCBub3QgdGhyb3cgd2hlbiBzdGF0ZSBpcyBuaWwADAQCAQAAAAT7AwAAlQIDAN4CAACCAAEAAQIAAAAAAADwPwAJAQEYAAAAAQoAAAAABAIBAAAABPsDAACVAgMA3gIAAIIAAQABAgAAAAAAAPA/AAwCARgAAAABDQAAAAAHAAEAAAApjAAAAIwBAAD7AgAA4gMCANkEAAASAQD/MAQDgAAAAADZBAEAEgEB/zAEA4MBAAAAnwICAlIDAgD/BAAAAAAAAP8FAAAAAAAAnwMDAaQFBAAAADBAUgYAAJ8FAgJNBAWSBQAAAE0DBHsGAAAAjAQBAJ8DAgGkBQQAAAAwQFIGAQCfBQICTQQFkgUAAABNAwR7BgAAAIwEAQCfAwIBwQAAAIIAAQAHAwEDAgUCAAEDAwQAADBAAwQDBQIAAQQAARgAAQIAAQAAAAMAAAD8CgAAAAAAAQAAAAAAAAAAAAEAAAAAAAAAAAABAAUAAAAABAIAAAAAA5ADAAGVAgMAggICAAICAAAAAAAA8D8CAAAAAAAAAAAAGQEBGAAAABoAAAAABAIAAAAAA5ADAAGVAgMAggICAAICAAAAAAAACEACAAAAAAAAAAAAHAIBGAAAAB0AAAAABgABAAAAJvsAAADiAQIAwAIDADACAYAAAAAAwAIEADACAYMBAAAAnwACAlIBAAD/AgAAAAAAAP8DAAAAAAAAnwEDAqQEBgAAAFBATQUBgAAAAACfBAICTQMEkgcAAABNAgN7CAAAAIwDAQCfAgIBpAQGAAAAUEBNBQGDAQAAAJ8EAgJNAwSSBwAAAE0CA3sIAAAAjAMDAJ8CAgGCAAEACQMBAwIFAgABBgMGBAMDBAAAUEADBAMFAgMEFwABGAAAAQAAAwAA/AkAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAABGAAAAAAEAgAAAAADkAMAAZUCAwCCAgIAAgIAAAAAAADwPwIAAAAAAAAAAAAoAQEYAAAAKQAAAAAEAgAAAAADkAMAAZUCAwCCAgIAAgIAAAAAAAAIQAIAAAAAAAAAAAArAgEYAAAALAAAAAADAAEAAAAG+wAAAMYBAAD/AgAAAAAAAJ8AAwGCAAEAAAAwAAEYAAAAAAABMQAAAAAGAAEAAAAW+wAAAOIBAgDAAgMAMAIBgAAAAADAAgQAMAIBgwEAAACfAAICpAQGAAAAUEDZBQIAEgAAAJ8EAgJNAwSSBwAAAE0CAzUIAAAATQEC2wkAAACfAQEBggABAAoDAQMCBQIAAQYGBgcDAwQAAFBAAwQDBgMHAwYHCCYAARgAAAEAAAMAAPwJAAAAAAIAAAAAAAABJwAAAAAEAAAAAAAcpAABAAAAAECkAwMAAAAgQE0CAyQEAAAATQEC4wUAAACfAAICpAEHAAAAYEBvAggA2QMAABIAAACfAQMBpAEHAAAAYEBvAgkA2QMBABIAAACfAQMBpAEHAAAAYEBvAgoA2QMCABIAAACfAQMBggABAAsDCAQAAABAAwkEAAAgQAMKAwsDDAQAAGBAAw0DDgMPAwIFCQEAARgAAAAAAAAAAAACAAAAAAATAAAAAAAPAAAAAAAOAgAAAAABAAABAgADowAAAMAAAACCAAIAAQYKAQoBAAEYAAAAAQAAAAAL3t5HPAw6HX7sGi2osXxnQTOu/W4dh1NXn7vXDJsvKl+bCUaxT2V1Yg==

-- Decompiled by Krnl

return function()
	local v_u_1 = require(script.Parent.combineReducers)
	it("should invoke each sub-reducer for every action", function()
		-- upvalues: (copy) v_u_1
		local v_u_2 = 0
		local v_u_3 = 0
		v_u_1({
			["a"] = function(_, _)
				-- upvalues: (ref) v_u_2
				v_u_2 = v_u_2 + 1
			end,
			["b"] = function(_, _)
				-- upvalues: (ref) v_u_3
				v_u_3 = v_u_3 + 1
			end
		})({}, {})
		expect(v_u_2).to.equal(1)
		expect(v_u_3).to.equal(1)
	end)
	it("should assign each sub-reducer\'s value to the new state", function()
		-- upvalues: (copy) v_u_1
		local v6 = v_u_1({
			["a"] = function(p4, _)
				return (p4 or 0) + 1
			end,
			["b"] = function(p5, _)
				return (p5 or 0) + 3
			end
		})({}, {})
		expect(v6.a).to.equal(1)
		expect(v6.b).to.equal(3)
	end)
	it("should not throw when state is nil", function()
		-- upvalues: (copy) v_u_1
		local v_u_9 = v_u_1({
			["a"] = function(p7, _)
				return (p7 or 0) + 1
			end,
			["b"] = function(p8, _)
				return (p8 or 0) + 3
			end
		})
		expect(function()
			-- upvalues: (copy) v_u_9
			v_u_9(nil, {})
		end).to.never.throw()
	end)
end
