-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMMB3JlcXVpcmUGc2NyaXB0BlBhcmVudAZleHBlY3QFU3RvcmUCdG8CYmUCb2sCaXQLc2hvdWxkIGxvYWQIZGVzY3JpYmUFUm9kdXgABAYAAAAAABSkAAEAAAAAQKQCAwAAACBATQECJAQAAACfAAICpAQGAAAAUEBNBQBeBwAAAJ8EAgJNAwSSCAAAAE0CA8wJAAAATQECEAoAAACfAQEBggABAAsDAQQAAABAAwIEAAAgQAMDAwQEAABQQAMFAwYDBwMIAAMAARgAAAAAAAAAAgAAAAAAAAAAAAAAAQQAAAAAAwAAAAAABqQAAQAAAABAbwECAMACAwCfAAMBggABAAQDCQQAAABAAwoGAAEAAgABGAAAAAAABQMAAAAAAwAAAAAABqQAAQAAAABAbwECAMACAwCfAAMBggABAAQDCwQAAABAAwwGAQEBAQABGAAAAAAABwIAAAAAAQAAAQIAA6MAAADAAAAAggACAAEGAgECAQABGAAAAAEAAAAAA/Rt3byT4J+Fxqm3KLkW9/1dGc+c9TouXmr9zcF9bcMDthWxfvxkoQg=

-- Decompiled by Krnl

return function()
	describe("Rodux", function()
		it("should load", function()
			local v1 = require(script.Parent)
			expect(v1.Store).to.be.ok()
		end)
	end)
end
