-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMaB3JlZHVjZXIDbmV3CGZvb1ZhbHVlCGJhclZhbHVlCGJhelZhbHVlBWhpQmF6Cm1pZGRsZXdhcmUOb3V0cHV0RnVuY3Rpb24EdHlwZQ50ZXN0QWN0aW9uVHlwZQhkaXNwYXRjaAZleHBlY3QCdG8FZXF1YWwEZmluZAJiZQJvawUxMjM0NQVwcmludAdyZXF1aXJlBnNjcmlwdAZQYXJlbnQFU3RvcmUQbG9nZ2VyTWlkZGxld2FyZQJpdC1zaG91bGQgcHJpbnQgd2hlbmV2ZXIgYW4gYWN0aW9uIGlzIGRpc3BhdGNoZWQABQICAAAAAAGCAAIAAAAJAQEYAAoAAAAAAwECAAAABfsCAACVAQIA3gEAAN4AAQCCAAEAAQIAAAAAAADwPwAWAAEYAAAAAQEXAAAAAAsAAgAAAIsBjAAAAMYBAADAAgAA+wQAAE0DBO8BAAAAUgQCAOIFBACMBjkwMAYFpQIAAADiBgYAbwcHADAHBt4FAAAAMAYF2QMAAAD/BgAAAQAAAPsIAQBNBwhuCAAAAMUGBwIBAAAAnwMEAvsEAQDZBQEAEgEA/xIBAf8wBQSDCQAAAOIGCwBvBwwAMAcGcQoAAAC8BANMDQAAAJ8EAwGkBg8AAADgQFIHAACfBgICTQUGkhAAAABNBAV7EQAAAIwFAQCfBAIBpAcPAAAA4EBvCgwAvAgBVhIAAACfCAMAnwcAAk0GB5IQAAAATQUGzBMAAABNBAUQFAAAAJ8EAQGkBw8AAADgQG8KAgC8CAFWEgAAAJ8IAwCfBwACTQYHkhAAAABNBQbMEwAAAE0EBRAUAAAAnwQBAaQHDwAAAOBAbwoVALwIAVYSAAAAnwgDAJ8HAAJNBgeSEAAAAE0FBswTAAAATQQFEBQAAACfBAEBpAcPAAAA4EBvCgMAvAgBVhIAAACfCAMAnwcAAk0GB5IQAAAATQUGzBMAAABNBAUQFAAAAJ8EAQGkBw8AAADgQG8KBQC8CAFWEgAAAJ8IAwCfBwACTQYHkhAAAABNBQbMEwAAAE0EBRAUAAAAnwQBAaQHDwAAAOBAbwoHALwIAVYSAAAAnwgDAJ8HAAJNBgeSEAAAAE0FBswTAAAATQQFEBQAAACfBAEB+wQBAKQFFwAAAGBBMAUEgwkAAADBAAAAggABABgGAAMCAwMDBAUCAgMDBQUBBQMGAwcDCAMJBQEKAwoDCwMMBAAA4EADDQMOAw8DEAMRAxIDEwQAAGBBAgABBQABGAABAgQAAAAAAQAAAQEAAP8AAwABAAAAAPoJAAAAAAAFAQAA/wAABAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAIAAAAAAQAGAAAAAAUAAAAAABqkAAEAAAAAQKQDAwAAACBATQIDJAQAAABNAQJeBQAAAJ8AAgKkAQEAAAAAQKQEAwAAACBATQMEJAQAAABNAgP6BgAAAJ8BAgKkAggAAABwQG8DCQDZBAAAEgAAABIAAQCfAgMBggABAAoDFAQAAABAAxUEAAAgQAMWAxcDGAMZBAAAcEADGgECAQABGAAAAAAAAAAAAAEAAAAAAAAAAAIAAAAAAAAkAgAAAAABAAABAgADowAAAMAAAACCAAIAAQYDAQMBAAEYAAAAAQAAAAAENASEYUao58IGwO71ChlVLlNmoYkD17rxJomu5x9eaedjH6bbBk8LsA==

-- Decompiled by Krnl

return function()
	local v_u_1 = require(script.Parent.Store)
	local v_u_2 = require(script.Parent.loggerMiddleware)
	it("should print whenever an action is dispatched", function()
		-- upvalues: (copy) v_u_1, (copy) v_u_2
		local v_u_3 = 0
		local v_u_4 = nil
		local v5 = {
			["fooValue"] = 12345,
			["barValue"] = {
				["bazValue"] = "hiBaz"
			}
		}
		local v7 = v_u_1.new(function(p6, _)
			return p6
		end, v5, { v_u_2.middleware })
		function v_u_2.outputFunction(p8)
			-- upvalues: (ref) v_u_3, (ref) v_u_4
			v_u_3 = v_u_3 + 1
			v_u_4 = p8
		end
		v7:dispatch({
			["type"] = "testActionType"
		})
		expect(v_u_3).to.equal(1)
		expect(v_u_4:find("testActionType")).to.be.ok()
		expect(v_u_4:find("fooValue")).to.be.ok()
		expect(v_u_4:find("12345")).to.be.ok()
		expect(v_u_4:find("barValue")).to.be.ok()
		expect(v_u_4:find("bazValue")).to.be.ok()
		expect(v_u_4:find("hiBaz")).to.be.ok()
		v_u_2.outputFunction = print
	end)
end
