-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMXBmV4cGVjdAJ0bwVlcXVhbAVoZWxsbwR0ZXN0BHdhaXQKdGVzdE1ldGhvZAVwY2FsbChBdHRlbXB0ZWQgdG8geWllbGQgaW5zaWRlIGNoYW5nZWQgZXZlbnQhBGZpbmQCYmUCb2sMTm9ZaWVsZC5zcGVjBWVycm9yA2ZvbwdyZXF1aXJlBnNjcmlwdAZQYXJlbnQHTm9ZaWVsZAJpdB5zaG91bGQgY2FsbCBmdW5jdGlvbnMgbm9ybWFsbHkVc2hvdWxkIHRocm93IG9uIHlpZWxkH3Nob3VsZCBwcm9wYWdhdGUgZXJyb3IgbWVzc2FnZXMACAYCAQAAABqkBAEAAAAAQFIFAACfBAICTQMEkgIAAABNAgN7AwAAAIwDBQCfAgIBpAQBAAAAAEBSBQEAnwQCAk0DBJICAAAATQIDewMAAACMAwYAnwICAfsDAACVAgME3gIAAIwCCwBvAwUAggIDAAYDAQQAAABAAwIDAwIAAAAAAADwPwMEAAcFARgAAAAAAAAAAAAAAQAAAAAAAAAAAAIAAAIAAAgAAAAACAABAAAAHowAAADZAQAAEgEA//sCAABSAwEAjAQFAIwFBgCfAgQDpAYBAAAAAEBSBwIAnwYCAk0FBpICAAAATQQFewMAAACMBQsAnwQCAaQGAQAAAABAUgcDAJ8GAgJNBQaSAgAAAE0EBXsDAAAAbwUEAJ8EAgHBAAAAggABAAUDAQQAAABAAwIDAwMEAQAEAAEYAAIACQAAAAACAAAAAAAAAAAAAQAAAAAAAAAAAAEABQAAAAACAAIAAAAK+wEAAJUAAQDeAAAApAACAAAAEECfAAEB+wEBAJUAAQDeAAEAggABAAMCAAAAAAAA8D8DBgQAABBAABoHARgAAAABAAABAAABGwAAAAAMAAEAAABGjAAAAIwBAADZAgAAEgEA/xIBAf+kAwEAAAAAQPsEAABSBQIAnwMDA6QHAwAAACBAUggAAJ8HAgJNBgeSBAAAAE0FBnsFAAAAjAYBAJ8FAgGkBwMAAAAgQFIIAQCfBwICTQYHkgQAAABNBQZ7BQAAAIwGAACfBQIBpAcDAAAAIEBSCAMAnwcCAk0GB5IEAAAATQUGewUAAACpBgAAnwUCAaQIAwAAACBAbwsGALwJBFYHAAAAnwkDAJ8IAAJNBwiSBAAAAE0GB8wIAAAATQUGEAkAAACfBQEBpAgDAAAAIEBvCwoAvAkEVgcAAACfCQMAnwgAAk0HCJIEAAAATQYHzAgAAABNBQYQCQAAAJ8FAQHBAAAAggABAAsDCAQAAABAAwEEAAAgQAMCAwMDCQMKAwsDDAMNAQIWAAEYAAECAAAGAAAAAAIAAAAAAAAAAAABAAAAAAAAAAAAAgAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAABABcAAAAAAgABAAAACPsBAACVAAEA3gAAAKQAAgAAABBAbwEDAJ8AAgGCAAEABAIAAAAAAADwPwMOBAAAEEADDwAtBQEYAAAAAQAAAAEuAAAAAAsAAQAAADCMAAAA2QEAABIBAP+kAgEAAAAAQPsDAABSBAEAnwIDA6QGAwAAACBAUgcCAJ8GAgJNBQaSBAAAAE0EBXsFAAAAqQUAAJ8EAgGkBwMAAAAgQG8KBgC8CANWBwAAAJ8IAwCfBwACTQYHkgQAAABNBQbMCAAAAE0EBRAJAAAAnwQBAaQHAwAAACBAbwoKALwIA1YHAAAAnwgDAJ8HAAJNBgeSBAAAAE0FBswIAAAATQQFEAkAAACfBAEBwQAAAIIAAQALAwgEAAAAQAMBBAAAIEADAgMDAw8DCgMLAwwDDQEEKgABGAACAAUAAAAAAgAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAABACsAAAAABAAAAAAAHKQAAQAAAABApAMDAAAAIEBNAgMkBAAAAE0BAgQFAAAAnwACAqQBBwAAAGBAbwIIANkDAAASAAAAnwEDAaQBBwAAAGBAbwIJANkDAQASAAAAnwEDAaQBBwAAAGBAbwIKANkDAgASAAAAnwEDAYIAAQALAxAEAAAAQAMRBAAAIEADEgMTAxQEAABgQAMVAxYDFwMBAwUBAAEYAAAAAAAAAAAAAgAAAAAAEgAAAAAAFAAAAAAADgIAAAAAAQAAAQIAA6MAAADAAAAAggACAAEGBgEGAQABGAAAAAEAAAAABxvZwXOEJ+uAKR2r51W5g8DKKjhcdhBF2cS0KIQG4mzWNgKxTs/Y+xs=

-- Decompiled by Krnl

return function()
	local v_u_1 = require(script.Parent.NoYield)
	it("should call functions normally", function()
		-- upvalues: (copy) v_u_1
		local v_u_2 = 0
		local v5, v6 = v_u_1(function(p3, p4)
			-- upvalues: (ref) v_u_2
			expect(p3).to.equal(5)
			expect(p4).to.equal(6)
			v_u_2 = v_u_2 + 1
			return 11, "hello"
		end, 5, 6)
		expect(v5).to.equal(11)
		expect(v6).to.equal("hello")
	end)
	it("should throw on yield", function()
		-- upvalues: (copy) v_u_1
		local v_u_7 = 0
		local v_u_8 = 0
		local function v9()
			-- upvalues: (ref) v_u_7, (ref) v_u_8
			v_u_7 = v_u_7 + 1
			wait()
			v_u_8 = v_u_8 + 1
		end
		local v10, v11 = pcall(v_u_1, v9)
		expect(v_u_7).to.equal(1)
		expect(v_u_8).to.equal(0)
		expect(v10).to.equal(false)
		expect(v11:find("Attempted to yield inside changed event!")).to.be.ok()
		expect(v11:find("NoYield.spec")).to.be.ok()
	end)
	it("should propagate error messages", function()
		-- upvalues: (copy) v_u_1
		local v_u_12 = 0
		local function v13()
			-- upvalues: (ref) v_u_12
			v_u_12 = v_u_12 + 1
			error("foo")
		end
		local v14, v15 = pcall(v_u_1, v13)
		expect(v14).to.equal(false)
		expect(v15:find("foo")).to.be.ok()
		expect(v15:find("NoYield.spec")).to.be.ok()
	end)
end
