-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMUBnR5cGVvZgV0YWJsZQJ7CgZpbnNlcnQFcGFpcnMEICAgIANyZXAIdG9zdHJpbmcDID0gAQoBfQZzdHJpbmcGZm9ybWF0AiVxCSAoc3RyaW5nKQIgKAEpBmNvbmNhdAALcHJldHR5UHJpbnQAAg0CAQAAAJkBkAEBAP8CAAAAAAAAuywAA1IEAACkAwIAAAAQQJ8DAgLwA00AAwAAgIE0AgUEAAAAUgQCAG8FBACkAwYAABQwgJ8DAwGkAwgAAABwQFIEAACfAwIEFwMsAFIJAgBvCgkAlQwBCrwKChYLAAAAnwoDAEw0AAKkCAYAABQwgJ8IAAG7PwYDUgsGAKQKDQAAAMBAnwoCAp40AgQKAAAAUgkCAKQIBgAAFDCAnwgDAYE0AgUOAAAAUgkCAG8KDgCkCAYAABQwgJ8IAwFSCQIA+woAAFILBwCVDAEKnwoDAEw0AAKkCAYAABQwgJ8IAAGBNAIFDwAAAFIJAgBvCg8ApAgGAAAUMICfCAMBbgPT/wIAAABSBAIAbwUJAFIHAQC8BQUWCwAAAJ8FAwBMNAACpAMGAAAUMICfAwABgTQCBRAAAABSBAIAbwUQAKQDBgAAFDCAnwMDAWUAPQC7LAADUgQAAKQDAgAAABBAnwMCAvADEwARAACAUgQCAKQFEwAASBCBbwYUAFIHAACfBQMATDQAAqQDBgAAFDCAnwMAAYE0AgUVAAAAUgQCAG8FFQCkAwYAABQwgJ8DAwFlACQAuz8AA1IGAACkBQ0AAADAQJ8FAgKeNAIEBQAAAFIEAgCkAwYAABQwgJ8DAwGBNAIFFgAAAFIEAgBvBRYApAMGAAAUMICfAwMBuywAA1IGAACkBQIAAAAQQJ8FAgKeNAIEBQAAAFIEAgCkAwYAABQwgJ8DAwGBNAIFFwAAAFIEAgBvBRcApAMGAAAUMICfAwMBpAMZAABgMIBSBAIAbwUaAJ8DAwCCAwAAGwIAAAAAAAAAAAMBBAAAEEADAgMDAwQEABQwgAMFBAAAcEADBgIAAAAAAADwPwMHAwgEAADAQAMJAwoDCwMMAw0EAEgQgQMOAw8DEAMRAxIEAGAwgAMTAAMUARgAAQACAAAAAAAAAQAAAAAAAAIAAAAAAQAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAIAAAAAAAAAAAEAAAAAAAD6AAkAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAABAAAAAAAAAAAAAQAAAAAAAAACAAAAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAADAAAAAAAEAAAAAAEAAAECAASjAAAAwAAAABIAAACCAAIAAQYAAQABAAEYAAIAHwEAAAAAATzP9pZQg0vhDgucAlQlNoEgF/KRRx0SLMr7g01g6aS+yhe6ou0LIKw=

-- Decompiled by Krnl

local function v_u_14(p1, p2)
	-- upvalues: (copy) v_u_14
	local v3 = p2 or 0
	local v4 = {}
	if typeof(p1) == "table" then
		table.insert(v4, "{\n")
		for v5, v6 in pairs(p1) do
			local v7 = v3 + 1
			table.insert(v4, ("    "):rep(v7))
			local v8 = tostring(v5)
			table.insert(v4, v8)
			table.insert(v4, " = ")
			local v9 = v_u_14
			local v10 = v3 + 1
			table.insert(v4, v9(v6, v10))
			table.insert(v4, "\n")
		end
		table.insert(v4, ("    "):rep(v3))
		table.insert(v4, "}")
	elseif typeof(p1) == "string" then
		local v11 = string.format
		table.insert(v4, v11("%q", p1))
		table.insert(v4, " (string)")
	else
		local v12 = tostring(p1)
		table.insert(v4, v12)
		table.insert(v4, " (")
		local v13 = typeof(p1)
		table.insert(v4, v13)
		table.insert(v4, ")")
	end
	return table.concat(v4, "")
end
return v_u_14
