-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMRBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZAZFbnVtZXIKVGFibGVVdGlscxpyZXF1aXJlVmFsaWRJbmRleEFuZEZyZWV6ZRpDQVNIX0VBUk5FRF9UUklHR0VSX0FNT1VOVBxTSE9XX0xJS0VfUFJPTVBUX1JFTU9URV9OQU1FIExJS0VfUFJPTVBUX1JFU1BPTlNFX1JFTU9URV9OQU1FDVJFU1BPTlNFX0VOVU0YTElLRV9QUk9NUFRfVklTSUJMRV9USU1FDlNob3dMaWtlUHJvbXB0Ekxpa2VQcm9tcHRSZXNwb25zZQJPaw1SZW1pbmRNZUxhdGVyAAEJAAABAgAwowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAoQYAAABNAgNXBwAAAJ8BAgKkAgUAAABAQE0EAKEGAAAATQMEGAgAAACfAgICTQMCAAkAAADiBA8AjAWoYTAFBNcKAAAAbwUQADAFBB0LAAAAbwURADAFBFkMAAAAUgUBAP8GAAACAAAAbwcSAG8IEwDFBgcDAQAAAJ8FAgIwBQRaDQAAAIwFHgAwBQRyDgAAAJ8DAgCCAwAAFAMBBAAAAEADAgMDAwQEAABAQAMFAwYDBwMIAwkDCgMLAwwDDQUFCgsMDQ4DDgMPAxADEQABAAEYAAEAAAAAAAEAAAAAAAABAAAAAAAAAQAAAQAAAQAAAQAAAQAAAAAAAAAAAAEAAPsAAQAAAAAAawS05I93gfdZwN5wIHcLKhD0854F14a9OLy4y0LC34O46Hk1XMKiUg==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v2 = require(v1.Std.Enumer)
return require(v1.Std.TableUtils).requireValidIndexAndFreeze({
	["CASH_EARNED_TRIGGER_AMOUNT"] = 25000,
	["SHOW_LIKE_PROMPT_REMOTE_NAME"] = "ShowLikePrompt",
	["LIKE_PROMPT_RESPONSE_REMOTE_NAME"] = "LikePromptResponse",
	["RESPONSE_ENUM"] = v2({ "Ok", "RemindMeLater" }),
	["LIKE_PROMPT_VISIBLE_TIME"] = 30
})
