-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgPfAQNEb3QEbWF0aANhYnMRZ2V0Q2xvc2VzdFZlY0R1YWwFQ3Jvc3MGQ0ZyYW1lBkFuZ2xlcwNuZXcBeAF5AXoLcm90QnR3blVuaXQFZmxvb3IGcm91bmRODVVzZXJJbnB1dFR5cGUERW51bQhHYW1lcGFkMQdLZXlDb2RlB0J1dHRvbkEMTW91c2VCdXR0b24xBVRvdWNoCmlzRHJhZ2dpbmcXZ2V0VGltZVNpbmNlTGFzdERyYWdFbmQYcXVlcnlDdXJyZW50U3RhbmRpbmdIb21lDHJheWNhc3RNb3VzZQhJbnN0YW5jZQZpcGFpcnMGR2V0QWxsBkdldE9iag5Jc0Rlc2NlbmRhbnRPZglzdGFydERyYWcKaW5wdXRCZWdhbghUb3VjaFRhcAdDb25uZWN0GF9saXN0ZW5Gb3JDdXN0b21pemVUb3VjaApJbnB1dEJlZ2FuGF9saXN0ZW5Gb3JDdXN0b21pemVDbGljawhzdG9wRHJhZw1jcmVhdGVBbmREcmFnBG5hbWUcYXR0ZW1wdERlbGV0ZUN1cnJlbnRIb21lSXRlbQVfbWFpZBJvbkN1c3RvbWl6ZVN0YXJ0ZWQQb25DdXN0b21pemVFbmRlZAhvbkV4aXRlZBJvbkF0dGVtcHRQbGFjZUl0ZW0Tb25BdHRlbXB0RGVsZXRlSXRlbQRpbml0CFBvc2l0aW9uElBvaW50VG9PYmplY3RTcGFjZQdWZWN0b3IzEVBvaW50VG9Xb3JsZFNwYWNlBk5vcm1hbBFnZXRUYXJnZXRQb3NpdGlvbhBfY3VycmVudEhvbWVJdGVtD1NldEJlaW5nRHJhZ2dlZAR0eXBlBXZhbHVlCnNldFZpc2libGUIZGlzcGF0Y2gEX29iagtUcmFuc2xhdGVDZhRTZXRQcmltYXJ5UGFydENGcmFtZQhJc1BsYWNlZA1BdHRlbXB0RGVsZXRlEkNsZWFyQ2FjaGVTdXJmYWNlcwpDYW5Db2xsaWRlBEp1bXACb3MFY2xvY2sDbWluCVNldFRhcmdldAhkb1JvdGF0ZRFsaXN0ZW5Gb3JGZWVkYmFjawxfcGxhY2VSZW1vdGUNT25DbGllbnRFdmVudAlfYWxpZ25NYXQPU2V0U2VydmVyQ0ZyYW1lG2F0dGVtcHRQbGFjZUN1cnJlbnRIb21lSXRlbQ1vbkNsaWNrRGVsZXRlDG9uQ2xpY2tQbGFjZQlIZWFydGJlYXQPcm90YXRlSGVhcnRiZWF0C29uRG93blJpZ2h0CW9uVXBSaWdodApvbkRvd25MZWZ0CG9uVXBMZWZ0B3VubW91bnQOVXNlcklucHV0U3RhdGUDRW5kCndhaXRGb3JFbmQIS2V5Ym9hcmQBUQhCdXR0b25MMgFFCEJ1dHRvblIyGEdldFByb3BlcnR5Q2hhbmdlZFNpZ25hbAZVcGRhdGUKZnJvbU1hdHJpeAtSaWdodFZlY3RvcgRVbml0CFVwVmVjdG9yDElzVmFsaWRVcERvdBRJc1dpdGhpbkJvdW5kc0NhY2hlZAxUcmFuc3BhcmVuY3kJU2V0Q0ZyYW1lDl9sYXN0RHJhZ1N0YXJ0C1ByaW1hcnlQYXJ0DVVudHJhbnNsYXRlQ2YJcGxhY2VNYWlkCEdpdmVUYXNrDUNhY2hlU3VyZmFjZXMOR2V0RGVzY2VuZGFudHMIQmFzZVBhcnQDSXNBBXRhYmxlBmluc2VydAlDaGFyYWN0ZXIISHVtYW5vaWQORmluZEZpcnN0Q2hpbGQHQ2hhbmdlZAdjb25uZWN0BFBhcnQGQ29sb3IzBUNvbG9yCEFuY2hvcmVkClRvcFN1cmZhY2UNQm90dG9tU3VyZmFjZQRTaXplBlBhcmVudAFwB0ludmVyc2UNVG9PcmllbnRhdGlvbgVtb3VudAlTY3JlZW5HdWkOWkluZGV4QmVoYXZpb3IMUmVzZXRPblNwYXduDklnbm9yZUd1aUluc2V0DERpc3BsYXlPcmRlcgdTaWJsaW5nD1BsYWNlckNvbnRhaW5lcgVGcmFtZRZCYWNrZ3JvdW5kVHJhbnNwYXJlbmN5C0FuY2hvclBvaW50BVVEaW0yCWZyb21TY2FsZQdWZWN0b3IyF1VJQXNwZWN0UmF0aW9Db25zdHJhaW50CVBsYWNlckFwcAtBc3BlY3RSYXRpbwthc3BlY3RSYXRpbxR2ZXJ0aWNhbFBhZGRpbmdSYXRpbwlzaG93UGxhY2UMVG91Y2hFbmFibGVkC0xvY2FsUGxheWVyCVBsYXllckd1aQ1JdGVtUGxhY2VyR3VpCklucHV0RW5kZWQNb25EcmFnU3RhcnRlZARGaXJlCkxvb2tWZWN0b3IEZmluZAZyZW1vdmUSVmVjdG9yVG9Xb3JsZFNwYWNlE1ZlY3RvclRvT2JqZWN0U3BhY2UMX2xhc3REcmFnRW5kC29uRHJhZ0VuZGVkBmFzc2VydBlnZXRUaW1lU2luY2VMYXN0RHJhZ1N0YXJ0CHJlb3BlblVJDl9saXN0ZW5OZXdJdGVtAmlkGUVOVU1fSE9NRV9JVEVNX05FV19SRVNVTFQHU1VDQ0VTUxl5aWVsZEZvck9ialZhbHVlUG9wdWxhdGVkCG1vZGVsUHRyBVZhbHVlEXByb21pc2VCb3VuZENsYXNzB2FuZFRoZW4Ed2FybgVjYXRjaAhUT09fTUFOWQRUZXh0K1RvbyBtYW55IGl0ZW1zIHBsYWNlZC4uLiB0cnkgZGVsZXRpbmcgc29tZS4QQUxMX09XTkVEX1BMQUNFRCdZb3UgcGxhY2VkIGFsbCBvZiB0aGVzZSB0aGF0IHlvdSBvd24uLi4KTUFYX1BMQUNFRDBZb3UgcmVhY2hlZCB0aGUgcGxhY2VtZW50IGxpbWl0IGZvciB0aGlzIGl0ZW0uLi4FZXJyb3IXVW5oYW5kbGVkIHJlc3VsdCBpZDogJWQGZm9ybWF0El9ob21lSXRlbU5ld1JlbW90ZRVBdHRlbXB0Q3JlYXRlSG9tZUl0ZW0EZ2FtZQpHdWlTZXJ2aWNlCkdldFNlcnZpY2UHUGxheWVycwpSdW5TZXJ2aWNlEFVzZXJJbnB1dFNlcnZpY2URUmVwbGljYXRlZFN0b3JhZ2UHcmVxdWlyZQNBcHAUU3RyZWFtaW5nSGVscGVyVXRpbHMER2FtZQxOb3RpZmljYXRpb24ESG9tZQpIb21lQ29uc3RzA1N0ZARNYWlkBlNwcmluZwZTaWduYWwOSG9tZUl0ZW1CaW5kZXIISG9tZUl0ZW0GQmluZGVyC0JpbmRlclV0aWxzD0l0ZW1QbGFjZXJVdGlscwZzY3JpcHQKSG9tZVN5c3RlbQ5Ib21lSXRlbVN5c3RlbQJVSQlob21lU3RvcmUFUm9hY3QNY3JlYXRlRWxlbWVudAAxDQIAAAAAHBMCAABvAwAAUgQAAMYFAADGBgAAZAQTAFILAQC8CQgrAQAAAJ8JAwK7AgkDUgsJAKQKBAAADCCAnwoCAmADCQAKAAAAUgMKAIwMAABgDAMACQAAAIwLAQBlAAEAjAv//wkCCAtuBOz/AgAAAIICAgAFAgAAAAAAAPD/AwEDAgMDBAAMIIAAGQQBGAACAQAAAAEAAAABAAAAAAEAAQEAAAAAAAD7AAgaAAAAAAwCAAAABwQAAAUCCAggUgQBALwCALsAAAAAnwIDAlIFAQC8AwArAQAAAJ8DAwJvBAIAYAMIAAQAAACkBAUAABAwgG8FBgCMBgAAjAcAAJ8EBACCBAAApAQIAAAcMICMBQAAjAYAAIwHAABNCAKZCQAAAE0JApgKAAAATQoCmwsAAACVCwMMnwQIAIIEAAANAwUDAQIrhxbZzvfvvwMGAwcEABAwgAIYLURU+yEJQAMIBAAcMIADCQMKAwsCAAAAAAAA8D8AJwwBGAAAAAABAAAAAQAAAgAAAAAAAAIAAAAAAAAAAAAAAAAAKAAAAAAGAgAAAAAI7AUAAZUEBQC7DAQCpAMDAAAIEICfAwICCQIDAYICAgAEAgAAAAAAAOA/AwIDDQQACBCAADAOARgAAAAAAAAAADEAAAAADwIFAAAAVKkCAABNAwDCAAAAAKQEAwACABDAmgMJAAQAAABNAwCzBAAAAKQEBgAFEBDA8QMCAAQAAACpAgABqQIBAA4BAgArAgEAggABAE0DAMIAAAAApAQIAAcAEMDxAwgABAAAAE0DAMIAAAAApAQKAAkAEMDxAwIABAAAAA4CNAD7BAAATQME9wsAAACfAwECDgMBAIIAAQD7BAAATQMEvgwAAACfAwECbwQNAGADAgAEAAAAggABAPsEAQBNAwRcDgAAAJ8DAQIrAwEAggABAPsFAgBNBAUHDwAAAPsFAwCpBgEAnwQDAg4EGQBNBQT0EAAAAKQGEgAAABBB+wcEALwHB9ATAAAAnwcCAJ8GAARRBg0AvA0KyRQAAACfDQIAvAsFrRUAAACfCwACDgsGAPsMAABNCwzYFgAAAFIMCgCfCwIBggABAG4G8v8CAACAggABABcDDwMQAxEEAgAQwAMSAxMEBRAQwAMUBAcAEMADFQQJABDAAxYDFwKamZmZmZm5PwMYAxkDGgMbBAAAEEEDHAMdAx4DHwBDIAEYAAAAAAAAAAEAAAAAAAAAAQABAwAAAAAAAQAAAAAAAAsAAAAAAQMAAAAAAAABBAAAAAEBAwAAAAAAAQEAAQAAAAAAAAABAAAAAAAAAQAAAAAB/QAIRAAAAAAFAAcAAAAb2QAAABICAAASAgEAEgICABICAwASAgQA+wEFAPsDBgBNAgPTAAAAAFIEAAC8AgLHAQAAAJ8CAwIwAgFrAgAAAPsBBQD7AwYATQIDggMAAABSBAAAvAICxwEAAACfAgMCMAIBqAQAAACCAAEABQMhAyIDIwMkAyUBA0IAARgAAAAAAAAtAAAAAAAAAAAAAQAAAAAAAAAAAAFDAAAAAAIAAgAAABL7AAAAxgEAADABAKgAAAAA+wAAAMYBAAAwAQBrAQAAAPsBAQBNAAH3AgAAAJ8AAQIOAAQA+wEBAE0AAa8DAAAAnwABAYIAAQAEAyUDIwMWAyYAcwABGAAAAAABAAAAAQAAAAABAAAAAnQAAAAAAgACAAAAEvsAAADGAQAAMAEAqAAAAAD7AAAAxgEAADABAGsBAAAA+wEBAE0AAfcCAAAAnwABAg4ABAD7AQEATQABrwMAAACfAAEBggABAAQDJQMjAxYDJgB7AAEYAAAAAAEAAAABAAAAAAEAAAACfAAAAAADAQEAAAAH+wIAAE0BApUAAAAATQIAWgEAAACfAQIBggABAAIDJwMoAIMBAAEYAAAAAAAAAYYAAAAAAgABAAAABfsBAABNAAEqAAAAAJ8AAQGCAAEAAQMpAIgBAAEYAAAAAAGJAAAAAAUABwAAADr7AQAATQAB7wAAAACfAAEC+wEBADAAAcEBAAAA/wEAAAAAAAD7AwIATQIDhQIAAADZBAAAEgIBABICAwASAgQAEgABABICBQASAAAAEgIGALwCAscDAAAAnwIDAfsDAgBNAgNDBAAAANkEAQASAAAAEgIBALwCAscDAAAAnwIDAfsDAwBNAgNPBQAAANkEAgASAAAAEgIBALwCAscDAAAAnwIDAfsDAgBNAgOfBgAAAMAEBwASAgEAvAICxwMAAACfAgMB+wMCAE0CAyUIAAAAwAQJABICAQC8AgLHAwAAAJ8CAwGCAAEACgMIAyoDKwMiAywDLQMuBgcDLwYIBQQFBgcIPDABGAAAAAABAAACAAIAAAAAAAAAAAAAAAAAMQAAAAAAAAAACAAAAAAAAAAACAAAAAAAAAAFAAAAAAAAAAM9AAAAAAwBAQAAADX7AgAATQECBwAAAABSAgAAnwECAg4BLgBNAgH0AQAAAE0DAoUCAAAATQUBOwMAAAC8AwPGBAAAAJ8DAwJNBgOZBQAAAD4JBgaVCAkHuwwIAqQHCgAAJICAnwcCAlsFBwZNBgOYCwAAAE0IA5sMAAAAPgsIBpUKCwe7DAoCpAkKAAAkgICfCQICWwcJBkw2AAKkBA8AADjQgJ8EBAJSAwQATQQChQIAAABSBgMAvAQEOBAAAACfBAMCUgUEAE0GARARAAAATQcChQIAAACCBQQAggABABIDGQMaAwYDMQMyAwkCmpmZmZmZuT8CAAAAAAAA4D8DAgMNBAAkgIADCgMLAzMDCAQAONCAAzQDNQCOATYBGF4AAAAAAQEAAgAAAAAAAAIAnAAAAAAAAGUAAQCaAAAAAAAAYwAAAAAFAAAAAAABAAAAAAACMQAAAAACAAEAAAAF+wAAAMYBAAAwAQABAAAAAIIAAQABAzcApwEAARgAAAAAAagAAAAAAwABAAAABvsAAACpAgAAvAAAygAAAACfAAMBggABAAEDOACrAQABGAAAAAAAAawAAAAABAABAAAADPsAAADiAgIAbwMDADADAnEAAAAAqQMBADADAswBAAAAvAAATAQAAACfAAMBggABAAUDOQM6BQIAAQM7AzwAtAEAARgAAAEAAAEAAP4AAAS1AAAAAAUAAwAAABv7AAAAKwAYAPsBAQBNAAFuAAAAAA4ACwD7AQEATQABbgAAAAD7AgEA+wQCALwCAjIBAAAAnwIDALwAAGYCAAAAnwAAAfsAAQC8AADVAwAAAJ8AAgIrAAQA+wABALwAANMEAAAAnwACAYIAAQAFAz0DPgM/A0ADQQC8AQABGAAAAQAAAAEAAAAAAAAAAAAAAgAAAAABAAAAA70AAAAAAgABAAAABfsAAAC8AABGAAAAAJ8AAgGCAAEAAQNCAMkBAAEYAAAAAAHKAAAAAAYAAQAAAAukAAEAAAAAQPsBAACfAAIEUQADAKkFAQAwBQTTAgAAAG4A/P8CAACAggABAAMDGwQAAABAA0MA3QEAARgAAAAAAAEAAP8ABt4AAAAAAgABAAAABfsAAACpAQAAMAEAUwAAAACCAAEAAQNEAOgBAAEYAAAAAAHpAAAAAAsDAwAAADSkAwIAAAQAgJ8DAQImBAMCbwYDAGAGCgAEAAAAjAYMAD4IBAOVBwgEnhMGAwcAAACkBQcAABhQgJ8FAwJlAAEAjAUBAPsHAAAmBgMHbwcDAGAGAgAHAAAAggABAN4DAAAOAAYA+wYBAG8ICAAJBwgFQwYGB94GAQBlAAYADgEFAPsGAQBvCAgACQcIBSYGBgfeBgEA+wcBAD4KBwiVCQoJuwwJAqQICwAAKFCAnwgCAlsGCAjeBgEA+wYCAPsIAQC8BgaXDAAAAJ8GAwGCAAEADQNFA0YEAAQAgAKamZmZmZm5PwIAAAAAAADwPwMCA0cEABhQgAKHROdKGFe2PwIAAAAAAADgPwMNBAAoUIADSACOAkkBGN4AAAEBAAAAAAAAAAAAAAAAAQAAAAABAgIBAAAAAAABAQAAAAACFQAAAAAAAOsBAAAAAAExAAAAAAYBAwAAABf7AgAATQECwQAAAADGAgAAMAIBiAEAAAArAA8A+wIBAE0BAm4CAAAADgELAPsCAQBNAQJuAgAAAPsDAQD7BQIAvAMDMgMAAACfAwMAvAEBZgQAAACfAQABggABAAUDKgNKAz0DPgM/AKECAAEYAAAAAAAAAQEAAAABAAAAAAAAAAAAAAMiAQAAAAwABwAAADX7AQAATQABwQAAAAD7AwEATQIDmwEAAABNAQKMAgAAANkDAAASAgAAEgIBABICAgC8AQHHAwAAAJ8BAwIwAQCIBAAAAPsBAABNAAHrBQAAAPsBAwCfAAIE+wQAAE0DBMMGAAAAUgQBAFIFAgD7BgQAnwMEAvsEAQCkCAkAACBwgIwJAAD7CgUAjAsAAJ8IBAIJBwMIQwYHALwEBDIKAAAAnwQDAvsFAQBSBwQAvAUF5wsAAACfBQMBqQUBAN4FBgD7BgAATQUGrwwAAACfBQEBggABAA0DKgNLA0wDIgNKAzYDTQMGAwcEACBwgAM+A04DJgEToAJPARgAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAQAAAAAAAAIAAAAAAAAAAAAAAAEAAAAAAQABAAAAASEBAAAAAgABAAAABfsBAABNAAEqAAAAAJ8AAQGCAAEAAQMpAMYCUAEYAAAAAAFHAQAAAAEAAQAAAAP7AAAAnwABAYIAAQAAAMkCUQEYAAABSgEAAAAEAAIAAAAG+wAAAKkBAACpAgEA+wMBAJ8ABAGCAAEAAADOAgABGAAAAAAAAU8BAAAABQADAAAAEKQAAgAABACAnwABAvsBAAD7AwEATQID/QMAAADZBAAAEgICABIAAAC8AgLHBAAAAJ8CAwIwAgH5BQAAAIIAAQAGA0UDRgQABACAA1IDIgNTARfMAlQBGAAAAAEAAAAAAAAAAAAAAANNAQAAAAIAAQAAAAX7AAAAxgEAADABAPkAAAAAggABAAEDUwDSAlUBGAAAAAABUwEAAAAEAAIAAAAG+wAAAKkBAQCpAgAA+wMBAJ8ABAGCAAEAAADXAgABGAAAAAAAAVgBAAAABQADAAAAEKQAAgAABACAnwABAvsBAAD7AwEATQID/QMAAADZBAAAEgICABIAAAC8AgLHBAAAAJ8CAwIwAgH5BQAAAIIAAQAGA0UDRgQABACAA1IDIgNTARrVAlYBGAAAAAEAAAAAAAAAAAAAAANWAQAAAAIAAQAAAAX7AAAAxgEAADABAPkAAAAAggABAAEDUwDbAlcBGAAAAAABXAEAAAACAAIAAAAG+wEAAE0AARIAAAAA+wEBAJ8AAgGCAAEAAQNYAOUCAAEYAAAAAAABZgEAAAAEAgEAAAANDgEBAIIAAQBNAgDCAAAAAKQDAwACABDAmgIFAAMAAAD7AgAAxgMAADADAvkEAAAAggABAAUDDwMQAxQEAgAQwANTAOoCAAEYAAECAAAAAAABAAAAAmsBAAAAAgACAAAAEPsBAABNAAH/AAAAAKQBAwACABDAmgAJAAEAAAD7AAEAxgEAADABAPMEAAAA+wABAMYBAAAwAQD5BQAAAIIAAQAGA1kDEANaBAIAEMADWwNTAIIDAAEYAAAAAAAAAAEAAAABAAAAAoMBAAAABAAEAAAABvsAAAD7AQEA+wICAPsDAwCfAAQBggABAAAAiAMAARgAAAAAAAGJAQAAAAkCAwAAAE0OAQEAggABAE0CAMIAAAAApAMDAAIAEMDxAgcAAwAAAE0CAMIAAAAApAMFAAQAEMCaAj8AAwAAAKkCAQBNAwCzBgAAAKQECAAHGBDA8QMJAAQAAABNAwCzBgAAAKQECgAJGBDA8QMCAAQAAACpAgABqQIBAKkDAQBNBACzBgAAAKQFDAALGBDA8QQJAAUAAABNBACzBgAAAKQFDgANGBDA8QQCAAUAAACpAwABqQMBACsDAQAOAh4ApAQRAABA8ICfBAEC+wUAAG8IEgC8BgCUEwAAAJ8GAwLZCAAAEgAAABICAAC8BgbHFAAAAJ8GAwIwBgXzFQAAAPsFAAD7BwEATQYH/RYAAADZCAEAEgICABIAAgASAAMAEgAEALwGBscUAAAAnwYDAjAGBfkXAAAAggABABgDDwMQA1wEAgAQwAMRBAQAEMADEgNdBAcYEMADXgQJGBDAA18ECxgQwANgBA0YEMADRQNGBABA8IADWQNhAyIDWwNSA1MCHyDyAgABGAABAwAAAAAAAQAAAAAAAgAAAAAAAAEAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAgABAAACAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAFcwEAAAAZAA0AAACAAfsBAABNAAHrAAAAAPsBAQCfAAIEDgB5APsDAgBSBQAAvAMDlwEAAACfAwMD+wUDAFIHAAC8BQWXAQAAAJ8FAwP7BwQAvAcHJgIAAACfBwIC+woFALwIASsDAAAAnwgDAm8JBABgCAkACQAAAPsJBwD7CgUAUgsBAJ8JAwL7CgYACQgJCt4IBgDeAQUA+wkAAE0ICcMFAAAAUgkBAFIKAgD7CwYAnwgEAqQJCAAAHGCAbwoJAPsMCABNDghNCgAAALwMDJcBAAAAnwwDAk0LDAcLAAAA+w0JAE0PCBEMAAAAvA0NlwEAAACfDQMCTQwNBwsAAACfCQQC+woKAKQODgAANGCAjA8AAPsQCwCMEQAAnw4EAgkNCA5DDA0AvAoKMg8AAACfCgMCTQsKEQwAAABvDRAAvAsLKwMAAACfCwMC+wwKAFIOCwC8DAxyEQAAAJ8MAwL7DQoAUg8KALwNDZQSAAAAnw0DAucODQz7DwwADg4CAIwQAQBlAAEAbxATADAQD9kUAAAA+w8KAKQUDgAANGCATRcGmxYAAAA5FhcAWxUWFYwWAABNGAaZFwAAAFsXGBWfFAQCCRMJFKQUDgAANGCAjBUAAFIWBwCMFwAAnxQEAgkSExRDERIDvA8PMg8AAACfDwMC+xAKAFISDwC8EBDaGAAAAJ8QAwGCAAEAGQM2A0gDYgMBAq5H4XoUru8/A00DBgNjBAAcYIAHAAAAAAAAAAAAAAAAAAAAAANkA2UDZgMHBAA0YIADPgcAAAAAAACAPwAAAAAAAAAAA2cDaAIAAAAAAADgPwNpAvp+arx0k1g/AwsDCQNqAI8DAAEYAAAAAAACAQAAAAABAAAAAAEAAAACAAAAAAAAAQAAAAAAAAEDAAAAAAAAAQABAQAAAAAAAAABAAAAAAAAAP0GAAAAAAAAAAAAAAACAAAAAAABAAAAAAMAAAAAAQEAAAAAAAACAgAAAAAAAAAAAAAAAQAAAAAAAAD9AAAGAAAAAAKQAQAAAAUCAQAAABypAgAATQMAwgAAAACkBAMAAgAQwJoDCQAEAAAATQMAswQAAACkBAYABRAQwPEDAgAEAAAAqQIAAakCAQAOAQIAKwIBAIIAAQBNAwDCAAAAAKQECAAHABDA8QMCAAQAAAAOAgIA+wMAAJ8DAQGCAAEACQMPAxADEQQCABDAAxIDEwQFEBDAAxQEBwAQwAC2AyABGAAAAAAAAAABAAAAAAAAAAIAAQIAAAAAAAAGAAK3AQAAACkBDAAACAAAAQgKmwEB3QP7AQAApAICAAAEAICfAgECMAIBfAMAAAC8AgDJBAAAAJ8CAgJNAQKbBQAAAE0EAYUGAAAAvAIAEQcAAACfAgMC+wQBAE0DBO8IAAAAnwMBAvsFAABNBAXBCQAAADADBMcKAAAA+wQAADAABAELAAAAwAYMABICAAC8BAP9DQAAAJ8EAwGpBgEAvAQAyg4AAACfBAMB2QYBABIAAAC8BAP9DQAAAJ8EAwH7BAIA4gYRAG8HEgAwBwZxDwAAAKkHAAAwBwbMEAAAALwEBEwTAAAAnwQDAcAGFAASAgIAvAQD/Q0AAACfBAMBqQQAANkHAwASAQT/EgAAABIAAgC8BQP9DQAAAJ8FAwG8BQCoFQAAAJ8FAgHZBwQAEgAAALwFA/0NAAAAnwUDAf8FAAAAAAAApAYXAAAAYEG8BwDJBAAAAJ8HAgK8BwdHGAAAAJ8HAgCfBgAEUQYSAG8NGQC8Cwr+GgAAAJ8LAwIOCw0ATQsK0xsAAAAOCwoAnjQFBQoAAABSDAUAUg0KAKQLHgAAdMCBnwsDAakLAAAwCwrTGwAAAG4G7f8CAACA2QgFABIABQC8BgP9DQAAAJ8GAwH7BwMATQYHaR8AAABvCCAAvAYGAyEAAACfBgMCTQkGhSIAAADZCwYAEgAGALwJCecjAAAAnwkDALwHA/0NAAAAnwcAAaQHJQAAIECCbwgmAJ8HAgKkCCgAACBwgowJAQCMCgAAjAsAAJ8IBAIwCAekKQAAAKkIAQAwCAdFKgAAAKkIAAAwCAfTGwAAAIwIAACMCQAAMAgHHysAAAAwCQcSLAAAAE0JAS8tAAAAbwouAEMICQowCAcvLQAAAE0IAYUGAAAAMAgHhQYAAACMCAEAMAgH2S8AAAC8CADJBAAAAJ8IAgIwCAckMAAAAFIKBwC8CAP9DQAAAJ8IAwH/CAAAAgAAALwJAMkEAAAAnwkCAvsLAwBNCgtpHwAAAMUICQMBAAAAUgkCAE0KCZExAAAAJgkJCvsLAABNCgvrMgAAAFILCACfCgIETQ0JETMAAABSEA0AvA4LKzQAAACfDgMCbw81AGAOBwAPAAAA+w4EAFIPDQBSEAsAnw4DAgkJDglSDQsA+w8AAE0OD8M2AAAAUg8LAFIQDABSEQkAnw4EArwQDto3AAAAnxACAgkPEAK8Dw8HOAAAAJ8PAgRNEgKRMQAAAPsUBQBNExTvCAAAAFIUEgBMNgACpBU6AAAgkIOfFQECbxY7AIwXMgCfEwUC+xUFAE0UFe8IAAAAUhUSAEw2AAKkFjoAACCQg58WAQJvFzwAjBgeAJ8UBQL7FgUATRUW7wgAAABNFg5NPQAAAEw2AAKkFzoAACCQg58XAQJvGDsAjBkyAJ8VBQL7FwUATRYX7wgAAABNFw4RMwAAAEw2AAKkGDoAACCQg58YAQJvGTsAjBoyAJ8WBQL7GAUATRcY7wgAAABSGBAAjBkAAG8aOwCMGx4AnxcFAowYAADZGQcAEgEY/xIBEP8SABcA2RoIABICAAASAAAAEgACABIACAASAQn/EgEQ/xIBBP/7HAYATRsc5D4AAAD7HAcAbx0/AOIeRACkH0cARgBRxDAfHntAAAAAqR8AADAfHqRBAAAAqR8BADAfHgVCAAAAjB8BADAfHstDAAAA4h9JAPsgBwBvIUoA4iJOAIwjAQAwIyI6SwAAAKQjUQAAQPGEbyRSAG8lUwCfIwMCMCMiLy0AAACkI1EAAEDxhG8kUgBvJVQAnyMDAjAjIjtMAAAApCNWAAAgUIVvJFIAjCUBAJ8jAwIwIyLoTQAAAOIjWQD7JAcAbyVXAOImWwCMJwcAMCcmaVoAAACfJAMCMCQjhlcAAAD7JAcA+yUIAOImZQCMJwcAMCcmiVwAAABvJ2YAMCcmxl0AAADAJ2cAEgIAADAnJiBeAAAA2ScKABIAGgAwJyaRXwAAANknCwASAAMAEgIJABIAGQAwJyb4YAAAANknDAASAAMAMCcmO2EAAADZJw0AEgADABICCQASABkAMCcmzWIAAADZJw4AEgADADAnJgNjAAAA+ygKAE0nKH9oAAAAMCcmCmQAAACfJAMCMCQjy1gAAACfIAQCMCAfwUgAAACfHAQC+x8LAE0eHzFpAAAATR0emWoAAABvHmsAnxsEAtkeDwASAgYAEgAbALwcA/0NAAAAnxwDAfsfCgBNHh+vbAAAANkgEAASAAMAvB4ex20AAACfHgMAvBwD/Q0AAACfHAAB+x8KAE0eH4JuAAAA2SARABIAAwASAgkAEgAZALweHsdtAAAAnx4DALwcA/0NAAAAnxwAAfsfCQBNHh/9bwAAANkgEgASAgAAEgAIABIAEwASABQAEgAXABIBDf8SAQn/EgIEABIAFQASABYAEgAAABIBEP8SAAcAvB4ex20AAACfHgMAvBwD/Q0AAACfHAAB2RwTABIAGgD7IAoATR8ggm4AAABSIRwAvB8fx20AAACfHwMAvB0D/Q0AAACfHQAB+x4AAE0dHmFwAAAAvB0d3XEAAACfHQIBwQQAAIIAAQByA0UDRgQABACAA2sDHQNsAwYDbQMIAyoDbgM3BgsDbwM4AzkDOgUCDxADOwM8Bg0DcAMbBAAAYEEDcQNyA3MDQwN0A3UEAHTAgQN2A3cDeAN5A3oDGgQAIECCA3sDfAQAIHCCA30DfgN/A4ABA4EBB83MzD3NzMw9zczMPQAAAAADaQOCAQODAQM2A2YDAQKuR+F6FK7vPwNNA4QBA4UBAzMEACCQgwKamZmZmZnpPwJmZmZmZmbmPwNkA4YBA4cBA4gBA4kBA4oBA4sBBQRAQUJDAxADjAEERgBRxAONAQUBSAOOAQOPAQMxA5ABBQRLLUxNA5EBA5IBBABA8YQCAAAAAAAA4D8CexSuR+F6tD8CMzMzMzMz6z8DkwEEACBQhQOUAQOVAQUCV1gDlgEFAVoDlwEDmAEDUANRA1QDVQNWA1cDmQEFCVxdXl9gYWJjZAKSJEmSJEkyQAYVA5oBA5sBA5wBA50BA54BAyIDJANSA58BA6ABFAsMDQ4PEBESFBUWGBkbHB0eISIjnQEfAQgAAAAAAAACAAAAAAEAAAAAAgAAAAEAAAAAAgAAAQAAAAADAAAAAQAAAAAFAAEAAAEAAP4AAAQAAAAABwEAAAAAAAAMAAABAAAAAAQAAgAAAAAAAAAAAAEAAAAAAQAAAQAAAAAAAAEAAPwADgAAAAAKAAAAAAAAAQAAAAAAAAAAAAUAAAABAAAAAAAAAAEAAAEAAAEAAAAAAAEAAAAAAAEAAAABAAABAAAAAAEAAAACAAAAAAAAAAAAAgEAAAEAAAAAAQABAAAAAAAAAQAAAAABAgAAAAAAAAEAAAAAAAACAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAACAAAAAAAAAAAAlQABAAAAAAAAAAAAAAABAAAAAAAAAAIBAAAAEgAAAAAAAAATAAABAAABAAAAAQAAAQAAAQAAAQEAAAEAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEBAAABAAD/AAADAAABAAABAAABAAAAAwAAAAMAAAAAAAYAAAADAAAAAAAGAAAAAwAAAADlAAD3AAD6LgAAAAAB0DIAAAAAAAUAAAAAAAAAAAAACAAAAAAAAAAAAAAAAB0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAJwAQAAAAAAAAAAAAAgAAAAAAAQCeAAAAawAAAAAOAwIAAAA7/wMAAAMAAABNBAFoAAAAAE0FAU0BAAAATQYBEQIAAADFAwQEAQAAAPsEAABSBQMAUgYAAJ8EAwKkBQUAABAwgFIGAwBSBwQAnwUDAg4FCQCkBQcAABgwgFIGAwCkBwUAABAwgFIIAwBSCQQAnwcDAJ8FAAGkBQUAABAwgFIGAwA5BwQAnwUDAg4FCQCkBQcAABgwgFIGAwCkBwUAABAwgFIIAwA5CQQAnwcDAJ8FAAH7BQEAbwYIAPsJAABSCgMAbw0IALwLAq4JAAAAnwsDAJ8JAAK8BwLsCgAAAJ8HAwCfBQACCQICBYICAgALA6EBA2QDZgN0A6IBBAAQMIADowEEABgwgAcAAIA/AAAAAAAAAAAAAAAAA6QBA6UBAMoDTQEYAAABAAEAAQAAAAMAAAABAAAAAAABAAAAAAAAAAACAAAAAAABAAAAAAAAAAAFAQEAAAAAAAAAAAD+AAXLAQAAAAIAAQAAABP7AQAATQABwQAAAADGAQAAMAEAxwEAAAD7AAAApAEEAAAMIICfAQECMAEAxgUAAAD7AQAATQABywYAAAC8AADdBwAAAJ8AAgGCAAEACAMqA24DRQNGBAAMIIADpgEDpwEDoAEA4gMmARgAAAAAAAABAAAAAAABAAAAAAAB4wEAAAAEAAEAAAAO+wEAAE0AAcEAAAAADgAJAPsDAABNAgPBAAAAAE0BAscBAAAARwECAAAAAICpAAABqQABAIIAAgACAyoDbgDnAxYBGAAAAAAAAAAAAAAAAAAA6AEAAAADAAEAAAAb+wIAAE0BAvcAAAAAnwEBAEwBAAKkAAIAAAAQQJ8AAAH7AQAATQABAQMAAABHAAIAAAAAgKkCAAGpAgEAuwECAqQBAgAAABBAnwECAfsCAABNAQKvBAAAAJ8BAQG8AQDTBQAAAJ8BAgGCAAEABgMWA6gBBAAAEEADNwMmA0EA6gMpARgAAAAAAAAAAAEAAAEAAAAAAAAAAQAAAAEAAAHrAQAAAAQAAQAAAAikAQIAAAQAgJ8BAQL7AwAATQIDfAMAAAAmAAECggACAAQDRQNGBAAEAIADawDxA6kBARgAAAAAAAAAAPIBAAAABAABAAAACKQBAgAABACAnwEBAvsDAABNAgPGAwAAACYAAQKCAAIABANFA0YEAAQAgAOmAQD0AxcBGAAAAAAAAAAA9QEAAAAEAAEAAAAM+wAAAOICAgBvAwMAMAMCcQAAAACpAwEAMAMCzAEAAAC8AABMBAAAAJ8AAwGCAAEABQM5AzoFAgABAzsDPAD8A6oBARgAAAEAAAEAAP4AAAT9AQAAAAQAAQAAAAz7AAAA4gICAG8DAwAwAwJxAAAAAKkDAQAwAwLMAQAAALwAAEwEAAAAnwADAYIAAQAFAzkDOgUCAAEDOwM8AI0EAAEYAAABAAABAAD+AAAEDgIAAAAEAQIAAAAQ+wIAAE0BAtgAAAAAUgIAAJ8BAgH7AwAATQIDwQEAAABNAQLHAgAAAMADAwASAgEAvAEB/QQAAACfAQMBggABAAUDHwMqA24GLANvASyKBAABGAAAAAAAAgAAAAAAAAAAAAYLAgAAAAUBCAAACAAAAQMChwECjAH7AgAATQECwQAAAADGAgAAMAIBXwEAAABNAQD0AgAAAPsEAQBNAwT0AwAAAE0CA9EEAAAAmgEdAAIAAAD7AgIATQEC9AUAAABNAgASBgAAAJ8BAgFNAgASBgAAAE0BAuwHAAAA+wMDAE0CAzUIAAAA+wMEAFIEAQCfAgMCwAQJABICBQASAgYAvAICtQoAAACfAgMCpAQMAAAAsEC8AgIZDQAAAJ8CAwGCAAEATQEA9AIAAAD7BAEATQME9AMAAABNAgOrDgAAAJoBFQACAAAA+wIHAE0BAu8PAAAA4gIRAG8DEgAwAwL1EAAAAJ8BAgH7AQYA4gMVAG8EFgAwBANxEwAAAKkEAQAwBAPMFAAAALwBAUwXAAAAnwEDAYIAAQBNAQD0AgAAAPsEAQBNAwT0AwAAAE0CA/sYAAAAmgEVAAIAAAD7AgcATQEC7w8AAADiAhEAbwMZADADAvUQAAAAnwECAfsBBgDiAxUAbwQWADAEA3ETAAAAqQQBADAEA8wUAAAAvAEBTBcAAACfAQMBggABAE0BAPQCAAAA+wQBAE0DBPQDAAAATQIDrxoAAACaARUAAgAAAPsCBwBNAQLvDwAAAOICEQBvAxsAMAMC9RAAAACfAQIB+wEGAOIDFQBvBBYAMAQDcRMAAACpBAEAMAQDzBQAAAC8AQFMFwAAAJ8BAwGCAAEApAEdAAAAwEFvAh4ATQQA9AIAAAC8AgKNHwAAAJ8CAwCfAQABggABACADKgOrAQOsAQOtAQOuAQOvAQOwAQOxAQOyAQYtA7MBA7QBBAAAsEADtQEDtgEDCAO3AQUBEAO4AQM5AzoFAhMUAzsDPAO5AQO6AQO7AQO8AQO9AQQAAMBBA74BA78BAS2EBAABGAgAAAAAAAEAAAAAAAAAAAEAAAAAAAEAAAABAAAAAAABAAAAAAAKAAAAAAABAAAAAAAAAAABAAAAAAAAAOcAAQAAAQAA/gAAABsAAAAAAAAAAAEAAAAAAAAA5AABAAABAAD+AAAAHgAAAAAAAAAAAQAAAAAAAADhAAEAAAEAAP4AAAAiAAAAAAAAAAAC/QEAAAAHAQkAAAAz+wEAAOIDAgBvBAMAMAQDcQAAAACpBAAAMAQDzAEAAAC8AQFMBAAAAJ8BAwHAAQUAEgIAAPsDAQBNAgNcBgAAAJ8CAQJHAgIAAAAAgKkEAAGpBAEAuwEEAqQDCAAAAHBAnwMCAfsEAgBNAwTBCQAAAE0FAqcKAAAATQQFjAsAAADABgwAEgICABICAwASAgQAEgIFABICBgASAgcAEgIAABICCAC8BATHDQAAAJ8EAwIwBANfDgAAAFIFAAC8AwKUDwAAAJ8DAwGCAAEAEAM5AzoFAgABAzsDPAYrAxgDqAEEAABwQAMqA8ABA0wGLgMiA6sBA8EBAisu9wMnARgAAAEAAAEAAP4AAAQABgAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAHgAAAAH4AQAAABoAAAECAO8BowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBAQAAAABAbwMEALwBARYDAAAAnwEDAk0CATEFAAAApAMBAAAAAEBvBQYAvAMDFgMAAACfAwMCpAQBAAAAAEBvBgcAvAQEFgMAAACfBAMCpAUBAAAAAEBvBwgAvAUFFgMAAACfBQMCpAYKAAAAkEBNCAXBCwAAAE0HCFoMAAAAnwYCAqQHCgAAAJBATQkFvQ0AAABNCAlJDgAAAJ8HAgKkCAoAAACQQE0KBWoPAAAATQkKWRAAAACfCAICpAkKAAAAkEBNCwWhEQAAAE0KC3YSAAAAnwkCAqQKCgAAAJBATQwFoREAAABNCwwiEwAAAJ8KAgKkCwoAAACQQE0NBaERAAAATQwNHxQAAACfCwICpAwKAAAAkEBNDwVqDwAAAE0OD+kWAAAATQ0OsBUAAACfDAICpA0KAAAAkEBNEAWhEQAAAE0PEH8XAAAATQ4P2RgAAACfDQICpA4KAAAAkECkERsAAACgQU0QESQcAAAATQ8QChkAAACfDgICpA8KAAAAkECkExsAAACgQU0SEyQcAAAATRESJBwAAABNEBFZHQAAAJ8PAgKkEAoAAACQQE0TBWoPAAAATRIT6RYAAABNERLdHgAAAJ8QAgKkEQoAAACQQE0UBWoPAAAATRMUXB8AAABNEhPLIAAAAJ8RAgKkEgoAAACQQE0UBWoPAAAATRMUgiEAAACfEgICpBMKAAAAkEBNFAUhIgAAAJ8TAgJNFBPKIwAAAMAVJADAFiUAwBcmAP8YBQAAAAAAxhkAADAZGMEnAAAAjBkAADAZGHwoAAAAjBkAADAZGMYpAAAAxhkAADAZGAEqAAAATRkL7ysAAACfGQECMBkYYSwAAABNGQvvKwAAAJ8ZAQIwGRjLLQAAAMAZLgASAAkAEgAYABIAEAASAA8AEgAOABIADAASAAQAMBkYEy8AAADAGTAAEgAOADAZGOsxAAAAwBkyABIAGAASAAkAEgASABIAAgASABYAEgAKABIAEwASABQAEgARABIAAwASAAQAEgABADAZGNgzAAAAwBk0ABIAFQASABYAMBkYwzUAAADAGTYAEgAYADAZGK83AAAAwBk4ABIAGAAwGRj3OQAAAMAZOgASABgAMBkYKjsAAADAGTwAEgAYADAZGIQ9AAAAwBk+ABIAGAAwGRi+PwAAAMAZQAASABIAEgAPABIAEAASAAgAEgAGABIADQASAAwAEgAYABIABwAwGRiVQQAAAIIYAgBCA8IBBAAAAEADwwEDxAEDxQEDmwEDxgEDxwEDyAEDyQEEAACQQAPKAQPLAQPMAQPNAQPOAQPPAQPQAQPRAQPSAQPTAQPUAQPVAQPWAQPXAQPYAQPZAQQAAKBBA4IBA9oBA9sBA9wBA5UBA90BA94BA98BBgAGAQYCAyoDawOmAQM3AwgDnwEDpwEGCQMwBgoDNgYkAx8GJQNNBiYDJgYnAxYGKAMpBikDqQEGKgMXBi8DJw0AAQIJCiQlJicoKSovAQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAIAAAAOAAAACQAAAAUAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSAAAAAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALQEAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAABQAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC0AAAAAMJD3XnMaP+/hojM05wLIWSnWNROx2E4GmJw00+Pl1anfG7Fdj9AkAYs=

-- Decompiled by Krnl

game:GetService("GuiService")
local v_u_1 = game:GetService("Players")
local v_u_2 = v_u_1.LocalPlayer
local v_u_3 = game:GetService("RunService")
local v_u_4 = game:GetService("UserInputService")
local v5 = game:GetService("ReplicatedStorage")
local v_u_6 = require(v5.App.StreamingHelperUtils)
local v_u_7 = require(v5.Game.Notification)
local v_u_8 = require(v5.Home.HomeConsts)
local v_u_9 = require(v5.Std.Maid)
local v_u_10 = require(v5.Std.Spring)
local v11 = require(v5.Std.Signal)
local v_u_12 = require(v5.Home.HomeItem.HomeItemBinder)
local v_u_13 = require(v5.Std.Binder.BinderUtils)
local v_u_14 = require(script.Parent.ItemPlacerUtils)
local v_u_15 = require(script.Parent.Parent.HomeSystem)
local v_u_16 = require(v5.Home.HomeItem.HomeItemSystem)
local v_u_17 = require(v5.Home.UI.PlacerApp)
local v_u_18 = require(v5.Home.homeStore)
local v_u_19 = require(v5.Roact)
local v_u_20 = v_u_19.createElement
local function v_u_28(p21, p22)
	local v23 = p21[1]
	local v24 = (-1 / 0)
	for _, v25 in p21 do
		local v26 = v25:Dot(p22)
		local v27 = math.abs(v26)
		if v24 < v27 then
			v23 = v25 * (v26 > 0 and 1 or -1)
			v24 = v27
		end
	end
	return v23
end
local function v_u_33(p29, p30)
	local v31 = p29:Cross(p30)
	local v32 = p29:Dot(p30)
	if v32 < -0.999 then
		return CFrame.Angles(3.141592653589793, 0, 0)
	else
		return CFrame.new(0, 0, 0, v31.x, v31.y, v31.z, v32 + 1)
	end
end
local v_u_138 = {
	["_maid"] = nil,
	["_lastDragStart"] = 0,
	["_lastDragEnd"] = 0,
	["_currentHomeItem"] = nil,
	["onDragStarted"] = v11.new(),
	["onDragEnded"] = v11.new(),
	["init"] = function()
		-- upvalues: (copy) v_u_9, (copy) v_u_138, (copy) v_u_16, (copy) v_u_15, (copy) v_u_14, (copy) v_u_12, (copy) v_u_4
		local v_u_34 = v_u_9.new()
		v_u_138._maid = v_u_34
		local v_u_35 = {}
		v_u_16.onCustomizeStarted:Connect(function()
			-- upvalues: (ref) v_u_138, (ref) v_u_15, (ref) v_u_14, (copy) v_u_35, (ref) v_u_12, (copy) v_u_34, (ref) v_u_4
			local function v42(p36, p37)
				-- upvalues: (ref) v_u_138, (ref) v_u_15, (ref) v_u_14, (ref) v_u_35, (ref) v_u_12
				local v38
				if p36.UserInputType == Enum.UserInputType.Gamepad1 then
					v38 = p36.KeyCode == Enum.KeyCode.ButtonA
				else
					v38 = false
				end
				if not p37 or v38 then
					if p36.UserInputType == Enum.UserInputType.MouseButton1 or (p36.UserInputType == Enum.UserInputType.Touch or v38) then
						if v_u_138.isDragging() then
							return
						end
						if v_u_138.getTimeSinceLastDragEnd() < 0.1 then
							return
						end
						if not v_u_15.queryCurrentStandingHome() then
							return
						end
						local v39 = v_u_14.raycastMouse(v_u_35, true)
						if v39 then
							local v40 = v39.Instance
							for _, v41 in ipairs(v_u_12:GetAll()) do
								if v40:IsDescendantOf(v41:GetObj()) then
									v_u_138.startDrag(v41)
									return
								end
							end
						end
					end
				end
			end
			v_u_34._listenForCustomizeTouch = v_u_4.TouchTap:Connect(v42)
			v_u_34._listenForCustomizeClick = v_u_4.InputBegan:Connect(v42)
		end)
		v_u_16.onCustomizeEnded:Connect(function()
			-- upvalues: (copy) v_u_34, (ref) v_u_138
			v_u_34._listenForCustomizeClick = nil
			v_u_34._listenForCustomizeTouch = nil
			if v_u_138.isDragging() then
				v_u_138.stopDrag()
			end
		end)
		v_u_15.onExited:Connect(function()
			-- upvalues: (copy) v_u_34, (ref) v_u_138
			v_u_34._listenForCustomizeClick = nil
			v_u_34._listenForCustomizeTouch = nil
			if v_u_138.isDragging() then
				v_u_138.stopDrag()
			end
		end)
		v_u_16.onAttemptPlaceItem:Connect(function(p43)
			-- upvalues: (ref) v_u_138
			v_u_138.createAndDrag(p43.name)
		end)
		v_u_16.onAttemptDeleteItem:Connect(function()
			-- upvalues: (ref) v_u_138
			v_u_138.attemptDeleteCurrentHomeItem()
		end)
	end,
	["getTargetPosition"] = function(p44)
		-- upvalues: (copy) v_u_14
		local v45 = v_u_14.raycastMouse(p44)
		if v45 then
			local v46 = v45.Instance
			local v47 = v46.CFrame:PointToObjectSpace(v45.Position)
			local v48 = v47.x / 0.1 + 0.5
			local v49 = math.floor(v48) * 0.1
			local v50 = v47.y
			local v51 = v47.z / 0.1 + 0.5
			local v52 = math.floor(v51) * 0.1
			local v53 = Vector3.new(v49, v50, v52)
			return v46.CFrame:PointToWorldSpace(v53), v45.Normal, v46.CFrame
		end
	end,
	["startDrag"] = function(p_u_54)
		-- upvalues: (copy) v_u_138, (copy) v_u_9, (copy) v_u_18, (copy) v_u_2, (copy) v_u_33, (copy) v_u_10, (copy) v_u_19, (copy) v_u_20, (copy) v_u_17, (copy) v_u_3, (copy) v_u_4, (copy) v_u_1
		v_u_138._lastDragStart = os.clock()
		local v55 = p_u_54:GetObj().PrimaryPart
		local v_u_56 = p_u_54:UntranslateCf(v55.CFrame)
		local v_u_57 = v_u_9.new()
		v_u_138._maid.placeMaid = v_u_57
		v_u_138._currentHomeItem = p_u_54
		v_u_57:GiveTask(function()
			-- upvalues: (ref) v_u_138
			v_u_138._currentHomeItem = nil
		end)
		p_u_54:SetBeingDragged(true)
		v_u_57:GiveTask(function()
			-- upvalues: (copy) p_u_54
			p_u_54:SetBeingDragged(false)
		end)
		v_u_18:dispatch({
			["type"] = "setVisible",
			["value"] = false
		})
		v_u_57:GiveTask(function()
			-- upvalues: (ref) v_u_18
			v_u_18:dispatch({
				["type"] = "setVisible",
				["value"] = true
			})
		end)
		local v_u_58 = false
		v_u_57:GiveTask(function()
			-- upvalues: (ref) v_u_58, (copy) p_u_54, (copy) v_u_56
			if not v_u_58 then
				if p_u_54._obj then
					p_u_54._obj:SetPrimaryPartCFrame(p_u_54:TranslateCf(v_u_56))
				end
				if not p_u_54:IsPlaced() then
					p_u_54:AttemptDelete()
				end
			end
		end)
		p_u_54:CacheSurfaces()
		v_u_57:GiveTask(function()
			-- upvalues: (copy) p_u_54
			p_u_54:ClearCacheSurfaces()
		end)
		local v_u_59 = v_u_58
		local v_u_60 = {}
		for _, v61 in ipairs(p_u_54:GetObj():GetDescendants()) do
			if v61:IsA("BasePart") and v61.CanCollide then
				table.insert(v_u_60, v61)
				v61.CanCollide = false
			end
		end
		v_u_57:GiveTask(function()
			-- upvalues: (copy) v_u_60
			for _, v62 in ipairs(v_u_60) do
				v62.CanCollide = true
			end
		end)
		local v_u_63 = v_u_2.Character:FindFirstChild("Humanoid")
		v_u_57:GiveTask(v_u_63.Changed:connect(function()
			-- upvalues: (copy) v_u_63
			v_u_63.Jump = false
		end))
		local v_u_64 = Instance.new("Part")
		v_u_64.Color = Color3.new(1, 0, 0)
		v_u_64.Anchored = true
		v_u_64.CanCollide = false
		v_u_64.TopSurface = 0
		v_u_64.BottomSurface = 0
		v_u_64.Size = v55.Size + Vector3.new(0.1, 0.1, 0.1)
		v_u_64.CFrame = v55.CFrame
		v_u_64.Transparency = 1
		v_u_64.Parent = p_u_54:GetObj()
		v_u_57:GiveTask(v_u_64)
		local v_u_65 = { p_u_54:GetObj(), v_u_2.Character }
		local v_u_66 = v_u_56 - v_u_56.p
		local _, v67, v68 = v_u_138.getTargetPosition(v_u_65)
		local v_u_69 = v_u_66.UpVector
		if v67:Dot(v_u_69) < 0.99 then
			v_u_66 = v_u_33(v_u_69, v67) * v_u_66
			v_u_69 = v67
		end
		local v70 = v_u_138._alignMat(v67, v68, v_u_66)
		local _, v_u_71, _ = (v70:Inverse() * v_u_56):ToOrientation()
		local v72 = v_u_56.p
		local v_u_73 = v_u_10.new(v72, Vector3.new(), 0.8, 50)
		local v_u_74 = v_u_10.new(v72, Vector3.new(), 0.7, 30)
		local v_u_75 = v_u_10.new(v70.RightVector, Vector3.new(), 0.8, 50)
		local v_u_76 = v_u_10.new(v70.UpVector, Vector3.new(), 0.8, 50)
		local v_u_77 = v_u_10.new(v_u_71, 0, 0.8, 30)
		local v_u_78 = 0
		local function v_u_87(p79, p80, p81)
			-- upvalues: (ref) v_u_78, (ref) v_u_71, (copy) v_u_77
			local v82 = os.clock()
			local v83 = v82 - p81
			local v84
			if v83 > 0.1 then
				local v85 = v83 / 0.1 + 1
				v84 = math.min(12, v85)
			else
				v84 = 1
			end
			if v82 - v_u_78 >= 0.1 then
				v_u_78 = v82
				if p79 then
					v_u_71 = v_u_71 + 0.08726646259971647 * v84
				elseif p80 then
					v_u_71 = v_u_71 - 0.08726646259971647 * v84
				end
				local v86 = v_u_71 / 0.08726646259971647 + 0.5
				v_u_71 = math.floor(v86) * 0.08726646259971647
				v_u_77:SetTarget(v_u_71)
			end
		end
		local function v_u_92()
			-- upvalues: (ref) v_u_138, (copy) p_u_54, (copy) v_u_56, (copy) v_u_65, (ref) v_u_66, (ref) v_u_71, (ref) v_u_59
			v_u_138._maid.listenForFeedback = p_u_54._placeRemote.OnClientEvent:Connect(function(p88)
				-- upvalues: (ref) v_u_138, (ref) p_u_54, (ref) v_u_56
				v_u_138._maid.listenForFeedback = nil
				if not p88 and p_u_54._obj then
					p_u_54._obj:SetPrimaryPartCFrame(p_u_54:TranslateCf(v_u_56))
				end
			end)
			local v89, v90, v91 = v_u_138.getTargetPosition(v_u_65)
			p_u_54:SetServerCFrame((p_u_54:TranslateCf(v_u_138._alignMat(v90, v91, v_u_66) * CFrame.Angles(0, v_u_71, 0) + v89)))
			v_u_59 = true
			v_u_138.stopDrag()
		end
		local v93 = v_u_19.mount
		local v94 = v_u_20
		local v95 = {
			["ZIndexBehavior"] = Enum.ZIndexBehavior.Sibling,
			["ResetOnSpawn"] = false,
			["IgnoreGuiInset"] = true,
			["DisplayOrder"] = 1
		}
		local v96 = {}
		local v97 = v_u_20
		local v98 = {
			["BackgroundTransparency"] = 1,
			["Size"] = UDim2.fromScale(0.5, 0.08),
			["Position"] = UDim2.fromScale(0.5, 0.85),
			["AnchorPoint"] = Vector2.new(0.5, 1)
		}
		local v101 = {
			["UIAspectRatioConstraint"] = v_u_20("UIAspectRatioConstraint", {
				["AspectRatio"] = 7
			}),
			["PlacerApp"] = v_u_20(v_u_17, {
				["aspectRatio"] = 7,
				["verticalPaddingRatio"] = 18.285714285714285,
				["onClickDelete"] = function()
					-- upvalues: (ref) v_u_138
					v_u_138.attemptDeleteCurrentHomeItem()
				end,
				["onClickPlace"] = function()
					-- upvalues: (copy) v_u_92
					v_u_92()
				end,
				["onDownRight"] = function()
					-- upvalues: (copy) v_u_57, (ref) v_u_3, (copy) v_u_87
					local v_u_99 = os.clock()
					v_u_57.rotateHeartbeat = v_u_3.Heartbeat:Connect(function()
						-- upvalues: (ref) v_u_87, (copy) v_u_99
						v_u_87(false, true, v_u_99)
					end)
				end,
				["onUpRight"] = function()
					-- upvalues: (copy) v_u_57
					v_u_57.rotateHeartbeat = nil
				end,
				["onDownLeft"] = function()
					-- upvalues: (copy) v_u_57, (ref) v_u_3, (copy) v_u_87
					local v_u_100 = os.clock()
					v_u_57.rotateHeartbeat = v_u_3.Heartbeat:Connect(function()
						-- upvalues: (ref) v_u_87, (copy) v_u_100
						v_u_87(true, false, v_u_100)
					end)
				end,
				["onUpLeft"] = function()
					-- upvalues: (copy) v_u_57
					v_u_57.rotateHeartbeat = nil
				end,
				["showPlace"] = v_u_4.TouchEnabled
			})
		}
		v96.PlacerContainer = v97("Frame", v98, v101)
		local v_u_102 = v93(v94("ScreenGui", v95, v96), v_u_1.LocalPlayer.PlayerGui, "ItemPlacerGui")
		v_u_57:GiveTask(function()
			-- upvalues: (ref) v_u_19, (copy) v_u_102
			v_u_19.unmount(v_u_102)
		end)
		v_u_57:GiveTask(v_u_4.InputEnded:Connect(function(p103, p104)
			-- upvalues: (copy) v_u_57
			if not p104 then
				if p103.UserInputType == Enum.UserInputType.MouseButton1 then
					v_u_57.rotateHeartbeat = nil
				end
			end
		end))
		v_u_57:GiveTask(v_u_4.InputBegan:Connect(function(p_u_105, p106)
			-- upvalues: (copy) v_u_57, (ref) v_u_3, (copy) v_u_87
			if not p106 then
				if p_u_105.UserInputType == Enum.UserInputType.Keyboard or p_u_105.UserInputType == Enum.UserInputType.Gamepad1 then
					local v_u_107 = p_u_105.KeyCode == Enum.KeyCode.Q and true or p_u_105.KeyCode == Enum.KeyCode.ButtonL2
					local v_u_108 = p_u_105.KeyCode == Enum.KeyCode.E and true or p_u_105.KeyCode == Enum.KeyCode.ButtonR2
					if v_u_108 or v_u_107 then
						local v_u_109 = os.clock()
						v_u_57.waitForEnd = p_u_105:GetPropertyChangedSignal("UserInputState"):Connect(function()
							-- upvalues: (copy) p_u_105, (ref) v_u_57
							if p_u_105.UserInputState == Enum.UserInputState.End then
								v_u_57.waitForEnd = nil
								v_u_57.rotateHeartbeat = nil
							end
						end)
						v_u_57.rotateHeartbeat = v_u_3.Heartbeat:Connect(function()
							-- upvalues: (ref) v_u_87, (copy) v_u_107, (copy) v_u_108, (copy) v_u_109
							v_u_87(v_u_107, v_u_108, v_u_109)
						end)
					end
				end
			end
		end))
		v_u_57:GiveTask(v_u_3.Heartbeat:Connect(function()
			-- upvalues: (ref) v_u_138, (copy) v_u_65, (copy) v_u_73, (copy) v_u_74, (copy) v_u_77, (ref) v_u_69, (ref) v_u_66, (ref) v_u_33, (copy) v_u_75, (copy) v_u_76, (copy) p_u_54, (ref) v_u_71, (copy) v_u_64
			local v110, v111, v112 = v_u_138.getTargetPosition(v_u_65)
			if v110 then
				local v113, _ = v_u_73:SetTarget(v110)
				local _, v114 = v_u_74:SetTarget(v110)
				local v115 = v_u_77:Update()
				if v111:Dot(v_u_69) < 0.99 then
					v_u_66 = v_u_33(v_u_69, v111) * v_u_66
					v_u_69 = v111
				end
				local v116 = v_u_138._alignMat(v111, v112, v_u_66)
				local v117 = CFrame.fromMatrix(Vector3.new(0, 0, 0), v_u_75:SetTarget(v116.RightVector).Unit, v_u_76:SetTarget(v116.UpVector).Unit)
				local v118 = p_u_54:TranslateCf(v116 * CFrame.Angles(0, v_u_71, 0) + v110)
				local v119 = p_u_54:IsValidUpDot((v118.UpVector:Dot(Vector3.new(0, 1, 0))))
				v_u_64.Transparency = p_u_54:IsWithinBoundsCached(v118) and v119 and 1 or 0.5
				p_u_54:SetCFrame((p_u_54:TranslateCf(v117 * CFrame.Angles(-v114.z * 0.0015, 0, v114.x * 0.0015) * CFrame.Angles(0, v115, 0) + v113)))
			end
		end))
		v_u_57:GiveTask(v_u_4.InputBegan:Connect(function(p120, p121)
			-- upvalues: (copy) v_u_92
			local v122
			if p120.UserInputType == Enum.UserInputType.Gamepad1 then
				v122 = p120.KeyCode == Enum.KeyCode.ButtonA
			else
				v122 = false
			end
			if not p121 or v122 then
				if p120.UserInputType == Enum.UserInputType.MouseButton1 or v122 then
					v_u_92()
				end
			end
		end))
		v_u_138.onDragStarted:Fire()
	end,
	["_alignMat"] = function(p123, p124, p125)
		-- upvalues: (copy) v_u_28, (copy) v_u_33
		local v126 = { p124.LookVector, p124.RightVector, p124.UpVector }
		local v127 = v_u_28(v126, p123)
		if table.find(v126, v127) then
			table.remove(v126, table.find(v126, v127))
		end
		if table.find(v126, -v127) then
			table.remove(v126, table.find(v126, -v127))
		end
		return p125 * v_u_33(Vector3.new(1, 0, 0), p125:VectorToObjectSpace((v_u_28(v126, p125:VectorToWorldSpace(Vector3.new(1, 0, 0))))))
	end,
	["stopDrag"] = function()
		-- upvalues: (copy) v_u_138
		v_u_138._maid.placeMaid = nil
		v_u_138._lastDragEnd = os.clock()
		v_u_138.onDragEnded:Fire()
	end,
	["isDragging"] = function()
		-- upvalues: (copy) v_u_138
		local v128 = v_u_138._maid
		if v128 then
			v128 = v_u_138._maid.placeMaid ~= nil
		end
		return v128
	end,
	["attemptDeleteCurrentHomeItem"] = function()
		-- upvalues: (copy) v_u_138
		local v129 = v_u_138.isDragging
		assert(v129())
		local v130 = v_u_138._currentHomeItem
		local v131 = v130 ~= nil
		assert(v131)
		v_u_138.stopDrag()
		v130:AttemptDelete()
	end,
	["getTimeSinceLastDragStart"] = function()
		-- upvalues: (copy) v_u_138
		return os.clock() - v_u_138._lastDragStart
	end,
	["getTimeSinceLastDragEnd"] = function()
		-- upvalues: (copy) v_u_138
		return os.clock() - v_u_138._lastDragEnd
	end,
	["createAndDrag"] = function(p132)
		-- upvalues: (copy) v_u_18, (copy) v_u_15, (copy) v_u_16, (copy) v_u_8, (copy) v_u_6, (copy) v_u_13, (copy) v_u_12, (copy) v_u_138, (copy) v_u_7
		v_u_18:dispatch({
			["type"] = "setVisible",
			["value"] = false
		})
		local v133 = v_u_15.queryCurrentStandingHome()
		local v134 = v133 ~= nil
		assert(v134)
		v_u_16._maid._listenNewItem = v133._homeItemNewRemote.OnClientEvent:Connect(function(p135)
			-- upvalues: (ref) v_u_16, (ref) v_u_8, (ref) v_u_6, (ref) v_u_13, (ref) v_u_12, (ref) v_u_138, (ref) v_u_18, (ref) v_u_7
			v_u_16._maid._listenNewItem = nil
			if p135.id == v_u_8.ENUM_HOME_ITEM_NEW_RESULT.SUCCESS then
				v_u_6.yieldForObjValuePopulated(p135.modelPtr)
				local v136 = p135.modelPtr.Value
				v_u_13.promiseBoundClass(v_u_12, v136):andThen(function(p137)
					-- upvalues: (ref) v_u_138, (ref) v_u_18
					v_u_138.startDrag(p137)
					v_u_138._maid.placeMaid:GiveTask(function()
						-- upvalues: (ref) v_u_18
						v_u_18:dispatch({
							["type"] = "setVisible",
							["value"] = true
						})
					end)
				end):catch(warn)
				return
			elseif p135.id == v_u_8.ENUM_HOME_ITEM_NEW_RESULT.TOO_MANY then
				v_u_7.new({
					["Text"] = "Too many items placed... try deleting some."
				})
				v_u_18:dispatch({
					["type"] = "setVisible",
					["value"] = true
				})
				return
			elseif p135.id == v_u_8.ENUM_HOME_ITEM_NEW_RESULT.ALL_OWNED_PLACED then
				v_u_7.new({
					["Text"] = "You placed all of these that you own..."
				})
				v_u_18:dispatch({
					["type"] = "setVisible",
					["value"] = true
				})
				return
			elseif p135.id == v_u_8.ENUM_HOME_ITEM_NEW_RESULT.MAX_PLACED then
				v_u_7.new({
					["Text"] = "You reached the placement limit for this item..."
				})
				v_u_18:dispatch({
					["type"] = "setVisible",
					["value"] = true
				})
			else
				error(("Unhandled result id: %d"):format(p135.id))
			end
		end)
		v133:AttemptCreateHomeItem(p132)
	end
}
return v_u_138
