-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMNGk1BWF9ESVNUX1RPX0xPQURfQVRUUl9OQU1FDEdldEF0dHJpYnV0ZRBNQVhfRElTVF9UT19MT0FEEGdldE1heERpc3RUb0xvYWQMU2V0QXR0cmlidXRlEHNldE1heERpc3RUb0xvYWQEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUER2FtZQxEZXN0cnVjdGlibGUSRGVzdHJ1Y3RpYmxlQ29uc3RzAAMEAAIAAAAM+wAAAPsDAQBNAgPyAAAAALwAABIBAAAAnwADAisAAwD7AQEATQABYAIAAACCAAIAAwMBAwIDAwAGBAEYAAAAAAAAAAABAAAABwAAAAAFAQIAAAAJ+wEAAPsEAQBNAwTyAAAAAFIEAAC8AQEuAQAAAJ8BBAGCAAEAAgMBAwUACgYBGAAAAAAAAAAAAQsAAAAABQAAAQIAHaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0EAL0GAAAATQMEqwcAAABNAgNwCAAAAJ8BAgL/AgIAAAAAAMADCQASAAAAEgABADADArAKAAAAwAMLABIAAAASAAEAMAMCTAwAAACCAgIADQMHBAAAAEADCAMJAwoEAABAQAMLAwwDDQYAAwQGAQMGAgABAQABGAABAAAAAAABAAAAAAAAAAABAAIAAAAABAAAAAADAQAAAAACe4hB7Jj9Oi1JTCt4qon0IKI5902jwOamGRyqML2IPEcd3Qtv2sMxDw==

-- Decompiled by Krnl

local v_u_1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v_u_1.Game.Destructible.DestructibleConsts)
return {
	["getMaxDistToLoad"] = function()
		-- upvalues: (copy) v_u_1, (copy) v_u_2
		return v_u_1:GetAttribute(v_u_2.MAX_DIST_TO_LOAD_ATTR_NAME) or v_u_2.MAX_DIST_TO_LOAD
	end,
	["setMaxDistToLoad"] = function(p3)
		-- upvalues: (copy) v_u_1, (copy) v_u_2
		v_u_1:SetAttribute(v_u_2.MAX_DIST_TO_LOAD_ATTR_NAME, p3)
	end
}
