-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMsCUdldEFjdGl2ZQRfcnVuB3J1bk1haWQKRG9DbGVhbmluZwZ1cGRhdGUDbmV3DHNldG1ldGF0YWJsZQhtYW5pZmVzdARtYWlkCEdpdmVUYXNrCWFjdGl2ZU9iagdDaGFuZ2VkB0Nvbm5lY3QKcG9vbE9ialB0cgVWYWx1ZQpHZXRQb29sT2JqCVNldEFjdGl2ZQhCYXNlUGFydANJc0EQX21hcFRyYW5zcGFyZW5jeQxUcmFuc3BhcmVuY3kHaGlkZU9iaghBbmNob3JlZAZDRnJhbWUDb2JqEm9ic2VydmVEZXNjZW5kYW50cwVNb2RlbA9vYnNlcnZlUHJvcGVydHkLUHJpbWFyeVBhcnQEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUDU3RkCkJhc2VPYmplY3QETWFpZA9SeEluc3RhbmNlVXRpbHMOTWFuaWZlc3RCaW5kZXIKTmV0T2JqUG9vbBROZXRPYmpQb29sSXRlbUNvbnN0cwdfX2luZGV4Dk5ldE9ialBvb2xJdGVtEVBPT0xfT0JKX1BUUl9OQU1FD0FDVElWRV9PQkpfTkFNRQAMAwABAAAAEfsAAAC8AABFAAAAAJ8AAgIOAAUA+wEAALwBAZ0BAAAAnwECAYIAAQD7AgAATQECVAIAAAC8AQFRAwAAAJ8BAgGCAAEABAMBAwIDAwMEABgFARgAAAAAAQEAAAAAAgAAAAAAAhkAAAAACQIDAAAAOPsDAABNAgPvAAAAAFIDAACfAgIC+wUBAJ49AgQFAAAAUgQCAKQDAgAAABBAnwMDATABAkgDAAAA+wQCAE0DBO8AAAAAnwMBAjADAlQEAAAATQMCFgUAAABNBQJUBAAAALwDA/0GAAAAnwMDAdkDAAASAAIAvAQCRQcAAACfBAICDgQEALwFAp0IAAAAnwUCAWUABQBNBQJUBAAAALwFBVEJAAAAnwUCAU0EAhYFAAAATQcBNgoAAABNBgeFCwAAAFIIAwC8BgbHDAAAAJ8GAwC8BAT9BgAAAJ8EAAGCAgIADQMGAwcEAAAQQAMIAwMDCQMKAwEDAgMEAwsDDAMNAQAPBgEYAAAAAAABAAAAAAAAAgACAAAAAAABAAAAAAAAAgABAAABAQAAAAIAAAAABAAAAAAAAAAAAAAAAAIQAAAAAAQBAAAAAAdNAwBIAAAAAE0CAxsBAAAATQEC7AIAAACCAQIAAwMIAw4DDwAlEAEYAAAAAAAAACYAAAAABAEAAAAAB00DAEgAAAAATQIDNgEAAABNAQLsAgAAAIIBAgADAwgDCwMPACgBARgAAAAAAAAAKQAAAAAEAgAAAAAHTQMASAAAAABNAgM2AQAAADABAuwCAAAAggABAAMDCAMLAw8AKxEBGAAAAAAAAAEsAAAAAAQBAQAAAA9vAwAAvAEA/gEAAACfAQMCDgEJAPsCAABNAQJLAgAAAE0CANkDAAAAagIBAIwBAQAwAQDZAwAAAIIAAQAEAxIDEwMUAxUAMRYBGAAAAAAAAQAAAAAAAQAAAjIAAAAAAgABAAAABfsAAACpAQAAMAEARQAAAACCAAEAAQMXAD4AARgAAAAAAT8AAAAAAgABAAAABfsAAACpAQAAMAEARQAAAACCAAEAAQMXAEYAARgAAAAAAUcAAAAABgIAAAAAEg4AEACpAgEAMAIARQAAAADZBAAAEgAAALwCAf0BAAAAnwIDAaQCBAAADCCAjAMAAIwEOP+MBQAAnwIEAjACAIUCAAAAggABAAUDFwMKAxgDBgQADCCAAQdDAAEYAAEAAAEAAAAAAwAAAAAAAAACRAAAAAAFAAEAAAAP+wMAAE0AA0sAAAAAxgEAAMYCAABkAAIAMAQD2QEAAABuAP3/AgAAAPsAAADGAQAAMAEASwAAAACCAAEAAgMUAxUATgABGAAAAAAAAAEA/wADAAAAAU8AAAAACQEBAAAAVk0BAFQAAAAAvAEBUQEAAACfAQIB/wEAAAAAAAAwAQBLAgAAANkBAAASAAAATQIAEwMAAABvBQQAvAMC/gUAAACfAwMCDgMIAE0DAEsCAAAATQQC2QYAAABqBAMCjAMBADADAtkGAAAATQMAVAAAAAD7BgAATQUGSQcAAABSBgIAUgcBAJ8FAwC8AwP9CAAAAJ8DAAFvBQQAvAMC/gUAAACfAwMCDgMTAKkDAQAwAwJFCQAAAE0DAFQAAAAA2QUBABIAAgC8AwP9CAAAAJ8DAwGkAwwAACyggIwEAACMBTj/jAYAAJ8DBAIwAwKFCgAAAGUAEQBvBQ0AvAMC/gUAAACfAwMCDgMMAE0DAFQAAAAA+wYAAE0FBkgOAAAAUgYCAG8HDwDACBAAnwUEALwDA/0IAAAAnwMAAU0DAFQAAAAA2QUDABIAAAC8AwP9CAAAAJ8DAwGCAAEAEQMDAwQDFAMZAxIDEwMVAxoDCgMXAxgDBgQALKCAAxsDHAMdBggEBQYICS4CARgAAAAAAAEAAAABAAcA+gAAAAABAAAAAAEAAAYAAAAAAAAAAAAAAgAAAAABAAABAAAAAAAAAwAAAAAAAAAAAQAAAAABAAAAAAAAAAAAAAALAAAAAAAABi8AAAAACwAAAQIAVaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DAKEGAAAATQIDSwcAAACfAQICpAIFAAAAQEBNBAChBgAAAE0DBHYIAAAAnwICAqQDBQAAAEBATQUAoQYAAABNBAVSCQAAAJ8DAgKkBAUAAABAQE0FAIkKAAAAnwQCAqQFBQAAAEBATQcAjAsAAABNBgdJDAAAAJ8FAgL/BgQAAAAAADAGBm4NAAAAnj0GBQEAAABSCAYAUgkBAKQHDwAAAOBAnwcDAcAHEAASAAEAEgAGABIAAgAwBwbvEQAAAMAHEgAwBwZBEwAAAMAHFAAwBwZFFQAAAMAHFgAwBwZZFwAAAMAHGAASAAMAMAcGnRkAAABNBwTvEQAAAG8IGgDiCR0ATQoF2x4AAAAwCgkbGwAAAE0KBewfAAAAMAoJNhwAAABSCgYAnwcEAIIHAAAgAx4EAAAAQAMfAyADIQQAAEBAAyIDIwMkAyUDJgMnAygDKQMHBAAA4EAGAQMGBgIDEAYDAwEGBAMRBgoDAgMqAw4DCwUCGxwDKwMsBQECAwQKAQABGAAAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAIAAAAAAAAEAAEAAQAAAAAAAAIAAAAAABYAAAMAAAMAAAMAAAAoAAAAAQAAAAEAAAAB/QABAAAAAAuMwrHC9UorYb4G21bE2+iKCZgVq0HGpmY33fvEi3Egu4IC4rmkF7r7

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.BaseObject)
local v_u_3 = require(v1.Std.Maid)
local v_u_4 = require(v1.Std.RxInstanceUtils)
local v5 = require(v1.ManifestBinder)
local v6 = require(v1.NetObjPool.NetObjPoolItemConsts)
local v_u_7 = {}
v_u_7.__index = v_u_7
setmetatable(v_u_7, v_u_2)
function v_u_7.new(p8, p9)
	-- upvalues: (copy) v_u_2, (copy) v_u_7, (copy) v_u_3
	local v_u_10 = v_u_2.new(p8)
	local v11 = v_u_7
	setmetatable(v_u_10, v11)
	v_u_10.manifest = p9
	v_u_10.runMaid = v_u_3.new()
	v_u_10.maid:GiveTask(v_u_10.runMaid)
	local function v12()
		-- upvalues: (copy) v_u_10
		if v_u_10:GetActive() then
			v_u_10:_run()
		else
			v_u_10.runMaid:DoCleaning()
		end
	end
	if v_u_10:GetActive() then
		v_u_10:_run()
	else
		v_u_10.runMaid:DoCleaning()
	end
	v_u_10.maid:GiveTask(p9.activeObj.Changed:Connect(v12))
	return v_u_10
end
function v_u_7.GetPoolObj(p13)
	return p13.manifest.poolObjPtr.Value
end
function v_u_7.GetActive(p14)
	return p14.manifest.activeObj.Value
end
function v_u_7.SetActive(p15, p16)
	p15.manifest.activeObj.Value = p16
end
function v_u_7._run(p_u_17)
	-- upvalues: (copy) v_u_4
	p_u_17.runMaid:DoCleaning()
	p_u_17._mapTransparency = {}
	local function v19(p18)
		-- upvalues: (copy) p_u_17
		if p18:IsA("BasePart") then
			p_u_17._mapTransparency[p18] = p18.Transparency
			p18.Transparency = 1
		end
	end
	local v_u_20 = p_u_17.obj
	if v_u_20:IsA("BasePart") then
		p_u_17._mapTransparency[v_u_20] = v_u_20.Transparency
		v_u_20.Transparency = 1
	end
	p_u_17.runMaid:GiveTask(v_u_4.observeDescendants(v_u_20, v19))
	if v_u_20:IsA("BasePart") then
		v_u_20.Anchored = true
		p_u_17.runMaid:GiveTask(function()
			-- upvalues: (copy) v_u_20
			v_u_20.Anchored = false
		end)
		v_u_20.CFrame = CFrame.new(0, -200, 0)
	elseif v_u_20:IsA("Model") then
		p_u_17.runMaid:GiveTask(v_u_4.observeProperty(v_u_20, "PrimaryPart", function(p_u_21, p22)
			if p_u_21 then
				p_u_21.Anchored = true
				p22:GiveTask(function()
					-- upvalues: (copy) p_u_21
					p_u_21.Anchored = false
				end)
				p_u_21.CFrame = CFrame.new(0, -200, 0)
			end
		end))
	end
	p_u_17.runMaid:GiveTask(function()
		-- upvalues: (copy) p_u_17
		for v23, v24 in p_u_17._mapTransparency do
			v23.Transparency = v24
		end
		p_u_17._mapTransparency = nil
	end)
end
return v5.new("NetObjPoolItem", {
	["poolObjPtr"] = v6.POOL_OBJ_PTR_NAME,
	["activeObj"] = v6.ACTIVE_OBJ_NAME
}, v_u_7)
