-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgOLAQlUZXh0TGFiZWwETmFtZQFABENtZHIJUGxhY2VOYW1lASQEVGV4dAtVcGRhdGVMYWJlbAhHZXRMYWJlbAVwYWlycwtHZXRDaGlsZHJlbglHdWlPYmplY3QDSXNBBFNpemUBWQZPZmZzZXQFVURpbTIDbmV3CkNhbnZhc1NpemUBWAVTY2FsZQdWZWN0b3IyEkFic29sdXRlV2luZG93U2l6ZQRtYXRoA21heA5DYW52YXNQb3NpdGlvbhJVcGRhdGVXaW5kb3dIZWlnaHQIdG9zdHJpbmcGdHlwZW9mBkNvbG9yMwVDb2xvcgRVdGlsD0VtdWxhdGVUYWJzdG9wcwNuaWwFQ2xvbmUKVGV4dENvbG9yMwhSaWNoVGV4dAZQYXJlbnQHQWRkTGluZQdWaXNpYmxlCUlzVmlzaWJsZQdUZXh0Qm94DENhcHR1cmVGb2N1cwR0YXNrBHdhaXQADFNldEVudHJ5VGV4dBZBY3RpdmF0aW9uVW5sb2Nrc01vdXNlDU1vdXNlQmVoYXZpb3IVUHJldmlvdXNNb3VzZUJlaGF2aW9yBEVudW0HRGVmYXVsdAxSZWxlYXNlRm9jdXMMQXV0b0NvbXBsZXRlBEhpZGUKU2V0VmlzaWJsZQRTaG93DkN1cnNvclBvc2l0aW9uAQkEZ3N1YgxHZXRFbnRyeVRleHQHZnJvbVJHQgVWYWxpZApfZXJyb3JUZXh0D1NldElzVmFsaWRJbnB1dBBIaWRlSW52YWxpZFN0YXRlEUNsZWFySGlzdG9yeVN0YXRlCk1lbnVJc09wZW4MUHJvY2Vzc0VudHJ5CUxvc2VGb2N1cwpEaXNwYXRjaGVyCkdldEhpc3RvcnkMSGlzdG9yeVN0YXRlCFBvc2l0aW9uC0luaXRpYWxUZXh0BWNsYW1wD1RyYXZlcnNlSGlzdG9yeQZTZWxlY3QOU2VsZWN0VmVydGljYWwOQWN0aXZhdGlvbktleXMHS2V5Q29kZQxNYXNoVG9FbmFibGUHRW5hYmxlZAR0aWNrClNldEVuYWJsZWQPSGlkZU9uTG9zdEZvY3VzBXRhYmxlBGZpbmQNVXNlcklucHV0VHlwZRBBYnNvbHV0ZVBvc2l0aW9uDEFic29sdXRlU2l6ZQREb3duAlVwBlJldHVybgEKAQ0DVGFiD0dldFNlbGVjdGVkSXRlbQNzdWICJXMFbWF0Y2gITGFzdEl0ZW0HQ29tbWFuZANBcmcFQWxpYXMHTnVtQXJncxNBcmd1bWVudERlZmluaXRpb25zCUlzUGFydGlhbAlBcmd1bWVudHMLUmF3U2VnbWVudHMGUHJlZml4BmNvbmNhdAEsASACJXEGZm9ybWF0BSVzICVzCkJlZ2luSW5wdXQNT25UZXh0Q2hhbmdlZARnYW1lCkd1aVNlcnZpY2UKR2V0U2VydmljZRBVc2VySW5wdXRTZXJ2aWNlC1RleHRTZXJ2aWNlB1BsYXllcnMLTG9jYWxQbGF5ZXIMTW91c2VCdXR0b24xDE1vdXNlQnV0dG9uMgVUb3VjaA5DbWRyRnJhbWVWYWx1ZQxXYWl0Rm9yQ2hpbGQFVmFsdWUETGluZQVFbnRyeQlGb2N1c0xvc3QHQ29ubmVjdApJbnB1dEJlZ2FuGEdldFByb3BlcnR5Q2hhbmdlZFNpZ25hbApDaGlsZEFkZGVkABUIAQIAAAAQ+wIAAE0BApoAAAAA+wcBAE0DB7oBAAAAbwQCAE0HAJ4DAAAATQUHsQQAAABvBgUAcwIDBjACAfUGAAAAggABAAcDAQMCAwMDBAMFAwYDBwAdCAEYAAAAAAAAAAAAAAAAAAAAAR4AAAAABAEBAAAABvsDAABNAgOaAAAAAE0BAvUBAAAAggECAAIDAQMHACIJARgAAAAAAAAjAAAAAAoBAQAAAEGMARQApAIBAAAAAED7AwAAvAMDaAIAAACfAwIAnwIABBcCDABvCQMAvAcG/gQAAACfBwMCDgcHAE0JBi8FAAAATQgJeAYAAABNBwhwBwAAAEMBAQduAvP/AgAAAPsCAACkAwoAACSAgPsHAABNBgfPCwAAAE0FBnkMAAAATQQFhA0AAAD7CAAATQcIzwsAAABNBgd5DAAAAE0FBnAHAAAAjAYAAFIHAQCfAwUCMAMCzwsAAAD7AgAApAMPAAAk4ICMBAAA+wkAAE0ICcUQAAAATQcIeAYAAAAmBgEHgRIGBBEAAABvBxEApAUUAABMIIGfBQMCnwMDAjADApUVAAAAggABABYDCgQAAABAAwsDDAMNAw4DDwMQAxEDEgQAJICAAxMDFAMVAxYEACTggAMXAgAAAAAAAAAAAxgDGQQATCCBAxoAJxsBGAACAAAAAAAAAAEAAAAAAQAAAAAAAP4ABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAABKAAAAAAHAwMAAAA9UgMCACsDAgD/AwAAAAAAAFICAwC7PwEDUgQBAKQDAQAAAABAnwMCAlIBAwC7LAIDUgQCAKQDAwAAACBAnwMCAvADBQAEAACA4gMGADACA6QFAAAAUgIDABwDAQANAwYABwAAgPsDAAC8AwN/CAAAAJ8DAgGCAAEATQUAngkAAABNBAWeCgAAAE0DBKMLAAAAkAQBDIwFCACfAwMC+wQBALwEBDoNAAAAnwQCAjADBPUOAAAATQUCpAUAAAArBQIATQUEcw8AAAAwBQRzDwAAAE0GAtERAAAAkAUGEDAFBNERAAAA+wUCADAFBCQSAAAAggABABMDHAQAAABAAx0EAAAgQAMeAx8FAQUCAAAAAAAAAAADGwMEAyADIQMiAyMDBwMkAQADJQMmADUnARgAAAAAAAEAAAAAAAIAAAAAAAABAAAAAwAAAQAAAAEDAAAAAAAAAAACAAAAAQABAAAAAAAAAQAAAAABAAABNgAAAAADAQEAAAAE+wIAAE0BAoAAAAAAggECAAEDKABMKQEYAAAAAE0AAAAABQIDAAAAOPsCAAAwAQKAAAAAAA4BHQD7AwEATQIDXAEAAAC8AgLUAgAAAJ8CAgGkAgUAABAwgJ8CAQFvBAYAvAIAowcAAACfAgMBTQMAnggAAABNAgMeCQAAAA4CIQD7AwIATQID6AoAAAAwAgAsCwAAAPsCAgCkAw4ADSjAwDADAugKAAAAggABAPsDAQBNAgNcAQAAALwCAq0PAAAAnwICAU0CAMoQAAAAvAICzxEAAACfAgIBTQIALAsAAAAOAggA+wICAE0DACwLAAAAMAMC6AoAAADGAgAAMAIALAsAAACCAAEAEgMoAyoDKwMsAy0EABAwgAMuAy8DBAMwAzEDMgMzAzQEDSjAwAM1AzYDNwBROAEYAAAAAgEAAAAAAAEAAAEAAAACAAAAAAEAAAAAAQAAAAAAAwAAAAAAAQAAAAACAAABAAAAAAEAAANSAAAAAAQBAAAAAAWpAwAAvAEAqQAAAACfAQMAggEAAAEDOABpNwEYAAAAAABqAAAAAAQBAAAAAAWpAwEAvAEAqQAAAACfAQMAggEAAAEDOABuOQEYAAAAAABvAAAAAAUCAgAAABv7AwAATQIDXAAAAAAwAQL1AQAAALwCADECAAAAnwICAg4CEQD7AwAATQIDXAAAAAC8AgLUAwAAAJ8CAgH7AwAATQIDXAAAAAAcBAEAlQMEBDADAkEFAAAA+wIBALwCAn8GAAAAnwICAYIAAQAHAyoDBwMpAysCAAAAAAAA8D8DOgMbAHMvARgAAAAAAAIAAAABAAAAAAABAAAAAAAAAQAAAAJ0AAAAAAUBAQAAAAv7AwAATQIDXAAAAABNAQL1AQAAAG8DAgBvBAMAvAEBzAQAAACfAQQAggEAAAUDKgMHAzsDLgM8AH49ARgAAAAAAAAAAAAAAH8AAAAACAMBAAAAGPsEAABNAwRcAAAAAA4BBwCkBAMAAAgQgIwF/wCMBv8AjAf/AJ8EBAIrBAYApAQDAAAIEICMBf8AjAZJAIwHSQCfBAQCMAQDcwQAAAAwAQDwBQAAADACAEEGAAAAggABAAcDKgMeAz4EAAgQgAMkAz8DQACEAUEBGAAAAAAAAAAAAAAAAAAAAAAAAAABAAEAAYUAAAAABgEBAAAADPsCAABNAQJcAAAAAKQCAwAACBCAjAP/AIwE/wCMBf8AnwIEAjACAXMEAAAAggABAAUDKgMeAz4EAAgQgAMkAIoBQgEYAAAAAAAAAAAAAAABiwAAAAAKAgMAAAA/+wQAAE0DBFwAAAAATQID9QEAAAC8AwAUAgAAAJ8DAgH7BAEATQMEgAMAAAAOAwsA+wQCAE0DBL0EAAAAKwMHAPsEAABNAwRcAAAAALwDA9QFAAAAnwMCAWUACwD7BAIATQMEvQQAAAAOAwcA+wQBAE0DBIADAAAADgMDALwDAM8GAAAAnwMCAQ4BDwBNAwDwBwAAAA4DDACkAwkAAACAQJ8DAQFvBQoAvAMAowsAAACfAwMBTQMAxwwAAABSBAIAnwMCAYIAAQAOAQsATQUAQQ0AAACkBhAAADzggIwH/wCMCJkAjAmZAJ8GBAC8AwBoEQAAAJ8DAAGCAAEAEgMqAwcDQwMoA0QDKwM3Az8DLQQAAIBAAy4DLwNFA0ADHgM+BAA84IADJwCPAUYBGAAAAAAAAgAAAgAAAAAAAAACAAAAAAAAAQAAAAAAAAABAAADAAAAAQAAAQAAAAEAAAAAAQEAAAAAAAAAAAAAApAAAAAACQIAAAAAPU0DAJ4AAAAATQIDCgEAAAC8AgKMAgAAAJ8CAgJNAwCeAwAAAEcDDQAAAACA4gMGABwFAgCVBAUHMAQDOwQAAAC8BACXCAAAAJ8EAgIwBAPuBQAAADADAJ4DAAAATQMAngMAAABNBwCeAwAAAE0GBzsEAAAAQwUGAYwGAQAcCAIAlQcIB0wuAAKkBAsAACiQgJ8EBAIwBAM7BAAAAE0HAJ4DAAAATQYHOwQAAAAcCAIAlQcIB5oGBgAHAAAATQYAngMAAABNBQbuBQAAACsFBQBNBwCeAwAAAE0GBzsEAAAAhwUCBrwDAKMMAAAAnwMDAYIAAQANAwQDRwNIA0kDSgNLBQIEBQIAAAAAAADwPwM9AxgDTAQAKJCAAy8ApAFNARgAAAAAAAAAAgAAAAEBAAAAAQAAAAD+AAYAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAQAAAAD+AAAEpQAAAAACAQAAAAAExgEAADABAJ4AAAAAggABAAEDSQC2AUMBGAAAAAG3AAAAAAUCAAAAABVNAgDKAAAAALwCAjEBAAAAnwICAg4CCgBNAgCeAgAAACsCBwBNAgDKAAAAAFIEAQC8AgKUAwAAAJ8CAwGCAAEAUgQBALwCALQEAAAAnwIDAYIAAQAFAzYDKQNJA04DTQC6AU8BGAAAAAAAAAAAAAEAAAAAAAACAAAAArsAAAAAFQMFAAANAAACAxGuAgIDEbUCAtkC+wQAAE0DBL0AAAAADgMDALwDAM8BAAAAnwMCAQ4CBgC8AwAxAgAAAJ8DAgIqAwIAAAAAgIIAAQBNBQCeAwAAAE0EBdoEAAAATQUBswUAAACHAwQFDgNDAE0EAJ4DAAAATQMEXwYAAAAOAyMATQQAngMAAABNAwTwBwAAACsDHgCkBAkAAACAQJ8EAQL7BQEAJgMEBYwEAQBgAxAABAAAAPsDAgCMBAUAfQQIAAMAAABNAwCeAwAAAKkFAQC8AwOeCgAAAJ8DAwCCAwAA+wQCAJUDBAveAwIAZQACAIwDAQDeAwIApAMJAAAAgECfAwEC3gMBAIIAAQBNBACeAwAAAE0DBPAHAAAADgMVALwGADECAAAAnwYCAlYFBgC8AwCpDAAAAJ8DAwGkAw4AAADQQJ8DAQFvBQ8AvAMAoxAAAACfAwMB+wQAAE0DBL0AAAAADgMDALwDAM8BAAAAnwMCAYIAAQBNBACeAwAAAE0DBPAHAAAAKgMFAAAAAAC8AwAxAgAAAJ8DAgIrAwgAvAMAMQIAAACfAwICDgMDALwDAM8BAAAAnwMCAYIAAQBNBACeAwAAAE0DBJ4RAAAADgMxAKQDFAAATCCB+wQDAE0FAcIVAAAAnwMDAg4DKgBNAwE7FgAAAPsFBABNBAV1FwAAAPsGBABNBQZxGAAAAE0GA3kZAAAATQcEeRkAAAC3BhkABwAAAE0GA3kZAAAATQgEeRkAAABNCQV5GQAAAEMHCAm3BxAABgAAAE0GA3gaAAAATQcEeBoAAAC3BgoABwAAAE0GA3gaAAAATQgEeBoAAABNCQV4GgAAAEMHCAlgB7wABgAAALwGAM8BAAAAnwYCAYIAAQBNAwGzBQAAAKQEHQAcFLDBmgMGAAQAAACMBQEAvAMAQx4AAACfAwMBggABAE0DAbMFAAAApAQgAB8UsMGaAwYABAAAAIwF//+8AwBDHgAAAJ8DAwGCAAEATQMBswUAAACkBCIAIRSwwZoDFQAEAAAApAMOAAAA0ECfAwEBvAUAlyMAAACfBQICbwckAG8IDwC8BQXMJQAAAJ8FBAJvByYAbwgPALwFBcwlAAAAnwUEALwDAKMQAAAAnwMAAYIAAQBNAwGzBQAAAKQEKAAnFLDBmgN/AAQAAABNAwDKKQAAALwDAwQqAAAAnwMCArwEAJcjAAAAnwQCAg4DawAcBwQAHAgEALwFBPArAAAAnwUEAm8HLAC8BQXnLQAAAJ8FAwIOBQUATQYAyikAAABNBQZLLgAAACsFXAATBQMBxgYAAKkHAQBNCQDKKQAAAE0ICWwvAAAADghGAE0KAMopAAAATQkKfTAAAABNBgiOMQAAAKkKAABNDADKKQAAAE0LDN8yAAAATQ0IDTMAAAAcDA0A8QsJAAwAAABNDADKKQAAAE0LDLQ0AAAAKgsCAAAAAACpCgABqQoBAFIHCgBNCgiZNQAAAIwNAQAcCwoAjAwBAKgLKACHDgoNTQ8OGzYAAACaDgMACQAAABwQDwBqBQ8QTREOSjcAAACkEjkAAOAggVITDwBvFDoAnxIDAnMQERJvEzsAvBEQVhMAAACfEQMCKxECAPAQBwAPAACAbxE8AFITEAC8ERGNPQAAAJ8RAwJSEBEAbxE+AFITBgBSFBAAvBERjT0AAACfEQQCUgYRAPEOBAAJAAAAiwva/2UAAQBSBgUApAkOAAAA0ECfCQEBUgwGAA4HAgBvDTsAZQABAG8NDwBzCwwNvAkAoxAAAACfCQMBggABAKQFDgAAANBAnwUBAbwHAJcjAAAAnwcCALwFAKMQAAAAnwUAAYIAAQC8AwAUPwAAAJ8DAgGCAAEAQANEAzcDKQMEA1ADUQNSA1MDVAQAAIBAA1UCAAAAAAAA8D8DOAMtBAAA0EADLgMvA1YDVwNYBABMIIEDWQNKA1oDWwMUAw8DMwNcBBwUsMEDTwNdBB8UsMEDXgQhFLDBAz0DXwM8A2ADYQQnFLDBAzYDYgNjA2QDZQNmA2cDaANpA2oDawNsA20DbgNvA3AEAOAggQNxA3IDcwN0A3UDQwDFAXYBGAAAAAABAAADAAAAAAABAwAAAAAAAAABAAAAAAAAAAAAAQAAAAAAAAABAAAAAQAAAAAAAAIAAAADAAIAAAAAAQAAAAABAAAAAAAAAQAAAQAAAAIAAAABAAAEAwAAAAAAAAAAAAEAAAABAAADAwAAAAAAAAAAAAAAAQABAAABAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAgAAAAAAAQAAAAABAAAAAAABAAAAAAEAAAAAAAEAAAEAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAQAAAAABAAABAAAAAAAAAAAAAAAAAAAAAQEBAQAAAAIBAAAAAgABAAAAAAAAAAAAAQAAAAAAAAAAAgABAAAAAQEAAQABAAMAAAAAAAAAAwAAAAAAAAEAAAAAAAMAAAAAAAACAPAAFQMAAAIAAAAAAAAAAAADAAABAAAAAAAAAwAAAsYAAAAABAEBAAAABvsBAABSAwAAvAEBWAAAAACfAQMAggEAAAEDRgC0AgABGAAAAAAAADUBAAAABgIBAAAAB/sCAABSBAAAUgUBALwCAgIAAAAAnwIEAIICAAABA3YAuAIAARgAAAAAAAAAOQEAAAAFAAIAAAAp+wIAAE0BAlwAAAAATQAB9QEAAABvAgIAvAAA5wMAAACfAAMCDgAQAPsBAABNAAFcAAAAAPsDAABNAgNcAAAAAE0BAvUBAAAAbwMCAG8EBAC8AQHMBQAAAJ8BBAIwAQD1AQAAAIIAAQD7AQEATQABiQYAAAAOAAoA+wEBAE0AAYkGAAAA+wMAAE0CA1wAAAAATQEC9QEAAACfAAIAggAAAIIAAQAHAyoDBwM7A2UDLgM8A3cAvAIAARgAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAQIAAAABAAAAAAAAAAAAAj0BAAAADwAAAQIAuwGjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIBAAAAAEBvBAUAvAICFgMAAACfAgMCpAMBAAAAAEBvBQYAvAMDFgMAAACfAwMCTQQDMQcAAAD/BQAAAwAAAKQGCwAKJIDApAcNAAwkgMCkCA8ADiSAwMUFBgQBAAAA4gYWAKkHAQAwBwbwEAAAAMYHAAAwBwbKEQAAAMYHAAAwBwbHEgAAAMYHAAAwBwaJEwAAAMYHAAAwBwaeFAAAAMYHAAAwBwaeFQAAAG8KFwC8CATTGAAAAJ8IAwJNBwjsGQAAAG8KGgC8CAfTGAAAAJ8IAwJvCxsAvAkH0xgAAACfCQMCxgoAADAKCCQcAAAAwAodABIACQASAAQAMAoG1x4AAADACh8AEgAJADAKBoogAAAAwAohABIABwAwCgZ/IgAAAMAKIwASAAYAEgAIABIABwAwCgZoJAAAAMAKJQASAAcAMAoGMSYAAADACicAEgAHABIACQASAAEAMAoGqSgAAADACikAMAoGzyoAAADACisAMAoGmCwAAADACi0AEgAJABIABgAwCgajLgAAAMAKLwASAAkAMAoGlzAAAADACjEAEgAJADAKBuEyAAAAwAozABIACQAwCgb6NAAAAMAKNQASAAkAEgAHABIAAAAwCgZYNgAAAMAKNwAwCga0OAAAAMAKOQAwCgYUOgAAAMAKOwAwCgZDPAAAAIwKAACMCwAA2QwQABIAAAASAQr/EgEL/xIABQASAAcAMAwGAj0AAABNDQlcPgAAAE0MDbg/AAAAwA5AABIABgC8DAzHQQAAAJ8MAwFNDAGCQgAAAMAOQwASAAYAvAwMx0EAAACfDAMBTQwJXD4AAABvDkQAvAwMlEUAAACfDAMCwA5GABIACQASAAYAvAwMx0EAAACfDAMBTQwHa0cAAABNDgZ/IgAAALwMDMdBAAAAnwwDAcEKAACCBgIASAN4BAAAAEADeQN6A3sDfAN9A34DMwNZA38ECiSAwAOAAQQMJIDAA4EBBA4kgMADPwM2A0UDdwMEA0kFBhAREhMUFQOCAQODAQOEAQOFAQOGAQMmBgADCAYBAwkGAgMbBgMDJwYEAykGBQM4BgYDNwYHAzkGCAMvBgkDPQYKA0EGCwNCBgwDRgYNA00GDgNDBg8DTwN2AyoDhwEGEQOIAQOJAQYSAwcDigEGEwOLARQAAQIDBAUGBwgJCgsMDQ4PEBESEwEAAQcAAgAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQADAAAAAAAAAAAAAwEAAAEAAAEAAAEAAAEAAAEAAAMAAAAAAAEAAAABAAAAAgAAAwAAAAAFAAAABQAAAA4AAAAAABcAAAAFAAAAAAAYAAAFAAAFAAAAAAsAAAAGAAAABgAAAAUAAHIAABUAABIAAAQAAAgBAgAAAAAAAABvAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAAAAAACgAAAAAAAAIAAQAAAI4AAAAAFKLR96uoXcZtkBWdP+ZsDbXbwWkf209/+oMjHQ9dOqZoaYxzKQr9vYY=

-- Decompiled by Krnl

local v_u_1 = game:GetService("GuiService")
local v_u_2 = game:GetService("UserInputService")
game:GetService("TextService")
local v_u_3 = game:GetService("Players").LocalPlayer
local v_u_4 = { Enum.UserInputType.MouseButton1, Enum.UserInputType.MouseButton2, Enum.UserInputType.Touch }
local v_u_5 = {
	["Valid"] = true,
	["AutoComplete"] = nil,
	["ProcessEntry"] = nil,
	["OnTextChanged"] = nil,
	["Cmdr"] = nil,
	["HistoryState"] = nil
}
local v_u_6 = v_u_3:WaitForChild("CmdrFrameValue").Value
local v_u_7 = v_u_6:WaitForChild("Line")
local v_u_8 = v_u_6:WaitForChild("Entry")
v_u_7.Parent = nil
function v_u_5.UpdateLabel(p9)
	-- upvalues: (copy) v_u_8, (copy) v_u_3
	v_u_8.TextLabel.Text = v_u_3.Name .. "@" .. p9.Cmdr.PlaceName .. "$"
end
function v_u_5.GetLabel(_)
	-- upvalues: (copy) v_u_8
	return v_u_8.TextLabel.Text
end
function v_u_5.UpdateWindowHeight(_)
	-- upvalues: (copy) v_u_6
	local v10 = 20
	for _, v11 in pairs(v_u_6:GetChildren()) do
		if v11:IsA("GuiObject") then
			v10 = v10 + v11.Size.Y.Offset
		end
	end
	v_u_6.CanvasSize = UDim2.new(v_u_6.CanvasSize.X.Scale, v_u_6.CanvasSize.X.Offset, 0, v10)
	local v12 = v_u_6
	local v13 = Vector2.new
	local v14 = v10 - v_u_6.AbsoluteWindowSize.Y
	v12.CanvasPosition = v13(0, (math.max(v14, 0)))
end
function v_u_5.AddLine(p15, p16, p17)
	-- upvalues: (copy) v_u_5, (copy) v_u_7, (copy) v_u_6
	local v18 = p17 or {}
	local v19 = tostring(p16)
	local v20 = typeof(v18) == "Color3" and {
		["Color"] = v18
	} or v18
	if #v19 == 0 then
		v_u_5:UpdateWindowHeight()
	else
		local v21 = p15.Cmdr.Util.EmulateTabstops(v19 or "nil", 8)
		local v22 = v_u_7:Clone()
		v22.Text = v21
		v22.TextColor3 = v20.Color or v22.TextColor3
		v22.RichText = v20.RichText or false
		v22.Parent = v_u_6
	end
end
function v_u_5.IsVisible(_)
	-- upvalues: (copy) v_u_6
	return v_u_6.Visible
end
function v_u_5.SetVisible(p23, p24)
	-- upvalues: (copy) v_u_6, (copy) v_u_8, (copy) v_u_2
	v_u_6.Visible = p24
	if p24 then
		v_u_8.TextBox:CaptureFocus()
		task.wait()
		p23:SetEntryText("")
		if p23.Cmdr.ActivationUnlocksMouse then
			p23.PreviousMouseBehavior = v_u_2.MouseBehavior
			v_u_2.MouseBehavior = Enum.MouseBehavior.Default
			return
		end
	else
		v_u_8.TextBox:ReleaseFocus()
		p23.AutoComplete:Hide()
		if p23.PreviousMouseBehavior then
			v_u_2.MouseBehavior = p23.PreviousMouseBehavior
			p23.PreviousMouseBehavior = nil
		end
	end
end
function v_u_5.Hide(p25)
	return p25:SetVisible(false)
end
function v_u_5.Show(p26)
	return p26:SetVisible(true)
end
function v_u_5.SetEntryText(p27, p28)
	-- upvalues: (copy) v_u_8, (copy) v_u_5
	v_u_8.TextBox.Text = p28
	if p27:IsVisible() then
		v_u_8.TextBox:CaptureFocus()
		v_u_8.TextBox.CursorPosition = #p28 + 1
		v_u_5:UpdateWindowHeight()
	end
end
function v_u_5.GetEntryText(_)
	-- upvalues: (copy) v_u_8
	return v_u_8.TextBox.Text:gsub("\t", "")
end
function v_u_5.SetIsValidInput(p29, p30, p31)
	-- upvalues: (copy) v_u_8
	v_u_8.TextBox.TextColor3 = p30 and Color3.fromRGB(255, 255, 255) or Color3.fromRGB(255, 73, 73)
	p29.Valid = p30
	p29._errorText = p31
end
function v_u_5.HideInvalidState(_)
	-- upvalues: (copy) v_u_8
	v_u_8.TextBox.TextColor3 = Color3.fromRGB(255, 255, 255)
end
function v_u_5.LoseFocus(p32, p33)
	-- upvalues: (copy) v_u_8, (copy) v_u_6, (copy) v_u_1
	local v34 = v_u_8.TextBox.Text
	p32:ClearHistoryState()
	if v_u_6.Visible and not v_u_1.MenuIsOpen then
		v_u_8.TextBox:CaptureFocus()
	elseif v_u_1.MenuIsOpen and v_u_6.Visible then
		p32:Hide()
	end
	if p33 and p32.Valid then
		wait()
		p32:SetEntryText("")
		p32.ProcessEntry(v34)
	elseif p33 then
		p32:AddLine(p32._errorText, Color3.fromRGB(255, 153, 153))
	end
end
function v_u_5.TraverseHistory(p35, p36)
	local v37 = p35.Cmdr.Dispatcher:GetHistory()
	if p35.HistoryState == nil then
		p35.HistoryState = {
			["Position"] = #v37 + 1,
			["InitialText"] = p35:GetEntryText()
		}
	end
	local v38 = p35.HistoryState
	local v39 = p35.HistoryState.Position + p36
	local v40 = #v37 + 1
	v38.Position = math.clamp(v39, 1, v40)
	p35:SetEntryText(p35.HistoryState.Position == #v37 + 1 and p35.HistoryState.InitialText or v37[p35.HistoryState.Position])
end
function v_u_5.ClearHistoryState(p41)
	p41.HistoryState = nil
end
function v_u_5.SelectVertical(p42, p43)
	if p42.AutoComplete:IsVisible() and not p42.HistoryState then
		p42.AutoComplete:Select(p43)
	else
		p42:TraverseHistory(p43)
	end
end
local v_u_44 = 0
local v_u_45 = 0
function v_u_5.BeginInput(p46, p47, p48)
	-- upvalues: (copy) v_u_1, (ref) v_u_44, (ref) v_u_45, (copy) v_u_4, (copy) v_u_6
	if v_u_1.MenuIsOpen then
		p46:Hide()
	end
	if p48 and p46:IsVisible() == false then
		return
	elseif p46.Cmdr.ActivationKeys[p47.KeyCode] then
		if p46.Cmdr.MashToEnable and not p46.Cmdr.Enabled then
			if tick() - v_u_44 < 1 then
				if v_u_45 >= 5 then
					return p46.Cmdr:SetEnabled(true)
				end
				v_u_45 = v_u_45 + 1
			else
				v_u_45 = 1
			end
			v_u_44 = tick()
		elseif p46.Cmdr.Enabled then
			p46:SetVisible(not p46:IsVisible())
			wait()
			p46:SetEntryText("")
			if v_u_1.MenuIsOpen then
				p46:Hide()
			end
		end
	elseif p46.Cmdr.Enabled == false or not p46:IsVisible() then
		if p46:IsVisible() then
			p46:Hide()
		end
	elseif p46.Cmdr.HideOnLostFocus and table.find(v_u_4, p47.UserInputType) then
		local v49 = p47.Position
		local v50 = v_u_6.AbsolutePosition
		local v51 = v_u_6.AbsoluteSize
		if v49.X < v50.X or (v49.X > v50.X + v51.X or (v49.Y < v50.Y or v49.Y > v50.Y + v51.Y)) then
			p46:Hide()
			return
		end
	else
		if p47.KeyCode == Enum.KeyCode.Down then
			p46:SelectVertical(1)
			return
		end
		if p47.KeyCode == Enum.KeyCode.Up then
			p46:SelectVertical(-1)
			return
		end
		if p47.KeyCode == Enum.KeyCode.Return then
			wait()
			p46:SetEntryText(p46:GetEntryText():gsub("\n", ""):gsub("\r", ""))
			return
		end
		if p47.KeyCode == Enum.KeyCode.Tab then
			local v52 = p46.AutoComplete:GetSelectedItem()
			local v53 = p46:GetEntryText()
			if v52 and not (v53:sub(#v53, #v53):match("%s") and p46.AutoComplete.LastItem) then
				local v54 = v52[2]
				local v55 = p46.AutoComplete.Command
				local v56, v57
				if v55 then
					local v58 = p46.AutoComplete.Arg
					v56 = v55.Alias
					if p46.AutoComplete.NumArgs == #v55.ArgumentDefinitions then
						v57 = false
					else
						v57 = p46.AutoComplete.IsPartial == false
					end
					local v59 = v55.Arguments
					for v60 = 1, #v59 do
						local v61 = v59[v60]
						local v62 = v61.RawSegments
						if v61 == v58 then
							v62[#v62] = v54
						end
						local v63 = v61.Prefix .. table.concat(v62, ",")
						if v63:find(" ") or v63 == "" then
							v63 = ("%q"):format(v63)
						end
						v56 = ("%s %s"):format(v56, v63)
						if v61 == v58 then
							break
						end
					end
				else
					v56 = v54
					v57 = true
				end
				wait()
				p46:SetEntryText(v56 .. (v57 and " " or ""))
			else
				wait()
				p46:SetEntryText(p46:GetEntryText())
			end
		end
		p46:ClearHistoryState()
	end
end
v_u_8.TextBox.FocusLost:Connect(function(p64)
	-- upvalues: (copy) v_u_5
	return v_u_5:LoseFocus(p64)
end)
v_u_2.InputBegan:Connect(function(p65, p66)
	-- upvalues: (copy) v_u_5
	return v_u_5:BeginInput(p65, p66)
end)
v_u_8.TextBox:GetPropertyChangedSignal("Text"):Connect(function()
	-- upvalues: (copy) v_u_8, (copy) v_u_5
	if v_u_8.TextBox.Text:match("\t") then
		v_u_8.TextBox.Text = v_u_8.TextBox.Text:gsub("\t", "")
	elseif v_u_5.OnTextChanged then
		return v_u_5.OnTextChanged(v_u_8.TextBox.Text)
	end
end)
v_u_6.ChildAdded:Connect(v_u_5.UpdateWindowHeight)
return v_u_5
