-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMuA25ldwRtYWlkBGluaXQFcHJvcHMHdmlzaWJsZQVGcmFtZRBCYWNrZ3JvdW5kQ29sb3IzFkJhY2tncm91bmRUcmFuc3BhcmVuY3kEU2l6ZQtBbmNob3JQb2ludAhQb3NpdGlvbgZDb2xvcjMEc2l6ZQthbmNob3JQb2ludAhwb3NpdGlvbgRUZXh0CVRleHRMYWJlbARGb250ClRleHRDb2xvcjMKVGV4dFNjYWxlZAVVRGltMglmcm9tU2NhbGUHVmVjdG9yMgRFbnVtCkZyZWRva2FPbmUEdGV4dAZTdHJva2UIVUlTdHJva2UJVGhpY2tuZXNzBUNvbG9yDFRyYW5zcGFyZW5jeQZyZW5kZXIKRG9DbGVhbmluZwt3aWxsVW5tb3VudARnYW1lEVJlcGxpY2F0ZWRTdG9yYWdlCkdldFNlcnZpY2UHcmVxdWlyZQVSb2FjdANTdGQETWFpZA1jcmVhdGVFbGVtZW50DVB1cmVDb21wb25lbnQHVG9vbHRpcAZleHRlbmQMZGVmYXVsdFByb3BzAAQDAQEAAAAH+wIAAE0BAu8AAAAAnwEBAjABABYBAAAAggABAAIDAQMCAA4DARgAAAAAAAABDwAAAAAQAQEAAABxTQIABwAAAABNAQKgAQAAACsBAQCCAAEA+wEAAG8CAgDiAwgApAQLAAAokICMBQAAjAYAAIwHAACfBAQCMAQDnwMAAACMBAEAMAQDOgQAAABNBQAHAAAAAE0EBQ8MAAAAMAQDLwUAAABNBQAHAAAAAE0EBQgNAAAAMAQD6AYAAABNBQAHAAAAAE0EBdsOAAAAMAQDOwcAAADiBBAA+wUAAG8GEQDiBxUAjAgBADAIBzoEAAAApAgYAABcYIGMCQEAjAoBAJ8IAwIwCAcvBQAAAKQIGAAAXGCBbwkZAG8KGQCfCAMCMAgHOwcAAACkCBsAACiggW8JGQBvChkAnwgDAjAIB+gGAAAApAgeAB1IwMEwCAc5EgAAAE0JAAcAAAAATQgJ1R8AAAAwCAf1DwAAAKQICwAAKJCAbwkgAG8KIABvCyAAnwgEAjAIB3MTAAAAqQgBADAIB94UAAAA4ggiAPsJAABvCiMA4gsnAIwMAQAwDAsYJAAAAKQMCwAAKJCAbw0oAG8OKABvDygAnwwEAjAMC6QlAAAAbwwpADAMC9kmAAAAnwkDAjAJCKUhAAAAnwUEAjAFBPUPAAAAnwEEAIIBAAAqAwQDBQMGAwcDCAMJAwoDCwUFAwQFBgcDDAMBBAAokIADDQMOAw8DEAUBDwMRAxIDEwMUBQgEBQcGEg8TFAMVAxYEAFxggQIAAAAAAADgPwMXBAAooIEDGAMZBB1IwMEDGgJmZmZmZmbuPwMbBQEhAxwDHQMeAx8FAyQlJgKamZmZmZnZPwKamZmZmZnJPwARIAEYAAAAAAABAgAAAQAAAAAAAAABAAABAAAAAAABAAAAAAABAAAAAAABAQAAAQAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAEAAAAAAAEAAAAAAAAAAQAAAQEAAAEAAAEAAAAAAAAAAQAA/QAA9gAA+QASAAAAAAMBAAAAAAZNAQAWAAAAALwBAVEBAAAAnwECAYIAAQACAwIDIQAuIgEYAAAAAAABLwAAAAAJAAABAgA/owAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQIAIQYAAACfAQICpAIFAAAAQEBNBAChBwAAAE0DBHYIAAAAnwICAk0DAcoJAAAATQQB+AoAAABvBgsAvAQEnAwAAACfBAMC4gUQAKQGEwAASBCBbwcUAG8IFQCfBgMCMAYFDw0AAACkBhgAAFxggW8HGQCMCAAAnwYDAjAGBQgOAAAApAYTAABIEIFvBxkAjAgAAJ8GAwIwBgXbDwAAADAFBJIaAAAAwAUbABIAAgAwBQQTHAAAAMAFHQASAAMAMAUEgB4AAADABR8AMAUENCAAAACCBAIAIQMjBAAAAEADJAMlAyYEAABAQAMnAygDKQMqAysDLAMtAw0DDgMPBQMNDg8DFQMWBABIEIECAAAAAAAA6D8CmpmZmZmZqT8DFwMBBABcYIECAAAAAAAA4D8DLgYAAwMGAQMgBgIDIgMAAQIBAAEYAAEAAAAAAAEAAAAAAQAAAAAAAAEAAgAAAAAAAgEAAAAAAAABAAAAAAAAAQAAAAAAAP0ABQAAAAMAAAAdAAADAQAAAAADZaAD6MXfdoFXZGl8tPLtyqIeeRcByhTk49XTp2XkwK92Egjnxbt9kg==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v2 = require(v1.Roact)
local v_u_3 = require(v1.Std.Maid)
local v_u_4 = v2.createElement
local v5 = v2.PureComponent:extend("Tooltip")
v5.defaultProps = {
	["size"] = UDim2.fromScale(0.75, 0.05),
	["anchorPoint"] = Vector2.new(0.5, 0),
	["position"] = UDim2.fromScale(0.5, 0)
}
function v5.init(p6)
	-- upvalues: (copy) v_u_3
	p6.maid = v_u_3.new()
end
function v5.render(p7)
	-- upvalues: (copy) v_u_4
	if p7.props.visible then
		local v8 = v_u_4
		local v9 = {
			["BackgroundColor3"] = Color3.new(0, 0, 0),
			["BackgroundTransparency"] = 1,
			["Size"] = p7.props.size,
			["AnchorPoint"] = p7.props.anchorPoint,
			["Position"] = p7.props.position
		}
		local v10 = {}
		local v11 = v_u_4
		local v12 = {
			["BackgroundTransparency"] = 1,
			["Size"] = UDim2.fromScale(1, 1),
			["Position"] = UDim2.fromScale(0.5, 0.5),
			["AnchorPoint"] = Vector2.new(0.5, 0.5),
			["Font"] = Enum.Font.FredokaOne,
			["Text"] = p7.props.text,
			["TextColor3"] = Color3.new(0.95, 0.95, 0.95),
			["TextScaled"] = true
		}
		local v13 = {
			["Stroke"] = v_u_4("UIStroke", {
				["Thickness"] = 1,
				["Color"] = Color3.new(0.4, 0.4, 0.4),
				["Transparency"] = 0.2
			})
		}
		v10.Text = v11("TextLabel", v12, v13)
		return v8("Frame", v9, v10)
	end
end
function v5.willUnmount(p14)
	p14.maid:DoCleaning()
end
return v5
