-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNeDl91cGRhdGVTZWVraW5nCmNoZWNrT3duZXIDbmV3DHNldG1ldGF0YWJsZQhtYW5pZmVzdARtYWlkEW5ldHdvcmtPd25lcklkT2JqB0NoYW5nZWQHQ29ubmVjdAhHaXZlVGFzawtnZXREaXNhYmxlZANvYmoLZ2V0SXNMaW5rZWQOX2dldE5lYXJlc3RPYmoKbmVhcmVzdE9iagtuZWFyZXN0TWFpZAxfaG9va05lYXJlc3QIR2V0T3duZXILTG9jYWxQbGF5ZXIFZXZlcnkHc2Vla2luZxBWZWhpY2xlSGFzRHJpdmVyDEdldEF0dHJpYnV0ZRJjbG9zZXN0UG9pbnRJblBhcnQIUG9zaXRpb24GQ0ZyYW1lBFNpemUCb3MFY2xvY2sEbWF0aANtaW4IU2V0VmFsdWUNcmVxTGlua1JlbW90ZRJQb2ludFRvT2JqZWN0U3BhY2UKRmlyZVNlcnZlcgZ1cGRhdGUKRG9DbGVhbmluZw5nZXRQcmltYXJ5UGFydBNfbWFrZVBhcnRWaXN1YWxCYWxsCXdvcmtzcGFjZQZQYXJlbnQUX21ha2VQYXJ0VmlzdWFsQmxvY2sFVURpbTILU2V0UG9zaXRpb24JSGVhcnRiZWF0GGdldElzTGlua2VkQ2hhbmdlZFNpZ25hbBhnZXREaXNhYmxlZENoYW5nZWRTaWduYWwISW5zdGFuY2UEUGFydApDYW5Db2xsaWRlBkNvbG9yMwVDb2xvcgRFbnVtCFBhcnRUeXBlBEJhbGwFU2hhcGUMVHJhbnNwYXJlbmN5ClRvcFN1cmZhY2UNQm90dG9tU3VyZmFjZQhBbmNob3JlZAtCb3VuZGluZ0JveA5GaW5kRmlyc3RDaGlsZAtQcmltYXJ5UGFydA9fZ2V0UHJpbWFyeVBhcnQKSGVsaVBpY2t1cAlHZXRUYWdnZWQGaXBhaXJzDklzRGVzY2VuZGFudE9mCU1hZ25pdHVkZQVWYWx1ZRFHZXRQbGF5ZXJCeVVzZXJJZA9yZXFVbmxpbmtSZW1vdGUIVW5hdHRhY2gEZ2FtZRFDb2xsZWN0aW9uU2VydmljZQpHZXRTZXJ2aWNlB1BsYXllcnMKUnVuU2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQdyZXF1aXJlA1N0ZApCYXNlT2JqZWN0Dk1hbmlmZXN0QmluZGVyCUdlb21VdGlscwhJbnRlcnZhbARNYWlkC1ZlaGljbGVMaW5rEFZlaGljbGVMaW5rVXRpbHMKTG9hZGluZ0JhcgRHYW1lB19faW5kZXgHUmVxTGluawlSZXFVbmxpbmsOTmV0d29ya093bmVySWQADwIAAQAAAAX7AAAAvAAANwAAAACfAAIBggABAAEDAQAZAgEYAAAAAAEaAAAAAAkCAgAAACP7AwAATQID7wAAAABSAwAAnwICAvsFAQCePQIEBQAAAFIEAgCkAwIAAAAQQJ8DAwEwAQJIAwAAANkDAAASAAIAvAQCNwQAAACfBAIBTQQCFgUAAABNCAJIAwAAAE0HCEEGAAAATQYHhQcAAABSCAMAvAYGxwgAAACfBgMAvAQE/QkAAACfBAABggICAAoDAwMEBAAAEEADBQMBAwYDBwMIAwkDCgEAEwMBGAAAAAAAAQAAAAAAAAIAAgABAAADAAAAAAAAAAAAAAAAAAACFAAAAAAFAAMAAAA1+wEAAE0AAd0AAAAA+wIBAE0BAhMBAAAAnwACAg4AAQCCAAEA+wEAAE0AAa0CAAAA+wIBAE0BAhMBAAAAnwACAisAIwD7AAEAjAIIALwAAG8DAAAAnwADAvsCAQBNAQIZBAAAAPEAGgABAAAA+wEBADAAARkEAAAADgAPAPsCAgBNAQLvBQAAAJ8BAQL7AwEATQIDFgYAAAAwAQJhBwAAAPsCAQBSBAEAvAICCQgAAACfAgMBggABAPsCAQBNAQIWBgAAAMYCAAAwAgFhBwAAAIIAAQAJAwsDDAMNAw4DDwMDAwYDEAMRACQAARgAAAAAAAAAAAECAAAAAAAAAAEAAAAAAgAAAAABAAABAQAAAAEAAAAAAQAAAAAAAgAAAAAABCUAAAAABgEEAAAAJLwBAMMAAAAAnwECAvsDAABNAgMxAQAAAJoBEgACAAAATQIAFgIAAAD7BAEATQMExAMAAABvBAQAnwMCAtkFAAASAgIAEgAAABICAwC8AwPHBQAAAJ8DAwIwAwIoBgAAAIIAAQBNAgAWAgAAAMYDAAAwAwIoBgAAAE0CABYCAAAAxgMAADADAmEHAAAAggABAAgDEgMTAwYDFAIAAAAAAADQPwMJAxUDEAECIQEBGAAAAAEAAAAAAQAAAAAAAAAAAAAAAAAAAAAUAAAAAAEAAAAAAiIAAAAACgAJAAAAUowAAQD7AQAAbwMAALwBARIBAAAAnwEDAioBAwABAACAjAAFAGUAAQCMAAEA+wIBAE0BAp8CAAAA+wICAPsFAwBNBAUTAwAAAE0DBDsEAAAAnwEDAvsCBACkAwcAABhQgFIEAQCfAwICMAMChQUAAAD7AgUA+wUCAE0EBS8JAAAAWwMECDADAi8JAAAA+wIFAPsEAgBNAwSFBQAAADADAoUFAAAApAIMAAAsoICfAgEC+wQGACYDAgT7BAcAjAcBAOwIAwCeEwcDCAAAAKQGDwAAONCAnwYDArwEBP8QAAAAnwQDAWAAFwADAAAA+wUIACYEAgWMBQEAYAUSAAQAAADeAggA+wYDAE0FBkgRAAAATQQFuRIAAAD7BgAA+wgCAE0HCIUFAAAAUgkBALwHB8YTAAAAnwcDALwEBGsUAAAAnwQAAYIAAQAVAxYDFwMYAwwDGQMaAwMEABhQgAJSuB6F61HwPwMbAxwDHQQALKCAAx4DHwQAONCAAyADBQMhAyIDIwBLJAEYAAEAAAAAAAABAAIDAAAAAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAACAAABAAEAAAAAAAAAAAAAAQABAAAAAAEBAAAAAAAAAAAAAAAAAAAAA0wAAAAAAwADAAAADfsBAABNAAGtAAAAAPsCAQBNAQITAQAAAJ8AAgIOAAQA+wACALwAAFECAAAAnwACAYIAAQADAw0DDAMlAGQAARgAAAAAAAAAAAEAAAACZgAAAAADAAMAAAAN+wEAAE0AAd0AAAAA+wIBAE0BAhMBAAAAnwACAg4ABAD7AAIAvAAAUQIAAACfAAIBggABAAMDCwMMAyUAagABGAAAAAAAAAAAAQAAAAJrAAAAAA8CBAAAAGtNAgAZAAAAAPsEAABNAwRoAQAAAFIEAgCfAwICvAQAmQIAAACfBAICpAUEAAAAMEAwBQQkBQAAAFIHBAC8BQH9BgAAAJ8FAwG8BQAjBwAAAJ8FAgKkBgQAAAAwQDAGBSQFAAAAUggFALwGAf0GAAAAnwYDAfsHAQBNBgfvCAAAAJ8GAQJSCQYAvAcB/QYAAACfBwMBpAkKAAAgkIBvCgsAjAsAAG8MDACMDQAAnwkFALwHBugNAAAAnwcAAYwHAACkCBAAADzggJ8IAQLZCQAAEgACABICAgASAAMAEgAAABIABAASAAUAEgAIABIABgASAQf/+w0DAE0MDf0RAAAAUg4JALwMDMcSAAAAnwwDALwKAf0GAAAAnwoAAVIKCQCfCgEB+w0AAE0MDXcTAAAATQ0AExQAAACfDAIC2Q4BABICAAASAAAAEgABALwMDMcSAAAAnwwDALwKAf0GAAAAnwoAAfsNAABNDA3hFQAAAE0NABMUAAAAnwwCAtkOAgASAgAAEgAAABIAAQC8DAzHEgAAAJ8MAwC8CgH9BgAAAJ8KAAHBBwAAggABABYDDwMmAycDKAQAADBAAykDCgMqAwMDKwQAIJCAAgAAAAAAAOA/AlVVVVVVVeU/AywDHAMdBAA84IADLQMJAy4DDAMvAwQFBjwRARgAAAEAAAAAAQAAAQAAAAEAAAABAAABAAAAAQAAAAEAAAABAAAAAQAAAAAAAAAAAAIBAAABAAAAAAAAAAAAFwAAAAAAAAAAAAEAAQAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAFAD0AAAAABgEAAAAAI6QBAgAABACAbwIDAJ8BAgJvAgQAMAIBLwUAAACpAgAAMAIB0wYAAACkAggAAARwgIwDAQCMBAAAjAUAAJ8CBAIwAgGkCQAAAKQCDQAMLKDAMAIBfg4AAABvAg8AMAIB2RAAAACMAgAAjAMAADACAR8RAAAAMAMBEhIAAACpAgEAMAIBRRMAAACCAQIAFAMwAwMEAAQAgAMxBwAAgD8AAIA/AACAPwAAAAADGwMyAzMEAARwgAM0AzUDNgM3BAwsoMADOAIzMzMzMzPTPwM5AzoDOwM8AHAnARgAAAAAAQAAAQAAAQAAAAAAAAABAAAAAQAAAQAAAAAAAQAAAXEAAAAABgEAAAAAHKQBAgAABACAbwIDAJ8BAgKpAgAAMAIB0wQAAACkAgYAAARQgIwDAACMBAEAjAUAAJ8CBAIwAgGkBwAAAG8CCAAwAgHZCQAAAIwCAACMAwAAMAIBHwoAAAAwAwESCwAAAKkCAQAwAgFFDAAAAIIBAgANAzADAwQABACAAzEDMgMzBAAEUIADNAKamZmZmZnpPwM5AzoDOwM8AHsqARgAAAAAAQAAAQAAAAAAAAABAAABAAAAAAABAAABfAAAAAAFAgAAAAAIbwQAALwCAQMBAAAAnwIDAisCAgBNAgGbAgAAAIICAgADAz0DPgM/AIQBQAEYAAAAAAAAAACFAAAAAA8CAwAAAC/7AgAAbwQAALwCAgUBAAAAnwIDAsYDAACkBAMAAAAgQFIFAgCfBAIEUQQhAE0JABMEAAAAUgsIALwJCa0FAAAAnwkDAisJGgD7CgEATQkKaAYAAABSCggAnwkCAg4JFAD7CwIATQoLnwcAAABSCwkATQ0AEwQAAABNDA07CAAAAJ8KAwJNDgATBAAAAE0NDjsIAAAAJgwNCk0LDKoJAAAAYAsDAAEAAABSAQsAUgMIAG4E3v8CAACAggMCAAoDQQNCA0MEAAAgQAMMA0QDJgMYAxkDRQCHAQ4BGAAAAAAAAgEAAAAAAwAAAAAAAAEAAAAAAQEAAAAAAAAAAAIAAAAAAAABAAEB9QARiAAAAAAFAQEAAAAMTQMASAAAAABNAgNBAQAAAE0BAuwCAAAA+wIAAFIEAQC8AgJhAwAAAJ8CAwKCAgIABAMFAwcDRgNHAJ4BEgEYAAAAAAAAAQAAAAABnwAAAAADAQAAAAAITQIASAAAAABNAQLMAQAAALwBAWsCAAAAnwECAYIAAQADAwUDSAMjAKMBSQEYAAAAAAAAAAGkAAAAABAAAAECAIwBowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBAQAAAABAbwMEALwBARYDAAAAnwEDAqQCAQAAAABAbwQFALwCAhYDAAAAnwIDAqQDAQAAAABAbwUGALwDAxYDAAAAnwMDAqQECAAAAHBATQYDoQkAAABNBQZLCgAAAJ8EAgKkBQgAAABwQE0GA4kLAAAAnwUCAqQGCAAAAHBATQgDoQkAAABNBwg8DAAAAJ8GAgKkBwgAAABwQE0JA6EJAAAATQgJrA0AAACfBwICpAgIAAAAcEBNCgOhCQAAAE0JCnYOAAAAnwgCAqQJCAAAAHBATQsDxA8AAABNCgsPEAAAAJ8JAgKkCggAAABwQE0MA70SAAAATQsMOREAAACfCgIC/wsFAAAAAAAwCwtuEwAAAJ49CwUEAAAAUg0LAFIOBACkDBUAAABAQZ8MAwHADBYAEgAEABIACwAwDAvvFwAAAMAMGAASAAEAEgAHABIACQASAAgAMAwLNxkAAADADBoAEgAJABIACgASAAYAEgACADAMCwkbAAAAwAwcADAMC5kdAAAAwAweADAMCyMfAAAAwAwgADAMCzwhAAAAwAwiABIAAAASAAkAEgAGADAMC28jAAAAwAwkABIAAQAwDAvDJQAAAMAMJgAwDAtYJwAAAE0MBe8XAAAAbw0PAOIOKwBvDywAMA8OuSgAAABvDy0AMA8OzCkAAABvDy4AMA8OQSoAAABSDwsAnwwEAIIMAAAvA0oEAAAAQANLA0wDTQNOA08DUAQAAHBAA1EDUgNTA1QDVQNWA1cDWANZA1oDWwMEBAAAQEEGAQMDBgMDAQYHAxEGCAMnBgkDKgYKA0AGCwMOBgwDEgYNA0kDIQNIAwcFAygpKgNcA10DXgkBAwcICQoLDA0BAAEYAAEAAAAAAAEAAAAAAAEAAAAAAAEAAAAAAAEAAAAAAAABAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAIAAAAAAAABAAAAAAAAAgABAAEAAAAAAAACAAAAAA4AAAAAAAAbAAAAAAAANAAACwAACQAAAwAAAAAAFwAAAAUAAAQAAAABAAABAAABAAAB/AABAAAAAA4QOfxdMeIZjSL9lsnUqi3ZqDQZ/lHNl2yDsmD0c3SzmbUG6A+JJzOr

-- Decompiled by Krnl

local v_u_1 = game:GetService("CollectionService")
local v_u_2 = game:GetService("Players")
local v_u_3 = game:GetService("RunService")
local v4 = game:GetService("ReplicatedStorage")
local v_u_5 = require(v4.Std.BaseObject)
local v6 = require(v4.ManifestBinder)
local v_u_7 = require(v4.Std.GeomUtils)
local v_u_8 = require(v4.Std.Interval)
local v_u_9 = require(v4.Std.Maid)
local v_u_10 = require(v4.VehicleLink.VehicleLinkUtils)
local v_u_11 = require(v4.Game.LoadingBar)
local v_u_12 = {}
v_u_12.__index = v_u_12
setmetatable(v_u_12, v_u_5)
function v_u_12.new(p13, p14)
	-- upvalues: (copy) v_u_5, (copy) v_u_12
	local v_u_15 = v_u_5.new(p13)
	local v16 = v_u_12
	setmetatable(v_u_15, v16)
	v_u_15.manifest = p14
	v_u_15:_updateSeeking()
	v_u_15.maid:GiveTask(v_u_15.manifest.networkOwnerIdObj.Changed:Connect(function()
		-- upvalues: (copy) v_u_15
		v_u_15:_updateSeeking()
	end))
	return v_u_15
end
function v_u_12._updateSeeking(p_u_17)
	-- upvalues: (copy) v_u_2, (copy) v_u_8, (copy) v_u_10, (copy) v_u_9
	if p_u_17:GetOwner() == v_u_2.LocalPlayer then
		p_u_17.maid.seeking = v_u_8.every(0.25):Connect(function()
			-- upvalues: (ref) v_u_10, (copy) p_u_17, (ref) v_u_9
			if not v_u_10.getDisabled(p_u_17.obj) then
				if not v_u_10.getIsLinked(p_u_17.obj) then
					local v18 = p_u_17:_getNearestObj(8)
					if v18 ~= p_u_17.nearestObj then
						p_u_17.nearestObj = v18
						if v18 then
							local v19 = v_u_9.new()
							p_u_17.maid.nearestMaid = v19
							p_u_17:_hookNearest(v19)
							return
						end
						p_u_17.maid.nearestMaid = nil
					end
				end
			end
		end)
	else
		p_u_17.maid.seeking = nil
		p_u_17.maid.nearestMaid = nil
	end
end
function v_u_12._hookNearest(p_u_20, p_u_21)
	-- upvalues: (copy) v_u_10, (copy) v_u_11, (copy) v_u_7, (copy) v_u_3
	local v_u_22 = p_u_20.nearestObj
	local v_u_23 = v_u_10.getPrimaryPart(v_u_22)
	local v_u_24 = p_u_20:_makePartVisualBall()
	v_u_24.Parent = workspace
	p_u_21:GiveTask(v_u_24)
	local v_u_25 = p_u_20:_makePartVisualBlock()
	v_u_25.Parent = workspace
	p_u_21:GiveTask(v_u_25)
	local v_u_26 = v_u_11.new()
	p_u_21:GiveTask(v_u_26)
	v_u_26:SetPosition(UDim2.new(0.5, 0, 0.6666666666666666, 0))
	local v_u_27 = 0
	local v_u_28 = os.clock()
	local function v35()
		-- upvalues: (copy) v_u_22, (ref) v_u_7, (copy) v_u_23, (copy) p_u_20, (copy) v_u_24, (copy) v_u_25, (copy) v_u_28, (copy) v_u_26, (ref) v_u_27
		local v29 = v_u_22:GetAttribute("VehicleHasDriver") == true and 5 or 1
		local v30 = v_u_7.closestPointInPart(v_u_23, p_u_20.obj.Position)
		v_u_24.CFrame = CFrame.new(v30)
		v_u_25.Size = v_u_23.Size * 1.02
		v_u_25.CFrame = v_u_23.CFrame
		local v31 = os.clock()
		local v32 = v31 - v_u_28
		local v33 = v_u_26
		local v34 = v32 / v29
		v33:SetValue((math.min(1, v34)))
		if v29 < v32 and v31 - v_u_27 > 1 then
			v_u_27 = v31
			p_u_20.manifest.reqLinkRemote:FireServer(v_u_22, v_u_23.CFrame:PointToObjectSpace(v30))
		end
	end
	p_u_21:GiveTask(v_u_3.Heartbeat:Connect(v35))
	v35()
	p_u_21:GiveTask(v_u_10.getIsLinkedChangedSignal(p_u_20.obj):Connect(function()
		-- upvalues: (ref) v_u_10, (copy) p_u_20, (copy) p_u_21
		if v_u_10.getIsLinked(p_u_20.obj) then
			p_u_21:DoCleaning()
		end
	end))
	p_u_21:GiveTask(v_u_10.getDisabledChangedSignal(p_u_20.obj):Connect(function()
		-- upvalues: (ref) v_u_10, (copy) p_u_20, (copy) p_u_21
		if v_u_10.getDisabled(p_u_20.obj) then
			p_u_21:DoCleaning()
		end
	end))
end
function v_u_12._makePartVisualBall(_)
	local v36 = Instance.new("Part")
	v36.Size = Vector3.new(1, 1, 1)
	v36.CanCollide = false
	v36.Color = Color3.new(1, 0, 0)
	v36.Shape = Enum.PartType.Ball
	v36.Transparency = 0.3
	v36.TopSurface = 0
	v36.BottomSurface = 0
	v36.Anchored = true
	return v36
end
function v_u_12._makePartVisualBlock(_)
	local v37 = Instance.new("Part")
	v37.CanCollide = false
	v37.Color = Color3.new(0, 1, 0)
	v37.Transparency = 0.8
	v37.TopSurface = 0
	v37.BottomSurface = 0
	v37.Anchored = true
	return v37
end
function v_u_12._getPrimaryPart(_, p38)
	return p38:FindFirstChild("BoundingBox") or p38.PrimaryPart
end
function v_u_12._getNearestObj(p39, p40)
	-- upvalues: (copy) v_u_1, (copy) v_u_10, (copy) v_u_7
	local v41 = v_u_1:GetTagged("HeliPickup")
	local v42 = nil
	for _, v43 in ipairs(v41) do
		if not p39.obj:IsDescendantOf(v43) then
			local v44 = v_u_10.getPrimaryPart(v43)
			if v44 then
				local v45 = v_u_7.closestPointInPart(v44, p39.obj.Position)
				local v46 = (p39.obj.Position - v45).Magnitude
				if v46 < p40 then
					v42 = v43
					p40 = v46
				end
			end
		end
	end
	return v42
end
function v_u_12.GetOwner(p47)
	-- upvalues: (copy) v_u_2
	return v_u_2:GetPlayerByUserId(p47.manifest.networkOwnerIdObj.Value)
end
function v_u_12.Unattach(p48)
	p48.manifest.reqUnlinkRemote:FireServer()
end
return v6.new("VehicleLink", {
	["reqLinkRemote"] = "ReqLink",
	["reqUnlinkRemote"] = "ReqUnlink",
	["networkOwnerIdObj"] = "NetworkOwnerId"
}, v_u_12)
