-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMqBnR5cGVvZghJbnN0YW5jZQZhc3NlcnQVTUlTU0lMRV9PQkpfUE9PTF9OQU1FDkZpbmRGaXJzdENoaWxkFWdldE1pc3NpbGVJdGVtUG9vbE9iagdFbmFibGVkA25ldwRQYXJ0BFNpemUKQ2FuQ29sbGlkZQhBbmNob3JlZAxUcmFuc3BhcmVuY3kIUG9zaXRpb24Jd29ya3NwYWNlBlBhcmVudAlFeHBsb3Npb24IUmVzb3VyY2UKSXRlbVN5c3RlbQtQcm9qZWN0aWxlcwVDbG9uZQRFbWl0BkRlYnJpcwVTbW9rZQxMYW5kaW5nU21va2UFZGVsYXkITGlmZXRpbWUDTWF4BGdhbWUHQWRkSXRlbQtPYmplY3RMb2NhbBJleHBsb3Npb25fbGFyZ2VfMDIGVm9sdW1lC0VtaXR0ZXJTaXplCWV4cGxvZGVBdBFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUDU3RkBUF1ZGlvBnNjcmlwdBRSb2NrZXRMYXVuY2hlckNvbnN0cwAEBQEBAAAAFLssAANSBAAApAMBAAAAAECfAwIC8AMCAAIAAACpAgABqQIBALsBAgKkAQQAAAAwQJ8BAgH7BAAATQMEeAUAAAC8AQADBgAAAJ8BAwCCAQAABwMBBAAAAEADAgMDBAAAMEADBAMFAAkGARgAAAAAAAAAAAAAAAAAAQAAAAAAAAoAAAAAAgABAAAABfsAAACpAQAAMAEA8AAAAACCAAEAAQMHACgAARgAAAAAASkAAAAACwEDAAAAhQG7AQADUgIAAKQBAQAAAABAnwECAaQBBAAADCCAbwIFAJ8BAgJvAgYAMAIBLwcAAACpAgAAMAIB0wgAAACpAgEAMAIBRQkAAACMAgEAMAIB2QoAAAAwAAE7CwAAAKQCDQAAAMBAMAIBJA4AAAD7BgAATQUGYhAAAABNBAXwEQAAAE0DBA8SAAAATQIDlg8AAAC8AgI6EwAAAJ8CAgIwAQIkDgAAAIwFBAC8AwJWFAAAAJ8DAwH7BwAATQYHYhAAAABNBQbwEQAAAE0EBQ8SAAAATQMEnRUAAAC8AwM6EwAAAJ8DAgIwAQMkDgAAAIwGMgC8BANWFAAAAJ8EAwH7CAAATQcIYhAAAABNBgfwEQAAAE0FBg8SAAAATQQFJRYAAAC8BAQ6EwAAAJ8EAgIwAQQkDgAAAIwHAwC8BQRWFAAAAJ8FAwH7CQAATQgJYhAAAABNBwjwEQAAAE0GBw8SAAAATQUGEhcAAAC8BQU6EwAAAJ8FAgKpBgEAMAYF8BgAAAAwAQUkDgAAAKQGGgAAAJBBTQkFyxwAAABNCAm0HQAAAPUHGwjZCAAAEgAFAJ8GAwGkBx8AAADgQU0GB50VAAAAUggBAIwJCgC8BgZ4IAAAAJ8GBAH7BwEATQYH0SEAAABSBwEA+wkCAE0ICeIiAAAA4gkkAIwKAQAwCglLIwAAAJ8GBAKMBxQAMAcGgyUAAACCAAEAJgMDBAAAAEADAgMIBAAMIIADCQfNzMw9zczMPc3MzD0AAAAAAwoDCwMMAw0DDgMPBAAAwEADEAMRAxIDEwMUAxUDFgMXAxgDGQMHAxoEAACQQQIAAAAAAAAkQAMbAxwDHQQAAOBBAx4DHwMgAyEFASMDIgEBDSMBGAAAAAAAAQAAAAEAAAEAAAEAAAEAAAEAAQAAAAIAAAAAAAAAAAAAAAEAAQAAAAIAAAAAAAAAAAAAAAEAAQAAAAIAAAAAAAAAAAAAAAEAAQAAAAIAAAAAAAAAAAAAAAEAAAEAAwAAAAAAAAAAAAMAAAAAAAAAAAIAAAAAAAAAAAAAAAEAAAEOAAAAAAYAAAECACijAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CA9IHAAAAnwECAqQCBQAAAEBApAUJAAAAgEBNBAUkCgAAAE0DBA4LAAAAnwICAv8DAgAAAAAA4gQNAG8FDgAwBQTiDAAAAMAFDwASAAIAMAUDPRAAAADABREAEgAAABIAAQASAAQAMAUDGBIAAACCAwIAEwMdBAAAAEADJAMlAyYEAABAQAMnAygDKQQAAIBAAxADKgMgBQEMAgAA4C24beBBBgADBgYCAyMCAAIBAAEYAAEAAAAAAAEAAAAAAAABAAAAAAAAAAABAAEBAAACAAAABAAAAAAAIwEAAAAAAxkXDsBroLaoK9NkVJCqNUF1n10KjFVWTr1x+aXtXOmVmEl1GAJUviM=

-- Decompiled by Krnl

local v_u_1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v_u_1.Std.Audio)
local v_u_3 = require(script.Parent.RocketLauncherConsts)
local v4 = {}
local v_u_5 = {
	["explosion_large_02"] = 2205008239
}
function v4.getMissileItemPoolObj(p6)
	-- upvalues: (copy) v_u_3
	local v7 = typeof(p6) == "Instance"
	assert(v7)
	return p6:FindFirstChild(v_u_3.MISSILE_OBJ_POOL_NAME)
end
function v4.explodeAt(p8)
	-- upvalues: (copy) v_u_1, (copy) v_u_2, (copy) v_u_5
	assert(p8)
	local v9 = Instance.new("Part")
	v9.Size = Vector3.new(0.1, 0.1, 0.1)
	v9.CanCollide = false
	v9.Anchored = true
	v9.Transparency = 1
	v9.Position = p8
	v9.Parent = workspace
	local v10 = v_u_1.Resource.ItemSystem.Projectiles.Explosion:Clone()
	v10.Parent = v9
	v10:Emit(4)
	local v11 = v_u_1.Resource.ItemSystem.Projectiles.Debris:Clone()
	v11.Parent = v9
	v11:Emit(50)
	local v12 = v_u_1.Resource.ItemSystem.Projectiles.Smoke:Clone()
	v12.Parent = v9
	v12:Emit(3)
	local v_u_13 = v_u_1.Resource.ItemSystem.Projectiles.LandingSmoke:Clone()
	v_u_13.Enabled = true
	v_u_13.Parent = v9
	delay(10 - v_u_13.Lifetime.Max, function()
		-- upvalues: (copy) v_u_13
		v_u_13.Enabled = false
	end)
	game.Debris:AddItem(v9, 10)
	v_u_2.ObjectLocal(v9, v_u_5.explosion_large_02, {
		["Volume"] = 1
	}).EmitterSize = 20
end
return v4
