-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNiCmhvc3RQYXJlbnQHaG9zdEtleQVkZXB0aAZwYXJlbnQPb3JpZ2luYWxDb250ZXh0B2NvbnRleHQTcGFyZW50TGVnYWN5Q29udGV4dAx3YXNVbm1vdW50ZWQScmVwbGFjZVZpcnR1YWxOb2RlEmludGVybmFsVHlwZUNoZWNrcwJvZgtWaXJ0dWFsTm9kZSlFeHBlY3RlZCBhcmcgIzEgdG8gYmUgb2YgdHlwZSBWaXJ0dWFsTm9kZRN1cGRhdGVDaGlsZHJlbkNvdW50BXBhaXJzCGNoaWxkcmVuD2dldEVsZW1lbnRCeUtleQ9pdGVyYXRlRWxlbWVudHMMVXNlUGFyZW50S2V5DWxlZ2FjeUNvbnRleHQOdXBkYXRlQ2hpbGRyZW4ddXBkYXRlVmlydHVhbE5vZGVXaXRoQ2hpbGRyZW4HRWxlbWVudAZ0eXBlb2YHYm9vbGVhbgVlcnJvcgUlcwolcyRDb21wb25lbnQgcmV0dXJuZWQgaW52YWxpZCBjaGlsZHJlbjobPGVuYWJsZSBlbGVtZW50IHRyYWNlYmFja3M+DmN1cnJlbnRFbGVtZW50BnNvdXJjZQZmb3JtYXQhdXBkYXRlVmlydHVhbE5vZGVXaXRoUmVuZGVyUmVzdWx0BEhvc3QPdW5tb3VudEhvc3ROb2RlCEZ1bmN0aW9uCFN0YXRlZnVsCGluc3RhbmNlCV9fdW5tb3VudAZQb3J0YWwIRnJhZ21lbnQWVW5rbm93biBFbGVtZW50S2luZCAlcQh0b3N0cmluZxJ1bm1vdW50VmlydHVhbE5vZGUJY29tcG9uZW50BXByb3BzGXVwZGF0ZUZ1bmN0aW9uVmlydHVhbE5vZGUGdGFyZ2V0DGlzSG9zdE9iamVjdCFFeHBlY3RlZCB0YXJnZXQgdG8gYmUgaG9zdCBvYmplY3QGYXNzZXJ0F3VwZGF0ZVBvcnRhbFZpcnR1YWxOb2RlCGVsZW1lbnRzGXVwZGF0ZUZyYWdtZW50VmlydHVhbE5vZGUKdHlwZUNoZWNrczZFeHBlY3RlZCBhcmcgIzIgdG8gYmUgb2YgdHlwZSBFbGVtZW50LCBib29sZWFuLCBvciBuaWwOdXBkYXRlSG9zdE5vZGUIX191cGRhdGURdXBkYXRlVmlydHVhbE5vZGUjRXhwZWN0ZWQgYXJnICMyIHRvIGJlIGEgaG9zdCBvYmplY3QFdGFibGUqRXhwZWN0ZWQgYXJnICM0IHRvIGJlIG9mIHR5cGUgdGFibGUgb3IgbmlsKkV4cGVjdGVkIGFyZyAjNSB0byBiZSBvZiB0eXBlIHRhYmxlIG9yIG5pbB1FeHBlY3RlZCBhcmcgIzMgdG8gYmUgbm9uLW5pbDBFeHBlY3RlZCBhcmcgIzEgdG8gYmUgb2YgdHlwZSBFbGVtZW50IG9yIGJvb2xlYW4RY3JlYXRlVmlydHVhbE5vZGUYbW91bnRGdW5jdGlvblZpcnR1YWxOb2RlFm1vdW50UG9ydGFsVmlydHVhbE5vZGUYbW91bnRGcmFnbWVudFZpcnR1YWxOb2RlDW1vdW50SG9zdE5vZGUHX19tb3VudBBtb3VudFZpcnR1YWxOb2RlJUV4cGVjdGVkIGFyZyAjMSB0byBiZSBvZiB0eXBlIEVsZW1lbnQJUm9hY3RUcmVlC1ZpcnR1YWxUcmVlCHJvb3ROb2RlB21vdW50ZWQQbW91bnRWaXJ0dWFsVHJlZSRFeHBlY3RlZCBhcmcgIzEgdG8gYmUgYSBSb2FjdCBoYW5kbGU9Q2Fubm90IHVubW91bnRlZCBhIFJvYWN0IHRyZWUgdGhhdCBoYXMgYWxyZWFkeSBiZWVuIHVubW91bnRlZBJ1bm1vdW50VmlydHVhbFRyZWUlRXhwZWN0ZWQgYXJnICMyIHRvIGJlIGEgUm9hY3QgRWxlbWVudBF1cGRhdGVWaXJ0dWFsVHJlZRBjcmVhdGVSZWNvbmNpbGVyB3JlcXVpcmUGc2NyaXB0BlBhcmVudARUeXBlC0VsZW1lbnRLaW5kDEVsZW1lbnRVdGlscwtQcm9wTWFya2VycwhDaGlsZHJlbgZTeW1ib2wOaW50ZXJuYWxBc3NlcnQMR2xvYmFsQ29uZmlnA2dldAVuYW1lZAxJbnRlcm5hbERhdGEAEw4CAgAAACNNAgDIAAAAAE0DADkBAAAATQQAHQIAAABNBQDEAwAAAE0GAAMEAAAAKwYCAE0GAK4FAAAATQcA1QYAAABNCABxBwAAACsIAwD7CAAAUgkAAJ8IAgH7CAEAUgkBAFIKAgBSCwMAUgwGAFINBwCfCAYCRwgFAAAAAAAwBAgdAgAAADAFCMQDAAAAgggCAAgDAQMCAwMDBAMFAwYDBwMIACUJARgAAAEAAQABAAUAAAAAAQAFAAABAAACAAAAAAAAAwABAAEAAyYAAAAAEQMHAAAAgwH7BAAATQME4AAAAAAOAw8A+wMBAPsGAgBNBQa8AQAAAFIGAACfBQIC+wcCAE0GB2cCAAAA8QUCAAYAAACpBAABqQQBAG8FAwCfAwMBTQQA8gUAAACVAwQEMAMA8gUAAABNAwDyBQAAAP8EAAAAAAAApAUHAAAAYEBNBgDuCAAAAJ8FAgQXBSAA+wsDAE0KC2gJAAAAUgsCAFIMCACfCgMC+wsEAFIMCQBSDQoAnwsDAk0MAPIFAAAA8QwLAAMAAAAOCwgATQ0A7ggAAACHDA0I8QsEAAwAAAD7DAUAUg0LAJ8MAgGCAAEARwsFAAAAAABNDADuCAAAAGoLDAhlAAIAqQwBAGoMBAhuBd//AgAAAKQFBwAAAGBAUgYEAJ8FAgQXBQQATQoA7ggAAADGCwAAagsKCG4F+/8BAAAA+wYDAE0FBlIKAAAAUgYCAJ8FAgRkBSsAUgoIAPsMAwBNCwzNCwAAAJoIAwALAAAATQoAOQwAAABNDADuCAAAAIcLDAhHCx8AAAAAgPsLBgBSDAkAUg0BAFIOCgBNDwCuDQAAAE0QAJEOAAAAnwsGAk0MAPIFAAAA8QwGAAMAAAAOCwMA+wwFAFINCwCfDAIBggABAEcLCwAAAAAATQ0AHQ8AAACVDA0EMAwLHQ8AAAAwAAvEEAAAAE0MAO4IAAAAagsMCG4F1P8CAAAAggABABEDCgMLAwwDDQIAAAAAAADwPwMOAw8EAABgQAMQAxEDEgMTAwIDBgMUAwMDBABGFQEYAAAAAAEAAAAAAAAAAAAAAAAAAAMAAAAAAgACAAMAAAAAAAEAAAAAAAEAAAAFAAAAAQAAAAAAAQAAAgMAAQAAAAIA7wAVAAAAAAEAAAD/AAUAAAAAAAEBAAAAAAEAAwAAAAABAQEBAQABAPsLAAAAAQEAAAIEAAEAAAAAAQABAADjACFHAAAAAAcDAQAAAAb7AwAAUgQAAFIFAQBSBgIAnwMEAYIAAQAAAI8BFgEYAAAAAAABkAAAAAAKAwIAAAcAAAEDBCICKPsEAABNAwS8AAAAAFIEAgCfAwIC+wUAAE0EBZcBAAAA8QMKAAQAAABHAggAAAAAALssAgNSBAIApAMDAAAAIECfAwIC8AMHAAQAAID7AwEAUgQAAFIFAQBSBgIAnwMEAYIAAQCkAwYAAABQQG8EBwBvBggATQkAWgoAAABNCAliCwAAAJAHCAm8BASNDAAAAJ8EBAKMBQAAnwMDAYIAAQANAwsDFwMYBAAAIEADGQMaBAAAUEADGwMcAx0DHgMfAyAAkwEhARgAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAgABAQEAAAAA/gAABPsIlAAAAAAJAQcAAAcAAAEDA24CdPsCAABNAQLgAAAAAA4BDwD7AQEA+wQCAE0DBLwBAAAAUgQAAJ8DAgL7BQIATQQFZwIAAADxAwIABAAAAKkCAAGpAgEAbwMDAJ8BAwGpAQEAMAEAcQQAAAD7AgMATQECvAEAAABNAgBaBQAAAJ8BAgL7AwMATQIDKAYAAACaAQgAAgAAAPsDBABNAgNeBwAAAPsDBQBSBAAAnwIDAYIAAQD7AwMATQIDiAgAAACaAQ0AAgAAAKQCCgAAAJBATQMA7gsAAACfAgIEFwIDAPsHBgBSCAYAnwcCAW4C/P8CAAAAggABAPsDAwBNAgMmDAAAAJoBBwACAAAATQIAFA0AAAC8AgLNDgAAAJ8CAgGCAAEA+wMDAE0CAxIPAAAAmgENAAIAAACkAgoAAACQQE0DAO4LAAAAnwICBBcCAwD7BwYAUggGAJ8HAgFuAvz/AgAAAIIAAQD7AwMATQIDKRAAAACaAQ0AAgAAAKQCCgAAAJBATQMA7gsAAACfAgIEFwIDAPsHBgBSCAYAnwcCAW4C/P8CAAAAggABAKQCEgAAABBBbwMTALs/AQNSBgEApAUVAAAAQEGfBQICvAMDjRYAAACfAwMCjAQCAJ8CAwGCAAEAFwMKAwsDDAMNAwgDHgMiAyMDJAMPBAAAkEADEAMlAyYDJwMoAykDGgQAABBBAyoDKwQAAEBBAyAApAEsARgAAAAAAQAAAAAAAAAAAAAAAAAAAwAAAgAAAAAAAwAAAAABAAAAAAAAAQAAAAABAAAAAAABAAD/AAADAAAAAAEAAAAAAAEAAAAAAQAAAAAAAQAA/wAAAwAAAAABAAAAAAABAAD/AAAEAAAAAAAAAAAAAAAAAqUAAAAABwIBAAAADE0CAegAAAAATQMBBwEAAACfAgIC+wMAAFIEAABNBQDIAgAAAFIGAgCfAwQBggACAAMDLQMuAwEAwwEvARgAAAAAAAIAAAAAAALEAAAAABICBQAAAEVNAgBaAAAAAE0EAgcBAAAATQMEDAIAAABNBQEHAQAAAE0EBQwCAAAA+wcAAE0GB1UDAAAAUgcEAJ8GAgKBAQYEBAAAAG8HBACkBQYAAABQQJ8FAwHxBCUAAwAAAE0GAMgHAAAATQcAOQgAAABNCAAdCQAAAE0JAMQKAAAATQoAAwsAAAArCgIATQoArgwAAABNCwDVDQAAAE0MAHEOAAAAKwwDAPsMAQBSDQAAnwwCAfsMAgBSDQEAUg4GAFIPBwBSEAoAUhELAJ8MBgJHDAUAAAAAADAIDB0JAAAAMAkMxAoAAABSBQwAggUCAE0GAQcBAAAA+wcDAIcFBgf7BgQAUgcAAFIIBABSCQUAnwYEAYIAAgAPAx4DLgMwAzEDMgMzBAAAUEADAQMCAwMDBAMFAwYDBwMIAMsBNAEYpgABAAAAAgAAAAIAAAAAAAAAAAAAAgBTAAEAAQABAAUAAAAAAQAFAAABAAACAAAAAAAAAwABAAEAAwCYAAAAuQAAAABLJgAAAAAIAgEAAAAKTQIAyAAAAABNAwHCAQAAAPsEAABSBQAAUgYCAFIHAwCfBAQBggACAAIDAQM1AN4BNgEYTwAAALEAAAAAUZAAAAAAFQMLAAAIAAABAwaQAgKaAvsEAABNAwTgAAAAAA4DDwD7AwEA+wYCAE0FBrwBAAAAUgYAAJ8FAgL7BwIATQYHZwIAAADxBQIABgAAAKkEAAGpBAEAbwUDAJ8DAwH7BAAATQMEQgQAAAAOAx0AqQQBAPsGAgBNBQa8AQAAAFIGAQCfBQIC+wcCAE0GB5cFAAAA8QUNAAYAAACpBAEAuywBA1IGAQCkBQcAAABgQJ8FAgLwBQUACAAAAEcBAgAAAAAAqQQAAakEAQCBAQQECQAAAG8FCQCkAwsAAACgQJ8DAwFNAwBaDAAAAJoDBAABAAAARwICAAAAAICCAAIAuywBA1IEAQCkAwcAAABgQJ8DAgLwAwMACAAAAEcBBgAAAACA+wMDAFIEAACfAwIBxgMAAIIDAgBNBABaDAAAAE0DBOgNAAAATQQB6A0AAADxAyYABAAAAFIEAABNBQTIDgAAAE0GBDkPAAAATQcEHRAAAABNCATEEQAAAE0JBAMSAAAAKwkCAE0JBK4TAAAATQoE1RQAAABNCwRxFQAAACsLAwD7CwMAUgwEAJ8LAgH7CwQAUgwBAFINBQBSDgYAUg8JAFIQCgCfCwYCRwsFAAAAAAAwBwsdEAAAADAIC8QRAAAAUgMLAIIDAgD7BAUATQMEvAEAAABSBAEAnwMCAqkEAQD7BgUATQUGKBYAAACaAwoABQAAAPsGBgBNBQa3FwAAAPsGBwBSBwAAUggBAJ8FBAJSAAUAZQCLAPsGBQBNBQaIGAAAAJoDDwAFAAAAUgUAAE0GAegNAAAATQcBBxkAAACfBgIC+wcIAFIIBQBNCQXIDgAAAFIKBgCfBwQBUgAFAGUAeAD7BgUATQUGJhoAAACaAwoABQAAAE0FABQbAAAAUgcBAFIIAgC8BQUIHAAAAJ8FBAJSBAUAZQBqAPsGBQBNBQYSHQAAAJoDSAAFAAAAUgUAAE0GBVoMAAAATQgGBxkAAABNBwgMHgAAAE0JAQcZAAAATQgJDB4AAAD7CwYATQoLVR8AAABSCwgAnwoCAoEBCgQgAAAAbwsgAKQJCwAAAKBAnwkDAfEIJQAHAAAATQkFyA4AAABNCgU5DwAAAE0LBR0QAAAATQwFxBEAAABNDQUDEgAAACsNAgBNDQWuEwAAAE0OBdUUAAAATQ8FcRUAAAArDwMA+w8DAFIQBQCfDwIB+w8EAFIQAQBSEQkAUhIKAFITDQBSFA4Anw8GAkcPBQAAAAAAMAsPHRAAAAAwDA/EEQAAAFIADwBlACkATQoBBxkAAAD7CwkAhwkKC/sKCgBSCwUAUgwIAFINCQCfCgQBUgAFAGUAHgD7BgUATQUGKSEAAACaAw0ABQAAAFIFAABNBgXIDgAAAE0HAcIiAAAA+wgKAFIJBQBSCgYAUgsHAJ8IBAFSAAUAZQANAKQFJAAAADBCbwYlALs/AwNSCQMApAgnAAAAYEKfCAICvAYGjSgAAACfBgMCjAcCAJ8FAwErBAEAggACADABAFoMAAAAggACACkDCgMLAwwDDQM3AxcDGAQAAGBAAxkDOAMzBAAAoEADHgMtAwEDAgMDAwQDBQMGAwcDCAMiAzkDJAMuAyUDJgM6AygDMAMxAzIDKQM1AxoEAAAwQgMqAysEAABgQgMgAPABOwEYywAAAAEAAAAAAAAAAAAAAAAAAAIAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAcAAAAAAAEDAAAAAAAAAAABAAABAAMAAAAAAAAAASAAAQABAAEABQAAAAABAAUAAAEAAAIAAAAAAAADAAEAAQADAMoAAAAAAgIAAAAAAQAAAAAAAAAAAQAAAAABtAAAAAACAAAAAAACAEkAAAAAAQAAAAAAAAAAAQAAAAABuAABAAAAAgAAAAIAAAAAAAAAAAAAAgBTAAEAAQABAAUAAAAAAQAFAAABAAACAAAAAAAAAwABAAEAAwCYAAAAuQAAAABLADoAAAAAAckAAACxAAAAAFEANwAAAAAAAAAAAAAAAAUBAwACJgAAAAAKBQQAAACCAfsGAABNBQbgAAAAAA4FKwD7BQEA+wcCAE0GB1UBAAAAUgcBAJ8GAgIrBgQARwECAAAAAACpBgABqQYBAG8HAgCfBQMB+wUBAKkGAQC7LAMDUggDAKQHBAAAADBAnwcCAvAHBQAFAAAARwMCAAAAAACpBgABqQYBAG8HBgCfBQMB+wUBAKkGAQC7LAQDUggEAKQHBAAAADBAnwcCAvAHBQAFAAAARwQCAAAAAACpBgABqQYBAG8HBwCfBQMB+wYAAE0FBkIIAAAADgUkAEcCAgAAAACAqQYAAakGAQCBAQYECQAAAG8HCQCkBQsAAACgQJ8FAwGpBgEA+wgDAE0HCLwMAAAAUggAAJ8HAgL7CQMATQgJlw0AAADxBwoACAAAALssAANSCAAApAcEAAAAMECfBwIC8AcCAA4AAACpBgABqQYBAIEBBgQPAAAAbwcPAKQFCwAAAKBAnwUDAf8FBQAAAAAA+wYDAPsIAwBNBwhnEAAAAGoHBQYwAAVaEQAAAIwGAQAwBgUdEgAAAMYGAAAwBgXEEwAAAP8GAAAAAAAAMAYF7hQAAAAwAQXIFQAAADACBTkWAAAAjAYAADAGBfIXAAAAqQYAADAGBXEYAAAAMAQFkRkAAAAwBAXVGgAAAFIGAwArBgIA/wYAAAAAAAAwBgWuGwAAAMYGAAAwBgUDHAAAAIIFAgAdAwoDMQM8AxgEAAAwQAM9Az4DPwM3A0ADMwQAAKBAAwsDFwMZA0EDDAMeAwMDBAMQAwEDAgMOAwgDFAMHAwYDBQCpAkIBGAAAAAABAQAAAAAAAAAAAAH+BAAAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAH+BQAAAAEAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAYAAQAAAAABAAEAAAEAAAEAAAABAAEAAQAAAQAABAADAAQAAAAAAAQAAAAqAQAAAAcBAQAAAA5NAQBaAAAAAE0CAegBAAAATQMBBwIAAACfAgIC+wMAAFIEAABNBQDIAwAAAFIGAgCfAwQBggABAAQDHgMtAy4DAQDZAkMBGAAAAgAAAAACAAAAAAABWgEAAAAIAQMAAAAbTQEAWgAAAABNAwEHAQAAAE0CAwwCAAAATQQBBwEAAAD7BQAAhwMEBfsGAQBNBQZVAwAAAFIGAgCfBQICgQEFBAQAAABvBgQApAQGAAAAUECfBAMB+wQCAFIFAABSBgIAUgcDAJ8EBAGCAAEABwMeAy4DMAMxAzIDMwQAAFBAAOECRAEY0gACAAAAAQAAAAIAAAAAAAAAAAAAKQAAAADakAAAAAAIAQEAAAAMTQEAWgAAAABNAgHCAQAAAE0DAMgCAAAA+wQAAFIFAABSBgMAUgcCAJ8EBAGCAAEAAwMeAzUDAQDsAkUBGN0AAQACACAAAAAA4ZAAAAAADgUKAAAIAAABAwjCAQLIAfsGAABNBQbgAAAAAA4FHAD7BQEA+wcCAE0GB1UBAAAAUgcBAJ8GAgIrBgQARwECAAAAAACpBgABqQYBAG8HAgCfBQMB+wUBAKkGAQC7LAQDUggEAKQHBAAAADBAnwcCAvAHBQAFAAAARwQCAAAAAACpBgABqQYBAG8HBgCfBQMB+wYAAE0FBkIHAAAADgUkAEcCAgAAAACAqQYAAakGAQCBAQYECAAAAG8HCACkBQoAAACQQJ8FAwGpBgEA+wgDAE0HCLwLAAAAUggAAJ8HAgL7CQMATQgJlwwAAADxBwoACAAAALssAANSCAAApAcEAAAAMECfBwIC8AcCAA0AAACpBgABqQYBAIEBBgQOAAAAbwcOAKQFCgAAAJBAnwUDAbssAANSBgAApAUEAAAAMECfBQIC8AUDAA0AAIDGBQAAggUCAPsGBABNBQa8CwAAAFIGAACfBQIC+wYFAFIHAABSCAEAUgkCAFIKAwBSCwQAnwYGAvsIBABNBwgoDwAAAJoFCAAHAAAA+wgCAE0HCEoQAAAA+wgGAFIJBgCfBwMBggYCAPsIBABNBwiIEQAAAJoFDwAHAAAATQcGWhIAAABNCAfoEwAAAE0JBwcUAAAAnwgCAvsJBwBSCgYATQsGyBUAAABSDAgAnwkEAYIGAgD7CAQATQcIJhYAAACaBQkABwAAAE0HAOgTAAAA+wkGAFIKBgC8BwcdFwAAAJ8HBAGCBgIA+wgEAE0HCBIYAAAAmgUcAAcAAABNBwZaEgAAAE0JBwcUAAAATQgJDBkAAABNCgcHFAAAAPsLCACHCQoL+wwCAE0LDFUBAAAAUgwIAJ8LAgKBAQsEGgAAAG8MGgCkCgoAAACQQJ8KAwH7CgkAUgsGAFIMCABSDQkAnwoEAYIGAgD7CAQATQcIKRsAAACaBQ0ABwAAAE0HBloSAAAATQgHwhwAAABNCQbIFQAAAPsKCQBSCwYAUgwJAFINCACfCgQBggYCAKQHHgAAANBBbwgfALs/BQNSCwUApAohAAAAAEKfCgICvAgIjSIAAACfCAMCjAkCAJ8HAwGCBgIAIwMKAzEDPAMYBAAAMEADPQM/AzcDQAMzBAAAkEADCwMXAxkDQQMiA0YDJAMeAy0DLgMBAyUDRwMoAzADMgMpAzUDGgQAANBBAyoDKwQAAABCAyAA9wJIAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgBAAAAAAAAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAD+////BAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAD+////BQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////8AAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAxf///wAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5AAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAADJ////AAAAAAIAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAp////AAAAAAAAAAAAAAAAAAAAAAAAAAALAQAAAAAAAAAAAAAAAAAAAAAAANL///8AAAAAAQAAAAAAAAACAAAAAAAAACD///8AAAAAAAAAAAAAAAAAAAAAAAAAAA4BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAkDBQAAAEP7BAAATQMEQgAAAAAOAyIA+wYBAE0FBrwBAAAAUgYAAJ8FAgL7BwEATQYHlwIAAADxBQIABgAAAKkEAAGpBAEAgQEEBAMAAABvBQMApAMFAAAAQECfAwMB+wUCAE0EBVUGAAAAUgUBAJ8EAgIrBAQARwECAAAAAACpBAABqQQBAIEBBAQHAAAAbwUHAKQDBQAAAEBAnwMDAUcCAgAAAACAbwIIAP8DAgAAAAAA+wQBAPsGAQBNBQbfCQAAAGoFAwT7BAMA4gUMAMYGAAAwBgVPCgAAAKkGAQAwBgWgCwAAAGoFAwT7BQMAhwQDBfsFBABSBgAAUgcBAFIIAgCfBQQCMAUETwoAAACCAwIADQM3AwsDFwNJAzMEAABAQAMxAzwDSgNLA0wDTQUCCgsAqANOARgAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAMAAQMAAQAAAAABAAMAAAEAAPwIAAAAAAAAAAACqQEAAAAHAQQAAAAs+wIAAIcBAAL7AwEATQIDQgAAAAAOAhoA+wUCAE0EBbwBAAAAUgUAAJ8EAgL7BgIATQUG3wIAAADxBAIABQAAAKkDAAGpAwEAgQEDBAMAAABvBAMApAIFAAAAQECfAgMBTQMBoAYAAACBAQMEBwAAAG8EBwCkAgUAAABAQJ8CAwGpAgAAMAIBoAYAAABNAgFPCAAAAEcCBQAAAAAA+wIDAE0DAU8IAAAAnwICAYIAAQAJAzcDCwNLA08DMwQAAEBAA00DUANMAMcDUQEYAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAADAAACAAAAAQAAAALIAQAAAAgCBAAAADL7AwAAhwIAA/sEAQBNAwRCAAAAAA4DJAD7BgIATQUGvAEAAABSBgAAnwUCAvsHAgBNBgffAgAAAPEFAgAGAAAAqQQAAakEAQCBAQQEAwAAAG8FAwCkAwUAAABAQJ8DAwH7BgIATQUGvAEAAABSBgEAnwUCAvsHAgBNBgeXBgAAAPEFAgAGAAAAqQQAAakEAQCBAQQEBwAAAG8FBwCkAwUAAABAQJ8DAwH7AwMATQQCTwgAAABSBQEAnwMDAjADAk8IAAAAggACAAkDNwMLA0sDTwMzBAAAQEADFwNSA0wA2QNTARgAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAtoBAAAAFAEHAAAAcMYBAADGAgAAxgMAAMYEAADZBQAAEgEE/xIBAv/ZBgEAEgIAABICAQASAgIAEgIDABIBA/8SAQT/EgEC/9kHAgASAAYA2QgDABICAgASAAYA2QQEABICAAASAgEAEgICABICBAASAAAAEgEB/xIBBP/ZCQUAEgAIANkKBgASAAAAEgEE/xIBAv8SAgUAEgAGANkLBwASAAYA2QMIABICAAASAgEAEgICABIBBP8SAQL/EgIEABIAAAASAQH/EgAIABICBQASAAYA2QwJABICAAASAgEAEgAAABICAgDZDQoAEgAIANkOCwASAgUAEgAAABIABgDZDwwAEgAGANkCDQASAgAAEgIBABIAAAASAgIAEgIEABIADAASAQH/EgAIABICBQASAAYA2RAOABICAAASAgIAEgAAABICBgASAQL/2REPABICBgASAgAAEgICABIBBP/ZEhAAEgIGABICAAASAgIAEgED/+ITCQAwEBMdAAAAADARE/IBAAAAMBITOwIAAAAwDBOjAwAAADACE74EAAAAMAQTDAUAAAAwAxP+BgAAADAHE1IHAAAAMAgTdQgAAABSARMAwQEAAIIBAgAKA04DUQNTA0IDSAMsAzsDFgMhBQkAAQIDBAUGBwgRAAECAwQFBgcICQoLDA0ODxAZVAEFAAEBAQgAACEAAAAAAAAASQAEAAARAAAAAAAAAB8ACABPAAAAEwASAAAAAAAAAAAAAAA5AAAAADAACAAAAAsAC1QAAAAAAAAAAAAxAAAAAAAfAAAAABIAAAAADAEAAQABjwIAAQABAAEAAQABAAADABoAAACxAAAArAAAAHEAAAAACwAAAQIAUqMAAACkAAEAAAAAQKQDAwAAACBATQIDJAQAAABNAQIRBQAAAJ8AAgKkAQEAAAAAQKQEAwAAACBATQMEJAQAAABNAgN6BgAAAJ8BAgKkAgEAAAAAQKQFAwAAACBATQQFJAQAAABNAwT8BwAAAJ8CAgKkAwEAAAAAQKQHAwAAACBATQYHJAQAAABNBQbUCAAAAE0EBc4JAAAAnwMCAqQEAQAAAABApAcDAAAAIEBNBgckBAAAAE0FBpMKAAAAnwQCAqQFAQAAAABApAgDAAAAIEBNBwgkBAAAAE0GB/ILAAAAnwUCAqQHAQAAAABApAoDAAAAIEBNCQokBAAAAE0ICYwMAAAAnwcCAk0GB18NAAAAnwYBAk0HBFEOAAAAbwgPAJ8HAgLACBAAEgAGABIABQASAAAAEgACABIAAQASAAMAEgAHAIIIAgARA1UEAAAAQANWBAAAIEADVwNYA1kDWgNbA1wDXQNeA18DYANhA2IGEQERAQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADcAQAAABIRrh8g3gBN1SNqdbQ8f8ZnRA2qNMnYR/nZJKQ3xk8wPmD8aFb7ElK3

-- Decompiled by Krnl

local v_u_1 = require(script.Parent.Type)
local v_u_2 = require(script.Parent.ElementKind)
local v_u_3 = require(script.Parent.ElementUtils)
local v_u_4 = require(script.Parent.PropMarkers.Children)
local v5 = require(script.Parent.Symbol)
local v_u_6 = require(script.Parent.internalAssert)
local v_u_7 = require(script.Parent.GlobalConfig).get()
local v_u_8 = v5.named("InternalData")
return function(p_u_9)
	-- upvalues: (copy) v_u_7, (copy) v_u_6, (copy) v_u_1, (copy) v_u_3, (copy) v_u_2, (copy) v_u_4, (copy) v_u_8
	local v_u_10 = nil
	local v_u_11 = nil
	local v_u_12 = nil
	local v_u_13 = nil
	local function v_u_27(p14, p15, p16)
		-- upvalues: (ref) v_u_7, (ref) v_u_6, (ref) v_u_1, (ref) v_u_3, (ref) v_u_12, (ref) v_u_13, (ref) v_u_11
		if v_u_7.internalTypeChecks then
			v_u_6(v_u_1.of(p14) == v_u_1.VirtualNode, "Expected arg #1 to be of type VirtualNode")
		end
		p14.updateChildrenCount = p14.updateChildrenCount + 1
		local v17 = p14.updateChildrenCount
		local v18 = {}
		for v19, v20 in pairs(p14.children) do
			local v21 = v_u_12(v20, (v_u_3.getElementByKey(p16, v19)))
			if p14.updateChildrenCount ~= v17 then
				if v21 and v21 ~= p14.children[v19] then
					v_u_13(v21)
				end
				return
			end
			if v21 == nil then
				v18[v19] = true
			else
				p14.children[v19] = v21
			end
		end
		for v22 in pairs(v18) do
			p14.children[v22] = nil
		end
		for v23, v24 in v_u_3.iterateElements(p16) do
			local v25
			if v23 == v_u_3.UseParentKey then
				v25 = p14.hostKey
			else
				v25 = v23
			end
			if p14.children[v23] == nil then
				local v26 = v_u_11(v24, p15, v25, p14.context, p14.legacyContext)
				if p14.updateChildrenCount ~= v17 then
					if v26 then
						v_u_13(v26)
					end
					return
				end
				if v26 ~= nil then
					v26.depth = p14.depth + 1
					v26.parent = p14
					p14.children[v23] = v26
				end
			end
		end
	end
	local function v_u_31(p28, p29, p30)
		-- upvalues: (ref) v_u_1, (copy) v_u_27
		if v_u_1.of(p30) == v_u_1.Element or (p30 == nil or typeof(p30) == "boolean") then
			v_u_27(p28, p29, p30)
		else
			error(("%s\n%s"):format("Component returned invalid children:", p28.currentElement.source or "<enable element tracebacks>"), 0)
		end
	end
	v_u_13 = function(p32)
		-- upvalues: (ref) v_u_7, (ref) v_u_6, (ref) v_u_1, (ref) v_u_2, (copy) p_u_9, (ref) v_u_10, (ref) v_u_13
		if v_u_7.internalTypeChecks then
			v_u_6(v_u_1.of(p32) == v_u_1.VirtualNode, "Expected arg #1 to be of type VirtualNode")
		end
		p32.wasUnmounted = true
		local v33 = v_u_2.of(p32.currentElement)
		if v33 == v_u_2.Host then
			p_u_9.unmountHostNode(v_u_10, p32)
			return
		elseif v33 == v_u_2.Function then
			for _, v34 in pairs(p32.children) do
				v_u_13(v34)
			end
			return
		elseif v33 == v_u_2.Stateful then
			p32.instance:__unmount()
			return
		elseif v33 == v_u_2.Portal then
			for _, v35 in pairs(p32.children) do
				v_u_13(v35)
			end
			return
		elseif v33 == v_u_2.Fragment then
			for _, v36 in pairs(p32.children) do
				v_u_13(v36)
			end
		else
			error(("Unknown ElementKind %q"):format((tostring(v33))), 2)
		end
	end
	v_u_12 = function(p37, p38, p39)
		-- upvalues: (ref) v_u_7, (ref) v_u_6, (ref) v_u_1, (ref) v_u_13, (ref) v_u_11, (ref) v_u_2, (copy) p_u_9, (ref) v_u_10, (copy) v_u_31, (ref) v_u_4, (copy) v_u_27
		if v_u_7.internalTypeChecks then
			v_u_6(v_u_1.of(p37) == v_u_1.VirtualNode, "Expected arg #1 to be of type VirtualNode")
		end
		if v_u_7.typeChecks then
			local v40 = (v_u_1.of(p38) == v_u_1.Element or typeof(p38) == "boolean") and true or p38 == nil
			assert(v40, "Expected arg #2 to be of type Element, boolean, or nil")
		end
		if p37.currentElement == p38 and p39 == nil then
			return p37
		end
		if typeof(p38) == "boolean" or p38 == nil then
			v_u_13(p37)
			return nil
		end
		if p37.currentElement.component == p38.component then
			local v41 = v_u_2.of(p38)
			local v42 = true
			if v41 == v_u_2.Host then
				p37 = p_u_9.updateHostNode(v_u_10, p37, p38)
			elseif v41 == v_u_2.Function then
				local v43 = p38.component(p38.props)
				v_u_31(p37, p37.hostParent, v43)
			elseif v41 == v_u_2.Stateful then
				v42 = p37.instance:__update(p38, p39)
			elseif v41 == v_u_2.Portal then
				local v44 = p37.currentElement.props.target
				local v45 = p38.props.target
				local v46 = p_u_9.isHostObject(v45)
				assert(v46, "Expected target to be host object")
				if v45 == v44 then
					v_u_27(p37, v45, p38.props[v_u_4])
				else
					local v47 = p37.hostParent
					local v48 = p37.hostKey
					local v49 = p37.depth
					local v50 = p37.parent
					local v51 = p37.originalContext or p37.context
					local v52 = p37.parentLegacyContext
					if not p37.wasUnmounted then
						v_u_13(p37)
					end
					p37 = v_u_11(p38, v47, v48, v51, v52)
					if p37 ~= nil then
						p37.depth = v49
						p37.parent = v50
					end
				end
			elseif v41 == v_u_2.Fragment then
				v_u_27(p37, p37.hostParent, p38.elements)
			else
				error(("Unknown ElementKind %q"):format((tostring(v41))), 2)
			end
			if not v42 then
				return p37
			end
			p37.currentElement = p38
			return p37
		end
		local v53 = p37.hostParent
		local v54 = p37.hostKey
		local v55 = p37.depth
		local v56 = p37.parent
		local v57 = p37.originalContext or p37.context
		local v58 = p37.parentLegacyContext
		if not p37.wasUnmounted then
			v_u_13(p37)
		end
		local v59 = v_u_11(p38, v53, v54, v57, v58)
		if v59 ~= nil then
			v59.depth = v55
			v59.parent = v56
		end
		return v59
	end
	local function v_u_67(p60, p61, p62, p63, p64)
		-- upvalues: (ref) v_u_7, (ref) v_u_6, (copy) p_u_9, (ref) v_u_1
		if v_u_7.internalTypeChecks then
			v_u_6(p_u_9.isHostObject(p61) or p61 == nil, "Expected arg #2 to be a host object")
			v_u_6(typeof(p63) == "table" and true or p63 == nil, "Expected arg #4 to be of type table or nil")
			v_u_6(typeof(p64) == "table" and true or p64 == nil, "Expected arg #5 to be of type table or nil")
		end
		if v_u_7.typeChecks then
			local v65 = p62 ~= nil
			assert(v65, "Expected arg #3 to be non-nil")
			local v66 = v_u_1.of(p60) == v_u_1.Element and true or typeof(p60) == "boolean"
			assert(v66, "Expected arg #1 to be of type Element or boolean")
		end
		return {
			[v_u_1] = v_u_1.VirtualNode,
			["currentElement"] = p60,
			["depth"] = 1,
			["parent"] = nil,
			["children"] = {},
			["hostParent"] = p61,
			["hostKey"] = p62,
			["updateChildrenCount"] = 0,
			["wasUnmounted"] = false,
			["legacyContext"] = p64,
			["parentLegacyContext"] = p64,
			["context"] = p63 or {},
			["originalContext"] = nil
		}
	end
	v_u_11 = function(p68, p69, p70, p71, p72)
		-- upvalues: (ref) v_u_7, (ref) v_u_6, (copy) p_u_9, (ref) v_u_1, (ref) v_u_2, (copy) v_u_67, (ref) v_u_10, (copy) v_u_31, (ref) v_u_4, (copy) v_u_27
		if v_u_7.internalTypeChecks then
			v_u_6(p_u_9.isHostObject(p69) or p69 == nil, "Expected arg #2 to be a host object")
			v_u_6(typeof(p72) == "table" and true or p72 == nil, "Expected arg #5 to be of type table or nil")
		end
		if v_u_7.typeChecks then
			local v73 = p70 ~= nil
			assert(v73, "Expected arg #3 to be non-nil")
			local v74 = v_u_1.of(p68) == v_u_1.Element and true or typeof(p68) == "boolean"
			assert(v74, "Expected arg #1 to be of type Element or boolean")
		end
		if typeof(p68) == "boolean" then
			return nil
		end
		local v75 = v_u_2.of(p68)
		local v76 = v_u_67(p68, p69, p70, p71, p72)
		if v75 == v_u_2.Host then
			p_u_9.mountHostNode(v_u_10, v76)
			return v76
		end
		if v75 == v_u_2.Function then
			local v77 = v76.currentElement
			local v78 = v77.component(v77.props)
			v_u_31(v76, v76.hostParent, v78)
			return v76
		end
		if v75 == v_u_2.Stateful then
			p68.component:__mount(v_u_10, v76)
			return v76
		end
		if v75 ~= v_u_2.Portal then
			if v75 ~= v_u_2.Fragment then
				error(("Unknown ElementKind %q"):format((tostring(v75))), 2)
				return v76
			end
			local v79 = v76.currentElement.elements
			v_u_27(v76, v76.hostParent, v79)
			return v76
		end
		local v80 = v76.currentElement
		local v81 = v80.props.target
		local v82 = v80.props[v_u_4]
		local v83 = p_u_9.isHostObject(v81)
		assert(v83, "Expected target to be host object")
		v_u_27(v76, v81, v82)
		return v76
	end
	v_u_10 = {
		["mountVirtualTree"] = function(p84, p85, p86)
			-- upvalues: (ref) v_u_7, (ref) v_u_1, (copy) p_u_9, (ref) v_u_8, (ref) v_u_11
			if v_u_7.typeChecks then
				local v87 = v_u_1.of(p84) == v_u_1.Element
				assert(v87, "Expected arg #1 to be of type Element")
				local v88 = p_u_9.isHostObject(p85) or p85 == nil
				assert(v88, "Expected arg #2 to be a host object")
			end
			local v89 = p86 == nil and "RoactTree" or p86
			local v90 = {
				[v_u_1] = v_u_1.VirtualTree,
				[v_u_8] = {
					["rootNode"] = nil,
					["mounted"] = true
				}
			}
			v90[v_u_8].rootNode = v_u_11(p84, p85, v89)
			return v90
		end,
		["unmountVirtualTree"] = function(p91)
			-- upvalues: (ref) v_u_8, (ref) v_u_7, (ref) v_u_1, (ref) v_u_13
			local v92 = p91[v_u_8]
			if v_u_7.typeChecks then
				local v93 = v_u_1.of(p91) == v_u_1.VirtualTree
				assert(v93, "Expected arg #1 to be a Roact handle")
				local v94 = v92.mounted
				assert(v94, "Cannot unmounted a Roact tree that has already been unmounted")
			end
			v92.mounted = false
			if v92.rootNode ~= nil then
				v_u_13(v92.rootNode)
			end
		end,
		["updateVirtualTree"] = function(p95, p96)
			-- upvalues: (ref) v_u_8, (ref) v_u_7, (ref) v_u_1, (ref) v_u_12
			local v97 = p95[v_u_8]
			if v_u_7.typeChecks then
				local v98 = v_u_1.of(p95) == v_u_1.VirtualTree
				assert(v98, "Expected arg #1 to be a Roact handle")
				local v99 = v_u_1.of(p96) == v_u_1.Element
				assert(v99, "Expected arg #2 to be a Roact Element")
			end
			v97.rootNode = v_u_12(v97.rootNode, p96)
			return p95
		end,
		["createVirtualNode"] = v_u_67,
		["mountVirtualNode"] = v_u_11,
		["unmountVirtualNode"] = v_u_13,
		["updateVirtualNode"] = v_u_12,
		["updateVirtualNodeWithChildren"] = function(p100, p101, p102)
			-- upvalues: (copy) v_u_27
			v_u_27(p100, p101, p102)
		end,
		["updateVirtualNodeWithRenderResult"] = v_u_31
	}
	return v_u_10
end
