-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMkCVRleHRMYWJlbA9pdGVyYXRlRWxlbWVudHMGZXhwZWN0AnRvBWVxdWFsDFVzZVBhcmVudEtleQFhAWIGdHlwZW9mBnN0cmluZwJvZgdFbGVtZW50BXRocm93Aml0JnNob3VsZCBpdGVyYXRlIG9uY2UgZm9yIGEgc2luZ2xlIGNoaWxkGnNob3VsZCBpdGVyYXRlIG92ZXIgdGFibGVzMnNob3VsZCByZXR1cm4gYSB6ZXJvLWVsZW1lbnQgaXRlcmF0b3IgZm9yIGJvb2xlYW5zLXNob3VsZCByZXR1cm4gYSB6ZXJvLWVsZW1lbnQgaXRlcmF0b3IgZm9yIG5pbCZzaG91bGQgdGhyb3cgaWYgZ2l2ZW4gYW4gaWxsZWdhbCB2YWx1ZQ9nZXRFbGVtZW50QnlLZXkEdGVzdDRzaG91bGQgcmV0dXJuIHRoZSBlbGVtZW50IGlmIHRoZSBrZXkgaXMgVXNlUGFyZW50S2V5MHNob3VsZCByZXR1cm4gbmlsIGlmIHRoZSBrZXkgaXMgbm90IFVzZVBhcmVudEtleR5zaG91bGQgcmV0dXJuIG5pbCBmb3IgYm9vbGVhbnMZc2hvdWxkIHJldHVybiBuaWwgZm9yIG5pbAhkZXNjcmliZQ9zaW5nbGUgZWxlbWVudHM0c2hvdWxkIHJldHVybiB0aGUgY29ycmVzcG9uZGluZyBlbGVtZW50IGZyb20gYSB0YWJsZStzaG91bGQgcmV0dXJuIG5pbCBpZiB0aGUga2V5IGRvZXMgbm90IGV4aXN0B3JlcXVpcmUGc2NyaXB0BlBhcmVudAxFbGVtZW50VXRpbHMNY3JlYXRlRWxlbWVudA5jcmVhdGVGcmFnbWVudARUeXBlABEIAAIAAAAu+wAAAG8BAACfAAIC+wIBAE0BAlIBAAAAUgIAAJ8BAgJSAgEAnwIBA6QGAwAAACBAUgcCAJ8GAgJNBQaSBAAAAE0EBXsFAAAA+wYBAE0FBs0GAAAAnwQCAaQGAwAAACBAUgcDAJ8GAgJNBQaSBAAAAE0EBXsFAAAAUgUAAJ8EAgFSBAEAnwQBAlICBACkBgMAAAAgQFIHAgCfBgICTQUGkgQAAABNBAV7BQAAAMYFAACfBAIBggABAAcDAQMCAwMEAAAgQAMEAwUDBgAIAAEYAAAAAQAAAAABAAIAAAAAAAAAAAAAAAEAAAAAAAAAAAACAAABAAAAAAAAAAAAAQkAAAAADQADAAAAWeIAAgD7AQAAbwIDAJ8BAgIwAQCAAAAAAPsBAABvAgMAnwECAjABAIMBAAAA/wEAAAAAAACMAgAA+wQBAE0DBFIEAAAAUgQAAJ8DAgRkAyAApAoGAAAAUEC7LAYDUgwGAKQLCAAAAHBAnwsCAp8KAgJNCQqSCQAAAE0ICXsKAAAAbwkLAJ8IAgGkCgYAAABQQPsMAgBNCwy8DAAAAFIMBwCfCwIAnwoAAk0JCpIJAAAATQgJewoAAAD7CgIATQkKlw0AAACfCAIBagYBB5UCAg5uA9//AgAAAKQFBgAAAFBAUgYCAJ8FAgJNBAWSCQAAAE0DBHsKAAAAjAQCAJ8DAgGkBQYAAABQQE0HAIAAAAAAhwYBB58FAgJNBAWSCQAAAE0DBHsKAAAAbwQAAJ8DAgGkBQYAAABQQE0HAIMBAAAAhwYBB58FAgJNBAWSCQAAAE0DBHsKAAAAbwQBAJ8DAgGCAAEADwMHAwgFAgABAwEDAgMDBAAAUEADCQQAAHBAAwQDBQMKAwsDDAIAAAAAAADwPwAUAAEYAAEAAAAAAQAAAAADAAECAAAAAAABAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAfwABwAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEVAAAAAAUAAQAAABH7AQAATQABUgAAAACpAQAAnwACAqQDAgAAABBAUgQAAJ8EAQCfAwACTQIDkgMAAABNAQJ7BAAAAMYCAACfAQIBggABAAUDAgMDBAAAEEADBAMFACkAARgAAAAAAAEAAAAAAAAAAAAAASoAAAAABQABAAAAEfsBAABNAAFSAAAAAMYBAACfAAICpAMCAAAAEEBSBAAAnwQBAJ8DAAJNAgOSAwAAAE0BAnsEAAAAxgIAAJ8BAgGCAAEABQMCAwMEAAAQQAMEAwUALgABGAAAAAAAAQAAAAAAAAAAAAABLwAAAAACAAEAAAAG+wEAAE0AAVIAAAAAjAEBAJ8AAgGCAAEAAQMCADQAARgAAAAAAAE1AAAAAAQAAQAAAAukAgEAAAAAQNkDAAASAgAAnwICAk0BApICAAAATQAB2wMAAACfAAEBggABAAQDAwQAAABAAwQDDQEEMwABGAAAAAAAAgAAAAABNAAAAAADAAMAAAAipAABAAAAAEBvAQIA2QIAABICAAASAgEAnwADAaQAAQAAAABAbwEDANkCAQASAgAAEgIBABICAgCfAAMBpAABAAAAAEBvAQQA2QICABICAQCfAAMBpAABAAAAAEBvAQUA2QIDABICAQCfAAMBpAABAAAAAEBvAQYA2QIEABICAQCfAAMBggABAAcDDgQAAABAAw8DEAMRAxIDEwUAAQIDBQcAARgAAAAAAAAADAAAAAAAAAAVAAAAAAAFAAAAAAAFAAAAAAAFCAAAAAAGAAEAAAAQpAIBAAAAAED7BAAATQMEaAIAAACpBAEAbwUDAJ8DAwCfAgACTQECkgQAAABNAAF7BQAAAMYBAACfAAIBggABAAYDAwQAAABAAxQDFQMEAwUAOwABGAAAAAAAAAAAAAAAAAAAAAE8AAAAAAYAAQAAABCkAgEAAAAAQPsEAABNAwRoAgAAAMYEAABvBQMAnwMDAJ8CAAJNAQKSBAAAAE0AAXsFAAAAxgEAAJ8AAgGCAAEABgMDBAAAAEADFAMVAwQDBQA/AAEYAAAAAAAAAAAAAAAAAAAAAUAAAAAABwACAAAAEqQCAQAAAABA+wQAAE0DBGgCAAAA+wQBAPsGAABNBQbNAwAAAJ8DAwCfAgACTQECkgQAAABNAAF7BQAAAPsBAQCfAAIBggABAAYDAwQAAABAAxQDBgMEAwUARgABGAAAAAAAAAAAAAAAAAAAAAAAAUcAAAAABgACAAAAEKQCAQAAAABA+wQAAE0DBGgCAAAA+wQBAG8FAwCfAwMAnwIAAk0BApIEAAAATQABewUAAADGAQAAnwACAYIAAQAGAwMEAAAAQAMUAxUDBAMFAEoAARgAAAAAAAAAAAAAAAAAAAABSwAAAAAEAAIAAAAS+wAAAG8BAACfAAICpAECAAAAEEBvAgMA2QMAABICAQASAAAAnwEDAaQBAgAAABBAbwIEANkDAQASAgEAEgAAAJ8BAwGCAAEABQMBAw4EAAAQQAMWAxcCCQpDAAEYAAAAAgAAAAAAAAQAAAAAAAADRAAAAAAHAAIAAAAs4gACAPsBAABvAgMAnwECAjABAIAAAAAA+wEAAG8CAwCfAQICMAEAgwEAAACkAwUAAABAQPsFAQBNBAVoBgAAAFIFAABvBgAAnwQDAJ8DAAJNAgOSBwAAAE0BAnsIAAAATQIAgAAAAACfAQIBpAMFAAAAQED7BQEATQQFaAYAAABSBQAAbwYBAJ8EAwCfAwACTQIDkgcAAABNAQJ7CAAAAE0CAIMBAAAAnwECAYIAAQAJAwcDCAUCAAEDAQMDBAAAQEADFAMEAwUATwABGAABAAAAAAEAAAAAAwAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABUAAAAAAHAAIAAAAU+wAAAP8BAAAAAAAAnwACAqQDAQAAAABA+wUBAE0EBWgCAAAAUgUAAG8GAwCfBAMAnwMAAk0CA5IEAAAATQECewUAAADGAgAAnwECAYIAAQAGAwMEAAAAQAMUAwcDBAMFAFkAARgAAAAAAgAAAAAAAAAAAAAAAAAAAVoAAAAAAwADAAAAIqQAAQAAAABAbwECANkCAAASAgAAnwADAaQAAQAAAABAbwEDANkCAQASAgAAnwADAaQABQAAAEBAbwEGANkCAgASAgEAEgIAAJ8AAwGkAAEAAAAAQG8BBwDZAgMAEgIBABICAACfAAMBpAABAAAAAEBvAQgA2QIEABICAgASAgAAnwADAYIAAQAJAw4EAAAAQAMYAxkDGgQAAEBAAxsDHAMdBQcICwwNOgABGAAAAAAAAAQAAAAAAAQAAAAAAAAMAAAAAAAACgAAAAAAAAU7AAAAAAcAAAAAADWkAAEAAAAAQKQDAwAAACBATQIDJAQAAABNAQL8BQAAAJ8AAgKkAQEAAAAAQKQEAwAAACBATQMEJAQAAABNAgPKBgAAAJ8BAgKkAgEAAAAAQKQFAwAAACBATQQFJAQAAABNAwQ2BwAAAJ8CAgKkAwEAAAAAQKQGAwAAACBATQUGJAQAAABNBAURCAAAAJ8DAgKkBAoAAACQQG8FCwDZBgAAEgABABIAAAASAAMAnwQDAaQECgAAAJBAbwUMANkGAQASAAAAEgABABIAAgCfBAMBggABAA0DHgQAAABAAx8EAAAgQAMgAyEDIgMjAyQDGgQAAJBAAwIDFAIGDgEAARgAAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAAACAAAAAAAAADMAAAAAAAAAJQIAAAAAAQAAAQIAA6MAAADAAAAAggACAAEGDwEPAQABGAAAAAEAAAAAEJ9GdUvOxk7crYIf3xb6ngjPJnrCMuWbhYg2tsRnqv+VPfhNGmayEfg=

-- Decompiled by Krnl

return function()
	local v_u_1 = require(script.Parent.ElementUtils)
	local v_u_2 = require(script.Parent.createElement)
	local v_u_3 = require(script.Parent.createFragment)
	local v_u_4 = require(script.Parent.Type)
	describe("iterateElements", function()
		-- upvalues: (copy) v_u_2, (copy) v_u_1, (copy) v_u_4
		it("should iterate once for a single child", function()
			-- upvalues: (ref) v_u_2, (ref) v_u_1
			local v5 = v_u_2("TextLabel")
			local v6 = v_u_1.iterateElements(v5)
			local v7, v8 = v6()
			expect(v7).to.equal(v_u_1.UseParentKey)
			expect(v8).to.equal(v5)
			local v9 = v6()
			expect(v9).to.equal(nil)
		end)
		it("should iterate over tables", function()
			-- upvalues: (ref) v_u_2, (ref) v_u_1, (ref) v_u_4
			local v10 = {
				["a"] = v_u_2("TextLabel"),
				["b"] = v_u_2("TextLabel")
			}
			local v11 = {}
			local v12 = 0
			for v13, v14 in v_u_1.iterateElements(v10) do
				expect((typeof(v13))).to.equal("string")
				expect(v_u_4.of(v14)).to.equal(v_u_4.Element)
				v11[v14] = v13
				v12 = v12 + 1
			end
			expect(v12).to.equal(2)
			expect(v11[v10.a]).to.equal("a")
			expect(v11[v10.b]).to.equal("b")
		end)
		it("should return a zero-element iterator for booleans", function()
			-- upvalues: (ref) v_u_1
			local v15 = v_u_1.iterateElements(false)
			expect(v15()).to.equal(nil)
		end)
		it("should return a zero-element iterator for nil", function()
			-- upvalues: (ref) v_u_1
			local v16 = v_u_1.iterateElements(nil)
			expect(v16()).to.equal(nil)
		end)
		it("should throw if given an illegal value", function()
			-- upvalues: (ref) v_u_1
			expect(function()
				-- upvalues: (ref) v_u_1
				v_u_1.iterateElements(1)
			end).to.throw()
		end)
	end)
	describe("getElementByKey", function()
		-- upvalues: (copy) v_u_1, (copy) v_u_2, (copy) v_u_3
		it("should return nil for booleans", function()
			-- upvalues: (ref) v_u_1
			expect(v_u_1.getElementByKey(true, "test")).to.equal(nil)
		end)
		it("should return nil for nil", function()
			-- upvalues: (ref) v_u_1
			expect(v_u_1.getElementByKey(nil, "test")).to.equal(nil)
		end)
		describe("single elements", function()
			-- upvalues: (ref) v_u_2, (ref) v_u_1
			local v_u_17 = v_u_2("TextLabel")
			it("should return the element if the key is UseParentKey", function()
				-- upvalues: (ref) v_u_1, (copy) v_u_17
				expect(v_u_1.getElementByKey(v_u_17, v_u_1.UseParentKey)).to.equal(v_u_17)
			end)
			it("should return nil if the key is not UseParentKey", function()
				-- upvalues: (ref) v_u_1, (copy) v_u_17
				expect(v_u_1.getElementByKey(v_u_17, "test")).to.equal(nil)
			end)
		end)
		it("should return the corresponding element from a table", function()
			-- upvalues: (ref) v_u_2, (ref) v_u_1
			local v18 = {
				["a"] = v_u_2("TextLabel"),
				["b"] = v_u_2("TextLabel")
			}
			expect(v_u_1.getElementByKey(v18, "a")).to.equal(v18.a)
			expect(v_u_1.getElementByKey(v18, "b")).to.equal(v18.b)
		end)
		it("should return nil if the key does not exist", function()
			-- upvalues: (ref) v_u_3, (ref) v_u_1
			local v19 = v_u_3({})
			expect(v_u_1.getElementByKey(v19, "a")).to.equal(nil)
		end)
	end)
end
