-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMMBmV4cGVjdAJ0bwJiZQJvawNzZXQDZ2V0B3JlcXVpcmUGc2NyaXB0BlBhcmVudAxHbG9iYWxDb25maWcCaXQfc2hvdWxkIGhhdmUgdGhlIGNvcnJlY3QgbWV0aG9kcwADBgABAAAAJqQDAQAAAABA+wQAAJ8DAgJNAgOSAgAAAE0BAswDAAAATQABEAQAAACfAAEBpAMBAAAAAED7BQAATQQFUwUAAACfAwICTQIDkgIAAABNAQLMAwAAAE0AARAEAAAAnwABAaQDAQAAAABA+wUAAE0EBV8GAAAAnwMCAk0CA5ICAAAATQECzAMAAABNAAEQBAAAAJ8AAQGCAAEABwMBBAAAAEADAgMDAwQDBQMGAAQAARgAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAQUAAAAABAAAAAAAEKQAAQAAAABApAMDAAAAIEBNAgMkBAAAAE0BAowFAAAAnwACAqQBBwAAAGBAbwIIANkDAAASAAAAnwEDAYIAAQAJAwcEAAAAQAMIBAAAIEADCQMKAwsEAABgQAMMAQABAAEYAAAAAAAAAAAAAgAAAAAABQIAAAAAAQAAAQIAA6MAAADAAAAAggACAAEGAQEBAQABGAAAAAEAAAAAApHRs4U+IrkWoxXZEaJaU4H95cy/l3x2zKzU21X3w0UMmS/q0qgtfgg=

-- Decompiled by Krnl

return function()
	local v_u_1 = require(script.Parent.GlobalConfig)
	it("should have the correct methods", function()
		-- upvalues: (copy) v_u_1
		expect(v_u_1).to.be.ok()
		expect(v_u_1.set).to.be.ok()
		expect(v_u_1.get).to.be.ok()
	end)
end
