-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMdC015Q29tcG9uZW50BmV4dGVuZAZleHBlY3QCdG8CYmUCb2sKd2lsbFVwZGF0ZQZyZW5kZXIFdmFsdWUFc3RhdGUEaW5pdAhzZXRTdGF0ZQhkaWRNb3VudAlQdXJlQ2hpbGQNUHVyZUNvbnRhaW5lchBtb3VudFZpcnR1YWxUcmVlElB1cmVDb21wb25lbnQgVHJlZQVlcXVhbBJ1bm1vdW50VmlydHVhbFRyZWUHcmVxdWlyZQZzY3JpcHQGUGFyZW50DWNyZWF0ZUVsZW1lbnQMTm9vcFJlbmRlcmVyEGNyZWF0ZVJlY29uY2lsZXINUHVyZUNvbXBvbmVudAJpdBRzaG91bGQgYmUgZXh0ZW5kYWJsZStzaG91bGQgc2tpcCB1cGRhdGVzIGZvciBzaGFsbG93LWVxdWFsIHByb3BzAAoGAAEAAAAR+wAAAG8CAAC8AACcAQAAAJ8AAwKkBAMAAAAgQFIFAACfBAICTQMEkgQAAABNAgPMBQAAAE0BAhAGAAAAnwEBAYIAAQAHAwEDAgMDBAAAIEADBAMFAwYACgABGAAAAAAAAgAAAAAAAAAAAAABCwAAAAADAQEAAAAE+wIAAJUBAgDeAQAAggABAAECAAAAAAAA8D8AFgcBGAAAAAEXAAAAAAIBAAAAAALGAQAAggECAAAAGggBGAAAGwAAAAADAQAAAAAH4gEBAIwCAAAwAgHMAAAAADABABgCAAAAggABAAMDCQUBAAMKACALARgAAQAA/wADIQAAAAAEAQEAAAAI+wEAAOIDAQAwAAPMAAAAALwBASoCAAAAnwEDAYIAAQADAwkFAQADDAAnAAEYAAABAP8AAAMoAAAAAAIBAQAAAATZAQAAEgAAAN4BAACCAAEAAAEEJg0BGAAAAAUnAAAAAAYBAgAAAAv7AQAA+wIBAOIDAQBNBQAYAgAAAE0EBcwAAAAAMAQDzAAAAACfAQMAggEAAAMDCQUBAAMKAC4IARgAAAABAAAAAAD/AC8AAAAACgADAAAAbowAAADGAQAA+wIAAG8EAAC8AgKcAQAAAJ8CAwLZAwAAEgEA/zADAn0CAAAAwAMDADADAoAEAAAA+wMAAG8FBQC8AwOcAQAAAJ8DAwLABAYAMAQDEwcAAADZBAMAEgEB/zAEA2oIAAAA2QQEABICAQASAAIAMAQDgAQAAAD7BAEAUgUDAJ8EAgL7BgIATQUGHQkAAABSBgQAxgcAAG8ICgCfBQQCpAgMAAAAsEBSCQAAnwgCAk0HCJINAAAATQYHew4AAACMBwAAnwYCAVIGAQCMBwEAnwYCAaQIDAAAALBAUgkAAJ8IAgJNBwiSDQAAAE0GB3sOAAAAjAcBAJ8GAgFSBgEAjAcBAJ8GAgGkCAwAAACwQFIJAACfCAICTQcIkg0AAABNBgd7DgAAAIwHAQCfBgIBUgYBAIwHAgCfBgIBpAgMAAAAsEBSCQAAnwgCAk0HCJINAAAATQYHew4AAACMBwIAnwYCAVIGAQCMBwEAnwYCAaQIDAAAALBAUgkAAJ8IAgJNBwiSDQAAAE0GB3sOAAAAjAcDAJ8GAgH7BwIATQYH8g8AAABSBwUAnwYCAcEAAACCAAEAEAMOAwIDBwYCAwgDDwYDAwsDDQMQAxEDAwQAALBAAwQDEgMTBQECAwUGEAABGAABAgAAAAACAAAABAAABAAAAAACAAAGAAAACAAAAAAGAAABAAAAAAAAAgAAAAAAAAAAAAIAAAIAAAAAAAAAAAACAAACAAAAAAAAAAAAAgAAAgAAAAAAAAAAAAIAAAIAAAAAAAAAAAACAAAAAAEAEQAAAAAIAAAAAAA2pAABAAAAAECkAwMAAAAgQE0CAyQEAAAATQECygUAAACfAAICpAEBAAAAAECkBAMAAAAgQE0DBCQEAAAATQIDagYAAACfAQICpAIBAAAAAECkBQMAAAAgQE0EBSQEAAAATQMEiwcAAACfAgICpAMBAAAAAECkBgMAAAAgQE0FBiQEAAAATQQF+AgAAACfAwICUgQCAFIFAQCfBAICpAUKAAAAkEBvBgsA2QcAABIAAwCfBQMBpAUKAAAAkEBvBgwA2QcBABIAAwASAAAAEgAEAJ8FAwGCAAEADQMUBAAAAEADFQQAACBAAxYDFwMYAxkDGgMbBAAAkEADHAMdAgAHAQABGAAAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAIAAAAAAAAAAAIAAAIAAAAAAAYAAAAAAAAAOwIAAAAAAQAAAQIAA6MAAADAAAAAggACAAEGCAEIAQABGAAAAAEAAAAACVIzvwKeEHzYYPfVllU+/eC/M5Ot2LVCYX/8V+UpcKl9OV4xw/WFO4A=

-- Decompiled by Krnl

return function()
	local v_u_1 = require(script.Parent.createElement)
	local v2 = require(script.Parent.NoopRenderer)
	local v3 = require(script.Parent.createReconciler)
	local v_u_4 = require(script.Parent.PureComponent)
	local v_u_5 = v3(v2)
	it("should be extendable", function()
		-- upvalues: (copy) v_u_4
		local v6 = v_u_4:extend("MyComponent")
		expect(v6).to.be.ok()
	end)
	it("should skip updates for shallow-equal props", function()
		-- upvalues: (copy) v_u_4, (copy) v_u_1, (copy) v_u_5
		local v_u_7 = 0
		local v_u_8 = nil
		local v_u_9 = v_u_4:extend("PureChild")
		function v_u_9.willUpdate(_)
			-- upvalues: (ref) v_u_7
			v_u_7 = v_u_7 + 1
		end
		function v_u_9.render(_)
			return nil
		end
		local v10 = v_u_4:extend("PureContainer")
		function v10.init(p11)
			p11.state = {
				["value"] = 0
			}
		end
		function v10.didMount(p_u_12)
			-- upvalues: (ref) v_u_8
			v_u_8 = function(p13)
				-- upvalues: (copy) p_u_12
				p_u_12:setState({
					["value"] = p13
				})
			end
		end
		function v10.render(p14)
			-- upvalues: (ref) v_u_1, (copy) v_u_9
			return v_u_1(v_u_9, {
				["value"] = p14.state.value
			})
		end
		local v15 = v_u_1(v10)
		local v16 = v_u_5.mountVirtualTree(v15, nil, "PureComponent Tree")
		expect(v_u_7).to.equal(0)
		v_u_8(1)
		expect(v_u_7).to.equal(1)
		v_u_8(1)
		expect(v_u_7).to.equal(1)
		v_u_8(2)
		expect(v_u_7).to.equal(2)
		v_u_8(1)
		expect(v_u_7).to.equal(3)
		v_u_5.unmountVirtualTree(v16)
	end)
end
