-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMQBmV4cGVjdAJvZgJ0bwVlcXVhbAR0ZXN0BXByaW50B0VsZW1lbnQCaXQtc2hvdWxkIHJldHVybiBuaWwgaWYgdGhlIHZhbHVlIGlzIG5vdCBhIHRhYmxlKnNob3VsZCByZXR1cm4gbmlsIGlmIHRoZSB0YWJsZSBoYXMgbm8gdHlwZR9zaG91bGQgcmV0dXJuIHRoZSBhc3NpZ25lZCB0eXBlB3JlcXVpcmUGc2NyaXB0BlBhcmVudARUeXBlCGRlc2NyaWJlAAYFAAEAAAA6pAIBAAAAAED7BAAATQMEvAIAAACMBAEAnwMCAJ8CAAJNAQKSAwAAAE0AAXsEAAAAxgEAAJ8AAgGkAgEAAAAAQPsEAABNAwS8AgAAAKkEAQCfAwIAnwIAAk0BApIDAAAATQABewQAAADGAQAAnwACAaQCAQAAAABA+wQAAE0DBLwCAAAAbwQFAJ8DAgCfAgACTQECkgMAAABNAAF7BAAAAMYBAACfAAIBpAIBAAAAAED7BAAATQMEvAIAAACkBAcAAABgQJ8DAgCfAgACTQECkgMAAABNAAF7BAAAAMYBAACfAAIBggABAAgDAQQAAABAAwIDAwMEAwUDBgQAAGBAAAUAARgAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAABBgAAAAAFAAEAAAAQpAIBAAAAAED7BAAATQMEvAIAAAD/BAAAAAAAAJ8DAgCfAgACTQECkgMAAABNAAF7BAAAAMYBAACfAAIBggABAAUDAQQAAABAAwIDAwMEAAwAARgAAAAAAAAAAAAAAAAAAAABDQAAAAAGAAEAAAAY/wABAAAAAAD7AQAA+wMAAE0CA5cAAAAAagIAAaQDAgAAABBA+wUAAE0EBbwDAAAAUgUAAJ8EAgCfAwACTQIDkgQAAABNAQJ7BQAAAPsDAABNAgOXAAAAAJ8BAgGCAAEABgMHAwEEAAAQQAMCAwMDBAAQAAEYAAABAAAAAAMAAAAAAAAAAAAAAAAAAAABEQAAAAADAAEAAAATpAABAAAAAEBvAQIA2QIAABICAACfAAMBpAABAAAAAEBvAQMA2QIBABICAACfAAMBpAABAAAAAEBvAQQA2QICABICAACfAAMBggABAAUDCAQAAABAAwkDCgMLAwABAgQAARgAAAAAAAAHAAAAAAAEAAAAAAAHBQAAAAAEAAAAAAAQpAABAAAAAECkAwMAAAAgQE0CAyQEAAAATQECEQUAAACfAAICpAEHAAAAYEBvAggA2QMAABIAAACfAQMBggABAAkDDAQAAABAAw0EAAAgQAMOAw8DEAQAAGBAAwIBAwEAARgAAAAAAAAAAAACAAAAAAAUAgAAAAABAAABAgADowAAAMAAAACCAAIAAQYEAQQBAAEYAAAAAQAAAAAF3M99C1xnbeXuCxefS0nDN+j+h5gbjmG7NiYjPo9zIqHpjdcPd35t9g==

-- Decompiled by Krnl

return function()
	local v_u_1 = require(script.Parent.Type)
	describe("of", function()
		-- upvalues: (copy) v_u_1
		it("should return nil if the value is not a table", function()
			-- upvalues: (ref) v_u_1
			expect(v_u_1.of(1)).to.equal(nil)
			expect(v_u_1.of(true)).to.equal(nil)
			expect(v_u_1.of("test")).to.equal(nil)
			expect(v_u_1.of(print)).to.equal(nil)
		end)
		it("should return nil if the table has no type", function()
			-- upvalues: (ref) v_u_1
			expect(v_u_1.of({})).to.equal(nil)
		end)
		it("should return the assigned type", function()
			-- upvalues: (ref) v_u_1
			local v2 = {
				[v_u_1] = v_u_1.Element
			}
			expect(v_u_1.of(v2)).to.equal(v_u_1.Element)
		end)
	end)
end
