-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMLBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZAZFbnVtZXIETk9ORQpDQU5fVU5MT0FEDkhFTFBfQlVTVF9ET09SBGxpc3QEZW51bQABBwAAAQIAIKMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DAKEGAAAATQIDVwcAAACfAQIC/wICAAAAAAD/AwAAAwAAAG8ECABvBQkAbwYKAMUDBAQBAAAAMAMCCwsAAABSAwEATQQCCwsAAACfAwICMAMCvQwAAACCAgIADQMBBAAAAEADAgMDAwQEAABAQAMFAwYDBwMIAwkDCgMLAAEAARgAAQAAAAAAAQAAAAAAAAIAAQAAAAAAAAAAAQAAAAAAAgEAAAAAALaFtmkNnEPHhEHc/WPOpSge2gU/cOE+2OZ8PZfsS46QqztG8l65FbU=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v2 = {
	["list"] = { "NONE", "CAN_UNLOAD", "HELP_BUST_DOOR" }
}
v2.enum = require(v1.Std.Enumer)(v2.list)
return v2
