-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMNBmFzc2VydAhJbnN0YW5jZQNJc0ELdmFsaWRhdGVPYmoYQVJNSU5HX1RFQU1fSURfQVRUUl9OQU1FDEdldEF0dHJpYnV0ZQ9nZXRBcm1pbmdUZWFtSWQMU2V0QXR0cmlidXRlD3NldEFybWluZ1RlYW1JZAdyZXF1aXJlBnNjcmlwdAZQYXJlbnQLVmF1bHRDb25zdHMABAUBAAAAABFHAAIAAAAAgKkCAAGpAgEAuwECAqQBAQAAAABAnwECAW8EAgC8AgD+AwAAAJ8CAwBMAQACpAEBAAAAAECfAQABggABAAQDAQQAAABAAwIDAwAEBAEYAAAAAAAAAAABAAAAAAAAAAEFAAAAAAUBAQAAABdHAAIAAAAAgKkCAAGpAgEAuwECAqQBAQAAAABAnwECAW8EAgC8AgD+AwAAAJ8CAwBMAQACpAEBAAAAAECfAQAB+wQAAE0DBMUEAAAAvAEAEgUAAACfAQMAggEAAAYDAQQAAABAAwIDAwMFAwYACgcBGAAAAAAAAAAAAQAAAAAAAAAGAAAAAAAABQAAAAAGAgEAAAAYRwACAAAAAICpAwABqQMBALsBAwKkAgEAAAAAQJ8CAgFvBQIAvAMA/gMAAACfAwMATAEAAqQCAQAAAABAnwIAAfsFAABNBAXFBAAAAFIFAQC8AgAuBQAAAJ8CBAGCAAEABgMBBAAAAEADAgMDAwUDCAAOCQEYAAAAAAAAAAABAAAAAAAAAAoAAAAAAAABBQAAAAAEAAABAgAWowAAAKQAAQAAAABApAMDAAAAIEBNAgMkBAAAAE0BAtEFAAAAnwACAsABBgD/AgIAAAAAAMADBwASAAAAMAMCPggAAADAAwkAEgAAADADAioKAAAAggICAAsDCgQAAABAAwsEAAAgQAMMAw0GAAYBAwcGAgMJAwABAgEAARgAAQAAAAAAAAAAAgQAAgAAAAQAAAAEAQAAAAADaGuPwZX/TpBar+VVlqFZ0xDLj0HZFTHC4FSJprnM6z5A29fnLEhjGw==

-- Decompiled by Krnl

local v_u_1 = require(script.Parent.VaultConsts)
return {
	["getArmingTeamId"] = function(p2)
		-- upvalues: (copy) v_u_1
		local v3 = p2 ~= nil
		assert(v3)
		assert(p2:IsA("Instance"))
		return p2:GetAttribute(v_u_1.ARMING_TEAM_ID_ATTR_NAME)
	end,
	["setArmingTeamId"] = function(p4, p5)
		-- upvalues: (copy) v_u_1
		local v6 = p4 ~= nil
		assert(v6)
		assert(p4:IsA("Instance"))
		p4:SetAttribute(v_u_1.ARMING_TEAM_ID_ATTR_NAME, p5)
	end
}
