-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNWBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzBkVudW1lcgNrZXkEbmFtZQptYXJrZXJOYW1lB2ltYWdlSWQEQkFOSxBSaXNpbmcgQ2l0eSBCYW5rBEJhbmsFQkFOSzILQ3JhdGVyIEJhbmsFQmFuazIHSkVXRUxSWQ1KZXdlbHJ5IFN0b3JlB0pld2VscnkGTVVTRVVNBk11c2V1bQtQT1dFUl9QTEFOVAtQb3dlciBQbGFudApQb3dlclBsYW50D1RSQUlOX1BBU1NFTkdFUg9QYXNzZW5nZXIgVHJhaW4OVHJhaW5QYXNzZW5nZXILVFJBSU5fQ0FSR08LQ2FyZ28gVHJhaW4KVHJhaW5DYXJnbwpDQVJHT19TSElQCkNhcmdvIFNoaXAJQ2FyZ29TaGlwC0NBUkdPX1BMQU5FC0NhcmdvIFBsYW5lCkNhcmdvUGxhbmUJU1RPUkVfR0FTC0dhcyBTdGF0aW9uA0dhcwtTVE9SRV9ET05VVAtEb251dCBTdG9yZQVEb251dAtNT05FWV9UUlVDSwtNb25leSBUcnVjawpNb25leVRydWNrCkhPTUVfVkFVTFQKSG9tZSBWYXVsdAlIb21lVmF1bHQEVE9NQgRUb21iC0NST1dOX0pFV0VMC0Nyb3duIEpld2VsBkNhc2lubwdNQU5TSU9OB01hbnNpb24HT0lMX1JJRwdPaWwgUmlnBk9pbFJpZwZpcGFpcnMGYXNzZXJ0BXRhYmxlBmluc2VydBpyZXF1aXJlVmFsaWRJbmRleEFuZEZyZWV6ZQtGT0xERVJfTkFNRQxEQVRBX1JPQkJFUlkMTElTVF9ST0JCRVJZDEVOVU1fUk9CQkVSWQtQUkVUVFlfTkFNRRBTVEFUVVNfQVRUUl9OQU1FC0VOVU1fU1RBVFVTG0RJU0FCTEVfQVVUT19PUEVOX0FUVFJfTkFNRQ1JR05PUkVfU1RBVFVTElJPVU5EX01JTl9EVVJBVElPThJST1VORF9NQVhfRFVSQVRJT04pUk9CQkVSWV9TVEFSVEVEX1JPVU5EX1BST1RFQ1RJT05fRFVSQVRJT04ZSU5fQkVUV0VFTl9ST1VORF9EVVJBVElPThNLRVlDQVJEX0RST1BfQ0hBTkNFGVJPQkJFUllfU1RBVEVfRk9MREVSX05BTUUNUm9iYmVyeUZvbGRlcg1Sb2JiZXJ5U3RhdHVzBk9QRU5FRAdTVEFSVEVEBkNMT1NFRBZSb2JiZXJ5RGlzYWJsZUF1dG9PcGVuDFJvYmJlcnlTdGF0ZQABFQAAAQAA9AKjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CAxgHAAAAnwECAqQCBQAAAEBATQQAoQYAAABNAwRXCAAAAJ8CAgL/AwAAEQAAAOIEDQBvBQ4AMAUESgkAAABvBQ8AMAUEWgoAAABvBRAAMAUEwAsAAABvBREAMAUEtgwAAADiBQ0AbwYSADAGBUoJAAAAbwYTADAGBVoKAAAAbwYUADAGBcALAAAAbwYRADAGBbYMAAAA4gYNAG8HFQAwBwZKCQAAAG8HFgAwBwZaCgAAAG8HFwAwBwbACwAAAG8HGAAwBwa2DAAAAOIHDQBvCBkAMAgHSgkAAABvCBoAMAgHWgoAAABvCBoAMAgHwAsAAABvCBsAMAgHtgwAAADiCA0AbwkcADAJCEoJAAAAbwkdADAJCFoKAAAAbwkeADAJCMALAAAAbwkfADAJCLYMAAAA4gkNAG8KIAAwCglKCQAAAG8KIQAwCglaCgAAAG8KIgAwCgnACwAAAG8KIwAwCgm2DAAAAOIKDQBvCyQAMAsKSgkAAABvCyUAMAsKWgoAAABvCyYAMAsKwAsAAABvCycAMAsKtgwAAADiCw0AbwwoADAMC0oJAAAAbwwpADAMC1oKAAAAbwwqADAMC8ALAAAAbwwrADAMC7YMAAAA4gwNAG8NLAAwDQxKCQAAAG8NLQAwDQxaCgAAAG8NLgAwDQzACwAAAG8NLwAwDQy2DAAAAOINDQBvDjAAMA4NSgkAAABvDjEAMA4NWgoAAABvDjIAMA4NwAsAAABvDjMAMA4NtgwAAADiDg0Abw80ADAPDkoJAAAAbw81ADAPDloKAAAAbw82ADAPDsALAAAAbw83ADAPDrYMAAAA4g8NAG8QOAAwEA9KCQAAAG8QOQAwEA9aCgAAAG8QOgAwEA/ACwAAAG8QOwAwEA+2DAAAAOIQDQBvETwAMBEQSgkAAABvET0AMBEQWgoAAABvET4AMBEQwAsAAABvET8AMBEQtgwAAADiEQ0AbxJAADASEUoJAAAAbxJBADASEVoKAAAAbxJBADASEcALAAAAbxJCADASEbYMAAAA4hINAG8TQwAwExJKCQAAAG8TRAAwExJaCgAAAG8TRQAwExLACwAAAG8TRgAwExK2DAAAAOITDQBvFEcAMBQTSgkAAABvFEgAMBQTWgoAAABvFEgAMBQTwAsAAABvFEkAMBQTtgwAAADFAwQRAQAAAOIEDQBvFEoAMBQESgkAAABvFEsAMBQEWgoAAABvFEwAMBQEwAsAAABvFE0AMBQEtgwAAADFAwQCEQAAAP8EAAAAAAAApAVPAAAA4ERSBgMAnwUCBFEFHABNDAlKCQAAAEcMAgAAAACAqQsAAakLAQC7AQsCpApRAAAAAEWfCgIBTQwJWgoAAABHDAIAAAAAgKkLAAGpCwEAuwELAqQKUQAAAABFnwoCAU0MCUoJAAAAnjQEBAwAAABSCwQApApUAABMIYWfCgMBbgXj/wIAAID/BQAAAAAAAP8GAAAAAAAAUgcCAFIIBACfBwICpAhPAAAA4ERSCQMAnwgCBFEICgBNDgxKCQAAAIcNBw5NDgxaCgAAAGoOBQ1NDgxKCQAAAIcNBw5qDAYNbgj1/wIAAIBNCAEAVQAAAOIJZQBvCmYAMAoJplYAAAAwBgn1VwAAADAECYxYAAAAMAcJm1kAAAAwBQmcWgAAAG8KZwAwCgniWwAAAFIKAgD/CwAAAwAAAG8MaABvDWkAbw5qAMULDAQBAAAAnwoCAjAKCV1cAAAAbwprADAKCatdAAAA/woAAAMAAABNCwcDMAAAAE0MB7U0AAAATQ0HaTwAAADFCgsEAQAAADAKCcpeAAAAjAq0ADAKCetfAAAAjAqkATAKCR9gAAAAjArwADAKCbVhAAAAjAoUADAKCW5iAAAAbwpsADAKCcNjAAAAbwptADAKCQZkAAAAnwgCAIIIAABuAwEEAAAAQAMCAwMDBAQAAEBAAwUDBgMHAwgDCQMKAwsFBAkKCwwDDAMNAw4CAABQ3J9M8UEDDwMQAxEDEgMTAxQCAABg9Z9M8UEDFQMWAgAA0AGgTPFBAxcDGAMZAgAAQOufTPFBAxoDGwMcAgAAUMcpM/tBAx0DHgMfAgAAUKApM/tBAyADIQMiAgAAsOUpM/tBAyMDJAMlAgAAEAMqM/tBAyYDJwMoAgAA0DigTPFBAykDKgMrAgAAQDCgTPFBAywDLQMuAgAAkBdA2fZBAy8DMAMxAgAA2F40vAhCAzIDMwIAAHBDaLH5QQM0AzUDNgIAAAiUPz0BQgM3AzgCAABALLcJBkIDOQM6AzsCAABAkzkXDUIDPAQAAOBEAz0EAAAARQM+Az8EAEwhhQNAA0EDQgNDA0QDRQNGA0cDSANJA0oDSwNMA00DTgNPBQ9WV1hZWltcXV5fYGFiY2QDUANRA1IDUwNUA1UCMzMzMzMz4z8DVgABAAEYAAEAAAAAAAEAAAAAAAABAAAAAAAAAwABAQAAAQAAAQAAAQAAAgEAAAEAAAEAAAEAAAIBAAABAAABAAABAAACAQAAAQAAAQAAAQAAAgEAAAEAAAEAAAEAAAIBAAABAAABAAABAAACAQAAAQAAAQAAAQAAAgEAAAEAAAEAAAEAAAIBAAABAAABAAABAAACAQAAAQAAAQAAAQAAAgEAAAEAAAEAAAEAAAIBAAABAAABAAABAAACAQAAAQAAAQAAAQAAAgEAAAEAAAEAAAEAAAIBAAABAAABAAABAAACAQAAAQAAAQAAAQAAAgAAAQAAAQAAAQAAAQAAAAADAAEAAAAAAQAAAAAAAAAAAAEAAAAAAAAAAAABAAAAAAAAAP0ABQABAAEAAAEAAAAAAQAAAAAAAQAAAP4ABQAAAQAAAgABAAEAAQACAAABAAAAAAAAAAAAAAEAAAEAAAAAAAAAAAAAAAIAAAEAAAEAAAMAAAIAAAEAAOsAAQAAAAAACgis3FGbtUM4zMZIKcBmwSxRSPaIg9+kU0qpBnllJWFleeOYhU1leg==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v2 = require(v1.Std.TableUtils)
local v3 = require(v1.Std.Enumer)
local v4 = {
	{
		["key"] = "BANK",
		["name"] = "Rising City Bank",
		["markerName"] = "Bank",
		["imageId"] = 4643749317
	},
	{
		["key"] = "BANK2",
		["name"] = "Crater Bank",
		["markerName"] = "Bank2",
		["imageId"] = 4643749317
	},
	{
		["key"] = "JEWELRY",
		["name"] = "Jewelry Store",
		["markerName"] = "Jewelry",
		["imageId"] = 4643749718
	},
	{
		["key"] = "MUSEUM",
		["name"] = "Museum",
		["markerName"] = "Museum",
		["imageId"] = 4643749917
	},
	{
		["key"] = "POWER_PLANT",
		["name"] = "Power Plant",
		["markerName"] = "PowerPlant",
		["imageId"] = 4643749556
	},
	{
		["key"] = "TRAIN_PASSENGER",
		["name"] = "Passenger Train",
		["markerName"] = "TrainPassenger",
		["imageId"] = 7301405813
	},
	{
		["key"] = "TRAIN_CARGO",
		["name"] = "Cargo Train",
		["markerName"] = "TrainCargo",
		["imageId"] = 7301405189
	},
	{
		["key"] = "CARGO_SHIP",
		["name"] = "Cargo Ship",
		["markerName"] = "CargoShip",
		["imageId"] = 7301406299
	},
	{
		["key"] = "CARGO_PLANE",
		["name"] = "Cargo Plane",
		["markerName"] = "CargoPlane",
		["imageId"] = 7301406769
	},
	{
		["key"] = "STORE_GAS",
		["name"] = "Gas Station",
		["markerName"] = "Gas",
		["imageId"] = 4643750797
	},
	{
		["key"] = "STORE_DONUT",
		["name"] = "Donut Store",
		["markerName"] = "Donut",
		["imageId"] = 4643750660
	},
	{
		["key"] = "MONEY_TRUCK",
		["name"] = "Money Truck",
		["markerName"] = "MoneyTruck",
		["imageId"] = 6133383545
	},
	{
		["key"] = "HOME_VAULT",
		["name"] = "Home Vault",
		["markerName"] = "HomeVault",
		["imageId"] = 13279595483
	},
	{
		["key"] = "TOMB",
		["name"] = "Tomb",
		["markerName"] = "Tomb",
		["imageId"] = 6896911415
	},
	{
		["key"] = "CROWN_JEWEL",
		["name"] = "Crown Jewel",
		["markerName"] = "Casino",
		["imageId"] = 9255252609
	},
	{
		["key"] = "MANSION",
		["name"] = "Mansion",
		["markerName"] = "Mansion",
		["imageId"] = 11831534984
	},
	{
		["key"] = "OIL_RIG",
		["name"] = "Oil Rig",
		["markerName"] = "OilRig",
		["imageId"] = 15617962600
	}
}
local v5 = {}
for _, v6 in ipairs(v4) do
	local v7 = v6.key ~= nil
	assert(v7)
	local v8 = v6.name ~= nil
	assert(v8)
	local v9 = v6.key
	table.insert(v5, v9)
end
local v10 = v3(v5)
local v11 = {}
local v12 = {}
for _, v13 in ipairs(v4) do
	v11[v10[v13.key]] = v13.name
	v12[v10[v13.key]] = v13
end
return v2.requireValidIndexAndFreeze({
	["FOLDER_NAME"] = "RobberyFolder",
	["DATA_ROBBERY"] = v12,
	["LIST_ROBBERY"] = v5,
	["ENUM_ROBBERY"] = v10,
	["PRETTY_NAME"] = v11,
	["STATUS_ATTR_NAME"] = "RobberyStatus",
	["ENUM_STATUS"] = v3({ "OPENED", "STARTED", "CLOSED" }),
	["DISABLE_AUTO_OPEN_ATTR_NAME"] = "RobberyDisableAutoOpen",
	["IGNORE_STATUS"] = { v10.STORE_GAS, v10.STORE_DONUT, v10.HOME_VAULT },
	["ROUND_MIN_DURATION"] = 180,
	["ROUND_MAX_DURATION"] = 420,
	["ROBBERY_STARTED_ROUND_PROTECTION_DURATION"] = 240,
	["IN_BETWEEN_ROUND_DURATION"] = 20,
	["KEYCARD_DROP_CHANCE"] = 0.6,
	["ROBBERY_STATE_FOLDER_NAME"] = "RobberyState"
})
