-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgOxAQVfcGF0aAdEZXN0cm95Cl93YXlwb2ludHMQbG9va0F0Q29uc3RyYWludAhHaXZlVGFzawtQcmltYXJ5UGFydAlnZXRUYXJnZXQIUG9zaXRpb24IVmVsb2NpdHkJTWFnbml0dWRlBFVuaXQaZ2V0VHJhamVjdG9yeUludGVyY2VwdFRpbWUEbWF0aAVjbGFtcBxnZXRFeHRyYXBvbGF0ZVRhcmdldE1vdmVtZW50EGhhc0FsbG93ZWRSZWdpb24NYWxsb3dlZFJlZ2lvbglDYXN0UG9pbnQPZ2V0SG9tZVBvc2l0aW9uBGdvVG8EbW92ZQhodW1hbm9pZBNyYW5kb21Qb2ludE9uQ2lyY2xlBnJhbmRvbQFYAVkHVmVjdG9yMwNuZXcEbWFpZAp0YXJnZXRNYWlkDklzTG9jYWxseU93bmVkEmN1c3RvbVVwZGF0ZVRhcmdldA1nZXRUYXJnZXRUeXBlCURFU1RfVFlQRQNPQkoOUG9zdFNpbXVsYXRpb24HQ29ubmVjdANQT1MJSGVhcnRiZWF0BElETEUFZXZlcnkFZXJyb3IRaW52YWxpZCB0YXJnZVR5cGUMdXBkYXRlVGFyZ2V0B0NoYW5nZWQGbG9va0F0B0VuYWJsZWQKbG9va0F0TWFpZA1nZXRMb29rQXRUeXBlCWdldExvb2tBdAdydW50aW1lDHVwZGF0ZUxvb2tBdA5fY3JlYXRlTmV3UGF0aA9fdXBkYXRlUGF0aGZpbmQERW51bRFIdW1hbm9pZFN0YXRlVHlwZQREZWFkB1J1bm5pbmcHSnVtcGluZwZMYW5kZWQIRnJlZWZhbGwGaXBhaXJzDEdldEVudW1JdGVtcwROb25lD0dldFN0YXRlRW5hYmxlZA9TZXRTdGF0ZUVuYWJsZWQIR2V0U3RhdGULQ2hhbmdlU3RhdGUYX2J1aWxkT2NjbHVzaW9uQmxhY2tsaXN0GkZpbHRlckRlc2NlbmRhbnRzSW5zdGFuY2VzBVZhbHVlAWMBcwtHZXRDaGlsZHJlbgFmBkNGcmFtZRRvYnNlcnZlT25lQ2hpbGROYW1lZAhBZGRQcmlzbQ9vYnNlcnZlQ2hpbGRyZW4MaG9tZVBvc2l0aW9uBnVwZGF0ZQNvYmoSX25leHRXYXlwb2ludEluZGV4EXJlYWNoZWRDb25uZWN0aW9uCV9sYXN0SnVtcApvbldheXBvaW50HHNob3VsZE1vdmVUb05leHRXYXlwb2ludEZ1bmMXTE9PS19BVF9DT05TVFJBSU5UX05BTUUSREVTVF9QT1NfQVRUUl9OQU1FGUdldEF0dHJpYnV0ZUNoYW5nZWRTaWduYWwTREVTVF9UWVBFX0FUVFJfTkFNRRNERVNUX09CSl9WQUxVRV9OQU1FGk5FVFdPUktfT1dORVJfSURfQVRUUl9OQU1FFUxPT0tfQVRfUE9TX0FUVFJfTkFNRRZMT09LX0FUX1RZUEVfQVRUUl9OQU1FFkxPT0tfQVRfT0JKX1ZBTFVFX05BTUUNUmF5Y2FzdFBhcmFtcxFSYXljYXN0RmlsdGVyVHlwZQlCbGFja2xpc3QKRmlsdGVyVHlwZQtJZ25vcmVXYXRlchNvY2NsdXNpb25DYXN0UGFyYW1zDE5pbENvbmRpdGlvbhpBTExPV0VEX1BSSVNNU19GT0xERVJfTkFNRRZIT01FX1BPU0lUSU9OX09CSl9OQU1FBXNldHVwCEh1bWFub2lkCUdldFRhZ2dlZAZQYXJlbnQFdGFibGUGaW5zZXJ0CkdldFBsYXllcnMJQ2hhcmFjdGVyDkZpbmRGaXJzdENoaWxkC0FnZW50SGVpZ2h0C0FnZW50UmFkaXVzD1dheXBvaW50U3BhY2luZwVDb3N0cwphZ2VudENvc3RzCkNyZWF0ZVBhdGgLX3BhdGhmaW5kVG8KcGF0aGZpbmRUbwhVcFZlY3RvcgxDb21wdXRlQXN5bmMERmlyZRpKVU1QSU5HX0RJU0FCTEVEX0FUVFJfTkFNRQxHZXRBdHRyaWJ1dGUGQWN0aW9uElBhdGhXYXlwb2ludEFjdGlvbgRKdW1wAm9zBWNsb2NrBm1vdmVUbwVwY2FsbAZTdGF0dXMKUGF0aFN0YXR1cwdTdWNjZXNzGV9kb2VzUGF0aGZpbmRpbmdQYXRoRXhpc3QMR2V0V2F5cG9pbnRzDk1vdmVUb0ZpbmlzaGVkC0F0dGFjaG1lbnQwDVdvcmxkUG9zaXRpb24ZX2xhc3RUYXJnZXRPY2NsdXNpb25DaGVjaw1pc05vbk9jY2x1ZGVkCFJvb3RQYXJ0Gl9pc1RhcmdldE5vbk9jY2x1ZGVkQ2FjaGVkCWdldERpc3RUbxxNSU5fRElTVF9UT19UQVJHRVRfQVRUUl9OQU1FDXppZ1phZ1Rvd2FyZHMLbW92ZVRvd2FyZHMKY29sbGlkYWJsZQZNb3ZlVG8aU0lERV9TVFJBRkVfTVVMVF9BVFRSX05BTUUVRlJFUV9PRkZTRVRfQVRUUl9OQU1FBUNyb3NzA2NvcwRNb3ZlBGdhbWURQ29sbGVjdGlvblNlcnZpY2UKR2V0U2VydmljZQdQbGF5ZXJzClJ1blNlcnZpY2USUGF0aGZpbmRpbmdTZXJ2aWNlEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUDU3RkCUdlb21VdGlscwhJbnRlcnZhbAZSZWdpb24GU2lnbmFsC1JlZ2lvblV0aWxzBE1haWQHUmF5Y2FzdA9SeEluc3RhbmNlVXRpbHMDTlBDCU5QQ0NvbnN0cwhOUENVdGlscwAqAgABAAAAE/sBAABNAAHwAAAAAA4ACgD7AQAATQAB8AAAAAC8AABQAQAAAJ8AAgH7AAAAxgEAADABAPAAAAAA+wAAAMYBAAAwAQCDAgAAAIIAAQADAwEDAgMDABgAARgAAAAAAQAAAAAAAQAAAAIAAAABGQAAAAABAAAAAAACqQABAIIAAgAAACcAARgAACgAAAAAAgABAAAABfsAAADGAQAAMAEAnQAAAACCAAEAAQMEADIAARgAAAAAATMAAAAABQIBAAAACfsCAAAwAAKdAAAAANkEAAASAgAAvAIB/QEAAACfAgMBggABAAIDBAMFAQIwAAEYAAAAAQAAAAADMQAAAAAPAAUAAACAAfsBAABNAAGbAAAAACsAAQCCAAEA+wEBAE0AAfsBAAAA+wEAAJ8AAgJNAQA7AgAAAE0EAIUDAAAAbwUEAAkDBAVNAgOqBQAAAPsFAABNBAWbAAAAAE0DBDsCAAAA+wcAAE0GB5sAAAAATQUGhQMAAABNBAWqBQAAAMYFAABvBgYAYAYIAAIAAABNBwCFAwAAAG8IBAAJBgcITQUGBwcAAABlAAEAbwUIAPsHAgBNBgf2CQAAAFIHAwBSCAQAUgkBAFIKAgBSCwUAnwYGAiYJAQNvCgQACQgJCk0HCKoFAAAAKwYIAD4JBwuMCgAAjAsBAEwuAAKkCA4AADTAgJ8IBAJbBggKUggBAPsKAQBNCQpBDwAAAPsKAACfCQICDgkDAAkKBQIJCQoGQwgICakJAQCpCgEA+wwDAE0LDHEQAAAADgsQAPsMAwBNCwzAEQAAAFINAQC8CwuhEgAAAJ8LAwJSCQsA+wwDAE0LDMARAAAAUg0DALwLC6ESAAAAnwsDAlIKCwD7DAEATQsM2RMAAAD7DAAAnwsCAg4JBwD7DQQATQwNLxQAAAD7DQMAUg4IAJ8MAwGCAAEADgsIACsKBwD7DQQATQwNLxQAAAD7DQMAUg4LAJ8MAwGCAAEA+w0EAE0MDZIVAAAA+w4DAE0NDuEWAAAAbw4IAJ8MAwGCAAEAFwMGAwcDCAMJBwAAgD8AAAAAAACAPwAAAAADCgKamZmZmZm5PwMLBwAAAAAAAAAAAAAAAAAAAAADDAIAAAAAAAAIQAIAAAAAAABCQAMNAw4EADTAgAMPAxADEQMSAxMDFAMVAxYATwABGAAAAAABAgAAAAABAAEAAAAAAAEAAAAAAQAAAAAAAAEBAAABAAAAAAAAAgMAAAAAAAAAAAMAAAAAAQIAAAAAAAAAAgIAAAAAAAEAAAMBAQAAAAEAAAAAAAAAAQAAAAAAAAADAAAAAAQBAAAAAAAAAgABAAAAAAAAAgAAAAAAAAAHUAAAAAADAAMAAAAH+wEAAE0AAS8AAAAA+wEBAPsCAgCfAAMBggABAAEDFACLAQABGAAAAAAAAAGMAAAAAAMAAwAAAAn7AAAADgAGAPsBAQBNAAEvAAAAAPsBAgD7AgAAnwADAYIAAQABAxQAkQEAARgAAAEAAAAAAAKSAAAAAAcABAAABwAAAQgDGwEe+wEAAE0AAfsAAAAA+wEBAJ8AAgIrAAEAggABAPsDAgBNAgO0AgAAAJ8CAQJbAQIBpAIFAAAQMICfAgECbwMGAGACDAADAAAATQQBeQcAAACMBQAATQYBeAgAAABMNgACpAMLAAAokICfAwQCQwIAA94CAwCCAAEADAMHAgAAAAAAADBAAxcDDQMYBAAQMIACAAAAAAAA4D8DGQMaAxsDHAQAKJCAAJYBAAEYAAAAAAABAQIAAAAAAwAAAAAAAQAAAAAAAAAAAAAClwAAAAAIAAkAAACIAfsBAABNAAHvAAAAAJ8AAQL7AgEATQECFgEAAAAwAAG5AgAAAPsBAQC8AQHLAwAAAJ8BAgIrAQEAggABAPsCAQBNAQLVBAAAAA4BCAD7AQEAUgMAALwBAdUEAAAAnwEDAioBAgABAACAggABAPsCAgBNAQIlBQAAAPsCAwCfAQICDgFmAPsEBABNAwTqBgAAAE0CAx0HAAAAmgEYAAIAAAD7AwIATQID+wgAAAD7AwMAnwICAisCAQCCAAEA+wUFAE0EBbYJAAAA2QYAABICAwASAgIAEgIGABICAQASAgcAvAQExwoAAACfBAMAvAIA/QsAAACfAgABggABAPsEBABNAwTqBgAAAE0CA6kMAAAAmgEWAAIAAAD7AwIATQID+wgAAAD7AwMAnwICAisCAQCCAAEA+wYFAE0FBv0NAAAA2QcBABICBwASAgEAEgACALwFBccKAAAAnwUDALwDAP0LAAAAnwMAAYIAAQD7BAQATQME6gYAAABNAgPdDgAAAJoBIQACAAAAxgIAAPsGBQBNBQb9DQAAANkHAgASAQL/EgIHABICAQC8BQXHCgAAAJ8FAwC8AwD9CwAAAJ8DAAH7BggATQUGxA8AAACMBgIAnwUCAtkHAwASAgIAEgIDABICBgASAQL/vAUFxwoAAACfBQMAvAMA/QsAAACfAwABwQIAAIIAAQCkAhEAAAAAQW8DEgBSBAEAnwIDAYIAAQATAxwDHQMeAx8DIAMhAyIDIwMHAyQDJQMFAyYDJwMoAykDKgQAAABBAysEBAUGBzksARgAAAAAAQAAAAABAAAAAAEDAAAAAQAAAAAAAAEEAAAAAAEBAAAAAAAAAQAAAAAAAQUAAAAAAAAAAAAAAAAAAAA3AAAAAAAAAQAAAAABAQIAAAAAAAAAAAAAAAAAAwAAAAAAAAIBAAAAAAAAAAAAAAAABQAAAAAAAAAAAAAAAAAAAAAADQAAAAADOgAAAAAHAgEAAAAM+wIAAJ8CAQFNBACFAAAAAPsGAAC8BATHAQAAAJ8EAwC8AgH9AgAAAJ8CAAGCAAEAAwMtAyUDBQCrAQABGAAAAQAAAAAAAAAAAawAAAAABAADAAAACfsBAABNAAEtAAAAAPsBAQD7AwIATQIDOwEAAACfAAMBggABAAIDLgMIAMIBAAEYAAAAAAAAAAABwwAAAAADAAMAAAAH+wEAAE0AAS0AAAAA+wEBAPsCAgCfAAMBggABAAEDLgDKAQABGAAAAAAAAAHLAAAAAAIAAQAAAAv7AQAATQABnQAAAAAOAAYA+wEAAE0AAZ0AAAAAqQEAADABAPABAAAAggABAAIDBAMvAM8BAAEYAAAAAAEAAAAAAALQAAAAAAYABwAAAFD7AQAATQAB7wAAAACfAAEC+wIBAE0BAhYBAAAAMAAB3wIAAAD7AQEAvAEBywMAAACfAQICKwEBAIIAAQD7AgIATQECywQAAAD7AgMAnwECAg4BNQD7BAQATQME6gUAAABNAgMdBgAAAJoBFQACAAAA+wMCAE0CA3cHAAAA+wMDAJ8CAgIrAgEAggABAPsEBQBNAwT9CAAAANkFAAASAgYAEgIBABIAAgC8AwPHCQAAAJ8DAwIwAwBYCgAAAGUAGgD7BAQATQME6gUAAABNAgOpCwAAAJoBFAACAAAA+wMCAE0CA3cHAAAA+wMDAJ8CAgIrAgEAggABAPsEBQBNAwT9CAAAANkFAQASAgYAEgIBABIAAgC8AwPHCQAAAJ8DAwIwAwBYCgAAANkEAgASAgEAvAIA/QwAAACfAgMBggABAA0DHAMdAzADHwMxAyIDIwMyAycDJQMzAyYDBQMKCwyzATQBGAAAAAABAAAAAAEAAAAAAQMAAAAAAQEAAAAAAAABAAAAAAEBAgAAAAAAAAAAAAAAAAMAAAAAAAABAAAAAAEBAgAAAAAAAAAAAAAABQAAAAAFtQAAAAAHAgEAAAAM+wIAAJ8CAQFNBACFAAAAAPsGAAC8BATHAQAAAJ8EAwC8AgH9AgAAAJ8CAAGCAAEAAwMtAyUDBQDZAQABGAAAAQAAAAAAAAAAAdoAAAAAAgACAAAAC/sBAABNAAHCAAAAAPsBAQCfAAIB+wEAAE0AAawBAAAA+wEBAJ8AAgGCAAEAAgM1AzYA4AEAARgAAAAAAAEAAAAAAeQAAAAACwABAAAARPsAAAC8AADLAAAAAJ8AAgIOAD4A/wAEAAAAAACkAQQAAwgQwKkCAQBqAgABpAEGAAUIEMCpAgEAagIAAaQBCAAHCBDAqQIBAGoCAAGkAQoACQgQwKkCAQBqAgABpAEMAAsIEMCpAgEAagIAAfsCAABNAQLhDQAAAKQCDwAAAOBApAMQAAAIEIC8AwMWEQAAAJ8DAgCfAgAEUQIQAKQHEwASCBDA8QYNAAcAAABSCQYAvAcB/BQAAACfBwMCDgcHAIcHAAYrBwUAUgkGAKkKAAC8BwHoFQAAAJ8HBAFuAu//AgAAgLwDAXYWAAAAnwMCAocCAAMrAgUApAQGAAUIEMC8AgEhFwAAAJ8CAwGCAAEAGAMfAzcDOAM5BAMIEMADOgQFCBDAAzsEBwgQwAM8BAkIEMADPQQLCBDAAxYDPgQAAOBABAAIEIADPwNABBIIEMADQQNCA0MDRADnAQABGAAAAAAAAQABAAAAAQAAAAEAAAABAAAAAQAAAAIAAAEAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAD+AAUAAAAAAQAAAAAD6AAAAAADAAMAAAAJ+wAAAPsCAQBNAQK9AAAAAPsCAgCfAQICMAEAfQEAAACCAAEAAgNFA0YAgQIAARgAAAAAAAAAAAECAQAAAAMBAQAAAAb7AQAATQIA7AAAAAAwAgGCAQAAAIIAAQACA0cDSACUAgABGAAAAAAAARUBAAAAAwEBAAAABvsBAABNAgDsAAAAADACAZIBAAAAggABAAIDRwNJAJkCAAEYAAAAAAABGgEAAAAFAAIAAAAO+wAAAPsDAQC8AwNoAAAAAJ8DAgIcAgMAjAMAALcDAgACAAAAqQEAAakBAQAwAQBxAQAAAIIAAQACA0oDEACfAksBGAAAAAAAAAAAAAAAAAABIAEAAAAKAgMAAABC4gICAKQDBQAAEDCAnwMBAjADAoIAAAAATDYAAqQDBwAAEGCAnwMBAjADApIBAAAA+wYAAE0FBuoIAAAAUgYAAG8HAADZCAAAEgACAJ8FBAC8AwH9CQAAAJ8DAAH7BgAATQUG6ggAAABSBgAAbwcBANkIAQASAAIAnwUEALwDAf0JAAAAnwMAAfsEAQBNAwTACgAAAFIFAgC8AwNXCwAAAJ8DAwJSBgMAvAQB/QkAAACfBAMB2QQCABICAQASAgIA+wUBAPsIAgC8CAhoDAAAAJ8IAgIcBwgAjAgAALcIAgAHAAAAqQYAAakGAQAwBgVxDQAAAFIHBAC8BQH9CQAAAJ8FAwGCAAEADgNIA0kFAgABA0wDHAQAEDCAAxsEABBggANNAwUDEQNOA0oDEAMSExSRAgABGAAAAAAAAAAAAAAAAAIAAAAAAAAA/wAABgAAAAAAAAD/AAAFAAAAAAAAAQAAAAEAAAEAAAAAAAAAAAAAAAADAAAAARIBAAAABwICAAAADfsFAABNBAX3AAAAAFIFAADZBgAAEgIAABICAQASAAAAnwQDALwCAf0BAAAAnwIAAYIAAQACA08DBQEVjQIAARgBAAABAQAAAP7/AAAZDgEAAAADAAMAAAAJ+wAAAPsCAQBNAQLZAAAAAPsCAgCfAQICMAEAqwEAAACCAAEAAgMTA1AAsQJRARgAAAAAAAAAAAEyAQAAAAIAAQAAAAX7AAAAxgEAADABAKsAAAAAggABAAEDUAC2AgABGAAAAAABNwEAAAAIAgMAAAAb2QIAABICAAASAgEAEgICAPsDAAD7BQEATQQF2QAAAAD7BQIAnwQCAjAEA6sBAAAATQUAhQIAAABSBwIAvAUFxwMAAACfBQMAvAMB/QQAAACfAwAB2QUBABICAAC8AwH9BAAAAJ8DAwGCAAEABQMTA1ADLQMlAwUCFxiwAgABGAAAAAABAAAAAAAAAAMAAAAAAAAAAAEAAAAAAzEBAAAACwELAAAAtQJNAQATAAAAAE0CABYBAAAA2QQAABIAAAC8AgL9AgAAAJ8CAwHGAgAAMAIAgwMAAADGAgAAMAIAeAQAAABNAgAWAQAAAMYDAAAwAwIwBQAAAIwCAAAwAgAIBgAAAPsDAABNAgPvBwAAAJ8CAQIwAgB7CAAAAMACCQAwAgBaCgAAAMYCAAAwAgCdCwAAAE0CABYBAAAA+wUBAE0EBeoMAAAAUgUBAPsHAgBNBgcLDQAAANkHAgASAAAAnwQEALwCAv0CAAAAnwIAAdkCAwASAgMAEgAAABICBAASAAEAEgICABICBQASAgYAEgIHABICCABSAwIAnwMBAU0DABYBAAAA+wgCAE0HCBIOAAAAvAUBFg8AAACfBQMCUgcCALwFBccQAAAAnwUDALwDA/0CAAAAnwMAAU0DABYBAAAA+wgCAE0HCOgRAAAAvAUBFg8AAACfBQMCUgcCALwFBccQAAAAnwUDALwDA/0CAAAAnwMAAU0DABYBAAAA+wYBAE0FBuoMAAAAUgYBAPsIAgBNBwj1EgAAANkIBAASAAIAnwUEALwDA/0CAAAAnwMAAU0DABYBAAAA+wgCAE0HCGYTAAAAvAUBFg8AAACfBQMCUgcCALwFBccQAAAAnwUDALwDA/0CAAAAnwMAAdkDBQASAgMAEgAAABICBAASAAEAEgICABICBQASAgcAUgQDAJ8EAQFNBAAWAQAAAPsJAgBNCAk4FAAAALwGARYPAAAAnwYDAlIIAwC8BgbHEAAAAJ8GAwC8BAT9AgAAAJ8EAAFNBAAWAQAAAPsJAgBNCAn4FQAAALwGARYPAAAAnwYDAlIIAwC8BgbHEAAAAJ8GAwC8BAT9AgAAAJ8EAAFNBAAWAQAAAPsHAQBNBgfqDAAAAFIHAQD7CQIATQgJ4BYAAADZCQYAEgADAJ8GBAC8BAT9AgAAAJ8EAAFNBAAWAQAAAPsJAgBNCAlmEwAAALwGARYPAAAAnwYDAlIIAwC8BgbHEAAAAJ8GAwC8BAT9AgAAAJ8EAAFNBAAWAQAAAPsHCABNBgfEFwAAAIwHAQCfBgIC2QgHABICBwASAAAAvAYGxxAAAACfBgMAvAQE/QIAAACfBAABTQQAFgEAAAD7BwgATQYHxBcAAACMBwEAnwYCAtkICAASAAAAvAYGxxAAAACfBgMAvAQE/QIAAACfBAABpAQZAAAcgIGfBAECpAUdABxsoMEwBQRXHgAAAP8FAAAAAAAAMAUEfR8AAACpBQEAMAUEYyAAAAAwBAC7IQAAAE0FABYBAAAA+wgIAE0HCMQXAAAAjAgBAJ8HAgLZCQkAEgAEABICBwASAAAAvAcHxxAAAACfBwMAvAUF/QIAAACfBQAB+wYJAE0FBu8HAAAA+wcKAE0GB94iAAAAnwUCAjAFAMAjAAAATQUAFgEAAABNBwDAIwAAALwFBf0CAAAAnwUDAakFAAAwBQBxJAAAAE0FABYBAAAA+wgBAE0HCOoMAAAAUggBAPsKAgBNCQpTJQAAANkKCgASAgEAEgAAAJ8HBAC8BQX9AgAAAJ8FAAFNBQAWAQAAAPsIAQBNBwjqDAAAAFIIAQD7CgIATQkKmyYAAADZCgsAEgAAABICBAASAAEAnwcEALwFBf0CAAAAnwUAAYIAAQAnA1IDHQMFAwMDUwNUA1UDHANWBgEDVwMEA00DWANZA1oDJQNbA1wDXQNeA18DYAMpA2EEAByAgQM3A2IDYwQcbKDBA2QDRgNlA2YDZwMRAxADaANpDAABAwgJDQ4PEBEWGRVqAQgAAAIAAAAAAAAIAAABAAACAAAAAAEAAAIAAAAAAAEAAAQAAAEAAQAAAQEAAAEA/f8AAA0AAAAAAAAAAABuAAEAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAEAAQAAAAAAAAAAAP8AAAYAAAAAAAAAAAAAAAAAAAMAAAAAAAAAIgABAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAABAAEAAAAAAAAAAAD/AAAGAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAAAAAFQAAAQAAAAEAAAABAAABAAEAAAAAAAAAAAAAAAAAAAAAFQAAAAAAAAAAAQAAAAAAAAEAAAEAAQAAAQEAAAEAAP3/AAAjAAEAAAEBAAABAAAA/f8AABAWAAAA8AAAAAAMAQIAAAA7/wEAAAEAAABNAgATAAAAAMUBAgIBAAAA/wIAAAAAAAD7AwAAbwUBALwDAwUCAAAAnwMDBGQDCgCpCAEAaggCB00KByQDAAAAnjQBBAoAAABSCQEApAgGAAAUQICfCAMBbgP1/wIAAACkAwgAAABwQPsEAQC8BASrCQAAAJ8EAgCfAwAEUQMWAE0IB2kKAAAADggTAE0IB2kKAAAAbwoBALwICAMLAAAAnwgDAg4IDABNCggkAwAAAIcJAgorCQgATQsIJAMAAACeNAEECwAAAFIKAQCkCQYAABRAgJ8JAwFuA+n/AgAAgIIBAgAMA1IDawNsA20DbgNvBAAUQIADPgQAAHBAA3ADcQNyAL0CRQEYAAABAAAAAgABAAAAAAABAAEAAAAAAAAA/gAEAAAAAAAAAAEAAAEAAAAAAAEAAAAAAQAAAAAAAAD8AAg+AQAAAAUBAQAAACBNAQDwAAAAAA4BCABNAQDwAAAAALwBAVABAAAAnwECAcYBAAAwAQDwAAAAAPsBAADiAwYAjAQEADAEA8ECAAAAjAQCADAEAz8DAAAAbwQHADAEAx0EAAAATQQASQgAAAAwBAPIBQAAALwBAesJAAAAnwEDAjABAPAAAAAAggABAAoDAQMCA3MDdAN1A3YFBAIDBAUCAAAAAAAA8H8DdwN4ANACNQEYAAAAAQAAAAABAAACAAEAAAEAAAEAAAEAAAD8AAAAAAZRAQAAAAICAAAAAAMwAQBYAAAAAIIAAQABA3kA3AJ6ARgAAAFdAQAAAAoAAgAAABr7AQAATQAB8AAAAAD7BgAATQUGEwEAAABNBAWbAgAAAE0DBDsDAAAA+wkAAE0ICRMBAAAATQcImwIAAABNBgeFBQAAAE0FBhEGAAAAWwQFBEMCAwT7AwEAvAAARQcAAACfAAQBggABAAgDAQNSAwYDCAIAAAAAAAAQwANMA3sDfADiAgABGAAAAAEAAAAAAAAAAAAAAAAAAAAAAAH+AAAEZAEAAAAGAQMAAABeDgBOAPsCAABNAQKDAAAAAA4BSgD7AgAATQECeAEAAAD7BAAATQMEgwAAAAAcAgMAYAFCAAIAAAD7AQAATQIBeAEAAACVAgICMAIBeAEAAAD7AwAATQIDgwAAAAD7BAAATQMEeAEAAACHAQID+wMAAE0CA3sDAAAAUgQBALwCAt0EAAAAnwIDAfsDAABNAgMTBQAAAPsFAQBNBAVtBgAAALwCAhIHAAAAnwIDAioCEwABAAAATQIBAggAAACkAwwACyiQwJoCDQADAAAA+wIAAKQDDwAAONCAnwMBAjADAggQAAAA+wMAAE0CA+ERAAAAqQMBADADAlMLAAAA+wMAAE0CA1oSAAAAUgMBAJ8CAgIOAhgA+wMCAE0CAxcTAAAA+wQAAE0DBOERAAAATQQBOxQAAACfAgMBggABAPsCAgBNAQKSFQAAAPsDAABNAgPhEQAAAG8DFgCfAQMB+wIAAE0BAhYXAAAAxgIAADACATAYAAAAggABABkDAwNTAgAAAAAAAPA/A1YDfQNSA34DfwOAAQM3A4EBA4IBBAsokMADgwEDhAEEADjQgANVAxYDVwOFAQMIAxUHAAAAAAAAAAAAAAAAAAAAAAMdA1QA8wIAARgAAAAAAAAAAAAAAAAAAAIAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAABAAAAAAABAAAAAAABAAAAAAADAAAAAAABAAAAAAAAAAAAAwAAAAAAAAABAAAAAAACdAEAAAAKAQIAAACKAU0BAFgAAAAADgF8AKQCAgAAABBA2QMAABIAAAASAAEAnwICA00EAFADAAAARwQCAAAAAICCAAEAUgQCAA4ECgBNBgDwBAAAAE0FBuwFAAAApAYJAAgcYMDxBQIABgAAAKkEAAGpBAEAMAQAoAoAAAAOBFoATQUA8AQAAAC8BQX7CwAAAJ8FAgIwBQCDDAAAAE0GABYNAAAATQUGMA4AAAArBQ8ATQUAFg0AAABNBwDhDwAAAE0GB2UQAAAA2QgBABIAAAASAgAAEgIBALwGBscRAAAAnwYDAjAGBTAOAAAAjAUCADAFAHgSAAAATQYAgwwAAABNBwB4EgAAAIcFBgcOBS4ATQYAexMAAABSCAUAvAYG3RQAAACfBgMBTQYAExUAAAD7CQAATQgJbRYAAAC8BgYSFwAAAJ8GAwIqBhEAAQAAAE0GBQIYAAAApAcbABpkYMCaBgsABwAAAKQGHgAAdMCBnwYBAjAGAAgfAAAATQYA4Q8AAACpBwEAMAcGUxoAAABNBgBaIAAAAFIHBQCfBgICDgYjAPsHAQBNBgcXIQAAAE0HAOEPAAAATQgFOyIAAACfBgMBggABAPsHAQBNBgeSIwAAAE0HAOEPAAAAbwgkAJ8GAwGCAAEA+wYBAE0FBpIjAAAATQYA4Q8AAABvByQAnwUDAYIAAQBNAwAWDQAAAE0CAzAOAAAADgIFAE0CABYNAAAAxgMAADADAjAOAAAAggABACUDeQOGAQQAABBAAwIDAQOHAQM3A4gBA4kBBAgcYMADigEDiwEDAwMdA1QDFgOMAQMlA1MDVgN9A1IDfgN/A4ABA4EBA4IBBBpkYMADgwEDhAEEAHTAgQNVA1cDhQEDCAMVBwAAAAAAAAAAAAAAAAAAAAACHh/fAjYBGAAAAQEAAAAAAAgAAAABAgAAAAAAAAAAAAAAAQABAQAAAAAAAAIAAAAAAQAAAAAAAAAAAAAAAAAAFwAAAQAAAAABAQAAAAAAAQAAAAAAAAAAAAEAAAAAAAEAAAAAAQAAAAADAAAAAAEAAAAAAAAAAAMAAAAAAAAAAwAAAAAAAAADAAAAAAEAAAAAA2ABAAAABwIAAAAHBAAABQIPiCtNAgCdAAAAAEcCJwAAAAAARwEbAAAAAABNAwCdAAAAAE0CA/ABAAAAKwIFAE0CAJ0AAAAAqQMBADADAvABAAAATQQAnQAAAABNAwRrAgAAAE0CA+ADAAAATQMAnQAAAACkBAYAABRAgFIFAgBSBgEAnwQDAjAEA4UEAAAAggABAE0DAJ0AAAAATQID8AEAAAAOAgUATQIAnQAAAACpAwAAMAMC8AEAAACCAAEABwMEAy8DjQEDjgEDTAMuBAAUQIAAowMuARgAAAAAAQABAAAAAAEAAAAAAgAAAAAAAQAAAAAAAAAAAAIAAAAAAQAAAAAEpAEAAAAJAgIAAABTTQIA4QAAAACkAwMAAAgQgJ8DAQJNBADBBAAAACsEAwCMBAAAMAQAwQQAAABNBQDBBAAAACYEAwWMBQEAYAUOAAQAAAAwAwDBBAAAAPsFAABNBAUQBQAAAE0FAkYGAAAAUgYBAE0HALsHAAAAnwQEAjAEAHsIAAAA+wUAAE0EBSIJAAAATQUCRgYAAABSBgEAnwQDAk0FAiQKAAAA+wgBAE0HCFwLAAAAvAUFEgwAAACfBQMCfQUeAAQAAABNBgB7CAAAAA4GCgD7BwAATQYH3g0AAABSBwIAUggBAJ8GAwHGBgAAMAYAWA4AAACCAAEA+wcAAE0GB3sPAAAAUgcAAFIIAQCfBgMBTQYAoBAAAAArBg0A+wcAAE0GB68RAAAAUgcCAFIIAQCfBgMBggABAPsHAABNBgeSEgAAAFIHAgBvCBMAnwYDAYIAAQAUAxYDgwEDhAEEAAgQgAOPAQOQAQORAQNmA5IBA5MBA20DlAEDfwOVAQN5A3oDigEDlgEDFQcAAAAAAAAAAAAAAAAAAAAAALIDFAEYAAACAAABAAABAAACAAAAAAABAAEAAAAAAAAAAAAAAgAAAAAAAAEAAAAAAAAAAQABAAABAAAAAAABAAAAAgAAAAAAAQAAAQAAAAAAAAQAAAAAAAKzAQAAAAoDAQAAACJNAwA7AAAAACYEAQNNBQSqAQAAAG8GAgBgBQMABgAAAKkFAACCBQIA+wYAAE0FBpoDAAAAUgYDAE0HBAcEAAAATQgEqgEAAABSCQIAnwUFAisFAgCpBgEAggYCAE0IBTsAAAAAJgcIAU0GB6oBAAAAbwgCALcGAgAIAAAAqQcAAakHAQCCBwIABQMIAwoCmpmZmZmZuT8DlwEDCwDNA5ABARgAAAEBAAAAAAEAAgAAAAAAAAAAAAEBAAIAAAAAAQAAAAAAzgEAAAAFAgAAAAAFUgQBALwCAHcAAAAAnwIDAYIAAQABA5gBANoDhQEBGAAAAAAB2wEAAAAGAgEAAAANTQQARgAAAABNAwQ7AQAAACYCAQP7BAAATQMEkgIAAABSBAAATQUCBwMAAACfAwMBggABAAQDkQEDCAMVAwsA3QOWAQEYAAAAAAABAAAAAAAAAd4BAAAAEAICAAAAOk0CACQAAAAA+wUAAE0EBUABAAAAvAICEgIAAACfAgMCTQMAJAAAAAD7BgAATQUG8AMAAAC8AwMSAgAAAJ8DAwJNBgBGBAAAAE0FBjsFAAAAJgQBBU0FBKoGAAAAPgcFB4wIAACMCQEATC4AAqQGCgAAJICAnwYEAk0HBAcLAAAAbwkMALwHB7sNAAAAnwcDAqQMEQAAQPCAnwwBAlsLDA5DCgsDuwkKAqQJEwAASICAnwkCAgkICQb7CgEATQkKkhQAAABSCgAATQwEBwsAAAAJDwcIWw4PFQkNDgJDCwwNnwkDAYIAAQAWA20DmQEDfwOaAQORAQMIAwoCAAAAAAAAOEADDQMOBAAkgIADCwcAAAAAAACAPwAAAAAAAAAAA5sBAgAAAAAAABxAA4MBA4QBBABA8IADnAEEAEiAgAMVAjMzMzMzM9M/AOEDlQEBGAAAAAAAAAAAAQAAAAAAAAABAAAAAAEAAQAAAAAAAAEAAAAAAAEAAAAAAAAAAAABAAAAAAAAAAAAAAHiAQAAAAUCAAAAAAVSBAEAvAIAsgAAAACfAgMBggABAAEDnQEA6wMVARgAAAAAAewBAAAABwIAAAAACE0CADsAAAAAJgUBAm8GAQAJBAUGTQMEqgIAAACCAwIAAwMIBwAAgD8AAAAAAACAPwAAAAADCgDuA5MBARgAAAEAAAAAAO8BAAAAEQAAAQIApwGjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIBAAAAAEBvBAUAvAICFgMAAACfAgMCpAMBAAAAAEBvBQYAvAMDFgMAAACfAwMCpAQBAAAAAEBvBgcAvAQEFgMAAACfBAMCpAUJAAAAgEBNBwShCgAAAE0GBzwLAAAAnwUCAqQGCQAAAIBATQgEoQoAAABNBwisDAAAAJ8GAgKkBwkAAACAQE0JBKEKAAAATQgJ8w0AAACfBwICpAgJAAAAgEBNCgShCgAAAE0JCh8OAAAAnwgCAqQJCQAAAIBATQwEoQoAAABNCwzzDQAAAE0KC/4PAAAAnwkCAqQKCQAAAIBATQwEoQoAAABNCwx2EAAAAJ8KAgKkCwkAAACAQE0NBKEKAAAATQwNwhEAAACfCwICpAwJAAAAgEBNDgShCgAAAE0NDlISAAAAnwwCAqQNCQAAAIBATQ8EXBMAAABNDg9EFAAAAJ8NAgKkDgkAAACAQE0QBFwTAAAATQ8QexUAAACfDgIC/w8FAAAAAADAEBYAEgAIABIADAASAA0AEgAKABIADgASAAIAEgAFABIADwASAAYAEgAHABIACQAwEA/5FwAAAMAQGAASAAAAEgABADAQD70ZAAAAwBAaABIAAwAwEA/CGwAAAMAQHAAwEA97HQAAAMAQHgASAA0AEgAPADAQD6wfAAAAwBAgADAQDy0hAAAAwBAiABIADwASAA0AMBAPLyMAAADAECQAEgALADAQDxAlAAAAwBAmADAQDxcnAAAAwBAoABIADwAwEA+vKQAAAMAQKgASAA0AEgAPADAQD94rAAAAwBAsADAQD5ItAAAAwBAuADAQDyIvAAAAgg8CADADngEEAAAAQAOfAQOgAQOhAQOiAQOjAQOkAQOlAQQAAIBAA6YBA6cBA6gBA6kBA6oBA6sBA6wBA60BA64BA68BA7ABA7EBBhoDagYbA0UGHAM1Bh0DegYgAzYGIQMuBiIDFAYjA5ABBiQDhQEGJQOWAQYmA5UBBicDFQYoA5MBDRobHB0gISIjJCUmJygBAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgBAAAAAAAAAAAAAAAAAAAAAAAAEwAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAARAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAbAAAAAAAAAAAAAAAAAAAADQAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAAAAAAAAAAAAwAAAAAAAAAAAAAABAAAAAApS+TwLRWOlkF5IJq58HJIo51LAPskFd/ZenIJIaLrE9qGECfljwhDqg==

-- Decompiled by Krnl

local v_u_1 = game:GetService("CollectionService")
local v_u_2 = game:GetService("Players")
local v_u_3 = game:GetService("RunService")
local v_u_4 = game:GetService("PathfindingService")
local v5 = game:GetService("ReplicatedStorage")
local v_u_6 = require(v5.Std.GeomUtils)
local v_u_7 = require(v5.Std.Interval)
local v_u_8 = require(v5.Std.Region)
local v_u_9 = require(v5.Std.Signal)
local v_u_10 = require(v5.Std.Region.RegionUtils)
local v_u_11 = require(v5.Std.Maid)
local v_u_12 = require(v5.Std.Raycast)
local v_u_13 = require(v5.Std.RxInstanceUtils)
local v_u_14 = require(v5.NPC.NPCConsts)
local v_u_15 = require(v5.NPC.NPCUtils)
local v_u_116 = {
	["setup"] = function(p_u_16)
		-- upvalues: (copy) v_u_9, (copy) v_u_13, (copy) v_u_14, (copy) v_u_11, (copy) v_u_15, (copy) v_u_3, (copy) v_u_6, (copy) v_u_116, (copy) v_u_7, (copy) v_u_8, (copy) v_u_10
		local v_u_17 = p_u_16.obj
		p_u_16.maid:GiveTask(function()
			-- upvalues: (copy) p_u_16
			if p_u_16._path then
				p_u_16._path:Destroy()
				p_u_16._path = nil
			end
			p_u_16._waypoints = nil
		end)
		p_u_16._waypoints = nil
		p_u_16._nextWaypointIndex = nil
		p_u_16.maid.reachedConnection = nil
		p_u_16._lastJump = 0
		p_u_16.onWaypoint = v_u_9.new()
		function p_u_16.shouldMoveToNextWaypointFunc()
			return true
		end
		p_u_16.lookAtConstraint = nil
		p_u_16.maid:GiveTask(v_u_13.observeOneChildNamed(v_u_17, v_u_14.LOOK_AT_CONSTRAINT_NAME, function(p18, p19)
			-- upvalues: (copy) p_u_16
			p_u_16.lookAtConstraint = p18
			p19:GiveTask(function()
				-- upvalues: (ref) p_u_16
				p_u_16.lookAtConstraint = nil
			end)
		end))
		local function v_u_41()
			-- upvalues: (ref) v_u_11, (copy) p_u_16, (ref) v_u_15, (copy) v_u_17, (ref) v_u_14, (ref) v_u_3, (ref) v_u_6, (ref) v_u_116, (ref) v_u_7
			local v20 = v_u_11.new()
			p_u_16.maid.targetMaid = v20
			if p_u_16:IsLocallyOwned() then
				if not p_u_16.customUpdateTarget or p_u_16:customUpdateTarget(v20) ~= true then
					local v21 = v_u_15.getTargetType(v_u_17)
					if v21 then
						if v21 == v_u_14.DEST_TYPE.OBJ then
							if v_u_15.getTarget(v_u_17) then
								v20:GiveTask(v_u_3.PostSimulation:Connect(function()
									-- upvalues: (ref) v_u_17, (ref) v_u_15, (ref) v_u_6, (ref) p_u_16, (ref) v_u_116
									if v_u_17.PrimaryPart then
										local v22 = v_u_15.getTarget(v_u_17)
										local v23 = v22.Position
										local v24 = (v22.Velocity * Vector3.new(1, 0, 1)).Magnitude
										local v25 = v_u_17.PrimaryPart.Position
										local v26 = v_u_17.PrimaryPart.Velocity.Magnitude
										local v27 = v24 <= 0.1 and Vector3.new(0, 0, 0) or (v22.Velocity * Vector3.new(1, 0, 1)).Unit
										local v28 = v_u_6.getTrajectoryInterceptTime(v25, v26, v23, v24, v27)
										local v29 = ((v23 - v25) * Vector3.new(1, 0, 1)).Magnitude
										if not v28 then
											local v30 = v29 / 36
											v28 = math.clamp(v30, 0, 1) * 3
										end
										local v31
										if v_u_15.getExtrapolateTargetMovement(v_u_17) then
											v31 = v23 + v27 * v24 * v28
										else
											v31 = v23
										end
										local v32, v33
										if p_u_16.hasAllowedRegion then
											v32 = p_u_16.allowedRegion:CastPoint(v23)
											v33 = p_u_16.allowedRegion:CastPoint(v25)
										else
											v32 = true
											v33 = true
										end
										local v34 = v_u_15.getHomePosition(v_u_17)
										if v32 then
											v_u_116.goTo(p_u_16, v31)
											return
										elseif v34 and not v33 then
											v_u_116.goTo(p_u_16, v34)
										else
											v_u_116.move(p_u_16.humanoid, Vector3.new(0, 0, 0))
										end
									else
										return
									end
								end))
							end
						end
						if v21 == v_u_14.DEST_TYPE.POS then
							local v_u_35 = v_u_15.getTarget(v_u_17)
							if v_u_35 then
								v20:GiveTask(v_u_3.Heartbeat:Connect(function()
									-- upvalues: (ref) v_u_116, (ref) p_u_16, (copy) v_u_35
									v_u_116.goTo(p_u_16, v_u_35)
								end))
							end
						end
						if v21 == v_u_14.DEST_TYPE.IDLE then
							local v_u_36 = nil
							v20:GiveTask(v_u_3.Heartbeat:Connect(function()
								-- upvalues: (ref) v_u_36, (ref) v_u_116, (ref) p_u_16
								if v_u_36 then
									v_u_116.goTo(p_u_16, v_u_36)
								end
							end))
							v20:GiveTask(v_u_7.every(2):Connect(function()
								-- upvalues: (ref) v_u_15, (ref) v_u_17, (ref) v_u_6, (ref) v_u_36
								local v37 = v_u_15.getTarget(v_u_17)
								if v37 then
									local v38 = v_u_6.randomPointOnCircle() * 16
									if math.random() < 0.5 then
										local v39 = v38.X
										local v40 = v38.Y
										v_u_36 = v37 + Vector3.new(v39, 0, v40)
									end
								end
							end))
							return
						end
						error("invalid targeType", v21)
					end
				end
			else
				return
			end
		end
		v_u_41()
		p_u_16.maid:GiveTask(v_u_17:GetAttributeChangedSignal(v_u_14.DEST_POS_ATTR_NAME):Connect(v_u_41))
		p_u_16.maid:GiveTask(v_u_17:GetAttributeChangedSignal(v_u_14.DEST_TYPE_ATTR_NAME):Connect(v_u_41))
		p_u_16.maid:GiveTask(v_u_13.observeOneChildNamed(v_u_17, v_u_14.DEST_OBJ_VALUE_NAME, function(p42, p43)
			-- upvalues: (copy) v_u_41
			v_u_41()
			p43:GiveTask(p42.Changed:Connect(v_u_41))
		end))
		p_u_16.maid:GiveTask(v_u_17:GetAttributeChangedSignal(v_u_14.NETWORK_OWNER_ID_ATTR_NAME):Connect(v_u_41))
		local function v_u_48()
			-- upvalues: (ref) v_u_11, (copy) p_u_16, (ref) v_u_15, (copy) v_u_17, (ref) v_u_14, (ref) v_u_3, (ref) v_u_116
			local v44 = v_u_11.new()
			p_u_16.maid.lookAtMaid = v44
			if p_u_16:IsLocallyOwned() then
				local v45 = v_u_15.getLookAtType(v_u_17)
				if v45 then
					if v45 == v_u_14.DEST_TYPE.OBJ then
						local v_u_46 = v_u_15.getLookAt(v_u_17)
						if not v_u_46 then
							return
						end
						v44.runtime = v_u_3.Heartbeat:Connect(function()
							-- upvalues: (ref) v_u_116, (ref) p_u_16, (copy) v_u_46
							v_u_116.lookAt(p_u_16, v_u_46.Position)
						end)
					elseif v45 == v_u_14.DEST_TYPE.POS then
						local v_u_47 = v_u_15.getLookAt(v_u_17)
						if not v_u_47 then
							return
						end
						v44.runtime = v_u_3.Heartbeat:Connect(function()
							-- upvalues: (ref) v_u_116, (ref) p_u_16, (copy) v_u_47
							v_u_116.lookAt(p_u_16, v_u_47)
						end)
					end
				end
				v44:GiveTask(function()
					-- upvalues: (ref) p_u_16
					if p_u_16.lookAtConstraint then
						p_u_16.lookAtConstraint.Enabled = false
					end
				end)
			end
		end
		v_u_48()
		p_u_16.maid:GiveTask(v_u_17:GetAttributeChangedSignal(v_u_14.LOOK_AT_POS_ATTR_NAME):Connect(v_u_48))
		p_u_16.maid:GiveTask(v_u_17:GetAttributeChangedSignal(v_u_14.LOOK_AT_TYPE_ATTR_NAME):Connect(v_u_48))
		p_u_16.maid:GiveTask(v_u_13.observeOneChildNamed(v_u_17, v_u_14.LOOK_AT_OBJ_VALUE_NAME, function(p49, p50)
			-- upvalues: (copy) v_u_48
			v_u_48()
			p50:GiveTask(p49.Changed:Connect(v_u_48))
		end))
		p_u_16.maid:GiveTask(v_u_17:GetAttributeChangedSignal(v_u_14.NETWORK_OWNER_ID_ATTR_NAME):Connect(v_u_48))
		p_u_16.maid:GiveTask(v_u_7.every(1):Connect(function()
			-- upvalues: (ref) v_u_116, (copy) p_u_16
			v_u_116._createNewPath(p_u_16)
			v_u_116._updatePathfind(p_u_16)
		end))
		p_u_16.maid:GiveTask(v_u_7.every(1):Connect(function()
			-- upvalues: (copy) p_u_16
			if p_u_16:IsLocallyOwned() then
				local v51 = {
					[Enum.HumanoidStateType.Dead] = true,
					[Enum.HumanoidStateType.Running] = true,
					[Enum.HumanoidStateType.Jumping] = true,
					[Enum.HumanoidStateType.Landed] = true,
					[Enum.HumanoidStateType.Freefall] = true
				}
				local v52 = p_u_16.humanoid
				for _, v53 in ipairs(Enum.HumanoidStateType:GetEnumItems()) do
					if v53 ~= Enum.HumanoidStateType.None and (v52:GetStateEnabled(v53) and not v51[v53]) then
						v52:SetStateEnabled(v53, false)
					end
				end
				if not v51[v52:GetState()] then
					v52:ChangeState(Enum.HumanoidStateType.Running)
				end
			end
		end))
		local v_u_54 = RaycastParams.new()
		v_u_54.FilterType = Enum.RaycastFilterType.Blacklist
		v_u_54.FilterDescendantsInstances = {}
		v_u_54.IgnoreWater = true
		p_u_16.occlusionCastParams = v_u_54
		p_u_16.maid:GiveTask(v_u_7.every(1):Connect(function()
			-- upvalues: (copy) v_u_54, (ref) v_u_116, (copy) p_u_16
			v_u_54.FilterDescendantsInstances = v_u_116._buildOcclusionBlacklist(p_u_16)
		end))
		p_u_16.allowedRegion = v_u_8.new(v_u_10.NilCondition)
		p_u_16.maid:GiveTask(p_u_16.allowedRegion)
		p_u_16.hasAllowedRegion = false
		p_u_16.maid:GiveTask(v_u_13.observeOneChildNamed(v_u_17, v_u_14.ALLOWED_PRISMS_FOLDER_NAME, function(p_u_55, p56)
			-- upvalues: (ref) v_u_13, (copy) p_u_16
			p56:GiveTask(v_u_13.observeChildren(p_u_55, function(p57, p58)
				-- upvalues: (ref) v_u_13, (ref) p_u_16, (copy) p_u_55
				local v_u_59 = {
					["c"] = CFrame.new(),
					["s"] = Vector3.new()
				}
				p58:GiveTask(v_u_13.observeOneChildNamed(p57, "c", function(p60)
					-- upvalues: (copy) v_u_59
					v_u_59.c = p60.Value
				end))
				p58:GiveTask(v_u_13.observeOneChildNamed(p57, "s", function(p61)
					-- upvalues: (copy) v_u_59
					v_u_59.s = p61.Value
				end))
				p58:GiveTask((p_u_16.allowedRegion:AddPrism(v_u_59)))
				local function v62()
					-- upvalues: (ref) p_u_16, (ref) p_u_55
					p_u_16.hasAllowedRegion = #p_u_55:GetChildren() > 0
				end
				p_u_16.hasAllowedRegion = #p_u_55:GetChildren() > 0
				p58:GiveTask(v62)
			end))
		end))
		p_u_16.maid:GiveTask(v_u_13.observeOneChildNamed(v_u_17, v_u_14.HOME_POSITION_OBJ_NAME, function(p63, p64)
			-- upvalues: (copy) p_u_16, (ref) v_u_15, (copy) v_u_17
			local function v65()
				-- upvalues: (ref) p_u_16, (ref) v_u_15, (ref) v_u_17
				p_u_16.homePosition = v_u_15.getHomePosition(v_u_17)
			end
			p_u_16.homePosition = v_u_15.getHomePosition(v_u_17)
			p64:GiveTask(p63.Changed:Connect(v65))
			p64:GiveTask(function()
				-- upvalues: (ref) p_u_16
				p_u_16.homePosition = nil
			end)
		end))
	end,
	["_buildOcclusionBlacklist"] = function(p66)
		-- upvalues: (copy) v_u_1, (copy) v_u_2
		local v67 = { p66.obj }
		local v68 = {}
		for _, v69 in v_u_1:GetTagged("Humanoid") do
			v68[v69] = true
			local v70 = v69.Parent
			table.insert(v67, v70)
		end
		for _, v71 in ipairs(v_u_2:GetPlayers()) do
			if v71.Character then
				local v72 = v71.Character:FindFirstChild("Humanoid")
				if v72 and not v68[v72.Parent] then
					local v73 = v72.Parent
					table.insert(v67, v73)
				end
			end
		end
		return v67
	end,
	["_createNewPath"] = function(p74)
		-- upvalues: (copy) v_u_4
		if p74._path then
			p74._path:Destroy()
			p74._path = nil
		end
		p74._path = v_u_4:CreatePath({
			["AgentHeight"] = 4,
			["AgentRadius"] = 2,
			["WaypointSpacing"] = (1 / 0),
			["Costs"] = p74.agentCosts
		})
	end,
	["pathfindTo"] = function(p75, p76)
		p75._pathfindTo = p76
	end,
	["_updatePathfind"] = function(p_u_77)
		-- upvalues: (copy) v_u_14, (copy) v_u_116
		local v_u_78 = p_u_77._pathfindTo
		if v_u_78 then
			local v79, _ = pcall(function()
				-- upvalues: (copy) p_u_77, (copy) v_u_78
				p_u_77._path:ComputeAsync(p_u_77.obj.PrimaryPart.Position + p_u_77.obj.PrimaryPart.CFrame.UpVector * -4, v_u_78)
			end)
			if p_u_77.Destroy == nil then
				return
			end
			if v79 then
				v79 = p_u_77._path.Status == Enum.PathStatus.Success
			end
			p_u_77._doesPathfindingPathExist = v79
			if not v79 then
				v_u_116.move(p_u_77.humanoid, Vector3.new(0, 0, 0))
				return
			end
			p_u_77._waypoints = p_u_77._path:GetWaypoints()
			if not p_u_77.maid.reachedConnection then
				p_u_77.maid.reachedConnection = p_u_77.humanoid.MoveToFinished:Connect(function(p80)
					-- upvalues: (copy) p_u_77, (ref) v_u_14, (ref) v_u_116
					if p80 and (p_u_77._waypoints and p_u_77._nextWaypointIndex < #p_u_77._waypoints) then
						local v81 = p_u_77
						v81._nextWaypointIndex = v81._nextWaypointIndex + 1
						local v82 = p_u_77._waypoints[p_u_77._nextWaypointIndex]
						p_u_77.onWaypoint:Fire(v82)
						if p_u_77.obj:GetAttribute(v_u_14.JUMPING_DISABLED_ATTR_NAME) ~= true and v82.Action == Enum.PathWaypointAction.Jump then
							p_u_77._lastJump = os.clock()
							p_u_77.humanoid.Jump = true
						end
						if p_u_77.shouldMoveToNextWaypointFunc(v82) then
							v_u_116.moveTo(p_u_77.humanoid, v82.Position)
							return
						end
					else
						v_u_116.move(p_u_77.humanoid, Vector3.new(0, 0, 0))
						p_u_77.maid.reachedConnection = nil
					end
				end)
			end
			p_u_77._nextWaypointIndex = 2
			local v83 = p_u_77._waypoints[p_u_77._nextWaypointIndex]
			if not v83 then
				v_u_116.move(p_u_77.humanoid, Vector3.new(0, 0, 0))
				return
			end
			p_u_77.onWaypoint:Fire(v83)
			if p_u_77.obj:GetAttribute(v_u_14.JUMPING_DISABLED_ATTR_NAME) ~= true and v83.Action == Enum.PathWaypointAction.Jump then
				p_u_77._lastJump = os.clock()
				p_u_77.humanoid.Jump = true
			end
			if p_u_77.shouldMoveToNextWaypointFunc(v83) then
				v_u_116.moveTo(p_u_77.humanoid, v83.Position)
				return
			end
		elseif p_u_77.maid.reachedConnection then
			p_u_77.maid.reachedConnection = nil
		end
	end,
	["lookAt"] = function(p84, p85)
		if p84.lookAtConstraint ~= nil then
			if p85 ~= nil then
				if not p84.lookAtConstraint.Enabled then
					p84.lookAtConstraint.Enabled = true
				end
				local v86 = p84.lookAtConstraint.Attachment0.WorldPosition
				p84.lookAtConstraint.CFrame = CFrame.lookAt(v86, p85)
				return
			end
			if p84.lookAtConstraint.Enabled then
				p84.lookAtConstraint.Enabled = false
			end
		end
	end,
	["goTo"] = function(p87, p88)
		-- upvalues: (copy) v_u_116, (copy) v_u_14
		local v89 = p87.humanoid
		local v90 = os.clock()
		if not p87._lastTargetOcclusionCheck then
			p87._lastTargetOcclusionCheck = 0
		end
		if v90 - p87._lastTargetOcclusionCheck > 1 then
			p87._lastTargetOcclusionCheck = v90
			p87._isTargetNonOccludedCached = v_u_116.isNonOccluded(v89.RootPart, p88, p87.occlusionCastParams)
		end
		if v_u_116.getDistTo(v89.RootPart, p88) >= v89.Parent:GetAttribute(v_u_14.MIN_DIST_TO_TARGET_ATTR_NAME) then
			if p87._isTargetNonOccludedCached then
				v_u_116.zigZagTowards(v89, p88)
				p87._pathfindTo = nil
				return
			end
			v_u_116.pathfindTo(p87, p88)
			if not p87._doesPathfindingPathExist then
				v_u_116.moveTowards(v89, p88)
				return
			end
		else
			v_u_116.move(v89, Vector3.new(0, 0, 0))
		end
	end,
	["isNonOccluded"] = function(p91, p92, p93)
		-- upvalues: (copy) v_u_12
		local v94 = p91.Position
		local v95 = p92 - v94
		if v95.Magnitude < 0.1 then
			return false
		end
		local v96 = v_u_12.collidable(v94, v95.Unit, v95.Magnitude, p93)
		return not v96 and true or (v96.Position - p92).Magnitude < 0.1
	end,
	["moveTo"] = function(p97, p98)
		p97:MoveTo(p98)
	end,
	["moveTowards"] = function(p99, p100)
		-- upvalues: (copy) v_u_116
		local v101 = p100 - p99.RootPart.Position
		v_u_116.move(p99, v101.Unit)
	end,
	["zigZagTowards"] = function(p102, p103)
		-- upvalues: (copy) v_u_14, (copy) v_u_116
		local v104 = p102.Parent:GetAttribute(v_u_14.SIDE_STRAFE_MULT_ATTR_NAME)
		local v105 = p102.Parent:GetAttribute(v_u_14.FREQ_OFFSET_ATTR_NAME)
		local v106 = p103 - p102.RootPart.Position
		local v107 = v106.Magnitude / 24
		local v108 = math.clamp(v107, 0, 1)
		local v109 = v106.Unit:Cross(Vector3.new(0, 1, 0))
		local v110 = os.clock() * 7 + v105
		local v111 = math.cos(v110) * v108
		v_u_116.move(p102, v106.Unit + v109 * v111 * 0.3 * v104)
	end,
	["move"] = function(p112, p113)
		p112:Move(p113)
	end,
	["getDistTo"] = function(p114, p115)
		return ((p115 - p114.Position) * Vector3.new(1, 0, 1)).Magnitude
	end
}
return v_u_116
