-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgPaAQVwYWlycwV0cmFjawRTdG9wB0Rlc3Ryb3kVZGVzdHJveVdhbGtBbmltYXRpb25zE3Jlc2V0VmVsb2NpdHlCb3VuZHMBeAF5FHVwZGF0ZVZlbG9jaXR5Qm91bmRzA3J1bgR3YWxrBHdhcm5CU3RyYWZlIGJsZW5kaW5nIGRpc2FibGVkLiAgUnVuIGFuZCB3YWxrIG11c3QgYmUgc3RyYWZpbmctZnJpZW5kbHkuElN0cmFmaW5nIHJlZW5hYmxlZBRjaGVja1N0cmFmaW5nRW5hYmxlZAJsdgRhbmltDUxvYWRBbmltYXRpb24ERW51bRFBbmltYXRpb25Qcmlvcml0eQRDb3JlCFByaW9yaXR5E3NldHVwV2Fsa0FuaW1hdGlvbnMFc3BlZWQJTWFnbml0dWRlB1ZlY3RvcjIDbmV3FnJlcGxhY2VMb2NvbW90aW9uVHJhY2sLY29ubmVjdGlvbnMKZGlzY29ubmVjdAVjb3VudAt0b3RhbFdlaWdodA5GaW5kRmlyc3RDaGlsZApDaGlsZEFkZGVkB2Nvbm5lY3QFdGFibGUGaW5zZXJ0DENoaWxkUmVtb3ZlZAtHZXRDaGlsZHJlbglBbmltYXRpb24DSXNBBldlaWdodAVWYWx1ZQZ3ZWlnaHQHQ2hhbmdlZA5MaW5lYXJWZWxvY2l0eQxHZXRBdHRyaWJ1dGUISW5zdGFuY2UETmFtZQJpZAtBbmltYXRpb25JZBVjb25maWd1cmVBbmltYXRpb25TZXQLU3RyaW5nVmFsdWUDaXNBE3NjcmlwdENoaWxkTW9kaWZpZWQKRGlzY29ubmVjdARpZGxlABFzdG9wQWxsQW5pbWF0aW9ucxdBdXRvbWF0aWNTY2FsaW5nRW5hYmxlZAlIaXBIZWlnaHQVU2NhbGVEYW1wZW5pbmdQZXJjZW50DmdldEhlaWdodFNjYWxlBG1hdGgFYXRhbjILc2lnbmVkQW5nbGUFY2xhbXALZ2V0MkRXZWlnaHQDbWluBHNxcnQJSXNQbGF5aW5nDFRpbWVQb3NpdGlvbgRQbGF5A21heAxBZGp1c3RXZWlnaHQLQWRqdXN0U3BlZWQHYmxlbmQyRAtXYWxrVG9Qb2ludApXYWxrVG9QYXJ0DU1vdmVEaXJlY3Rpb24GQ0ZyYW1lEVBvaW50VG9Xb3JsZFNwYWNlCFJvb3RQYXJ0CFBvc2l0aW9uAXoHVmVjdG9yMxBnZXRXYWxrRGlyZWN0aW9uCFVwVmVjdG9yAVkDYWJzB1J1bm5pbmcKTG9va1ZlY3RvcgFYAVoDRG90BXlBeGlzDnVwZGF0ZVZlbG9jaXR5EXNldEFuaW1hdGlvblNwZWVkA0VuZAZMb29wZWQTa2V5RnJhbWVSZWFjaGVkRnVuYwZyYW5kb20Ncm9sbEFuaW1hdGlvbg9LZXlmcmFtZVJlYWNoZWQMc3dpdGNoVG9BbmltDXBsYXlBbmltYXRpb24XdG9vbEtleUZyYW1lUmVhY2hlZEZ1bmMRcGxheVRvb2xBbmltYXRpb24Sc3RvcFRvb2xBbmltYXRpb25zCVdhbGtTcGVlZAhTdGFuZGluZwlvblJ1bm5pbmcERGVhZAZvbkRpZWQEanVtcAdKdW1waW5nCW9uSnVtcGluZwVjbGltYghDbGltYmluZwpvbkNsaW1iaW5nCUdldHRpbmdVcAtvbkdldHRpbmdVcARmYWxsCEZyZWVGYWxsCm9uRnJlZUZhbGwLRmFsbGluZ0Rvd24Nb25GYWxsaW5nRG93bgZTZWF0ZWQIb25TZWF0ZWQQUGxhdGZvcm1TdGFuZGluZxJvblBsYXRmb3JtU3RhbmRpbmcEc3dpbQhTd2ltbWluZwhzd2ltaWRsZQpvblN3aW1taW5nBE5vbmUIdG9vbG5vbmUESWRsZQVTbGFzaAl0b29sc2xhc2gGQWN0aW9uBUx1bmdlCXRvb2xsdW5nZQthbmltYXRlVG9vbAZpcGFpcnMIdG9vbGFuaW0JY2xhc3NOYW1lC2dldFRvb2xBbmltA3NpdARUb29sFUZpbmRGaXJzdENoaWxkT2ZDbGFzcwZIYW5kbGUGUGFyZW50C3N0ZXBBbmltYXRlCkRvQ2xlYW5pbmcCb3MFY2xvY2sZR2V0UGxheWluZ0FuaW1hdGlvblRyYWNrcwR0YXNrBWRlZmVyEEFuaW1hdGlvbnNGb2xkZXIGRm9sZGVyBnNjcmlwdANSZXMRRGVmYXVsdEFuaW1hdGlvbnMFQ2xvbmUISHVtYW5vaWQEd2F2ZQVwb2ludAVkYW5jZQZkYW5jZTIGZGFuY2UzBWxhdWdoBWNoZWVyKWh0dHA6Ly93d3cucm9ibG94LmNvbS9hc3NldC8/aWQ9NTA3NzY2NjY2KWh0dHA6Ly93d3cucm9ibG94LmNvbS9hc3NldC8/aWQ9NTA3NzY2OTUxKWh0dHA6Ly93d3cucm9ibG94LmNvbS9hc3NldC8/aWQ9NTA3NzY2Mzg4KWh0dHA6Ly93d3cucm9ibG94LmNvbS9hc3NldC8/aWQ9NTA3Nzc3ODI2KWh0dHA6Ly93d3cucm9ibG94LmNvbS9hc3NldC8/aWQ9NTA3NzY3NzE0KWh0dHA6Ly93d3cucm9ibG94LmNvbS9hc3NldC8/aWQ9NTA3Nzg0ODk3KWh0dHA6Ly93d3cucm9ibG94LmNvbS9hc3NldC8/aWQ9NTA3Nzg1MDcyKWh0dHA6Ly93d3cucm9ibG94LmNvbS9hc3NldC8/aWQ9NTA3NzY1MDAwKWh0dHA6Ly93d3cucm9ibG94LmNvbS9hc3NldC8/aWQ9NTA3NzY3OTY4KWh0dHA6Ly93d3cucm9ibG94LmNvbS9hc3NldC8/aWQ9NTA3NzY1NjQ0Kmh0dHA6Ly93d3cucm9ibG94LmNvbS9hc3NldC8/aWQ9MjUwNjI4MTcwMylodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTUwNzc2ODM3NSlodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTUyMjYzNTUxNClodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTUyMjYzODc2NylodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTUwNzc3MDIzOSlodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTUwNzc3MDQ1MylodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTUwNzc3MTAxOSlodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTUwNzc3MTk1NSlodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTUwNzc3MjEwNClodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTUwNzc3NjA0MylodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTUwNzc3NjcyMClodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTUwNzc3Njg3OSlodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTUwNzc3NzI2OClodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTUwNzc3NzQ1MSlodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTUwNzc3NzYyMylodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTUwNzc3MDgxOClodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTUwNzc3MDY3NwpyYW5kb21zZWVkBHRpY2sIR2l2ZVRhc2sIQW5pbWF0b3IISXNTZXJ2ZXIGYXNzZXJ0BERpZWQLRnJlZUZhbGxpbmcJSGVhcnRiZWF0B0Nvbm5lY3QEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUDU3RkBE1haWQKUnVuU2VydmljZQAwBwADAAAAMaQAAQAAAABA+wEAAJ8AAgQXABAATQUEwAIAAAAOBQ0ATQUEwAIAAAC8BQX6AwAAAJ8FAgFNBQTAAgAAALwFBVAEAAAAnwUCAcYFAAAwBQTAAgAAAG4A7/8CAAAApAABAAAAAED7AQEAnwACBBcAEABNBQTAAgAAAA4FDQBNBQTAAgAAALwFBfoDAAAAnwUCAU0FBMACAAAAvAUFUAQAAACfBQIBxgUAADAFBMACAAAAbgDv/wIAAACMAAAA3gACAIIAAQAFAwEEAAAAQAMCAwMDBAB6BQEYAAAAAAABAAABAAAAAAEAAAAAAQAA/AAHAAAAAAEAAAEAAAAAAQAAAAABAAD8AAcAAXsAAAAAAgEEAAAACYwBAADeAQAAjAEAAN4BAQCMAQAA3gECAIwBAADeAQMAggABAAAAkAEGARgAAAEAAQABAAGRAAAAAAMBBAAAACIOACAATQEAmQAAAAD7AgAAYAIEAAEAAABNAQCZAAAAAN4BAABNAQCYAQAAAPsCAQBgAgQAAQAAAE0BAJgBAAAA3gEBAE0BAJkAAAAA+wICAGABBAACAAAATQEAmQAAAADeAQIATQEAmAEAAAD7AgMAYAEEAAIAAABNAQCYAQAAAN4BAwCCAAEAAgMHAwgAlwEJARgAAQAAAAABAAACAAAAAAEAAAIAAAAAAQAAAgAAAAABAAADmAAAAAADAQcAAAAx+wEAAA0BCgAAAAAA+wEBAA0BBwAAAAAA+wECAA0BBAAAAAAA+wEDAA0BCAAAAACA+wEEAPsCBQCaAQEAAgAAAPsBBgDeAQQAggABAPsCBQBNAQI2AQAAAA4BBAD7AgUATQEC/wIAAAArAQsA+wEEAPsCBQCaAQUAAgAAAKQBBAAAADBAbwIFAJ8BAgH7AQYA3gEEAIIAAQD7AQQA+wIFAPEBBwACAAAA+wEFAN4BBACkAQQAAAAwQG8CBgCfAQIBggABAAcCAAAAAAAAAAADCgMLAwwEAAAwQAMNAw4AqAEPARgAAAAAAAAAAAAAAAABAAAAAwAAAQAAAAAAAAABAAAAAQAAAAIAAAIAAAABAAEAAAADqQAAAAALAAkAAABNjAAAAN4AAACMAAAA3gABAIwAAADeAAIAjAAAAN4AAwCkAAEAAAAAQPsBBACfAAIEFwAjAE0FBK0CAAAADgUgAE0GBZkDAAAA+wcBAGAHBAAGAAAATQYFmQMAAADeBgEATQYFmAQAAAD7BwMAYAcEAAYAAABNBgWYBAAAAN4GAwBNBgWZAwAAAPsHAABgBgQABwAAAE0GBZkDAAAA3gYAAE0GBZgEAAAA+wcCAGAGBAAHAAAATQYFmAQAAADeBgIAbgDc/wIAAAD7AAUAnwABAaQAAQAAAABA+wEGAJ8AAgQXABEA+wUHAPsKCACHCQoDEwgJAE0HCC4FAAAAvAUFlAYAAACfBQMCMAUEwAcAAABNBQTABwAAAKQGCwAKJIDAMAYFzQwAAABuAO7/AgAAAIIAAQANAwEEAAAAQAMQAwcDCAMRAxIDAgMTAxQDFQQKJIDAAxYAuwEXARgAAAEAAQABACoAAAAAAQDZAQAAAAABAAACAAAAAAEAAAIAAAAAAQAAAgAAAAABAAAbAAMAAQAAAAABAAAAAAAAAAAAAAEAAAAAAP4ABJEAAAAACQIHAAAAPKkCAAD7AwAA8AMHAAAAAID7BAEAhwMEAA4DAwD7AwIAnwMBAakCAQAOAQoA+wMDAOIEAwAwAQStAQAAAE0FAaoEAAAAMAUEzAIAAABqBAMAZQADAPsDAwDGBAAAagQDAPAAAwAFAAAA8AAbAAAAAIAOAQUA+wMEAPsFAwCHBAUAagQDAGUAFADwAAMABQAAgG8DBgBlAAEAbwMHAPsEBADiBQMApAYKAAAkgICMBwAAUggDAJ8GAwIwBgWtAQAAADADBcwCAAAAagUEAPsEAwDGBQAAagUEAA4CBAD7AwUAnwMBAYwDAADeAwYAggABAAsDCwMQAxgFAgECAxkDCgKamZmZmZkpQAKamZmZmZkZQAMaAxsEACSAgADIARwBGAABAAAAAAACAAEDAQAAAAAAAAAAAAIAAAIAAAABAQAAAAACAAAAAAEAAAAAAAAAAAAAAAEAAAMBAAEAAskAAAAABAEDAAAABfsBAAD7AgEA+wMCAJ8BAwGCAAEAAAD0AQABGAAAAAAB9QAAAAAEAQMAAAAF+wEAAPsCAQD7AwIAnwEDAYIAAQAAAPoBAAEYAAAAAAH7AAAAAAQBAwAAAAX7AQAA+wIBAPsDAgCfAQMBggABAAAAkAIAARgAAAAAAREBAAAABAEDAAAABfsBAAD7AgEA+wMCAJ8BAwGCAAEAAACWAgABGAAAAAABFwEAAAAEAQMAAAAF+wEAAPsCAQD7AwIAnwEDAYIAAQAAAJwCAAEYAAAAAAEdAQAAABICBgAAALgC+wMAAIcCAwBHAg4AAAAAAKQCAQAAAABA+wYAAIcFBgBNAwWRAgAAAJ8CAgQXAgMAvAcG+gMAAACfBwIBbgL8/wIAAAD7AgAA/wMAAAAAAABqAwIA+wMAAIcCAwCMAwAAMAMCGgQAAAD7AwAAhwIDAIwDAAAwAwKdBQAAAPsDAACHAgMA/wMAAAAAAAAwAwKRAgAAAPsCAQBSBAAAvAICAwYAAACfAgMCRwKgAAAAAAD7BgAAhwUGAE0EBZECAAAATQUCawcAAADZBwAAEgICABIAAAASAAEAvAUF5wgAAACfBQMATDQAAqQDCwAAKJCAnwMAAfsGAACHBQYATQQFkQIAAABNBQK9DAAAANkHAQASAgIAEgAAABIAAQC8BQXnCAAAAJ8FAwBMNAACpAMLAAAokICfAwABjAMAAKQEAQAAAABAvAUCaA0AAACfBQIAnwQABBcEcwBvCw4AvAkI/g8AAACfCQMCDgluAIwJAQBvDBAAvAoIAwYAAACfCgMCRwoDAAAAAABNCQrsEQAAAPsMAACHCwwA+w8AAIcODwBNDQ4aBAAAAJUMDRIwDAsaBAAAAPsMAACHCwwATQMLGgQAAAD7DAAAhwsMAP8MAAAAAAAAagwLA/sNAACHDA0AhwsMAzAICy4TAAAA+w0AAIcMDQCHCwwDMAkLyxQAAAD7DAAAhwsMAPsPAACHDg8ATQ0OnQUAAAD7EQAAhxARAIcPEANNDg/LFAAAAEMMDQ4wDAudBQAAAPsOAACHDQ4ATQwNkQIAAABNDQiFFQAAANkPAgASAgIAEgAAABIAAQC8DQ3nCAAAAJ8NAwBMNAACpAsLAAAokICfCwAB+w4AAIcNDgBNDA2RAgAAAE0NCGsHAAAA2Q8DABICAgASAAAAEgABALwNDecIAAAAnw0DAEw0AAKkCwsAACiQgJ8LAAH7DgAAhw0OAE0MDZECAAAATQ0IvQwAAADZDwQAEgICABIAAAASAAEAvA0N5wgAAACfDQMATDQAAqQLCwAAKJCAnwsAAW8NFgC8CwgSFwAAAJ8LAwL7DAMAUg0AAFIOCwCfDAMBbgSM/wIAAAD7BQAAhwQFAE0DBBoEAAAAjAQAAH0DQQAEAAAApAMBAAAAAEBSBAEAnwMCBBcDOQD7CQAAhwgJAP8JAAAAAAAAagkIBvsKAACHCQoAhwgJBqQJGgAAZICBbwoOAJ8JAgIwCQguEwAAAPsLAACHCgsAhwkKBk0ICS4TAAAAMAAIuhsAAAD7CwAAhwoLAIcJCgZNCAkuEwAAAE0JB/QcAAAAMAkIth0AAAD7CgAAhwkKAIcICQZNCQfLFAAAADAJCMsUAAAA+wkAAIcICQD7DAAAhwsMAE0KCxoEAAAAlQkKEjAJCBoEAAAA+wkAAIcICQD7DAAAhwsMAE0KC50FAAAATQsHyxQAAABDCQoLMAkInQUAAABuA8b/AgAAAKQDAQAAAABA+wQAAJ8DAgQXAx4AjAoBAE0IBxoEAAAAjAkBAKgIGQD7DAQAhw8HCk0ODy4TAAAATQ0Oth0AAACHCwwNRwsQAAAAAID7CwUAhw4HCk0NDi4TAAAAvAsLlB4AAACfCwMB+wsEAIcOBwpNDQ4uEwAAAE0MDbYdAAAAqQ0BAGoNCwyLCOf/bgPh/wIAAACCAAEAHwMBBAAAAEADHQMeAx8DIAMhAyIDIwMkAyUEACiQgAMmAycDKAMpAyoDKwIAAAAAAADwPwMRAywDLQMuAy8DMAMbBABkgIEDMQMyAzMDEgUGBwgJCuQBNAEYAAAAAAEAAAAAAAAAAQAA/wAEAAAAAQAAAAABAAAAAAEAAAAAAAMAAAAAAQACAAAAAQAAAAAAAAAA/gAAAAcAAAABAAAAAAAAAAD+AAAABwIAAAAAAAABAAAAAAEBAAAAAQABAAIAAAAAAAAAAAEAAAABAAAAAAEAAAAAAQAAAAABAAAAAAAAAAAAAAAAAAIAAAABAAAAAAAAAAD+AAAABwAAAAEAAAAAAAAAAP4AAAAHAAAAAQAAAAAAAAAA/gAAAAYAAAABAAAA4AAmAAAAAAAAAQAAAAABAAAAAAEAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAABAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAAD5AAwAAAAAAQAAAAABAAAAAAAAAAABAAAAAAAAAQAAAAAAAAD9/wAI5QAAAAAHAQIAAAAg+wIAAE0DALoAAAAAhwECA0cBBwAAAAAA+wIBAE0DALoAAAAAUgQBAJ8CAwGCAAEAbwQBALwCAN4CAAAAnwIDAg4CDgD7AgAATQMAugAAAAD/BAAAAAAAAGoEAgP7AgEATQMAugAAAAD7BQAATQYAugAAAACHBAUGnwIDAYIAAQADAzEDNQM2AL8CNwEYAAAAAAEAAQAAAAAAAgAAAAABAAAAAAABAAAAAAAAAANAAQAAAAwAAQAAABH7AAAAxgEAAMYCAABkAAoATQUEkQAAAADGBgAAxgcAAGQFAwC8CgkaAQAAAJ8KAgFuBfz/AgAAAG4A9f8CAAAAggABAAIDHQM4AM0CAAEYAAAAAAEAAAAAAQAA/wD/AAVPAQAAAAgABwAAAD/7AAAA+wIBAIcBAgBHAQYAAAAAAPsCAQCHAQIAKgECAAAAAIBvAAAA+wECAA4BAwBvAAAAqQEAAN4BAgBvAQEA3gEAAMYBAADeAQMA+wEEAEcBBQAAAAAA+wEEALwBAfoCAAAAnwECAfsBBQBHAQsAAAAAAPsBBQC8AQH6AwAAAJ8BAgH7AQUAvAEBUAQAAACfAQIBxgEAAN4BBQCkAQYAAABQQPsCBgCfAQIEFwEQAE0GBcAHAAAADgYNAE0GBcAHAAAAvAYG+gMAAACfBgIBTQYFwAcAAAC8BgZQBAAAAJ8GAgHGBgAAMAYFwAcAAABuAe//AgAAAIIAAgAIAzkDOgMeAwMDBAMBBAAAUEADAgCEAzsBGAADAAAAAAAAAAEDAAEBAAMAAQABAAABAAAAAwAAAQAAAAEAAAABAAMAAAAAAQAAAQAAAAABAAAAAAEAAPwACIUBAAAABwACAAAAJvsAAAAOACIA+wEAAE0AAZkAAAAAKwACAIwAAQCCAAIA+wIAAE0BAhcCAAAAPgABAfsBAQBHAQcAAAAAgPsBAABvAwMAvAEBAwQAAACfAQMC3gEBAPsBAQBHAQwAAAAAAIwBAQD7BgAATQUGFwIAAAB4BAUB+wYBAE0FBuwFAAAACQMEBT4CAwFDAAECggACAIwAAQCCAAIABgM8AgAAAAAAAABAAz0DPgMhAysAqAM/ARgAAAEAAAABAAMAAAABAAABAAAAAAACAAABAQAAAAEAAAAAAAMCAKkBAAAACgIAAAAAHU0GAJkAAAAATQcBmAEAAAAJBQYHTQcAmAEAAABNCAGZAAAAAAkGBwgmBAUGTQcAmQAAAABNCAGZAAAAAAkGBwhNCACYAQAAAE0JAZgBAAAACQcICUMFBgeeBQQDBQAAAKQDBAAADCCAnwMDAjkCAwCCAgIABQMHAwgDQANBBAAMIIAAvQNCARgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL4BAAAAEwYAAAAAbm8HAABDCAQFCQYHCOIHAwAmCQME7AgJBjAIB5kBAAAAjAkCAE0OAZkBAAAATQ8AmAIAAAAJDQ4PTQ8BmAIAAABNEACZAQAAAAkODxAmDA0OTQ8BmQEAAABNEACZAQAAAAkODxBNEAGYAgAAAE0RAJgCAAAACQ8QEUMNDg+eBQwDDQAAAKQLBgAAFECAnwsDAjkKCwAJCAkKMAgHmAIAAADiCAMAJgoFBOwJCgYwCQiZAQAAAIwKAgBNDwGZAQAAAE0QApgCAAAACQ4PEE0QAZgCAAAATRECmQEAAAAJDxARJg0OD00QAZkBAAAATRECmQEAAAAJDxARTREBmAIAAABNEgKYAgAAAAkQERJDDg8QngUNAw4AAACkDAYAABRAgJ8MAwI5CwwACQkKCzAJCJgCAAAAbwoHAE0NCJkBAAAATQ4ImQEAAAAJDA0OTQ4ImAIAAABNDwiYAgAAAAkNDg9DCwwNQwkKC00MB5kBAAAATQ0ImQEAAAAJCwwNTQ0HmAIAAABNDgiYAgAAAAkMDQ5DCgsM7A0KCfUMCA2MDQAAjA4BAEwuAAKkCwoAACRAgJ8LBAKCCwIACwIAAAAAAADgPwMHAwgFAgECA0ADQQQAFECAAi1DHOviNho/AgAAAAAAAPA/A0MEACRAgADCA0QBGAUAAAIAAAAAAPkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwABAAAAAAD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAABvgEAAAAXAgQAAAD1Af8CAAAAAAAAjAMAAKQEAQAAAABA+wUAAJ8EAgQXBEkATQoAmQIAAABNDAitAwAAAE0LDJkCAAAACQkKC4wKAAC3CQsACgAAAE0KAJgEAAAATQwIrQMAAABNCwyYBAAAAAkJCguMCgAAYAkEAAoAAACMCQAAagkCB2UAMgBvCQUAagkCB6QJAQAAAABA+woAAJ8JAgQXCScATQ8AmQIAAABNEQ2tAwAAAE0QEZkCAAAACQ4PEIwPAAC3Dh4ADwAAAE0PAJgEAAAATRENrQMAAABNEBGYBAAAAAkODxCMDwAAtw4UAA8AAACHDwIH+xABAFIRAABNEgitAwAAAE0TDa0DAAAAUhQBAE0VCMwGAAAATRYNzAYAAACfEAcCnhMPAxAAAACkDgkAACBwgJ8OAwJqDgIHbgnY/wIAAACHCQIHQwMDCW4Etv8CAAAAjAQAAIwFAACMBgAApAcBAAAAAED7CAAAnwcCBBcHGACHDQIK7AwNA28NCgBgDRIADAAAAIcMAgpDBAQMhw0CCk0PC60DAAAATQ4PmQIAAAAJDA0OQwUFDIcNAgpNDwutAwAAAE0OD5gEAAAACQwNDkMGBgxlAAIAjAwAAGoMAgpuB+f/AgAAAMYHAAAJCQUFCQoGBkMICQpvCQsAYAkJAAgAAAAJCwEB7AoLCLsZCgKkCQ0AADBwgJ8JAgJSBwkAZQABAIwHAAD7CgIADgojAPsLAgBNCguZDgAAACsKAgCMCQEAZQAeAPsMAgBNCwwXEAAAAD4KCw/7CwMARwsHAAAAAID7CwIAbw0RALwLCwMSAAAAnwsDAt4LAwD7CwMARwsMAAAAAACMCwEA+xACAE0PEBcQAAAAeA4PD/sQAwBNDxDsEwAAAAkNDg8+DA0PQwoLDFIJCgBlAAEAjAkBAOwHBwmMCQAApAoBAAAAAED7CwAAnwoCBBcKCgBNEA7AFAAAAE0PEJwVAAAADg8FAE0PDsAUAAAATQkPxhYAAABlAAIAbgr1/wIAAACkCgEAAAAAQPsLAACfCgIEFwovAIcPAg2MEAAAYBAmAA8AAABNEA7AFAAAAE0PEJwVAAAAKw8KAE0PDsAUAAAAbxEXALwPD+4YAAAAnw8DAU0PDsAUAAAAMAkPxhYAAABvEAsAhxICDewREgSeEhADEQAAAKQPGgAAZHCAnw8DAk0QDsAUAAAAUhIPAG8TFwC8EBDgGwAAAJ8QBAFNEA7AFAAAAFISBwC8EBDfHAAAAJ8QAwFlAAYATQ8OwBQAAABvERcAvA8P+h0AAACfDwMBbgrQ/wIAAACCAAEAHgMBBAAAAEADBwMQAwgCAAAAAAAA8H8DGANAA0UEACBwgAKamZmZmZm5PwItQxzr4jYaPwNGBAAwcIADPAIAAAAAAAAAQAM9Az4DIQMrAwIDRwNIApqZmZmZmck/A0kDSgQAZHCAA0sDTAMDAM0DTQEYJQABAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAQIAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAD7AAcA8gASAQEBAAAAAAEAAAAAAQABAAAAAAAAAQAAAAAAAAACAPoACQEAAAEAAAEAAAAAAAAAArYAAQAAAAEAAwAAAAEAAAEAAAAAAAIAAAEBAAAAAQAAAAAAAwACAD0BAAAAAAEAAAAAAQAAAAH9AAYAAAAAAgAAAAEAAAAAAQAAAAAAAQAAAAMAAAAAAAAAAQAAAAAAAAEAAAAAAAACAAAAAAD0AA+pAQAAAAgAAQAAAEH7AQAATQABFwAAAAD7AgAATQECeQEAAAD7AwAATQIDaQIAAABvAwMA8QIFAAMAAAD7AwAATQIDaQIAAACCAgIAKwEDAG8CAwDxACoAAgAAAMYCAAAOAQgATQMBhQQAAABSBQAAvAMDOAUAAACfAwMCUgIDAGUAAQBSAgAAbwMDAPsFAABNBAVGBgAAAA4EGAD7BwAATQYHRgYAAABNBQaFBAAAAE0EBTsHAAAAJgMCBE0FA5kIAAAAjAYAAE0HA5sJAAAATDYAAqQEDAAALKCAnwQEAlIDBABNBAOqDQAAAG8FDgBgBQIABAAAAOwDAwSCAwIA+wMAAE0CA2kCAAAAggICAA8DTgNPA1AHAAAAAAAAAAAAAAAAAAAAAANRA1IDUwNUAwcDVQNWAxsEACyggAMZAnsUrkfheoQ/AI8EVwEYAAAAAQAAAQAAAAAAAQAAAAEAAAABAQEAAAAAAAAAAgIBAAAAAQAAAAAAAAABAAAAAAAAAAAAAQABAAABAwIAAAAQAgAAAA4BCgAAAKMB+wEAAPsCAQCaAYgAAgAAAPsBAgCfAQEC+wMDAE0CA0YAAAAAKwIBAIIAAQD7BAMATQMERgAAAABNAgOFAQAAAE0FAhECAAAATQQFeAMAAAC7AgQCpAMGAAAUQICfAwICbwQHALcDCAAEAAAA+wMEAPADBQAIAACA+wMFAG8ECQBgAxMABAAAAKQDCwAAAKBA+wQAAJ8DAgQXAwoATQgHwAwAAAAOCAcATQgHwAwAAABvCgcAbwsNALwICOAOAAAAnwgEAW4D9f8CAAAAggABAE0DAmgPAAAATQUDeRAAAACMBgAATQcDexEAAABMNgACpAQUAABMIIGfBAQCTQUEqhUAAADsBAQFUgcEALwFASsWAAAAnwUDAowGAAB9BQUABgAAAG8GFwBgBgIABQAAAG8FBwBNCAR5EAAAAE0JAXsRAAAACQcICU0JBHsRAAAATQoBeRAAAAAJCAkKJgYHCKQHGQAATICBUggGAFIJBQCfBwMCpAgZAABMgIFNCgeZGgAAAPsMBgBNCwyZGgAAACYJCgtNCweYGwAAAPsNBgBNDA2YGwAAACYKCwyfCAMCUgsIALwJCCsWAAAAnwkDAm8KCQC3ChAACQAAAPsLBQD7DAcAJgoLDLsCCgKkCQYAABRAgJ8JAgJvChwAtwoGAAkAAAD7CggAJgkACowKAQBgCiEACQAAAN4HBgD7CQUA3gkHAN4ACAD7CQkA+woGAPsLBwCfCQMBggABAPsDBQD7BAcAJgIDBLsCAgKkAQYAABRAgJ8BAgJvAhwAtwIGAAEAAAD7AggAJgEAAowCAQBgAgkAAQAAAPsBBQDeAQcA3gAIAPsBCQCkAh4AAHSAgfsDBwCfAQMBggABAB8DUwNRA1gDWQNAA1oEABRAgAItQxzr4jYaPwNbAvyp8dJNYlA/AwEEAACgQAMCApqZmZmZmck/A0sDXANdA14DVgMbBABMIIEDGQNfApqZmZmZmam/AxoEAEyAgQMHAwgCexSuR+F6hD8DYAQAdICBAKoEYQEYAAAAAAEAAgAAAAEDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAQAAAQAAAAAAAP4ABQIAAQAAAAAAAAAAAQAAAQAAAAEAAAAAAAECAAAAAAAAAAAAAAEAAAAAAQAAAAAAAAAAAAAAAAAAAwAAAAAAAAEAAAAAAAAAAAABAAAAAAIBAAEBAAAAAAMAAAAAAAAAAAAAAAAAAAEAAQEAAAAAAy0CAAAABAEDAAAADfsBAADwAQoAAAAAAPsBAQDxAAcAAQAAAN4AAQD7AQIA+wMBALwBAd8BAAAAnwEDAYIAAQACAwsDTADcBGIBGAAAAAEAAAEBAAAAAANdAgAAAAcBBwAAACnwACcAAAAAgPsBAAD7AwEAhwIDAUcCBgAAAAAA+wMBAIcCAwEqAgIAAAAAgG8BAQD7AgIADgIIAPsDAwBNAgO1AgAAAA4CAQCCAAEAbwEBAKkCAADeAgIA+wIEAPsDBQBSBAEAbwUDAPsGBgCfAwQB+wMAAPADCgAEAAAA+wMEAPECBwADAAAA3gIEAPsDAwD7BQQAvAMD3wUAAACfAwMBggABAAYDYwM5A2QCMzMzMzMzwz8DCwNMAOUEZQEYCQABAgAAAAAAAAABAwABAAAAAgMBAAMBAAAAAOUAAAEAAAEBAAAAABtdAgAAAAgBAQAAABqkAQIAAAQAgIwCAQD7BQAAhwQFAE0DBJ0DAAAAnwEDAlICAQCMAwEA+wcAAIcGBwCHBQYDTQQFywQAAABgBAkAAQAAAPsHAACHBgcAhwUGA00EBcsEAAAAJgEBBJUDAwVIAPH/ggMCAAYDQANmBAAEAIADIAMsAgAAAAAAAPA/AP0EZwEYAAAAAAAAAAABAQEAAAAAAAABAAAAAAAB/gR+AgAAAAcECAAAADn7BAAA8QA2AAQAAAD7BAEARwQKAAAAAAD7BAEAUgYCALwEBPoAAAAAnwQDAfsEAQC8BARQAQAAAJ8EAgH7BAIARwQFAAAAAAD7BAIAvAQE+gIAAACfBAIBjAQBAN4EAwDeAQQA3gAAAPABBAADAACA+wQFAJ8EAQGCAAEA+wQGAJ8EAQFSBgAAvAQDlAQAAACfBAMC3gQBAPsEAQCkBQgABxhQwDAFBM0JAAAA+wQBAFIGAgC8BATuCgAAAJ8EAwH7BQEATQQFywsAAAD7BgcAvAQE5wwAAACfBAMC3gQCAIIAAQANAwMDBAMeAwsDEgMTAxQDFQQHGFDAAxYDSQNoAyMAiAVpARgAAAABAAABAAAAAAEAAAACAAABAAAAAwACAQIAAQAAAgACAAAAAAEAAAAAAgAAAAADAAAAAAAAAAOKAgAAAAoDBAAAABH7AwAAUgQAAJ8DAgL7BwEAhwYHAIcFBgNNBAUuAAAAAPsFAgBSBgQAUgcAAFIIAQBSCQIAnwUFAakFAADeBQMAggABAAEDEQCoBWoBGAAAAAEAAAAAAgAAAAAAAQABqQIAAAAFAQMAAAAI8AAGAAAAAID7AQAA+wIBAIwDAAD7BAIAnwEEAYIAAQABA2MAugVrARgAAAEAAAAAArsCAAAACQQHAAAAMPsEAABSBQAAnwQCAvsIAQCHBwgAhwYHBE0FBi4AAAAA+wYCAPEGJQAFAAAA+wYDAEcGCgAAAAAA+wYDALwGBvoBAAAAnwYCAfsGAwC8BgZQAgAAAJ8GAgGMAQAAUggFALwGApQDAAAAnwYDAt4GAwAOAwMA+wYDADADBs0EAAAA+wYDAFIIAQC8BgbuBQAAAJ8GAwHeAAQA3gUCAPsHAwBNBgfLBgAAAPsIBgC8BgbnBwAAAJ8GAwLeBgUAggABAAgDEQMDAwQDEgMWA0kDaAMjAMAFbAEYAAAAAQAAAAACAAABAAABAAAAAQAAAAEEAAAAAAEBAAAEAAAAAAEBAgAAAAAAAAACwQIAAAADAAQAAAAa+wAAAPsBAQBHAQUAAAAAAPsBAQC8AQH6AAAAAJ8BAgFvAQEA3gEAAMYBAADeAQIA+wEDAEcBCwAAAAAA+wEDALwBAfoCAAAAnwECAfsBAwC8AQFQAwAAAJ8BAgHGAQAA3gEDAIIAAgAEAx4DOgMDAwQA2gVtARgAAgAAAQAAAAMAAQABAAABAAAAAQAAAAEAA9sCAAAABwEIAAAAMPsBAAAOAQgA+wMBAE0CA2kAAAAAbwMBAPECAgADAAAAqQEAAakBAQAOAQQA+wMBAE0CA44CAAAAKwIBAG8CAwDeAAIAYAIPAAAAAAD7AwMAbwQEAG8FBQD7BgEAnwMEAfsDBADwAxUABgAAAG8DBgDeAwQA+wMFAIwEAACfAwIBggABAPsEBgD7BQcAhwMEBUcDCgAAAACA+wMAACsDBwD7AwMAbwQHAG8FBQD7BgEAnwMEAW8DCADeAwQAggABAAkDUAcAAAAAAAAAAAAAAAAAAAAAA24CAAAAAAAA6D8DCwKamZmZmZnJPwNbAzkDbwDwBXABGAAAAAAAAAAAAAABAAAAAAABAQABAAAAAAEAAAEAAQAAAAMAAAAAAAABAAAAAAEAA/ECAAAAAQABAAAAA28AAADeAAAAggABAAEDcQCCBnIBGAAAAQMDAAAABAAEAAAACvsAAABvAQAAbwIBAPsDAQCfAAQBbwACAN4AAgBvAAMA3gADAIIAAQAEA3MCmpmZmZmZuT8C16NwPQrX0z8DdACGBnUBGAAAAAAAAQABAAEHAwAAAAUBBgAAABX7AQAAbwIAAG8DAQD7BAEAnwEEAT4BAAL7AgIA8AIKAAMAAAD7AgMA8QEHAAIAAADeAQMA+wIEAPsEAwC8AgLfBAAAAJ8CAwFvAQUA3gEFAIIAAQAGA3YCmpmZmZmZuT8CAAAAAAAAFEADCwNMA3cAjAZ4ARixAAAAAAFOAAABAAABAQAAAACwAAFdAgAAAAEAAQAAAANvAAAA3gAAAIIAAQABA3kAkwZ6ARgAAAEUAwAAAAQABAAAAAz7AAAAjAEAAH0ABgABAAAA+wABAG8BAABvAgEA+wMCAJ8ABAFvAAIA3gADAIIAAQADA3sCmpmZmZmZyT8DfACXBn0BGAAAAAABAAAAAAIAARgDAAAAAQABAAAAA28AAADeAAAAggABAAEDfgCeBn8BGAAAAR8DAAAAAQABAAAAA28AAADeAAAAggABAAEDgAEAogaBAQEYAAABIwMAAAABAAEAAAADbwAAAN4AAACCAAEAAQOCAQCmBoMBARgAAAEnAwAAAAUBBgAAACCMAQEAYAEWAAAAAAD7AQAAbwIAAG8DAQD7BAEAnwEEAT4BAAL7AgIA8AIKAAMAAAD7AgMA8QEHAAIAAADeAQMA+wIEAPsEAwC8AgLfBAAAAJ8CAwFvAQUA3gEFAIIAAQD7AQAAbwIGAG8DAQD7BAEAnwEEAW8BBwDeAQUAggABAAgDhAECmpmZmZmZ2T8CAAAAAAAAJEADCwNMA4UBA4YBA28ArQaHAQEY0QAAAgAAAAABLAAAAQAAAQEAAAAA0gAAAgAAAAABAAJdAgAAAAUAAwAAACL7AAAA8AAJAAAAAID7AAEAbwEBAG8CAgD7AwIApAQGAAUQMMCfAAUBggABAPsAAADwAAkABwAAgPsAAQBvAQgAjAIAAPsDAgCkBAoACRAwwJ8ABQGCAAEA+wAAAPAACQALAACA+wABAG8BDACMAgAA+wMCAKQECgAJEDDAnwAFAYIAAQCCAAEADQOIAQOJAQKamZmZmZm5PwMTAxQDigEEBRAwwAOLAQOMAQONAQQJEDDAA44BA48BALkGkAEBGAAAAAEAAAAAAAABAwAAAQAAAAAAAAEDAAABAAAAAAAAAQI6AwAAAAcBAAAAABSkAQEAAAAAQLwCAGgCAAAAnwICAJ8BAARRAQkATQYFugMAAADwBgYABAAAgE0GBbsFAAAA8AYCAAYAAICCBQIAbgH2/wIAAIDGAQAAggECAAcDkQEEAAAAQAMnAzEDkgEDkwEDNQDKBpQBARgAAAAAAAAAAQAAAAAAAAAB/gAFAEsDAAAACQEQAAAAhAGMAQEAjAIBAPsEAAAmAwAE3gAAAKkEAAD7BQEAjAYAAGAGBAAFAAAA+wYBACYFBgPeBQEA+wUCAPAFCwAAAACA+wUBAIwGAAB9BQcABgAAAPsFAwBvBgEAbwcCAPsIBACfBQQBZQApAPsFAgDwBQcAAwAAgPsFAwBvBgQAbwcFAPsIBACfBQQBggABAPsFAgDwBQoABgAAgPsFAwBvBgcAbwcCAPsIBACfBQQB+wUFAFIGAACfBQIBZQAUAPsFAgDwBQ0ACAAAAPsFAgDwBQoACQAAAPsFAgDwBQcACgAAAPsFAgDwBQQAAwAAAPsFAgDwBQYACwAAgPsFBgCfBQEBbwEMAIwCAQCpBAEA+wUHAG8HDQC8BQW4DgAAAJ8FAwIOBRsAbwgPALwGBQMQAAAAnwYDAg4GFgD7BggAUgcFAJ8GAgIOBggATQcG7BEAAADeBwkAxgcAADAHBiQSAAAAlQcAE94HCgD7BwoAYAcFAAAAAACMBwAA3gcKAG8HFADeBwkA+wcLAJ8HAQGCAAEA+wYMAPsHDQBHBwUAAAAAAPsHDQC8Bwf6FQAAAJ8HAgFvBxYA3gcMAMYHAADeBw4A+wcPAEcHCwAAAAAA+wcPALwHB/oXAAAAnwcCAfsHDwC8BwdQGAAAAJ8HAgHGBwAA3gcPAG8GFADeBgkAxgYAAN4GDgCMBgAA3gYKAIIAAQAZA3wDewKamZmZmZnJPwOAAQOVAQIAAAAAAADgPwNbAwsDcQN5A34DggECmpmZmZmZuT8DlgEDlwEDmAEDIQMrA5kBAjMzMzMzM9M/A4gBAx4DOgMDAwQA1QaaAQEYewEBAAEDAgAAAAEAAAMAAAAAAAABAAAAAAABAAABAAAAAAEBAAABAAAAAAEAAAACAAABAAABAAABAAABAAACAAEBAQQAAAAAAQAAAAAAAQAAAgEAAAIAAAEAAwAAAQABAAMAAFMCAAABAAAAAwABAAEAAAEAAAABAAAAAQClAAEAAQAC2wIAAAACAAMAAAAQ+wEAAE0AASQAAAAARwAGAAAAAID7AAEAvAAAUQEAAACfAAIBggABAPsAAgCkAQQAAAwggJ8BAQCfAAABggABAAUDmQEDmwEDnAEDnQEEAAwggACkBwABGAAAAAAAAQAAAAECAAAAAAGlAwAAAAgAAQAAABH7AAAADgAOAPsAAAC8AADNAAAAAJ8AAgRkAAcAjAcAALwFBPoBAAAAnwUDAbwFBFACAAAAnwUCAW4A+P8CAAAAggABAAMDngEDAwMEAK0HAAEYAAABAAAAAAEAAAABAAD+AAWuAwAAAAIAAQAAAAakAAIAAAQAgNkBAAASAgAAnwACAYIAAQADA58BA6ABBAAEAIABK6wHAAEYAAAAAAAIrQMAAAADAQEAAAAF+wEAALwBAVEAAAAAnwECAYIAAQABA5sBALgHBAEYAAAAAAG5AwAAAE0BAgAABgMAAAUBB8kG+wIAAE0BAu8AAAAAnwEBAm8EAQC8AgADAgAAAJ8CAwIrAiEApAMEAAAAMIBvBAUAnwMCAlICAwBvAwEAMAMCugYAAAAwAAIkBwAAAKQECQAAAIBATQMEJAcAAABvBQoAvAMDAwIAAACfAwMCbwULALwDAwMCAAAAnwMDArwDA2gMAAAAnwMCBGQDBQC8CAc6DQAAAJ8IAgIwAggkBwAAAG4D+v8CAAAAbwUOALwDAAMCAAAAnwMDAm8EDwBvBxAAvAUDAwIAAACfBQMCjAYAAIwHAADiCBMAjAkAADAJCJkRAAAAjAkAADAJCJgSAAAAjAkAAG8KFADGCwAAxgwAAMYNAACMDgEA/w8AAAAAAAD/EAAAAAAAAOIRKAD/EgAAAwAAAOITKwBvFCwAMBQT9CkAAACMFAEAMBQTyyoAAADiFCsAbxUtADAVFPQpAAAAjBUBADAVFMsqAAAA4hUrAG8WLgAwFhX0KQAAAIwWCQAwFhXLKgAAAMUSEwQBAAAAMBIR8hUAAAD/EgAAAQAAAOITKwBvFC8AMBQT9CkAAACMFAoAMBQTyyoAAADFEhMCAQAAADASEf8WAAAA/xIAAAEAAADiEysAbxQwADAUE/QpAAAAjBQKADAUE8sqAAAAxRITAgEAAAAwEhE2FwAAAP8SAAABAAAA4hMrAG8UMQAwFBP0KQAAAIwUCgAwFBPLKgAAAMUSEwIBAAAAMBIRNxgAAAD/EgAAAQAAAOITKwBvFDIAMBQT9CkAAACMFAoAMBQTyyoAAADFEhMCAQAAADASEUsZAAAA/xIAAAEAAADiEysAbxQzADAUE/QpAAAAjBQKADAUE8sqAAAAxRITAgEAAAAwEhEzGgAAAP8SAAABAAAA4hMrAG8UNAAwFBP0KQAAAIwUCgAwFBPLKgAAAMUSEwIBAAAAMBIRTRsAAAD/EgAAAQAAAOITKwBvFDUAMBQT9CkAAACMFAoAMBQTyyoAAADFEhMCAQAAADASEQMcAAAA/xIAAAEAAADiEysAbxQ2ADAUE/QpAAAAjBQKADAUE8sqAAAAxRITAgEAAAAwEhHUHQAAAP8SAAABAAAA4hMrAG8UNwAwFBP0KQAAAIwUCgAwFBPLKgAAAMUSEwIBAAAAMBIRRh4AAAD/EgAAAQAAAOITKwBvFDgAMBQT9CkAAACMFAoAMBQTyyoAAADFEhMCAQAAADASEZwfAAAA/xIAAAEAAADiEysAbxQ5ADAUE/QpAAAAjBQKADAUE8sqAAAAxRITAgEAAAAwEhGiIAAAAP8SAAABAAAA4hMrAG8UOgAwFBP0KQAAAIwUCgAwFBPLKgAAAMUSEwIBAAAAMBIRWSEAAAD/EgAAAQAAAOITKwBvFDsAMBQT9CkAAACMFAoAMBQTyyoAAADFEhMCAQAAADASEeIiAAAA/xIAAAMAAADiEysAbxQ8ADAUE/QpAAAAjBQKADAUE8sqAAAA4hQrAG8VPQAwFRT0KQAAAIwVCgAwFRTLKgAAAOIVKwBvFj4AMBYV9CkAAACMFgoAMBYVyyoAAADFEhMEAQAAADASEeojAAAA/xIAAAMAAADiEysAbxQ/ADAUE/QpAAAAjBQKADAUE8sqAAAA4hQrAG8VQAAwFRT0KQAAAIwVCgAwFRTLKgAAAOIVKwBvFkEAMBYV9CkAAACMFgoAMBYVyyoAAADFEhMEAQAAADASEWMkAAAA/xIAAAMAAADiEysAbxRCADAUE/QpAAAAjBQKADAUE8sqAAAA4hQrAG8VQwAwFRT0KQAAAIwVCgAwFRTLKgAAAOIVKwBvFkQAMBYV9CkAAACMFgoAMBYVyyoAAADFEhMEAQAAADASEYUlAAAA/xIAAAEAAADiEysAbxRFADAUE/QpAAAAjBQKADAUE8sqAAAAxRITAgEAAAAwEhFwJgAAAP8SAAABAAAA4hMrAG8URgAwFBP0KQAAAIwUCgAwFBPLKgAAAMUSEwIBAAAAMBIRhCcAAAD/EgAAAAAAAP8TAAAAAAAAUhQSAOIVRwCpFgAAMBYVWSEAAACpFgAAMBYV4iIAAACpFgEAMBYV6iMAAACpFgEAMBYVYyQAAACpFgEAMBYVhSUAAACpFgAAMBYVcCYAAACpFgAAMBYVhCcAAACkFkoAACSBhKQXTAAAALBEnxcBAJ8WAAHZFgAAEgASABIAEwASAQf/xhcAAMYYAADGGQAAxhoAAMYbAADZHAEAEgEZ/xIBGP8SARv/EgEa/9kdAgASARj/EgEa/xIBGf8SARv/2R4DABIBGP8SARn/EgEa/xIBG/8SART/EgASABIAEwDZHwQAEgEZ/xIBGP8SARv/EgEa/xIAEgASAB4AEgEU/xIAAwASABAA2SAFABIBCv8SART/EgAWABIAEgASABMAEgAfABIBCf/ZIQYAEgAQABIBAv8SACEAEgAgABIADwASAAMA2SIHABIAEQASACEATSUCa00AAABSJyIAvCUl504AAACfJQMAvCMB/U8AAACfIwABTSUCvVAAAABSJyIAvCUl504AAACfJQMAvCMB/U8AAACfIwAB2SUIABIAEAC8IwH9TwAAAJ8jAwEOAwUAbyVRALwjA7hSAAAAnyMDAmUAAQDGIwAAKyMTAPskAQC8JCQLUwAAAJ8kAgIOJA0ApCQEAAAAMIBvJVEAnyQCAlIjJAC7ASMDUiUjAKQkVQAAAEBFnyQCAjADJCQHAAAAZQABAFIjAwAOIxEAvCQjzVYAAACfJAICpCVYAAAAcEVSJiQAnyUCBFElBwCMLAAAvCop+lkAAACfKgMBvCopUFoAAACfKgIBbiX4/wIAAICkJFwAAACwRVIlEQCfJAIEFyQEAFIpIQBSKicAUisoAJ8pAwFuJPv/AgAAALwkAmgMAAAAnyQCBGQkEQBvK10AvCko3l4AAACfKQMCDikMAE0pKLoGAAAA/yoAAAAAAABqKhEpUikhAE0qKLoGAAAATSwougYAAACHKxEsnykDAW4k7v8CAAAAbyRfAIwlAACMJgAAqScAANkoCQASAQr/EgAVABIBJ/8SAQv/EgEN/xIBDP8SART/2SkKABIAAwASAQX/wCpgAMArYQDZLA0AEgEU/xIAKwASAAMAEgEF/9ktDgASAAMA2S4PABIBFP8SABIAEgAtABIAAwASAQT/EgEG/xIBCP8SAQf/EgEJ/xIALADZLxAAEgEK/xIBDv8SAQz/2TARABIBCv8SABUAEgEn/xIBDP8SAQ7/EgEX/xIAAwDZMRIAEgAQANkyEwASAQv/EgEM/xIBDf8SAQ7/EgEK/xIAHwASABYAEgAwANkXFAASADEAEgAQABIAMgASASf/bzMUAMY0AADGNQAAxjYAAMY3AADZOBUAEgE3/xIBM/8SAAMA2TcWABIAMQASABAAEgE1/xIBNP8SATP/EgE2/xIAOADZORcAEgEz/xIBNv8SATX/EgE0/9k6GAASASf/EgADABIBBv8SARf/EgEE/xIALgASABUAEgEK/9k7GQASAQT/2TwaABIBF/8SAAMAEgEm/xIBBP/ZPRsAEgEX/xIAAwASAQr/EgEO/xIBDP8SAQT/2T4cABIBBP/ZPx0AEgEm/xIBF/8SAAMAEgEE/9lAHgASAQT/2UEfABIBBP/ZQiAAEgEE/9lDIQASARf/EgADABIBCv8SAQ7/EgEM/xIBBP/ZRCIAEgEk/xIBN/8SAAMAwEViAIxGAADZRyQAEgFG/xIBJv8SAQT/EgEX/xIAAwASAC4AEgAoABIAAAASAEUAEgEk/xIBJf8SAEQAEgEz/xIBNv8SATX/EgE0/01KA8djAAAAUkw7ALxKSudOAAAAn0oDALxIAf1PAAAAn0gAAU1KA+lkAAAAUkw6ALxKSudOAAAAn0oDALxIAf1PAAAAn0gAAU1KA8tlAAAAUkw8ALxKSudOAAAAn0oDALxIAf1PAAAAn0gAAU1KA6BmAAAAUkw9ALxKSudOAAAAn0oDALxIAf1PAAAAn0gAAU1KA3lnAAAAUkw+ALxKSudOAAAAn0oDALxIAf1PAAAAn0gAAU1KA45oAAAAUkw/ALxKSudOAAAAn0oDALxIAf1PAAAAn0gAAU1KAxBpAAAAUkxAALxKSudOAAAAn0oDALxIAf1PAAAAn0gAAU1KA7BqAAAAUkxBALxKSudOAAAAn0oDALxIAf1PAAAAn0gAAU1KA5lrAAAAUkxCALxKSudOAAAAn0oDALxIAf1PAAAAn0gAAU1KAzdsAAAAUkxDALxKSudOAAAAn0oDALxIAf1PAAAAn0gAAU1IACQHAAAAR0gHAAAAAABSSBcAb0kVAG9KbQBSSwMAn0gEAW8EDwD7SwEATUpL/W4AAADZTCUAEgAAABIAAQASAEcAvEpKx28AAACfSgMAvEgB/U8AAACfSAAB2UomABIBI/+8SAH9TwAAAJ9IAwH/SAEAAAAAANlJJwASAAEAMElIUFoAAADBAgAAgkgCAHADGwOhAQMhAzAEAAAwgAOiAQMxA5kBA6MBBAAAgEADpAEDpQEDJwOmAQOnAQNvAz4DBwMIBQIREgM6AzkDCwMKA4QBA4YBA3MDewN2A5UBA4kBA4wBA48BA6gBA6kBA6oBA6sBA6wBA60BA64BBRMVFhcYGRobHB0eHyAhIiMkJSYnAzIDLAUCKSoDrwEDsAEDsQEDsgEDswEDtAEDtQEDtgEDtwEDuAEDuQEDugEDuwEDvAEDvQEDvgEDvwEDwAEDwQEDwgEDwwEDxAEDxQEDxgEDxwEDyAEDyQEFByEiIyQlJicDQAPKAQQAJIGEA8sBBAAAsEQDIgMjA8wBAyYDzQEDlwEDzgEDzwEEAABARQOeAQORAQQAAHBFAwMDBAMBBAAAsEUDNQM2A4gBBhAGEQYoA9ABA1sDdAN3A3kD0QEDfgOAAQOCAQOFAQKamZmZmZm5PwPSAQPTASgAAQIDBAULDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKiwtBQABBQAAAAAEAAAAAQEAAAAAAQAAAQABAAAAAAAAAAAAAAAA9wAAAQAAAAD/AAUAAAABAgAAAAMBAQAAAAAAAAMEAQHqAQIAAgABAQABAAAAAAAAAQAAAAAAAAEAAAAAAAAAAPYABQABAAAAAAAAAAD/AAMAAQAAAAAAAAAA/wAEAAEA9AAAAAAAAP8AAwABAAAAAAAAAAD/AAMAAQAAAAAAAAD6/wADAAEAAAAAAAAAAP8AAwABAAAAAAAAAAD/AAMAAfcAAAAAAAAA/wADAAEAAAAAAAAAAP8AAwABAAAAAAAA+gD/AAMAAQAAAAAAAAAA/wADAAEAAAAAAAAAAP8AAwD4AAAAAAAAAAD/AAMAAQAAAAAAAAEAAAAAAAABAAAAAP0AAAD9AAUAAQAAAAAAAAEAAAAAAAABAAAAAAAAAAD9+wUAAQAAAAAAAAEAAAAAAAABAAAAAAAAAAD9AAUAAQD2AAAAAAAA/wADAAEAAAAAAAAAAP8ABQABAAEDAAAAAPMAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAgAAABICAAAA6AAAAAAHAAAAABEAAAAAAAAAEwAAAAAAAAAAAA0AAADIAAAAHAAAAAAAAFsAAAwAAAAAAAAAAAEAAAAAAAAAAHwAAAAACwAAAAAAAAEBAAAAAAEAAAAAAQAAAAAAAAAD7gEAAAEAAAAAAQAAAAEAAP4ABgAAAAABAAAA/wADAAD1AQAAAAABAAAAAAEAAAAAAAD9AAoBAgYEAAAAAAAAAOkAABUFCwAAAABCABsAAAAAAAAAAAAAMgAAAAkAAAAAQwAAGAALAAAAAAAAAAAgAAAAAAsBAQECAgAAAAYAAAClAAAAGgAAAAAWAAAAAAAAAAASAAQAAAAABgAAAAAAALQABAAAAAAHAAQABAAHAAAAAAAADAAAABEJAgAAAAAAvgAAAAAAAAAAAAA9AAAAAAAAAAABAAAAAAAAAAABAADBAAAAAAABAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAP0BAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAAABAAAA/AAAAAACAAAAAgAAAAABBAAAAAAAAAAAAAAAAAgAAADvCwABAAAAAwAGAAAACQAAABcAAAAHAAAADAAAAAYAAAAJAAAABgAAAAkAAAADAAAABQAAAAoAAAANAAAAGgAAADgAAACFAAAAFQAAAAsAAAA7AAAAvQAAAFsAAABTAAAAQgAAAD8AAAADAAAABAAAABEAAAAABQAAAQIAGKMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DAKEGAAAATQIDdgcAAACfAQICpAIBAAAAAEBvBAgAvAICFgMAAACfAgMCwAMJABIAAQASAAIAggMCAAoD1AEEAAAAQAPVAQPWAQPXAQQAAEBAA9gBA9kBA9oBBi4BLgEAARgAAAAAAAAAAQAAAAAAAAEAAAAAAAIAAAABAAAAAC/KGivrM1dQffjeQX9vtnCx6iKttbPei35dYU8UUcEXvSx9Mfx+AFZ+

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.Maid)
local v_u_3 = game:GetService("RunService")
return function(p_u_4)
	-- upvalues: (copy) v_u_2, (copy) v_u_3
	local v_u_5 = v_u_2.new()
	local v_u_6 = p_u_4:FindFirstChild("AnimationsFolder")
	if not v_u_6 then
		v_u_6 = Instance.new("Folder")
		v_u_6.Name = "AnimationsFolder"
		v_u_6.Parent = p_u_4
		for _, v7 in script.Parent:FindFirstChild("Res"):FindFirstChild("DefaultAnimations"):GetChildren() do
			v7:Clone().Parent = v_u_6
		end
	end
	local v_u_8 = p_u_4:FindFirstChild("Humanoid")
	local v_u_9 = "Standing"
	local v_u_10 = v_u_8:FindFirstChild("ScaleDampeningPercent")
	local v_u_11 = 0
	local v_u_12 = 0
	local v_u_13 = {
		["x"] = 0,
		["y"] = 0
	}
	local v_u_14 = 0
	local v_u_15 = ""
	local v_u_16 = nil
	local v_u_17 = nil
	local v_u_18 = nil
	local v_u_19 = 1
	local v_u_20 = {}
	local v_u_21 = {}
	local v_u_22 = {
		["idle"] = {
			{
				["id"] = "http://www.roblox.com/asset/?id=507766666",
				["weight"] = 1
			},
			{
				["id"] = "http://www.roblox.com/asset/?id=507766951",
				["weight"] = 1
			},
			{
				["id"] = "http://www.roblox.com/asset/?id=507766388",
				["weight"] = 9
			}
		},
		["walk"] = {
			{
				["id"] = "http://www.roblox.com/asset/?id=507777826",
				["weight"] = 10
			}
		},
		["run"] = {
			{
				["id"] = "http://www.roblox.com/asset/?id=507767714",
				["weight"] = 10
			}
		},
		["swim"] = {
			{
				["id"] = "http://www.roblox.com/asset/?id=507784897",
				["weight"] = 10
			}
		},
		["swimidle"] = {
			{
				["id"] = "http://www.roblox.com/asset/?id=507785072",
				["weight"] = 10
			}
		},
		["jump"] = {
			{
				["id"] = "http://www.roblox.com/asset/?id=507765000",
				["weight"] = 10
			}
		},
		["fall"] = {
			{
				["id"] = "http://www.roblox.com/asset/?id=507767968",
				["weight"] = 10
			}
		},
		["climb"] = {
			{
				["id"] = "http://www.roblox.com/asset/?id=507765644",
				["weight"] = 10
			}
		},
		["sit"] = {
			{
				["id"] = "http://www.roblox.com/asset/?id=2506281703",
				["weight"] = 10
			}
		},
		["toolnone"] = {
			{
				["id"] = "http://www.roblox.com/asset/?id=507768375",
				["weight"] = 10
			}
		},
		["toolslash"] = {
			{
				["id"] = "http://www.roblox.com/asset/?id=522635514",
				["weight"] = 10
			}
		},
		["toollunge"] = {
			{
				["id"] = "http://www.roblox.com/asset/?id=522638767",
				["weight"] = 10
			}
		},
		["wave"] = {
			{
				["id"] = "http://www.roblox.com/asset/?id=507770239",
				["weight"] = 10
			}
		},
		["point"] = {
			{
				["id"] = "http://www.roblox.com/asset/?id=507770453",
				["weight"] = 10
			}
		},
		["dance"] = {
			{
				["id"] = "http://www.roblox.com/asset/?id=507771019",
				["weight"] = 10
			},
			{
				["id"] = "http://www.roblox.com/asset/?id=507771955",
				["weight"] = 10
			},
			{
				["id"] = "http://www.roblox.com/asset/?id=507772104",
				["weight"] = 10
			}
		},
		["dance2"] = {
			{
				["id"] = "http://www.roblox.com/asset/?id=507776043",
				["weight"] = 10
			},
			{
				["id"] = "http://www.roblox.com/asset/?id=507776720",
				["weight"] = 10
			},
			{
				["id"] = "http://www.roblox.com/asset/?id=507776879",
				["weight"] = 10
			}
		},
		["dance3"] = {
			{
				["id"] = "http://www.roblox.com/asset/?id=507777268",
				["weight"] = 10
			},
			{
				["id"] = "http://www.roblox.com/asset/?id=507777451",
				["weight"] = 10
			},
			{
				["id"] = "http://www.roblox.com/asset/?id=507777623",
				["weight"] = 10
			}
		},
		["laugh"] = {
			{
				["id"] = "http://www.roblox.com/asset/?id=507770818",
				["weight"] = 10
			}
		},
		["cheer"] = {
			{
				["id"] = "http://www.roblox.com/asset/?id=507770677",
				["weight"] = 10
			}
		}
	}
	local v_u_23 = {}
	local v_u_24 = {}
	local v_u_25 = v_u_23
	local v_u_26 = {
		["wave"] = false,
		["point"] = false,
		["dance"] = true,
		["dance2"] = true,
		["dance3"] = true,
		["laugh"] = false,
		["cheer"] = false
	}
	math.randomseed(tick())
	local function v_u_29()
		-- upvalues: (copy) v_u_23, (copy) v_u_24, (ref) v_u_12
		for _, v27 in pairs(v_u_23) do
			if v27.track then
				v27.track:Stop()
				v27.track:Destroy()
				v27.track = nil
			end
		end
		for _, v28 in pairs(v_u_24) do
			if v28.track then
				v28.track:Stop()
				v28.track:Destroy()
				v28.track = nil
			end
		end
		v_u_12 = 0
	end
	local v_u_30 = nil
	local v_u_31 = nil
	local v_u_32 = nil
	local v_u_33 = nil
	local v_u_34 = nil
	local function v_u_35(_)
		-- upvalues: (ref) v_u_31, (ref) v_u_32, (ref) v_u_33, (ref) v_u_34, (ref) v_u_25, (copy) v_u_23, (copy) v_u_24
		if v_u_31 == 0 or (v_u_32 == 0 or (v_u_33 == 0 or v_u_34 == 0)) then
			local _ = v_u_25 == v_u_23
			v_u_25 = v_u_24
			return
		elseif v_u_23.run and v_u_23.walk then
			if v_u_25 ~= v_u_23 then
				v_u_25 = v_u_23
				warn("Strafing reenabled")
			end
		else
			if v_u_25 == v_u_23 then
				warn("Strafe blending disabled.  Run and walk must be strafing-friendly.")
			end
			v_u_25 = v_u_24
		end
	end
	local function v_u_40()
		-- upvalues: (ref) v_u_32, (ref) v_u_31, (ref) v_u_34, (ref) v_u_33, (copy) v_u_23, (copy) v_u_35, (ref) v_u_25, (copy) v_u_8, (copy) v_u_21
		v_u_32 = 0
		v_u_31 = 0
		v_u_34 = 0
		v_u_33 = 0
		for _, v36 in pairs(v_u_23) do
			local v37 = v36.lv
			if v37 then
				if v_u_31 < v37.x then
					v_u_31 = v37.x
				end
				if v_u_33 < v37.y then
					v_u_33 = v37.y
				end
				if v37.x < v_u_32 then
					v_u_32 = v37.x
				end
				if v37.y < v_u_34 then
					v_u_34 = v37.y
				end
			end
		end
		v_u_35()
		for v38, v39 in pairs(v_u_25) do
			v39.track = v_u_8:LoadAnimation(v_u_21[v38][1].anim)
			v39.track.Priority = Enum.AnimationPriority.Core
		end
	end
	local function v_u_45(p41, p42)
		-- upvalues: (ref) v_u_15, (ref) v_u_25, (copy) v_u_29, (copy) v_u_23, (copy) v_u_24, (copy) v_u_40, (ref) v_u_14
		local v43
		if v_u_15 == "walk" and v_u_25[p41] then
			v_u_29()
			v43 = true
		else
			v43 = false
		end
		if p42 then
			v_u_23[p41] = {
				["lv"] = p42,
				["speed"] = p42.Magnitude
			}
		else
			v_u_23[p41] = nil
		end
		if p41 == "run" or p41 == "walk" then
			if p42 then
				v_u_24[p41] = v_u_23[p41]
			else
				local v44 = p41 == "run" and 12.8 or 6.4
				v_u_24[p41] = {
					["lv"] = Vector2.new(0, v44),
					["speed"] = v44
				}
				v_u_23[p41] = nil
			end
		end
		if v43 then
			v_u_40()
			v_u_14 = 0
		end
	end
	local function v_u_73(p_u_46, p_u_47)
		-- upvalues: (copy) v_u_21, (ref) v_u_6, (copy) v_u_73, (copy) v_u_45, (copy) v_u_20, (copy) v_u_8
		if v_u_21[p_u_46] ~= nil then
			for _, v48 in pairs(v_u_21[p_u_46].connections) do
				v48:disconnect()
			end
		end
		v_u_21[p_u_46] = {}
		v_u_21[p_u_46].count = 0
		v_u_21[p_u_46].totalWeight = 0
		v_u_21[p_u_46].connections = {}
		local v49 = v_u_6:FindFirstChild(p_u_46)
		if v49 ~= nil then
			local v50 = v_u_21[p_u_46].connections
			local v51 = v49.ChildAdded
			local function v52(_)
				-- upvalues: (ref) v_u_73, (copy) p_u_46, (copy) p_u_47
				v_u_73(p_u_46, p_u_47)
			end
			table.insert(v50, v51:connect(v52))
			local v53 = v_u_21[p_u_46].connections
			local v54 = v49.ChildRemoved
			local function v55(_)
				-- upvalues: (ref) v_u_73, (copy) p_u_46, (copy) p_u_47
				v_u_73(p_u_46, p_u_47)
			end
			table.insert(v53, v54:connect(v55))
			for _, v56 in pairs(v49:GetChildren()) do
				if v56:IsA("Animation") then
					local v57 = v56:FindFirstChild("Weight")
					local v58 = v57 == nil and 1 or v57.Value
					v_u_21[p_u_46].count = v_u_21[p_u_46].count + 1
					local v59 = v_u_21[p_u_46].count
					v_u_21[p_u_46][v59] = {}
					v_u_21[p_u_46][v59].anim = v56
					v_u_21[p_u_46][v59].weight = v58
					v_u_21[p_u_46].totalWeight = v_u_21[p_u_46].totalWeight + v_u_21[p_u_46][v59].weight
					local v60 = v_u_21[p_u_46].connections
					local v61 = v56.Changed
					local function v62(_)
						-- upvalues: (ref) v_u_73, (copy) p_u_46, (copy) p_u_47
						v_u_73(p_u_46, p_u_47)
					end
					table.insert(v60, v61:connect(v62))
					local v63 = v_u_21[p_u_46].connections
					local v64 = v56.ChildAdded
					local function v65(_)
						-- upvalues: (ref) v_u_73, (copy) p_u_46, (copy) p_u_47
						v_u_73(p_u_46, p_u_47)
					end
					table.insert(v63, v64:connect(v65))
					local v66 = v_u_21[p_u_46].connections
					local v67 = v56.ChildRemoved
					local function v68(_)
						-- upvalues: (ref) v_u_73, (copy) p_u_46, (copy) p_u_47
						v_u_73(p_u_46, p_u_47)
					end
					table.insert(v66, v67:connect(v68))
					v_u_45(p_u_46, (v56:GetAttribute("LinearVelocity")))
				end
			end
		end
		if v_u_21[p_u_46].count <= 0 then
			for v69, v70 in pairs(p_u_47) do
				v_u_21[p_u_46][v69] = {}
				v_u_21[p_u_46][v69].anim = Instance.new("Animation")
				v_u_21[p_u_46][v69].anim.Name = p_u_46
				v_u_21[p_u_46][v69].anim.AnimationId = v70.id
				v_u_21[p_u_46][v69].weight = v70.weight
				v_u_21[p_u_46].count = v_u_21[p_u_46].count + 1
				v_u_21[p_u_46].totalWeight = v_u_21[p_u_46].totalWeight + v70.weight
			end
		end
		for _, v71 in pairs(v_u_21) do
			for v72 = 1, v71.count do
				if v_u_20[v71[v72].anim.AnimationId] == nil then
					v_u_8:LoadAnimation(v71[v72].anim)
					v_u_20[v71[v72].anim.AnimationId] = true
				end
			end
		end
	end
	local function v76(p74)
		-- upvalues: (copy) v_u_22, (copy) v_u_73
		local v75 = v_u_22[p74.Name]
		if v75 == nil then
			if p74:isA("StringValue") then
				v_u_22[p74.Name] = {}
				v_u_73(p74.Name, v_u_22[p74.Name])
			end
		else
			v_u_73(p74.Name, v75)
		end
	end
	v_u_5:GiveTask(v_u_6.ChildAdded:connect(v76))
	v_u_5:GiveTask(v_u_6.ChildRemoved:connect(v76))
	v_u_5:GiveTask(function()
		-- upvalues: (copy) v_u_21
		for _, v77 in v_u_21 do
			for _, v78 in v77.connections do
				v78:Disconnect()
			end
		end
	end)
	local v_u_79
	if v_u_8 then
		v_u_79 = v_u_8:FindFirstChildOfClass("Animator")
	else
		v_u_79 = nil
	end
	if not v_u_79 then
		if v_u_3:IsServer() then
			v_u_79 = Instance.new("Animator")
			assert(v_u_79).Parent = v_u_8
		else
			v_u_79 = v_u_8
		end
	end
	local v_u_80, v_u_81, v_u_82, v_u_83
	if v_u_79 then
		local v84 = v_u_79:GetPlayingAnimationTracks()
		v_u_80 = v_u_25
		v_u_81 = v_u_15
		v_u_82 = v_u_14
		v_u_83 = v_u_12
		for _, v85 in ipairs(v84) do
			v85:Stop(0)
			v85:Destroy()
		end
	else
		v_u_80 = v_u_25
		v_u_81 = v_u_15
		v_u_82 = v_u_14
		v_u_83 = v_u_12
	end
	for v86, v87 in pairs(v_u_22) do
		v_u_73(v86, v87)
	end
	for _, v88 in v_u_6:GetChildren() do
		if v88:isA("StringValue") then
			v_u_22[v88.Name] = {}
			v_u_73(v88.Name, v_u_22[v88.Name])
		end
	end
	local v_u_89 = "None"
	local v_u_90 = 0
	local v_u_91 = 0
	local v_u_92 = false
	local function v_u_96()
		-- upvalues: (ref) v_u_81, (copy) v_u_26, (ref) v_u_92, (ref) v_u_16, (ref) v_u_18, (ref) v_u_17, (ref) v_u_80
		local v93 = v_u_81
		local v94 = v_u_26[v93] ~= nil and v_u_26[v93] == false and "idle" or v93
		if v_u_92 then
			v94 = "idle"
			v_u_92 = false
		end
		v_u_81 = ""
		v_u_16 = nil
		if v_u_18 ~= nil then
			v_u_18:disconnect()
		end
		if v_u_17 ~= nil then
			v_u_17:Stop()
			v_u_17:Destroy()
			v_u_17 = nil
		end
		for _, v95 in pairs(v_u_80) do
			if v95.track then
				v95.track:Stop()
				v95.track:Destroy()
				v95.track = nil
			end
		end
		return v94
	end
	local function v_u_112(p97, p98, p99, p100, p101, p102)
		local v103 = 0.5 * (p101 + p102)
		local v104 = {
			["x"] = (p100 - p101) / v103
		}
		local v105 = p98.x * p97.y - p98.y * p97.x
		local v106 = p98.x * p97.x + p98.y * p97.y
		v104.y = 2 * -math.atan2(v105, v106)
		local v107 = {
			["x"] = (p102 - p101) / v103
		}
		local v108 = p98.x * p99.y - p98.y * p99.x
		local v109 = p98.x * p99.x + p98.y * p99.y
		v107.y = 2 * -math.atan2(v108, v109)
		local v110 = 0.0001 + (v107.x * v107.x + v107.y * v107.y)
		local v111 = 1 - (v104.x * v107.x + v104.y * v107.y) / v110
		return math.clamp(v111, 0, 1)
	end
	local function v_u_138(p113, p114)
		-- upvalues: (ref) v_u_80, (copy) v_u_112, (copy) v_u_8, (ref) v_u_10
		local v115 = {}
		local v116 = 0
		for v117, v118 in pairs(v_u_80) do
			if p113.x * v118.lv.x < 0 or p113.y * v118.lv.y < 0 then
				v115[v117] = 0
			else
				v115[v117] = (1 / 0)
				for _, v119 in pairs(v_u_80) do
					if p113.x * v119.lv.x >= 0 and p113.y * v119.lv.y >= 0 then
						local v120 = v115[v117]
						local v121 = v_u_112(p113, v118.lv, v119.lv, p114, v118.speed, v119.speed)
						v115[v117] = math.min(v120, v121)
					end
				end
				v116 = v116 + v115[v117]
			end
		end
		local v122 = 0
		local v123 = 0
		local v124 = 0
		for v125, v126 in pairs(v_u_80) do
			if v115[v125] / v116 > 0.1 then
				v122 = v122 + v115[v125]
				v123 = v123 + v115[v125] * v126.lv.x
				v124 = v124 + v115[v125] * v126.lv.y
			else
				v115[v125] = 0
			end
		end
		local v127 = v123 * v123 + v124 * v124
		local v128
		if v127 > 0.0001 then
			local v129 = p114 * p114 / v127
			v128 = math.sqrt(v129)
		else
			v128 = 0
		end
		local v130
		if v_u_8 and v_u_8.AutomaticScalingEnabled then
			v130 = v_u_8.HipHeight / 2
			if v_u_10 == nil then
				v_u_10 = v_u_8:FindFirstChild("ScaleDampeningPercent")
			end
			if v_u_10 ~= nil then
				v130 = 1 + (v_u_8.HipHeight - 2) * v_u_10.Value / 2
			end
		else
			v130 = 1
		end
		local v131 = v128 / v130
		local v132 = 0
		for _, v133 in pairs(v_u_80) do
			if v133.track.IsPlaying then
				v132 = v133.track.TimePosition
				break
			end
		end
		for v134, v135 in pairs(v_u_80) do
			if v115[v134] > 0 then
				if not v135.track.IsPlaying then
					v135.track:Play(0.2)
					v135.track.TimePosition = v132
				end
				local v136 = v115[v134] / v122
				local v137 = math.max(0.0001, v136)
				v135.track:AdjustWeight(v137, 0.2)
				v135.track:AdjustSpeed(v131)
			else
				v135.track:Stop(0.2)
			end
		end
	end
	local function v_u_146()
		-- upvalues: (copy) v_u_8
		local v139 = v_u_8.WalkToPoint
		local v140 = v_u_8.WalkToPart
		if v_u_8.MoveDirection ~= Vector3.new(0, 0, 0) then
			return v_u_8.MoveDirection
		end
		if not v140 and v139 == Vector3.new(0, 0, 0) then
			return v_u_8.MoveDirection
		end
		if v140 then
			v139 = v140.CFrame:PointToWorldSpace(v139)
		end
		local v141
		if v_u_8.RootPart then
			local v142 = v139 - v_u_8.RootPart.CFrame.Position
			local v143 = v142.x
			local v144 = v142.z
			v141 = Vector3.new(v143, 0, v144)
			local v145 = v141.Magnitude
			if v145 > 0.01 then
				v141 = v141 / v145
			end
		else
			v141 = Vector3.new(0, 0, 0)
		end
		return v141
	end
	local function v_u_164(p147)
		-- upvalues: (ref) v_u_80, (copy) v_u_23, (copy) v_u_146, (copy) v_u_8, (ref) v_u_9, (ref) v_u_11, (ref) v_u_13, (ref) v_u_83, (ref) v_u_82, (copy) v_u_138
		if v_u_80 == v_u_23 then
			local v148 = v_u_146()
			if not v_u_8.RootPart then
				return
			end
			local v149 = v_u_8.RootPart.CFrame
			local v150 = v149.UpVector.Y
			if math.abs(v150) < 0.0001 or (v_u_9 ~= "Running" or v_u_11 < 0.001) then
				for _, v151 in pairs(v_u_80) do
					if v151.track then
						v151.track:AdjustWeight(0.0001, 0.2)
					end
				end
				return
			end
			local v152 = v149.LookVector
			local v153 = v152.X
			local v154 = v152.Z
			local v155 = Vector3.new(v153, 0, v154)
			local v156 = v155 / v155.Magnitude
			local v157 = v148:Dot(v156)
			local v158 = v157 <= 0 and v157 > -0.05 and 0.0001 or v157
			local v159 = v156.X * v148.Z - v156.Z * v148.X
			local v160 = Vector2.new(v159, v158)
			local v161 = Vector2.new(v160.x - v_u_13.x, v160.y - v_u_13.y)
			if v161:Dot(v161) <= 0.001 then
				local v162 = v_u_11 - v_u_83
				if math.abs(v162) <= 0.01 and p147 - v_u_82 <= 1 then
					::l19::
					return
				end
			end
			v_u_13 = v160
			v_u_83 = v_u_11
			v_u_82 = p147
			v_u_138(v_u_13, v_u_83)
			return
		else
			local v163 = v_u_11 - v_u_83
			if math.abs(v163) > 0.01 or p147 - v_u_82 > 1 then
				v_u_83 = v_u_11
				v_u_82 = p147
				v_u_138(Vector2.yAxis, v_u_83)
			end
			goto l19
		end
	end
	local function v_u_169(p165)
		-- upvalues: (ref) v_u_81, (copy) v_u_26, (ref) v_u_92, (ref) v_u_17, (ref) v_u_19, (ref) v_u_30, (copy) v_u_8
		if p165 == "End" then
			local v166 = v_u_81
			local v167 = v_u_26[v166] ~= nil and v_u_26[v166] == false and "idle" or v166
			if v_u_92 then
				if v_u_17.Looped then
					return
				end
				v167 = "idle"
				v_u_92 = false
			end
			local v168 = v_u_19
			v_u_30(v167, 0.15, v_u_8)
			if v_u_81 ~= "walk" and v168 ~= v_u_19 then
				v_u_19 = v168
				v_u_17:AdjustSpeed(v_u_19)
			end
		end
	end
	local function v_u_173(p170)
		-- upvalues: (copy) v_u_21
		local v171 = math.random(1, v_u_21[p170].totalWeight)
		local v172 = 1
		while v_u_21[p170][v172].weight < v171 do
			v171 = v171 - v_u_21[p170][v172].weight
			v172 = v172 + 1
		end
		return v172
	end
	local function v_u_178(p174, p175, p176, p177)
		-- upvalues: (ref) v_u_16, (ref) v_u_17, (ref) v_u_18, (ref) v_u_19, (ref) v_u_81, (copy) v_u_40, (copy) v_u_29, (copy) v_u_169
		if p174 ~= v_u_16 then
			if v_u_17 ~= nil then
				v_u_17:Stop(p176)
				v_u_17:Destroy()
			end
			if v_u_18 ~= nil then
				v_u_18:disconnect()
			end
			v_u_19 = 1
			v_u_81 = p175
			v_u_16 = p174
			if p175 == "walk" then
				v_u_40()
				return
			end
			v_u_29()
			v_u_17 = p177:LoadAnimation(p174)
			v_u_17.Priority = Enum.AnimationPriority.Core
			v_u_17:Play(p176)
			v_u_18 = v_u_17.KeyframeReached:connect(v_u_169)
		end
	end
	local function v_u_183(p179, p180, p181)
		-- upvalues: (copy) v_u_173, (copy) v_u_21, (copy) v_u_178, (ref) v_u_92
		local v182 = v_u_173(p179)
		v_u_178(v_u_21[p179][v182].anim, p179, p180, p181)
		v_u_92 = false
	end
	local v_u_184 = ""
	local v_u_185 = nil
	local v_u_186 = nil
	local v_u_187 = nil
	local v_u_188 = nil
	local function v_u_190(p189)
		-- upvalues: (ref) v_u_188, (ref) v_u_184, (copy) v_u_8
		if p189 == "End" then
			v_u_188(v_u_184, 0, v_u_8)
		end
	end
	v_u_188 = function(p191, p192, p193, p194)
		-- upvalues: (copy) v_u_173, (copy) v_u_21, (ref) v_u_186, (ref) v_u_185, (ref) v_u_184, (ref) v_u_187, (copy) v_u_190
		local v195 = v_u_173(p191)
		local v196 = v_u_21[p191][v195].anim
		if v_u_186 ~= v196 then
			if v_u_185 ~= nil then
				v_u_185:Stop()
				v_u_185:Destroy()
				p192 = 0
			end
			v_u_185 = p193:LoadAnimation(v196)
			if p194 then
				v_u_185.Priority = p194
			end
			v_u_185:Play(p192)
			v_u_184 = p191
			v_u_186 = v196
			v_u_187 = v_u_185.KeyframeReached:connect(v_u_190)
		end
	end
	local function v200(p197)
		-- upvalues: (ref) v_u_92, (copy) v_u_8, (ref) v_u_11, (ref) v_u_183, (ref) v_u_9, (copy) v_u_164, (copy) v_u_26, (ref) v_u_81
		local v198 = v_u_92
		if v198 then
			v198 = v_u_8.MoveDirection == Vector3.new(0, 0, 0)
		end
		local v199 = v198 and v_u_8.WalkSpeed or 0.75
		v_u_11 = p197
		if v199 < p197 then
			v_u_183("walk", 0.2, v_u_8)
			if v_u_9 ~= "Running" then
				v_u_9 = "Running"
				v_u_164(0)
				return
			end
		elseif v_u_26[v_u_81] == nil and not v_u_92 then
			v_u_183("idle", 0.2, v_u_8)
			v_u_9 = "Standing"
		end
	end
	local function v201()
		-- upvalues: (ref) v_u_183, (copy) v_u_8, (ref) v_u_91, (ref) v_u_9
		v_u_183("jump", 0.1, v_u_8)
		v_u_91 = 0.31
		v_u_9 = "Jumping"
	end
	local function v204(p202)
		-- upvalues: (ref) v_u_183, (copy) v_u_8, (ref) v_u_81, (ref) v_u_19, (ref) v_u_17, (ref) v_u_9
		v_u_183("climb", 0.1, v_u_8)
		local v203 = p202 / 5
		if v_u_81 ~= "walk" and v203 ~= v_u_19 then
			v_u_19 = v203
			v_u_17:AdjustSpeed(v_u_19)
		end
		v_u_9 = "Climbing"
	end
	local function v205()
		-- upvalues: (ref) v_u_91, (ref) v_u_183, (copy) v_u_8, (ref) v_u_9
		if v_u_91 <= 0 then
			v_u_183("fall", 0.2, v_u_8)
		end
		v_u_9 = "FreeFall"
	end
	local function v208(p206)
		-- upvalues: (ref) v_u_183, (copy) v_u_8, (ref) v_u_81, (ref) v_u_19, (ref) v_u_17, (ref) v_u_9
		if p206 > 1 then
			v_u_183("swim", 0.4, v_u_8)
			local v207 = p206 / 10
			if v_u_81 ~= "walk" and v207 ~= v_u_19 then
				v_u_19 = v207
				v_u_17:AdjustSpeed(v_u_19)
			end
			v_u_9 = "Swimming"
		else
			v_u_183("swimidle", 0.4, v_u_8)
			v_u_9 = "Standing"
		end
	end
	local function v_u_209()
		-- upvalues: (ref) v_u_89, (ref) v_u_188, (copy) v_u_8
		if v_u_89 == "None" then
			v_u_188("toolnone", 0.1, v_u_8, Enum.AnimationPriority.Idle)
			return
		elseif v_u_89 == "Slash" then
			v_u_188("toolslash", 0, v_u_8, Enum.AnimationPriority.Action)
			return
		elseif v_u_89 == "Lunge" then
			v_u_188("toollunge", 0, v_u_8, Enum.AnimationPriority.Action)
		end
	end
	local function v_u_212(p210)
		for _, v211 in ipairs(p210:GetChildren()) do
			if v211.Name == "toolanim" and v211.className == "StringValue" then
				return v211
			end
		end
		return nil
	end
	local v_u_213 = 0
	local function v_u_218(p214)
		-- upvalues: (ref) v_u_213, (ref) v_u_91, (ref) v_u_9, (ref) v_u_183, (copy) v_u_8, (copy) v_u_164, (copy) v_u_96, (copy) p_u_4, (copy) v_u_212, (ref) v_u_89, (ref) v_u_90, (copy) v_u_209, (ref) v_u_184, (ref) v_u_187, (ref) v_u_186, (ref) v_u_185
		local v215 = p214 - v_u_213
		v_u_213 = p214
		if v_u_91 > 0 then
			v_u_91 = v_u_91 - v215
		end
		if v_u_9 == "FreeFall" and v_u_91 <= 0 then
			v_u_183("fall", 0.2, v_u_8)
		else
			if v_u_9 == "Seated" then
				v_u_183("sit", 0.5, v_u_8)
				return
			end
			if v_u_9 == "Running" then
				v_u_183("walk", 0.2, v_u_8)
				v_u_164(p214)
			elseif v_u_9 == "Dead" or (v_u_9 == "GettingUp" or (v_u_9 == "FallingDown" or (v_u_9 == "Seated" or v_u_9 == "PlatformStanding"))) then
				v_u_96()
			end
		end
		local v216 = p_u_4:FindFirstChildOfClass("Tool")
		if v216 and v216:FindFirstChild("Handle") then
			local v217 = v_u_212(v216)
			if v217 then
				v_u_89 = v217.Value
				v217.Parent = nil
				v_u_90 = p214 + 0.3
			end
			if v_u_90 < p214 then
				v_u_90 = 0
				v_u_89 = "None"
			end
			v_u_209()
		else
			if v_u_187 ~= nil then
				v_u_187:disconnect()
			end
			v_u_184 = ""
			v_u_186 = nil
			if v_u_185 ~= nil then
				v_u_185:Stop()
				v_u_185:Destroy()
				v_u_185 = nil
			end
			v_u_89 = "None"
			v_u_186 = nil
			v_u_90 = 0
		end
	end
	v_u_5:GiveTask(v_u_8.Died:connect(function()
		-- upvalues: (ref) v_u_9
		v_u_9 = "Dead"
	end))
	v_u_5:GiveTask(v_u_8.Running:connect(v200))
	v_u_5:GiveTask(v_u_8.Jumping:connect(v201))
	v_u_5:GiveTask(v_u_8.Climbing:connect(v204))
	v_u_5:GiveTask(v_u_8.GettingUp:connect(function()
		-- upvalues: (ref) v_u_9
		v_u_9 = "GettingUp"
	end))
	v_u_5:GiveTask(v_u_8.FreeFalling:connect(v205))
	v_u_5:GiveTask(v_u_8.FallingDown:connect(function()
		-- upvalues: (ref) v_u_9
		v_u_9 = "FallingDown"
	end))
	v_u_5:GiveTask(v_u_8.Seated:connect(function()
		-- upvalues: (ref) v_u_9
		v_u_9 = "Seated"
	end))
	v_u_5:GiveTask(v_u_8.PlatformStanding:connect(function()
		-- upvalues: (ref) v_u_9
		v_u_9 = "PlatformStanding"
	end))
	v_u_5:GiveTask(v_u_8.Swimming:connect(v208))
	if p_u_4.Parent ~= nil then
		v_u_183("idle", 0.1, v_u_8)
		local _ = "Standing"
	end
	v_u_5:GiveTask(v_u_3.Heartbeat:Connect(function()
		-- upvalues: (copy) p_u_4, (copy) v_u_5, (copy) v_u_218
		if p_u_4.Parent == nil then
			v_u_5:DoCleaning()
		else
			v_u_218(os.clock())
		end
	end))
	v_u_5:GiveTask(function()
		-- upvalues: (ref) v_u_79
		task.defer(function()
			-- upvalues: (ref) v_u_79
			if v_u_79 then
				for _, v219 in v_u_79:GetPlayingAnimationTracks() do
					v219:Stop(0)
					v219:Destroy()
				end
			end
		end)
	end)
	return {
		["Destroy"] = function(_)
			-- upvalues: (copy) v_u_5
			v_u_5:DoCleaning()
		end
	}
end
