-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMmBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzBkVudW1lchpyZXF1aXJlVmFsaWRJbmRleEFuZEZyZWV6ZRFSRU1PVEVfRVZFTlRfTkFNRRFBTU9VTlRfVkFMVUVfTkFNRRJNQVhJTVVNX1ZBTFVFX05BTUUPTVVMVF9WQUxVRV9OQU1FF01VTFRfRU5BQkxFRF9WQUxVRV9OQU1FD1RJTUVfVkFMVUVfTkFNRQ9USUVSX1ZBTFVFX05BTUUSTUVTU0FHRV9WQUxVRV9OQU1FFUJBR19WSVNVQUxfVkFMVUVfTkFNRRRGT1JNQVRURVJfVkFMVUVfTkFNRRBPV05FUl9WQUxVRV9OQU1FEkFXQVJERURfVkFMVUVfTkFNRSNCQUdfVklTVUFMX0lOVkVOVE9SWV9JVEVNX0FUVFJfTkFNRRdST0JCRVJZX0VOVU1fVkFMVUVfTkFNRQNuZXQLUmVtb3RlRXZlbnQGQW1vdW50B01heGltdW0ETXVsdAtNdWx0RW5hYmxlZARUaW1lBFRpZXIHTWVzc2FnZQlCYWdWaXN1YWwJRm9ybWF0dGVyBU93bmVyB0F3YXJkZWQWQmFnVmlzdWFsSW52ZW50b3J5SXRlbRREdWZmZWxCYWdSb2JiZXJ5RW51bRBQTEFZX0FXQVJEX1NPVU5EAAEIAAABAgBNowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAoQYAAABNAgMYBwAAAJ8BAgKkAgUAAABAQE0EAKEGAAAATQMEVwgAAACfAgICTQMBAAkAAADiBBkAbwUaADAFBA0KAAAAbwUbADAFBFsLAAAAbwUcADAFBFwMAAAAbwUdADAFBOINAAAAbwUeADAFBPUOAAAAbwUfADAFBGsPAAAAbwUgADAFBA4QAAAAbwUhADAFBBIRAAAAbwUiADAFBCESAAAAbwUjADAFBLcTAAAAbwUkADAFBEoUAAAAbwUlADAFBKIVAAAAbwUmADAFBEAWAAAAbwUnADAFBBYXAAAAUgUCAP8GAAABAAAAbwcoAMUGBwIBAAAAnwUCAjAFBFQYAAAAnwMCAIIDAAApAwEEAAAAQAMCAwMDBAQAAEBAAwUDBgMHAwgDCQMKAwsDDAMNAw4DDwMQAxEDEgMTAxQDFQMWAxcFDwoLDA0ODxAREhMUFRYXGAMYAxkDGgMbAxwDHQMeAx8DIAMhAyIDIwMkAyUDJgABAAEYAAEAAAAAAAEAAAAAAAABAAAAAAAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAgAAAAAAAAAA8AABAAAAAAAHjG8RO0mgczVIBYVVDuJqXcUvYEOjr2M/ugBls3ga6EZ7OGLNON3w

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v2 = require(v1.Std.TableUtils)
local v3 = require(v1.Std.Enumer)
return v2.requireValidIndexAndFreeze({
	["REMOTE_EVENT_NAME"] = "RemoteEvent",
	["AMOUNT_VALUE_NAME"] = "Amount",
	["MAXIMUM_VALUE_NAME"] = "Maximum",
	["MULT_VALUE_NAME"] = "Mult",
	["MULT_ENABLED_VALUE_NAME"] = "MultEnabled",
	["TIME_VALUE_NAME"] = "Time",
	["TIER_VALUE_NAME"] = "Tier",
	["MESSAGE_VALUE_NAME"] = "Message",
	["BAG_VISUAL_VALUE_NAME"] = "BagVisual",
	["FORMATTER_VALUE_NAME"] = "Formatter",
	["OWNER_VALUE_NAME"] = "Owner",
	["AWARDED_VALUE_NAME"] = "Awarded",
	["BAG_VISUAL_INVENTORY_ITEM_ATTR_NAME"] = "BagVisualInventoryItem",
	["ROBBERY_ENUM_VALUE_NAME"] = "DuffelBagRobberyEnum",
	["net"] = v3({ "PLAY_AWARD_SOUND" })
})
