-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMJBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZAZCaW5kZXIDbmV3CUR1ZmZlbEJhZwRHYW1lAAEIAAABAgAcowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAoQYAAABNAgN/BwAAAJ8BAgJNAgHvCAAAAG8DCQCkBAUAAABAQE0HAL0KAAAATQYHxgkAAABNBQbGCQAAAJ8EAgCfAgAAggIAAAsDAQQAAABAAwIDAwMEBAAAQEADBQMGAwcDCAMJAAEAARgAAQAAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAAAAAQAAAAAAeNyWFUEzlrhKGPyBfdz1RTF9/cXaMCjx9ExST5k3QFJR6q2QrB12NA==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Std.Binder).new("DuffelBag", require(v1.Game.DuffelBag.DuffelBag))
