-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgM0C0xvY2FsUGxheWVyCVBsYXllckd1aQtPYmplY3RMb2NhbAZWb2x1bWUIcGxheVRpY2sFcHJvcHMNYmF0dGxlSW52aXRlcw1yZW1vdmVCeUluZGV4CG9uQWNjZXB0CW9uRGVjbGluZQRpbml0FW1heGltdW1JdGVtc0Rpc3BsYXllZAthc3BlY3RSYXRpbwRtYXRoA21pbgVtZXJnZQhwb3NpdGlvbgVpbmRleAVVRGltMgNuZXcFRnJhbWUWQmFja2dyb3VuZFRyYW5zcGFyZW5jeQRTaXplCFBvc2l0aW9uC0FuY2hvclBvaW50BHNpemULYW5jaG9yUG9pbnQLQXNwZWN0UmF0aW8XVUlBc3BlY3RSYXRpb0NvbnN0cmFpbnQGcmVuZGVyBHR5cGUaYmF0dGxlSW52aXRlc1JlbW92ZUJ5SW5kZXgEZ2FtZQdQbGF5ZXJzCkdldFNlcnZpY2URUmVwbGljYXRlZFN0b3JhZ2UHcmVxdWlyZQNTdGQFQXVkaW8KUm9hY3RSb2R1eARFelVpCkRpY3Rpb25hcnkFUm9hY3QNY3JlYXRlRWxlbWVudAZzY3JpcHQGUGFyZW50DEJhdHRsZUludml0ZQ1QdXJlQ29tcG9uZW50DUJhdHRsZUludml0ZXMGZXh0ZW5kDGRlZmF1bHRQcm9wcwdjb25uZWN0AAkFAAIAAAAZ+wEAAE0AATEAAAAADgAUAPsCAABNAQIxAAAAAE0AAZkBAAAADgAOAPsBAQBNAAHRAgAAAPsDAABNAgMxAAAAAE0BApkBAAAAbwIDAOIDBQBvBAYAMAQDSwQAAACfAAQBggABAAcDAQMCAwMCAABgMp++9kEDBAUBBAIzMzMzMzPDPwAMBQEYAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAg0AAAAABwEDAAAAM/sEAABNAwQHAAAAAE0CA2QBAAAAhwECAPsEAABNAwQHAAAAAE0CAywCAAAAUgMAAJ8CAgH7AwEATQIDMQMAAAAOAhQA+wQBAE0DBDEDAAAATQIDmQQAAAAOAg4A+wMCAE0CA9EFAAAA+wUBAE0EBTEDAAAATQMEmQQAAABvBAYA4gUIAG8GCQAwBgVLBwAAAJ8CBAH7BAAATQMEBwAAAABNAgMqCgAAAA4CBwD7BAAATQMEBwAAAABNAgMqCgAAAFIDAQCfAgIBggABAAsDBgMHAwgDAQMCAwMCAABgMp++9kEDBAUBBwIzMzMzMzPDPwMJABoAARgOAAAAAAABAAAAAAAA8QAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAEAAAAAAAAQAAAAAAAAINAAAAAAcBAwAAADP7BAAATQMEBwAAAABNAgNkAQAAAIcBAgD7BAAATQMEBwAAAABNAgMsAgAAAFIDAACfAgIB+wMBAE0CAzEDAAAADgIUAPsEAQBNAwQxAwAAAE0CA5kEAAAADgIOAPsDAgBNAgPRBQAAAPsFAQBNBAUxAwAAAE0DBJkEAAAAbwQGAOIFCABvBgkAMAYFSwcAAACfAgQB+wQAAE0DBAcAAAAATQIDLQoAAAAOAgcA+wQAAE0DBAcAAAAATQIDLQoAAABSAwEAnwICAYIAAQALAwYDBwMIAwEDAgMDAgAAYDKfvvZBAwQFAQcCMzMzMzMzwz8DCgAiAAEYFgAAAAAAAQAAAAAAAOkAAAAAAAAAAAABAAAAAAAAAAAAAAAAABgAAAAAAAEAAAAAAAACDQAAAAACAQIAAAAN2QEAABIAAAASAgAAEgIBADABACoAAAAA2QEBABIAAAASAgAAEgIBADABAC0BAAAAggABAAIDCQMKAgECGQsBGAAAAAAAAAgAAAAAAAgaAAAAABcBAwAAAIwBTQYABwEAAABNBQaHAgAAANgEAAVNCAAHAQAAAE0HCIcCAAAA2AYDB9gFAAYmAwQF2AIAA00EAAcBAAAATQMEiQQAAAAJAQIDTQQABwEAAABNAwSHAgAAAE0FAAcBAAAATQQFiQQAAAAJAgME/wMAAAAAAABNBgAHAQAAAE0FBmQFAAAAHAQFAIwHAQBNCwAHAQAAAE0KC4cCAAAAnhMEBAoAAABSCQQApAgIAAAcYICfCAMCUgUIAIwGAQCoBTAAJgkEB5UICQBNCwAHAQAAAE0KC2QFAAAAhwkKCPsKAAD7CwEA+w0CAE0MDR8JAAAA4g0OADABDYkEAAAApA4RAABA8ICMDwAAjBAAAIwSAQAmFgcEeBUWAOwUFQJNFgAHAQAAAE0VFokEAAAACRMUFUMREhOMEgAAnw4FAjAODdsKAAAAMAgNAgsAAABNDgAqDAAAADAODSoMAAAATQ4ALQ0AAAAwDg0tDQAAAFIOCQCfDAMAnwoAAmoKAweLBdD/+wUAAG8GEgDiBxcAjAgBADAIBzoTAAAATQkABwEAAABNCAkPGAAAADAIBy8UAAAATQkABwEAAABNCAnbCgAAADAIBzsVAAAATQkABwEAAABNCAkIGQAAADAIB+gWAAAA+wkCAE0ICR8JAAAA4gkbAPsKAABvCxwA4gwbAE0OAAcBAAAATQ0OiQQAAAAwDQxpGgAAAJ8KAwIwCglpGgAAAFIKAwCfCAMAnwUAAIIFAAAdAgAAAAAAAPA/AwYDDAIAAAAAAABwQAMNAwcDDgMPBAAcYIADEAMRAxIDCQMKBQUECgsMDQMTAxQEAEDwgAMVAxYDFwMYAxkFBBMUFRYDGgMbAxwFARoDHQArHgEYAAAAAAAAAAAAAAAAAAEAAAAAAQAAAAAAAAAAAQABAAAAAAEAAAAAAAAAAAAAAAAAAQABAAAAAAMBAQAAAAEAAQABAQEAAAAAAAAAAAAB/AAABgABAAAAAQAAAAH1/gD7FQEBAQAAAQAAAAAAAQAAAAAAAQAAAAAAAgAAAAEAAAEAAAAAAP8AAAP8+AAuAAAAAAQCAAAAAAbiAgEATQMAZAAAAAAwAwJkAAAAAIICAgACAwcFAQAAVwABGAABAAAAAFgAAAAABAEBAAAACfsBAADiAgIAbwMDADADAnEAAAAAMAACAgEAAACfAQIBggABAAQDHwMSBQIAAQMgAF0IARgAAAEAAAEA/gReAAAAAAMBAAAAAAbiAQEA2QIAABIAAAAwAgEsAAAAAIIBAgACAwgFAQABBlsAARgAAQAAAABcAAAAABAAAAECAGejAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIGAAAAUEBNBAGhBwAAAE0DBNIIAAAAnwICAqQDBgAAAFBATQQBLQkAAACfAwICpAQGAAAAUEBNBgEtCgAAAE0FBqkLAAAAnwQCAqQFBgAAAFBATQYBIQwAAACfBQICTQYFyg0AAACkBwYAAABQQKQKDwAAAOBATQkKJBAAAABNCAmNEQAAAJ8HAgLACBIAEgAAABIAAgBNCQX4EwAAAG8LFAC8CQmcFQAAAJ8JAwLiChoApAsdAABwsIGMDAEAjA0AAIwOAQCMDwAAnwsFAjALCg8WAAAApAsdAABwsIGMDAAAjA0AAIwOAACMDwAAnwsFAjALCtsXAAAAbwseADALCokYAAAAjAsEADALCocZAAAAMAoJkh8AAADACiAAEgAAABIAAgAwCgkTIQAAAMAKIgASAAYAEgAHABIABAAwCgmAIwAAAE0KA+ckAAAAwAslAMAMJgCfCgMCUgsJAJ8KAgCCCgAAJwMhBAAAAEADIgMjAyQDJQQAAFBAAyYDJwMoAykDKgMrAywDLQQAAOBAAy4DLwYAAzADMQMyAxoDEQMNAwwFBBYXGBkDEwMUBABwsIECAAAAAAAA9D8DMwYDAwsGBAMeAzQGBQYHBQADBAUHAQABGAABAAAAAAABAAAAAAABAAAAAAAAAQAAAAABAAAAAAAAAQAAAAABAAIAAAAAAAAAAAIAAAYAAAAAAAEBAAAAAAAAAAABAAAAAAAAAAABAAABAAD8AAYAAAAAEgAAAAAALAAABPwNAAABAAAAAAhOZ7T8K4fJjnyj3mhhU1IzDqhLcmROi23BevvDn70b2J1aw8XhZnIJ

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players")
local v2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v2.Std.Audio)
local v4 = require(v2.RoactRodux)
local v_u_5 = require(v2.EzUi.Dictionary)
local v6 = require(v2.Roact)
local v_u_7 = v6.createElement
local v_u_8 = require(script.Parent.BattleInvite)
local v9 = v6.PureComponent:extend("BattleInvites")
v9.defaultProps = {
	["size"] = UDim2.new(1, 0, 1, 0),
	["position"] = UDim2.new(0, 0, 0, 0),
	["aspectRatio"] = 1.25,
	["maximumItemsDisplayed"] = 4
}
function v9.init(p_u_10)
	-- upvalues: (copy) v_u_1, (copy) v_u_3
	function p_u_10.onAccept(p11)
		-- upvalues: (copy) p_u_10, (ref) v_u_1, (ref) v_u_3
		local v12 = p_u_10.props.battleInvites[p11]
		p_u_10.props.removeByIndex(p11)
		if v_u_1.LocalPlayer and v_u_1.LocalPlayer.PlayerGui then
			v_u_3.ObjectLocal(v_u_1.LocalPlayer.PlayerGui, 6105461542, {
				["Volume"] = 0.15
			})
		end
		if p_u_10.props.onAccept then
			p_u_10.props.onAccept(v12)
		end
	end
	function p_u_10.onDecline(p13)
		-- upvalues: (copy) p_u_10, (ref) v_u_1, (ref) v_u_3
		local v14 = p_u_10.props.battleInvites[p13]
		p_u_10.props.removeByIndex(p13)
		if v_u_1.LocalPlayer and v_u_1.LocalPlayer.PlayerGui then
			v_u_3.ObjectLocal(v_u_1.LocalPlayer.PlayerGui, 6105461542, {
				["Volume"] = 0.15
			})
		end
		if p_u_10.props.onDecline then
			p_u_10.props.onDecline(v14)
		end
	end
end
function v9.render(p15)
	-- upvalues: (copy) v_u_7, (copy) v_u_8, (copy) v_u_5
	local v16 = 1 / (1 / p15.props.maximumItemsDisplayed - 1 / (256 / p15.props.maximumItemsDisplayed)) * p15.props.aspectRatio
	local v17 = p15.props.maximumItemsDisplayed * p15.props.aspectRatio
	local v18 = #p15.props.battleInvites
	local v19 = p15.props.maximumItemsDisplayed
	local v20 = {}
	for v21 = 1, math.min(v18, v19) do
		local v22 = v18 - v21 + 1
		local v23 = p15.props.battleInvites[v22]
		v20[v21] = v_u_7(v_u_8, v_u_5.merge({
			["aspectRatio"] = v16,
			["position"] = UDim2.new(0, 0, 1 + (v21 - v18 - 1) / v17 * p15.props.aspectRatio, 0),
			["index"] = v22,
			["onAccept"] = p15.onAccept,
			["onDecline"] = p15.onDecline
		}, v23))
	end
	local v24 = v_u_7
	local v25 = {
		["BackgroundTransparency"] = 1,
		["Size"] = p15.props.size,
		["Position"] = p15.props.position,
		["AnchorPoint"] = p15.props.anchorPoint
	}
	local v26 = v_u_5.merge
	local v27 = {
		["AspectRatio"] = v_u_7("UIAspectRatioConstraint", {
			["AspectRatio"] = p15.props.aspectRatio
		})
	}
	return v24("Frame", v25, v26(v27, v20))
end
return v4.connect(function(p28, _)
	return {
		["battleInvites"] = p28.battleInvites
	}
end, function(p_u_29)
	return {
		["removeByIndex"] = function(p30)
			-- upvalues: (copy) p_u_29
			p_u_29({
				["type"] = "battleInvitesRemoveByIndex",
				["index"] = p30
			})
		end
	}
end)(v9)
