-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgM1BXByb3BzCHJvd0luZGV4BUZyYW1lD0JvcmRlclNpemVQaXhlbBBCYWNrZ3JvdW5kQ29sb3IzBFNpemULQW5jaG9yUG9pbnQIUG9zaXRpb24Qcm9iYmVyeUNvbXBsZXRlZApicmlnaHRlbkJ5D2JhY2tncm91bmRDb2xvcgVVRGltMgNuZXcHVmVjdG9yMglVSUNvcm5lcnMOVGl0bGVDb250YWluZXIPU3RhdHVzQ29udGFpbmVyCFVJQ29ybmVyDENvcm5lclJhZGl1cwRVRGltFkJhY2tncm91bmRUcmFuc3BhcmVuY3kEVGV4dAlUZXh0TGFiZWwERm9udA5UZXh0WEFsaWdubWVudApMaW5lSGVpZ2h0ClRleHRTY2FsZWQKVGV4dENvbG9yMwRFbnVtCkZyZWRva2FPbmUETGVmdAtQUkVUVFlfTkFNRQtyb2JiZXJ5VHlwZQZTdGF0dXMJZnJvbVNjYWxlC0FzcGVjdFJhdGlvF1VJQXNwZWN0UmF0aW9Db25zdHJhaW50BnJlbmRlcgRnYW1lEVJlcGxpY2F0ZWRTdG9yYWdlCkdldFNlcnZpY2UHcmVxdWlyZQNTdGQKQ29sb3JVdGlscwdSb2JiZXJ5DVJvYmJlcnlDb25zdHMFUm9hY3QNY3JlYXRlRWxlbWVudAZDb2xvcjMHZnJvbVJHQg1QdXJlQ29tcG9uZW50E0JhdHRsZVJvYmJlcnlTdGF0dXMGZXh0ZW5kAAIUAQQAAACLAk0CAAcAAAAATQEC0gEAAAD7AgAAbwMCAOIECACMBQAAMAUEjgMAAABNBwAHAAAAAE0GB4YJAAAADgYHAPsGAQBNBQacCgAAAPsGAgBvBwsAnwUDAmUABABNBgAHAAAAAE0FBg4MAAAAMAUEnwQAAACkBQ8AADjQgIwGAQCMBwAAbwgQAIwJAACfBQUCMAUELwUAAACkBRIAADgQgYwGAACMBwAAnwUDAjAFBOgGAAAApAUPAAA40ICMBgAAjAcAAG8KEAB4CwETCQkKC5UICRNvChQACQkKAZ8FBQIwBQQ7BwAAAOIFGAD7BgAAbwcZAOIIGwCkCR0AADjAgYwKAACMCwQAnwkDAjAJCE8aAAAAnwYDAjAGBeEVAAAA+wYAAG8HAgDiCB8AjAkBADAJCDoeAAAApAkPAAA40IBvCiAAjAsAAIwMAQCMDQAAnwkFAjAJCC8FAAAA4gkiAPsKAABvCyMA4gwpAIwNAQAwDQw6HgAAAKQNDwAAONCAbw4qAIwPAABvECsAjBEAAJ8NBQIwDQwvBQAAAKQNDwAAONCAjA4BAIwPAABvECwAjBEAAJ8NBQIwDQw7BwAAAKQNEgAAOBCBjA4BAG8PLACfDQMCMA0M6AYAAACkDS8ALpDQwjANDDkkAAAApA0xADCU0MIwDQx7JQAAAPsPAwBNDg+cMgAAAE0QAAcAAAAATQ8QHDMAAACHDQ4PMA0M9SEAAACMDQEAMA0MgiYAAACpDQEAMA0M3icAAAD7DgEATQ0OnAoAAABNDwAHAAAAAE0ODw4MAAAAbw80AJ8NAwIwDQxzKAAAAJ8KAwIwCgn1IQAAAJ8GBAIwBgUWFgAAAPsGAABvBwIA4gg1AIwJAQAwCQg6HgAAAKQJDwAAONCAbwo2AIwLAACMDAEAjA0AAJ8JBQIwCQgvBQAAAKQJEgAAOBCBjAoBAIwLAACfCQMCMAkI6AYAAACkCQ8AADjQgIwKAQCMCwAAjAwAAIwNAACfCQUCMAkIOwcAAADiCTgA+woAAG8LAgDiDDkATQ8ABwAAAABNDg+GCQAAAA4OAgD7DQIAZQAJAPsOAQBNDQ6cCgAAAE0PAAcAAAAATQ4PDgwAAABvDzoAnw0DAjANDJ8EAAAAjA0AADANDDoeAAAApA08AADs0IBvDj0Abw89AJ8NAwIwDQwvBQAAAKQNEgAAOBCBbw4sAG8PLACfDQMCMA0M6AYAAACkDTwAAOzQgG8OLABvDywAnw0DAjANDDsHAAAA4g0/APsOAABvDxkA4hAbAKQRHQAAOMCBjBIBAIwTAACfEQMCMBEQTxoAAACfDgMCMA4N4RUAAAD7DgAAbw9AAOIQQQCMEQMAMBEQaT4AAACfDgMCMA4NaT4AAACfCgQCMAoJ7DcAAACfBgQCMAYF/RcAAACfAgQAggIAAEIDAQMCAwMDBAMFAwYDBwMIBQUDBAUGBwMJAwoCmpmZmZmZub8DCwMMAw0EADjQgAJVVVVVVVXlPwMOBAA4EIECAAAAAAAA8D8CVVVVVVVVBUADDwMQAxEFAxUWFwMSAxMFARoDFAQAOMCBAxUFAh4FApqZmZmZmek/AxYFASEDFwMYAxkDGgMbAxwFCh4FBwYkJSEmJygCZmZmZmZm7j8CzczMzMzM7D8CAAAAAAAA4D8DHQMeBC6Q0MIDHwQwlNDCAyADIQIAAAAAAADovwUEHgUGBwKamZmZmZnJPwMiBQE3BQUEHgUGBwKamZmZmZnpvwMjBADs0IACAAAAAAAA6D8DJAUCFT4DJQUBPgALJgEYAAAAAAQAAAEAAAEAAAAAAQAAAAAAAAEAAAD+AAMAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAAAAAAAAQEAAAEAAAAAAAD/AAADAAABAAABAAAAAAAAAAABAQAAAQAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAABAAAAAQAAAAAAAAAAAAEAAAEAAAEAAAAAAAAAAAAA9gAA/AAAEQAAAQAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAEBAAABAAAAAAEAAQAAAAAAAAAA/gADAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAQAAAQAAAAAAAP8AAAMAAAEAAP8AAPQAAPoAAOMADAAAAAAJAAABAgAwowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAoQYAAABNAgMzBwAAAJ8BAgKkAgUAAABAQE0EAAQIAAAATQMEWAkAAACfAgICpAMFAAAAQEBNBAAhCgAAAJ8DAgJNBAPKCwAAAKQFDgAANMCAjAZ/AIwH+QCMCFIAnwUEAk0GA/gPAAAAbwgQALwGBpwRAAAAnwYDAsAHEgASAAQAEgABABIABQASAAIAMAcGgBMAAACCBgIAFAMnBAAAAEADKAMpAyoEAABAQAMrAywDLQMuAy8DMAMxAzIEADTAgAMzAzQDNQYAAyYBAAEAARgAAQAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAEAAgAAAAAAAgAAAAAAAQAAAAAAAEABAAAAAAEPG6lsJE8H9j3fw/hciX51KotwdIJcVghQKLCtDQCeTvaSkUywPNKY

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.ColorUtils)
local v_u_3 = require(v1.Robbery.RobberyConsts)
local v4 = require(v1.Roact)
local v_u_5 = v4.createElement
local v_u_6 = Color3.fromRGB(127, 249, 82)
local v7 = v4.PureComponent:extend("BattleRobberyStatus")
function v7.render(p8)
	-- upvalues: (copy) v_u_5, (copy) v_u_2, (copy) v_u_6, (copy) v_u_3
	local v9 = p8.props.rowIndex
	local v10 = v_u_5
	local v11 = "Frame"
	local v12 = {
		["BorderSizePixel"] = 0
	}
	local v13
	if p8.props.robberyCompleted then
		v13 = v_u_2.brightenBy(v_u_6, -0.1)
	else
		v13 = p8.props.backgroundColor
	end
	v12.BackgroundColor3 = v13
	v12.Size = UDim2.new(1, 0, 0.6666666666666666, 0)
	v12.AnchorPoint = Vector2.new(0, 0)
	v12.Position = UDim2.new(0, 0, 0.6666666666666666 * (v9 - 1) + 1, 2.6666666666666665 * v9)
	local v14 = {
		["UICorners"] = v_u_5("UICorner", {
			["CornerRadius"] = UDim.new(0, 4)
		})
	}
	local v15 = v_u_5
	local v16 = {
		["BackgroundTransparency"] = 1,
		["Size"] = UDim2.new(0.8, 0, 1, 0)
	}
	local v17 = {
		["Text"] = v_u_5("TextLabel", {
			["BackgroundTransparency"] = 1,
			["Size"] = UDim2.new(0.95, 0, 0.9, 0),
			["Position"] = UDim2.new(1, 0, 0.5, 0),
			["AnchorPoint"] = Vector2.new(1, 0.5),
			["Font"] = Enum.Font.FredokaOne,
			["TextXAlignment"] = Enum.TextXAlignment.Left,
			["Text"] = v_u_3.PRETTY_NAME[p8.props.robberyType],
			["LineHeight"] = 1,
			["TextScaled"] = true,
			["TextColor3"] = v_u_2.brightenBy(p8.props.backgroundColor, -0.75)
		})
	}
	v14.TitleContainer = v15("Frame", v16, v17)
	local v18 = v_u_5
	local v19 = "Frame"
	local v20 = {
		["BackgroundTransparency"] = 1,
		["Size"] = UDim2.new(0.2, 0, 1, 0),
		["AnchorPoint"] = Vector2.new(1, 0),
		["Position"] = UDim2.new(1, 0, 0, 0)
	}
	local v21 = {}
	local v22 = v_u_5
	local v23 = "Frame"
	local v24 = {}
	local v25
	if p8.props.robberyCompleted then
		v25 = v_u_6
	else
		v25 = v_u_2.brightenBy(p8.props.backgroundColor, -0.8)
	end
	v24.BackgroundColor3 = v25
	v24.BackgroundTransparency = 0
	v24.Size = UDim2.fromScale(0.75, 0.75)
	v24.AnchorPoint = Vector2.new(0.5, 0.5)
	v24.Position = UDim2.fromScale(0.5, 0.5)
	local v26 = {
		["UICorners"] = v_u_5("UICorner", {
			["CornerRadius"] = UDim.new(1, 0)
		}),
		["AspectRatio"] = v_u_5("UIAspectRatioConstraint", {
			["AspectRatio"] = 3
		})
	}
	v21.Status = v22(v23, v24, v26)
	v14.StatusContainer = v18(v19, v20, v21)
	return v10(v11, v12, v14)
end
return v7
