-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgM8C2FzcGVjdFJhdGlvC293bmVyVXNlcklkCGNsYW5OYW1lCmNsYW5SYXRpbmcJb3duZXJOYW1lDWNsYW5GbGFnQ29sb3IJR29vZCBHYW5nCHRvc3RyaW5nBFhpa2sLQ0xBTl9DT0xPUlMEbWF0aAZyYW5kb20FY29sb3IERmF6ZQVCYWRjYwZCYWJveXoIQ3JpdFN0eXgOQ2VpbGluZ0ZhbkNyZXcETmljZQVBc2ltbw9sZWFkZXJib2FyZEluZm8EaW5pdAVwcmludA9hdHRlbXB0aW5nIGpvaW4RYXR0ZW1wdFZpZXdDbGFuSWQNY3JlYXRlRWxlbWVudA1TdG9yZVByb3ZpZGVyBXN0b3JlBUZyYW1lBFNpemUFVURpbTIJZnJvbVNjYWxlAXgGQXNwZWN0C2Rpc3BsYXlUeXBlHUxFQURFUkJPQVJEX0RJU1BMQVlfVFlQRV9FTlVNDUNyZXdzSW5TZXJ2ZXIXVUlBc3BlY3RSYXRpb0NvbnN0cmFpbnQLQXNwZWN0UmF0aW8GcmVuZGVyB3VubW91bnQJQ29tcG9uZW50A0FwcAZleHRlbmQHcmVxdWlyZQ9DcmV3TGVhZGVyYm9hcmQGc2NyaXB0BlBhcmVudA5QZXJzaXN0ZW50Q3JldxNwZXJzaXN0ZW50Q3Jld1N0b3JlFFBlcnNpc3RlbnRDcmV3QmF0dGxlGlBlcnNpc3RlbnRDcmV3QmF0dGxlQ29uc3RzBW1vdW50BGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQRDbGFuCkNsYW5Db25zdHMFUm9hY3QKUm9hY3RSb2R1eAAGGgEBAAAAqAdvAQAAMAEAiQEAAAD/AQAAHAAAAOICBwBvAwgAMAMCMgIAAABvAwkAMAMC6AMAAACMBJgIuz8EAqQDCwAAAKBAnwMCAjADAh8EAAAAbwMMADADArMFAAAA+wYAAE0FBsANAAAApAYQAAA84ICMBwEA+woAAE0JCsANAAAAHAgJAJ8GAwKHBAUGTQMERBEAAAAwAwIXBgAAAOIDBwBvBBIAMAQDMgIAAABvBBMAMAQD6AMAAACMBTQIuz8FAqQECwAAAKBAnwQCAjAEAx8EAAAAbwQUADAEA7MFAAAA+wcAAE0GB8ANAAAApAcQAAA84ICMCAEA+wsAAE0KC8ANAAAAHAkKAJ8HAwKHBQYHTQQFRBEAAAAwBAMXBgAAAOIEBwCMBQEAMAUEMgIAAABvBRUAMAUE6AMAAACMBkAGuz8GAqQFCwAAAKBAnwUCAjAFBB8EAAAAbwUWADAFBLMFAAAA+wgAAE0HCMANAAAApAgQAAA84ICMCQEA+wwAAE0LDMANAAAAHAoLAJ8IAwKHBgcITQUGRBEAAAAwBQQXBgAAAOIFBwCMBgIAMAYFMgIAAABvBhcAMAYF6AMAAACMB9wFuz8HAqQGCwAAAKBAnwYCAjAGBR8EAAAAbwYWADAGBbMFAAAA+wkAAE0ICcANAAAApAkQAAA84ICMCgEA+w0AAE0MDcANAAAAHAsMAJ8JAwKHBwgJTQYHRBEAAAAwBgUXBgAAAOIGBwBvBwgAMAcGMgIAAABvBxgAMAcG6AMAAACMCJgIuz8IAqQHCwAAAKBAnwcCAjAHBh8EAAAAbwcZADAHBrMFAAAA+woAAE0JCsANAAAApAoQAAA84ICMCwEA+w4AAE0NDsANAAAAHAwNAJ8KAwKHCAkKTQcIRBEAAAAwBwYXBgAAAOIHBwBvCBIAMAgHMgIAAABvCBMAMAgH6AMAAACMCTQIuz8JAqQICwAAAKBAnwgCAjAIBx8EAAAAbwgUADAIB7MFAAAA+wsAAE0KC8ANAAAApAsQAAA84ICMDAEA+w8AAE0OD8ANAAAAHA0OAJ8LAwKHCQoLTQgJRBEAAAAwCAcXBgAAAOIIBwCMCQEAMAkIMgIAAABvCRUAMAkI6AMAAACMCkAGuz8KAqQJCwAAAKBAnwkCAjAJCB8EAAAAbwkWADAJCLMFAAAA+wwAAE0LDMANAAAApAwQAAA84ICMDQEA+xAAAE0PEMANAAAAHA4PAJ8MAwKHCgsMTQkKRBEAAAAwCQgXBgAAAOIJBwCMCgIAMAoJMgIAAABvChcAMAoJ6AMAAACMC9wFuz8LAqQKCwAAAKBAnwoCAjAKCR8EAAAAbwoWADAKCbMFAAAA+w0AAE0MDcANAAAApA0QAAA84ICMDgEA+xEAAE0QEcANAAAAHA8QAJ8NAwKHCwwNTQoLRBEAAAAwCgkXBgAAAOIKBwBvCwgAMAsKMgIAAABvCxgAMAsK6AMAAACMDJgIuz8MAqQLCwAAAKBAnwsCAjALCh8EAAAAbwsZADALCrMFAAAA+w4AAE0NDsANAAAApA4QAAA84ICMDwEA+xIAAE0REsANAAAAHBARAJ8OAwKHDA0OTQsMRBEAAAAwCwoXBgAAAOILBwBvDBIAMAwLMgIAAABvDBMAMAwL6AMAAACMDTQIuz8NAqQMCwAAAKBAnwwCAjAMCx8EAAAAbwwUADAMC7MFAAAA+w8AAE0OD8ANAAAApA8QAAA84ICMEAEA+xMAAE0SE8ANAAAAHBESAJ8PAwKHDQ4PTQwNRBEAAAAwDAsXBgAAAOIMBwCMDQEAMA0MMgIAAABvDRUAMA0M6AMAAACMDkAGuz8OAqQNCwAAAKBAnw0CAjANDB8EAAAAbw0WADANDLMFAAAA+xAAAE0PEMANAAAApBAQAAA84ICMEQEA+xQAAE0TFMANAAAAHBITAJ8QAwKHDg8QTQ0ORBEAAAAwDQwXBgAAAOINBwCMDgIAMA4NMgIAAABvDhcAMA4N6AMAAACMD9wFuz8PAqQOCwAAAKBAnw4CAjAODR8EAAAAbw4WADAODbMFAAAA+xEAAE0QEcANAAAApBEQAAA84ICMEgEA+xUAAE0UFcANAAAAHBMUAJ8RAwKHDxARTQ4PRBEAAAAwDg0XBgAAAOIOBwBvDwgAMA8OMgIAAABvDxgAMA8O6AMAAACMEJgIuz8QAqQPCwAAAKBAnw8CAjAPDh8EAAAAbw8ZADAPDrMFAAAA+xIAAE0REsANAAAApBIQAAA84ICMEwEA+xYAAE0VFsANAAAAHBQVAJ8SAwKHEBESTQ8QRBEAAAAwDw4XBgAAAOIPBwBvEBIAMBAPMgIAAABvEBMAMBAP6AMAAACMETQIuz8RAqQQCwAAAKBAnxACAjAQDx8EAAAAbxAUADAQD7MFAAAA+xMAAE0SE8ANAAAApBMQAAA84ICMFAEA+xcAAE0WF8ANAAAAHBUWAJ8TAwKHERITTRARRBEAAAAwEA8XBgAAAOIQBwCMEQEAMBEQMgIAAABvERUAMBEQ6AMAAACMEkAGuz8SAqQRCwAAAKBAnxECAjAREB8EAAAAbxEWADARELMFAAAA+xQAAE0TFMANAAAApBQQAAA84ICMFQEA+xgAAE0XGMANAAAAHBYXAJ8UAwKHEhMUTRESRBEAAAAwERAXBgAAAOIRBwCMEgIAMBIRMgIAAABvEhcAMBIR6AMAAACME9wFuz8TAqQSCwAAAKBAnxICAjASER8EAAAAbxIWADASEbMFAAAA+xUAAE0UFcANAAAApBUQAAA84ICMFgEA+xkAAE0YGcANAAAAHBcYAJ8VAwKHExQVTRITRBEAAAAwEhEXBgAAAMUBAhEBAAAA4gIHAG8DCAAwAwIyAgAAAG8DGAAwAwLoAwAAAIwEmAi7PwQCpAMLAAAAoECfAwICMAMCHwQAAABvAxkAMAMCswUAAAD7BgAATQUGwA0AAACkBhAAADzggIwHAQD7CgAATQkKwA0AAAAcCAkAnwYDAocEBQZNAwREEQAAADADAhcGAAAA4gMHAG8EEgAwBAMyAgAAAG8EEwAwBAPoAwAAAIwFNAi7PwUCpAQLAAAAoECfBAICMAQDHwQAAABvBBQAMAQDswUAAAD7BwAATQYHwA0AAACkBxAAADzggIwIAQD7CwAATQoLwA0AAAAcCQoAnwcDAocFBgdNBAVEEQAAADAEAxcGAAAA4gQHAIwFAQAwBQQyAgAAAG8FFQAwBQToAwAAAIwGQAa7PwYCpAULAAAAoECfBQICMAUEHwQAAABvBRYAMAUEswUAAAD7CAAATQcIwA0AAACkCBAAADzggIwJAQD7DAAATQsMwA0AAAAcCgsAnwgDAocGBwhNBQZEEQAAADAFBBcGAAAA4gUHAIwGAgAwBgUyAgAAAG8GFwAwBgXoAwAAAIwH3AW7PwcCpAYLAAAAoECfBgICMAYFHwQAAABvBhYAMAYFswUAAAD7CQAATQgJwA0AAACkCRAAADzggIwKAQD7DQAATQwNwA0AAAAcCwwAnwkDAocHCAlNBgdEEQAAADAGBRcGAAAA4gYHAG8HCAAwBwYyAgAAAG8HGAAwBwboAwAAAIwImAi7PwgCpAcLAAAAoECfBwICMAcGHwQAAABvBxkAMAcGswUAAAD7CgAATQkKwA0AAACkChAAADzggIwLAQD7DgAATQ0OwA0AAAAcDA0AnwoDAocICQpNBwhEEQAAADAHBhcGAAAA4gcHAG8IEgAwCAcyAgAAAG8IEwAwCAfoAwAAAIwJNAi7PwkCpAgLAAAAoECfCAICMAgHHwQAAABvCBQAMAgHswUAAAD7CwAATQoLwA0AAACkCxAAADzggIwMAQD7DwAATQ4PwA0AAAAcDQ4AnwsDAocJCgtNCAlEEQAAADAIBxcGAAAA4ggHAIwJAQAwCQgyAgAAAG8JFQAwCQjoAwAAAIwKQAa7PwoCpAkLAAAAoECfCQICMAkIHwQAAABvCRYAMAkIswUAAAD7DAAATQsMwA0AAACkDBAAADzggIwNAQD7EAAATQ8QwA0AAAAcDg8AnwwDAocKCwxNCQpEEQAAADAJCBcGAAAA4gkHAIwKAgAwCgkyAgAAAG8KFwAwCgnoAwAAAIwL3AW7PwsCpAoLAAAAoECfCgICMAoJHwQAAABvChYAMAoJswUAAAD7DQAATQwNwA0AAACkDRAAADzggIwOAQD7EQAATRARwA0AAAAcDxAAnw0DAocLDA1NCgtEEQAAADAKCRcGAAAA4goHAG8LCAAwCwoyAgAAAG8LGAAwCwroAwAAAIwMmAi7PwwCpAsLAAAAoECfCwICMAsKHwQAAABvCxkAMAsKswUAAAD7DgAATQ0OwA0AAACkDhAAADzggIwPAQD7EgAATRESwA0AAAAcEBEAnw4DAocMDQ5NCwxEEQAAADALChcGAAAA4gsHAG8MEgAwDAsyAgAAAG8MEwAwDAvoAwAAAIwNNAi7Pw0CpAwLAAAAoECfDAICMAwLHwQAAABvDBQAMAwLswUAAAD7DwAATQ4PwA0AAACkDxAAADzggIwQAQD7EwAATRITwA0AAAAcERIAnw8DAocNDg9NDA1EEQAAADAMCxcGAAAA4gwHAIwNAQAwDQwyAgAAAG8NFQAwDQzoAwAAAIwOQAa7Pw4CpA0LAAAAoECfDQICMA0MHwQAAABvDRYAMA0MswUAAAD7EAAATQ8QwA0AAACkEBAAADzggIwRAQD7FAAATRMUwA0AAAAcEhMAnxADAocODxBNDQ5EEQAAADANDBcGAAAA4g0HAIwSAgAwEg0yAgAAAG8SFwAwEg3oAwAAAIwT3AW7PxMCpBILAAAAoECfEgICMBINHwQAAABvEhYAMBINswUAAAD7FQAATRQVwA0AAACkFRAAADzggIwWAQD7GQAATRgZwA0AAAAcFxgAnxUDAocTFBVNEhNEEQAAADASDRcGAAAAxQECDREAAAAwAQDLGgAAAIIAAQAbAgAAAAAAAPg/AwEDAgMDAwQDBQMGBQUCAwQFBgIAAACAa6ZFQQMHAwgEAACgQAMJAwoDCwMMBAA84IADDQIAAAAAluY+QQMOAw8DEAMRAxIDEwMUAxUADBYBGAAAAAEAAQEAAAEAAAEAAAAAAAABAAABAAAAAAAAAAAAAAAAAAAAAgEAAAEAAAEAAAAAAAABAAABAAAAAAAAAAAAAAAAAAAAAgEAAAEAAAEAAAAAAAABAAABAAAAAAAAAAAAAAAAAAAAAgEAAAEAAAEAAAAAAAABAAABAAAAAAAAAAAAAAAAAAAAAgEAAAEAAAEAAAAAAAABAAABAAAAAAAAAAAAAAAAAAAAAgEAAAEAAAEAAAAAAAABAAABAAAAAAAAAAAAAAAAAAAAAgEAAAEAAAEAAAAAAAABAAABAAAAAAAAAAAAAAAAAAAAAgEAAAEAAAEAAAAAAAABAAABAAAAAAAAAAAAAAAAAAAAAgEAAAEAAAEAAAAAAAABAAABAAAAAAAAAAAAAAAAAAAAAgEAAAEAAAEAAAAAAAABAAABAAAAAAAAAAAAAAAAAAAAAgEAAAEAAAEAAAAAAAABAAABAAAAAAAAAAAAAAAAAAAAAgEAAAEAAAEAAAAAAAABAAABAAAAAAAAAAAAAAAAAAAAAgEAAAEAAAEAAAAAAAABAAABAAAAAAAAAAAAAAAAAAAAAgEAAAEAAAEAAAAAAAABAAABAAAAAAAAAAAAAAAAAAAAAgEAAAEAAAEAAAAAAAABAAABAAAAAAAAAAAAAAAAAAAAAgEAAAEAAAEAAAAAAAABAAABAAAAAAAAAAAAAAAAAAAAAgAAAQAAAQAAAQAAAAAAAAEAAAEAAAAAAAAAAAAAAAAAAAACAQAAAQAAAQAAAAAAAAEAAAEAAAAAAAAAAAAAAAAAAAACAQAAAQAAAQAAAAAAAAEAAAEAAAAAAAAAAAAAAAAAAAACAQAAAQAAAQAAAAAAAAEAAAEAAAAAAAAAAAAAAAAAAAACAQAAAQAAAQAAAAAAAAEAAAEAAAAAAAAAAAAAAAAAAAACAQAAAQAAAQAAAAAAAAEAAAEAAAAAAAAAAAAAAAAAAAACAQAAAQAAAQAAAAAAAAEAAAEAAAAAAAAAAAAAAAAAAAACAQAAAQAAAQAAAAAAAAEAAAEAAAAAAAAAAAAAAAAAAAACAQAAAQAAAQAAAAAAAAEAAAEAAAAAAAAAAAAAAAAAAAACAQAAAQAAAQAAAAAAAAEAAAEAAAAAAAAAAAAAAAAAAAACAQAAAQAAAQAAAAAAAAEAAAEAAAAAAAAAAAAAAAAAAAACAQAAAQAAAQAAAAAAAAEAAAEAAAAAAAAAAAAAAAAAAAAAAD0Axg0AAAAAAgAAAAAABaQAAQAAAABAbwECAJ8AAgGCAAEAAwMXBAAAAEADGADhARkBGAAAAAAB4gAAAAAPAQUAAABE+wIAAE0BAsoAAAAA+wMBAE0CA7oBAAAA4gMDAPsEAgAwBAN+AgAAAP8EAAABAAAA+wYAAE0FBsoAAAAAbwYEAOIHBgCkCAkAACBwgIwJAQCMCgEAnwgDAjAIBy8FAAAA4ggMAPsKAABNCQrKAAAAAPsKAwDiCxEATQwAyw0AAAAwDAvLDQAAAE0MAIkOAAAAMAwLiQ4AAAD7DgQATQ0ODBIAAABNDA34EwAAADAMC78PAAAAwAwUADAMCwgQAAAAnwkDAjAJCJkKAAAA+woAAE0JCsoAAAAAbwoVAOILFwBNDACJDgAAADAMC2kWAAAAnwkDAjAJCC8LAAAAnwUEAMUEBQABAAAAnwEEAIIBAAAYAxoDGwMcBQECAx0DHgUBBQMfAyAEACBwgAMhAyIFAgoLAxUDAQMjAxkFBA0ODxADJAMlBgEDJgMnBQEWAQHWASgBGAAAAAAAAAABAAABAAEAAAAAAQAAAAAAAAEBAAAAAAEAAAABAAAAAQAAAAAAAAEAAPwAAAgAAAAAAQAAAP8AAPUAAP0A1wAAAAACAAIAAAAG+wEAAE0AARIAAAAA+wEBAJ8AAgGCAAEAAQMpAO0BAAEYAAAAAAAB7gAAAAAIAQQAAAA6+wIAAE0BAogAAAAAbwMBALwBAZwCAAAAnwEDAqQCBAAAADBApAUHAAAAYEBNBAUkCAAAAE0DBCUFAAAAnwICAqQDBAAAADBA+wYBAE0FBsUJAAAATQQFUgoAAACfAwICpAQEAAAAMED7BwEATQYHWAsAAABNBQbnDAAAAJ8EAgLABQ0AEgICADAFARMOAAAA2QUBABICAAASAgMAEgADABIAAgASAAQAMAUBgA8AAAD7BgAATQUG5BAAAAD7BwAATQYHyhEAAABSBwEAnwYCAlIHAACfBQMC2QYCABICAAASAAUAggYCABIDKgMrAywDLQQAADBAAy4DLwQAAGBAAzADMQMyAzMDNAYAAxYDKAM1AxoDAAIDBwABGAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAMoAAAAAAAAAFgAAAAAAAAAAAAEAAAAIAAAAAAUAAAECAB6jAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwDLBgAAAE0CAzQHAAAAnwECAqQCBQAAAEBATQMAIQgAAACfAgICpAMFAAAAQEBNBAAtCQAAAJ8DAgLABAoAEgACABIAAAASAAEAEgADAIIEAgALAzYEAAAAQAM3AzgDLQQAAEBAAzkDOgM7AzwGBAEEAQABGAABAAAAAAABAAAAAAAAAQAAAAABAAAAAAIAAAAAAAEAAAAABS10lTVCb48qH7D/oROhOZQio4IHNqgKlZqn1AX393JwQoVvTQamPEE=

-- Decompiled by Krnl

local v_u_1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v_u_1.Clan.ClanConsts)
local v_u_3 = require(v_u_1.Roact)
local v_u_4 = require(v_u_1.RoactRodux)
return function(p5)
	-- upvalues: (copy) v_u_3, (copy) v_u_1, (copy) v_u_2, (copy) v_u_4
	local v6 = v_u_3.Component:extend("App")
	local v_u_7 = require(script.Parent.CrewLeaderboard)
	local v_u_8 = require(v_u_1.PersistentCrew.persistentCrewStore)
	local v_u_9 = require(v_u_1.PersistentCrewBattle.PersistentCrewBattleConsts)
	function v6.init(p10)
		-- upvalues: (ref) v_u_2
		p10.aspectRatio = 1.5
		p10.leaderboardInfo = {
			{
				["ownerUserId"] = 2837719,
				["clanName"] = "Good Gang",
				["clanRating"] = tostring(2200),
				["ownerName"] = "Xikk",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 2025110,
				["clanName"] = "Faze",
				["clanRating"] = tostring(2100),
				["ownerName"] = "Badcc",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 1,
				["clanName"] = "Baboyz",
				["clanRating"] = tostring(1600),
				["ownerName"] = "CritStyx",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 2,
				["clanName"] = "CeilingFanCrew",
				["clanRating"] = tostring(1500),
				["ownerName"] = "CritStyx",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 2837719,
				["clanName"] = "Nice",
				["clanRating"] = tostring(2200),
				["ownerName"] = "Asimo",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 2025110,
				["clanName"] = "Faze",
				["clanRating"] = tostring(2100),
				["ownerName"] = "Badcc",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 1,
				["clanName"] = "Baboyz",
				["clanRating"] = tostring(1600),
				["ownerName"] = "CritStyx",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 2,
				["clanName"] = "CeilingFanCrew",
				["clanRating"] = tostring(1500),
				["ownerName"] = "CritStyx",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 2837719,
				["clanName"] = "Nice",
				["clanRating"] = tostring(2200),
				["ownerName"] = "Asimo",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 2025110,
				["clanName"] = "Faze",
				["clanRating"] = tostring(2100),
				["ownerName"] = "Badcc",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 1,
				["clanName"] = "Baboyz",
				["clanRating"] = tostring(1600),
				["ownerName"] = "CritStyx",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 2,
				["clanName"] = "CeilingFanCrew",
				["clanRating"] = tostring(1500),
				["ownerName"] = "CritStyx",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 2837719,
				["clanName"] = "Nice",
				["clanRating"] = tostring(2200),
				["ownerName"] = "Asimo",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 2025110,
				["clanName"] = "Faze",
				["clanRating"] = tostring(2100),
				["ownerName"] = "Badcc",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 1,
				["clanName"] = "Baboyz",
				["clanRating"] = tostring(1600),
				["ownerName"] = "CritStyx",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 2,
				["clanName"] = "CeilingFanCrew",
				["clanRating"] = tostring(1500),
				["ownerName"] = "CritStyx",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 2837719,
				["clanName"] = "Nice",
				["clanRating"] = tostring(2200),
				["ownerName"] = "Asimo",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 2025110,
				["clanName"] = "Faze",
				["clanRating"] = tostring(2100),
				["ownerName"] = "Badcc",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 1,
				["clanName"] = "Baboyz",
				["clanRating"] = tostring(1600),
				["ownerName"] = "CritStyx",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 2,
				["clanName"] = "CeilingFanCrew",
				["clanRating"] = tostring(1500),
				["ownerName"] = "CritStyx",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 2837719,
				["clanName"] = "Nice",
				["clanRating"] = tostring(2200),
				["ownerName"] = "Asimo",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 2025110,
				["clanName"] = "Faze",
				["clanRating"] = tostring(2100),
				["ownerName"] = "Badcc",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 1,
				["clanName"] = "Baboyz",
				["clanRating"] = tostring(1600),
				["ownerName"] = "CritStyx",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 2,
				["clanName"] = "CeilingFanCrew",
				["clanRating"] = tostring(1500),
				["ownerName"] = "CritStyx",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 2837719,
				["clanName"] = "Nice",
				["clanRating"] = tostring(2200),
				["ownerName"] = "Asimo",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 2025110,
				["clanName"] = "Faze",
				["clanRating"] = tostring(2100),
				["ownerName"] = "Badcc",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 1,
				["clanName"] = "Baboyz",
				["clanRating"] = tostring(1600),
				["ownerName"] = "CritStyx",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			},
			{
				["ownerUserId"] = 2,
				["clanName"] = "CeilingFanCrew",
				["clanRating"] = tostring(1500),
				["ownerName"] = "CritStyx",
				["clanFlagColor"] = v_u_2.CLAN_COLORS[math.random(1, #v_u_2.CLAN_COLORS)].color
			}
		}
	end
	function v6.render(p11)
		-- upvalues: (ref) v_u_3, (ref) v_u_4, (copy) v_u_8, (copy) v_u_7, (copy) v_u_9
		local v12 = v_u_3.createElement
		local v13 = v_u_4.StoreProvider
		local v14 = {
			["store"] = v_u_8
		}
		local v15 = {}
		local v16 = v_u_3.createElement
		local v17 = {
			["Size"] = UDim2.fromScale(1, 1)
		}
		local v18 = {
			["x"] = v_u_3.createElement(v_u_7, {
				["leaderboardInfo"] = p11.leaderboardInfo,
				["aspectRatio"] = p11.aspectRatio,
				["displayType"] = v_u_9.LEADERBOARD_DISPLAY_TYPE_ENUM.CrewsInServer,
				["attemptViewClanId"] = function()
					print("attempting join")
				end
			}),
			["Aspect"] = v_u_3.createElement("UIAspectRatioConstraint", {
				["AspectRatio"] = p11.aspectRatio
			})
		}
		__set_list(v15, 1, {v16("Frame", v17, v18)})
		return v12(v13, v14, v15)
	end
	local v_u_19 = v_u_3.mount(v_u_3.createElement(v6), p5)
	return function()
		-- upvalues: (ref) v_u_3, (copy) v_u_19
		v_u_3.unmount(v_u_19)
	end
end
