-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMWBGluaXQNY3JlYXRlRWxlbWVudAljcmVhdGVkQXQRYWx3YXlzU2hvd01pbnV0ZXMJY291bnREb3duCXdvcmtzcGFjZRBHZXRTZXJ2ZXJUaW1lTm93BnJlbmRlcgt3aWxsVW5tb3VudAd1bm1vdW50CUNvbXBvbmVudANBcHAGZXh0ZW5kB3JlcXVpcmUHRWxhcHNlZAZzY3JpcHQGUGFyZW50BW1vdW50BGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQVSb2FjdAAGAQEAAAAAAYIAAQAAAAgBARgACAAAAAAHAQIAAAAV+wIAAE0BAsoAAAAA+wIBAOIDBACkBQcAAABgQLwFBbcIAAAAnwUCApUEBQUwBAOJAQAAAKkEAAAwBANaAgAAAKkEAQAwBAOvAwAAAJ8BAwCCAQAACQMCAwMDBAMFBQMBAgMCAAAAAAAANEADBgQAAGBAAwcACQgBGAAAAAAAAgAAAAAAAAABAAABAAD8AAoAAAAAAQEAAAAAAYIAAQAAABEJARgAEQAAAAACAAIAAAAG+wEAAE0AARIAAAAA+wEBAJ8AAgGCAAEAAQMKABQAARgAAAAAAAEVAAAAAAYBAQAAACn7AgAATQECiAAAAABvAwEAvAEBnAIAAACfAQMCpAIEAAAAMECkBQcAAABgQE0EBSQIAAAATQMEpAUAAACfAgICwAMJADADARMKAAAA2QMBABICAAASAAIAMAMBgAsAAADAAwwAMAMBNA0AAAD7BAAATQME5A4AAAD7BQAATQQFyg8AAABSBQEAnwQCAlIFAACfAwMC2QQDABICAAASAAMAggQCABADCwMMAw0DDgQAADBAAw8DEAQAAGBAAxEGAAMBAwgGAgMJAxIDAgQAAQIDBQABGAAAAAAAAAABAAAAAAAAAAABAAABAAAAAAgAAAIAAAAAAAAAAAABAAAABgAAAAADAAABAgAPowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQIAIQYAAACfAQICwAIHABIAAQCCAgIACAMTBAAAAEADFAMVAw4EAABAQAMWBgQBBAEAARgAAQAAAAAAAQAAAAACAAABAAAAAAWk4zZVtgUCYJYnXMFLzcnVxjIinBCDuYRthTlKFnU8h3yKK+WUloi8

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Roact)
return function(p3)
	-- upvalues: (copy) v_u_2
	local v4 = v_u_2.Component:extend("App")
	local v_u_5 = require(script.Parent.Elapsed)
	function v4.init(_) end
	function v4.render(_)
		-- upvalues: (ref) v_u_2, (copy) v_u_5
		return v_u_2.createElement(v_u_5, {
			["createdAt"] = workspace:GetServerTimeNow() + 20,
			["alwaysShowMinutes"] = false,
			["countDown"] = true
		})
	end
	function v4.willUnmount(_) end
	local v_u_6 = v_u_2.mount(v_u_2.createElement(v4), p3)
	return function()
		-- upvalues: (ref) v_u_2, (copy) v_u_6
		v_u_2.unmount(v_u_6)
	end
end
