-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMVBGluaXQFcHJpbnQIb25TdWJtaXQOd2FudHMgdG8gY2xvc2UHb25DbG9zZQ1jcmVhdGVFbGVtZW50BnJlbmRlcgt3aWxsVW5tb3VudAd1bm1vdW50CUNvbXBvbmVudANBcHAGZXh0ZW5kB3JlcXVpcmUKUmVwb3J0Q3JldwZzY3JpcHQGUGFyZW50BW1vdW50BGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQVSb2FjdAAIAQEAAAAAAYIAAQAAAAgBARgACAAAAAAEAgAAAAAJpAIBAAAAAEBSAwAAnwICAaQCAQAAAABAUgMBAJ8CAgGCAAEAAgMCBAAAAEAACwMBGAAAAAABAAAAAQwAAAAAAgAAAAAABaQAAQAAAABAbwECAJ8AAgGCAAEAAwMCBAAAAEADBAAPBQEYAAAAAAEQAAAAAAUBAgAAAA37AgAATQECygAAAAD7AgEA4gMDAMAEBAAwBAMGAQAAAMAEBQAwBAN7AgAAAJ8BAwCCAQAABgMGAwMDBQUCAQIGAQYCAgECCQcBGAAAAAAAAQAABAAA+wAKAAAAAAEBAAAAAAGCAAEAAAAUCAEYABQAAAAAAgACAAAABvsBAABNAAESAAAAAPsBAQCfAAIBggABAAEDCQAXAAEYAAAAAAABGAAAAAAGAQEAAAAp+wIAAE0BAogAAAAAbwMBALwBAZwCAAAAnwEDAqQCBAAAADBApAUHAAAAYEBNBAUkCAAAAE0DBL0FAAAAnwICAsADCQAwAwETCgAAANkDAQASAgAAEgACADADAYALAAAAwAMMADADATQNAAAA+wQAAE0DBOQOAAAA+wUAAE0EBcoPAAAAUgUBAJ8EAgJSBQAAnwMDAtkEAwASAgAAEgADAIIEAgAQAwoDCwMMAw0EAAAwQAMOAw8EAABgQAMQBgADAQMHBgQDCAMRAwYEAAMEBQUAARgAAAAAAAAAAQAAAAAAAAAAAQAAAQAAAAALAAACAAAAAAAAAAAAAQAAAAYAAAAAAwAAAQIAD6MAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0CACEGAAAAnwECAsACBwASAAEAggICAAgDEgQAAABAAxMDFAMNBAAAQEADFQYGAQYBAAEYAAEAAAAAAAEAAAAAAgAAAQAAAAAHI6T/o0+77IgRYJU38YgifM81M/WyOXM9fUXPQLGVndsGC8DDPQCltw==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Roact)
return function(p3)
	-- upvalues: (copy) v_u_2
	local v4 = v_u_2.Component:extend("App")
	local v_u_5 = require(script.Parent.ReportCrew)
	function v4.init(_) end
	function v4.render(_)
		-- upvalues: (ref) v_u_2, (copy) v_u_5
		return v_u_2.createElement(v_u_5, {
			["onSubmit"] = function(p6, p7)
				print(p6)
				print(p7)
			end,
			["onClose"] = function()
				print("wants to close")
			end
		})
	end
	function v4.willUnmount(_) end
	local v_u_8 = v_u_2.mount(v_u_2.createElement(v4), p3)
	return function()
		-- upvalues: (ref) v_u_2, (copy) v_u_8
		v_u_2.unmount(v_u_8)
	end
end
