-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMWCExpdmUyMDI0DkZpbmRGaXJzdENoaWxkBlJ1bm5lcgxNb2R1bGVTY3JpcHQDSXNBD2dldFJ1bm5lck1vZHVsZQdyZXF1aXJlBXByaW50DGdvbm5hIHN0YXJ0IQVzdGFydARnYW1lEVJlcGxpY2F0ZWRTdG9yYWdlCkdldFNlcnZpY2UDQXBwCVJ1bkNvbnN0cwhSdW5VdGlscwhnZXRXb3JsZA9NQUlOX1dPUkxEX05BTUUFcGNhbGwEd2FybgR0YXNrBHdhaXQABAUAAQAAABX7AAAAbwIAALwAAAMBAAAAnwADAisAAgDGAQAAggECAG8DAgC8AQADAQAAAJ8BAwIOAQUAbwQDALwCAf4EAAAAnwIDAisCAgDGAgAAggICAIIBAgAFAwEDAgMDAwQDBQAIBgEYAAAAAAABAQACAAAAAQAAAAAAAQACCQAAAAAGAAIAAAAX+wEBAG8DAAC8AQEDAQAAAJ8BAwIrAQIAxgAAAGUADQBvBAIAvAIBAwEAAACfAgMCDgIFAG8FAwC8AwL+BAAAAJ8DAwIrAwIAxgAAAGUAAQBSAAIA3gAAAIIAAQAFAwEDAgMDAwQDBQAVAAEYAAAAAAABAQACAAAAAQAAAAAAAQACBQEJAAAAAAMAAQAAAAykAAEAAAAAQPsBAACfAAICpAEDAAAAIEBvAgQAnwECAU0BAPwFAAAAnwEBAYIAAQAGAwcEAAAAQAMIBAAAIEADCQMKAB4AARgAAAAAAQAAAAEAAAEfAAAAAAkAAAEAAEWjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwDBBgAAAE0CA28HAAAAnwECAqQCBQAAAEBATQQAwQYAAABNAwRCCAAAAJ8CAgJNAwJxCQAAAJ8DAQJNBAHjCgAAAPEDAgAEAAAAggABAMADCwASAAAAxgQAAKQFDQAAAMBA2QYBABIBBP8SAAAAnwUCAysFBACkBw8AAADgQFIIBgCfBwIBDgQSAKQHEgAARACBjAgBAJ8HAgGkBw0AAADAQNkIAgASAQT/nwcCA1IFBwBSBggAKwUEAKQHDwAAAOBAUggGAJ8HAgHBBAAAggABAKQHEgAARACBjAgBAJ8HAgHBBAAASADb/4IAAQATAwsEAAAAQAMMAw0DBwQAAEBAAw4DDwMQAxEDEgYAAxMEAADAQAMUBAAA4EADFQMWBABEAIEDAAECAQABGAABAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAgAMAQAAAAAAAwEAAAACAgAAAAEAAAAAAAAFAQAAAAIAAgAAAADrFwEAAAAAA2O66TqRsrhMUX6DrgReHLNvuj1r9WTGG3ZfD3IKSHJ959gB8DiHFEg=

-- Decompiled by Krnl

local v_u_1 = game:GetService("ReplicatedStorage")
local v2 = require(v_u_1.App.RunConsts)
if require(v_u_1.App.RunUtils).getWorld() ~= v2.MAIN_WORLD_NAME then
	return
end
while true do
	local v_u_3 = nil
	local v6, v7 = pcall(function()
		-- upvalues: (ref) v_u_3, (copy) v_u_1
		local v4 = v_u_1:FindFirstChild("Live2024")
		local v5
		if v4 then
			v5 = v4:FindFirstChild("Runner")
			if not (v5 and v5:IsA("ModuleScript")) then
				v5 = nil
			end
		else
			v5 = nil
		end
		v_u_3 = v5
	end)
	if not v6 then
		warn(v7)
	end
	if v_u_3 then
		task.wait(1)
		local v9, v10 = pcall(function()
			-- upvalues: (ref) v_u_3
			local v8 = require(v_u_3)
			print("gonna start!")
			v8.start()
		end)
		if not v9 then
			warn(v10)
		end
		return
	end
	task.wait(1)
end
