-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNRCUNoYXJhY3RlcghIdW1hbm9pZA5GaW5kRmlyc3RDaGlsZAhSb290UGFydAtHZXRSb290UGFydAxzZXRtZXRhdGFibGUDbmV3BV9tYWlkCVNjcmVlbkd1aQhQb3NpdGlvbgZSYWRpdXMKQW5pbVJhZGl1cwtTdGFydFJhZGl1cwlFbmRSYWRpdXMHRW5hYmxlZAhJbnN0YW5jZQpJbWFnZUxhYmVsD0JvcmRlclNpemVQaXhlbBZCYWNrZ3JvdW5kVHJhbnNwYXJlbmN5BkNvbG9yMwtJbWFnZUNvbG9yMxdyYnhhc3NldGlkOi8vMjgxOTMyNjU0NwVJbWFnZQdWZWN0b3IyC0FuY2hvclBvaW50BlpJbmRleAtXb3JsZE1hcmtlcgROYW1lBUZyYW1lCEdpdmVUYXNrBVVEaW0yBFNpemUGUGFyZW50CkZyYW1lSW5uZXIIU2V0U2l6ZXMJU2V0UmFkaXVzClNldEVuYWJsZWQGX3NpemVzB1Zpc2libGUXSW1wb3J0YW50TG9jYXRpb25NYXJrZXIFcHJpbnQPc2V0dGluZyBlbmFibGVkDFNldFNjcmVlbkd1aQlGcmFtZUljb24GYXNzZXJ0D0NyZWF0ZUZyYW1lSWNvbgdEZXN0cm95EERlc3Ryb3lGcmFtZUljb24PcmJ4YXNzZXRpZDovLyVkBmZvcm1hdAdTZXRJY29uC1NldFBvc2l0aW9uC0dldFBvc2l0aW9uC09uQ29tcGxldGVkB0Nvbm5lY3QNQW5pbWF0ZVJhZGl1cwhfYWRvcm5lZQpTZXRBZG9ybmVlCkdldEFkb3JuZWUMQWJzb2x1dGVTaXplAVgBWRJXb3JsZFRvU2NyZWVuUG9pbnQBWgRtYXRoA21pbglNYWduaXR1ZGUGVXBkYXRlBGdhbWUHUGxheWVycwpHZXRTZXJ2aWNlC0xvY2FsUGxheWVyEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUEQW5pbQZNb2R1bGUDU3RkBE1haWQJd29ya3NwYWNlDUN1cnJlbnRDYW1lcmEHX19pbmRleAASBAABAAAAEvsBAABNAAFpAAAAAEcAAwAAAACAxgEAAIIBAgBvAwEAvAEAAwIAAACfAQMCRwEDAAAAAIDGAgAAggICAE0CAUYDAAAAggICAAQDAQMCAwMDBAAOBQEYAAAAAQABAAIAAAABAAEAAgAADwAAAAAIAAMAAACSAf8ABQAAAAAA+wMAAJ49AAQDAAAAUgIAAKQBAQAAAABAnwEDAfsCAQBNAQLvAgAAAJ8BAQIwAQDBAwAAAMYBAAAwAQB6BAAAAMYBAAAwAQA7BQAAAIwBCAAwAQBxBgAAAMYBAAAwAQBIBwAAAMYBAAAwAQBGCAAAAMYBAAAwAQAoCQAAAKkBAAAwAQDwCgAAAKQBDAAACLCAbwINAJ8BAgKMAgAAMAIBjg4AAACMAgEAMAIBOg8AAACkAhEAAAgAgYwDAACMBAAAjAUAAJ8CBAIwAgEAEgAAAG8CEwAwAgGpFAAAAKQCFgAACFCBbwMXAG8EFwCfAgMCMAIB6BgAAACMAgEAMAIBDRkAAABvAhoAMAIBuhsAAAAwAQCdHAAAAE0CAMEDAAAATQQAnRwAAAC8AgL9HQAAAJ8CAwGkAgwAAAiwgG8DDQCfAgICjAMAADADAo4OAAAAjAMBADADAjoPAAAApAMRAAAIAIFvBB4AbwUeAG8GHgCfAwQCMAMCABIAAABvAxMAMAMCqRQAAACkAyAAAAjwgW8EIQCMBQAAbwYhAIwHAACfAwUCMAMCLyIAAACkAyAAAAjwgW8EFwCMBQAAbwYXAIwHAACfAwUCMAMCOwUAAACkAxYAAAhQgW8EFwBvBRcAnwMDAjADAugYAAAAjAMCADADAg0ZAAAAMAECJCMAAAAwAgB4JAAAAPsFAgC8AwDqJQAAAJ8DAwFNBQBxBgAAALwDAD4mAAAAnwMDAakFAQC8AwCeJwAAAJ8DAwGCAAIAKAMGBAAAAEADBwMIAwkDCgMLAwwDDQMOAw8DEAQACLCAAxEDEgMTAxQEAAgAgQMVAxYDFwMYBAAIUIECAAAAAAAA4D8DGQMaAxsDHAMdAx4CmpmZmZmZuT8DHwQACPCBAjMzMzMzM+s/AyADIQMiAyMDJAMlACAHARgAAAEAAAAAAAACAAAAAAACAAABAAABAAADAAABAAABAAACAAACAAAAAQAAAQAAAQAAAAAAAAABAAABAAAAAAAAAQAAAQAAAQACAAAAAAAAAgAAAAEAAAEAAAEAAAAAAAAAAQAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAEAAQACAAAAAQAAAAABAAAAAiEAAAAAAgIBAAAABSsBAQD7AQAAMAEANgAAAACCAAEAAQMmAE8jARgAAQIAAVEAAAAABQIAAAAAEjABAPAAAAAATQIAnQEAAAAwAQKAAgAAAE0DAJ0BAAAATQIDugMAAADwAgYABAAAgKQCBgAAAFBAbwMHAFIEAQCfAgMBggABAAgDDwMdAycDHAMoAykEAABQQAMqAFYlARgAAAEAAAABAAAAAAABAAAAAAJXAAAAAAQCAAAAAAkwAQB6AAAAAE0CAJ0BAAAATQMAegAAAAAwAwIkAgAAAIIAAQADAwkDHQMhAF0rARgAAAEAAAAAAAJeAAAAAAcBAAAAADdNAwCCAAAAAEcDAgAAAAAAqQIAAakCAQC7AQICpAECAAAAEECfAQIBpAEFAAAQMIBvAgYAnwECAowCAAAwAgGOBwAAAIwCAQAwAgE6CAAAAKQCCgAAEJCAjAMBAIwEAACMBQEAjAYAAJ8CBQIwAgEvCwAAAKQCCgAAEJCAbwMMAIwEAABvBQwAjAYAAJ8CBQIwAgE7DQAAAKQCDwAAEOCAbwMMAG8EDACfAgMCMAIB6BAAAACMAgMAMAIBDREAAABNAgB4EgAAADACASQTAAAAMAEAggAAAACCAAEAFAMsAy0EAAAQQAMQAwcEABAwgAMRAxIDEwMfBAAQkIADIAIAAAAAAADgPwMKAxgEABDggAMZAxoDIgMhAGIuARgAAAAAAAAAAAAAAQAAAAEAAAEAAAEAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAABAAABAAAAAQABYwAAAAAEAQAAAAATTQMAggAAAABHAwIAAAAAgKkCAAGpAgEAuwECAqQBAgAAABBAnwECAU0BAIIAAAAAvAEBUAMAAACfAQIBxgEAADABAIIAAAAAggABAAQDLAMtBAAAEEADLwBuMAEYAAAAAAAAAAAAAAEAAAAAAQAAAW8AAAAABgIAAAAHAAABAwMNAiBHARcAAAAAAE0CAIIAAAAARwIEAAAAAIC8AgCMAQAAAJ8CAgFNAgCCAAAAAG8DAgBSBQEAvAMDjQMAAACfAwMCMAMCqQQAAABNBABxBQAAALwCAD4GAAAAnwIDAYIAAQBNAgCCAAAAAEcCBAAAAAAAvAIApwcAAACfAgIBggABAAgDLAMuAzEDMgMXAwsDJAMwAHMzARgAAAEAAAABAAACAAAAAAAAAAADAAAAAAACAAAAAQAAA3QAAAAAAgIAAAAAAzABADsAAAAAggABAAEDCgCCATQBGAAAAYMAAAAAAgEAAAAAA00BADsAAAAAggECAAEDCgCFATUBGAAAAIYAAAAACQIAAAAALjABAHEAAAAATQIAnQEAAACkAwQAAAwggIwEAACMBgIACQUGAYwGAACMCAIACQcIAZ8DBQIwAwIvBQAAAE0CAIIGAAAARwIbAAAAAACMAggAYAENAAIAAABNAwCCBgAAAE0CA4AHAAAAKgISAAEAAIBNAgCCBgAAAKkDAAAwAwKABwAAAIIAAQBNAwCCBgAAAE0CA4AHAAAAKgIGAAAAAIBNAgCCBgAAAKkDAQAwAwKABwAAAIIAAQAIAwsDHQMfAwcEAAwggAMgAywDJwCIASQBGAAAAQAAAAAAAAAAAAAAAAIAAAABAAABAAAAAAABAAAAAAADAAAAAAABAAAAAASJAAAAAAQAAQAAABL7AQAATQABSAAAAAC8AABQAQAAAJ8AAgH7AAAAxgEAADABAEgAAAAA+wAAAPsDAABNAgMoAgAAALwAAD4DAAAAnwADAYIAAQAEAwwDLwMOAyQAoQEAARgAAAAAAAABAAAAAgAAAAAAAAGiAAAAAAYCAQAAACFNAgBIAAAAAEcCCQAAAAAATQIASAAAAAC8AgJQAQAAAJ8CAgHGAgAAMAIASAAAAABNAgBxAgAAADACAEYDAAAAMAEAKAQAAAD7AwAATQID7wUAAABvAwYAnwICAk0DAs8HAAAA2QUAABIAAAC8AwPHCAAAAJ8DAwEwAgBIAAAAAIIAAQAJAwwDLwMLAw0DDgMHApqZmZmZmbk/AzYDNwELmAE4ARgAAAAAAQAAAAABAAACAAAAAQACAAAAAAEAAAAAAAAGAAGZAAAAAAQCAAAAAAkwAQB1AAAAAE0DAHUAAAAATQIDOwEAAAAwAgA7AQAAAIIAAQACAzkDCgCpAToBGAAAAQAAAAAAAaoAAAAAAgEAAAAAA00BAHUAAAAAggECAAEDOQCtATsBGAAAAK4AAAAAFQECAAAAxAFNAQDwAAAAACsBAQCCAAEATQIAegEAAABNAQJxAgAAAE0CAXkDAAAATQMBeAQAAABNBAB1BQAAAA4EBgBNBQB1BQAAAE0EBTsGAAAAMAQAOwYAAABNBAA7BgAAACsEAQCCAAEA+wQAAE0GADsGAAAAvAQEsQcAAACfBAMCTQUEeQMAAABNBgR4BAAAAE0IBHsIAAAAjAkAALcIAgAJAAAAqQcAAakHAQBNCQBxCgAAAJUICQlNCgBxCgAAAJUJCgmpCgAAYAUDAAgAAABSBQgAqQoBACYLAghgCwMABQAAACYFAgipCgEAYAYDAAkAAABSBgkAqQoBACYLAwlgCwMABgAAACYGAwmpCgEADgcgAKkKAQBSCwUAUgwGACYFAgUmBgMGnhMFBQsAAABSDgUAUg8LAKQNDQAAMLCAnw0DAp4TBgUMAAAAUg8GAFIQDACkDg0AADCwgJ8OAwJgDQcADgAAAGAFAwALAAAAUgUIAGUABwAmBQIIZQAFAGAGAwAMAAAAUgYJAGUAAQAmBgMJTQsAnQ4AAACkDBEAAEDwgIwNAABSDgUAjA8AAFIQBgCfDAUCMAwLOwYAAABvCxIA+w4BAE0NDmkTAAAARw0DAAAAAIDGDAAAZQAKAG8QFAC8Dg0DFQAAAJ8OAwJHDgMAAAAAgMYMAABlAAIATQwORhYAAAAODAcATQ4MOwYAAABNDwA7BgAAACYNDg9NCw2qFwAAAMYNAAAOCgQATQ4ANhgAAAATDQ4AZQATAIwQAgBNEQA2GAAAABwOEQCMDwEAqA4NAE0TADYYAAAAhxITEBMREgBNFAA2GAAAAIcTFBATEhMBfQsDABEAAABSDRIAZQABAIsO8/+7AQ0DUg8NAKQOGgAAAJBBnw4CAU0OACgbAAAA8Q4FAA0AAABSEA0AvA4AjhwAAACfDgMBTQ4ASB0AAABHDhEAAAAAAE0OAEgdAAAAvA4OJh4AAACfDgICTRMARh8AAAD1FCAOCRITFE0UACgbAAAACRMUDkMREhO8DwA+IQAAAJ8PAwGCAAEAIgMPAwkDPAM9Az4DOQMKAz8DQAIAAAAAAAAQQAMLA0EDQgQAMLCAAx0DHwMHBABA8IACAAAAAAAA8H8DAQMCAwMDBANDAyYDLQQAAJBBAw4DOAMMA0QDDQIAAAAAAADwPwMkALABRAEHogAAAQQAAAABAAAAAQAAAQAAAAAAAgAAAQIAAAAAAAEAAAABAAAAAAAAAgAAAQAAAgMAAQECAAABAQIAAQECAAABAQMBAgECAQEAAAAAAAABAAAAAAAAAQABAAEAAgADAAEAAgQAAAAAAAAAAAAAAxsAAAEAAQACAAAAAQABAAL43wEAAAAAAAACAQIAAAACAAAAAAABAAAAAQAAAAEAAQH7CQAAAAABAAAAAQAAAAMAAAABAAAAAAEAAAAAAAAAAAAAAg8AAAAIAAAAAAQBAAAAABZNAQDBAAAAALwBAVABAAAAnwECAcYBAAAwAQDBAAAAAMYBAAAwAQB6AgAAAMYBAAAwAQA7AwAAAIE9AAUEAAAAUgIAAG8DBACkAQYAAABQQJ8BAwGCAAEABwMIAy8DCQMKAAMGBAAAUEAAkQIvARgAAAAAAAEAAAEAAAEAAAEAAAAAAAABEgEAAAAOAAABAgBzowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAk0BADEEAAAApAIBAAAAAEBvBAUAvAICFgMAAACfAgMCpAMHAAAAYEBNBQJACQAAAE0EBQ4IAAAAnwMCAqQEBwAAAGBATQYCoQoAAABNBQZ2CwAAAJ8EAgKkBg0AAADAQE0FBkgOAAAAwAYPABIAAQD/BwAABAAAAIwIBAD/CQAAAgAAAIwKMACMCwAAxQkKAwEAAAD/CgAAAgAAAIwLwACMDBgAxQoLAwEAAAD/CwAAAgAAAG8MEACMDQgAxQsMAwEAAADFBwgFAQAAAP8IBQAAAAAAMAgIbhEAAADACRIAEgAIABIABAASAAcAMAkI7xMAAADACRQAEgAHADAJCOoVAAAAwAkWADAJCJ4XAAAAwAkYADAJCBQZAAAAwAkaADAJCIwbAAAAwAkcADAJCKcdAAAAwAkeADAJCCofAAAAwAkgADAJCOghAAAAwAkiADAJCPwjAAAAwAkkADAJCD4lAAAAwAkmABIAAwAwCQiOJwAAAMAJKAAwCQhXKQAAAMAJKgAwCQhjKwAAAMAJLAASAAUAEgABADAJCCYtAAAAwAkuADAJCFAvAAAAgggCADADRQQAAABAA0YDRwNIA0kDSgQAAGBAA0sDTANNA04DTwQAAMBAA1AGAAIAAAAAAADwfwNRBgEDBwYCAyMGAwMlBgQDKwYFAy4GBgMwBgcDMwYIAzQGCQM1BgoDJAYMAzgGDQM6Bg4DOwYPA0QGEAMvEAABAgMEBQYHCAkKDA0ODxABAAEGAAEAAAAAAAEAAQAAAAAAAQAAAAAAAAEAAAAAAAADAAAABQAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAQABAOEAAAAvAAAABwAABwAABQAADAAABQAADwAAAwAAAwAAEAAAABEAAAQAAAMAAAAAYQAABwEAAAAfAAAAABHO4t2sLtGKnfwmtzhMaT4vjBj15r30yu05Xo3GdUihgd8gU4xAVTyz

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players").LocalPlayer
local v2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v2.Module.Anim)
local v_u_4 = require(v2.Std.Maid)
local v_u_5 = workspace.CurrentCamera
local v_u_6 = {
	4,
	{ 48, 0 },
	{ 192, 24 },
	{ (1 / 0), 8 }
}
local v_u_7 = {}
v_u_7.__index = v_u_7
function v_u_7.new()
	-- upvalues: (copy) v_u_7, (copy) v_u_4, (copy) v_u_6
	local v8 = {}
	local v9 = v_u_7
	setmetatable(v8, v9)
	v8._maid = v_u_4.new()
	v8.ScreenGui = nil
	v8.Position = nil
	v8.Radius = 8
	v8.AnimRadius = nil
	v8.StartRadius = nil
	v8.EndRadius = nil
	v8.Enabled = false
	local v10 = Instance.new("ImageLabel")
	v10.BorderSizePixel = 0
	v10.BackgroundTransparency = 1
	v10.ImageColor3 = Color3.new(0, 0, 0)
	v10.Image = "rbxassetid://2819326547"
	v10.AnchorPoint = Vector2.new(0.5, 0.5)
	v10.ZIndex = 1
	v10.Name = "WorldMarker"
	v8.Frame = v10
	v8._maid:GiveTask(v8.Frame)
	local v11 = Instance.new("ImageLabel")
	v11.BorderSizePixel = 0
	v11.BackgroundTransparency = 1
	v11.ImageColor3 = Color3.new(0.1, 0.1, 0.1)
	v11.Image = "rbxassetid://2819326547"
	v11.Size = UDim2.new(0.85, 0, 0.85, 0)
	v11.Position = UDim2.new(0.5, 0, 0.5, 0)
	v11.AnchorPoint = Vector2.new(0.5, 0.5)
	v11.ZIndex = 2
	v11.Parent = v10
	v8.FrameInner = v11
	v8:SetSizes(v_u_6)
	v8:SetRadius(v8.Radius)
	v8:SetEnabled(true)
	return v8
end
function v_u_7.SetSizes(p12, p13)
	-- upvalues: (copy) v_u_6
	p12._sizes = p13 or v_u_6
end
function v_u_7.SetEnabled(p14, p15)
	p14.Enabled = p15
	p14.Frame.Visible = p15
	if p14.Frame.Name == "ImportantLocationMarker" then
		print("setting enabled", p15)
	end
end
function v_u_7.SetScreenGui(p16, p17)
	p16.ScreenGui = p17
	p16.Frame.Parent = p16.ScreenGui
end
function v_u_7.CreateFrameIcon(p18)
	local v19 = p18.FrameIcon == nil
	assert(v19)
	local v20 = Instance.new("ImageLabel")
	v20.BorderSizePixel = 0
	v20.BackgroundTransparency = 1
	v20.Size = UDim2.new(1, 0, 1, 0)
	v20.Position = UDim2.new(0.5, 0, 0.5, 0)
	v20.AnchorPoint = Vector2.new(0.5, 0.5)
	v20.ZIndex = 3
	v20.Parent = p18.FrameInner
	p18.FrameIcon = v20
end
function v_u_7.DestroyFrameIcon(p21)
	local v22 = p21.FrameIcon ~= nil
	assert(v22)
	p21.FrameIcon:Destroy()
	p21.FrameIcon = nil
end
function v_u_7.SetIcon(p23, p24)
	if p24 == nil then
		if p23.FrameIcon ~= nil then
			p23:DestroyFrameIcon()
		end
	else
		if p23.FrameIcon == nil then
			p23:CreateFrameIcon()
		end
		p23.FrameIcon.Image = ("rbxassetid://%d"):format(p24)
		p23:SetRadius(p23.Radius)
	end
end
function v_u_7.SetPosition(p25, p26)
	p25.Position = p26
end
function v_u_7.GetPosition(p27)
	return p27.Position
end
function v_u_7.SetRadius(p28, p29)
	p28.Radius = p29
	p28.Frame.Size = UDim2.new(0, 2 * p29, 0, 2 * p29)
	if p28.FrameIcon ~= nil then
		if p29 < 8 then
			if p28.FrameIcon.Visible == true then
				p28.FrameIcon.Visible = false
				return
			end
		elseif p28.FrameIcon.Visible == false then
			p28.FrameIcon.Visible = true
		end
	end
end
function v_u_7.AnimateRadius(p_u_30, p31)
	-- upvalues: (copy) v_u_3
	if p_u_30.AnimRadius ~= nil then
		p_u_30.AnimRadius:Destroy()
		p_u_30.AnimRadius = nil
	end
	p_u_30.StartRadius = p_u_30.Radius
	p_u_30.EndRadius = p31
	local v32 = v_u_3.new(0.1)
	v32.OnCompleted:Connect(function()
		-- upvalues: (copy) p_u_30
		p_u_30.AnimRadius:Destroy()
		p_u_30.AnimRadius = nil
		p_u_30:SetRadius(p_u_30.EndRadius)
	end)
	p_u_30.AnimRadius = v32
end
function v_u_7.SetAdornee(p33, p34)
	p33._adornee = p34
	p33.Position = p33._adornee.Position
end
function v_u_7.GetAdornee(p35)
	return p35._adornee
end
function v_u_7.Update(p36)
	-- upvalues: (copy) v_u_5, (copy) v_u_1
	if not p36.Enabled then
		return
	end
	local v37 = p36.ScreenGui.AbsoluteSize
	local v38 = v37.X
	local v39 = v37.Y
	if p36._adornee then
		p36.Position = p36._adornee.Position
	end
	if not p36.Position then
		return
	end
	local v40 = v_u_5:WorldToScreenPoint(p36.Position)
	local v41 = v40.X
	local v42 = v40.Y
	local v43 = v40.Z < 0
	local v44 = p36.Radius + 4
	local v45 = p36.Radius + 4
	local v46
	if v41 < v44 then
		v41 = v44
		v46 = true
	else
		v46 = false
	end
	if v38 - v44 < v41 then
		v41 = v38 - v44
		v46 = true
	end
	if v42 < v45 then
		v42 = v45
		v46 = true
	end
	if v39 - v45 < v42 then
		v42 = v39 - v45
		v46 = true
	end
	local v47
	if v43 then
		v46 = true
		local v48 = v38 - v41
		v47 = v39 - v42
		if math.min(v48, v41) < math.min(v47, v42) then
			if v48 >= v41 then
				v44 = v38 - v44
			end
		elseif v47 < v42 then
			v47 = v45
			v44 = v48
		else
			v47 = v39 - v45
			v44 = v48
		end
	else
		v47 = v42
		v44 = v41
	end
	p36.Frame.Position = UDim2.new(0, v44, 0, v47)
	local v49 = (1 / 0)
	local v50 = v_u_1.Character
	local v51
	if v50 == nil then
		v51 = nil
	else
		local v52 = v50:FindFirstChild("Humanoid")
		if v52 == nil then
			v51 = nil
		else
			v51 = v52.RootPart
		end
	end
	if v51 then
		v49 = (v51.Position - p36.Position).Magnitude
	end
	local v53 = nil
	if v46 then
		v53 = p36._sizes[1]
	else
		for v54 = 2, #p36._sizes do
			local v55 = p36._sizes[v54][1]
			local v56 = p36._sizes[v54][2]
			if v49 <= v55 then
				v53 = v56
				break
			end
		end
	end
	assert(v53)
	if p36.EndRadius ~= v53 then
		p36:AnimateRadius(v53)
	end
	if p36.AnimRadius ~= nil then
		local v57 = p36.AnimRadius:Update()
		p36:SetRadius(p36.StartRadius * (1 - v57) + p36.EndRadius * v57)
	end
end
function v_u_7.Destroy(p58)
	p58._maid:Destroy()
	p58._maid = nil
	p58.ScreenGui = nil
	p58.Position = nil
	setmetatable(p58, nil)
end
return v_u_7
