-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNwB19faW5kZXgGdHlwZW9mBnN0cmluZwVlcnJvch9JbnZhbGlkIHR5cGUgbmFtZSBwcm92aWRlZDogbmlsC15bJWQlbF0ldyokBGZpbmRwSW52YWxpZCB0eXBlIG5hbWUgcHJvdmlkZWQ6ICIlcyIsIHR5cGUgbmFtZXMgbXVzdCBiZSBhbHBoYW51bWVyaWMgYW5kIHN0YXJ0IHdpdGggYSBsb3dlci1jYXNlIGxldHRlciBvciBhIGRpZ2l0LgZmb3JtYXQFcGFpcnMLVHlwZU1ldGhvZHMcVW5rbm93biBrZXkvbWV0aG9kIGluIHR5cGUgIgMiOiAFVHlwZXMmVHlwZSAiJXMiIGhhcyBhbHJlYWR5IGJlZW4gcmVnaXN0ZXJlZC4ETmFtZQtEaXNwbGF5TmFtZQhQcmVmaXhlcxJSZWdpc3RlclR5cGVQcmVmaXgMUmVnaXN0ZXJUeXBlC1R5cGVBbGlhc2VzBSVzICVzHVR5cGUgYWxpYXMgJXMgYWxyZWFkeSBleGlzdHMhBmFzc2VydBFSZWdpc3RlclR5cGVBbGlhcwtHZXRDaGlsZHJlbgxNb2R1bGVTY3JpcHQDSXNBBENtZHIOUmVwbGljYXRlZFJvb3QGUGFyZW50B3JlcXVpcmUPUmVnaXN0ZXJUeXBlc0luDkNvbW1hbmRNZXRob2RzHlVua25vd24ga2V5L21ldGhvZCBpbiBjb21tYW5kIA91bmtub3duIGNvbW1hbmQCOiAEQXJncwR0eXBlBXRhYmxlD0NvbW1hbmRBcmdQcm9wczFVbmtub3duIHByb3BlcnR5IGluIGNvbW1hbmQgIiVzIiBhcmd1bWVudCAjJWQ6ICVzB3Vua25vd24IQXV0b0V4ZWMISXNDbGllbnQOQXV0b0V4ZWNCdWZmZXIGaW5zZXJ0G0ZsdXNoQXV0b0V4ZWNCdWZmZXJEZWZlcnJlZAhDb21tYW5kcwVsb3dlcgdBbGlhc2VzDUNvbW1hbmRzQXJyYXkVUmVnaXN0ZXJDb21tYW5kT2JqZWN0UkludmFsaWQgcmV0dXJuIHZhbHVlIGZyb20gY29tbWFuZCBzY3JpcHQgIiUqIiAoQ29tbWFuZERlZmluaXRpb24gZXhwZWN0ZWQsIGdvdCAlKikDUnVuD1JlZ2lzdGVyQ29tbWFuZAZTZXJ2ZXIORmluZEZpcnN0Q2hpbGQSUmVnaXN0ZXJDb21tYW5kc0luBHdhcm4PQ29tbWFuZCBzY3JpcHQgViB3YXMgc2tpcHBlZCBiZWNhdXNlIGl0IGhhcyAnU2VydmVyJyBpbiBpdHMgbmFtZSwgYW5kIGhhcyBubyBlcXVpdmFsZW50IHNoYXJlZCBzY3JpcHQuBUdyb3VwDk1ha2VEaWN0aW9uYXJ5FURlZmF1bHRDb21tYW5kc0ZvbGRlchdSZWdpc3RlckRlZmF1bHRDb21tYW5kcwAKR2V0Q29tbWFuZAtHZXRDb21tYW5kcw9HZXRDb21tYW5kTmFtZXMMR2V0VHlwZU5hbWVzB0dldFR5cGULR2V0VHlwZU5hbWUIcHJpb3JpdHkFSG9va3MVSW52YWxpZCBob29rIG5hbWU6ICVxCGNhbGxiYWNrBHNvcnQMUmVnaXN0ZXJIb29rBlN0b3JlcwhHZXRTdG9yZRdBdXRvRXhlY0ZsdXNoQ29ubmVjdGlvbgpEaXNjb25uZWN0E0ZsdXNoQXV0b0V4ZWNCdWZmZXIJSGVhcnRiZWF0B0Nvbm5lY3QGaXBhaXJzCkRpc3BhdGNoZXIORXZhbHVhdGVBbmRSdW4EZ2FtZQpSdW5TZXJ2aWNlCkdldFNlcnZpY2UGc2NyaXB0BFV0aWwJVHJhbnNmb3JtCFZhbGlkYXRlDEF1dG9jb21wbGV0ZQVQYXJzZQhMaXN0YWJsZQxWYWxpZGF0ZU9uY2UHRGVmYXVsdAtEZXNjcmlwdGlvbglDbGllbnRSdW4ERGF0YQRUeXBlCE9wdGlvbmFsCUJlZm9yZVJ1bghBZnRlclJ1bgxzZXRtZXRhdGFibGUPUmVnaXN0ZXJIb29rc0luFEdldENvbW1hbmRzQXNTdHJpbmdzB0FkZEhvb2sAGAMCAAAAAAX/AgAAAAAAAGoCAAGHAgABggICAAAAFAEBGAAAAAEAFQAAAAAOAwAAAAsAAAIDBBUCAwQ2Ak4OAQcAuywBA1IEAQCkAwEAAAAAQJ8DAgLwAwUAAgAAAKQDBAAAADBAbwQFAJ8DAgFvBQYAvAMBVgcAAACfAwMCKwMIAKQDBAAAADBAbwQIAFIGAQC8BASNCQAAAJ8EAwCfAwABpAMLAAAAoEBSBAIAnwMCBBcDDQBNCQAYDAAAAIcICQZHCAkAAAAAgKQIBAAAADBAbwoNAFILAQBvDA4AUg0GAHMJCg2fCAIBbgPy/wEAAABNBADvDwAAAIcDBAFHAwkAAAAAAKQDBAAAADBAbwQQAFIGAQC8BASNCQAAAJ8EAwCfAwABMAECuhEAAABNBAJXEgAAAMoDBAEwAwJXEgAAAE0DAO8PAAAAagIDAU0DAj8TAAAADgMGAFIFAQBNBgI/EwAAALwDAGIUAAAAnwMEAYIAAQAVAwIEAAAAQAMDAwQEAAAwQAMFAwYDBwMIAwkDCgQAAKBAAwsDDAMNAw4DDwMQAxEDEgMTAB4UARgAAAAAAAAAAAEAAAADAAAAAAEAAAAAAAAAAwAAAAABAAAAAAEAAAAAAAAA/gAGAAAAAAEAAAAAAAAAAwABAAAAAAIAAAIAAAEAAAAAAAIfAAAAAAgDAAAABwAAAQMEDgITTQQAlgAAAACHAwQBKwMDAE0DAJYAAAAAagEDAU0DAJYAAAAAbwQBAE0HAJYAAAAAhwYHAVIHAgC8BASNAgAAAJ8EBAJqBAMBggABAAMDFQMWAwkAOxMBGAAAAAABAAADAAAAAAAAAAAAAAE8AAAAAAgDAAAABwAAAQMFCQIUTQYAlgAAAACHBQYBRwUCAAAAAACpBAABqQQBAG8FAQBSBwIAvAUFjQIAAACfBQMATAEAAqQDBAAAADBAnwMAAU0DAJYAAAAAagIDAYIAAQAFAxUDFwMJAxgEAAAwQABDGQEYAAAAAAAAAAAAAAAAAAAAAAEAAAFEAAAAAAoCAAAAACKkAgEAAAAAQLwDAWgCAAAAnwMCAJ8CAAQXAhgAbwkDALwHBv4EAAAAnwcDAg4HDwBNCQCeBQAAAE0ICWQGAAAATQcI7wcAAAAwBwYkCAAAAKQHCgAAAJBAUggGAJ8HAgJSCAAAnwcCAWUABABSCQYAvAcA1AsAAACfBwMBbgLn/wIAAACCAAEADAMKBAAAAEADGgMbAxwDHQMeAw4DHwMgBAAAkEADIQBJIQEYAAAAAAAAAAEAAAAAAQAAAAAAAAACAAAAAAAAAgAAAPoACUoAAAAAEwMBAAAHAAABAw44ApMBpAMBAAAAAEBSBAEAnwMCBBcDDwBNCQAhAgAAAIcICQZHCAsAAAAAgKQIBAAAADBAbwoFAE0OAboHAAAAkAsOBm8MCABSDQYAcwkKDZ8IAgFuA/D/AQAAAE0DAdsJAAAADgMnAKQDAQAAAABATQQB2wkAAACfAwIEFwMfALsoBwNSCQcApAgLAAAAoECfCAIC8AgZAAwAAICkCAEAAAAAQFIJBwCfCAIEFwgRAE0OAD0NAAAAhw0OC0cNDQAAAACApA0EAAAAMEBvDg4ATREBugcAAACQEBEPUhEGAFISCwC8Dg6NEAAAAJ8OBQCfDQABbgju/wEAAABuA+D/AgAAAE0DAX0RAAAADgMRAPsDAAC8AwMEEgAAAJ8DAgIOAwwATQQA3hMAAABNBQF9EQAAAJ40BAMFAAAApAMVAABQwICfAwMBvAMAOhYAAACfAwIBTQQA0RcAAABNBQG6BwAAALwFBe8YAAAAnwUCAocDBAUOAxMATQQDJxkAAAAOBBAApAQBAAAAAEBNBQMnGQAAAJ8EAgQXBAcATQkA0RcAAAC8CgjvGAAAAJ8KAgLGCwAAagsJCm4E+P8CAAAAZQAJACsDCABNBQB0GgAAAJ40BQQBAAAAUgYBAKQEFQAAUMCAnwQDAU0EANEXAAAATQUBugcAAAC8BQXvGAAAAJ8FAgJqAQQFTQQBJxkAAAAOBA4ApAQBAAAAAEBNBQEnGQAAAJ8EAgQXBAYATQkA0RcAAAC8CgjvGAAAAJ8KAgJqAQkKbgT5/wIAAACCAAEAGwMKBAAAAEADIgMEBAAAMEADIwMkAxADJQMmAycEAACgQAMoAykDKgMrAwkDLAMtAy4DLwQAUMCAAzADMQMyAzMDNABaNQEYAAAAAAABAAAAAAEAAAAAAAAAAAD+AAYAAAEAAAAAAAEAAAAAAAABAAAAAAEAAAAAAQAAAAAAAAAAAAAA/gD+AAsAAAAAAAAAAQAAAAAAAAAAAQAABAAAAAAAAAABAAAAAQAAAAAAAQAAAAAAAP8AAAMBAAAAAAAAAAMAAAAAAAAAAgAAAQAAAAAAAQAAAAAA/wAEWwAAAAANBAAAAAA4pAQBAAAAAEBSBQEAnwQCArssBANSCAQApAcDAAAAIECfBwIC8AcCAAQAAACpBgABqQYBAG8IBQBNCgG6BgAAALssBANSDAQApAsDAAAAIECfCwICvAgIjQcAAACfCAQCUgcIAJ4BBgMHAAAApAUJAAAAgECfBQMBDgIGAKQFAQAAAABAUgYCAJ8FAgIwBQQWCgAAAA4DBQBSBQMAUgYEAJ8FAgIrBQEAggABAFIHBAC8BQDJCwAAAJ8FAwFNBwCeDAAAAE0GB2QNAAAATQUG0Q4AAAAwBQEkDwAAAIIAAQAQAyAEAAAAQAMCBAAAIEADKAM2AxADCQMYBAAAgEADNwM1Ax0DHgMxAx8AhwE4ARgAAAAAAgAAAAAAAAAAAQAAAAAAAAAAAAAAAAD+AAAFAQAAAAAAAwAAAAABAwAAAAIAAAAAAAAAAYgAAAAAEAMAAAAARP8DAAAAAAAA/wQAAAAAAACkBQEAAAAAQLwGAWgCAAAAnwYCAJ8FAAQXBSUAbwwDALwKCf4EAAAAnwoDAg4KGwBNCgm6BQAAAG8MBgC8CgpWBwAAAJ8KAwIrChEATQ0JugUAAABvDgYAcwwNDrwKAQMIAAAAnwoDAg4KAgCpCwEAagsEClINCQBSDgoAUg8CALwLANEJAAAAnwsFAWUACACpCgEAagoDCWUABQBSDAkAUg0CALwKAAIKAAAAnwoEAW4F2v8CAAAApAUBAAAAAEBSBgMAnwUCBBcFCgCHCgQIKwoIAKQKDAAAALBAbwwNAE0NCLoFAAAAbw4OAHMLDA6fCgIBbgX1/wEAAACCAAEADwMKBAAAAEADGgMbAxwDEAM5AwcDOgM4AzsDPAQAALBAAz0DPgCcATsBGAAAAQACAAAAAAAAAQAAAAABAAAAAAAAAQAAAAAAAAIBAAMAAAAAAAACAAADAAAAAPIAEgAAAAABAAEAAAAAAAAA/gAFnQAAAAAFAQEAAAAG+wMAAE0EAMQBAAAAhwIDBJABAgCCAQIAAgEAAz8AwQEAARgAAAAAAADCAAAAAAcCAQAAAB67KAEDUgQBAKQDAQAAAABAnwMCAvADAgACAAAAqQIAAakCAQAOAgYA+wQAAE0DBBUDAAAAUgQBAJ8DAgJSAQMATQYAngQAAABNBQY/BQAAAA4CAwDZBgAAEgEB/ysGAQBSBgEAvAMAAgYAAACfAwQBwQEAAIIAAQAHAycEAAAAQAMoA0ADHQNBAzsBCLoBQgEYAAAAAAAAAAAAAgEAAAAAAAMAAAAAAAAAAv4AAAMAuwAAAAAGAgAAAAAIkAEBAE0DANEBAAAAvAQB7wIAAACfBAIChwIDBIICAgADA0MDMQMyAMcBRAEYAAEAAAAAAADIAAAAAAIBAAAAAANNAQB0AAAAAIIBAgABAzQAzQFFARgAAADOAAAAAAoBAAAAABP/AQAAAAAAAKQCAQAAAABATQMAdAIAAACfAgIEFwIIAE0JBroDAAAAnjQBBAkAAABSCAEApAcGAAAUQICfBwMBbgL3/wIAAACCAQIABwMKBAAAAEADNAMQAygDLwQAFECAANIBRgEYAAACAAAAAAABAAAAAAAAAP8ABNMAAAAACgEAAAAAEv8BAAAAAAAApAIBAAAAAEBNAwDvAgAAAJ8CAgQXAgcAnjQBBQUAAABSCAEAUgkFAKQHBQAAEDCAnwcDAW4C+P8BAAAAggECAAYDCgQAAABAAw4DKAMvBAAQMIAA3wFHARgAAAIAAAAAAAEAAAAAAAD/AATgAAAAAAQCAAAAAARNAwDvAAAAAIcCAwGCAgIAAQMOAOsBSAEYAAAAAOwAAAAABQIAAAAABU0EAJYAAAAAhwMEAcoCAwGCAgIAAQMVAPABSQEYAAAAAADxAAAAAAUCAAAAAAlNAwDtAAAAAE0EAe0AAAAAtwMCAAQAAACpAgABqQIBAIICAgABA0oA+wEAARgAAAAAAAAAAAD7AAAAAAgEAAAABwAAAQMFCAIjTQUACAAAAACHBAUBKwQJAKQEAgAAABBAbwUDAFIHAQC8BQWNBAAAAJ8FAwKMBgIAnwQDAU0GAAgAAAAAhwUGAeIGBwAwAgamBQAAAJAHAwgwBwbtBgAAAJ40BQMGAAAApAQLAAAokICfBAMBpAQNAAAwkIBNBgAIAAAAAIcFBgHABg4AnwQDAYIAAQAPA0sDBAQAABBAA0wDCQNNA0oFAgUGAgAAAAAAAAAAAygDLwQAKJCAA04EADCQgAYQARD1AU8BGAAAAAABAAAAAAAAAAADAAAAAAAAAAAAAAAAAAEAAAAAAAAB9gAAAAAEAgAAAAAETQMAdAAAAACHAgMBggICAAEDUACDAlEBGAAAAAAEAQAAAAIAAQAAAA/7AQAATQABvAAAAAC8AAAaAQAAAJ8AAgH7AAAAxgEAADABALwAAAAA+wAAALwAAMACAAAAnwACAYIAAQADA1IDUwNUAI0CAAEYAAAAAAAAAQAAAAEAAAABDgEAAAAEAQEAAAAPTQEAvAAAAAAOAQEAggABAPsCAABNAQL9AQAAANkDAAASAAAAvAEBxwIAAACfAQMCMAEAvAAAAACCAAEAAwNSA1UDVgETiAIwARgAAAABAwAAAAAAAAAAAAUJAQAAAA4BAAAAABykAQEAAAAAQE0CAN4CAAAAnwECBFEBDwCkBgEAAAAAQFIHBQCfBgIEUQYIAE0MAJ4DAAAATQsMCgQAAABSDQoAvAsLXgUAAACfCwMBbgb3/wIAAIBuAfD/AgAAgP8BAAAAAAAAMAEA3gIAAACCAAEABgNXBAAAAEADLgMdA1gDWQCVAlQBGAAAAAAAAAEAAAAAAQAAAAAAAAD/AP8ABgAAAAEWAQAAAAIBAQAAAAX7AQAAMAABngAAAAD7AQAAggECAAEDHQCfAgABGAAAAAIAIAEAAAAOAAABAgC6AaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQKQEBwAAAGBATQMEJAgAAABNAgOeCQAAAJ8BAgLiAhUATQMBFRYAAAD/BAAACQAAAG8FFwBvBhgAbwcZAG8IGgBvCRsAbwocAG8LHQBvDB4Abw0fAMUEBQoBAAAAnwMCAjADAhgKAAAATQMBFRYAAAD/BAAACQAAAG8FIABvBiEAbwciAG8IIwBvCSQAbwolAG8LJgBvDCcAbw0oAMUEBQoBAAAAnwMCAjADAiELAAAATQMBFRYAAAD/BAAABQAAAG8FIABvBikAbwcjAG8IKgBvCR8AxQQFBgEAAACfAwICMAMCPQwAAAD/AwAAAAAAADADAu8NAAAA/wMAAAAAAAAwAwKWDgAAAP8DAAAAAAAAMAMC0Q8AAAD/AwAAAAAAADADAnQQAAAAxgMAADADAp4RAAAA4gMtAP8EAAAAAAAAMAQD1CsAAAD/BAAAAAAAADAEA+AsAAAAMAMCCBIAAAD/BAAAAAAAAOIFLwDABjAAMAYFbi4AAACePQQDBQAAAKQDMgAAABBDnwMDAjADAnQTAAAA/wMAAAAAAAAwAwLeFAAAAMADMwAwAwLdNAAAAMADNQAwAwJiNgAAAMADNwAwAwL9OAAAAMADOQAwAwLUOgAAAE0DAtQ6AAAAMAMC0jsAAADAAzwAEgAAADADAsk9AAAAwAM+ADADAtE/AAAAwANAADADAgJBAAAAwANCABIAAQAwAwJ3QwAAAMADRAAwAwJzRQAAAMADRgAwAwIZRwAAAMADSAAwAwLaSQAAAE0DAtpJAAAAMAMC6EoAAADAA0sAMAMCgkwAAADAA00AMAMCG04AAADAA08AMAMCHFAAAADAA1EAMAMC71IAAABNAwLvUgAAADADAlZTAAAAwANUADADAlVVAAAAwANWABIAAAAwAwI6VwAAAMADWAAwAwLAWQAAAMADWgASAAIAggMCAFsDWgQAAABAA1sDXAMgBAAAQEADXQQAAGBAAx8DXgMLAyIDKQMOAxUDMQM0Ax0DSwNQAy4FCwoLDA0ODxAREhMUA0ADXwNgA2EDYgMRA2MDZAMSA2UDEAMzAywDZgMmAzcDZwNoAz8DaQNqA2sDbAUCKywDAQUBLgYAA20EAAAQQwYBAxQGAgMTBgMDGQYEAyEDbgYFAzUGBgM4BgcDOwYJA0IGCgNEBgsDRQYMA0YDbwYNA0cGDgNIBg8DSQYRA08DcAYSA1EGFAMwBhUDVAYWFAABAgMEBQYHCQoLDA0ODxESFBUWAQABBwAAAAAAAAACAAAAAAAAAAADAQAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAABAAAAAQAAAAEAAAABAAAAAQAAAQEAAAABAAAA/gAEAAABAAAAAP8AAAAABgAAAAUAAB0AAAgAAAYAAA0AqwAEAAAALQAAFQAAHgAAAA0AAAYAAAUAAAoAAAADAAAMAAAFAAAFAAAKAAAABAAABQAAAA0AAAoAAAEAAABVAAAAABc3YfiHqUTrSAWlkhPS6C/3qIuZ0dqcpPYmn9Evqxr9vBTiDIJSdEhS

-- Decompiled by Krnl

local v_u_1 = game:GetService("RunService")
local v_u_2 = require(script.Parent.Util)
local v_u_19 = {
	["TypeMethods"] = v_u_2.MakeDictionary({
		"Transform",
		"Validate",
		"Autocomplete",
		"Parse",
		"DisplayName",
		"Listable",
		"ValidateOnce",
		"Prefixes",
		"Default"
	}),
	["CommandMethods"] = v_u_2.MakeDictionary({
		"Name",
		"Aliases",
		"AutoExec",
		"Description",
		"Args",
		"Run",
		"ClientRun",
		"Data",
		"Group"
	}),
	["CommandArgProps"] = v_u_2.MakeDictionary({
		"Name",
		"Type",
		"Description",
		"Optional",
		"Default"
	}),
	["Types"] = {},
	["TypeAliases"] = {},
	["Commands"] = {},
	["CommandsArray"] = {},
	["Cmdr"] = nil,
	["Hooks"] = {
		["BeforeRun"] = {},
		["AfterRun"] = {}
	},
	["Stores"] = setmetatable({}, {
		["__index"] = function(p3, p4)
			p3[p4] = {}
			return p3[p4]
		end
	}),
	["AutoExecBuffer"] = {},
	["RegisterType"] = function(p5, p6, p7)
		if not p6 or typeof(p6) ~= "string" then
			error("Invalid type name provided: nil")
		end
		if not p6:find("^[%d%l]%w*$") then
			error(("Invalid type name provided: \"%s\", type names must be alphanumeric and start with a lower-case letter or a digit."):format(p6))
		end
		for v8 in pairs(p7) do
			if p5.TypeMethods[v8] == nil then
				error("Unknown key/method in type \"" .. p6 .. "\": " .. v8)
			end
		end
		if p5.Types[p6] ~= nil then
			error(("Type \"%s\" has already been registered."):format(p6))
		end
		p7.Name = p6
		p7.DisplayName = p7.DisplayName or p6
		p5.Types[p6] = p7
		if p7.Prefixes then
			p5:RegisterTypePrefix(p6, p7.Prefixes)
		end
	end,
	["RegisterTypePrefix"] = function(p9, p10, p11)
		if not p9.TypeAliases[p10] then
			p9.TypeAliases[p10] = p10
		end
		p9.TypeAliases[p10] = ("%s %s"):format(p9.TypeAliases[p10], p11)
	end,
	["RegisterTypeAlias"] = function(p12, p13, p14)
		local v15 = p12.TypeAliases[p13] == nil
		assert(v15, ("Type alias %s already exists!"):format(p14))
		p12.TypeAliases[p13] = p14
	end,
	["RegisterTypesIn"] = function(p16, p17)
		for _, v18 in pairs(p17:GetChildren()) do
			if v18:IsA("ModuleScript") then
				v18.Parent = p16.Cmdr.ReplicatedRoot.Types
				require(v18)(p16)
			else
				p16:RegisterTypesIn(v18)
			end
		end
	end
}
v_u_19.RegisterHooksIn = v_u_19.RegisterTypesIn
function v_u_19.RegisterCommandObject(p20, p21, _)
	-- upvalues: (copy) v_u_1
	for v22 in pairs(p21) do
		if p20.CommandMethods[v22] == nil then
			error("Unknown key/method in command " .. (p21.Name or "unknown command") .. ": " .. v22)
		end
	end
	if p21.Args then
		for v23, v24 in pairs(p21.Args) do
			if type(v24) == "table" then
				for v25 in pairs(v24) do
					if p20.CommandArgProps[v25] == nil then
						error(("Unknown property in command \"%s\" argument #%d: %s"):format(p21.Name or "unknown", v23, v25))
					end
				end
			end
		end
	end
	if p21.AutoExec and v_u_1:IsClient() then
		local v26 = p20.AutoExecBuffer
		local v27 = p21.AutoExec
		table.insert(v26, v27)
		p20:FlushAutoExecBufferDeferred()
	end
	local v28 = p20.Commands[p21.Name:lower()]
	if v28 and v28.Aliases then
		for _, v29 in pairs(v28.Aliases) do
			p20.Commands[v29:lower()] = nil
		end
	elseif not v28 then
		local v30 = p20.CommandsArray
		table.insert(v30, p21)
	end
	p20.Commands[p21.Name:lower()] = p21
	if p21.Aliases then
		for _, v31 in pairs(p21.Aliases) do
			p20.Commands[v31:lower()] = p21
		end
	end
end
function v_u_19.RegisterCommand(p32, p33, p34, p35)
	local v36 = require(p33)
	local v37 = typeof(v36) == "table"
	local v38 = ("Invalid return value from command script \"%*\" (CommandDefinition expected, got %*)"):format(p33.Name, (typeof(v36)))
	assert(v37, v38)
	if p34 then
		v36.Run = require(p34)
	end
	if not p35 or p35(v36) then
		p32:RegisterCommandObject(v36)
		p33.Parent = p32.Cmdr.ReplicatedRoot.Commands
	end
end
function v_u_19.RegisterCommandsIn(p39, p40, p41)
	local v42 = {}
	local v43 = {}
	for _, v44 in pairs(p40:GetChildren()) do
		if v44:IsA("ModuleScript") then
			if v44.Name:find("Server") then
				v42[v44] = true
			else
				local v45 = p40:FindFirstChild(v44.Name .. "Server")
				if v45 then
					v43[v45] = true
				end
				p39:RegisterCommand(v44, v45, p41)
			end
		else
			p39:RegisterCommandsIn(v44, p41)
		end
	end
	for v46 in pairs(v42) do
		if not v43[v46] then
			warn("Command script " .. v46.Name .. " was skipped because it has \'Server\' in its name, and has no equivalent shared script.")
		end
	end
end
function v_u_19.RegisterDefaultCommands(p47, p_u_48)
	-- upvalues: (copy) v_u_2
	local v49 = type(p_u_48) == "table"
	if v49 then
		p_u_48 = v_u_2.MakeDictionary(p_u_48)
	end
	p47:RegisterCommandsIn(p47.Cmdr.DefaultCommandsFolder, v49 and function(p50)
		-- upvalues: (ref) p_u_48
		return p_u_48[p50.Group] or false
	end or p_u_48)
end
function v_u_19.GetCommand(p51, p52)
	return p51.Commands[(p52 or ""):lower()]
end
function v_u_19.GetCommands(p53)
	return p53.CommandsArray
end
function v_u_19.GetCommandNames(p54)
	local v55 = {}
	for _, v56 in pairs(p54.CommandsArray) do
		local v57 = v56.Name
		table.insert(v55, v57)
	end
	return v55
end
v_u_19.GetCommandsAsStrings = v_u_19.GetCommandNames
function v_u_19.GetTypeNames(p58)
	local v59 = {}
	for v60 in pairs(p58.Types) do
		table.insert(v59, v60)
	end
	return v59
end
function v_u_19.GetType(p61, p62)
	return p61.Types[p62]
end
function v_u_19.GetTypeName(p63, p64)
	return p63.TypeAliases[p64] or p64
end
function v_u_19.RegisterHook(p65, p66, p67, p68)
	if not p65.Hooks[p66] then
		error(("Invalid hook name: %q"):format(p66), 2)
	end
	local v69 = p65.Hooks[p66]
	table.insert(v69, {
		["callback"] = p67,
		["priority"] = p68 or 0
	})
	table.sort(p65.Hooks[p66], function(p70, p71)
		return p70.priority < p71.priority
	end)
end
v_u_19.AddHook = v_u_19.RegisterHook
function v_u_19.GetStore(p72, p73)
	return p72.Stores[p73]
end
function v_u_19.FlushAutoExecBufferDeferred(p_u_74)
	-- upvalues: (copy) v_u_1
	if not p_u_74.AutoExecFlushConnection then
		p_u_74.AutoExecFlushConnection = v_u_1.Heartbeat:Connect(function()
			-- upvalues: (copy) p_u_74
			p_u_74.AutoExecFlushConnection:Disconnect()
			p_u_74.AutoExecFlushConnection = nil
			p_u_74:FlushAutoExecBuffer()
		end)
	end
end
function v_u_19.FlushAutoExecBuffer(p75)
	for _, v76 in ipairs(p75.AutoExecBuffer) do
		for _, v77 in ipairs(v76) do
			p75.Cmdr.Dispatcher:EvaluateAndRun(v77)
		end
	end
	p75.AutoExecBuffer = {}
end
return function(p78)
	-- upvalues: (copy) v_u_19
	v_u_19.Cmdr = p78
	return v_u_19
end
