-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMPB1dpbmRvd3MPTWFrZVdpbmRvd0dyb3VwBXRhYmxlBmluc2VydAVHcm91cA5XaW5kb3dHcm91cEFkZARuZXh0EE1ha2VXaW5kb3dHcm91cEEGSXNPcGVuB09wZW5GdW4IQ2xvc2VGdW4KTWFrZVdpbmRvdwtXaW5kb3dDbG9zZQpXaW5kb3dPcGVuDFdpbmRvd1RvZ2dsZQAIAgAAAAAABuIAAQD/AQAAAAAAADABACwAAAAAggACAAIDAQUBAAACAgEYAAEAAAAAAwAAAAAFAgAAAAALTQMALAAAAACeNAMEAQAAAFIEAQCkAgMAAAgQgJ8CAwEwAAHEBAAAAIIAAQAFAwEDAwMEBAAIEIADBQAHBgEYAAAAAAAAAAABAAEIAAAAAAkAAAEAAByjAAAA4gABAP8BAAAAAAAAMAEALAAAAACkAQMAAAAgQP8CAAAAAAAA3QQAAMUCBAABAAAAxgMAABcBCgBNBwAsAAAAAJ40BwQFAAAAUggFAKQGBgAAFECAnwYDATAABcQHAAAAbgH1/wIAAACCAAEACAMBBQEAAwcEAAAgQAMDAwQEABRAgAMFAAsIARgI+AEAAAAJAAAAAAAAAAD7AAAAAAAAAAEABAADAwAAAAACAAAAAAAO4gAEAKkBAAAwAQAxAAAAAMYBAAAwAQDkAQAAAMYBAAAwAQBMAgAAAMYBAAAwAQDEAwAAAIIAAgAFAwkDCgMLAwUFBAABAgMAEQwBGAABAAABAAABAAABAAAAEgAAAAACAQAAAAAHqQEAADABADEAAAAATQEATAEAAACfAQEBggABAAIDCQMLABkNARgAAAABAAABGgAAAAAIAQAAAAAdTQEAxAAAAAAOARMApAICAAAAEEBNAwEsAwAAAMYEAAAXAgsA8QYKAAAAAABNBwYxBAAAAA4HBgCpBwAAMAcGMQQAAABNBwZMBQAAAJ8HAQFuAvT/AgAAAKkCAQAwAgAxBAAAAE0CAOQGAAAAnwIBAYIAAQAHAwUDBwQAABBAAwEDCQMLAwoAHQ4BGAQAAQEAAAAAAAEAAQAA+AAAAQAABQAIAAABAAABGgAAAAADAQEAAAATTQIAMQAAAABWAQIAMAEAMQAAAABNAQAxAAAAAA4BBAD7AQAAUgIAAJ8BAgGCAAEAqQEAADABADEAAAAATQEATAEAAACfAQEBggABAAIDCQMLACsPARgSAAAAAAEAAAEAAADsAAABAAAXGgAAAAAIAAABAgAZowAAAMAAAADAAQEAwAICAMADAwDABAQAwAUFAMAGBgASAAUA4gcOADAAB8MHAAAAMAEHjggAAAAwAgfuCQAAADADB7kKAAAAMAUHWAsAAAAwBAdNDAAAADAGB2gNAAAAggcCAA8GAAYBBgIGAwYEBgUGBgMCAwYDCAMMAw4DDQMPBQcHCAkKCwwNBwABAgMEBQYBAAEYAAEFBAYIBA4ACAEAAQABAAEAAQABAAEAAAEAAAAAB1tm3nneyhM8aaK07QCAGDfKtnOR/t7d0RlC0KEodLNiz5rPyuLNDlE=

-- Decompiled by Krnl

local function v_u_4(p1)
	local v2 = p1.Group
	if v2 then
		for _, v3 in next, v2.Windows do
			if v3 ~= p1 and v3.IsOpen then
				v3.IsOpen = false
				v3.CloseFun()
			end
		end
	end
	p1.IsOpen = true
	p1.OpenFun()
end
return {
	["MakeWindowGroup"] = function()
		return {
			["Windows"] = {}
		}
	end,
	["WindowGroupAdd"] = function(p5, p6)
		local v7 = p5.Windows
		table.insert(v7, p6)
		p6.Group = p5
	end,
	["MakeWindowGroupA"] = function(...)
		local v8 = {
			["Windows"] = {}
		}
		for _, v9 in next, { ... } do
			local v10 = v8.Windows
			table.insert(v10, v9)
			v9.Group = v8
		end
	end,
	["MakeWindow"] = function()
		return {
			["IsOpen"] = false,
			["OpenFun"] = nil,
			["CloseFun"] = nil,
			["Group"] = nil
		}
	end,
	["WindowOpen"] = v_u_4,
	["WindowClose"] = function(p11)
		p11.IsOpen = false
		p11.CloseFun()
	end,
	["WindowToggle"] = function(p12)
		-- upvalues: (copy) v_u_4
		p12.IsOpen = not p12.IsOpen
		if p12.IsOpen then
			v_u_4(p12)
		else
			p12.IsOpen = false
			p12.CloseFun()
		end
	end
}
