-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMNBUlzTmFOBmV4cGVjdAJ0bwVlcXVhbAJpdBdzaG91bGQgaWRlbnRpZnkgbnVtYmVycxtzaG91bGQgaWRlbnRpZnkgbm9uLW51bWJlcnMHcmVxdWlyZQZzY3JpcHQGcGFyZW50BE1hdGgIZGVzY3JpYmUFaXNOYU4ABQUAAQAAABD7AQAATQABFgAAAACMAQEAnwACAqQDAgAAABBAUgQAAJ8DAgJNAgOSAwAAAE0BAnsEAAAAqQIAAJ8BAgGCAAEABQMBAwIEAAAQQAMDAwQABgABGAAAAAAAAQAAAAAAAAAAAAEHAAAAAAUAAQAAABD7AQAATQABFgAAAABvAQEAnwACAqQDAwAAACBAUgQAAJ8DAgJNAgOSBAAAAE0BAnsFAAAAqQIBAJ8BAgGCAAEABgMBAgAAAAAAAPj/AwIEAAAgQAMDAwQACgABGAAAAAAAAQAAAAAAAAAAAAELAAAAAAMAAQAAAA2kAAEAAAAAQG8BAgDZAgAAEgIAAJ8AAwGkAAEAAAAAQG8BAwDZAgEAEgIAAJ8AAwGCAAEABAMFBAAAAEADBgMHAgABBQABGAAAAAAAAAQAAAAAAAQGAAAAAAQAAAAAABCkAAEAAAAAQKQDAwAAACBATQIDxAQAAABNAQKMBQAAAJ8AAgKkAQcAAABgQG8CCADZAwAAEgAAAJ8BAwGCAAEACQMIBAAAAEADCQQAACBAAwoDCwMMBAAAYEADDQECAgABGAAAAAAAAAAAAAIAAAAAAAoDAAAAAAEAAAECAAOjAAAAwAAAAIIAAgABBgMBAwEAARgAAQABAAAAAAQFQ7Gy+pfn7TeH2yZ3BY7+kRQ39WvIrSGklrus6xkL+vQvq9pyCM6P

-- Decompiled by Krnl

return function()
	local v_u_1 = require(script.parent.Math)
	describe("isNaN", function()
		-- upvalues: (copy) v_u_1
		it("should identify numbers", function()
			-- upvalues: (ref) v_u_1
			local v2 = v_u_1.IsNaN(1)
			expect(v2).to.equal(false)
		end)
		it("should identify non-numbers", function()
			-- upvalues: (ref) v_u_1
			local v3 = v_u_1.IsNaN((0 / 0))
			expect(v3).to.equal(true)
		end)
	end)
end
