-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgM3AXgBeQF6B2lzTmFuVjMKbG9va1ZlY3RvcgtyaWdodFZlY3Rvcgh1cFZlY3Rvcgdpc05hbkNmBVBhcnQwBVBhcnQxBkNGcmFtZQJDMAJDMQdpbnZlcnNlA25ldwRTaXplAVkBcAlNYWduaXR1ZGUNQ29tcHV0ZVJhd0FybQ1SaWdodFNob3VsZGVyDVJpZ2h0VXBwZXJBcm0KUmlnaHRFbGJvdw1SaWdodExvd2VyQXJtClJpZ2h0V3Jpc3QJUmlnaHRIYW5kDExlZnRTaG91bGRlcgxMZWZ0VXBwZXJBcm0JTGVmdEVsYm93DExlZnRMb3dlckFybQlMZWZ0V3Jpc3QITGVmdEhhbmQPQnVpbGRQYWNrZXRBcm1zCFJpZ2h0QXJtClJpZ2h0QW5nbGUWUmlnaHRTaG91bGRlclRyYW5zZm9ybRNSaWdodEVsYm93VHJhbnNmb3JtB0xlZnRBcm0JTGVmdEFuZ2xlFUxlZnRTaG91bGRlclRyYW5zZm9ybRJMZWZ0RWxib3dUcmFuc2Zvcm0LQ29tcHV0ZUFybXMMQ3VycmVudEFuZ2xlCVRyYW5zZm9ybQlBcHBseUFybXMIQXJtc0Z1bGwEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUFTG9naWMGTW9kdWxlB1NvbHZlSUsGQW5nbGVzBEFybXMACAQBAAAAABepAQEATQIAmQAAAABNAwCZAAAAAJoCEAADAAAAqQEBAE0CAJgBAAAATQMAmAEAAACaAgkAAwAAAE0CAJsCAAAATQMAmwIAAACaAgIAAwAAAKkBAAGpAQEAggECAAMDAQMCAwMACwQBGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAFAQAAAABLTQIASAAAAACpAQEATQMCmQEAAABNBAKZAQAAAJoDEAAEAAAAqQEBAE0DApgCAAAATQQCmAIAAACaAwkABAAAAE0DApsDAAAATQQCmwMAAACaAwIABAAAAKkBAAGpAQEAKwExAE0CAG0EAAAAqQEBAE0DApkBAAAATQQCmQEAAACaAxAABAAAAKkBAQBNAwKYAgAAAE0EApgCAAAAmgMJAAQAAABNAwKbAwAAAE0EApsDAAAAmgMCAAQAAACpAQABqQEBACsBGABNAgAxBQAAAKkBAQBNAwKZAQAAAE0EApkBAAAAmgMQAAQAAACpAQEATQMCmAIAAABNBAKYAgAAAJoDCQAEAAAATQMCmwMAAABNBAKbAwAAAJoDAgAEAAAAqQEAAakBAQCCAQIABgMFAwEDAgMDAwYDBwAOCAEYAwD9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMA/QAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAP0AAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAfBgIAAACdAk0GADwAAAAATQcAsQEAAABNCgaFAgAAAE0LAO0DAAAACQkKC00KAMwEAAAAvAoK+gUAAACfCgICCQgJCk0LAe0DAAAACQoIC00LAcwEAAAAvAsL+gUAAACfCwICCQkKC6QMBwAAGCCAjA0AAE0QBy8JAAAATQ8QeAoAAABbDg8IjA8AAJ8MBAIJCwgMCQoLBU0LCpELAAAATQ4IkQsAAABNDwmRCwAAAEMNDg9bDA0ITQ8C7QMAAAAJDgkPTQ8CzAQAAAC8Dw/6BQAAAJ8PAgIJDQ4PTQ4NkQsAAAAmEAsMTQ8QqgwAAAAmEQwOTRARqgwAAAD7EQAAUhIPAFITEABSFAoAUhUDAFIWBACfEQYDDhJLAE0UEkgNAAAAqRMBAE0VFJkOAAAATRYUmQ4AAACaFRAAFgAAAKkTAQBNFRSYDwAAAE0WFJgPAAAAmhUJABYAAABNFRSbEAAAAE0WFJsQAAAAmhUCABYAAACpEwABqRMBACsTMQBNFBJtEQAAAKkTAQBNFRSZDgAAAE0WFJkOAAAAmhUQABYAAACpEwEATRUUmA8AAABNFhSYDwAAAJoVCQAWAAAATRUUmxAAAABNFhSbEAAAAJoVAgAWAAAAqRMAAakTAQArExgATRQSMRIAAACpEwEATRUUmQ4AAABNFhSZDgAAAJoVEAAWAAAAqRMBAE0VFJgPAAAATRYUmA8AAACaFQkAFgAAAE0VFJsQAAAATRYUmxAAAACaFQIAFgAAAKkTAAGpEwEADhMBAIIAAQAOEUsATRQRSA0AAACpEwEATRUUmQ4AAABNFhSZDgAAAJoVEAAWAAAAqRMBAE0VFJgPAAAATRYUmA8AAACaFQkAFgAAAE0VFJsQAAAATRYUmxAAAACaFQIAFgAAAKkTAAGpEwEAKxMxAE0UEW0RAAAAqRMBAE0VFJkOAAAATRYUmQ4AAACaFRAAFgAAAKkTAQBNFRSYDwAAAE0WFJgPAAAAmhUJABYAAABNFRSbEAAAAE0WFJsQAAAAmhUCABYAAACpEwABqRMBACsTGABNFBExEgAAAKkTAQBNFRSZDgAAAE0WFJkOAAAAmhUQABYAAACpEwEATRUUmA8AAABNFhSYDwAAAJoVCQAWAAAATRUUmxAAAABNFhSbEAAAAJoVAgAWAAAAqRMAAakTAQAOEwEAggABAE0WAO0DAAAAvBYW+gUAAACfFgICTRcGhQIAAAC8Fxf6BQAAAJ8XAgIJFRYXpBgHAAAYIICMGQAAjBoAADkcDwBbGxwInxgEAgkXEhj7GAEACRYXGAkUFRZNFQDMBAAAAAkTFBVNFwaFAgAAAE0YAO0DAAAACRYXGAkVFhNNFgDMBAAAALwWFvoFAAAAnxYCAgkUFRZNGAHtAwAAALwYGPoFAAAAnxgCArwZFPoFAAAAnxkCAgkXGBmkGgcAABgggIwbAACMHAAAOR4QAFsdHgifGgQCCRkRGvsaAQAJGBkaCRYXGE0XAcwEAAAACRUWF1IWEwBSFxUAghYDABMDCQMKAwsDDAMNAw4DDwQAGCCAAgAAAAAAAOA/AxADEQMSAxMDBQMBAwIDAwMGAwcAERQBGAYAAQACAAAAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAQAAAAAAAQAAAAAAAAAAAQABAAABAAABAAAAAAAAAu8A/QAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAP0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwD9AAAAAAAAAAAAAAAAAAAAAAAAAAAAABUC7AD9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMA/QAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAP0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAMAAAAAAQAAAAAAAQAAAAAAAAAAAAABAAABAAAAAAAAAAAAAAABAAAAAAEAAAABAAAAAAAAAAAAAAEAAAEAAAwAAAAABAEAAAAAJ/8BBAAAAAAATQMA0gEAAABNAgPLAAAAADACAcsAAAAATQMA2QMAAABNAgP2AgAAADACAfYCAAAATQMAJQUAAABNAgNtBAAAADACAW0EAAAATQMAuAcAAABNAgNSBgAAADACAVIGAAAATQMA4QkAAABNAgOtCAAAADACAa0IAAAATQMAWgsAAABNAgP8CgAAADACAfwKAAAAggECAAwDFQMWAxcDGAMZAxoDGwMcAx0DHgMfAyAAMiEBGAAAAQAAAAAAAQAAAAAAAQAAAAAAAgAAAAAAAQAAAAAAAQAAAAAAATMAAAAACgEDAAAAOU0BAJEAAAAADgETAPsCAABNAwDLAQAAAE0EAPYCAAAATQUAbQMAAABSBgEATQcA+wQAAAD7CAEAnwIHAw4CAgAwAgDfBQAAAA4DCQAwAwCJBgAAAGUABgDGAgAAMAIA3wUAAADGAgAAMAIAiQYAAABNAgBbBwAAAA4CEwD7AwAATQQAUggAAABNBQCtCQAAAE0GAPwKAAAAUgcCAE0IAEALAAAA+wkCAJ8DBwMOAwIAMAMALQwAAAAOBAkAMAQATw0AAACCAAEAxgMAADADAC0MAAAAxgMAADADAE8NAAAAggABAA4DIgMVAxcDGQMjAyQDJQMmAxsDHQMfAycDKAMpAD4qARgAAAEBAQABAAEAAQEAAfoIAQACAQAAAwAAAQAAAwABAQEAAQABAAEBAAH6CAEAAgEAAAMAAAEAAAI/AAAAAAMBAAAAADNNAQDfAAAAAA4BFgBNAQDLAQAAAIwCAAAwAgG4AgAAAE0BAPYDAAAAjAIAADACAbgCAAAATQEAywEAAABNAgDfAAAAADACASEEAAAATQEA9gMAAABNAgCJBQAAADACASEEAAAATQEALQYAAAAOARYATQEAUgcAAACMAgAAMAIBuAIAAABNAQCtCAAAAIwCAAAwAgG4AgAAAE0BAFIHAAAATQIALQYAAAAwAgEhBAAAAE0BAK0IAAAATQIATwkAAAAwAgEhBAAAAIIAAQAKAyQDFQMrAxcDLAMlAygDGwMdAykAaS0BGAAAAAEAAAAAAQAAAAABAAAAAAABAAAAAAADAAABAAAAAAEAAAAAAQAAAAAAAQAAAAAAAmoAAAAAAwEBAAAANvsBAABSAgAAnwECAU0BAN8AAAAADgEWAE0BAMsBAAAAjAIAADACAbgCAAAATQEA9gMAAACMAgAAMAIBuAIAAABNAQDLAQAAAE0CAN8AAAAAMAIBIQQAAABNAQD2AwAAAE0CAIkFAAAAMAIBIQQAAABNAQAtBgAAAA4BFgBNAQBSBwAAAIwCAAAwAgG4AgAAAE0BAK0IAAAAjAIAADACAbgCAAAATQEAUgcAAABNAgAtBgAAADACASEEAAAATQEArQgAAABNAgBPCQAAADACASEEAAAAggABAAoDJAMVAysDFwMsAyUDKAMbAx0DKQB5LgEYEAAA8AAAAQAAAAABAAAAAAEAAAAAAAEAAAAAAAMAAAEAAAAAAQAAAAABAAAAAAABAAAAAAAHagAAAAAPAAABAgA9owAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAQAcAAABNAgOuBgAAAJ8BAgJNAgFgCAAAAKQDCwAAKJCAnwMBAqQECwAAKJCAbwUMAG8GDQBvBw4AnwQEAqQFCwAAKJCAbwYPAG8HDQBvCA4AnwUEAqQGEQAAQJCAbwcSAIwIAACMCQAAnwYEAsAHEwDACBQAwAkVABIAAgASAAYAwAoWAMALFwASAAkAEgAEABIABQDADBgAwA0ZABIACwD/DgMAAAAAADAKDu8aAAAAMA0OzBsAAAAwCw5sHAAAADAMDokdAAAAgg4CAB4DLwQAAABAAzADMQMyBAAAQEADMwM0AzUDCwMPBAAokIACmpmZmZmZub8CmpmZmZmZyb8CmpmZmZmZqb8CmpmZmZmZuT8DNgQAQJCAAhgtRFT7Ifk/BgAGAQYCBgMGBAYFBgYDIQM3AyoDLQcAAQIDBAUGAQABGAABAAAAAAABAAAAAAAAAgACAAABAAAAAAABAAAAAAABAAAAAAABAwMAACEMAAAAKxAABQABAAEAAQABAAIBAAAAAAd7vv6WMpo060l6lAKJjCol1d/HtjeSF9iLAs6WUxDiJ5zNsss5i4U4

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Module.Logic).SolveIK
CFrame.new()
local v_u_3 = CFrame.new(-0.1, -0.2, -0.05)
local v_u_4 = CFrame.new(0.1, -0.2, -0.05)
local v_u_5 = CFrame.Angles(1.5707963267948966, 0, 0)
local function v_u_34(p6, p7, p8, p9, p10, p11)
	-- upvalues: (copy) v_u_2, (copy) v_u_5
	local v12 = p6.Part0
	local v13 = p6.Part1
	local v14 = v12.CFrame * p6.C0 * p6.C1:inverse()
	local v15 = v14 * p7.C0 * p7.C1:inverse()
	local v16 = v14 * CFrame.new(0, v13.Size.Y * 0.5, 0) * p11
	local v17 = v16.p
	local v18 = (v14.p + v15.p) * 0.5
	local v19 = (v15 * p8.C0 * p8.C1:inverse()).p
	local v20 = (v17 - v18).Magnitude
	local v21 = (v18 - v19).Magnitude
	local v22, v23 = v_u_2(v20, v21, v16, p9, p10)
	if v23 then
		local v24 = v23.lookVector
		local v25 = (v24.x ~= v24.x or v24.y ~= v24.y) and true or v24.z ~= v24.z
		if not v25 then
			local v26 = v23.rightVector
			v25 = (v26.x ~= v26.x or v26.y ~= v26.y) and true or v26.z ~= v26.z
			if not v25 then
				local v27 = v23.upVector
				v25 = (v27.x ~= v27.x or v27.y ~= v27.y) and true or v27.z ~= v27.z
			end
		end
		if not v25 then
			if v22 then
				local v28 = v22.lookVector
				local v29 = (v28.x ~= v28.x or v28.y ~= v28.y) and true or v28.z ~= v28.z
				if not v29 then
					local v30 = v22.rightVector
					v29 = (v30.x ~= v30.x or v30.y ~= v30.y) and true or v30.z ~= v30.z
					if not v29 then
						local v31 = v22.upVector
						v29 = (v31.x ~= v31.x or v31.y ~= v31.y) and true or v31.z ~= v31.z
					end
				end
				if not v29 then
					local v32 = p6.C0:inverse() * v12.CFrame:inverse() * (v23 * CFrame.new(0, 0, -v20 * 0.5) * v_u_5) * p6.C1
					local v33 = v12.CFrame * p6.C0 * v32 * p6.C1:inverse()
					return v32, p7.C0:inverse() * v33:inverse() * (v22 * CFrame.new(0, 0, -v21 * 0.5) * v_u_5) * p7.C1
				end
			end
			return
		end
	end
end
local function v_u_42(p35)
	-- upvalues: (copy) v_u_34, (copy) v_u_3, (copy) v_u_4
	local v36 = p35.RightArm
	if v36 then
		local v37, v38 = v_u_34(p35.RightShoulder, p35.RightElbow, p35.RightWrist, v36, p35.RightAngle, v_u_3)
		if v37 then
			p35.RightShoulderTransform = v37
		end
		if v38 then
			p35.RightElbowTransform = v38
		end
	else
		p35.RightShoulderTransform = nil
		p35.RightElbowTransform = nil
	end
	local v39 = p35.LeftArm
	if v39 then
		local v40, v41 = v_u_34(p35.LeftShoulder, p35.LeftElbow, p35.LeftWrist, v39, p35.LeftAngle, v_u_4)
		if v40 then
			p35.LeftShoulderTransform = v40
		end
		if v41 then
			p35.LeftElbowTransform = v41
			return
		end
	else
		p35.LeftShoulderTransform = nil
		p35.LeftElbowTransform = nil
	end
end
return {
	["BuildPacketArms"] = function(p43)
		return {
			["RightShoulder"] = p43.RightUpperArm.RightShoulder,
			["RightElbow"] = p43.RightLowerArm.RightElbow,
			["RightWrist"] = p43.RightHand.RightWrist,
			["LeftShoulder"] = p43.LeftUpperArm.LeftShoulder,
			["LeftElbow"] = p43.LeftLowerArm.LeftElbow,
			["LeftWrist"] = p43.LeftHand.LeftWrist
		}
	end,
	["Arms"] = function(p44)
		-- upvalues: (copy) v_u_42
		v_u_42(p44)
		if p44.RightShoulderTransform then
			p44.RightShoulder.CurrentAngle = 0
			p44.RightElbow.CurrentAngle = 0
			p44.RightShoulder.Transform = p44.RightShoulderTransform
			p44.RightElbow.Transform = p44.RightElbowTransform
		end
		if p44.LeftShoulderTransform then
			p44.LeftShoulder.CurrentAngle = 0
			p44.LeftElbow.CurrentAngle = 0
			p44.LeftShoulder.Transform = p44.LeftShoulderTransform
			p44.LeftElbow.Transform = p44.LeftElbowTransform
		end
	end,
	["ComputeArms"] = v_u_42,
	["ApplyArms"] = function(p45)
		if p45.RightShoulderTransform then
			p45.RightShoulder.CurrentAngle = 0
			p45.RightElbow.CurrentAngle = 0
			p45.RightShoulder.Transform = p45.RightShoulderTransform
			p45.RightElbow.Transform = p45.RightElbowTransform
		end
		if p45.LeftShoulderTransform then
			p45.LeftShoulder.CurrentAngle = 0
			p45.LeftElbow.CurrentAngle = 0
			p45.LeftShoulder.Transform = p45.LeftShoulderTransform
			p45.LeftElbow.Transform = p45.LeftElbowTransform
		end
	end
}
