-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMjDHNldG1ldGF0YWJsZQNuZXcISW5zdGFuY2UKSW1hZ2VMYWJlbAdCYWNraW5nBE5hbWUFVURpbTIEU2l6ZRZyYnhhc3NldGlkOi8vNzM1NjM3MTQ0BUltYWdlBFJlY3QLU2xpY2VDZW50ZXIQQmFja2dyb3VuZENvbG9yMwtJbWFnZUNvbG9yMwRFbnVtCVNjYWxlVHlwZQVTbGljZRZCYWNrZ3JvdW5kVHJhbnNwYXJlbmN5BlpJbmRleAZQYXJlbnQNQ3JlYXRlQmFja2luZwdWZWN0b3IyDUltYWdlUmVjdFNpemUQQ3JlYXRlVG9wQmFja2luZwZTaGFkb3cLQW5jaG9yUG9pbnQIUG9zaXRpb24WcmJ4YXNzZXRpZDovLzczNTY0NDE1NQZDb2xvcjMRSW1hZ2VUcmFuc3BhcmVuY3kMQ3JlYXRlU2hhZG93BkNyZWF0ZQdfX2luZGV4FVJvdW5kZWRCYWNraW5nQnVpbGRlcglDbGFzc05hbWUABgMAAQAAAAn/AQAAAAAAAPsCAACePQEDAgAAAKQAAQAAAABAnwADAoIAAgACAwEEAAAAQAAJAgEYAAAAAAAAAAACCgAAAAAIAgAAAAAypAICAAAEAIBvAwMAnwICAm8DBAAwAwK6BQAAAKQDBwAABGCAjAQBAIwFAACMBgEAjAcAAJ8DBQIwAwIvCAAAAG8DCQAwAwKpCgAAAKQDDAAABLCAjAQEAIwFBACMBhAAjAcQAJ8DBQIwAwLPDQAAAE0DAZ8OAAAAMAMCAA8AAACkAxMAEkQAwTADAtERAAAAjAMBADADAjoUAAAATQQBDRYAAAB4AwQVMAMCDRYAAAAwAQIkFwAAAIwDAQAwAwE6FAAAAIICAgAYAwMDAgQABACAAwQDBQMGAwcEAARggAMIAwkDCgMLBAAEsIADDAMNAw4DDwMQAxEEEkQAwQMSAgAAAAAAAPA/AxMDFAAPFQEYAAAAAAEAAAEAAAAAAAAAAAEAAAIAAAAAAAAAAAEAAAABAAAAAQAAAQAAAAABAAIAAAIQAAAAAAgCAAAAABVSBAEAvAIAewAAAACfAgMCpAMDAAAIEICMBBQAjAUQAJ8DAwIwAwLrBAAAAKQDBgAACFCAjAQEAIwFBACMBhAAjAcQAJ8DBQIwAwLPBwAAAIICAgAIAxUDFgMCBAAIEIADFwMLBAAIUIADDAAhGAEYAAAAAAEAAAAAAAABAAAAAAAAAAACJAAAAAAIAgAAAABIpAICAAAEAIBvAwMAnwICAm8DBAAwAwK6BQAAAKQDBwAABGCAjAQBAIwFBgCMBgEAjAcGAJ8DBQIwAwIvCAAAAKQDCgAABJCAbwQLAG8FCwCfAwMCMAMC6AwAAACkAwcAAARggG8ECwCMBQAAbwYLAIwHAQCfAwUCMAMCOw0AAABvAw4AMAMCqQ8AAACkAxEAAAQAgYwEEACMBRAAjAZAAIwHQACfAwUCMAMCzxIAAACkAxQAAAQwgYwEAACMBQAAjAYAAJ8DBAIwAwIAFQAAAKQDGQAYXGDBMAMC0RcAAACMAwEAMAMCOhoAAABvAxsAMAMCoxwAAABNBAENHgAAAHgDBB0wAwINHgAAAE0DASQfAAAAMAMCJB8AAACCAgIAIAMDAwIEAAQAgAMEAxkDBgMHBAAEYIADCAMWBAAEkIACAAAAAAAA4D8DGgMbAxwDCgMLBAAEAIEDDAMdBAAEMIEDDgMPAxADEQQYXGDBAxICZmZmZmZm5j8DHgIAAAAAAADwPwMTAxQAKx8BGAAAAAABAAABAAAAAAAAAAABAAAAAAAAAQAAAAAAAAAAAQAAAgAAAAAAAAAAAQAAAAAAAAABAAAAAQAAAQAAAQAAAAABAAAAAiwAAAAABgIAAAAACVIEAQC8AgB7AAAAAJ8CAwJSBQIAvAMAwQEAAACfAwMCggICAAIDFQMfAD4gARgAAAAAAQAAAAJBAAAAAAIAAAECABmjAAAA/wAEAAAAAAAwAABuAAAAAG8BAQAwAQDbAgAAAMABAwASAAAAMAEA7wQAAADAAQUAMAEAewYAAADAAQcAMAEAIQgAAADAAQkAMAEAwQoAAADAAQsAMAEAlgwAAACCAAIADQMhAyIDIwYAAwIGAQMVBgIDGAYDAx8GBAMgBQABAgMEAQABGAAEAAEAAQAAAgAAAAYAABIAAAoAABMAAAkBAAAAAAVkXEYNRb2vmVaYLJnPkv35RZKPDLvAGELtQx2DMyk5jI/3XAjnmLq8

-- Decompiled by Krnl

local v_u_1 = {}
v_u_1.__index = v_u_1
v_u_1.ClassName = "RoundedBackingBuilder"
function v_u_1.new()
	-- upvalues: (copy) v_u_1
	local v2 = v_u_1
	return setmetatable({}, v2)
end
function v_u_1.CreateBacking(_, p3)
	local v4 = Instance.new("ImageLabel")
	v4.Name = "Backing"
	v4.Size = UDim2.new(1, 0, 1, 0)
	v4.Image = "rbxassetid://735637144"
	v4.SliceCenter = Rect.new(4, 4, 16, 16)
	v4.ImageColor3 = p3.BackgroundColor3
	v4.ScaleType = Enum.ScaleType.Slice
	v4.BackgroundTransparency = 1
	v4.ZIndex = p3.ZIndex - 1
	v4.Parent = p3
	p3.BackgroundTransparency = 1
	return v4
end
function v_u_1.CreateTopBacking(p5, p6)
	local v7 = p5:CreateBacking(p6)
	v7.ImageRectSize = Vector2.new(20, 16)
	v7.SliceCenter = Rect.new(4, 4, 16, 16)
	return v7
end
function v_u_1.CreateShadow(_, p8)
	local v9 = Instance.new("ImageLabel")
	v9.Name = "Shadow"
	v9.Size = UDim2.new(1, 6, 1, 6)
	v9.AnchorPoint = Vector2.new(0.5, 0.5)
	v9.Position = UDim2.new(0.5, 0, 0.5, 1)
	v9.Image = "rbxassetid://735644155"
	v9.SliceCenter = Rect.new(16, 16, 64, 64)
	v9.ImageColor3 = Color3.new(0, 0, 0)
	v9.ScaleType = Enum.ScaleType.Slice
	v9.BackgroundTransparency = 1
	v9.ImageTransparency = 0.7
	v9.ZIndex = p8.ZIndex - 1
	v9.Parent = p8.Parent
	return v9
end
function v_u_1.Create(p10, p11)
	local v12 = p10:CreateBacking(p11)
	p10:CreateShadow(v12)
	return v12
end
return v_u_1
