-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNGBmFzc2VydAlDaGFyYWN0ZXIISHVtYW5vaWQORmluZEZpcnN0Q2hpbGQLR2V0SHVtYW5vaWQIUm9vdFBhcnQLR2V0Um9vdFBhcnQIU3BlY3RhdGUGQ2VudGVyCVRleHRMYWJlbARUZXh0DVNldENlbnRlclRleHQOU3BlY3RhdGluZ05hbWUITmFtZUxpc3QQR2V0SW5kZXhGcm9tTmFtZQpDeWNsZVJpZ2h0CUN5Y2xlTGVmdAdWaWV3aW5nBXByaW50HENhbm5vdCBzcGVjdGF0ZSwgbm8gTmFtZUxpc3QLQnV0dG9uUmlnaHQHVmlzaWJsZQpCdXR0b25MZWZ0ClRvZ2dsZVZpZXcKQ2FtZXJhVHlwZQRFbnVtClNjcmlwdGFibGUIUG9zaXRpb24LVGFyZ2V0Rm9jdXMGQ0ZyYW1lCkxvb2tWZWN0b3IOVGFyZ2V0UG9zaXRpb24TU3RlcENpbmVtYXRpY0NhbWVyYRNDaG9vc2luZyBuZXcgcGxheWVyBG1hdGgGcmFuZG9tGUNvdWxkIG5vdCBmaW5kIG5ldyBwbGF5ZXIGQ3VzdG9tDUNhbWVyYVN1YmplY3QJSGVhcnRiZWF0BklzT3BlbgNuZXcETWFpZAlQbGF5ZXJHdWkGUGFyZW50EE1vdXNlQnV0dG9uMURvd24HQ29ubmVjdAhHaXZlVGFzawVTdGFydAZzY3JpcHQHRGVzdHJveQRTdG9wLlBsYXllciBubyBsb25nZXIgZXhpc3RzLCB3aWxsIGxvb2sgZm9yIG5ldyBvbmUGVXBkYXRlCXdvcmtzcGFjZQ1DdXJyZW50Q2FtZXJhBGdhbWUKUnVuU2VydmljZQpHZXRTZXJ2aWNlB1BsYXllcnMLTG9jYWxQbGF5ZXIRUmVwbGljYXRlZFN0b3JhZ2UHcmVxdWlyZQ9DaW5lbWF0aWNDYW1lcmEGTW9kdWxlA1N0ZAZTaWduYWwLU3BlY3RhdGVHdWkIUmVzb3VyY2UTTWFrZUNpbmVtYXRpY0NhbWVyYQAMBQEAAAAAELsBAANSAgAApAEBAAAAAECfAQIBTQEAaQIAAAAOAQYAbwQDALwCAQMEAAAAnwIDAg4CAQCCAgIAxgIAAIICAgAFAwEEAAAAQAMCAwMDBAAcBQEYAAAAAAABAAEBAAAAAQEDAB0AAAAABgEAAAAAG7sBAANSAgAApAEBAAAAAECfAQIBuwEAA1IDAACkAgEAAAAAQJ8CAgFNAgBpAgAAAA4CBwBvBQMAvAMCAwQAAACfAwMCDgMCAFIBAwBlAAEAxgEAAA4BBABNAgFGBQAAAA4CAQCCAgIAggABAAYDAQQAAABAAwIDAwMEAwYAJwcBGAsAAAAA9QAAAAABAAEBAAAAAQEAAwUBAAEBAx0AAAAABQEBAAAACvsEAABNAwQnAAAAAE0CA+oBAAAATQECmgIAAAAwAAH1AwAAAIIAAQAEAwgDCQMKAwsAMQwBGAAAAAAAAAAAAAEyAAAAAAYAAQAAACH7AQAATQAB6AAAAABHAAMAAAAAgMYAAACCAAIA+wEAAE0AAaIBAAAARwADAAAAAIDGAAAAggACAIwCAQD7BAAATQMEogEAAAAcAAMAjAEBAKgACwD7BQAATQQFogEAAACHAwQC+wUAAE0EBegAAAAAmgMCAAQAAACCAgIAiwD1/4IAAQACAw0DDgBBDwEYAAAAAAABAAIAAAAAAQACAAAAAAAAAQAAAAAAAAAAAf4FQgAAAAAHAAIAAABK+wIAAE0BAugAAAAARwEDAAAAAIDGAAAAZQAbAPsCAABNAQKiAQAAAEcBAwAAAACAxgAAAGUAFACMAwEA+wUAAE0EBaIBAAAAHAEEAIwCAQCoAQwA+wYAAE0FBqIBAAAAhwQFA/sGAABNBQboAAAAAJoEAwAFAAAAUgADAGUAAgCLAfT/xgAAALsBAANSAgAApAEDAAAAIECfAQIB+wMAAE0CA6IBAAAAHAECAJoACQABAAAA+wEAAPsEAABNAwSiAQAAABMCAwAwAgHoAAAAAGUACAD7AQAA+wQAAE0DBKIBAAAAlQQABIcCAwQwAgHoAAAAAPsCAABNAQLoAAAAAPsFAQBNBAUnBQAAAE0DBOoGAAAATQIDmgcAAAAwAQL1CAAAAIIAAQAJAw0DDgMBBAAAIEACAAAAAAAA8D8DCAMJAwoDCwBOEAEYEAAAAAABAAIAAAAAAQACAAAAAAAAAQAAAAAAAAAAAQD+AAgAAAAAAQAAAAAAAQAAAAAAAAACAAAAAAAAAAMAANsAAAAAAAAAACYyAAAAAAcAAgAAAEr7AgAATQEC6AAAAABHAQMAAAAAgMYAAABlABsA+wIAAE0BAqIBAAAARwEDAAAAAIDGAAAAZQAUAIwDAQD7BQAATQQFogEAAAAcAQQAjAIBAKgBDAD7BgAATQUGogEAAACHBAUD+wYAAE0FBugAAAAAmgQDAAUAAABSAAMAZQACAIsB9P/GAAAAuwEAA1ICAACkAQMAAAAgQJ8BAgENAA0ABAAAgPsBAAD7BAAATQMEogEAAAD7BgAATQUGogEAAAAcBAUAhwIDBDACAegAAAAAZQAIAPsBAAD7BAAATQMEogEAAAB4BAAEhwIDBDACAegAAAAA+wIAAE0BAugAAAAA+wUBAE0EBScFAAAATQME6gYAAABNAgOaBwAAADABAvUIAAAAggABAAkDDQMOAwEEAAAgQAIAAAAAAADwPwMIAwkDCgMLAFkRARgQAAAAAAEAAgAAAAABAAIAAAAAAAABAAAAAAAAAAABAP4AEwAAAAABAAEAAAAAAAAAAAAAAAIAAAAAAAAAAwAA0AAAAAAAAAAAMTIAAAAABwACAAAAhwH7AQAATQABgAAAAAAOAAUA+wAAAKkBAAAwAQCAAAAAAGUAEwD7AQAATQABogEAAAAOAA8A+wIAAE0BAqIBAAAAHAABAIwBAABgAQkAAAAAAKQAAwAAACBAbwEEAJ8AAgH7AAAAqQEBADABAIAAAAAA+wEAAE0AAYAAAAAADgARAPsCAQBNAQInBQAAAE0AAfUGAAAAqQEBADABAIAHAAAA+wIBAE0BAicFAAAATQABzggAAACpAQEAMAEAgAcAAABlABoA+wIBAE0BAicFAAAATQAB9QYAAACpAQAAMAEAgAcAAAD7AgEATQECJwUAAABNAAHOCAAAAKkBAAAwAQCABwAAAPsDAQBNAgMnBQAAAE0BAuoJAAAATQABmgoAAABvAQUAMAEA9QsAAAD7AQAATQABgAAAAAAOADcA+wIAAE0BAugMAAAARwEDAAAAAIDGAAAAZQAbAPsCAABNAQKiAQAAAEcBAwAAAACAxgAAAGUAFACMAwEA+wUAAE0EBaIBAAAAHAEEAIwCAQCoAQwA+wYAAE0FBqIBAAAAhwQFA/sGAABNBQboDAAAAJoEAwAFAAAAUgADAGUAAgCLAfT/xgAAAEcACAAAAACA+wEAAPsEAABNAwSiAQAAABMCAwAwAgHoDAAAAPsCAABNAQLoDAAAAPsFAQBNBAUnBQAAAE0DBOoJAAAATQIDmgoAAAAwAQL1CwAAAIIAAQANAxIDDgMTBAAAIEADFAMIAxUDFgMXAwkDCgMLAw0AZBgBGDQAAAABAAAAAAIAAAAAAAAAAAAAAQAAAAEAAAAEAAAAAQAAAAAAAAABAAAAAAAAAAACAAAAAAAAAAEAAAAAAAAAvgAAAAAAAAAAAEcAAADJAAAAAAEAAgAAAAABAAIAAAAAAAABAAAAAAAAAAABAP4AMwABAAAAAAAAAwAAswAAAAAAAAAATzIAAAAACwEIAAAHAAABCAdJAa4B+wIAAE0BAoAAAAAADgGJAPsCAQBNAQIqAQAAAKQCBAADBCDA8QEGAAIAAAD7AQEApAIEAAMEIMAwAgEqAQAAAKkBAAD7AwAATQID6AUAAAAOAkAA+wICAPsFAABNBAXoBQAAALwCAgMGAAAAnwIDAg4COAC7AQIDUgUCAKQECAAAAHBAnwQCAbsBAgNSBgIApAUIAAAAcECfBQIBTQUCaQkAAAAOBQcAbwgKALwGBQMGAAAAnwYDAg4GAgBSBAYAZQABAMYEAAAOBAUATQUERgsAAAAOBQIAUgMFAGUAAQDGAwAADgMbAPsEAwBNBQM7DAAAADAFBOcNAAAA+wQDAE0HAzsMAAAATQoDhQ8AAABNCQpoEAAAAFsICQ5DBgcIbwcRAEMFBgcwBQSpEgAAAPsFBABNBAU3EwAAAFIFAAD7BgMAjAcDAIwIAgCfBAUBqQEBACoBVwAAAACA+wMAAE0CA6IUAAAADgInAPsEAABNAwSiFAAAABwCAwCMAwAAYAMhAAIAAACkAhYAAABQQW8DFwCfAgIB+wIAAPsFAABNBAWiFAAAAKQFGgAAZICBjAYBAPsJAABNCAmiFAAAABwHCACfBQMChwMEBTADAugFAAAA+wMAAE0CA+gFAAAA+wYFAE0FBicbAAAATQQF6hwAAABNAwSaHQAAADACA/UeAAAAggABAKQCFgAAAFBBbwMfAJ8CAgH7AgAAxgMAADADAugFAAAA+wIGAJ8CAQGCAAEA+wIBAE0BAioBAAAApAIhACAEIMDxARoAAgAAAPsBAQCkAiEAIAQgwDACASoBAAAA+wEBAPsDBwC7AQMDUgUDAKQECAAAAHBAnwQCAU0EA2kJAAAADgQHAG8HCgC8BQQDBgAAAJ8FAwIOBQIAUgIFAGUAAQDGAgAAMAIBnCIAAACCAAEAIwMSAxkDGgMbBAMEIMADDQMEAwEEAABwQAMCAwMDBgMcAx0CAAAAAAAAJMADHgMfBwAAAAAAAKBAAAAAAAAAAAADIAMhAw4DEwQAAFBBAyIDIwMkBABkgIEDCAMJAwoDCwMlAyYEIAQgwAMnAIIBKAEYZgAAAAEAAAAAAAABAAAAAAIBAAAAAQAAAAAAAAGeAAAAAPUAAAAAAQABAQAAAAEBAAMFAQABAQAAXwEAAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAQUAAQAAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAQAAmQAAAAAAAAAAAGkAAAABAAAAAQAABAAAAAAAAAEAAAAAAQB6AAAAAAEAAQEAAAABAQADfgADHQAAAAAGAAkAAABv+wMAAE0CAzEAAAAAKgICAAAAAACpAQABqQEBALsBAQKkAAIAAAAQQJ8AAgH7AAAAqQEBADABADEAAAAA+wAAAPsCAQBNAQLvAwAAAJ8BAQIwAQB2BAAAAPsAAgD7AgMATQECmQUAAAAwAQAkBgAAAPsDAgBNAgMnBwAAAE0BAuoIAAAATQABmgkAAABvAQcAMAEA9QoAAAD7AAAAxgEAADABAOgLAAAA+wAAAKkBAAAwAQCADAAAAPsBAABNAAF2BAAAAPsFAgBNBAUnBwAAAE0DBOoIAAAATQIDYQ0AAAD7BAQAvAICxw4AAACfAgMAvAAA/Q8AAACfAAAB+wEAAE0AAXYEAAAA+wUCAE0EBScHAAAATQME9RAAAABNAgNhDQAAAPsEBQC8AgLHDgAAAJ8CAwC8AAD9DwAAAJ8AAAH7AQAATQABdgQAAAD7BQIATQQFJwcAAABNAwTOEQAAAE0CA2ENAAAA+wQGALwCAscOAAAAnwIDALwAAP0PAAAAnwAAAfsBAABNAAF2BAAAAPsDBwBNAgP9EgAAAPsECAC8AgLHDgAAAJ8CAwC8AAD9DwAAAJ8AAAGCAAEAEwMpAwEEAAAQQAMqAysDLAMtAwgDCQMKAwsDDQMSAy4DLwMwAxUDFwMoAKcBMQEYdgAAAAAAAAAAAAABAAAAAQAAAAAAAAIAAAAAAIYAAAAAAAAAAAB9AAAAAQAAAAIAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAABMgAAAAAHAAQAAAA4+wMAAE0CAzEAAAAAKgICAAEAAACpAQABqQEBALsBAQKkAAIAAAAQQJ8AAgH7AAEApAEEAAAAMEAwAQAkBQAAAPsBAABNAAF2BgAAALwAAFAHAAAAnwACAfsAAADGAQAAMAEAdgYAAAD7AAIApAELAAokgMAwAQAqCQAAAPsAAgD7AgMAuwECA1IEAgCkAwIAAAAQQJ8DAgFNAwJpDAAAAA4DBwBvBg0AvAQDAw4AAACfBAMCDgQCAFIBBABlAAEAxgEAADABAJwPAAAA+wAAAKkBAAAwAQAxAAAAAIIAAQAQAykDAQQAABBAAzIEAAAwQAMtAysDMwMaAxkDJgQKJIDAAwIDAwMEAycAtwE0ARibAAAAAAAAAAAAAAEAAAAAAQAAAAAAAQAAAAEAAAAAAQBgAAAAAAEAAQEAAAABAQADmAABAAAAAR0AAAAACAEBAAAAOPsBAAAwAAGiAAAAAPsCAABNAQKAAQAAAA4BMAD7AgAATQEC6AIAAAAOASwA+wMAAE0CA+gCAAAARwIDAAAAAIDGAQAAZQAbAPsDAABNAgOiAAAAAEcCAwAAAACAxgEAAGUAFACMBAEA+wYAAE0FBqIAAAAAHAIFAIwDAQCoAgwA+wcAAE0GB6IAAAAAhwUGBPsHAABNBgfoAgAAAJoFAwAGAAAAUgEEAGUAAgCLAvT/xgEAAEcBCQAAAACApAIEAAAAMEBvAwUAnwICAfsCAADGAwAAMAMC6AIAAACCAAEABgMOAxIDDQMTBAAAMEADNQDAATYBGIAAAAMAAAAAAAAAfQAAAAABAAIAAAAAAQACAAAAAAAAAQAAAAAAAAAAAQD+AIAAAQAAAAEAAAADQgAAAAAUAAABAgB6owAAAKQBAQAAAABATQABSAIAAACkAQQAAAAwQG8DBQC8AQEWBgAAAJ8BAwKkAgQAAAAwQG8EBwC8AgIWBgAAAJ8CAwJNAwIxCAAAAKQEBAAAADBAbwYJALwEBBYGAAAAnwQDAqQFCwAAAKBATQcEQA0AAABNBgcNDAAAAJ8FAgKkBgsAAACgQE0IBKEOAAAATQcIHw8AAACfBgICpAcLAAAAoEBNCQShDgAAAE0ICXYQAAAAnwcCAk0JBGISAAAATQgJohEAAADACRMAwAoUAMALFQASAAgATQwFQxYAAACfDAEC/w0FAAAAAACpDgAAMA4NMRcAAADGDgAAMA4NohgAAADGDgAAMA4N6BkAAACpDgAAMA4NgBoAAADGDgAAMA4NdhAAAAD/DgAAAAAAADAODR8PAAAAwA4bABIADQDADxwAEgANABIACADAEB0AEgANABIACADAER4AEgANABIACADAEh8AEgANABIAAAASAAIAEgAMABIABQASAAgAEgARABIAAwDAEyAAEgANABIABwASAAgAEgADABIAEQASAA8AEgAQABIAAQASABIAMBMNHCEAAADAEyIAEgANABIACAASAAAAEgADADATDfojAAAAwBMkABIADQAwEw0mJQAAAIINAgAmAzcEAAAAQAM4AzkEAAAwQAM6AzsDPAM9Az4DPwQAAKBAA0ADQQNCA0MDKwNEA0UGAAYBBgIDRgMpAw4DDQMSBgMGBAYFBgYGBwYIAzEGCQM0BgoDNgsAAQIDBAUGBwgJCgEAARgAAQAAAAEAAAAAAAEAAAAAAAEAAQAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAABILCgAEAAACAAEAAAEAAAEAAAEAAAEAAAEAAAAEAA0AAAsAAAsAAB4AAAAAAAAAACUAAAAAAAAAAAAAABAAAAAAAAAJAAAADgEAAAAAC9cbOVDqQ2A25d9TxAolaG0BcGnf5GvXsUrkZ4OJvLGrJ+nzr3riyrk=

-- Decompiled by Krnl

local v_u_1 = workspace.CurrentCamera
local v_u_2 = game:GetService("RunService")
local v_u_3 = game:GetService("Players")
local v_u_4 = v_u_3.LocalPlayer
local v5 = game:GetService("ReplicatedStorage")
local v_u_6 = require(v5.Module.CinematicCamera)
require(v5.Std.Signal)
local v_u_7 = require(v5.Std.Maid)
local v_u_8 = v5.Resource.SpectateGui
local v_u_9 = v_u_6.MakeCinematicCamera()
local v_u_10 = {
	["IsOpen"] = false,
	["NameList"] = nil,
	["SpectatingName"] = nil,
	["Viewing"] = false,
	["Maid"] = nil,
	["Signal"] = {}
}
local function v_u_14()
	-- upvalues: (copy) v_u_10, (copy) v_u_8
	local v12
	if v_u_10.SpectatingName == nil or v_u_10.NameList == nil then
		v12 = nil
	else
		for v12 = 1, #v_u_10.NameList do
			if v_u_10.NameList[v12] == v_u_10.SpectatingName then
				goto l3
			end
		end
		v12 = nil
	end
	::l3::
	assert(v12)
	if v12 == #v_u_10.NameList then
		v_u_10.SpectatingName = v_u_10.NameList[1]
	else
		v_u_10.SpectatingName = v_u_10.NameList[v12 + 1]
	end
	local v13 = v_u_10.SpectatingName
	v_u_8.Spectate.Center.TextLabel.Text = v13
end
local function v_u_18()
	-- upvalues: (copy) v_u_10, (copy) v_u_8
	local v16
	if v_u_10.SpectatingName == nil or v_u_10.NameList == nil then
		v16 = nil
	else
		for v16 = 1, #v_u_10.NameList do
			if v_u_10.NameList[v16] == v_u_10.SpectatingName then
				goto l3
			end
		end
		v16 = nil
	end
	::l3::
	assert(v16)
	if v16 == 1 then
		v_u_10.SpectatingName = v_u_10.NameList[#v_u_10.NameList]
	else
		v_u_10.SpectatingName = v_u_10.NameList[v16 - 1]
	end
	local v17 = v_u_10.SpectatingName
	v_u_8.Spectate.Center.TextLabel.Text = v17
end
local function v_u_22()
	-- upvalues: (copy) v_u_10, (copy) v_u_8
	if v_u_10.Viewing then
		v_u_10.Viewing = false
	elseif v_u_10.NameList and #v_u_10.NameList > 0 then
		print("Cannot spectate, no NameList")
		v_u_10.Viewing = true
	end
	if v_u_10.Viewing then
		v_u_8.Spectate.ButtonRight.Visible = true
		v_u_8.Spectate.ButtonLeft.Visible = true
	else
		v_u_8.Spectate.ButtonRight.Visible = false
		v_u_8.Spectate.ButtonLeft.Visible = false
		v_u_8.Spectate.Center.TextLabel.Text = "Spectate"
	end
	if not v_u_10.Viewing then
		::l10::
		return
	end
	local v20
	if v_u_10.SpectatingName == nil or v_u_10.NameList == nil then
		v20 = nil
	else
		for v20 = 1, #v_u_10.NameList do
			if v_u_10.NameList[v20] == v_u_10.SpectatingName then
				goto l13
			end
		end
		v20 = nil
	end
	::l13::
	if v20 == nil then
		v_u_10.SpectatingName = v_u_10.NameList[1]
	end
	local v21 = v_u_10.SpectatingName
	v_u_8.Spectate.Center.TextLabel.Text = v21
	goto l10
end
local function v_u_33(p23)
	-- upvalues: (copy) v_u_10, (copy) v_u_1, (copy) v_u_3, (copy) v_u_9, (copy) v_u_6, (copy) v_u_8, (copy) v_u_22, (copy) v_u_4
	if v_u_10.Viewing then
		if v_u_1.CameraType ~= Enum.CameraType.Scriptable then
			v_u_1.CameraType = Enum.CameraType.Scriptable
		end
		local v24 = false
		if v_u_10.SpectatingName then
			local v25 = v_u_3:FindFirstChild(v_u_10.SpectatingName)
			if v25 then
				assert(v25)
				assert(v25)
				local v26 = v25.Character
				local v27 = v26 and v26:FindFirstChild("Humanoid") or nil
				local v28 = v27 and v27.RootPart or nil
				if v28 then
					v_u_9.TargetFocus = v28.Position
					v_u_9.TargetPosition = v28.Position + v28.CFrame.LookVector * -10 + Vector3.new(0, 5, 0)
					v_u_6.StepCinematicCamera(p23, v_u_9, 3, 2)
					v24 = true
				end
			end
		end
		if v24 == false then
			if v_u_10.NameList and #v_u_10.NameList > 0 then
				print("Choosing new player")
				v_u_10.SpectatingName = v_u_10.NameList[math.random(1, #v_u_10.NameList)]
				local v29 = v_u_10.SpectatingName
				v_u_8.Spectate.Center.TextLabel.Text = v29
			else
				print("Could not find new player")
				v_u_10.SpectatingName = nil
				v_u_22()
			end
		end
	elseif v_u_1.CameraType ~= Enum.CameraType.Custom then
		v_u_1.CameraType = Enum.CameraType.Custom
		local v30 = v_u_1
		local v31 = v_u_4
		assert(v31)
		local v32 = v31.Character
		v30.CameraSubject = v32 and v32:FindFirstChild("Humanoid") or nil
	end
end
function v_u_10.Start()
	-- upvalues: (copy) v_u_10, (copy) v_u_7, (copy) v_u_8, (copy) v_u_4, (copy) v_u_22, (copy) v_u_14, (copy) v_u_18, (copy) v_u_2, (copy) v_u_33
	local v34 = v_u_10.IsOpen == false
	assert(v34)
	v_u_10.IsOpen = true
	v_u_10.Maid = v_u_7.new()
	v_u_8.Parent = v_u_4.PlayerGui
	v_u_8.Spectate.Center.TextLabel.Text = "Spectate"
	v_u_10.SpectatingName = nil
	v_u_10.Viewing = false
	v_u_10.Maid:GiveTask(v_u_8.Spectate.Center.MouseButton1Down:Connect(v_u_22))
	v_u_10.Maid:GiveTask(v_u_8.Spectate.ButtonRight.MouseButton1Down:Connect(v_u_14))
	v_u_10.Maid:GiveTask(v_u_8.Spectate.ButtonLeft.MouseButton1Down:Connect(v_u_18))
	v_u_10.Maid:GiveTask(v_u_2.Heartbeat:Connect(v_u_33))
end
function v_u_10.Stop()
	-- upvalues: (copy) v_u_10, (copy) v_u_8, (copy) v_u_1, (copy) v_u_4
	local v35 = v_u_10.IsOpen == true
	assert(v35)
	v_u_8.Parent = script
	v_u_10.Maid:Destroy()
	v_u_10.Maid = nil
	v_u_1.CameraType = Enum.CameraType.Custom
	local v36 = v_u_1
	local v37 = v_u_4
	assert(v37)
	local v38 = v37.Character
	v36.CameraSubject = v38 and v38:FindFirstChild("Humanoid") or nil
	v_u_10.IsOpen = false
end
function v_u_10.Update(p39)
	-- upvalues: (copy) v_u_10
	v_u_10.NameList = p39
	if not (v_u_10.Viewing and v_u_10.SpectatingName) then
		::l2::
		return
	end
	local v41
	if v_u_10.SpectatingName == nil or v_u_10.NameList == nil then
		v41 = nil
	else
		for v41 = 1, #v_u_10.NameList do
			if v_u_10.NameList[v41] == v_u_10.SpectatingName then
				goto l6
			end
		end
		v41 = nil
	end
	::l6::
	if v41 == nil then
		print("Player no longer exists, will look for new one")
		v_u_10.SpectatingName = nil
	end
	goto l2
end
return v_u_10
