-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgOJAQdSdW5uaW5nCU1ha2VHcm91cAhEdXJhdGlvbgVTdGFydANFbmQGQ2FuY2VsBlVwZGF0ZQhNYWtlU3BlYwZhc3NlcnQEUHVzaAJvcwVjbG9jawdTdGFydGVkB0VsYXBzZWQGUmVtb3ZlLU5vIGtleSBmb3VuZCwgc2Vjb25kIHBhcmFtIHRvIEFkZCBtdXN0IGJlIG5pbANUYWcHRW5hYmxlZAhQcmlvcml0eQV0YWJsZQZpbnNlcnQDQWRkBnJlbW92ZQxHZXRDaXJjbGVQY3QFRnJhbWUKT3V0ZXJGcmFtZQRMZWZ0BUltYWdlBVJpZ2h0CU91dGVyRnVsbApVSUdyYWRpZW50BG1hdGgFY2xhbXAIUm90YXRpb24HVmlzaWJsZQxTZXRDaXJjbGVQY3QLSW1hZ2VDb2xvcjMOU2V0Q2lyY2xlQ29sb3IFVURpbTIDbmV3BFNpemUIUG9zaXRpb24PU2V0Q2lyY2xlUmFkaXVzBkNvbG9yMwdmcm9tUkdCDGFmU3Bpbl9TdGFydAphZlNwaW5fRW5kDWFmU3Bpbl9VcGRhdGUMRWFzZV9vdXRCYWNrDWFmUHVsc2VfU3RhcnQLYWZQdWxzZV9FbmQDUmVkDmFmUHVsc2VfVXBkYXRlCk5vdEFsbG93ZWQEU3BlYwhDYWxsYmFjawVUaW1lZAdQcmVzc2VkCVByZXNzZWRBdA9HZXRBY2N1bXVsYXRpb24JQW5pbWF0aW9uBVByZXNzDlNjcmVlblBvc2l0aW9uD1JlbGVhc2VDYWxsYmFjawdSZWxlYXNlBEtpbGwJQ2hhcmFjdGVyC1ByaW1hcnlQYXJ0BFBhcnQKQXR0YWNobWVudA1Xb3JsZFBvc2l0aW9uCU1hZ25pdHVkZQREaXN0Dklnbm9yZU92ZXJyaWRlDFByZVVwZGF0ZUZ1bg9QcmVVcGRhdGVQZXJpb2QNTGFzdFByZVVwZGF0ZQVOb1JheQ1SYXljYXN0UGFyYW1zGkZpbHRlckRlc2NlbmRhbnRzSW5zdGFuY2VzCmNvbGxpZGFibGUEVW5pdAhJbnN0YW5jZQlWYWxpZFJvb3QOSXNEZXNjZW5kYW50T2YHSGlkZUZ1bgdTaG93RnVuEldvcmxkVG9TY3JlZW5Qb2ludAFYAVkHVmVjdG9yMwxBYnNvbHV0ZVNpemUESGVscAAETmFtZQRUZXh0CFVwZGF0ZVVJEldoaWxlUHJlc3NlZFVwZGF0ZQtQcm9jZXNzU3BlYxBHZXRMYXN0SW5wdXRUeXBlDFRvdWNoRW5hYmxlZARFbnVtDVVzZXJJbnB1dFR5cGUIR2FtZXBhZDEHS2V5Q29kZQdCdXR0b25ZE0dldFN0cmluZ0ZvcktleUNvZGUOQnV0dG9uVHJpYW5nbGUD4pazAUUJVGV4dExhYmVsClBvaW50TGFiZWwESG9sZA5VcGRhdGVQbGF0Zm9ybRNvblZpc2liaWxpdHlDaGFuZ2VkBEZpcmUMVG91Y2hTdGFydGVkClRvdWNoRW5kZWQMTW91c2VCdXR0b24xCklucHV0QmVnYW4KSW5wdXRFbmRlZARnYW1lB1BsYXllcnMKR2V0U2VydmljZRBVc2VySW5wdXRTZXJ2aWNlC0xvY2FsUGxheWVyCXdvcmtzcGFjZQ1DdXJyZW50Q2FtZXJhEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUDU3RkBlNpZ25hbAdSYXljYXN0BVNwZWNzA3Npbgdjb25uZWN0DENpcmNsZUFjdGlvbgAfAgAAAAAABeIAAQDGAQAAMAEA6QAAAACCAAIAAgMBBQEAAA0CARgAAQAAAA4AAAAAAgAAAAAAEeIABQDGAQAAMAEA5QAAAADGAQAAMAEAHAEAAADGAQAAMAEACwIAAADGAQAAMAEAoQMAAADGAQAAMAEAJgQAAACCAAIABgMDAwQDBQMGAwcFBQABAgMEABIIARgAAQAAAQAAAQAAAQAAAQAAABMAAAAABAEAAAAACk0BAOkAAAAADgEGALwCAaEBAAAAnwICAcYCAAAwAgDpAAAAAIIAAQACAwEDBgAbBgEYAAABAQAAAQAAAhwAAAAABAIBAAAAJ/sDAABNAgOhAAAAAFIDAACfAgIBTQMB5QEAAAC7AQMCpAIDAAAAIECfAgIBTQMBHAQAAAC7AQMCpAIDAAAAIECfAgIBTQMBCwUAAAC7AQMCpAIDAAAAIECfAgIBTQMBJgYAAAC7AQMCpAIDAAAAIECfAgIBTQIBoQAAAAArAgQATQIBCwUAAAAwAgGhAAAAADABAOkHAAAAggABAAgDBgMDAwkEAAAgQAMEAwUDBwMBACIKARgAAAAAAAEAAAAAAAEAAAAAAAEAAAAAAAEAAAAAAAEAAAEAAAACAAEjAAAAAAoCAAAAAC5NAgDpAAAAACsCAQCCAAEApAMDAAAIEICfAwECTQQCswQAAAArBAUAMAMCswQAAAC8BAIcBQAAAJ8EAgFNBQKzBAAAACYEAwVNBQKkBgAAAA4FAwBNBQKkBgAAAEMEBAVNBgLlBwAAAOwFBAaMBgEAfQYCAAUAAACMBQEAUggFAFIJAQC8BgImCAAAAJ8GBAGMBgEAfQYHAAUAAAC8BgILCQAAAJ8GAgHGBgAAMAYA6QAAAACCAAEACgMBAwsDDAQACBCAAw0DBAMOAwMDBwMFAC0HARgAAAEBAwAAAgAAAQABAAACAAABAAABAAACAAACAAABAgAAAAABAAABAAABAAACLgAAAAACAAIAAAAG+wEAAE0AAWkAAAAA+wEBAJ8AAgCCAAAAAQMPAFsAARgAAAAAAABcAAAAAAUCAgAAACCBAQEFAAAAAFIDAQBvBAAApAICAAAAEECfAgMBMAEAXwMAAABNAgDwBAAAACsCAwCpAgEAMAIA8AQAAABNAgDNBQAAACsCAwCMAgEAMAIAzQUAAAD7AwAAnjQDBAAAAABSBAAApAIIAAAcYICfAgMB2QIAABICAQASAAEAggICAAkDEAMJBAAAEEADEQMSAxMDFAMVBAAcYIABBVEWARgAAAAAAAAAAQABAAABAAACAAABAAACAAAAAAAAAQAAAFIAAAAACAEBAAAAFfsEAAAcAwQAjAEBAIwC//+oAQ4A+wUAAIcEBQNNBQRfAAAAAJoFCAAAAAAApAUDAAAIEID7BgAAUgcDAJ8FAwGpBQEAggUCAIsB8v+pAQAAggECAAQDEQMUAxcEAAgQgABfDwEYAAAAAAABAAEAAAABAAAAAAEA/AkAYAAAAAABAAEAAAAC+wAAAIIAAgAAAGwYARgAAG0AAAAADAECAAAAQN4AAAD7AgEATQECnQAAAABNBQH0AQAAAE0EBcYCAAAATQIEqQMAAABNBQH0AQAAAE0EBQUEAAAATQMEqQMAAABNBQH0AQAAAE0EBUEFAAAATQUC+gYAAABNBgP6BgAAAFsIAAeMCQAAjApoAUwuAAKkBwoAACSAgJ8HBAKMCrQAjAtoATQuBwQKCwAAUgkHAKQICgAAJICAnwgEAjAIBTgLAAAAjAoAAIwLtAA0LgcECgsAAFIJBwCkCAoAACSAgJ8IBAIwCAY4CwAAAG8JDAC3AAIACQAAAKkIAAGpCAEAMAgCgA0AAAAwCAOADQAAAFYJCAAwCQSADQAAAIIAAQAOAxkDGgMbAxwDHQMeAx8CAAAAAACAdkADIAMhBAAkgIADIgIrhxbZzvfvPwMjAG8kARgAAQAAAQAAAAAAAAAAAAAAAQAAAAEAAAABAAAAAAAAAQAAAAAAAAAAAAEAAAAAAAAAAAACAAAAAAEAAQABAAABcAAAAAAGAQEAAAAa+wIAAE0BAp0AAAAATQUB9AEAAABNBAXGAgAAAE0CBKkDAAAATQUB9AEAAABNBAUFBAAAAE0DBKkDAAAATQUB9AEAAABNBAVBBQAAADAAAgAGAAAAMAADAAYAAAAwAAQABgAAAIIAAQAHAxkDGgMbAxwDHQMeAyUAfiYBGAAAAAEAAAAAAAAAAAAAAAEAAAABAAEAAQABfwAAAAAJAQEAAAAc+wIAAE0BAp0AAAAATQIB9AEAAACkAwQAAAwggIwEAQCMBgIACQUGAIwGAQCMCAIACQcIAJ8DBQIwAwIvBQAAAE0CAfQBAAAApAMEAAAMIICMBAAAOQUAAIwGAAA5BwAAnwMFAjADAjsGAAAAggABAAcDGQMaAycDKAQADCCAAykDKgCGASsBGAAAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAGHAAAAAAcAAgAAADz7AAAAjAEAAJ8AAgH7AQEATQABnQAAAABNAQD0AQAAAKQCBAAADCCAjAMBAIwECACMBQEAjAYIAJ8CBQIwAgEvBQAAAE0BAPQBAAAApAIEAAAMIICMAwAAjAT8/4wFAACMBvz/nwIFAjACATsGAAAApAAJAAAgcICMAdYAjALWAIwD1gCfAAQC+wIBAE0BAp0AAAAATQUB9AEAAABNBAXGCgAAAE0CBKkLAAAATQUB9AEAAABNBAUFDAAAAE0DBKkLAAAATQUB9AEAAABNBAVBDQAAADAAAgAOAAAAMAADAA4AAAAwAAQADgAAAIIAAQAPAxkDGgMnAygEAAwggAMpAyoDLAMtBAAgcIADGwMcAx0DHgMlAI4BLgEYEAAA+AAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAgAAAAAAO4AAAEAAAAAAAAAAAAAAAEAAAABAAEAAQAOfwAAAAAHAAIAAAA8+wAAAIwBAQCfAAIB+wEBAE0AAZ0AAAAATQEA9AEAAACkAgQAAAwggIwDAQCMBBAAjAUBAIwGEACfAgUCMAIBLwUAAABNAQD0AQAAAKQCBAAADCCAjAMAAIwE+P+MBQAAjAb4/58CBQIwAgE7BgAAAKQACQAAIHCAjAHWAIwC1gCMA9YAnwAEAvsCAQBNAQKdAAAAAE0FAfQBAAAATQQFxgoAAABNAgSpCwAAAE0FAfQBAAAATQQFBQwAAABNAwSpCwAAAE0FAfQBAAAATQQFQQ0AAAAwAAIADgAAADAAAwAOAAAAMAAEAA4AAACCAAEADwMZAxoDJwMoBAAMIIADKQMqAywDLQQAIHCAAxsDHAMdAx4DJQCTAS8BGBUAAPMAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAANAAAAAADpAAABAAAAAAAAAAAAAAABAAAAAQABAAEAE38AAAAADwMDAAAASLsYAQJSBQEA+wQAAJ8EAgI+AwQA+wQBAFIFAwCfBAIB9QQBA1sGBAP1BQIGpAYGAAAUQIBSBwUAUggFAFIJBQCfBgQC+wgCAE0HCJ0HAAAATQsH9AgAAABNCgvGCQAAAE0ICqkKAAAATQsH9AgAAABNCgsFCwAAAE0JCqkKAAAATQsH9AgAAABNCgtBDAAAADAGCAANAAAAMAYJAA0AAAAwBgoADQAAAFsHAw6VBgcO+wgCAE0HCJ0HAAAATQgH9AgAAACkCREAAEDwgIwKAQCMDAIACQsMBowMAQCMDgIACQ0OBp8JBQIwCQgvEgAAAE0IB/QIAAAApAkRAABA8ICMCgAAOQsGAIwMAAA5DQYAnwkFAjAJCDsTAAAAggABABQC7gwJj1Tt6j8CAAAAAAAA8D8CAAAAAADAakACAAAAAAAAUEADLAMtBAAUQIADGQMaAxsDHAMdAx4DJQIAAAAAAAAQQAMnAygEAEDwgAMpAyoAmAEwARgaAAAAAAIAAAIBAAEAAAAAAOAAAAEAAAAAAAAAAAAAAAEAAAABAAEAAQAcAOcAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAABh/AAAAAA0FAAAAAA0rBAEAbwQAAOwFAAN4AAUBCQkAAJUMBAEJCwwAQwoLBAkICQqVBwgBCQYCB0MFBgGCBQIAAgJhcTjzqzn7PwIAAAAAAADwPwCmATEBGAABAgABAAAAAAAAAACnAAAAAAcAAQAAADmkAAIAAAQAgIwB1gCMAtYAjAPWAJ8ABAL7AgAATQECnQMAAABNBQH0BAAAAE0EBcYFAAAATQIEqQYAAABNBQH0BAAAAE0EBQUHAAAATQMEqQYAAABNBQH0BAAAAE0EBUEIAAAAMAACAAkAAAAwAAMACQAAADAABAAJAAAA+wEAAE0AAZ0DAAAATQEA9AQAAACkAgwAACyggIwDAQCMBAAAjAUBAIwGAACfAgUCMAIBLw0AAABNAQD0BAAAAKQCDAAALKCAjAMAAG8EDgCMBQAAbwYOAJ8CBQIwAgE7DwAAAIIAAQAQAywDLQQABACAAxkDGgMbAxwDHQMeAyUDJwMoBAAsoIADKQIAAAAAAAAAgAMqAK0BMgEYMAAAAAAA0AAAAQAAAAAAAAAAAAAAAQAAAAEAAQABAAMAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAofwAAAAAHAAMAAAA++wAAAIwBAQCfAAIBjAABAN4AAQCkAAIAAAQAgIwB1gCMAtYAjAPWAJ8ABAL7AgIATQECnQMAAABNBQH0BAAAAE0EBcYFAAAATQIEqQYAAABNBQH0BAAAAE0EBQUHAAAATQMEqQYAAABNBQH0BAAAAE0EBUEIAAAAMAACAAkAAAAwAAMACQAAADAABAAJAAAA+wECAE0AAZ0DAAAATQEA9AQAAACkAgwAACyggIwDAQCMBBAAjAUBAIwGEACfAgUCMAIBLw0AAABNAQD0BAAAAKQCDAAALKCAjAMAAIwE+P+MBQAAjAb4/58CBQIwAgE7DgAAAIIAAQAPAywDLQQABACAAxkDGgMbAxwDHQMeAyUDJwMoBAAsoIADKQMqALIBMwEYNAAAAQACAAAAAADJAAABAAAAAAAAAAAAAAABAAAAAQABAAEAAwAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAC9/AAAAABADAwAAAGj7AwAA+wYBAPUHAAEJBQYHQwQFAZ8DAgGMBAgAUgYBAIwHBgArBwEAbwcBAD4IBgB4BggAjAkBAAkMBgaVDwcACQ4PBkMNDgcJCwwNlQoLAAkICQqVBQgCCQMEBfsFAgBNBAWdAwAAAE0FBPQEAAAApAYHAAAYUICMBwEAjAkCAAkICQOMCQEAjAsCAAkKCwOfBgUCMAYFLwgAAABNBQT0BAAAAKQGBwAAGFCAjAcAADkIAwCMCQAAOQoDAJ8GBQIwBgU7CQAAAE0EAG8KAAAADgQyAIwGKAAJBQYB9QQLBfUFAAGkBg4AADTAgIwK1gAJCQoFjAvWAAkKCwFDCAkKQwcIBIwLRQAJCgsFjAzWAAkLDAFDCQoLQwgJBIwMRQAJCwwFjA3WAAkMDQFDCgsMQwkKBJ8GBAL7CAIATQcInQMAAABNCwf0BAAAAE0KC8YPAAAATQgKqRAAAABNCwf0BAAAAE0KCwURAAAATQkKqRAAAABNCwf0BAAAAE0KC0ESAAAAMAYIABMAAAAwBgkAEwAAADAGCgATAAAAggABABQCAAAAAAAA8D8CYXE486s5+z8CAAAAAAAAAAADGQMaAycDKAQAGFCAAykDKgM0AgAAAAAAAERAAywDLQQANMCAAxsDHAMdAx4DJQC5ATUBGDsAAAAAAAEAAOwBAgABAAAAAAAAAAAA3AAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAANAAAAQAAAwEAAAAAAAAAAAAAAAAAAAAAAAAAAL0AAAEAAAAAAAAAAAAAAAEAAAABAAEAAQBAfwAAAAAEAAUAAAAa+wEAAE0AATkAAAAAnwABAm8BAQAwAQDlAgAAAPsBAQAwAQAcAwAAAPsBAgAwAQALBAAAAPsBAwAwAQAmBQAAAKkBAQAwAQBvBgAAAPsCAABNAQIZBwAAAPsCBABSAwAAnwEDAYIAAQAIAwgCMzMzMzMz0z8DAwMEAwUDBwM0AwoAxgE2ARgAAAAAAQAAAQAAAQAAAQAAAQAAAQAAAAAAAccAAAAABgAJAAAAbPsBAABNAAE1AAAAACsAAQCCAAEAqQMAALwBAEYBAAAAnwEDAU0BAHECAAAADgEqAKkBAQAwAQCPAwAAAKQBBgAAFECAnwEBAjABALUHAAAA+wIBAE0BAjkIAAAAnwEBAk0CAOUJAAAAMAIB5QkAAAD7AgIAMAIBHAoAAAD7AgMAMAIBCwsAAAD7AgQAMAIBJgwAAABNAgCkDQAAAA4CBQBNAgCkDQAAAJ8CAQIwAgGkDgAAAPsDAQBNAgMZDwAAAPsDBQBSBAEAnwIDATABADMQAAAAggABAKkDAQC8AQBGAQAAAJ8BAwIOARcA+wMBAE0CAzkIAAAAnwIBAm8DEQAwAwLlCQAAAPsDBgAwAwIcCgAAAPsDBwAwAwILCwAAAPsDCAAwAwImDAAAAPsEAQBNAwQZDwAAAPsEBQBSBQIAnwMDAYIAAQD7AwEATQIDOQgAAACfAgECbwMRADADAuUJAAAA+wMGADADAhwKAAAA+wMHADADAgsLAAAA+wMIADADAiYMAAAAqQMBADADAm8SAAAA+wQBAE0DBBkPAAAA+wQFAFIFAgCfAwMBggABABMDNwM4AzkDOgMLAwwEABRAgAM7AwgDAwMEAwUDBwM8Aw4DCgM9AjMzMzMzM9M/AzQA0AE+ARgKAAABAQIAAAABAAABAAABAAAAAAEAAAABAAAAAQAAAQAAAQAAAQAAAQAAAAACAAAAAAACAAACAAAAAgEAAAABAAABAAABAAABAAABAAAAAAAA2gAAAAEAAAEAAAEAAAEAAAEAAAEAAAAAACXHAAAAAAUACAAAAEj7AQAATQABNQAAAAAOAEMAqQEAADABAI8BAAAAxgEAADABALUCAAAA+wIBAE0BAukDAAAARwEoAAAAAAD7AgEATQEC6QMAAABNAgAzBAAAAJoBIQACAAAA+wEDAN4BAgD7AgQATQECoQUAAAD7AgEAnwECAfsCBABNAQI5BgAAAJ8BAQJvAgcAMAIB5QgAAAD7AgUAMAIBHAkAAAD7AgYAMAIBCwoAAAD7AgcAMAIBJgsAAACpAgEAMAIBbwwAAAD7AwQATQIDGQ0AAAD7AwEAUgQBAJ8CAwHGAQAAMAEAMwQAAADGAQAAMAEAIA4AAAD7AQAAxgIAADACATUAAAAATQEApg8AAAAOAQQAqQMAALwBAKYPAAAAnwEDAYIAAQAQAzcDOgM7AwEDPQMGAwgCMzMzMzMz0z8DAwMEAwUDBwM0AwoDPwNAAPMBQQEYhwAAAQEAAAEAAAEAAAAAAAAAAAAAAHWMAQAAAADNAAAAAQAAAQAAAQAAAQAAAQAAAQAAAAAAMAAAAQAAAQAAAAEAAAEAAAADbQAAAAAcAAYAAACrAowA5wOMAQEAxgIAAPsGAAAcBQYAjAMBAIwE//+oAwsA+wcAAIcGBwVNBwZiAAAAAA4HBQCkBwMAAAgQgPsIAABSCQUAnwcDAYsD9f/7BAEATQMEaQQAAAArAwEAggABAE0EA5sFAAAAKwQBAIIAAQBNBQQ7BgAAAKQGCQAAIHCAnwYBAv8HAAABAAAAUggDAMUHCAIBAAAA+wsAABwKCwCMCAEAjAn//6gIfwD7DAAAhwsMCk0MC0QKAAAATQ0LDQsAAABNDgvgDAAAACsOCwBHDQQAAAAAAE0ODeAMAAAAKw4GAEcMBAAAAAAATQ4MOwYAAAArDgEA+w4CACYPDgVNEA+qDQAAAE0RC+MOAAAATRILRA8AAABNEwujEAAAAA4TFAAODAIAfRASABEAAABNEwtEEQAAACsTAQBvExIATRQLexMAAAAOFAUATRULexMAAAAmFAYVfRMGABQAAAAwBgt7EwAAALwUC6MQAAAAnxQCAU0TC/AUAAAADhNJAIwTAABgE0cAEAAAAH0QRQARAAAAqRMAAE0UC7YVAAAADhQCAKkTAQBlADQApBQYAABcYIGfFAECyhUSBzAVFH0ZAAAA+xYDAE0VFpoaAAAAUhYFAE0XDwcbAAAAUhgQAFIZFACfFQUCxhYAAMYXAAAOFQUATRYV9BwAAABNFxU7BgAAAGUABABNGQ8HGwAAAAkYGRBDFwUYJhkXDk0YGaoNAAAAjBkBAH0YAwAZAAAAqRMBAGUAEQAOFhAATRkLRAoAAACaFgMAGQAAAKkTAQBlAAoATRkLSR0AAAAOGQcATRsLSR0AAAC8GRatHgAAAJ8ZAwIOGQEAqRMBAA4TCQBNFAvNHwAAANQQAwAAAAAAYAEEABQAAABSAgsAUgAQAFIBFACLCIH/+wkEAE0ICZ0gAAAA+woEAE0JCjUhAAAADgkGAPECBQAJAAAATQoJjyIAAAAOCgEAggABAA4JCABNCgkqIwAAAA4KBQDxAgQACQAAALwKCSojAAAAnwoCAfsKBAAwAgo1IQAAACsCAQCCAAEATQoCviQAAAAOCgUA8QIEAAkAAAC8CgK+JAAAAJ8KAgHGCQAATQoCJiUAAAAOCgMAvAoCJiUAAACfCgIBTQoCDQsAAABNCwJECgAAAE0MAuAMAAAAKwwLAEcKBAAAAAAATQwK4AwAAAArDAYARwsEAAAAAABNDAs7BgAAACsMAQD7DAIA+w0FAFIPDAC8DQ2xJgAAAJ8NAwMwDgiAJwAAACsOBgBNDwKPIgAAAA4PAgCpDwEAgg8CAIIAAQBNEA15KAAAAE0RDXgpAAAAjBIAAEw2AAKkDysAAFyggp8PBAIwDwIgLAAAAKQQLgAAXNCCjBEAAE0SDXkoAAAAjBMAAE0UDXgpAAAAnxAFAqQRLgAAXNCCjBIAAE0VCHEwAAAATRQVeSgAAABbExQvjBQAAE0XCHEwAAAATRYXeCkAAABbFRYvnxEFAiYPEBEwDwg7BgAAAE0PCAoxAAAATRECujMAAACQEBEyMBAP9TQAAABNDwgKMQAAAE0SArozAAAAVhESAFYQEQAwEA+AJwAAAKkPAQCCDwIANQNCAxQDFwQACBCAA0MDRAMqAwsDDAQAIHCAA0UDRgNHA0gDSQNKA0sDTAKamZmZmZnJPwNNAxIDTgNPAygEAFxggQNQA1EDUgNTA1QDVQMTAxkDNwM6A1YDVwMHA1gDIwNZA1oDWwQAXKCCAz8DJwQAXNCCAgAAAAAAAOA/A1wDXQNeA18DYACQAmEBGAAAAAIAAAAAAQADAAABAAAAAPsJAAABAQIAAQECAAIAAAEAAAAAAQAAAAABAAEAAQABAAAAAAEAAAAAAQAAAQEBAAEAAQABAAABAAABAAEBAgAAAAAAAAABAAEAAAQAAAEAAAAAAQEAAAEAAgAAAQAAAgAAAAAAAAAAAQABAQABAAACAAAAAgAAAQAAAQABAQAAAAEAAQAAAAAAAAAAAQUBAAEAAAABAQHGQQAAAgAAAgAAAAAAAQIAAAAAAAEAAAIAAAEBAgAAAAABAAACAQAAAQAAAgABAAEAAAAAAQAAAAABAAABAQAAAAABAAEDAAABAAICAAAAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAD/AAIAAAAAAAABAAAAAAAAAAEAEQEAAAAJAAYAAABp+wEAAE0AATUAAAAAKwABAIIAAQBNAQCPAQAAACsBAQCCAAEApAEEAAAMIICfAQECTQMAtQUAAAAmAgEDTQMApAYAAAAOAwQATQMApAYAAACfAwECQwICA00EAOUHAAAA7AMCBIwEAQB9BAIAAwAAAIwDAQBNBACoCAAAAA4EBABNBACoCAAAAFIFAwCfBAIBDQNDAAkAAICpBAAAMAQAjwEAAADGBAAAMAQAtQUAAACpBgEAvAQARgoAAACfBAMCTQUApgsAAAAOBQQAqQcBALwFAKYLAAAAnwUDAQ4EFwD7BgEATQUGOQwAAACfBQECbwYNADAGBeUHAAAA+wYCADAGBRwOAAAA+wYDADAGBQsPAAAA+wYEADAGBSYQAAAA+wcBAE0GBxkRAAAA+wcFAFIIBQCfBgMBggABAPsGAQBNBQY5DAAAAJ8FAQJvBhIAMAYF5QcAAAD7BgIAMAYFHA4AAAD7BgMAMAYFCw8AAAD7BgQAMAYFJhAAAACpBgEAMAYFbxMAAAD7BwEATQYHGREAAAD7BwUAUggFAJ8GAwGCAAEAFAM3AzoDCwMMBAAMIIADOwM8AwMDYgIAAAAAAADwPwM4A0ADCAIAAAAAAADgPwMEAwUDBwMKAjMzMzMzM9M/AzQAlQNjARjPAAABAQIAAAEDAAABAAABAAABAAAAAgAAAQAAAQIAAAEAAAACAAEAAAEAAAEAAAABAAABAAAAAgEAAAABAAABAAABAAABAAABAAAAAAAAEAAAAAEAAAEAAAEAAAEAAAEAAAEAAAAAAO/HAAAAAAYAAgAAAEP7AQAATQABnQAAAAD7AQEAvAEBbwEAAACfAQICxgIAAPsEAQBNAwR/AgAAAA4DAgDGAgAAZQAUAKQDBgAFEDDAmgEQAAMAAAD7AwEApAUJAAgcMMC8AwMTCgAAAJ8DAwJSAgMA8AIDAAsAAIBvAgwAZQAFAPACBAAIAACAbwINAGUAAQBvAg4ATQMAmg8AAABHAgIAAAAAgKkEAAGpBAEAMAQDgBAAAABNAwC7EQAAAEcCAgAAAAAAqQQAAakEAQAwBAOAEAAAAA4CBABNAwCaDwAAADACA/USAAAA+wQAAE0DBDUTAAAATQQAyhQAAABSBQMADgUCAE0FA3EVAAAAMAUEgBAAAACCAAEAFgMZA2QDZQNmA2cDaAQFEDDAA2kDagQIHDDAA2sDbANtA1oDbgNvAyMDcANgAzcDcQM5AL0DcgEYAAAAAQAAAAEBAAAAAQABAAAAAQAAAAAAAAEAAQABAAEAAwIAAAAAAAAAAQAAAAAAAAABAQAAAAIAAAEAAAAAAAAAAb4BAAAABwEIAAAAPfsBAACfAQECKwEYAPsDAQBNAgOdAAAAAKkDAAAwAwKAAQAAAPsEAQBNAwQ1AgAAAA4DDgD7BQEATQQFNQIAAABNAwQqAwAAAA4DBgD7BAEATQMENQIAAAC8AwMqAwAAAJ8DAgH7AwIAnwMBAfsCAwCfAgEB+wMEAE0CAyYEAAAA+wMFAFIEAACfAgMB+wIGAJ8CAQH7AwEATQIDNQIAAAD7AwcA8QIOAAMAAAD7AwEATQIDOAUAAAD7BgEATQUGNQIAAABHBQIAAAAAgKkEAAGpBAEAvAIC3QYAAACfAgMB+wMBAE0CAzUCAAAA3gIHAIIAAQAHAxkDIwM3A1YDBwNzA3QA1gMHARgAAAEBAAABAAABAAAAAQAAAAAAAQAAAAAAAgAFAAMAAAAAAAMAAgAAAAAAAQAAAAAAAAAAAAAAAAIAAAAB2AEAAAAKAQIAAAAc+wIAAE0BAjUAAAAAKwEBAIIAAQBNAgEgAQAAAE0DADsCAAAAJgUDAk0EBaoDAAAA+wkAAE0ICZ0FAAAATQcIcQYAAABNBgd5BwAAAFsFBgRgBAUABQAAAPsEAQCfBAEBqQQBAIIEAgCpBAAAggQCAAgDNwM/AyoDSAIAAAAAAADgPwMZA1wDWQDyA3UBGAAAAAEBAgABAAEAAAAAAAAAAAAAAAABAAEAAgDzAQAAAAIBAQAAAAP7AQAAnwEBAYIAAQAAAP8DdgEYAAABAAIAAAAMAgMAAAApDgEBAIIAAQBNAgDCAAAAAKQDAwACABDAmgIhAAMAAAD7BAAATQMENQQAAAArAwIAxgIAAGUAFgBNBAMgBQAAAE0FADsGAAAAJgcFBE0GB6oHAAAA+wsAAE0KC50JAAAATQkKcQoAAABNCAl5CwAAAFsHCAhgBgUABwAAAPsGAQCfBgEBqQIBAGUAAQCpAgAADgIDAKQDAwACABDA3gMCAIIAAQAMA2cDZgN3BAIAEMADNwM/AyoDSAIAAAAAAADgPwMZA1wDWQCDBHgBGBEBAgAAAAAA7AAAAQEAAgABAAEAAAAAAAAAAAAAAAABAAEAAgwBAAAD8wEAAAAEAgIAAAAQDgEBAIIAAQBNAgDCAAAAAKQDAwACABDAmgIIAAMAAAD7AgAApAMDAAIAEMCaAgMAAwAAAPsCAQCfAgEBggABAAQDZwNmA3cEAgAQwACOBHkBGA8BAgAAAAAAAAAAAADuABUAAgAAACcAAAECAOcBowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBAQAAAABAbwMEALwBARYDAAAAnwEDAk0CADEFAAAApAQHAAAAYEBNAwRICAAAAKQEAQAAAABAbwYJALwEBBYDAAAAnwQDAqQFCwAAAKBATQcEoQwAAABNBgcfDQAAAJ8FAgKkBgsAAACgQE0IBKEMAAAATQcIwg4AAACfBgICxgcAAP8HAAAAAAAAwAgPADAIBwEQAAAAwAgRADAIBzkSAAAAwAgTADAIB6EUAAAA2QgDABIBB/8wCAcZFQAAAMAIFgAwCAcmFwAAAMYIAAD/CAAAAAAAAE0JBe8YAAAAnwkBAjAJCDgZAAAATQkHARAAAACfCQEC/woAAAAAAAAwCggRGgAAANkLBQASAAoAEgEI/zALCF8bAAAAwAscABIACgAwCwhpHQAAAIwLAQDZDAcAEgEL/9kNCAASAQv/EgEI/9kOCQASAQj/2Q8KABIBCP/GEAAAxhEAAMYSAACkEyAAAHzggdkQCwASAA0AEgEI/9kRDAASAA0AEgEI/9kSDQASABMAEgANABIBCP+MEwEAxhQAAMYVAADGFgAAwBchANkUDwASAQj/2RUQABIADQASARP/EgEI/9kWEQASAA0AEgET/xIBCP/ZFxIAEgEH/xIBFP8SARX/EgEW/xIACQAwFwiKIgAAANkYEwASAQj/EgEH/xIBEP8SARH/EgES/xIACQASART/EgEV/xIBFv/ZGRQAEgEI/xIACQASARP/EgEL/xIBB/8SART/EgEV/xIBFv8wGAjrIwAAADAZCFwkAAAATDYAAqQaJgAAYFCCnxoBAtkbFQASAAoAEgACABIAGgASAAYAEgEI/xIAAwDZHBYAEgEI/xIBB/8SART/EgEV/xIBFv8SAAkA2R0XABIBCP8SAAEAxh4AANkfGAASABsAEgEI/xIAGQASAB0AEgEH/xIACQASABwAEgEe/zAfCCYXAAAA2R8ZABIBCP8SABgAwCAnABIAGQDGIQAA2SIbABIBCP8SABgAEgEh/9kjHAASASH/EgAZAE0kAYIoAAAAUiYiALwkJOcpAAAAnyQDAU0kAa8qAAAAUiYjALwkJOcpAAAAnyQDAU0kAcUrAAAAUiYfALwkJOcpAAAAnyQDAU0kAYssAAAAUiYgALwkJOcpAAAAnyQDAcELAADiCS8AMAgJ3S0AAAAwBwkzLgAAAMEHAACCCQIAMAN6BAAAAEADewN8A30DfgN/BAAAYEADgAEDgQEDggEEAACgQAODAQOEAQOFAQYAAwIGAQMIBgIDBgMKBgQDBwMoA3MDhgEDFgYHAw8DIAOHAQQAfOCBBg8DNgM+A0EDWwQAYFCCBhsDeAOIAQN5A3UDdgOJAQM9BQItLh0AAQIDBAYHCAkKCwwNDg8QERITFBUWFxgZGhscHQEAAQUAAQAAAAAAAQAAAAAAAQABAAAAAQAAAAAAAQAAAAAAAPoAAAAAAAACAgABAAAFAAAJAAAHAAAACwAAHQIAAQAAuwABAAABAAEAAQAAAAAOAAAADAEAAwAADwAIAAUAAALAAQAABQAABQAAAAsBAAACBwAFAAAABwAAAA0AAAAAAMcAAQAAAAAAAAAAACMAAAAAAAAAABIAAQAJAAAAAQAAvwAAAIUAAAAAAAAoAAAYAQAAAAAAAAAAAAAcAAANAAMOAAAACwAACAAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAOoBAAEAAAABAAAABwAAAEUAAABAAAAAQgAAAEEAAADzAAAAGAAAAAAe6GpQNHG2e5varjqgZEIgzA7wSeng9ftjzGgVU91D3SBfZgd9XvaHQQ==

-- Decompiled by Krnl

local v1 = game:GetService("Players")
local v_u_2 = game:GetService("UserInputService")
local v_u_3 = v1.LocalPlayer
local v_u_4 = workspace.CurrentCamera
local v5 = game:GetService("ReplicatedStorage")
local v6 = require(v5.Std.Signal)
local v_u_7 = require(v5.Std.Raycast)
local v_u_23 = {
	["MakeGroup"] = function()
		return {
			["Running"] = nil
		}
	end,
	["MakeSpec"] = function()
		return {
			["Duration"] = nil,
			["Start"] = nil,
			["End"] = nil,
			["Cancel"] = nil,
			["Update"] = nil
		}
	end,
	["Cancel"] = function(p8)
		local v9 = p8.Running
		if v9 then
			v9:Cancel()
			p8.Running = nil
		end
	end,
	["Push"] = function(p10, p11)
		-- upvalues: (ref) v_u_23
		v_u_23.Cancel(p10)
		local v12 = p11.Duration
		assert(v12)
		local v13 = p11.Start
		assert(v13)
		local v14 = p11.End
		assert(v14)
		local v15 = p11.Update
		assert(v15)
		if not p11.Cancel then
			p11.Cancel = p11.End
		end
		p10.Running = p11
	end,
	["Update"] = function(p16, p17)
		local v18 = p16.Running
		if v18 then
			local v19 = os.clock()
			if not v18.Started then
				v18.Started = v19
				v18:Start()
			end
			local v20 = v19 - v18.Started
			if v18.Elapsed then
				v20 = v20 + v18.Elapsed
			end
			local v21 = v20 / v18.Duration
			local v22 = v21 >= 1 and 1 or v21
			v18:Update(v22, p17)
			if v22 >= 1 then
				v18:End()
				p16.Running = nil
			end
		end
	end
}
local v_u_24 = {
	["onVisibilityChanged"] = v6.new()
}
local v_u_25 = v_u_23.MakeGroup()
local v_u_26 = {}
v_u_24.Specs = v_u_26
function v_u_24.Add(p27, p_u_28)
	-- upvalues: (copy) v_u_26, (ref) v_u_24
	assert(p_u_28, "No key found, second param to Add must be nil")
	p27.Tag = p_u_28
	if not p27.Enabled then
		p27.Enabled = true
	end
	if not p27.Priority then
		p27.Priority = 1
	end
	local v29 = v_u_26
	table.insert(v29, p27)
	return function()
		-- upvalues: (ref) v_u_24, (copy) p_u_28
		return v_u_24.Remove(p_u_28)
	end
end
function v_u_24.Remove(p30)
	-- upvalues: (copy) v_u_26
	for v31 = #v_u_26, 1, -1 do
		if v_u_26[v31].Tag == p30 then
			table.remove(v_u_26, v31)
			return true
		end
	end
	return false
end
local v_u_32 = 1
local function v_u_43(p33)
	-- upvalues: (ref) v_u_32, (ref) v_u_24
	v_u_32 = p33
	local v34 = v_u_24.Frame
	local v35 = v34.OuterFrame.Left.Image
	local v36 = v34.OuterFrame.Right.Image
	local v37 = v34.OuterFrame.OuterFull
	local v38 = v35.UIGradient
	local v39 = v36.UIGradient
	local v40 = p33 * 360
	local v41 = math.clamp(v40, 0, 360)
	v38.Rotation = math.clamp(v41, 180, 360)
	v39.Rotation = math.clamp(v41, 0, 180)
	local v42 = p33 < 0.999
	v35.Visible = v42
	v36.Visible = v42
	v37.Visible = not v42
end
local v_u_44 = math.sin
local function v_u_51()
	-- upvalues: (copy) v_u_43, (ref) v_u_24
	v_u_43(0)
	local v45 = v_u_24.Frame
	v45.OuterFrame.Size = UDim2.new(1, 8, 1, 8)
	v45.OuterFrame.Position = UDim2.new(0, -4, 0, -4)
	local v46 = Color3.fromRGB(214, 214, 214)
	local v47 = v_u_24.Frame
	local v48 = v47.OuterFrame.Left.Image
	local v49 = v47.OuterFrame.Right.Image
	local v50 = v47.OuterFrame.OuterFull
	v48.ImageColor3 = v46
	v49.ImageColor3 = v46
	v50.ImageColor3 = v46
end
local function v_u_58()
	-- upvalues: (copy) v_u_43, (ref) v_u_24
	v_u_43(1)
	local v52 = v_u_24.Frame
	v52.OuterFrame.Size = UDim2.new(1, 16, 1, 16)
	v52.OuterFrame.Position = UDim2.new(0, -8, 0, -8)
	local v53 = Color3.fromRGB(214, 214, 214)
	local v54 = v_u_24.Frame
	local v55 = v54.OuterFrame.Left.Image
	local v56 = v54.OuterFrame.Right.Image
	local v57 = v54.OuterFrame.OuterFull
	v55.ImageColor3 = v53
	v56.ImageColor3 = v53
	v57.ImageColor3 = v53
end
local function v_u_69(_, p59, _)
	-- upvalues: (copy) v_u_44, (copy) v_u_43, (ref) v_u_24
	local v60 = v_u_44(p59) / 0.8414709848078965
	v_u_43(v60)
	local v61 = 214 - (1 - v60) * 64
	local v62 = Color3.fromRGB(v61, v61, v61)
	local v63 = v_u_24.Frame
	local v64 = v63.OuterFrame.Left.Image
	local v65 = v63.OuterFrame.Right.Image
	local v66 = v63.OuterFrame.OuterFull
	v64.ImageColor3 = v62
	v65.ImageColor3 = v62
	v66.ImageColor3 = v62
	local v67 = v60 * 4 + 4
	local v68 = v_u_24.Frame
	v68.OuterFrame.Size = UDim2.new(1, 2 * v67, 1, 2 * v67)
	v68.OuterFrame.Position = UDim2.new(0, -v67, 0, -v67)
end
local v_u_70 = 1
local function v_u_77()
	-- upvalues: (ref) v_u_24
	local v71 = Color3.fromRGB(214, 214, 214)
	local v72 = v_u_24.Frame
	local v73 = v72.OuterFrame.Left.Image
	local v74 = v72.OuterFrame.Right.Image
	local v75 = v72.OuterFrame.OuterFull
	v73.ImageColor3 = v71
	v74.ImageColor3 = v71
	v75.ImageColor3 = v71
	local v76 = v_u_24.Frame
	v76.OuterFrame.Size = UDim2.new(1, 0, 1, 0)
	v76.OuterFrame.Position = UDim2.new(0, -0, 0, -0)
end
local function v_u_84()
	-- upvalues: (copy) v_u_43, (ref) v_u_70, (ref) v_u_24
	v_u_43(1)
	v_u_70 = 1
	local v78 = Color3.fromRGB(214, 214, 214)
	local v79 = v_u_24.Frame
	local v80 = v79.OuterFrame.Left.Image
	local v81 = v79.OuterFrame.Right.Image
	local v82 = v79.OuterFrame.OuterFull
	v80.ImageColor3 = v78
	v81.ImageColor3 = v78
	v82.ImageColor3 = v78
	local v83 = v_u_24.Frame
	v83.OuterFrame.Size = UDim2.new(1, 16, 1, 16)
	v83.OuterFrame.Position = UDim2.new(0, -8, 0, -8)
end
local function v_u_98(p85, p86, _)
	-- upvalues: (copy) v_u_43, (ref) v_u_70, (ref) v_u_24
	v_u_43(v_u_70 * (1 - p86) + p86)
	local v87 = 6 or 1.70158
	local v88 = p86 / 1 - 1
	local v89 = 8 * (1 * (v88 * v88 * ((v87 + 1) * v88 + v87) + 1) + 0)
	local v90 = v_u_24.Frame
	v90.OuterFrame.Size = UDim2.new(1, 2 * v89, 1, 2 * v89)
	v90.OuterFrame.Position = UDim2.new(0, -v89, 0, -v89)
	if p85.Red then
		local v91 = 40 - 40 * p86
		local v92 = 1 - p86
		local v93 = Color3.fromRGB(214 * v92 + 214 * p86 + v91, 69 * v92 + 214 * p86 + v91, 69 * v92 + 214 * p86 + v91)
		local v94 = v_u_24.Frame
		local v95 = v94.OuterFrame.Left.Image
		local v96 = v94.OuterFrame.Right.Image
		local v97 = v94.OuterFrame.OuterFull
		v95.ImageColor3 = v93
		v96.ImageColor3 = v93
		v97.ImageColor3 = v93
	end
end
function v_u_24.NotAllowed()
	-- upvalues: (ref) v_u_23, (ref) v_u_77, (ref) v_u_84, (ref) v_u_98, (copy) v_u_25
	local v99 = v_u_23.MakeSpec()
	v99.Duration = 0.3
	v99.Start = v_u_77
	v99.End = v_u_84
	v99.Update = v_u_98
	v99.Red = true
	v_u_23.Push(v_u_25, v99)
end
local function v_u_104()
	-- upvalues: (ref) v_u_24, (ref) v_u_23, (ref) v_u_51, (ref) v_u_58, (ref) v_u_69, (copy) v_u_25, (ref) v_u_77, (ref) v_u_84, (ref) v_u_98
	local v100 = v_u_24.Spec
	if v100 then
		v100:Callback(false)
		if v100.Timed then
			v100.Pressed = true
			v100.PressedAt = os.clock()
			local v101 = v_u_23.MakeSpec()
			v101.Duration = v100.Duration
			v101.Start = v_u_51
			v101.End = v_u_58
			v101.Update = v_u_69
			if v100.GetAccumulation then
				v101.Elapsed = v100.GetAccumulation()
			end
			v_u_23.Push(v_u_25, v101)
			v100.Animation = v101
			return
		elseif v100:Callback(true) then
			local v102 = v_u_23.MakeSpec()
			v102.Duration = 0.3
			v102.Start = v_u_77
			v102.End = v_u_84
			v102.Update = v_u_98
			v_u_23.Push(v_u_25, v102)
		else
			local v103 = v_u_23.MakeSpec()
			v103.Duration = 0.3
			v103.Start = v_u_77
			v103.End = v_u_84
			v103.Update = v_u_98
			v103.Red = true
			v_u_23.Push(v_u_25, v103)
		end
	else
		return
	end
end
local function v_u_107()
	-- upvalues: (ref) v_u_24, (copy) v_u_25, (ref) v_u_70, (ref) v_u_32, (ref) v_u_23, (ref) v_u_77, (ref) v_u_84, (ref) v_u_98
	local v105 = v_u_24.Spec
	if v105 then
		v105.Pressed = false
		v105.PressedAt = nil
		if v_u_25.Running ~= nil and v_u_25.Running == v105.Animation then
			v_u_70 = v_u_32
			v_u_23.Cancel(v_u_25)
			local v106 = v_u_23.MakeSpec()
			v106.Duration = 0.3
			v106.Start = v_u_77
			v106.End = v_u_84
			v106.Update = v_u_98
			v106.Red = true
			v_u_23.Push(v_u_25, v106)
		end
		v105.Animation = nil
		v105.ScreenPosition = nil
		v_u_24.Spec = nil
		if v105.ReleaseCallback then
			v105:ReleaseCallback(false)
		end
	end
end
v_u_24.Press = v_u_104
v_u_24.Release = v_u_107
local v_u_108 = Vector3.new()
local function v_u_142()
	-- upvalues: (copy) v_u_26, (copy) v_u_3, (copy) v_u_108, (copy) v_u_7, (ref) v_u_24, (copy) v_u_4
	local v109 = 999
	local v110 = 1
	local v111 = nil
	for v112 = #v_u_26, 1, -1 do
		if v_u_26[v112].Kill then
			table.remove(v_u_26, v112)
		end
	end
	local v113 = v_u_3.Character
	if v113 then
		local v114 = v113.PrimaryPart
		if v114 then
			local v115 = v114.Position
			local v116 = os.clock()
			local v117 = { v113 }
			for v118 = #v_u_26, 1, -1 do
				local v119 = v_u_26[v118]
				local v120 = v119.Part
				local v121 = v119.Attachment
				local v122 = v119.WorldPosition or v121 ~= nil and v121.WorldPosition or (v120 ~= nil and v120.Position or v_u_108)
				local v123 = v122 - v115
				local v124 = v123.Magnitude
				local v125 = v119.Dist
				local v126 = v119.IgnoreOverride
				if v119.PreUpdateFun and (not v120 or v124 <= v125) then
					local v127 = v119.PreUpdatePeriod or 0.2
					if not v119.LastPreUpdate or v127 <= v116 - v119.LastPreUpdate then
						v119.LastPreUpdate = v116
						v119:PreUpdateFun()
					end
				end
				if v119.Enabled and (v124 > 0 and v124 <= v125) then
					local v128 = false
					if v119.NoRay then
						v128 = true
					else
						local v129 = RaycastParams.new()
						v129.FilterDescendantsInstances = v126 or v117
						local v130 = v_u_7.collidable(v115, v123.Unit, v124, v129)
						local v131 = nil
						local v132
						if v130 then
							v131 = v130.Instance
							v132 = v130.Position
						else
							v132 = v115 + v123.Unit * v124
						end
						if (v132 - v122).Magnitude <= 1 then
							v128 = true
						elseif v131 then
							v128 = v131 == v119.Part and true or (v119.ValidRoot and v131:IsDescendantOf(v119.ValidRoot) and true or v128)
						end
					end
					if v128 then
						local v133 = v119.Priority
						if v124 <= v109 or v110 < v133 then
							v111 = v119
							v110 = v133
							v109 = v124
						end
					end
				end
			end
			local v134 = v_u_24.Frame
			local v135 = v_u_24.Spec
			if v135 and (v111 ~= v135 and v135.Pressed) then
				return
			else
				if v135 and (v135.HideFun and v111 ~= v135) then
					v135:HideFun()
				end
				v_u_24.Spec = v111
				if v111 then
					if v111.ShowFun and v111 ~= v135 then
						v111:ShowFun()
					end
					if v111.Update then
						v111:Update()
					end
					local v136 = v111.Attachment
					local v137 = v111.Part
					local v138, v139 = v_u_4:WorldToScreenPoint(v111.WorldPosition or v136 ~= nil and v136.WorldPosition or (v137 ~= nil and v137.Position or v_u_108))
					v134.Visible = v139
					if v139 then
						local v140 = v138.X
						local v141 = v138.Y
						v111.ScreenPosition = Vector3.new(v140, v141, 0)
						v134.Position = UDim2.new(0, v138.X, 0, v138.Y) - UDim2.new(0, v134.AbsoluteSize.X * 0.5, 0, v134.AbsoluteSize.Y * 0.5)
						v134.Help.Text = v111.Name or ""
						v134.Help.Visible = v111.Name and true or false
						return true
					end
					if v111.Pressed then
						return true
					end
				end
			end
		else
			return
		end
	else
		return
	end
end
local function v_u_150()
	-- upvalues: (ref) v_u_24, (ref) v_u_23, (ref) v_u_77, (ref) v_u_84, (ref) v_u_98, (copy) v_u_25
	local v143 = v_u_24.Spec
	if v143 then
		if v143.Pressed then
			local v144 = os.clock() - v143.PressedAt
			if v143.GetAccumulation then
				v144 = v144 + v143.GetAccumulation()
			end
			local v145 = v144 / v143.Duration
			local v146 = v145 >= 1 and 1 or v145
			if v143.WhilePressedUpdate then
				v143.WhilePressedUpdate(v146)
			end
			if v146 == 1 then
				v143.Pressed = false
				v143.PressedAt = nil
				local v147 = v143:Callback(true)
				if v143.ReleaseCallback then
					v143:ReleaseCallback(true)
				end
				if v147 then
					local v148 = v_u_23.MakeSpec()
					v148.Duration = 0.5
					v148.Start = v_u_77
					v148.End = v_u_84
					v148.Update = v_u_98
					v_u_23.Push(v_u_25, v148)
					return
				end
				local v149 = v_u_23.MakeSpec()
				v149.Duration = 0.3
				v149.Start = v_u_77
				v149.End = v_u_84
				v149.Update = v_u_98
				v149.Red = true
				v_u_23.Push(v_u_25, v149)
			end
		end
	else
		return
	end
end
local function v_u_157()
	-- upvalues: (ref) v_u_24, (copy) v_u_2
	local v151 = v_u_24.Frame
	local v152 = v_u_2:GetLastInputType()
	local v153
	if v_u_2.TouchEnabled then
		v153 = nil
	elseif v152 == Enum.UserInputType.Gamepad1 then
		local v154 = v_u_2:GetStringForKeyCode(Enum.KeyCode.ButtonY)
		v153 = v154 == "ButtonTriangle" and "\226\150\179" or (v154 == "ButtonY" and "Y" or v154)
	else
		v153 = "E"
	end
	v151.TextLabel.Visible = v153 ~= nil
	v151.PointLabel.Visible = v153 == nil
	if v153 then
		v151.TextLabel.Text = v153
	end
	local v155 = v_u_24.Spec
	local v156 = v151.Hold
	if v155 then
		v155 = v155.Timed
	end
	v156.Visible = v155
end
local v_u_158 = nil
function v_u_24.Update(p159)
	-- upvalues: (copy) v_u_142, (ref) v_u_24, (copy) v_u_107, (copy) v_u_157, (ref) v_u_23, (copy) v_u_25, (copy) v_u_150, (ref) v_u_158
	if not v_u_142() then
		v_u_24.Frame.Visible = false
		if v_u_24.Spec then
			if v_u_24.Spec.HideFun then
				v_u_24.Spec:HideFun()
			end
			v_u_107()
		end
	end
	v_u_157()
	v_u_23.Update(v_u_25, p159)
	v_u_150()
	if v_u_24.Spec ~= v_u_158 then
		v_u_24.onVisibilityChanged:Fire(v_u_24.Spec ~= nil)
	end
	v_u_158 = v_u_24.Spec
end
local function v163(p160)
	-- upvalues: (ref) v_u_24, (copy) v_u_104
	local v161 = v_u_24.Spec
	if v161 then
		local v162 = v161.ScreenPosition
		if (p160.Position - v162).Magnitude >= v_u_24.Frame.AbsoluteSize.X * 0.5 then
			return false
		end
		v_u_104()
		return true
	end
end
local v_u_164 = nil
local function v170(p165, p166)
	-- upvalues: (ref) v_u_24, (copy) v_u_104, (ref) v_u_164
	if not p166 then
		if p165.UserInputType == Enum.UserInputType.MouseButton1 then
			local v167 = v_u_24.Spec
			local v168
			if v167 then
				local v169 = v167.ScreenPosition
				if (p165.Position - v169).Magnitude < v_u_24.Frame.AbsoluteSize.X * 0.5 then
					v_u_104()
					v168 = true
				else
					v168 = false
				end
			else
				v168 = nil
			end
			if v168 then
				v_u_164 = Enum.UserInputType.MouseButton1
			end
		end
	end
end
local function v173(p171, p172)
	-- upvalues: (ref) v_u_164, (copy) v_u_107
	if not p172 then
		if p171.UserInputType == Enum.UserInputType.MouseButton1 and v_u_164 == Enum.UserInputType.MouseButton1 then
			v_u_107()
		end
	end
end
v_u_2.InputBegan:connect(v170)
v_u_2.InputEnded:connect(v173)
v_u_2.TouchStarted:connect(v163)
v_u_2.TouchEnded:connect(function(_)
	-- upvalues: (copy) v_u_107
	v_u_107()
end)
return {
	["CircleAction"] = v_u_24,
	["Animation"] = v_u_23
}
