-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgM5BXByb3BzCW1haW5SYXRpbwthc3BlY3RSYXRpbwVGcmFtZRZCYWNrZ3JvdW5kVHJhbnNwYXJlbmN5BFNpemUFVURpbTIDbmV3C0FzcGVjdFJhdGlvBExlZnQFUmlnaHQFVGl0bGUHQnV5Q2FzaBdVSUFzcGVjdFJhdGlvQ29uc3RyYWludA9Cb3JkZXJTaXplUGl4ZWwQQmFja2dyb3VuZENvbG9yMwhQb3NpdGlvbgZDb2xvcjMHZnJvbVJHQghVSUNvcm5lcgxDb3JuZXJSYWRpdXMEVURpbQlUZXh0TGFiZWwLQW5jaG9yUG9pbnQEVGV4dARGb250CkxpbmVIZWlnaHQKVGV4dFNjYWxlZA5UZXh0WEFsaWdubWVudApUZXh0Q29sb3IzBlpJbmRleAdWZWN0b3IyDllPVVIgQ0FTSDogJCVzBWNvbW1hBGNhc2gGZm9ybWF0BEVudW0LTHVja2llc3RHdXkKVGV4dEJ1dHRvbgAFRXZlbnQJQWN0aXZhdGVkEnByb21wdENhc2hQdXJjaGFzZQlCVVkgQ0FTSD8GcmVuZGVyBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZAZTdHJpbmcFUm9hY3QNY3JlYXRlRWxlbWVudA1QdXJlQ29tcG9uZW50B0Nhc2hCYXIGZXh0ZW5kDGRlZmF1bHRQcm9wcwACEgEDAAAIAAABAwm4AQLnAk0CAAcAAAAATQECHQEAAAArAQQATQIABwAAAABNAQKJAgAAAPsCAABvAwMA4gQGAIwFAQAwBQQ6BAAAAKQFCQAAIHCAjAYBAIwHAACMCAEAjAkAAJ8FBQIwBQQvBQAAAOIFDwD7BgAAbwcQAOIIEQBbCgETPgkKEjAJCGkKAAAAnwYDAjAGBWkKAAAA+wYAAG8HAwDiCBcAjAkAADAJCDoEAAAAjAkAADAJCI4UAAAApAkaAABkgIGMCoYAjAvDAIwMUQCfCQQCMAkInxUAAACkCQkAACBwgIwKAACMCwAAjAwAAIwNAACfCQUCMAkIOxYAAACkCQkAACBwgG8KGwCMCwAAjAwBAIwNAACfCQUCMAkILwUAAADiCR0A+woAAG8LHADiDB8ApA0hAAAgAIJvDiIAjA8AAJ8NAwIwDQxPHgAAAJ8KAwIwCgn0HAAAAJ8GBAIwBgXGCwAAAPsGAABvBwMA4ggXAIwJAAAwCQg6BAAAAIwJAAAwCQiOFAAAAKQJGgAAZICBjAqGAIwLwwCMDFEAnwkEAjAJCJ8VAAAApAkJAAAgcIBvCiMAjAsAAIwMAACMDQAAnwkFAjAJCDsWAAAApAkJAAAgcIBvChsAjAsAAIwMAQCMDQAAnwkFAjAJCC8FAAAA4gkdAPsKAABvCxwA4gwfAKQNIQAAIACCjA4BAIwPAACfDQMCMA0MTx4AAACfCgMCMAoJ9BwAAACfBgQCMAYFBQwAAAD7BgAAbwckAOIILQCMCQEAMAkIOgQAAACMCQAAMAkIjhQAAACkCQkAACBwgG8KLgCMCwAAbwwvAIwNAACfCQUCMAkILwUAAACkCQkAACBwgFsMARM+Cwww2AojC4wLAABvDC8AjA0AAJ8JBQIwCQg7FgAAAKQJMgAAIBCDjAoAAG8LLwCfCQMCMAkI6CUAAABvCTMA+wwBAE0LDOQ0AAAATQ0ABwAAAABNDA2fNQAAAJ8LAgC8CQmNNgAAAJ8JAAIwCQj1JgAAAKQJOQA4nHDDMAkIOScAAABvCS4AMAkIgigAAACpCQEAMAkI3ikAAACkCToAC6hwwzAJCHsqAAAApAk7AAAggIGMCgAAjAsAAIwMAACfCQQCMAkIcysAAACMCQQAMAkIDSwAAACfBgMCMAYFug0AAAD7BgAAbwc8AP8IBAAAAAAAbwk9ADAJCPUmAAAApAk7AAAggIFvCj4Abws+AG8MPgCfCQQCMAkInxUAAACkCQkAACBwgIwKAQCMCwAAbww/AIwNAACfCQUCMAkILwUAAACkCTIAACAQg4wKAQBvCy8AnwkDAjAJCOglAAAApAkJAAAgcIBbDQETPgwNMNgLQQz1CkALjAsAAG8MLwCMDQAAnwkFAjAJCDsWAAAAjAkFADAJCA0sAAAA+wsCAE0KCzZCAAAATQkKHkMAAABNCwAHAAAAAE0KC/REAAAAagoICeIJRQD7CgAAbwsQAOIMEQBvDUYAMA0MaQoAAACfCgMCMAoJaQoAAAD7CgAAbwscAOIMHwCkDSEAACAAgowOAQCMDwAAnw0DAjANDE8eAAAAnwoDAjAKCfQcAAAA+woAAG8LJADiDEcAjA0BADANDDoEAAAApA0JAAAgcIBvDj8AjA8AAG8QPwCMEQAAnw0FAjANDC8FAAAApA0JAAAgcIBvDi8AjA8AAG8QLwCMEQAAnw0FAjANDDsWAAAApA0yAAAgEINvDi8Abw8vAJ8NAwIwDQzoJQAAAG8NSAAwDQz1JgAAAKQNOQA4nHDDMA0MOScAAABvDS4AMA0MgigAAACpDQEAMA0M3ikAAACkDTsAACCAgYwOAQCMDwEAjBABAJ8NBAIwDQxzKwAAAIwNBAAwDQwNLAAAAJ8KAwIwCgm6DQAAAJ8GBAIwBgXiDgAAAJ8CBACCAgAASQMBAwIDAwMEAwUDBgUCBAUDBwMIBAAgcIADCQMKAwsDDAMNBQUKCwwNDgMOBQEKAgAAAAAAACJAAgAAAAAAABRAAw8DEAMRBQUEFBUWBQMSAxMEAGSAgQIAAAAAAADoPwMUBQEcAxUFAR4DFgQAIACCApqZmZmZmck/AgAAAAAAANA/AxcDGAMZAxoDGwMcAx0DHgMfBQwEFAUWJSYnKCkqKywCZmZmZmZm5j8CAAAAAAAA4D8CAAAAAAAAHEADIAQAIBCDAyEDIgMjAyQDJQMmBDiccMMEC6hwwwQAIICBAycDKAKamZmZmZm5PwKamZmZmZnpPwIAAAAAAADwPwL+//////+/PwMpAyoDKwUDChwNAgAAAAAAABZABQoEBRYlJicoKSssAywADC0BGAAAAAAAAAAAAAIAAAEAAAEAAAAAAAAAAAEBAAABAAAA/wAAAwAAAQAAAQAAAQAAAAAAAAABAAAAAAAAAAABAAAAAAAAAAABAQAAAQAAAAAAAP8AAPkAAAsAAAEAAAEAAAEAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAQEAAAEAAAAAAAD/AAD5AAALAAABAAABAAABAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAAAAAAAAAEAAAABAAABAAABAAAAAQAAAAAAAAABAAD0AAAOAAAAAQAAAQAAAAAAAAABAAAAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAAAAQAAAQAAAAAAAAAAAAEBAAABAAD/AAADAAABAAAAAAAA/wAAAwAAAQAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAEAAAABAAABAAABAAAAAAAAAAEAAPYAAPEAANUADQAAAAAHAAABAgAoowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAoQYAAABNAgOhBwAAAJ8BAgKkAgUAAABAQE0DACEIAAAAnwICAk0DAsoJAAAATQQC+AoAAABvBgsAvAQEnAwAAACfBAMC4gUOAIwGAAAwBgWfDQAAADAFBJIPAAAAwAUQABIAAwASAAEAEgACADAFBIARAAAAggQCABIDLgQAAABAAy8DMAMxBAAAQEADMgMzAzQDNQM2AzcDOAMjBQENAzkGAAMtAQABAAEYAAEAAAAAAAEAAAAAAAABAAAAAAEAAgAAAAAAAgEAAP8AAwAAAAAATQEAAAAAAT5vFfQy5qYjDKt/YAroZBa7Oj10/FKMwtH+VulOZsNKkWeP03cRl5I=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.String)
local v_u_3 = require(v1.Roact)
local v_u_4 = v_u_3.createElement
local v5 = v_u_3.PureComponent:extend("CashBar")
v5.defaultProps = {
	["cash"] = 0
}
function v5.render(p6)
	-- upvalues: (copy) v_u_4, (copy) v_u_2, (copy) v_u_3
	local v7 = p6.props.mainRatio or p6.props.aspectRatio
	return v_u_4("Frame", {
		["BackgroundTransparency"] = 1,
		["Size"] = UDim2.new(1, 0, 1, 0)
	}, {
		["AspectRatio"] = v_u_4("UIAspectRatioConstraint", {
			["AspectRatio"] = v7 * 5 / 9
		}),
		["Left"] = v_u_4("Frame", {
			["BackgroundTransparency"] = 0,
			["BorderSizePixel"] = 0,
			["BackgroundColor3"] = Color3.fromRGB(134, 195, 81),
			["Position"] = UDim2.new(0, 0, 0, 0),
			["Size"] = UDim2.new(0.75, 0, 1, 0)
		}, {
			["UICorner"] = v_u_4("UICorner", {
				["CornerRadius"] = UDim.new(0.2, 0)
			})
		}),
		["Right"] = v_u_4("Frame", {
			["BackgroundTransparency"] = 0,
			["BorderSizePixel"] = 0,
			["BackgroundColor3"] = Color3.fromRGB(134, 195, 81),
			["Position"] = UDim2.new(0.25, 0, 0, 0),
			["Size"] = UDim2.new(0.75, 0, 1, 0)
		}, {
			["UICorner"] = v_u_4("UICorner", {
				["CornerRadius"] = UDim.new(1, 0)
			})
		}),
		["Title"] = v_u_4("TextLabel", {
			["BackgroundTransparency"] = 1,
			["BorderSizePixel"] = 0,
			["Size"] = UDim2.new(0.7, 0, 0.5, 0),
			["Position"] = UDim2.new(0.25 / (v7 * 5 / 7), 0, 0.5, 0),
			["AnchorPoint"] = Vector2.new(0, 0.5),
			["Text"] = ("YOUR CASH: $%s"):format(v_u_2.comma(p6.props.cash)),
			["Font"] = Enum.Font.LuckiestGuy,
			["LineHeight"] = 0.7,
			["TextScaled"] = true,
			["TextXAlignment"] = Enum.TextXAlignment.Left,
			["TextColor3"] = Color3.new(0, 0, 0),
			["ZIndex"] = 4
		}),
		["BuyCash"] = v_u_4("TextButton", {
			["Text"] = "",
			["BackgroundColor3"] = Color3.new(0.1, 0.1, 0.1),
			["Size"] = UDim2.new(1, 0, 0.8, 0),
			["AnchorPoint"] = Vector2.new(1, 0.5),
			["Position"] = UDim2.new(1 - 0.12499999999999997 / (v7 * 5 / 7), 0, 0.5, 0),
			["ZIndex"] = 5,
			[v_u_3.Event.Activated] = p6.props.promptCashPurchase
		}, {
			["AspectRatio"] = v_u_4("UIAspectRatioConstraint", {
				["AspectRatio"] = 5.5
			}),
			["UICorner"] = v_u_4("UICorner", {
				["CornerRadius"] = UDim.new(1, 0)
			}),
			["Title"] = v_u_4("TextLabel", {
				["BackgroundTransparency"] = 1,
				["Size"] = UDim2.new(0.8, 0, 0.8, 0),
				["Position"] = UDim2.new(0.5, 0, 0.5, 0),
				["AnchorPoint"] = Vector2.new(0.5, 0.5),
				["Text"] = "BUY CASH?",
				["Font"] = Enum.Font.LuckiestGuy,
				["LineHeight"] = 0.7,
				["TextScaled"] = true,
				["TextColor3"] = Color3.new(1, 1, 1),
				["ZIndex"] = 4
			})
		})
	})
end
return v5
