-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgM/BXByb3BzC2FzcGVjdFJhdGlvClRleHRCdXR0b24IZGlzYWJsZWQPQXV0b0J1dHRvbkNvbG9yAARUZXh0FkJhY2tncm91bmRUcmFuc3BhcmVuY3kPQm9yZGVyU2l6ZVBpeGVsCmJyaWdodGVuVG8FY29sb3IQQmFja2dyb3VuZENvbG9yMwhwb3NpdGlvbghQb3NpdGlvbgthbmNob3JQb2ludAtBbmNob3JQb2ludARzaXplBFNpemULbGF5b3V0T3JkZXILTGF5b3V0T3JkZXIFRXZlbnQJQWN0aXZhdGVkB29uQ2xpY2sLQXNwZWN0UmF0aW8IVUlDb3JuZXIFVGl0bGUETG9jaxdVSUFzcGVjdFJhdGlvQ29uc3RyYWludAxDb3JuZXJSYWRpdXMEVURpbQNuZXcJVGV4dExhYmVsBEZvbnQKTGluZUhlaWdodApUZXh0U2NhbGVkClRleHRDb2xvcjMFVURpbTIHVmVjdG9yMgV0aXRsZQRFbnVtB0JhbmdlcnMGQ29sb3IzCFVJU3Ryb2tlBUNvbG9yCVRoaWNrbmVzcwZsb2NrZWQKSW1hZ2VMYWJlbAVJbWFnZRdyYnhhc3NldGlkOi8vODcxNTcwODQ1NRdyYnhhc3NldGlkOi8vODcxNTcwODgyNAZyZW5kZXIEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUDU3RkCkNvbG9yVXRpbHMFUm9hY3QNY3JlYXRlRWxlbWVudA1QdXJlQ29tcG9uZW50C1JvdW5kQnV0dG9uBmV4dGVuZAxkZWZhdWx0UHJvcHMAAhEBAwAAAO0BTQIABwAAAABNAQKJAQAAAPsCAABvAwIA/wQFAAAAAABNBwAHAAAAAE0GB4IDAAAAVgUGADAFBNcEAAAAbwUFADAFBPUGAAAAjAUAADAFBDoHAAAAjAUAADAFBI4IAAAATQcABwAAAABNBgeCAwAAAA4GCgD7BgEATQUGsAkAAABNBwAHAAAAAE0GB0QKAAAAbwcLAJ8FAwIrBQQATQYABwAAAABNBQZECgAAADAFBJ8MAAAATQYABwAAAABNBQbbDQAAADAFBDsOAAAATQYABwAAAABNBQYIDwAAADAFBOgQAAAATQYABwAAAABNBQYPEQAAADAFBC8SAAAATQYABwAAAABNBQYgEwAAADAFBAAUAAAA+wcCAE0GBzYVAAAATQUGHhYAAABNBwAHAAAAAE0GB24XAAAAagYEBeIFHACpBgAATQgABwAAAABNBwiJAQAAAEcHCwAAAAAA+wYAAG8HHQDiCB4ATQoABwAAAABNCQqJAQAAADAJCGkYAAAAnwYDAjAGBWkYAAAA+wYAAG8HGQDiCCAApAkjAACIEIKMCgEAjAsAAJ8JAwIwCQhPHwAAAJ8GAwIwBgX0GQAAAPsGAABvByQA4ggpAIwJAQAwCQg6BwAAAKQJKwAAiKCCbwosAIwLAABvDCwAjA0AAJ8JBQIwCQgvEgAAAKQJKwAAiKCCbwotAIwLAABvDC0AjA0AAJ8JBQIwCQg7DgAAAKQJLwAAiOCCbwotAG8LLQCfCQMCMAkI6BAAAABNCgAHAAAAAE0JCpowAAAAMAkI9QYAAACkCTMAMpQQwzAJCDklAAAAbwk0ADAJCIImAAAAqQkBADAJCN4nAAAApAk2AACIUIOMCgEAjAsBAIwMAQCfCQQCMAkIcygAAADiCTgA+woAAG8LNwDiDDsApA02AACIUIOMDgAAjA8AAIwQAACfDQQCMA0MpDkAAACMDQEAMA0MGDoAAACfCgMCMAoJbTcAAACfBgQCMAYFuhoAAACpBgAATQgABwAAAABNBwiMPAAAAEcHJwAAAAAA+wYAAG8HPQDiCD8AjAkAADAJCI4IAAAAjAkBADAJCDoHAAAApAkrAACIoILYCkABjAsAAG8MQACMDQAAnwkFAjAJCC8SAAAApAkrAACIoILYCkEBjAsAAG8MQQCMDQAAnwkFAjAJCDsOAAAATQsABwAAAABNCguMPAAAAA4KAgBvCUIAZQABAG8JQwAwCQipPgAAAJ8GAwIwBgUrGwAAAJ8CBACCAgAARAMBAwIDAwMEAwUDBgMHAwgDCQMKAwsCmpmZmZmZuT8DDAMNAw4DDwMQAxEDEgMTAxQDFQMWAxcDGAMZAxoDGwUEGBkaGwMcBQEYAx0FAR8DHgMfBACIEIIDIAMhAyIDIwMkBQkHEg4QBiUmJygDJQQAiKCCAmZmZmZmZuY/AgAAAAAAAOA/AyYEAIjgggMnAygDKQQylBDDAs3MzMzMzOw/AyoEAIhQgwMrBQE3AywDLQUCOToDLgMvAzAFBQgHEg4+AjMzMzMzM+M/ApqZmZmZmck/AzEDMgANMwEYAAAAAAMAAAABAAAAAAAAAQAAAQAAAQAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAAAAAAEBAAAAAAAAAAAAAQAAAAAA/wAAAwAAAQAAAAAAAP8AAAMAAAEAAAEAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAABAAAAAAABAAAAAQAAAQAAAQAAAAAAAAABAQAAAQAAAAAAAAABAAD+AAD1AAAQAAAAAAAAAAAAAQAAAQAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAPsAAN4ADgAAAAALAAABAgAxowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAoQYAAABNAgMzBwAAAJ8BAgKkAgUAAABAQE0DACEIAAAAnwICAk0DAsoJAAAATQQC+AoAAABvBgsAvAQEnAwAAACfBAMC4gUPAKQGEgAARACBjAcBAIwIAACMCQEAjAoAAJ8GBQIwBgUPDQAAAKkGAAAwBgWCDgAAADAFBJITAAAAwAUUABIAAwASAAEAEgACADAFBIAVAAAAggQCABYDNAQAAABAAzUDNgM3BAAAQEADOAM5AzoDOwM8Az0DPgMRAwQFAg0OAyUDHwQARACBAz8GAAMzAQABAAEYAAEAAAAAAAEAAAAAAAABAAAAAAEAAgAAAAAAAQEAAAAAAAAAAAIAAP0ABQAAAAAAMAEAAAAAAdsZSIDe81ro6d0iFKpXYbCxSi1OukHnn6Vb3/voYU99UpV1xChfl5k=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.ColorUtils)
local v_u_3 = require(v1.Roact)
local v_u_4 = v_u_3.createElement
local v5 = v_u_3.PureComponent:extend("RoundButton")
v5.defaultProps = {
	["size"] = UDim2.new(1, 0, 1, 0),
	["disabled"] = false
}
function v5.render(p6)
	-- upvalues: (copy) v_u_4, (copy) v_u_2, (copy) v_u_3
	local v7 = p6.props.aspectRatio
	local v8 = v_u_4
	local v9 = "TextButton"
	local v10 = {
		["AutoButtonColor"] = not p6.props.disabled,
		["Text"] = "",
		["BackgroundTransparency"] = 0,
		["BorderSizePixel"] = 0,
		["BackgroundColor3"] = p6.props.disabled and v_u_2.brightenTo(p6.props.color, 0.1) or p6.props.color,
		["Position"] = p6.props.position,
		["AnchorPoint"] = p6.props.anchorPoint,
		["Size"] = p6.props.size,
		["LayoutOrder"] = p6.props.layoutOrder,
		[v_u_3.Event.Activated] = p6.props.onClick
	}
	local v11 = {}
	local v12
	if p6.props.aspectRatio == nil then
		v12 = false
	else
		v12 = v_u_4("UIAspectRatioConstraint", {
			["AspectRatio"] = p6.props.aspectRatio
		})
	end
	v11.AspectRatio = v12
	v11.UICorner = v_u_4("UICorner", {
		["CornerRadius"] = UDim.new(1, 0)
	})
	v11.Title = v_u_4("TextLabel", {
		["BackgroundTransparency"] = 1,
		["Size"] = UDim2.new(0.7, 0, 0.7, 0),
		["Position"] = UDim2.new(0.5, 0, 0.5, 0),
		["AnchorPoint"] = Vector2.new(0.5, 0.5),
		["Text"] = p6.props.title,
		["Font"] = Enum.Font.Bangers,
		["LineHeight"] = 0.9,
		["TextScaled"] = true,
		["TextColor3"] = Color3.new(1, 1, 1)
	}, {
		["UIStroke"] = v_u_4("UIStroke", {
			["Color"] = Color3.new(0, 0, 0),
			["Thickness"] = 1
		})
	})
	local v13
	if p6.props.locked == nil then
		v13 = false
	else
		v13 = v_u_4("ImageLabel", {
			["BorderSizePixel"] = 0,
			["BackgroundTransparency"] = 1,
			["Size"] = UDim2.new(0.6 / v7, 0, 0.6, 0),
			["Position"] = UDim2.new(0.2 / v7, 0, 0.2, 0),
			["Image"] = p6.props.locked and "rbxassetid://8715708455" or "rbxassetid://8715708824"
		})
	end
	v11.Lock = v13
	return v8(v9, v10, v11)
end
return v5
