-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgM3A25ldwRtYWlkBGluaXQFcHJvcHMLaW5uZXJSYWRpdXMEbWF0aANjb3MDc2luBVVEaW0yBGxpc3QKSW1hZ2VMYWJlbBZCYWNrZ3JvdW5kVHJhbnNwYXJlbmN5BUltYWdlBFNpemULSW1hZ2VDb2xvcjMLQW5jaG9yUG9pbnQIUG9zaXRpb24IUm90YXRpb24RSW1hZ2VUcmFuc3BhcmVuY3kGWkluZGV4F3JieGFzc2V0aWQ6Ly85NDgyNjkxNzc0BWNvbG9yB1ZlY3RvcjIFYW5nbGUDbWFwDHRyYW5zcGFyZW5jeQVGcmFtZQRzaXplC2FuY2hvclBvaW50CHBvc2l0aW9uBW1lcmdlC0FzcGVjdFJhdGlvF1VJQXNwZWN0UmF0aW9Db25zdHJhaW50BnJlbmRlcgJfYwZyYW5kb20Ic2V0U3RhdGUNb25Gb3JjZVVwZGF0ZQdDb25uZWN0CEdpdmVUYXNrCGRpZE1vdW50BGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZARNYWlkCkRpY3Rpb25hcnkFUm9hY3QNY3JlYXRlRWxlbWVudA9EYW1hZ2VJbmRpY2F0b3IWRGFtYWdlSW5kaWNhdG9yU2VydmljZQ1QdXJlQ29tcG9uZW50BmV4dGVuZAxkZWZhdWx0UHJvcHMABwMBAQAAAAf7AgAATQEC7wAAAACfAQECMAEAFgEAAACCAAEAAgMBAwIAEQMBGAAAAAAAAAESAAAAAAgBAQAAACD7BQAATQQFBwAAAABNAwSJAQAAALsJAANSBQAApAQEAAAMIICfBAICCQEDBPsFAABNBAUHAAAAAE0DBIkBAAAAuxgAA1IFAACkBAYAABQggJ8EAgIJAgMEpAMJAAAgcIBvBQoAQwQFAYwFAABvBwoAQwYHAowHAACfAwUAggMAAAsDBAMFAwYDBwQADCCAAwgEABQggAMJAwEEACBwgAIAAAAAAADgPwAhAAEYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAiAAAAAAUBAAAAAAWMBLQACQMEAD4CAwGVAQIAggECAAICAAAAAACAVkACGC1EVPshCUAAJQABGAAAAAAAJgAAAAAOAQMAAABt/wEAAAAAAACMBAEA+wYAAE0FBgsAAAAAHAIFAIwDAQCoAjsA+wcAAE0GBwsAAAAAhwUGBPsGAQBvBwEA4ggLAIwJAQAwCQg6AgAAAG8JDAAwCQipAwAAAKQJDwAAONCAbwoQAIwLAABvDBEAjA0AAJ8JBQIwCQgvBAAAAE0JBUQSAAAAMAkIAAUAAACkCRQAADgwgW8KFQBvCxUAnwkDAjAJCOgGAAAATQkFzRYAAADZCwAAEgAAALwJCZAXAAAAnwkDAjAJCDsHAAAATQkFzRYAAADACxgAvAkJkBcAAACfCQMCMAkIOAgAAABNCQU5GQAAADAJCKMJAAAAMAQIDQoAAACfBgMCagYBBIsCxf/7AgEAbwMaAOIEGwCMBQEAMAUEOgIAAABNBgAHHAAAAE0FBg8dAAAAMAUELwQAAABNBgAHHAAAAE0FBggeAAAAMAUE6AYAAABNBgAHHAAAAE0FBtsfAAAAMAUEOwcAAAD7BgIATQUGHyAAAADiBiIA+wcBAG8IIwDiCSIAjAoBADAKCWkhAAAAnwcDAjAHBmkhAAAAUgcBAJ8FAwCfAgAAggIAACQDCgMLAwwDDQMOAw8DEAMRAxIDEwMUBQkCAwQFBgcICQoDFQMJAwEEADjQgAJmZmZmZmbmPwI8KUj+vMrSPwMWAxcEADgwgQIAAAAAAADgPwMYAxkGAgMaAxsFBAIEBgcDBAMcAx0DHgMfAyAFASEDIQIBAhQiARgAAAEAAAAAAAABAAAAAwAAAQAAAQAAAQAAAAAAAAAAAQAAAAEAAAAAAAABAAAAAAAAAAAEAAAAAAAAAAMAAAABAPIA/BUBAQEAAAEAAAAAAAEAAAAAAAEAAAAAAAIAAAABAAABAAD/AAAD/PgAFgAAAAAEAAEAAAAL+wAAAOICAQCkAwQAAAwggJ8DAQIwAwIGAAAAALwAACoFAAAAnwADAYIAAQAGAyMFAQADBgMkBAAMIIADJQA8AAEYAAABAAAAAP8AAAM+AAAAAAYBAQAAAA5NAQAWAAAAAPsEAABNAwQ2AQAAANkFAAASAAAAvAMDxwIAAACfAwMAvAEB/QMAAACfAQABggABAAQDAgMmAycDKAEEOykBGAAAAAAAAAAAAAAAAAAGPAAAAAANAAABAgBXowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAoQYAAABNAgN2BwAAAJ8BAgKkAgUAAABAQE0EAKEGAAAATQMEqQgAAACfAgICpAMFAAAAQEBNBAAhCQAAAJ8DAgJNBAPKCgAAAKQFBQAAAEBATQcAoQsAAABNBgfjDAAAAJ8FAgJNBgP4DQAAAG8ICwC8BgacDgAAAJ8GAwLiBxMAbwgUADAIB4kPAAAApAgXAABYUIFvCRgAjAoAAG8LGACMDAAAnwgFAjAIBw8QAAAApAgaAABYkIFvCRQAbwoUAJ8IAwIwCAcIEQAAAKQIFwAAWFCBbwkUAIwKAABvCxQAjAwAAJ8IBQIwCAfbEgAAADAHBpIbAAAAwAccABIAAQAwBwYTHQAAAMAHHgASAAUAEgAEABIAAgAwBwaAHwAAAMAHIAASAAUAMAcGaiEAAACCBgIAIgMqBAAAAEADKwMsAy0EAABAQAMuAy8DMAMxAzIDMwM0AzUDNgMFAxwDHQMeBQQPEBESAgAAAAAAAOA/AwkDAQQAWFCBApqZmZmZmck/AxcEAFiQgQM3BgADAwYDAyIGBQMpAwADBQEAARgAAQAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAEAAgAAAAAAAAIAAAAAAAEBAAABAAAAAAAAAAABAAAAAAAAAQAAAAAAAAAA/AAGAAAAAwAAAAAAJwAAAAkBAAAAAAbNCp4VcRyD0//O9IHVceJy9Fr1vNUNY0fPRzYMuvTlHVcKsw/LwtpY

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.Maid)
local v_u_3 = require(v1.Std.Dictionary)
local v4 = require(v1.Roact)
local v_u_5 = v4.createElement
local v_u_6 = require(v1.DamageIndicator.DamageIndicatorService)
local v7 = v4.PureComponent:extend("DamageIndicator")
v7.defaultProps = {
	["innerRadius"] = 0.5,
	["size"] = UDim2.new(0.2, 0, 0.2, 0),
	["anchorPoint"] = Vector2.new(0.5, 0.5),
	["position"] = UDim2.new(0.5, 0, 0.5, 0)
}
function v7.init(p8)
	-- upvalues: (copy) v_u_2
	p8.maid = v_u_2.new()
end
function v7.render(p_u_9)
	-- upvalues: (copy) v_u_6, (copy) v_u_5, (copy) v_u_3
	local v10 = {}
	for v11 = 1, #v_u_6.list do
		local v12 = v_u_6.list[v11]
		v10[v11] = v_u_5("ImageLabel", {
			["BackgroundTransparency"] = 1,
			["Image"] = "rbxassetid://9482691774",
			["Size"] = UDim2.new(0.7, 0, 0.2936241610738255, 0),
			["ImageColor3"] = v12.color,
			["AnchorPoint"] = Vector2.new(0.5, 0.5),
			["Position"] = v12.angle:map(function(p13)
				-- upvalues: (copy) p_u_9
				local v14 = p_u_9.props.innerRadius * math.cos(p13)
				local v15 = p_u_9.props.innerRadius * math.sin(p13)
				return UDim2.new(0.5 + v14, 0, 0.5 + v15, 0)
			end),
			["Rotation"] = v12.angle:map(function(p16)
				return 180 * p16 / 3.141592653589793 + 90
			end),
			["ImageTransparency"] = v12.transparency,
			["ZIndex"] = v11
		})
	end
	local v17 = v_u_5
	local v18 = {
		["BackgroundTransparency"] = 1,
		["Size"] = p_u_9.props.size,
		["AnchorPoint"] = p_u_9.props.anchorPoint,
		["Position"] = p_u_9.props.position
	}
	local v19 = v_u_3.merge
	local v20 = {
		["AspectRatio"] = v_u_5("UIAspectRatioConstraint", {
			["AspectRatio"] = 1
		})
	}
	return v17("Frame", v18, v19(v20, v10))
end
function v7.didMount(p_u_21)
	-- upvalues: (copy) v_u_6
	p_u_21.maid:GiveTask(v_u_6.onForceUpdate:Connect(function()
		-- upvalues: (copy) p_u_21
		p_u_21:setState({
			["_c"] = math.random()
		})
	end))
end
return v7
