-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgM5BWhvdmVyCHNldFN0YXRlBGluaXQFVURpbTIDbmV3BXByb3BzCHBhZGRpbmdYBmFjdGl2ZQ9iYWNrZ3JvdW5kQ29sb3IFc3RhdGUKYnJpZ2h0ZW5UbwpUZXh0QnV0dG9uDXNjYWxlWEJpbmRpbmcDbWFwBFNpemUPQm9yZGVyU2l6ZVBpeGVsFkJhY2tncm91bmRUcmFuc3BhcmVuY3kQQmFja2dyb3VuZENvbG9yMwtsYXlvdXRPcmRlcgtMYXlvdXRPcmRlcgAEVGV4dA9BdXRvQnV0dG9uQ29sb3IFRXZlbnQQTW91c2VCdXR0b24xRG93bgdvbkNsaWNrCk1vdXNlRW50ZXIKTW91c2VMZWF2ZQhVSUNvcm5lcgVUaXRsZQxDb3JuZXJSYWRpdXMEVURpbQlUZXh0TGFiZWwIUG9zaXRpb24ERm9udApMaW5lSGVpZ2h0ClRleHRTY2FsZWQKVGV4dENvbG9yMwV0aXRsZQRFbnVtC0x1Y2tpZXN0R3V5BkNvbG9yMwpzYXR1cmF0ZVRvCmJyaWdodGVuQnkGcmVuZGVyBnNjcmlwdARFelVpEUZpbmRGaXJzdEFuY2VzdG9yB3JlcXVpcmUGUGFyZW50A1N0ZApDb2xvclV0aWxzBVJvYWN0DWNyZWF0ZUVsZW1lbnQNUHVyZUNvbXBvbmVudANUYWIGZXh0ZW5kAAYFAQAAAAAI4gMBAKkEAAAwBAOwAAAAALwBACoCAAAAnwEDAYIAAQADAwEFAQADAgAJAwEYAAEAAP8AAAMKAAAAAAcBAQAAAA2kAQIAAAQAgFICAAD7BgAATQUGBwMAAABNBAUTBAAAADkDBACMBAEAjAUAAJ8BBQCCAQAABQMEAwUEAAQAgAMGAwcAFAABGAAAAAAAAAAAAAAAAAAVAAAAAAQAAQAAAAn7AAAA4gIBAKkDAQAwAwKwAAAAALwAACoCAAAAnwADAYIAAQADAwEFAQADAgAhAAEYAAABAAD/AAADIgAAAAAEAAEAAAAJ+wAAAOICAQCpAwAAMAMCsAAAAAC8AAAqAgAAAJ8AAwGCAAEAAwMBBQEAAwIAJgABGAAAAQAA/wAAAycAAAAADgEDAAAAswFNAwAHAAAAAE0CA+MBAAAADgIFAE0CAAcAAAAATQECDgIAAAArARgATQMAGAMAAABNAgOwBAAAAA4CCgD7AgAATQECsAUAAABNAwAHAAAAAE0CAw4CAAAAbwMGAJ8BAwIrAQkA+wIAAE0BArAFAAAATQMABwAAAABNAgMOAgAAAG8DBwCfAQMC+wIBAG8DCAD/BAUAAAAAAE0GAAcAAAAATQUGDAkAAADZBwAAEgAAALwFBZAKAAAAnwUDAjAFBC8LAAAAjAUAADAFBI4MAAAAjAUAADAFBDoNAAAAMAEEnw4AAABNBgAHAAAAAE0FBiAPAAAAMAUEABAAAABvBREAMAUE9RIAAACpBQAAMAUE1xMAAAD7BwIATQYHNhQAAABNBQZhFQAAAE0HAAcAAAAATQYHbhYAAABqBgQF+wcCAE0GBzYUAAAATQUGFBcAAADZBgEAEgAAAGoGBAX7BwIATQYHNhQAAABNBQbdGAAAANkGAgASAAAAagYEBeIFGwD7BgEAbwcZAOIIHQCkCSAAAHzggYwKAACMCwYAnwkDAjAJCE8cAAAAnwYDAjAGBfQZAAAA+wYBAG8HIQDiCCcAjAkBADAJCDoNAAAApAkpAAB8gIJvCioAjAsAAG8MKgCMDQAAnwkFAjAJCC8LAAAApAkpAAB8gIJvCgcAjAsAAG8MBwCMDQAAnwkFAjAJCDsiAAAATQoABwAAAABNCQqaKwAAADAJCPUSAAAApAkuAC2MwMIwCQg5IwAAAG8JLwAwCQiCJAAAAKkJAQAwCQjeJQAAAE0LAAcAAAAATQoL4wEAAAAOCgcApAkxAAB8AIOMCgEAjAsBAIwMAQCfCQQCKwkLAPsKAABNCQoTMgAAAPsLAABNCgucMwAAAFILAQCMDAIAnwoDAowLAACfCQMCMAkIcyYAAACfBgMCMAYFuhoAAACfAgQAggIAADQDBgMIAwkDCgMBAwsCmpmZmZmZ2T8CmpmZmZmZyT8DDAMNAw4DDwMQAxEDEgMTAxQDFQMWAxcDGAMZAxoDGwMcAx0DHgUCGRoDHwUBHAMgAwUEAHzggQMhAyIDIwMkAyUDJgUIDQsiEiMkJSYDBAQAfICCAjMzMzMzM+M/AycDKAMpBC2MwMICZmZmZmZm5j8DKgQAfACDAysDLAMBAgMOLQEYAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAEAAAABAAAAAAAAAAAAAAMAAAQAAAEAAQAAAAAAAQAAAQAAAQAAAAAAAAAAAAEAAAAAAAAABQAAAAAAAAAFAQAAAQAAAAAAAP8AAAMAAAEAAAEAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAEAAAABAAABAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAP8A+AAA5AAQAAAAAAcAAAECACmjAAAApAABAAAAAEBvAgIAvAAAfAMAAACfAAMCpAEFAAAAQEBNBAAkBgAAAE0DBKEHAAAATQIDMwgAAACfAQICpAIFAAAAQEBNBAAkBgAAAE0DBCEJAAAAnwICAk0DAsoKAAAATQQC+AsAAABvBgwAvAQEnA0AAACfBAMCwAUOADAFBBMPAAAAwAUQABIAAQASAAMAEgACADAFBIARAAAAggQCABIDLgQAAABAAy8DMAMxBAAAQEADMgMzAzQDNQM2AzcDOAM5BgADAwYEAy0CAAQBAAEYAAEAAAAAAAEAAAAAAAAAAAEAAAAAAAABAAIAAAAAAAIAAAUAAAAAAC8BAAAAAAXmkW7G8FIhytRVBFKIkhjf0pGz2ygDJoCktVtZAlz2vAvx2ATjdLj8

-- Decompiled by Krnl

local v1 = script:FindFirstAncestor("EzUi")
local v_u_2 = require(v1.Parent.Std.ColorUtils)
local v_u_3 = require(v1.Parent.Roact)
local v_u_4 = v_u_3.createElement
local v5 = v_u_3.PureComponent:extend("Tab")
function v5.init(p6)
	p6:setState({
		["hover"] = false
	})
end
function v5.render(p_u_7)
	-- upvalues: (copy) v_u_2, (copy) v_u_4, (copy) v_u_3
	local v8 = p_u_7.props.active and p_u_7.props.backgroundColor or (p_u_7.state.hover and v_u_2.brightenTo(p_u_7.props.backgroundColor, 0.4) or v_u_2.brightenTo(p_u_7.props.backgroundColor, 0.2))
	return v_u_4("TextButton", {
		["Size"] = p_u_7.props.scaleXBinding:map(function(p9)
			-- upvalues: (copy) p_u_7
			return UDim2.new(p9, -p_u_7.props.paddingX, 1, 0)
		end),
		["BorderSizePixel"] = 0,
		["BackgroundTransparency"] = 0,
		["BackgroundColor3"] = v8,
		["LayoutOrder"] = p_u_7.props.layoutOrder,
		["Text"] = "",
		["AutoButtonColor"] = false,
		[v_u_3.Event.MouseButton1Down] = p_u_7.props.onClick,
		[v_u_3.Event.MouseEnter] = function()
			-- upvalues: (copy) p_u_7
			p_u_7:setState({
				["hover"] = true
			})
		end,
		[v_u_3.Event.MouseLeave] = function()
			-- upvalues: (copy) p_u_7
			p_u_7:setState({
				["hover"] = false
			})
		end
	}, {
		["UICorner"] = v_u_4("UICorner", {
			["CornerRadius"] = UDim.new(0, 6)
		}),
		["Title"] = v_u_4("TextLabel", {
			["BackgroundTransparency"] = 1,
			["Size"] = UDim2.new(0.6, 0, 0.6, 0),
			["Position"] = UDim2.new(0.2, 0, 0.2, 0),
			["Text"] = p_u_7.props.title,
			["Font"] = Enum.Font.LuckiestGuy,
			["LineHeight"] = 0.7,
			["TextScaled"] = true,
			["TextColor3"] = p_u_7.props.active and Color3.new(1, 1, 1) or v_u_2.saturateTo(v_u_2.brightenBy(v8, 2), 0)
		})
	})
end
return v5
