-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMmC2N1cnJlbnRQYWdlCHNldFN0YXRlBGluaXQKdXBkYXRlUGFnZQ1jcmVhdGVFbGVtZW50B3JlcXVpcmUGc2NyaXB0BlBhcmVudAd2aXNpYmxlBHNpemULYW5jaG9yUG9pbnQIcG9zaXRpb24FcGFnZXMFY29sb3IFVURpbTIDbmV3B1ZlY3RvcjIHQ09OU09MRQV0aXRsZQtsYXlvdXRPcmRlchZiYWNrZ3JvdW5kVHJhbnNwYXJlbmN5A1JlZghTRVRUSU5HUwlHQU1FTU9ERVMGQ29sb3IzCHRhYkNvbG9yB2Zyb21SR0IFc3RhdGUGcmVuZGVyB3VubW91bnQJY3JlYXRlUmVmDVB1cmVDb21wb25lbnQDQXBwBmV4dGVuZAVtb3VudARFelVpEUZpbmRGaXJzdEFuY2VzdG9yBVJvYWN0AAYFAQAAAAAI4gMBAMYEAAAwBAMcAAAAALwBACoCAAAAnwEDAYIAAQADAwEFAQADAgAKAwEYAAEAAP8AAAMLAAAAAAQBAQAAAAj7AQAA4gMBADAAAxwAAAAAvAEBKgIAAACfAQMBggABAAMDAQUBAAMCACoEARgAAAEA/wAAAysAAAAADAEEAAAAc/sCAABNAQLKAAAAAKQCAgAAABBApAQEAAAAMEBNAwQkBQAAAJ8CAgLiAw4AqQQBADAEA6AGAAAApAQRAABA8IBvBRIAjAYAAG8HEgCMCAAAnwQFAjAEAw8HAAAApAQUAABAMIFvBRUAbwYVAJ8EAwIwBAMICAAAAKQEEQAAQPCAbwUVAIwGAABvBxUAjAgAAJ8EBQIwBAPbCQAAAP8EAAADAAAA/wUDAAAAAABvBhYAMAYFmhcAAACMBgEAMAYFIBgAAABvBhUAMAYFGhkAAAD7BwAATQYH3RoAAAD7BwEAagcFBv8GAwAAAAAAbwcbADAHBpoXAAAAjAcCADAHBiAYAAAA+wgAAE0HCN0aAAAA+wgCAGoIBgf/BwMAAAAAAG8IHAAwCAeaFwAAAKQIHgAAQNCBjAkAAIwKAACMCwEAnwgEAjAIBxEfAAAAjAgDADAIByAYAAAA+wkAAE0ICd0aAAAA+wkDAGoJBwjFBAUEAQAAADAEA84KAAAApAQhAACA0IGMBfwAjAYoAIwHLwCfBAQCMAQDRAsAAABNBQAYIgAAAE0EBRwMAAAAMAQDHAwAAADZBAAAEgAAADAEA9MNAAAAnwEDAIIBAAAjAwUDBgQAABBAAwcEAAAwQAMIAwkDCgMLAwwDDQMOAwEDBAUIBgcICQoLDA0DDwMQBABA8IACZmZmZmZm7j8DEQQAQDCBAgAAAAAAAOA/AxIDEwMUAxUDFgMXAxgDGQQAQNCBAxoDGwQAgNCBAxwBAQ8dARgAAAAAAAAAAAAAAAEAAAEAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAABAAEAAQAAAQAAAQAAAQAAAAACAAEAAAEAAAEAAAAAAgABAAABAAAAAAAAAAEAAAEAAAAAAADwABMAAAAAAAAAAQAAAAAAAQAAAOYAEAAAAAACAAIAAAAG+wEAAE0AARIAAAAA+wEBAJ8AAgGCAAEAAQMeADIAARgAAAAAAAEzAAAAAAgBAQAAACv7AgAATQEC0AAAAACfAQEC+wMAAE0CA9AAAAAAnwIBAvsEAABNAwTQAAAAAJ8DAQL7BQAATQQF+AEAAABvBgIAvAQEnAMAAACfBAMCwAUEADAFBBMFAAAA2QUBABICAAASAAEAEgACABIAAwAwBQSABgAAAPsGAABNBQbkBwAAAPsHAABNBgfKCAAAAFIHBACfBgICUgcAAJ8FAwLZBgIAEgIAABIABQCCBgIACQMfAyADIQMiBgADAwMdAyMDBQMAAgMFAAEYAAAAAAEAAAABAAAAAQAAAAAAAAEAAAUAAAAAAAAiAAAAAAAAAAAAAQAAAAYAAAAABAAAAQIAEaMAAACkAAEAAAAAQG8CAgC8AAB8AwAAAJ8AAwKkAQUAAABAQE0DACQGAAAATQIDIQcAAACfAQICwAIIABIAAQCCAgIACQMHBAAAAEADJAMlAwYEAABAQAMIAyYGBAEEAQABGAABAAAAAAABAAAAAAAAAgAAAQAAAAAFCg2ou63dThU4ycIvwCIWnStoUO3+Rf5pcYAFY5z//ID44bBDcdCGTw==

-- Decompiled by Krnl

local v1 = script:FindFirstAncestor("EzUi")
local v_u_2 = require(v1.Parent.Roact)
return function(p3)
	-- upvalues: (copy) v_u_2
	local v_u_4 = v_u_2.createRef()
	local v_u_5 = v_u_2.createRef()
	local v_u_6 = v_u_2.createRef()
	local v7 = v_u_2.PureComponent:extend("App")
	function v7.init(p8)
		p8:setState({
			["currentPage"] = nil
		})
	end
	function v7.render(p_u_9)
		-- upvalues: (ref) v_u_2, (copy) v_u_4, (copy) v_u_5, (copy) v_u_6
		local v10 = v_u_2.createElement
		local v11 = require(script.Parent)
		local v13 = {
			["visible"] = true,
			["size"] = UDim2.new(0.95, 0, 0.95, 0),
			["anchorPoint"] = Vector2.new(0.5, 0.5),
			["position"] = UDim2.new(0.5, 0, 0.5, 0),
			["pages"] = {
				{
					["title"] = "CONSOLE",
					["layoutOrder"] = 1,
					["backgroundTransparency"] = 0.5,
					[v_u_2.Ref] = v_u_4
				},
				{
					["title"] = "SETTINGS",
					["layoutOrder"] = 2,
					[v_u_2.Ref] = v_u_5
				},
				{
					["title"] = "GAMEMODES",
					["tabColor"] = Color3.new(0, 0, 1),
					["layoutOrder"] = 3,
					[v_u_2.Ref] = v_u_6
				}
			},
			["color"] = Color3.fromRGB(252, 40, 47),
			["currentPage"] = p_u_9.state.currentPage,
			["updatePage"] = function(p12)
				-- upvalues: (copy) p_u_9
				p_u_9:setState({
					["currentPage"] = p12
				})
			end
		}
		return v10(v11, v13)
	end
	local v_u_14 = v_u_2.mount(v_u_2.createElement(v7), p3)
	return function()
		-- upvalues: (ref) v_u_2, (copy) v_u_14
		v_u_2.unmount(v_u_14)
	end
end
