-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMSCVRyYW5zZm9ybTlObyB2YWxpZCBhaXJEcm9wRGlmZmljdWx0eSB3aXRoIHRoYXQgbmFtZSBjb3VsZCBiZSBmb3VuZC4IVmFsaWRhdGUMQXV0b2NvbXBsZXRlBVBhcnNlEWFpckRyb3BEaWZmaWN1bHR5DFJlZ2lzdGVyVHlwZQRnYW1lEVJlcGxpY2F0ZWRTdG9yYWdlCkdldFNlcnZpY2UHcmVxdWlyZQpDbWRyQ2xpZW50BlNoYXJlZARVdGlsB0FpckRyb3ANQWlyRHJvcENvbnN0cxFUWVBFX0VOVU1fVE9fTkFNRQ9NYWtlRnV6enlGaW5kZXIABgMBAQAAAAT7AQAAUgIAAJ8BAgCCAQAAAAAKAQEYAAAAAAsAAAAABAEAAAAACBwCAACMAwAAtwMCAAIAAACpAQABqQEBAG8CAACCAQMAAQMCAA4DARgAAAAAAAAAAA8AAAAAAQEAAAAAAYIAAgAAABIEARgAEwAAAAACAQAAAAACEwEAAIIBAgAAABYFARgAABcAAAAABQEBAAAABm8DAAD7BAAAvAEA3QEAAACfAQQBggABAAIDBgMHABsAARgAAAAAAAEcAAAAAAcAAAECAC6jAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNBAAOBgAAAE0DBBIHAAAATQIDnggAAACfAQICpAIFAAAAQEBNBACDCQAAAE0DBEkKAAAAnwICAk0DAv0LAAAATQQBPQwAAABSBQMAnwQCAuIFEQDABhIAEgAEADAGBSENAAAAwAYTADAGBXYOAAAAwAYUADAGBasPAAAAwAYVADAGBZsQAAAAwAYWABIABQCCBgIAFwMIBAAAAEADCQMKAwsEAABAQAMMAw0DDgMPAxADEQMSAwEDAwMEAwUFBA0ODxAGAAYBBgIGAwYEBQABAgMEAQABGAABAAAAAAABAAAAAAAAAAABAAAAAAAAAgABAAAAAgEAAAAEAAAEAAAEAAAFAAABAAAAAAWp9c1JSz4+Zpsxp93wBNXomoQREfAkZr6O03bK69cSvXsG2b/SEYUJ

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v2 = require(v1.CmdrClient.Shared.Util)
local v3 = require(v1.AirDrop.AirDropConsts).TYPE_ENUM_TO_NAME
local v_u_4 = v2.MakeFuzzyFinder(v3)
local v_u_9 = {
	["Transform"] = function(p5)
		-- upvalues: (copy) v_u_4
		return v_u_4(p5)
	end,
	["Validate"] = function(p6)
		return #p6 > 0, "No valid airDropDifficulty with that name could be found."
	end,
	["Autocomplete"] = function(p7)
		return p7
	end,
	["Parse"] = function(p8)
		return p8[1]
	end
}
return function(p10)
	-- upvalues: (copy) v_u_9
	p10:RegisterType("airDropDifficulty", v_u_9)
end
