-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMUCVRyYW5zZm9ybS9ObyB2YWxpZCByb2JiZXJ5IHdpdGggdGhhdCBuYW1lIGNvdWxkIGJlIGZvdW5kLghWYWxpZGF0ZQxBdXRvY29tcGxldGUFUGFyc2UHcm9iYmVyeQxSZWdpc3RlclR5cGUJcm9iYmVyaWVzEE1ha2VMaXN0YWJsZVR5cGUEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUKQ21kckNsaWVudAZTaGFyZWQEVXRpbAdSb2JiZXJ5DVJvYmJlcnlDb25zdHMMTElTVF9ST0JCRVJZD01ha2VGdXp6eUZpbmRlcgAGAwEBAAAABPsBAABSAgAAnwECAIIBAAAAAAwBARgAAAAADQAAAAAEAQAAAAAIHAIAAIwDAAC3AwIAAgAAAKkBAAGpAQEAbwIAAIIBAwABAwIAEAMBGAAAAAAAAAAAEQAAAAABAQAAAAABggACAAAAFAQBGAAVAAAAAAIBAAAAAAITAQAAggECAAAAGAUBGAAAGQAAAAAGAQIAAAAPbwMAAPsEAAC8AQDdAQAAAJ8BBAFvAwIA+wUBAE0EBSQDAAAA+wUAAJ8EAgC8AQDdAQAAAJ8BAAGCAAEABAMGAwcDCAMJAB0AARgAAAAAAAEAAAAAAAAAAAEeAAAAAAcAAAECAC+jAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNBAAOBgAAAE0DBBIHAAAATQIDnggAAACfAQICpAIFAAAAQEBNBAAECQAAAE0DBFgKAAAAnwICAk0DAowLAAAATQQBPQwAAABSBQMAnwQCAuIFEQDABhIAEgAEADAGBSENAAAAwAYTADAGBXYOAAAAwAYUADAGBasPAAAAwAYVADAGBZsQAAAAwAYWABIABQASAAEAggYCABcDCgQAAABAAwsDDAMNBAAAQEADDgMPAxADEQMSAxMDFAMBAwMDBAMFBQQNDg8QBgAGAQYCBgMGBAUAAQIDBAEAARgAAQAAAAAAAQAAAAAAAAAAAQAAAAAAAAIAAQAAAAIDAAAABAAABAAABAAABQAAAAEAAAAABajdnL/XXuAqmhn2K1QMJxVee1+jL0dzyAxgiyLoZWYxGTBE9Fftq9g=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.CmdrClient.Shared.Util)
local v3 = require(v1.Robbery.RobberyConsts).LIST_ROBBERY
local v_u_4 = v_u_2.MakeFuzzyFinder(v3)
local v_u_9 = {
	["Transform"] = function(p5)
		-- upvalues: (copy) v_u_4
		return v_u_4(p5)
	end,
	["Validate"] = function(p6)
		return #p6 > 0, "No valid robbery with that name could be found."
	end,
	["Autocomplete"] = function(p7)
		return p7
	end,
	["Parse"] = function(p8)
		return p8[1]
	end
}
return function(p10)
	-- upvalues: (copy) v_u_9, (copy) v_u_2
	p10:RegisterType("robbery", v_u_9)
	p10:RegisterType("robberies", v_u_2.MakeListableType(v_u_9))
end
