-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMiBmFzc2VydAxzZXRtZXRhdGFibGUGUHJpc21zB0xpc3RPYmoGTWFwT2JqCUNvbmRpdGlvbgNuZXcKT25PYmpBZGRlZAxPbk9ialJlbW92ZWQFdGFibGUEZmluZAZyZW1vdmUGaW5zZXJ0CEFkZFByaXNtCGdldFByaXNtBkNGcmFtZQRTaXplB0FkZFBhcnQJQ2FzdFBvaW50C0dldE9iakNvdW50Bkhhc09iagpHZXRPYmpMaXN0BEZpcmUGVXBkYXRlB0Rlc3Ryb3kEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUDU3RkBlNpZ25hbAtSZWdpb25VdGlscwZzY3JpcHQHX19pbmRleAALBAECAAAAKLsBAANSAgAApAEBAAAAAECfAQIB/wIEAAAAAAD7AwAAnj0CAwMAAACkAQMAAAAgQJ8BAwL/AgAAAAAAADACAX4EAAAA/wIAAAAAAAAwAgGEBQAAAP8CAAAAAAAAMAIBQAYAAAAwAAHmBwAAAPsDAQBNAgPvCAAAAJ8CAQIwAgF3CQAAAPsDAQBNAgPvCAAAAJ8CAQIwAgEQCgAAAIIBAgALAwEEAAAAQAMCBAAAIEADAwMEAwUDBgMHAwgDCQAIBwEYAAAAAAABAAAAAAAAAAEAAAABAAAAAQAAAAEAAQAAAAAAAQAAAAAAAgkAAAAABAACAAAAD6QAAgAABACA+wIAAE0BAn4DAAAA+wIBAJ8AAwKkAQUAABAAgPsDAABNAgN+AwAAAFIDAACfAQMAggEAAAYDCgMLBAAEAIADAwMMBAAQAIAAGAABGAAAAAAAAAABAAAAAAAAABkAAAAABQIAAAAAEbsBAQNSAwEApAIBAAAAAECfAgIBTQMAfgIAAACeNAMEAQAAAFIEAQCkAgUAABAwgJ8CAwHZAgAAEgAAABIAAQCCAgIABgMBBAAAAEADAwMKAw0EABAwgAEBFA4BGAAAAAAAAQAAAAAAAAACAAAAFQAAAAAHAgEAAAAM+wUAAE0EBZsAAAAATQUBhQEAAABNBgEvAgAAAJ8EAwC8AgBXAwAAAJ8CAACCAgAABAMPAxADEQMOAB0SARgAAAAAAAAAAAAAAAAeAAAAAAkCAQAAABJNAgB+AAAAAIwFAQAcAwIAjAQBAKgDCgD7BwAATQYHoQEAAACHBwIFUggBAJ8GAwIOBgIAqQcBAIIHAgCLA/b/qQMAAIIDAgACAwMDEwAgEwEYAAABAAAAAQAAAAAAAQEA/QYAIQAAAAADAQAAAAAETQIAhAAAAAAcAQIAggECAAEDBAAqFAEYAAAAACsAAAAABQIAAAAACE0EAEAAAAAAhwMEASoDAgABAAAAqQIAAakCAQCCAgIAAQMFAC0VARgAAAAAAAAAAC4AAAAAAgEAAAAAA00BAIQAAAAAggECAAEDBAAwFgEYAAAAMQAAAAARAgAAAABYTQIAhAAAAABNAwBAAQAAAE0EAOYCAAAA/wUAAAAAAACMCAEAHAYBAIwHAQCoBjUAhwkBCKkKAQBqCgUJUgoEAFILAABSDAkAnwoDAg4KEwCHCwMJRwsRAAAAAICpCwEAagsDCZ40AgUJAAAAUgwCAFINCQCkCwUAABAwgJ8LAwFNCwB3BgAAAFINCQC8CwvdBwAAAJ8LAwFlABkAKwoYAIcLAwlHCxYAAAAAAMYLAABqCwMJHA0CAIwLAQCMDP//qAsJAIcOAg2aDgYACQAAAKQOCQAAIDCAUg8CAFIQDQCfDgMBiwv3/00LABAKAAAAUg0JALwLC90HAAAAnwsDAYsGy/8cCAIAjAYBAIwH//+oBhIAhwkCCIcKBQlHCg4AAAAAgKQKCQAAIDCAUgsCAFIMCACfCgMBxgoAAGoKAwlNCgAQCgAAAFIMCQC8CgrdBwAAAJ8KAwGLBu7/ggABAAsDBAMFAwYDCgMNBAAQMIADCAMXAwwEACAwgAMJADMYARgAAAAAAQABAAEAAAABAQAFAAAAAgAAAAIAAQAAAAAAAAEAAAAAAAABAAAAAgABAAAAAQAAAQAAAAD+BQAAAAAA6hoAAAABAQAAAQAAAAABAAEAAAAAAPsINAAAAAAJAQAAAAAlTQEAhAAAAACMBAEAHAIBAIwDAQCoAggAhwUBBE0GABABAAAAUggFALwGBt0CAAAAnwYDAYsC+P/GAgAAMAIAhAAAAADGAgAAMAIAQAMAAABNAgB3BAAAALwCAlAFAAAAnwICAcYCAAAwAgB3BAAAAE0CABABAAAAvAICUAUAAACfAgIBxgIAADACABABAAAAggABAAYDBAMJAxcDBQMIAxkAWhkBGAAAAQAAAAEBAAAAAAD+BAAAAQAAAQAAAAABAAABAAAAAAEAAAFbAAAAAAUAAAECADmjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CAx8HAAAAnwECAqQCBQAAAEBApAQKAAAAkEBNAwT+CAAAAJ8CAgL/AwUAAAAAADADA24LAAAAwAQMABIAAwASAAEAMAQD7w0AAADABA4AMAQDVw8AAADABBAAEgACADAEA90RAAAAwAQSABIAAgAwBAOhEwAAAMAEFAAwBAPMFQAAAMAEFgAwBANUFwAAAMAEGAAwBANLGQAAAMAEGgAwBAMmGwAAAMAEHAAwBANQHQAAAIIDAgAeAxoEAAAAQAMbAxwDHQQAAEBAAx4DHwMgAyEEAACQQAMiBgADBwYCAw4GAwMSBgQDEwYFAxQGBgMVBgcDFgYIAxgGCQMZCQACAwQFBgcICQEAARgAAQAAAAAAAQAAAAAAAAEAAAAAAAACAAEAAQAAAAAMAAAJAAAAAwAAAAoAAAMAAAMAAAMAACcAAA0BAAAAAAp1SGhAOlnBLEeMAtSAdyCGaAmU+9mkFmqA3CbqkX89wDCylsH80xaT

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.Signal)
local v_u_3 = require(script.RegionUtils)
local v_u_4 = {}
v_u_4.__index = v_u_4
function v_u_4.new(p5)
	-- upvalues: (copy) v_u_4, (copy) v_u_2
	assert(p5)
	local v6 = v_u_4
	local v7 = setmetatable({}, v6)
	v7.Prisms = {}
	v7.ListObj = {}
	v7.MapObj = {}
	v7.Condition = p5
	v7.OnObjAdded = v_u_2.new()
	v7.OnObjRemoved = v_u_2.new()
	return v7
end
function v_u_4.AddPrism(p_u_8, p_u_9)
	assert(p_u_9)
	local v10 = p_u_8.Prisms
	table.insert(v10, p_u_9)
	return function()
		-- upvalues: (copy) p_u_8, (copy) p_u_9
		local v11 = table.find(p_u_8.Prisms, p_u_9)
		return table.remove(p_u_8.Prisms, v11)
	end
end
function v_u_4.AddPart(p12, p13)
	-- upvalues: (copy) v_u_3
	return p12:AddPrism(v_u_3.getPrism(p13.CFrame, p13.Size))
end
function v_u_4.CastPoint(p14, p15)
	-- upvalues: (copy) v_u_3
	local v16 = p14.Prisms
	for v17 = 1, #v16 do
		if v_u_3.CastPoint(v16[v17], p15) then
			return true
		end
	end
	return false
end
function v_u_4.GetObjCount(p18)
	return #p18.ListObj
end
function v_u_4.HasObj(p19, p20)
	return p19.MapObj[p20] == true
end
function v_u_4.GetObjList(p21)
	return p21.ListObj
end
function v_u_4.Update(p22, p23)
	local v24 = p22.ListObj
	local v25 = p22.MapObj
	local v26 = p22.Condition
	local v27 = {}
	for v28 = 1, #p23 do
		local v29 = p23[v28]
		v27[v29] = true
		local v30 = v26(p22, v29)
		if v30 and v25[v29] == nil then
			v25[v29] = true
			table.insert(v24, v29)
			p22.OnObjAdded:Fire(v29)
		elseif not v30 and v25[v29] ~= nil then
			v25[v29] = nil
			for v31 = #v24, 1, -1 do
				if v24[v31] == v29 then
					table.remove(v24, v31)
				end
			end
			p22.OnObjRemoved:Fire(v29)
		end
	end
	for v32 = #v24, 1, -1 do
		local v33 = v24[v32]
		if v27[v33] == nil then
			table.remove(v24, v32)
			v25[v33] = nil
			p22.OnObjRemoved:Fire(v33)
		end
	end
end
function v_u_4.Destroy(p34)
	local v35 = p34.ListObj
	for v36 = 1, #v35 do
		local v37 = v35[v36]
		p34.OnObjRemoved:Fire(v37)
	end
	p34.ListObj = nil
	p34.MapObj = nil
	p34.OnObjAdded:Destroy()
	p34.OnObjAdded = nil
	p34.OnObjRemoved:Destroy()
	p34.OnObjRemoved = nil
end
return v_u_4
