-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgOJAQxzZXRtZXRhdGFibGUDbmV3BV9tYWlkCV9jb250cmFjdBVfY29udHJhY3RBY3Rpb25SZW1vdGUKRmlyZVNlcnZlcgtPYmplY3RMb2NhbAlQbGF5ZXJHdWkKR2V0U3RhdGVJZAllbnVtU3RhdGUGQUNUSVZFJlJlLXJvbGwgZm9yIGEgcmFuZG9tIGNvbnRyYWN0IGZvciAkJXM/BWNvbW1hDFJFUk9MTF9QUklDRQZmb3JtYXQETWFpZAVPblllcwdDb25uZWN0CEdpdmVUYXNrDl9yZXJvbGxDb25maXJtDGdldG1ldGF0YWJsZQxfdXBkYXRlU3RhdGUGYXNzZXJ0Bl9mcmFtZQpCYWNrZ3JvdW5kBEJvZHkGQm90dG9tBkFjdGlvbhBNb3VzZUJ1dHRvbjFEb3duJGdldEFueUNvbnRyYWN0QWN0aXZlVHJhbnNpdGlvblNpZ25hbAhTZXRGcmFtZQtMYXlvdXRPcmRlcg5TZXRMYXlvdXRPcmRlcg9fdXBkYXRlUHJvZ3Jlc3MLdXBkYXRlU3RhdGUQR2V0UHJvZ3Jlc3NWYWx1ZQVWYWx1ZRhHZXRQcm9wZXJ0eUNoYW5nZWRTaWduYWwZR2V0UmVxdWlyZVNlYXNvblBhc3NWYWx1ZQ1HZXRTdGF0ZVZhbHVlGWdldE51bVRpbWVzUmVyb2xsZWRPYmplY3QDb2JqB0NoYW5nZWQYZ2V0U2Vhc29uUGFzc093bmVkU2lnbmFsB0dldE5hbWUETmFtZQlHZXRUZWFtSWQKX3NldFRlYW1JZAxHZXRSZXdhcmRFeHANX3NldFJld2FyZEV4cApHZXRNZXNzYWdlC19zZXRNZXNzYWdlC1NldENvbnRyYWN0BVRpdGxlCVRleHRMYWJlbARUZXh0CFNldFRpdGxlA1RvcAxDb250cmFjdERlc2MGUmV3YXJkBkFtb3VudA1SRVdBUkQ6ICVkIFhQCEVudW1UZWFtBlBvbGljZQhDcmltaW5hbAVlcnJvchJJbnZhbGlkIHRlYW1JZDogJWQPcmJ4YXNzZXRpZDovLyVkBUltYWdlC0dldFByb2dyZXNzCFByb2dyZXNzB1Zpc2libGUPUFJPR1JFU1M6ICVkLyVkB0dldEdvYWwRQ09PTERPV05fRFVSQVRJT04IRGF0ZVRpbWUDbm93DVVuaXhUaW1lc3RhbXASR2V0TGFzdFN0YXRlVXBkYXRlBG1hdGgDbWF4D2Zvcm1hdFJlbWFpbmluZwVSZXRyeRZSRVRSWSBBVkFJTEFCTEUgSU46ICVzEHVwZGF0ZVJldHJ5VGltZXINRG9lc1BsYXllck93bgxFbnVtR2FtZXBhc3MDVklQCkFDQ0VQVEFCTEUGQUNDRVBUCWNhblJlcm9sbAdSRS1ST0xMBkZBSUxFRAdBQk9SVEVECUNPTVBMRVRFRAZDb2xvcjMKVGV4dENvbG9yMwtJbWFnZUNvbG9yMxRHZXRSZXF1aXJlU2Vhc29uUGFzcxdkb2VzUGxheWVyT3duU2Vhc29uUGFzcxFnZXRBY3RpdmVDb250cmFjdBVBTExPV19NVUxUSVBMRV9BQ1RJVkUJT25lQWN0aXZlBWV2ZXJ5D3N0YXRlVXBkYXRlTG9vcA5TZWFzb25QYXNzSWNvbhRTZWFzb25QYXNzVW5sb2NrVGV4dAdEZXN0cm95BGdhbWUHUGxheWVycwpHZXRTZXJ2aWNlC0xvY2FsUGxheWVyEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUDU3RkBUF1ZGlvCEludGVydmFsBlN0cmluZwhTZXR0aW5ncwhSZXNvdXJjZQxTZWFzb25TeXN0ZW0ER2FtZQZTZWFzb24MQ29uZmlybWF0aW9uBk1vZHVsZQ5HYW1lcGFzc1N5c3RlbQhHYW1lcGFzcw1HYW1lcGFzc1V0aWxzC1NlYXNvblV0aWxzDkNvbnRyYWN0Q29uc3RzBnNjcmlwdAZQYXJlbnQOQ29udHJhY3RTeXN0ZW0NQ29udHJhY3RVdGlscwdfX2luZGV4CkNvbnRyYWN0VUkLX19DbGFzc05hbWUAEwQAAgAAABD/AAEAAAAAAPsDAACePQAEAwAAAFICAACkAQEAAAAAQJ8BAwH7AgEATQEC7wIAAACfAQECMAEAwQMAAACCAAIABAMBBAAAAEADAgMDABcCARgAAAEAAAAAAAACAAAAAAACGAAAAAADAAEAAAAJ+wIAAE0BAuIAAAAATQABmgEAAAC8AABrAgAAAJ8AAgGCAAEAAwMEAwUDBgAsAAEYAAAAAAAAAAABLQAAAAAGAAYAAAcAAAEDASACP/sBAABNAAHRAAAAAPsCAQBNAQKZAQAAAG8CAgCfAAMB+wECAE0AAeIDAAAAvAAAaQQAAACfAAIC+wMDAE0CA6oFAAAATQECYQYAAACaACIAAQAAAPsBBABNAAHvBwAAAG8BCAD7BAUATQME5AkAAAD7BQMATQQFWAoAAACfAwIAvAEBjQsAAACfAQAAnwAAAk0BAHYMAAAATQMA3A0AAADZBQAAEgICALwDA8cOAAAAnwMDALwBAf0PAAAAnwEAAfsCAgBNAQLiAwAAADAAAQYQAAAAggABAPsCAgBNAQLiAwAAAE0AAZoRAAAAvAAAaxIAAACfAAIBggABABMDBwMIAgAAYDKfvvZBAwQDCQMKAwsDAgMMAw0DDgMPAxADEQMSAxMDFAMFAwYBASUAARgAAAAAAAAAAAEAAAAAAAAAAAAAAAACAAABAAAAAAAAAAAAAP8DAAAAAAAAAAAAAAADAAAAAAACAAAAAAAAAAImAAAAAAQAAQAAAB37AQAAuzwBAqQAAQAAAABAnwACAkcAAgAAAACAggABAPsCAABNAQLiAgAAALs8AQKkAAEAAAAAQJ8AAgJHAAIAAAAAgIIAAQD7AAAA+wMAAE0CA+ICAAAAvAICaQMAAACfAgIAvAAAxQQAAACfAAABggABAAUDFQQAAABAAwQDCQMWADUAARgAAAAAAAAAAQIAAAAAAAAAAAECAAAAAAAAAAAAATYAAAAACgIGAAAAQkcBAgAAAACAqQMAAakDAQC7AQMCpAIBAAAAAECfAgIBTQQAyQIAAABWAwQAuwEDAqQCAQAAAABAnwICATABAMkCAAAATQIAwQMAAABNBADJAgAAALwCAv0EAAAAnwIDAU0CAMEDAAAATQkAyQIAAABNCAntBQAAAE0HCGcGAAAATQYHEwcAAABNBQYCCAAAAE0EBWEJAAAA2QYAABICAAASAgEAEgAAABICAgASAgMAEgIEALwEBMcKAAAAnwQDALwCAv0EAAAAnwIAAU0CAMEDAAAA+wUFAE0EBZwLAAAAnwQBAtkGAQASAAAAvAQExwoAAACfBAMAvAIC/QQAAACfAgABggABAAwDFwQAAABAAxgDAwMTAxkDGgMbAxwDHQMSAx4CAgMfHwEYAAAAAAAAAAABAAAAAAAAAQABAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAJIAAAAAAEAgAAAAANRwECAAAAAICpAwABqQMBALsBAwKkAgEAAAAAQJ8CAgFNAgDJAgAAADABAgADAAAAggABAAQDFwQAAABAAxgDIAA/IQEYAAAAAAAAAAABAAAAAUAAAAAAAgABAAAABfsAAAC8AAAQAAAAAJ8AAgGCAAEAAQMiAEYAARgAAAAAAUcAAAAABAABAAAAC/sAAAD7AwAATQID4gAAAAC8AgJpAQAAAJ8CAgC8AADFAgAAAJ8AAAGCAAEAAwMEAwkDFgBLIwEYAAAAAAAAAAAAAAFMAAAAAAUBAgAAAA/7AQAA8QACAAEAAACCAAEA+wEBAPsEAQBNAwTiAAAAALwDA2kBAAAAnwMCALwBAcUCAAAAnwEAAYIAAQADAwQDCQMWAFQAARgJAAAB9gAAAAAAAAAAAA1MAAAAAAkCAwAAAJEBTQQA4gAAAABWAwQAuwEDAqQCAgAAABBAnwICATABAOIAAAAATQIAwQMAAABNBADiAAAAALwEBH4EAAAAnwQCAm8GBQC8BASUBgAAAJ8EAwLZBgAAEgAAALwEBMcHAAAAnwQDALwCAv0IAAAAnwIAAbwCABAJAAAAnwICAdkCAQASAAAATQMAwQMAAABNBQDiAAAAALwFBfIKAAAAnwUCAm8HBQC8BQWUBgAAAJ8FAwJSBwIAvAUFxwcAAACfBQMAvAMD/QgAAACfAwABTQMAwQMAAABNBQDiAAAAALwFBcULAAAAnwUCAm8HBQC8BQWUBgAAAJ8FAwJSBwIAvAUFxwcAAACfBQMAvAMD/QgAAACfAwABTQMAwQMAAAD7BwAATQYHjwwAAABNCADiAAAAAE0HCBMNAAAAnwYCAk0FBoUOAAAAUgcCALwFBccHAAAAnwUDALwDA/0IAAAAnwMAAU0FAOIAAAAAvAUFaQ8AAACfBQIAvAMAxRAAAACfAwABTQMAwQMAAAD7BgEATQUGvBEAAACfBQEC2QcCABICAgASAAAAvAUFxwcAAACfBQMAvAMD/QgAAACfAwABTQMAyRIAAABNBADiAAAAALwEBFYTAAAAnwQCAjAEA7oUAAAATQUA4gAAAAC8BQVEFQAAAJ8FAgC8AwCGFgAAAJ8DAAFNBQDiAAAAALwFBbcXAAAAnwUCALwDAKYYAAAAnwMAAU0FAOIAAAAAvAUFihkAAACfBQIAvAMAexoAAACfAwABggABABsDBAMXBAAAEEADAwMkAyUDJgMSAxMDIgMnAygDKQMqAysDCQMWAywDGAMtAy4DLwMwAzEDMgMzAzQDBgcIQzUBGAAAAAAAAAABAAEAAAAAAAAAAAAAAAAAAAAAAAADAAACAAMAAQAAAAAAAAAAAAAAAP8AAAMAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAD6AAAAAAAAAAgAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAACAAAAAAAAAAFEAAAAAAYCAAAAAAtNBQDJAAAAAE0EBe0BAAAATQMEugIAAABNAgOaAwAAADABAvUEAAAAggABAAUDGAMZAzYDNwM4AGE5ARgAAAAAAAAAAAAAAWIAAAAABwIAAAAADU0CAMkAAAAATQYC7QEAAABNBQZnAgAAAE0EBZgDAAAATQMEvQQAAAAwAQP1BQAAAIIAAQAGAxgDGQMaAzoDOwM4AGQ0ARgAAAEAAAAAAAAAAQABZQAAAAAIAgAAAAcAAAEDBA4CFE0CAMkAAAAATQcC7QEAAABNBgdnAgAAAE0FBhMDAAAATQQFPwQAAABNAwQrBQAAAG8EBgBSBgEAvAQEjQcAAACfBAMCMAQD9QgAAACCAAEACQMYAxkDGgMbAzwDPQM+Aw8DOABpMgEYAAABAAAAAAAAAAAAAQAAAAAAAAFqAAAAAAcCAQAACwAAAgMEFwIDBCECJ8YCAAD7BQAATQQFTAAAAABNAwSyAQAAAJoBAwADAAAAbwICAGUAEQD7BQAATQQFTAAAAABNAwR1AwAAAJoBAwADAAAAbwIEAGUACACkAwYAAABQQG8EBwBSBgEAvAQEjQgAAACfBAMAnwMAAU0EAMkJAAAATQME7QoAAABvBAsAUgYCALwEBI0IAAAAnwQDAjAEA6kMAAAAggABAA0DPwNAAgAAcMSUL/ZBA0ECAADAzokv9kEDQgQAAFBAA0MDDwMYAxkDRANFAG4wARgAAQAAAAAAAAEAAQAAAAAAAAEAAgAAAAAAAAACAAAAAAAAAAAAAAFvAAAAAAoBAQAABwAAAQMFMgI4xgEAAE0CAOIAAAAAvAICaQEAAACfAgIC+wUAAE0EBaoCAAAATQMEYQMAAACaAgcAAwAAAE0CAOIAAAAAvAICAwQAAACfAgICUgECAE0CAMkFAAAATQUC7QYAAABNBAVnBwAAAE0DBBMIAAAATQQD5AkAAABHAQIAAAAAgKkFAAGpBQEAMAUEgAoAAABHARMAAAAAAE0EA+QJAAAAbwULAE0HAOIAAAAAvAcHAwQAAACfBwICTQgA4gAAAAC8CAgVDAAAAJ8IAgC8BQWNDQAAAJ8FAAIwBQT1DgAAAIIAAQAPAwQDCQMKAwsDRgMYAxkDGgMbA0cDSANJA0oDDwM4AHkiARgAAQAAAAAAAAAAAAAAAQAAAAAAAwABAAAAAAABAAAAAAAAAAEAAQAAAAAAAAAAAAAAAAAAAAAAAnoAAAAACAAEAAAHAAABAwUgAib7AQAATQABQwAAAACkAwMAAAgQgJ8DAQJNAgO3BAAAAPsEAQBNAwTiBQAAALwDA30GAAAAnwMCAiYBAgMmAwABgRIDBAcAAABvBAcApAIKAAAkgICfAgMC+wQCAE0DBPELAAAAUgQCAJ8DAgL7BQMATQQFYgwAAABvBQ0AUgcDALwFBY0OAAAAnwUDAjAFBPUPAAAAggABABADSwNMA00EAAgQgANOAwQDTwIAAAAAAAAAAANQA1EEACSAgANSA1MDVAMPAzgAwAFVARgAAAABAAAAAAAAAAAAAAACAAAAAAAAAQAAAAABAAAAAAAAAAAAAcEAAAAAEwIJAAAHAAABAwleArgCuzwAA1IDAACkAgEAAAAAQJ8CAgJHAgIAAAAAgIIAAQDGAgAAxgMAAPsFAABNBAUbAgAAAPsHAQBNBgeNAwAAAE0FBskEAAAAnwQCAvsHAgBNBgeqBQAAAE0FBgkGAAAAmgEEAAUAAABvAgcAbwMIAGUALQD7BwIATQYHqgUAAABNBQZhCQAAAJoBDgAFAAAA+wYDAE0FBtkKAAAATQcA4gsAAABNBgcTDAAAAFIHBACfBQMCDgUDAG8CDQBvAw4AZQAZAPsHAgBNBgeqBQAAAE0FBrMPAAAAmgECAAUAAABlABEA+wcCAE0GB6oFAAAATQUGhxAAAACaAQIABQAAAGUACQD7BwIATQYHqgUAAABNBQb/EQAAAJoBAwAFAAAAbwINAG8DEQBNBQDJEgAAAE0IBe0TAAAATQcIZxQAAABNBgeYFQAAAE0JBe0TAAAATQgJZxQAAABNBwgTFgAAAA4CRAAOA0MATQgHAhcAAABvCRgAUgsCALwJCY0ZAAAAnwkDAjAJCKkaAAAATQkHAhcAAABNCAmaGwAAADADCPUcAAAA+woCAE0JCqoFAAAATQgJYQkAAACaARgACAAAAE0JBwIXAAAATQgJmhsAAACkCR8AAHjQgYwKAQCMCwAAjAwAAJ8JBAIwCQhzIAAAAE0IBwIXAAAApAkfAAB40IGMCgEAjAsAAIwMAACfCQQCMAkIACEAAABlABYATQkHAhcAAABNCAmaGwAAAKQJHwAAeNCBjAoBAIwLAQCMDAEAnwkEAjAJCHMgAAAATQgHAhcAAACkCR8AAHjQgYwKAQCMCwEAjAwBAJ8JBAIwCQgAIQAAAE0IAOILAAAAvAgIwiIAAACfCAIC+woEAE0JCpcjAAAA+woFAJ8JAgJSCggADgoBAFYKCQD7DAYATQsMsSQAAABNDADiCwAAALwMDEQlAAAAnwwCAJ8LAAKpDAAARwsUAAAAAACpDAAATQ0A4gsAAADxCw8ADQAAAKkMAAD7DwIATQ4PqgUAAABNDQ7/EQAAAPEBBwANAAAAVgwKAA4MBAD7DgIATQ0ODSYAAABWDA0ATQ0HpycAAAAwDA2AKAAAAPsQAgBNDxCqBQAAAE0OD4cQAAAA8QEJAA4AAACpDQAA+xACAE0PEKoFAAAATQ4Psw8AAACaAQIADgAAAFYNDABNDgdiKQAAADANDoAoAAAADg0VANkOAAASAgIAEgAAABICBwASAAcATQ8AwSoAAAD7EQgATRARxCsAAACMEQEAnxACAlISDgC8EBDHLAAAAJ8QAwIwEA+8LQAAAFIPDgCfDwEBZQAFAE0OAMEqAAAAxg8AADAPDrwtAAAAqQ4AAPsRAgBNEBGqBQAAAE0PEIcQAAAA8QEgAA8AAACpDgAA+xECAE0QEaoFAAAATQ8Qsw8AAADxARgADwAAAFYODAAODhUAVg4KAA4OEwCpDwAA+xICAE0REqoFAAAATRARYQkAAACaAQsAEAAAAPsRAwBNEBHZCgAAAE0SAOILAAAATRESEwwAAABSEgQAnxADAlYPEABWDg8ATQ8HAhcAAAAwDg+AKAAAAE0PBr0uAAAAVhAKADAQD4AoAAAATQ8GGy8AAAAwCg+AKAAAAE0PB7UwAAAAMAoPgCgAAAC8DwAQMQAAAJ8PAgGCAAEAMgMVBAAAAEADVgNXA1gDCgNZAgAAYKeJL/ZBA1oDCwNbAwQDKgIAABC5iS/2QQNcA10DXgNfAxgDGQMaAzoDGwMcA0QDDwNFAzcDOANgAwIEAHjQgQNhA2IDYwNkA2UDLwNmA2cDSANTAwMDaAMSA2kDOwNqA2sDIgEPhgEWARgAAAAAAAAAAQIBAQAAAAAAAAAAAQAAAAAAAAIBAAEAAAAAAAAAAAAAAAAAAAAAAgEAAQAAAAAAAAACAAAAAAAAAAIAAAAAAAACAQMAAQAAAAAAAQAAAAAAAQABAAAAAAAAAAABAAAAAAABAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAACAAAAAAAAAAAAAAABAAAAAAAAAAAABQAAAAABAAAAAAEAAAIAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAABAAEAAAABAAAAAgAAAAAAAAAAAAAAAAAAAQEAAAADAQAAAAAIAAAAAAAAAAAAAAAAAQAAAgAAAAADAAAAAAAAAAAAAAAAAAAAAQABAAEAAAAAAAAAAAAAAAAAAAAAAAACAAAAAgAAAAABAAAAAQAAAAIAAAGHAAAAAAQBAAAAABpNAwDBAAAAAEcDAgAAAACAqQIAAakCAQC7AQICpAECAAAAEECfAQIBTQEAwQAAAAC8AQFQAwAAAJ8BAgHGAQAAMAEAwQAAAACBPQAFBAAAAFICAABvAwQApAEGAAAAUECfAQMBggABAAcDAwMXBAAAEEADbAADAQQAAFBAANsBbAEYAAAAAAAAAAAAAAEAAAAAAQAAAQAAAAAAAAHcAAAAABMAAAECALcBowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAk0BADEEAAAApAIBAAAAAEBvBAUAvAICFgMAAACfAgMCpAMHAAAAYEBNBQKhCAAAAE0EBXYJAAAAnwMCAqQEBwAAAGBATQYCoQgAAABNBQbSCgAAAJ8EAgKkBQcAAABgQE0HAqEIAAAATQYHrAsAAACfBQICpAYHAAAAYEBNCAKhCAAAAE0HCKEMAAAAnwYCAqQHBwAAAGBATQkCYg4AAABNCAnKDQAAAJ8HAgKkCAcAAABgQE0LAr0QAAAATQoLhhEAAABNCQpLDwAAAJ8IAgKkCQcAAABgQE0LAkATAAAATQoLhBIAAACfCQICpAoHAAAAYEBNDQK9EAAAAE0MDb0VAAAATQsMjhQAAACfCgICpAsHAAAAYEBNDgK9EAAAAE0NDr0VAAAATQwNPhYAAACfCwICpAwHAAAAYEBNDwK9EAAAAE0OD4YRAAAATQ0O8hcAAACfDAICpA0HAAAAYECkEBoAAACQQU0PECQbAAAATQ4PqRgAAACfDQICpA4HAAAAYECkERoAAACQQU0QESQbAAAATQ8QhBwAAACfDgICpA8HAAAAYECkEhoAAACQQU0REiQbAAAATRARqB0AAACfDwIC/xAFAAAAAAAwEBBuHgAAAG8RHwAwERDlIAAAAMARIQASABAAEgADADAREO8iAAAAwBEjABIABAASAAEAEgANABIACQASAAYAEgAOADAREA4kAAAAwBElADARED8mAAAAwBEnABIADwASAAgAEgABADAREOgoAAAAwBEpADAREJ4qAAAAwBErADAREHssAAAAwBEtADAREKYuAAAAwBEvABIABwAwERCGMAAAAMARMQASAA0AMBEQEDIAAADAETMAEgAKABIACwASAA0AEgAPABIACAASAAEAEgAOABIADAASAAUAMBEQxTQAAADAETUAMBEQUDYAAACCEAIANwNtBAAAAEADbgNvA3ADcQNyBAAAYEADcwMQA3QDdQN2A3cDeAN5A3oDewN8A30DfgN/A4ABA4EBA4IBA4MBBAAAkEEDhAEDhQEDhgEDhwEDiAEDiQEGAAMCBgQDHwYFAyEGCQM1BgoDOQYLAzQGDAMyBg0DMAYOAyIGEAMWBhEDbAsABAUJCgsMDQ4QEQEAARgAAQAAAAAAAQABAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAAACAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAAACAAEAAQAAAQAAAAAIAAAAAAAAAAAgAAAEAAAAAAAeAAADAAAFAAAFAAAACwAAAA0AAAAAAAAAAAAAAFUAAAcBAAAAABJGIgYkgvVibXTmbLANvjZvRkTGdq5WsaIipUNkx+0s9pPbjm7G3d4z

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players").LocalPlayer
local v2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v2.Std.Maid)
local v_u_4 = require(v2.Std.Audio)
local v_u_5 = require(v2.Std.Interval)
local v_u_6 = require(v2.Std.String)
local v_u_7 = require(v2.Resource.Settings)
local v_u_8 = require(v2.Game.Season.SeasonSystem)
local v_u_9 = require(v2.Module.Confirmation)
local v_u_10 = require(v2.Game.Gamepass.GamepassSystem)
local v_u_11 = require(v2.Game.Gamepass.GamepassUtils)
local v_u_12 = require(v2.Game.Season.SeasonUtils)
local v_u_13 = require(script.Parent.ContractConsts)
local v_u_14 = require(script.Parent.ContractSystem)
local v_u_15 = require(script.Parent.ContractUtils)
local v_u_16 = {}
v_u_16.__index = v_u_16
v_u_16.__ClassName = "ContractUI"
function v_u_16.new()
	-- upvalues: (copy) v_u_16, (copy) v_u_3
	local v17 = {}
	local v18 = v_u_16
	setmetatable(v17, v18)
	v17._maid = v_u_3.new()
	return v17
end
function v_u_16.SetFrame(p_u_19, p20)
	-- upvalues: (copy) v_u_4, (copy) v_u_1, (copy) v_u_13, (copy) v_u_9, (copy) v_u_6, (copy) v_u_14
	local v21 = p20 ~= nil
	assert(v21)
	local v22 = not p_u_19._frame
	assert(v22)
	p_u_19._frame = p20
	p_u_19._maid:GiveTask(p_u_19._frame)
	p_u_19._maid:GiveTask(p_u_19._frame.Background.Body.Bottom.Action.MouseButton1Down:Connect(function()
		-- upvalues: (ref) v_u_4, (ref) v_u_1, (copy) p_u_19, (ref) v_u_13, (ref) v_u_9, (ref) v_u_6
		v_u_4.ObjectLocal(v_u_1.PlayerGui, 6105461542)
		if p_u_19._contract:GetStateId() == v_u_13.enumState.ACTIVE then
			local v23 = v_u_9.new(("Re-roll for a random contract for $%s?"):format(v_u_6.comma(v_u_13.REROLL_PRICE)))
			v23.Maid:GiveTask(v23.OnYes:Connect(function()
				-- upvalues: (ref) p_u_19
				p_u_19._contract._contractActionRemote:FireServer()
			end))
			p_u_19._contract._rerollConfirm = v23
		else
			p_u_19._contract._contractActionRemote:FireServer()
		end
	end))
	p_u_19._maid:GiveTask(v_u_14.getAnyContractActiveTransitionSignal():Connect(function()
		-- upvalues: (copy) p_u_19
		local v24 = p_u_19
		if getmetatable(v24) == nil then
			return
		else
			local v25 = p_u_19._contract
			if getmetatable(v25) ~= nil then
				p_u_19:_updateState(p_u_19._contract:GetStateId())
			end
		end
	end))
end
function v_u_16.SetLayoutOrder(p26, p27)
	local v28 = p27 ~= nil
	assert(v28)
	p26._frame.LayoutOrder = p27
end
function v_u_16.SetContract(p_u_29, p30)
	-- upvalues: (copy) v_u_15, (copy) v_u_8, (copy) v_u_1
	local v31 = not p_u_29._contract
	assert(v31)
	p_u_29._contract = p30
	p_u_29._maid:GiveTask(p_u_29._contract:GetProgressValue():GetPropertyChangedSignal("Value"):Connect(function()
		-- upvalues: (copy) p_u_29
		p_u_29:_updateProgress()
	end))
	p_u_29:_updateProgress()
	local function v32()
		-- upvalues: (copy) p_u_29
		p_u_29:_updateState(p_u_29._contract:GetStateId())
	end
	p_u_29._maid:GiveTask(p_u_29._contract:GetRequireSeasonPassValue():GetPropertyChangedSignal("Value"):Connect(v32))
	p_u_29._maid:GiveTask(p_u_29._contract:GetStateValue():GetPropertyChangedSignal("Value"):Connect(v32))
	p_u_29._maid:GiveTask(v_u_15.getNumTimesRerolledObject(p_u_29._contract.obj).Changed:Connect(v32))
	p_u_29:_updateState(p_u_29._contract:GetStateId())
	p_u_29._maid:GiveTask(v_u_8.getSeasonPassOwnedSignal():Connect(function(p33)
		-- upvalues: (ref) v_u_1, (copy) p_u_29
		if p33 == v_u_1 then
			p_u_29:_updateState(p_u_29._contract:GetStateId())
		end
	end))
	p_u_29._frame.Name = p_u_29._contract:GetName()
	p_u_29:_setTeamId(p_u_29._contract:GetTeamId())
	p_u_29:_setRewardExp(p_u_29._contract:GetRewardExp())
	p_u_29:_setMessage(p_u_29._contract:GetMessage())
end
function v_u_16.SetTitle(p34, p35)
	p34._frame.Background.Title.TextLabel.Text = p35
end
function v_u_16._setMessage(p36, p37)
	p36._frame.Background.Body.Top.ContractDesc.Text = p37
end
function v_u_16._setRewardExp(p38, p39)
	p38._frame.Background.Body.Bottom.Reward.Amount.Text = ("REWARD: %d XP"):format(p39)
end
function v_u_16._setTeamId(p40, p41)
	-- upvalues: (copy) v_u_7
	local v42 = nil
	if p41 == v_u_7.EnumTeam.Police then
		v42 = 5955472455
	elseif p41 == v_u_7.EnumTeam.Criminal then
		v42 = 5955427564
	else
		error(("Invalid teamId: %d"):format(p41))
	end
	p40._frame.Background.Image = ("rbxassetid://%d"):format(v42)
end
function v_u_16._updateProgress(p43)
	-- upvalues: (copy) v_u_13
	local v44
	if p43._contract:GetStateId() == v_u_13.enumState.ACTIVE then
		v44 = p43._contract:GetProgress()
	else
		v44 = nil
	end
	local v45 = p43._frame.Background.Body.Bottom
	v45.Progress.Visible = v44 ~= nil
	if v44 ~= nil then
		v45.Progress.Text = ("PROGRESS: %d/%d"):format(p43._contract:GetProgress(), p43._contract:GetGoal())
	end
end
function v_u_16._updateState(p_u_46, p47)
	-- upvalues: (copy) v_u_10, (copy) v_u_11, (copy) v_u_13, (copy) v_u_15, (copy) v_u_8, (copy) v_u_1, (copy) v_u_14, (copy) v_u_12, (copy) v_u_5
	if getmetatable(p_u_46) ~= nil then
		local v48 = nil
		local v49 = nil
		local v50 = v_u_10.DoesPlayerOwn(v_u_11.EnumGamepass.VIP)
		if p47 == v_u_13.enumState.ACCEPTABLE then
			v48 = 5955426934
			v49 = "ACCEPT"
		elseif p47 == v_u_13.enumState.ACTIVE and v_u_15.canReroll(p_u_46._contract.obj, v50) then
			v48 = 5955427217
			v49 = "RE-ROLL"
		elseif p47 ~= v_u_13.enumState.FAILED and (p47 ~= v_u_13.enumState.ABORTED and p47 == v_u_13.enumState.COMPLETED) then
			v48 = 5955427217
			v49 = "COMPLETED"
		end
		local v51 = p_u_46._frame
		local v52 = v51.Background.Body.Top
		local v_u_53 = v51.Background.Body.Bottom
		if v48 and v49 then
			v_u_53.Action.Image = ("rbxassetid://%d"):format(v48)
			v_u_53.Action.TextLabel.Text = v49
			if p47 == v_u_13.enumState.ACTIVE then
				v_u_53.Action.TextLabel.TextColor3 = Color3.new(1, 0, 0)
				v_u_53.Action.ImageColor3 = Color3.new(1, 0, 0)
			else
				v_u_53.Action.TextLabel.TextColor3 = Color3.new(1, 1, 1)
				v_u_53.Action.ImageColor3 = Color3.new(1, 1, 1)
			end
		end
		local v54 = p_u_46._contract:GetRequireSeasonPass()
		local v55 = v_u_8.doesPlayerOwnSeasonPass(v_u_1)
		if v54 then
			v54 = not v55
		end
		local v56 = v_u_14.getActiveContract(p_u_46._contract:GetTeamId())
		local v57 = v56 ~= nil and (v56 ~= p_u_46._contract and p47 ~= v_u_13.enumState.COMPLETED) and not v54
		if v57 then
			v57 = not v_u_13.ALLOW_MULTIPLE_ACTIVE
		end
		v_u_53.OneActive.Visible = v57
		local v58
		if p47 == v_u_13.enumState.ABORTED or p47 == v_u_13.enumState.FAILED then
			v58 = not v57
		else
			v58 = false
		end
		v_u_53.Retry.Visible = v58
		if v58 then
			local function v62()
				-- upvalues: (ref) v_u_13, (copy) p_u_46, (ref) v_u_12, (copy) v_u_53
				local v59 = v_u_13.COOLDOWN_DURATION - (DateTime.now().UnixTimestamp - p_u_46._contract:GetLastStateUpdate())
				local v60 = math.max(v59, 0)
				local v61 = v_u_12.formatRemaining(v60)
				v_u_53.Retry.Text = ("RETRY AVAILABLE IN: %s"):format(v61)
			end
			p_u_46._maid.stateUpdateLoop = v_u_5.every(1):Connect(v62)
			v62()
		else
			p_u_46._maid.stateUpdateLoop = nil
		end
		local v63 = p47 ~= v_u_13.enumState.ABORTED and p47 ~= v_u_13.enumState.FAILED and not (v57 or v54)
		if v63 then
			local v64
			if p47 == v_u_13.enumState.ACTIVE then
				v64 = not v_u_15.canReroll(p_u_46._contract.obj, v50)
			else
				v64 = false
			end
			v63 = not v64
		end
		v_u_53.Action.Visible = v63
		v52.ContractDesc.Visible = not v54
		v52.SeasonPassIcon.Visible = v54
		v_u_53.SeasonPassUnlockText.Visible = v54
		p_u_46:_updateProgress()
	end
end
function v_u_16.Destroy(p65)
	local v66 = p65._maid ~= nil
	assert(v66)
	p65._maid:Destroy()
	p65._maid = nil
	setmetatable(p65, nil)
end
return v_u_16
