-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMYB2NoZWNrZWQIc2V0U3RhdGUEaW5pdAlvbkNoZWNrZWQNY3JlYXRlRWxlbWVudARzaXplCHBvc2l0aW9uBXZhbHVlBVVEaW0yA25ldwVzdGF0ZQZyZW5kZXIHdW5tb3VudAlDb21wb25lbnQDQXBwBmV4dGVuZAdyZXF1aXJlCENoZWNrYm94BnNjcmlwdAZQYXJlbnQFbW91bnQERXpVaRFGaW5kRmlyc3RBbmNlc3RvcgVSb2FjdAAGBQEAAAAACOIDAQCpBAAAMAQDAgAAAAC8AQAqAgAAAJ8BAwGCAAEAAwMBBQEAAwIACAMBGAABAAD/AAADCQAAAAAEAQEAAAAI+wEAAOIDAQAwAAMCAAAAALwBASoCAAAAnwEDAYIAAQADAwEFAQADAgASBAEYAAABAP8AAAMTAAAAAAkBAgAAACP7AgAATQECygAAAAD7AgEA4gMFAKQECAAAHGCAjAUAAIwGHgCMBwAAjAgeAJ8EBQIwBAMPAQAAAKQECAAAHGCAbwUJAIwGAABvBwoAjAgAAJ8EBQIwBAPbAgAAAE0FABgLAAAATQQFAgwAAAAwBAPMAwAAANkEAAASAAAAMAQDYAQAAACfAQMAggEAAA0DBQMGAwcDCAMEBQQBAgMEAwkDCgQAHGCAAgAAAAAAANA/AgAAAAAAAOA/AwsDAQEBDQwBGAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAQAAAPwADgAAAAACAAIAAAAG+wEAAE0AARIAAAAA+wEBAJ8AAgGCAAEAAQMNABsAARgAAAAAAAEcAAAAAAYBAQAAACb7AgAATQECiAAAAABvAwEAvAEBnAIAAACfAQMCpAIEAAAAMECkBQcAAABgQE0EBSQIAAAATQME8AUAAACfAgICwAMJADADARMKAAAA2QMBABICAAASAAIAMAMBgAsAAAD7BAAATQME5AwAAAD7BQAATQQFyg0AAABSBQEAnwQCAlIFAACfAwMC2QQCABICAAASAAMAggQCAA4DDgMPAxADEQQAADBAAxIDEwQAAGBAAxQGAAMDAwwDFQMFAwACAwUAARgAAAAAAAAAAQAAAAAAAAAAAQAABQAAAAANAAAAAAAAAAAAAQAAAAYAAAAABAAAAQIAEaMAAACkAAEAAAAAQG8CAgC8AAB8AwAAAJ8AAwKkAQUAAABAQE0DACQGAAAATQIDIQcAAACfAQICwAIIABIAAQCCAgIACQMTBAAAAEADFgMXAxEEAABAQAMUAxgGBAEEAQABGAABAAAAAAABAAAAAAAAAgAAAQAAAAAFG7CZYDfvaf0pdPP0mln+oFFpRfX2ltxzOfB9Gu4kJuSVzqykGbcYHA==

-- Decompiled by Krnl

local v1 = script:FindFirstAncestor("EzUi")
local v_u_2 = require(v1.Parent.Roact)
return function(p3)
	-- upvalues: (copy) v_u_2
	local v4 = v_u_2.Component:extend("App")
	local v_u_5 = require(script.Parent.Checkbox)
	function v4.init(p6)
		p6:setState({
			["checked"] = false
		})
	end
	function v4.render(p_u_7)
		-- upvalues: (ref) v_u_2, (copy) v_u_5
		return v_u_2.createElement(v_u_5, {
			["size"] = UDim2.new(0, 30, 0, 30),
			["position"] = UDim2.new(0.25, 0, 0.5, 0),
			["value"] = p_u_7.state.checked,
			["onChecked"] = function(p8)
				-- upvalues: (copy) p_u_7
				p_u_7:setState({
					["checked"] = p8
				})
			end
		})
	end
	local v_u_9 = v_u_2.mount(v_u_2.createElement(v4), p3)
	return function()
		-- upvalues: (ref) v_u_2, (copy) v_u_9
		v_u_2.unmount(v_u_9)
	end
end
