-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMiBHBvczABWAFZBHBvczEEbWF0aARzcXJ0BVVEaW0yA25ldwVhdGFuMgNkZWcJZnJvbVNjYWxlC2FzcGVjdFJhdGlvBXdpZHRoCWxpbmVDb2xvcgxqb2luQmluZGluZ3MLcG9zMEJpbmRpbmcLcG9zMUJpbmRpbmcFRnJhbWULQW5jaG9yUG9pbnQQQmFja2dyb3VuZENvbG9yMw9Cb3JkZXJTaXplUGl4ZWwEU2l6ZQhSb3RhdGlvbghQb3NpdGlvbgdWZWN0b3IyBkNvbG9yMwNtYXAGc2NyaXB0BEV6VWkRRmluZEZpcnN0QW5jZXN0b3IHcmVxdWlyZQZQYXJlbnQFUm9hY3QNY3JlYXRlRWxlbWVudAAFDQECAAAWAwAEBQEEBwMCAgcDBgIHBQoCBwUOAiVNAwC3AAAAAE0BA3kBAAAATQMAtwAAAABNAgN4AgAAAE0FAJ4DAAAATQMFeQEAAABNBQCeAwAAAE0EBXgCAAAAJgUDASYGBAIJCwYG+wwAAOwKCwz7CwAA7AkKCwkKBQVDCAkKuxkIAqQHBgAAFECAnwcCAqQICQAAIHCAUgkHAIwKAACMCwAA+wwBAJ8IBQCCCAAACgMBAwIDAwMEAwUDBgQAFECAAwcDCAQAIHCAABkAARgAAAAAAAAAAAEAAAAAAAAAAgECAAAAAAAAAAAAAAIAAAAAAAAAGgAAAAAKAQEAABYDAAQFAQQHAwICBwMGAgcFCgIHBQ4CIE0DALcAAAAATQEDeQEAAABNAwC3AAAAAE0CA3gCAAAATQUAngMAAABNAwV5AQAAAE0FAJ4DAAAATQQFeAIAAAAmBQMBJgYEAvsJAADsCAYJngUIBAUAAABSCQUApAcGAAAUQICfBwMCOQkHALsKCQKkCAgAABxAgJ8IAgKCCAIACQMBAwIDAwMEAwUDCQQAFECAAwoEABxAgAAkAAEYAAAAAAAAAAABAAAAAAAAAAIBAgAAAAAAAAACAAAAAAAlAAAAAAoBAAAAFgMABAUBBAcDAgIHAwYCBwUKAgcFDgIaTQMAtwAAAABNAQN5AQAAAE0DALcAAAAATQIDeAIAAABNBQCeAwAAAE0DBXkBAAAATQUAngMAAABNBAV4AgAAAEMGAQNbBQYEQwcCBFsGBwSkBwcAABhQgFIIBQD1CQgGnwcDAIIHAAAJAwEDAgMDAwQCAAAAAAAA4D8DBwMLBAAYUIACAAAAAAAA8D8ALwABGAAAAAAAAAAAAQAAAAAAAAACAAEAAgAAAAAAMAAAAAAMAQIAAABBTQEAiQAAAABNAgD3AQAAAE0DAJkCAAAA+wUAAE0EBeEDAAAA4gUGAE0GAEMHAAAAMAYFtwQAAABNBgBoCAAAADAGBZ4FAAAAnwQCAvsFAQBvBgkA4gcQAKQIEwAASBCBbwkUAG8KFACfCAMCMAgH6AoAAABSCAMAKwgGAKQIFgAASFCBjAkBAIwKAQCMCwEAnwgEAjAIB58LAAAAjAgAADAIB44MAAAA2QoAABIAAQASAAIAvAgEkBcAAACfCAMCMAgHLw0AAADZCgEAEgABALwIBJAXAAAAnwgDAjAIBzgOAAAAwAoYALwIBJAXAAAAnwgDAjAIBzsPAAAAnwUDAIIFAAAZAwwDDQMOAw8DAQMEBQIEBQMQAxEDEgMTAxQDFQMWAxcDGAUGCgsMDQ4PAxkDCAQASBCBAgAAAAAAAOA/AxoEAEhQgQMbBgIDAAECCwABGAAAAQABAAIAAAABAAAAAQAAAP4FAAABAAAAAAAAAQAAAAAAAAAAAAEAAAEAAAAAAAAACwAAAAAAAAsAAAAAAOYADAAAAAAEAAABAgAUowAAAKQAAQAAAABAbwICALwAAHwDAAAAnwADAqQBBQAAAEBATQMAJAYAAABNAgMhBwAAAJ8BAgJNAgHKCAAAAMADCQASAAEAEgACAIIDAgAKAxwEAAAAQAMdAx4DHwQAAEBAAyADIQMiBgMBAwEAARgAAQAAAAAAAQAAAAAAAAEABwAAAAEAAAAABHD2zoQ5eLaqQjKkEHvI2zM4o17xeaW3PZX6ptJTvkxR4jjEtyHGmys=

-- Decompiled by Krnl

local v1 = script:FindFirstAncestor("EzUi")
local v_u_2 = require(v1.Parent.Roact)
local v_u_3 = v_u_2.createElement
return function(p4)
	-- upvalues: (copy) v_u_2, (copy) v_u_3
	local v_u_5 = p4.aspectRatio
	local v_u_6 = p4.width
	local v7 = p4.lineColor
	local v8 = v_u_2.joinBindings({
		["pos0"] = p4.pos0Binding,
		["pos1"] = p4.pos1Binding
	})
	return v_u_3("Frame", {
		["AnchorPoint"] = Vector2.new(0.5, 0.5),
		["BackgroundColor3"] = v7 or Color3.new(1, 1, 1),
		["BorderSizePixel"] = 0,
		["Size"] = v8:map(function(p9)
			-- upvalues: (copy) v_u_5, (copy) v_u_6
			local v10 = p9.pos0.X
			local v11 = p9.pos0.Y
			local v12 = p9.pos1.X
			local v13 = p9.pos1.Y
			local v14 = v12 - v10
			local v15 = v13 - v11
			local v16 = v15 * v15 / v_u_5 / v_u_5 + v14 * v14
			local v17 = math.sqrt(v16)
			return UDim2.new(v17, 0, 0, v_u_6)
		end),
		["Rotation"] = v8:map(function(p18)
			-- upvalues: (copy) v_u_5
			local v19 = p18.pos0.X
			local v20 = p18.pos0.Y
			local v21 = p18.pos1.X
			local v22 = p18.pos1.Y
			local v23 = v21 - v19
			local v24 = (v22 - v20) / v_u_5
			local v25 = -math.atan2(v24, v23)
			return math.deg(v25)
		end),
		["Position"] = v8:map(function(p26)
			local v27 = p26.pos0.X
			local v28 = p26.pos0.Y
			local v29 = p26.pos1.X
			local v30 = p26.pos1.Y
			local v31 = (v27 + v29) * 0.5
			local v32 = (v28 + v30) * 0.5
			return UDim2.fromScale(v31, 1 - v32)
		end)
	})
end
