-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMQB3VubW91bnQNY3JlYXRlQmluZGluZwdyZXF1aXJlBFBsb3QGc2NyaXB0BlBhcmVudAVtb3VudA1jcmVhdGVFbGVtZW50BHNpemUIcG9zaXRpb24Gd2luZG93BVVEaW0yA25ldwRFelVpEUZpbmRGaXJzdEFuY2VzdG9yBVJvYWN0AAMCAAIAAAAG+wEAAE0AARIAAAAA+wEBAJ8AAgGCAAEAAQMBABEAARgAAAAAAAESAAAAAA0BAQAAADn7AgAATQECMQAAAACMAgAAnwECA6QDAgAAABBApAYFAAAAQEBNBQYkBgAAAE0EBZADAAAAnwMCAvsFAABNBAXkBwAAAPsGAABNBQbKCAAAAFIGAwDiBwwApAgPAAA40IBvCRAAjAoAAG8LEACMDAAAnwgFAjAIBw8JAAAApAgPAAA40IBvCREAjAoAAG8LEQCMDAAAnwgFAjAIB9sKAAAA/wgAAAQAAACMCQAAjAoAAIwLZACMDGQAxQgJBQEAAAAwCAcFCwAAAJ8FAwJSBgAAnwQDAtkFAAASAgAAEgAEAIIFAgASAwIDAwQAABBAAwQDBQQAAEBAAwYDBwMIAwkDCgMLBQMJCgsDDAMNBAA40IACAAAAAAAA4D8CAAAAAAAA0D8BAAUAARgAAAAAAAIAAAAAAAAAAAEAAAEAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAP0F+ggAAAAGAAAAAAQAAAECABGjAAAApAABAAAAAEBvAgIAvAAAfAMAAACfAAMCpAEFAAAAQEBNAwAkBgAAAE0CAyEHAAAAnwECAsACCAASAAEAggICAAkDBQQAAABAAw4DDwMDBAAAQEADBgMQBgEBAQEAARgAAQAAAAAAAQAAAAAAAAIAAAEAAAAAAt0fTRJKZZ3b79snhv9KHzag9aPyHGqYVcP3mJC1Kf6cnvWbZ2Z50qc=

-- Decompiled by Krnl

local v1 = script:FindFirstAncestor("EzUi")
local v_u_2 = require(v1.Parent.Roact)
return function(p3)
	-- upvalues: (copy) v_u_2
	local _, _ = v_u_2.createBinding(0)
	local v4 = require(script.Parent.Plot)
	local v_u_5 = v_u_2.mount(v_u_2.createElement(v4, {
		["size"] = UDim2.new(0.5, 0, 0.5, 0),
		["position"] = UDim2.new(0.25, 0, 0.25, 0),
		["window"] = {
			0,
			0,
			100,
			100
		}
	}), p3)
	return function()
		-- upvalues: (ref) v_u_2, (copy) v_u_5
		v_u_2.unmount(v_u_5)
	end
end
