-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMPBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzA0FwcAhSdW5VdGlscxpyZXF1aXJlVmFsaWRJbmRleEFuZEZyZWV6ZRpTUEFXTl9ERUJPVU5DRV9OT05fUFJFTUlVTRZTUEFXTl9ERUJPVU5DRV9QUkVNSVVNF1NQQVdOX0RFQk9VTkNFX1BIWVNJQ0FMDk5VTV9TQVZFX1NMT1RTE05VTV9GUkVFX1NBVkVfU0xPVFMLaXNNYWluV29ybGQAAQcAAAECADWjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CAxgHAAAAnwECAqQCBQAAAEBATQQAwQgAAABNAwRCCQAAAJ8CAgJNAwEACgAAAOIEEABNBgJQEQAAAJ8GAQIOBgIAjAVaAGUAAQCMBR4AMAUEbgsAAABNBgJQEQAAAJ8GAQIOBgIAjAU8AGUAAQCMBQoAMAUErgwAAACMBQUAMAUEdA0AAACMBRQAMAUEtQ4AAACMBQoAMAUELw8AAACfAwIAggMAABIDAQQAAABAAwIDAwMEBAAAQEADBQMGAwcDCAMJAwoDCwMMAw0DDgUFCwwNDg8DDwABAAEYAAEAAAAAAAEAAAAAAAABAAAAAAAAAQAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAgAAAQAA+gABAAAAAAAiT4TWPZkboBCL7kLEqUbIl0BC7c9Nr/aAQrsqRbRL2aZ+BEw46a9U

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v2 = require(v1.Std.TableUtils)
local v3 = require(v1.App.RunUtils)
return v2.requireValidIndexAndFreeze({
	["SPAWN_DEBOUNCE_NON_PREMIUM"] = v3.isMainWorld() and 90 or 30,
	["SPAWN_DEBOUNCE_PREMIUM"] = v3.isMainWorld() and 60 or 10,
	["SPAWN_DEBOUNCE_PHYSICAL"] = 5,
	["NUM_SAVE_SLOTS"] = 20,
	["NUM_FREE_SAVE_SLOTS"] = 10
})
