-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMIBXZhbHVlC3NldEVxdWlwcGVkBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlBVJvZHV4DWNyZWF0ZVJlZHVjZXIAAgMCAAAAAANNAgHMAAAAAIICAgABAwEABgIBGAAAAAcAAAAABgAAAQIAFqMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0CAKcGAAAAnwECAk0CAdYHAAAA/wMAAAAAAADiBAkAwAUKADAFBBkIAAAAnwIDAIICAAALAwMEAAAAQAMEAwUDBgQAAEBAAwcDCAMCBQEIBgABAAEAARgAAQAAAAAAAQAAAAACAAAAAAEAAP8AAQAAAAABqX0RRJLN6HObuXvQWDY8HJEdZhP0ixPpw+CCxN0nPgIMI73eRnExyQ==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Rodux).createReducer({}, {
	["setEquipped"] = function(_, p2)
		return p2.value
	end
})
