-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMIBXZhbHVlEXNldFF1YW50aXR5UGxhY2VkBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlBVJvZHV4DWNyZWF0ZVJlZHVjZXIAAgMCAAAAAANNAgHMAAAAAIICAgABAwEABwIBGAAAAAgAAAAABgAAAQIAFqMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0CAKcGAAAAnwECAk0CAdYHAAAA/wMAAAAAAADiBAkAwAUKADAFBMAIAAAAnwIDAIICAAALAwMEAAAAQAMEAwUDBgQAAEBAAwcDCAMCBQEIBgABAAEAARgAAQAAAAAAAgAAAAACAAAAAAEAAP8AAQAAAAABs0Uaeia3/uaBgXDuFchhupnG6sBiTV1d+9K+KoLMRQ3sAZVHsktRPg==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Rodux).createReducer({}, {
	["setQuantityPlaced"] = function(_, p2)
		return p2.value
	end
})
