-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgODAQZzdHJpbmcFbWF0Y2gVXihbXiVkXSolZCkoJWQqKSguLSkkB3JldmVyc2UIKCVkJWQlZCkDJTEsBGdzdWIFY29tbWEPc2VsZWN0SWZHYW1lcGFkD1NlbGVjdElmR2FtZXBhZARuZXh0C0dldENoaWxkcmVuCEJhc2VQYXJ0A0lzQQhBbmNob3JlZAZBbmNob3IFRnJhbWUISW5zdGFuY2UDbmV3CVRleHRMYWJlbAVVRGltMgRTaXplCFBvc2l0aW9uBE5hbWUEVGV4dBZCYWNrZ3JvdW5kVHJhbnNwYXJlbmN5BkNvbG9yMwpUZXh0Q29sb3IzBEVudW0ERm9udA5Tb3VyY2VTYW5zQm9sZAhUZXh0U2l6ZQZQYXJlbnQFUHJpY2UDJCVzBmZvcm1hdBZUZXh0U3Ryb2tlVHJhbnNwYXJlbmN5B2Zyb21SR0IQVGV4dFN0cm9rZUNvbG9yMwpUZXh0U2NhbGVkDlRleHRMYWJlbFByaWNlClRleHRCdXR0b24QQmFja2dyb3VuZENvbG9yMwdCdXkgJCVzD0JvcmRlclNpemVQaXhlbAdWaXNpYmxlDVRleHRCdXR0b25CdXkMSXRlbUZyYW1lR2VuDURvZXNQbGF5ZXJPd24FT3duZWQFT1dORUQPVXBkYXRlSXRlbUZyYW1lEEdldExvY2FsRXF1aXBwZWQFZXJyb3IcUGxheWVyIGhhcyBubyBpdGVtIGVxdWlwcGVkLgtfX0NsYXNzTmFtZQhnZXRNb2RlbAtHZXRJbnN0YW5jZQR0aWNrBkNGcmFtZQZBbmdsZXMEbWF0aANzaW4LQm91bmRpbmdCb3gIU2tlbGV0b24JTWFnbml0dWRlDlZpZXdwb3J0VXBkYXRlBEluaXQOQ2xlYXJTZWxlY3Rpb24OT25Ta2luQnV5Q2xpY2sERmlyZQdPbkNsaWNrC09uU2tpbkNsaWNrCUhlYXJ0YmVhdAZJc09wZW4NQWxyZWFkeSBvcGVuIQRNYWlkCVNjcmVlbkd1aQlQbGF5ZXJHdWkIR2l2ZVRhc2sMVUlMaXN0TGF5b3V0CVNvcnRPcmRlcgtMYXlvdXRPcmRlcgRVRGltB1BhZGRpbmcNRmlsbERpcmVjdGlvbghWZXJ0aWNhbBFWZXJ0aWNhbEFsaWdubWVudANUb3ATSG9yaXpvbnRhbEFsaWdubWVudAZDZW50ZXIGaXBhaXJzBkhpZGRlbgV0YWJsZQZpbnNlcnQJU2V0UGFyZW50D21WaWV3cG9ydFNsaWRlcghMaXN0SXRlbQlWaWV3cG9ydHMQTW91c2VCdXR0b24xRG93bgdDb25uZWN0BXNwYXduDE9uTW91c2VDbGljawRPcGVuBlVwZGF0ZQtVcGRhdGVPd25lZAlOb3Qgb3BlbiEHRGVzdHJveQhPbkNsb3NlZAVDbG9zZQRnYW1lClJ1blNlcnZpY2UKR2V0U2VydmljZQdQbGF5ZXJzC0xvY2FsUGxheWVyEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUGc2NyaXB0D0l0ZW1Ta2luVUlVdGlscwRFelVpB0V6VXRpbHMDU3RkBlNpZ25hbA5WaWV3cG9ydFNsaWRlcgRHYW1lBkdhcmFnZQhHYXJhZ2VVSQhJdGVtU2tpbgtJdGVtU2tpbklkcwxJdGVtU2tpbkxpc3QKSXRlbVN5c3RlbQASDAEAAAAAFaQBAgAABACAUgIAAG8DAwCfAQMEUgUBALwIApsEAAAAnwgCAm8KBQBvCwYAvAgIzAcAAACfCAQCvAgImwQAAACfCAICUgYIAFIHAwBzBAUHggQCAAgDAQMCBAAEAIADAwMEAwUDBgMHABAIARgAAAAAAAEAAAAAAAAAAAAAAAAAAAARAAAAAAMBAQAAAAb7AgAATQECBAAAAABSAgAAnwECAYIAAQABAwkAFQoBGAAAAAAAARYAAAAACgIBAAAAFKQCAQAAAABAvAMAaAIAAACfAwIDFwILAG8JAwC8Bwb+BAAAAJ8HAwIOBwIAMAEGRQUAAAD7BwAAUggGAFIJAQCfBwMBbgL0/wIAAACCAAEABgMLBAAAAEADDAMNAw4DDwAZEAEYAAAAAAAAAQAAAAABAAIAAAD8AAYaAAAAABQCAAAADAAAAgMFYAIDBsMBAtoBTQIBnQAAAACkAwMAAAgQgG8EBACfAwICpAQGAAAIUICMBQEAjAYAAIwHAACMCBQAnwQFAjAEAy8HAAAApAQGAAAIUICMBQAAjAYAAIwHAACMCAUAnwQFAjAEAzsIAAAATQQAugkAAAAwBAP1CgAAAIwEAQAwBAM6CwAAAKQEDQAACMCAjAUBAIwGAQCMBwEAnwQEAjAEA3MOAAAApAQSABFA8MAwBAM5EAAAAIwEFAAwBANuEwAAADACAyQUAAAATQQAJBUAAAAOBKYApAQDAAAIEIBvBQQAnwQCAqQFBgAACFCAjAYBAIwHAABvCBYAjAkAAJ8FBQIwBQQvBwAAAKQFBgAACFCAjAYAAIwHAABvCBcAjAkAAJ8FBQIwBQQ7CAAAAG8FGABNCAAkFQAAAKQJGwAAaJCBUgoIAG8LHACfCQMEUgwJALwPCpsdAAAAnw8CAm8RHgBvEh8AvA8PzCAAAACfDwQCvA8Pmx0AAACfDwICUg0PAFIOCwBzBwwOvAUFjSEAAACfBQMCMAUE9QoAAACMBQEAMAUEOgsAAACkBQ0AAAjAgIwGAACMBwEAjAgAAJ8FBAIwBQRzDgAAAG8FIgAwBQRHIwAAAKQFJQAAkMCAjAYLAIwHbwCMCAAAnwUEAjAFBKQmAAAApAUSABFA8MAwBQQ5EAAAAKkFAQAwBQTeJwAAADACBCQUAAAAMAQBGygAAACkBQMAAAgQgG8GKQCfBQICpAYNAAAIwIBvByoAbwgqAG8JKgCfBgQCMAYFnysAAACkBg0AAAjAgIwHAQCMCAEAjAkBAJ8GBAIwBgVzDgAAAKQGBgAACFCAbwcsAIwIAABvCRYAjAoAAJ8GBQIwBgUvBwAAAKQGBgAACFCAbwcqAIwIAABvCRcAjAoAAJ8GBQIwBgU7CAAAAG8GLQBNCQAkFQAAAKQKGwAAaJCBUgsJAG8MHACfCgMEUg0KALwQC5sdAAAAnxACAm8SHgBvEx8AvBAQzCAAAACfEAQCvBAQmx0AAACfEAICUg4QAFIPDABzCA0PvAYGjSEAAACfBgMCMAYF9QoAAACMBgAAMAYFji4AAACkBhIAEUDwwDAGBTkQAAAAqQYBADAGBd4nAAAAqQYAADAGBYAvAAAAMAIFJBQAAAAwBQFZMAAAAIIAAQAxAxEDEgMTBAAIEIADFAMVBAAIUIADFgMXAxgDGQMaAxsEAAjAgAMcAx0DHgMfBBFA8MADIAMhAyICmpmZmZmZyT8CAAAAAAAA6D8DIwMBAwIEAGiQgQMDAwQDBQMGAwcDJAIAAAAAAADgPwMlAyYEAJDAgAMnAygDKQMqApqZmZmZmbk/AysCmpmZmZmZ6T8DLAMtAy4DLwAhMAEYEQACAAAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAEAAAEAAAAAAAAAAQAAAAEAAAEAAgAAAQAAAAEAAAAAAAAAAAEAAAAAAAAAAAEAAN8AAAAAAQAAAAAAAAAAAAAAAAAAIAAAAAABAAABAAAAAAAAAAEAAAEAAAAAAAAAAQAAAAMAAAEAAgACAAAAAQAAAAAAAAABAAAAAAAAAAMAAAAAAAAAAAEAAAAAAAAAAAEAAMsAAAAAAQAAAAAAAAAAAAAAAAAANAAAAAABAAABAAAAAQAAAwAAAQACAAIRAAAAAAgCAQAAAB77AwAATQIDGwAAAABNAwC6AQAAAJ8CAgIwAgGEAgAAAA4CFABNAwEbAwAAAG8EBAAwBAP1BQAAAKQECAAAHGCAjAXmAIwG5gCMB+YAnwQEAjAEA3MJAAAAjAQBADAEA0cKAAAApAQOAA0wsMAwBAM5DAAAAIIAAQAPAzEDGAMyAykDMwMZAxsDJgQAHGCAAxwDJQMdAx4DHwQNMLDAAFI0ARgAAAAAAAABAAICAAEAAAEAAAAAAAAAAQAAAQAAAAJVAAAAAAYBAgAAABT7AgAATQECMwAAAACfAQECRwEFAAAAAICkAgIAAAAQQG8DAwCfAgIBTQIB5QQAAAD7BAEATQMEIgUAAABNBAC6BgAAAFIFAgCfAwMAggMAAAcDNQM2BAAAEEADNwM4AzkDGABhOgEYAAAAAAEAAQAAAAIAAQAAAAAAAABjAAAAAA0CAAAAACikAgEAAAAAQJ8CAQKkBQQAAAwggIwGAAAhBwIFjAgAAJ8FBAKkBgQAAAwggFsKAgi7GAoCpAkLAAAokICfCQICWwgJB3gHCAaMCAAAjAkAAJ8GBAIJBAUGpAUNAAAwIICMBgAAjAcAAE0MAUYQAAAATQsMbw8AAABNCgsvEQAAAE0JCqoSAAAAWwgJDp8FBAIJAwQFMAMAhQIAAACCAAEAEwM7BAAAAEADPAM9BAAMIIACGC1EVPshGUACMzMzMzMz0z8CAAAAAAAA0D8CAAAAAAAA4D8DPgM/BAAokIADEwQAMCCAApqZmZmZmek/A0ADQQMWA0IAakMBGAAAAAEAAAAAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAD+AANrAAAAAAAAAAAAAAGCAAEAAAB2RAEYAHoAAAAAAgABAAAAC/sAAAAOAAgA+wEAAE0AAVkAAAAAqQEAADABAIABAAAAxgAAAN4AAACCAAEAAgMvAy4AnwFFARgAAAEAAAAAAAIAAqAAAAAAAwADAAAAEvsAAAAOAAgA+wEAAE0AAVkAAAAAqQEAADABAIABAAAAxgAAAN4AAAD7AQEATQABogIAAAD7AgIAvAAA3QMAAACfAAMBggABAAQDLwMuA0YDRwCwAUgBGAAAAQAAAAAAAgAPAAAAAAAAAqAAAAAAAwACAAAACfsBAABNAAGdAAAAAPsCAQBNAQIEAQAAAFICAACfAQIBggABAAIDEQMJALkBAAEYpAAAXAAAAAClFgAAAAAFAgMAAAAi+wIAAA4CCAD7AwAATQIDWQAAAACpAwAAMAMCgAEAAADGAgAA3gIAAE0CAYQCAAAAKwIFAE0CAVkAAAAAqQMBADADAoABAAAA+wMBAE0CA+kDAAAAUgQAALwCAt0EAAAAnwIDAU0CAVkAAAAA+wQCAE0DBAQFAAAAUgQCAJ8DAgHeAQAAggABAAYDLwMuAzIDSQNHAwkAvwEAARiKAAEAAAAAAAIAHgAAAQAAAAACAAAAAAAAAQBRAAAAALEBFgAAAAACAAEAAAAF+wEAAE0AAf0AAAAAnwABAYIAAQABA0oAygEAARgAAAAAAcsAAAAAEgALAAAA5AH7AQAATQABMQAAAAAqAAUAAQAAgKQAAgAAABBAbwEDAJ8AAgH7AAAAqQEBADABADEAAAAA+wAAAPsCAQBNAQLvBAAAAJ8BAQIwAQB2BQAAAKQABwAAEGCAbwEIAJ8AAgL7AgIATQECmQkAAAAwAQAkCgAAAPsCAABNAQJ2BQAAAFIDAAC8AQH9CwAAAJ8BAwGkAQcAABBggG8CDACfAQICpAIQAA840MAwAgG5DgAAAKQCEgAAEBCBbwMTAIwEAACfAgMCMAIB3RQAAACkAhcAFlTQwDACAVEVAAAApAIaABlg0MAwAgF4GAAAAKQCHQAcbNDAMAIBYhsAAAAwAAEkCgAAAP8CAAAAAAAApAMfAAAA4EH7BAMAnwMCBFEDHACpCAEATQkHtiAAAAAOCQgA+woEAE0JChshAAAATQoHuiIAAACfCQICKwkBAKkIAAAOCA8A4gskAE0MB7oiAAAAMAwLuiIAAABNDAckIwAAADAMCyQjAAAAnjQCBAsAAABSCgIApAknAACYUIKfCQMBbgPj/wIAAIDGAwAA2QQAABIBA//7BgUATQUG7wQAAABSBgIA+wcGAPsIBwD7CQgAnwUFAlIIAAC8BgUZKAAAAJ8GAwH7BgAAMAUGdSkAAAD7BwAATQYHdgUAAAD7CQAATQgJdSkAAAC8Bgb9CwAAAJ8GAwGMCAEATQkFtSoAAAAcBgkAjAcBAKgGPgBNCgW1KgAAAIcJCghNCwX1KwAAAIcKCwjZCwEAEgED/xICAAASAAkA+w0AAE0MDXYFAAAATQ8KWSwAAABNDg9hLQAAAFIQCwC8Dg7HLgAAAJ8OAwC8DAz9CwAAAJ8MAAH7DQQATQwNGyEAAABNDQm6IgAAAJ8MAgIwDAqELwAAAA4MFABNDQobMAAAAG8OMQAwDg31MgAAAKQONQAA0DCDjA/mAIwQ5gCMEeYAnw4EAjAODXM2AAAAjA4BADAODUc3AAAApA46ADng0MAwDg05OAAAAA0IBwA7AACApAw9AAAAwEPZDQIAEgAKABICCQCfDAIBiwbC//sHAABNBgd2BQAAAE0IBWI+AAAA2QoDABIBA/8SAgAAEgIJALwICMcuAAAAnwgDALwGBv0LAAAAnwYAAfsHAABNBgd2BQAAAPsJCgBNCAn9PwAAAMAKQAASAgAAvAgIxy4AAACfCAMAvAYG/QsAAACfBgABwQMAAIIAAQBBA0sDNgQAABBAA0wDEwNNAxIEABBggANOA08DIQNQA1EDHQNSA1MEDzjQwANUBAAQEIECexSuR+F6lD8DVQNWA1cEFlTQwANYA1kEGWDQwANaA1sEHGzQwANcBAAA4EEDXQMxAxgDIgUCIiMDXgNfBACYUIIDYANhA2IDYwMvA2QDZQMyAykDMwMZAxsDJgQA0DCDAxwDJQMeAx8EOeDQwAIAAAAAAADwPwNmBAAAwEMDZwNKBgwFCAkKCwx7aAEYJwAAAAABAAAAAgAAAAEAAAAAAAACAAAAAQAAAAABAAAAAAAAAgAAAAEAAAABAAAAAAAAAQAAAAEAAAABAAAAAQACAAEAAAAAAQEAAAEAAAAAAAABAwEBAAAAAQAAAAAAAP4AAPgADwEACAAAAAAAAAABAAAAAQAAAQAAAAAAAAAAAgAAAAAAAQAAAQAAAgAAAAUAAAAAAAAAAAAAAAAAoAAAAAAAAQACAgABAAABAAAAAAAAAAEAAAEAAABaAAEAAAAAAPMTAAAAAAAAAAAAAAAAAAALAAAAAAAAAAAAAAAAAAMAVQAAAAACAAEAAAAH+wEAAE0AAXUAAAAAvAAAJgEAAACfAAIBggABAAIDYQNpAM4BSgEYAAAAAAAAAc8AAAAADAACAAAAMvsBAABNAAF1AAAAAEcAAwAAAACAqQEAAIIBAgCMAwEATQQAtQEAAAAcAQQAjAIBAKgBJABNBQC1AQAAAIcEBQNNBgD1AgAAAIcFBgP7BwEATQYHGwMAAABNBwS6BAAAAJ8GAgIwBgWEBQAAAA4GFABNBwUbBgAAAG8IBwAwCAf1CAAAAKQICwAAKJCAjAnmAIwK5gCMC+YAnwgEAjAIB3MMAAAAjAgBADAIB0cNAAAApAgRABA84MAwCAc5DwAAAIsB3P+CAAEAEgNhA2IDYwMxAxgDMgMpAzMDGQMbAyYEACiQgAMcAyUDHQMeAx8EEDzgwADRAWoBGH0AAAEAAQACAAAAAAABAAABAAB9AAAAAAABAAICAAEAAAEAAAAAAAAAAQAAAQAAAHgFVQAAAAACAAEAAAAe+wEAAE0AATEAAAAAKgAFAAEAAACkAAIAAAAQQG8BAwCfAAIB+wAAAKkBAAAwAQAxAAAAAPsBAABNAAF2BAAAALwAAFAFAAAAnwACAfsAAADGAQAAMAEAdgQAAAD7AQAATQABOAYAAAC8AADdBwAAAJ8AAgGCAAEACANLAzYEAAAQQANrA00DbANtA0cA3AFuARgAAAAAAAEAAAACAAAAAQAAAAAAAQAAAAEAAAAAAAHdAAAAABYAAAECAKEBowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBAQAAAABAbwMEALwBARYDAAAAnwEDAk0CATEFAAAApAMBAAAAAEBvBQYAvAMDFgMAAACfAwMCpAQIAAAAcECkBwoAAACQQE0GByQLAAAATQUGBgwAAACfBAICpAUIAAAAcEBNBwMtDQAAAE0GB8IOAAAAnwUCAqQGCAAAAHBATQgDoQ8AAABNBwh2EAAAAJ8GAgKkBwgAAABwQE0JA6EPAAAATQgJHxEAAACfBwICpAgIAAAAcEBNDAO9EwAAAE0LDCgUAAAATQoLJBUAAABNCQo7EgAAAJ8IAgKkCQgAAABwQE0MA70TAAAATQsM4RYAAABNCgvhFgAAAJ8JAgKkCggAAABwQE0NA70TAAAATQwN4RYAAABNCwzMFwAAAJ8KAgKkCwgAAABwQE0OA70TAAAATQ0O4RYAAABNDA0DGAAAAJ8LAgKkDAgAAABwQE0PA70TAAAATQ4P8BkAAABNDQ7wGQAAAJ8MAgLADRoAwA4bABIABQDADxwAEgAPAMAQHQDAER4AEgAJAMASHwASAAwAEgAEAMATIAD/FAUAAAAAAE0VB+8hAAAAnxUBAjAVFOkiAAAATRUH7yEAAACfFQECMBUUoiMAAABNFQfvIQAAAJ8VAQIwFRQ4JAAAAKkVAAAwFRQxJQAAAMAVJgAwFRRzJwAAAMAVKAASABQAEgAGABIAAgASAAsAEgAJABIACAASABAAEgASABIAEwASAAUAEgAAADAVFBYpAAAAwBUqABIAFAAwFRT9KwAAAMAVLAASABQAEgAJADAVFAotAAAAwBUuABIAFAAwFRRjLwAAAIIUAgAwA28EAAAAQANwA3EDcgNzA3QDdQQAAHBAA3YEAACQQAMhA3cDeAN5A3oDTQN7A3wDfQN+A38DgAEDgQEDggEDgwEGAAYBBgIGAwYEBgUGBgMTA0kDRgNtA0sGBwNEBg0DaAYOA0oGDwNqBhADbgwAAQIDBAUGBw0ODxABAAEYAAEAAAAAAAEAAAAAAAEAAQAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAAACBQAEAAgxAA8AAAkHAAEAAAAAAQAAAAABAAAAAAEAAAEAAAUAAAAAAAAAAAAAAAAAUwAAAAMAAAAACwAAAAkBAAAAABHCo/T2XI1klfBnnmLGZvQsIyas8fGvXMHTkp7/IAaMGkcIgB/IWu+Z

-- Decompiled by Krnl

local v_u_1 = game:GetService("RunService")
local v_u_2 = game:GetService("Players").LocalPlayer
local v3 = game:GetService("ReplicatedStorage")
local v_u_4 = require(script.Parent.ItemSkinUIUtils)
local v_u_5 = require(v3.EzUi.EzUtils)
local v_u_6 = require(v3.Std.Maid)
local v7 = require(v3.Std.Signal)
local v_u_8 = require(v3.Game.Garage.GarageUI.ViewportSlider)
local v_u_9 = require(v3.Game.ItemSkin.ItemSkin)
require(v3.Game.ItemSkin.ItemSkinIds)
local v_u_10 = require(v3.Game.ItemSkin.ItemSkinList)
local v_u_11 = require(v3.Game.ItemSystem.ItemSystem)
local function v_u_18(p12, p13)
	-- upvalues: (copy) v_u_18
	local v14 = next
	local v15, v16 = p12:GetChildren()
	for _, v17 in v14, v15, v16 do
		if v17:IsA("BasePart") then
			v17.Anchored = p13
		end
		v_u_18(v17, p13)
	end
end
local function v_u_33(p19, p20)
	local v21 = p20.Frame
	local v22 = Instance.new("TextLabel")
	v22.Size = UDim2.new(1, 0, 0, 20)
	v22.Position = UDim2.new(0, 0, 0, 5)
	v22.Text = p19.Name
	v22.BackgroundTransparency = 1
	v22.TextColor3 = Color3.new(1, 1, 1)
	v22.Font = Enum.Font.SourceSansBold
	v22.TextSize = 20
	v22.Parent = v21
	if p19.Price then
		local v23 = Instance.new("TextLabel")
		v23.Size = UDim2.new(1, 0, 0.2, 0)
		v23.Position = UDim2.new(0, 0, 0.75, 0)
		local v24 = p19.Price
		local v25, v26, v27 = string.match(v24, "^([^%d]*%d)(%d*)(.-)$")
		v23.Text = ("$%s"):format(v25 .. v26:reverse():gsub("(%d%d%d)", "%1,"):reverse() .. v27)
		v23.BackgroundTransparency = 1
		v23.TextColor3 = Color3.new(0, 1, 0)
		v23.TextStrokeTransparency = 0.5
		v23.TextStrokeColor3 = Color3.fromRGB(11, 111, 0)
		v23.Font = Enum.Font.SourceSansBold
		v23.TextScaled = true
		v23.Parent = v21
		p20.TextLabelPrice = v23
		local v28 = Instance.new("TextButton")
		v28.BackgroundColor3 = Color3.new(0.1, 0.1, 0.1)
		v28.TextColor3 = Color3.new(1, 1, 1)
		v28.Size = UDim2.new(0.8, 0, 0.2, 0)
		v28.Position = UDim2.new(0.1, 0, 0.75, 0)
		local v29 = p19.Price
		local v30, v31, v32 = string.match(v29, "^([^%d]*%d)(%d*)(.-)$")
		v28.Text = ("Buy $%s"):format(v30 .. v31:reverse():gsub("(%d%d%d)", "%1,"):reverse() .. v32)
		v28.BorderSizePixel = 0
		v28.Font = Enum.Font.SourceSansBold
		v28.TextScaled = true
		v28.Visible = false
		v28.Parent = v21
		p20.TextButtonBuy = v28
	end
end
local function v_u_37(p34)
	-- upvalues: (copy) v_u_11, (copy) v_u_4
	local v35 = v_u_11.GetLocalEquipped()
	if v35 == nil then
		error("Player has no item equipped.")
	end
	local v36 = v35.__ClassName
	return v_u_4.getModel(p34.Name, v36)
end
local function v_u_44(p38, p39)
	local v40 = tick()
	local v41 = CFrame.Angles(0, v40 % 6.283185307179586, 0)
	local v42 = CFrame.Angles
	local v43 = v40 * 0.5
	p38.CFrame = v41 * v42(math.sin(v43) * 0.25 - 0.3, 0, 0) * CFrame.new(0, 0, p39.Skeleton.BoundingBox.Size.Magnitude * 0.8)
end
local v_u_69 = {
	["OnSkinClick"] = v7.new(),
	["OnSkinBuyClick"] = v7.new(),
	["OnClosed"] = v7.new(),
	["IsOpen"] = false,
	["Init"] = function() end,
	["Open"] = function()
		-- upvalues: (copy) v_u_69, (copy) v_u_6, (copy) v_u_2, (copy) v_u_10, (copy) v_u_9, (copy) v_u_8, (copy) v_u_33, (copy) v_u_37, (copy) v_u_44, (copy) v_u_5, (copy) v_u_1
		if v_u_69.IsOpen == true then
			error("Already open!")
		end
		v_u_69.IsOpen = true
		v_u_69.Maid = v_u_6.new()
		local v45 = Instance.new("ScreenGui")
		v45.Parent = v_u_2.PlayerGui
		v_u_69.Maid:GiveTask(v45)
		local v46 = Instance.new("UIListLayout")
		v46.SortOrder = Enum.SortOrder.LayoutOrder
		v46.Padding = UDim.new(0.02, 0)
		v46.FillDirection = Enum.FillDirection.Vertical
		v46.VerticalAlignment = Enum.VerticalAlignment.Top
		v46.HorizontalAlignment = Enum.HorizontalAlignment.Center
		v46.Parent = v45
		local v47 = {}
		for _, v48 in ipairs(v_u_10) do
			if (not v48.Hidden or v_u_9.DoesPlayerOwn(v48.Name)) and true or false then
				local v49 = {
					["Name"] = v48.Name,
					["Price"] = v48.Price
				}
				table.insert(v47, v49)
			end
		end
		local v50 = nil
		local v51 = v_u_8.new(v47, v_u_33, v_u_37, v_u_44)
		v51:SetParent(v45)
		v_u_69.mViewportSlider = v51
		v_u_69.Maid:GiveTask(v_u_69.mViewportSlider)
		local v_u_52 = v50
		for v53 = 1, #v51.ListItem do
			local v_u_54 = v51.ListItem[v53]
			local v_u_55 = v51.Viewports[v53]
			local function v56()
				-- upvalues: (ref) v_u_52, (ref) v_u_69, (copy) v_u_54
				if v_u_52 then
					v_u_52.TextButtonBuy.Visible = false
					v_u_52 = nil
				end
				v_u_69.OnSkinBuyClick:Fire(v_u_54)
			end
			v_u_69.Maid:GiveTask(v_u_55.TextButtonBuy.MouseButton1Down:Connect(v56))
			local v57 = v_u_9.DoesPlayerOwn(v_u_54.Name)
			v_u_55.Owned = v57
			if v57 then
				local v58 = v_u_55.TextLabelPrice
				v58.Text = "OWNED"
				v58.TextColor3 = Color3.fromRGB(230, 230, 230)
				v58.TextStrokeTransparency = 1
				v58.Font = Enum.Font.SourceSansBold
			end
			if v53 == 1 then
				spawn(function()
					-- upvalues: (copy) v_u_55, (ref) v_u_5
					local v59 = v_u_55.Frame
					v_u_5.selectIfGamepad(v59)
				end)
			end
		end
		v_u_69.Maid:GiveTask(v51.OnMouseClick:Connect(function(p60, p61)
			-- upvalues: (ref) v_u_52, (ref) v_u_69, (ref) v_u_5
			if v_u_52 then
				v_u_52.TextButtonBuy.Visible = false
				v_u_52 = nil
			end
			if not p61.Owned then
				p61.TextButtonBuy.Visible = true
			end
			v_u_69.OnSkinClick:Fire(p60)
			local v62 = p61.TextButtonBuy
			v_u_5.selectIfGamepad(v62)
			v_u_52 = p61
		end))
		v_u_69.Maid:GiveTask(v_u_1.Heartbeat:Connect(function()
			-- upvalues: (ref) v_u_69
			v_u_69.Heartbeat()
		end))
	end,
	["Heartbeat"] = function()
		-- upvalues: (copy) v_u_69
		v_u_69.mViewportSlider:Update()
	end,
	["UpdateOwned"] = function()
		-- upvalues: (copy) v_u_69, (copy) v_u_9
		local v63 = v_u_69.mViewportSlider
		if v63 == nil then
			return false
		end
		for v64 = 1, #v63.ListItem do
			local v65 = v63.ListItem[v64]
			local v66 = v63.Viewports[v64]
			local v67 = v_u_9.DoesPlayerOwn(v65.Name)
			v66.Owned = v67
			if v67 then
				local v68 = v66.TextLabelPrice
				v68.Text = "OWNED"
				v68.TextColor3 = Color3.fromRGB(230, 230, 230)
				v68.TextStrokeTransparency = 1
				v68.Font = Enum.Font.SourceSansBold
			end
		end
	end,
	["Close"] = function()
		-- upvalues: (copy) v_u_69
		if v_u_69.IsOpen ~= true then
			error("Not open!")
		end
		v_u_69.IsOpen = false
		v_u_69.Maid:Destroy()
		v_u_69.Maid = nil
		v_u_69.OnClosed:Fire()
	end
}
return v_u_69
