-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgM4ClN0YXJ0ZXJHdWkRQ29udGV4dE1lc3NhZ2VHdWkORmluZEZpcnN0Q2hpbGQJUGxheWVyR3VpBlBhcmVudANndWkDbmV3ClNldEVuYWJsZWQRX3dvcmxkTWFya2VyR3JvdXAMU2V0U2NyZWVuR3VpB1NldEljb24KRnJhbWVJbm5lcgZDb2xvcjMHZnJvbVJHQgtJbWFnZUNvbG9yMwNBZGQIYWRkR3JvdXAMX3dvcmxkTWFya2VyBGluaXQHRW5hYmxlZBVzZXRXb3JsZE1hcmtlckVuYWJsZWQOb25DbG9zZUNsaWNrZWQERmlyZQVjbG9zZQVfbWFpZAZhc3NlcnQIR2l2ZVRhc2sJQ29udGFpbmVyBUNsb3NlEE1vdXNlQnV0dG9uMURvd24HQ29ubmVjdARvcGVuB0Rlc3Ryb3kHTWVzc2FnZQRUZXh0C09iamVjdExvY2FsCnNldE1lc3NhZ2ULU2V0UG9zaXRpb24Wc2V0V29ybGRNYXJrZXJQb3NpdGlvbghTZXRTaXplcxNzZXRXb3JsZE1hcmtlclNpemVzBmlzT3BlbgRnYW1lB1BsYXllcnMKR2V0U2VydmljZQtMb2NhbFBsYXllchFSZXBsaWNhdGVkU3RvcmFnZQdyZXF1aXJlA1N0ZARNYWlkBlNpZ25hbAVBdWRpbxFXb3JsZE1hcmtlclN5c3RlbQRHYW1lC1dvcmxkTWFya2VyEFdvcmxkTWFya2VyR3JvdXAADAgABgAAAD/7AQAATQABCwAAAABvAgEAvAAAAwIAAACfAAMC+wIBAE0BApkDAAAAMAEAJAQAAAD7AQIAMAABfwUAAAD7AgMATQEC7wYAAACfAQECqQQAALwCAZ4HAAAAnwIDAfsCAgAwAQJXCAAAAPsDBABNAgPvBgAAAJ8CAQL7BgUATQUGfwUAAAC8AwIUCQAAAJ8DAwFvBQoAvAMCKgsAAACfAwMBTQMCeAwAAACkBA8AADjQgIwF/wCMBssAjAdGAJ8EBAIwBAMAEAAAAFIFAgC8AwFfEQAAAJ8DAwH7BAUATQMEOBIAAABSBAEAnwMCAfsDAgAwAgOQEwAAAIIAAQAUAwEDAgMDAwQDBQMGAwcDCAMJAwoCAAAA4nUO9kEDCwMMAw0DDgQAONCAAw8DEAMRAxIAERMBGAAAAAAAAAABAAAAAAEAAAIAAAABAAAAAQAAAgAAAAEAAAAAAAEAAAABAAAAAAAAAAAAAQAAAAEAAAAAAQAAAxIAAAAAAgABAAAABfsAAACpAQAAMAEA8AAAAACCAAEAAQMUACsAARgAAAAAASwAAAAAAgABAAAABvsBAABNAAFMAAAAAKkBAACfAAIBggABAAEDFQAuAAEYAAAAAAABLwAAAAACAAEAAAAL+wEAAE0AAUAAAAAAvAAA3QEAAACfAAIB+wEAAE0AAYMCAAAAnwABAYIAAQADAxYDFwMYADIAARgAAAAAAAABAAAAATMAAAAABwACAAAAMfsDAABNAgPBAAAAAEcCAgAAAAAAqQEAAakBAQC7AQECpAACAAAAEECfAAIB+wEBAE0AAe8DAAAAnwABAvsBAAAwAAHBAAAAAPsCAABNAQJ/BAAAAKkCAQAwAgHwBQAAANkEAAASAAEAvAIA/QYAAACfAgMBwAQHABICAAC8AgD9BgAAAJ8CAwFNBgFvCAAAAE0FBmMJAAAATQQFYQoAAADABgsAEgIAALwEBMcMAAAAnwQDALwCAP0GAAAAnwIAAYIAAQANAxkDGgQAABBAAwcDBgMUAxsGAgMcAx0DHgYDAx8DAQIDJCABGAAAAAAAAAAAAAAAAQAAAAEAAAIAAAEAAAEAAAAAAwAAAAAEAAAAAAAAAAAAAAAAAAQlAAAAAAQAAQAAABb7AwAATQIDwQAAAABHAgIAAAAAgKkBAAGpAQEAuwEBAqQAAgAAABBAnwACAfsBAABNAAHBAAAAAPsBAADGAgAAMAIBwQAAAAC8AQBQAwAAAJ8BAgGCAAEABAMZAxoEAAAQQAMhADcYARgAAAAAAAAAAAAAAAEAAAEAAAACAAABOAAAAAAFAQIAAAAS+wIAAE0BAn8AAAAATQQBbwEAAABNAwRvAQAAAE0CA/gCAAAAMAAC9QMAAAD7AwEATQID0QQAAABSAwEAbwQFAJ8CAwGCAAEABgMGAxwDIgMjAyQCAACAi9959UEAPiUBGAAAAAEAAAAAAAAAAwAAAAAAAT8AAAAABAEBAAAACPsCAABNAQJXAAAAAFIDAAC8AQGeAQAAAJ8BAwGCAAEAAgMJAwgARRUBGAAAAAAAAAABRgAAAAAEAQEAAAAI+wIAAE0BApAAAAAAUgMAALwBAegBAAAAnwEDAYIAAQACAxIDJgBIJwEYAAAAAAAAAAFJAAAAAAQBAQAAAAj7AgAATQECkAAAAABSAwAAvAEB6gEAAACfAQMBggABAAIDEgMoAEspARgAAAAAAAAAAUwAAAAAAwABAAAACPsCAABNAQLBAAAAAEcBAgAAAACAqQAAAakAAQCCAAIAAQMZAE4qARgAAAAAAAAAAE8AAAAADAAAAQIAcaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwJNAQAxBAAAAKQCAQAAAABAbwQFALwCAhYDAAAAnwIDAqQDBwAAAGBATQUCoQgAAABNBAV2CQAAAJ8DAgKkBAcAAABgQE0GAqEIAAAATQUGHwoAAACfBAICpAUHAAAAYEBNBwKhCAAAAE0GB9ILAAAAnwUCAqQGBwAAAGBATQkCvQ0AAABNCAlBDgAAAE0HCAoMAAAAnwYCAqQHBwAAAGBATQoCvQ0AAABNCQpBDgAAAE0ICUEOAAAAnwcCAqQIBwAAAGBATQsCvQ0AAABNCgtBDgAAAE0JCucPAAAAnwgCAv8JBQAAAAAAxgoAADAKCcEQAAAATQoE7xEAAACfCgECMAoJQBIAAADAChMAEgACABIAAQASAAkAEgAIABIABwASAAYAMAoJExQAAADAChUAEgAJABIAAwAwCgl2FgAAAMAKFwASAAkAMAoJgxgAAADAChkAEgAJABIABQAwCglmGgAAAMAKGwASAAkAMAoJTBwAAADACh0AEgAJADAKCcUeAAAAwAofABIACQAwCgmHIAAAAMAKIQASAAkAMAoJESIAAACCCQIAIwMrBAAAAEADLAMtAy4DLwMwBAAAYEADMQMyAzMDNAM1AzYDNwM4AxkDBwMWBgADEwYEAyAGBQMYBgYDJQYHAxUGCAMnBgkDKQYKAyoIAAQFBgcICQoBAAEYAAEAAAAAAAEAAQAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAABAABAAABAAAAAAEAAAAAAAAAABMAAAAAEwAAAAcAAAAABwAAAAMAAAADAAAAAwAAAAMBAAAAAAvj7oCOrBtkrNEq6hqp8dHDLBbKQqWOegDHquNPGg4my0y3igGq/Ecr

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players").LocalPlayer
local v_u_2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v_u_2.Std.Maid)
local v4 = require(v_u_2.Std.Signal)
local v_u_5 = require(v_u_2.Std.Audio)
local v_u_6 = require(v_u_2.Game.WorldMarker.WorldMarkerSystem)
local v_u_7 = require(v_u_2.Game.WorldMarker.WorldMarker)
local v_u_8 = require(v_u_2.Game.WorldMarker.WorldMarkerGroup)
local v_u_22 = {
	["_maid"] = nil,
	["onCloseClicked"] = v4.new(),
	["init"] = function()
		-- upvalues: (copy) v_u_2, (copy) v_u_1, (copy) v_u_22, (copy) v_u_8, (copy) v_u_7, (copy) v_u_6
		local v9 = v_u_2.StarterGui:FindFirstChild("ContextMessageGui")
		v9.Parent = v_u_1.PlayerGui
		v_u_22.gui = v9
		local v10 = v_u_8.new()
		v10:SetEnabled(false)
		v_u_22._worldMarkerGroup = v10
		local v11 = v_u_7.new()
		v11:SetScreenGui(v_u_6.gui)
		v11:SetIcon(5920742944)
		v11.FrameInner.ImageColor3 = Color3.fromRGB(255, 203, 70)
		v10:Add(v11)
		v_u_6.addGroup(v10)
		v_u_22._worldMarker = v11
	end,
	["open"] = function()
		-- upvalues: (copy) v_u_22, (copy) v_u_3
		local v12 = v_u_22._maid == nil
		assert(v12)
		local v13 = v_u_3.new()
		v_u_22._maid = v13
		local v_u_14 = v_u_22.gui
		v_u_14.Enabled = true
		v13:GiveTask(function()
			-- upvalues: (copy) v_u_14
			v_u_14.Enabled = false
		end)
		v13:GiveTask(function()
			-- upvalues: (ref) v_u_22
			v_u_22.setWorldMarkerEnabled(false)
		end)
		v13:GiveTask(v_u_14.Container.Close.MouseButton1Down:Connect(function()
			-- upvalues: (ref) v_u_22
			v_u_22.onCloseClicked:Fire()
			v_u_22.close()
		end))
	end,
	["close"] = function()
		-- upvalues: (copy) v_u_22
		local v15 = v_u_22._maid ~= nil
		assert(v15)
		local v16 = v_u_22._maid
		v_u_22._maid = nil
		v16:Destroy()
	end,
	["setMessage"] = function(p17)
		-- upvalues: (copy) v_u_22, (copy) v_u_5
		local v18 = v_u_22.gui
		v18.Container.Container.Message.Text = p17
		v_u_5.ObjectLocal(v18, 5764937912)
	end,
	["setWorldMarkerEnabled"] = function(p19)
		-- upvalues: (copy) v_u_22
		v_u_22._worldMarkerGroup:SetEnabled(p19)
	end,
	["setWorldMarkerPosition"] = function(p20)
		-- upvalues: (copy) v_u_22
		v_u_22._worldMarker:SetPosition(p20)
	end,
	["setWorldMarkerSizes"] = function(p21)
		-- upvalues: (copy) v_u_22
		v_u_22._worldMarker:SetSizes(p21)
	end,
	["isOpen"] = function()
		-- upvalues: (copy) v_u_22
		return v_u_22._maid ~= nil
	end
}
return v_u_22
