-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMgDWlzU21hbGxTY3JlZW4JQ29udGFpbmVyBVVEaW0yA25ldwRTaXplCVVJUGFkZGluZwRVRGltDVBhZGRpbmdCb3R0b20Xc2hvdWxkSGF2ZVRvdWNoQ29udHJvbHMKdXBkYXRlU2l6ZQlIb3RiYXJHdWkGc2NyaXB0BlBhcmVudANSZXMLTG9jYWxQbGF5ZXIJUGxheWVyR3VpDERpc3BsYXlPcmRlcgNndWkESXRlbQVDbG9uZQdEZXN0cm95C3ByZXNldEZyYW1lHGdldFZpZXdwb3J0U2l6ZUNoYW5nZWRTaWduYWwHQ29ubmVjdARpbml0BGdhbWUHUGxheWVycwpHZXRTZXJ2aWNlEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUERXpVaQVVdGlscwADBgACAAAAT/sBAABNAAF5AAAAAJ8AAQIOABcA+wEBAE0AAW8BAAAApAEEAAAMIIBvAgUAjAMAAIwEAQCMBQAAnwEFAjABAC8GAAAA+wEBAE0AAWIHAAAApAEJAAAMgIBvAgoAjAMAAJ8BAwIwAQDsCwAAAIIAAQD7AQAATQABgAwAAACfAAECDgAXAPsBAQBNAAFvAQAAAKQBBAAADCCAbwIFAIwDAACMBAEAjAUAAJ8BBQIwAQAvBgAAAPsBAQBNAAFiBwAAAKQBCQAADICAbwIKAIwDAACfAQMCMAEA7AsAAACCAAEA+wEBAE0AAW8BAAAApAEEAAAMIIBvAg0AjAMAAIwEAQCMBQAAnwEFAjABAC8GAAAA+wEBAE0AAWIHAAAApAEJAAAMgIBvAgoAjAMAAJ8BAwIwAQDsCwAAAIIAAQAOAwEDAgMDAwQEAAwggAJmZmZmZmbmPwMFAwYDBwQADICAAnsUrkfheoQ/AwgDCQKamZmZmZnZPwARCgEYAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAACAAAAAAAAAAAAAAABAAAAAAAAAAAAAhIAAAAABgADAAAANKQDAgAAABBATQIDJAMAAABNAQJNBAAAAE0AAfsAAAAA+wMAAE0CAzEFAAAATQECmQYAAAAwAQAkAwAAAIwBCwAwAQDLBwAAAPsBAQAwAAF/CAAAAE0CAG8KAAAATQECygkAAAC8AQE6CwAAAJ8BAgJNAwBvCgAAAE0CA8oJAAAAvAICUAwAAACfAgIB+wIBADABAvENAAAA2QIAABICAgASAAAA+wQCAE0DBOsOAAAAnwMBAlIFAgC8AwPHDwAAAJ8DAwFSAwIAnwMBAYIAAQAQAwsDDAQAABBAAw0DDgMPAxADEQMSAxMDAgMUAxUDFgMXAxgBAAcZARgAAAAAAAAAAAEAAAAAAAABAAABAAACAAAAAAAAAQAAAAAAAAEAAAIAAAwAAAAAAAAAAQABCAAAAAAFAAABAgAdowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBAQAAAABAbwMEALwBARYDAAAAnwEDAqQCBgAAAFBATQQBLQcAAABNAwShCAAAAJ8CAgL/AwMAAAAAAMAECQASAAAAEgADABIAAgAwBAMTCgAAAIIDAgALAxoEAAAAQAMbAxwDHQMeBAAAUEADHwMgBgEDGQEBAQABGAABAAAAAAABAAAAAAABAAAAAAAAAgABAAAAAAAZAQAAAAACJ9Vw7i+GCQYVERp6toDn04KtFXdABDltDfYK/C6xfDmOdMrJ1oD6yA==

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players")
local v2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v2.EzUi.Utils)
local v_u_7 = {
	["init"] = function()
		-- upvalues: (copy) v_u_1, (copy) v_u_7, (copy) v_u_3
		local v_u_4 = script.Parent.Res.HotbarGui
		v_u_4.Parent = v_u_1.LocalPlayer.PlayerGui
		v_u_4.DisplayOrder = 11
		v_u_7.gui = v_u_4
		local v5 = v_u_4.Container.Item:Clone()
		v_u_4.Container.Item:Destroy()
		v_u_7.presetFrame = v5
		local function v6()
			-- upvalues: (ref) v_u_3, (copy) v_u_4
			if v_u_3.isSmallScreen() then
				v_u_4.Container.Size = UDim2.new(0.7, 0, 1, 0)
				v_u_4.UIPadding.PaddingBottom = UDim.new(0.01, 0)
				return
			elseif v_u_3.shouldHaveTouchControls() then
				v_u_4.Container.Size = UDim2.new(0.7, 0, 1, 0)
				v_u_4.UIPadding.PaddingBottom = UDim.new(0.01, 0)
			else
				v_u_4.Container.Size = UDim2.new(0.4, 0, 1, 0)
				v_u_4.UIPadding.PaddingBottom = UDim.new(0.01, 0)
			end
		end
		v_u_3.getViewportSizeChangedSignal():Connect(v6)
		v6()
	end
}
return v_u_7
