-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMwBERhbXAERnJlcQlTZXRUYXJnZXQEdGljawtPYmplY3RMb2NhbAtNYXhEaXN0YW5jZQVkZWxheQZVcGRhdGUGQ0ZyYW1lA25ldwZQYXJlbnQWR2V0UGxheWVyRnJvbUNoYXJhY3RlcgpTbGFtUGxheWVyDHNldG1ldGF0YWJsZQRNYWlkBlBpc3Rvbg5GaW5kRmlyc3RDaGlsZAxQaXN0b25PcmlnaW4ISW5zdGFuY2UEUGFydAROYW1lCEFuY2hvcmVkDFRyYW5zcGFyZW5jeQpDYW5Db2xsaWRlC1JlbW90ZUV2ZW50DFdhaXRGb3JDaGlsZAZhc3NlcnQJSGVhcnRiZWF0B0Nvbm5lY3QIR2l2ZVRhc2sHVG91Y2hlZA9Cb2R5SGVpZ2h0U2NhbGUFVmFsdWUIUm9vdFBhcnQJQ2hhcmFjdGVyCEh1bWFub2lkCkZpcmVTZXJ2ZXIHRGVzdHJveQRnYW1lB1BsYXllcnMKR2V0U2VydmljZQpSdW5TZXJ2aWNlEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUDU3RkBUF1ZGlvBlNwcmluZwdfX2luZGV4AAgDAAIAAAAQ+wAAAG8BAAAwAQCIAQAAAPsAAACMAQoAMAEAtQIAAAD7AAAAjAIAALwAAJcDAAAAnwADAakAAQDeAAEAggABAAQCzczMzMzM7D8DAQMCAwMAMwABGAAAAAABAAAAAQAAAAABAAE0AAAAAAkABgAAADykAAEAAAAAQJ8AAQL7AgAAJgEAAowCAwBgAiIAAQAAAN4AAAD7AQEAbwICADACAYgDAAAA+wEBAIwCMgAwAgG1BAAAAPsBAQCMAwEAvAEBlwUAAACfAQMB+wICAE0BAtEGAAAA+wIDAG8DBwDiBAkAjAVgADAFBJkIAAAAnwEEAakBAADeAQQApAELAAAAoECMAgEA2QMAABICAQASAgQAnwEDAfsBAQC8AQEmDAAAAJ8BAgL7AgMA+wUFAE0EBYUNAAAApAUPAAA40ICMBgAA9QgRAVsHCBCMCAAAnwUEAgkDBAUwAwKFDQAAAIIAAQASAwQEAAAAQAJmZmZmZmbmPwMBAwIDAwMFAgAAUPR02PNBAwYFAQgDBwQAAKBAAwgDCQMKBAA40IACAAAAAAAAJEACAAAAAAAA8D8BACoAARgAAAABAAAAAAEBAAAAAQAAAAEAAAAAAQAAAAAAAAAAAAEAAQAAAAAAAAcAAAABAAAAAAAAAAAAAAAAAAErAAAAAAcBBQAAACP7AQAAvAEBJgAAAACfAQIC+wIBAE0EACQBAAAAvAICiQIAAACfAgMCDgIXAKQDBAAAADBAnwMBAvsFAgAmBAMFbwUFAGAFEAAEAAAAbwQGAGAEDQABAAAAbwQHAGABCgAEAAAA+wQDACoEBwAAAACA3gMCAPsEBABSBgIAvAQEVAgAAACfBAMBggABAAkDCAMLAwwDBAQAADBAAgAAAAAAAPg/ApqZmZmZmak/AmZmZmZmZu4/Aw0APwABGAAAAAABAAAAAAABAQAAAgAAAAABAAABAAABAAACAQAAAAADQAAAAAANAQYAAABr/wECAAAAAAD7BAAAnj0BBAQAAABSAwEApAIBAAAAAECfAgMB+wMBAE0CA+8CAAAAnwIBAjACAXYDAAAAbwQEALwCAAMFAAAAnwIDAm8FBgC8AwADBQAAAJ8DAwIrAxcApAQIAAAIcIBvBQkAnwQCAlIDBABvBAYAMAQDugoAAACpBAEAMAQDRQsAAACMBAEAMAQD2QwAAACpBAAAMAQD0w0AAABNBAKFDgAAADAEA4UOAAAAMAADJA8AAABvBhAAvAQA0xEAAACfBAMCMAQBIRAAAAD7BQIATQQF7wIAAACMBQAAjAYAAIwHAQCMCAAAnwQFAqkGAQC7AQYCpAUTAAAAIEGfBQIBpAUVAAAAQEGfBQECqQYBAE0HAXYDAAAA+woDAE0JCv0WAAAA2QsAABIBBf8SAAQAEgIEABIAAgASAQb/EgED/7wJCccXAAAAnwkDALwHB/0YAAAAnwcAAYwHAABNCAF2AwAAAE0KAiwZAAAA2QwBABIABAASAgUAEgEH/xIBBv8SAAEAvAoKxxcAAACfCgMAvAgI/RgAAACfCAABwQMAAIIBAgAaAw4EAAAAQAMKAw8DEAMRAxIDEwQACHCAAxQDFQMWAxcDGAMJAwsDGQMaAxsEAAAgQQMEBAAAQEEDHAMdAx4DHwIBAgsKARgAAAEAAAAAAAACAAAAAAACAAAAAgAAAAEBAAAAAAEAAAEAAAEAAAEAAAEAAAABAAMAAAAAAAIAAAAAAAAABAAAAAAEAAABAQAAAAAAAAAAAAAAAAAAAAAAFAEAAAAAAAAAAAAAAAAAAAARAAwAAAAAAwACAAAAD/sBAABNAAFnAAAAAIwBAQAwAQDsAQAAAPsBAQBNAAHRAgAAAPsCAABNAQJGAwAAAG8CBACfAAMBggABAAUDIAMhAwUDIgIAAJAXy97zQQBXAAEYAAAAAAAAAQAAAAAAAAABWAAAAAAHAgEAAAAdTQIBaQAAAABNAwIBAQAAAE0EA2cCAAAAbwUDADAFBOwEAAAA+wUAAE0EBdEFAAAATQUDRgYAAABvBgcAnwQDAaQECQAAAIBAjAUEANkGAAASAAMAEgIAAJ8EAwFNBAAhCgAAALwEBGsLAAAAnwQCAYIAAQAMAyMDJAMgAjMzMzMzM9M/AyEDBQMiAgAAYALL3vNBAwcEAACAQAMZAyUBBFINARgAAAEAAQAAAAABAAAAAAAAAQAAAAAAAAQAAAAAAVMAAAAAAwEAAAAACU0BAHYAAAAAvAEBUAEAAACfAQIBxgEAADABAHYAAAAAggABAAIDDwMmAF0mARgAAAAAAAEAAAFeAAAAAAgAAAECAD2jAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIBAAAAAEBvBAUAvAICFgMAAACfAgMCpAMHAAAAYEBNBQKhCAAAAE0EBXYJAAAAnwMCAqQEBwAAAGBATQYCoQgAAABNBQbSCgAAAJ8EAgKkBQcAAABgQE0HAqEIAAAATQYHIgsAAACfBQIC/wYDAAAAAAAwBgZuDAAAAMAHDQASAAYAEgADABIABQASAAEAEgAEABIAAAAwBwbvDgAAAMAHDwASAAQAMAcGVBAAAADABxEAMAcGUBIAAACCBgIAEwMnBAAAAEADKAMpAyoDKwMsBAAAYEADLQMPAy4DLwMwBgMDCgYFAw0GBgMmAwMFBgEAARgAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAgABAAEAAAAAAAAAAEcAAAALAAAEAQAAAAAHPhNxUanxAd0M1xvFaYGGayOTDraksTr3teitUY+5bYKJfjNbxk2FyQ==

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players")
local v_u_2 = game:GetService("RunService")
local v3 = game:GetService("ReplicatedStorage")
local v_u_4 = require(v3.Std.Maid)
local v_u_5 = require(v3.Std.Audio)
local v_u_6 = require(v3.Std.Spring)
local v_u_7 = {}
v_u_7.__index = v_u_7
function v_u_7.new(p8)
	-- upvalues: (copy) v_u_7, (copy) v_u_4, (copy) v_u_6, (copy) v_u_2, (copy) v_u_5, (copy) v_u_1
	local v_u_9 = {}
	local v10 = v_u_7
	setmetatable(v_u_9, v10)
	v_u_9.Maid = v_u_4.new()
	local v_u_11 = p8:FindFirstChild("Piston")
	local v_u_12 = p8:FindFirstChild("PistonOrigin")
	if not v_u_12 then
		v_u_12 = Instance.new("Part")
		v_u_12.Name = "PistonOrigin"
		v_u_12.Anchored = true
		v_u_12.Transparency = 1
		v_u_12.CanCollide = false
		v_u_12.CFrame = v_u_11.CFrame
		v_u_12.Parent = p8
	end
	v_u_9.RemoteEvent = p8:WaitForChild("RemoteEvent")
	local v_u_13 = v_u_6.new(0, 0, 1, 0)
	assert(true)
	local v_u_14 = tick()
	local v_u_15 = true
	v_u_9.Maid:GiveTask(v_u_2.Heartbeat:Connect(function()
		-- upvalues: (ref) v_u_14, (copy) v_u_13, (ref) v_u_5, (copy) v_u_11, (ref) v_u_15, (ref) v_u_12
		local v16 = tick()
		if v16 - v_u_14 > 3 then
			v_u_14 = v16
			v_u_13.Damp = 0.7
			v_u_13.Freq = 50
			v_u_13:SetTarget(1)
			v_u_5.ObjectLocal(v_u_11, 5327245125, {
				["MaxDistance"] = 96
			})
			v_u_15 = false
			delay(1, function()
				-- upvalues: (ref) v_u_13, (ref) v_u_15
				v_u_13.Damp = 0.9
				v_u_13.Freq = 10
				v_u_13:SetTarget(0)
				v_u_15 = true
			end)
		end
		local v17 = v_u_13:Update()
		v_u_11.CFrame = v_u_12.CFrame * CFrame.new(0, (1 - v17) * 10, 0)
	end))
	local v_u_18 = 0
	v_u_9.Maid:GiveTask(v_u_11.Touched:Connect(function(p19)
		-- upvalues: (copy) v_u_13, (ref) v_u_1, (ref) v_u_18, (ref) v_u_15, (copy) v_u_9
		local v20 = v_u_13:Update()
		local v21 = v_u_1:GetPlayerFromCharacter(p19.Parent)
		if v21 then
			local v22 = tick()
			if v22 - v_u_18 > 1.5 and (v20 > 0.05 and (v20 < 0.95 and v_u_15 == false)) then
				v_u_18 = v22
				v_u_9:SlamPlayer(v21)
			end
		end
	end))
	return v_u_9
end
function v_u_7.SlamPlayer(p23, p24)
	-- upvalues: (copy) v_u_5
	local v_u_25 = p24.Character.Humanoid
	v_u_25.BodyHeightScale.Value = 0.3
	v_u_5.ObjectLocal(v_u_25.RootPart, 5333889062)
	delay(4, function()
		-- upvalues: (copy) v_u_25, (ref) v_u_5
		v_u_25.BodyHeightScale.Value = 1
		v_u_5.ObjectLocal(v_u_25.RootPart, 5333889401)
	end)
	p23.RemoteEvent:FireServer()
end
function v_u_7.Destroy(p26)
	p26.Maid:Destroy()
	p26.Maid = nil
end
return v_u_7
