-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgN7DVNob3J0ZXN0QW5nbGUEVW5pdAVDcm9zcwZDRnJhbWUKZnJvbU1hdHJpeAZMb29rQXQFVmFsdWUKU2V0RW5hYmxlZAlTZXRBbmdsZXMLU2V0RGlzdGFuY2UGYXNzZXJ0DHNldG1ldGF0YWJsZQ5TcG90bGlnaHRNb3RvcgNuZXcETWFpZAhJbnN0YW5jZQpBdHRhY2htZW50BVBhcnQxBlBhcmVudApQb2ludExpZ2h0BVJhbmdlB0VuYWJsZWQEQmVhbQVQYXJ0MAVMaWdodAtBdHRhY2htZW50MQdWZWN0b3IzE1NwcmluZ01vdXNlTG9jYXRpb24MU3ByaW5nQW5nbGVzF0xhc3RVcGRhdGVBbmdsZURpc3RhbmNlC1JlbW90ZUV2ZW50DFdhaXRGb3JDaGlsZAdPblZhbHVlGEdldFByb3BlcnR5Q2hhbmdlZFNpZ25hbAdDb25uZWN0CEdpdmVUYXNrCkFuZ2xlVmFsdWUNRGlzdGFuY2VWYWx1ZQtQb2xpY2VWYWx1ZQhWZWhpY2xlcwl3b3Jrc3BhY2UJQ2hhcmFjdGVyCklnbm9yZUxpc3QbVHJhbnNmb3JtTG9jYWxNb3VzZVBvc2l0aW9uAXgBeRJWaWV3cG9ydFBvaW50VG9SYXkhUmF5SWdub3JlTm9uQ29sbGlkZVdpdGhJZ25vcmVMaXN0Bk9yaWdpbglEaXJlY3Rpb24bUHJvamVjdE1vdXNlTG9jYXRpb25Ub1dvcmxkDFRvdWNoRW5hYmxlZAxWaWV3cG9ydFNpemUBWAFZEEdldE1vdXNlTG9jYXRpb24GVXBkYXRlCUhlYXJ0YmVhdApVcGRhdGVMb29wBEVudW0ITWF0ZXJpYWwETmVvbgdQbGFzdGljDUVWRU5UX0RJU0FCTEUKRmlyZVNlcnZlcgtVbmhvb2tMb2NhbAxFVkVOVF9FTkFCTEUJSG9va0xvY2FsDVJlcXVlc3RUb2dnbGUTVXBkYXRlTW91c2VQb3NpdGlvbghQb3NpdGlvbgpGYWtlQ2lyY2xlB0Rlc3Ryb3kJTG9jYWxNYWlkBFBhcnQEU2l6ZQhBbmNob3JlZAxUcmFuc3BhcmVuY3kKQ2FuQ29sbGlkZQVEZWNhbBdyYnhhc3NldGlkOi8vNTQ3Nzk5OTExNQdUZXh0dXJlCE5vcm1hbElkBUZyb250BEZhY2UJU2V0VGFyZ2V0CERpc3RhbmNlC0F0dGFjaG1lbnQwDVdvcmxkUG9zaXRpb24JTWFnbml0dWRlCkxvb2tWZWN0b3INVG9PYmplY3RTcGFjZRBUb0V1bGVyQW5nbGVzWFlaBHRpY2sbRVZFTlRfVVBEQVRFX0FOR0xFX0RJU1RBTkNFEmZyb21FdWxlckFuZ2xlc1hZWgFaAkMxAXANVGV4dHVyZUxlbmd0aAZXaWR0aDEISHVtYW5vaWQORmluZEZpcnN0Q2hpbGQIUm9vdFBhcnQcRG9lc0ZpeGVkQ29uZUludGVyc2VjdFNwaGVyZRJJc0xvY2FsSW5TcG90bGlnaHQEZ2FtZQdQbGF5ZXJzCkdldFNlcnZpY2ULTG9jYWxQbGF5ZXIKUnVuU2VydmljZQ1DdXJyZW50Q2FtZXJhEFVzZXJJbnB1dFNlcnZpY2URUmVwbGljYXRlZFN0b3JhZ2UHcmVxdWlyZQdSYXlDYXN0Bk1vZHVsZQNTdGQGU3ByaW5nBE1hdGgSU3BvdGxpZ2h0Q29uc3RhbnRzBnNjcmlwdAdfX2luZGV4ABcHAgAAAAAGJgYAAZUFBgAhBAUBeAMEAEMCAwGCAgIAAgIYLURU+yEJQAIYLURU+yEZQAATAQEYAAAAAAAAFAAAAAAJAgAAAAASJgMBAE0CAwcAAAAAbwUBALwDArsCAAAAnwMDAlIGAgC8BAO7AgAAAJ8EAwKkBQUAABAwgFIGAABSBwMAUggEAJ8FBACCBQAABgMCBwAAgD8AAAAAAAAAAAAAAAADAwMEAwUEABAwgAAXBgEYAAAAAQAAAAEAAAACAAAAAAAAGAAAAAAEAAIAAAAI+wAAAPsDAQBNAgPsAAAAALwAAJ4BAAAAnwADAYIAAQACAwcDCABFAAEYAAAAAAAAAAFGAAAAAAQAAgAAAAj7AAAA+wMBAE0CA+wAAAAAvAAAOwEAAACfAAMBggABAAIDBwMJAEkAARgAAAAAAAAAAUoAAAAABAACAAAACPsAAAD7AwEATQID7AAAAAC8AACYAQAAAJ8AAwGCAAEAAgMHAwoATQABGAAAAAAAAAABTgAAAAANAQQAAADHAbsBAANSAgAApAEBAAAAAECfAQIB/wEFAAAAAAD7BAAAnj0BBAQAAABSAwEApAIDAAAAIECfAgMBMAABCQQAAAD7AwEATQID7wUAAACfAgECMAIBdgYAAACkAggAABRwgG8DCQCfAgICMAIBDQkAAABNBAEJBAAAAE0DBLEKAAAAMAMCJAsAAACkAwgAABRwgG8EDACfAwICjAQgADAEAwYNAAAAqQQAADAEA/AOAAAATQQBDQkAAAAwBAMkCwAAADADATkMAAAATQgBCQQAAABNBwg8EAAAAE0GByQLAAAATQUGDxEAAABNBAWaDwAAADACBC8SAAAAMAQBmg8AAAD7BgIATQUG7wUAAABMNgACpAYUAAAUMIGfBgECTDYAAqQHFAAAFDCBnwcBAm8IFQCMCRQAnwUFAjAFAecWAAAA+wYCAE0FBu8FAAAATDYAAqQGFAAAFDCBnwYBAkw2AAKkBxQAABQwgZ8HAQJvCBUAjAkUAJ8FBQIwBQGbFwAAAEw2AAKkBxQAABQwgZ8HAQK8BQE7GAAAAJ8FAwGMBwAAvAUBmBkAAACfBQMBqQcAALwFAZ4aAAAAnwUDAYwFAAAwBQGiGwAAAG8HHAC8BQDTHQAAAJ8FAwIwBQEhHAAAAG8HHgC8BQDTHQAAAJ8FAwIwBQF/HgAAAE0GAXYGAAAAbwofALwIBZQgAAAAnwgDAtkKAAASAAEAEgAFALwICMchAAAAnwgDALwGBv0iAAAAnwYAAW8IIwC8BgDTHQAAAJ8GAwJNBwF2BgAAAG8LHwC8CQaUIAAAAJ8JAwLZCwEAEgABABIABgC8CQnHIQAAAJ8JAwC8Bwf9IgAAAJ8HAAFvCSQAvAcA0x0AAACfBwMCTQgBdgYAAABvDB8AvAoHlCAAAACfCgMC2QwCABIAAQASAAcAvAoKxyEAAACfCgMAvAgI/SIAAACfCAABbwolALwIANMdAAAAnwgDAjAIAbglAAAA/wgAAAIAAACkCigAAABwQk0JCqImAAAA+wsDAE0KC2kpAAAAxQgJAwEAAAAwCAHKKgAAAIIBAgArAwsEAAAAQAMMBAAAIEADDQMOAw8DEAQAFHCAAxEDEgMTAxQDFQMWAxcDGAMZAxoDGwQAFDCBApqZmZmZmek/AxwDHQMJAwoDCAMeAx8DIAMhAwcDIgMjAyQDJQMmAycDKAMpBAAAcEIDKgMrAwIDBCMOARgAAAAAAAEAAQAAAAAAAAIAAQAAAAAAAgAAAAEAAQAAAAAAAgAAAAEAAAEAAAEAAAABAAIAAAAAAAAAAAABAAEAAgAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAACAAAAAAAAAQAAAAEAAAACAAABAAAAAAACAAAAAQABAAAAAAAAAAAAAAAAAAADAAAAAQAAAAAAAAAAAAAAAAAAAwAAAAEAAAAAAAAAAAAAAAAAAAQAAAAAAAIAAAAAAAAAAAAAAAACJAAAAAACAgAAAAABggECAAAAVywBGABYAAAAAAkCAgAAABr7AgAATQQBmQAAAABNBQGYAQAAALwCAkYCAAAAnwIEAvsEAQBNAwTIAwAAAE0EAkMEAAAATQUCYQUAAACMBucDTQcAygYAAACfAwUEUggEALwGAIEHAAAAnwYDAlIHBgBSCAUAggcDAAgDLQMuAy8DMAMxAzIDKwMsAFozARgAAAAAAAAAAAIAAAAAAAAAAAAAAQAAAAEAAFsAAAAABwECAAAAG8YBAAD7AwAATQIDfwAAAAAOAhAA+wMBAE0CA7ABAAAATQUCeQMAAABbBAUCTQYCeAUAAABbBQYEjAYAAEw2AAKkAwgAABxggJ8DBAJSAQMAggECAPsCAAC8AgIGCQAAAJ8CAgJSAQIAggECAAoDNAM1AgAAAAAAAOA/AzYCAAAAAAAA7D8DNwMbAw4EABxggAM4AGE4ARgAAQAAAAEAAAIAAAAAAAAAAAAAAAACAAAAAAJiAAAAAAIAAQAAAAX7AAAAvAAAJgAAAACfAAIBggABAAEDOQBuAAEYAAAAAAFvAAAAAAYCAQAAACgOAQ0ATQIAdgAAAAD7BAAATQME/QEAAADZBQAAEgAAALwDA8cCAAAAnwMDAjADAhUDAAAAZQAFAE0CAHYAAAAAxgMAADADAhUDAAAATQIAmgQAAAAwAQLwBQAAAE0CADkGAAAAMAEC8AUAAABNAwCaBAAAAE0CAyQHAAAADgEDAKQDCwAKJIDAKwMCAKQDDQAMJIDAMAMCLQkAAACCAAEADgMPAzoDIwM7AxcDFgMUAxMDPAM9Az4ECiSAwAM/BAwkgMABCWwIARgAAQAAAAAAAAAAAAAAAAQAAAAAAgAAAAEAAAABAAAAAAAAAAAAAAABbQAAAAAFAQEAAAAdTQIAfwAAAABNAQLsAQAAAA4BDABNAQAhAgAAAPsEAABNAwTbAwAAALwBAWsEAAAAnwEDAbwBACkFAAAAnwECAYIAAQBNAQAhAgAAAPsEAABNAwSYBgAAALwBAWsEAAAAnwEDAbwBAMkHAAAAnwECAYIAAQAIAyEDBwMfA0ADQQNCA0MDRAB4RQEYAAAAAAABAAAAAAAAAAEAAAACAAAAAAAAAAEAAAJ5AAAAAAIAAQAAAAX7AAAAvAAAlQAAAACfAAIBggABAAEDRgCSAQABGAAAAAABkwAAAAACAAEAAAAK+wEAAE0AAQ0AAAAATDYAAqQBAwAACBCAnwEBAjABADsEAAAAggABAAUDEQMbAw4EAAgQgANHAJUBAAEYAAAAAAAAAAAAAZYAAAAAAgABAAAAC/sBAABNAAFVAAAAALwAAFABAAAAnwACAfsAAADGAQAAMAEAVQAAAACCAAEAAgNIA0kAmAEAARgAAAAAAAABAAAAAZkAAAAACAECAAAAXE0EAHYAAAAATQMExgEAAABHAwIAAAAAAKkCAAGpAgEAuwECAqQBAwAAACBAnwECAU0BAHYAAAAA+wMAAE0CA+8EAAAAnwIBAjACAcYBAAAApAEGAAAQUIBvAgcAnwECAm8CCAAwAgEvCQAAAKkCAQAwAgFFCgAAAIwCAQAwAgHZCwAAAKkCAAAwAgHTDAAAAKQCDgAAANBAMAIBJA8AAACkAgYAABBQgG8DEACfAgICbwMRADADAk8SAAAApAMWABVQMMEwAwIFFwAAAG8DGAAwAwLZCwAAADABAiQPAAAAMAEAVRkAAABNBAB2AAAAAE0DBMYBAAAA+wYBAE0FBv0aAAAA2QcAABIAAAC8BQXHGwAAAJ8FAwC8AwP9HAAAAJ8DAAFNBAB2AAAAAE0DBMYBAAAA2QUBABIAAAC8AwP9HAAAAJ8DAwFNBAB2AAAAAE0DBMYBAAAA2QUCABIAAAC8AwP9HAAAAJ8DAwGCAAEAHQMPA0oDCwQAACBAAw4DEAQAEFCAA0sHAACAQgAAgELNzMw9AAAAAANMA00DTgNPAykEAADQQAMTA1ADUQNSAzwDUwNUBBVQMMEDVQIAAAAAAADgPwNIAzoDIwMkAwwNDoEBRAEYAAAAAAAAAAAAAAAAAQAAAAAAAAACAAAAAQAAAQAAAQAAAQAAAQAAAAEAAAABAAABAAAAAQAAAQABAAIAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAMAAAAAAAAAAASCAAAAAAMBAAAAAAxNAgB2AAAAAE0BAsYBAAAARwEGAAAAAABNAQB2AAAAAMYCAAAwAgHGAQAAAIIAAQACAw8DSgCdAUIBGAAAAAAAAAEAAAAAAp4AAAAABQIAAAAAB00CAJsAAAAAUgQBALwCApcBAAAAnwIDAYIAAQACAx0DVgCiAQkBGAAAAAAAAAGjAAAAAAICAAAAAAMwAQBVAAAAAIIAAQABA1cApQEKARgAAAGmAAAAABEBAgAAAJYBvAMABgAAAACfAwIAvAEAQAEAAACfAQADTQYAmgIAAABNBQZrAwAAAE0EBeAEAAAAJgMBBE0EA6oFAAAAjAWgAGAFHgAEAAAAjASgAE0GAFUGAAAATQUGJAcAAABHBQYAAAAAAE0FAFUGAAAAxgYAADAGBSQHAAAATQcAmgIAAABNBgdrAwAAAE0FBuAEAAAATQoACQkAAABNCQqxCgAAAE0ICYULAAAATQcIaAwAAABbBgcIQwEFBmUAIQBNBwMHDQAAAAkGBwRNCQCaAgAAAE0ICWsDAAAATQcI4AQAAABDBQYHTQYAVQYAAACkBw8AADiwgFIIBQBDCQUCnwcDAjAHBoULAAAATQcAVQYAAABNBgckBwAAAKQHEQAAAABB8QYHAAcAAABNBgBVBgAAAKQHEQAAAABBMAcGJAcAAABSBwQAvAUAmBIAAACfBQMBTQcACQkAAABNBgexCgAAAE0FBoULAAAA+wcAAE0KAAkJAAAATQkKsQoAAABNCAk7EwAAAFIJAQCfBwMAvAUFRhQAAACfBQACvAYFhxUAAACfBgIETQkAmxYAAAC8CQkmFwAAAJ8JAgJNDAmZGAAAACYQBgyVDxAZIQ4PGngNDhlDCw0MNDYLBQcIAABSDAcAUg0IAKQKHAAAOLCBnwoEAlINCgC8CwA7HQAAAJ8LAwGkCx8AAADgQZ8LAQJNDQCiIAAAACYMCw1vDSEAYA0NAAwAAAAwCwCiIAAAAE0MACEiAAAA+w8BAE0ODzsjAAAAUg8KAFIQBAC8DAxrJAAAAJ8MBQGCAAEAJQM4AzMDFwNYA1kDWgNIAxMCAAAAAAAAZEADDQMSAwQDWwMCAw4EADiwgAMpBAAAAEEDCgNHA1wDXQMdAzkDLQIYLURU+yEJQAIYLURU+yEZQAMbBAA4sIEDCQNeBAAA4EEDHgIAAAAAAADAPwMfA18DQQCpAUYBGJYAAAAAAAIAAAAAAAABAAIAAAEBAAAAAAABAAAAAAMAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAwAAAAIAAAAAAAAAAAAAAAAAAAAAAAEAAAEAAAAAAgBRAAAAAAAAAACvAAABAAAAAgAAAQAAAAAAAQABAAAAAAAAAAAAAhQAAAAAEwECAAAAXk0BAJsAAAAAvAEBJgEAAACfAQICpAIEAAAMIIBNAwF5BQAAAE0EAXgGAAAATQUBewcAAACfAgQCTQMAVQgAAABNBAAJCQAAADACBMwKAAAATQYACQkAAABNBQY8CwAAAE0EBYUCAAAATQUADQwAAABNBwSRDQAAAE0JBGgOAAAAlQoDDwkICQpDBgcIMAYF4BAAAABNBQCaEQAAAJUGAw8wBgVPEgAAAE0FAJoRAAAAWwcDFD4GBxMwBgVLFQAAAE0GAHYWAAAATQUGxhcAAABHBSgAAAAAgE0GALgYAAAATQUG7BkAAAAOBSIA+wYAAE0FBmkaAAAARwUeAAAAAABvCBsAvAYFAxwAAACfBgMCRwYYAAAAAABNBwZGHQAAAEcHFAAAAAAATQgEkQ0AAABNCQRoDgAAAJUKAw9NCwc7HgAAAPsNAQBNDA1AHwAAAFINCABSDgkAUg8KAG8QIABSEQsAjBIDAJ8MBwIwDADrIQAAAIIAAQAiAx0DOQMEA2AEAAwggAM2AzcDYQNXAw0DYgMYAxEDYwNbAgAAAAAAABBAA1kDFwNkAgAAAAAAAAhAAgAAAAAAAABAA2UDDwNKAycDBwMqA2YDZwNoA0cDaQJQaesxxyjOPwNqAMwBOQEYAAAAAAABAAAAAAAAAAABAAIAAAABAAAAAAABAAAAAAAAAAAAAAEAAAAAAQAAAAAAAwAAAAAAAgAAAAABAAABAAEAAAABAAEAAQACAAEAAQIAAgAAAQEBAQEB+ggABs0AAAAAAwEAAAAADKkBAAAwAQDrAAAAAE0BAHYBAAAAvAEBUAIAAACfAQIBxgEAADABAHYBAAAAggABAAMDagMPA0kA9wFJARgAAAABAAAAAAEAAAH4AAAAABAAAAECAIIBowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAk0BADEEAAAApAIBAAAAAEBvBAUAvAICFgMAAACfAgMCpAQHAAAAYEBNAwRICAAAAKQEAQAAAABAbwYJALwEBBYDAAAAnwQDAqQFAQAAAABAbwcKALwFBRYDAAAAnwUDAqQGDAAAALBATQgFQA4AAABNBwgyDQAAAJ8GAgKkBwwAAACwQE0JBaEPAAAATQgJdhAAAACfBwICpAgMAAAAsEBNCgWhDwAAAE0JCiIRAAAAnwgCAqQJDAAAALBATQsFQA4AAABNCguMEgAAAJ8JAgLAChMAwAsUAKQMDAAAALBApA8XAAAAYEFNDg8kGAAAAE0NDh0VAAAAnwwCAv8NBQAAAAAAMA0NbhkAAADADhoAEgANABIABwASAAgAEgABADAODe8bAAAAwA4cADAODYEdAAAAwA4eABIAAwASAAYAMA4NQB8AAADADiAAEgAEABIAAwAwDg0GIQAAAMAOIgASAAIAMA4NniMAAADADiQAEgAMADAODcAlAAAAwA4mABIABwASAAIAMA4NyScAAADADigAMA4NKSkAAADADioAMA4NOysAAADADiwAMA4NmC0AAADADi4AEgALABIADAAwDg2VLwAAAMAOMAASAAEAEgAJADAODSYxAAAAwA4yADAODVAzAAAAgg0CADQDawQAAABAA2wDbQNuA28DKQQAAGBAA3ADcQNyA3MEAACwQAN0A3UDdgMPA3cDeAYABgEDeQN6BAAAYEEDEwN7BgUDDgYGAywGBwMzBggDOAYKAwgGCwNFBg8DRAYQA0IGEQMJBhIDCgYTA0YGFAM5BhUDSQ8AAQUGBwgKCw8QERITFBUBAAEYAAEAAAAAAAEAAQAAAAAAAQAAAAEAAAAAAAEAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAAIBAgAAAAAAAAAAAIAAQABAAAAAAAANAAAAwAAAAAHAAAAAAsAAAAMAAAACQAAAAAcAAAFAAADAAAEAAAAACMAAAAAKwAABQEAAAAAFjI5Y6TXxGKwAP0JMMaECtuzS2sGz5f7Qs90UxSpnwAG29xJL56DIWE=

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players").LocalPlayer
local v_u_2 = game:GetService("RunService")
local v_u_3 = workspace.CurrentCamera
local v_u_4 = game:GetService("UserInputService")
local v5 = game:GetService("ReplicatedStorage")
local v_u_6 = require(v5.Module.RayCast)
local v_u_7 = require(v5.Std.Maid)
local v_u_8 = require(v5.Std.Spring)
local v_u_9 = require(v5.Module.Math)
local function v_u_15(p10, p11)
	local v12 = (p11 - p10).Unit
	local v13 = v12:Cross(Vector3.new(1, 0, 0))
	local v14 = v13:Cross(v12)
	return CFrame.fromMatrix(p10, v13, v14)
end
local v_u_16 = require(script.Parent.SpotlightConstants)
local v_u_17 = {}
v_u_17.__index = v_u_17
function v_u_17.new(p18)
	-- upvalues: (copy) v_u_17, (copy) v_u_7, (copy) v_u_8, (copy) v_u_1
	assert(p18)
	local v_u_19 = {}
	local v20 = v_u_17
	setmetatable(v_u_19, v20)
	v_u_19.SpotlightMotor = p18
	v_u_19.Maid = v_u_7.new()
	local v21 = Instance.new("Attachment")
	v_u_19.Attachment = v21
	v21.Parent = v_u_19.SpotlightMotor.Part1
	local v22 = Instance.new("PointLight")
	v22.Range = 32
	v22.Enabled = false
	v22.Parent = v_u_19.Attachment
	v_u_19.PointLight = v22
	local v23 = v_u_19.SpotlightMotor.Part0.Parent.Light.Beam
	v23.Attachment1 = v21
	v_u_19.Beam = v23
	v_u_19.SpringMouseLocation = v_u_8.new(Vector3.new(), Vector3.new(), 0.8, 20)
	v_u_19.SpringAngles = v_u_8.new(Vector3.new(), Vector3.new(), 0.8, 20)
	v_u_19:SetAngles((Vector3.new()))
	v_u_19:SetDistance(0)
	v_u_19:SetEnabled(false)
	v_u_19.LastUpdateAngleDistance = 0
	v_u_19.RemoteEvent = p18:WaitForChild("RemoteEvent")
	local v_u_24 = p18:WaitForChild("OnValue")
	v_u_19.OnValue = v_u_24
	v_u_19.Maid:GiveTask(v_u_24:GetPropertyChangedSignal("Value"):Connect(function()
		-- upvalues: (copy) v_u_19, (copy) v_u_24
		v_u_19:SetEnabled(v_u_24.Value)
	end))
	local v_u_25 = p18:WaitForChild("AngleValue")
	v_u_19.Maid:GiveTask(v_u_25:GetPropertyChangedSignal("Value"):Connect(function()
		-- upvalues: (copy) v_u_19, (copy) v_u_25
		v_u_19:SetAngles(v_u_25.Value)
	end))
	local v_u_26 = p18:WaitForChild("DistanceValue")
	v_u_19.Maid:GiveTask(v_u_26:GetPropertyChangedSignal("Value"):Connect(function()
		-- upvalues: (copy) v_u_19, (copy) v_u_26
		v_u_19:SetDistance(v_u_26.Value)
	end))
	v_u_19.PoliceValue = p18:WaitForChild("PoliceValue")
	v_u_19.IgnoreList = { workspace.Vehicles, v_u_1.Character }
	return v_u_19
end
function v_u_17.TransformLocalMousePosition(_, p27)
	return p27
end
function v_u_17.ProjectMouseLocationToWorld(p28, p29)
	-- upvalues: (copy) v_u_3, (copy) v_u_6
	local v30 = v_u_3:ViewportPointToRay(p29.x, p29.y)
	local _, v31, v32 = v_u_6.RayIgnoreNonCollideWithIgnoreList(v30.Origin, v30.Direction, 999, p28.IgnoreList)
	return p28:TransformLocalMousePosition(v31), v32
end
function v_u_17.GetMouseLocation(_)
	-- upvalues: (copy) v_u_4, (copy) v_u_3
	if not v_u_4.TouchEnabled then
		return v_u_4:GetMouseLocation()
	end
	local v33 = v_u_3.ViewportSize
	local v34 = v33.X * 0.5
	local v35 = v33.Y * 0.875
	return Vector3.new(v34, v35, 0)
end
function v_u_17.SetEnabled(p_u_36, p37)
	-- upvalues: (copy) v_u_2
	if p37 then
		p_u_36.Maid.UpdateLoop = v_u_2.Heartbeat:Connect(function()
			-- upvalues: (copy) p_u_36
			p_u_36:Update()
		end)
	else
		p_u_36.Maid.UpdateLoop = nil
	end
	p_u_36.Beam.Enabled = p37
	p_u_36.PointLight.Enabled = p37
	p_u_36.Beam.Parent.Material = p37 and Enum.Material.Neon or Enum.Material.Plastic
end
function v_u_17.RequestToggle(p38)
	-- upvalues: (copy) v_u_16
	if p38.OnValue.Value then
		p38.RemoteEvent:FireServer(v_u_16.EVENT_DISABLE)
		p38:UnhookLocal()
	else
		p38.RemoteEvent:FireServer(v_u_16.EVENT_ENABLE)
		p38:HookLocal()
	end
end
function v_u_17.HookLocal(p_u_39)
	-- upvalues: (copy) v_u_7, (copy) v_u_2
	local v40 = p_u_39.Maid.LocalMaid == nil
	assert(v40)
	p_u_39.Maid.LocalMaid = v_u_7.new()
	local v41 = Instance.new("Part")
	v41.Size = Vector3.new(64, 64, 0.1)
	v41.Anchored = true
	v41.Transparency = 1
	v41.CanCollide = false
	v41.Parent = workspace
	local v42 = Instance.new("Decal")
	v42.Texture = "rbxassetid://5477999115"
	v42.Face = Enum.NormalId.Front
	v42.Transparency = 0.5
	v42.Parent = v41
	p_u_39.FakeCircle = v41
	p_u_39.Maid.LocalMaid:GiveTask(v_u_2.Heartbeat:Connect(function()
		-- upvalues: (copy) p_u_39
		p_u_39:UpdateMousePosition()
	end))
	p_u_39.Maid.LocalMaid:GiveTask(function()
		-- upvalues: (copy) p_u_39
		p_u_39.Attachment.Position = Vector3.new()
	end)
	p_u_39.Maid.LocalMaid:GiveTask(function()
		-- upvalues: (copy) p_u_39
		p_u_39.FakeCircle:Destroy()
		p_u_39.FakeCircle = nil
	end)
end
function v_u_17.UnhookLocal(p43)
	if p43.Maid.LocalMaid ~= nil then
		p43.Maid.LocalMaid = nil
	end
end
function v_u_17.SetAngles(p44, p45)
	p44.SpringAngles:SetTarget(p45)
end
function v_u_17.SetDistance(p46, p47)
	p46.Distance = p47
end
function v_u_17.UpdateMousePosition(p48)
	-- upvalues: (copy) v_u_15, (copy) v_u_16
	local v49, v50 = p48:ProjectMouseLocationToWorld(p48:GetMouseLocation())
	local v51 = v49 - p48.Beam.Attachment0.WorldPosition
	local v52 = v51.Magnitude
	if v52 > 160 then
		v52 = 160
		if p48.FakeCircle.Parent ~= nil then
			p48.FakeCircle.Parent = nil
		end
		v49 = p48.Beam.Attachment0.WorldPosition + p48.SpotlightMotor.Part1.CFrame.LookVector * 160
	else
		local v53 = v51.Unit * v52 + p48.Beam.Attachment0.WorldPosition
		p48.FakeCircle.CFrame = CFrame.new(v53, v53 + v50)
		if p48.FakeCircle.Parent ~= workspace then
			p48.FakeCircle.Parent = workspace
		end
	end
	p48:SetDistance(v52)
	local v54, v55, v56 = p48.SpotlightMotor.Part1.CFrame:ToObjectSpace(v_u_15(p48.SpotlightMotor.Part1.Position, v49)):ToEulerAnglesXYZ()
	local v57 = p48.SpringAngles:Update().x
	local v58 = (v54 - v57 + 3.141592653589793) % 6.283185307179586 - 3.141592653589793 + v57
	local v59 = Vector3.new(v58, v55, v56)
	p48:SetAngles(v59)
	local v60 = tick()
	if v60 - p48.LastUpdateAngleDistance > 0.125 then
		p48.LastUpdateAngleDistance = v60
		p48.RemoteEvent:FireServer(v_u_16.EVENT_UPDATE_ANGLE_DISTANCE, v59, v52)
	end
end
function v_u_17.Update(p61)
	-- upvalues: (copy) v_u_1, (copy) v_u_9
	local v62 = p61.SpringAngles:Update()
	local v63 = CFrame.fromEulerAnglesXYZ(v62.X, v62.Y, v62.Z)
	local v64 = p61.Distance
	p61.SpotlightMotor.C1 = v63
	local v65 = p61.SpotlightMotor.Part0.CFrame
	p61.Attachment.WorldPosition = v65.p + v65.LookVector * (v64 + 4)
	p61.Beam.TextureLength = v64 + 4
	p61.Beam.Width1 = v64 * 2 / 3
	if p61.Maid.LocalMaid == nil and p61.PoliceValue.Value then
		local v66 = v_u_1.Character
		if v66 ~= nil then
			local v67 = v66:FindFirstChild("Humanoid")
			if v67 ~= nil then
				local v68 = v67.RootPart
				if v68 ~= nil then
					local v69 = v65.p
					local v70 = v65.LookVector
					local v71 = v64 + 4
					local v72 = v68.Position
					p61.IsLocalInSpotlight = v_u_9.DoesFixedConeIntersectSphere(v69, v70, v71, 0.23561944901923448, v72, 3)
				end
			end
		end
	end
end
function v_u_17.Destroy(p73)
	p73.IsLocalInSpotlight = false
	p73.Maid:Destroy()
	p73.Maid = nil
end
return v_u_17
