-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMHBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlB1Rvb2x0aXAOVG9vbHRpcFNlcnZpY2UEaW5pdAABBAAAAQIAEqMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DAHUGAAAATQIDOAcAAACfAQICTQIBEwgAAACfAgEBggABAAkDAQQAAABAAwIDAwMEBAAAQEADBQMGAwcAAQABGAABAAAAAAABAAAAAAAAAQAAAQEAAAAAAPGDIS0Hk160w0dLudySST0VvwBbnzfDlr6E1QjSGu09UumpPCRAmBM=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
require(v1.Tooltip.TooltipService).init()
