-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNIEG1pc3NpbmcgUGFydE5vZGUGYXNzZXJ0DHNldG1ldGF0YWJsZQhJbnN0YW5jZQNuZXcKQXR0YWNobWVudAZQYXJlbnQLVmVjdG9yRm9yY2UERW51bRJBY3R1YXRvclJlbGF0aXZlVG8LQXR0YWNobWVudDAKUmVsYXRpdmVUbwdWZWN0b3IzBUZvcmNlBlRvcnF1ZQVXb3JsZAhQYXJ0Tm9kZQJkeANkMngOUm90YXRpb25WaXN1YWwRVmlzdWFsSGVpZ2h0RmxvYXQNRWZmZWN0aXZlTWFzcwtJZ25vcmVNb2RlbBBIZWlnaHRTdXNwZW5zaW9uDFJhZGl1c1Zpc3VhbAdTcHJpbmdrB1NwcmluZ0IHQkhGcmljMAdCRkZyaWMwB0JGRnJpYzEIX3ZlcnNpb24MX2FwcGx5Rm9yY2VzE1NldFN1c3BlbnNpb25IZWlnaHQPU2V0VmlzdWFsUmFkaXVzElNldFNwcmluZ0NvbnN0YW50cxVTZXRIb3Jpem9udGFsRnJpY3Rpb24SU2V0Rm9yd2FyZEZyaWN0aW9uE1NldEZvcndhcmRGcmljdGlvbjIKU2V0VmVyc2lvbg5TZXRBcHBseUZvcmNlcw9fZXh0R3JvdW5kQWNjZWwWU2V0RXh0ZXJuYWxHcm91bmRBY2NlbAZDRnJhbWUBcAhVcFZlY3RvchNSYXlJZ25vcmVOb25Db2xsaWRlCFZlbG9jaXR5E3ZlY3RvclRvT2JqZWN0U3BhY2UBeAF6BG1hdGgFY2xhbXATVmVjdG9yVG9PYmplY3RTcGFjZQNEb3QJd29ya3NwYWNlB0dyYXZpdHkSVmVjdG9yVG9Xb3JsZFNwYWNlDVdvcmxkUG9zaXRpb24IUG9zaXRpb24FQ3Jvc3MGVXBkYXRlBUNsZWFyB0Rlc3Ryb3kEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUHUmF5Q2FzdAZNb2R1bGUDYWJzBkFuZ2xlcwdfX2luZGV4AA4HAgEAAABwgQEABQAAAABSAwAAbwQAAKQCAgAAABBAnwIDAf8DBgAAAAAA+wQAAJ49AwMEAAAApAIEAAAAMECfAgMCKwEwAKQDBwAAGFCAbwQIAJ8DAgIwAAMkCQAAADADAg0IAAAApAQHAAAYUIBvBQoAnwQCAqQFDgANMLDAMAUEkQ8AAAAwAwRrDQAAAEw2AAKkBREAABgAgZ8FAQIwBQQtEgAAADAABCQJAAAAMAQCFwoAAACkBQcAABhQgG8GEwCfBQICpAYVABQwsMAwBgWRDwAAADADBWsNAAAATDYAAqQGEQAAGACBnwYBAjAGBTUTAAAAMAAFJAkAAAAwBQI1EwAAADAAAjUWAAAAjAMAADADAmgXAAAAjAMAADADApsYAAAAjAMAADADAh0ZAAAAjAMAADADAhoaAAAAjAMAADADAuQbAAAAxgMAADADAhocAAAAjAMAADADAuUdAAAAjAMAADADAiweAAAAbwMfADADAnMgAAAAbwMhADADAlQiAAAAjAMHADADAoMjAAAAbwMkADADAsElAAAAbwMmADADAnQnAAAAjAMBADADAt4oAAAAVgMBADADAmopAAAAggICACoDAQMCBAAAEEADAwQAADBAAwQDBQQAGFCAAwYDBwMIAwkDCgMLBA0wsMADDAMNBAAYAIEDDgMPAxAEFDCwwAMRAxIDEwMUAxUDFgMXAxgDGQIAAAAAAAD4PwMaAgAAAAAAAAxAAxsDHAJ7FK5H4XqUPwMdAnsUrkfhenQ/Ax4DHwMgABMFARgAAAAAAAAAAQAAAAAAAAACAQAAAAEAAQACAAAAAQAAAAEAAQAAAAAAAQABAAIAAAABAAAAAQABAAAAAAABAAEABAABAAABAAABAAABAAACAAABAAACAAABAAABAAABAAABAAABAAABAAABAAABAAABFAAAAAAEAgAAAAAIuwEBA1IDAQCkAgEAAAAAQJ8CAgEwAQDlAgAAAIIAAQADAwIEAAAAQAMYAEEhARgAAAAAAAEAAUIAAAAABAIAAAAACLsBAQNSAwEApAIBAAAAAECfAgIBMAEALAIAAACCAAEAAwMCBAAAAEADGQBFIgEYAAAAAAABAAFGAAAAAAMDAAAAAAUwAQBzAAAAADACAFQBAAAAggABAAIDGgMbAEkjARgAAAAAAUoAAAAAAgIAAAAAAzABAIMAAAAAggABAAEDHABMJAEYAAABTQAAAAACAgAAAAADMAEAwQAAAACCAAEAAQMdAE8lARgAAAFQAAAAAAICAAAAAAMwAQB0AAAAAIIAAQABAx4AUiYBGAAAAVMAAAAAAgIAAAAAAzABAN4AAAAAggABAAEDHwBVJwEYAAABVgAAAAACAgAAAAADMAEAagAAAACCAAEAAQMgAFgoARgAAAFZAAAAAAICAAAAAAMwAQAfAAAAAIIAAQABAykAWyoBGAAAAVwAAAAAKAMGAAASAAADCCSPAQIIJJoBAQgjogEBiQJNAwA1AAAAAE0EABcBAAAATQUANQIAAABNBgDlAwAAAE0HA4UEAAAATQgA5AUAAABNCQBzBgAAAE0KAFQHAAAATQsAaAgAAABNDACbCQAAAE0NAIMKAAAATQ4AwQsAAAAOAgYA+w8AAIwQAABSEQIAjBIAAJ8PBAIJBwcPTQ8HkQwAAABNEQcRDQAAADkQEQBNEQDeDgAAAIwSAQB9EQQAEgAAAAkSEAZbERIPJg8PEfsSAQBNERJXEAAAAFISDwBSExAAUhQGAE0VABoRAAAAnxEFBPsUAgAmFRIPUhYQAJ8UAwImFQYUJhYVC4waAgAJGRoLJhgVGUMXGAw5GwkACRobFQkbChYmGRobWxsKDwkaGxcmGBkaTRsDhRIAAAC8GQcMEwAAAJ8ZAwJNGhmZFAAAAE0bGZsVAAAAjBwAAIwdAABvHhYAYB4hABUAAABNHgB0FwAAAIwhGPyMIugDNC4aAyEiAABSIBoA+x8DAJ8fBAJSGh8AjCEY/Iwi6AM0LhsDISIAAFIgGwD7HwMAnx8EAlIbHwA5IBoAPh8gGAkcHw05IRsAPiAhGAkfIA67AhsCUiQbAPsjBACfIwICCSIbIwkhIh4+ICEYJh0fIIwg/v+MIQIANC4YBCAhAABSHxgApB4bAABokIGfHgQCUhgeAMYeAADGHwAATSAAahwAAAAOIEEATSADhQQAAABSIhMAvCAg7B0AAACfIAMCjCUAADkmGACMJwAATDYAAfskBQCfJAQCUiYgALwkJCseAAAAnyQDAgkjJCCMJgAAjCcAADQ2HAMmJwAAUiUcAPskBQCfJAQCQyIjJIwkAACMJQAANDYkAyUdAABSJh0A+yMFAJ8jBAJDISIjTSIAHx8AAAAOIgYAbyIWAGAiBAAVAAAATSIAHx8AAABDISEipCQhAAAAAEJNIyQlIgAAAAkiCCMJHiIhTSIDhQQAAABSJB4AvCIiriMAAACfIgMCTSYADSQAAABNJSbgJQAAAE0mAzsmAAAAJiQlJrwiIrsnAAAAnyIDAlIfIgAOBAgAUiAeACsgBABMNgACpCAqAACkgIKfIAECMCAELSsAAAAOBQgAUiAfACsgBABMNgACpCAqAACkgIKfIAECMCAFNQIAAAAJIRsBTSIALCwAAADsICEiTSIAHS0AAABDISIgMCEAHS0AAADGIgAAxiMAAE0kAN4OAAAAjCUBAH0kCQAlAAAATScALCwAAABbJicuQyUmBlskJQ8mIiQUbyMvAGUABgBNJAAsLAAAACYiJBRNJAAsLAAAADkjJABgIwIAIgAAAFIiIwBNJAAaMAAAAGAkAwAiAAAAUiQiAGUAAwAmJiIkWyUmMUMkJCUwJAAaMAAAADALAJsJAAAAMBUAaAgAAABSJSQAUiYhAAknGwGCJQQAMgMRAwgDDwMYAysDFgMaAxsDEgMTAxwDHQMsAy0DHwIAAAAAAADgPwMuAxcDLwMwAzEDMgJ7FK5H4XqEPwMeAgAAAAAAAE5AAzMDNAQAaJCBAyADNQM2AykDNwQAAABCAzgDOQMGAzoDOwM8Aw0DBQQApICCAw4DGQMUAgAAAAAAAABAApqZmZmZmck/AxUCmpmZmZmZ2T8AXj0BGAAAAQABAAEAAQABAAEAAQABAAEAAQABAAIBAAAAAAAEAAAAAAEAAAAAAQAABAAAAAAAAAAAAQAAAAECAAAAAAEAAAAAAAADAAAAAAEAAAABAQIAAAIAAwAAAAAAAAABAAAAAAAAAAEAAAEAAAAAAAAAAAAAAwAAAAAAAAAABQEBAAABAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAABAAACAAAAAAACAAAAAAAAAAAAAAAAAAAAAAIBAAAAAAAAAAIBAAAAAAAAAAUAAAABAAABAAMBAQAAAAABAAAAAAABAAIAAAEAAAMAAQMAAgABAAMAAAIAAwAAAAIAAABgAAAAAAMBAQAAABFNAQAXAAAAAA4BBQBNAQAXAAAAAPsCAAAwAgEtAQAAAE0BADUCAAAADgEFAE0BADUCAAAA+wIAADACATUCAAAAggABAAMDCAMOAw8AzgE+ARgAAAABAAAAAAIAAAEAAAAAAs8AAAAAAwEAAAAAIk0BABcAAAAADgEIAE0BABcAAAAAvAEBUAEAAACfAQIBxgEAADABABcAAAAATQEANQIAAAAOAQgATQEANQIAAAC8AQFQAQAAAJ8BAgHGAQAAMAEANQIAAABNAQANAwAAAA4BCABNAQANAwAAALwBAVABAAAAnwECAcYBAAAwAQANAwAAAIIAAQAEAwgDPwMPAwYA1gE/ARgAAAABAAAAAAEAAAIAAAEAAAAAAQAAAgAAAQAAAAABAAAC1wAAAAAKAAABAgcAAAEIBRYCUqMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DAEAHAAAATQIDMgYAAACfAQICpAIKAAAkgIBMNgABUgMCAJ8DAQJMNgABUgUCAJ8FAQJNBAUrCwAAAKQFDgAANMCApAYQAAA8wICkBxMAAEgQgf8IBQAAAAAAMAgIbhQAAADACRUAEgAIADAJCO8JAAAAwAkWADAJCKgXAAAAwAkYADAJCCYZAAAAwAkaADAJCN8bAAAAwAkcADAJCA4dAAAAwAkeADAJCJkfAAAAwAkgADAJCAQhAAAAwAkiADAJCOUjAAAAwAkkADAJCDclAAAAwAkmADAJCMcnAAAAwAkoABIABwASAAEAEgAEABIABQASAAYAEgACADAJCCYpAAAAwAkqABIAAwAwCQiQKwAAAMAJLAAwCQhQLQAAAIIIAgAuA0AEAAAAQANBA0IDQwQAAEBAA0QDRQMNAwUEACSAgAM2AzMDNAQANMCAA0YEADzAgAMrA0cEAEgQgQNIBgAGAQMhBgIDIgYDAyMGBAMkBgUDJQYGAyYGBwMnBggDKAYJAyoGCgM9BgsDPgYMAz8NAAECAwQFBgcICQoLDAEAARgAAQAAAAAAAQAAAAAAAAUAAQAAAQAAAAABAAEAAQAEAAEAAQAAAC4AAAQAAAQAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAAAAAAAAHAAAAAIAAAPAQAAAAANeHsGgjMPf/NKv2wWSXmYSC3meVIsIqwdGvqmjPiL0Sg25nWFpR/N3A==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Module.RayCast)
local v_u_3 = Vector3.new
local v_u_4 = v_u_3()
local v_u_5 = v_u_3().Dot
local v_u_6 = math.clamp
local v_u_7 = math.abs
local v_u_8 = CFrame.Angles
local v_u_9 = {}
v_u_9.__index = v_u_9
function v_u_9.new(p10, p11)
	-- upvalues: (copy) v_u_9
	assert(p10, "missing PartNode")
	local v12 = v_u_9
	local v13 = setmetatable({}, v12)
	if not p11 then
		local v14 = Instance.new("Attachment")
		v14.Parent = p10
		v13.Attachment = v14
		local v15 = Instance.new("VectorForce")
		v15.RelativeTo = Enum.ActuatorRelativeTo.Attachment0
		v15.Attachment0 = v14
		v15.Force = Vector3.new()
		v15.Parent = p10
		v13.VectorForce = v15
		local v16 = Instance.new("Torque")
		v16.RelativeTo = Enum.ActuatorRelativeTo.World
		v16.Attachment0 = v14
		v16.Torque = Vector3.new()
		v16.Parent = p10
		v13.Torque = v16
	end
	v13.PartNode = p10
	v13.dx = 0
	v13.d2x = 0
	v13.RotationVisual = 0
	v13.VisualHeightFloat = 0
	v13.EffectiveMass = 0
	v13.IgnoreModel = nil
	v13.HeightSuspension = 0
	v13.RadiusVisual = 0
	v13.Springk = 1.5
	v13.SpringB = 3.5
	v13.BHFric0 = 7
	v13.BFFric0 = 0.02
	v13.BFFric1 = 0.005
	v13._version = 1
	v13._applyForces = not p11
	return v13
end
function v_u_9.SetSuspensionHeight(p17, p18)
	assert(p18)
	p17.HeightSuspension = p18
end
function v_u_9.SetVisualRadius(p19, p20)
	assert(p20)
	p19.RadiusVisual = p20
end
function v_u_9.SetSpringConstants(p21, p22, p23)
	p21.Springk = p22
	p21.SpringB = p23
end
function v_u_9.SetHorizontalFriction(p24, p25)
	p24.BHFric0 = p25
end
function v_u_9.SetForwardFriction(p26, p27)
	p26.BFFric0 = p27
end
function v_u_9.SetForwardFriction2(p28, p29)
	p28.BFFric1 = p29
end
function v_u_9.SetVersion(p30, p31)
	p30._version = p31
end
function v_u_9.SetApplyForces(p32, p33)
	p32._applyForces = p33
end
function v_u_9.SetExternalGroundAccel(p34, p35)
	p34._extGroundAccel = p35
end
function v_u_9.Update(p36, p37, p38)
	-- upvalues: (copy) v_u_8, (copy) v_u_2, (copy) v_u_5, (copy) v_u_6, (copy) v_u_7, (copy) v_u_3
	local v39 = p36.PartNode
	local v40 = p36.VectorForce
	local v41 = p36.Torque
	local v42 = p36.HeightSuspension
	local v43 = v39.CFrame
	local v44 = p36.EffectiveMass
	local v45 = p36.Springk
	local v46 = p36.SpringB
	local v47 = p36.dx
	local v48 = p36.d2x
	local v49 = p36.BHFric0
	local v50 = p36.BFFric0
	if p38 then
		v43 = v43 * v_u_8(0, p38, 0)
	end
	local v51 = v43.p
	local v52 = -v43.UpVector
	if p36._version <= 1 then
		v51 = v51 - v52 * v42 * 0.5
	end
	local _, v53, v54 = v_u_2.RayIgnoreNonCollide(v51, v52, v42, p36.IgnoreModel)
	local v55 = v_u_5(v53 - v51, v52)
	local v56 = v42 - v55
	local v57 = v56 - v47
	local v58 = v56 - 2 * v47 + v48
	local v59 = -v45 * v56 - v46 * v57 - v46 * 0.5 * v58
	local v60 = v43:vectorToObjectSpace(v39.Velocity)
	local v61 = v60.x
	local v62 = v60.z
	local v63, v64
	if v56 > 0.01 then
		local v65 = p36.BFFric1
		local v66 = v_u_6(v61, -1000, 1000)
		v62 = v_u_6(v62, -1000, 1000)
		v63 = -v66 / 60 * v49
		v64 = -v62 / 60 * v50 - v62 * v_u_7(v62) * v65 / 60
	else
		v63 = 0
		v64 = 0
	end
	local v67 = math.clamp(v59, -2, 2)
	local v68, v69
	if p36._applyForces then
		local v70 = v39.CFrame:VectorToObjectSpace(v54)
		local v71 = v_u_3(0, -v67, 0):Dot(v70) * v70 + v_u_3(v63, 0, 0) + v_u_3(0, 0, v64)
		if p36._extGroundAccel and v56 > 0.01 then
			v71 = v71 + p36._extGroundAccel
		end
		v68 = v44 * workspace.Gravity * v71
		v69 = v39.CFrame:VectorToWorldSpace(v68):Cross(p36.Attachment.WorldPosition - v39.Position)
	else
		v68 = nil
		v69 = nil
	end
	if v40 then
		v40.Force = v68 or Vector3.new()
	end
	if v41 then
		v41.Torque = v69 or Vector3.new()
	end
	local v72 = v62 * p37 / p36.RadiusVisual
	local v73 = p36.RotationVisual + v72
	p36.RotationVisual = v73
	local v74, v75
	if p36._version <= 1 then
		v74 = (p36.RadiusVisual * 2 + v42) * 0.5 - v55
		v75 = 0.2
	else
		v74 = p36.RadiusVisual - v55
		v75 = -p36.RadiusVisual
	end
	if v75 >= v74 then
		v75 = v74
	end
	local v76 = p36.VisualHeightFloat
	if v76 >= v75 then
		v75 = v76 + (v75 - v76) * 0.4
	end
	p36.VisualHeightFloat = v75
	p36.d2x = v47
	p36.dx = v56
	return v75, v73, v62 * p37
end
function v_u_9.Clear(p77)
	-- upvalues: (copy) v_u_4
	if p77.VectorForce then
		p77.VectorForce.Force = v_u_4
	end
	if p77.Torque then
		p77.Torque.Torque = v_u_4
	end
end
function v_u_9.Destroy(p78)
	if p78.VectorForce then
		p78.VectorForce:Destroy()
		p78.VectorForce = nil
	end
	if p78.Torque then
		p78.Torque:Destroy()
		p78.Torque = nil
	end
	if p78.Attachment then
		p78.Attachment:Destroy()
		p78.Attachment = nil
	end
end
return v_u_9
