-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMhCXdvcmtzcGFjZQ1DdXJyZW50Q2FtZXJhBkNGcmFtZQhQb3NpdGlvbgFZB1ZlY3RvcjMDbmV3CkZpcmVTZXJ2ZXIIQW5jaG9yZWQERW51bQpDYW1lcmFUeXBlClNjcmlwdGFibGUJSGVhcnRiZWF0B0Nvbm5lY3QIR2l2ZVRhc2sFZGVsYXkHYW5kVGhlbgtHaXZlUHJvbWlzZQRnYW1lB1BsYXllcnMKR2V0U2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQdyZXF1aXJlA1N0ZAdQcm9taXNlClJ1blNlcnZpY2UPUnhJbnN0YW5jZVV0aWxzC19Gb2N1c1BhcnRzDFdhaXRGb3JDaGlsZAtMb2NhbFBsYXllcgROYW1lG1NldFJlcGxpY2F0aW9uRm9jdXNPdmVycmlkZQ9vYnNlcnZlUHJvcGVydHkABQUAAQAABwAAAQgBFgEbpAMBAAAAAEBNAgNIAgAAAE0BAoUDAAAATQABOwQAAABNAQB4BQAAAIwCzv9gAQsAAgAAAIwCAABNBAB4BQAAAPUDBgSMBAAATDYAAqQBCQAAIHCAnwEEAkMAAAH7AQAAMAABOwQAAACCAAEACgMBBAAAAEADAgMDAwQDBQIAAAAAAABJwAMGAwcEACBwgAASAAEYAAAAAAAAAAACAAAAAAIAAAAAAAAAAAACAAABEwAAAAADAAEAAAAG+wAAAKkCAQC8AABrAAAAAJ8AAwGCAAEAAQMIAB4AARgAAAAAAAEfAAAAAAIAAQAAAAn7AAAAbwEAADABADsBAAAA+wAAAKkBAQAwAQBFAgAAAIIAAQADBwAAAAAAAPpDAAAAAAAAAAADBAMJACMAARgAAAAAAQAAAAEkAAAAAAcCBAAAADSkAgMAAgQAwJoAHgACAAAA+wIAAKkDAAAwAwJFBAAAAPsFAQBNBAX9BQAAAMAGBgASAgAAvAQExwcAAACfBAMAvAIB/QgAAACfAgAB+wUCAE0EBb4JAAAAjAUBAJ8EAgLABgoAEgIDALwEBLULAAAAnwQDALwCAekMAAAAnwIAAYIAAQD7AgMAqQQAALwCAmsNAAAAnwIDAfsFAgBNBAW+CQAAAIwFAQCfBAICwAYOABICAAC8BAS1CwAAAJ8EAwC8AgHpDAAAAJ8CAAGCAAEADwMKAwsDDAQCBADAAwkDDQYAAw4DDwMQBgEDEQMSAwgGAgMAAQIPAAEYAAAAAAEAAAABAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAABAAAAAABAAAAAAAAAAAAAAAABRAAAAAADAAAAQIAQ6MAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQEAAAAAQG8DBAC8AQEWAwAAAJ8BAwKkAgYAAABQQE0EAaEHAAAATQMEcggAAACfAgICpAMBAAAAAEBvBQkAvAMDFgMAAACfAwMCpAQGAAAAUEBNBgGhBwAAAE0FBlIKAAAAnwQCAqQFDAAAALBAbwcNALwFBdMOAAAAnwUDAk0JADEPAAAATQgJuhAAAAC8BgXTDgAAAJ8GAwKpBwEAMAcGRREAAABvCRIAvAcB0w4AAACfBwMCTQgESBMAAACkCgwAAACwQE0JCkgUAAAAbwoVAMALFgASAAYAEgADABIAAgASAAcAnwgEAYIAAQAXAxMEAAAAQAMUAxUDFgMXBAAAUEADGAMZAxoDGwMBBAAAsEADHAMdAx4DHwMJAyADIQMCAwsGAwEDAQABGAABAAAAAAABAAAAAAABAAAAAAAAAQAAAAAAAQAAAAAAAAIAAAAAAAEAAAAAAAABAAACAAAAAwAAAAAAAAAAAAAAABoBAAAAAARSzSjhP7WA7GAJQnX0xRS+VqOF9H/HC4ZnEaEtOW5Uv0cw0uWriNid

-- Decompiled by Krnl

local v1 = game:GetService("Players")
local v2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v2.Std.Promise)
local v_u_4 = game:GetService("RunService")
local v5 = require(v2.Std.RxInstanceUtils)
local v_u_6 = workspace:WaitForChild("_FocusParts"):WaitForChild(v1.LocalPlayer.Name)
v_u_6.Anchored = true
local v_u_7 = v2:WaitForChild("SetReplicationFocusOverride")
v5.observeProperty(workspace.CurrentCamera, "CameraType", function(p8, p9)
	-- upvalues: (copy) v_u_6, (copy) v_u_4, (copy) v_u_3, (copy) v_u_7
	if p8 == Enum.CameraType.Scriptable then
		v_u_6.Anchored = false
		p9:GiveTask(v_u_4.Heartbeat:Connect(function()
			-- upvalues: (ref) v_u_6
			local v10 = workspace.CurrentCamera.CFrame.Position
			if v10.Y < -50 then
				local v11 = -50 - v10.Y
				v10 = v10 + Vector3.new(0, v11, 0)
			end
			v_u_6.Position = v10
		end))
		p9:GivePromise(v_u_3.delay(1):andThen(function()
			-- upvalues: (ref) v_u_7
			v_u_7:FireServer(true)
		end))
	else
		v_u_7:FireServer(false)
		p9:GivePromise(v_u_3.delay(1):andThen(function()
			-- upvalues: (ref) v_u_6
			v_u_6.Position = Vector3.new(0, 500, 0)
			v_u_6.Anchored = true
		end))
	end
end)
