-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgPuAQtMb2NhbFBsYXllcglQbGF5ZXJHdWkLT2JqZWN0TG9jYWwGVm9sdW1lCXBsYXlDbGljawVwcm9wcwxhdHRlbXB0QWRtaW4GdXNlcklkEWF0dGVtcHRSZW5hbWVDcmV3DmF0dGVtcHRVbkFkbWluC2F0dGVtcHRLaWNrGG9uQ2xpY2tKb2luUmVxdWVzdEFjY2VwdBZvbkNsaWNrSm9pblJlcXVlc3REZW55DWlzU21hbGxTY3JlZW4Ic2V0U3RhdGUMc2hvd1JlcXVlc3RzBXN0YXRlDndlbGNvbWVWaXNpYmxlFWF0dGVtcHRWaWV3VXNlcklkQ2xhbgZVc2VySWQNb25DbGlja1ZpZXdNZRBjb3VudGRvd25WaXNpYmxlE29uQ291bnRkb3duRmluaXNoZWQTcmVwb3J0RGlhbG9nVmlzaWJsZRFhdHRlbXB0UmVwb3J0Q3JldwNuZXcEbWFpZAxvbkNsaWNrQWRtaW4Rb25DbGlja1JlbmFtZUNyZXcOb25DbGlja1VuQWRtaW4Lb25DbGlja0tpY2sMY291bnRkb3duVGlsHGdldFZpZXdwb3J0U2l6ZUNoYW5nZWRTaWduYWwHQ29ubmVjdAhHaXZlVGFzaxVvbkNsaWNrVG9nZ2xlUmVxdWVzdHMTb25DbGlja0Nsb3NlV2VsY29tZRJvbkNvdW50ZG93bkVsYXBzZWQTb25SZXBvcnREaWFsb2dDbG9zZRRvblJlcG9ydERpYWxvZ1N1Ym1pdARpbml0D2N1cnJlbnRDbGFuSW5mbw92aWV3aW5nQ2xhbkluZm8MZ3JvdXBWaXNpYmxlCENsYW5OYW1lDURpc3BsYXlSYXRpbmcKREVGQVVMVF9NVQ1CYXR0bGVzUGxheWVkCkJhdHRsZXNXb24FVURpbTIJZnJvbVNjYWxlEmJhdHRsZVJlc3BvbnNlRGF0YQthc3BlY3RSYXRpbxR2ZXJ0aWNhbFBhZGRpbmdSYXRpbwZDbGFuSWQGY2xhbklkDVBsYXllcnNDbGFuSWQNcGxheWVyc0NsYW5JZA1pc1BsYXllcnNDbGFuD0xlYWRlcmJvYXJkUmFuaw9sZWFkZXJib2FyZFJhbmsKQWRtaW5JZE1hcAh0b3N0cmluZxRpc0FkbWluT2ZWaWV3aW5nQ2xhbhRpc0FkbWluT2ZDdXJyZW50Q2xhbg1iYXR0bGVzUGxheWVkCmJhdHRsZXNXb24MYXR0ZW1wdExlYXZlC093bmVyVXNlcklkD2NsYW5Pd25lclVzZXJJZAhjbGFuTmFtZRFjbGFuRGlzcGxheVJhdGluZwlGbGFnQ29sb3IJZmxhZ0NvbG9yEG1lbWJlcnNPbmxpbmVNYXAHbWVtYmVycwxqb2luUmVxdWVzdHMLaXNSZWFkaWVkVXAXcGxheWVySGFzQWNjZXB0ZWRJbnZpdGUTUGxheWVyRGlzcGxheVJhdGluZxNwbGF5ZXJEaXNwbGF5UmF0aW5nE2F0dGVtcHRCYXR0bGVDbGFuSWQYYXR0ZW1wdFJlcXVlc3RKb2luVXNlcklkDm9uQ2xpY2tSZWFkeVVwEG9uQ2xpY2tVbnJlYWR5VXASbmV0d29ya011dGV4TG9ja2VkDG9uQ2xpY2tDbG9zZQRDcmV3DWF0dGVtcHRDcmVhdGUMSm9pbk9yQ3JlYXRlBUZyYW1lFkJhY2tncm91bmRUcmFuc3BhcmVuY3kQQmFja2dyb3VuZENvbG9yMwRTaXplCFBvc2l0aW9uC0FuY2hvclBvaW50BkNvbG9yMwthbmNob3JQb2ludAVtZXJnZQtBc3BlY3RSYXRpbwhVSUNvcm5lchdVSUFzcGVjdFJhdGlvQ29uc3RyYWludAxDb3JuZXJSYWRpdXMEVURpbQVHcm91cAdXZWxjb21lBHNpemUIcG9zaXRpb24Ib25BY2NlcHQJb25EZWNsaW5lB1ZlY3RvcjIUb25BY2NlcHRCYXR0bGVJbnZpdGUVb25EZWNsaW5lQmF0dGxlSW52aXRlDUJhdHRsZUludml0ZXMFdGFibGUGaW5zZXJ0D2F0dGFja2luZ0NsYW5JZAdmcm9tUkdCB3BlbmFsdHkOaXNCYXR0bGVTZXJ2ZXILQm9yZGVyT3V0ZXILQm9yZGVySW5uZXIPQm9yZGVyU2l6ZVBpeGVsCmZyb21PZmZzZXQIVUlTdHJva2UJVGhpY2tuZXNzBUNvbG9yDFRyYW5zcGFyZW5jeQlDb250YWluZXIGWkluZGV4BVRpbWVyCVVJQ29ybmVycwRUZXh0CVRleHRMYWJlbARGb250CkxpbmVIZWlnaHQKVGV4dFNjYWxlZApUZXh0Q29sb3IzBEVudW0KRnJlZG9rYU9uZQdQZW5hbHR5CENyZXdPdXJzCkNyZXdUaGVpcnMQRWxhcHNlZENvbnRhaW5lcgRmb250CXRleHRDb2xvcgljcmVhdGVkQXQHZWxhcHNlZAhkaXNhYmxlZApzYXR1cmF0ZUJ5CXN0YXJ0ZWRBdAh0aW1lVG9vaw9iYWNrZ3JvdW5kQ29sb3IJYXR0YWNraW5nEnJvYmJlcmllc0NvbXBsZXRlZAZSZXBvcnQFSW1hZ2ULSW1hZ2VCdXR0b24YcmJ4YXNzZXRpZDovLzE0MjgwNDYzNzc2BUV2ZW50CUFjdGl2YXRlZAZDb3JuZXIGVG9wQmFyCWNvdW50RG93bglvbkVsYXBzZWQRYWx3YXlzU2hvd01pbnV0ZXMJQ291bnRkb3duB29uQ2xvc2UIb25TdWJtaXQMUmVwb3J0RGlhbG9nDVRoZWlyQ2xhbkluZm8GekluZGV4EW51bVBsYXllcnNQZXJUZWFtDGNsYW5OYW1lT3Vycw1jbGFuT3duZXJPdXJzDWNsYW5Db2xvck91cnMPY2xhbk1lbWJlcnNPdXJzDmNsYW5OYW1lVGhlaXJzD2NsYW5Pd25lclRoZWlycw9jbGFuQ29sb3JUaGVpcnMRY2xhbk1lbWJlcnNUaGVpcnMWb25VbkFjY2VwdEJhdHRsZUludml0ZRFOdW1QbGF5ZXJzUGVyVGVhbQtPdXJDbGFuSW5mbwdmcm9tSGV4DEZsYWdDb2xvclN0cg9PdXJDbGFuQWNjZXB0ZWQRVGhlaXJDbGFuQWNjZXB0ZWQJUmVzcG9uc2VzDmNyZWF0ZUZyYWdtZW50BnJlbmRlchBnZXRSb3VuZFN0YXJ0c0F0CXdvcmtzcGFjZRBHZXRTZXJ2ZXJUaW1lTm93D3VwZGF0ZUNvdW50ZG93bhVfdXBkYXRlV2VsY29tZVZpc2libGUmZ2V0Um91bmRTdGFydHNBdEF0dHJpYnV0ZUNoYW5nZWRTaWduYWwIZGlkTW91bnQJZGlkVXBkYXRlCkRvQ2xlYW5pbmcLd2lsbFVubW91bnQEdHlwZQV2YWx1ZQ9zZXRHcm91cFZpc2libGUKc2V0TWVtYmVycxJzZXRWaWV3aW5nQ2xhbkluZm8EZ2FtZQdQbGF5ZXJzCkdldFNlcnZpY2URUmVwbGljYXRlZFN0b3JhZ2UHcmVxdWlyZQNTdGQETWFpZAVBdWRpbwpDb2xvclV0aWxzBEV6VWkFVXRpbHMKUm9hY3RSb2R1eAVSb2FjdA1jcmVhdGVFbGVtZW50B0dsaWNrbzINR2xpY2tvMkNvbnN0cwpEaWN0aW9uYXJ5FFBlcnNpc3RlbnRDcmV3QmF0dGxlGlBlcnNpc3RlbnRDcmV3QmF0dGxlQ29uc3RzGVBlcnNpc3RlbnRDcmV3QmF0dGxlVXRpbHMGc2NyaXB0BlBhcmVudARJbmZvAlVJB0VsYXBzZWQOQmF0dGxlQ3Jld0luZm8KUmVwb3J0Q3Jldw1QdXJlQ29tcG9uZW50EVBlcnNpc3RlbnRDcmV3QXBwBmV4dGVuZAxkZWZhdWx0UHJvcHMHY29ubmVjdAAbBQACAAAAFfsCAABNAQIxAAAAAE0AAZkBAAAADgAOAPsBAQBNAAHRAgAAAPsDAABNAgMxAAAAAE0BApkBAAAAbwIDAOIDBQBvBAYAMAQDSwQAAACfAAQBggABAAcDAQMCAwMCAABQFX2AB0IDBAUBBAKamZmZmZnJPwAbBQEYAAAAAAAAAQAAAAAAAAAAAAAAAAACHAAAAAAEAQEAAAAJ+wMAAE0CAwcAAAAATQECJQEAAABNAgCGAgAAAJ8BAgGCAAEAAwMGAwcDCAAqAAEYAAAAAAAAAAABKwAAAAAEAQEAAAAI+wMAAE0CAwcAAAAATQECtwEAAABSAgAAnwECAYIAAQACAwYDCQAtAAEYAAAAAAAAAAEuAAAAAAQBAQAAAAn7AwAATQIDBwAAAABNAQK0AQAAAE0CAIYCAAAAnwECAYIAAQADAwYDCgMIADAAARgAAAAAAAAAAAExAAAAAAQBAQAAAAn7AwAATQIDBwAAAABNAQJnAQAAAE0CAIYCAAAAnwECAYIAAQADAwYDCwMIADMAARgAAAAAAAAAAAE0AAAAAAQBAQAAAAn7AwAATQIDBwAAAABNAQIVAQAAAE0CAIYCAAAAnwECAYIAAQADAwYDDAMIADYAARgAAAAAAAAAAAE3AAAAAAQBAQAAAAn7AwAATQIDBwAAAABNAQLXAQAAAE0CAIYCAAAAnwECAYIAAQADAwYDDQMIADkAARgAAAAAAAAAAAE6AAAAAAUAAgAAAAz7AAAA4gIBAPsEAQBNAwR5AAAAAJ8DAQIwAwJ5AAAAALwAACoCAAAAnwADAYIAAQADAw4FAQADDwBCAAEYAAABAAAAAAD/AAADQwAAAAAHAAMAAAAi+wAAAOICAQD7BgAATQUGGAIAAABNBAU+AAAAAFYDBAAwAwI+AAAAALwAACoDAAAAnwADAfsCAQBNAQIxBAAAAE0AAZkFAAAADgAOAPsBAgBNAAHRBgAAAPsDAQBNAgMxBAAAAE0BApkFAAAAbwIHAOIDCQBvBAoAMAQDSwgAAACfAAQBggABAAsDEAUBAAMRAw8DAQMCAwMCAABQFX2AB0IDBAUBCAKamZmZmZnJPwBHAAEYLAABAAAAAAAAAP8AANQAAAAAAAEAAAAAAAAAAAAAAAAALxwAAAAABQADAAAAHfsAAADiAgEAqQMAADADAkoAAAAAvAAAKgIAAACfAAMB+wIBAE0BAjEDAAAATQABmQQAAAAOAA4A+wECAE0AAdEFAAAA+wMBAE0CAzEDAAAATQECmQQAAABvAgYA4gMIAG8ECQAwBANLBwAAAJ8ABAGCAAEACgMSBQEAAw8DAQMCAwMCAABQFX2AB0IDBAUBBwKamZmZmZnJPwBNAAEYMgABAAD/AADOAAAAAAABAAAAAAAAAAAAAAAAADUcAAAAAAUAAwAAACb7AgAATQECBwAAAABNAAFUAQAAAPsDAQBNAgMxAgAAAE0BAuYDAAAAnwACAfsCAABNAQIHAAAAAE0AAdgEAAAAnwABAfsCAQBNAQIxAgAAAE0AAZkFAAAADgAOAPsBAgBNAAHRBgAAAPsDAQBNAgMxAgAAAE0BApkFAAAAbwIHAOIDCQBvBAoAMAQDSwgAAACfAAQBggABAAsDBgMTAwEDFAMVAwIDAwIAAFAVfYAHQgMEBQEIApqZmZmZmck/AFMAARg4AAAAAAAAAAAAAAEAAAAAAMcAAAAAAAEAAAAAAAAAAAAAAAAAOhwAAAAABQEBAAAAEowBAABgAA8AAQAAAPsBAADiAwEAqQQAADAEA4sAAAAAvAEBKgIAAACfAQMB+wMAAE0CAwcDAAAATQEC5gQAAACfAQEBggABAAUDFgUBAAMPAwYDFwBYAAEYAAAAAQABAAD/AAADAAAAAAACWQAAAAAEAAEAAAAJ+wAAAOICAQCpAwAAMAMCXQAAAAC8AAAqAgAAAJ8AAwGCAAEAAwMYBQEAAw8AYQABGAAAAQAA/wAAA2IAAAAABQIBAAAACfsEAABNAwQHAAAAAE0CA2kBAAAAUgMAAFIEAQCfAgMBggABAAIDBgMZAGYAARgAAAAAAAAAAAFnAAAAAAYBBAAAAF/7AgAATQEC7wAAAACfAQECMAEAFgEAAADZAQAAEgAAADABAGwCAAAA2QEBABIAAAAwAQBUAwAAANkBAgASAAAAMAEA7gQAAADZAQMAEgAAADABADIFAAAA2QEEABIAAAAwAQAVBgAAANkBBQASAAAAMAEA1wcAAADiAwwAqQQAADAEAz4IAAAAjAQAADAEA/MJAAAAqQQAADAEA4sKAAAA+wUBAE0EBXkLAAAAnwQBAjAEA3kLAAAAvAEAKg0AAACfAQMBTQEAFgEAAAD7BAEATQME6w4AAACfAwEC2QUGABIAAAASAgEAvAMDxw8AAACfAwMAvAEB/RAAAACfAQAB2QEHABIAAAASAgIAEgIDADABAPARAAAA2QEIABIAAAASAgIAEgIDADABAI4SAAAA2QEJABIAAAASAgIAEgIDADABANgTAAAA2QEKABIAAAAwAQBIFAAAANkBCwASAAAAMAEAaRUAAADZAQwAEgAAADABAOUWAAAAggABABcDGgMbAxwDHQMeAx8DDAMNAxADIAMWAw4FBAgJCgsDDwMhAyIDIwMkAyUDFQMmAycDKA0BAgMEBQYHCAkKCwwNJykBGAAAAAAAAAIAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMBAAABAAABAAABAAAAAAD8AAAGAAAAAAAAAAAAAAAAAAAFAAAAAAAGAAAAAAAGAAAAAAAFAAAACQAAAAUAAAADKAAAAAAHAAEAAAAO+wAAAOICAQD7BgAATQUGGAIAAABNBAVdAAAAAFYDBAAwAwJdAAAAALwAACoDAAAAnwADAYIAAQAEAxgFAQADEQMPAIUDAAEYAAABAAAAAAAAAP8AAAOGAQAAACIBDgAAAPAKTQIABwAAAABNAQJvAQAAAE0EAAcAAAAATQMEOQIAAADKAgMB/wMFAAAAAABNBQAHAAAAAE0EBdsDAAAADgRoAf8EAgAAAAAAxgUAAMYGAAAOAvwATQcCiAQAAABNCAJlBQAAACsIAwD7CQAATQgJdQYAAABNCgK0CAAAAJAJCgdNCwJDCQAAAJAKCwf7DQEATQwNMQoAAAAODAYA+w0BAE0MDTEKAAAATQsM5gsAAABlAAEAjAv//6QMDgAANMCAjA0BAG8ODwCfDAMCUgUMAKQMDgAANMCAbw0PAE0RAAcAAAAATRARVxAAAABHEAMAAAAAAG8PEQBlAAEAjA8AAPUODw+fDAMCUgYMAPsMAgD7DQMA/w4HAAAAAABvDxIAMA8OiRMAAACMD4AAMA8OxhQAAABNDwI7FQAAADAPDhsWAAAATQ8CLBcAAAAwDw5MGAAAAE0QAiwXAAAATRECOxUAAADxEAIAEQAAAKkPAAGpDwEAMA8O9BkAAABNDwLhGgAAADAPDsEbAAAATRECXRwAAAC7PwsDUhMLAKQSHgAAANBBnxICAocQERIqEAIAAQAAAKkPAAGpDwEAMA8OGR8AAABSDwEADg8MAE0RAV0cAAAAuz8LA1ITCwCkEh4AAADQQZ8SAgKHEBESKhACAAEAAACpDwABqQ8BADAPDnggAAAAMAkOVCEAAAAwCg5jIgAAAE0QAAcAAAAATQ8QQSMAAAAwDw5BIwAAAE0PAhIkAAAAMA8OuCUAAAAwBw7oJgAAADAIDvUnAAAATQ8CrygAAAAwDw6PKQAAAE0QAAcAAAAATQ8QhyoAAAAwDw6HKgAAAE0QABgrAAAATQ8QPiwAAAAwDw4+LAAAAE0QAAcAAAAATQ8QVi0AAAAwDw5WLQAAAE0QAAcAAAAATQ8Q2S4AAAAwDw7ZLgAAAE0QAAcAAAAATQ8QGi8AAAAwDw4aLwAAAE0RAAcAAAAATRARVxAAAABHEAIAAAAAgKkPAAGpDwEAMA8OBDAAAABNDwKlMQAAADAPDoUyAAAATRAABwAAAABNDxDUMwAAADAPDtQzAAAATRAABwAAAABNDxBUNAAAADAPDlQ0AAAATQ8AbDUAAAAwDw5sNQAAAE0PAFQ2AAAAMA8OVDYAAABNDwDuNwAAADAPDu43AAAATQ8AMjgAAAAwDw4yOAAAAE0PABU5AAAAMA8OFTkAAABNDwDXOgAAADAPDtc6AAAATQ8A8DsAAAAwDw7wOwAAAE0QAAcAAAAATQ8QTjwAAAAwDw5OPAAAAE0QAAcAAAAATQ8QqT0AAAAwDw6pPQAAAE0QAAcAAAAATQ8QPz4AAAAwDw4/PgAAAE0QAAcAAAAATQ8QOT8AAAAwDw45PwAAAE0PANhAAAAAMA8O2EAAAABNEAAHAAAAAE0PEP9BAAAAMA8O/0EAAACfDAMCMAwEb0IAAABlADAApAcOAAA0wICMCAEAbwlDAJ8HAwJSBQcApAcOAAA0wIBvCA8AbwkPAJ8HAwJSBgcA+wcCAPsIBADiCUUAbwoSADAKCYkTAAAAjAqAADAKCcYUAAAATQsABwAAAABNCgvIRAAAADAKCchEAAAATQsABwAAAABNCgtUNAAAADAKCVQ0AAAATQsABwAAAABNCgs5PwAAADAKCTk/AAAATQsABwAAAABNCgv/QQAAADAKCf9BAAAAnwcDAjAHBJNGAAAA+wcCAG8IRwDiCU0AbwpOADAKCTpIAAAApApRAABA8YSMCwAAjAwAAIwNAACfCgQCMAoJn0kAAAAwBQkvSgAAADAGCTtLAAAATQsABwAAAABNCgsIUgAAADAKCehMAAAA+wsFAE0KCx9TAAAA4gtWAPsMAgBvDVcA4g5YAG8PEgAwDw5pVAAAAJ8MAwIwDAtpVAAAAPsMAgBvDVUA4g5aAKQPXAAAQLGFjBAAAIwRCACfDwMCMA8OT1kAAACfDAMCMAwL9FUAAABSDAQAnwoDAJ8HAAIwBwPEXQAAAE0FABgrAAAATQQFSl4AAAAOBAoA+wQCAPsFBgDiBl8ATQcAjmAAAAAwBwb/QQAAAJ8EAwIwBAPhYQAAAPsEAgD7BQcA4gZmAKQHZwAAQMGAbwhoAIwJAABvCmgAjAsAAJ8HBQIwBwYPYgAAAE0JABgrAAAATQgJeWkAAAAOCAgApAdnAABAwYBvCA8AjAkAAG8KagCMCwAAnwcFAisHBwCkB2cAAEDBgIwIAQCMCQAAbwoPAIwLAACfBwUCMAcG22MAAABNCQAYKwAAAE0ICXlpAAAADggGAKQHbAAAQLGGbwgPAG8JDwCfBwMCKwcFAKQHbAAAQLGGjAgBAG8JDwCfBwMCMAcGCFIAAABNCAAHAAAAAE0HCIBtAAAAMAcGKmQAAABNCAAHAAAAAE0HCLxuAAAAMAcGLWUAAACfBAMCMAQDRG8AAABSBAIADgQCAE0EAjsVAAAA/wUAAAAAAABNCQAHAAAAAE0GCegmAAAAxgcAAMYIAABkBgcAnjQFBQkAAABSDAUAUg0JAKQLcgAAxAGHnwsDAW4G+P8BAAAAEwcFAJoHAwAEAAAAEwYFAWUAAQATBgUATQgABwAAAABNBwhucwAAAKQIdQAA0PGEjAl5AIwK+wCMC7EAnwgEAqQJdQAA0PGEjAr/AIwLMQCMDDEAnwkEAk0LAAcAAAAATQoL7XYAAABHCgIAAAAAgKkLAAGpCwEATQ0ABwAAAABNDA0kdwAAAA4M+QL7DAIAbw1HAOIOeACMDwEAMA8OOkgAAACkD2cAAEDBgIwQAQCMEQAAjBIBAIwTAACfDwUCMA8OL0oAAADiD3sA+xACAG8RRwDiEn0AjBMAADATEo58AAAAjBMBADATEjpIAAAApBNnAABAwYCMFAEAjBXQ/4wWAQCMF9D/nxMFAjATEi9KAAAApBN/AAD4wYCMFBgAjBUYAJ8TAwIwExI7SwAAAOITgQD7FAIAbxWAAOIWhQCMFwIAMBcWGIIAAAAOCwIAUhcJAGUAAQBSFwgAMBcWpIMAAABvF4YAMBcW2YQAAACfFAMCMBQTbYAAAAD7FAIAbxVVAOIWWgCkF1wAAECxhYwYAACMGSAAnxcDAjAXFk9ZAAAAnxQDAjAUE/RVAAAAnxAEAjAQD4h5AAAA+xACAG8RRwDiEn0AjBMAADATEo58AAAAjBMBADATEjpIAAAApBNnAABAwYCMFAEAjBWs/4wWAQCMF6z/nxMFAjATEi9KAAAApBN/AAD4wYCMFCoAjBUqAJ8TAwIwExI7SwAAAOITgQD7FAIAbxWAAOIWhQCMFwIAMBcWGIIAAAAwCBakgwAAAG8XDwAwFxbZhAAAAJ8UAwIwFBNtgAAAAPsUAgBvFVUA4hZaAKQXXAAAQLGFjBgAAIwZIACfFwMCMBcWT1kAAACfFAMCMBQT9FUAAACfEAQCMBAP5noAAACfDAQCMAwDb4cAAABSDAsADgyLAPsMAgBvDUcA4g6JAIwPAAAwDw6OfAAAAIwPAQAwDw46SAAAAKQPZwAAQMGAbxAPAIwRAACMEgAAjBMQAJ8PBQIwDw4vSgAAAKQPbAAAQLGGbxAPAG8RDwCfDwMCMA8O6EwAAACkD2cAAEDBgG8QDwCMEQAAjBIAAIwTFwCfDwUCMA8OO0sAAACMDwMAMA8ODYgAAADiD4sA+xACAG8RRwDiEowAjBMAADATEo58AAAAMAkSn0kAAACkEw4AADTAgG8UEQCMFQEAnxMDAjATEi9KAAAApBNsAABAsYZvFA8AjBUAAJ8TAwIwExLoTAAAAKQTDgAANMCAbxQPAIwVAACfEwMCMBMSO0sAAADiE48A+xQCAG8VVQDiFloApBdcAABAsYVvGJAAjBkAAJ8XAwIwFxZPWQAAAJ8UAwIwFBPhjQAAAPsUAgBvFZEA4haWAIwXAQAwFxY6SAAAAKQXZwAAQMGAjBgBAIwZAACMGgEAjBsAAJ8XBQIwFxYvSgAAAKQXZwAAQMGAbxgPAIwZAABvGg8AjBsAAJ8XBQIwFxY7SwAAAKQXbAAAQLGGbxgPAG8ZDwCfFwMCMBcW6EwAAACkF5kAmEhyyTAXFjmSAAAAMAoW9Y4AAACMFwEAMBcWgpMAAACpFwEAMBcW3pQAAACkF1EAAEDxhIwYAQCMGQEAjBoBAJ8XBAIwFxZzlQAAAJ8UAwIwFBP1jgAAAJ8QBAIwEA88igAAAJ8MBAIwDAPNmgAAAPsMAgBvDUcA4g6JAIwPAAAwDw6OfAAAAIwPAQAwDw46SAAAAKQPZwAAQMGAbxAPAIwRAACMEgAAjBMYAJ8PBQIwDw4vSgAAAKQPbAAAQLGGbxAPAG8RDwCfDwMCMA8O6EwAAACkD2cAAEDBgG8QDwCMEQAAjBIAAIwTKQCfDwUCMA8OO0sAAACMDwMAMA8ODYgAAADiD50A+xACAG8RRwDiEowAjBMAADATEo58AAAApBNRAABA8YRvFBEAbxURAG8WEQCfEwQCMBMSn0kAAACkEw4AADTAgG8UngBvFZ8AnxMDAjATEi9KAAAApBNsAABAsYZvFA8AbxWQAJ8TAwIwExLoTAAAAKQTDgAANMCAbxQPAG8VDwCfEwMCMBMSO0sAAADiE6EA+xQCAG8VgADiFoUAjBcCADAXFhiCAAAAMAgWpIMAAABvFw8AMBcW2YQAAACfFAMCMBQTbYAAAAD7FAIAbxVVAOIWWgCkF1wAAECxhW8YkACMGQAAnxcDAjAXFk9ZAAAAnxQDAjAUE+GNAAAA+xQCAPsVCADiFqcApBeZAJhIcskwFxYZogAAAKQXDgAANMCAbxgPAG8ZDwCfFwMCMBcW22MAAAD7GAkATRcY3qgAAABSGAgAbxlOAJ8XAwIwFxa/owAAAE0ZAAcAAAAATRgZSqkAAACHFxgHMBcWiaQAAABNGQAHAAAAAE0YGaOqAAAAhxcYBzAXFoSlAAAATRoABwAAAABNGRpKqQAAAIcYGQdHGAIAAAAAAKkXAAGpFwEAMBcWgqYAAACfFAMCMBQT+qAAAACfEAQCMBAPPIoAAAD7EAIA+xEKAOISrgBNFQAHAAAAAE0UFegmAAAAhxMUBDATEugmAAAAMAgSDqsAAACkEw4AADTAgG8UrwCMFQEAnxMDAjATEg9iAAAApBMOAAA0wICMFAAAbxUPAJ8TAwIwExLbYwAAAKQTbAAAQLGGjBQAAG8VDwCfEwMCMBMSCFIAAABNFQAHAAAAAE0UFUqpAAAAhxMUBDATEomkAAAATRYABwAAAABNFRZKqQAAAIcUFQRHFAMAAAAAgIwTAABlAAUATRUABwAAAABNFBWjqgAAAIcTFAQwExKEpQAAAE0WAAcAAAAATRUWSqkAAACHFBUERxQCAAAAAACpEwABqRMBADATEoKmAAAA8QQCAAcAAACpEwABqRMBADATEvmsAAAATRQABwAAAABNExRxrQAAADATEnGtAAAAnxADAjAQD/ebAAAA+xACAPsRCgDiEq4ATRUABwAAAABNFBXoJgAAAIcTFAYwExLoJgAAADAIEg6rAAAApBMOAAA0wIBvFK8AjBUBAJ8TAwIwExIPYgAAAKQTDgAANMCAjBQBAG8VDwCfEwMCMBMS22MAAACkE2wAAECxhowUAQBvFQ8AnxMDAjATEghSAAAATRUABwAAAABNFBVKqQAAAIcTFAYwExKJpAAAAE0WAAcAAAAATRUWSqkAAACHFBUGRxQDAAAAAICMEwAAZQAFAE0VAAcAAAAATRQVo6oAAACHExQGMBMShKUAAABNFgAHAAAAAE0VFkqpAAAAhxQVBkcUAgAAAAAAqRMAAakTAQAwExKCpgAAAPEGAgAHAAAAqRMAAakTAQAwExL5rAAAAE0UAAcAAAAATRMUca0AAAAwExJxrQAAAOITsQD7FAIAbxVHAOIWsgCMFwEAMBcWOkgAAACkFw4AADTAgIwYAQCMGQEAnxcDAjAXFi9KAAAApBdnAABAwYCMGAEAjBkEAIwaAACMGwAAnxcFAjAXFjtLAAAA4he0APsYAgBvGbUA/xoDAAAAAACkG3UAANDxhIwc+wCMHXkAjB55AJ8bBAIwGxqfSQAAAKQbDgAANMCAjBwBAIwdAQCfGwMCMBsaL0oAAABvG7YAMBsaqbMAAAD7HQsATRwdNrcAAABNGxweuAAAANkcAAASAAAAahwaG+IbugD7HAIAbx1VAOIeWgCkH1wAAECxhYwgAACMIQQAnx8DAjAfHk9ZAAAAnxwDAjAcG2q5AAAAnxgEAjAYF6mzAAAA+xgCAG8ZVwDiGlgAjBsBADAbGmlUAAAAnxgDAjAYF2lUAAAAnxQEAjAUE3CwAAAAnxAEAjAQD6mcAAAAnwwEAjAMA0a7AAAATQ0AGCsAAABNDA2LvAAAAA4MMAD7DAIA+w0IAOIOwABNEAAYKwAAAE0PEPPBAAAAMA8OiaQAAACpDwEAMA8Or70AAABNDwBIwgAAADAPDha+AAAApA9RAABA8YRvEMMAbxHDAG8SwwCfDwQCMA8Ov6MAAACpDwAAMA8OWr8AAADiD8QA+xACAG8RgADiEsUAjBMCADATEhiCAAAApBN1AADQ8YSMFP8AjBXXAIwWAACfEwQCMBMSpIMAAACfEAMCMBAPbYAAAACfDAQCMAwDOMYAAABNDQAYKwAAAE0MDV3HAAAADgwVAPsMAgD7DQwA4g7KAKQPDgAANMCAjBABAG8RywCfDwMCMA8OD2IAAABNDwBpzAAAADAPDnvIAAAATQ8A5c0AAAAwDw4GyQAAAJ8MAwIwDAN+zgAAAE0NAAcAAAAATQwNVxAAAAAODGkATQ0ABwAAAABNDA1XEAAAAE0NDHvPAAAA+w4CAPsPDQDiENsApBFsAABAsYZvEg8AjBMBAJ8RAwIwERAIUgAAAKQRDgAANMCAbxIPAG8T3ACfEQMCMBEQ22MAAACkEQ4AADTAgIwSAQBvE8MAnxEDAjAREA9iAAAAbxHdADAREIkTAAAAjBFAADAREMYUAAAAjBEDADAREG3QAAAATREMwd4AAAAwERCh0QAAAE0SDFnfAAAATRESiAQAAAAwERAQ0gAAAE0SDFnfAAAATRESEiQAAAAwERB30wAAAKQR4QAAgPOETRMMWd8AAABNEhPk4gAAAJ8RAgIwERBJ1AAAAE0RDPbjAAAAMBEQBtUAAAAODQMATRENiAQAAABlAAEAxhEAADAREPrWAAAADg0DAE0RDRIkAAAAZQABAMYRAAAwERBo1wAAAA4NBgCkEeEAAIDzhE0SDeTiAAAAnxECAmUAAQDGEQAAMBEQMNgAAABNEQyc5AAAADAREK/ZAAAATRIABwAAAABNERK+2gAAADAREL7aAAAAnw4DAjAOA3blAAAA+w0LAE0MDTbmAAAAUg0DAJ8MAgCCDAAA5wEDBgMqAysDLAMtAy4DLwIAAAAAAAAAAAMwAzEDAQMUAzIDMwQANMCAAgAAAAAAAOA/AzQCmpmZmZmZuT8CHMdxHMdx/D8DNQM2AzcDOAM5AzoDOwM8Az0DPgM/BAAA0EEDQANBA0IDQwNEA0UDRgNHA0gDSQNKA0sDEQMQA0wDTQNOA08DUANRA1IDEwMcAx0DHgMfAwwDDQMkA1MDVANVA1YDFQNXA1gCZmZmZmZm1j8DWQUGExREND9BA1oDWwNcA10DXgNfA2AFBUhJSktMApqZmZmZmek/A2EDGgQAQPGEA2IDYwNkA2UFAlRVA2YFAVQDZwUBWQNoBABAsYUDaQMSBQFBAyUDagNrA2wDbQNuBQViY1JkZQQAQMGAAlVVVVVVVdU/Aw4CVVVVVVVV5T8DbwQAQLGGA3ADcQNyA3MDdAQAxAGHA3UDdgQA0PGEA3cDeAUCSEoDeQN6BQJ5egN7BQR8SEpLA3wEAPjBgAN9BQKAAVUDfgN/A4ABBQOCAYMBhAECAAAAAAAA6D8DgQEDggEFBnxISkxLiAEDgwEFAYoBBQV8SUpMSwOEAQOFAQUCjQGOAQIAAAAAAADQPwOGAQOHAQOIAQOJAQOKAQUJSEpLTJIBjgGTAZQBlQEDiwEDjAEEmEhyyQONAQOOAQOPAQUDigGbAZwBAgAAAAAAAMA/AgAAAAAAAPg/A5ABBQOAAY0BoAEDkQEDkgEDkwEDlAEDlQEFBqIBY6MBpAGlAaYBA5YBA5cBA5gBA5kBA5oBA5sBBQomqwFiY1KkAaUBpgGsAa0BApqZmZmZmdk/A5wBBQGwAQUDSEpLA50BBQKzAVQDngEDnwEDoAEDoQEDogEFAbkBA6MBAxYDpAEDpQEDpgEFBaQBvQG+AaMBvwEDIAMmApqZmZmZmck/BQGAAQUCggGDAQOnAQMYA6gBA6kBBQNiyAHJAQLNzMzMzMzcPwMnAygDqgEDqwEDrAEDrQEDrgEDrwEDsAEDsQEDsgEDswEDtAEDtQEDtgEFEFJjYhMU0AHRAdIB0wHUAdUB1gHXAdgB2QHaAQIAAAAAAADsPwJmZmZmZmYGQAO3AQO4AQO5AQQAgPOEA7oBA7sBA7wBA70BA74BAQ9qvwEBCQAAAAABAAAAAAEABQAAAAABAAIBAQEAAQAAAAAAAQAAAQAAAQAAAAAAAAAAAAACAAAAAAABAAAAAAAAAAAAAAAAAAACAAAAAQAAAQAAAgAAAAEAAAABAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAQABAAAAAAABAAAAAQABAAEAAAABAAAAAAABAAAAAAABAAAAAAABAAAAAAABAAAAAAABAAAAAAAAAAAAAQAAAAIAAAAAAAEAAAAAAAEAAAABAAAAAQAAAAEAAAACAAAAAQAAAAEAAAABAAAAAAACAAAAAAABAAAAAAABAAAAAAACAAAAAQAAAAAA1gAAAC0AAAAAAAEAAAAAAAIAAAEAAAEAAAIAAAAAAAEAAAAAAAEAAAAAAAIAAAAAAPgAAAwBAQEAAAEAAAAAAAAAAQABAAEAAAAAAAIAAAABAAABAAD/AAADAAABAAAAAAAA/wAAA/n3AAAbAAAAAAEAAAEAAAD/AAAFAAABAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAQAAAAAA+wAACAAAAAEAAQAAAAAAAAEAAAAAAAD/AAMAAAAAAAEAAAACAAAAAAABAAAAAAACAAAAAQAAAAIAdwAABQAAAQAAAQAAAAAAAAAAAQEAAAEAAAEAAAEAAAAAAAAAAAEAAAAAAAABAQAAAQAAAQAAAAAAAQAA/QAABgAAAQAAAAAAAP8AAPQAABAAAAEAAAEAAAEAAAAAAAAAAAEAAAAAAAABAQAAAQAAAQABAAD9AAAFAAABAAAAAAAA/wAA9QAA7AAAJQABAAABAAABAAABAAAAAAAAAAABAAAAAAAAAQAAAAAAAAAAAQAAAQEAAAEAAAEAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQEAAAEAAAAAAAD/AAADAAABAAABAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAQAAAAEAAQAAAQAAAQAAAAAAAAD3AAD2AAD4/wAhAAABAAABAAABAAAAAAAAAAABAAAAAAAAAQAAAAAAAAAAAQAAAQEAAAEAAAEAAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQEAAAEAAAEAAQAA/QAABQAAAQAAAAAAAP8AAAMAAAEAAAABAAAAAAAAAQAAAAAAAAACAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAAA+QAA8QAAGQAAAQAAAAAAAAEAAQAAAAAAAAEAAAAAAAABAAAAAAAAAgAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAIAAAAAAAEAAAC1APQAAA4AAAEAAAAAAAABAAEAAAAAAAABAAAAAAAAAQAAAAAAAAIAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAACAAAAAAABAAAAAAABAQAAAQAAAQAAAAAAAAEAAAAAAAAAAAEBAAAAAQAAAAAAAAABAAAAAAAAAQAAAQAAAAAAAAAFAQAAAQAAAAAAAP8AAPYAAA4AAAEAAP8AAO0AAPIAANEAAGoAAAAAAQAAAQAAAAAAAQAAAQAAAAEAAAAAAAAAAQAAAgEAAAIAAAEAAAAAAAAA/QAA+AAAEAAAAAABAAABAAAAAAAAAQAAAAEAAAD9AAAIAAAAAAEAAAABAAIAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAEAAAEAAAIAAAACAAAAAAABAAAAAAABAAAAAAAAAAABAAAAAgAAAAAAAAEAAAAAAAABAAAAAAAAAAAAAQAAAAEAAAAAAO0AABcAAAAAAGsAAACJAAAASwAAAAAFAAIAAAAX+wEAAE0AAc4AAAAAnwABAg4AEQCkAQIAAAAQQLwBAbcDAAAAnwECAmABCwAAAAAA+wEBAOIDBgCpBAEAMAQDiwQAAAAwAAPzBQAAALwBASoHAAAAnwEDAYIAAQAIA8ABA8EBBAAAEEADwgEDFgMgBQIEBQMPAOMDwwEBGAAAAAABAAAAAAAAAAEAAQAAAQD+AAAF5AEAAAAHAQEAAAAWvAEACwAAAACfAQIB2QEAABICAAASAAAATQIAFgEAAAD7BQAATQQFMAIAAACfBAECUgYBALwEBMcDAAAAnwQDALwCAv0EAAAAnwIAAVICAQCfAgEBggABAAUDxAEDGwPFAQMiAyMBEeADxgEBGAAAAAIAAAkAAAAAAAAAAAAAAAABAAHhAQAAAAUBAAAAAA1NAgAHAAAAAE0BAiQBAAAADgEHAOIDAwCpBAEAMAQDSgIAAAC8AQAqBAAAAJ8BAwGCAAEABQMGA3gDEgUBAgMPAO8DxAEBGAAAAAAAAQEAAP8AAATwAQAAAAUDAAAAAAxNBAAHAAAAAE0DBCQBAAAATQQBJAEAAADxAwQABAAAALwDAAsCAAAAnwMCAYIAAQADAwYDeAPEAQD2A8cBARgAAAAAAAAAAAEAAAL3AQAAAAMBAAAAAAZNAQAWAAAAALwBAVEBAAAAnwECAYIAAQACAxsDyAEA+wPJAQEYAAAAAAAB/AEAAAAEAgAAAABC4gIQAE0DADkAAAAAMAMCOQAAAABNAwBvAQAAADADAm8BAAAATQMAhwIAAAAwAwKHAgAAAE0DAFYDAAAAMAMCVgMAAABNAwDZBAAAADADAtkEAAAATQMAGgUAAAAwAwIaBQAAAE0DANsGAAAAMAMC2wYAAABNAwCjBwAAADADAqMHAAAATQMASggAAAAwAwJKCAAAAE0DACQJAAAAMAMCJAkAAABNAwDoCgAAADADAugKAAAATQMAOQsAAAAwAwI5CwAAAE0DAHEMAAAAMAMCcQwAAABNAwBuDQAAADADAm4NAAAATQMAVw4AAAAwAwJXDgAAAE0DAO0PAAAAMAMC7Q8AAACCAgIAEQMrAyoDSwNMA00DTgMsA5gBA5cBA3gDRwNWA5sBA3UDNAN3BRAAAQIDBAUGBwgJCgsMDQ4PAP4DAAEYAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAACAAAAAQAAAAEAAAABAAAAAQAAAAEAAAAA/wEAAAAFAAMAAAAe+wAAAOIBAgBvAgMAMAIBcQAAAACpAgAAMAIBzAEAAACfAAIB+wIBAE0BAjEEAAAATQABmQUAAAAOAA4A+wECAE0AAdEGAAAA+wMBAE0CAzEEAAAATQECmQUAAABvAgcA4gMJAG8ECgAwBANLCAAAAJ8ABAGCAAEACwPKAQPLAQUCAAEDzAEDAQMCAwMCAABQFX2AB0IDBAUBCAKamZmZmZnJPwCUBFcBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABUCAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAA/v///wf+//8AAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/QEAAAADAAEAAAAU+wAAAOIBAgBvAgMAMAIBcQAAAAD/AgAAAAAAADACAcwBAAAAnwACAfsAAADiAQIAbwIEADACAXEAAAAAxgIAADACAcwBAAAAnwACAYIAAQAFA8oBA8sBBQIAAQPNAQPOAQCbBBUBGAAAAQAAAQAAAP4EAAEAAAEAAP4EHAIAAAADAQIAAAAM4gECANkCAAASAAAAEgIAABICAQAwAgH/AAAAANkCAQASAAAAMAIB2AEAAACCAQIAAwNXAxUFAgABAhcYkgQAARgAAQAAAAAABwAAAAATAgAAABsAAAECAOkBowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBAQAAAABAbwMEALwBARYDAAAAnwEDAqQCBgAAAFBATQQBoQcAAABNAwR2CAAAAJ8CAgKkAwYAAABQQE0FAaEHAAAATQQF0gkAAACfAwICpAQGAAAAUEBNBgGhBwAAAE0FBjMKAAAAnwQCAqQFBgAAAFBATQcBLQsAAABNBgehDAAAAJ8FAgKkBgYAAABQQE0HAS0NAAAAnwYCAqQHBgAAAFBATQgBIQ4AAACfBwICTQgHyg8AAACkCQYAAABQQE0LAb0QAAAATQoL8hEAAACfCQICpAoGAAAAUEBNDAEtCwAAAE0LDKkSAAAAnwoCAqQLBgAAAFBATQ0BWBMAAABNDA3nFAAAAJ8LAgKkDAYAAABQQE0OAVgTAAAATQ0OqRUAAACfDAICpA0GAAAAUECkEBcAAABgQU0PECQYAAAATQ4PkxkAAACfDQICpA4GAAAAUECkERcAAABgQU0QESQYAAAATQ8QehoAAACfDgICpA8GAAAAUEBNEgFYEwAAAE0RElwbAAAATRARRBwAAACfDwICpBAGAAAAUEBNEwFYEwAAAE0SE1wbAAAATRESpB0AAACfEAICpBEGAAAAUEBNFAFYEwAAAE0TFFwbAAAATRIT9B4AAACfEQICpBIGAAAAUEBNFQFYEwAAAE0UFVwbAAAATRMUvR8AAACfEgICpBMGAAAAUEBNFgFYEwAAAE0VFlwbAAAATRQV4SAAAACfEwICpBQGAAAAUEBNFwFYEwAAAE0WF1wbAAAATRUWdiEAAACfFAICwBUiABIAAAASAAMATRYH+CMAAABvGCQAvBYWnCUAAACfFgMC4hcpAKQYLAAArKCCbxktAG8aLQCfGAMCMBgXDyYAAACkGCwAAKyggm8ZLgBvGi4AnxgDAjAYF9snAAAApBgxAADA8IJvGS4AbxouAJ8YAwIwGBcIKAAAADAXFpIyAAAAwBczABIAAgASAAUAEgAAABIAAwAwFxYTNAAAAMAXNQASAAkAEgAAABIACAASAA4AEgANABIACgASABMAEgAPABIAEAASAAQAEgARABIABwASABIAEgAUADAXFoA2AAAAwBc3ABIADAAwFxZqOAAAAMAXOQAwFxYLOgAAAMAXOwAwFxaOPAAAAMAXPQAwFxY0PgAAAE0XBuc/AAAAwBhAAMAZQQASAAAAEgADAJ8XAwJSGBYAnxcCAIIXAABCA88BBAAAAEAD0AED0QED0gED0wEEAABQQAPUAQPVAQPWAQPXAQPYAQPZAQPaAQPbAQPcAQPdAQPeAQPfAQPgAQPhAQPiAQPjAQQAAGBBA+QBA1oD5QED5gEDcgPnAQPoAQPpAQNqA70BBgAD6gED6wED7AEDawNsA2IFAyYnKAMyAzMEAKygggLNzMzMzMzsPwIAAAAAAADgPwNvAxoEAMDwggPtAQYOAykGEAO/AQYSA8YBBhMDxAEGFAPHAQYVA8kBA+4BBhYGGQkADhASExQVFhkBAAEBAAH/AAAAAAH/AAAAAAH/AAAAAAAAAAAAAAAAAf8AAAAAAAAAAAAAAAAB/wAAAAAAAAAAAf8B/wAAAAAAAAAAAAAAAAL+AAAAAAAAAAAAAAAAAv4AAAAAAAAAAAAAAAAAAAAAAv4AAAAAAAAAAAAAAAAAAAAAAf8AAAAAAAAAAAAAAAAAAAAAAf8AAAAAAAAAAAAAAAAAAAAAAv4AAAAAAAAAAAH/AAAAAAAAAAAAAAAAAf8AAAAAAAAAAAAAAAAAAEO9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf5AAAAAAP9AAAAFOwAAAABAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAGAAAAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAP3///8FAAAAAAAAAAAAAAAAAAAAQwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB2AQAAAAAAAA8AAAAAAAAABwAAAAUAAAAAAAAAAwAAABQAAADs////KAAAAAAAAAAAGi0lifNzyrv8H+HjZxDHOXeu4fY7/Eh7DStc2rQifjq3oO38Pt2jmTg=

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players")
local v2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v2.Std.Maid)
local v_u_4 = require(v2.Std.Audio)
local v_u_5 = require(v2.Std.ColorUtils)
local v_u_6 = require(v2.EzUi.Utils)
local v7 = require(v2.RoactRodux)
local v_u_8 = require(v2.Roact)
local v_u_9 = v_u_8.createElement
local v_u_10 = require(v2.Glicko2.Glicko2Consts)
local v_u_11 = require(v2.EzUi.Dictionary)
require(v2.PersistentCrewBattle.PersistentCrewBattleConsts)
local v_u_12 = require(v2.PersistentCrewBattle.PersistentCrewBattleUtils)
local v_u_13 = require(script.Parent.JoinOrCreate)
local v_u_14 = require(script.Parent.Info)
local v_u_15 = require(v2.PersistentCrewBattle.UI.BattleInvites)
local v_u_16 = require(v2.PersistentCrewBattle.UI.Elapsed)
local v_u_17 = require(v2.PersistentCrewBattle.UI.BattleCrewInfo)
local v_u_18 = require(v2.PersistentCrewBattle.UI.ReportCrew)
local v_u_19 = require(v2.PersistentCrewBattle.UI.Welcome)
local v_u_20 = require(v2.PersistentCrewBattle.UI.Responses)
local v21 = v_u_8.PureComponent:extend("PersistentCrewApp")
v21.defaultProps = {
	["size"] = UDim2.fromScale(0.9, 0.9),
	["position"] = UDim2.fromScale(0.5, 0.5),
	["anchorPoint"] = Vector2.new(0.5, 0.5)
}
function v21.init(p_u_22)
	-- upvalues: (copy) v_u_3, (copy) v_u_6, (copy) v_u_1, (copy) v_u_4
	p_u_22.maid = v_u_3.new()
	function p_u_22.onClickAdmin(p23)
		-- upvalues: (copy) p_u_22
		p_u_22.props.attemptAdmin(p23.userId)
	end
	function p_u_22.onClickRenameCrew(p24)
		-- upvalues: (copy) p_u_22
		p_u_22.props.attemptRenameCrew(p24)
	end
	function p_u_22.onClickUnAdmin(p25)
		-- upvalues: (copy) p_u_22
		p_u_22.props.attemptUnAdmin(p25.userId)
	end
	function p_u_22.onClickKick(p26)
		-- upvalues: (copy) p_u_22
		p_u_22.props.attemptKick(p26.userId)
	end
	function p_u_22.onClickJoinRequestAccept(p27)
		-- upvalues: (copy) p_u_22
		p_u_22.props.onClickJoinRequestAccept(p27.userId)
	end
	function p_u_22.onClickJoinRequestDeny(p28)
		-- upvalues: (copy) p_u_22
		p_u_22.props.onClickJoinRequestDeny(p28.userId)
	end
	p_u_22:setState({
		["showRequests"] = false,
		["countdownTil"] = 0,
		["countdownVisible"] = false,
		["isSmallScreen"] = v_u_6.isSmallScreen()
	})
	p_u_22.maid:GiveTask(v_u_6.getViewportSizeChangedSignal():Connect(function()
		-- upvalues: (copy) p_u_22, (ref) v_u_6
		p_u_22:setState({
			["isSmallScreen"] = v_u_6.isSmallScreen()
		})
	end))
	function p_u_22.onClickToggleRequests()
		-- upvalues: (copy) p_u_22, (ref) v_u_1, (ref) v_u_4
		p_u_22:setState({
			["showRequests"] = not p_u_22.state.showRequests
		})
		if v_u_1.LocalPlayer.PlayerGui then
			v_u_4.ObjectLocal(v_u_1.LocalPlayer.PlayerGui, 12617491114, {
				["Volume"] = 0.2
			})
		end
	end
	function p_u_22.onClickCloseWelcome()
		-- upvalues: (copy) p_u_22, (ref) v_u_1, (ref) v_u_4
		p_u_22:setState({
			["welcomeVisible"] = false
		})
		if v_u_1.LocalPlayer.PlayerGui then
			v_u_4.ObjectLocal(v_u_1.LocalPlayer.PlayerGui, 12617491114, {
				["Volume"] = 0.2
			})
		end
	end
	function p_u_22.onClickViewMe()
		-- upvalues: (copy) p_u_22, (ref) v_u_1, (ref) v_u_4
		p_u_22.props.attemptViewUserIdClan(v_u_1.LocalPlayer.UserId)
		p_u_22.props.onClickViewMe()
		if v_u_1.LocalPlayer.PlayerGui then
			v_u_4.ObjectLocal(v_u_1.LocalPlayer.PlayerGui, 12617491114, {
				["Volume"] = 0.2
			})
		end
	end
	function p_u_22.onCountdownElapsed(p29)
		-- upvalues: (copy) p_u_22
		if p29 < 0 then
			p_u_22:setState({
				["countdownVisible"] = false
			})
			p_u_22.props.onCountdownFinished()
		end
	end
	function p_u_22.onReportDialogClose()
		-- upvalues: (copy) p_u_22
		p_u_22:setState({
			["reportDialogVisible"] = false
		})
	end
	function p_u_22.onReportDialogSubmit(p30, p31)
		-- upvalues: (copy) p_u_22
		p_u_22.props.attemptReportCrew(p30, p31)
	end
end
function v21.render(p_u_32)
	-- upvalues: (copy) v_u_10, (copy) v_u_1, (copy) v_u_9, (copy) v_u_14, (copy) v_u_13, (copy) v_u_11, (copy) v_u_19, (copy) v_u_15, (copy) v_u_16, (copy) v_u_5, (copy) v_u_17, (copy) v_u_8, (copy) v_u_18, (copy) v_u_20
	local v33 = p_u_32.props.currentClanInfo
	local v34 = p_u_32.props.viewingClanInfo or v33
	local v35 = {}
	if p_u_32.props.groupVisible then
		local v36 = {}
		local v37, v38
		if v34 then
			local v39 = v34.ClanName
			local v40 = v34.DisplayRating or v_u_10.DEFAULT_MU
			local v41 = v34.BattlesPlayed or 0
			local v42 = v34.BattlesWon or 0
			local v43 = not v_u_1.LocalPlayer and -1 or v_u_1.LocalPlayer.UserId
			v37 = UDim2.fromScale(1, 0.5)
			v38 = UDim2.fromScale(0.5, 0.5 - (p_u_32.props.battleResponseData == nil and 0 or 0.1))
			local v44 = v_u_9
			local v45 = v_u_14
			local v46 = {
				["aspectRatio"] = 1.7777777777777777,
				["verticalPaddingRatio"] = 128,
				["clanId"] = v34.ClanId,
				["playersClanId"] = v34.PlayersClanId,
				["isPlayersClan"] = v34.PlayersClanId == v34.ClanId,
				["leaderboardRank"] = v34.LeaderboardRank,
				["isAdminOfViewingClan"] = v34.AdminIdMap[tostring(v43)] == true
			}
			if v33 then
				v33 = v33.AdminIdMap[tostring(v43)] == true
			end
			v46.isAdminOfCurrentClan = v33
			v46.battlesPlayed = v41
			v46.battlesWon = v42
			v46.attemptLeave = p_u_32.props.attemptLeave
			v46.clanOwnerUserId = v34.OwnerUserId
			v46.clanName = v39
			v46.clanDisplayRating = v40
			v46.flagColor = v34.FlagColor
			v46.membersOnlineMap = p_u_32.props.membersOnlineMap
			v46.showRequests = p_u_32.state.showRequests
			v46.members = p_u_32.props.members
			v46.joinRequests = p_u_32.props.joinRequests
			v46.isReadiedUp = p_u_32.props.isReadiedUp
			v46.playerHasAcceptedInvite = p_u_32.props.battleResponseData ~= nil
			v46.playerDisplayRating = v34.PlayerDisplayRating
			v46.attemptBattleClanId = p_u_32.props.attemptBattleClanId
			v46.attemptViewUserIdClan = p_u_32.props.attemptViewUserIdClan
			v46.onClickAdmin = p_u_32.onClickAdmin
			v46.onClickRenameCrew = p_u_32.onClickRenameCrew
			v46.onClickUnAdmin = p_u_32.onClickUnAdmin
			v46.onClickKick = p_u_32.onClickKick
			v46.onClickJoinRequestAccept = p_u_32.onClickJoinRequestAccept
			v46.onClickJoinRequestDeny = p_u_32.onClickJoinRequestDeny
			v46.onClickToggleRequests = p_u_32.onClickToggleRequests
			v46.attemptRequestJoinUserId = p_u_32.props.attemptRequestJoinUserId
			v46.onClickReadyUp = p_u_32.props.onClickReadyUp
			v46.onClickUnreadyUp = p_u_32.props.onClickUnreadyUp
			v46.networkMutexLocked = p_u_32.props.networkMutexLocked
			v46.onClickViewMe = p_u_32.onClickViewMe
			v46.onClickClose = p_u_32.props.onClickClose
			v36.Crew = v44(v45, v46)
		else
			v37 = UDim2.fromScale(1, 0.35)
			v38 = UDim2.fromScale(0.5, 0.5)
			v36.JoinOrCreate = v_u_9(v_u_13, {
				["aspectRatio"] = 1.7777777777777777,
				["verticalPaddingRatio"] = 128,
				["attemptCreate"] = p_u_32.props.attemptCreate,
				["attemptViewUserIdClan"] = p_u_32.props.attemptViewUserIdClan,
				["networkMutexLocked"] = p_u_32.props.networkMutexLocked,
				["onClickClose"] = p_u_32.props.onClickClose
			})
		end
		v35.Group = v_u_9("Frame", {
			["BackgroundTransparency"] = 0.8,
			["BackgroundColor3"] = Color3.new(0, 0, 0),
			["Size"] = v37,
			["Position"] = v38,
			["AnchorPoint"] = p_u_32.props.anchorPoint
		}, v_u_11.merge({
			["AspectRatio"] = v_u_9("UIAspectRatioConstraint", {
				["AspectRatio"] = 1.7777777777777777
			}),
			["UICorner"] = v_u_9("UICorner", {
				["CornerRadius"] = UDim.new(0, 8)
			})
		}, v36))
	end
	if p_u_32.state.welcomeVisible then
		v35.Welcome = v_u_9(v_u_19, {
			["onClickClose"] = p_u_32.onClickCloseWelcome
		})
	end
	v35.BattleInvites = v_u_9(v_u_15, {
		["size"] = UDim2.new(0.3333333333333333, 0, 0.3333333333333333, 0),
		["position"] = p_u_32.state.isSmallScreen and UDim2.new(0.5, 0, 0.6666666666666666, 0) or UDim2.new(1, 0, 0.5, 0),
		["anchorPoint"] = p_u_32.state.isSmallScreen and Vector2.new(0.5, 0.5) or Vector2.new(1, 0.5),
		["onAccept"] = p_u_32.props.onAcceptBattleInvite,
		["onDecline"] = p_u_32.props.onDeclineBattleInvite
	})
	if v34 then
		v34 = v34.ClanId
	end
	local v47 = {}
	for v48 in p_u_32.props.clanName do
		table.insert(v47, v48)
	end
	local v49
	if v47[1] == v34 then
		v49 = v47[2]
	else
		v49 = v47[1]
	end
	local v50 = p_u_32.props.attackingClanId
	local v51 = Color3.fromRGB(121, 251, 177)
	local v52 = Color3.fromRGB(255, 49, 49)
	local v53 = p_u_32.props.penalty
	local v54 = v53 ~= nil
	if p_u_32.props.isBattleServer then
		local v55 = v_u_9
		local v56 = "Frame"
		local v57 = {
			["BackgroundTransparency"] = 1,
			["Size"] = UDim2.new(1, 0, 1, 0)
		}
		local v58 = {}
		local v59 = v_u_9
		local v60 = "Frame"
		local v61 = {
			["BorderSizePixel"] = 0,
			["BackgroundTransparency"] = 1,
			["Size"] = UDim2.new(1, -48, 1, -48),
			["Position"] = UDim2.fromOffset(24, 24)
		}
		local v62 = {}
		local v63 = v_u_9
		local v64 = "UIStroke"
		local v65 = {
			["Thickness"] = 2
		}
		local v66
		if v54 then
			v66 = v52
		else
			v66 = v51
		end
		v65.Color = v66
		v65.Transparency = 0.75
		v62.UIStroke = v63(v64, v65)
		v62.UICorner = v_u_9("UICorner", {
			["CornerRadius"] = UDim.new(0, 32)
		})
		v58.BorderOuter = v59(v60, v61, v62)
		v58.BorderInner = v_u_9("Frame", {
			["BorderSizePixel"] = 0,
			["BackgroundTransparency"] = 1,
			["Size"] = UDim2.new(1, -84, 1, -84),
			["Position"] = UDim2.fromOffset(42, 42)
		}, {
			["UIStroke"] = v_u_9("UIStroke", {
				["Thickness"] = 2,
				["Color"] = v51,
				["Transparency"] = 0.5
			}),
			["UICorner"] = v_u_9("UICorner", {
				["CornerRadius"] = UDim.new(0, 32)
			})
		})
		v35.Container = v55(v56, v57, v58)
		if v54 then
			v54 = v_u_9("Frame", {
				["BorderSizePixel"] = 0,
				["BackgroundTransparency"] = 1,
				["Size"] = UDim2.new(0.5, 0, 0, 16),
				["AnchorPoint"] = Vector2.new(0.5, 0.5),
				["Position"] = UDim2.new(0.5, 0, 0, 23),
				["ZIndex"] = 3
			}, {
				["Timer"] = v_u_9("Frame", {
					["BorderSizePixel"] = 0,
					["BackgroundColor3"] = v52,
					["Size"] = UDim2.fromScale(0.1, 1),
					["AnchorPoint"] = Vector2.new(0.5, 0),
					["Position"] = UDim2.fromScale(0.5, 0)
				}, {
					["UICorners"] = v_u_9("UICorner", {
						["CornerRadius"] = UDim.new(0.25, 0)
					}),
					["Text"] = v_u_9("TextLabel", {
						["BackgroundTransparency"] = 1,
						["Size"] = UDim2.new(1, 0, 1, 0),
						["Position"] = UDim2.new(0.5, 0, 0.5, 0),
						["AnchorPoint"] = Vector2.new(0.5, 0.5),
						["Font"] = Enum.Font.FredokaOne,
						["Text"] = v53,
						["LineHeight"] = 1,
						["TextScaled"] = true,
						["TextColor3"] = Color3.new(1, 1, 1)
					})
				})
			})
		end
		v35.Penalty = v54
		local v67 = v_u_9
		local v68 = {
			["BorderSizePixel"] = 0,
			["BackgroundTransparency"] = 1,
			["Size"] = UDim2.new(0.5, 0, 0, 24),
			["AnchorPoint"] = Vector2.new(0.5, 0.5),
			["Position"] = UDim2.new(0.5, 0, 0, 41),
			["ZIndex"] = 3
		}
		local v69 = {
			["Timer"] = v_u_9("Frame", {
				["BorderSizePixel"] = 0,
				["BackgroundColor3"] = Color3.new(0.1, 0.1, 0.1),
				["Size"] = UDim2.fromScale(0.125, 1.5),
				["AnchorPoint"] = Vector2.new(0.5, 0.25),
				["Position"] = UDim2.fromScale(0.5, 0.5)
			}, {
				["UIStroke"] = v_u_9("UIStroke", {
					["Thickness"] = 2,
					["Color"] = v51,
					["Transparency"] = 0.5
				}),
				["UICorners"] = v_u_9("UICorner", {
					["CornerRadius"] = UDim.new(0.25, 0)
				}),
				["ElapsedContainer"] = v_u_9(v_u_16, {
					["font"] = Enum.Font.FredokaOne,
					["position"] = UDim2.fromScale(0.5, 0.5),
					["textColor"] = v_u_5.saturateBy(v51, 0.8),
					["createdAt"] = p_u_32.props.startedAt[v50],
					["elapsed"] = p_u_32.props.timeTook[v50],
					["disabled"] = p_u_32.props.startedAt[v50] == nil
				})
			}),
			["CrewOurs"] = v_u_9(v_u_17, {
				["clanName"] = p_u_32.props.clanName[v34],
				["backgroundColor"] = v51,
				["size"] = UDim2.fromScale(0.4, 1),
				["position"] = UDim2.fromScale(0, 0.5),
				["anchorPoint"] = Vector2.new(0, 0.5),
				["createdAt"] = p_u_32.props.startedAt[v34],
				["elapsed"] = p_u_32.props.startedAt[v34] == nil and 0 or p_u_32.props.timeTook[v34],
				["disabled"] = p_u_32.props.startedAt[v34] == nil,
				["attacking"] = v34 == v50,
				["robberiesCompleted"] = p_u_32.props.robberiesCompleted
			}),
			["CrewTheirs"] = v_u_9(v_u_17, {
				["clanName"] = p_u_32.props.clanName[v49],
				["backgroundColor"] = v51,
				["size"] = UDim2.fromScale(0.4, 1),
				["position"] = UDim2.fromScale(1, 0.5),
				["anchorPoint"] = Vector2.new(1, 0.5),
				["createdAt"] = p_u_32.props.startedAt[v49],
				["elapsed"] = p_u_32.props.startedAt[v49] == nil and 0 or p_u_32.props.timeTook[v49],
				["disabled"] = p_u_32.props.startedAt[v49] == nil,
				["attacking"] = v49 == v50,
				["robberiesCompleted"] = p_u_32.props.robberiesCompleted
			}, {
				["Report"] = v_u_9("Frame", {
					["BackgroundTransparency"] = 1,
					["Size"] = UDim2.fromScale(1, 1),
					["Position"] = UDim2.new(1, 4, 0, 0)
				}, {
					["Image"] = v_u_9("ImageButton", {
						["BackgroundColor3"] = Color3.fromRGB(251, 121, 121),
						["Size"] = UDim2.fromScale(1, 1),
						["Image"] = "rbxassetid://14280463776",
						[v_u_8.Event.Activated] = function()
							-- upvalues: (copy) p_u_32
							p_u_32:setState({
								["reportDialogVisible"] = not p_u_32.state.reportDialogVisible
							})
						end
					}, {
						["Corner"] = v_u_9("UICorner", {
							["CornerRadius"] = UDim.new(0, 4)
						})
					}),
					["AspectRatio"] = v_u_9("UIAspectRatioConstraint", {
						["AspectRatio"] = 1
					})
				})
			})
		}
		v35.TopBar = v67("Frame", v68, v69)
		if p_u_32.state.countdownVisible then
			v35.Countdown = v_u_9(v_u_16, {
				["createdAt"] = p_u_32.state.countdownTil,
				["countDown"] = true,
				["onElapsed"] = p_u_32.onCountdownElapsed,
				["textColor"] = Color3.new(0.2, 0.2, 0.2),
				["alwaysShowMinutes"] = false
			}, {
				["UIStroke"] = v_u_9("UIStroke", {
					["Thickness"] = 2,
					["Color"] = Color3.fromRGB(255, 215, 0)
				})
			})
		end
		if p_u_32.state.reportDialogVisible then
			v35.ReportDialog = v_u_9(v_u_18, {
				["size"] = UDim2.fromScale(1, 0.45),
				["onClose"] = p_u_32.onReportDialogClose,
				["onSubmit"] = p_u_32.onReportDialogSubmit
			})
		end
	end
	if p_u_32.props.battleResponseData then
		local v70 = p_u_32.props.battleResponseData
		local v71 = v70.TheirClanInfo
		local v72 = v_u_9
		local v73 = v_u_20
		local v74 = {
			["anchorPoint"] = Vector2.new(0.5, 1),
			["position"] = UDim2.fromScale(0.5, 0.875),
			["size"] = UDim2.fromScale(1, 0.2),
			["aspectRatio"] = 2.8,
			["verticalPaddingRatio"] = 64,
			["zIndex"] = 3,
			["numPlayersPerTeam"] = v70.NumPlayersPerTeam,
			["clanNameOurs"] = v70.OurClanInfo.ClanName,
			["clanOwnerOurs"] = v70.OurClanInfo.OwnerUserId,
			["clanColorOurs"] = Color3.fromHex(v70.OurClanInfo.FlagColorStr),
			["clanMembersOurs"] = v70.OurClanAccepted
		}
		local v75
		if v71 then
			v75 = v71.ClanName
		else
			v75 = nil
		end
		v74.clanNameTheirs = v75
		local v76
		if v71 then
			v76 = v71.OwnerUserId
		else
			v76 = nil
		end
		v74.clanOwnerTheirs = v76
		local v77
		if v71 then
			v77 = Color3.fromHex(v71.FlagColorStr)
		else
			v77 = nil
		end
		v74.clanColorTheirs = v77
		v74.clanMembersTheirs = v70.TheirClanAccepted
		v74.onUnAcceptBattleInvite = p_u_32.props.onUnAcceptBattleInvite
		v35.Responses = v72(v73, v74)
	end
	return v_u_8.createFragment(v35)
end
function v21.didMount(p_u_78)
	-- upvalues: (copy) v_u_12
	p_u_78:_updateWelcomeVisible()
	local function v80()
		-- upvalues: (ref) v_u_12, (copy) p_u_78
		local v79 = v_u_12.getRoundStartsAt()
		if v79 and workspace:GetServerTimeNow() < v79 then
			p_u_78:setState({
				["countdownVisible"] = true,
				["countdownTil"] = v79
			})
		end
	end
	p_u_78.maid:GiveTask(v_u_12.getRoundStartsAtAttributeChangedSignal():Connect(v80))
	v80()
end
function v21._updateWelcomeVisible(p81)
	if p81.props.isBattleServer then
		p81:setState({
			["welcomeVisible"] = true
		})
	end
end
function v21.didUpdate(p82, p83, _)
	if p82.props.isBattleServer ~= p83.isBattleServer then
		p82:_updateWelcomeVisible()
	end
end
function v21.willUnmount(p84)
	p84.maid:DoCleaning()
end
return v7.connect(function(p85, _)
	return {
		["viewingClanInfo"] = p85.viewingClanInfo,
		["currentClanInfo"] = p85.currentClanInfo,
		["membersOnlineMap"] = p85.membersOnlineMap,
		["members"] = p85.members,
		["joinRequests"] = p85.joinRequests,
		["isReadiedUp"] = p85.isReadiedUp,
		["groupVisible"] = p85.groupVisible,
		["timeTook"] = p85.timeTook,
		["startedAt"] = p85.startedAt,
		["isBattleServer"] = p85.isBattleServer,
		["clanName"] = p85.clanName,
		["networkMutexLocked"] = p85.networkMutexLocked,
		["robberiesCompleted"] = p85.robberiesCompleted,
		["attackingClanId"] = p85.attackingClanId,
		["battleResponseData"] = p85.battleResponseData,
		["penalty"] = p85.penalty
	}
end, function(p_u_86)
	-- upvalues: (copy) v_u_1, (copy) v_u_4
	return {
		["onClickClose"] = function()
			-- upvalues: (copy) p_u_86, (ref) v_u_1, (ref) v_u_4
			p_u_86({
				["type"] = "setGroupVisible",
				["value"] = false
			})
			if v_u_1.LocalPlayer.PlayerGui then
				v_u_4.ObjectLocal(v_u_1.LocalPlayer.PlayerGui, 12617491114, {
					["Volume"] = 0.2
				})
			end
		end,
		["onClickViewMe"] = function()
			-- upvalues: (copy) p_u_86
			p_u_86({
				["type"] = "setMembers",
				["value"] = {}
			})
			p_u_86({
				["type"] = "setViewingClanInfo",
				["value"] = nil
			})
		end
	}
end)(v21)
