-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgOPARJwb2ludFRvT2JqZWN0U3BhY2UBeAF5AXoOaXNQb2ludEluUHJpc20XSE9NRVNfT1dORURfRk9MREVSX05BTUUORmluZEZpcnN0Q2hpbGQFZXJyb3IpUGxheWVyIGRvZXMgbm90IGhhdmUgYSBob21lcyBvd25lZCBmb2xkZXIEX29iagROYW1lEmRvSU93blRoaXNIb21lTmFtZQVjbG9zZRNfaG9tZVB1cmNoYXNlUmVtb3RlCkZpcmVTZXJ2ZXIFX21haWQJX29uQ2xvc2VkCl9vblNhbGVZZXMJX29uU2FsZU5vEl9ob21lVW5jbGFpbVJlbW90ZQhfY29uZmlybQpHZXRPd25lcklkEF9ob21lQ2xhaW1SZW1vdGUIc2V0UHJpY2ULX3ByaWNlVmFsdWUFVmFsdWUEb3BlbhNnZXRPbkNsaWNrWWVzU2lnbmFsB0Nvbm5lY3QSZ2V0T25DbGlja05vU2lnbmFsEWdldE9uQ2xvc2VkU2lnbmFsBlVzZXJJZANuZXdLVW5jbGFpbSBob21lPyBZb3Ugd2lsbCBzdGlsbCBvd24gaXQsIGJ1dCB3aWxsIGhhdmUgdG8gY2xhaW0gdGhlIGxhbmQgYWdhaW4uBE1haWQFT25ZZXMIR2l2ZVRhc2sET25ObwZhY3Rpb24GaXNPcGVuBUNsYWltA0J1eQdVbmNsYWltB0VuYWJsZWQMcHJlVXBkYXRlRnVuBlJlbW92ZRFfcmVjZWl2ZURvb3JNb2RlbAxzZXRtZXRhdGFibGUQUFJJQ0VfVkFMVUVfTkFNRQxXYWl0Rm9yQ2hpbGQZSE9NRV9JVEVNX05FV19SRU1PVEVfTkFNRRJfaG9tZUl0ZW1OZXdSZW1vdGUZSE9NRV9QVVJDSEFTRV9SRU1PVEVfTkFNRRlET09SX0lOVEVSQUNUX1JFTU9URV9OQU1FE19kb29ySW50ZXJhY3RSZW1vdGUeVVBEQVRFX0NVU1RPTUlaSU5HX1JFTU9URV9OQU1FGF91cGRhdGVDdXN0b21pemluZ1JlbW90ZRZIT01FX0NMQUlNX1JFTU9URV9OQU1FGEhPTUVfVU5DTEFJTV9SRU1PVEVfTkFNRRdQRVJNSVNTSU9OU19GT0xERVJfTkFNRRJfcGVybWlzc2lvbnNGb2xkZXIdU0VUX1NBVkVEX1NFVFRJTkdfUkVNT1RFX05BTUUWX3NldFNhdmVkU2V0dGluZ1JlbW90ZQhTYWxlU2lnbgRTaWduBFBhcnQFTm9SYXkFVGltZWQERGlzdAhDYWxsYmFjawxQcmVVcGRhdGVGdW4PUHJlVXBkYXRlUGVyaW9kA0FkZBRvYnNlcnZlQ2hpbGRyZW5OYW1lZAREb29yB2dldE9wZW4LZ2V0Um9vdFBhcnQIUG9zaXRpb24WSXNQb2ludEluU3RhbmRpbmdQcmlzbRRIYXNQZXJtaXNzaW9uVG9FbnRlcgVDbG9zZQRPcGVuEUdldFBsYXllckJ5VXNlcklkCWdldFRlYW1JZBlQT0xJQ0VfQlVTVF9ET09SX0RVUkFUSU9OCER1cmF0aW9uCEJyZWFrIEluDWdldElubmVyTW9kZWwGYXNzZXJ0BkdldE9iagdyZXF1aXJlDkhvbWVJdGVtQmluZGVyBnNjcmlwdAZQYXJlbnQISG9tZUl0ZW0LZ2V0Q2hpbGRyZW4MR2V0SG9tZUl0ZW1zFUF0dGVtcHRDcmVhdGVIb21lSXRlbQ5nZXREZXNjZW5kYW50cwtHZXRTdXJmYWNlcwZpcGFpcnMQR2V0U3RhbmRpbmdQcmlzbQhVcFZlY3RvcgNEb3QGX3ZhdWx0D0dldElzVmF1bHRBcm1lZA1HZXRBcm1lZFZhdWx0FFJlcGxpY2F0ZUN1c3RvbWl6aW5nEk9XTkVSX0lEX0FUVFJfTkFNRQxHZXRBdHRyaWJ1dGUIdG9zdHJpbmcRX2dldFBsYXllclBlcm1PYmoeUEVSTUlTU0lPTl9DQU5fRU5URVJfQVRUUl9OQU1FHVBFUk1JU1NJT05fQ0FOX0VESVRfQVRUUl9OQU1FE0hhc1Blcm1pc3Npb25Ub0VkaXQPU2V0U2F2ZWRTZXR0aW5nB0Rlc3Ryb3kEZ2FtZQdQbGF5ZXJzCkdldFNlcnZpY2ULTG9jYWxQbGF5ZXIRUmVwbGljYXRlZFN0b3JhZ2UDU3RkC1BsYXllclV0aWxzBEdhbWUGQmluZGVyC0JpbmRlclV0aWxzAlVJBk1vZHVsZQxDaXJjbGVBY3Rpb24MQ29uZmlybWF0aW9uDVN1cmZhY2VCaW5kZXIHU3VyZmFjZQpIb21lQ29uc3RzEEhvbWVTYWxlVUlTeXN0ZW0GSG9tZVVJBURvb3IyCURvb3JVdGlscwhHYW1lVXRpbA9SeEluc3RhbmNlVXRpbHMHX19pbmRleARIb21lC19fQ2xhc3NOYW1lAB4HAwAAAAAvUgYAALwEAeYAAAAAnwQDAlsFAgFDAwQFqQQAAE0FA5kCAAAAjAYAAH0GIwAFAAAAqQQAAE0FA5kCAAAATQYCmQIAAAB9BRwABgAAAKkEAABNBQOYAwAAAIwGAAB9BhYABQAAAKkEAABNBQOYAwAAAE0GApgDAAAAfQUPAAYAAACpBAAATQUDmwQAAACMBgAAfQYJAAUAAABNBQObBAAAAE0GApsEAAAA1AUCAAYAAACpBAABqQQBAIIEAgAFAwECAAAAAAAA4D8DAgMDAwQAFAUBGAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFQAAAAAGAAMAAAAa+wAAAPsDAQBNAgOXAAAAALwAAAMBAAAAnwADAisABQCkAQMAAAAgQG8CBACfAQIBggABAPsFAgBNBAVuBQAAAE0DBLoGAAAAvAEAAwEAAACfAQMCRwECAAAAAICpAgABqQIBAIICAgAHAwYDBwMIBAAAIEADCQMKAwsALQwBGAAAAAAAAAABAQAAAAECAAAAAAAAAAEAAAABLgAAAAACAAIAAAAL+wEAAE0AAYMAAAAAnwABAfsBAQBNAAGMAQAAALwAAGsCAAAAnwACAYIAAQADAw0DDgMPAEIAARgAAAAAAQAAAAAAAUMAAAAAAgABAAAABfsBAABNAAGDAAAAAJ8AAQGCAAEAAQMNAEYAARgAAAAAAUcAAAAAAgABAAAAE/sBAABNAAHBAAAAAMYBAAAwAQAgAQAAAPsBAABNAAHBAAAAAMYBAAAwAQBxAgAAAPsBAABNAAHBAAAAAMYBAAAwAQDuAwAAAIIAAQAEAxADEQMSAxMASQABGAAAAAAAAAEAAAAAAAEAAAAAAAFKAAAAAAIAAQAAAA37AQAATQAByQAAAAC8AABrAQAAAJ8AAgH7AQAATQABwQIAAADGAQAAMAEAHQMAAACCAAEABAMUAw8DEAMVAFMAARgAAAAAAAABAAAAAAABVAAAAAACAAEAAAAH+wEAAE0AAcEAAAAAxgEAADABAB0BAAAAggABAAIDEAMVAFcAARgAAAAAAAABWAAAAAAJAgUAAACSAQ4BjwD7AgAAvAICiQAAAACfAgICRwJdAAAAAID7AwEA+wYCAE0FBpcBAAAAvAMDAwIAAACfAwMCKwMGAKQEBAAAADBAbwUFAJ8EAgHGAgAAZQANAPsIAABNBwhuBgAAAE0GB7oHAAAAvAQDAwIAAACfBAMCRwQCAAAAAICpBQABqQUBAFICBQAOAgcA+wMAAE0CA9IIAAAAvAICawkAAACfAgIBZQBkAPsDAwBNAgMNCgAAAPsFAABNBAVyCwAAAE0DBOwMAAAAnwICAfsDAwBNAgN2DQAAAJ8CAQH7AwAATQIDwQ4AAAD7BAMATQMEbQ8AAACfAwEC2QUAABICAwASAgAAvAMDxxAAAACfAwMCMAMCcREAAAD7AwAATQIDwQ4AAAD7BAMATQMEfhIAAACfAwECwAUTABICAwC8AwPHEAAAAJ8DAwIwAwLuFAAAAPsDAABNAgPBDgAAAPsEAwBNAwSVFQAAAJ8DAQLZBQIAEgIAALwDA8cQAAAAnwMDAjADAiAWAAAAZQArAPsCAAC8AgKJAAAAAJ8CAgL7BAEATQME5hcAAACaAiMAAwAAAPsDBABNAgPvGAAAAG8DGQCfAgIC+wQAAE0DBMEOAAAAMAIDHRoAAABNAwJ2GwAAAE0FAtwcAAAA2QcDABICAAC8BQXHEAAAAJ8FAwC8AwP9HQAAAJ8DAAFNAwJ2GwAAAE0FAskeAAAA2QcEABICAAC8BQXHEAAAAJ8FAwC8AwP9HQAAAJ8DAAGpAgEAggICAKkCAACCAgIAHwMWAwYDBwMIBAAAMEADCQMKAwsDFwMPAxgDGQMaAxsDEAMcAx0DEgMeBgMDEwMfAxEDIAMhAyIDFQMjAyQDJQMmBQIDBAUGOScBGAwBAAAAAADzAAAAAAAAAQEAAAABAAIAAAAAAAAAAQAAAAEACQAAAAAAAAIAAAAAAAAAAAEAAAABAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAIAAAAAAQAAAAABAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAIALgAAAAAKAQQAAAA+qQEAAMYCAAD7BAAATQMEEQAAAACfAwECKwMyAPsDAQC8AwOJAQAAAJ8DAgJHAyIAAAAAgKkBAQD7BAIA+wcDAE0GB5cCAAAAvAQEAwMAAACfBAMCKwQGAKQFBQAAAEBAbwYGAJ8FAgHGAwAAZQANAPsJAQBNCAluBwAAAE0HCLoIAAAAvAUEAwMAAACfBQMCRwUCAAAAAICpBgABqQYBAFIDBgAOAwIAbwIJAGUADQBvAgoAZQALAPsDAQC8AwOJAQAAAJ8DAgL7BQIATQQF5gsAAACaAwMABAAAAKkBAQBvAgwAMAEA8A0AAAAwAgC6CAAAAIIAAQAOAygDFgMGAwcDCAQAAEBAAwkDCgMLAykDKgMgAysDLABfLQEYMgEBAAAAAAEAAAAAAAHKAAAAAAAAAQEAAAABAAIAAAAAAAAAAQAAAAEAMQACAAIAAAAAAAAAAAEBBAABAAEuAAAAAAIAAgAAAAb7AQAATQABaQAAAAD7AQEAnwACAYIAAQABAy4AfgABGAAAAAAAAX8AAAAABQIBAAAABvsCAABSBAAAvAICQwAAAACfAgMBggABAAEDLwCCAQABGAAAAAAAAYMAAAAADQEIAAAApQH/AQUAAAAAAPsEAACePQEEBAAAAFIDAQCkAgEAAAAAQJ8CAwH7AwEATQID7wIAAACfAgECMAIBwQMAAAAwAAFuBAAAAPsFAgBNBAURBQAAALwCANMGAAAAnwIDAjACAXIHAAAA+wUCAE0EBUQIAAAAvAIA0wYAAACfAgMCMAIBpwkAAAD7BQIATQQF+QoAAAC8AgDTBgAAAJ8CAwIwAgGMCwAAAPsFAgBNBAV9DAAAALwCANMGAAAAnwIDAjACATENAAAA+wUCAE0EBf4OAAAAvAIA0wYAAACfAgMCMAIBvQ8AAAD7BQIATQQFmxAAAAC8AgDTBgAAAJ8CAwIwAgHSEQAAAPsFAgBNBAXAEgAAALwCANMGAAAAnwIDAjACAckTAAAA+wUCAE0EBZQUAAAAvAIA0wYAAACfAgMCMAIBTxUAAAD7BQIATQQF1hYAAAC8AgDTBgAAAJ8CAwIwAgFnFwAAANkCAAASAgMAEgICABIAAQBNAwFuBAAAAG8FGAC8AwPTBgAAAJ8DAwJvBRkAvAMD0wYAAACfAwMC2QQBABIAAQASAgMAEgICABICBAASAgUA2QUCABICBAASAAEAEgIDABICAgDiBiIAMAMGRBoAAABvByMAMAcGuhsAAACpBwEAMAcGthwAAACpBwAAMAcGcR0AAACMBxAAMAcG4x4AAAAwBAZGHwAAADAFBqMgAAAAbwckADAHBkQhAAAA+wgGAE0HCF8lAAAAUggGAFIJAwCfBwMBTQcBwQMAAADZCQMAEgIGABIAAwC8Bwf9JgAAAJ8HAwFNBwHBAwAAAPsKBwBNCQqtJwAAAE0KAW4EAAAAbwsoANkMBAASAAEAnwkEALwHB/0mAAAAnwcAAYIBAgApAzAEAAAAQAMhAxADCgMxAzIDGQMzAzQDNQMOAzYDNwM4AzkDOgMXAzsDFAM8Az0DPgM/A0ADQQNCAwsDQwNEA0UDRgNHA0gFCBobHB0eHyAhAyoCmpmZmZmZuT8DSQMlA0oDSwUBBwgJChwhARgAAAEAAAAAAAACAAAAAAABAAIAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAIAAAALAAAAAAAAAAAAAQAAAAAAJgAAAAAUAQABAAABAAABAAABAAABAAEAAQAAAgAAAAAAAQAAAAAAAAAEAAAAAAAAAAAAAAAAAAQdAAAAAAYCAgAAABgOAQoA+wMAAE0CAzEAAAAA+wQBAKkFAQC8AgJrAQAAAJ8CBAGpAgEAggICAE0CAHECAAAADgIIAPsDAABNAgMxAAAAAPsEAQCpBQAAvAICawEAAACfAgQBqQIAAIICAgADAzcDDwNEAIwBJwEYAAEAAAAAAAAAAQACAAABAAAAAAAAAAMAjQAAAAALAQcAAABS+wIAAE0BAjoAAAAA+wIBAJ8BAgL7AwIATQIDGwEAAAD7AwMAnwICAisCAQCCAAEATQMCOwIAAAD7BAQAUgYDALwEBOUDAAAAnwQDAqkFAAD7BgQA+wgDALwGBkEEAAAAnwYDAisGAQAOBAsAqQUBAKkGAAAwBgBxBQAAAA4BAgBvBgYAZQABAG8GBwAwBgC6CAAAAGUAKQD7BgQAvAYGiQkAAACfBgICUgcGAA4HBQD7BwUAUgkGALwHB2EKAAAAnwcDAlIIBwAOCAUA+wkCAE0ICWQLAAAAUgkHAJ8IAgJHBhUAAAAAAPsKAgBNCQpkCwAAAPsKAwCfCQIC8QgOAAkAAACpBQEAqQkBADAJAHEFAAAA+woGAE0JCu4MAAAAMAkA5Q0AAABvCQ4AMAkAuggAAABlAAEAqQUAADAFAPAPAAAAggABABADTANNA04DTwNQA0QDUQNSAwsDFgNTA1QDVQNWA1cDLACXAS0BGAAAAAAAAgAAAAABAQIAAQAAAAADAQAAAAAAAAEBAAABAAAAAAAAAgAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAAAAQEAAAEAAAAAAQAAAAIDAAGaAAAAAAIAAgAAAAb7AQAATQABaQAAAAD7AQEAnwACAYIAAQABAy4AwwEAARgAAAAAAAHEAAAAAAoCBgAAAD77AwAATQIDjgAAAABSAwEAnwICAm8FAQC8AwIDAgAAAJ8DAwK7AQMDUgUDAKQEBAAAADBAnwQCAdkEAAASAAAAEgABANkFAQASAgAAEgABABICAQASAgIAEgAAABICAwASAgQA4gYNADADBkQFAAAAbwcOADAHBroGAAAAqQcBADAHBrYHAAAAqQcAADAHBnEIAAAAjAcKADAHBuMJAAAAMAQGRgoAAAAwBQajCwAAAG8HDwAwBwZEDAAAAPsIBQBNBwhfEAAAAFIIBgBSCQMAnwcDAU0HAMERAAAA2QkCABICBQASAAMAvAcH/RIAAACfBwMBggABABMDWANLAwcDWQQAADBAA0IDCwNDA0QDRQNGA0cDSAUIBQYHCAkKCwwDUgIAAAAAAADgPwNJAxADJQMMDQ6IAS8BGAAAAAAAAQAAAAEAAAAAAQAACwAAAAAAAAAhAQABAAABAAABAAABAAABAAEAAQAAAgAAAAAAAQAAAAAAAAADiQAAAAACAQAAAAADTQEAbgAAAACCAQIAAQMKAMcBWgEYAAAAyAAAAAAGAQIAAAAW+wEAACsBDACkAQEAAAAAQKQFBAAAADBATQQFJAUAAABNAwTpBgAAAE0CA7ACAAAAnwECAt4BAAD7AgEATQECSAcAAAD7AgAATQMAbggAAACfAQMAggEAAAkDWwQAAABAA1wDXQQAADBAA14DXwNgAwoAygFhARgAAAEAAAAAAAAAAAAAAAIAAAAAAAAAywAAAAAFAgAAAAAPRwECAAAAAICpAwABqQMBALsBAwKkAgEAAAAAQJ8CAgFNAgCnAgAAAFIEAQC8AgJrAwAAAJ8CAwGCAAEABANZBAAAAEADNAMPANABYgEYAAAAAAAAAAABAAAAAAAB0QAAAAAEAQIAAAAI+wIAAE0BAmcAAAAA+wIBAE0DAG4BAAAAnwEDAIIBAAACA2MDCgDUAWQBGAAAAAAAAAAA1QAAAAAPAgAAAABJvAIANgAAAACfAgICpAMCAAAAEEBSBAIAnwMCBFEDPQC8CAcNAwAAAJ8IAgNNCggRBAAAAG8MBQC8CgorBgAAAJ8KAwJvCwcAtwoyAAsAAABSDgEAvAwI5ggAAACfDAMCWw0JCUMLDA2pCgAATQwLmQoAAACMDQAAfQ0jAAwAAACpCgAATQwLmQoAAABNDQmZCgAAAH0MHAANAAAAqQoAAE0MC5gLAAAAjA0AAH0NFgAMAAAAqQoAAE0MC5gLAAAATQ0JmAsAAAB9DA8ADQAAAKkKAABNDAubDAAAAIwNAAB9DQkADAAAAE0MC5sMAAAATQ0JmwwAAADUDAIADQAAAKkKAAGpCgEADgoCAKkKAQCCCgIAbgPC/wIAAICpAwAAggMCAA0DZANlBAAAEEADZgNnBwAAAAAAAIA/AAAAAAAAAAADaAIAAAAAAADgvwMBAgAAAAAAAOA/AwIDAwMEANcBTwEYwwAAAQAAAAABAAACAAAAAAAAAAA5AAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMoA+QAKABUAAAAACgEAAAAAFLwBAPYAAAAAnwECAqQCAgAAABBAUgMBAJ8CAgRRAggATQcGfQMAAAAOBwUAvAgHGgQAAACfCAICDggBAIIHAgBuAvf/AgAAgMYCAACCAgIABQNhA2UEAAAQQANpA2oA5QFrARgAAAABAAAAAAEAAQAAAAAB/QAGAOYAAAAABQIAAAAAB00CAL0AAAAAUgQBALwCAmsBAAAAnwIDAYIAAQACAzkDDwDvAWwBGAAAAAAAAAHwAAAAAAUBAQAAAAlNAQBuAAAAAPsEAABNAwR4AQAAALwBARICAAAAnwEDAIIBAAADAwoDbQNuAPIBFgEYAAAAAAAAAAAA8wAAAAAHAgAAAAcEAAAFAgQHD00CAE8AAAAATQYB5gEAAAC7PwYCpAUDAAAAIECfBQICvAMCAwQAAACfAwMCKwMCAMYEAACCBAIAggMCAAUDPQMgA28EAAAgQAMHAPUBcAEYAAABAAAAAAAAAAABAQAC9gAAAAAIAgEAAAcEAAAFAgQHElIEAQC8AgBxAAAAAJ8CAwIrAgIAqQMAAIIDAgD7BwAATQYHzgEAAAC8BAISAgAAAJ8EAwIqBAIAAQAAAKkDAAGpAwEAggMCAAMDcANxA24A/QFQARgAAAAAAQEAAgAAAAAAAAAAAAD+AAAAAAgCAQAABwQAAAUCBAcSUgQBALwCAHEAAAAAnwIDAisCAgCpAwAAggMCAPsHAABNBgf4AQAAALwEAhICAAAAnwQDAioEAgABAAAAqQMAAakDAQCCAwIAAwNwA3IDbgCEAnMBGAAAAAABAQACAAAAAAAAAAAAAAUBAAAABwMAAAAIBQAABQMEAwEITQMAZwAAAABSBQEAUgYCALwDA2sBAAAAnwMEAYIAAQACAz8DDwCLAnQBGAAAAAAAAAABDAEAAAAEAQAAAAARTQEAwQAAAABHAQIAAAAAgKkDAAGpAwEAuwEDAqQCAgAAABBAnwICAcYCAAAwAgDBAAAAALwCAVADAAAAnwICAYIAAQAEAxADWQQAABBAA3UAjgJ1ARgAAAEAAAAAAAAAAQAAAQAAAQ8BAAAAEwAAAQIAtwGjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCTQEAMQQAAACkAgEAAAAAQG8EBQC8AgIWAwAAAJ8CAwKkAwcAAABgQE0FAqEIAAAATQQFdgkAAACfAwICpAQHAAAAYEBNBgK9CwAAAE0FBqYKAAAAnwQCAqQFBwAAAGBATQgCoQgAAABNBwh/DAAAAE0GB9kNAAAAnwUCAqQGBwAAAGBATQgCQA8AAABNBwhcDgAAAJ8GAgJNBwbdEAAAAKQIBwAAAGBATQoCQA8AAABNCQqEEQAAAJ8IAgKkCQcAAABgQKQNFAAAADBBTQwNJBUAAABNCwyhFgAAAE0KCz8SAAAAnwkCAqQKBwAAAGBApA0UAAAAMEFNDA0kFQAAAE0LDFkXAAAAnwoCAsYLAACkDAcAAABgQKQQFAAAADBBTQ8QJBUAAABNDg9MGQAAAE0NDk8YAAAAnwwCAqQNBwAAAGBATQ8CpRoAAABNDg+8GwAAAJ8NAgKkDgcAAABgQE0QAr0LAAAATQ8QPRwAAACfDgICpA8HAAAAYEBNEQKhCAAAAE0QEVIdAAAAnw8CAsAQHgD/EQYAAAAAADAREW4fAAAAbxIgADASEeUhAAAAwBIiABIAEQASAAMAEgAKABIAAQASAAwAEgAIABIABwASAA8AMBIR7yMAAADAEiQAEgANABIABAASAAEAEgAAABIACgASAAcAMBIRQyUAAADAEiYAMBIRyScAAADZEgQAEgEL/xIABQAwEhH2KAAAAMASKQAwEhGUKgAAAMASKwASAAUAEgAJADASETYsAAAAwBItADASEeUuAAAAwBIvADASEdkwAAAAwBIxADASETgyAAAAwBIzABIACgAwEhGJNAAAAMASNQAwEhFxNgAAAMASNwASAAoAMBIRQTgAAADAEjkAEgAKADASERM6AAAAwBI7ADASEUU8AAAAwBI9ADASEVA+AAAAwQsAAIIRAgA/A3YEAAAAQAN3A3gDeQN6A1sEAABgQAN7AyMDfAN9A34DfwOAAQOBAQOCAQODAQOEAQNdBAAAMEEDXgOFAQOGAQOHAQOIAQOJAQOKAQOLAQOMAQYAA40BA44BA48BBgsDIQYPAy8GEANaA2EGEgNiBhMDZAYUA08GFQNrBhYDbAYXAxYGGANwBhkDUAYaA3MGGwN0BhwDdRAACw8QERITFBUWFxgZGhscAQABBwABAAAAAAABAAEAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAQAAAAAAAAIAAAAAAAAAAAAAAQAAAAAAAAAAAQEAAAAAAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAgUAAQABAAABAAAAAAAAAAAAAGwAeQAAAAAAAD8AAAMAAAAABgAABAAAAAADAAAOAAAKAAADAAAAAwAACAAAAAcAAAAHAAADAAAHAAEAAACHAAAAAB1oGNMhk69/a1rcubXRd3ab9A3Sd2iETnJgxWOcM5nk3WyFWPAv1Cjl

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players")
local v_u_2 = v_u_1.LocalPlayer
local v3 = game:GetService("ReplicatedStorage")
local v_u_4 = require(v3.Std.Maid)
local v_u_5 = require(v3.Game.PlayerUtils)
local v_u_6 = require(v3.Std.Binder.BinderUtils)
local v_u_7 = require(v3.Module.UI).CircleAction
local v_u_8 = require(v3.Module.Confirmation)
local v_u_9 = require(script.Parent.Surface.SurfaceBinder)
local v_u_10 = require(script.Parent.HomeConsts)
local v_u_11 = nil
local v_u_12 = require(script.Parent.HomeUI.HomeSaleUISystem)
local v_u_13 = require(v3.Door2.DoorUtils)
require(v3.Game.GameUtil)
local v_u_14 = require(v3.Std.RxInstanceUtils)
local v_u_15 = {}
v_u_15.__index = v_u_15
v_u_15.__ClassName = "Home"
function v_u_15.new(p16)
	-- upvalues: (copy) v_u_15, (copy) v_u_4, (copy) v_u_10, (copy) v_u_2, (copy) v_u_12, (copy) v_u_8, (copy) v_u_7, (copy) v_u_14
	local v_u_17 = {}
	local v18 = v_u_15
	setmetatable(v_u_17, v18)
	v_u_17._maid = v_u_4.new()
	v_u_17._obj = p16
	v_u_17._priceValue = p16:WaitForChild(v_u_10.PRICE_VALUE_NAME)
	v_u_17._homeItemNewRemote = p16:WaitForChild(v_u_10.HOME_ITEM_NEW_REMOTE_NAME)
	v_u_17._homePurchaseRemote = p16:WaitForChild(v_u_10.HOME_PURCHASE_REMOTE_NAME)
	v_u_17._doorInteractRemote = p16:WaitForChild(v_u_10.DOOR_INTERACT_REMOTE_NAME)
	v_u_17._updateCustomizingRemote = p16:WaitForChild(v_u_10.UPDATE_CUSTOMIZING_REMOTE_NAME)
	v_u_17._homeClaimRemote = p16:WaitForChild(v_u_10.HOME_CLAIM_REMOTE_NAME)
	v_u_17._homeUnclaimRemote = p16:WaitForChild(v_u_10.HOME_UNCLAIM_REMOTE_NAME)
	v_u_17._permissionsFolder = p16:WaitForChild(v_u_10.PERMISSIONS_FOLDER_NAME)
	v_u_17._setSavedSettingRemote = p16:WaitForChild(v_u_10.SET_SAVED_SETTING_REMOTE_NAME)
	local v_u_19 = v_u_17._obj:WaitForChild("SaleSign"):WaitForChild("Sign")
	local v29 = {
		["Part"] = v_u_19,
		["Name"] = "Buy",
		["NoRay"] = true,
		["Timed"] = false,
		["Dist"] = 16,
		["Callback"] = function(_, p20)
			-- upvalues: (copy) v_u_17, (ref) v_u_2, (ref) v_u_10, (ref) v_u_12, (ref) v_u_8
			if not p20 then
				return false
			end
			if v_u_17:GetOwnerId() == nil then
				local v21 = v_u_2:FindFirstChild(v_u_10.HOMES_OWNED_FOLDER_NAME)
				local v22
				if v21 then
					v22 = v21:FindFirstChild(v_u_17._obj.Name) ~= nil
				else
					error("Player does not have a homes owned folder")
					v22 = nil
				end
				if v22 then
					v_u_17._homeClaimRemote:FireServer()
				else
					v_u_12.setPrice(v_u_17._priceValue.Value)
					v_u_12.open()
					v_u_17._maid._onSaleYes = v_u_12.getOnClickYesSignal():Connect(function()
						-- upvalues: (ref) v_u_12, (ref) v_u_17
						v_u_12.close()
						v_u_17._homePurchaseRemote:FireServer()
					end)
					v_u_17._maid._onSaleNo = v_u_12.getOnClickNoSignal():Connect(function()
						-- upvalues: (ref) v_u_12
						v_u_12.close()
					end)
					v_u_17._maid._onClosed = v_u_12.getOnClosedSignal():Connect(function()
						-- upvalues: (ref) v_u_17
						v_u_17._maid._onClosed = nil
						v_u_17._maid._onSaleYes = nil
						v_u_17._maid._onSaleNo = nil
					end)
				end
			elseif v_u_17:GetOwnerId() == v_u_2.UserId then
				local v23 = v_u_8.new("Unclaim home? You will still own it, but will have to claim the land again.")
				v_u_17._maid._confirm = v23
				v23.Maid:GiveTask(v23.OnYes:Connect(function()
					-- upvalues: (ref) v_u_17
					v_u_17._homeUnclaimRemote:FireServer()
					v_u_17._maid._confirm = nil
				end))
				v23.Maid:GiveTask(v23.OnNo:Connect(function()
					-- upvalues: (ref) v_u_17
					v_u_17._maid._confirm = nil
				end))
			end
			return true
		end,
		["PreUpdateFun"] = function(p24)
			-- upvalues: (ref) v_u_12, (copy) v_u_17, (ref) v_u_2, (ref) v_u_10
			local v25 = false
			local v26 = nil
			if not v_u_12.isOpen() then
				if v_u_17:GetOwnerId() == nil then
					v25 = true
					local v27 = v_u_2:FindFirstChild(v_u_10.HOMES_OWNED_FOLDER_NAME)
					local v28
					if v27 then
						v28 = v27:FindFirstChild(v_u_17._obj.Name) ~= nil
					else
						error("Player does not have a homes owned folder")
						v28 = nil
					end
					if v28 then
						v26 = "Claim"
					else
						v26 = "Buy"
					end
				elseif v_u_17:GetOwnerId() == v_u_2.UserId then
					v25 = true
					v26 = "Unclaim"
				end
			end
			p24.Enabled = v25
			p24.Name = v26
		end,
		["PreUpdatePeriod"] = 0.1
	}
	v_u_7.Add(v29, v_u_19)
	v_u_17._maid:GiveTask(function()
		-- upvalues: (ref) v_u_7, (copy) v_u_19
		v_u_7.Remove(v_u_19)
	end)
	v_u_17._maid:GiveTask(v_u_14.observeChildrenNamed(v_u_17._obj, "Door", function(p30, _)
		-- upvalues: (copy) v_u_17
		v_u_17:_receiveDoorModel(p30)
	end))
	return v_u_17
end
function v_u_15._receiveDoorModel(p_u_31, p_u_32)
	-- upvalues: (copy) v_u_13, (copy) v_u_5, (copy) v_u_2, (copy) v_u_1, (copy) v_u_10, (copy) v_u_7
	local v_u_33 = v_u_13.getInnerModel(p_u_32):FindFirstChild("Door")
	assert(v_u_33)
	local v43 = {
		["Part"] = v_u_33,
		["Name"] = "Open",
		["NoRay"] = true,
		["Timed"] = false,
		["Dist"] = 10,
		["Callback"] = function(p34, p35)
			-- upvalues: (copy) p_u_31, (copy) p_u_32
			if p35 then
				p_u_31._doorInteractRemote:FireServer(p_u_32, true)
				return true
			else
				if p34.Timed then
					p_u_31._doorInteractRemote:FireServer(p_u_32, false)
				end
				return false
			end
		end,
		["PreUpdateFun"] = function(p36)
			-- upvalues: (ref) v_u_13, (copy) p_u_32, (ref) v_u_5, (ref) v_u_2, (copy) p_u_31, (ref) v_u_1, (ref) v_u_10
			local v37 = v_u_13.getOpen(p_u_32)
			local v38 = v_u_5.getRootPart(v_u_2)
			if v38 then
				local v39 = p_u_31:IsPointInStandingPrism(v38.Position)
				local v40
				if p_u_31:HasPermissionToEnter(v_u_2) or v39 then
					p36.Timed = false
					p36.Name = v37 and "Close" or "Open"
					v40 = true
				else
					local v41 = p_u_31:GetOwnerId()
					local v42
					if v41 then
						v42 = v_u_1:GetPlayerByUserId(v41)
					else
						v42 = v41
					end
					if v42 then
						v42 = v_u_5.getTeamId(v42)
					end
					if v41 == nil or v42 == v_u_5.getTeamId(v_u_2) then
						v40 = false
					else
						p36.Timed = true
						p36.Duration = v_u_10.POLICE_BUST_DOOR_DURATION
						p36.Name = "Break In"
						v40 = true
					end
				end
				p36.Enabled = v40
			end
		end,
		["PreUpdatePeriod"] = 0.5
	}
	v_u_7.Add(v43, v_u_33)
	p_u_31._maid:GiveTask(function()
		-- upvalues: (ref) v_u_7, (copy) v_u_33
		v_u_7.Remove(v_u_33)
	end)
end
function v_u_15.GetObj(p44)
	return p44._obj
end
function v_u_15.GetHomeItems(p45)
	-- upvalues: (ref) v_u_11, (copy) v_u_6
	if not v_u_11 then
		v_u_11 = require(script.Parent.HomeItem.HomeItemBinder)
	end
	return v_u_6.getChildren(v_u_11, p45._obj)
end
function v_u_15.AttemptCreateHomeItem(p46, p47)
	local v48 = p47 ~= nil
	assert(v48)
	p46._homeItemNewRemote:FireServer(p47)
end
function v_u_15.GetSurfaces(p49)
	-- upvalues: (copy) v_u_6, (copy) v_u_9
	return v_u_6.getDescendants(v_u_9, p49._obj)
end
function v_u_15.IsPointInStandingPrism(p50, p51)
	local v52 = p50:GetSurfaces()
	for _, v53 in ipairs(v52) do
		local v54, v55 = v53:GetStandingPrism()
		if v54.UpVector:Dot(Vector3.new(0, 1, 0)) >= -0.5 then
			local v56 = v54:pointToObjectSpace(p51) + v55 * 0.5
			local v57
			if v56.x >= 0 and (v56.x <= v55.x and (v56.y >= 0 and (v56.y <= v55.y and v56.z >= 0))) then
				v57 = v56.z <= v55.z
			else
				v57 = false
			end
			if v57 then
				return true
			end
		end
	end
	return false
end
function v_u_15.GetArmedVault(p58)
	local v59 = p58:GetHomeItems()
	for _, v60 in ipairs(v59) do
		local v61 = v60._vault
		if v61 and v61:GetIsVaultArmed() then
			return v61
		end
	end
	return nil
end
function v_u_15.ReplicateCustomizing(p62, p63)
	p62._updateCustomizingRemote:FireServer(p63)
end
function v_u_15.GetOwnerId(p64)
	-- upvalues: (copy) v_u_10
	return p64._obj:GetAttribute(v_u_10.OWNER_ID_ATTR_NAME)
end
function v_u_15._getPlayerPermObj(p65, p66)
	local v67 = p65._permissionsFolder
	local v68 = p66.UserId
	return v67:FindFirstChild((tostring(v68))) or nil
end
function v_u_15.HasPermissionToEnter(p69, p70)
	-- upvalues: (copy) v_u_10
	local v71 = p69:_getPlayerPermObj(p70)
	if v71 then
		return v71:GetAttribute(v_u_10.PERMISSION_CAN_ENTER_ATTR_NAME) == true
	else
		return false
	end
end
function v_u_15.HasPermissionToEdit(p72, p73)
	-- upvalues: (copy) v_u_10
	local v74 = p72:_getPlayerPermObj(p73)
	if v74 then
		return v74:GetAttribute(v_u_10.PERMISSION_CAN_EDIT_ATTR_NAME) == true
	else
		return false
	end
end
function v_u_15.SetSavedSetting(p75, p76, p77)
	p75._setSavedSettingRemote:FireServer(p76, p77)
end
function v_u_15.Destroy(p78)
	local v79 = p78._maid
	local v80 = v79 ~= nil
	assert(v80)
	p78._maid = nil
	v79:Destroy()
end
return v_u_15
