-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNMDEZsYWdDb2xvclN0cgZDb2xvcjMHZnJvbUhleBhnZXRGbGFnQ29sb3JGcm9tQ2xhbkluZm8FVG9IZXgWc2V0RmxhZ0NvbG9ySW5DbGFuSW5mbw1NZW1iZXJJbmZvTWFwHGdldE1lbWJlckluZm9NYXBGcm9tQ2xhbkluZm8GdHlwZW9mBm51bWJlch1wbGF5ZXJVc2VySWQgbXVzdCBiZSBhIG51bWJlcgZhc3NlcnQIdG9zdHJpbmcXc2V0TWVtYmVySW5mb0luQ2xhbkluZm8ETmFtZRdnZXRDbGFuTmFtZUZyb21DbGFuSW5mbwtPd25lclVzZXJJZAh0b251bWJlchpnZXRPd25lclVzZXJJZEZyb21DbGFuSW5mbyNvd25lclVzZXJJZCBtdXN0IGJlIGEgbnVtYmVyIG9yIG5pbBhzZXRPd25lclVzZXJJZEluQ2xhbkluZm8KQWRtaW5JZE1hcBhzZXRBZG1pblN0YXR1c0luQ2xhbkluZm8ZZ2V0QWRtaW5JZE1hcEZyb21DbGFuSW5mbxNnZXROYW1lRnJvbUNsYW5JbmZvEXNldE5hbWVJbkNsYW5JbmZvGGNsYW5JbmZvIG11c3Qgbm90IGJlIG5pbBxnZXRJc1BsYXllckFkbWluRnJvbUNsYW5JbmZvFEpvaW5SZXF1ZXN0VXNlcklkTWFwI2dldEpvaW5SZXF1ZXN0VXNlcklkTWFwRnJvbUNsYW5JbmZvCEluc3RhbmNlA25ldwZGb2xkZXIaTUVNQkVSU19PTkxJTkVfT0JKRUNUX05BTUUGUGFyZW50Gl9jcmVhdGVNZW1iZXJzT25saW5lRm9sZGVyBnN0cmluZxdjbGFuSWQgbXVzdCBiZSBhIHN0cmluZwtOdW1iZXJWYWx1ZQVWYWx1ZR5fY3JlYXRlTWVtYmVyc09ubGluZUNoYW5nZWRWYWwdZ2V0TWVtYmVyc09ubGluZUNoYW5nZWRTaWduYWwgZ2V0TnVtTWVtYmVyc09ubGluZUNoYW5nZWRTaWduYWwQZ2V0TWVtYmVyc09ubGluZRNnZXROdW1NZW1iZXJzT25saW5lDkZpbmRGaXJzdENoaWxkB0NoYW5nZWQLR2V0Q2hpbGRyZW4bY2hpbGQuTmFtZSBtdXN0IGJlIGEgc3RyaW5nB0Rlc3Ryb3klbWVtYmVyc09ubGluZU1hcCBrZXlzIG11c3QgYmUgc3RyaW5ncwlCb29sVmFsdWUTc2V0TWVtYmVyc09ubGluZU1hcBlDVVJSRU5UX0NMQU5fSURfQVRUUl9OQU1FGUdldEF0dHJpYnV0ZUNoYW5nZWRTaWduYWwdZ2V0Q3VycmVudENsYW5JZENoYW5nZWRTaWduYWwMU2V0QXR0cmlidXRlEHNldEN1cnJlbnRDbGFuSWQMR2V0QXR0cmlidXRlEGdldEN1cnJlbnRDbGFuSWQHYm9vbGVhbh52YWx1ZSBtdXN0IGJlIGEgYm9vbGVhbiBvciBuaWwlSVNfUExBWUVSX0NMQU5fQURNSU5fQ0FDSEVEX0FUVFJfTkFNRRZzZXRJc1BsYXllckFkbWluQ2FjaGVkFmdldElzUGxheWVyQWRtaW5DYWNoZWQjZ2V0SXNQbGF5ZXJBZG1pbkNhY2hlZENoYW5nZWRTaWduYWwISm9pblRpbWUJd29ya3NwYWNlEEdldFNlcnZlclRpbWVOb3cSZ2V0RW1wdHlNZW1iZXJJbmZvBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlBENsYW4KQ2xhbkNvbnN0cwAcAwEAAAAADE0CAOQAAAAARwIHAAAAAACkAQMAAAgQgE0CAOQAAAAAnwECAoIBAgDGAQAAggECAAQDAQMCAwMEAAgQgAAHBAEYAAAAAAAAAAAAAAAACAAAAAAEAgAAAAcEAAAFAg8HBrwCAR8AAAAAnwICAjACAOQBAAAAggABAAIDBQMBAAoGARgAAAAAAAELAAAAAAIBAAAAAANNAQC1AAAAAIIBAgABAwcADQgBGAAAAA4AAAAABwMAAAAAI7ssAQNSBgEApAUBAAAAAECfBQIC8AUCAAIAAACpBAABqQQBAIEBBAQDAAAAbwUDAKQDBQAAAEBAnwMDAQ4CCQBNAwC1BgAAALs/AQNSBQEApAQIAAAAcECfBAICagIDBIIAAQBNAwC1BgAAALs/AQNSBQEApAQIAAAAcECfBAICxgUAAGoFAwSCAAEACQMJBAAAAEADCgMLAwwEAABAQAMHAw0EAABwQAAQDgEYAAAAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAIAAAAAAAAAAAIVAAAAAAIBAAAAAANNAQC6AAAAAIIBAgABAw8AHBABGAAAAB0AAAAAAwEAAAAAB00CABIAAAAAuz4CAqQBAgAAABBAnwECAoIBAgADAxEDEgQAABBAAB8TARgAAAAAAAAAIAAAAAAGAgAAAAcEAAAFAg+CFakDAQC7LAEDUgUBAKQEAQAAAABAnwQCAvAEBQACAAAARwECAAAAAACpAwABqQMBAIEBAwQDAAAAbwQDAKQCBQAAAEBAnwIDATABABIGAAAAggABAAcDCQQAAABAAwoDFAMMBAAAQEADEQAiFQEYAAAAAAAAAAAAAAAAAAAAAAAAAwABIwAAAAAHAwAAAAgFAAAFAw8CDxi7LAEDUgYBAKQFAQAAAABAnwUCAvAFAgACAAAAqQQAAakEAQCBAQQEAwAAAG8FAwCkAwUAAABAQJ8DAwFNAwBdBgAAALs/AQNSBQEApAQIAAAAcECfBAICagIDBIIAAQAJAwkEAAAAQAMKAwsDDAQAAEBAAxYDDQQAAHBAACgXARgAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAEpAAAAAAIBAAAAAANNAQBdAAAAAIIBAgABAxYALRgBGAAAAC4AAAAAAgEAAAAAA00BALoAAAAAggECAAEDDwAwGQEYAAAAMQAAAAACAgAAAAADMAEAugAAAACCAAEAAQMPADMaARgAAAE0AAAAAAcCAQAAAClHAAIAAAAAgKkDAAGpAwEAgQEDBAAAAABvBAAApAICAAAAEECfAgMBuywBA1IFAQCkBAQAAAAwQJ8EAgLwBAIABQAAAKkDAAGpAwEAgQEDBAYAAABvBAYApAICAAAAEECfAgMB+wUAAE0EBUkHAAAAUgUAAJ8EAgK7PwEDUgYBAKQFCQAAAIBAnwUCAocDBAUqAwIAAQAAAKkCAAGpAgEAggICAAoDGwMMBAAAEEADCQQAADBAAwoDCwMYAw0EAACAQAA2HAEYAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAA3AAAAAAIBAAAAAANNAQAtAAAAAIIBAgABAx0AOx4BGAAAADwAAAAAAwACAAAADaQAAgAABACAbwEDAJ8AAgL7AgAATQECPgQAAAAwAQC6BQAAAPsBAQAwAQAkBgAAAIIAAgAHAx8DIAQABACAAyEDIgMPAyMAPiQBGAAAAAABAAAAAAEAAAE/AAAAAAYCAAAABwQAAAUCDwMbuywBA1IFAQCkBAEAAAAAQJ8EAgLwBAIAAgAAAKkDAAGpAwEAgQEDBAMAAABvBAMApAIFAAAAQECfAgMBpAIIAAAcYIBvAwkAnwICAjABAroKAAAAjAMAADADAuwLAAAAMAACJAwAAACCAgIADQMJBAAAAEADJQMmAwwEAABAQAMfAyAEABxggAMnAw8DKAMjAEQpARgAAAAAAAAAAAAAAAAAAAACAAAAAQABAAABAAFFAAAAAAMBAQAABgMAAAUBAwb7AgAATQECnQAAAABSAgAAnwECAIIBAAABAyoATSsBGAAAAAAAAE4AAAAACAEBAAAGAwAABQEDILssAANSBAAApAMBAAAAAECfAwIC8AMCAAIAAACpAgABqQIBAIEBAgQDAAAAbwMDAKQBBQAAAEBAnwEDAfsCAABNAQItBgAAAFICAACfAQICKwECAIwCAACCAgIAjAIAAFIDAQDGBAAAxgUAAGQDAQCVAgIHbgP+/wIAAACCAgIACAMJBAAAAEADJQMmAwwEAABAQAMsAgAAAAAAAPA/AFAtARgAAAAAAAAAAAAAAAAAAAABAAAAAAEBAAIBAAAAAf8AA1EAAAAABQECAAAGAwAABQEDIbssAANSBAAApAMBAAAAAECfAwIC8AMCAAIAAACpAgABqQIBAIEBAgQDAAAAbwMDAKQBBQAAAEBAnwEDAfsBAAD7BAEATQMEPgYAAAC8AQEDBwAAAJ8BAwIrAQEAggABAFIEAAC8AgEDBwAAAJ8CAwIrAgEAggABAE0DAoUIAAAAggMCAAkDCQQAAABAAyUDJgMMBAAAQEADIgMuAy8AXCoBGAAAAAAAAAAAAAAAAAAAAAIAAAAAAAABAQIAAAABAQIAAF0AAAAACwECAAAGAwAABQEDK7ssAANSBAAApAMBAAAAAECfAwIC8AMCAAIAAACpAgABqQIBAIEBAgQDAAAAbwMDAKQBBQAAAEBAnwEDAfsBAAD7BAEATQMEPgYAAAC8AQEDBwAAAJ8BAwIrAQEAggABAFIEAAC8AgEDBwAAAJ8CAwIrAgEAggABAP8DAAAAAAAAvAQCaAgAAACfBAIEZAQEAE0JCLoJAAAAqQoBAGoKAwluBPv/AgAAAIIDAgAKAwkEAAAAQAMlAyYDDAQAAEBAAyIDLgMwAw8AaSwBGAAAAAAAAAAAAAAAAAAAAAIAAAAAAAABAQIAAAABAQIAAQAAAAEAAAD/AANqAAAAAA0CAwAABwQAAAUCAw98uywAA1IFAACkBAEAAAAAQJ8EAgLwBAIAAgAAAKkDAAGpAwEAgQEDBAMAAABvBAMApAIFAAAAQECfAgMB+wIAAPsFAQBNBAU+BgAAALwCAgMHAAAAnwIDAisCBQD7BAIATQMEpggAAACfAwECUgIDAFIFAAC8AwIDBwAAAJ8DAwIrAwcA+wUCAE0EBUcJAAAAUgUCAFIGAACfBAMCUgMEAFIEAQArBAIA/wQAAAAAAABSAQQAvAQDaAoAAACfBAIEZAQXAE0MCLoLAAAAuywMAqQLAQAAAABAnwsCAvALAgACAAAAqQoAAakKAQCBAQoEDAAAAG8LDACkCQUAAABAQJ8JAwFNCgi6CwAAAIcJAQorCQMAvAkIUA0AAACfCQIBbgTo/wIAAABSBAEAxgUAAMYGAABkBA8AuywHA1IMBwCkCwEAAAAAQJ8LAgLwCwIAAgAAAKkKAAGpCgEAgQEKBA4AAABvCw4ApAkFAAAAQECfCQMBbgTw/wIAAABSBAEAxgUAAMYGAABkBBEAUgsHALwJAwMHAAAAnwkDAisJDACkChEAAEDwgG8LEgCfCgICUgkKADAHCboLAAAAqQoBADAKCewTAAAAMAMJJBQAAABuBO7/AgAAAE0EA+wTAAAAlQQEFTAEA+wTAAAAggABABYDCQQAAABAAyUDJgMMBAAAQEADIgMuAyQDKQMwAw8DMQMyAzMDHwMgBABA8IADNAMoAyMCAAAAAAAA8D8AejUBGAAAAAAAAAAAAAAAAAAAAAIAAAAAAAABAQAAAAACAAAAAQEAAAAAAAACAAAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAEAAP0ABgAAAAEAAAAAAAAAAAAAAAAAAP8AAwAAAAEAAAABAQAAAAABAAEAAAEA+gAKAAAAAAF7AAAAAAUBAQAAAAf7BAAATQMEQwAAAAC8AQAWAQAAAJ8BAwCCAQAAAgM2AzcAnAE4ARgAAAAAAAAAnQAAAAAGAgEAAAcEAAAFAg+DGqkDAQC7LAEDUgUBAKQEAQAAAABAnwQCAvAEBQACAAAARwECAAAAAACpAwABqQMBAIEBAwQDAAAAbwQDAKQCBQAAAEBAnwIDAfsFAABNBAVDBgAAAFIFAQC8AgAuBwAAAJ8CBAGCAAEACAMJBAAAAEADJQMmAwwEAABAQAM2AzkAnwE6ARgAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAaAAAAAABQEBAAAAB/sEAABNAwRDAAAAALwBABIBAAAAnwEDAIIBAAACAzYDOwCkATwBGAAAAAAAAAClAAAAAAYCAQAABwQAAAUCD4EaqQMBALssAQNSBQEApAQBAAAAAECfBAIC8AQFAAIAAABHAQIAAAAAAKkDAAGpAwEAgQEDBAMAAABvBAMApAIFAAAAQECfAgMB+wUAAE0EBb8GAAAAUgUBALwCAC4HAAAAnwIEAYIAAQAIAwkEAAAAQAM9Az4DDAQAAEBAAz8DOQCnAUABGAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAABqAAAAAAFAQEAAAYDAAAFAQcH+wQAAE0DBL8AAAAAvAEAEgEAAACfAQMAggEAAAIDPwM7AKwBQQEYAAAAAAAAAK0AAAAABQEBAAAGAwAABQEHB/sEAABNAwS/AAAAALwBABYBAAAAnwEDAIIBAAACAz8DNwCvAUIBGAAAAAAAAACwAAAAAAMAAAAAAAniAAEApAEDAAAAIEC8AQG3BAAAAJ8BAgIwAQCFAAAAAIIAAgAFA0MFAQADRAQAACBAA0UAsgFGARgAAQAAAAAAAACzAAAAAAQAAAECAHSjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwDLBgAAAE0CAzQHAAAAnwECAv8CBgAAAAAAwAMIADADApUJAAAAwAMKADADArILAAAAwAMMADADAm8NAAAAwAMOADADAn4PAAAAwAMQADADArURAAAAwAMSADADAiUTAAAAwAMUADADAtcVAAAAwAMWADADAgoXAAAAwAMYADADAkkZAAAAwAMaADADAhcbAAAAwAMcADADAlEdAAAAwAMeABIAAgAwAwI+HwAAAMADIAAwAwL+IQAAAMADIgASAAEAEgAAADADAqYjAAAAwAMkADADAkclAAAAwAMmABIAAgAwAwJnJwAAAMADKAASAAIAMAMCfSkAAADAAyoAEgAAABIAAQAwAwKdKwAAAMADLAASAAAAEgABADADAi0tAAAAwAMuABIAAAASAAEAEgACADADApYvAAAAwAMwABIAAQAwAwJJMQAAAMADMgASAAEAMAMCBjMAAADAAzQAEgABADADAho1AAAAwAM2ABIAAQAwAwIvNwAAAMADOAASAAEAMAMCOzkAAADAAzoAEgABADADAvY7AAAAwAM8ADADAqI9AAAAggICAD4DRwQAAABAA0gDSQNKBAAAQEADSwNMBgADBAYBAwYGAgMIBgMDDgYEAxAGBQMTBgYDFQYHAxcGCAMYBgkDGQYKAxoGCwMcBgwDHgYNAyQGDgMpBg8DKwYQAy0GEQMqBhIDLAYTAzUGFAM4BhUDOgYWAzwGFwNABhgDQQYZA0IGGgNGGwABAgMEBQYHCAkKCwwNDg8QERITFBUWFxgZGgEAARgAAQAAAAAAAQAAAAAAAAIAAgAAAwAAAwAAAwAADAAAAwAAAwAABgAABQAAAwAAAwAAAwAAAAUAAAMAAAAABgAACQAAAAMAAAAMAAAAAA0AAAAAEQAAAAAAIgAAAAMAAAAFAAAAAwAAAAUAAAADAAAAAwAABQEAAAAAG81g6yleVAA8/6SBvci8bdggQbJVIBNkLfpWCPJwFTdOhvryiZ2VITk=

-- Decompiled by Krnl

local v_u_1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v_u_1.Clan.ClanConsts)
local v_u_73 = {
	["getFlagColorFromClanInfo"] = function(p3)
		if p3.FlagColorStr == nil then
			return nil
		else
			return Color3.fromHex(p3.FlagColorStr)
		end
	end,
	["setFlagColorInClanInfo"] = function(p4, p5)
		p4.FlagColorStr = p5:ToHex()
	end,
	["getMemberInfoMapFromClanInfo"] = function(p6)
		return p6.MemberInfoMap
	end,
	["setMemberInfoInClanInfo"] = function(p7, p8, p9)
		local v10 = typeof(p8) == "number"
		assert(v10, "playerUserId must be a number")
		if p9 then
			p7.MemberInfoMap[tostring(p8)] = p9
		else
			p7.MemberInfoMap[tostring(p8)] = nil
		end
	end,
	["getClanNameFromClanInfo"] = function(p11)
		return p11.Name
	end,
	["getOwnerUserIdFromClanInfo"] = function(p12)
		local v13 = p12.OwnerUserId
		return tonumber(v13)
	end,
	["setOwnerUserIdInClanInfo"] = function(p14, p15)
		local v16 = typeof(p15) == "number" and true or p15 == nil
		assert(v16, "ownerUserId must be a number or nil")
		p14.OwnerUserId = p15
	end,
	["setAdminStatusInClanInfo"] = function(p17, p18, p19)
		local v20 = typeof(p18) == "number"
		assert(v20, "playerUserId must be a number")
		p17.AdminIdMap[tostring(p18)] = p19
	end,
	["getAdminIdMapFromClanInfo"] = function(p21)
		return p21.AdminIdMap
	end,
	["getNameFromClanInfo"] = function(p22)
		return p22.Name
	end,
	["setNameInClanInfo"] = function(p23, p24)
		p23.Name = p24
	end,
	["getIsPlayerAdminFromClanInfo"] = function(p25, p26)
		-- upvalues: (copy) v_u_73
		local v27 = p25 ~= nil
		assert(v27, "clanInfo must not be nil")
		local v28 = typeof(p26) == "number"
		assert(v28, "playerUserId must be a number")
		return v_u_73.getAdminIdMapFromClanInfo(p25)[tostring(p26)] == true
	end,
	["getJoinRequestUserIdMapFromClanInfo"] = function(p29)
		return p29.JoinRequestUserIdMap
	end,
	["_createMembersOnlineFolder"] = function()
		-- upvalues: (copy) v_u_2, (copy) v_u_1
		local v30 = Instance.new("Folder")
		v30.Name = v_u_2.MEMBERS_ONLINE_OBJECT_NAME
		v30.Parent = v_u_1
		return v30
	end,
	["_createMembersOnlineChangedVal"] = function(p31, p32)
		local v33 = typeof(p32) == "string"
		assert(v33, "clanId must be a string")
		local v34 = Instance.new("NumberValue")
		v34.Name = p32
		v34.Value = 0
		v34.Parent = p31
		return v34
	end,
	["getNumMembersOnlineChangedSignal"] = function(p35)
		-- upvalues: (copy) v_u_73
		return v_u_73.getMembersOnlineChangedSignal(p35)
	end,
	["getNumMembersOnline"] = function(p36)
		-- upvalues: (copy) v_u_73
		local v37 = typeof(p36) == "string"
		assert(v37, "clanId must be a string")
		local v38 = v_u_73.getMembersOnline(p36)
		if not v38 then
			return 0
		end
		local v39 = 0
		for _, _ in v38 do
			v39 = v39 + 1
		end
		return v39
	end,
	["getMembersOnlineChangedSignal"] = function(p40)
		-- upvalues: (copy) v_u_1, (copy) v_u_2
		local v41 = typeof(p40) == "string"
		assert(v41, "clanId must be a string")
		local v42 = v_u_1:FindFirstChild(v_u_2.MEMBERS_ONLINE_OBJECT_NAME)
		if v42 then
			local v43 = v42:FindFirstChild(p40)
			if v43 then
				return v43.Changed
			end
		end
	end,
	["getMembersOnline"] = function(p44)
		-- upvalues: (copy) v_u_1, (copy) v_u_2
		local v45 = typeof(p44) == "string"
		assert(v45, "clanId must be a string")
		local v46 = v_u_1:FindFirstChild(v_u_2.MEMBERS_ONLINE_OBJECT_NAME)
		if v46 then
			local v47 = v46:FindFirstChild(p44)
			if v47 then
				local v48 = {}
				for _, v49 in v47:GetChildren() do
					v48[v49.Name] = true
				end
				return v48
			end
		end
	end,
	["setMembersOnlineMap"] = function(p50, p51)
		-- upvalues: (copy) v_u_1, (copy) v_u_2, (copy) v_u_73
		local v52 = typeof(p50) == "string"
		assert(v52, "clanId must be a string")
		local v53 = v_u_1:FindFirstChild(v_u_2.MEMBERS_ONLINE_OBJECT_NAME) or v_u_73._createMembersOnlineFolder()
		local v54 = v53:FindFirstChild(p50) or v_u_73._createMembersOnlineChangedVal(v53, p50)
		local v55 = p51 or {}
		for _, v56 in v54:GetChildren() do
			local v57 = v56.Name
			local v58 = typeof(v57) == "string"
			assert(v58, "child.Name must be a string")
			if not v55[v56.Name] then
				v56:Destroy()
			end
		end
		for v59, _ in v55 do
			local v60 = typeof(v59) == "string"
			assert(v60, "membersOnlineMap keys must be strings")
		end
		for v61, _ in v55 do
			if not v54:FindFirstChild(v61) then
				local v62 = Instance.new("BoolValue")
				v62.Name = v61
				v62.Value = true
				v62.Parent = v54
			end
		end
		v54.Value = v54.Value + 1
	end,
	["getCurrentClanIdChangedSignal"] = function(p63)
		-- upvalues: (copy) v_u_2
		return p63:GetAttributeChangedSignal(v_u_2.CURRENT_CLAN_ID_ATTR_NAME)
	end,
	["setCurrentClanId"] = function(p64, p65)
		-- upvalues: (copy) v_u_2
		local v66 = typeof(p65) == "string" and true or p65 == nil
		assert(v66, "clanId must be a string")
		p64:SetAttribute(v_u_2.CURRENT_CLAN_ID_ATTR_NAME, p65)
	end,
	["getCurrentClanId"] = function(p67)
		-- upvalues: (copy) v_u_2
		return p67:GetAttribute(v_u_2.CURRENT_CLAN_ID_ATTR_NAME)
	end,
	["setIsPlayerAdminCached"] = function(p68, p69)
		-- upvalues: (copy) v_u_2
		local v70 = typeof(p69) == "boolean" and true or p69 == nil
		assert(v70, "value must be a boolean or nil")
		p68:SetAttribute(v_u_2.IS_PLAYER_CLAN_ADMIN_CACHED_ATTR_NAME, p69)
	end,
	["getIsPlayerAdminCached"] = function(p71)
		-- upvalues: (copy) v_u_2
		return p71:GetAttribute(v_u_2.IS_PLAYER_CLAN_ADMIN_CACHED_ATTR_NAME)
	end,
	["getIsPlayerAdminCachedChangedSignal"] = function(p72)
		-- upvalues: (copy) v_u_2
		return p72:GetAttributeChangedSignal(v_u_2.IS_PLAYER_CLAN_ADMIN_CACHED_ATTR_NAME)
	end,
	["getEmptyMemberInfo"] = function()
		return {
			["JoinTime"] = workspace:GetServerTimeNow()
		}
	end
}
return v_u_73
