-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgM7CkRpc3BhdGNoZXIEdHlwZQhmdW5jdGlvbgdfX2luZGV4Dk1ha2VEaWN0aW9uYXJ5DkFjdGl2YXRpb25LZXlzEVNldEFjdGl2YXRpb25LZXlzCVBsYWNlTmFtZQZXaW5kb3cLVXBkYXRlTGFiZWwMU2V0UGxhY2VOYW1lB0VuYWJsZWQKU2V0RW5hYmxlZBZBY3RpdmF0aW9uVW5sb2Nrc01vdXNlGVNldEFjdGl2YXRpb25VbmxvY2tzTW91c2UEU2hvdwRIaWRlCUlzVmlzaWJsZQpTZXRWaXNpYmxlBlRvZ2dsZQxNYXNoVG9FbmFibGUPU2V0TWFzaFRvRW5hYmxlD0hpZGVPbkxvc3RGb2N1cxJTZXRIaWRlT25Mb3N0Rm9jdXMGRXZlbnRzC0hhbmRsZUV2ZW50CFJlZ2lzdHJ5BnNjcmlwdAVUeXBlcwxXYWl0Rm9yQ2hpbGQPUmVnaXN0ZXJUeXBlc0luCENvbW1hbmRzElJlZ2lzdGVyQ29tbWFuZHNJbgRnYW1lClJ1blNlcnZpY2UKR2V0U2VydmljZQZTaGFyZWQHcmVxdWlyZQRVdGlsCElzQ2xpZW50BWVycm9ycVNlcnZlciBzY3JpcHRzIGNhbm5vdCByZXF1aXJlIHRoZSBjbGllbnQgbGlicmFyeS4gUGxlYXNlIHJlcXVpcmUgdGhlIHNlcnZlciBsaWJyYXJ5IHRvIHVzZSBDbWRyIGluIHlvdXIgb3duIGNvZGUuDlJlcGxpY2F0ZWRSb290DlJlbW90ZUZ1bmN0aW9uC1JlbW90ZUV2ZW50DENtZHJGdW5jdGlvbglDbWRyRXZlbnQERW51bQdLZXlDb2RlAkYyBENtZHIMc2V0bWV0YXRhYmxlDUNtZHJJbnRlcmZhY2UISXNTZXJ2ZXIEdGFzawVkZWxheQ1PbkNsaWVudEV2ZW50B0Nvbm5lY3QURGVmYXVsdEV2ZW50SGFuZGxlcnMADwQBAgEAAAijAQAA+wEAAPsDAQBNAgMKAAAAAN0DAACfAQAAggEAAAEDAQAcAAEYAAEAAAAAAAAcAAAAAAUCAAAAABBNAwAKAAAAAIcCAwEOAgsAuygCA1IEAgCkAwIAAAAQQJ8DAgLwAwUAAwAAgNkDAAASAAIAEgAAAIIDAgCCAAEABAMBAwIEAAAQQAMDAQAZBAEYAAAAAQAAAAAAAAABAAAABBoAAAAABAIBAAAACPsDAABNAgMVAAAAAFIDAQCfAgICMAIA2gEAAACCAAEAAgMFAwYAKgcBGAAAAAAAAAABKwAAAAAEAgEAAAAJMAEAsQAAAAD7AwAATQIDZQEAAAC8AgLXAgAAAJ8CAgGCAAEAAwMIAwkDCgAvCwEYAAABAAAAAAABMAAAAAACAgAAAAADMAEA8AAAAACCAAEAAQMMADUNARgAAAE2AAAAAAICAAAAAAMwAQAeAAAAAIIAAQABAw4AOg8BGAAAATsAAAAAAwEBAAAAC00BAPAAAAAAKwEBAIIAAQD7AgAATQECZQEAAAC8AQGYAgAAAJ8BAgGCAAEAAwMMAwkDEAA/EAEYAAAAAQMAAAAAAAFAAAAAAAMBAQAAAAf7AgAATQECZQAAAAC8AQHPAQAAAJ8BAgGCAAEAAgMJAxEASBEBGAAAAAAAAAFJAAAAAAYBAQAAABVNAQDwAAAAACsBBAC8AQDPAQAAAJ8BAgCCAQAA+wIAAE0BAmUCAAAA+wUAAE0EBWUCAAAAvAQEMQMAAACfBAICVgMEALwBAakEAAAAnwEDAYIAAQAFAwwDEQMJAxIDEwBNFAEYAAAAAQAAAAMAAAAAAAAAAAAAAAABTgAAAAAFAgAAAAAIMAEAXwAAAAAOAQQAqQQAALwCAJ4BAAAAnwIDAYIAAQACAxUDDQBWFgEYAAACAQAAAAJXAAAAAAICAAAAAAMwAQCeAAAAAIIAAQABAxcAXxgBGAAAAWAAAAAABAMAAAAABE0DAFoAAAAAagIDAYIAAQABAxkAZBoBGAAAAAFlAAAAAAUAAQAAABn7AQAATQABsQAAAACkAgIAAAAQQG8EAwC8AgLTBAAAAJ8CAwC8AADUBQAAAJ8AAAH7AQAATQABsQAAAACkAgIAAAAQQG8EBgC8AgLTBAAAAJ8CAwC8AAACBwAAAJ8AAAGCAAEACAMbAxwEAAAQQAMdAx4DHwMgAyEAawABGAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAFsAAAAAAQBAQEAAA2jAQAA+wMAAE0CA1oAAAAAhwECAA4BBgD7AwAATQIDWgAAAACHAQIA3QIAAJ8BAAGCAAEAAQMZAHIAARgAAQAAAAABAAAAAAACcgAAAAAJAAABAgC3AaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQG8DBgC8AQHTBwAAAJ8BAwKkAgkAAACAQG8FCgC8AwHTBwAAAJ8DAwCfAgACvAMABAsAAACfAwICKgMFAAAAAICkAw0AAADAQG8EDgCfAwIBxgMAAOIFGQCkBgUAAABAQDAGBWQPAAAApAYFAAAAQEBvCBoAvAYG0wcAAACfBgMCMAYFaxAAAACkBgUAAABAQG8IGwC8BgbTBwAAAJ8GAwIwBgUhEQAAAP8GAQAAAAAApAcfAB50wMGpCAEAaggGBzAGBdoSAAAAqQYBADAGBfATAAAAqQYAADAGBV8UAAAAqQYAADAGBR4VAAAAqQYBADAGBZ4WAAAAbwYgADAGBbEXAAAAMAIFngoAAAD/BgAAAAAAADAGBVoYAAAA4gYiAMAHIwAwBwZuIQAAAJ49BQMGAAAApAQlAAAAQEKfBAMCUgMEAKQECQAAAIBATQUBsSYAAACfBAICUgUDAJ8EAgIwBAOxJgAAAKQECQAAAIBATQUBCicAAACfBAICUgUDAJ8EAgIwBAMKJwAAAKQECQAAAIBApAYFAAAAQEBNBQbsKAAAAJ8EAgJSBQMAnwQCAsAFKQASAAIAMAUDFyoAAADABSsAEgAEADAFA4gsAAAAwAUtADAFA54uAAAAwAUvADAFAzowAAAAwAUxABIABAAwBQOYMgAAAMAFMwASAAQAMAUDzzQAAADABTUAEgAEADAFA6w2AAAAwAU3ADAFA2I4AAAAwAU5ADAFA5E6AAAAwAU7ADAFA5Q8AAAAvAUACz0AAACfBQICKgUHAAAAAICkBUAAAPzgg4wGAQDZBwsAEgED/58FAwFNBgMhEQAAAE0FBoxBAAAA2QcMABIBA/+8BQXHQgAAAJ8FAwGkBQkAAACAQKQHBQAAAEBATQYHKkMAAACfBQICUgYDAJ8FAgHBAwAAggMCAEQDIgQAAABAAyMDJAMcBAAAQEADJQMeAyYEAACAQAMnAygDKQQAAMBAAyoDKwMsAy0DBgMMAxUDDgMXAwgDGQULDxAREhMUFRYXChgDLgMvAzADMQMyBB50wMEDMwMEBQEhBgEDNAQAAEBCAxsDAQM1BgIDBwYDAwsGBAMNBgUDDwYGAxAGBwMRBggDFAYJAxYGCgMYBgsDGgM2AzcDOAQA/OCDAzkDOgM7DQECAwQFBgcICQoLDA0BAAEYAAAAAAAAAAEAAAAAAAEAAAAAAAACAAAAAAEAAAADAQEAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAABAAABAAABAAABAAABAAEAAAABAwAAAADxAAAAGQAAAAAAAAAAAQAAAAAAAAAAAwAAAAAAAAAAAwAAAAUAAAAGAAAFAAAFAAAACQAAAAUAAAAJAAAJAAAFAAAFAAAAAAIAAAAAAAcAAAAAAAAAAAYAAAAAAAAAAAIAAQAAAAAOLlecjqdxzQYck/YaDIhPYeNlUn/3tWZKpyNBJ8mI4YtfFeamG/4dGg==

-- Decompiled by Krnl

local v1 = game:GetService("RunService")
local v2 = script:WaitForChild("Shared")
local v_u_3 = require(v2:WaitForChild("Util"))
if v1:IsClient() == false then
	error("Server scripts cannot require the client library. Please require the server library to use Cmdr in your own code.")
end
local v4 = {
	["ReplicatedRoot"] = script,
	["RemoteFunction"] = script:WaitForChild("CmdrFunction"),
	["RemoteEvent"] = script:WaitForChild("CmdrEvent"),
	["ActivationKeys"] = {
		[Enum.KeyCode.F2] = true
	},
	["Enabled"] = true,
	["MashToEnable"] = false,
	["ActivationUnlocksMouse"] = false,
	["HideOnLostFocus"] = true,
	["PlaceName"] = "Cmdr",
	["Util"] = v_u_3,
	["Events"] = {}
}
local v_u_8 = setmetatable(v4, {
	["__index"] = function(p_u_5, p6)
		local v_u_7 = p_u_5.Dispatcher[p6]
		if v_u_7 and type(v_u_7) == "function" then
			return function(_, ...)
				-- upvalues: (copy) v_u_7, (copy) p_u_5
				return v_u_7(p_u_5.Dispatcher, ...)
			end
		end
	end
})
v_u_8.Registry = require(v2.Registry)(v_u_8)
v_u_8.Dispatcher = require(v2.Dispatcher)(v_u_8)
local v_u_9 = require(script.CmdrInterface)(v_u_8)
function v_u_8.SetActivationKeys(p10, p11)
	-- upvalues: (copy) v_u_3
	p10.ActivationKeys = v_u_3.MakeDictionary(p11)
end
function v_u_8.SetPlaceName(p12, p13)
	-- upvalues: (copy) v_u_9
	p12.PlaceName = p13
	v_u_9.Window:UpdateLabel()
end
function v_u_8.SetEnabled(p14, p15)
	p14.Enabled = p15
end
function v_u_8.SetActivationUnlocksMouse(p16, p17)
	p16.ActivationUnlocksMouse = p17
end
function v_u_8.Show(p18)
	-- upvalues: (copy) v_u_9
	if p18.Enabled then
		v_u_9.Window:Show()
	end
end
function v_u_8.Hide(_)
	-- upvalues: (copy) v_u_9
	v_u_9.Window:Hide()
end
function v_u_8.Toggle(p19)
	-- upvalues: (copy) v_u_9
	if not p19.Enabled then
		return p19:Hide()
	end
	v_u_9.Window:SetVisible(not v_u_9.Window:IsVisible())
end
function v_u_8.SetMashToEnable(p20, p21)
	p20.MashToEnable = p21
	if p21 then
		p20:SetEnabled(false)
	end
end
function v_u_8.SetHideOnLostFocus(p22, p23)
	p22.HideOnLostFocus = p23
end
function v_u_8.HandleEvent(p24, p25, p26)
	p24.Events[p25] = p26
end
if v1:IsServer() == false then
	task.delay(1, function()
		-- upvalues: (ref) v_u_8
		v_u_8.Registry:RegisterTypesIn(script:WaitForChild("Types"))
		v_u_8.Registry:RegisterCommandsIn(script:WaitForChild("Commands"))
	end)
end
v_u_8.RemoteEvent.OnClientEvent:Connect(function(p27, ...)
	-- upvalues: (ref) v_u_8
	if v_u_8.Events[p27] then
		v_u_8.Events[p27](...)
	end
end)
require(script.DefaultEventHandlers)(v_u_8)
return v_u_8
