-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMQBE5hbWUQSHVtYW5vaWRSb290UGFydAR3YXJuGUh1bWFub2lkUm9vdFBhcnQgZXhwZWN0ZWQeUk9PVF9QQVJUX0hJVF9SQURJVVNfQVRUUl9OQU1FDEdldEF0dHJpYnV0ZRxERUZBVUxUX1JPT1RfUEFSVF9ISVRfUkFESVVTFGdldFJvb3RQYXJ0SGl0UmFkaXVzDFNldEF0dHJpYnV0ZRRzZXRSb290UGFydEhpdFJhZGl1cwRnYW1lEVJlcGxpY2F0ZWRTdG9yYWdlCkdldFNlcnZpY2UHcmVxdWlyZQZDb21iYXQMQ29tYmF0Q29uc3RzAAMFAQEAAAYDAAAFAQcUTQEAugAAAADwAQUAAQAAAKQBAwAAACBAbwIEAJ8BAgH7BAAATQMEvQUAAAC8AQASBgAAAJ8BAwJSAgEAKwIDAPsDAABNAgPKBwAAAIICAgAIAwEDAgMDBAAAIEADBAMFAwYDBwAECAEYAAAAAAEAAAACAAAAAAABAAAAAAAFAAAAAAYCAQAABwQAAAUCBwIQTQIAugAAAADwAgUAAQAAAKQCAwAAACBAbwMEAJ8CAgH7BQAATQQFvQUAAABSBQEAvAIALgYAAACfAgQBggABAAcDAQMCAwMEAAAgQAMEAwUDCQALCgEYAAAAAAEAAAACAAAAAAAAAQwAAAAABAAAAQIAGaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DAEIGAAAATQIDjwcAAACfAQIC/wICAAAAAADAAwgAEgABADADAj8JAAAAwAMKABIAAQAwAwIzCwAAAIICAgAMAwsEAAAAQAMMAw0DDgQAAEBAAw8DEAYAAwgGAQMKAgABAQABGAAAAAAAAAABAAAAAAAAAQABAAAABwAAAAYBAAAAAAJH3wnDw8i8W3UbY1czUIF7DWQ3KiqVZkmdPAXLyPatMqtGSwlUsO5y

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Combat.CombatConsts)
return {
	["getRootPartHitRadius"] = function(p3)
		-- upvalues: (copy) v_u_2
		if p3.Name ~= "HumanoidRootPart" then
			warn("HumanoidRootPart expected")
		end
		return p3:GetAttribute(v_u_2.ROOT_PART_HIT_RADIUS_ATTR_NAME) or v_u_2.DEFAULT_ROOT_PART_HIT_RADIUS
	end,
	["setRootPartHitRadius"] = function(p4, p5)
		-- upvalues: (copy) v_u_2
		if p4.Name ~= "HumanoidRootPart" then
			warn("HumanoidRootPart expected")
		end
		p4:SetAttribute(v_u_2.ROOT_PART_HIT_RADIUS_ATTR_NAME, p5)
	end
}
