-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMZBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplCFRBR19OQU1FGEZJUlNUX1NFR01FTlRfVkFMVUVfTkFNRRlTRUNPTkRfU0VHTUVOVF9WQUxVRV9OQU1FFVVQREFURURfQVRfVkFMVUVfTkFNRRFPRkZTRVRfVkFMVUVfTkFNRRBHUkFQSF9WQUxVRV9OQU1FGlNFQVRfT1dORURfUEFSVF9WQUxVRV9OQU1FGlNFQVRfVVBEQVRFRF9BVF9WQUxVRV9OQU1FF0FUVEVNUFRfU0lUX1JFTU9URV9OQU1FBENhcnQMRmlyc3RTZWdtZW50DVNlY29uZFNlZ21lbnQJVXBkYXRlZEF0Bk9mZnNldAVHcmFwaAlPd25lZFBhcnQNU2VhdFVwZGF0ZWRBdANTaXQAAQUAAAECAC6jAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CAxgHAAAAnwECAk0CAQAIAAAA4gMSAG8EEwAwBAO0CQAAAG8EFAAwBAOeCgAAAG8EFQAwBAOvCwAAAG8EFgAwBAPiDAAAAG8EFwAwBAOODQAAAG8EGAAwBAOaDgAAAG8EGQAwBAO2DwAAAG8EGgAwBAOBEAAAAG8EGwAwBAPGEQAAAJ8CAgCCAgAAHAMBBAAAAEADAgMDAwQEAABAQAMFAwYDBwMIAwkDCgMLAwwDDQMOAw8DEAUJCQoLDA0ODxARAxEDEgMTAxQDFQMWAxcDGAMZAAEAARgAAQAAAAAAAQAAAAAAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAIAAPYAAQAAAAAATnYMp95ApWp8smYz/noBRfTVZVuGbniO+ht65Q6+gvFL86H5jfXJSQ==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Std.TableUtils).requireValidIndexAndFreeze({
	["TAG_NAME"] = "Cart",
	["FIRST_SEGMENT_VALUE_NAME"] = "FirstSegment",
	["SECOND_SEGMENT_VALUE_NAME"] = "SecondSegment",
	["UPDATED_AT_VALUE_NAME"] = "UpdatedAt",
	["OFFSET_VALUE_NAME"] = "Offset",
	["GRAPH_VALUE_NAME"] = "Graph",
	["SEAT_OWNED_PART_VALUE_NAME"] = "OwnedPart",
	["SEAT_UPDATED_AT_VALUE_NAME"] = "SeatUpdatedAt",
	["ATTEMPT_SIT_REMOTE_NAME"] = "Sit"
})
