-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMSBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzBkVudW1lchpyZXF1aXJlVmFsaWRJbmRleEFuZEZyZWV6ZRVUSU1FX09GX0RBWV9BVFRSX05BTUUQVElNRV9PRl9EQVlfRU5VTRdQUkVDSVBJVEFUSU9OX0FUVFJfTkFNRRJQUkVDSVBJVEFUSU9OX0VOVU0JVGltZU9mRGF5A0RheQVOaWdodA1QcmVjaXBpdGF0aW9uBFJhaW4ETm9uZQABCQAAAQIANKMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DAKEGAAAATQIDGAcAAACfAQICpAIFAAAAQEBNBAChBgAAAE0DBFcIAAAAnwICAk0DAQAJAAAA4gQOAG8FDwAwBQTDCgAAAFIFAgD/BgAAAgAAAG8HEABvCBEAxQYHAwEAAACfBQICMAUEsgsAAABvBRIAMAUEZwwAAABSBQIA/wYAAAIAAABvBxMAbwgUAMUGBwMBAAAAnwUCAjAFBDgNAAAAnwMCAIIDAAAVAwEEAAAAQAMCAwMDBAQAAEBAAwUDBgMHAwgDCQMKAwsDDAUECgsMDQMNAw4DDwMQAxEDEgABAAEYAAEAAAAAAAEAAAAAAAABAAAAAAAAAgAAAQAAAQAAAAAAAAAAAAEAAAEAAAAAAAAAAAD8AAEAAAAAABNegcQllrEKIZrrUHoiY2UK9vsct9xe5wCu9I0T0A5h6NZRaGM0VzA=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v2 = require(v1.Std.TableUtils)
local v3 = require(v1.Std.Enumer)
return v2.requireValidIndexAndFreeze({
	["TIME_OF_DAY_ATTR_NAME"] = "TimeOfDay",
	["TIME_OF_DAY_ENUM"] = v3({ "Day", "Night" }),
	["PRECIPITATION_ATTR_NAME"] = "Precipitation",
	["PRECIPITATION_ENUM"] = v3({ "Rain", "None" })
})
