-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNLBVteJXddAARnc3ViD2VuY29kZVNwYXduTmFtZQRuYW1lGlNQQVdOX1RJTUVfSE9MREVSX09CSl9OQU1FDkZpbmRGaXJzdENoaWxkDEdldEF0dHJpYnV0ZRZnZXRQbGF5ZXJMYXN0U3Bhd25lZEF0CEluc3RhbmNlA25ldwlCb29sVmFsdWUETmFtZQZQYXJlbnQJd29ya3NwYWNlEEdldFNlcnZlclRpbWVOb3cMU2V0QXR0cmlidXRlFXJlY29yZFBsYXllclNwYXduZWRBdAlnZXRUZWFtSWQPZXhjbHVzaXZlVGVhbUlkDGlzVGVhbUlkU2FtZQ1leGNsdXNpdmVCb3NzE2RvZXNQbGF5ZXJPd25DYWNoZWQMRW51bUdhbWVwYXNzBEJPU1MQZ2FtZXBhc3NSZXF1aXJlZA1leGNsdXNpdmVTV0FUBFNXQVQMZXhjbHVzaXZlVklQA1ZJUBFMYXN0RGVhdGhQb3NpdGlvbgZ0eXBlb2YHVmVjdG9yMwhwb3NpdGlvbglNYWduaXR1ZGUIZGlzdGFuY2UTU1BBV05fQ09PTERPV05fVElNRQh0aW1lTGVmdBBjYW5QbGF5ZXJTcGF3bkF0CEVudW1UZWFtBlBvbGljZQhQcmlzb25lcghDcmltaW5hbCNTUEFXTl9FWENMVVNJVkVfVEVBTV9OQU1FX0FUVFJfTkFNRQVlcnJvcjpCbGFuayBhdHRyaWJ1dGUgU1BBV05fRVhDTFVTSVZFX1RFQU1fTkFNRV9BVFRSX05BTUUgZm9yICVzC0dldEZ1bGxOYW1lBmZvcm1hdAx1c2VQYXJhY2h1dGUIUG9zaXRpb24eU1BBV05fRVhDTFVTSVZFX0JPU1NfQVRUUl9OQU1FHlNQQVdOX0VYQ0xVU0lWRV9TV0FUX0FUVFJfTkFNRR1TUEFXTl9FWENMVVNJVkVfVklQX0FUVFJfTkFNRR1TUEFXTl9VU0VfUEFSQUNIVVRFX0FUVFJfTkFNRRlnZXRTcGF3bkRhdGFGcm9tU3Bhd25QYXJ0DlNQQVdOX1RBR19OQU1FCUdldFRhZ2dlZBRnZXRTcGF3blBhcnRGcm9tTmFtZQV0YWJsZQZpbnNlcnQPZ2V0QWxsU3Bhd25EYXRhBGdhbWURQ29sbGVjdGlvblNlcnZpY2UKR2V0U2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQdyZXF1aXJlBEdhbWULUGxheWVyVXRpbHMIUmVzb3VyY2UIU2V0dGluZ3MOU3Bhd25TZWxlY3Rpb24UU3Bhd25TZWxlY3Rpb25Db25zdHMIR2FtZXBhc3MOR2FtZXBhc3NTeXN0ZW0NR2FtZXBhc3NVdGlscwAJBQEAAAAABm8DAABvBAEAvAEAzAIAAACfAQQAggEAAAMDAQMCAwMACwQBGAAAAAAAAAwAAAAACAIBAAAAF00DAVoAAAAAbwYBAG8HAgC8BAPMAwAAAJ8EBAJSAgQA+wYAAE0FBrAEAAAAvAMAAwUAAACfAwMCKwMCAIwEAACCBAIAUgcCALwFAxIHAAAAnwUDApAEBQaCBAIACAMFAwEDAgMDAwYDBwIAAAAAAAAAAAMIAA4JARgDAP0AAAAAAAQAAAAAAAEBAAIAAAAAAAwAAAAACQIBAAAAJ00DAVoAAAAAbwYBAG8HAgC8BAPMAwAAAJ8EBAJSAgQA+wYAAE0FBrAEAAAAvAMAAwUAAACfAwMCKwMMAKQECAAAHGCAbwUJAJ8EAgJSAwQA+wUAAE0EBbAEAAAAMAQDugoAAAAwAAMkCwAAAKQEDQAAAMBAvAQEtw4AAACfBAICUgcCAFIIBAC8BQMuDwAAAJ8FBAGpBQEAggUCABADBQMBAwIDAwMGAwcDCgMLBAAcYIADDAMNAw4DDwQAAMBAAxADEQAWEgEYCwD1AAAAAAAMAAAAAAABAQAAAAABAAAAAAEAAgAAAAABAAAAAAEADAAAAAALAgUAAAcAAAEIB2oBjwH7AwAATQIDZAAAAABSAwAAnwICAk0DAWIBAAAADgMKAPsEAQBNAwTAAgAAAFIEAgBNBQFiAQAAAJ8DAwIrAwIAqQMAAIIDAgBNAwEvAwAAAA4DFQD7BAIATQMEvQQAAABSBAAA+wcDAE0GB40FAAAATQUGFQYAAACfAwMCKwMKAKkDAADiBAgA+wcDAE0GB40FAAAATQUGFQYAAAAwBQRXBwAAAIIDAwBNAwFjCQAAAA4DFQD7BAIATQMEvQQAAABSBAAA+wcDAE0GB40FAAAATQUGMgoAAACfAwMCKwMKAKkDAADiBAgA+wcDAE0GB40FAAAATQUGMgoAAAAwBQRXBwAAAIIDAwBNAwGjCwAAAA4DFQD7BAIATQMEvQQAAABSBAAA+wcDAE0GB40FAAAATQUGyQwAAACfAwMCKwMKAKkDAADiBAgA+wcDAE0GB40FAAAATQUGyQwAAAAwBQRXBwAAAIIDAwBvBQ0AvAMAEg4AAACfAwMCDgMWALssAwNSBQMApAQQAAAA8ECfBAIC8AQQABEAAIBNBwHbEgAAACYGAwdvBxMACQUGB00EBaoUAAAAjAWEA2AEBgAFAAAAqQUAAOIGFgAwBAZ1FQAAAIIFAwCkBBgAAABwQbwEBLcZAAAAnwQCAvsHBABNBgcSGgAAAPsJAQBNCAnpGwAAAFIJAABSCgEAnwgDAiYHBAgmBQYHjAYAAGAGBgAFAAAAqQYAAOIHHQAwBQfuHAAAAIIGAwCpBgEAggYCAB4DEwMUAxUDFgMXAxgDGQMaBQEHAxsDHAMdAx4DHwMIAyAEAADwQAMhAyIHAACAPwAAAAAAAIA/AAAAAAMjAyQFARUDDwQAAHBBAxADJQMJAyYFARwAIicBGAAAAAAAAQAAAQAAAAAAAAABAAMAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAMAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAMAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAMAAAABAAAAAAAAAAEAAAAAAAABAAABAAAAAAMAAAAAAQAAAQAAAAAAAAABAAABAAAAAAIAIwAAAAAFAgEAAAAw+wQAAE0DBEwAAAAATQIDsgEAAACaAQoAAgAAAPsEAABNAwRMAAAAAE0CA7IBAAAA8QADAAIAAACpAgAAggICAPsEAABNAwRMAAAAAE0CA54CAAAA8QEIAAIAAAD7BAAATQMETAAAAABNAgN1AwAAAJoBEQACAAAA+wQAAE0DBEwAAAAATQIDngIAAADxAAoAAgAAAPsEAABNAwRMAAAAAE0CA3UDAAAA8QADAAIAAACpAgAAggICAKkCAQCCAgIABAMoAykDKgMrAEcVARgAAAAAAAAAAQAAAAAAAAEAAwAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAEAAwBIAAAAAAkBAgAABwAAAQMEDwJV+wQAAE0DBKwAAAAAvAEAEgEAAACfAQMCxgIAAA4BEQArAQwApAMDAAAAIEBvBAQAvAYAsgUAAACfBgIAvAQEjQYAAACfBAAAnwMAAakDAACCAwIA+wQBAE0DBEwHAAAAhwIDAeIDDwBNBAC6EAAAADAEA1oIAAAATQQAOxEAAAAwBAPbCQAAADACA2IKAAAA+wgAAE0HCIsSAAAAvAUAEgEAAACfBQMCKgUCAAEAAACpBAABqQQBADAEAy8LAAAA+wgAAE0HCOoTAAAAvAUAEgEAAACfBQMCKgUCAAEAAACpBAABqQQBADAEA2MMAAAA+wgAAE0HCFYUAAAAvAUAEgEAAACfBQMCKgUCAAEAAACpBAABqQQBADAEA6MNAAAA+wgAAE0HCKAVAAAAvAUAEgEAAACfBQMCKgUCAAEAAACpBAABqQQBADAEAzYOAAAAggMCABYDLAMIAy0EAAAgQAMuAy8DMAMoAwUDIgMUAxYDGwMdAzEFBwgJCgsMDQ4DDQMyAzMDNAM1AzYAVDcBGAAAAAAAAAEBAQEAAAAAAAAAAAABAAIAAAACAQAAAAEAAAABAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAABVAAAAAAcBAgAAABD7AQAA+wQBAE0DBFQAAAAAvAEBBQEAAACfAQMEZAEFAE0GBboCAAAAmgYCAAAAAACCBQIAbgH6/wIAAACCAAEAAwM4AzkDDQBoOgEYAAAAAAAAAAABAAAAAf4ABWkAAAAACgADAAAAF/8AAAAAAAAA+wEAAPsEAQBNAwRUAAAAALwBAQUBAAAAnwEDBGQBCgBSBwAA+wkCAE0ICQwCAAAAUgkFAJ8IAgBMNAACpAYFAAAQMICfBgABbgH1/wIAAACCAAIABgM4AzkDNwM7AzwEABAwgABwPQEYAAABAAAAAAAAAAEAAAAAAAAAAAD/AANxAAAAAAoAAAECAFyjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIGAAAAUEBNBAG9BwAAAE0DBKYIAAAAnwICAqQDBgAAAFBATQUBYgkAAABNBAXKCgAAAJ8DAgKkBAYAAABQQE0GAZQLAAAATQUGcQwAAACfBAICpAUGAAAAUEBNCAG9BwAAAE0HCL0NAAAATQYHjg4AAACfBQICpAYGAAAAUEBNCQG9BwAAAE0ICb0NAAAATQcIPg8AAACfBgIC/wcEAAAAAADACBAAwAkRABIABAAwCQfpEgAAAMAJEwASAAQAMAkH1BQAAADACRUAEgACABIABwASAAUAEgAGABIABAAwCQeLFgAAAMAJFwASAAMAMAkHwBgAAADACRkAEgAEABIAAwAwCQcMGgAAAMAJGwASAAAAEgAEADAJBxocAAAAwAkdABIAAAASAAQAEgAHADAJB0EeAAAAggcCAB8DPgQAAABAAz8DQANBA0IEAABQQANDA0QDRQNGA0cDSANJA0oDSwYABgEDCQYCAxIGAwMnBgQDFQYFAzcGBgM6BgcDPQgAAQIDBAUGBwEAARgAAQAAAAAAAQAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAgABAwAAAAgAAAAMAAAAAAAAACUAAAANAAAAABQAAAAACAAAAAAABwEAAAAACLgiYNIwInYDiuYKRgFn/zI0ykE7EeP/T6VTbQzvIUkJcOrdDg8tURU=

-- Decompiled by Krnl

local v_u_1 = game:GetService("CollectionService")
local v2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v2.Game.PlayerUtils)
local v_u_4 = require(v2.Resource.Settings)
local v_u_5 = require(v2.SpawnSelection.SpawnSelectionConsts)
local v_u_6 = require(v2.Game.Gamepass.GamepassSystem)
local v_u_7 = require(v2.Game.Gamepass.GamepassUtils)
local v_u_33 = {
	["getPlayerLastSpawnedAt"] = function(p8, p9)
		-- upvalues: (copy) v_u_5
		local v10 = p9.name:gsub("[^%w]", "")
		local v11 = p8:FindFirstChild(v_u_5.SPAWN_TIME_HOLDER_OBJ_NAME)
		return v11 and (v11:GetAttribute(v10) or 0) or 0
	end,
	["recordPlayerSpawnedAt"] = function(p12, p13)
		-- upvalues: (copy) v_u_5
		local v14 = p13.name:gsub("[^%w]", "")
		local v15 = p12:FindFirstChild(v_u_5.SPAWN_TIME_HOLDER_OBJ_NAME)
		if not v15 then
			v15 = Instance.new("BoolValue")
			v15.Name = v_u_5.SPAWN_TIME_HOLDER_OBJ_NAME
			v15.Parent = p12
		end
		v15:SetAttribute(v14, (workspace:GetServerTimeNow()))
		return true
	end,
	["canPlayerSpawnAt"] = function(p16, p17)
		-- upvalues: (copy) v_u_3, (copy) v_u_33, (copy) v_u_6, (copy) v_u_7, (copy) v_u_5
		local v18 = v_u_3.getTeamId(p16)
		if p17.exclusiveTeamId and not v_u_33.isTeamIdSame(v18, p17.exclusiveTeamId) then
			return false
		elseif p17.exclusiveBoss and not v_u_6.doesPlayerOwnCached(p16, v_u_7.EnumGamepass.BOSS) then
			return false, {
				["gamepassRequired"] = v_u_7.EnumGamepass.BOSS
			}
		elseif p17.exclusiveSWAT and not v_u_6.doesPlayerOwnCached(p16, v_u_7.EnumGamepass.SWAT) then
			return false, {
				["gamepassRequired"] = v_u_7.EnumGamepass.SWAT
			}
		elseif p17.exclusiveVIP and not v_u_6.doesPlayerOwnCached(p16, v_u_7.EnumGamepass.VIP) then
			return false, {
				["gamepassRequired"] = v_u_7.EnumGamepass.VIP
			}
		else
			local v19 = p16:GetAttribute("LastDeathPosition")
			if v19 and typeof(v19) == "Vector3" then
				local v20 = ((v19 - p17.position) * Vector3.new(1, 0, 1)).Magnitude
				if v20 < 900 then
					return false, {
						["distance"] = v20
					}
				end
			end
			local v21 = workspace:GetServerTimeNow()
			local v22 = v_u_5.SPAWN_COOLDOWN_TIME - (v21 - v_u_33.getPlayerLastSpawnedAt(p16, p17))
			if v22 > 0 then
				return false, {
					["timeLeft"] = v22
				}
			else
				return true
			end
		end
	end,
	["isTeamIdSame"] = function(p23, p24)
		-- upvalues: (copy) v_u_4
		if p24 == v_u_4.EnumTeam.Police and p23 ~= v_u_4.EnumTeam.Police then
			return false
		else
			return p24 ~= v_u_4.EnumTeam.Prisoner and p24 ~= v_u_4.EnumTeam.Criminal or (p23 == v_u_4.EnumTeam.Prisoner or p23 == v_u_4.EnumTeam.Criminal)
		end
	end,
	["getSpawnDataFromSpawnPart"] = function(p25)
		-- upvalues: (copy) v_u_5, (copy) v_u_4
		local v26 = p25:GetAttribute(v_u_5.SPAWN_EXCLUSIVE_TEAM_NAME_ATTR_NAME)
		local v27
		if v26 then
			if not v26 then
				error(("Blank attribute SPAWN_EXCLUSIVE_TEAM_NAME_ATTR_NAME for %s"):format(p25:GetFullName()))
				return false
			end
			v27 = v_u_4.EnumTeam[v26]
		else
			v27 = nil
		end
		return {
			["name"] = p25.Name,
			["position"] = p25.Position,
			["exclusiveTeamId"] = v27,
			["exclusiveBoss"] = p25:GetAttribute(v_u_5.SPAWN_EXCLUSIVE_BOSS_ATTR_NAME) == true,
			["exclusiveSWAT"] = p25:GetAttribute(v_u_5.SPAWN_EXCLUSIVE_SWAT_ATTR_NAME) == true,
			["exclusiveVIP"] = p25:GetAttribute(v_u_5.SPAWN_EXCLUSIVE_VIP_ATTR_NAME) == true,
			["useParachute"] = p25:GetAttribute(v_u_5.SPAWN_USE_PARACHUTE_ATTR_NAME) == true
		}
	end,
	["getSpawnPartFromName"] = function(p28)
		-- upvalues: (copy) v_u_1, (copy) v_u_5
		for _, v29 in v_u_1:GetTagged(v_u_5.SPAWN_TAG_NAME) do
			if v29.Name == p28 then
				return v29
			end
		end
	end,
	["getAllSpawnData"] = function()
		-- upvalues: (copy) v_u_1, (copy) v_u_5, (copy) v_u_33
		local v30 = {}
		for _, v31 in v_u_1:GetTagged(v_u_5.SPAWN_TAG_NAME) do
			local v32 = v_u_33.getSpawnDataFromSpawnPart
			table.insert(v30, v32(v31))
		end
		return v30
	end
}
return v_u_33
