-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMYBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplCFRBR19OQU1FFUNSRUFUT1JfSURfVkFMVUVfTkFNRRFUSFJPV05fVkFMVUVfTkFNRRJUSFJPV05fUkVNT1RFX05BTUUTRVhQTE9ERV9SRU1PVEVfTkFNRQxNQVhfTElGRVRJTUUMQkxBU1RfUkFESVVTC0ZYX0RVUkFUSU9ODEZYX0JMVVJfU0laRQhGWF9DT0xPUgxTbW9rZUdyZW5hZGUJQ3JlYXRvcklkBlRocm93bgxUaHJvd25SZW1vdGUNRXhwbG9kZVJlbW90ZQZDb2xvcjMHZnJvbVJHQgABCAAAAQIANqMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DAKEGAAAATQIDGAcAAACfAQICTQIBAAgAAADiAxMAbwQUADAEA7QJAAAAbwQVADAEAzwKAAAAbwQWADAEA/ELAAAAbwQXADAEA1oMAAAAbwQYADAEA+QNAAAAjAR4ADAEA8EOAAAAjARAADAEA7kPAAAAjAQPADAEA8kQAAAAjARkADAEA1QRAAAApAQbAABokIGMBfoAjAb/AIwHZACfBAQCMAQDfRIAAACfAgIAggIAABwDAQQAAABAAwIDAwMEBAAAQEADBQMGAwcDCAMJAwoDCwMMAw0DDgMPAxADEQUKCQoLDA0ODxAREgMSAxMDFAMVAxYDFwMYBABokIEAAQABGAABAAAAAAABAAAAAAAAAQAAAQAAAQAAAQAAAQAAAQAAAgAAAQAAAgAAAQAAAQAAAAAAAAD0AAEAAAAAAInVrbDol6ZluxHHJG/lPzxcalGBCCjOKOiqMTwdCScXVXn/aWjctgA=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Std.TableUtils).requireValidIndexAndFreeze({
	["TAG_NAME"] = "SmokeGrenade",
	["CREATOR_ID_VALUE_NAME"] = "CreatorId",
	["THROWN_VALUE_NAME"] = "Thrown",
	["THROWN_REMOTE_NAME"] = "ThrownRemote",
	["EXPLODE_REMOTE_NAME"] = "ExplodeRemote",
	["MAX_LIFETIME"] = 120,
	["BLAST_RADIUS"] = 64,
	["FX_DURATION"] = 15,
	["FX_BLUR_SIZE"] = 100,
	["FX_COLOR"] = Color3.fromRGB(250, 255, 100)
})
