-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNcDFByZWxvYWRBc3luYwRuZXh0B0Rlc3Ryb3kISW5zdGFuY2UDbmV3BVNvdW5kDXJieGFzc2V0aWQ6Ly8HU291bmRJZAV0YWJsZQZpbnNlcnQFc3Bhd24HUHJlbG9hZAtQcmVsb2FkSGFzaAhJc0xvYWRlZAZMb2FkZWQEV2FpdApUaW1lTGVuZ3RoBGdhbWUGRGVicmlzCkdldFNlcnZpY2UHQWRkSXRlbRpTb3VyY2VPYmplY3QgY2Fubm90IGJlIG5pbAZhc3NlcnQGdHlwZW9mIFNvdXJjZU9iamVjdCBtdXN0IGJlIGFuIEluc3RhbmNlCXdvcmtzcGFjZQ5Jc0Rlc2NlbmRhbnRPZghCYXNlUGFydANJc0EEd2Fybi5Tb3VyY2VPYmplY3Qgc2hvdWxkIGJlIGEgQmFzZVBhcnQsIGJ1dCB3YXMgYTogCUNsYXNzTmFtZQggKE5hbWU6IAtHZXRGdWxsTmFtZQEpBEVudW0LUm9sbE9mZk1vZGUOSW52ZXJzZVRhcGVyZWQSUm9sbE9mZk1heERpc3RhbmNlBHR5cGUGbnVtYmVyCHRvc3RyaW5nBE5hbWUGVm9sdW1lBVBpdGNoDVBsYXliYWNrU3BlZWQMVGltZVBvc2l0aW9uC0VtaXR0ZXJTaXplC01heERpc3RhbmNlElJvbGxPZmZNaW5EaXN0YW5jZQZMb29wZWQPTWF4UGxheWJhY2tUaW1lCURvTm90UGxheQVHcm91cApTb3VuZEdyb3VwCUdyb3VwTmFtZQxTb3VuZFNlcnZpY2UORmluZEZpcnN0Q2hpbGQOU291bmRHcm91cE5hbWUGUGFyZW50DllpZWxkRm9yTG9hZGVkBFBsYXkEdGFzawtPYmplY3RMb2NhbARQYXJ0CEFuY2hvcmVkCkNhbkNvbGxpZGUEU2l6ZQhQb3NpdGlvbgxUcmFuc3BhcmVuY3kJU291bmRQYXJ0EldvcmxkUG9zaXRpb25Mb2NhbAR3YWl0B0ZhZGVPdXQORWFzZV9Jbk91dFF1YWQKRGlzY29ubmVjdAR0aWNrCUhlYXJ0YmVhdAdDb25uZWN0BkZhZGVUbwJvcwVjbG9jaxJObyBQYXJlbnQgdG8gc291bmQIR2l2ZVRhc2sNcHJvbWlzZUZhZGVUbxFSZXBsaWNhdGVkU3RvcmFnZQdyZXF1aXJlA1N0ZAdQcm9taXNlBE1haWQKUnVuU2VydmljZQ9Db250ZW50UHJvdmlkZXIAEAcAAgAAABD7AAAA+wIBALwAAE8AAAAAnwADAaQAAgAAABBA+wEBAMYCAAAXAAMAvAUEUAMAAACfBQIBbgD8/wIAAACCAAEABAMBAwIEAAAQQAMDABcAARgAAAAAAAEAAAAAAQAA/wADGAAAAAALAQEAAAAh/wEAAAAAAACkAgEAAAAAQFIDAADGBAAAFwIQAKQHBAAADCCAbwgFAJ8HAgJvCQYAUgoGAHMICQowCAd8BwAAAJ40AQUHAAAAUgkBAFIKBwCkCAoAACSAgJ8IAwFuAu//AgAAAKQCDAAAALBA2QMAABICAAASAAEAnwICAakCAQCCAgIADQMCBAAAAEADBAMFBAAMIIADBgMHAwgDCQMKBAAkgIADCwQAALBAAQALDAEYAAABAAAAAAEAAAABAAAAAAEAAAAAAAD9AAoAAAAAAAYADAAAAAAKAQEAAAAU/wEAAAAAAACkAgEAAAAAQFIDAADGBAAAFwIHAJ40AQUGAAAAUggBAFIJBgCkBwQAAAwggJ8HAwFuAvj/AgAAAPsCAABSAwEAnwICAoICAgAFAwIEAAAAQAMJAwoEAAwggAAfDQEYAAABAAAAAAEAAAAAAAD/AAMAAAAgAAAAAAUAAgAAAB37AAAARwAPAAAAAID7AgEATQECVQAAAAArAQYA+wIBAE0BAgQBAAAAvAEB9wIAAACfAQIB+wIBAE0BAtYEAAAAlQABA6QBBgAAAFBAbwMHALwBARYIAAAAnwEDAvsDAQBSBAAAvAEBeAkAAACfAQQBggABAAoDDgMPAxACAAAAAAAA8D8DEQMSBAAAUEADEwMUAxUAigEAARgAAQABAAAAAQAAAAAAAgAAAAIAAAAAAAAAAAAAAYsAAAAADAMAAAAIBQAABQMHAoTkAYEBAAUAAAAAUgQAAG8FAACkAwIAAAAQQJ8DAwG7LAADUgYAAKQFBAAAADBAnwUCAvAFAgAFAAAAqQQAAakEAQCBAQQEBgAAAG8FBgCkAwIAAAAQQJ8DAwGkBQgAAABwQLwDAK0JAAAAnwMDAg4DEgBvBQoAvAMA/gsAAACfAwMCKwMNAKQDDQAAAMBAbwUOAE0GANsPAAAAbwcQALwKALIRAAAAnwoCAlIICgBvCRIAcwQFCZ8DAgGkAxQAAExQgG8EFQCfAwICpAQZABhcYMEwBANEFwAAAIwEAAIwBAMqGgAAALsoAQNSBQEApAQcAAAAsEGfBAIC8AQHAB0AAIBvBR4AUgYBAHMEBQYwBAN8HwAAAGUAAgAwAQN8HwAAALs/AQNSBQEApAQhAAAAAEKfBAICMAQDuiIAAADGBAAAqQUAAA4CdQBNBgJLIwAAAA4GBABNBgJLIwAAADAGA0sjAAAATQYCACQAAAAOBgQATQYCACQAAAAwBgMoJQAAAE0GAsYmAAAADgYEAE0GAsYmAAAAMAYDxiYAAABNBgKDJwAAAA4GBABNBgKDJwAAADAGA4MnAAAATQYCmSgAAAAOBgQATQYCmSgAAAAwBgOZKAAAAE0GAkQXAAAADgYEAE0GAkQXAAAAMAYDRBcAAABNBgJvKQAAAA4GBABNBgJvKQAAADAGA28pAAAATQYCKhoAAAAOBgQATQYCKhoAAAAwBgMqGgAAAE0GArUqAAAADgYDAKkGAQAwBgO1KgAAAE0GAjsrAAAADgYCAE0EAjsrAAAATQYCiCwAAAAOBgEAqQUBAE0GAsQtAAAADgYEAE0GAsQtAAAAMAYD4S4AAABNBgLhLgAAAA4GBABNBgLhLgAAADAGA+EuAAAATQYC1i8AAAAOBg0ApAYxAAAAAENvCDIAvAYGFjMAAACfBgMCTQgC1i8AAAC8BgYDNAAAAJ8GAwIwBgPhLgAAAE0GAg01AAAADgYNAKQGMQAAAABDbwgyALwGBhYzAAAAnwYDAk0IAg01AAAAvAYGAzQAAACfBgMCMAYD4S4AAAAwAAMkNgAAAA4CCwBNBgJGNwAAAA4GCABNBgNVOAAAACsGBQBNBgMEOQAAALwGBvc6AAAAnwYCASsFDAC8BgPuOwAAAJ8GAgFNBgO1KgAAACsGBgCkBj4AAPTAg9kHAAASAQT/EgADAJ8GAgHBBAAAggMCAD8DFgMXBAAAEEADGAQAADBAAwQDGQMaBAAAcEADGwMcAx0DHgQAAMBAAx8DIAMhAyIDIwMFBABMUIADBgMkAyUDJgQYXGDBAycDKAQAALBBAykDBwMIAyoEAAAAQgMrAywDLQMuAy8DMAMxAzIDMwM0AzUDNgM3AzgDEgQAAABDAzkDFAM6AzsDPAM9Aw4DDwMQAz4DPwMLBAD0wIMBAzhAARgAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAEBAAEBAAAAAQD7CAAAAAIAAAABAAABAAAAAAAAAQAAAAAAAgACAAAAAAAAAQEBAQAAAQAAAAIAAAEAAAACAAABAAAAAgAAAQAAAAIAAAEAAAACAAABAAAAAwAAAQAAAAMAAAEAAAACAAABAAACAAABAAIAAAECAAABAAAAAgAAAQAAAAIAAAEAAAAAAAAAAAAAAAACAAABAAAAAAAAAAAAAAAAAwABAAAAAQAAAQAAAAADAQAAAQAAAQAAAAAADAA5AAAAAAgDAQAACAUAAAUDCAKEH6QDAgAABACAbwQDAJ8DAgKpBAEAMAQDRQQAAACpBAAAMAQD0wUAAABvBAYAMAQDLwcAAAAwAAM7CAAAAIwEAQAwBAPZCQAAAG8ECgAwBAO6CwAAAKQEDQAAAMBAMAQDJA4AAAD7BAAAUgUDAFIGAQBSBwIAnwQEAoIEAgAPAwQDBQQABACAA0EDQgNDB83MzD3NzMw9zczMPQAAAAADRANFA0YDRwMrAxoEAADAQAM8AJgBSAEYAAAAAAEAAAEAAAEAAAEAAQAAAQAAAQAAAAEAAAAAAJkAAAAABgACAAAAFfsBAABNAAFLAAAAAIwDAQCMAQAA+wQBANgCAQSoAQgA+wQAAAkFAAMwBQRLAAAAAKQEAwAAACBAnwQBAYsB+P/7AQAAjAIAADACAUsAAAAAggABAAQDLAK4HoXrUbievwNJBAAAIEAApAEAARgAAAADAAAAAAEAAAABAAD+BAAAAAGlAAAAAAQCAAAAAAekAgEAAAAAQNkDAAASAAAAEgABAJ8CAgGCAAEAAgMLBAAAAEABBqMBSgEYAAAAAAAACqQAAAAABgEAAAAADW8CAABgAAUAAgAAAIwDAgAJAgMACQECACsBBQCMBAIAeAUAAgkDBAUJAgMA9QEBAoIBAgADAgAAAAAAAOA/AgAAAAAAAPC/AgAAAAAAAABAAK8BSwEYAAAAAAAAAAAAAAAAALAAAAAABwAHAAAAN/sBAABNAAEkAAAAAEcABgAAAACA+wABALwAABoBAAAAnwACAYIAAQCkAAMAAAAgQJ8AAQL7AwIAJgIAA/sDAwDsAQIDjAIBAH0CBgABAAAAjAEBAPsCAQC8AgIaAQAAAJ8CAgFSAgEAbwMEAGACBQADAAAAjAQCAAkDBAIJAQMCKwEFAIwFAgB4BgIGCQQFBgkDBAL1AQUD+wIAAPsFBAD1BgcBCQQFBvsGBQAJBQYBQwMEBTADAksIAAAADQEGAAcAAID7AgYARwIDAAAAAAD7AgYAnwIBAYIAAQAJAzwDTANNBAAAIEACAAAAAAAA4D8CAAAAAAAA8L8CAAAAAAAAAEACAAAAAAAA8D8DLAC5AQABGAoAAAAAAQAAAAECAAABAAAAAQAAAQEAAAAC7AAAAAAAAAAAAAAAFQAAAAAAAAAAAQABAAABAAOwAAAAAAoEAQAAACa7AQADUgUAAKQEAQAAAABAnwQCAbsBAQNSBQEApAQBAAAAAECfBAIBuwECA1IFAgCkBAEAAAAAQJ8EAgFNBABLAgAAAKQFBAAAADBAnwUBAsYGAAD7CAAATQcI/QUAAADZCQAAEgAAABIBBv8SAAUAEgACABIABAASAAEAEgADALwHB8cGAAAAnwcDAlIGBwDBBgAAggYCAAcDFwQAAABAAywDTQQAADBAA04DTwEJsgFQARgAAAAAAAEAAAAAAQAAAAABAAEAAAEBAAAAAAAAAAAAAAAAAAATALMAAAAAAgABAAAAB/sAAAC8AABQAAAAAJ8AAgHGAAAA3gAAAIIAAQABAwMA1QEAARgAAAAAAQAB1gAAAAAIAAgAAAA2pAACAAAEAICfAAEC+wIAACYBAAL7AwEA7AIBA4wDAQB9AwIAAgAAAIwCAQBSAwIAbwQDAGADBQAEAAAAjAUCAAkEBQMJAgQDKwIFAIwGAgB4BwMFCQUGBwkEBQP1AgQE+wQCAE0DBCQGAAAAKwMIAPsDAwC8AwNQBwAAAJ8DAgH7AwQAbwQIAJ8DAgGCAAEA+wMCAPsGBQD1BwkCCQUGB/sHBgAJBgcCQwQFBjAEA0sKAAAADQIHAAkAAID7AwMAvAMDUAcAAACfAwIB+wMHAJ8DAQGCAAEACwNRA1IEAAQAgAIAAAAAAADgPwIAAAAAAADwvwIAAAAAAAAAQAM8AwMDUwIAAAAAAADwPwMsANwBAAEYLQAAAQABAAEAAAECzQAAAAAAAAAAAAAANAAAAAEAAAABAAABAgAAAAAAAAAAAQABAAAAAQACsAAAAAAKAwYAAAAi+wQAAE0DBO8AAAAAnwMBAlIEAgDZBQAAEgED/58EAgIOBAIAwQMAAIIAAQD7BQEATQQFSwEAAAD7CAIATQcI/QIAAADZCQEAEgIDABICBAASAgEAEgED/xIAAQASAAQAEgIFABIAAAC8BwfHAwAAAJ8HAwC8BQP9BAAAAJ8FAAHBAwAAggABAAUDBQMsA04DTwNUAgsM0wEAARgAAAAAAQAAAAAEAAIAAAEAAAAAAAAAAAAAAAAAAAAAABMA1AAAAAAGAwMAAAAeuwEAA1IEAACkAwEAAAAAQJ8DAgG7AQEDUgQBAKQDAQAAAABAnwMCAbsBAgNSBAIApAMBAAAAAECfAwIBpAMEAAAMIICfAwEC+wUAAE0EBe8FAAAA2QUAABICAQASAAAAEgICABIAAwASAAIAEgABAJ8EAgCCBAAABgMXBAAAAEADUQNSBAAMIIADBQENzgFVARgAAAAAAAEAAAAAAQAAAAABAAABAAAAAAAAAAAAAADPAAAAAA4AAAECAECjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CA3IHAAAAnwECAqQCBQAAAEBATQQAoQYAAABNAwR2CAAAAJ8CAgKkAwEAAAAAQG8FCQC8AwMWAwAAAJ8DAwKkBAEAAAAAQG8GCgC8BAQWAwAAAJ8EAwLABQsAEgAEAMAGDAASAAUAwAcNAMAIDgASAAcAwAkPAMAKEADACxEAEgADAMAMEgASAAEAEgACABIAAwDiDRoAMAcN0RMAAAAwCA1/FAAAADAFDUgVAAAAMAYNRhYAAAAwCQ2hFwAAADALDQcYAAAAMAwNdhkAAACCDQIAGwMSBAAAAEADVgMUA1cEAABAQANYA1kDWgNbA1wGAQYCBgQGBQYHBggGCgYOA0ADSAMMAw0DSgNQA1UFBxMUFRYXGBkIAQIEBQcICg4BAAEYAAEAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAQAAAAAABQAUABlgAAsMAwAcAAAAJAEAAQABAAEAAQABAAEAAAEAAAAAD40ZEHCO0Dllv9165PJ9XXXOS1z31A23+S5/k85AAe6hbEiDONk6Oc0=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.Promise)
local v_u_3 = require(v1.Std.Maid)
local v_u_4 = game:GetService("RunService")
local v_u_5 = game:GetService("ContentProvider")
local function v_u_11(p6)
	-- upvalues: (copy) v_u_5
	local v_u_7 = {}
	for _, v8 in next, p6 do
		local v9 = Instance.new("Sound")
		v9.SoundId = "rbxassetid://" .. v8
		table.insert(v_u_7, v9)
	end
	spawn(function()
		-- upvalues: (ref) v_u_5, (copy) v_u_7
		v_u_5:PreloadAsync(v_u_7)
		for _, v10 in next, v_u_7 do
			v10:Destroy()
		end
	end)
	return true
end
local function v_u_20(p12, p13, p14)
	assert(p12, "SourceObject cannot be nil")
	local v15 = typeof(p12) == "Instance"
	assert(v15, "SourceObject must be an Instance")
	if p12:IsDescendantOf(workspace) and not p12:IsA("BasePart") then
		warn("SourceObject should be a BasePart, but was a: " .. p12.ClassName .. " (Name: " .. p12:GetFullName() .. ")")
	end
	local v_u_16 = Instance.new("Sound")
	v_u_16.RollOffMode = Enum.RollOffMode.InverseTapered
	v_u_16.RollOffMaxDistance = 512
	if type(p13) == "number" then
		v_u_16.SoundId = "rbxassetid://" .. p13
	else
		v_u_16.SoundId = p13
	end
	v_u_16.Name = tostring(p13)
	local v_u_17 = nil
	local v18 = false
	if p14 then
		if p14.Volume then
			v_u_16.Volume = p14.Volume
		end
		if p14.Pitch then
			v_u_16.PlaybackSpeed = p14.Pitch
		end
		if p14.TimePosition then
			v_u_16.TimePosition = p14.TimePosition
		end
		if p14.EmitterSize then
			v_u_16.EmitterSize = p14.EmitterSize
		end
		if p14.MaxDistance then
			v_u_16.MaxDistance = p14.MaxDistance
		end
		if p14.RollOffMode then
			v_u_16.RollOffMode = p14.RollOffMode
		end
		if p14.RollOffMinDistance then
			v_u_16.RollOffMinDistance = p14.RollOffMinDistance
		end
		if p14.RollOffMaxDistance then
			v_u_16.RollOffMaxDistance = p14.RollOffMaxDistance
		end
		if p14.Looped then
			v_u_16.Looped = true
		end
		if p14.MaxPlaybackTime then
			v_u_17 = p14.MaxPlaybackTime
		end
		v18 = p14.DoNotPlay and true or v18
		if p14.Group then
			v_u_16.SoundGroup = p14.Group
		end
		if p14.SoundGroup then
			v_u_16.SoundGroup = p14.SoundGroup
		end
		if p14.GroupName then
			v_u_16.SoundGroup = game:GetService("SoundService"):FindFirstChild(p14.GroupName)
		end
		if p14.SoundGroupName then
			v_u_16.SoundGroup = game:GetService("SoundService"):FindFirstChild(p14.SoundGroupName)
		end
	end
	v_u_16.Parent = p12
	if p14 and (p14.YieldForLoaded and not v_u_16.IsLoaded) then
		v_u_16.Loaded:Wait()
	end
	if not v18 then
		v_u_16:Play()
		if not v_u_16.Looped then
			task.spawn(function()
				-- upvalues: (ref) v_u_17, (copy) v_u_16
				local v19 = v_u_17
				if v19 == nil then
					if not v_u_16.IsLoaded then
						v_u_16.Loaded:Wait()
					end
					v19 = v_u_16.TimeLength + 1
				end
				game:GetService("Debris"):AddItem(v_u_16, v19)
			end)
		end
	end
	return v_u_16
end
return {
	["ObjectLocal"] = v_u_20,
	["WorldPositionLocal"] = function(p21, p22, p23)
		-- upvalues: (copy) v_u_20
		local v24 = Instance.new("Part")
		v24.Anchored = true
		v24.CanCollide = false
		v24.Size = Vector3.new(0.1, 0.1, 0.1)
		v24.Position = p21
		v24.Transparency = 1
		v24.Name = "SoundPart"
		v24.Parent = workspace
		return v_u_20(v24, p22, p23)
	end,
	["Preload"] = v_u_11,
	["PreloadHash"] = function(p25)
		-- upvalues: (copy) v_u_11
		local v26 = {}
		for _, v27 in next, p25 do
			table.insert(v26, v27)
		end
		return v_u_11(v26)
	end,
	["FadeOut"] = function(p_u_28, p_u_29)
		spawn(function()
			-- upvalues: (copy) p_u_28, (copy) p_u_29
			local v30 = p_u_28.Volume
			for v31 = 1, 0, -0.03 / p_u_29 do
				p_u_28.Volume = v30 * v31
				wait()
			end
			p_u_28.Volume = 0
		end)
	end,
	["FadeTo"] = function(p_u_32, p_u_33, p_u_34, p_u_35)
		-- upvalues: (copy) v_u_4
		assert(p_u_32)
		assert(p_u_33)
		assert(p_u_34)
		local v_u_36 = p_u_32.Volume
		local v_u_37 = tick()
		local v_u_38 = nil
		v_u_38 = v_u_4.Heartbeat:Connect(function()
			-- upvalues: (copy) p_u_32, (ref) v_u_38, (copy) v_u_37, (copy) p_u_34, (copy) v_u_36, (copy) p_u_33, (copy) p_u_35
			if p_u_32.Parent == nil then
				v_u_38:Disconnect()
			else
				local v39 = (tick() - v_u_37) / p_u_34
				if v39 >= 1 then
					v_u_38:Disconnect()
					v39 = 1
				end
				local v40 = v39 < 0.5 and 2 * v39 * v39 or -1 - 2 * (v39 - 2) * v39
				p_u_32.Volume = v_u_36 * (1 - v40) + p_u_33 * v40
				if v40 == 1 and p_u_35 ~= nil then
					p_u_35()
				end
			end
		end)
		return v_u_38
	end,
	["promiseFadeTo"] = function(p_u_41, p_u_42, p_u_43)
		-- upvalues: (copy) v_u_2, (copy) v_u_3, (copy) v_u_4
		assert(p_u_41)
		assert(p_u_42)
		assert(p_u_43)
		local v_u_44 = os.clock()
		return v_u_2.new(function(p_u_45, p_u_46, p47)
			-- upvalues: (ref) v_u_3, (copy) p_u_41, (ref) v_u_4, (copy) v_u_44, (copy) p_u_43, (copy) p_u_42
			local v_u_48 = v_u_3.new()
			if not p47(function()
				-- upvalues: (ref) v_u_48
				v_u_48:Destroy()
				v_u_48 = nil
			end) then
				local v_u_49 = p_u_41.Volume
				v_u_48:GiveTask(v_u_4.Heartbeat:Connect(function()
					-- upvalues: (ref) v_u_44, (ref) p_u_43, (ref) p_u_41, (ref) v_u_48, (copy) p_u_46, (copy) v_u_49, (ref) p_u_42, (copy) p_u_45
					local v50 = (os.clock() - v_u_44) / p_u_43
					local v51 = v50 >= 1 and 1 or v50
					local v52 = v51 < 0.5 and 2 * v51 * v51 or -1 - 2 * (v51 - 2) * v51
					if p_u_41.Parent then
						p_u_41.Volume = v_u_49 * (1 - v52) + p_u_42 * v52
						if v52 == 1 then
							v_u_48:Destroy()
							p_u_45()
						end
					else
						v_u_48:Destroy()
						p_u_46("No Parent to sound")
					end
				end))
			end
		end)
	end
}
