-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMKBG1hdGgFY2xhbXAHY2xhbXAwMQVUb0hTVgZDb2xvcjMHZnJvbUhTVgpzYXR1cmF0ZUJ5CnNhdHVyYXRlVG8KYnJpZ2h0ZW5CeQpicmlnaHRlblRvAAYJAwAAAAAZjAUAAIwGAQA0LgAEBQYAAFIEAACkAwIAAAQAgJ8DBAKMBgAAjAcBADQuAQQGBwAAUgUBAKQEAgAABACAnwQEAowHAACMCAEANC4CBAcIAABSBgIApAUCAAAEAICfBQQCggMEAAMDAQMCBAAEAIAAAwMBGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAkCAQAAABe8AgDNAAAAAJ8CAgSMBgEAQwUGAQkDAwX7BgAATQUGCAEAAABSBgIAUgcDAFIIBACfBQQEUgIFAFIDBgBSBAcApAUEAAAMIIBSBgIAUgcDAFIIBACfBQQAggUAAAUDBAMDAwUDBgQADCCAAAYHARgAAAABAAABAAAAAAAAAAAAAQAAAAAAAAcAAAAACQIBAAAAFLwCAM0AAAAAnwICBPsGAABNBQYIAQAAAFIGAgBSBwEAUggEAJ8FBARSAgUAUgEGAFIEBwCkBQQAAAwggFIGAgBSBwEAUggEAJ8FBACCBQAABQMEAwMDBQMGBAAMIIAADAgBGAAAAAEAAAAAAAAAAAABAAAAAAAADQAAAAAJAgEAAAAXvAIAzQAAAACfAgIEjAYBAEMFBgEJBAQF+wYAAE0FBggBAAAAUgYCAFIHAwBSCAQAnwUEBFICBQBSAwYAUgQHAKQFBAAADCCAUgYCAFIHAwBSCAQAnwUEAIIFAAAFAwQDAwMFAwYEAAwggAARCQEYAAAAAQAAAQAAAAAAAAAAAAEAAAAAAAASAAAAAAkCAQAAABS8AgDNAAAAAJ8CAgT7BgAATQUGCAEAAABSBgIAUgcDAFIIAQCfBQQEUgIFAFIDBgBSAQcApAUEAAAMIIBSBgIAUgcDAFIIAQCfBQQAggUAAAUDBAMDAwUDBgQADCCAABcKARgAAAABAAAAAAAAAAAAAQAAAAAAABgAAAAAAgAAAQIAF6MAAAD/AAQAAAAAAMABAAAwAQAIAQAAAMABAgASAAAAMAEA3gMAAADAAQQAEgAAADABABMFAAAAwAEGABIAAAAwAQCcBwAAAMABCAASAAAAMAEAsAkAAACCAAIACgYAAwMGAQMHBgIDCAYDAwkGBAMKBQABAgMEAQABGAABAAEAAAMAAAAGAAAABQAAAAYAAAAFAQAAAAAFh0YM+B/BfT+1gmZs7GIMMezWyckcA2d9IGAZ2QZ3JxEEacxOkogLLQ==

-- Decompiled by Krnl

local v_u_36 = {
	["clamp01"] = function(p1, p2, p3)
		return math.clamp(p1, 0, 1), math.clamp(p2, 0, 1), math.clamp(p3, 0, 1)
	end,
	["saturateBy"] = function(p4, p5)
		-- upvalues: (copy) v_u_36
		local v6, v7, v8 = p4:ToHSV()
		local v9 = v7 * (1 + p5)
		local v10, v11, v12 = v_u_36.clamp01(v6, v9, v8)
		return Color3.fromHSV(v10, v11, v12)
	end,
	["saturateTo"] = function(p13, p14)
		-- upvalues: (copy) v_u_36
		local v15, _, v16 = p13:ToHSV()
		local v17, v18, v19 = v_u_36.clamp01(v15, p14, v16)
		return Color3.fromHSV(v17, v18, v19)
	end,
	["brightenBy"] = function(p20, p21)
		-- upvalues: (copy) v_u_36
		local v22, v23, v24 = p20:ToHSV()
		local v25 = v24 * (1 + p21)
		local v26, v27, v28 = v_u_36.clamp01(v22, v23, v25)
		return Color3.fromHSV(v26, v27, v28)
	end,
	["brightenTo"] = function(p29, p30)
		-- upvalues: (copy) v_u_36
		local v31, v32, _ = p29:ToHSV()
		local v33, v34, v35 = v_u_36.clamp01(v31, v32, p30)
		return Color3.fromHSV(v33, v34, v35)
	end
}
return v_u_36
