-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMJAWEBZQFpAW8BdQNzdWIFbG93ZXICYW4IZ2V0QU9yQW4AAggBAAAAAB7iAQUAqQIBADACAYAAAAAAqQIBADACAYQBAAAAqQIBADACAYgCAAAAqQIBADACAY4DAAAAqQIBADACAZQEAAAAjAYBAIwHAQC8BADwBgAAAJ8EBAK8BATvBwAAAJ8EAgKHAwEEDgMCAG8CCACCAgIAbwIAAIICAgAJAwEDAgMDAwQDBQUFAAECAwQDBgMHAwgABQkBGAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAYAAAAAAgAAAQIAB6MAAAD/AAEAAAAAAMABAAAwAQA/AQAAAIIAAgACBgADCQEAAQABGAABAAMAAAUBAAAAAAFD1er7JMe63HERgG/aIUBh6yKW4XFFv4MyGi7rygc3mGMRfbtXb/IY

-- Decompiled by Krnl

return {
	["getAOrAn"] = function(p1)
		return ({
			["a"] = true,
			["e"] = true,
			["i"] = true,
			["o"] = true,
			["u"] = true
		})[p1:sub(1, 1):lower()] and "an" or "a"
	end
}
