-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMqBl90YXNrcwxzZXRtZXRhdGFibGUDbmV3BnR5cGVvZg9SQlhTY3JpcHRTaWduYWwFZXJyb3JDVGFzayBjYW5ub3QgYmUgYSBSQlhTY3JpcHRTaWduYWwsIGRpZCB5b3UgbWVhbiBSQlhTY3JpcHRDb25uZWN0aW9uPwR0eXBlBXRhYmxlB0Rlc3Ryb3k0W01haWQuR2l2ZVRhc2tdIC0gR2F2ZSB0YWJsZSB0YXNrIHdpdGhvdXQgLkRlc3Ryb3kKCgx2YWxpZGF0ZVRhc2sIZnVuY3Rpb24TUkJYU2NyaXB0Q29ubmVjdGlvbgpEaXNjb25uZWN0BnRocmVhZAR0YXNrBmNhbmNlbAR3YXJuMFtNYWlkLkRvQ2xlYW5pbmddIC0gVW5hYmxlIHRvIGNsZWFuIHRhc2sgb2YgdHlwZQdfZG9UYXNrCUNsYXNzTmFtZQRNYWlkBmlzTWFpZAdfX2luZGV4ECclcycgaXMgcmVzZXJ2ZWQIdG9zdHJpbmcGZm9ybWF0Cl9fbmV3aW5kZXgbVGFzayBjYW5ub3QgYmUgZmFsc2Ugb3IgbmlsCEdpdmVUYXNrB2FuZFRoZW4FY2F0Y2gMZ2V0bWV0YXRhYmxlCWdldFN0YXR1cwZTdGF0dXMHU3RhcnRlZAdmaW5hbGx5C0dpdmVQcm9taXNlBXBhaXJzBG5leHQKRG9DbGVhbmluZwAOAwABAAAADOIBAQD/AgAAAAAAADACAacAAAAA+wIAAJ49AQMCAAAApAADAAAAIECfAAMCggACAAQDAQUBAAMCBAAAIEAADQMBGAABAAAAAQAA/gAAAA4AAAAABAEAAAAAHLssAANSAgAApAEBAAAAAECfAQIC8AEGAAIAAICkAQQAAAAwQG8CBQCMAwIAnwEDAbsoAANSAgAApAEHAAAAYECfAQIC8AEJAAgAAIBNAQBQCQAAACsBBQCkAQQAAAAwQG8CCgCMAwIAnwEDAYIAAQALAwQEAAAAQAMFAwYEAAAwQAMHAwgEAABgQAMJAwoDCwATDAEYAAAAAAAAAAEAAAAAAgAAAAAAAAAAAAEAAAAAAhYAAAAABgIAAAAAMrssAQNSAwEApAIBAAAAAECfAgIC8AIEAAIAAIBSAgEAnwIBAYIAAQC7LAEDUgMBAKQCAQAAAABAnwICAvACBQADAACAvAIBGgQAAACfAgIBggABALssAQNSAwEApAIBAAAAAECfAgIC8AIGAAUAAICkAggAABxggFIDAQCfAgIBggABAE0CAVAJAAAADgIEALwCAVAJAAAAnwICAYIAAQCkAgsAAACgQG8DDAC7LAEDUgUBAKQEAQAAAABAnwQCAp8CAwGCAAEADQMEBAAAAEADDQMOAw8DEAMRAxIEABxggAMKAxMEAACgQAMUAB4VARgAAAAAAAAAAQAAAQAAAAAAAAEAAAABAAAAAAAAAQAAAAABAAABAAAAAgAAAAAAAAAAAh8AAAAABAEAAAAAD6kBAAC7KAADUgMAAKQCAQAAAABAnwICAvACBwACAACATQIA2wMAAADwAgIABAAAAKkBAAGpAQEAggECAAUDCAQAAABAAwkDFgMXACwYARgAAAAAAAAAAAAAAAAAAAAtAAAAAAQCAQAAAAr7AwAAhwIDAQ4CAwD7AwAAhwIDAYICAgBNAwCnAAAAAIcCAwGCAgIAAQMBADIZARgAAAABAAACAAAAMwAAAAAIAwEAAAcAAAEDBAwCN/sEAACHAwQBRwMOAAAAAACkAwEAAAAAQG8EAgC7PwEDUgcBAKQGBAAAADBAnwYCArwEBI0FAAAAnwQDAowFAgCfAwMBTQMApwYAAACHBAMBDgIbALssAgNSBgIApAUIAAAAcECfBQIC8AUGAAkAAICkBQEAAAAAQG8GCgCMBwIAnwUDAbsoAgNSBgIApAUMAAAAsECfBQIC8AUJAA0AAIBNBQJQDgAAACsFBQCkBQEAAAAAQG8GDwCMBwIAnwUDAWoCAwEOBAQAUgcEALwFABcQAAAAnwUDAYIAAQARAwYEAAAAQAMaAxsEAAAwQAMcAwEDBAQAAHBAAwUDBwMIBAAAsEADCQMKAwsDFQBDHQEYLgAAAAEAAAAAAAAAAAAAAAADAAENwAAAAAAAAAEAAAAAAgAAAAAAAAAAAAEAAAAAQAIBAAAAAhYAAAAABQIAAAAAJysBBQCkAgEAAAAAQG8DAgCMBAIAnwIDAbssAQNSAwEApAIEAAAAMECfAgIC8AIGAAUAAICkAgEAAAAAQG8DBgCMBAIAnwIDAbsoAQNSAwEApAIIAAAAcECfAgIC8AIJAAkAAIBNAgFQCgAAACsCBQCkAgEAAAAAQG8DCwCMBAIAnwIDAU0EAKcNAAAAHAMEAJUCAwxqAQACggICAA4DBgQAAABAAx4DBAQAADBAAwUDBwMIBAAAcEADCQMKAwsCAAAAAAAA8D8DAQBkHwEYTwEAAAAAsAAAAAAAAAEAAAAAAgAAAAAAAAAAAAEAAAAAUAAAAAECFgAAAAACAAEAAAAF+wAAALwAAIEAAAAAnwACAYIAAQABAxIAeQABGAAAAAABegAAAAADAAIAAAAF+wAAAPsBAQDGAgAAagIAAYIAAQAAAHwAARgAAAAAAX0AAAAABgMDAAAAEfsDAABSBQAAvAMDtQAAAACfAwMB+wMAAFIFAQC8AwMZAQAAAJ8DAwH7AwIAUgUCALwDA/0CAAAAnwMDAt4DAQCCAAEAAwMgAyEDHwCCAQABGAAAAAAAAQAAAAABAAAAAAABgwAAAAADAAIAAAAF+wAAAPsBAQDGAgAAagIAAYIAAQAAAIgBAAEYAAAAAAGJAAAAAAcCAAAAABu7PAEDUgMBAKQCAQAAAABAnwICArwDAf0CAAAAnwMCAk0FAuwDAAAATQQFswQAAADxAwIABAAAAIIBAgDZBQAAEgABALwDAP0FAAAAnwMDAtkGAQASAAAAEgADALwEAUIGAAAAnwQDAYIBAgAHAyIEAAAAQAMjAyQDJQMfAyYCBwhyJwEYAAAAAAACAAAAAAAAAAABAwAAAAADAAAAAAADcwAAAAAKAQAAAAAxTQEApwAAAACkAgIAAAAQQFIDAQCfAgIEFwIUALssBgNSCAYApAcEAAAAMECfBwIC8AcIAAUAAAC7LAYDUggGAKQHBAAAADBAnwcCAvAHBwAGAACAxgcAAGoHAQVSCQYAvAcAFwcAAACfBwMBbgLr/wIAAACkAgkAAACAQFIDAQCfAgIDRwMOAAAAAADGBAAAagQBAlIGAwC8BAAXBwAAAJ8EAwGkBAkAAACAQFIFAQCfBAIDUgIEAFIDBQBIAPH/ggABAAoDAQMoBAAAEEADBAQAADBAAw4DEAMVAykEAACAQACTASoBGAAAAwAAAAABAAAAAAAAAAAAAAAAAAEAAQAAAP0ACAAAAAEAAQABAAAAAQAAAAAA/QWUAAAAAAMAAAECACejAAAA/wAFAAAAAABvAQAAMAEA2wEAAADAAQIAEgAAADABAO8DAAAAwAEEAMACBQAwAgAXBgAAAMACBwAwAgC2CAAAAMACCQASAAAAMAIAbgoAAADAAgsAEgAAADACAM4MAAAAwAINADACAP0OAAAAwAIPADACAOkQAAAAwAIRADACAFESAAAATQIAURIAAAAwAgBQEwAAAIIAAgAUAxcDFgYAAwMGAQYCAxUGAwMYBgQDGQYFAx0GBgMfBgsDJwYMAyoDCgkAAQIDBAUGCwwBAAEYAAYAAQAABQAAAAYLAAAOAAAGAAAAEQAAACEAAA4AACEAABYAAAADAQAAAAANhikJc3FrKzS07WPnonZ8acLz0T3sszGXPh8/XXWh5UHIrt8oBY1ALA==

-- Decompiled by Krnl

local v_u_25 = {
	["ClassName"] = "Maid",
	["new"] = function()
		-- upvalues: (copy) v_u_25
		local v1 = v_u_25
		return setmetatable({
			["_tasks"] = {}
		}, v1)
	end,
	["_doTask"] = function(_, p2)
		if typeof(p2) == "function" then
			p2()
			return
		elseif typeof(p2) == "RBXScriptConnection" then
			p2:Disconnect()
			return
		elseif typeof(p2) == "thread" then
			task.cancel(p2)
			return
		elseif p2.Destroy then
			p2:Destroy()
		else
			warn("[Maid.DoCleaning] - Unable to clean task of type", (typeof(p2)))
		end
	end,
	["isMaid"] = function(p3)
		local v4
		if type(p3) == "table" then
			v4 = p3.ClassName == "Maid"
		else
			v4 = false
		end
		return v4
	end,
	["__index"] = function(p5, p6)
		-- upvalues: (copy) v_u_25
		if v_u_25[p6] then
			return v_u_25[p6]
		else
			return p5._tasks[p6]
		end
	end,
	["__newindex"] = function(p7, p8, p9)
		-- upvalues: (copy) v_u_25
		if v_u_25[p8] ~= nil then
			error(("\'%s\' is reserved"):format((tostring(p8))), 2)
		end
		local v10 = p7._tasks
		local v11 = v10[p8]
		if p9 then
			if typeof(p9) == "RBXScriptSignal" then
				error("Task cannot be a RBXScriptSignal, did you mean RBXScriptConnection?", 2)
			end
			if type(p9) == "table" and not p9.Destroy then
				error("[Maid.GiveTask] - Gave table task without .Destroy\n\n", 2)
			end
		end
		v10[p8] = p9
		if v11 then
			p7:_doTask(v11)
		end
	end,
	["GiveTask"] = function(p12, p13)
		if not p13 then
			error("Task cannot be false or nil", 2)
		end
		if typeof(p13) == "RBXScriptSignal" then
			error("Task cannot be a RBXScriptSignal, did you mean RBXScriptConnection?", 2)
		end
		if type(p13) == "table" and not p13.Destroy then
			error("[Maid.GiveTask] - Gave table task without .Destroy\n\n", 2)
		end
		local v14 = #p12._tasks + 1
		p12[v14] = p13
		return v14
	end,
	["GivePromise"] = function(p_u_15, p_u_16)
		local v17 = getmetatable(p_u_16)
		if p_u_16:getStatus() ~= v17.Status.Started then
			return p_u_16
		end
		local v_u_18 = p_u_15:GiveTask(function()
			-- upvalues: (copy) p_u_16
			p_u_16:cancel()
		end)
		p_u_16:finally(function()
			-- upvalues: (copy) p_u_15, (copy) v_u_18
			p_u_15[v_u_18] = nil
		end)
		return p_u_16
	end,
	["DoCleaning"] = function(p19)
		local v20 = p19._tasks
		for v21, v22 in pairs(v20) do
			if typeof(v22) == "RBXScriptConnection" or typeof(v22) == "thread" then
				v20[v21] = nil
				p19:_doTask(v22)
			end
		end
		local v23, v24 = next(v20)
		while v24 ~= nil do
			v20[v23] = nil
			p19:_doTask(v24)
			v23, v24 = next(v20)
		end
	end
}
v_u_25.Destroy = v_u_25.DoCleaning
return v_u_25
