-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMMDHNldG1ldGF0YWJsZQZ0YXJnZXQCa1ACa0kCa0QIX2xhc3RFcnIMX2ludGVncmFsRXJyA25ldwZVcGRhdGUJU2V0VGFyZ2V0BVJlc2V0B19faW5kZXgABQcEAQAACQYAAAUEDwICAhuQAAAA/wUEAAAAAAD7BgAAnj0FAwYAAACkBAIAAAAQQJ8EAwIwAAQMAwAAAJAFAQQwBQRdBQAAAJAFAgAwBQRmBgAAAJAFAwAwBQTKBwAAAFsFAAAwBQSmCAAAAFsFAAAwBQQGCQAAAIIEAgAKAgAAAAAAAAAAAwEEAAAQQAMCAgAAAAAAAPA/AwMDBAMFAwYDBwAbCAEYAAEAAAAAAAAAAQABAAABAAABAAABAAABAAACHAAAAAAKAwAAAAgFAAAFAwQPAh1NBAAMAAAAACYDBAFNBAAGAQAAAAkFAwJDBAQFMAQABgEAAABNBgCmAgAAACYFAwbsBAUCMAMApgIAAABNBgBdAwAAAAkFBgNNBwBmBAAAAE0IAAYBAAAACQYHCE0IAMoFAAAACQcIBEMJBQZDCAkHgggCAAYDAgMHAwYDAwMEAwUAKAkBGAAAAAEAAAAAAAEAAAABAAEAAAEAAAAAAQAAAQABKQAAAAACAgAAAAADMAEADAAAAACCAAEAAQMCADMKARgAAAE0AAAAAAIBAAAAAAtNAQCmAAAAAFsBAQEwAQCmAAAAAE0BAAYCAAAAWwEBATABAAYCAAAAggABAAMDBgIAAAAAAAAAAAMHADYLARgAAAAAAAEAAAAAATcAAAAAAgAAAQIAE6MAAAD/AAQAAAAAADAAAG4AAAAAwAEBABIAAAAwAQDvAgAAAMABAwAwAQAmBAAAAMABBQAwAQCXBgAAAMABBwAwAQB/CAAAAIIAAgAJAwwGAAMIBgEDCQYCAwoGAwMLBAABAgMBAAEYAAEAAQAYAAAADQAACwAAAwAABQEAAAAABKeDxHheJMkUlUeu7MvmfBAt9HoxcgyruKroq519sfukbaUbgh6g4pg=

-- Decompiled by Krnl

local v_u_1 = {}
v_u_1.__index = v_u_1
function v_u_1.new(p2, p3, p4, p5)
	-- upvalues: (copy) v_u_1
	local v6 = p2 or 0
	local v7 = v_u_1
	local v8 = setmetatable({}, v7)
	v8.target = v6
	v8.kP = p3 or 1
	v8.kI = p4 or 0
	v8.kD = p5 or 0
	v8._lastErr = v6 * 0
	v8._integralErr = v6 * 0
	return v8
end
function v_u_1.Update(p9, p10, p11)
	local v12 = p9.target - p10
	p9._integralErr = p9._integralErr + v12 * p11
	local v13 = (v12 - p9._lastErr) / p11
	p9._lastErr = v12
	local v14 = p9.kP * v12
	local v15 = p9.kI * p9._integralErr
	local v16 = p9.kD * v13
	return v14 + v15 + v16
end
function v_u_1.SetTarget(p17, p18)
	p17.target = p18
end
function v_u_1.Reset(p19)
	p19._lastErr = p19._lastErr * 0
	p19._integralErr = p19._integralErr * 0
end
return v_u_1
