-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMXHW1pc3NpbmcgYnVkZ2V0UGVyV2luZG93IGxpbWl0BmFzc2VydAxzZXRtZXRhdGFibGUCb3MFY2xvY2sLX2xhc3RVcGRhdGUQX2J1ZGdldFBlcldpbmRvdxVfYnVkZ2V0V2luZG93RHVyYXRpb24FX2RhdGEDbmV3C21pc3Npbmcga2V5BlVwZGF0ZQZhbW91bnQMQ2FuVXNlQnVkZ2V0Cmxhc3RVcGRhdGUJVXNlQnVkZ2V0BXRhYmxlBWNsZWFyB0Rlc3Ryb3kHX19pbmRleAtSYXRlTGltaXRlcgtfX0NsYXNzTmFtZQlJbmNyZW1lbnQABgYCAQAABwQAAAUCAoIiRwACAAAAAICpAwABqQMBAIEBAwQAAAAAbwQAAKQCAgAAABBAnwIDAZABAQP/AgMAAAAAAPsFAACePQIEBQAAAFIEAgCkAwUAAABAQJ8DAwGkAwgAABxggJ8DAQIwAwK4CQAAADAAAsAKAAAAMAECgwsAAAD/AwAAAAAAADADAowMAAAAggICAA0DAQMCBAAAEEACAAAAAAAA8D8DAwQAAEBAAwQDBQQAHGCAAwYDBwMIAwkADAoBGAAAAAAAAAAAAAABAQABAAAAAAAAAgAAAAABAAEAAQAAAAINAAAAAAcDAAAACAUAAAUDBA8CIkcBAgAAAACAqQQAAakEAQCBAQQEAAAAAG8FAACkAwIAAAAQQJ8DAwGQAgIDvAMAJgQAAACfAwIBxgMAAE0FAIwFAAAAhwQFAQ4EBgBNBQCMBQAAAIcEBQFNAwQLBgAAAGUAAQCMAwAAQwUDAk0GAMAHAAAA1AUCAAYAAACpBAABqQQBAIIEAgAIAwsDAgQAABBAAgAAAAAAAPA/AwwDCQMNAwcAGQ4BGAAAAAAAAAAAAAABAQAAAQEAAAABAAAAAAACAgAAAAAAAAAaAAAAAAgEAAAACQYAAAUEBA+CgTGQAgIAuwECA1IFAgCkBAIAAAAQQJ8EAgFHAQIAAAAAgKkFAAGpBQEAgQEFBAMAAABvBgMApAQCAAAAEECfBAMBKwMIAFIGAQBSBwIAvAQApwQAAACfBAQCKwQCAKkFAACCBQIATQUAjAUAAACHBAUBKwQNAOIFCACMBgAAMAYFCwYAAACkBgsAACiQgJ8GAQIwBgVkBwAAAFIEBQBNBQCMBQAAAGoEBQFNBQQLBgAAAEMFBQIwBQQLBgAAAKkFAQCCBQIADAIAAAAAAADwPwMCBAAAEEADCwMOAwkDDQMPBQIGBwMEAwUEACiQgAAlEAEYAAEAAAAAAQAAAAAAAAAAAAIBAAAAAAEBAAMAAAEBAQAAAQAAAAAAAgAAAgAAAAABACYAAAAACgEAAAAAJKQBAgAABACAnwEBAk0CAIwDAAAAxgMAAMYEAABkAhkATQgGZAQAAAAmBwEITQgAgwUAAAB9CBMABwAAAE0IBgsGAAAATQkAwAcAAAAmCAgJMAgGCwYAAABNCAYLBgAAAIwJAAB9CAUACQAAAE0IAIwDAAAAxgkAAGoJCAUwAQZkBAAAAG4C5v8CAAAAggABAAgDBAMFBAAEAIADCQMPAwgDDQMHADwMARgAAAABAAAAAAIAAAEAAAABAAAAAAAAAQAAAAABAAAAAgD4AAs9AAAAAAQBAAAAAA2kAQIAAAQAgE0CAIwDAAAAnwECAYE9AAUEAAAAUgIAAG8DBACkAQYAAABQQJ8BAwGCAAEABwMRAxIEAAQAgAMJAAMDBAAAUEAAShMBGAAAAAAAAQAAAAAAAAFLAAAAAAIAAAECAB2jAAAA/wAEAAAAAAAwAABuAAAAAG8BAQAwAQDlAgAAAMABAwASAAAAMAEA7wQAAADAAQUAMAEApwYAAADAAQcAMAEABwgAAABNAQAHCAAAADABABUJAAAAwAEKADABACYLAAAAwAEMADABAFANAAAAggACAA4DFAMVAxYGAAMKBgEDDgYCAxADFwYDAwwGBAMTBQABAgMEAQABGAAIAAEAAQAAAQAAAA0AAAwAABYAAAABAAAOAAAFAQAAAAAFGyQQuKNzwCsp4HosIbhaXTRnjiFe+BBzEQswMcYDTT1i2z+1BaSq8Q==

-- Decompiled by Krnl

local v_u_1 = {}
v_u_1.__index = v_u_1
v_u_1.__ClassName = "RateLimiter"
function v_u_1.new(p2, p3)
	-- upvalues: (copy) v_u_1
	local v4 = p2 ~= nil
	assert(v4, "missing budgetPerWindow limit")
	local v5 = {}
	local v6 = v_u_1
	setmetatable(v5, v6)
	v5._lastUpdate = os.clock()
	v5._budgetPerWindow = p2
	v5._budgetWindowDuration = p3 or 1
	v5._data = {}
	return v5
end
function v_u_1.CanUseBudget(p7, p8, p9)
	local v10 = p8 ~= nil
	assert(v10, "missing key")
	p7:Update()
	return (not p7._data[p8] and 0 or p7._data[p8].amount) + (p9 or 1) <= p7._budgetPerWindow
end
function v_u_1.UseBudget(p11, p12, p13, p14)
	local v15 = p13 or 1
	assert(v15)
	local v16 = p12 ~= nil
	assert(v16, "missing key")
	if not (p14 or p11:CanUseBudget(p12, v15)) then
		return false
	end
	local v17 = p11._data[p12]
	if not v17 then
		v17 = {
			["amount"] = 0,
			["lastUpdate"] = os.clock()
		}
		p11._data[p12] = v17
	end
	v17.amount = v17.amount + v15
	return true
end
v_u_1.Increment = v_u_1.UseBudget
function v_u_1.Update(p18)
	local v19 = os.clock()
	for v20, v21 in p18._data do
		if v19 - v21.lastUpdate >= p18._budgetWindowDuration then
			v21.amount = v21.amount - p18._budgetPerWindow
			if v21.amount <= 0 then
				p18._data[v20] = nil
			end
			v21.lastUpdate = v19
		end
	end
end
function v_u_1.Destroy(p22)
	table.clear(p22._data)
	setmetatable(p22, nil)
end
return v_u_1
