-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMdBnR5cGVvZgZzdHJpbmcVdGV4dCBtdXN0IGJlIGEgc3RyaW5nBmFzc2VydAZDb2xvcjMbdGV4dENvbG9yMyBtdXN0IGJlIGEgQ29sb3IzAVIkdGV4dENvbG9yMy5SIG11c3QgYmUgYmV0d2VlbiAwIGFuZCAxAUckdGV4dENvbG9yMy5HIG11c3QgYmUgYmV0d2VlbiAwIGFuZCAxAUIkdGV4dENvbG9yMy5CIG11c3QgYmUgYmV0d2VlbiAwIGFuZCAxDjxmb250IGNvbG9yPScjBVRvSGV4Aic+BzwvZm9udD4OYWRkQ29sb3JUb1RleHQdc3Ryb2tlQ29sb3IzIG11c3QgYmUgYSBDb2xvcjMQPHN0cm9rZSBjb2xvcj0nIw0nIHRoaWNrbmVzcz0nCHRvc3RyaW5nDycgam9pbj0nbWV0ZXInPgk8L3N0cm9rZT4PYWRkU3Ryb2tlVG9UZXh0BGZpbmQRZG9lc1RleHRIYXZlQ29sb3IDc3ViB2Zyb21IZXgUZXh0cmFjdENvbG9yRnJvbVRleHQABQoCAAAAAGG7LAADUgUAAKQEAQAAAABAnwQCAvAEAgACAAAAqQMAAakDAQCBAQMEAwAAAG8EAwCkAgUAAABAQJ8CAwG7LAEDUgUBAKQEAQAAAABAnwQCAvAEAgAGAAAAqQMAAakDAQCBAQMEBwAAAG8EBwCkAgUAAABAQJ8CAwGpAwAATQQBcwgAAACMBQAAfQUIAAQAAABNBAFzCAAAAIwFAQDUBAIABQAAAKkDAAGpAwEAgQEDBAkAAABvBAkApAIFAAAAQECfAgMBqQMAAE0EAWYKAAAAjAUAAH0FCAAEAAAATQQBZgoAAACMBQEA1AQCAAUAAACpAwABqQMBAIEBAwQLAAAAbwQLAKQCBQAAAEBAnwIDAakDAABNBAFjDAAAAIwFAAB9BQgABAAAAE0EAWMMAAAAjAUBANQEAgAFAAAAqQMAAakDAQCBAQMEDQAAAG8EDQCkAgUAAABAQJ8CAwFvAw4AvAgBHw8AAACfCAICUgQIAG8FEABSBgAAbwcRAHMCAweCAgIAEgMBBAAAAEADAgMDAwQEAABAQAMFAwYDBwMIAwkDCgMLAwwDDQMOAw8DEAAFEQEYAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAYAAAAADQMAAAAIBQAABQMDBwIwuywAA1IGAACkBQEAAAAAQJ8FAgLwBQIAAgAAAKkEAAGpBAEAgQEEBAMAAABvBQMApAMFAAAAQECfAwMBuywBA1IGAQCkBQEAAAAAQJ8FAgLwBQIABgAAAKkEAAGpBAEAgQEEBAcAAABvBQcApAMFAAAAQECfAwMBkAICCG8ECQC8CwEfCgAAAJ8LAgJSBQsAbwYLALs/AgNSDAIApAsNAAAAwECfCwICUgcLAG8IDgBSCQAAbwoPAHMDBAqCAwIAEAMBBAAAAEADAgMDAwQEAABAQAMFAxICAAAAAAAA8D8DEwMOAxQDFQQAAMBAAxYDFwANGAEYAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAQEBAAAAAQEAAAAAAAEBAQAADgAAAAAFAQAAAAYDAAAFAQMZuywAA1IEAACkAwEAAAAAQJ8DAgLwAwIAAgAAAKkCAAGpAgEAgQECBAMAAABvAwMApAEFAAAAQECfAQMBpAIHAAAYIIBSAwAAbwQIAJ8CAwJHAgIAAAAAgKkBAAGpAQEAggECAAkDAQQAAABAAwIDAwMEBAAAQEADGQQAGCCAAw0AGRoBGAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAaAAAAAAcBAAAABgMAAAUBAye7LAADUgQAAKQDAQAAAABAnwMCAvADAgACAAAAqQIAAakCAQCBAQIEAwAAAG8DAwCkAQUAAABAQJ8BAwGkAQcAABgggFICAABvAwgAnwEDAg4BEACVAQEJlQMBC3gCAwo0LQAGAQIAAFIEAABSBQEAUgYCAKQDDQAAMCCAnwMEAqQEEAAAPOCAUgUDAJ8EAgKCBAIAxgIAAIICAgARAwEEAAAAQAMCAwMDBAQAAEBAAxkEABgggAMNAgAAAAAAACxAAgAAAAAAAPA/AgAAAAAAABhAAxsEADAggAMFAxwEADzggAAdHQEYAAAAAAAAAAAAAAAAAAAAAQAAAAABAQEAAQAAAAAAAAABAAAAAQIAHgAAAAACAAABAgAQowAAAP8AAwAAAAAAwAEAADABANoBAAAAwAECADABAOIDAAAAwAEEADABAAcFAAAAwAEGADABAHgHAAAAggACAAgGAAMRBgEDGAYCAxoGAwMdBAABAgMBAAEYAAEAAwAACAAADAAABAAADAEAAAAABBEQ4d4/QMH0I9SLSvP4RVCen3whI+SfIUrYJazioHAQGXGgTM/zUy4=

-- Decompiled by Krnl

return {
	["addColorToText"] = function(p1, p2)
		local v3 = typeof(p1) == "string"
		assert(v3, "text must be a string")
		local v4 = typeof(p2) == "Color3"
		assert(v4, "textColor3 must be a Color3")
		local v5
		if p2.R >= 0 then
			v5 = p2.R <= 1
		else
			v5 = false
		end
		assert(v5, "textColor3.R must be between 0 and 1")
		local v6
		if p2.G >= 0 then
			v6 = p2.G <= 1
		else
			v6 = false
		end
		assert(v6, "textColor3.G must be between 0 and 1")
		local v7
		if p2.B >= 0 then
			v7 = p2.B <= 1
		else
			v7 = false
		end
		assert(v7, "textColor3.B must be between 0 and 1")
		return "<font color=\'#" .. p2:ToHex() .. "\'>" .. p1 .. "</font>"
	end,
	["addStrokeToText"] = function(p8, p9, p10)
		local v11 = typeof(p8) == "string"
		assert(v11, "text must be a string")
		local v12 = typeof(p9) == "Color3"
		assert(v12, "strokeColor3 must be a Color3")
		return "<stroke color=\'#" .. p9:ToHex() .. "\' thickness=\'" .. tostring(p10 or 1) .. "\' join=\'meter\'>" .. p8 .. "</stroke>"
	end,
	["doesTextHaveColor"] = function(p13)
		local v14 = typeof(p13) == "string"
		assert(v14, "text must be a string")
		return string.find(p13, "<font color=\'#") ~= nil
	end,
	["extractColorFromText"] = function(p15)
		local v16 = typeof(p15) == "string"
		assert(v16, "text must be a string")
		local v17 = string.find(p15, "<font color=\'#")
		if not v17 then
			return nil
		end
		local v18 = v17 + 14
		local v19 = v18 + 6 - 1
		local v20 = string.sub(p15, v18, v19)
		return Color3.fromHex(v20)
	end
}
