-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMlBnN0cmluZwVtYXRjaAh0b3N0cmluZxVeKFteJWRdKiVkKSglZCopKC4tKSQHcmV2ZXJzZQgoJWQlZCVkKQMlMSwEZ3N1YgVjb21tYQZhc3NlcnQDJTAuAWQGZm9ybWF0G2dldFNvcnRhYmxlU3RyaW5nRnJvbU51bWJlcgRtYXRoBnJhbmRvbVUwMTIzNDU2Nzg5YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXpBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWi4tOis9XiEvKj8mPD4oKVtde31AJSQjA3N1YgV0YWJsZQZpbnNlcnQGY29uY2F0CmJhc2U4NVVVSUQCdGgCc3QCbmQCcmQSZ2V0U3VmZml4Rm9yTnVtYmVyBWZsb29yBCUuMWYLZm9ybWF0Q291bnQAAUsBTQFCAVQBUQxnZXRTaG9ydEhhbmQABwwBAAAABgMAAAUBAhmkAQIAAAQAgLs/AANSAwAApAIEAAAAMECfAgICbwMFAJ8BAwRSBQEAvAgCmwYAAACfCAICbwoHAG8LCAC8CAjMCQAAAJ8IBAK8CAibBgAAAJ8IAgJSBggAUgcDAHMEBQeCBAIACgMBAwIEAAQAgAMDBAAAMEADBAMFAwYDBwMIAAQJARgAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAABQAAAAAIAgAAAAcEAAAFAgICJ0cAAgAAAACAqQMAAakDAQC7AQMCpAIBAAAAAECfAgIBRwECAAAAAICpAwABqQMBALsBAwKkAgEAAAAAQJ8CAgGMBAAA1AQCAAEAAACpAwABqQMBALsBAwKkAgEAAAAAQJ8CAgFvAwIAuz8BA1IHAQCkBgQAAAAwQJ8GAgJSBAYAbwUFAHMCAwVSBAAAvAICjQYAAACfAgMAggIAAAcDCgQAAABAAwsDAwQAADBAAwwDDQAIDgEYAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAAAAAAACQAAAAAKAQAAAAYDAAAFAQIg/wEAAAAAAACMBAEAUgIAAIwDAQCoAhUApAUCAAAEAICMBgEAjAdVAJ8FAwJvBwMANC0HBQUFAABSCAUAUgkFAKQGBgAAFECAnwYEAp40AQUGAAAAUggBAFIJBgCkBwkAACBwgJ8HAwGLAuv/pAILAAAocIBSAwEAnwICAIICAAAMAw8DEAQABACAAxEDAQMSBAAUQIADEwMUBAAgcIADFQQAKHCAAA4WARgAAAIAAAABAAAAAAEAAAAAAAAAAQAAAAAAAP0FAAAAAA8AAAAABAEAAAAGAwAABQECGCEBAAANAQUAAQAAAA0BAwACAAAADQEDAAMAAIBvAgQAggICACECAAUNAgMABgAAgG8DBwCCAwIADQIDAAgAAIBvAwkAggMCAA0CAwAKAACAbwMLAIIDAgBvAwQAggMCAAwCAAAAAAAAWUACAAAAAAAAJkACAAAAAAAAKEACAAAAAAAAKkADFwIAAAAAAAAkQAIAAAAAAADwPwMYAgAAAAAAAABAAxkCAAAAAAAACEADGgAZGwEYAAIAAAAAAAEAAgEAAQABAAEAAQABAAIAGgAAAAAFAQAAAAoDAAEFAQIDAhMCFyECAABvAwEA1AICAAMAAACpAQABqQEBAA4BCgC7DAADUgQAAKQDBAAADCCAnwMCArs/AwKkAgYAAABQQJ8CAgKCAgIAbwIHAFIEAAC8AgKNCAAAAJ8CAwCCAgAACQIAAAAAAADwPwL8qfHSTWJQPwMPAxwEAAwggAMDBAAAUEADHQMNACseARgAAAAAAAABAQAAAAAAAAAAAAIAAAAAACwAAAAACwEAAAAKAwABBQECAwgsAjr/AQAABgAAAG8CAABvAwEAbwQCAG8FAwBvBgQAbwcFAMUBAgcBAAAAjAIBAIwD6AN9AwcAAAAAABwDAQBgAgQAAwAAAD4AAAaVAgIHSAD3/4wDAQBgAx4AAgAAAFIGAAAhCAYHbwkIANQIAgAJAAAAqQcAAakHAQAOBwsAuwwGA1IKBgCkCQsAACiQgJ8JAgK7PwkCpAgNAAAAwECfCAICUgQIAGUABwBvCA4AUgoGALwICI0PAAAAnwgDAlIECABlAAAAhwUBAnMDBAWCAwIAuz8AA1IEAACkAw0AAADAQJ8DAgKCAwIAEAMfAyADIQMiAyMDJAIAAAAAAECPQAIAAAAAAADwPwL8qfHSTWJQPwMPAxwEACiQgAMDBAAAwEADHQMNADMlARgIAAAAAAAAAAAAAQIAAAAAAAEB/gUAAAHvAAAAAAABAQAAAAAAAAAAAAACAAAAAAAADQAAAgAAAAAALAAAAAADAAABAgAUowAAAP8ABAAAAAAAwAEAADABAOQBAAAAwAECADABAIgDAAAAwAEEADABACIFAAAAwAEGADABAAwHAAAAwAEIAMACCQAwAgDACgAAAIIAAgALBgADCQYBAw4GAgMWBgMDGwYEBgUDJQYAAQIDBAUBAAEYAAEAAgAABAAABgAACwAAEggAABABAAAAAAYPS2DZlc5S6D2PCk3xj/gV/RGo/bN0ppvANxGSMiubvsY+QtX1jgH3

-- Decompiled by Krnl

return {
	["comma"] = function(p1)
		local v2, v3, v4 = string.match(tostring(p1), "^([^%d]*%d)(%d*)(.-)$")
		return v2 .. v3:reverse():gsub("(%d%d%d)", "%1,"):reverse() .. v4
	end,
	["getSortableStringFromNumber"] = function(p5, p6)
		local v7 = p5 ~= nil
		assert(v7)
		local v8 = p6 ~= nil
		assert(v8)
		local v9 = p6 >= 0
		assert(v9)
		return ("%0." .. tostring(p6) .. "d"):format(p5)
	end,
	["base85UUID"] = function(p10)
		local v11 = {}
		for _ = 1, p10 do
			local v12 = math.random(1, 85)
			local v13 = string.sub("0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ.-:+=^!/*?&<>()[]{}@%$#", v12, v12)
			table.insert(v11, v13)
		end
		return table.concat(v11)
	end,
	["getSuffixForNumber"] = function(p14)
		local v15 = p14 % 100
		if v15 == 11 or (v15 == 12 or v15 == 13) then
			return "th"
		end
		local v16 = p14 % 10
		return v16 == 1 and "st" or (v16 == 2 and "nd" or (v16 == 3 and "rd" or "th"))
	end,
	["getShortHand"] = function(p17)
		local v18 = {
			"",
			"K",
			"M",
			"B",
			"T",
			"Q"
		}
		local v19 = 1
		while p17 >= 1000 and v19 < #v18 do
			p17 = p17 / 1000
			v19 = v19 + 1
		end
		if v19 <= 1 then
			return tostring(p17)
		end
		local v20
		if p17 % 1 <= 0.001 then
			local v21 = math.floor(p17)
			v20 = tostring(v21)
		else
			v20 = ("%.1f"):format(p17)
		end
		return v20 .. v18[v19]
	end
}
