-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMZD19kb2dzT3duZWRWYWx1ZQdyZXF1aXJlE0Fkb3B0aW9uU3RhbmRCaW5kZXIGc2NyaXB0BlBhcmVudAVTdGFydAlQbGF5ZXJHdWkVRE9HU19PV05FRF9WQUxVRV9OQU1FB2FuZFRoZW4Ed2FybgVjYXRjaARpbml0DkZpbmRGaXJzdENoaWxkE0RPR19OQU1FX1ZBTFVFX05BTUUFVmFsdWUKZ2V0RG9nTmFtZQdkb2VzT3duBGdhbWUHUGxheWVycwpHZXRTZXJ2aWNlC0xvY2FsUGxheWVyEVJlcGxpY2F0ZWRTdG9yYWdlA1N0ZAx3YWl0Rm9yQ2hpbGQTQWRvcHRpb25TdGFuZENvbnN0cwAFAgEBAAAABPsBAAAwAAGVAAAAAIIAAQABAwEAEAABGAAAAAEWAAAAAAQABQAAACGkAAEAAAAAQKQDBAAAADBATQIDJAUAAABNAQLGAgAAAJ8AAgLeAAAA+wAAALwAABwGAAAAnwACAfsAAQD7AgIATQECmQcAAAD7AwMATQIDhggAAACfAAMCwAIJABICBAC8AAC1CgAAAJ8AAwKkAgwAAACwQLwAABkNAAAAnwADAYIAAQAOAwIEAAAAQAMDAwQEAAAwQAMFAwYDBwMIBgADCQMKBAAAsEADCwEACwwBGAAAAAAAAAAAAAABAAAAAgAAAAAAAAABAAAAAAgAAAAAAQwAAAAABgECAAAAF/sCAABNAQKVAAAAACsBAQCCAAEA+wIAAE0BApUAAAAAUgMAALwBAQMBAAAAnwEDAisBAQCCAAEA+wUBAE0EBXACAAAAvAIBAwEAAACfAgMCTQMC7AMAAACCAwIABAMBAw0DDgMPABoQARgAAAAAAQIAAAAAAAABAQIAAAAAAAEAABsAAAAABQEBAAAAEfsCAABNAQKVAAAAACsBAQCCAAEA+wMAAE0CA5UAAAAAUgQAALwCAgMBAAAAnwIDAkcCAgAAAACAqQEAAakBAQCCAQIAAgMBAw0AJREBGAAAAAABAgAAAAAAAAAAAAAAJgAAAAAJAAABAgA1owAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAk0BADEEAAAApAIBAAAAAEBvBAUAvAICFgMAAACfAgMCpAMHAAAAYEBNBQKhCAAAAE0EBfMJAAAAnwMCAsYEAACkBQcAAABgQKQIDAAAALBATQcIJA0AAABNBgf/CgAAAJ8FAgL/BgMAAAAAANkHAAASAQT/EgADABIAAQASAAUAEgAGADAHBhMOAAAAwAcPABIABgASAAUAMAcGhRAAAADABxEAEgAGADAHBjISAAAAwQQAAIIGAgATAxIEAAAAQAMTAxQDFQMWAwIEAABgQAMXAxgDGQMEBAAAsEADBQMMBgIDEAYDAxEDAQIDAQABGAABAAAAAAABAAEAAAAAAAEAAAAAAAACAQAAAAAAAAAAAgABAAAAAAAAAA8AAAAACwAAAAYAAQAAAAAELr79ss5CiNccepcmcwYFgn449JdRmTX8j/JlJ4TPJ5XVttmaWZZsKg==

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players").LocalPlayer
local v2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v2.Std.waitForChild)
local v_u_4 = nil
local v_u_5 = require(script.Parent.AdoptionStandConsts)
local v_u_10 = {
	["init"] = function()
		-- upvalues: (ref) v_u_4, (copy) v_u_3, (copy) v_u_1, (copy) v_u_5, (copy) v_u_10
		v_u_4 = require(script.Parent.AdoptionStandBinder)
		v_u_4:Start()
		v_u_3(v_u_1.PlayerGui, v_u_5.DOGS_OWNED_VALUE_NAME):andThen(function(p6)
			-- upvalues: (ref) v_u_10
			v_u_10._dogsOwnedValue = p6
		end):catch(warn)
	end,
	["getDogName"] = function(p7)
		-- upvalues: (copy) v_u_10, (copy) v_u_5
		if v_u_10._dogsOwnedValue then
			local v8 = v_u_10._dogsOwnedValue:FindFirstChild(p7)
			if v8 then
				return v8:FindFirstChild(v_u_5.DOG_NAME_VALUE_NAME).Value
			end
		end
	end,
	["doesOwn"] = function(p9)
		-- upvalues: (copy) v_u_10
		if v_u_10._dogsOwnedValue then
			return v_u_10._dogsOwnedValue:FindFirstChild(p9) ~= nil
		end
	end
}
return v_u_10
