-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNSC2dldFJvb3RQYXJ0CFBvc2l0aW9uCU1hZ25pdHVkZQZpc09wZW4FY2xvc2UHZ2V0TmFtZQxfYWRvcHRSZW1vdGUKRmlyZVNlcnZlcgVfbWFpZAx3YWxrQXdheUxvb3AIb25DbG9zZWQMb25DbGlja0Fkb3B0CkdldEJyZWVkSWQFZXZlcnkHQ29ubmVjdBVnZXRPbkNsaWNrQWRvcHRTaWduYWwRZ2V0T25DbG9zZWRTaWduYWwHZG9lc093bgVQUklDRQdzZXROYW1lAApnZXREb2dOYW1lCHNldFRpdGxlBVRJVExFBXVwcGVyCnNldEltYWdlSWQISU1BR0VfSUQSc2V0RGVzY3JpcHRpb25UZWFtCE9QVF9URUFNCHNldFByaWNlDXNldEZpcnN0QWRvcHQEb3BlbgZhY3Rpb24HRW5hYmxlZAxwcmVVcGRhdGVGdW4GUmVtb3ZlCEFkb3B0ICVzBmZvcm1hdAROYW1lCnVwZGF0ZVNwZWMMc2V0bWV0YXRhYmxlA25ldxNCUkVFRF9JRF9WQUxVRV9OQU1FDFdhaXRGb3JDaGlsZA1fYnJlZWRJZFZhbHVlEUFET1BUX1JFTU9URV9OQU1FBFBhcnQFVGltZWQERGlzdAhDYWxsYmFjawxQcmVVcGRhdGVGdW4PUHJlVXBkYXRlUGVyaW9kA0FkZAhHaXZlVGFzawdDaGFuZ2VkBVZhbHVlBmFzc2VydAdEZXN0cm95BGdhbWUHUGxheWVycwpHZXRTZXJ2aWNlC0xvY2FsUGxheWVyEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUDU3RkBE1haWQISW50ZXJ2YWwLUGxheWVyVXRpbHMER2FtZQlEb2dDb25zdHMDRG9nAlVJBk1vZHVsZQxDaXJjbGVBY3Rpb24PQWRvcHRpb25TdGFuZFVJBnNjcmlwdAZQYXJlbnQOQWRvcHRpb25TeXN0ZW0TQWRvcHRpb25TdGFuZENvbnN0cwdfX2luZGV4DUFkb3B0aW9uU3RhbmQLX19DbGFzc05hbWUACwYABAAAABv7AQAATQABGwAAAAD7AQEAnwACAg4AFABNAwA7AQAAAPsFAgBNBAU7AQAAACYCAwRNAQKqAgAAAIwCEABgAgoAAQAAAPsDAwBNAgMRAwAAAJ8CAQIOAgQA+wMDAE0CA4MEAAAAnwIBAYIAAQAFAwEDAgMDAwQDBQAeAAEYAAAAAAABAQAAAAAAAAABAAABAAAAAAEAAAAEHwAAAAAEAAIAAAAQ+wEAAE0AAbYAAAAAnwABAvsCAQBNAQLbAQAAAFIDAAC8AQFrAgAAAJ8BAwH7AgAATQECgwMAAACfAQEBggABAAQDBgMHAwgDBQApAAEYAAAAAAEAAAAAAAABAAAAASoAAAAAAgABAAAAE/sBAABNAAHBAAAAAMYBAAAwAQBcAQAAAPsBAABNAAHBAAAAAMYBAAAwAQDYAgAAAPsBAABNAAHBAAAAAMYBAAAwAQCaAwAAAIIAAQAEAwkDCgMLAwwALgABGAAAAAAAAAEAAAAAAAEAAAAAAAEvAAAAAAkCCAAAAHUOAXMA+wIAALwCAmcAAAAAnwICAvsEAABNAwTBAQAAAPsFAQBNBAXEAgAAAIwFAQCfBAIC2QYAABICAgASAgMAEgIEABICBQC8BATHAwAAAJ8EAwIwBANcBAAAAPsEAABNAwTBAQAAAPsFBQBNBAUKBQAAAJ8EAQLZBgEAEgIFABICAAC8BATHAwAAAJ8EAwIwBAOaBgAAAPsEAABNAwTBAQAAAPsFBQBNBAWVBwAAAJ8EAQLZBgIAEgIAALwEBMcDAAAAnwQDAjAEA9gIAAAA+wQGAE0DBDIJAAAAUgQCAJ8DAgLGBAAAKwMEAPsGBwBNBQYaCgAAAIcEBQL7BgUATQUGugsAAAD7CAYATQcIhQ0AAABSCAIAnwcCApAGBwyfBQIB+wYFAE0FBr4OAAAA+wgHAE0HCLoPAAAAhwYHArwGBksQAAAAnwYCAJ8FAAH7BgUATQUG2xEAAAD7CAcATQcINhIAAACHBgcCnwUCAfsGBQBNBQZFEwAAAPsIBwBNBwiEFAAAAIcGBwKfBQIB+wYFAE0FBg0VAAAAUgYEAJ8FAgH7BgUATQUGIhYAAABWBgMAnwUCAfsGBQBNBQZ2FwAAAJ8FAQGpBQEAggUCAIIAAQAYAw0DCQMOAw8DCgMQAwwDEQMLAxIDEwMUAxUDFgMXAxgDGQMaAxsDHAMdAx4DHwMgAwABAhshARgAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAsAAAAAAAAAAAAAAAAAAAUAAAAAAAAAAAAAAAAABQAAAAABAQEAAAACAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAABAAAAAAEAAAABAAIcAAAAAAQBAQAAAAj7AwAATQIDEQAAAACfAgECVgECADABAPABAAAAggABAAIDBAMiAEIjARgAAAAAAAAAAUMAAAAAAgACAAAABvsBAABNAAFpAAAAAPsBAQCfAAIBggABAAEDJABOAAEYAAAAAAABTwAAAAAHAAMAAAcAAAEDAgoCEPsAAAC8AABnAAAAAJ8AAgL7AQEAbwIBAPsGAgBNBQa6AgAAAIcEBQC8AgKNAwAAAJ8CAwIwAgG6BAAAAIIAAQAFAw0DJQMYAyYDJwBSKAEYAAAAAAEAAAAAAAAAAAAAAVMAAAAADAEKAAAHAAABAwdhAmf/AQMAAAAAAPsEAACePQEEBAAAAFIDAQCkAgEAAAAAQJ8CAwH7AwEATQID7wIAAACfAgECMAIBwQMAAAD7BQIATQQFSQQAAAC8AgDTBQAAAJ8CAwIwAgGMBgAAAPsFAgBNBAU6BwAAALwCANMFAAAAnwIDAjACAdsIAAAA2QIAABIAAQASAgMAEgIEABICBQASAAAAEgIGABICBwASAggAwAMJABICBgDiBBAAMAAERAoAAACpBQAAMAUEcQsAAACMBQgAMAUE4wwAAAAwAgRGDQAAADADBKMOAAAAbwURADAFBEQPAAAA+wYJAE0FBl8SAAAAUgYEAFIHAACfBQMBTQUBwQMAAADZBwIAEgIJABIAAAC8BQX9EwAAAJ8FAwHZBQMAEgABABIABAASAggATQYBwQMAAABNCQGMBgAAAE0ICYUUAAAAUgoFALwICMcVAAAAnwgDALwGBv0TAAAAnwYAAbwGAWcWAAAAnwYCAm8HFwD7CwgATQoLuhgAAACHCQoGvAcHjRkAAACfBwMCMAcEuhoAAACCAQIAGwMpBAAAAEADKgMJAysDLAMtAy4DBwYEAy8DMAMxAzIDMwM0BQYKCwwNDg8CAAAAAAAA4D8DNQM2AzcDDwMNAyUDGAMmAycEAwQFBhMqARgAAAEAAAAAAAACAAAAAAABAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAAAJwADAQABAAABAAABAAEAAQAAAgAAAAAAAQAAAAAAAAAEAAAABAAAAAAAAAAAAAAAAP0AAAEAAAAAAAAAAAAFFAAAAAADAQAAAAAFTQIAjAAAAABNAQLsAQAAAIIBAgACAy0DOABbDQEYAAAAAABcAAAAAAQBAAAAABFNAQDBAAAAAEcBAgAAAACAqQMAAakDAQC7AQMCpAICAAAAEECfAgIBxgIAADACAMEAAAAAvAIBUAMAAACfAgIBggABAAQDCQM5BAAAEEADOgBeOgEYAAABAAAAAAAAAAEAAAEAAAFfAAAAAA8AAAECAGyjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCTQEAMQQAAACkAgEAAAAAQG8EBQC8AgIWAwAAAJ8CAwKkAwcAAABgQE0FAqEIAAAATQQFdgkAAACfAwICpAQHAAAAYEBNBgKhCAAAAE0FBqwKAAAAnwQCAqQFBwAAAGBATQcCvQwAAABNBgemCwAAAJ8FAgKkBgcAAABgQE0JAr0MAAAATQgJ2Q4AAABNBwjlDQAAAJ8GAgKkBwcAAABgQE0JAkAQAAAATQgJXA8AAACfBwICTQgH3REAAACkCQcAAABgQKQMFAAAADBBTQsMJBUAAABNCguREgAAAJ8JAgKkCgcAAABgQKQNFAAAADBBTQwNJBUAAABNCwx7FgAAAJ8KAgKkCwcAAABgQKQOFAAAADBBTQ0OJBUAAABNDA3/FwAAAJ8LAgL/DAQAAAAAADAMDG4YAAAAbw0ZADANDOUaAAAAwA0bABIADAASAAMAEgALABIABAASAAUAEgABABIACQASAAoAEgAGABIACAAwDQzvHAAAAMANHQAwDQxnHgAAAMANHwAwDQxQIAAAAIIMAgAhAzsEAAAAQAM8Az0DPgM/A0AEAABgQANBA0IDQwNEA0UDRgNHA0gDSQNKA0sDTAQAADBBA00DTgNPA1ADUQNSBgcDKgYIAw0GCQM6AwcICQEAARgAAQAAAAAAAQABAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAAABAAAAAAAAAQACAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAAACAAEAAQAAAQAAAAAAAAAAAAAAAEgAAAMAAAcBAAAAAAo8+RQNEcSNQw49fpmF1x+aXOGhBpn+FkEXZoUbmrdQowyjjuPwFvoQ

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players").LocalPlayer
local v2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v2.Std.Maid)
local v_u_4 = require(v2.Std.Interval)
local v_u_5 = require(v2.Game.PlayerUtils)
local v_u_6 = require(v2.Game.Dog.DogConsts)
local v_u_7 = require(v2.Module.UI).CircleAction
local v_u_8 = require(script.Parent.AdoptionStandUI)
local v_u_9 = require(script.Parent.AdoptionSystem)
local v_u_10 = require(script.Parent.AdoptionStandConsts)
local v_u_11 = {}
v_u_11.__index = v_u_11
v_u_11.__ClassName = "AdoptionStand"
function v_u_11.new(p_u_12)
	-- upvalues: (copy) v_u_11, (copy) v_u_3, (copy) v_u_10, (copy) v_u_4, (copy) v_u_5, (copy) v_u_1, (copy) v_u_8, (copy) v_u_9, (copy) v_u_6, (copy) v_u_7
	local v_u_13 = {}
	local v14 = v_u_11
	setmetatable(v_u_13, v14)
	v_u_13._maid = v_u_3.new()
	v_u_13._breedIdValue = p_u_12:WaitForChild(v_u_10.BREED_ID_VALUE_NAME)
	v_u_13._adoptRemote = p_u_12:WaitForChild(v_u_10.ADOPT_REMOTE_NAME)
	local v_u_22 = {
		["Part"] = p_u_12,
		["Timed"] = false,
		["Dist"] = 8,
		["Callback"] = function(_, p15)
			-- upvalues: (copy) v_u_13, (ref) v_u_4, (ref) v_u_5, (ref) v_u_1, (copy) p_u_12, (ref) v_u_8, (ref) v_u_9, (ref) v_u_6
			if p15 then
				local v16 = v_u_13:GetBreedId()
				v_u_13._maid.walkAwayLoop = v_u_4.every(1):Connect(function()
					-- upvalues: (ref) v_u_5, (ref) v_u_1, (ref) p_u_12, (ref) v_u_8
					local v17 = v_u_5.getRootPart(v_u_1)
					if v17 and ((v17.Position - p_u_12.Position).Magnitude > 16 and v_u_8.isOpen()) then
						v_u_8.close()
					end
				end)
				v_u_13._maid.onClickAdopt = v_u_8.getOnClickAdoptSignal():Connect(function()
					-- upvalues: (ref) v_u_8, (ref) v_u_13
					local v18 = v_u_8.getName()
					v_u_13._adoptRemote:FireServer(v18)
					v_u_8.close()
				end)
				v_u_13._maid.onClosed = v_u_8.getOnClosedSignal():Connect(function()
					-- upvalues: (ref) v_u_13
					v_u_13._maid.walkAwayLoop = nil
					v_u_13._maid.onClosed = nil
					v_u_13._maid.onClickAdopt = nil
				end)
				local v19 = v_u_9.doesOwn(v16)
				local v20
				if v19 then
					v20 = nil
				else
					v20 = v_u_6.PRICE[v16]
				end
				v_u_8.setName(v_u_9.getDogName(v16) or "")
				v_u_8.setTitle(v_u_6.TITLE[v16]:upper())
				v_u_8.setImageId(v_u_6.IMAGE_ID[v16])
				v_u_8.setDescriptionTeam(v_u_6.OPT_TEAM[v16])
				v_u_8.setPrice(v20)
				v_u_8.setFirstAdopt(not v19)
				v_u_8.open()
				return true
			end
		end,
		["PreUpdateFun"] = function(p21)
			-- upvalues: (ref) v_u_8
			p21.Enabled = not v_u_8.isOpen()
		end,
		["PreUpdatePeriod"] = 0.5
	}
	v_u_7.Add(v_u_22, p_u_12)
	v_u_13._maid:GiveTask(function()
		-- upvalues: (ref) v_u_7, (copy) p_u_12
		v_u_7.Remove(p_u_12)
	end)
	local function v24()
		-- upvalues: (copy) v_u_13, (copy) v_u_22, (ref) v_u_6
		local v23 = v_u_13:GetBreedId()
		v_u_22.Name = ("Adopt %s"):format(v_u_6.TITLE[v23])
	end
	v_u_13._maid:GiveTask(v_u_13._breedIdValue.Changed:Connect(v24))
	local v25 = v_u_13:GetBreedId()
	v_u_22.Name = ("Adopt %s"):format(v_u_6.TITLE[v25])
	return v_u_13
end
function v_u_11.GetBreedId(p26)
	return p26._breedIdValue.Value
end
function v_u_11.Destroy(p27)
	local v28 = p27._maid
	local v29 = v28 ~= nil
	assert(v29)
	p27._maid = nil
	v28:Destroy()
end
return v_u_11
