-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMaDHNldG1ldGF0YWJsZQNuZXcFX21haWQHX2lzT3Blbg5fYmVmb3JlT3BlbkZ1bglfb25PcGVuZWQIR2l2ZVRhc2sRR2V0T25PcGVuZWRTaWduYWwJX29uQ2xvc2VkEUdldE9uQ2xvc2VkU2lnbmFsBmFzc2VydARGaXJlBE9wZW4FQ2xvc2UGSXNPcGVuB0Rlc3Ryb3kEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUDU3RkBlNpZ25hbARNYWlkBldpbmRvdwtfX0NsYXNzTmFtZQdfX2luZGV4AAgEAAIAAAAW/wADAAAAAAD7AwAAnj0ABAMAAABSAgAApAEBAAAAAECfAQMB+wIBAE0BAu8CAAAAnwEBAjABAMEDAAAAqQEAADABACQEAAAAxgEAADABABcFAAAAggACAAYDAQQAAABAAwIDAwMEAwUACQIBGAAAAQAAAAAAAAIAAAAAAAEAAAIAAAIKAAAAAAQBAQAAABNNAQAUAAAAACsBDQD7AgAATQEC7wEAAACfAQECMAEAFAAAAABNAQDBAgAAAE0DABQAAAAAvAEB/QMAAACfAQMBTQEAFAAAAACCAQIABAMGAwIDAwMHABQIARgAAAABAAAAAAABAAAAAAAAAgAAFQAAAAAEAQEAAAATTQEAIAAAAAArAQ0A+wIAAE0BAu8BAAAAnwEBAjABACAAAAAATQEAwQIAAABNAwAgAAAAALwBAf0DAAAAnwEDAU0BACAAAAAAggECAAQDCQMCAwMDBwAbCgEYAAAAAQAAAAAAAQAAAAAAAAIAABwAAAAABAEAAAAAGU0DACQAAAAAVgIDALsBAgKkAQIAAAAQQJ8BAgGpAQEAMAEAJAAAAABNAQAXAwAAAA4BAwC8AQAXAwAAAJ8BAgFNAQAUBAAAAA4BBQBNAQAUBAAAALwBAd0FAAAAnwECAYIAAQAGAwQDCwQAABBAAwUDBgMMACINARgAAAAAAAAAAQAAAQAAAQAAAgAAAQAAAAACIwAAAAADAQAAAAASTQIAJAAAAAC7AQICpAECAAAAEECfAQIBqQEAADABACQAAAAATQEAIAMAAAAOAQUATQEAIAMAAAC8AQHdBAAAAJ8BAgGCAAEABQMEAwsEAAAQQAMJAwwALA4BGAAAAAAAAAEAAAEAAAEAAAAAAi0AAAAAAgEAAAAAA00BACQAAAAAggECAAEDBAAzDwEYAAAANAAAAAAEAQAAAAAWTQIAwQAAAAC7AQICpAECAAAAEECfAQIBvAEAMQMAAACfAQICDgEDALwBAGMEAAAAnwECAU0BAMEAAAAAxgIAADACAMEAAAAAvAIBUAUAAACfAgIBggABAAYDAwMLBAAAEEADDwMOAxAANhABGAAAAAAAAAEAAAABAAACAAEAAAEAAAE3AAAAAAUAAAECADajAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CAx8HAAAAnwECAqQCBQAAAEBATQQAoQYAAABNAwR2CAAAAJ8CAgL/AwUAAAAAAG8ECQAwBAPlCgAAADADA24LAAAAwAQMABIAAwASAAIAMAQD7w0AAADABA4AEgABADAEAywPAAAAwAQQABIAAQAwBAN1EQAAAMAEEgAwBAMWEwAAAMAEFAAwBANjFQAAAMAEFgAwBAMxFwAAAMAEGAAwBANQGQAAAIIDAgAaAxEEAAAAQAMSAxMDFAQAAEBAAxUDFgMXAxgDGQMaBgADAgYBAwgGAgMKBgMDDQYEAw4GBQMPBgYDEAcAAQIDBAUGAQABGAABAAAAAAABAAAAAAAAAQAAAAAAAAIAAQAAAQABAAAAAAsAAAAHAAAABwAACgAABwAAAwAACQEAAAAABy7uVuZcBmJAHCo8cp8OQnXAOopwiuf1lajzFmmD0jn1tvUX86aCbqk=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.Signal)
local v_u_3 = require(v1.Std.Maid)
local v_u_4 = {
	["__ClassName"] = "Window"
}
v_u_4.__index = v_u_4
function v_u_4.new()
	-- upvalues: (copy) v_u_4, (copy) v_u_3
	local v5 = {}
	local v6 = v_u_4
	setmetatable(v5, v6)
	v5._maid = v_u_3.new()
	v5._isOpen = false
	v5._beforeOpenFun = nil
	return v5
end
function v_u_4.GetOnOpenedSignal(p7)
	-- upvalues: (copy) v_u_2
	if not p7._onOpened then
		p7._onOpened = v_u_2.new()
		p7._maid:GiveTask(p7._onOpened)
	end
	return p7._onOpened
end
function v_u_4.GetOnClosedSignal(p8)
	-- upvalues: (copy) v_u_2
	if not p8._onClosed then
		p8._onClosed = v_u_2.new()
		p8._maid:GiveTask(p8._onClosed)
	end
	return p8._onClosed
end
function v_u_4.Open(p9)
	local v10 = not p9._isOpen
	assert(v10)
	p9._isOpen = true
	if p9._beforeOpenFun then
		p9:_beforeOpenFun()
	end
	if p9._onOpened then
		p9._onOpened:Fire()
	end
end
function v_u_4.Close(p11)
	local v12 = p11._isOpen
	assert(v12)
	p11._isOpen = false
	if p11._onClosed then
		p11._onClosed:Fire()
	end
end
function v_u_4.IsOpen(p13)
	return p13._isOpen
end
function v_u_4.Destroy(p14)
	local v15 = p14._maid
	assert(v15)
	if p14:IsOpen() then
		p14:Close()
	end
	local v16 = p14._maid
	p14._maid = nil
	v16:Destroy()
end
return v_u_4
