-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMPBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplHkZPUkNFRklFTERfRElTQUxMT1dFRF9QQVJUX1RBRw9TVEFSVElOR19IRUFMVEgZSEVBTFRIX1VQREFURV9SRU1PVEVfTkFNRRJEQU1BR0VfUkVNT1RFX05BTUUGUkFESVVTGEZvcmNlZmllbGREaXNhbGxvd2VkUGFydBZGb3JjZWZpZWxkSGVhbHRoVXBkYXRlEEZvcmNlZmllbGREYW1hZ2UAAQUAAAECACKjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CAxgHAAAAnwECAk0CAQAIAAAA4gMOAG8EDwAwBANNCQAAAIwEyAAwBAPiCgAAAG8EEAAwBANlCwAAAG8EEQAwBAPcDAAAAIwECQAwBAPLDQAAAJ8CAgCCAgAAEgMBBAAAAEADAgMDAwQEAABAQAMFAwYDBwMIAwkDCgMLAwwFBQkKCwwNAw0DDgMPAAEAARgAAQAAAAAAAQAAAAAAAAEAAAEAAAEAAAEAAAEAAAEAAPsAAQAAAAAAtnJrP5eU6KyEtgGrg4VhfsrrnjfFH0LyHoy8pP4BSWyM41RxBh4KtQ==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Std.TableUtils).requireValidIndexAndFreeze({
	["FORCEFIELD_DISALLOWED_PART_TAG"] = "ForcefieldDisallowedPart",
	["STARTING_HEALTH"] = 200,
	["HEALTH_UPDATE_REMOTE_NAME"] = "ForcefieldHealthUpdate",
	["DAMAGE_REMOTE_NAME"] = "ForcefieldDamage",
	["RADIUS"] = 9
})
