-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgOiARpSRVFVRVNUX0xBVU5DSF9SRU1PVEVfTkFNRQ5GaW5kRmlyc3RDaGlsZApGaXJlU2VydmVyCFBvc2l0aW9uCU1hZ25pdHVkZQdEZXN0cm95C2dldFJvb3RQYXJ0C0xvY2FsUGxheWVyCUNoYXJhY3RlcgNuZXcbRmx5IGFjcm9zcyB0aGUgbWFwIGZvciAkJXM/EExBVU5DSF9DT1NUX0NBU0gGZm9ybWF0BE1haWQFT25ZZXMHQ29ubmVjdAhHaXZlVGFzawVldmVyeQZhY3Rpb24LR2V0RG9vck9wZW4LU2V0RG9vck9wZW4HRW5hYmxlZA51cGRhdGVEb29yT3BlbhBfaXNMb2NhbFN0YW5kaW5nEHNob3VsZE1vdmVQbGF5ZXIHX3VwZGF0ZQdDaGFuZ2VkDHNldG1ldGF0YWJsZQxUcmFuc3BvcnRKZXQDUmVzBUNsb25lCXdvcmtzcGFjZQZQYXJlbnQLdmlzdWFsTW9kZWwEbWFpZAtPYmplY3RMb2NhbAtQcmltYXJ5UGFydAZMb29wZWQSUm9sbE9mZk1pbkRpc3RhbmNlElJvbGxPZmZNYXhEaXN0YW5jZQZWb2x1bWUJRG9Ob3RQbGF5DmpldEVuZ2luZVNvdW5kDGpldFdpbmRTb3VuZA1SZXF1ZXN0TGF1bmNoBFBhcnQJVmFsaWRSb290BE5hbWUFVGltZWQERGlzdAhDYWxsYmFjawZMYXVuY2gDQWRkE0RPT1JfT1BFTl9BVFRSX05BTUUZR2V0QXR0cmlidXRlQ2hhbmdlZFNpZ25hbAZsYXN0Q0YIcmVhbFJvbGwQb2JzZXJ2ZUF0dHJpYnV0ZRVMQVVOQ0hFRF9BVF9BVFRSX05BTUUUb2JzZXJ2ZU9uZUNoaWxkTmFtZWQUUEFUSF9QT0lOVFNfT0JKX05BTUUNUmF5Y2FzdFBhcmFtcwRFbnVtEVJheWNhc3RGaWx0ZXJUeXBlCVdoaXRlbGlzdApGaWx0ZXJUeXBlD1RyYW5zcG9ydEZsb29ycwtHZXRDaGlsZHJlbhpGaWx0ZXJEZXNjZW5kYW50c0luc3RhbmNlcwdSYXljYXN0Am9zBWNsb2NrDWNhbGN1bGF0ZURpc3QSR2V0V29ybGRQb3NpdGlvbkF0BG1hdGgFY2xhbXANUGxheWJhY2tTcGVlZAZDRnJhbWUKTG9va1ZlY3RvcgRVbml0A0RvdARhY29zCFN0ZXBSb2xsBmxvb2tBdAZBbmdsZXMHSW52ZXJzZQVGb2N1cw1Ub09iamVjdFNwYWNlAXAHUGl2b3RUbxBzZXRGbGlnaHRFbGFwc2VkBFN0b3AGaXBhaXJzCFR1cmJpbmVzDlNwaW5uZXJFbmFibGVkDFNldEF0dHJpYnV0ZQ1nZXRJbm5lck1vZGVsB1R1cmJpbmUKQXR0YWNobWVudBZGaW5kRmlyc3RDaGlsZFdoaWNoSXNBD1BhcnRpY2xlRW1pdHRlcgdzZXRPcGVuEEZyb250TGFuZGluZ0dlYXIPUmVhckxhbmRpbmdHZWFyDF9zdG9wUnVubmluZwtydW5uaW5nTWFpZANvYmoMR2V0QXR0cmlidXRlBVZhbHVlG05PREVfT0ZGU0VUX1NUQVJUX0FUVFJfTkFNRRlOT0RFX09GRlNFVF9FTkRfQVRUUl9OQU1FDW1pc3NpbmcgcG9pbnQGYXNzZXJ0BXRhYmxlBmluc2VydBtubyBwb2ludHMgZm9yIHRyYW5zcG9ydCBqZXQJU2V0UG9pbnRzDVNldE5vZGVPZmZzZXQRQXBwcm94aW1hdGVMZW5ndGgNUlVOV0FZX0xFTkdUSAlUT1BfU1BFRUQJdGltZVVudGlsCnNwZWVkU3RhcnQIc3BlZWRFbmQeY29uc3RyYWluTGFzdFRpbWVUb1JlYWNoVGFyZ2V0KmNhbm5vdCBjb25zdHJhaW4gbGFzdCB0aW1lIHRvIHJlYWNoIHRhcmdldANjYXAERG9vcgtnZXREdXJhdGlvbgR0YXNrBWRlbGF5BFBsYXkQR2V0U2VydmVyVGltZU5vdwlIZWFydGJlYXQEZ2FtZQdQbGF5ZXJzCkdldFNlcnZpY2UKUnVuU2VydmljZQ1DdXJyZW50Q2FtZXJhEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUMQ29uZmlybWF0aW9uBk1vZHVsZQNTdGQKQmFzZU9iamVjdAZCaW5kZXIISW50ZXJ2YWwPUnhJbnN0YW5jZVV0aWxzBUF1ZGlvBEdhbWUKQmV6aWVyUGF0aARDYXJ0CkdyYXBoVXRpbHMCVUkMQ2lyY2xlQWN0aW9uBURvb3IyCURvb3JVdGlscw5DaGFyYWN0ZXJVdGlscxJUcmFuc3BvcnRKZXRDb25zdHMHVmVjdG9yMwdfX2luZGV4CFRBR19OQU1FABUEAAIAAAAL+wAAAPsDAQBNAgMaAAAAALwAAAMBAAAAnwADArwBAGsCAAAAnwECAYIAAQADAwEDAgMDAD8AARgAAAAAAAAAAQAAAUAAAAAAAQABAAAAA6kAAADeAAAAggABAAAAQwABGAAAAUQAAAAABQADAAAAD/sCAAD7BAEATQMEOwAAAAAmAQIDTQABqgEAAACMARAAYAEFAAAAAAD7AQIAvAEBUAIAAACfAQIBggABAAMDBAMFAwYARgABGAAAAAAAAAABAAABAAAAAkcAAAAACgIHAAAHAAABAwUYAkQOAUIA+wMAAE0CAxsAAAAA+wUBAE0EBTEBAAAATQMEaQIAAACfAgICTQMCOwMAAAD7BAIADgQBAIIAAQCpBAEA3gQCAPsFAwBNBAXvBAAAAG8FBQD7CAQATQcIOQYAAAC8BQWNBwAAAJ8FAwCfBAACTQUEdggAAABNBwTcCQAAANkJAAASAgUAEgIEALwHB8cKAAAAnwcDALwFBf0LAAAAnwUAAU0FBHYIAAAA2QcBABICAgC8BQX9CwAAAJ8FAwFNBQR2CAAAAPsIBgBNBwjEDAAAAIwIAQCfBwIC2QkCABIAAwASAAIAEgAEALwHB8cKAAAAnwcDALwFBf0LAAAAnwUAAakFAQCCBQIAggABAA0DBwMIAwkDBAMKAwsDDAMNAw4DDwMQAxEDEgMAAQI1EwEYAAEAAAAAAAAAAAEAAQABAgACAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAEAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAGAAI2AAAAAAQAAgAAAA37AAAAvAAAOQAAAACfAAIC+wEAAFIDAAC8AQEtAQAAAJ8BAwH7AQEAMAAB8AIAAACCAAEAAwMUAxUDFgBbFwEYAAAAAAEAAAAAAQAAAVwAAAAAAgABAAAAD/sAAAC8AADzAAAAAJ8AAgIOAAUA+wAAAKkBAQAwAQBkAQAAAIIAAQD7AAAAqQEAADABAGQBAAAAggABAAIDGAMZAGMAARgAAAAAAAEAAAAAAgAAAAJkAAAAAAIAAQAAAAX7AAAAvAAAAwAAAACfAAIBggABAAEDGgBuAAEYAAAAAAFvAAAAAAIAAQAAAAX7AAAAvAAAAwAAAACfAAIBggABAAEDGgB3AAEYAAAAAAF4AAAAAAcCAQAAABAOAAoATQQAhQAAAADZBgAAEgIAALwEBMcBAAAAnwQDALwCAf0CAAAAnwIAAfsCAAC8AgIDAwAAAJ8CAgGCAAEABAMbAxADEQMaAQd1AAEYAAEAAAAAAAAAAAAEAAAAAXYAAAAADgELAAAA3gH7AgAATQEC7wAAAABSAgAAnwECAvsEAQCePQEEBAAAAFIDAQCkAgIAAAAQQJ8CAwH7BQIATQQFjgMAAABNAwRNBAAAAE0CA44DAAAAvAICOgUAAACfAgICpAMHAAAAYEAwAwIkCAAAADACAcoJAAAATQMBFgoAAABSBQIAvAMD/QsAAACfAwMB+wQDAE0DBNEMAAAATQUBygkAAABNBAWbDQAAAG8FDgDiBhQAqQcBADAHBrUPAAAAjAcgADAHBm8QAAAAjAcAAjAHBioRAAAAjAcAADAHBksSAAAAqQcBADAHBogTAAAAnwMEAjADAboVAAAATQMBFgoAAABNBQG6FQAAALwDA/0LAAAAnwMDAfsEAwBNAwTRDAAAAE0FAcoJAAAATQQFmw0AAABvBRYA4gYUAKkHAQAwBwa1DwAAAIwHQAAwBwZvEAAAAIwHAAIwBwYqEQAAAIwHAAAwBwZLEgAAAKkHAQAwBwaIEwAAAJ8DBAIwAwFzFwAAAE0DARYKAAAATQUBcxcAAAC8AwP9CwAAAJ8DAwGpAwAA2QQAABICBAASAgUAEgED/xICBgASAgcAEgAAABICCABvBxgAvAUCAxkAAACfBQMC4gYgADAFBkQaAAAAMAIGSRsAAABvByEAMAcGuhwAAACpBwAAMAcGcR0AAACMBwcAMAcG4x4AAAAwBAZGHwAAAE0HARYKAAAA+woJAE0JCl8iAAAAUgoGAFILBQCfCQMAvAcH/QsAAACfBwAB2QcBABIAAQASAAYAvAgBOSMAAACfCAICUgsIALwJAS0kAAAAnwkDATAIBvAlAAAATQgBFgoAAAD7DQcATQwN5iYAAAC8CgAWJwAAAJ8KAwJSDAcAvAoKxygAAACfCgMAvAgI/QsAAACfCAABTQgBFgoAAAD7CwgATQoLxCkAAABvCyoAnwoCAtkMAgASAAEAvAoKxygAAACfCgMAvAgI/QsAAACfCAABxggAADAIAakrAAAAjAgAADAIAYAsAAAATQgBFgoAAAD7CwoATQoLgi0AAABSCwAA+w0HAE0MDXouAAAA2Q0DABIAAQCfCgQAvAgI/QsAAACfCAABTQgBFgoAAAD7CwoATQoL6i8AAABSCwAA+w0HAE0MDUcwAAAA2Q0EABIAAQCfCgQAvAgI/QsAAACfCAABwQMAAIIBAgAxAwoDHAQAABBAAx0DHgMfAyAEAABgQAMhAyIDIwMRAyQDJQIAALjbcssBQgMmAycDKAMpAyoFBQ8QERITAysCAACAzHLLAUIDLAMtAwIDLgMvAzADMQMyAzMFBhobHB0eHwM0AzUDFAMVAxYDNgM3AxADEgIAAAAAAADgPwM4AzkDOgM7AzwDPQUDBAUGCB0KARgAAAAAAAEAAAAAAAACAAAAAAAAAAAAAQAAAAEAAgAAAAAAAgAAAQAAAAEBAAAAAAAAAAAAAAAAAAAA/QAABQAAAAAAAAEAAAEAAAABAQAAAAAAAAAAAAAAAAAAAP0AAAUAAAAAAAACAQAAAAAAAAAaAAAAAQEAAQABAAABAAABAAABAAMAAAAAAAAAAAAAAgAAAQAAAQAAAAEAAwAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAACAAAAQAAAgAAAAAAAAAAAAAAAAAAAwABAAABAQAAAQD9/wAADwAeAAAAAAgBAgAAACz7AgAATQECGwAAAAD7BAEATQMEMQEAAABNAgNpAgAAAJ8BAgKkAgUAABAwgJ8CAQKkAwkACBxgwDADAlcKAAAATQMAygsAAABvBQwAvAMDAw0AAACfAwMCvAMDaA4AAACfAwICMAMCfQ8AAAArAQIAqQMAAIIDAgCkAxEAAAAAQU0FATsSAAAAbwYTAFIHAgC8AwPCFAAAAJ8DBQJHAwIAAAAAgKkEAAGpBAEAggQCABUDBwMIAwkDPgMKBAAQMIADPwNAA0EECBxgwANCAyIDQwMCA0QDRQMgBAAAAEEDBAcAAAAAAACgwQAAAAAAAAAAA0YAggEYARgAAAAAAAAAAAABAAABAAAAAQAAAAAAAAAAAAABAQACAAAAAAAAAAABAAAAAIMAAAAAEgELAAAAtAGkAQIAAAQAgJ8BAQL7AwAATQIDtgMAAAD7AwEAUgQAAJ8CAwL7AwIAUgUCALwDA38EAAAAnwMDA/sGAwAmBQYA+wYEAA4GLwD7CQQAJggDCU0HCKoFAAAA+wkFACYIAQnsBgcI+wgGAE0HCLoGAAAAPgoGCIwLAACMDAEATC4AAqQJCwAAKJCAnwkEAlsICQcwCAdLDAAAAPsIBgBNBwi6BgAAAD4LBgiMDAAAjA0BAEwuAAKkCgsAACiQgJ8KBAJbCQoNlQgJBzAIBygOAAAA+wgGAE0HCHMPAAAAPgoGEYwLAACMDAEATC4AAqQJCwAAKJCAnwkEAlsICRAwCAdLDAAAAN4BBQDeAwQA+wwGAE0LDMoTAAAATQoLmxQAAABNCQqFFQAAAE0ICWgWAAAATQoEBxcAAAC8CAgrGAAAAJ8IAwK7AwgCpAcaAABkkICfBwICWwYHEvsHBgCMCgEAYAUDAAoAAACMCQAAZQABAFIJBgCMCwEAYAUDAAsAAABvChsAZQABAG8KHAC8BwcZHQAAAJ8HBAKkCh8AAHhQgfsLBwBSDAQAnwoDAqQLIQAAgFCBjAwAAIwNAABSDgcAnwsEAgkJCgtDCAkD+woGAE0JCmQiAAAADgkyAPsKCABNCQobIwAAAPsMCQBNCwwxJAAAAE0KC2klAAAAnwkCAg4JKAD7CwYATQoLqSYAAAAOCiQA+wwGAE0LDKkmAAAAvAsL2icAAACfCwICCQoIC00MCYUVAAAACQsKDDALCYUVAAAA+wwKAE0LDIUVAAAA+w4KAE0NDssoAAAAvAsLRikAAACfCwMC+wwKAPsRCgBNEBGFFQAAAAkPEAtNEQqRKgAAACYQChEJDg8QvA8L2icAAACfDwICCQ0ODzANDIUVAAAA+wkGADAICakmAAAA+woGAE0JCsoTAAAAUgsIALwJCcIrAAAAnwkDAYIAAQAsA0cDSAQABACAA0kDSgMFAysCmpmZmZmZ6T8CAAAAAAAAWUADSwNMBAAokIADKQKamZmZmZnJPwNNAywCAAAAAAAA8D8CAAAAAAAAOUACAAAAAAAAJEADIgMlA04DTwNQA1EDUgQAZJCAArgehetRuJ4/AnsUrkfheoQ/A1MDVAQAeFCBA1UEAIBQgQMZAwcDCAMJAzgDVgNXA1gDWQNaALwBWwEYAAAAAQAAAAAAAQAAAAABAAIAAQAAAAAAAAIAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAACAQIAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAIAAAABAAAAAAAAAAABAQAAAAEAAAAAAAABAAAAAAIAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAUAAAEAAAAAAAABvQAAAAAEAAIAAAAL+wEAAE0AAdEAAAAA+wMBAE0CA8oBAAAATQECmwIAAABvAgMAnwADAYIAAQAEAyQDIgMlAgAAuC9zywFCAOgBAAEYAAAAAAAAAAAAAAHpAAAAAAIAAQAAAA37AQAATQABugAAAAC8AAD6AQAAAJ8AAgH7AQAATQABcwIAAAC8AAD6AQAAAJ8AAgGCAAEAAwMrA1wDLADxAQABGAAAAAAAAAEAAAAAAAHyAAAAAA0ACAAAAIMBpAACAAAEAICfAAEC+wIAACYBAALGAgAA+wMBAGABAwADAAAAjAIAAGUACQD7BAEA+wUCAEMDBAVgAwMAAQAAAPsCAgBlAAIA+wMBACYCAQOpAwAA+wQBAGAECAABAAAA+wUBAPsGAgBDBAUGtwECAAQAAACpAwABqQMBAPsEAwDxAysABAAAAN4DAwCkBAQAAAAwQPsGBABNBQbKBQAAAG8HBgC8BQUDBwAAAJ8FAwK8BQVoCAAAAJ8FAgCfBAAEUQQZAG8LCQD7DAMAvAkILgoAAACfCQQB+woFAE0JCo4LAAAAUgoIAJ8JAgJvCwwAvAkJAwcAAACfCQMCbwsNALwJCVQOAAAAnwkDAm8LDwC8CQlUDgAAAJ8JAwL7CgMAMAoJ8BAAAABuBOb/AgAAgKkEAAD7BgEAlQUGEWAFCQABAAAA+wcBAPsIAgBDBgcIeAUGEbcBAgAFAAAAqQQAAakEAQD7BQYA8QQaAAUAAADeBAYA+wYFAE0FBi4SAAAA+wcEAE0GB8oFAAAAbwgTALwGBgMHAAAAnwYDAvsHBgCfBQMB+wYFAE0FBi4SAAAA+wcEAE0GB8oFAAAAbwgUALwGBgMHAAAAnwYDAvsHBgCfBQMB+wUHAFIGAgCfBQIB+wcBAFsGBxH7BwIAQwUGB2AFBQABAAAA+wUEALwFBYkVAAAAnwUCAYIAAQAWA0cDSAQABACAA10EAAAwQAMiA14DAgNEA18DYANhA2IDYwNkA2UDFgIAAAAAAAAAQANmA2cDaANpAPcBAAEYAAAAAQABAQAAAQABAAAAAAEAAgADAAAAAAAAAAAAAAEAAAEBAAAAAAAAAAAAAAAAAAEAAAAAAQAAAAABAAAAAQAAAAEAAAABAAD6AAsAAAAAAAAAAAAAAAABAAABAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAwAAAgAAAAAAAQAAAAL4AAAAABwBCwAAAKsC+wIAAE0BAu8AAAAAnwEBAk0CABYBAAAAMAECUgIAAABNAgATAwAAAPsFAQBNBAV6BAAAALwCAhIFAAAAnwIDAk0DABMDAAAA+wYBAE0FBkcGAAAAvAMDAwcAAACfAwMCKwMBAIIAAQBNBAPsCAAAACsEAQCCAAEA+wkBAE0ICSoKAAAAvAYEEgUAAACfBgMCkAUGCfsKAQBNCQqnCwAAALwHBBIFAAAAnwcDApAGBwn7CAIATQcI7wAAAACfBwEC/wgAAAAAAACMCwEAvAwEaAwAAACfDAICHAkMAIwKAQCoCRcAUg4LALwMBAMHAAAAnwwDAkcMAgAAAACAqQ4AAakOAQCBAQ4EDQAAAG8PDQCkDQ8AAADgQJ8NAwFNDww7EAAAAJ40CAQPAAAAUg4IAKQNEwAASBCBnw0DAYsJ6f8cCwgAjAwAALcMAgALAAAAqQoAAakKAQCBAQoEFAAAAG8LFACkCQ8AAADgQJ8JAwFSCwgAvAkH/hUAAACfCQMBUgsFAJUMBha8CQdfFwAAAJ8JBAGMCxAnvAkHpBgAAACfCQMC/woAAAAAAAD7DAEATQsMFRkAAAD7DQEATQwNQhoAAADiDx4AbxAfADAQD0MbAAAAjBAAADAQDw4cAAAAMAwP0B0AAACeNAoEDwAAAFIOCgCkDRMAAEgQgZ8NAwH7DwMATQ4PDCAAAABSDwoAUhALAJ8OAwKBAQ4EIQAAAG8PIQCkDQ8AAADgQJ8NAwHiDx4AbxAfADAQD0MbAAAAMAwPDhwAAAAwDA/QHQAAAJ40CgQPAAAAUg4KAKQNEwAASBCBnw0DAfsPAwBNDg8MIAAAAFIPCgAmEAkLnw4DAoEBDgQhAAAAbw8hAKQNDwAAAOBAnw0DAeIPHgBvEB8AMBAPQxsAAAAwDA8OHAAAAIwQAAAwEA/QHQAAAJ40CgQPAAAAUg4KAKQNEwAASBCBnw0DAfsPAwBNDg8MIAAAAFIPCgBSEAkAnw4DAoEBDgQhAAAAbw8hAKQNDwAAAOBAnw0DAfsOAwBNDQ6KIgAAAFIOCgCfDQIBHBAKAHgPEBaHDgoPTQ0OQxsAAADGDgAApA8lAACQMIKfDwEC2RAAABICAwASAAoAEgAHABIADQASAQ7/EgEP/xIAAAASAgQAEgIFABICBgASAgcATREAyiYAAABvEycAvBERAwcAAACfEQMC+xMIAE0SE+koAAAAUhMRAJ8SAgKpEwAAqRQBAKQVKwAAqJCCWxcNLEMWEhfZFwEAEgIJABIAAACfFQMCUhgVALwWAf0tAAAAnxYDAU0WALouAAAAjBcAADAXFksvAAAATRYAui4AAAC8FhbuMAAAAJ8WAgFNFgBzMQAAAIwXAAAwFxZLLwAAAE0WAHMxAAAAvBYW7jAAAACfFgIB2RgCABIAAAC8FgH9LQAAAJ8WAwGkFyUAAJAwgp8XAQKkGTMAAAAgQ7wZGbc0AAAAnxkCAiYYAhlDFhcY+xoKAE0ZGv01AAAA2RsDABIAFgASABIAEgANABIBE/8SAAAAEgIIABIBFP8SABAAvBkZxzYAAACfGQMAvBcB/S0AAACfFwABwQ4AAIIAAQA3AwoDIwNqA2sDOwNsAz0DAgNtAgAAAAAAAAAAA24DbwNEA3ADcQQAAOBAAwQDcgNzBABIEIEDdAN1AgAAAAAAAPA/A3YDdwN4A3kDegN7A3wFAxscHQIAAAAgX6ACQgN9A34DfwNHA0gEAJAwggMiA4ABA4EBA4IBA4MBBACokIICAAAAAAAA4D8DEQMrAykDhAEDLAMgBAAAIEMDhQEDhgEDEAQLDA0OjQEaARgAAAAAAQAAAAIAAAAAAAAAAQAAAAAAAAABAQIAAQECAAAAAAAAAQAAAAAAAAMAAAABAAEAAAAAAAABAAAAAQAAAAAAAAAAAAEAAAAAAAAA/QUAAAAAAAAAAAAAAAEAAAABAAAAAAEAAAACAAEAAAEAAAEAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAgAAAAAAAAAA/wAABAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAACAAAAAAIBAAABAAAAAAAAAAAAAAAmAAAAAAABAAAAAAIBAgAAAAAAAAADAAAAAgAAAAABAAAAAAEAAAAAAQAAAAABAAAAAAUAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAnAI4AAAAAAwEAAAAABk0BABYAAAAAxgIAADACAVIBAAAAggABAAIDIwNqAJ8CaQEYAAAAAAABIAEAAAAGAwAAAAAM8QECAAEAAACMAQAATQQAgAEAAACQAwQAJgUBAwkEBQJDAwMEMAMAgAEAAACCAwIAAgIAAAAAAAAAAAM5AKICUwEYAAABAgAAAQAAAQABIwEAAAAGAgIAAAAUTQIAygAAAABvBAEAvAICAwIAAACfAgMC+wQAAE0DBC4DAAAAUgQCAFIFAQCfAwMB+wQBAE0DBNEEAAAATQQCmwUAAABvBQYAnwMDAYIAAQAHAyIDgAEDAgNmAyQDJQIAAOADVbfwQQCrAhUBGAAAAAAAAAEAAAAAAAEAAAAAAAABLAEAAAAGAQEAAAANTQIAEwAAAAD7BQAATQQF5gEAAAC8AgISAgAAAJ8CAwIqAgIAAQAAAKkBAAGpAQEAggECAAMDawM2A2wAsAIUARgAAAAAAAAAAAAAAAAAMQEAAAAXAAABAgC8AaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQEAAAAAQG8DBAC8AQEWAwAAAJ8BAwKkAwYAAABQQE0CA0gHAAAApAMBAAAAAEBvBQgAvAMDFgMAAACfAwMCpAQKAAAAkEBNBgNADAAAAE0FBoQLAAAAnwQCAqQFCgAAAJBATQcDoQ0AAABNBgdLDgAAAJ8FAgKkBgoAAACQQE0IA6ENAAAATQcIfw8AAACfBgICpAcKAAAAkEBNCQOhDQAAAE0ICawQAAAAnwcCAqQICgAAAJBATQoDoQ0AAABNCQpSEQAAAJ8IAgKkCQoAAACQQE0LA6ENAAAATQoL0hIAAACfCQICpAoKAAAAkEBNDAO9EwAAAE0LDK8UAAAAnwoCAqQLCgAAAJBATQ4DvRMAAABNDQ5xFQAAAE0MDQoWAAAAnwsCAqQMCgAAAJBATQ4DQAwAAABNDQ5cFwAAAJ8MAgJNDQzdGAAAAKQOCgAAAJBATRADpRkAAABNDxC8GgAAAJ8OAgKkDwoAAACQQE0RA6ENAAAATRARlhsAAACfDwICpBAKAAAAkEBNEgOhDQAAAE0REnYcAAAAnxACAqQRCgAAAJBATRMDjh0AAABNEhMqHgAAAJ8RAgJMNgACpBIhAACA8IGfEgEC/xMEAAAAAAAwExNuIgAAAJ49EwUFAAAAUhUTAFIWBQCkFCQAAAAwQp8UAwHAFCUAEgAFABIAEwASAAMAEgAJABIADwASAAAAEgAEABIAEQASAAcAEgANABIACAAwFBPvIAAAAMAUJgASAA8AEgAAADAUE/MnAAAAwBQoABIAEAASABEAEgAKABIACwASABIAEgAPABIAAAASAAIAEgAOABIACQASAAEAMBQTAykAAADAFCoAMBQTiSsAAADAFCwAMBQTGS0AAADAFC4AEgAOABIACQAwFBMtLwAAAMAUMAASABEAMBQTOTEAAABNFAbvIAAAAE0VEbQyAAAAUhYTAJ8UAwCCFAAAMwOHAQQAAABAA4gBA4kBA4oBAyAEAABQQAOLAQOMAQONAQQAAJBAA44BA48BA5ABA5EBA5IBA5MBA5QBA5UBA5YBA5cBA5gBA5kBA5oBA5sBA5wBA50BA54BAw4DHQOfAQOgAQMKBACA8IEDoQEDHAQAADBCBgkGCgMYBg8DGgYQA2kGEQNTBhIDFQYTAxQDogEHCQoPEBESEwEAAQUAAQAAAAAAAQAAAAAAAQAAAAEAAAAAAAEAAAAAAAABAPoAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAA/AEAAAAAAAABAAAAAAAAAAABAAAAAAAAAQABAAAAAAD7AQAAAAAAAAEAAAAAAAACAAAAAAAAAgAAAAMAAQABAPUAAAAAAgAAAAAAAAAAAAAAAABlAAAAAAsAAAAAAAAAjgAAAAAAkgAAAwAACQAAAAAFAAAABAAAAAAAAAEAAAAGAAAABAAAAAUAAAALAAAAcgAAAAAUNuPrG1Y3xaQEJ4GPdZzwLAFniG6NZPTKXI0fmdAGgfQbKzW/dIDYfA==

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players")
local v_u_2 = game:GetService("RunService")
local v_u_3 = workspace.CurrentCamera
local v_u_4 = game:GetService("ReplicatedStorage")
local v_u_5 = require(v_u_4.Module.Confirmation)
local v_u_6 = require(v_u_4.Std.BaseObject)
local v7 = require(v_u_4.Std.Binder)
local v_u_8 = require(v_u_4.Std.Interval)
local v_u_9 = require(v_u_4.Std.RxInstanceUtils)
local v_u_10 = require(v_u_4.Std.Audio)
local v_u_11 = require(v_u_4.Game.BezierPath)
local v_u_12 = require(v_u_4.Game.Cart.GraphUtils)
local v_u_13 = require(v_u_4.Module.UI).CircleAction
local v_u_14 = require(v_u_4.Door2.DoorUtils)
local v_u_15 = require(v_u_4.Std.CharacterUtils)
local v_u_16 = require(v_u_4.Std.Maid)
local v_u_17 = require(v_u_4.TransportJet.TransportJetConsts)
local v_u_18 = Vector3.new()
local v_u_19 = {}
v_u_19.__index = v_u_19
setmetatable(v_u_19, v_u_6)
function v_u_19.new(p_u_20)
	-- upvalues: (copy) v_u_6, (copy) v_u_19, (copy) v_u_4, (copy) v_u_10, (copy) v_u_15, (copy) v_u_1, (copy) v_u_5, (copy) v_u_17, (copy) v_u_8, (copy) v_u_13, (copy) v_u_9
	local v_u_21 = v_u_6.new(p_u_20)
	local v22 = v_u_19
	setmetatable(v_u_21, v22)
	local v23 = v_u_4.TransportJet.Res.TransportJet:Clone()
	v23.Parent = workspace
	v_u_21.visualModel = v23
	v_u_21.maid:GiveTask(v23)
	v_u_21.jetEngineSound = v_u_10.ObjectLocal(v_u_21.visualModel.PrimaryPart, 9553468279, {
		["Looped"] = true,
		["RollOffMinDistance"] = 32,
		["RollOffMaxDistance"] = 512,
		["Volume"] = 0,
		["DoNotPlay"] = true
	})
	v_u_21.maid:GiveTask(v_u_21.jetEngineSound)
	v_u_21.jetWindSound = v_u_10.ObjectLocal(v_u_21.visualModel.PrimaryPart, 9553467792, {
		["Looped"] = true,
		["RollOffMinDistance"] = 64,
		["RollOffMaxDistance"] = 512,
		["Volume"] = 0,
		["DoNotPlay"] = true
	})
	v_u_21.maid:GiveTask(v_u_21.jetWindSound)
	local v_u_24 = false
	local function v29(_, p25)
		-- upvalues: (ref) v_u_15, (ref) v_u_1, (ref) v_u_24, (ref) v_u_5, (ref) v_u_17, (copy) p_u_20, (ref) v_u_8
		if p25 then
			local v_u_26 = v_u_15.getRootPart(v_u_1.LocalPlayer.Character)
			local v_u_27 = v_u_26.Position
			if not v_u_24 then
				v_u_24 = true
				local v_u_28 = v_u_5.new(("Fly across the map for $%s?"):format(v_u_17.LAUNCH_COST_CASH))
				v_u_28.Maid:GiveTask(v_u_28.OnYes:Connect(function()
					-- upvalues: (ref) p_u_20, (ref) v_u_17
					p_u_20:FindFirstChild(v_u_17.REQUEST_LAUNCH_REMOTE_NAME):FireServer()
				end))
				v_u_28.Maid:GiveTask(function()
					-- upvalues: (ref) v_u_24
					v_u_24 = false
				end)
				v_u_28.Maid:GiveTask(v_u_8.every(1):Connect(function()
					-- upvalues: (copy) v_u_27, (copy) v_u_26, (copy) v_u_28
					if (v_u_27 - v_u_26.Position).Magnitude > 16 then
						v_u_28:Destroy()
					end
				end))
				return true
			end
		end
	end
	local v30 = v23:FindFirstChild("RequestLaunch")
	local v_u_31 = {
		["Part"] = v30,
		["ValidRoot"] = v23,
		["Name"] = "Launch",
		["Timed"] = false,
		["Dist"] = 7,
		["Callback"] = v29
	}
	v_u_21.maid:GiveTask(v_u_13.Add(v_u_31, v30))
	local v32 = v_u_21:GetDoorOpen()
	v_u_21:SetDoorOpen(v32)
	v_u_31.Enabled = v32
	v_u_21.maid:GiveTask(p_u_20:GetAttributeChangedSignal(v_u_17.DOOR_OPEN_ATTR_NAME):Connect(function()
		-- upvalues: (copy) v_u_21, (copy) v_u_31
		local v33 = v_u_21:GetDoorOpen()
		v_u_21:SetDoorOpen(v33)
		v_u_31.Enabled = v33
	end))
	v_u_21.maid:GiveTask(v_u_8.every(0.5):Connect(function()
		-- upvalues: (copy) v_u_21
		if v_u_21:_isLocalStanding() then
			v_u_21.shouldMovePlayer = true
		else
			v_u_21.shouldMovePlayer = false
		end
	end))
	v_u_21.lastCF = nil
	v_u_21.realRoll = 0
	v_u_21.maid:GiveTask(v_u_9.observeAttribute(p_u_20, v_u_17.LAUNCHED_AT_ATTR_NAME, function()
		-- upvalues: (copy) v_u_21
		v_u_21:_update()
	end))
	v_u_21.maid:GiveTask(v_u_9.observeOneChildNamed(p_u_20, v_u_17.PATH_POINTS_OBJ_NAME, function(p34, p35)
		-- upvalues: (copy) v_u_21
		if p34 then
			p35:GiveTask(p34.Changed:Connect(function()
				-- upvalues: (ref) v_u_21
				v_u_21:_update()
			end))
		end
		v_u_21:_update()
	end))
	return v_u_21
end
function v_u_19._isLocalStanding(p36)
	-- upvalues: (copy) v_u_15, (copy) v_u_1
	local v37 = v_u_15.getRootPart(v_u_1.LocalPlayer.Character)
	local v38 = RaycastParams.new()
	v38.FilterType = Enum.RaycastFilterType.Whitelist
	v38.FilterDescendantsInstances = p36.visualModel:FindFirstChild("TransportFloors"):GetChildren()
	if v37 then
		return workspace:Raycast(v37.Position, Vector3.new(0, -20, 0), v38) ~= nil
	else
		return false
	end
end
function v_u_19._update(p_u_39)
	-- upvalues: (copy) v_u_16, (copy) v_u_17, (copy) v_u_11, (copy) v_u_12, (copy) v_u_18, (copy) v_u_15, (copy) v_u_1, (copy) v_u_3, (copy) v_u_14, (copy) v_u_10, (copy) v_u_2
	local v40 = v_u_16.new()
	p_u_39.maid.runningMaid = v40
	local v41 = p_u_39.obj:GetAttribute(v_u_17.LAUNCHED_AT_ATTR_NAME)
	local v42 = p_u_39.obj:FindFirstChild(v_u_17.PATH_POINTS_OBJ_NAME)
	if v42 then
		local v43 = v42.Value
		if v43 then
			local v44 = v43:GetAttribute(v_u_17.NODE_OFFSET_START_ATTR_NAME) or 0
			local v45 = v43:GetAttribute(v_u_17.NODE_OFFSET_END_ATTR_NAME) or 0
			local v_u_46 = v_u_11.new()
			local v47 = {}
			for v48 = 1, #v43:GetChildren() do
				local v49 = v43:FindFirstChild(v48)
				local v50 = v49 ~= nil
				assert(v50, "missing point")
				local v51 = v49.Position
				table.insert(v47, v51)
			end
			local v52 = #v47 > 0
			assert(v52, "no points for transport jet")
			v_u_46:SetPoints(v47)
			v_u_46:SetNodeOffset(v44, v45 + 1)
			local v53 = v_u_46:ApproximateLength(10000)
			local v_u_54 = {}
			local v55 = v_u_17.RUNWAY_LENGTH
			local v56 = v_u_17.TOP_SPEED
			table.insert(v_u_54, {
				["timeUntil"] = 10000000000,
				["speedStart"] = 0,
				["speedEnd"] = v56
			})
			local v57 = v_u_12.constrainLastTimeToReachTarget(v_u_54, v55)
			assert(v57, "cannot constrain last time to reach target")
			table.insert(v_u_54, {
				["timeUntil"] = 10000000000,
				["speedStart"] = v56,
				["speedEnd"] = v56
			})
			local v58 = v_u_12.constrainLastTimeToReachTarget(v_u_54, v53 - v55)
			assert(v58, "cannot constrain last time to reach target")
			table.insert(v_u_54, {
				["timeUntil"] = 10000000000,
				["speedStart"] = v56,
				["speedEnd"] = 0
			})
			local v59 = v_u_12.constrainLastTimeToReachTarget(v_u_54, v53)
			assert(v59, "cannot constrain last time to reach target")
			v_u_12.cap(v_u_54)
			local v_u_60 = v_u_54[#v_u_54 - 1].timeUntil
			local v_u_61 = nil
			local v_u_62 = os.clock()
			local function v_u_82(p63)
				-- upvalues: (ref) v_u_12, (copy) v_u_54, (copy) v_u_46, (copy) v_u_60, (ref) v_u_61, (ref) v_u_62, (copy) p_u_39, (ref) v_u_18, (ref) v_u_15, (ref) v_u_1, (ref) v_u_3
				local v64 = os.clock()
				local v65, v66 = v_u_46:GetWorldPositionAt((v_u_12.calculateDist(v_u_54, p63)))
				local v67 = v_u_60 - p63
				if v_u_61 then
					local v68 = (v65 - v_u_61).Magnitude / (v64 - v_u_62)
					local v69 = p_u_39.jetEngineSound
					local v70 = v68 / 100
					v69.Volume = math.clamp(v70, 0, 1) * 0.8
					local v71 = p_u_39.jetEngineSound
					local v72 = v68 / 100
					v71.PlaybackSpeed = math.clamp(v72, 0, 1) * 0.2 + 0.8
					local v73 = p_u_39.jetWindSound
					local v74 = v68 / 25
					v73.Volume = math.clamp(v74, 0, 1) * 1
				end
				v_u_62 = v64
				v_u_61 = v65
				local v75 = p_u_39.visualModel.PrimaryPart.CFrame.LookVector:Dot(v66.Unit)
				local v76 = math.acos(v75) * 10
				local v77 = p_u_39:StepRoll(v67 < 1 and 0 or v76, v67 < 1 and 0.03 or 0.01)
				local v78 = CFrame.lookAt(v_u_18, v66) * CFrame.Angles(0, 0, v77) + v65
				if p_u_39.shouldMovePlayer then
					local v79 = v_u_15.getRootPart(v_u_1.LocalPlayer.Character)
					if v79 and p_u_39.lastCF then
						local v80 = v78 * p_u_39.lastCF:Inverse()
						v79.CFrame = v80 * v79.CFrame
						local v81 = v_u_3.CFrame:ToObjectSpace(v_u_3.Focus)
						v_u_3.CFrame = v_u_3.CFrame * v81 * (v80 - v80.p) * v81:Inverse()
					end
				end
				p_u_39.lastCF = v78
				p_u_39.visualModel:PivotTo(v78)
			end
			local v83 = p_u_39.visualModel:FindFirstChild("Door")
			local v_u_84 = v_u_14.getDuration(v83)
			local v_u_85 = false
			local v_u_86 = true
			v40:GiveTask((task.delay(v_u_84 + v_u_60 * 0.5, function()
				-- upvalues: (ref) v_u_10, (copy) p_u_39
				v_u_10.ObjectLocal(p_u_39.visualModel.PrimaryPart, 9553470967)
			end)))
			p_u_39.jetEngineSound.Volume = 0
			p_u_39.jetEngineSound:Play()
			p_u_39.jetWindSound.Volume = 0
			p_u_39.jetWindSound:Play()
			v40:GiveTask(function()
				-- upvalues: (copy) p_u_39
				p_u_39.jetEngineSound:Stop()
				p_u_39.jetWindSound:Stop()
			end)
			local v_u_87 = os.clock() + (v41 - workspace:GetServerTimeNow())
			v40:GiveTask(v_u_2.Heartbeat:Connect(function()
				-- upvalues: (copy) v_u_87, (copy) v_u_84, (copy) v_u_60, (ref) v_u_85, (copy) p_u_39, (ref) v_u_14, (ref) v_u_86, (copy) v_u_82
				local v88 = os.clock() - v_u_87
				local v89
				if v88 < v_u_84 then
					v89 = 0
				elseif v_u_84 + v_u_60 < v88 then
					v89 = v_u_60
				else
					v89 = v88 - v_u_84
				end
				local v90
				if v_u_84 < v88 then
					v90 = v88 < v_u_84 + v_u_60
				else
					v90 = false
				end
				if v90 ~= v_u_85 then
					v_u_85 = v90
					for _, v91 in ipairs(p_u_39.visualModel:FindFirstChild("Turbines"):GetChildren()) do
						v91:SetAttribute("SpinnerEnabled", v_u_85)
						v_u_14.getInnerModel(v91):FindFirstChild("Turbine"):FindFirstChildWhichIsA("Attachment"):FindFirstChildWhichIsA("ParticleEmitter").Enabled = v_u_85
					end
				end
				local v92
				if v_u_84 + 2 < v88 then
					v92 = v88 < v_u_84 + v_u_60 - 2
				else
					v92 = false
				end
				if v92 ~= v_u_86 then
					v_u_86 = v92
					v_u_14.setOpen(p_u_39.visualModel:FindFirstChild("FrontLandingGear"), v_u_86)
					v_u_14.setOpen(p_u_39.visualModel:FindFirstChild("RearLandingGear"), v_u_86)
				end
				v_u_82(v89)
				if v_u_84 * 2 + v_u_60 < v88 then
					p_u_39:_stopRunning()
				end
			end))
		end
	else
		return
	end
end
function v_u_19._stopRunning(p93)
	p93.maid.runningMaid = nil
end
function v_u_19.StepRoll(p94, p95, p96)
	local v97 = p95 ~= p95 and 0 or p95
	local v98 = p94.realRoll or 0
	local v99 = v98 + (v97 - v98) * p96
	p94.realRoll = v99
	return v99
end
function v_u_19.SetDoorOpen(p100, p101)
	-- upvalues: (copy) v_u_14, (copy) v_u_10
	local v102 = p100.visualModel:FindFirstChild("Door")
	v_u_14.setOpen(v102, p101)
	v_u_10.ObjectLocal(v102.PrimaryPart, 4487204926)
end
function v_u_19.GetDoorOpen(p103)
	-- upvalues: (copy) v_u_17
	return p103.obj:GetAttribute(v_u_17.DOOR_OPEN_ATTR_NAME) == true
end
return v7.new(v_u_17.TAG_NAME, v_u_19)
