-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNVFVZJRVdfQ0xBTl9SRU1PVEVfTkFNRQ5GaW5kRmlyc3RDaGlsZApGaXJlU2VydmVyBHR5cGUFdmFsdWUPc2V0R3JvdXBWaXNpYmxlCGRpc3BhdGNoEWF0dGVtcHRWaWV3Q2xhbklkDnNldEN1cnJFbmFibGVkC0xvY2FsUGxheWVyCUNoYXJhY3RlcghnZXRWYWx1ZQtQcmltYXJ5UGFydAhQb3NpdGlvbglNYWduaXR1ZGUlVU5SRU5ERVJfTEVBREVSQk9BUkRfRElTUExBWV9ESVNUQU5DRR1MRUFERVJCT0FSRF9ESVNQTEFZX1RZUEVfRU5VTQ1DcmV3c0luU2VydmVyGGNyZXdzSW5TZXJ2ZXJEaXNwbGF5SW5mbwtMZWFkZXJib2FyZA9sZWFkZXJib2FyZEluZm8FZXJyb3IVSW52YWxpZCBkaXNwbGF5VHlwZTogCHRvc3RyaW5nB3VubW91bnQQR2V0VmFsdWVGcm9tRW51bQNuZXcMc2V0bWV0YXRhYmxlEHlpZWxkRm9yUHJvcGVydHkNY3JlYXRlQmluZGluZwRtYWlkBWV2ZXJ5B0Nvbm5lY3QIR2l2ZVRhc2sDb2JqBFNpemUBWAFZB2Nvbm5lY3QKU3VyZmFjZUd1aQ5aSW5kZXhCZWhhdmlvcgxSZXNldE9uU3Bhd24HQWRvcm5lZQRGYWNlClNpemluZ01vZGUNUGl4ZWxzUGVyU3R1ZAdFbmFibGVkBEVudW0HU2libGluZwhOb3JtYWxJZAVGcm9udBRTdXJmYWNlR3VpU2l6aW5nTW9kZQdEaXNwbGF5C2Rpc3BsYXlUeXBlC2FzcGVjdFJhdGlvDWNyZWF0ZUVsZW1lbnQNU3RvcmVQcm92aWRlcgVzdG9yZQVtb3VudAlQbGF5ZXJHdWkQQ3Jld3NJblNlcnZlckd1aQRnYW1lB1BsYXllcnMKR2V0U2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQdyZXF1aXJlBnNjcmlwdAZQYXJlbnQaUGVyc2lzdGVudENyZXdCYXR0bGVDb25zdHMZcGVyc2lzdGVudENyZXdCYXR0bGVTdG9yZQ5QZXJzaXN0ZW50Q3JldxRQZXJzaXN0ZW50Q3Jld0NvbnN0cxNwZXJzaXN0ZW50Q3Jld1N0b3JlFFBlcnNpc3RlbnRDcmV3QmF0dGxlAlVJD0NyZXdMZWFkZXJib2FyZAVSb2FjdApSb2FjdFJvZHV4A1N0ZApCYXNlT2JqZWN0CEludGVydmFsD1J4SW5zdGFuY2VVdGlscxZDcmV3c1N1cmZhY2VHdWlEaXNwbGF5CUNsYXNzTmFtZQdfX2luZGV4AAcFAQMAAAAX+wEAAPsEAQBNAwTrAAAAALwBAQMBAAAAnwEDAlIDAAC8AQFrAgAAAJ8BAwH7AQIA4gMFAG8EBgAwBANxAwAAAKkEAQAwBAPMBAAAALwBAUwHAAAAnwEDAYIAAQAIAwEDAgMDAwQDBQUCAwQDBgMHABwIARgAAAAAAAAAAAAAAAEAAQAAAQAA/gAABB0AAAAAAwECAAAAB/sBAADxAAQAAQAAAPsBAQBSAgAAnwECAYIAAQAAACkJARgAAAABAAACKgAAAAAKAAUAAAA3+wIAAE0BAjEAAAAATQABaQEAAAD7AQEAvAEB0wIAAACfAQIC2QIAABIAAQASAgIAKwAGACoBBAAAAAAA+wMCAKkEAACfAwIBggABAE0DAJsDAAAAKwMGACoBBAAAAAAA+wQCAKkFAACfBAIBggABAE0GAzsEAAAA+wkDAE0ICZsDAAAATQcIOwQAAAAmBQYHTQQFqgUAAAD7BgQATQUGpQYAAAB9BQcABAAAACoBBAAAAAAA+wQCAKkFAACfBAIBggABACoBBAABAAAA+wQCAKkFAQCfBAIBggABAAcDCgMLAwwDDQMOAw8DEAEBJgABGAAAAAAAAQAAAAEAAAX8AAEAAAUCAAH3AAEAAAoDAAAAAAAAAAAAAQAAAADxAAEAABHuAAEAABQnAAAAAAgCAgAAACXGAgAA+wMAAPsGAQBNBQYMAAAAAE0EBfgBAAAAmgMEAAQAAABNAgBfAgAAAGUAFQD7AwAA+wYBAE0FBgwAAAAATQQF8AMAAACaAwQABAAAAE0CAMsEAAAAZQAKAKQDBgAAAFBAbwUHAPsHAAC7PwcCpAYJAAAAgECfBgICcwQFBp8DAgHiAwoAMAIDywQAAACCAwIACwMRAxIDEwMUAxUDFgQAAFBAAxcDGAQAAIBABQEEAEIAARgAAQAAAAAAAAABAAABAAAAAAAAAAEAAAIAAAAAAAAAAAACAQAAQwAAAAACAAIAAAAG+wEAAE0AARIAAAAA+wEBAJ8AAgGCAAEAAQMZAGkAARgAAAAAAAFqAAAAABACDgAAALgB+wMAAE0CAwwAAAAAUgQBALwCAssBAAAAnwIDAisCCgCkAgMAAAAgQG8EBAC7PwEDUgYBAKQFBgAAAFBAnwUCAnMDBAWfAgIB+wMBAE0CA+8HAAAAUgMAAJ8CAgL7BQIAnj0CBAUAAABSBAIApAMJAAAAgECfAwMB+wQDAE0DBA8KAAAAUgQAAG8FCwCfAwMBwAMMABICBAASAgUAEgIGAPsFBwBNBAUxDQAAAKkFAQCfBAIDTQYCFg4AAAD7CQgATQgJxA8AAACMCQEAnwgCAtkKAQASAgkAEgAEABIABQASAAAAEgIAALwICMcQAAAAnwgDALwGBv0RAAAAnwYAAU0KAhMSAAAATQkKmwsAAABNCAkvEwAAAE0HCHkUAAAATQsCExIAAABNCgubCwAAAE0JCi8TAAAATQgJeBUAAADsBgcI+wgKAE0HCOcWAAAA2QgCABIAAQASAgAAnwcCAvsICwCfBwICxggAAE0MAhMSAAAATQsMmwsAAABNCgsvEwAAAE0JCngVAAAAjAoeAGAJAwAKAAAAjAhQAGUAAQCMCBQA+wkMAG8KFwDiCx8ApAwiACFgAMIwDAt7GAAAAKkMAAAwDAukGQAAAE0NAhMSAAAATQwNmwsAAAAwDAsUGgAAAKQMJQAkjADCMAwLBRsAAACkDCcAHZgAwjAMC2kcAAAAMAgLfx0AAAAwBAvwHgAAAOIMKQD7DQwAUg4HAOIPLQAwAQ+/KgAAADAGD4krAAAAMAMPCCwAAACfDQMCMA0MPCgAAACfCQQC+wsHAE0KC8ouAAAA+wwKAE0LDLovAAAA4gwxAPsNDQAwDQx+MAAAAP8NAAABAAAAUg4JAMUNDgIBAAAAnwoEAlIJCgD7CwcATQoL5DIAAABSCwkA+w4JAE0NDjEzAAAATQwNmTQAAABvDTUAnwoEAk0LAhYOAAAA2Q0DABICBwASAAoAvAsL/REAAACfCwMBggICADYDEQMaAxYEAAAgQAMXAxgEAABQQAMbAxwEAACAQAMdAw0GAAMeAx8DIAMhAyIDIwMkAyUDJgMnAygDKQMqAysDLAMtAy4DLwUHGBkaGxwdHgMwAzEEIWAAwgMyAzMEJIwAwgM0BB2YAMIDNQUBKAM2AzcDCAUDKissAzgDOQM6BQEwAzsDCgM8Az0EAAIDBBQbARgAAAAAAAAAAAEAAAAAAAAAAAACAAAAAAEAAAAAAAABAAAAAAACAAAACAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAGwAAAAAAAAAAAAAAAAAAAAABAAAAAAAADAACAQAAAAAAAAAAAAABAAICAAABAAAAAQAAAQAAAAAAAQAAAAEAAAABAAEAAQEAAAEAAQABAP0AAPcPAAAAAAAAAQAAAQAAAAD+AAMAAAAAAAAAAAAAAQAAAAAAAAADFQAAAAAPAAABAgBwowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBAQAAAABAbwMEALwBARYDAAAAnwEDAqQCBgAAAFBApAUIAAAAcEBNBAUkCQAAAE0DBOcKAAAAnwICAqQDBgAAAFBApAYIAAAAcEBNBQYkCQAAAE0EBSQLAAAAnwMCAqQEBgAAAFBATQYBxQwAAABNBQarDQAAAJ8EAgKkBQYAAABQQE0HAcUMAAAATQYHUg4AAACfBQICpAYGAAAAUEBNCQFYDwAAAE0ICVwQAAAATQcIJREAAACfBgICpAcGAAAAUEBNCAEhEgAAAJ8HAgKkCAYAAABQQE0JAS0TAAAAnwgCAqQJBgAAAFBATQsBoRQAAABNCgtLFQAAAJ8JAgKkCgYAAABQQE0MAaEUAAAATQsMrBYAAACfCgICpAsGAAAAUEBNDQGhFAAAAE0MDVIXAAAAnwsCAk0MB8oYAAAA/w0DAAAAAABvDhkAMA4N2xoAAAAwDQ1uGwAAAMAOHAASAAIAEgAJABIADQASAAsAEgABABIABAASAAUAEgAHABIACgASAAAAEgAIABIABgASAAwAEgADADAODe8dAAAAgg0CAB4DPgQAAABAAz8DQANBA0IEAABQQANDBAAAcEADRANFA0YDRwNIA0kDSgNLA0wDTQNOA08DUANRA1IDOANTA1QDVQYFAxsBBQEAARgAAQAAAAAAAQAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAAABAAAAAAEAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQACAAEAAAEAAgAAAAAAAAAAAAAAAAAAAABbAQAAAAAGnIkvvUtH7AeuTUUpRX6DNGFem7fJF4G5GzXlG3GPCezlwqsgR09oVA==

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players")
local v_u_2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(script.Parent.PersistentCrewBattleConsts)
local v_u_4 = require(script.Parent.persistentCrewBattleStore)
local v_u_5 = require(v_u_2.PersistentCrew.PersistentCrewConsts)
local v_u_6 = require(v_u_2.PersistentCrew.persistentCrewStore)
local v_u_7 = require(v_u_2.PersistentCrewBattle.UI.CrewLeaderboard)
local v_u_8 = require(v_u_2.Roact)
local v_u_9 = require(v_u_2.RoactRodux)
local v_u_10 = require(v_u_2.Std.BaseObject)
local v_u_11 = require(v_u_2.Std.Interval)
local v_u_12 = require(v_u_2.Std.RxInstanceUtils)
local v_u_13 = v_u_8.createElement
local v_u_14 = {
	["ClassName"] = "CrewsSurfaceGuiDisplay"
}
v_u_14.__index = v_u_14
function v_u_14.new(p_u_15, p_u_16)
	-- upvalues: (copy) v_u_3, (copy) v_u_10, (copy) v_u_14, (copy) v_u_12, (copy) v_u_2, (copy) v_u_5, (copy) v_u_6, (copy) v_u_8, (copy) v_u_11, (copy) v_u_1, (copy) v_u_9, (copy) v_u_7, (copy) v_u_13, (copy) v_u_4
	if not v_u_3.LEADERBOARD_DISPLAY_TYPE_ENUM:GetValueFromEnum(p_u_16) then
		error("Invalid displayType: " .. tostring(p_u_16))
	end
	local v17 = v_u_10.new(p_u_15)
	local v18 = v_u_14
	setmetatable(v17, v18)
	v_u_12.yieldForProperty(p_u_15, "PrimaryPart")
	local function v20(p19)
		-- upvalues: (ref) v_u_2, (ref) v_u_5, (ref) v_u_6
		v_u_2:FindFirstChild(v_u_5.VIEW_CLAN_REMOTE_NAME):FireServer(p19)
		v_u_6:dispatch({
			["type"] = "setGroupVisible",
			["value"] = true
		})
	end
	local v_u_21, v_u_22 = v_u_8.createBinding(true)
	v17.maid:GiveTask(v_u_11.every(1):Connect(function()
		-- upvalues: (ref) v_u_1, (copy) v_u_21, (copy) v_u_22, (copy) p_u_15, (ref) v_u_3
		local v23 = v_u_1.LocalPlayer.Character
		local v24 = v_u_21:getValue()
		if v23 then
			local v25 = v23.PrimaryPart
			if v25 then
				if (v25.Position - p_u_15.PrimaryPart.Position).Magnitude >= v_u_3.UNRENDER_LEADERBOARD_DISPLAY_DISTANCE then
					if v24 ~= false then
						v_u_22(false)
					end
				elseif v24 ~= true then
					v_u_22(true)
				end
			else
				if v24 ~= false then
					v_u_22(false)
				end
				return
			end
		else
			if v24 ~= false then
				v_u_22(false)
			end
			return
		end
	end))
	local v26 = v17.obj.PrimaryPart.Size.X / v17.obj.PrimaryPart.Size.Y
	local v30 = v_u_9.connect(function(p27, _)
		-- upvalues: (copy) p_u_16, (ref) v_u_3
		local v28 = nil
		if p_u_16 == v_u_3.LEADERBOARD_DISPLAY_TYPE_ENUM.CrewsInServer then
			v28 = p27.crewsInServerDisplayInfo
		elseif p_u_16 == v_u_3.LEADERBOARD_DISPLAY_TYPE_ENUM.Leaderboard then
			v28 = p27.leaderboardInfo
		else
			local v29 = p_u_16
			error("Invalid displayType: " .. tostring(v29))
		end
		return {
			["leaderboardInfo"] = v28
		}
	end)(v_u_7)
	local v31 = v17.obj.PrimaryPart.Size.Y < 30 and 80 or 20
	local v32 = v_u_13("SurfaceGui", {
		["ZIndexBehavior"] = Enum.ZIndexBehavior.Sibling,
		["ResetOnSpawn"] = false,
		["Adornee"] = v17.obj.PrimaryPart,
		["Face"] = Enum.NormalId.Front,
		["SizingMode"] = Enum.SurfaceGuiSizingMode.PixelsPerStud,
		["PixelsPerStud"] = v31,
		["Enabled"] = v_u_21
	}, {
		["Display"] = v_u_13(v30, {
			["displayType"] = p_u_16,
			["aspectRatio"] = v26,
			["attemptViewClanId"] = v20
		})
	})
	local v33 = {
		["store"] = v_u_4
	}
	local v34 = v_u_8.createElement(v_u_9.StoreProvider, v33, { v32 })
	local v_u_35 = v_u_8.mount(v34, v_u_1.LocalPlayer.PlayerGui, "CrewsInServerGui")
	v17.maid:GiveTask(function()
		-- upvalues: (ref) v_u_8, (copy) v_u_35
		v_u_8.unmount(v_u_35)
	end)
	return v17
end
return v_u_14
