-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMFCXN0dWRzVG9LbQlrbVRvU3R1ZHMJc3R1ZHNUb01pCW1pVG9TdHVkcwRzVG9IAAYDAQAAAAADPgIAAT4BAgCCAQIAAgIAAAAAAECPQAIAAAAAAAAIQAAHAQEYAAAACAAAAAADAQAAAAADWwIAAVsBAgCCAQIAAgIAAAAAAECPQAIAAAAAAAAIQAAKAgEYAAAACwAAAAAEAQEAAAAH+wMAAE0CAykBAAAAUgMAAJ8CAgJbAQIAggECAAICodl1b0Xi4z8DAQANAwEYAAAAAAAAAA4AAAAAAwEBAAAABvsCAABNAQICAAAAAD4CAAGfAQIAggEAAAIDAgKh2XVvReLjPwAQBAEYAAAAAAAAEQAAAAADAQAAAAADWwIAAFsBAgCCAQIAAQIAAAAAAABOQAATBQEYAAAAFAAAAAACAAABAgAVowAAAP8ABAAAAAAAwAEAADABACkBAAAAwAECADABAAIDAAAAwAEEABIAAAAwAQDxBQAAAMABBgASAAAAMAEAkQcAAADAAQgAMAEAUQkAAACCAAIACgYAAwEGAQMCBgIDAwYDAwQGBAMFBQABAgMEAQABGAADAAMAAAMAAAMAAAADAAAAAwAAAwEAAAAABWNfChCenEjrUZtghOa0xmN4r9BNC363sdjNCEWHtRnIAehwTVWIgvQ=

-- Decompiled by Krnl

local v_u_6 = {
	["studsToKm"] = function(p1)
		return p1 / 3 / 1000
	end,
	["kmToStuds"] = function(p2)
		return p2 * 3 * 1000
	end,
	["studsToMi"] = function(p3)
		-- upvalues: (copy) v_u_6
		return v_u_6.studsToKm(p3) * 0.621371
	end,
	["miToStuds"] = function(p4)
		-- upvalues: (copy) v_u_6
		return v_u_6.kmToStuds(p4 / 0.621371)
	end,
	["sToH"] = function(p5)
		return p5 * 60 * 60
	end
}
return v_u_6
