-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMnBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlD0d1blN5c3RlbUNvbnN0cwRHYW1lCkl0ZW1TeXN0ZW0IUmVzb3VyY2UIU2V0dGluZ3MDSGlwBVNjb3BlD1JpZ2h0RWxib3dBbmdsZRJSaWdodFdyaXN0Um90YXRpb24HU3ByaW5ncwpJdGVtT2Zmc2V0DEl0ZW1Sb3RhdGlvbgxOZWNrUm90YXRpb24HVmVjdG9yMwNuZXcGQ0ZyYW1lBk1vdGlvbg9mbGludGxvY2tfc2hvb3QVZmxpbnRsb2NrX3JlbG9hZF9vcGVuFmZsaW50bG9ja19yZWxvYWRfY2xvc2UQZmxpbnRsb2NrX2hhbW1lcgVTb3VuZAdNYWdTaXplEUNhbVNoYWtlTWFnbml0dWRlC0J1bGxldFNwZWVkDkZpcmVBdXRvTW9iaWxlCEZpcmVBdXRvCEZpcmVGcmVxClJlbG9hZFRpbWUGRGFtYWdlBVByaWNlBkltYWdlcwlGbGludGxvY2sHSW1hZ2VJZAlFcXVpcFRpbWUAAQgAAAECAHyjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNBAC9BwAAAE0DBPAIAAAATQIDSQYAAACfAQICpAIFAAAAQEBNBABiCQAAAE0DBMoKAAAAnwICAv8DBQAAAAAA4gQPAOIFEQDiBhUAbwcWADAHBoASAAAAbwcXADAHBuUTAAAATDYAAqQHGgAAZICBnwcBAjAHBo0UAAAAMAYFmBAAAAAwBQS9CwAAAOIFEQDiBhUAbwcbADAHBoASAAAAbwccADAHBuUTAAAATDYAAqQHGgAAZICBnwcBAjAHBo0UAAAAMAYFmBAAAAAwBQT0DAAAAIwFAAAwBQSgDQAAAKQFHgAAZNCBnwUBAjAFBA4OAAAAMAQDlx8AAADiBCQAbwUlADAFBPogAAAAbwUmADAFBJkhAAAAbwUnADAFBDwiAAAAbwUoADAFBKgjAAAAMAQDbikAAACMBAEAMAQD9yoAAACMBJYAMAQDoysAAACMBIQDMAQDpSwAAACpBAEAMAQDPS0AAACpBAAAMAQDTS4AAACMBAQAMAQDQC8AAACMBAQAMAQDvDAAAACMBC0AMAQDDzEAAACMBBAnMAQDJDIAAABNBQLjMwAAAE0EBU80AAAAMAQDljUAAABvBDYAMAQD1zcAAACCAwIAOAMBBAAAAEADAgMDAwQEAABAQAMFAwYDBwMIAwkDCgMLAwwDDQUECwwNDgMOBQEQAw8DEAMRBQMSExQHAACAPzMzsz8AAADAAAAAAAcAAAAAzczMvQAAAAAAAAAAAxIDEwQAZICBBwAAgD8zM7M/zcwswAAAAAAHzcxMPs3MzL4AAAAAAAAAAAMUBABk0IEDFQMWAxcDGAMZBQQgISIjAgAAGJa4BA9CAgAAUJdk4/FBAgAAkK1k4/FBAgAAULtk4/FBAxoDGwMcAx0DHgMfAyADIQMiAyMDJAMlAyYCAAAAAAAA4D8DJwABAAEYAAEAAAAAAAEAAAAAAAAAAAEAAAAAAAACAAEBAQEAAAEAAAEAAAAAAP0A/wAHAQEAAAEAAAEAAAAAAP0A/wAIAAACAAAAAO4AFAEAAAEAAAEAAAEAAPwABgAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAAAAAQAAAgEAAAAAAPQBGaFm/LfixsVzNZuJEqHIKSHWyEd61zndoKipfjyt82mu7XVtkkM=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
require(v1.Game.ItemSystem.GunSystemConsts)
local v2 = require(v1.Resource.Settings)
local v3 = {}
local v4 = {}
local v5 = {
	["Springs"] = {
		["ItemOffset"] = Vector3.new(1, 1.4, -2),
		["ItemRotation"] = Vector3.new(0, -0.1, 0),
		["NeckRotation"] = Vector3.new()
	}
}
v4.Hip = v5
local v6 = {
	["Springs"] = {
		["ItemOffset"] = Vector3.new(1, 1.4, -2.7),
		["ItemRotation"] = Vector3.new(0.2, -0.4, 0),
		["NeckRotation"] = Vector3.new()
	}
}
v4.Scope = v6
v4.RightElbowAngle = 0
v4.RightWristRotation = CFrame.new()
v3.Motion = v4
v3.Sound = {
	["flintlock_shoot"] = 16652899011,
	["flintlock_reload_open"] = 4801841525,
	["flintlock_reload_close"] = 4801841881,
	["flintlock_hammer"] = 4801842101
}
v3.MagSize = 1
v3.CamShakeMagnitude = 150
v3.BulletSpeed = 900
v3.FireAutoMobile = true
v3.FireAuto = false
v3.FireFreq = 4
v3.ReloadTime = 4
v3.Damage = 45
v3.Price = 10000
v3.ImageId = v2.Images.Flintlock
v3.EquipTime = 0.5
return v3
