-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMsBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlDUdhbWVwYXNzVXRpbHMER2FtZQhHYW1lcGFzcwhSZXNvdXJjZQhTZXR0aW5ncwNIaXAFU2NvcGUOTGVmdEVsYm93QW5nbGUPUmlnaHRFbGJvd0FuZ2xlEUxlZnRXcmlzdFJvdGF0aW9uElJpZ2h0V3Jpc3RSb3RhdGlvbgdTcHJpbmdzCkl0ZW1PZmZzZXQMSXRlbVJvdGF0aW9uDE5lY2tSb3RhdGlvbgdWZWN0b3IzA25ldwZDRnJhbWUGQW5nbGVzBk1vdGlvbh9ndW5fc2VtaV9hdXRvX3JpZmxlX2RyeV9maXJlXzAxG2d1bl9zZW1pX2F1dG9fcmlmbGVfc2hvdF8wMSRndW5fc2VtaV9hdXRvX3JpZmxlX21hZ2F6aW5lX2xvYWRfMDEmZ3VuX3NlbWlfYXV0b19yaWZsZV9tYWdhemluZV91bmxvYWRfMDEFU291bmQHTWFnU2l6ZRFDYW1TaGFrZU1hZ25pdHVkZQtCdWxsZXRTcGVlZAhGaXJlQXV0bwhGaXJlRnJlcQpSZWxvYWRUaW1lBkRhbWFnZQVQcmljZQZJbWFnZXMFUmlmbGUHSW1hZ2VJZAxFbnVtR2FtZXBhc3MEU1dBVARCT1NTElJlcXVpcmVBbnlHYW1lcGFzcwABCQAAAQIAjAGjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNBAC9BwAAAE0DBL0IAAAATQIDPgYAAACfAQICpAIFAAAAQEBNBABiCQAAAE0DBMoKAAAAnwICAv8DBQAAAAAA4gQRAOIFEwDiBhcAbwcYADAHBoAUAAAAbwcZADAHBuUVAAAATDYAAqQHHAAAbKCBnwcBAjAHBo0WAAAAMAYFmBIAAAAwBQS9CwAAAOIFEwDiBhcAbwcdADAHBoAUAAAAbwceADAHBuUVAAAAbwcfADAHBo0WAAAAMAYFmBIAAAAwBQT0DAAAAIwFAAAwBQTSDQAAAIwFAAAwBQSgDgAAAKQFIgAAhACCjAYAAG8HIwCMCAAAnwUEAjAFBIUPAAAApAUkAABsAIKfBQECMAUEDhAAAAAwBAOXJQAAAOIEKgBvBSsAMAUE4yYAAABvBSwAMAUE7ScAAABvBS0AMAUE/ygAAABvBS4AMAUEHikAAAAwBANuLwAAAIwEHgAwBAP3MAAAAIwECgAwBAOjMQAAAIwE3AUwBAOlMgAAAKkEAQAwBANNMwAAAIwEDQAwBANANAAAAG8ENQAwBAO8NgAAAIwEBQAwBAMPNwAAAIwEAAAwBAMkOAAAAE0FAuM5AAAATQQFrToAAAAwBAOWOwAAAP8EAAACAAAATQYBjTwAAABNBQYyPQAAAE0HAY08AAAATQYHFT4AAADFBAUDAQAAADAEAy8/AAAAggMCAEADAQQAAABAAwIDAwMEBAAAQEADBQMGAwcDCAMJAwoDCwMMAw0DDgMPBQYLDA0ODxADEAUBEgMRAxIDEwUDFBUWB5qZGT8AAIA/zczMvwAAAAAHmpkZvpqZGT8AAAAAAAAAAAMUAxUEAGyggQfNzMw+ZmamPzMz878AAAAAB5qZGT4zMzM/AAAAAAAAAAAHAAAAAAAAAADNzMy+AAAAAAMWAxcEAIQAggJQaesxxyj+PwQAbACCAxgDGQMaAxsDHAUEJicoKQIAAIBW/prfQQIAAOjKuAQPQgIAAMCN/prfQQIAAEDI/prfQQMdAx4DHwMgAyEDIgIAAAAAAAD4PwMjAyQDJQMmAycDKAMpAyoDKwMsAAEAARgAAQAAAAAAAQAAAAAAAAAAAQAAAAAAAAIAAQEBAQAAAQAAAQAAAAAA/QD/AAcBAQAAAQAAAQAA/QD/AAgAAAEAAAIAAAAAAAAAAQAAAADsABYBAAABAAACAAABAAD7AAcAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAAAAAEAAQAAAAEAAAAAAP4ABQEAAAAAAO5fL7ek2Wf93JtFI3tRw3MvY516V3FyG/f+vyaa3Tk/6MoIXCe9S9g=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v2 = require(v1.Game.Gamepass.GamepassUtils)
local v3 = require(v1.Resource.Settings)
local v4 = {}
local v5 = {}
local v6 = {
	["Springs"] = {
		["ItemOffset"] = Vector3.new(0.6, 1, -1.6),
		["ItemRotation"] = Vector3.new(-0.15, 0.6, 0),
		["NeckRotation"] = Vector3.new()
	}
}
v5.Hip = v6
local v7 = {
	["Springs"] = {
		["ItemOffset"] = Vector3.new(0.4, 1.3, -1.9),
		["ItemRotation"] = Vector3.new(0.15, 0.7, 0),
		["NeckRotation"] = Vector3.new(0, 0, -0.4)
	}
}
v5.Scope = v7
v5.LeftElbowAngle = 0
v5.RightElbowAngle = 0
v5.LeftWristRotation = CFrame.Angles(0, 1.8849555921538759, 0)
v5.RightWristRotation = CFrame.new()
v4.Motion = v5
v4.Sound = {
	["gun_semi_auto_rifle_dry_fire_01"] = 2121005402,
	["gun_semi_auto_rifle_shot_01"] = 16652900701,
	["gun_semi_auto_rifle_magazine_load_01"] = 2121005623,
	["gun_semi_auto_rifle_magazine_unload_01"] = 2121005857
}
v4.MagSize = 30
v4.CamShakeMagnitude = 10
v4.BulletSpeed = 1500
v4.FireAuto = true
v4.FireFreq = 13
v4.ReloadTime = 1.5
v4.Damage = 5
v4.Price = 0
v4.ImageId = v3.Images.Rifle
v4.RequireAnyGamepass = { v2.EnumGamepass.SWAT, v2.EnumGamepass.BOSS }
return v4
