-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMqBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQpSdW5TZXJ2aWNlB3JlcXVpcmUIUmVzb3VyY2UIU2V0dGluZ3MDSGlwBVNjb3BlDkxlZnRFbGJvd0FuZ2xlD1JpZ2h0RWxib3dBbmdsZRFMZWZ0V3Jpc3RSb3RhdGlvbhJSaWdodFdyaXN0Um90YXRpb24HU3ByaW5ncwpJdGVtT2Zmc2V0DEl0ZW1Sb3RhdGlvbgxOZWNrUm90YXRpb24HVmVjdG9yMwNuZXcGQ0ZyYW1lBk1vdGlvbhV3ZWFwb25fY2Fubm9uX3Nob3RfMDQWZ3VuX3Bpc3RvbF9kcnlfZmlyZV8wMQVTb3VuZAdNYWdTaXplC0FtbW9DdXJyZW50CEZpcmVBdXRvCElzU3R1ZGlvCEZpcmVGcmVxClJlbG9hZFRpbWULUm9ja2V0U3BlZWQGRGFtYWdlBlJhZGl1cwVQcmljZQtSb2NrZXRQcmljZQZJbWFnZXMOUm9ja2V0TGF1bmNoZXIHSW1hZ2VJZBFDdXN0b21TaG9vdFJlbW90ZRJDdXN0b21EYW1hZ2VSZW1vdGUJRXF1aXBUaW1lD0VxdWlwVGltZUZvcmNlZAABCAAAAQIAigGjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIGAAAAUEBNBABiBwAAAE0DBMoIAAAAnwICAv8DBgAAAAAA4gQPAOIFEQDiBhUAbwcWADAHBoASAAAAbwcXADAHBuUTAAAATDYAAqQHGgAAZICBnwcBAjAHBo0UAAAAMAYFmBAAAAAwBQS9CQAAAOIFEQDiBhUAbwcWADAHBoASAAAAbwcXADAHBuUTAAAAbwcbADAHBo0UAAAAMAYFmBAAAAAwBQT0CgAAAIwFAAAwBQTSCwAAAIwFAAAwBQSgDAAAAKQFHQAAZMCBnwUBAjAFBIUNAAAApAUdAABkwIGfBQECMAUEDg4AAAAwBAOXHgAAAOIEIQBvBSIAMAUEZx8AAABvBSMAMAUE5iAAAAAwBANuJAAAAIwECgAwBAP3JQAAAIwEAAAwBAO5JgAAAKkEAAAwBANNJwAAALwFAQooAAAAnwUCAg4FAgCMBAMAZQABAG8EKQAwBANAKgAAAG8EKwAwBAO8LAAAAIwEyAAwBAPiLQAAAIwEUAAwBAMPLgAAAIwEGAAwBANxLwAAAG8EMAAwBAMkMQAAAIwE6AMwBANtMgAAAE0FAuMzAAAATQQF0zQAAAAwBAOWNQAAAKkEAQAwBAMyNgAAAKkEAQAwBAN2NwAAAIwEAQAwBAPXOAAAAKkEAQAwBAN8OQAAAIIDAgA6AwEEAAAAQAMCAwMDBAMFBAAAUEADBgMHAwgDCQMKAwsDDAMNBQYJCgsMDQ4DDgUBEAMPAxADEQUDEhMUB83MTD8zM7M/zcxMvwAAAAAHAAAAANsPST8AAAAAAAAAAAMSAxMEAGSAgQcAAAAAAAAAAAAAAAAAAAAAAxQEAGTAgQMVAxYDFwUCHyACAABgGbht4EECAACAVI7l30EDGAMZAxoDGwMcApqZmZmZmdk/Ax0CAAAAAAAA+D8DHgMfAyADIQIAAAAAAIjjQAMiAyMDJAMlAyYDJwMoAykDKgABAAEYAAEAAAAAAAEAAAAAAAEAAAAAAAACAAEBAQEAAAEAAAEAAAAAAP0A/wAHAQEAAAEAAAEAAP0A/wAIAAABAAACAAAAAAEAAAAA7AAWAQAAAQAA/gAEAAABAAABAAABAAAAAAAAAAABAAABAAABAAABAAABAAABAAABAAAAAAABAAABAAABAAABAAACAQAAAAAAC/jyVDpqoNA5PJjAdCsB1vUqSAfCXIOj1mCvSy6PJ++8QVptvWz+Vg==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v2 = game:GetService("RunService")
local v3 = require(v1.Resource.Settings)
local v4 = {
	["Motion"] = {
		["Hip"] = {
			["Springs"] = {
				["ItemOffset"] = Vector3.new(0.8, 1.4, -0.8),
				["ItemRotation"] = Vector3.new(0, 0.7853982, 0),
				["NeckRotation"] = Vector3.new()
			}
		},
		["Scope"] = {
			["Springs"] = {
				["ItemOffset"] = Vector3.new(0.8, 1.4, -0.8),
				["ItemRotation"] = Vector3.new(0, 0.7853982, 0),
				["NeckRotation"] = Vector3.new(0, 0, 0)
			}
		},
		["LeftElbowAngle"] = 0,
		["RightElbowAngle"] = 0,
		["LeftWristRotation"] = CFrame.new(),
		["RightWristRotation"] = CFrame.new()
	},
	["Sound"] = {
		["weapon_cannon_shot_04"] = 2205008075,
		["gun_pistol_dry_fire_01"] = 2140551506
	},
	["MagSize"] = 10,
	["AmmoCurrent"] = 0,
	["FireAuto"] = false,
	["FireFreq"] = v2:IsStudio() and 3 or 0.4,
	["ReloadTime"] = 1.5,
	["RocketSpeed"] = 200,
	["Damage"] = 80,
	["Radius"] = 24,
	["Price"] = 40000,
	["RocketPrice"] = 1000,
	["ImageId"] = v3.Images.RocketLauncher,
	["CustomShootRemote"] = true,
	["CustomDamageRemote"] = true,
	["EquipTime"] = 1,
	["EquipTimeForced"] = true
}
return v4
