-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMuBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlCFJlc291cmNlCFNldHRpbmdzA0hpcAVTY29wZRFMZWZ0V3Jpc3RSb3RhdGlvbhJSaWdodFdyaXN0Um90YXRpb24OTGVmdEVsYm93QW5nbGUPUmlnaHRFbGJvd0FuZ2xlB1NwcmluZ3MKSXRlbU9mZnNldAxJdGVtUm90YXRpb24MTmVja1JvdGF0aW9uClB1bXBPZmZzZXQIUHVtcERhbXAIUHVtcEZyZXEGQ0ZyYW1lBkFuZ2xlcwNuZXcGTW90aW9uE2d1bl9zaG90Z3VuX2NvY2tfMDETZ3VuX3Nob3RndW5fc2hvdF8wMRdndW5fc2hvdGd1bl9kcnlfZmlyZV8wMQVTb3VuZAdNYWdTaXplEUNhbVNoYWtlTWFnbml0dWRlC0J1bGxldFNwZWVkCEZpcmVBdXRvDkZpcmVBdXRvTW9iaWxlCEZpcmVGcmVxFElnbm9yZVZlcmlmeUZpcmVGcmVxDkJ1bGxldHNQZXJTaG90DEJ1bGxldFNwcmVhZARQdW1wD0xlZnRBcm1SZWxhdGl2ZQpSZWxvYWRUaW1lEUxvY2FsUmVsb2FkT2Zmc2V0BkRhbWFnZQVQcmljZQZJbWFnZXMHU2hvdGd1bgdJbWFnZUlkCUVxdWlwVGltZQABCAAAAQIAjQGjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwBiBgAAAE0CA8oHAAAAnwECAv8CBgAAAAAA4gMOAOIEEADiBRcAbwYYADAGBYARAAAAbwYZADAGBeUSAAAAbwYaADAGBY0TAAAAbwYaADAGBRUUAAAAbwYbADAGBTwVAAAAjAYUADAGBUAWAAAAMAUEmA8AAAAwBAO9CAAAAOIEEADiBRwAbwYdADAGBYARAAAAbwYeADAGBeUSAAAAbwYfADAGBY0TAAAAMAUEmA8AAAAwBAP0CQAAAKQEIgAAhACCjAUAAG8GIwCMBwAAnwQEAjAEA4UKAAAApAQlAACQAIKfBAECMAQDDgsAAABvBCYAMAQD0gwAAACMBAAAMAQDoA0AAAAwAwKXJwAAAOIDKwBvBCwAMAQDsCgAAABvBC0AMAQDRykAAABvBC4AMAQDySoAAAAwAwJuLwAAAIwDBQAwAwL3MAAAAIwDUAAwAwKjMQAAAIwDtgMwAwKlMgAAAKkDAAAwAwJNMwAAAKkDAQAwAwI9NAAAAG8DNQAwAwJANgAAAKkDAQAwAwJsNwAAAIwDFAAwAwIjOAAAAG8DOQAwAwKqOgAAAG8DOwAwAwI1PAAAAG8DPQAwAwK8PgAAAG8DPwAwAwLpQAAAAIwDAwAwAwIPQQAAAIwDAAAwAwIkQgAAAE0EAeNDAAAATQME4UQAAAAwAwKWRQAAAG8DRgAwAwLXRwAAAIICAgBIAwEEAAAAQAMCAwMDBAQAAEBAAwUDBgMHAwgDCQMKAwsDDAUGCAkKCwwNAw0FAQ8DDgMPAxADEQMSAxMFBhESExQVFgeamRk/AACAP5qZmb8AAAAAB5qZGb5mZmY/AAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAALNzMzMzMzsPwUDERITB83MzD5mZqY/zczMvwAAAAAHmpkZPgAAgD8AAAAAAAAAAAcAAAAAAAAAAM3MDL8AAAAAAxQDFQQAhACCAsRSyYfJlwFAAxYEAJAAggIYLURU+yHpPwMXAxgDGQMaBQMoKSoCAABAoSuk30ECAAAAdy+k30ECAAAAASyk30EDGwMcAx0DHgMfAyACq6qqqqqq+j8DIQMiAyMCMzMzMzMzwz8DJAMlAyYChutRuB6F+z8DJwKamZmZmZn5PwMoAykDKgMrAywDLQJmZmZmZmbWPwMuAAEAARgAAQAAAAAAAQAAAAAAAAEAAQEBAQAAAQAAAQAAAgAAAQAAAQAA+QD/AAsBAQAAAQAAAQAA/QD/AAcAAAAAAAAAAQAAAAABAAABAADqABgBAAABAAABAAD9AAYAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAAAAAEAAAIBAAAAAACRifWd8rzMG6NNnwlXVTS1nIdySUXoqUO2FpHmnKWFTmNZo3QSKRWc

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v2 = require(v1.Resource.Settings)
local v3 = {}
local v4 = {}
local v5 = {
	["Springs"] = {
		["ItemOffset"] = Vector3.new(0.6, 1, -1.2),
		["ItemRotation"] = Vector3.new(-0.15, 0.9, 0),
		["NeckRotation"] = Vector3.new(0, 0, 0),
		["PumpOffset"] = Vector3.new(0, 0, 0),
		["PumpDamp"] = 0.9,
		["PumpFreq"] = 20
	}
}
v4.Hip = v5
local v6 = {
	["Springs"] = {
		["ItemOffset"] = Vector3.new(0.4, 1.3, -1.6),
		["ItemRotation"] = Vector3.new(0.15, 1, 0),
		["NeckRotation"] = Vector3.new(0, 0, -0.55)
	}
}
v4.Scope = v6
v4.LeftWristRotation = CFrame.Angles(0, 2.199114857512855, 0)
v4.RightWristRotation = CFrame.new()
v4.LeftElbowAngle = 0.7853981633974483
v4.RightElbowAngle = 0
v3.Motion = v4
v3.Sound = {
	["gun_shotgun_cock_01"] = 2123411077,
	["gun_shotgun_shot_01"] = 2123415004,
	["gun_shotgun_dry_fire_01"] = 2123411460
}
v3.MagSize = 5
v3.CamShakeMagnitude = 80
v3.BulletSpeed = 950
v3.FireAuto = false
v3.FireAutoMobile = true
v3.FireFreq = 1.6666666666666667
v3.IgnoreVerifyFireFreq = true
v3.BulletsPerShot = 20
v3.BulletSpread = 0.15
v3.LeftArmRelative = "Pump"
v3.ReloadTime = 1.7200000000000002
v3.LocalReloadOffset = 1.6
v3.Damage = 3
v3.Price = 0
v3.ImageId = v2.Images.Shotgun
v3.EquipTime = 0.35
return v3
