-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMRA0hpcBJSaWdodFdyaXN0Um90YXRpb24RTGVmdFdyaXN0Um90YXRpb24HU3ByaW5ncwpJdGVtT2Zmc2V0DEl0ZW1Sb3RhdGlvbgxOZWNrUm90YXRpb24NV2Fpc3RSb3RhdGlvbgdWZWN0b3IzA25ldwZDRnJhbWUGTW90aW9uCnRhc2VyX2J1enoFU291bmQKUmVsb2FkVGltZQ1SZWxvYWRUaW1lSGl0BVJhbmdlAAEFAAABAgA7owAAAP8ABAAAAAAA4gEDAOICBQDiAwoAbwQLADAEA4AGAAAATDYAAqQEDgAANMCAnwQBAjAEA+UHAAAATDYAAqQEDgAANMCAnwQBAjAEA40IAAAATDYAAqQEDgAANMCAnwQBAjAEA18JAAAAMAMCmAQAAAAwAgG9AAAAAKQCEAAANPCAnwIBAjACAQ4BAAAApAIQAAA08ICfAgECMAIBhQIAAAAwAQCXEQAAAOIBEwBvAhQAMAIBLhIAAAAwAQBuFQAAAIwBBAAwAQC8FgAAAIwBCgAwAQAGFwAAAIwBVQAwAQAGGAAAAIIAAgAZAwEDAgMDBQMAAQIDBAUBBAMFAwYDBwMIBQQGBwgJBwAAgD/NzEw/AADAvwAAAAADCQMKBAA0wIADCwQANPCAAwwDDQUBEgIAAIBq+3/GQQMOAw8DEAMRAAEAARgAAQABAQEBAAABAAAAAAABAAAAAAABAAAAAAD8AP8ACQAAAAABAAAAAPUADQEAAP8AAwAAAQAAAQAAAgEAAAAAAGwRnSUtyHfjXtX3saFhIFGfMEjooHj+Za2Q3sJcBK5/P7KMVIwyvZA=

-- Decompiled by Krnl

local v1 = {}
local v2 = {}
local v3 = {
	["Springs"] = {
		["ItemOffset"] = Vector3.new(1, 0.8, -1.5),
		["ItemRotation"] = Vector3.new(),
		["NeckRotation"] = Vector3.new(),
		["WaistRotation"] = Vector3.new()
	}
}
v2.Hip = v3
v2.RightWristRotation = CFrame.new()
v2.LeftWristRotation = CFrame.new()
v1.Motion = v2
v1.Sound = {
	["taser_buzz"] = 754972373
}
v1.ReloadTime = 4
v1.ReloadTimeHit = 10
v1.Range = 85
return v1
