-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMcCFJlc291cmNlBkJyYWtlcwROYW1lDkZpbmRGaXJzdENoaWxkBWVycm9yEU5vIEJyYWtlcyBuYW1lZDogBUNsb25lBkNlbnRlcgtQcmltYXJ5UGFydAZDRnJhbWUDbmV3BkFuZ2xlcxRTZXRQcmltYXJ5UGFydENGcmFtZQtHZXRJbnN0YW5jZQJvcwVjbG9jawRtYXRoA3NpbgZVcGRhdGUEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlBVByaWNlBkFtb3VudAdMZXZlbCAxB0xldmVsIDIHTGV2ZWwgMwVJdGVtcwADCgEBAAAAKPsDAABNAgNiAAAAAE0BAgcBAAAATQMAugIAAAC8AQEDAwAAAJ8BAwIrAQcApAIFAAAAQEBvBAYATQUAugIAAABzAwQFnwICAbwCAToHAAAAnwICAlIBAgBNAgHqCAAAADACAZsJAAAApAUMAAAsoICfBQECpAYOAAA0oIBvBw8AjAgAAIwJAACfBgQCCQQFBrwCAWYQAAAAnwIDAYIBAgARAwEDAgMDAwQDBQQAAEBAAwYDBwMIAwkDCgMLBAAsoIADDAQANKCAAhgtRFT7Ifk/Aw0AFA4BGAAAAAAAAAAAAAABAQAAAAAAAAIAAAABAAAAAQAAAAAAAAAAAAAAAAEVAAAAAA0CAAAAACKkAgIAAAQAgJ8CAQI+AwIDIQQDBKQHBwAAGFCAjAgAAFIJBACMCgAAnwcEAqQIBwAAGFCAuxgDA1IMAwCkCwwAACyggJ8LAgJbCgsJeAkKCIwKAACMCwAAnwgEAgkGBwikBw4AADRQgIwIAACMCQAAjAoKAJ8HBAIJBQYHMAUAhQUAAACCAAEADwMPAxAEAAQAgAIAAAAAAAAAQAIYLURU+yEZQAMKAwwEABhQgAKamZmZmZnJPwIAAAAAAADgPwMRAxIEACyggAMLBAA0UIAAHxMBGAAAAAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEgAAAAAAYAAAECADSjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMC/wEAAAMAAADiAgcAbwMIADADAroEAAAAjAMAADADAiQFAAAAjAMAADADAisGAAAA4gMHAG8ECQAwBAO6BAAAAIwE0AcwBAMkBQAAAG8ECgAwBAMrBgAAAOIEBwBvBQsAMAUEugQAAACMBZQRMAUEJAUAAACMBQUAMAUEKwYAAADFAQIEAQAAAMACDAASAAAAwAMNAOIEEQAwAQQ4DgAAADACBFEPAAAAMAMEJhAAAACCBAIAEgMUBAAAAEADFQMWAwMDFwMYBQMEBQYDGQMaAgAAAAAAAARAAxsGAAYBAxwDDgMTBQMODxACAAEBAAEYAAEAAAAAAAEAAQEAAAEAAAEAAAIBAAABAAABAAACAQAAAQAAAQAAAAADAAsGAQABAAEAAAEAAAAAAlJ1/qz7YLb8YLGUOARrLfteix0TjIaTUTpqyrw/auqJNLdEIh01Qqw=

-- Decompiled by Krnl

local v_u_1 = game:GetService("ReplicatedStorage")
return {
	["Items"] = {
		{
			["Name"] = "Level 1",
			["Price"] = 0,
			["Amount"] = 0
		},
		{
			["Name"] = "Level 2",
			["Price"] = 2000,
			["Amount"] = 2.5
		},
		{
			["Name"] = "Level 3",
			["Price"] = 4500,
			["Amount"] = 5
		}
	},
	["GetInstance"] = function(p2)
		-- upvalues: (copy) v_u_1
		local v3 = v_u_1.Resource.Brakes:FindFirstChild(p2.Name)
		if not v3 then
			error("No Brakes named: " .. p2.Name)
		end
		local v4 = v3:Clone()
		v4.PrimaryPart = v4.Center
		v4:SetPrimaryPartCFrame(CFrame.new() * CFrame.Angles(1.5707963267948966, 0, 0))
		return v4
	end,
	["Update"] = function(p5, _)
		local v6 = os.clock() / 2
		local v7 = v6 % 6.283185307179586
		p5.CFrame = CFrame.Angles(0, v7, 0) * CFrame.Angles(math.sin(v6) * 0.5 - 0.2, 0, 0) * CFrame.new(0, 0, 10)
	end
}
