-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMdCFJlc291cmNlBkVuZ2luZQROYW1lDkZpbmRGaXJzdENoaWxkBWVycm9yEU5vIEVuZ2luZSBuYW1lZDogBUNsb25lBkNGcmFtZQNuZXcLR2V0SW5zdGFuY2UCb3MFY2xvY2sGQW5nbGVzBG1hdGgDc2luBFNpemUJTWFnbml0dWRlBlVwZGF0ZQRnYW1lEVJlcGxpY2F0ZWRTdG9yYWdlCkdldFNlcnZpY2UFU3BlZWQFUHJpY2UHTGV2ZWwgMQdMZXZlbCAyB0xldmVsIDMHTGV2ZWwgNAdMZXZlbCA1BUl0ZW1zAAMGAQEAAAAf+wMAAE0CA2IAAAAATQECZgEAAABNAwC6AgAAALwBAQMDAAAAnwEDAisBBwCkAgUAAABAQG8EBgBNBQC6AgAAAHMDBAWfAgIBvAIBOgcAAACfAgICUgECAKQCCgAAJICAjAMAAIwEAACMBQAAnwIEAjACAYUIAAAAggECAAsDAQMCAwMDBAMFBAAAQEADBgMHAwgDCQQAJICAAB4KARgAAAAAAAAAAAAAAQEAAAAAAAACAAAABAAAAAAAAAABHwAAAAANAgAAAAAlpAICAAAEAICfAgECPgMCAyEEAwSkBwcAABhQgIwIAABSCQQAjAoAAJ8HBAKkCAcAABhQgLsYAwNSDAMApAsMAAAsoICfCwICWwoLCXgJCgiMCgAAjAsAAJ8IBAIJBgcIpAcOAAA0UICMCAAAjAkAAE0LAS8PAAAATQoLqhAAAACfBwQCCQUGBzAFAIUFAAAAggABABEDCwMMBAAEAIACAAAAAAAAAEACGC1EVPshGUADCAMNBAAYUIACMzMzMzMz0z8CmpmZmZmZuT8DDgMPBAAsoIADCQQANFCAAxADEQArEgEYAAAAAQEBAAAAAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAP4AAywAAAAACAAAAQIASKMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwL/AQAABQAAAOICBwBvAwgAMAMCugQAAACMAwAAMAMCLAUAAACMAwAAMAMCJAYAAADiAwcAbwQJADAEA7oEAAAAbwQKADAEAywFAAAAjARAHzAEAyQGAAAA4gQHAG8FCwAwBQS6BAAAAG8FDAAwBQQsBQAAAIwFUEYwBQQkBgAAAOIFBwBvBg0AMAYFugQAAABvBg4AMAYFLAUAAACMBgB9MAYFJAYAAADiBgcAbwcPADAHBroEAAAAjAcDADAHBiwFAAAAbwcQADAHBiQGAAAAxQECBgEAAADAAhEAEgAAAMADEgDiBBYAMAEEOBMAAAAwAgRRFAAAADADBCYVAAAAggQCABcDEwQAAABAAxQDFQMDAxYDFwUDBAUGAxgDGQIAAAAAAADoPwMaAgAAAAAAAPg/AxsCAAAAAAAAAkADHAIAAAAAAGroQAYABgEDHQMKAxIFAxMUFQIAAQEAARgAAQAAAAAAAQABAQAAAQAAAQAAAgEAAAEAAAEAAAIBAAABAAABAAACAQAAAQAAAQAAAgEAAAEAAAEAAAAAAwANCAEAAQABAAABAAAAAAL1WYNOY/69hsed6drSxY7XuQuIpfejdTlS7UmfazKs5hyFtYuabAIW

-- Decompiled by Krnl

local v_u_1 = game:GetService("ReplicatedStorage")
return {
	["Items"] = {
		{
			["Name"] = "Level 1",
			["Speed"] = 0,
			["Price"] = 0
		},
		{
			["Name"] = "Level 2",
			["Speed"] = 0.75,
			["Price"] = 8000
		},
		{
			["Name"] = "Level 3",
			["Speed"] = 1.5,
			["Price"] = 18000
		},
		{
			["Name"] = "Level 4",
			["Speed"] = 2.25,
			["Price"] = 32000
		},
		{
			["Name"] = "Level 5",
			["Speed"] = 3,
			["Price"] = 50000
		}
	},
	["GetInstance"] = function(p2)
		-- upvalues: (copy) v_u_1
		local v3 = v_u_1.Resource.Engine:FindFirstChild(p2.Name)
		if not v3 then
			error("No Engine named: " .. p2.Name)
		end
		local v4 = v3:Clone()
		v4.CFrame = CFrame.new(0, 0, 0)
		return v4
	end,
	["Update"] = function(p5, p6)
		local v7 = os.clock() / 2
		local v8 = v7 % 6.283185307179586
		p5.CFrame = CFrame.Angles(0, v8, 0) * CFrame.Angles(math.sin(v7) * 0.1 - 0.3, 0, 0) * CFrame.new(0, 0, p6.Size.Magnitude)
	end
}
