-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMjFUdldExvY2FsVmVoaWNsZVBhY2tldARNYWtlBFR5cGUKSGVhZGxpZ2h0cwVNb2RlbAxUcmFuc3BhcmVuY3kIR2V0Q29sb3IETmFtZQVDb2xvcgtHZXRJbnN0YW5jZQJvcwVjbG9jawZDRnJhbWUGQW5nbGVzBG1hdGgDY29zA3NpbgNuZXcLQm91bmRpbmdCb3gEU2l6ZQlNYWduaXR1ZGUGVXBkYXRlBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlB1ZlaGljbGUMVmVoaWNsZVV0aWxzBnNjcmlwdAZQYXJlbnQFUGFpbnQER2FtZQZHYXJhZ2UWZ2V0RGVmYXVsdFZlaGljbGVNb2RlbAVJdGVtcwADBgEDAAAAGvsCAABNAQKHAAAAAJ8BAQL7AgEATQMBrQEAAABNBAERAgAAAJ8CAwJNBAI7BAAAAE0DBJ0DAAAAjAQAADAEA9kFAAAA+wUCAE0EBQsGAAAATQUAugcAAACfBAICMAQDpAgAAACCAgIACQMBAwIDAwMEAwUDBgMHAwgDCQAICgEYAAAAAAEAAAAAAAEAAAABAAABAAAAAAAAAAEJAAAAAA4CAAAAAC+kAgIAAAQAgJ8CAQI+AwIDIQQDBKQHBwAAGFCAjAgAAG8KCAC7CQQDUg0EAKQMDAAALKCAnwwCAlsLDAlDCQoLjAoAAJ8HBAKkCAcAABhQgLsYAwNSDAMApAsPAAA4oICfCwICWwoLCXgJCg2MCgAAjAsAAJ8IBAIJBgcIpAcRAABAUICMCAAAjAkAAE0NAW8TAAAATQwNLxQAAABNCwyqFQAAAFsKCxKfBwQCCQUGBzAFAIUFAAAAggABABYDCwMMBAAEAIACAAAAAAAAAEACGC1EVPshGUADDQMOBAAYUIACGC1EVPshCUACmpmZmZmZuT8DDwMQBAAsoIACmpmZmZmZqT8DEQQAOKCAAxIEAEBQgAJmZmZmZmbmPwMTAxQDFQARFgEYAAAAAQEBAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAD+AAMSAAAAAAkAAAECADajAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwCNBgAAAE0CA20HAAAAnwECAqQCBQAAAEBApAUKAAAAkEBNBAUkCwAAAE0DBKQIAAAAnwICAqQDBQAAAEBATQYAvQ0AAABNBQYoDgAAAE0EBVEMAAAAnwMCAqQEBQAAAEBATQYAvQ0AAABNBQZ2DwAAAJ8EAgLABRAAEgABABIABAASAAMAwAYRAE0HAjgSAAAA4ggVADAHCDgSAAAAMAUIURMAAAAwBggmFAAAAIIIAgAWAxcEAAAAQAMYAxkDGgQAAEBAAxsDHAMJAx0EAACQQAMeAx8DIAMhAyIGAAYBAyMDCgMWBQMSExQCAAEBAAEYAAEAAAAAAAEAAAAAAAABAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAgAAAAkIAAEBAAEAAQAAAQAAAAACn3vMbKBZS+Stv6b4jRYgOXBeHe1Ffr9eRdVb98yDxaqYoYNxi4tu4A==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Vehicle.VehicleUtils)
local v3 = require(script.Parent.Color)
local v_u_4 = require(v1.Game.Garage.Paint)
local v_u_5 = require(v1.Game.getDefaultVehicleModel)
return {
	["Items"] = v3.Items,
	["GetInstance"] = function(p6)
		-- upvalues: (copy) v_u_2, (copy) v_u_5, (copy) v_u_4
		local v7 = v_u_2.GetLocalVehiclePacket()
		local v8 = v_u_5(v7.Make, v7.Type)
		local v9 = v8.Model.Headlights
		v9.Transparency = 0
		v9.Color = v_u_4.GetColor(p6.Name)
		return v8
	end,
	["Update"] = function(p10, p11)
		local v12 = os.clock() / 2
		local v13 = v12 % 6.283185307179586
		p10.CFrame = CFrame.Angles(0, 3.141592653589793 + math.cos(v13) * 0.1, 0) * CFrame.Angles(math.sin(v12) * 0.1 - 0.05, 0, 0) * CFrame.new(0, 0, p11.BoundingBox.Size.Magnitude * 0.7)
	end
}
