-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgM/CFJlc291cmNlEEdhcmFnZUhvcm5WaXN1YWwORmluZEZpcnN0Q2hpbGQFQ2xvbmUGQ0ZyYW1lA25ldwdQaXZvdFRvC0dldEluc3RhbmNlAm9zBWNsb2NrBkFuZ2xlcwRtYXRoA3NpbgtQcmltYXJ5UGFydARTaXplCU1hZ25pdHVkZQZVcGRhdGUHRGVzdHJveQtMb2NhbFBsYXllcgtPYmplY3RMb2NhbAlQbGF5ZXJHdWkHU291bmRJZAZWb2x1bWUPTWF4UGxheWJhY2tUaW1lDm9uSXRlbVNlbGVjdGVkBGdhbWUHUGxheWVycwpHZXRTZXJ2aWNlEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUDU3RkBUF1ZGlvBE5hbWUFUHJpY2UHU2VuZG9mZgZBaG9vZ2EHQWlyaG9ybgtDcnVpc2VsaW5lcgdCaWN5Y2xlBkxvb3BlZAtGaXJlQnJpZ2FkZQVRdWFjawRDaXR5B1N0ZWFtZXIITWVlcE1lZXAITG9vcGFibGUGU2Vhc29uBlRvcFBjdAxTZWFzb25JY29uSWQQQ2hhbXBpb25UcnVtcGV0cwZXaW5uZXIJQ3VjYXJhY2hhCE9yaWdpbmFsCVJlYWxpc3RpYwVUcmFpbgVDbG93bgtEcm9wV2VhcG9ucwtSdW1ibGVTaXJlbglDb3VudGRvd24GSGlkZGVuB05vVHJhZGUFSW5qYW4FSXRlbXMABAgBAQAAABX7AgAATQECYgAAAABvAwEAvAEBAwIAAACfAQMCvAIBOgMAAACfAgICUgECAKQEBgAAFECAjAUAAIwGAACMBwAAnwQEALwCAcIHAAAAnwIAAYIBAgAIAwEDAgMDAwQDBQMGBAAUQIADBwCHAQgBGAAAAAAAAAABAAAAAQAAAAAAAAAAAYgAAAAADQIAAAAAJ6QCAgAABACAnwIBAj4DAgMhBAMEpAcHAAAYUICMCAAAUgkEAIwKAACfBwQCpAgHAAAYUIC7GAMDUgwDAKQLDAAALKCAnwsCAlsKCwl4CQoIjAoAAIwLAACfCAQCCQYHCKQHDgAANFCAjAgAAIwJAABNDAGbDwAAAE0LDC8QAAAATQoLqhEAAACfBwQCCQUGBzAFAIUFAAAAggABABIDCQMKBAAEAIACAAAAAAAAAEACGC1EVPshGUADBQMLBAAYUIACMzMzMzMz0z8CmpmZmZmZuT8DDAMNBAAsoIADBgQANFCAAw4DDwMQAI4BEQEYAAAAAQEBAAAAAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAA/gADjwAAAAAHAQMAAAAj+wEAAA4BBgD7AQAAvAEBUAAAAACfAQIBxgEAAN4BAAD7AgEATQECMQEAAAArAQEAggABAPsCAgBNAQLRAgAAAPsEAQBNAwQxAQAAAE0CA5kDAAAATQMAfAQAAADiBAcAbwUIADAFBEsFAAAATQYAOwYAAACQBQYJMAUEOwYAAACfAQQC3gEAAIIAAQAKAxIDEwMUAxUDFgMXAxgFAgUGAgAAAAAAANA/AgAAAAAAAABAAJcBGQEYAAABAAAAAQACAAAAAQIAAAEAAAAAAQABAAAAAAAAAAD9AAWYAAAAABUAAAECAMECowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBAQAAAABAbwMEALwBARYDAAAAnwEDAqQCBgAAAFBATQQBoQcAAABNAwTSCAAAAJ8CAgL/AwAAFQAAAOIEDABvBQ0AMAUEugkAAABvBQ4AMAUEfAoAAACMBahhMAUEJAsAAADiBQwAbwYPADAGBboJAAAAbwYQADAGBXwKAAAAjAaoYTAGBSQLAAAA4gYMAG8HEQAwBwa6CQAAAG8HEgAwBwZ8CgAAAG8HEwAwBwYkCwAAAOIHDABvCBQAMAgHugkAAABvCBUAMAgHfAoAAACMCBAnMAgHJAsAAADiCAwAbwkWADAJCLoJAAAAbwkXADAJCHwKAAAAjAnECTAJCCQLAAAA4gkZAG8KGgAwCgm6CQAAAG8KGwAwCgl8CgAAAIwKiBMwCgkkCwAAAKkKAQAwCgm1GAAAAOIKDABvCxwAMAsKugkAAABvCx0AMAsKfAoAAABvCxMAMAsKJAsAAADiCxkAbwweADAMC7oJAAAAbwwfADAMC3wKAAAAjAzECTAMCyQLAAAAqQwBADAMC7UYAAAA4gwZAG8NIAAwDQy6CQAAAG8NIQAwDQx8CgAAAIwNmDowDQwkCwAAAKkNAQAwDQy1GAAAAOINDABvDiIAMA4NugkAAABvDiMAMA4NfAoAAACMDtQwMA4NJAsAAADiDigAbw8pADAPDroJAAAAbw8qADAPDnwKAAAAqQ8BADAPDrkkAAAAjA8OADAPDoYlAAAAjA8CADAPDjwmAAAAbw8rADAPDqEnAAAA4g8oAG8QLAAwEA+6CQAAAG8QLQAwEA98CgAAAKkQAAAwEA+5JAAAAIwQDAAwEA+GJQAAAIwQAgAwEA88JgAAAG8QLgAwEA+hJwAAAOIQLwBvETAAMBEQugkAAABvETEAMBEQfAoAAACpEQAAMBEQuSQAAACMEQkAMBEQhiUAAACMEQUAMBEQPCYAAADiETMAbxI0ADASEboJAAAAbxI1ADASEXwKAAAAqRIBADASEbkkAAAAjBIBADASETsyAAAAjBIAADASESQLAAAA4hI2AG8TNwAwExK6CQAAAG8TOAAwExJ8CgAAAIwTiBMwExIkCwAAAKkTAQAwExK5JAAAAOITNgBvFDkAMBQTugkAAABvFDoAMBQTfAoAAACMFKhhMBQTJAsAAACpFAAAMBQTuSQAAADFAwQRAQAAAOIENgBvBTsAMAUEugkAAABvBTwAMAUEfAoAAACMBSBOMAUEJAsAAACpBQAAMAUEuSQAAADiBTYAbwY9ADAGBboJAAAAbwY+ADAGBXwKAAAAjAaYOjAGBSQLAAAAqQYAADAGBbkkAAAA4gY2AG8HPwAwBwa6CQAAAG8HQAAwBwZ8CgAAAIwHECcwBwYkCwAAAKkHAQAwBwa5JAAAAOIHQQBvCEIAMAgHugkAAABvCEMAMAgHfAoAAACMCIgTMAgHJAsAAACpCAAAMAgHuSQAAABvCEQAMAgHOzIAAADiCEcAbxRIADAUCLoJAAAAbxRJADAUCHwKAAAAqRQBADAUCLkkAAAAqRQBADAUCLZFAAAAqRQBADAUCJVGAAAAxQMEBhEAAADABEoAEgABAMAFSwDGBgAA2QcCABIBBv8SAAAAEgACAOIIUAAwAwg4TAAAADAECFFNAAAAMAUIJk4AAAAwBwgTTwAAAMEGAACCCAIAUQMaBAAAAEADGwMcAx0DHgQAAFBAAx8DIAMhAxYDIgUDCQoLAyMCAACQCsx/B0IDJAIAAEg0zH8HQgMlAgAAUFjMfwdCAgAAAAAAF+FAAyYCAACwdsx/B0IDJwIAAOCRzH8HQgMoBQQJCgsYAykCAADAqsx/B0IDKgIAACDIzH8HQgMrAgAAaPnMfwdCAywCAABwEc1/B0IDLQIAAMhIzX8HQgMuAy8DMAMxBQYJCiQlJicDMgIAAFiGMB8HQgIAAEiWsiQHQgMzAgAACNjL1ARCAgAA4ErJ1ARCBQUJCiQlJgM0AgAA6JdxWgFCAxgFBQkKJDILAzUCAAAY95XfAEIFBAkKCyQDNgIAAJgx/b4AQgM3AgAAmCH9vgBCAzgCAAAQDP2+AEIDOQIAAOBl/L4AQgM6AgAAqKhd3wBCBQUJCgskMgM7AgAAaD/8vgBCAgAAAAAAAAxAAzwDPQUFCQokRUYDPgIAAAAavAvGQQYABgEDPwMIAxEDGQUETE1OTwMAAQIBAAEYAAEAAAAAAAEAAAAAAAEAAAAAAAACAAEBAAABAAABAAACAQAAAQAAAQAAAgEAAAEAAAEAAAIBAAABAAABAAACAQAAAQAAAQAAAgEAAAEAAAEAAAEAAAIBAAABAAABAAACAQAAAQAAAQAAAQAAAgEAAAEAAAEAAAEAAAIBAAABAAABAAACAQAAAQAAAQAAAQAAAQAAAQAAAgEAAAEAAAEAAAEAAAEAAAEAAAIBAAABAAABAAABAAABAAACAQAAAQAAAQAAAQAAAQAAAgEAAAEAAAEAAAEAAAIBAAABAAABAAABAAACAAABAAABAAABAAABAAACAQAAAQAAAQAAAQAAAgEAAAEAAAEAAAEAAAIBAAABAAABAAABAAABAAACAQAAAQAAAQAAAQAAAQAAAAADAAcIAQAAAA4BAAEAAQABAAAAAQAAAAADqCFDENJMe+2a5SmE58u9YFkMkK+m2HfvPbPWR82vF9pSx7tDmkXl/g==

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players")
local v_u_2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v_u_2.Std.Audio)
local v_u_4 = nil
return {
	["Items"] = {
		{
			["Name"] = "Sendoff",
			["SoundId"] = 12616040786,
			["Price"] = 25000
		},
		{
			["Name"] = "Ahooga",
			["SoundId"] = 12616042121,
			["Price"] = 25000
		},
		{
			["Name"] = "Airhorn",
			["SoundId"] = 12616043274,
			["Price"] = 35000
		},
		{
			["Name"] = "Cruiseliner",
			["SoundId"] = 12616044246,
			["Price"] = 10000
		},
		{
			["Name"] = "Bicycle",
			["SoundId"] = 12616045116,
			["Price"] = 2500
		},
		{
			["Name"] = "FireBrigade",
			["SoundId"] = 12616045912,
			["Price"] = 5000,
			["Looped"] = true
		},
		{
			["Name"] = "Quack",
			["SoundId"] = 12616046852,
			["Price"] = 35000
		},
		{
			["Name"] = "City",
			["SoundId"] = 12616048429,
			["Price"] = 2500,
			["Looped"] = true
		},
		{
			["Name"] = "Steamer",
			["SoundId"] = 12616049198,
			["Price"] = 15000,
			["Looped"] = true
		},
		{
			["Name"] = "MeepMeep",
			["SoundId"] = 12616050969,
			["Price"] = 12500
		},
		{
			["Name"] = "ChampionTrumpets",
			["SoundId"] = 12413440203,
			["Loopable"] = true,
			["Season"] = 14,
			["TopPct"] = 2,
			["SeasonIconId"] = 12424991433
		},
		{
			["Name"] = "Winner",
			["SoundId"] = 11183684353,
			["Loopable"] = false,
			["Season"] = 12,
			["TopPct"] = 2,
			["SeasonIconId"] = 11183663452
		},
		{
			["Name"] = "Cucaracha",
			["SoundId"] = 9316479741,
			["Loopable"] = false,
			["Season"] = 9,
			["TopPct"] = 5
		},
		{
			["Name"] = "Original",
			["SoundId"] = 9058828003,
			["Loopable"] = true,
			["MaxPlaybackTime"] = 1,
			["Price"] = 0
		},
		{
			["Name"] = "Realistic",
			["SoundId"] = 8990467635,
			["Price"] = 5000,
			["Loopable"] = true
		},
		{
			["Name"] = "Train",
			["SoundId"] = 8990467123,
			["Price"] = 25000,
			["Loopable"] = false
		},
		{
			["Name"] = "Clown",
			["SoundId"] = 8990466434,
			["Price"] = 20000,
			["Loopable"] = false
		},
		{
			["Name"] = "DropWeapons",
			["SoundId"] = 8990461116,
			["Price"] = 15000,
			["Loopable"] = false
		},
		{
			["Name"] = "RumbleSiren",
			["SoundId"] = 9058366741,
			["Price"] = 10000,
			["Loopable"] = true
		},
		{
			["Name"] = "Countdown",
			["SoundId"] = 8990459885,
			["Price"] = 5000,
			["Loopable"] = false,
			["MaxPlaybackTime"] = 3.5
		},
		{
			["Name"] = "Injan",
			["SoundId"] = 739735604,
			["Loopable"] = true,
			["Hidden"] = true,
			["NoTrade"] = true
		}
	},
	["GetInstance"] = function(_)
		-- upvalues: (copy) v_u_2
		local v5 = v_u_2.Resource:FindFirstChild("GarageHornVisual"):Clone()
		v5:PivotTo(CFrame.new(0, 0, 0))
		return v5
	end,
	["Update"] = function(p6, p7)
		local v8 = os.clock() / 2
		local v9 = v8 % 6.283185307179586
		p6.CFrame = CFrame.Angles(0, v9, 0) * CFrame.Angles(math.sin(v8) * 0.1 - 0.3, 0, 0) * CFrame.new(0, 0, p7.PrimaryPart.Size.Magnitude)
	end,
	["onItemSelected"] = function(p10)
		-- upvalues: (ref) v_u_4, (copy) v_u_1, (copy) v_u_3
		if v_u_4 then
			v_u_4:Destroy()
			v_u_4 = nil
		end
		if v_u_1.LocalPlayer then
			v_u_4 = v_u_3.ObjectLocal(v_u_1.LocalPlayer.PlayerGui, p10.SoundId, {
				["Volume"] = 0.25,
				["MaxPlaybackTime"] = p10.MaxPlaybackTime or 2
			})
		end
	end
}
