-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMeCFJlc291cmNlClN1c3BlbnNpb24ETmFtZQ5GaW5kRmlyc3RDaGlsZAVlcnJvchVObyBTdXNwZW5zaW9uIG5hbWVkOiAFQ2xvbmUGQ0ZyYW1lA25ldwtHZXRJbnN0YW5jZQJvcwVjbG9jawZBbmdsZXMEbWF0aANzaW4EU2l6ZQlNYWduaXR1ZGUGVXBkYXRlBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQVQcmljZQZIZWlnaHQHU2xhbW1lZANMb3cGTm9ybWFsBlJhaXNlZARIaWdoB01vbnN0ZXIFSXRlbXMAAwYBAQAAAB/7AwAATQIDYgAAAABNAQKPAQAAAE0DALoCAAAAvAEBAwMAAACfAQMCKwEHAKQCBQAAAEBAbwQGAE0FALoCAAAAcwMEBZ8CAgG8AgE6BwAAAJ8CAgJSAQIApAIKAAAkgICMAwAAjAQAAIwFAACfAgQCMAIBhQgAAACCAQIACwMBAwIDAwMEAwUEAABAQAMGAwcDCAMJBAAkgIAAIwoBGAAAAAAAAAAAAAABAQAAAAAAAAIAAAAEAAAAAAAAAAEkAAAAAA0CAAAAACWkAgIAAAQAgJ8CAQI+AwIDIQQDBKQHBwAAGFCAjAgAAFIJBACMCgAAnwcEAqQIBwAAGFCAuxgDA1IMAwCkCwwAACyggJ8LAgJbCgsJeAkKCIwKAACMCwAAnwgEAgkGBwikBw4AADRQgIwIAACMCQAATQsBLw8AAABNCguqEAAAAJ8HBAIJBQYHMAUAhQUAAACCAAEAEQMLAwwEAAQAgAIAAAAAAAAAQAIYLURU+yEZQAMIAw0EABhQgAKamZmZmZnJPwIAAAAAAADgPwMOAw8EACyggAMJBAA0UIADEAMRADASARgAAAABAQEAAAAAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAA/gADMQAAAAAJAAABAgBSowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAv8BAAAGAAAA4gIHAG8DCAAwAwK6BAAAAIwDuAswAwIkBQAAAG8DCQAwAwK8BgAAAOIDBwBvBAoAMAQDugQAAACMBMQJMAQDJAUAAABvBAsAMAQDvAYAAADiBAwAbwUNADAFBLoEAAAAjAUAADAFBLwGAAAAjAUAADAFBCQFAAAA4gUHAG8GDgAwBgW6BAAAAIwGxAkwBgUkBQAAAG8GDwAwBgW8BgAAAOIGBwBvBxAAMAcGugQAAACMB7gLMAcGJAUAAABvBxEAMAcGvAYAAADiBwcAbwgSADAIB7oEAAAAjAiIEzAIByQFAAAAbwgTADAIB7wGAAAAxQECBwEAAADAAhQAEgAAAMADFQDiBBkAMAEEOBYAAAAwAgRRFwAAADADBCYYAAAAggQCABoDEwQAAABAAxQDFQMDAxYDFwUDBAUGAxgCAAAAAAAA4L8DGQIAAAAAAADQvwUDBAYFAxoDGwKamZmZmZnJPwMcAgAAAAAAAOA/Ax0CAAAAAAAA+D8GAAYBAx4DCgMSBQMWFxgCAAEBAAEYAAEAAAAAAAEAAQEAAAEAAAEAAAIBAAABAAABAAACAQAAAQAAAQAAAgEAAAEAAAEAAAIBAAABAAABAAACAQAAAQAAAQAAAAADAA0IAQABAAEAAAEAAAAAAsc7TwHpnF609f8llYP0O1qfs3+xwT0Lo49tX5i4emgpmOE/symg1sQ=

-- Decompiled by Krnl

local v_u_1 = game:GetService("ReplicatedStorage")
return {
	["Items"] = {
		{
			["Name"] = "Slammed",
			["Price"] = 3000,
			["Height"] = -0.5
		},
		{
			["Name"] = "Low",
			["Price"] = 2500,
			["Height"] = -0.25
		},
		{
			["Name"] = "Normal",
			["Height"] = 0,
			["Price"] = 0
		},
		{
			["Name"] = "Raised",
			["Price"] = 2500,
			["Height"] = 0.2
		},
		{
			["Name"] = "High",
			["Price"] = 3000,
			["Height"] = 0.5
		},
		{
			["Name"] = "Monster",
			["Price"] = 5000,
			["Height"] = 1.5
		}
	},
	["GetInstance"] = function(p2)
		-- upvalues: (copy) v_u_1
		local v3 = v_u_1.Resource.Suspension:FindFirstChild(p2.Name)
		if not v3 then
			error("No Suspension named: " .. p2.Name)
		end
		local v4 = v3:Clone()
		v4.CFrame = CFrame.new(0, 0, 0)
		return v4
	end,
	["Update"] = function(p5, p6)
		local v7 = os.clock() / 2
		local v8 = v7 % 6.283185307179586
		p5.CFrame = CFrame.Angles(0, v8, 0) * CFrame.Angles(math.sin(v7) * 0.5 - 0.2, 0, 0) * CFrame.new(0, 0, p6.Size.Magnitude)
	end
}
