-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMfFUdldExvY2FsVmVoaWNsZVBhY2tldARNYWtlBFR5cGUFTW9kZWwLR2V0SW5zdGFuY2UCb3MFY2xvY2sGQ0ZyYW1lBkFuZ2xlcwRtYXRoA3NpbgNuZXcLQm91bmRpbmdCb3gEU2l6ZQlNYWduaXR1ZGUGVXBkYXRlBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlB1ZlaGljbGUMVmVoaWNsZVV0aWxzBUNvbG9yBnNjcmlwdAZQYXJlbnQKV2hlZWxDb2xvcgRHYW1lBkdhcmFnZQlDdXN0b21pemUWZ2V0RGVmYXVsdFZlaGljbGVNb2RlbAVJdGVtcwADBwEDAAAAGvsCAABNAQKHAAAAAJ8BAQL7AgEATQMBrQEAAABNBAERAgAAAJ8CAwLiAwQAMAIDOwMAAABNBAGtAQAAADAEA60BAAAATQQBEQIAAAAwBAMRAgAAAPsEAgBSBQAAUgYDAJ8EAwGCAgIABQMBAwIDAwMEBQMDAQIACAUBGAAAAAABAAAAAAABAAAAAAAAAAAAAAEAAAABCQAAAAAOAgAAAAAopAICAAAEAICfAgECPgMCAyEEAwSkBwcAABhQgIwIAABSCQQAjAoAAJ8HBAKkCAcAABhQgLsYAwNSDAMApAsMAAAsoICfCwICWwoLCXgJCgiMCgAAjAsAAJ8IBAIJBgcIpAcOAAA0UICMCAAAjAkAAE0NAW8QAAAATQwNLxEAAABNCwyqEgAAAFsKCw+fBwQCCQUGBzAFAIUFAAAAggABABMDBgMHBAAEAIACAAAAAAAAAEACGC1EVPshGUADCAMJBAAYUIACMzMzMzMz0z8CAAAAAAAA0D8DCgMLBAAsoIADDAQANFCAAmZmZmZmZuY/Aw0DDgMPABAQARgAAAABAQEAAAAAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAA/gADEQAAAAAJAAABAgA4owAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAjQYAAABNAgNtBwAAAJ8BAgKkAgUAAABAQKQFCgAAAJBATQQFJAsAAABNAwSkCAAAAJ8CAgKkAwUAAABAQE0HAL0NAAAATQYHKA4AAABNBQY7DwAAAE0EBWQMAAAAnwMCAqQEBQAAAEBATQYAvQ0AAABNBQZ2EAAAAJ8EAgLABREAEgABABIABAASAAMAwAYSAE0HAjgTAAAA4ggWADAHCDgTAAAAMAUIURQAAAAwBggmFQAAAIIIAgAXAxEEAAAAQAMSAxMDFAQAAEBAAxUDFgMXAxgEAACQQAMZAxoDGwMcAx0DHgYABgEDHwMFAxAFAxMUFQIAAQEAARgAAQAAAAAAAQAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAIAAAAICAABAQABAAEAAAEAAAAAAnc19pOcMb12RfGcBx9OmGyTfczm1xtYIlvW6wP/kEBkyQOSwFnYk9c=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Vehicle.VehicleUtils)
local v3 = require(script.Parent.Color)
local v_u_4 = require(v1.Game.Garage.Customize.WheelColor)
local v_u_5 = require(v1.Game.getDefaultVehicleModel)
return {
	["Items"] = v3.Items,
	["GetInstance"] = function(p6)
		-- upvalues: (copy) v_u_2, (copy) v_u_5, (copy) v_u_4
		local v7 = v_u_2.GetLocalVehiclePacket()
		local v8 = v_u_5(v7.Make, v7.Type)
		v_u_4(p6, {
			["Model"] = v8,
			["Make"] = v7.Make,
			["Type"] = v7.Type
		})
		return v8
	end,
	["Update"] = function(p9, p10)
		local v11 = os.clock() / 2
		local v12 = v11 % 6.283185307179586
		p9.CFrame = CFrame.Angles(0, v12, 0) * CFrame.Angles(math.sin(v11) * 0.25 - 0.3, 0, 0) * CFrame.new(0, 0, p10.BoundingBox.Size.Magnitude * 0.7)
	end
}
