-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMnFUdldExvY2FsVmVoaWNsZVBhY2tldARUeXBlBE1ha2UHQ2hhc3NpcwZDYW1hcm8FTW9kZWwLR2V0SW5zdGFuY2UCb3MFY2xvY2sGQ0ZyYW1lBkFuZ2xlcwRtYXRoA2NvcwNzaW4DbmV3C0JvdW5kaW5nQm94BFNpemUJTWFnbml0dWRlBlVwZGF0ZQRnYW1lEVJlcGxpY2F0ZWRTdG9yYWdlCkdldFNlcnZpY2UHcmVxdWlyZQdWZWhpY2xlDFZlaGljbGVVdGlscwpXaW5kb3dUaW50BnNjcmlwdAZQYXJlbnQJQ3VzdG9taXplBEdhbWUWZ2V0RGVmYXVsdFZlaGljbGVNb2RlbAROYW1lBVByaWNlBVZhbHVlAjgwAjYwAjQwAjIwBUl0ZW1zAAMHAQMAAAAj+wIAAE0BAocAAAAAnwEBAisBCADiAgMAbwMEADADAhEBAAAAbwMFADADAq0CAAAAUgECAPsCAQBNAwGtAgAAAE0EAREBAAAAnwIDAuIDBwAwAgM7BgAAAE0EAa0CAAAAMAQDrQIAAABNBAERAQAAADAEAxEBAAAA+wQCAFIFAABSBgMAnwQDAYICAgAIAwEDAgMDBQIBAgMEAwUDBgUDBgIBAAcHARgAAAAAAQEBAAABAAAAAwAAAAAAAQAAAAAAAAAAAAABAAAAAQgAAAAADgIAAAAAL6QCAgAABACAnwIBAj4DAgMhBAMEpAcHAAAYUICMCAAAbwoIALsJBANSDQQApAwMAAAsoICfDAICWwsMCUMJCguMCgAAnwcEAqQIBwAAGFCAuxgDA1IMAwCkCxAAADyggJ8LAgJbCgsOeAkKDYwKAACMCwAAnwgEAgkGBwikBxIAAERQgIwIAACMCQAATQ0BbxQAAABNDA0vFQAAAE0LDKoWAAAAWwoLE58HBAIJBQYHMAUAhQUAAACCAAEAFwMIAwkEAAQAgAIAAAAAAAAAQAIYLURU+yEZQAMKAwsEABhQgALSITN/fNkCQAKamZmZmZm5PwMMAw0EACyggAIzMzMzMzPTPwIAAAAAAADQPwMOBAA8oIADDwQARFCAAjMzMzMzM+M/AxADEQMSABUTARgAAAABAQEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAP4AAxYAAAAADAAAAQIAW6MAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DAI0GAAAATQIDbQcAAACfAQICpAIFAAAAQECkBwoAAACQQE0GByQLAAAATQUGJAsAAABNBAU7DAAAAE0DBIYIAAAAnwICAqQDBQAAAEBATQUAvQ0AAABNBAV2DgAAAJ8DAgLABA8AEgABABIAAwASAAIAwAUQAP8GAAAEAAAA4gcUAG8IFQAwCAe6EQAAAIwIuAswCAckEgAAAG8IFgAwCAfsEwAAAOIIFABvCRcAMAkIuhEAAACMCbgLMAkIJBIAAABvCRgAMAkI7BMAAADiCRQAbwoZADAKCboRAAAAjAq4CzAKCSQSAAAAbwoaADAKCewTAAAA4goUAG8LGwAwCwq6EQAAAIwLuAswCwokEgAAAG8LHAAwCwrsEwAAAMUGBwUBAAAA4gcgADAGBzgdAAAAMAQHUR4AAAAwBQcmHwAAAIIHAgAhAxQEAAAAQAMVAxYDFwQAAEBAAxgDGQMaAxsEAACQQAMcAx0DHgMfBgAGAQMgAyEDIgUDERITAyMCmpmZmZmZ6T8DJAIzMzMzMzPjPwMlApqZmZmZmdk/AyYCmpmZmZmZyT8DJwMHAxMFAx0eHwIAAQEAARgAAQAAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAAABAAAAAAAAAgAAAA4IAAEBAAABAAABAAACAQAAAQAAAQAAAgEAAAEAAAEAAAIBAAABAAABAAAAAAMBAAEAAQAAAQAAAAACsSpns9RYz46D7g0nFeDgiLSNHISnC7pvW9+7GBm4GwZhtbvArioS7Q==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Vehicle.VehicleUtils)
local v_u_3 = require(script.Parent.Parent.Customize.WindowTint)
local v_u_4 = require(v1.Game.getDefaultVehicleModel)
return {
	["Items"] = {
		{
			["Name"] = "80",
			["Price"] = 3000,
			["Value"] = 0.8
		},
		{
			["Name"] = "60",
			["Price"] = 3000,
			["Value"] = 0.6
		},
		{
			["Name"] = "40",
			["Price"] = 3000,
			["Value"] = 0.4
		},
		{
			["Name"] = "20",
			["Price"] = 3000,
			["Value"] = 0.2
		}
	},
	["GetInstance"] = function(p5)
		-- upvalues: (copy) v_u_2, (copy) v_u_4, (copy) v_u_3
		local v6 = v_u_2.GetLocalVehiclePacket()
		if not v6 then
			v6 = {
				["Type"] = "Chassis",
				["Make"] = "Camaro"
			}
		end
		local v7 = v_u_4(v6.Make, v6.Type)
		v_u_3(p5, {
			["Model"] = v7,
			["Make"] = v6.Make,
			["Type"] = v6.Type
		})
		return v7
	end,
	["Update"] = function(p8, p9)
		local v10 = os.clock() / 2
		local v11 = v10 % 6.283185307179586
		p8.CFrame = CFrame.Angles(0, 2.356194490192345 + math.cos(v11) * 0.1, 0) * CFrame.Angles(math.sin(v10) * 0.25 - 0.3, 0, 0) * CFrame.new(0, 0, p9.BoundingBox.Size.Magnitude * 0.6)
	end
}
