-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMVBHR5cGUIdXNlcmRhdGEIdG9zdHJpbmcGc3RyaW5nA3N1YgdYYm94T25lBHdhcm4WQ291bGQgbm90IGZpbmQgc3R5bGU6IAlHZXRTcHJpdGUQZ2V0SW1hZ2VJbnN0YW5jZQpJbWFnZUxhYmVsDUdldEltYWdlTGFiZWwLSW1hZ2VCdXR0b24OR2V0SW1hZ2VCdXR0b24FcGFpcnMGc2NyaXB0DFNwcml0ZXNoZWV0cwtHZXRDaGlsZHJlbgROYW1lB3JlcXVpcmUDbmV3AAQIAwEAAAAluygBA1IEAQCkAwEAAAAAQJ8DAgLwAw0AAgAAgLs/AQNSBQEApAQEAAAAMECfBAICgS0EBAUAAABvBQUApAMIAAAcYICfAwMCUgEDAPsFAABNBAV5CQAAAIcDBAIrAwcApAQLAAAAoEBvBgwAUgcCAHMFBgefBAIBggABAFIGAABSBwEAvAQD7Q0AAACfBAQCggQCAA4DAQQAAABAAwIDAwQAADBAAgAAAAAAACxAAwQDBQQAHGCAAwYDBwQAAKBAAwgDCQALCgEYAAAAAAAAAAEAAAAAAAAAAAAAAAIAAAABAQAAAAAAAQIAAAAAAQ0AAAAACQQBAAAAB/sEAABvBQAAUgYBAFIHAgBSCAMAnwQFAIIEAAABAwsAGQwBGAAAAAAAAAAaAAAAAAkEAQAAAAf7BAAAbwUAAFIGAQBSBwIAUggDAJ8EBQCCBAAAAQMNAB0OARgAAAAAAAAAHgAAAAARAAABAAA4owAAAP8AAgAAAAAA/wEAAAAAAACkAgEAAAAAQKQEAwAAACBATQMEHQQAAAC8AwNoBQAAAJ8DAgCfAgAEFwIbAE0HBroGAAAA/wgAAAAAAABqCAEHpAcBAAAAAEC8CAZoBQAAAJ8IAgCfBwAEFwcNAE0NBroGAAAAhwwBDU0NC7oGAAAApA8IAAAAcEBSEAsAnw8CAk0OD+8JAAAAnw4BAmoODA1uB/L/AgAAAG4C5P8CAAAAwAIKABIAAQDAAwsAEgACADADAIEMAAAAwAMNABIAAgAwAwCODgAAAIIAAgAPAw8EAAAAQAMQBAAAIEADEQMSAxMDFAQAAHBAAxUGAAYBAwwGAgMOAwABAgEAARgAAAACAAEAAAAAAAAAAAAAAQAAAAABAAAAAAAAAQAAAAAAAAAAAAAAAP8A/gAHAA4AAAAEAAAABAEAAAAAA29ST9IDOe6PXZYlRnjSz3aXn5woiPI0IcGEQQwO+hdgxXW9N7T/gfA=

-- Decompiled by Krnl

local v_u_1 = {}
local v2 = {}
for _, v3 in pairs(script.Spritesheets:GetChildren()) do
	v_u_1[v3.Name] = {}
	for _, v4 in pairs(v3:GetChildren()) do
		v_u_1[v3.Name][v4.Name] = require(v4).new()
	end
end
local function v_u_10(p5, p6, p7)
	-- upvalues: (copy) v_u_1
	if type(p6) == "userdata" then
		local v8 = tostring(p6)
		p6 = string.sub(v8, 14)
	end
	local v9 = v_u_1.XboxOne[p7]
	if v9 then
		return v9:GetSprite(p5, p6)
	end
	warn("Could not find style: " .. p7)
end
function v2.GetImageLabel(_, p11, p12, p13)
	-- upvalues: (copy) v_u_10
	return v_u_10("ImageLabel", p11, p12, p13)
end
function v2.GetImageButton(_, p14, p15, p16)
	-- upvalues: (copy) v_u_10
	return v_u_10("ImageButton", p14, p15, p16)
end
return v2
