-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMKBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplD1BPUlRBTF9UQUdfTkFNRQ1QUk9EX1BMQUNFX0lEEFJvY2tldGVlcnNQb3J0YWwAAQUAAAECABmjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CAxgHAAAAnwECAk0CAQAIAAAA4gMLAG8EDAAwBAOACQAAAG8EDQAwBAN3CgAAAJ8CAgCCAgAADgMBBAAAAEADAgMDAwQEAABAQAMFAwYDBwMIAwkFAgkKAwoCAABIbvjNB0IAAQABGAABAAAAAAABAAAAAAAAAQAAAQAAAQAA/gABAAAAAAAV9OHHjoLUzCcwi1M2TQxBPtQ/csbcACoiMm7GmagDJplN9tVCe5sy

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Std.TableUtils).requireValidIndexAndFreeze({
	["PORTAL_TAG_NAME"] = "RocketeersPortal",
	["PROD_PLACE_ID"] = 12779982281
})
