-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgN7BlBsYXllcg9fb25JdGVtRXF1aXBwZWQLR2V0RXF1aXBwZWQOb25JdGVtRXF1aXBwZWQHQ29ubmVjdAhHaXZlVGFzawpEb0NsZWFuaW5nB1Byb21pc2UHYW5kVGhlbgtHaXZlUHJvbWlzZRBvYnNlcnZlUGxheWVyT2JqCXdvcmtzcGFjZRBHZXRTZXJ2ZXJUaW1lTm93CkdldFBsYXllcnMJQ2hhcmFjdGVyC1ByaW1hcnlQYXJ0CFBvc2l0aW9uA29iaglNYWduaXR1ZGUGVXNlcklkE0RJU1RfVE9fUFVTSF9XSVRISU4TVElNRV9CRVRXRUVOX1BVU0hFUwV0YWJsZQZpbnNlcnQEVW5pdBdQVVNIX0lNUFVMU0VfTVVMVElQTElFUgxBcHBseUltcHVsc2UFX21haWQJSGVhcnRiZWF0F2luaXRpYWxpemVQbGF5ZXJQdXNoaW5nA25ldwxzZXRtZXRhdGFibGUUY2hhcmFjdGVyVG9QbGF5ZXJPYmoFVmFsdWUHQ2hhbmdlZARwYXJ0BWNvbG9yBG5hbWUEc2l6ZQVmbGFzaAZDb2xvcjMHZnJvbVJHQgpCYXNlODVVVUlEBVVEaW0yA2FkZAlEZXN0cm95ZWQNVXNlcklucHV0VHlwZQRFbnVtDE1vdXNlQnV0dG9uMQpJbnB1dEVuZGVkAm9zBWNsb2NrCEh1bWFub2lkBkhlYWx0aA1HZXRUYXJnZXRUeXBlCURFU1RfVFlQRQRJRExFE3JhbmRvbVBvaW50SW5DaXJjbGUBWAFZB1ZlY3RvcjMIVmVsb2NpdHkGQ0ZyYW1lCkxvb2tWZWN0b3IVU2V0VGhpcmRNb3VzZVBvc2l0aW9uCUdldFRhcmdldAZ0eXBlb2YISW5zdGFuY2UMY2FuU2VlVGFyZ2V0E29jY2x1c2lvbkNhc3RQYXJhbXMGUGFyZW50BEhlYWQORmluZEZpcnN0Q2hpbGQPZ2V0QnVsbGV0U3ByZWFkDEJ1bGxldFNwcmVhZBNnZXRUcmlnZ2VyUHJlc3NGcmVxBG1hdGgGcmFuZG9tCklucHV0QmVnYW4EdGFzawVkZWxheQNtaW4GdXBkYXRlBWRlYnVnDHByb2ZpbGViZWdpbhJHdWFyZE5QQyBIZWFydGJlYXQKcHJvZmlsZWVuZA1TaW11bGF0ZUxvY2FsCU1pbmltYWxGeA1CdWxsZXRFbWl0dGVyEUlnbm9yZUxvY2FsUGxheWVyDlNoaWVsZEJsb2NrUGN0DElnbm9yZUd1YXJkcwVDb2xvcg1pdGVtSGVhcnRiZWF0BGdhbWUKUnVuU2VydmljZQpHZXRTZXJ2aWNlEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUER2FtZQpJdGVtU3lzdGVtCUludmVudG9yeRhJbnZlbnRvcnlJdGVtT3duZXJCaW5kZXIDTlBDDk1hbmlmZXN0QmluZGVyA1N0ZARNYWlkCUdlb21VdGlscwhHdWFyZE5QQw5HdWFyZE5QQ1NoYXJlZA1HdWFyZE5QQ1V0aWxzDkd1YXJkTlBDQ29uc3RzCU5QQ0NvbnN0cwNBcHAOTWluaW1hcFNlcnZpY2UGTW9kdWxlBE1hdGgHUGxheWVycwdfX2luZGV4CFRBR19OQU1FCGh1bWFub2lkG0NIQVJDVEVSX1RPX1BMQVlFUl9PQkpfTkFNRQALBAECAAAADE0BAPkAAAAA+wIAAPEBAgACAAAAggABAPsBAQBSAwAAvAEBegEAAACfAQMBggABAAIDAQMCACYAARgAAAAAAAECAAAAAAEnAAAAAAcBAwAAABn7AgAATQECLQAAAABSAgAAnwECAg4BBQD7AgEAUgQBALwCAnoBAAAAnwIDAfsCAgD7BQAATQQFGwIAAADZBgAAEgAAABICAQC8BATHAwAAAJ8EAwC8AgL9BAAAAJ8CAAGCAAEABQMDAwIDBAMFAwYBACEAARgAAAAAAAEBAAAAAAIAAAAAAAAAAAAAAAAGIgAAAAAGAQQAAAAX+wEAALwBAVEAAAAAnwECASsAAQCCAAEA+wEAAPsDAQBSBQAAvAMDcgEAAACfAwMC2QUAABICAgASAgMAEgIAALwDA7UCAAAAnwMDALwBAekDAAAAnwEAAYIAAQAEAwcDCAMJAwoBARwLARgAAAAAAQECAAAAAAAAAAAAAAAAAAAADB0AAAAADwAEAAAAYP8AAAAAAAAApAEBAAAAAEC8AQG3AgAAAJ8BAgL7AgAAvAICqwMAAACfAgIEZAIzAE0HBmkEAAAADgcwAE0LB5sFAAAATQoLOwYAAAD7DgEATQ0OEwcAAABNDA2bBQAAAE0LDDsGAAAAJgkKC00ICaoIAAAAxgkAAPsLAgBNDAbmCQAAAIcKCwwOCgYA+wsCAE0MBuYJAAAAhwoLDCYJAQplAAEAbwkKAPsLAwBNCguhCwAAAH0IEQAKAAAA+wsDAE0KC+MMAAAAYAoMAAkAAAD7CgIATQsG5gkAAABqAQoLnjQABQcAAABSCwAAUgwHAKQKDwAAONCAnwoDAW4CzP8CAAAAUgIAAMYDAADGBAAAZAIXAE0KBpsFAAAATQkKOwYAAAD7DQEATQwNEwcAAABNCwybBQAAAE0KCzsGAAAAJggJCk0HCAcQAAAATQgGmwUAAAD7DAMATQsMBREAAAAJCgcLvAgIChIAAACfCAMBbgLo/wIAAACpAgEAggICABMDDAQAAABAAw0DDgMPAxADEQMSAxMDFAIAAAAAAADwfwMVAxYDFwMYBAA40IADGQMaAxsAPQABGAAAAQAAAAABAAAAAAEAAQEAAAAAAAAAAAAAAAAAAQEAAAAAAQAAAAAAAgMAAAAAAQAAAAACAAAAAQAAAAAAAPEAFAAAAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAAA/gAEAD4AAAAABgAEAAAAFP8AAAAAAAAA+wIAAE0BAsEAAAAA+wQBAE0DBP0BAAAA2QUAABICAgASAgAAEgAAABICAwC8AwPHAgAAAJ8DAwC8AQH9AwAAAJ8BAAGCAAEABAMcAx0DBQMGAQM7HgEYAAABAAAAAAAAAAAAAAAAAAAAAB08AAAAAAsCCgAAAGH7AwAATQID7wAAAABSAwAAUgQBAJ8CAwL7BQEAnj0CBAUAAABSBAIApAMCAAAAEECfAwMB+wQCAE0DBO8AAAAAnwMBAk0EAsEDAAAAUgYDALwEBP0EAAAAnwQDAdkEAAASAAMAEgIDABICBAASAAIAUgUEAE0HAXIFAAAATQYH7AYAAACfBQIBTQUCwQMAAABNCAFyBQAAAE0HCIUHAAAAUgkEALwHB8cIAAAAnwcDALwFBf0EAAAAnwUAAeIFDgBNBwITDwAAAE0GB5sQAAAAMAYFJAkAAACkBhMAAEgQgYwH/wCMCMwAjAkAAJ8GBAIwBgVECgAAAPsHBQBNBgfCFAAAAIwHBQCfBgICMAYFWgsAAACkBhYAAABQgYwHAACMCAwAjAkAAIwKDACfBgUCMAYFDwwAAACpBgEAMAYFpw0AAABNBgLBAwAAAPsJBgBNCAm/FwAAAFIJBQCfCAIAvAYG/QQAAACfBgAB2QYBABIAAgASAgcAEgIIABICCQCCAgIAGAMfAyAEAAAQQAMcAwYDIQMiAyMDBQMkAyUDJgMnAygFBQkKCwwNAxIDEAMpAyoEAEgQgQMrAywEAABQgQMtAgIEFh8BGAAAAAAAAAEAAAAAAAACAAAAAQAAAAAAAQAAAAASAAAAAAABAAAAAAAAAAAAAAAAAwEAAAAAAAEAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAEAAAIAAAAAAAAAAAACAAAAACEXAAAAAAQAAQAAAA/7AQAATQABJQAAAAAOAAEAggABAPsAAADiAgIApAMFAAQEMMAwAwLCAQAAALwAAK8GAAAAnwADAYIAAQAHAy4DLwUBAQMwAzEEBAQwwAMyAKkBAAEYAAAAAAECAAAAAAAAAAABqgAAAAALAA0AAAcAAAEIA1YByQGkAQIAAAQAgJ8BAQL7AgAAQwABAvsDAQBNAgMTAwAAAE0BAgEEAAAADgEKAPsEAQBNAwQTAwAAAE0CAwEEAAAATQECWgUAAACMAgAAfQEDAAIAAACpAQAAggECAPsBAQC8AQEFBgAAAJ8BAgL7BAIATQME6gcAAABNAgPdCAAAAJoBPAACAAAA+wIDACYBAAJvAgkAYAIQAAEAAAD7AgQATQECfwoAAACfAQECTQMBeQsAAACMBAAATQUBeAwAAABMNgACpAIPAAA40ICfAgQC3gIFAN4AAwD7BQEATQQFEwMAAABNAwSbEAAAAE0CA4URAAAATQECqhIAAAD7BgEATQUGEwMAAABNBAWbEAAAAE0DBDsTAAAA+wkBAE0ICRMDAAAATQcImxAAAABNBgeFFQAAAE0FBmgWAAAAWwQFFEMCAwSMAwgAYAEEAAMAAAD7BAUAWwMEF0MCAgP7AwYAUgUCALwDA/YYAAAAnwMDAWUAagD7AQEAvAEBmxkAAACfAQICKwECAKkCAACCAgIAuywBA1IDAQCkAhsAAACgQZ8CAgLwAgMAHAAAAKkCAACCAgIA+wMHACYCAAOMAwEAYAMOAAIAAAD7AwkATQID1R0AAAD7BAEATQMEEwMAAABSBAEA+wYBAE0FBrseAAAAnwIEAt4CCADeAAcA+wIIACsCAgCpAgAAggICAE0CASQfAAAAKwICAKkDAACCAwIAbwYgALwEAgMhAAAAnwQDAk0DBDsTAAAA+wQGAPsGCgBNBQbjIgAAAPsHAQBNBgcTAwAAAJ8FAgIwBQSqIwAAAPsEBgBSBgMAvAQE9hgAAACfBAMB+wUKAE0EBa8kAAAA+wYBAE0FBhMDAAAAnwQCAvsGCwAmBQAG2AYlBGAGHwAFAAAA3gALAKQFKAAAnGCCnwUBAt4FDAD7BQYA4gcqAKQILQAspLDCMAgHwikAAAC8BQWCLgAAAJ8FAwGkBTEAAMDwgm8HMgDYCSUE+woMAAkICQqeEwcDCAAAAKQGNAAAzGCCnwYDAtkHAAASAgYAnwUDAakFAQCCBQIAqQEAAIIBAgA1AzMDNAQABACAAxIDNQM2AzcDOAM5AgAAAAAAAPg/AzoDOwM8Az0DHwQAONCAAxADPgMTAxECAAAAAAAAJEADPwNAAgAAAAAAABxAA0EDQgNDBAAAoEEDRANFA0YDRwNIA0kDSgNLA0wCAAAAAAAA8D8DTQNOBACcYIIDLwUBKQMwAzEELKSwwgNPA1ADUQQAwPCCAgAAAAAAAOA/A1IEAMxgggEGd1MBGAAAAAAAAgAAAAAAAAAAAAAAAAAAAAEAAwAAAAAAAAAAAAABAAAAAAEAAAABAAAAAAAAAAAAAQIAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAEAAAEAAAIAAAAAAAIAAAABAQACAAAAAAAAAQACAAAAAAEAAAAAAAAAAAAAAAECAAEAAgABAwACAAAAAAABAAAAAAAAAAAAAQAAAAACAAAAAAAAAQAAAAABAQAAAAEAAAAAAAAAAAIAAAAAAAAAAAAAAAAABgADAHgAAAAAAgABAAAACqQAAgAABACAbwEDAJ8AAgH7AAAAnwABAaQABQAAEACAnwABAYIAAQAGA1QDVQQABACAA1YDVwQAEACAALQBAAEYAAAAAAEAAQAAAbUAAAAADgIFAAAAUaQDAwAACBCAnwMBAlsCAwCpAwEAMAMBBgQAAACpAwEAMAMBnwUAAABNAwFnBgAAAKkEAQAwBAMGBAAAAE0DAWcGAAAAqQQAADAEA9cHAAAATQMBZwYAAABvBAgAMAQDngkAAABNAwFnBgAAAKkEAQAwBAOQCgAAAE0DAWcGAAAApAQNAAAwsICMBcQAjAYoAIwHHACfBAQCMAQDpA4AAACMAwAATDYAAqQEEQAAQPCAnwQBAqQFFAAATCCBnwUBAowGAACpBwAApAgUAABMIIGfCAEC2QkAABIAAgASAAAAEgIAABIBA/8SAgEAEgEE/xIAAQASAQj/EgEH/xICAgASAgMAEgEF/xIBBv9NCgDBFQAAAPsMBABNCwz9FgAAANkNAQASAAkAvAsLxxcAAACfCwMCMAsKGhgAAADBAwAAggABABkCAAAAAAAAWUADTQNOBAAIEIADWANZA1oDWwIAAAAAAADoPwNcA10DKQMqBAAwsIADXgM9Ax8EAEDwgAMzAzQEAEwggQMcAx0DBQNfAgcIYQIBGAAAAAADAAABAAACAAAAAAEAAAAAAQAAAAABAAAAAAIAAAAAAAAAAAACAQAAAAIAAAEBAQAAAQAAAAAAAAAAAAAAAAA9AAAAAAAAAAAAAAAFAGMAAAAAFAAAAQIAlgGjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIGAAAAUEBNBQG9BwAAAE0EBfAIAAAATQME8AgAAACfAgICpAMGAAAAUEBNBQFgCQAAAE0EBQQKAAAAnwMCAqQEBgAAAFBATQYBXAsAAABNBQZcCwAAAJ8EAgKkBQYAAABQQE0GAYkMAAAAnwUCAqQGBgAAAFBATQgBoQ0AAABNBwh2DgAAAJ8GAgKkBwYAAABQQE0JAaENAAAATQgJPA8AAACfBwICpAgGAAAAUEBNCgFcEAAAAE0JCrYRAAAAnwgCAqQJBgAAAFBATQsBXBAAAABNCgviEgAAAJ8JAgKkCgYAAABQQE0MAVwQAAAATQsMwxMAAACfCgICpAsGAAAAUEBNDQFcCwAAAE0MDUQUAAAAnwsCAqQMBgAAAFBATQ4BwRUAAABNDQ5dFgAAAJ8MAgKkDQYAAABQQE0PAUAXAAAATQ4PjBgAAACfDQICpA4BAAAAAEBvEBkAvA4OFgMAAACfDgMC/w8DAAAAAAAwDw9uGgAAAJ49DwUEAAAAUhEPAFISBACkEBwAAACwQZ8QAwHAEB0AEgAEABIADwASAAYAEgADABIAAgASAA0AEgAMABIAAAASAA4AEgAKADAQD+8eAAAAwBAfABIACwASAAcAEgAIABIACQASAAAAMBAPeiAAAABNEAXvHgAAAE0RCrQhAAAA4hIkAG8TJQAwExLhIgAAAE0TCiEmAAAAMBMSciMAAABSEw8AnxAEAIIQAAAnA2AEAAAAQANhA2IDYwNkBAAAUEADZQNmA2cDaANpA2oDawNsA20DbgNvA3ADcQNyA3MDdAN1A3YDdwN4AyAEAACwQQYFAx8GCQMCA3kDegMhBQIiIwM1A3sCBQkBAAEYAAEAAAAAAAEAAAAAAAEAAAAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAIAAQABAAAAAAAAAgAAAAAAAAAAAAAAAEsAAAAAAAAAWgAAAAABAAABAAAAAf0AAQAAAAAKzQDyitr9rRb/xJgeRvSMLDjoIr0kkvZsgFhSCibQ9TtWTyO4BipqYw==

-- Decompiled by Krnl

local v_u_1 = game:GetService("RunService")
local v2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v2.Game.ItemSystem.ItemSystem)
local v_u_4 = require(v2.Inventory.InventoryItemOwnerBinder)
local v_u_5 = require(v2.NPC.NPC)
local v6 = require(v2.ManifestBinder)
local v_u_7 = require(v2.Std.Maid)
local v_u_8 = require(v2.Std.GeomUtils)
local v_u_9 = require(v2.GuardNPC.GuardNPCShared)
local v_u_10 = require(v2.GuardNPC.GuardNPCUtils)
local v_u_11 = require(v2.GuardNPC.GuardNPCConsts)
local v_u_12 = require(v2.NPC.NPCConsts)
local v_u_13 = require(v2.App.MinimapService)
local v_u_14 = require(v2.Module.Math)
local v_u_15 = game:GetService("Players")
local v_u_16 = {}
v_u_16.__index = v_u_16
setmetatable(v_u_16, v_u_5)
function v_u_16.new(p17, p18)
	-- upvalues: (copy) v_u_5, (copy) v_u_16, (copy) v_u_7, (copy) v_u_4, (copy) v_u_3, (copy) v_u_14, (copy) v_u_13, (copy) v_u_1, (copy) v_u_15, (copy) v_u_11
	local v_u_19 = v_u_5.new(p17, p18)
	local v20 = v_u_16
	setmetatable(v_u_19, v20)
	local v_u_21 = v_u_7.new()
	v_u_19._maid:GiveTask(v_u_21)
	local function v26(p22)
		-- upvalues: (copy) v_u_21, (ref) v_u_4, (ref) v_u_3, (copy) v_u_19
		v_u_21:DoCleaning()
		if p22 then
			v_u_21:GivePromise(v_u_4:Promise(p22):andThen(function(p_u_23)
				-- upvalues: (ref) v_u_3, (ref) v_u_19, (ref) v_u_21
				local v24 = v_u_3.GetEquipped(p_u_23)
				if v24 then
					v_u_19:_onItemEquipped(v24)
				end
				v_u_21:GiveTask(v_u_3.onItemEquipped:Connect(function(p25)
					-- upvalues: (copy) p_u_23, (ref) v_u_19
					if p25.Player == p_u_23 then
						v_u_19:_onItemEquipped(p25)
					end
				end))
			end))
		end
	end
	v26(p18.characterToPlayerObj.Value)
	v_u_19._maid:GiveTask(p18.characterToPlayerObj.Changed:Connect(v26))
	local v27 = {
		["part"] = v_u_19.obj.PrimaryPart,
		["color"] = Color3.fromRGB(255, 204, 0),
		["name"] = v_u_14.Base85UUID(5),
		["size"] = UDim2.new(0, 12, 0, 12),
		["flash"] = true
	}
	v_u_19._maid:GiveTask(v_u_13.add(v27))
	return v_u_19
end
function v_u_16._onItemEquipped(p_u_28, p_u_29)
	-- upvalues: (copy) v_u_12, (copy) v_u_8, (copy) v_u_9, (copy) v_u_10, (copy) v_u_1
	local v_u_30 = math.random() * 100
	p_u_29.SimulateLocal = true
	p_u_29.MinimalFx = true
	p_u_29.BulletEmitter.SimulateLocal = true
	p_u_29.BulletEmitter.IgnoreLocalPlayer = false
	p_u_29.BulletEmitter.ShieldBlockPct = 0.75
	p_u_29.BulletEmitter.IgnoreGuards = true
	p_u_29.BulletEmitter.Color = Color3.fromRGB(196, 40, 28)
	local v_u_31 = 0
	local v_u_32 = Vector3.new()
	local v_u_33 = os.clock()
	local v_u_34 = 0
	local v_u_35 = false
	local v_u_36 = os.clock()
	local function v_u_49()
		-- upvalues: (copy) v_u_30, (copy) p_u_28, (ref) v_u_12, (ref) v_u_31, (ref) v_u_8, (ref) v_u_32, (copy) p_u_29, (ref) v_u_36, (ref) v_u_35, (ref) v_u_9, (ref) v_u_10, (ref) v_u_33, (ref) v_u_34
		local v37 = os.clock() + v_u_30
		if not p_u_28.obj.Humanoid or p_u_28.obj.Humanoid.Health <= 0 then
			return false
		end
		if p_u_28:GetTargetType() == v_u_12.DEST_TYPE.IDLE then
			if v37 - v_u_31 > 1.5 then
				local v38 = v_u_8.randomPointInCircle()
				local v39 = v38.X
				local v40 = v38.Y
				v_u_32 = Vector3.new(v39, 0, v40)
				v_u_31 = v37
			end
			local v41 = p_u_28.obj.PrimaryPart.Velocity.Magnitude
			local v42 = p_u_28.obj.PrimaryPart.Position + p_u_28.obj.PrimaryPart.CFrame.LookVector * 10
			if v41 < 8 then
				v42 = v42 + v_u_32 * 7
			end
			p_u_29:SetThirdMousePosition(v42)
		else
			local v43 = p_u_28:GetTarget()
			if not v43 then
				return false
			end
			if typeof(v43) ~= "Instance" then
				return false
			end
			if v37 - v_u_36 > 1 then
				v_u_35 = v_u_9.canSeeTarget(p_u_28.obj, v43, p_u_28.occlusionCastParams)
				v_u_36 = v37
			end
			if not v_u_35 then
				return false
			end
			local v44 = v43.Parent
			if not v44 then
				return false
			end
			local v45 = v44:FindFirstChild("Head").Position
			p_u_29.BulletSpread = v_u_10.getBulletSpread(p_u_28.obj)
			p_u_29:SetThirdMousePosition(v45)
			local v46 = v_u_10.getTriggerPressFreq(p_u_28.obj)
			if v37 - v_u_33 > 1 / v46 then
				v_u_33 = v37
				v_u_34 = math.random()
				p_u_29:InputBegan({
					["UserInputType"] = Enum.UserInputType.MouseButton1
				})
				local v47 = task.delay
				local v48 = 1 / v46 * v_u_34
				v47(math.min(0.5, v48), function()
					-- upvalues: (ref) p_u_29
					if not p_u_29.Destroyed then
						p_u_29:InputEnded({
							["UserInputType"] = Enum.UserInputType.MouseButton1
						})
					end
				end)
				return true
			end
		end
		return false
	end
	p_u_28._maid.itemHeartbeat = v_u_1.Heartbeat:Connect(function()
		-- upvalues: (copy) v_u_49
		debug.profilebegin("GuardNPC Heartbeat")
		v_u_49()
		debug.profileend()
	end)
end
return v6.new(v_u_11.TAG_NAME, {
	["humanoid"] = "Humanoid",
	["characterToPlayerObj"] = v_u_11.CHARCTER_TO_PLAYER_OBJ_NAME
}, v_u_16)
