-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMbCmNvdW50SW5uZXIKY291bnRPdXRlcghzZXRTdGF0ZQRpbml0DWNyZWF0ZUVsZW1lbnQIcG9zaXRpb24LYW5jaG9yUG9pbnQEc2l6ZQVVRGltMgNuZXcHVmVjdG9yMgVzdGF0ZQZyZW5kZXILd2lsbFVubW91bnQHdW5tb3VudAlDb21wb25lbnQDQXBwBmV4dGVuZAdyZXF1aXJlBEdyaWQGc2NyaXB0BlBhcmVudAVtb3VudARnYW1lEVJlcGxpY2F0ZWRTdG9yYWdlCkdldFNlcnZpY2UFUm9hY3QABgUBAAAAAAviAwIAjAQDADAEAzkAAAAAjAQEADAEAx8BAAAAvAEAKgMAAACfAQMBggABAAQDAQMCBQIAAQMDAAcEARgAAQAAAQAA/gAABAgAAAAACQECAAAALPsCAABNAQLKAAAAAPsCAQDiAwYApAQJAAAgcICMBQEAjAYAAIwHAQCMCAAAnwQFAjAEA9sBAAAApAQLAAAgoICMBQEAjAYBAJ8EAwIwBAMIAgAAAKQECQAAIHCAbwUMAIwGAABvBw0AjAgAAJ8EBQIwBAMPAwAAAE0FABgOAAAATQQFOQQAAAAwBAM5BAAAAE0FABgOAAAATQQFHwUAAAAwBAMfBQAAAJ8BAwCCAQAADwMFAwYDBwMIAwEDAgUFAQIDBAUDCQMKBAAgcIADCwQAIKCAApqZmZmZmck/AgAAAAAAAOA/AwwADQ0BGAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAEAAAAAAAEAAAAAAPsADgAAAAABAQAAAAABggABAAAAFg4BGAAWAAAAAAIAAgAAAAb7AQAATQABEgAAAAD7AQEAnwACAYIAAQABAw8AGQABGAAAAAAAARoAAAAABgEBAAAAKfsCAABNAQKIAAAAAG8DAQC8AQGcAgAAAJ8BAwKkAgQAAAAwQKQFBwAAAGBATQQFJAgAAABNAwQHBQAAAJ8CAgLAAwkAMAMBEwoAAADZAwEAEgIAABIAAgAwAwGACwAAAMADDAAwAwE0DQAAAPsEAABNAwTkDgAAAPsFAABNBAXKDwAAAFIFAQCfBAICUgUAAJ8DAwLZBAMAEgIAABIAAwCCBAIAEAMQAxEDEgMTBAAAMEADFAMVBAAAYEADFgYAAwQDDQYCAw4DFwMFBAABAgMEAAEYAAAAAAAAAAEAAAAAAAAAAAEAAAYAAAAACQAAAgAAAAAAAAAAAAEAAAAFAAAAAAMAAAECAA+jAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAgAhBgAAAJ8BAgLAAgcAEgABAIICAgAIAxgEAAAAQAMZAxoDEwQAAEBAAxsGBAEEAQABGAAAAAAAAAABAAAAAAIAAAEAAAAABcYd9p8CgHqY9NmcCwiL2HbULt5eNZ6XSjj3N1osPlcpyqKFzLYBbqI=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Roact)
return function(p3)
	-- upvalues: (copy) v_u_2
	local v4 = v_u_2.Component:extend("App")
	local v_u_5 = require(script.Parent.Grid)
	function v4.init(p6)
		p6:setState({
			["countInner"] = 3,
			["countOuter"] = 4
		})
	end
	function v4.render(p7)
		-- upvalues: (ref) v_u_2, (copy) v_u_5
		return v_u_2.createElement(v_u_5, {
			["position"] = UDim2.new(1, 0, 1, 0),
			["anchorPoint"] = Vector2.new(1, 1),
			["size"] = UDim2.new(0.2, 0, 0.5, 0),
			["countInner"] = p7.state.countInner,
			["countOuter"] = p7.state.countOuter
		})
	end
	function v4.willUnmount(_) end
	local v_u_8 = v_u_2.mount(v_u_2.createElement(v4), p3)
	return function()
		-- upvalues: (ref) v_u_2, (copy) v_u_8
		v_u_2.unmount(v_u_8)
	end
end
