-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgM3BVVEaW0yA25ldwVGcmFtZRZCYWNrZ3JvdW5kVHJhbnNwYXJlbmN5BFNpemULTGF5b3V0T3JkZXIGQnV0dG9uBXByb3BzC19tYWtlQnV0dG9uCmNvdW50SW5uZXIFJXNfJWQFaW5uZXIGZm9ybWF0CmNvdW50T3V0ZXIFb3V0ZXIHVmlzaWJsZQhQb3NpdGlvbgtBbmNob3JQb2ludAdlbmFibGVkBHNpemUIcG9zaXRpb24LYW5jaG9yUG9pbnQFbWVyZ2UKR3JpZExheW91dAtBc3BlY3RSYXRpbwxVSUdyaWRMYXlvdXQIQ2VsbFNpemULQ2VsbFBhZGRpbmcTSG9yaXpvbnRhbEFsaWdubWVudBFWZXJ0aWNhbEFsaWdubWVudAtTdGFydENvcm5lcglTb3J0T3JkZXIERW51bQVSaWdodAZCb3R0b20LQm90dG9tUmlnaHQXVUlBc3BlY3RSYXRpb0NvbnN0cmFpbnQGcmVuZGVyBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlBEV6VWkKRGljdGlvbmFyeQVSb2FjdA1jcmVhdGVFbGVtZW50BnNjcmlwdAZQYXJlbnQKbWFrZUJ1dHRvbg1QdXJlQ29tcG9uZW50BEdyaWQGZXh0ZW5kBWNvbG9yBkNvbG9yMwxkZWZhdWx0UHJvcHMAAxEEAgAAACykBAIAAAQAgG8FAwCMBgAAbwcDAIwIAACfBAUCpAUCAAAEAIBvBgQAjAcAAG8IBACMCQAAnwUFAvsGAABvBwUA4ggJAIwJAQAwCQg6BgAAAKQJAgAABACAjAoBAIwLAQCMDAEAnwkEAjAJCC8HAAAAMAMIAAgAAADiCQsA+woBAE0LAAcMAAAAUgwBAFINAgCMDgEAUg8EAFIQBQCfCgcCMAoJrAoAAACfBgQAggYAAA0DAQMCBAAEAIACzczMzMzM7D8CAAAAAAAA4D8DAwMEAwUDBgUDBgcIAwcFAQoDCAAOCQEYAAAAAAAAAAEAAAAAAAACAAABAAABAAAAAAAAAAEAAQEAAAAAAAAAAAAA+wAQAAAAAA8BAgAACwAAAgMFDAIDBSECiAH/AQAAAAAAAIwEAQBNBQAHAAAAAE0CBTkBAAAAjAMBAKgCDgBvBQIAbwcDAFIIBAC8BQWNBAAAAJ8FBAJvCAMAUgkEAFIKBAC8BgA6BQAAAJ8GBQJqBgEFiwLy/4wEAQBNBQAHAAAAAE0CBR8GAAAAjAMBAKgCEwBvBQIAbwcHAFIIBAC8BQWNBAAAAJ8FBAJNCAAHAAAAAE0HCDkBAAAAQwYEB28JBwBSCgQAUgsGALwHADoFAAAAnwcFAmoHAQWLAu3/+wIAAG8DCADiBA4ATQYABwAAAABNBQaQDwAAADAFBIAJAAAAjAUBADAFBDoKAAAATQYABwAAAABNBQYPEAAAADAFBC8LAAAATQYABwAAAABNBQbbEQAAADAFBDsMAAAATQYABwAAAABNBQYIEgAAADAFBOgNAAAA+wYBAE0FBh8TAAAA4gYWAPsHAABvCBcA4gkeAKQKIQAAgPCBbwsiAIwMAACMDQEAjA4AAJ8KBQIwCgmaGAAAAKQKIQAAgPCBjAsAAIwMAACMDQAAjA4AAJ8KBQIwCgkiGQAAAKQKJQAkaDDCMAoJYhoAAACkCicAJmwwwjAKCXgbAAAApAopAChwMMIwCgmXHAAAAKQKKwAqdDDCMAoJuR0AAACfBwMCMAcG3BQAAAD7BwAAbwgsAOIJLQCMCgIAMAoJaRUAAACfBwMCMAcGaRUAAABSBwEAnwUDAJ8CAACCAgAALgMIAwoDCwMMAw0DCQMOAw8DAwMQAwQDBQMRAxIFBQkKCwwNAxMDFAMVAxYDFwMYAxkFAhQVAxoDGwMcAx0DHgMfAyAFBhgZGhscHQMBAwIEAIDwgQIAAAAAAADgPwMhAyIEJGgwwgMjBCZsMMIDJAQocDDCAwYEKnQwwgMlBQEVABsmARgAAAEAAAAAAAACAAAAAAACAAAAAAAA/AYAAAAAAAACAAAAAAABAAAAAAEAAAAAAAD8BgEBAQAAAAAAAQAAAQAAAAAAAQAAAAAAAQAAAAAAAgAAAAEAAAEAAAAAAAAAAAEAAAAAAAAAAAEAAAABAAAAAQAAAAEAAAD6AAAIAAABAAD/AAAD9PcAHAAAAAALAAABAgA6owAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMALQYAAABNAgOpBwAAAJ8BAgKkAgUAAABAQE0DACEIAAAAnwICAk0DAsoJAAAApAQFAAAAQECkBwsAAACgQE0GByQMAAAATQUGHg0AAACfBAICTQUC+A4AAABvBw8AvAUFnBAAAACfBQMC4gYSAKQHFQAAUDCBjAgBAIwJAACMCgAAnwcEAjAHBkQRAAAAMAYFkhYAAADABhcAEgADABIABAAwBgU6GAAAAMAGGQASAAMAEgABADAGBYAaAAAAggUCABsDJwQAAABAAygDKQMqBAAAQEADKwMsAy0DLgMvBAAAoEADMAMxAzIDMwM0AzUFAREDNgMCBABQMIEDNwYAAwkGAQMmAgABAQABGAAAAAAAAAABAAAAAAAAAQAAAAABAAEAAAAAAAAAAAUAAAAAAAEBAAAAAAAAAP8AAwAAAAANAAAAACYBAAAAAAJ+81zoPK3tpUw3Nnyzze2eSi6kYMXv5nRYfgKKQJHHbC+wYfGvKJOQ

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.EzUi.Dictionary)
local v3 = require(v1.Roact)
local v_u_4 = v3.createElement
local v_u_5 = require(script.Parent.makeButton)
local v6 = v3.PureComponent:extend("Grid")
v6.defaultProps = {
	["color"] = Color3.new(1, 0, 0)
}
function v6._makeButton(p7, p8, p9, p10)
	-- upvalues: (copy) v_u_4, (copy) v_u_5
	local v11 = UDim2.new(0.9, 0, 0.9, 0)
	local v12 = UDim2.new(0.5, 0, 0.5, 0)
	return v_u_4("Frame", {
		["BackgroundTransparency"] = 1,
		["Size"] = UDim2.new(1, 1, 1),
		["LayoutOrder"] = p10
	}, {
		["Button"] = v_u_5(p7.props, p8, p9, 1, v11, v12)
	})
end
function v6.render(p13)
	-- upvalues: (copy) v_u_4, (copy) v_u_2
	local v14 = {}
	for v15 = 1, p13.props.countInner do
		v14[("%s_%d"):format("inner", v15)] = p13:_makeButton("inner", v15, v15)
	end
	for v16 = 1, p13.props.countOuter do
		v14[("%s_%d"):format("outer", v16)] = p13:_makeButton("outer", v16, v16 + p13.props.countInner)
	end
	local v17 = v_u_4
	local v18 = {
		["Visible"] = p13.props.enabled,
		["BackgroundTransparency"] = 1,
		["Size"] = p13.props.size,
		["Position"] = p13.props.position,
		["AnchorPoint"] = p13.props.anchorPoint
	}
	local v19 = v_u_2.merge
	local v20 = {
		["GridLayout"] = v_u_4("UIGridLayout", {
			["CellSize"] = UDim2.new(0.5, 0, 1, 0),
			["CellPadding"] = UDim2.new(0, 0, 0, 0),
			["HorizontalAlignment"] = Enum.HorizontalAlignment.Right,
			["VerticalAlignment"] = Enum.VerticalAlignment.Bottom,
			["StartCorner"] = Enum.StartCorner.BottomRight,
			["SortOrder"] = Enum.SortOrder.LayoutOrder
		}),
		["AspectRatio"] = v_u_4("UIAspectRatioConstraint", {
			["AspectRatio"] = 2
		})
	}
	return v17("Frame", v18, v19(v20, v14))
end
return v6
