-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMZEGxpa2VQcm9tcHRDb25maWcgTElLRV9QUk9NUFRfUkVTUE9OU0VfUkVNT1RFX05BTUUORmluZEZpcnN0Q2hpbGQNUkVTUE9OU0VfRU5VTQJPawpGaXJlU2VydmVyBHR5cGUHdmlzaWJsZRNzZXRMaWtlUHJvbXB0Q29uZmlnCGRpc3BhdGNoC29uQ2xpY2tEb25lDVJlbWluZE1lTGF0ZXIJb25FeHBpcmVkBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlBnNjcmlwdAZQYXJlbnQKTGlrZVByb21wdANBcHAFc3RvcmUQTGlrZVByb21wdENvbnN0cwpSb2FjdFJvZHV4B2Nvbm5lY3QABQMCAAAAAANNAgDSAAAAAIICAgABAwEACAABGAAAAAkAAAAABQADAAAAG/sAAAD7AwEATQIDWQAAAAC8AAADAQAAAJ8AAwL7BAEATQMEWgIAAABNAgMwAwAAALwAAGsEAAAAnwADAfsAAgDiAgcAbwMIADADAnEFAAAAqQMAADADAqAGAAAAvAAATAkAAACfAAMBggABAAoDAgMDAwQDBQMGAwcDCAUCBQYDCQMKAAwLARgAAAAAAAAAAQAAAAAAAAABAAEAAAEAAP4AAAQNAAAAAAUAAwAAABv7AAAA+wMBAE0CA1kAAAAAvAAAAwEAAACfAAMC+wQBAE0DBFoCAAAATQIDtgMAAAC8AABrBAAAAJ8AAwH7AAIA4gIHAG8DCAAwAwJxBQAAAKkDAAAwAwKgBgAAALwAAEwJAAAAnwADAYIAAQAKAwIDAwMEAwwDBgMHAwgFAgUGAwkDCgAUDQEYAAAAAAAAAAEAAAAAAAAAAQABAAABAAD+AAAEFQAAAAADAQMAAAAO4gECAMACAwASAgAAEgIBABICAgAwAgFTAAAAAMACBAASAgAAEgIBABICAgAwAgFhAQAAAIIBAgAFAwsDDQUCAAEGAQYCAgECCgABGAABAAAAAAAIAAAAAAAACwAAAAAIAAABAgAuowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBApAQHAAAAYEBNAwQkCAAAAE0CA4YJAAAAnwECAqQCBQAAAEBATQQAwQoAAABNAwR+CwAAAJ8CAgKkAwUAAABAQE0FAIYJAAAATQQFhwwAAACfAwICpAQFAAAAQEBNBQAtDQAAAJ8EAgJNBQTnDgAAAMAGDwDABxAAEgAAABIAAwASAAIAnwUDAlIGAQCfBQIAggUAABEDDgQAAABAAw8DEAMRBAAAQEADEgQAAGBAAxMDFAMVAxYDFwMYAxkGAAYDAgADAQABGAABAAAAAAABAAAAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAgAAAgAAAP4VAAABAAAAAAQH7yVu04uBxzUrT/rr7VwU+mcYcIW4kBAYyI6Q3lP32u1uylyydlPq

-- Decompiled by Krnl

local v_u_1 = game:GetService("ReplicatedStorage")
local v2 = require(script.Parent.LikePrompt)
local v_u_3 = require(v_u_1.App.store)
local v_u_4 = require(v_u_1.LikePrompt.LikePromptConsts)
return require(v_u_1.RoactRodux).connect(function(p5, _)
	return p5.likePromptConfig
end, function(_)
	-- upvalues: (copy) v_u_1, (copy) v_u_4, (copy) v_u_3
	return {
		["onClickDone"] = function()
			-- upvalues: (ref) v_u_1, (ref) v_u_4, (ref) v_u_3
			v_u_1:FindFirstChild(v_u_4.LIKE_PROMPT_RESPONSE_REMOTE_NAME):FireServer(v_u_4.RESPONSE_ENUM.Ok)
			v_u_3:dispatch({
				["type"] = "setLikePromptConfig",
				["visible"] = false
			})
		end,
		["onExpired"] = function()
			-- upvalues: (ref) v_u_1, (ref) v_u_4, (ref) v_u_3
			v_u_1:FindFirstChild(v_u_4.LIKE_PROMPT_RESPONSE_REMOTE_NAME):FireServer(v_u_4.RESPONSE_ENUM.RemindMeLater)
			v_u_3:dispatch({
				["type"] = "setLikePromptConfig",
				["visible"] = false
			})
		end
	}
end)(v2)
