-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMjBnJlbmRlcgtNeUNvbXBvbmVudAZleHRlbmQFdmFsdWUJZGlkVXBkYXRlAWEQbW91bnRWaXJ0dWFsTm9kZQRUZXN0BmV4cGVjdAljYWxsQ291bnQCdG8FZXF1YWwBYhF1cGRhdGVWaXJ0dWFsTm9kZQRzZWxmCG9sZFByb3BzCG9sZFN0YXRlDWNhcHR1cmVWYWx1ZXMCb2YZU3RhdGVmdWxDb21wb25lbnRJbnN0YW5jZQhzZXRTdGF0ZQRpbml0B3JlcXVpcmUGc2NyaXB0BlBhcmVudA9hc3NlcnREZWVwRXF1YWwNY3JlYXRlRWxlbWVudBBjcmVhdGVSZWNvbmNpbGVyCWNyZWF0ZVNweQxOb29wUmVuZGVyZXIEVHlwZQlDb21wb25lbnQCaXQ0c2hvdWxkIGJlIGludm9rZWQgd2hlbiB1cGRhdGVkIHZpYSB1cGRhdGVWaXJ0dWFsTm9kZStzaG91bGQgYmUgaW52b2tlZCB3aGVuIHVwZGF0ZWQgdmlhIHNldFN0YXRlAAgCAQAAAAACxgEAAIIBAgAAABMBARgAABQAAAAADQAGAAAAZ/sAAABvAgAAvAAAnAEAAACfAAMC+wEBAJ8BAQJNAgHMAgAAADACAI4DAAAAwAIEADACAIAFAAAA4gIHAIwDBQAwAwKABgAAAPsDAgBSBAAAUgUCAJ8DAwL7BQMATQQFvggAAABSBQMAxgYAAG8HCQCfBAQCpAcLAAAAoEBNCAHkDAAAAJ8HAgJNBgeSDQAAAE0FBnsOAAAAjAYAAJ8FAgHiBRAAjAYGADAGBYAGAAAAjAYCADAGBYMPAAAA+wYCAFIHAABSCAUAnwYDAvsIAwBNBwj+EQAAAFIIBABSCQYAnwcDAaQJCwAAAKBATQoB5AwAAACfCQICTQgJkg0AAABNBwh7DgAAAIwIAQCfBwIBbwkSAG8KEwBvCxQAvAcBphUAAACfBwUCpAoLAAAAoED7DAQATQsMvBYAAABNDAewEgAAAJ8LAgCfCgACTQkKkg0AAABNCAl7DgAAAPsKBABNCQqmFwAAAJ8IAgH7CAUATQkHJBMAAABSCgIAnwgDAfsIBQBNCQfmFAAAAP8KAAAAAAAAnwgDAYIAAQAYAwIDAwMEAwUGAAMBAwYFAQYDBwMIAwkEAACgQAMKAwsDDAMNBQIGDwMOAw8DEAMRAxIDEwMUAQANAAEYAAAAAAACAAEAAAACAAAEAQAAAgAAAAQAAAAAAAACAAAAAAAAAAAAAAIBAAABAAACAAAAAQAAAAAAAgAAAAAAAAAAAAACAAAAAAACAAAAAAAAAAAAAAAAAAAAAAEAAAAAAQAAAAAAAQ4AAAAAAwABAQAAB6MAAAD7AAAA3QIAALwAACoAAAAAnwAAAIIAAAABAxUAPgABGAABAAAAAAA+AAAAAAQBAgAAAAjZAQAAEgAAAN4BAAD7AwEAvAEAKgAAAACfAQMBggABAAEDFQECPRYBGAAAAAQAAAABPgAAAAABAQAAAAABggABAAAARQEBGABFAAAAAAsABgAAAGL7AAAAbwIAALwAAJwBAAAAnwADAvsBAQCfAQECTQIBzAIAAAAwAgCOAwAAAOICBQCMAwQAMAMCgAQAAADGAwAA2QQAABIBA/8SAAIAMAQAEwYAAADABAcAMAQAgAgAAAD7BAIAUgUAAJ8EAgL7BgMATQUGvgkAAABSBgQAxgcAAG8ICgCfBQQBpAcMAAAAsEBNCAHkDQAAAJ8HAgJNBgeSDgAAAE0FBnsPAAAAjAYAAJ8FAgFSBQMA4gYFAIwHBQAwBwaABAAAAJ8FAgGkBwwAAACwQE0IAeQNAAAAnwcCAk0GB5IOAAAATQUGew8AAACMBgEAnwUCAW8HEABvCBEAbwkSALwFAaYTAAAAnwUFAqQIDAAAALBA+woEAE0JCrwUAAAATQoFsBAAAACfCQIAnwgAAk0HCJIOAAAATQYHew8AAAD7CAQATQcIphUAAACfBgIB+wYFAE0HBSQRAAAA/wgAAAAAAACfBgMB+wYFAE0HBeYSAAAAUggCAJ8GAwHBAwAAggABABYDAgMDAwQDBQMGBQEEAxYGBAMBAwcDCAMJBAAAsEADCgMLAwwDDwMQAxEDEgMTAxQCAwQyAAEYAAAAAAACAAEAAAACAQAAAwEAAAAACAAAAgAABAAAAAAAAAIAAAAAAAAAAAAAAgABAAD/BAAAAAAAAAAAAAACAAAAAAACAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAEAAAAAAQAzAAAAAAsAAAAAAGekAAEAAAAAQKQEAwAAACBATQMEJAQAAABNAgMkBAAAAE0BAmUFAAAAnwACAqQBAQAAAABApAUDAAAAIEBNBAUkBAAAAE0DBCQEAAAATQIDygYAAACfAQICpAIBAAAAAECkBgMAAAAgQE0FBiQEAAAATQQFJAQAAABNAwSLBwAAAJ8CAgKkAwEAAAAAQKQHAwAAACBATQYHJAQAAABNBQYkBAAAAE0EBQAIAAAAnwMCAqQEAQAAAABApAgDAAAAIEBNBwgkBAAAAE0GByQEAAAATQUGagkAAACfBAICpAUBAAAAAECkCQMAAAAgQE0ICSQEAAAATQcIJAQAAABNBgcRCgAAAJ8FAgKkBgEAAAAAQKQKAwAAACBATQkKJAQAAABNCAkkBAAAAE0HCIgLAAAAnwYCAlIHAgBSCAQAnwcCAqQIDQAAAMBAbwkOANkKAAASAAYAEgADABIAAQASAAcAEgAFABIAAACfCAMBpAgNAAAAwEBvCQ8A2QoBABIABgASAAMAEgABABIABwASAAUAEgAAAJ8IAwGCAAEAEAMXBAAAAEADGAQAACBAAxkDGgMbAxwDHQMeAx8DIAMhBAAAwEADIgMjAgEFAQABGAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAIAAAAAAAAAAAAAAgAAAgAAAAAAAAAAAAAlAAAAAAAAAAAAACkCAAAAAAEAAAECAAOjAAAAwAAAAIIAAgABBgYBBgEAARgAAAABAAAAAAdTZqGeMQlYOmGiywq4Kv6D0uX51m/NavVeemv6/ECw9bYEOW7Ne89V

-- Decompiled by Krnl

return function()
	local v_u_1 = require(script.Parent.Parent.assertDeepEqual)
	local v_u_2 = require(script.Parent.Parent.createElement)
	local v3 = require(script.Parent.Parent.createReconciler)
	local v_u_4 = require(script.Parent.Parent.createSpy)
	local v5 = require(script.Parent.Parent.NoopRenderer)
	local v_u_6 = require(script.Parent.Parent.Type)
	local v_u_7 = require(script.Parent.Parent.Component)
	local v_u_8 = v3(v5)
	it("should be invoked when updated via updateVirtualNode", function()
		-- upvalues: (copy) v_u_7, (copy) v_u_4, (copy) v_u_2, (copy) v_u_8, (copy) v_u_6, (copy) v_u_1
		local v9 = v_u_7:extend("MyComponent")
		local v10 = v_u_4()
		v9.didUpdate = v10.value
		function v9.render(_)
			return nil
		end
		local v11 = {
			["a"] = 5
		}
		local v12 = v_u_2(v9, v11)
		local v13 = v_u_8.mountVirtualNode(v12, nil, "Test")
		expect(v10.callCount).to.equal(0)
		local v14 = v_u_2(v9, {
			["a"] = 6,
			["b"] = 2
		})
		v_u_8.updateVirtualNode(v13, v14)
		expect(v10.callCount).to.equal(1)
		local v15 = v10:captureValues("self", "oldProps", "oldState")
		expect(v_u_6.of(v15.self)).to.equal(v_u_6.StatefulComponentInstance)
		v_u_1(v15.oldProps, v11)
		v_u_1(v15.oldState, {})
	end)
	it("should be invoked when updated via setState", function()
		-- upvalues: (copy) v_u_7, (copy) v_u_4, (copy) v_u_2, (copy) v_u_8, (copy) v_u_6, (copy) v_u_1
		local v16 = v_u_7:extend("MyComponent")
		local v17 = v_u_4()
		v16.didUpdate = v17.value
		local v_u_18 = {
			["a"] = 4
		}
		local v_u_19 = nil
		function v16.init(p_u_20)
			-- upvalues: (ref) v_u_19, (copy) v_u_18
			v_u_19 = function(...)
				-- upvalues: (copy) p_u_20
				return p_u_20:setState(...)
			end
			p_u_20:setState(v_u_18)
		end
		function v16.render(_) end
		local v21 = v_u_2(v16)
		v_u_8.mountVirtualNode(v21, nil, "Test")
		expect(v17.callCount).to.equal(0)
		v_u_19({
			["a"] = 5
		})
		expect(v17.callCount).to.equal(1)
		local v22 = v17:captureValues("self", "oldProps", "oldState")
		expect(v_u_6.of(v22.self)).to.equal(v_u_6.StatefulComponentInstance)
		v_u_1(v22.oldProps, {})
		v_u_1(v22.oldState, v_u_18)
	end)
end
