-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMaClRoZSBTZW5hdGUGZXh0ZW5kBmV4cGVjdAJ0bwJiZQJvawJvZgVlcXVhbBZTdGF0ZWZ1bENvbXBvbmVudENsYXNzBUZyYW5rBVNoZWV2BXRocm93BkZvb0Jhcgh0b3N0cmluZwFhBnN0cmluZwRmaW5kB3JlcXVpcmUGc2NyaXB0BlBhcmVudARUeXBlCUNvbXBvbmVudAJpdBRzaG91bGQgYmUgZXh0ZW5kYWJsZSlzaG91bGQgcHJldmVudCBleHRlbmRpbmcgYSB1c2VyIGNvbXBvbmVudBdzaG91bGQgdXNlIGEgZ2l2ZW4gbmFtZQAGBgACAAAAIfsAAABvAgAAvAAAnAEAAACfAAMCpAQDAAAAIEBSBQAAnwQCAk0DBJIEAAAATQIDzAUAAABNAQIQBgAAAJ8BAQGkAwMAAAAgQPsFAQBNBAW8BwAAAFIFAACfBAIAnwMAAk0CA5IEAAAATQECewgAAAD7AwEATQIDmgkAAACfAQIBggABAAoDAQMCAwMEAAAgQAMEAwUDBgMHAwgDCQAGAAEYAAAAAAACAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABBwAAAAADAAEAAAAG+wAAAG8CAAC8AACcAQAAAJ8AAwGCAAEAAgMKAwIAEAABGAAAAAAAAREAAAAABQABAAAAEPsAAABvAgAAvAAAnAEAAACfAAMCpAMDAAAAIEDZBAAAEgAAAJ8DAgJNAgOSBAAAAE0BAtsFAAAAnwEBAYIAAQAGAwsDAgMDBAAAIEADBAMMAQENAAEYAAAAAAACAAAAAAIAAAAAAQ4AAAAACQABAAAAJfsAAABvAgAAvAAAnAEAAACfAAMCuz8AA1ICAACkAQMAAAAgQJ8BAgKkBQUAAABAQFIGAQCfBQICTQQFkgYAAABNAwTMBwAAAE0CA4AIAAAAbwMJAJ8CAgGkBQUAAABAQG8IAAC8BgFWCgAAAJ8GAwCfBQACTQQFkgYAAABNAwTMBwAAAE0CAxALAAAAnwIBAYIAAQAMAw0DAgMOBAAAIEADAwQAAEBAAwQDBQMPAxADEQMGABUAARgAAAAAAAIAAAAAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAABFgAAAAAGAAAAAAAqpAABAAAAAECkBAMAAAAgQE0DBCQEAAAATQIDJAQAAABNAQIRBQAAAJ8AAgKkAQEAAAAAQKQFAwAAACBATQQFJAQAAABNAwQkBAAAAE0CA4gGAAAAnwECAqQCCAAAAHBAbwMJANkEAAASAAEAEgAAAJ8CAwGkAggAAABwQG8DCgDZBAEAEgABAJ8CAwGkAggAAABwQG8DCwDZBAIAEgABAJ8CAwGCAAEADAMSBAAAAEADEwQAACBAAxQDFQMWAxcEAABwQAMYAxkDGgMAAgMBAAEYAAAAAAAAAAAAAAACAAAAAAAAAAAAAAIAAAAAAAAHAAAAAAAIAAAAAAAIAgAAAAABAAABAgADowAAAMAAAACCAAIAAQYEAQQBAAEYAAAAAQAAAAAFhoI9ZSn6y7u0Rlfx1J+btEoVyLCe+g97p9/QvYjALPkdQ34Qv28bBw==

-- Decompiled by Krnl

return function()
	local v_u_1 = require(script.Parent.Parent.Type)
	local v_u_2 = require(script.Parent.Parent.Component)
	it("should be extendable", function()
		-- upvalues: (copy) v_u_2, (copy) v_u_1
		local v3 = v_u_2:extend("The Senate")
		expect(v3).to.be.ok()
		expect(v_u_1.of(v3)).to.equal(v_u_1.StatefulComponentClass)
	end)
	it("should prevent extending a user component", function()
		-- upvalues: (copy) v_u_2
		local v_u_4 = v_u_2:extend("Sheev")
		expect(function()
			-- upvalues: (copy) v_u_4
			v_u_4:extend("Frank")
		end).to.throw()
	end)
	it("should use a given name", function()
		-- upvalues: (copy) v_u_2
		local v5 = v_u_2:extend("FooBar")
		local v6 = tostring(v5)
		expect(v6).to.be.a("string")
		expect(v6:find("FooBar")).to.be.ok()
	end)
end
