-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgOZAQ1DdXJyZW50Q2FtZXJhDHNldG1ldGF0YWJsZQFmAXABdgNuZXcGVXBkYXRlBVJlc2V0BmZDdXJ2ZQlmRGVhZHpvbmUPdGh1bWJzdGlja0N1cnZlAlVwBERvd24LVGh1bWJzdGljazEBWAhCdXR0b25SMghCdXR0b25MMgFZB1ZlY3RvcjMBRAFBAUsBSAFFAVEBSQFTAVcBSgFVBEVudW0HS2V5Q29kZQlMZWZ0U2hpZnQJSXNLZXlEb3duClJpZ2h0U2hpZnQDVmVsB1ZlY3RvcjILVGh1bWJzdGljazIFRGVsdGEDUGFuB0J1dHRvblgHQnV0dG9uWQpNb3VzZVdoZWVsA0ZvdgROYW1lDlVzZXJJbnB1dFN0YXRlBUJlZ2luE0NvbnRleHRBY3Rpb25SZXN1bHQEU2luawhLZXlwcmVzcwhHcEJ1dHRvbgF5AXgITW91c2VQYW4IUG9zaXRpb24FVGh1bWIBegdUcmlnZ2VyDVVzZXJJbnB1dFR5cGUFcGFpcnMEWmVybw9GcmVlY2FtS2V5Ym9hcmQUQmluZEFjdGlvbkF0UHJpb3JpdHkPRnJlZWNhbU1vdXNlUGFuDU1vdXNlTW92ZW1lbnQRRnJlZWNhbU1vdXNlV2hlZWwURnJlZWNhbUdhbWVwYWRCdXR0b24VRnJlZWNhbUdhbWVwYWRUcmlnZ2VyGEZyZWVjYW1HYW1lcGFkVGh1bWJzdGljawxTdGFydENhcHR1cmUMVW5iaW5kQWN0aW9uC1N0b3BDYXB0dXJlDFZpZXdwb3J0U2l6ZQtyaWdodFZlY3Rvcgh1cFZlY3Rvcgpsb29rVmVjdG9yA1JheQR1bml0DUZpbmRQYXJ0T25SYXkJbWFnbml0dWRlA0RvdBBHZXRGb2N1c0Rpc3RhbmNlBkNGcmFtZQ9mcm9tT3JpZW50YXRpb24FRm9jdXMLRmllbGRPZlZpZXcLU3RlcEZyZWVjYW0LQ29yZUd1aVR5cGURR2V0Q29yZUd1aUVuYWJsZWQRU2V0Q29yZUd1aUVuYWJsZWQHR2V0Q29yZQdTZXRDb3JlCVBsYXllckd1aRVGaW5kRmlyc3RDaGlsZE9mQ2xhc3MLR2V0Q2hpbGRyZW4JU2NyZWVuR3VpA0lzQQdFbmFibGVkCkNhbWVyYVR5cGUGQ3VzdG9tEE1vdXNlSWNvbkVuYWJsZWQNTW91c2VCZWhhdmlvcgdEZWZhdWx0BFB1c2gGUGFyZW50A1BvcBB0b0V1bGVyQW5nbGVzWVhaB0ZyZWVjYW0OUmVuZGVyUHJpb3JpdHkGQ2FtZXJhBVZhbHVlEEJpbmRUb1JlbmRlclN0ZXAMU3RhcnRGcmVlY2FtFFVuYmluZEZyb21SZW5kZXJTdGVwC1N0b3BGcmVlY2FtDVRvZ2dsZUZyZWVjYW0KQ2hlY2tNYWNybwRQYXNzFUhhbmRsZUFjdGl2YXRpb25JbnB1dARtYXRoA2FicwVjbGFtcANleHADcmFkBHNpZ24Ec3FydAN0YW4EZ2FtZRRDb250ZXh0QWN0aW9uU2VydmljZQpHZXRTZXJ2aWNlB1BsYXllcnMKUnVuU2VydmljZQpTdGFydGVyR3VpEFVzZXJJbnB1dFNlcnZpY2UJV29ya3NwYWNlC0xvY2FsUGxheWVyGEdldFByb3BlcnR5Q2hhbmdlZFNpZ25hbARXYWl0B0Nvbm5lY3QVQ29udGV4dEFjdGlvblByaW9yaXR5A0xvdwRIaWdoAVAHX19pbmRleAhEUGFkRG93bgZEUGFkVXAIQmFja3BhY2sEQ2hhdAZIZWFsdGgKUGxheWVyTGlzdBlCYWRnZXNOb3RpZmljYXRpb25zQWN0aXZlGVBvaW50c05vdGlmaWNhdGlvbnNBY3RpdmUNRnJlZWNhbVRvZ2dsZQAdAgACAAAABvsBAABNAAFIAAAAAA4AAQDeAAEAggABAAEDAQAdAAEYAAAAAQECHgAAAAAFAgEAAAAQ/wMDAAAAAAD7BAAAnj0DAwQAAACkAgEAAAAAQJ8CAwIwAAKHAgAAADABApEDAAAAWwMBBDADApcFAAAAggICAAYDAgQAAABAAwMDBAIAAAAAAAAAAAMFADkGARgAAAAAAAAAAAEAAQABAAABOgAAAAAPAwEAAAAgTQUAhwIAAABbBAUBWwMEAE0EAJEDAAAATQUAlwQAAAAmBgIEOQkDAAkICQG7CwgB+wcAAJ8HAgIJCwUBCQ4DAZUNDgUJDAYNJgoLDAkJCgdDCAIJCQwDAQkOBgMmDQ4FCQsMDUMKCwUJCQoHMAgAkQMAAAAwCQCXBAAAAIIIAgAGAhgtRFT7IQlAAgAAAAAAAABAAwMDBAMFAgAAAAAAAPA/AEEHARgAAAAAAQABAAIBAAAAAAIAAAAAAAABAAAAAAACAAEAAkIAAAAAAwIAAAAABjABAJEAAAAAWwIBATACAJcCAAAAggABAAMDBAIAAAAAAAAAAAMFAFIIARgAAAEAAAFTAAAAAAYBAQAAAAiMBQIACQQFALsLBAH7AwAAnwMCAngCAwE+AQIAggECAAICrt3UuGSOGUACAAAAAAAA8D8AaQkBGAAAAAAAAAAAagAAAAAHAQEAAAAKeAMAAT4CAwCMBgIACQUGArsLBQH7BAAAnwQCAngDBAM+AQMCggECAAQCMzMzMzMz6z8CMzMzMzMzwz8Crt3UuGSOGUACAAAAAAAA8D8AbQoBGAQA/AAAAAAAAABqAAAAAAsBBAAAABi7LwACUgMAAPsCAACfAgICuwIAAlIGAAD7BQEAnwUCAngHBQE+BgcAjAoCAAkJCga7CwkB+wgCAJ8IAgJ4BwgDPgQHAowFAACMBgEATC4AAfsDAwCfAwQCCQECA4IBAgAEAjMzMzMzM+s/AjMzMzMzM8M/Aq7d1LhkjhlAAgAAAAAAAPA/AHELARgIAAAAAAAAAPwA/AAAAAAAAAgAAAAAAABqAAAAAAwBBgAADwAAAwgCMAEIA2MBCAV4AXr7AwAA+wgBAE0HCHMBAAAA+wkBAE0ICR4CAAAAJgYHCAkFAAZbBAUAQwIDBG8DAwCMBAQATC4AAfsBAgCfAQQC3gEAAPsDAwD7BgQATQUGnAQAAABNBAV5BQAAAJ8DAgL7BQMA+wcEAE0GB34GAAAAnwUCAvsGAwD7CAQATQcIfgcAAACfBgICJgQFBvsFAwD7CQQATQgJnAQAAABNBwh4CAAAADkGBwCfBQIATDYAAqQCCwAAKJCAnwIAAm8DDAAJAQID+wgBAE0HCGUNAAAA+wkBAE0ICWAOAAAAJgYHCPsIAQBNBwhqDwAAAEMFBgf7BwEATQYHaRAAAAAmBAUG+wkBAE0ICWQRAAAA+woBAE0JCnASAAAAJgcICfsJAQBNCAloEwAAAEMGBwj7CAEATQcIeAgAAAAmBQYH+woBAE0JCnIUAAAA+wsBAE0KC3YVAAAAJggJCvsKAQBNCQprFgAAAEMHCAn7CQEATQgJdBcAAAAmBgcITDYAAqQDCwAAKJCAnwMEAm8EDAAJAgME+wMFAKQFGwAaZIDBvAMDbBwAAACfAwMCKwMGAPsDBQCkBR4AHWSAwbwDA2wcAAAAnwMDAkMFAQL7BwAADgMCAG8IHwBlAAEAjAgBAAkGBwgJBAUGggQCACACAAAAAAAA6D8DDAMNAnsUrkfheoQ/Aw4DDwMQAxEDEgMTAwYEACiQgAcAAIA/AACAPwAAgD8AAAAAAxQDFQMWAxcDGAMZAxoDGwMcAx0DHgMfAyADIQQaZIDBAyIDIwQdZIDBAgAAAAAAANA/AKQBJAEYAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAP0AAAAEAAMAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAP0AAAAEAAIAAAAAAAAAAAAAAAACAAAAAAAAAAClAAAAAAkBBQAAACGkAgIAAAQAgPsDAAD7BgEATQUGiQMAAABNBAV4BAAAAJ8DAgL7BAAA+wgBAE0HCIkDAAAATQYHeQUAAAA5BQYAnwQCAJ8CAAL7AwIACQECA/sEAwBNAwT2BgAAAPsEBAAJAgME+wMDAKQEAgAABACAnwQBAjAEA/YGAAAAQwMBAoIDAgAHAyUDBgQABACAAyYDEgMPAycAuAEoARgAAAEAAAAAAAABAAAAAAAAAP4DAAEAAAAAAQAAAAAAAQC5AAAAAAYBAgAAABL7BAAATQMEZAEAAAD7BQAATQQFfgIAAAAmAgMEWwECAPsEAQBNAwSVBAAAAFsCAwP7AwEAjAQAADAEA5UEAAAAQwMBAoIDAgAFAgAAAAAAANA/AykDKgIAAAAAAADwPwMrAMIBLAEYAAAAAAAAAAABAAAAAQAAAAEAwwAAAAAHAwEAAAAQ+wMAAE0FArMAAAAATQQFugEAAACkBgUABAwgwJoBAwAGAAAAjAUBAGUAAQCMBQAAagUDBKQDCAAHGCDAggMCAAkDIAMtAx8DLgMvBAQMIMADMAMxBAcYIMAAygEyARgAAAAAAAAAAAAAAAAAAQAAywAAAAAHAwEAAAAQ+wMAAE0FArMAAAAATQQFugEAAACkBgUABAwgwJoBAwAGAAAAjAUBAGUAAQCMBQAAagUDBKQDCAAHGCDAggMCAAkDIAMtAx8DLgMvBAQMIMADMAMxBAcYIMAAzwEzARgAAAAAAAAAAAAAAAAAAQAA0AAAAAAJAwEAAAARTQMC9gAAAAD7BAAApAUDAAAIEIBNBwOYBAAAADkGBwBNCAOZBQAAADkHCACfBQMCMAUE9gAAAACkBAkACBxgwIIEAgAKAycDJQMGBAAIEIADNAM1Ax8DMAMxBAgcYMAA1AE2ARgAAAEAAAAAAAAAAAAAAAEAANUAAAAABgMBAAAAC/sDAABNBQKzAAAAAE0EBboBAAAATQUCOwIAAABqBQMEpAMGAAUQMMCCAwIABwMgAy0DNwMfAzADMQQFEDDAANoBOAEYAAAAAAAAAAABAADbAAAAAAcDAQAAAA37AwAATQUCswAAAABNBAW6AQAAAE0GAjsCAAAATQUGmwMAAABqBQMEpAMHAAYUQMCCAwIACAMgAy0DNwM5Ax8DMAMxBAYUQMAA3wE6ARgAAAAAAAAAAAAAAQAA4AAAAAAIAwEAAAAO+wMAAE0FAsIAAAAATQQFugEAAABNBwI7AgAAAE0GB5sDAAAAOQUGAGoFAwSkAwcABhRAwIIDAgAIAzsDLQM3AzkDHwMwAzEEBhRAwADkASsBGAAAAAAAAAAAAAAAAQAA5QAAAAAHAQAAAAAKpAEBAAAAAEBSAgAAnwECBBcBAgBbBgUCagYABG4B/f8CAAAAggABAAMDPAQAAABAAgAAAAAAAAAAAOkBPQEYAAAAAAABAP8AA+oAAAAAFAAIAAAAXfsAAABvAgAA+wMBAKkEAAD7BQIApAYEAAMIEMCkBwYABQgQwKQICAAHCBDApAkKAAkIEMCkCgwACwgQwKQLDgANCBDApAwQAA8IEMCkDRIAEQgQwKQOFAATCBDApA8WABUIEMCkEBgAFwgQwKQRGgAZCBDApBIcABsIEMCkEx4AHQgQwLwAAIEfAAAAnwAUAfsAAABvAiAA+wMDAKkEAAD7BQIApAYjACKEEMC8AACBHwAAAJ8ABwH7AAAAbwIkAPsDBACpBAAA+wUCAKQGJgAlhBDAvAAAgR8AAACfAAcB+wAAAG8CJwD7AwUAqQQAAPsFAgCkBikAKAgQwKQHKwAqCBDAvAAAgR8AAACfAAgB+wAAAG8CLAD7AwYAqQQAAPsFAgCkBi4ALQgQwKQHMAAvCBDAvAAAgR8AAACfAAgB+wAAAG8CMQD7AwcAqQQAAPsFAgCkBjMAMggQwKQHNQA0CBDAvAAAgR8AAACfAAgBggABADYDPgMfAyADHAQDCBDAAx4EBQgQwAMVBAcIEMADFwQJCBDAAxsECwgQwAMdBA0IEMADFAQPCBDAAxYEEQgQwAMYBBMIEMADGgQVCBDAAxkEFwgQwAMSBBkIEMADDAQbCBDAAw0EHQgQwAM/A0ADOwNBBCKEEMADQgMrBCWEEMADQwMpBCgIEMADKgQqCBDAA0QDEAQtCBDAAxEELwgQwANFAw4EMggQwAMmBDQIEMAA7wFGARgAAAAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAD5AAAJAAAAAAAAAAAAAQAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAHwAAAAAAcABQAAAD+MAAEA3gAAAPsAAQCkAQEAAAAAQFICAACfAQIEFwECAFsGBQJqBgAEbgH9/wIAAAD7AAIApAEBAAAAAEBSAgAAnwECBBcBAgBbBgUCagYABG4B/f8CAAAA+wADAKQBAQAAAABAUgIAAJ8BAgQXAQIAWwYFAmoGAARuAf3/AgAAAPsABABvAgMAvAAAFgQAAACfAAMB+wAEAG8CBQC8AAAWBAAAAJ8AAwH7AAQAbwIGALwAABYEAAAAnwADAfsABABvAgcAvAAAFgQAAACfAAMB+wAEAG8CCAC8AAAWBAAAAJ8AAwH7AAQAbwIJALwAABYEAAAAnwADAYIAAQAKAzwEAAAAQAIAAAAAAAAAAAM+A0cDQANCA0MDRANFAIACSAEYFwAB6AAAAAABAP8AGecAAAAAAQD/ABrmAAAAAAEA/wAbAAAAAAEAAAAAAQAAAAABAAAAAAEAAAAAAQAAAAAB6gAAAAAZAQQAAABJ+wIAAE0BArAAAAAA+wUBAD4EBQG7GwQB+wMCAJ8DAgJbAgMBTQUBmQIAAABNBgGYAwAAAOwEBQYJAwQCTQQAbQQAAABNBQAxBQAAAE0GAEgGAAAATDYAAqQHCQAAIHCAnwcBAowIAAKMCwAAjAkBAG8KCgCoCSUAjA4AAIwMAQBvDQoAqAwgAHgQCwoJDxADeBEOCgkQEQIJEwQPCRQFECYSExRDERIGTRMAkQsAAABbFBEMQxITFPsTAwCkFQ4AACDQgFIWEgBNGBEnDwAAAAkXGAifFQMAvBMT7RAAAACfEwADJhYUEk0VFsoRAAAAYBUEAAgAAABSCBUATQcRJw8AAACLDOD/iwnb/1IMBwC8CgYrEgAAAJ8KAwIJCQoIggkCABMDSQIAAAAAAAAAQAM1AzQDSgNLA0wDEwMGBAAgcIACAAAAAAAA4D8DBAKamZmZmZm5PwNNBAAg0IADTgNPA1ADUQCPAlIBGAAAAAEAAAAAAAEAAAAAAAEAAQABAAIAAAABAgAAAAEAAAABAAEAAQAAAAEAAAABAAAAAAAAAAAAAAEAAAEAAQEA9/8PAAAAAAARAQAAAA4BDgAAAHr7AQAAUgMAAPsFAQBNBAVUAAAAAFIFAACfBAIAvAEBJgEAAACfAQAC+wICAFIEAAD7BgEATQUG1wIAAABSBgAAnwUCALwCAiYBAAAAnwIAAvsDAwBSBQAA+wcBAE0GB9sDAAAAUgcAAJ8GAgC8AwMmAQAAAJ8DAAL7CQQAPggJBbsWCAH7BwUAnwcCArsbBwH7BgYAnwYCAtgFBAa7GQUB+wQHAJ8EAgL7BwQAWwkDBuwKAAQJCAkKQwYHCIwHAQCMCHgATC4AAfsFCACfBQQC3gUEAPsGCQD7CQoACQgCCewJAAQJBwgJQwUGB94FCQCkBQkAACBwgPsICQBNBwiZCgAAAG8ICwBvCQwATC4AAfsGCACfBgQC+wkJAE0ICZgOAAAAIQcIDZ8FAwLeBQkApAcQAAAg8ID7CAsAnwcCAqQIEgAARPCA+woJAE0JCpkKAAAA+wsJAE0KC5gOAAAAjAsAAJ8IBAIJBgcIpAcQAAAg8IBvChMACQkBCgkICQCfBwICCQUGB00GBZEUAAAA3gYLAPsGDAAwBQaFDwAAAPsGDACkCBAAACDwgIwJAACMCgAA+wwNAFINBQCfDAICOQsMAJ8IBAIJBwUIMAcGyxUAAAD7BgwA+wcEADAHBmEWAAAAggABABcDJAMHAygDLAJ6v6CjGWjmPwIAAAAAAAAAQAIAAAAAAMByQAMlAwYEACBwgAM1AhgtRFT7Ifm/AhgtRFT7Ifk/AhgtRFT7IRlAAzQDUwQAIPCAA1QEAETwgAcAAIBCAACAQgAAgEIAAAAAAwQDVQNWAK8CVwEYAAAAAAAAAAAAAAEAAAAAAAAAAAABAAAAAAAAAAAAAgAAAAAAAAAAAAAAAgAAAAAAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAACAAABAAAAAAAAAAAAAAAAAQAAAAEwAQAAAAoADQAAAHakAAEAAAAAQPsBAACfAAIEFwARAPsFAAD7BgEApAkEAAAMIICHCAkDvAYGLAUAAACfBgMCagYFA/sFAQCkCAQAAAwggIcHCAOpCAAAvAUFGAYAAACfBQQBbgDu/wEAAACkAAEAAAAAQPsBAgCfAAIEFwANAPsFAgD7BgEAUggDALwGBosHAAAAnwYDAmoGBQP7BQEAUgcDAKkIAAC8BQW/CAAAAJ8FBAFuAPL/AQAAAPsAAwBvAgkAvAAAuAoAAACfAAMCDgAZAKQBAQAAAABAvAIAaAsAAACfAgIAnwEABBcBEABvCAwAvAYF/g0AAACfBgMCDgYLAE0GBfAOAAAADgYIAPsGBAD7CQQAHAgJAJUHCA9qBQYHqQYAADAGBfAOAAAAbgHv/wIAAAD7AgYATQECYRAAAADeAQUA+wEGAIwCRgAwAgFhEAAAAPsCBgBNAQIqEQAAAN4BBwD7AQYApAITABJEIMAwAgEqEQAAAPsCBgBNAQKFFAAAAN4BCAD7AgYATQECyxUAAADeAQkA+wILAE0BAqsWAAAA3gEKAPsBCwCpAgAAMAIBqxYAAAD7AgsATQEC6BcAAADeAQwA+wELAKQCGQAYXCDAMAIB6BcAAACCAAEAGgM8BAAAAEADHwNYBAAMIIADWQNaA1sDXANdA14DXwNgA2EDYgIAAAAAAADwPwNWA2MDZAQSRCDAA1MDVQNlA2YDZwQYXCDAANgCaAEYAAAAAAABAAAAAAAAAAABAAAAAAAAAP4ABAAAAAABAAAAAAAAAQAAAAAA/gAEAAAAAAEBAAAAAAAAAQAAAAAAAAABAAAAAAEAAP0ACAAAAAEAAAACAAAAAQAAAAACAAAAAQAAAAIAAAABAAAAAgAAAAEAAAAAAVkBAAAACQAMAAAATqQAAQAAAABA+wEAAJ8AAgQXAAgA+wUBAKQIBAAADCCAhwcIA1IIBAC8BQUYBQAAAJ8FBAFuAPf/AgAAAKQAAQAAAABA+wECAJ8AAgQXAAYA+wUBAFIHAwBSCAQAvAUFvwYAAACfBQQBbgD5/wIAAACkAAEAAAAAQPsBAwCfAAIEFwAGAE0FBCQHAAAADgUDAKkFAQAwBQTwCAAAAG4A+f8CAAAA+wAEAPsBBQAwAQBhCQAAAMYAAADeAAUA+wAEAPsBBgAwAQAqCgAAAMYAAADeAAYA+wAEAPsBBwAwAQCFCwAAAMYAAADeAAcA+wAEAPsBCAAwAQDLDAAAAMYAAADeAAgA+wAJAPsBCgAwAQCrDQAAAMYAAADeAAoA+wAJAPsBCwAwAQDoDgAAAMYAAADeAAsAggABAA8DPAQAAABAAx8DWAQADCCAA1oDXANpA2IDVgNjA1MDVQNlA2YA/AJqARgAAAAAAAEAAAAAAAAA/wADAAAAAAEAAAAAAP8AAwAAAAABAAABAAD+AAYAAAABAAIAAAABAAIAAAABAAIAAAABAAIAAAABAAIAAAABAAF9AQAAAAYACwAAADj7AQAATQABhQAAAACkAQMAAAgQgLwCAHgEAAAAnwICAJ8BAALeAQEATQEAkQUAAADeAQIA+wIAAE0BAmEGAAAA3gEDAPsBBABMNgACpAMIAAAIcICfAwECvAEBfwkAAACfAQMB+wEFAKQDAwAACBCAnwMBALwBAX8JAAAAnwEAAfsBBgCMAwAAvAEBfwkAAACfAQMB+wIHAE0BAhkKAAAAnwEBAfsBCABvAwsApAUPAA40wMBNBAXsEAAAAPsFCQC8AQFvEQAAAJ8BBQH7AgoATQECMhIAAACfAQEBggABABMDUwMlAwYEAAgQgANrAwQDVgMTBAAIcIADCANoA2wDHwNtA24EDjTAwANvA3ADRgCdA3EBGAAAAAEAAAAAAAABAAABAAAAAgAAAAAAAAABAAAAAAAAAQAAAAACAAAAAQAAAAAAAAAAAAEAAAABngEAAAADAAMAAAAO+wEAAE0AAekAAAAAnwABAfsAAQBvAgEAvAAAJwIAAACfAAMB+wECAE0AAZQDAAAAnwABAYIAAQAEA0gDbANyA2oArANzARgAAAAAAQAAAAABAAAAAa0BAAAAAwAFAAAAFvsAAAAOAA4A+wEBAE0AAekAAAAAnwABAfsAAgBvAgEAvAAAJwIAAACfAAMB+wEDAE0AAZQDAAAAnwABAWUAAgD7AAQAnwABAfsBAABWAAEA3gAAAIIAAQAEA0gDbANyA2oAtwN0ARgLAPUAAAABAAAAAAEAAAAADAACAAABrQEAAAAHAQYAAAAjjAMBABwEAAB4AQQAjAIBAKgBCAD7BAAAhwYAA7wEBGwBAAAAnwQDAisEAQCCAAEAiwH4//sBAQAOAQ4A+wICAE0BAukCAAAAnwEBAfsBAwBvAwMAvAEBJwQAAACfAQMB+wIEAE0BApQFAAAAnwEBAWUAAgD7AQUAnwEBAfsCAQBWAQIA3gEBAIIAAQAGAgAAAAAAAPA/AyIDSANsA3IDagDAA3UBGBQAAAAAAQAAAAAAAf73APUAAAABAAAAAAEAAAAADAACAAAKrQEAAAAIAwIAAAASpAMDAAIEAMCaAQwAAwAAAE0DArMEAAAA+wUAAPsHAAAcBgcAhwQFBpoDBAAEAAAA+wMBAPsEAACfAwIBpAMHAAYUAMCCAwIACAMfAy4DLwQCBADAAyADMAN2BAYUAMAAyQN3ARgAAAAAAQAAAAAAAAABAAADAADKAQAAACwAAAECALIDowAAAKQAAgAABACApAEEAAAMAICkAgYAABQAgKQDCAAAHACApAQKAAAkAICkBQwAACwAgKQGDgAANACApAcQAAAA8EBvCREAvAcHFhIAAACfBwMCpAgQAAAA8EBvChMAvAgIFhIAAACfCAMCpAkQAAAA8EBvCxQAvAkJFhIAAACfCQMCpAoQAAAA8EBvDBUAvAoKFhIAAACfCgMCpAsQAAAA8EBvDRYAvAsLFhIAAACfCwMCpAwQAAAA8EBvDhcAvAwMFhIAAACfDAMCTQ0IMRgAAAArDQkAbxAYALwOCJQZAAAAnw4DArwODvcaAAAAnw4CAU0NCDEYAAAATQ4MSBsAAABvERsAvA8MlBkAAACfDwMC2REAABIADAASAQ7/vA8PxxwAAACfDwMBpBAgAB940MFNDxDsIQAAAKQRIwAieNDBTRAR7CEAAAD/EQAAAgAAAKQSJgAlkNDBpBMoACeQ0MHFERIDAQAAAKQTLAAArKCCbxQtAIwVAQCfEwMCWxITKf8TAwAAAAAAMBMTbi4AAADAFC8AEgATADAUE+8rAAAAwBQwABIAAgAwFBMmMQAAAMAUMgAwFBN/MwAAAEw2AAKkFDUAAKxAg58UAQKkFSwAAKyggp8VAQKMFgAATRcT7ysAAABvGDYATDYAAqQZNQAArECDnxkBAp8XAwJNGBPvKwAAAIwZAQCkGiwAAKyggp8aAQCfGAACTRkT7ysAAACMGgQAjBsAAJ8ZAwL/GgQAAAAAAMYbAADAHDcAEgACAMAdOAASAAIAwBs5ABIABAASAAAAEgACABIAAQDiHEIAjB0AADAdHGQ6AAAAjB0AADAdHH47AAAAjB0AADAdHP08AAAAjB0AADAdHPg9AAAAjB0AADAdHH4+AAAAjB0AADAdHH4/AAAApB0sAACsoIKfHQECMB0cnEAAAACkHSwAAKyggp8dAQIwHRyJQQAAAOIdUgCMHgAAMB4ddkMAAACMHgAAMB4dYEQAAACMHgAAMB4dckUAAACMHgAAMB4dZUYAAACMHgAAMB4dZEcAAACMHgAAMB4dcEgAAACMHgAAMB4ddEkAAACMHgAAMB4daUoAAACMHgAAMB4da0sAAACMHgAAMB4dakwAAACMHgAAMB4daE0AAACMHgAAMB4deE4AAACMHgAAMB4dc08AAACMHgAAMB4dHlAAAACMHgAAMB4dCCUAAACMHgAAMB4do1EAAADiHlUApB8sAACsoIKfHwECMB8e9lMAAACMHwAAMB8elVQAAACkICwAAKyggowhAQCMIgEAnyADAlsfIFakISwAAKyggowiAQCMIwEAnyEDAlsgIVeMIQEA2SIHABIBIf8SAB0AEgABABIBG/8SABwAEgALADAiGlRYAAAA2SIIABIBG/8SABwAEgAgABIAHgASAB8AMCIa11kAAADAIloAEgAcABIAHgAwIhrbWwAAAMAiXAASAB0AwCNdABIAHADAJF4AEgAeAMAlXwASABwAwCZgABIAHADAJ2EAEgAeAMAoYgDAKWMAEgAHABIAIgASABAAEgAkABIAJwASACMAEgAmABIAJQAwKRoyZAAAANkpEgASASH/EgAcABIAHQASAB4AEgAHADApGullAAAAwRsAANkbEwASAQ7/EgEW/xIABgASAAwA2RwUABIAFwASABoAEgAYABIAGQASARb/EgADABIABgASAAUAEgABABIBFf8SABIAEgEU/xIBDv8SABsA/x0CAAAAAADGHgAAxh8AAMYgAADGIQAAxiIAAMYjAAD/JAAAAAAAAOIlagCpJgEAMCYlr2YAAACpJgEAMCYlx2cAAACpJgEAMCYlWmgAAACpJgEAMCYlQWkAAADiJm0AqScBADAnJjxrAAAAqScBADAnJtJsAAAA2ScVABIAJQASAAoAEgAmABIBDf8SACQAEgEj/xIBDv8SASD/EgEi/xIBIf8SAR//EgALABIBHv8wJx0ZbgAAANknFgASACUAEgAKABIAJgASACQAEgEO/xIBI/8SASD/EgEi/xIBIf8SAAsAEgEf/xIBHv8wJx2UbwAAAMEeAADZHhcAEgEO/xIBFf8SART/EgEW/xIAFwASABgAEgAZABIAHQASAAkAEgAcABIAGgDAH3AAEgAaABIACQASAB0AqSAAANkhGQASASD/EgAaABIACQASAB0AEgAeANkiGgASAAsAEgEg/xIAGgASAAkAEgAdABIAHgDAI3EAEgARABIAIgBvJnIAUicjAKkoAABSKQ8AHCsRAIcqESu8JAeBcwAAAJ8kBwHBIAAAwQ0AAIIAAQB0A3gDeQQABACAA3oEAAwAgAN7BAAUAIADfAQAHACAA30EACQAgAN+BAAsAIADfwQANACAA4ABBAAA8EADgQEDggEDgwEDhAEDhQEDhgEDhwEDiAEDiQEDigEDAQOLAQMfA4wBA40BBB940MEDbwOOAQQieNDBAyADIQQlkNDBA48BBCeQ0MECAAAAAAAAIEADJQMGBACsoIICAAAAAAAA6D8DkAEGAQYCAwcGAwMIAxMEAKxAgwIAAAAAAAD4PwYEBgUGBgMpAyoDkQEDkgEDEQMQAw4DJgUIOjs8PT4/QEEDHAMVAxsDFAMYAxkDHgMXAx0DFgMaAxIDDAMNAyMFEENERUZHSElKS0xNTk9QJVEDJwMrBQJTVAIYLURU+yGpPwIYLURU+yHZPwMkAygGCQMsBgoGCwYMBg0GDgYPBhAGEQNGA0gDkwEDlAEDlQEDlgEFBGZnaGkDlwEDmAEFAmtsA2gDagYYBhsDmQEDPxwAAQIDBAUGBwgJCgsMDQ4PEBESExQVFhcYGRobAQABBwAGAAEAAQABAAEAAQABAAIAAAAAAAEAAAAAAAEAAAAAAAEAAAAAAAEAAAAAAAEAAAAAAAIAAQEAAAAAAAABAAMAAQAAAAAAAAAAAAkAAAABAAAAAQAAAAAAAAADAAAAAAALAAEAAgAAAAgAAAARAAAIAAAAAQAAAQIAAAAAAAAAowAAAAAAAAEAAAAABAABBAAEAAQAAAAABQEAAAEAAAEAAAEAAAEAAAEAAAEAAAAAAQAAAAADAQAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAQAAAwEAAAAAAQAABQAAAAAAAQAAAAAABgIAAAC7AAAAABQAAAAAAAAACgAAAAAIAAUABQAGAAUABQAFBgAAAAAAAAAAAAARAAAAAAAAAAAPAAAAACAAAAAAAAAAAAAAAAAAABUAAQEBAQEBAQABAQAAAQAAAQAAAQAAAgEAAAEAAAQAAAAAAAAAAAAAAAAAAAAkAAAAAAAAAAAAACgAAAAAIQAAAAAAAAAAAAAADwAAAAkCAAAAAAAJAAAAAAAACQAACQAAAAAAAAAAAAEAAQAAAF4AAABFAAAA2AAAAAAc0r223nqmlejgedxKC7jwsGnE9pZMTII8xPpsESJke22te58MtJbzgg==

-- Decompiled by Krnl

local v_u_1 = math.abs
local v_u_2 = math.clamp
local v_u_3 = math.exp
local v_u_4 = math.rad
local v_u_5 = math.sign
local v_u_6 = math.sqrt
local v_u_7 = math.tan
local v_u_8 = game:GetService("ContextActionService")
local v9 = game:GetService("Players")
local v_u_10 = game:GetService("RunService")
local v_u_11 = game:GetService("StarterGui")
local v_u_12 = game:GetService("UserInputService")
local v_u_13 = game:GetService("Workspace")
local v_u_14 = v9.LocalPlayer
if not v_u_14 then
	v9:GetPropertyChangedSignal("LocalPlayer"):Wait()
	v_u_14 = v9.LocalPlayer
end
local v_u_15 = v_u_13.CurrentCamera
v_u_13:GetPropertyChangedSignal("CurrentCamera"):Connect(function()
	-- upvalues: (copy) v_u_13, (ref) v_u_15
	local v16 = v_u_13.CurrentCamera
	if v16 then
		v_u_15 = v16
	end
end)
local v17 = Enum.ContextActionPriority.Low.Value
local v_u_18 = Enum.ContextActionPriority.High.Value
local v_u_19 = { Enum.KeyCode.LeftShift, Enum.KeyCode.P }
local v_u_20 = Vector2.new(0.75, 1) * 8
local v_u_21 = {}
v_u_21.__index = v_u_21
function v_u_21.new(p22, p23)
	-- upvalues: (copy) v_u_21
	local v24 = v_u_21
	local v25 = setmetatable({}, v24)
	v25.f = p22
	v25.p = p23
	v25.v = p23 * 0
	return v25
end
function v_u_21.Update(p26, p27, p28)
	-- upvalues: (copy) v_u_3
	local v29 = p26.f * 2 * 3.141592653589793
	local v30 = p26.p
	local v31 = p26.v
	local v32 = p28 - v30
	local v33 = v_u_3(-v29 * p27)
	local v34 = p28 + (v31 * p27 - v32 * (v29 * p27 + 1)) * v33
	local v35 = (v29 * p27 * (v32 * v29 - v31) + v31) * v33
	p26.p = v34
	p26.v = v35
	return v34
end
function v_u_21.Reset(p36, p37)
	p36.p = p37
	p36.v = p37 * 0
end
local v_u_38 = Vector3.new()
local v_u_39 = Vector2.new()
local v_u_40 = 0
local v_u_41 = v_u_21.new(1.5, (Vector3.new()))
local v_u_42 = v_u_21.new(1, Vector2.new())
local v_u_43 = v_u_21.new(4, 0)
local v_u_44 = {}
local function v_u_46(p45)
	-- upvalues: (copy) v_u_5, (copy) v_u_1, (copy) v_u_3, (copy) v_u_2
	return v_u_5(p45) * v_u_2((v_u_3(2 * ((v_u_1(p45) - 0.15) / 0.85)) - 1) / 6.38905609893065, 0, 1)
end
local v_u_47 = {
	["ButtonX"] = 0,
	["ButtonY"] = 0,
	["DPadDown"] = 0,
	["DPadUp"] = 0,
	["ButtonL2"] = 0,
	["ButtonR2"] = 0,
	["Thumbstick1"] = Vector2.new(),
	["Thumbstick2"] = Vector2.new()
}
local v_u_48 = {
	["W"] = 0,
	["A"] = 0,
	["S"] = 0,
	["D"] = 0,
	["E"] = 0,
	["Q"] = 0,
	["U"] = 0,
	["H"] = 0,
	["J"] = 0,
	["K"] = 0,
	["I"] = 0,
	["Y"] = 0,
	["Up"] = 0,
	["Down"] = 0,
	["LeftShift"] = 0,
	["RightShift"] = 0
}
local v_u_49 = {
	["Delta"] = Vector2.new(),
	["MouseWheel"] = 0
}
local v_u_50 = Vector2.new(1, 1) * 0.04908738521234052
local v_u_51 = Vector2.new(1, 1) * 0.39269908169872414
local v_u_52 = 1
function v_u_44.Vel(p53)
	-- upvalues: (ref) v_u_52, (copy) v_u_48, (copy) v_u_2, (ref) v_u_46, (copy) v_u_47, (copy) v_u_12
	v_u_52 = v_u_2(v_u_52 + p53 * (v_u_48.Up - v_u_48.Down) * 0.75, 0.01, 4)
	local v54 = v_u_46(v_u_47.Thumbstick1.X)
	local v55 = v_u_46(v_u_47.ButtonR2) - v_u_46(v_u_47.ButtonL2)
	local v56 = v_u_46
	local v57 = -v_u_47.Thumbstick1.Y
	local v58 = Vector3.new(v54, v55, v56(v57)) * Vector3.new(1, 1, 1)
	local v59 = v_u_48.D - v_u_48.A + v_u_48.K - v_u_48.H
	local v60 = v_u_48.E - v_u_48.Q + v_u_48.I - v_u_48.Y
	local v61 = v_u_48.S - v_u_48.W + v_u_48.J - v_u_48.U
	local v62 = Vector3.new(v59, v60, v61) * Vector3.new(1, 1, 1)
	local v63 = v_u_12:IsKeyDown(Enum.KeyCode.LeftShift) or v_u_12:IsKeyDown(Enum.KeyCode.RightShift)
	return (v58 + v62) * (v_u_52 * (v63 and 0.25 or 1))
end
function v_u_44.Pan(_)
	-- upvalues: (ref) v_u_46, (copy) v_u_47, (copy) v_u_51, (copy) v_u_49, (copy) v_u_50
	local v64 = Vector2.new(v_u_46(v_u_47.Thumbstick2.Y), v_u_46(-v_u_47.Thumbstick2.X)) * v_u_51
	local v65 = v_u_49.Delta * v_u_50
	v_u_49.Delta = Vector2.new()
	return v64 + v65
end
function v_u_44.Fov(_)
	-- upvalues: (copy) v_u_47, (copy) v_u_49
	local v66 = (v_u_47.ButtonX - v_u_47.ButtonY) * 0.25
	local v67 = v_u_49.MouseWheel * 1
	v_u_49.MouseWheel = 0
	return v66 + v67
end
local function v_u_70(_, p68, p69)
	-- upvalues: (copy) v_u_48
	v_u_48[p69.KeyCode.Name] = p68 == Enum.UserInputState.Begin and 1 or 0
	return Enum.ContextActionResult.Sink
end
local function v_u_73(_, p71, p72)
	-- upvalues: (copy) v_u_47
	v_u_47[p72.KeyCode.Name] = p71 == Enum.UserInputState.Begin and 1 or 0
	return Enum.ContextActionResult.Sink
end
local function v_u_76(_, _, p74)
	-- upvalues: (copy) v_u_49
	local v75 = p74.Delta
	v_u_49.Delta = Vector2.new(-v75.y, -v75.x)
	return Enum.ContextActionResult.Sink
end
local function v_u_78(_, _, p77)
	-- upvalues: (copy) v_u_47
	v_u_47[p77.KeyCode.Name] = p77.Position
	return Enum.ContextActionResult.Sink
end
local function v_u_80(_, _, p79)
	-- upvalues: (copy) v_u_47
	v_u_47[p79.KeyCode.Name] = p79.Position.z
	return Enum.ContextActionResult.Sink
end
local function v_u_82(_, _, p81)
	-- upvalues: (copy) v_u_49
	v_u_49[p81.UserInputType.Name] = -p81.Position.z
	return Enum.ContextActionResult.Sink
end
function v_u_44.StartCapture()
	-- upvalues: (copy) v_u_8, (copy) v_u_70, (copy) v_u_18, (copy) v_u_76, (copy) v_u_82, (copy) v_u_73, (copy) v_u_80, (copy) v_u_78
	v_u_8:BindActionAtPriority("FreecamKeyboard", v_u_70, false, v_u_18, Enum.KeyCode.W, Enum.KeyCode.U, Enum.KeyCode.A, Enum.KeyCode.H, Enum.KeyCode.S, Enum.KeyCode.J, Enum.KeyCode.D, Enum.KeyCode.K, Enum.KeyCode.E, Enum.KeyCode.I, Enum.KeyCode.Q, Enum.KeyCode.Y, Enum.KeyCode.Up, Enum.KeyCode.Down)
	v_u_8:BindActionAtPriority("FreecamMousePan", v_u_76, false, v_u_18, Enum.UserInputType.MouseMovement)
	v_u_8:BindActionAtPriority("FreecamMouseWheel", v_u_82, false, v_u_18, Enum.UserInputType.MouseWheel)
	v_u_8:BindActionAtPriority("FreecamGamepadButton", v_u_73, false, v_u_18, Enum.KeyCode.ButtonX, Enum.KeyCode.ButtonY)
	v_u_8:BindActionAtPriority("FreecamGamepadTrigger", v_u_80, false, v_u_18, Enum.KeyCode.ButtonR2, Enum.KeyCode.ButtonL2)
	v_u_8:BindActionAtPriority("FreecamGamepadThumbstick", v_u_78, false, v_u_18, Enum.KeyCode.Thumbstick1, Enum.KeyCode.Thumbstick2)
end
function v_u_44.StopCapture()
	-- upvalues: (ref) v_u_52, (copy) v_u_47, (copy) v_u_48, (copy) v_u_49, (copy) v_u_8
	v_u_52 = 1
	local v83 = v_u_47
	for v84, v85 in pairs(v83) do
		v83[v84] = v85 * 0
	end
	local v86 = v_u_48
	for v87, v88 in pairs(v86) do
		v86[v87] = v88 * 0
	end
	local v89 = v_u_49
	for v90, v91 in pairs(v89) do
		v89[v90] = v91 * 0
	end
	v_u_8:UnbindAction("FreecamKeyboard")
	v_u_8:UnbindAction("FreecamMousePan")
	v_u_8:UnbindAction("FreecamMouseWheel")
	v_u_8:UnbindAction("FreecamGamepadButton")
	v_u_8:UnbindAction("FreecamGamepadTrigger")
	v_u_8:UnbindAction("FreecamGamepadThumbstick")
end
local function v_u_109(p92)
	-- upvalues: (ref) v_u_15, (ref) v_u_40, (copy) v_u_7, (copy) v_u_13
	local v93 = v_u_15.ViewportSize
	local v94 = v_u_7(v_u_40 / 2) * 2
	local v95 = v93.x / v93.y * v94
	local v96 = p92.rightVector
	local v97 = p92.upVector
	local v98 = p92.lookVector
	local v99 = Vector3.new()
	local v100 = 512
	for v101 = 0, 1, 0.5 do
		for v102 = 0, 1, 0.5 do
			local v103 = (v101 - 0.5) * v95
			local v104 = (v102 - 0.5) * v94
			local v105 = v96 * v103 - v97 * v104 + v98
			local v106 = p92.p + v105 * 0.1
			local _, v107 = v_u_13:FindPartOnRay(Ray.new(v106, v105.unit * v100))
			local v108 = (v107 - v106).magnitude
			if v108 < v100 then
				v99 = v105.unit
				v100 = v108
			end
		end
	end
	return v98:Dot(v99) * v100
end
local function v_u_116(p110)
	-- upvalues: (copy) v_u_41, (copy) v_u_44, (copy) v_u_42, (copy) v_u_43, (ref) v_u_40, (copy) v_u_4, (copy) v_u_7, (copy) v_u_6, (copy) v_u_2, (ref) v_u_39, (copy) v_u_20, (ref) v_u_38, (ref) v_u_15, (copy) v_u_109
	local v111 = v_u_41:Update(p110, v_u_44.Vel(p110))
	local v112 = v_u_42:Update(p110, v_u_44.Pan(p110))
	local v113 = v_u_43:Update(p110, v_u_44.Fov(p110))
	local v114 = v_u_6(0.7002075382097097 / v_u_7((v_u_4(v_u_40 / 2))))
	v_u_40 = v_u_2(v_u_40 + v113 * 300 * (p110 / v114), 1, 120)
	v_u_39 = v_u_39 + v112 * v_u_20 * (p110 / v114)
	v_u_39 = Vector2.new(v_u_2(v_u_39.x, -1.5707963267948966, 1.5707963267948966), v_u_39.y % 6.283185307179586)
	local v115 = CFrame.new(v_u_38) * CFrame.fromOrientation(v_u_39.x, v_u_39.y, 0) * CFrame.new(v111 * Vector3.new(64, 64, 64) * p110)
	v_u_38 = v115.p
	v_u_15.CFrame = v115
	v_u_15.Focus = v115 * CFrame.new(0, 0, -v_u_109(v115))
	v_u_15.FieldOfView = v_u_40
end
local v_u_117 = {}
local v_u_118 = nil
local v_u_119 = nil
local v_u_120 = nil
local v_u_121 = nil
local v_u_122 = nil
local v_u_123 = nil
local v_u_124 = {}
local v_u_125 = {
	["Backpack"] = true,
	["Chat"] = true,
	["Health"] = true,
	["PlayerList"] = true
}
local v_u_126 = {
	["BadgesNotificationsActive"] = true,
	["PointsNotificationsActive"] = true
}
function v_u_117.Push()
	-- upvalues: (copy) v_u_125, (copy) v_u_11, (copy) v_u_126, (ref) v_u_14, (copy) v_u_124, (ref) v_u_123, (ref) v_u_15, (ref) v_u_120, (ref) v_u_122, (ref) v_u_121, (ref) v_u_119, (copy) v_u_12, (ref) v_u_118
	for v127 in pairs(v_u_125) do
		v_u_125[v127] = v_u_11:GetCoreGuiEnabled(Enum.CoreGuiType[v127])
		v_u_11:SetCoreGuiEnabled(Enum.CoreGuiType[v127], false)
	end
	for v128 in pairs(v_u_126) do
		v_u_126[v128] = v_u_11:GetCore(v128)
		v_u_11:SetCore(v128, false)
	end
	local v129 = v_u_14:FindFirstChildOfClass("PlayerGui")
	if v129 then
		for _, v130 in pairs(v129:GetChildren()) do
			if v130:IsA("ScreenGui") and v130.Enabled then
				v_u_124[#v_u_124 + 1] = v130
				v130.Enabled = false
			end
		end
	end
	v_u_123 = v_u_15.FieldOfView
	v_u_15.FieldOfView = 70
	v_u_120 = v_u_15.CameraType
	v_u_15.CameraType = Enum.CameraType.Custom
	v_u_122 = v_u_15.CFrame
	v_u_121 = v_u_15.Focus
	v_u_119 = v_u_12.MouseIconEnabled
	v_u_12.MouseIconEnabled = false
	v_u_118 = v_u_12.MouseBehavior
	v_u_12.MouseBehavior = Enum.MouseBehavior.Default
end
function v_u_117.Pop()
	-- upvalues: (copy) v_u_125, (copy) v_u_11, (copy) v_u_126, (copy) v_u_124, (ref) v_u_15, (ref) v_u_123, (ref) v_u_120, (ref) v_u_122, (ref) v_u_121, (copy) v_u_12, (ref) v_u_119, (ref) v_u_118
	for v131, v132 in pairs(v_u_125) do
		v_u_11:SetCoreGuiEnabled(Enum.CoreGuiType[v131], v132)
	end
	for v133, v134 in pairs(v_u_126) do
		v_u_11:SetCore(v133, v134)
	end
	for _, v135 in pairs(v_u_124) do
		if v135.Parent then
			v135.Enabled = true
		end
	end
	v_u_15.FieldOfView = v_u_123
	v_u_123 = nil
	v_u_15.CameraType = v_u_120
	v_u_120 = nil
	v_u_15.CFrame = v_u_122
	v_u_122 = nil
	v_u_15.Focus = v_u_121
	v_u_121 = nil
	v_u_12.MouseIconEnabled = v_u_119
	v_u_119 = nil
	v_u_12.MouseBehavior = v_u_118
	v_u_118 = nil
end
local function v_u_137()
	-- upvalues: (ref) v_u_15, (ref) v_u_39, (ref) v_u_38, (ref) v_u_40, (copy) v_u_41, (copy) v_u_42, (copy) v_u_43, (copy) v_u_117, (copy) v_u_10, (copy) v_u_116, (copy) v_u_44
	local v136 = v_u_15.CFrame
	v_u_39 = Vector2.new(v136:toEulerAnglesYXZ())
	v_u_38 = v136.p
	v_u_40 = v_u_15.FieldOfView
	v_u_41:Reset((Vector3.new()))
	v_u_42:Reset(Vector2.new())
	v_u_43:Reset(0)
	v_u_117.Push()
	v_u_10:BindToRenderStep("Freecam", Enum.RenderPriority.Camera.Value, v_u_116)
	v_u_44.StartCapture()
end
local v_u_138 = false
local function v_u_141(p139)
	-- upvalues: (copy) v_u_12, (ref) v_u_138, (copy) v_u_44, (copy) v_u_10, (copy) v_u_117, (copy) v_u_137
	for v140 = 1, #p139 - 1 do
		if not v_u_12:IsKeyDown(p139[v140]) then
			return
		end
	end
	if v_u_138 then
		v_u_44.StopCapture()
		v_u_10:UnbindFromRenderStep("Freecam")
		v_u_117.Pop()
	else
		v_u_137()
	end
	v_u_138 = not v_u_138
end
v_u_8:BindActionAtPriority("FreecamToggle", function(_, p142, p143)
	-- upvalues: (copy) v_u_19, (copy) v_u_141
	if p142 == Enum.UserInputState.Begin and p143.KeyCode == v_u_19[#v_u_19] then
		v_u_141(v_u_19)
	end
	return Enum.ContextActionResult.Pass
end, false, v17, v_u_19[#v_u_19])
