-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMLB3VubW91bnQHcmVxdWlyZQVCb2FyZAZzY3JpcHQGUGFyZW50BW1vdW50DWNyZWF0ZUVsZW1lbnQEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlBVJvYWN0AAMCAAIAAAAG+wEAAE0AARIAAAAA+wEBAJ8AAgGCAAEAAQMBAAgAARgAAAAAAAEJAAAAAAYBAQAAABmkAQEAAAAAQKQEBAAAADBATQMEJAUAAABNAgPzAgAAAJ8BAgL7AwAATQID5AYAAAD7BAAATQMEygcAAABSBAEA/wUAAAAAAACfAwMCUgQAAJ8CAwLZAwAAEgIAABIAAgCCAwIACAMCBAAAAEADAwMEBAAAMEADBQMGAwcBAAUAARgAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAABgAAAAADAAABAgAPowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQIAIQYAAACfAQICwAIHABIAAQCCAgIACAMIBAAAAEADCQMKAwIEAABAQAMLBgEBAQEAARgAAQAAAAAAAQAAAAACAAABAAAAAAIyjdgPTl8qKwBJspule8iVEWrTxO60MBKZ1JNuxWwY/XCpB4T1uaHu

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Roact)
return function(p3)
	-- upvalues: (copy) v_u_2
	local v4 = require(script.Parent.Board)
	local v_u_5 = v_u_2.mount(v_u_2.createElement(v4, {}), p3)
	return function()
		-- upvalues: (ref) v_u_2, (copy) v_u_5
		v_u_2.unmount(v_u_5)
	end
end
