-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgM5BUV2ZW50BGluaXQEU2l6ZQFYAVkHVmVjdG9yMwNuZXcGQ0ZyYW1lBF9vYmoGU3Bpa2VzDkZpbmRGaXJzdENoaWxkCFNoZWx2aW5nEVNldFVwZGF0ZUNhbGxiYWNrBmNhbmNlbAFjAXMLdXBkYXRlUHJpc20Hc2V0T3BlbgdnZXRPcGVuCG9uc3Vhc3E5CkZpcmVTZXJ2ZXIFZGVsYXkHYW5kVGhlbgtPYmplY3RMb2NhbAtQcmltYXJ5UGFydAZWb2x1bWUSUm9sbE9mZk1heERpc3RhbmNlBlVwZGF0ZQhGYWtlRG9vcgxXYWl0Rm9yQ2hpbGQRcHJvbWlzZUJvdW5kQ2xhc3MDdGFwBV9tYWlkCEdpdmVUYXNrD0NvbmRpdGlvblBsYXllcgZSZWdpb24IQWRkUHJpc20KT25PYmpBZGRlZAdDb25uZWN0BWV2ZXJ5BXNldHVwBGdhbWUHUGxheWVycwpHZXRTZXJ2aWNlC0xvY2FsUGxheWVyEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUDU3RkB1Byb21pc2ULUmVnaW9uVXRpbHMGQmluZGVyC0JpbmRlclV0aWxzBURvb3IyCkRvb3JCaW5kZXIJRG9vclV0aWxzBUF1ZGlvCEludGVydmFsAAsCAQEAAAAETQEANgAAAADeAQAAggABAAEDAQAQAgEYAAAAAREAAAAACwIDAAAAKm8EAAD1BQEBCQMEBW8FAgAJBAUBQwIDBPsDAAD7BwAATQYHLwMAAABNBQZ5BAAAAPsIAABNBwgvAwAAAE0GB3gFAAAANDYFBAYCAABSBwIApAQIAAAcYICfBAQCMAQDLwMAAAD7AwAA+wcBAE0GB4UJAAAA+wcCAAkFBgekBgoAAByQgIwHAACMCAAAOQoCAFsJCgufBgQCCQQFBjAEA4UJAAAAggABAAwCy6FFtvP9+D8CAAAAAAAA8D8CiUFg5dAiGkADAwMEAwUDBgMHBAAcYIADCAQAHJCAAgAAAAAAAOA/AB0AARgAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEeAAAAAAYBAgAAABb7AgAATQECbgAAAABvAwEAvAEBAwIAAACfAQMC+wMAAE0CA24AAAAAbwQDALwCAgMCAAAAnwIDAtkFAAASAAEAEgACABICAQC8AwDIBAAAAJ8DAwGCAAEABQMJAwoDCwMMAw0BARgAARgAAAAAAAAAAQAAAAAAAAMAAAAAAAAFGQAAAAABAAEAAAADxgAAAN4AAACCAAEAAAAjAAEYAAABJAAAAAACAAEAAAAJ+wAAAA4ABgD7AAAAvAAAgQAAAACfAAIBxgAAAN4AAACCAAEAAQMOACYAARgAAAEAAAABAAInAAAAAAMAAgAAAA37AAAA+wIBAE0BAoUAAAAAMAEAggEAAAD7AAAA+wIBAE0BAi8CAAAAMAEAkgMAAACCAAEABAMIAw8DAwMQADARARgAAAAAAAABAAAAAAABMQAAAAADAAIAAAAH+wEAAE0AAS4AAAAA+wEBAKkCAACfAAMBggABAAEDEgA7AAEYAAAAAAAAATwAAAAABQAFAAAALfsBAABNAAE6AAAAAPsBAQCfAAICKwAmAPsAAgBvAgEAjAMkALwAAGsCAAAAnwAEAfsBAABNAAEuAwAAAPsBAQCpAgEAnwADAfsBAwBNAAG+BAAAAIwBAQCfAAIC2QIAABICAAASAgEAvAAAtQUAAACfAAMB+wEEAE0AAdEGAAAA+wIBAE0BApsHAAAAbwIIAOIDCwBvBAwAMAQDSwkAAACMBEAAMAQDKgoAAACfAAQBggABAA0DEwMUAxUDEgMWAxcDGAMZAgAAkLAqvflBAxoDGwUCCQoCAAAAAAAA4D8BBjcAARgAAAAAAAABAAAAAAABAAAAAAABAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAI4AAAAAAQABAAAABb7AAAA+wIBAE0BAoUAAAAAMAEAggEAAAD7AAAA+wIBAE0BAi8CAAAAMAEAkgMAAAD7AAIA/wIAAAEAAAD7AwMAxQIDAgEAAAC8AAAmBAAAAJ8AAwGCAAEABQMIAw8DAwMQAxwAQQABGAAAAAAAAAEAAAAAABEAAAAAAAAAAAExAAAAAA4BCgAAAHekAQIAAAQAgG8CAwBvAwQAbwQFAIwFAQCMBgAAjAcAAIwIAACMCQEAjAoAAIwLAACMDAAAjA0BAJ8BDQLGAgAATQMAbgYAAABvBQcAvAMD0wgAAACfAwMC+wUAAE0EBTUJAAAA+wUBAFIGAwCfBAMC2QYAABIAAAASAAEAvAQEmwoAAACfBAMC2QYBABIBAv+8BAS1CwAAAJ8EAwJSAgQATQQAwQwAAADZBgIAEgEC/7wEBP0NAAAAnwQDAfsFAgBNBAXvAQAAAPsGAwBNBQbUDgAAAJ8EAgJNBQBuBgAAAG8HDwC8BQUDEAAAAJ8FAwL/BgIAAAAAANkHAwASAAYAEgAFAE0IBYUAAAAAMAgGghEAAABNCAUvEgAAADAIBpITAAAAUgoGALwIBFcUAAAAnwgDAU0IAMEMAAAAUgoEALwICP0NAAAAnwgDAU0IAMEMAAAATQoEdxUAAADZDAQAEgIEABIAAwASAgUAEgIGABICBwC8CgrHFgAAAJ8KAwC8CAj9DQAAAJ8IAAFNCADBDAAAAPsLCABNCgvEFwAAAG8LGACfCgIC2QwFABIABgASAAUAEgAEABICCQC8CgrHFgAAAJ8KAwC8CAj9DQAAAJ8IAAHBAgAAggABABkDCAMHBAAEAIACumIuAAANtz8CQX1eAAARwj8Cy6FFtvP96D8DCQMdAx4DHwMgAxcDIQMiAyMDJAMLAw8DAwMQAyUDJgMnAygCmpmZmZmZyT8GAgMEBQcIEykBGAAAAAAAAAAAAAAAAAAAAAEBAAAAAAABAAAAAAABAAAAAAALAAAAAAADAAAAAAAABwAAAAAAAAEAAAAAAAEAAQAAAQAAAAEAAAADAAAAAQAAAAAAAQAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAQAFAAAAAAOAAABAgBhowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAk0BADEEAAAApAIBAAAAAEBvBAUAvAICFgMAAACfAgMCpAMHAAAAYEBNBQKhCAAAAE0EBfMJAAAAnwMCAqQEBwAAAGBATQYCoQgAAABNBQZyCgAAAJ8EAgKkBQcAAABgQE0IAqEIAAAATQcI8wkAAABNBgf+CwAAAJ8FAgKkBgcAAABgQE0JAqEIAAAATQgJfwwAAABNBwjZDQAAAJ8GAgKkBwcAAABgQE0JAqUOAAAATQgJkA8AAACfBwICpAgHAAAAYEBNCgKlDgAAAE0JCrwQAAAAnwgCAqQJBwAAAGBATQsCoQgAAABNCgvSEQAAAJ8JAgKkCgcAAABgQE0MAqEIAAAATQsMrBIAAACfCgICxgsAAP8MAgAAAAAA2Q0AABIBC/8wDQwTEwAAANkNAQASAAYAEgAHABIAAwASAAUAEgAIABIBC/8SAAQAEgAJABIACgASAAEAMA0M+RQAAADBCwAAggwCABUDKgQAAABAAysDLAMtAy4DLwQAAGBAAzADJAMxAzIDMwM0AzUDNgM3AzgDOQMCAykCAAkBAAEYAAEAAAAAAAEAAQAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAgEAAQAAAAMAAAAAAAAAAAAAAAAzAAEAAAAACnZkeoyFV2MRRKAQGJB1aDddhPPi+Q689/8NX47ZYgNpYru7WlknHrM=

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players").LocalPlayer
local v2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v2.Std.Region)
local v_u_4 = require(v2.Std.Promise)
local v_u_5 = require(v2.Std.Region.RegionUtils)
local v_u_6 = require(v2.Std.Binder.BinderUtils)
local v_u_7 = require(v2.Door2.DoorBinder)
local v_u_8 = require(v2.Door2.DoorUtils)
local v_u_9 = require(v2.Std.Audio)
local v_u_10 = require(v2.Std.Interval)
local v_u_11 = nil
return {
	["init"] = function(p12)
		-- upvalues: (ref) v_u_11
		v_u_11 = p12.Event
	end,
	["setup"] = function(p_u_13)
		-- upvalues: (copy) v_u_6, (copy) v_u_7, (copy) v_u_3, (copy) v_u_5, (copy) v_u_8, (ref) v_u_11, (copy) v_u_4, (copy) v_u_9, (copy) v_u_10, (copy) v_u_1
		local v_u_14 = CFrame.new(0.0900421143, 0.141143799, 0.781, 1, 0, 0, 0, 1, 0, 0, 0, 1)
		local v_u_15 = nil
		local v_u_16 = p_u_13._obj:WaitForChild("FakeDoor")
		v_u_15 = v_u_6.promiseBoundClass(v_u_7, v_u_16):tap(function(p17)
			-- upvalues: (copy) p_u_13, (copy) v_u_14
			local v_u_18 = p_u_13._obj:FindFirstChild("Spikes")
			local v_u_19 = p_u_13._obj:FindFirstChild("Shelving")
			p17:SetUpdateCallback(function(_, p20)
				-- upvalues: (copy) v_u_18, (copy) v_u_19, (ref) v_u_14
				local v21 = 1.562 * (1 - p20) + 6.534 * p20
				local v22 = v_u_18
				local v23 = v_u_18.Size.X
				local v24 = v_u_18.Size.Y
				v22.Size = Vector3.new(v23, v24, v21)
				v_u_18.CFrame = v_u_19.CFrame * v_u_14 * CFrame.new(0, 0, -v21 * 0.5)
			end)
		end):andThen(function()
			-- upvalues: (ref) v_u_15
			v_u_15 = nil
		end)
		p_u_13._maid:GiveTask(function()
			-- upvalues: (ref) v_u_15
			if v_u_15 then
				v_u_15:cancel()
				v_u_15 = nil
			end
		end)
		local v_u_25 = v_u_3.new(v_u_5.ConditionPlayer)
		local v_u_26 = p_u_13._obj:FindFirstChild("Region")
		local v_u_27 = {
			["c"] = v_u_26.CFrame,
			["s"] = v_u_26.Size
		}
		v_u_25:AddPrism(v_u_27)
		p_u_13._maid:GiveTask(v_u_25)
		p_u_13._maid:GiveTask(v_u_25.OnObjAdded:Connect(function()
			-- upvalues: (ref) v_u_8, (copy) v_u_16, (ref) v_u_11, (ref) v_u_4, (ref) v_u_9
			if not v_u_8.getOpen(v_u_16) then
				v_u_11:FireServer("onsuasq9", 36)
				v_u_8.setOpen(v_u_16, true)
				v_u_4.delay(1):andThen(function()
					-- upvalues: (ref) v_u_8, (ref) v_u_16
					v_u_8.setOpen(v_u_16, false)
				end)
				v_u_9.ObjectLocal(v_u_16.PrimaryPart, 6909242121, {
					["Volume"] = 0.5,
					["RollOffMaxDistance"] = 64
				})
			end
		end))
		p_u_13._maid:GiveTask(v_u_10.every(0.2):Connect(function()
			-- upvalues: (copy) v_u_27, (copy) v_u_26, (copy) v_u_25, (ref) v_u_1
			v_u_27.c = v_u_26.CFrame
			v_u_27.s = v_u_26.Size
			v_u_25:Update({ v_u_1 })
		end))
	end
}
