-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMlBVVEaW0yA25ldxNBYnNvbHV0ZUNvbnRlbnRTaXplAVkEU2l6ZQZyZXNpemUIUG9zaXRpb24Hc2Nyb2xsWQxBYnNvbHV0ZVNpemULR2V0Q2hpbGRyZW4EbWF0aARjZWlsBWZsb29yA21pbglDb250YWluZXIMV2FpdEZvckNoaWxkDFVJTGlzdExheW91dBhHZXRQcm9wZXJ0eUNoYW5nZWRTaWduYWwHQ29ubmVjdAhHaXZlVGFzawVldmVyeQxzZXRtZXRhdGFibGUFX21haWQUb2JzZXJ2ZU9uZUNoaWxkTmFtZWQIQm9hcmRHdWkHRGVzdHJveQRnYW1lClJ1blNlcnZpY2UKR2V0U2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQxUd2VlblNlcnZpY2UHcmVxdWlyZQNTdGQISW50ZXJ2YWwETWFpZA9SeEluc3RhbmNlVXRpbHMHX19pbmRleAAHCAACAAAAD/sAAACkAQIAAAQAgIwCAQCMAwAAjAQAAPsHAQBNBgfGAwAAAE0FBngEAAAAnwEFAjABAC8FAAAAggABAAYDAQMCBAAEAIADAwMEAwUAFAYBGAAAAAAAAAAAAAAAAAAAARUAAAAABwEBAAAAC/sBAACkAgIAAAQAgIwDAACMBAAAjAUAADkGAACfAgUCMAIBOwMAAACCAAEABAMBAwIEAAQAgAMHABoIARgAAAAAAAAAAAAAARsAAAAADQADAAAANvsCAABNAQJxAAAAAE0AAXgBAAAA+wMBAE0CA3EAAAAATQECeAEAAAD7BAEAvAQEaAMAAACfBAICHAMEAHgCAwLsAwEC7AUBALsHBQKkBAYAABRAgJ8EAgL7BgIACQUGAOwHBQO7DAcCpAYIAAAcQICfBgICCQUGAyYIAQCeEwUECAAAAFIHBQCkBgoAACRAgJ8GAwJSBQYAUgYFAPsHAQCkCA0AADCwgIwJAACMCgAAjAsAADkMBgCfCAUCMAgHOw4AAAD7CAIAlQcIAs8GBwTeBgIAggABAA8DCQMEAgAAAAAAAPA/AwoDCwMMBAAUQIADDQQAHECAAw4EACRAgAMBAwIEADCwgAMHAB4AARgEAAAAAAEAAAAAAQAAAAAAAQEAAAAAAQABAAAAAAABAAAAAAAAAAH0AAAAAAAAAAAADQAAAAEbAAAAAAsCAQAAADNvBAAAvAIA0wEAAACfAgMCbwUCALwDAtMBAAAAnwMDAtkEAAASAAIAEgADAKQFBQAAEDCAjAYBAIwHAACMCAAATQoDxgYAAABNCQp4BwAAAJ8FBQIwBQIvCAAAAG8JBgC8BwOUCQAAAJ8HAwJSCQQAvAcHxwoAAACfBwMAvAUB/QsAAACfBQAB2QUBABIAAgCMBgAA+wgAAE0HCMQMAAAAjAgFAJ8HAgLZCQIAEgAAABIAAgASAQb/vAcHxwoAAACfBwMBwQYAAIIAAQANAw8DEAMRAwEDAgQAEDCAAwMDBAMFAxIDEwMUAxUDAAECEQABGAAAAAABAAAAAQAAAQAAAAAAAAAAAAAAAwAAAAAAAAAAAAACAAMBAAAAAAAAAAAAAAAMABIAAAAACAEEAAAAHf8BAQAAAAAA+wQAAJ49AQQEAAAAUgMBAKQCAQAAAABAnwIDAfsDAQBNAgPvAgAAAJ8CAQIwAgHBAwAAAE0CAcEDAAAA+wUCAE0EBeoEAAAAUgUAAG8GBQDABwYAEgIDAJ8EBAC8AgL9BwAAAJ8CAAGCAQIACAMWBAAAAEADAgMXAxgDGQYDAxQBAwwCARgAAAEAAAAAAAACAAAAAAABAAAAAAAAAAAAAAAAGw0AAAAABAEAAAAADU0BAMEAAAAAvAEBUAEAAACfAQIBgT0ABQIAAABSAgAAbwMCAKQBBAAAADBAnwEDAYIAAQAFAxcDGgADFgQAADBAAC4aARgAAAAAAAEAAAAAAAABLwAAAAAIAAABAgA3owAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBAQAAAABAbwMEALwBARYDAAAAnwEDAqQCAQAAAABAbwQFALwCAhYDAAAAnwIDAqQDBwAAAGBATQUBoQgAAABNBAWsCQAAAJ8DAgKkBAcAAABgQE0GAaEIAAAATQUGdgoAAACfBAICpAUHAAAAYEBNBwGhCAAAAE0GB1ILAAAAnwUCAv8GAwAAAAAAMAYGbgwAAADABw0AEgAGABIABAASAAUAEgADADAHBu8OAAAAwAcPADAHBlAQAAAAggYCABEDGwQAAABAAxwDHQMeAx8DIAQAAGBAAyEDIgMjAyQDJQYEAwIGBQMaAgQFAQABGAABAAAAAAABAAAAAAABAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAACAAEAAgAAAAAAACIAAAUBAAAAAAZGeIra0FVYE3S84E642MoAoI5ZIAHKlIBRueLbn1ThzOo27Z2LOJUj

-- Decompiled by Krnl

game:GetService("RunService")
local v1 = game:GetService("ReplicatedStorage")
game:GetService("TweenService")
local v_u_2 = require(v1.Std.Interval)
local v_u_3 = require(v1.Std.Maid)
local v_u_4 = require(v1.Std.RxInstanceUtils)
local v_u_5 = {}
v_u_5.__index = v_u_5
function v_u_5.new(p6)
	-- upvalues: (copy) v_u_5, (copy) v_u_3, (copy) v_u_4, (copy) v_u_2
	local v7 = {}
	local v8 = v_u_5
	setmetatable(v7, v8)
	v7._maid = v_u_3.new()
	v7._maid:GiveTask(v_u_4.observeOneChildNamed(p6, "BoardGui", function(p_u_9, p10)
		-- upvalues: (ref) v_u_2
		local v_u_11 = p_u_9:WaitForChild("Container")
		local v_u_12 = v_u_11:WaitForChild("UIListLayout")
		v_u_11.Size = UDim2.new(1, 0, 0, v_u_12.AbsoluteContentSize.Y)
		p10:GiveTask(v_u_12:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function()
			-- upvalues: (copy) v_u_11, (copy) v_u_12
			v_u_11.Size = UDim2.new(1, 0, 0, v_u_12.AbsoluteContentSize.Y)
		end))
		local v_u_13 = 0
		v_u_2.every(5):Connect(function()
			-- upvalues: (copy) p_u_9, (copy) v_u_11, (ref) v_u_13
			local v14 = p_u_9.AbsoluteSize.Y
			local v15 = v_u_11.AbsoluteSize.Y
			local v16 = v15 / (#v_u_11:GetChildren() - 1)
			local v17 = v15 / v14
			local v18 = math.ceil(v17)
			local v19 = v_u_13 * v14 / v16
			local v20 = math.floor(v19) * v16
			local v21 = v15 - v14
			local v22 = math.min(v20, v21)
			v_u_11.Position = UDim2.new(0, 0, 0, -v22)
			v_u_13 = (v_u_13 + 1) % v18
		end)
	end))
	return v7
end
function v_u_5.Destroy(p23)
	p23._maid:Destroy()
	setmetatable(p23, nil)
end
return v_u_5
