-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMOA25ldwhUQUdfTkFNRQdyZXF1aXJlC1RvcEV4cEJvYXJkBnNjcmlwdAZQYXJlbnQFU3RhcnQEaW5pdARnYW1lEVJlcGxpY2F0ZWRTdG9yYWdlCkdldFNlcnZpY2UDU3RkBkJpbmRlchFUb3BFeHBCb2FyZENvbnN0cwACBgACAAAAFPsBAABNAAHvAAAAAPsCAQBNAQK0AQAAAKQCAwAAACBApAUGAAAAUEBNBAUkBwAAAE0DBIIEAAAAnwICAJ8AAAK8AQAcCAAAAJ8BAgGCAAEACQMBAwIDAwQAACBAAwQDBQQAAFBAAwYDBwAICAEYAAAAAAAAAAAAAAAAAAAAAAEAAAEJAAAAAAYAAAECAB+jAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CA38HAAAAnwECAqQCBQAAAEBApAUKAAAAkEBNBAUkCwAAAE0DBIUIAAAAnwICAv8DAQAAAAAAwAQMABIAAQASAAIAMAQDEw0AAACCAwIADgMJBAAAAEADCgMLAwMEAABAQAMMAw0DDgMFBAAAkEADBgYAAwgBAAEAARgAAQAAAAAAAQAAAAAAAAIAAAAAAAAAAAIAAQAAAAAEAQAAAAABQmVaMT4BDtZwoTClpy4aOgTXK5TTjWSMC7Sbr0Ha9a6KjdUAh3NhYA==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.Binder)
local v_u_3 = require(script.Parent.TopExpBoardConsts)
return {
	["init"] = function()
		-- upvalues: (copy) v_u_2, (copy) v_u_3
		v_u_2.new(v_u_3.TAG_NAME, require(script.Parent.TopExpBoard)):Start()
	end
}
