-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMJBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplCFRBR19OQU1FC1RvcEV4cEJvYXJkAAEFAAABAgAWowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAoQYAAABNAgMYBwAAAJ8BAgJNAgEACAAAAOIDCgBvBAsAMAQDtAkAAACfAgIAggIAAAwDAQQAAABAAwIDAwMEBAAAQEADBQMGAwcDCAUBCQMJAAEAARgAAQAAAAAAAQAAAAAAAAEAAAEAAP8AAQAAAAAAN6rVLW07584Fbr+5M8j8ztbdy4CapolZVBwTTSZRWRQSWZgA07KYGg==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Std.TableUtils).requireValidIndexAndFreeze({
	["TAG_NAME"] = "TopExpBoard"
})
