-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNSDHNldG1ldGF0YWJsZQRNZXRhBU1vZGVsF1NVU1BFTlNJT05fSEVJR0hUX0ZST05UFlNVU1BFTlNJT05fSEVJR0hUX0JBQ0sQQ09FRkZJQ0lFTlRfRFJBRwpNQVhfVEhSVVNUF1RIUk9UVExFX1dIRUVMX1RVUk5fTUlOEFRIUk9UVExFX1RBS0VPRkYQQ0FNRVJBX09GRlNFVF9DRgpIRUlHSFRfTUFYGVdIRUVMX1ZJU1VBTF9SQURJVVNfRlJPTlQYV0hFRUxfVklTVUFMX1JBRElVU19CQUNLBkNGcmFtZQNuZXcFUGxhbmUETWFpZAVTZWF0cwtCb3VuZGluZ0JveBVNb3RvckFpbGVyb25XaW5nUmlnaHQUTW90b3JBaWxlcm9uV2luZ0xlZnQVTW90b3JBaWxlcm9uVGFpbFJpZ2h0FE1vdG9yQWlsZXJvblRhaWxMZWZ0EE1vdG9yQWlsZXJvblRhaWwOTW90b3JQcm9wZWxsZXIKV2hlZWxzQ29uZglKb3lzdGlja3gJSm95c3RpY2t5CElucHV0WWF3BkFuZ2xlcwJDMAhUaHJvdHRsZQRtYXRoBWNsYW1wBWZsb29yDVByb3BlbGxlckRpc2MMVHJhbnNwYXJlbmN5EUhlYXJ0YmVhdEFpbGVyb25zDlNvdW5kUHJvcGVsbGVyBlZvbHVtZQ9IZWFydGJlYXRTb3VuZHMJSGVhcnRiZWF0CFBsYW5lR3VpB0Nvbm5lY3QIR2l2ZVRhc2sQTW91bnRMb2NhbFBsYXllcghWZWxvY2l0eQlNYWduaXR1ZGUDZXhwE1NldFBhcnRpY2xlc0VuYWJsZWQQTW91bnRUaGlyZFBsYXllcgtNb3VudFBsYXllcgtPYmplY3RMb2NhbAZMb29wZWQFUGl0Y2gLTWF4RGlzdGFuY2ULRW1pdHRlclNpemUSVW5tb3VudExvY2FsUGxheWVyElVubW91bnRUaGlyZFBsYXllcgZhc3NlcnQIT2NjdXBpZWQHRGVzdHJveQZQbGF5ZXILVW5tb3VudFNlYXQEZ2FtZQdQbGF5ZXJzCkdldFNlcnZpY2ULTG9jYWxQbGF5ZXIKUnVuU2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQdyZXF1aXJlDEFjdGlvbkJ1dHRvbhNBY3Rpb25CdXR0b25TZXJ2aWNlBEdhbWUESXRlbQNHdW4XQmFzZVVzZXJDb250cm9sbGVkUGxhbmUDU3RkBUF1ZGlvBVN0dW50C19fQ2xhc3NOYW1lB19faW5kZXgADgcBAgAAAGv/AgUAAAAAAPsDAACePQIDAwAAAKQBAQAAAABAnwEDAjAAAVQCAAAATQIAOwMAAAAwAgE7AwAAAOICDgCMAwQAMAMCDQQAAACMAwQAMAMCFQUAAABvAw8AMAMCGAYAAACMAxYDMAMCbAcAAABvAxAAMAMCJAgAAABvAxAAMAMCogkAAACkAxMAAEgQgYwEAACMBQoAjAYeAJ8DBAIwAwJvCgAAAIwDTAQwAwJACwAAAG8DFAAwAwIGDAAAAG8DFQAwAwLfDQAAAPsEAQBNAwTvEgAAAFIEAABSBQIAnwMDAjADAbYWAAAATQQBthYAAABNAwR2FwAAADADAXYXAAAATQQBthYAAABNAwR0GAAAADADAXQYAAAATQQBOwMAAABNAwRvGQAAADADAW8ZAAAATQMAShoAAAAwAwFKGgAAAE0DACIbAAAAMAMBIhsAAABNAwAHHAAAADADAQccAAAATQMAVh0AAAAwAwFWHQAAAE0DAIQeAAAAMAMBhB4AAABNAwBEHwAAADADAUQfAAAATQMBthYAAABNBAAbIAAAADAEAxsgAAAAggECACEDAQQAAABAAwIDAwMEAwUDBgMHAwgDCQMKAwsDDAMNBQoEBQYHCAkKCwwNApqZmZmZmek/AgAAAAAAAOA/Aw4DDwQASBCBAsHKoUW28/Q/AqRwPQrXo+Y/AxADEQMSAxMDFAMVAxYDFwMYAxkDGgARDwEYAAAAAAAAAAABAAEAAAACAQAAAQAAAQAAAQAAAQAAAQAAAQAAAAAAAAABAAABAAABAAACAAAAAAAAAAEAAAAAAAEAAAAAAAEAAAAAAAIAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAAAAAISAAAAABEBCQAAANIB+wQAAE0DBLYAAAAATQEDIwEAAAD7BAAATQMEtgAAAABNAgMoAgAAAPsFAABNBAW2AAAAAE0DBM4DAAAACQYBAQkHAgJDBQYHBAQFBIwGAQBgBgMABAAAAOwFAQQrBQEAUgUBAIwHAQBgBwMABAAAAOwGAgQrBgEAUgYCAPsHAQCkCQcAABhQgIwKAACMCwAAjAz//58JBAKkCgkAACBQgG8MCgA5DgYAJg0OBQkLDA2MDAAAjA0AAJ8KBAIJCAkKMAgH7QsAAAD7BwIApAkHAAAYUICMCgAAjAsAAIwM//+fCQQCpAoJAAAgUIBvDAoAOQ4GAEMNDgUJCwwNjAwAAIwNAACfCgQCCQgJCjAIB+0LAAAA+wcDAKQJBwAAGFCAjAoAAIwLAACMDP//nwkEAqQKCQAAIFCAbwwMADkOBgAmDQ4FCQsMDYwMAACMDQAAnwoEAgkICQowCAftCwAAAPsHBACkCQcAABhQgIwKAACMCwAAjAz//58JBAKkCgkAACBQgG8MDAA5DgYAQw0OBQkLDA2MDAAAjA0AAJ8KBAIJCAkKMAgH7QsAAAD7BwUApAsHAAAYUICMDAAAjA0AAIwOAQCfCwQCpAwJAAAgUIBvDQ0AjA4AAIwPAACfDAQCCQoLDKQLCQAAIFCAjAwAAG8PDgAJDg8FbxAPAAkPEAMmDQ4PjA4AAJ8LBAIJCQoLpAoJAAAgUIBvCxAAjAwAAIwNAACfCgQCCQgJCjAIB+0LAAAAjAgKAIwKCgD7DQAATQwNtgAAAABNCwxJEQAAAAkJCgtDBwgJ+wkGAAkKBwBDCAkK3ggGAPsIBgBvCRIAYAkEAAgAAAD7CQYAeAgJEt4IBgD7CAcApAoHAAAYUICMCwAAjAwAAIwN//+fCgQCpAsJAAAgUICMDAAAjA0AAPsOBgCfCwQCCQkKCzAJCO0LAAAA+w8AAE0OD7YAAAAATQ0OSREAAACMDgAAjA8BAEwuAAKkDBkAAGBwgZ8MBAIECwwW9QoVC1sJChSVCAkTWwsIGrsMCwKkChwAAGxwgZ8KAgI+CQoa+woIAPEJCQAKAAAA3gkIAPsMAABNCwxUHQAAAE0KC60eAAAAMAkK2R8AAACCAAEAIAMQAxsDHAMdAgAAAAAAAOA/Aw4DDwQAGFCAAx4EACBQgAIzMzMzMzPTPwMfApqZmZmZmck/AmVzLThSweC/ApqZmZmZmbk/AuxRuB6F67E/AmVzLThSweA/AyACGC1EVPshGUACMzMzMzMz4z8CmpmZmZmZ2T8CAAAAAAAA8D8CAAAAAAAAAEADIQMiBABgcIECAAAAAAAANEADIwQAbHCBAwIDJAMlAD0mARgAAAAAAAAAAAAAAQAAAAABAAAAAQAAAAAAAQAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAA/QAFAAAAAAAAAAABAAAAAQAAAAEAAAIAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAABAAAAAAACAAABAQAAAAAAAAI+AAAAAAQBAQAAAAz7AwAATQIDtgAAAABNAQJJAQAAAPsDAABNAgP3AgAAAAkDAQEwAwJLAwAAAIIAAQAEAxADIAMnAygAXykBGAAAAAAAAQAAAAAAAWAAAAAABAECAAAAD/sBAABSAgAAnwECAfsDAQBNAgO2AAAAAE0BAkkBAAAA+wMBAE0CA/cCAAAACQMBATADAksDAAAAggABAAQDEAMgAycDKABjKgEYBAAA/AAAAAABAAAAAAAFYAAAAAADAAEAAAAJ+wIAAE0BAlQAAAAATQABrQEAAACMAQEAMAEA2QIAAACCAAEAAwMCAyQDJQBoAAEYAAAAAAAAAAABaQAAAAAUAwEAAAA2TQQAtgAAAABNAwTQAQAAAE0EAEoCAAAATQUAIgMAAABNBgAHBAAAAE0HAFYFAAAATQgAhAYAAABNCQBEBwAAAIwKAACMCwAA2QwAABIAAAASAAQAEgAFABIABgASAAcAEgAIABIBCv8SAAkAEgEL/9kNAQASAAAA2Q4CABIADAASAAAATQ8CdggAAAD7EgAATRES/QkAAABSEw4AvBERxwoAAACfEQMAvA8P/QsAAACfDwABTQ8CdggAAADZEQMAEgAAALwPD/0LAAAAnw8DAcEKAACCAAEADAMQAysDFAMVAxYDFwMYAxkDEQMqAywDLQQBAgMEMS4BGAAAAAACAAEAAQABAAEAAQACAQEAAAAAAAAAAAAiAAQAAAQAAAAAAAAAAAAAAAEAAAAAAAAEADIAAAAACAEDAAAAMPsCAACMBAoACQMEAEMBAgPeAQAA+wEAAG8CAABgAgQAAQAAAPsCAAB4AQIA3gEAAPsBAQCkAwMAAAgQgIwEAACMBQAAjAb//58DBAKkBAUAABAQgIwFAACMBgAA+wcAAJ8EBAIJAgMEMAIB7QYAAAD7BAIATQMEbwcAAABNAgOFCAAAAE0BAqoJAAAAOQUBAD4EBQu7CwQCpAMOAAA0wICfAwIC9QIKA/sEAgBNAwT3DwAAADACA0sQAAAAggABABECGC1EVPshGUADDgMPBAAIEIADHgQAEBCAAx8DEwMvAzACAAAAAAAA8D8CAAAAAAAASUADIQMxBAA0wIADJwMoAHEqARgAAAAAAAEAAAABAAACAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAIAAAAAAAABAAAAAAFzAAAAAAsDAQAAABtNAwBEAAAAAIwEAADZBQAAEgEE/xIAAwASAAAATQYCdgEAAAD7CQAATQgJ/QIAAABSCgUAvAgIxwMAAACfCAMAvAYG/QQAAACfBgABTQYAtgUAAACpCAEAvAYGOQYAAACfBgMBwQQAAIIAAQAHAxkDEQMqAywDLQMQAzIBBm0zARgAAAIBAAAADQAAAAAAAAAAAAAAAgAAAAAAAQBuAAAAAAgDBAAAADFNAwC2AAAAAFIFAQBSBgIAvAMDGAEAAACfAwQB+wQAAE0DBNECAAAATQUAOwQAAABNBAVvAwAAAG8FBQDiBgkAqQcBADAHBrUGAAAAjAcAADAHBksHAAAAjAcBADAHBgAIAAAAnwMEAowEuAswBAOZCgAAAIwEFAAwBAODCwAAADADAPcMAAAA+wQBAJoBBwAEAAAA+wQCAFIFAABSBgEAUgcCAJ8EBAGCAAEA+wQDAFIFAABSBgEAUgcCAJ8EBAGCAAEADQMQAzQDNQMTAwMCAABQhoPfAEIDNgMoAzcFAwYHCAM4AzkDJwCCATQBGAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAQAAAQAAAQACAAABAAAAAAACAAAAAAKDAAAAAAICAAAAAAGCAAEAAACRAToBGACRAAAAAAYDAAAAAAdNAwC2AAAAAKkFAAC8AwM5AQAAAJ8DAwGCAAEAAgMQAzIAkgE7ARgAAAAAAAABkwAAAAAGAgEAAAAouwEBA1IDAQCkAgEAAAAAQJ8CAgFNAwGWAgAAALsBAwKkAgEAAAAAQJ8CAgFNAgD3AwAAALwCAlAEAAAAnwICAcYCAAAwAgD3AwAAAE0CAfkFAAAA+wMAAJoCAgADAAAAZQAIAE0CAfkFAAAATQMAtgYAAACpBQAAvAMDOQcAAACfAwMBTQIAtgYAAABSBAEAvAICMwgAAACfAgMAggIAAAkDPAQAAABAAz0DJwM+Az8DEAMyA0AAlQFAARgDAAAAAAEAAAAAAAEAAAAAAQAAAgAAAAABAgD1AAAAAAANAAAAAAAAkwAAAAADAQAAAAAGTQEAtgAAAAC8AQFQAQAAAJ8BAgGCAAEAAgMQAz4AogE+ARgAAAAAAAGjAAAAAA8AAAECAF2jAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCTQEAMQQAAACkAgEAAAAAQG8EBQC8AgIWAwAAAJ8CAwKkAwEAAAAAQG8FBgC8AwMWAwAAAJ8DAwKkBAgAAABwQE0GA5QJAAAATQUGYgoAAACfBAICpAUIAAAAcEBNCAO9CwAAAE0HCMoMAAAATQYHDQ0AAACfBQICpAYIAAAAcEBNCQO9CwAAAE0ICbYPAAAATQcIEg4AAACfBgICpAcIAAAAcEBNCQOhEAAAAE0ICdIRAAAAnwcCAqQICAAAAHBATQoDoRAAAABNCQp2EgAAAJ8IAgL/CQQAAAAAAG8KEwAwCgnlFAAAADAJCW4VAAAAwAoWABIACQASAAYAMAoJ7xcAAADAChgAEgACAMALGQASAAIAwAwaABIABwASAAEAEgAKABIACwAwDAkYGwAAAMAMHADADR0AwA4eABIAAQAwDgkzHwAAAMAOIAAwDglQIQAAAIIJAgAiA0EEAAAAQANCA0MDRANFA0YDRwQAAHBAA0gDSQNKA0sDTANNAxADTgNPAxEDUANRA1IGAAMPBgUGBwYIAzQGCQYKBgsDQAYMAz4IAAUHCAkKCwwBAAEYAAEAAAAAAAEAAQAAAAAAAQAAAAAAAQAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAABAAAAAAAABAABAAABAAEAAAAAIAA8ABUAAAAAAAAPAQMAAAANAAAEAQAAAAANg9pSoLhVyuOxHjg07j6uUrqJyXhksuyvfGtlSgRLsOln+TCwRNrVcA==

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players").LocalPlayer
local v_u_2 = game:GetService("RunService")
local v3 = game:GetService("ReplicatedStorage")
require(v3.ActionButton.ActionButtonService)
require(v3.Game.Item.Gun)
local v_u_4 = require(v3.Game.Plane.BaseUserControlledPlane)
local v_u_5 = require(v3.Std.Audio)
require(v3.Std.Maid)
local v_u_6 = {
	["__ClassName"] = "Stunt"
}
v_u_6.__index = v_u_6
function v_u_6.new(p7)
	-- upvalues: (copy) v_u_6, (copy) v_u_4
	local v8 = v_u_6
	local v9 = setmetatable({}, v8)
	v9.Meta = p7
	v9.Model = p7.Model
	local v10 = {
		["SUSPENSION_HEIGHT_FRONT"] = 4,
		["SUSPENSION_HEIGHT_BACK"] = 4,
		["COEFFICIENT_DRAG"] = 0.8,
		["MAX_THRUST"] = 790,
		["THROTTLE_WHEEL_TURN_MIN"] = 0.5,
		["THROTTLE_TAKEOFF"] = 0.5,
		["CAMERA_OFFSET_CF"] = CFrame.new(0, 10, 30),
		["HEIGHT_MAX"] = 1100,
		["WHEEL_VISUAL_RADIUS_FRONT"] = 1.3095,
		["WHEEL_VISUAL_RADIUS_BACK"] = 0.7075
	}
	v9.Plane = v_u_4.new(p7, v10)
	v9.Maid = v9.Plane.Maid
	v9.Seats = v9.Plane.Seats
	v9.BoundingBox = v9.Model.BoundingBox
	v9.MotorAileronWingRight = p7.MotorAileronWingRight
	v9.MotorAileronWingLeft = p7.MotorAileronWingLeft
	v9.MotorAileronTailRight = p7.MotorAileronTailRight
	v9.MotorAileronTailLeft = p7.MotorAileronTailLeft
	v9.MotorAileronTail = p7.MotorAileronTail
	v9.MotorPropeller = p7.MotorPropeller
	v9.Plane.WheelsConf = p7.WheelsConf
	return v9
end
local function v_u_32(p_u_11, _, p12)
	-- upvalues: (copy) v_u_2
	local _ = p_u_11.Plane.PlaneGui
	local v_u_13 = p_u_11.MotorAileronWingRight
	local v_u_14 = p_u_11.MotorAileronWingLeft
	local v_u_15 = p_u_11.MotorAileronTailRight
	local v_u_16 = p_u_11.MotorAileronTailLeft
	local v_u_17 = p_u_11.MotorAileronTail
	local v_u_18 = p_u_11.MotorPropeller
	local v_u_19 = 0
	local v_u_20 = 0
	local function v_u_29(p21)
		-- upvalues: (copy) p_u_11, (copy) v_u_13, (copy) v_u_14, (copy) v_u_15, (copy) v_u_16, (copy) v_u_17, (ref) v_u_19, (copy) v_u_18, (ref) v_u_20
		local v22 = p_u_11.Plane.Joystickx
		local v23 = p_u_11.Plane.Joysticky
		local v24 = p_u_11.Plane.InputYaw
		local v25 = (v22 * v22 + v23 * v23) ^ 0.5
		if v25 > 1 then
			v22 = v22 / v25 or v22
		end
		if v25 > 1 then
			v23 = v23 / v25 or v23
		end
		v_u_13.C0 = CFrame.new(0, 0, -1) * CFrame.Angles(0.3 * (-v23 - v22), 0, 0)
		v_u_14.C0 = CFrame.new(0, 0, -1) * CFrame.Angles(0.3 * (-v23 + v22), 0, 0)
		v_u_15.C0 = CFrame.new(0, 0, -1) * CFrame.Angles(0.2 * (-v23 - v22), 0, 0)
		v_u_16.C0 = CFrame.new(0, 0, -1) * CFrame.Angles(0.2 * (-v23 + v22), 0, 0)
		v_u_17.C0 = CFrame.new(0, 0, 1) * CFrame.Angles(-0.5235987755982988, 0, 0) * CFrame.Angles(0, 0.1 * v22 - 0.07 * v24, 0) * CFrame.Angles(0.5235987755982988, 0, 0)
		v_u_19 = v_u_19 + (10 + 10 * p_u_11.Plane.Throttle) * p21
		if v_u_19 > 6.283185307179586 then
			v_u_19 = v_u_19 - 6.283185307179586
		end
		v_u_18.C0 = CFrame.new(0, 0, -1) * CFrame.Angles(0, 0, v_u_19)
		local v26 = p_u_11.Plane.Throttle
		local v27 = ((1 - math.clamp(v26, 0, 1) ^ 2) * 0.4 + 0.6) * 20
		local v28 = math.floor(v27) / 20
		if v28 ~= v_u_20 then
			v_u_20 = v28
			p_u_11.Meta.PropellerDisc.Transparency = v28
		end
	end
	p12.Maid:GiveTask(v_u_2.Heartbeat:Connect(function(p30)
		-- upvalues: (copy) v_u_29, (copy) p_u_11
		v_u_29(p30)
		local v31 = p_u_11.Plane.Throttle
		p_u_11.SoundPropeller.Volume = v31 * v31
	end))
	p12.Maid:GiveTask(function()
		-- upvalues: (copy) p_u_11
		p_u_11.Meta.PropellerDisc.Transparency = 1
	end)
end
local function v_u_41(p_u_33, _, p34)
	-- upvalues: (copy) v_u_2
	local v_u_35 = p_u_33.MotorPropeller
	local v_u_36 = 0
	local function v40(p37)
		-- upvalues: (ref) v_u_36, (copy) v_u_35, (copy) p_u_33
		v_u_36 = v_u_36 + 10 * p37
		if v_u_36 > 6.283185307179586 then
			v_u_36 = v_u_36 - 6.283185307179586
		end
		v_u_35.C0 = CFrame.new(0, 0, -1) * CFrame.Angles(0, 0, v_u_36)
		local v38 = -p_u_33.BoundingBox.Velocity.Magnitude / 50
		local v39 = 1 - math.exp(v38)
		p_u_33.SoundPropeller.Volume = v39
	end
	p34.Maid:GiveTask(v_u_2.Heartbeat:Connect(v40))
	p_u_33.Plane:SetParticlesEnabled(true)
end
function v_u_6.MountPlayer(p42, p43, p44)
	-- upvalues: (copy) v_u_5, (copy) v_u_1, (copy) v_u_32, (copy) v_u_41
	p42.Plane:MountPlayer(p43, p44)
	local v45 = v_u_5.ObjectLocal(p42.Model.BoundingBox, 9058676938, {
		["Looped"] = true,
		["Volume"] = 0,
		["Pitch"] = 1
	})
	v45.MaxDistance = 3000
	v45.EmitterSize = 20
	p42.SoundPropeller = v45
	if p43 == v_u_1 then
		v_u_32(p42, p43, p44)
	else
		v_u_41(p42, p43, p44)
	end
end
function v_u_6.UnmountSeat(p46, p47)
	-- upvalues: (copy) v_u_1
	assert(p47)
	local v48 = p47.Occupied
	assert(v48)
	p46.SoundPropeller:Destroy()
	p46.SoundPropeller = nil
	if p47.Player ~= v_u_1 then
		local _ = p47.Player
		p46.Plane:SetParticlesEnabled(false)
	end
	return p46.Plane:UnmountSeat(p47)
end
function v_u_6.Destroy(p49)
	p49.Plane:Destroy()
end
return v_u_6
