-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMWB3VubW91bnQHcmVxdWlyZQRDQ1RWBnNjcmlwdAZQYXJlbnQFbW91bnQNY3JlYXRlRWxlbWVudARzaXplCHBvc2l0aW9uCGRpc3RhbmNlC2FzcGVjdFJhdGlvDGNhbWVyYUNGcmFtZQtmaWVsZE9mVmlldwVVRGltMgNuZXcJd29ya3NwYWNlDUN1cnJlbnRDYW1lcmEGQ0ZyYW1lBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQVSb2FjdAADAgACAAAABvsBAABNAAESAAAAAPsBAQCfAAIBggABAAEDAQASAAEYAAAAAAABEwAAAAALAQEAAAA7pAEBAAAAAECkBAQAAAAwQE0DBCQFAAAATQIDjwIAAACfAQIC+wMAAE0CA+QGAAAA+wQAAE0DBMoHAAAAUgQBAOIFDgCkBhEAAEDwgG8HEgCMCAAAbwkSAIwKAACfBgUCMAYFDwgAAACkBhEAAEDwgG8HEgCMCAAAbwkSAIwKAACfBgUCMAYF2wkAAACMBmAAMAYFdQoAAABvBhMAMAYFiQsAAACkCBUAAABAQU0HCEgWAAAATQYHhRcAAAAwBgXBDAAAAIwGRgAwBgWBDQAAAJ8DAwJSBAAAnwIDAtkDAAASAgAAEgACAIIDAgAYAwIEAAAAQAMDAwQEAAAwQAMFAwYDBwMIAwkDCgMLAwwDDQUGCAkKCwwNAw4DDwQAQPCAAgAAAAAAAOA/AhzHcRzHcfw/AxAEAABAQQMRAxIBAAUAARgAAAAAAAAAAAABAAABAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAEAAAEAAAEAAAAAAAAAAQAA+gj3CwAAAAYAAAAAAwAAAQIAD6MAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0CACEGAAAAnwECAsACBwASAAEAggICAAgDEwQAAABAAxQDFQMCBAAAQEADFgYBAQEBAAEYAAEAAAAAAAEAAAAAAgAAAQAAAAACSa1aKaMwbwh7aTC92AmzOrXAR/TI8JIc1/0pD9cckhxyADMgARRnGQ==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Roact)
return function(p3)
	-- upvalues: (copy) v_u_2
	local v4 = require(script.Parent.CCTV)
	local v_u_5 = v_u_2.mount(v_u_2.createElement(v4, {
		["size"] = UDim2.new(0.5, 0, 0.5, 0),
		["position"] = UDim2.new(0.5, 0, 0.5, 0),
		["distance"] = 96,
		["aspectRatio"] = 1.7777777777777777,
		["cameraCFrame"] = workspace.CurrentCamera.CFrame,
		["fieldOfView"] = 70
	}), p3)
	return function()
		-- upvalues: (ref) v_u_2, (copy) v_u_5
		v_u_2.unmount(v_u_5)
	end
end
