-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgOkAQdHZXRUYWdzBmlwYWlycwlSZW1vdmVUYWcId2lwZVRhZ3MOR2V0RGVzY2VuZGFudHMTd2lwZVRhZ3NSZWN1cnNpdmVseQhCYXNlUGFydANJc0EFU2hpcnQFUGFudHMNQ2hhcmFjdGVyTWVzaApXcmFwVGFyZ2V0BURlY2FsCUFjY2Vzc29yeQhIdW1hbm9pZApzaG91bGRDb3B5BUNsb25lE0NoYXJhY3RlckFwcGVhcmFuY2UETmFtZQ5GaW5kRmlyc3RDaGlsZAdEZXN0cm95EENsZWFyQWxsQ2hpbGRyZW4GUGFyZW50CEFuY2hvcmVkBEVudW0bSHVtYW5vaWREaXNwbGF5RGlzdGFuY2VUeXBlBE5vbmUTRGlzcGxheURpc3RhbmNlVHlwZQtHZXRDaGlsZHJlbgRjb3B5CWhhbmRsZU9iagxzZXRtZXRhdGFibGUJY2hhcmFjdGVyA25ldwVfbWFpZAhvblNjcmVlbhNsYXN0T25TY3JlZW5DaGFuZ2VkCEluc3RhbmNlBU1vZGVsCkNoaWxkQWRkZWQHQ29ubmVjdAhHaXZlVGFzaw5jaGFyYWN0ZXJDbG9uZQhjbG9uZVJlZgVwYWlycwZDRnJhbWUGVXBkYXRlCWNyZWF0ZVJlZgljYW1lcmFSZWYLdmlld3BvcnRSZWYHZnV6elJlZgRpbml0BUZyYW1lD0JvcmRlclNpemVQaXhlbBZCYWNrZ3JvdW5kVHJhbnNwYXJlbmN5EEJhY2tncm91bmRDb2xvcjMEU2l6ZQhQb3NpdGlvbgtMYXlvdXRPcmRlcgtBbmNob3JQb2ludBBDbGlwc0Rlc2NlbmRhbnRzBXByb3BzCGRpc2FibGVkBkNvbG9yMwRzaXplCHBvc2l0aW9uC2xheW91dE9yZGVyB1ZlY3RvcjIIVUlDb3JuZXIIVUlTdHJva2ULQXNwZWN0UmF0aW8NVmlld3BvcnRGcmFtZQRGdXp6BUZsYXNoDENvcm5lclJhZGl1cwRVRGltBUNvbG9yCVRoaWNrbmVzcwdFbmFibGVkBmFjdGl2ZRdVSUFzcGVjdFJhdGlvQ29uc3RyYWludAthc3BlY3RSYXRpbwVVRGltMg1DdXJyZW50Q2FtZXJhBlpJbmRleAdWaXNpYmxlA1JlZgZDYW1lcmELZmllbGRPZlZpZXcLRmllbGRPZlZpZXcMY2FtZXJhQ0ZyYW1lCkltYWdlTGFiZWwXcmJ4YXNzZXRpZDovLzgyNjA1MzA0MjkFSW1hZ2URSW1hZ2VUcmFuc3BhcmVuY3kFZmxhc2gGcmVuZGVyCGdldFZhbHVlBl9jbGVhchBvbkNoYXJhY3RlckFkZGVkE29uQ2hhcmFjdGVyUmVtb3ZpbmcDb2JqBXRhYmxlBWNsZWFyAm9zBWNsb2NrC1ByaW1hcnlQYXJ0AXAEVW5pdApMb29rVmVjdG9yA0RvdAlNYWduaXR1ZGUIZGlzdGFuY2UEbWF0aANyYWQDY29zEG9uQ2hhcmFjdGVyRW50ZXIKY2FudmFzTWFpZAN0YW4HVmVjdG9yMwl3b3Jrc3BhY2UFSXRlbXMKR2V0UGxheWVycwlDaGFyYWN0ZXIGaW5zZXJ0DU92ZXJsYXBQYXJhbXMRUmF5Y2FzdEZpbHRlclR5cGUJQmxhY2tsaXN0CkZpbHRlclR5cGUaRmlsdGVyRGVzY2VuZGFudHNJbnN0YW5jZXMBehJHZXRQYXJ0Qm91bmRzSW5Cb3gQSHVtYW5vaWRSb290UGFydAVTdGFydAZHZXRBbGwTR2V0Q2xhc3NBZGRlZFNpZ25hbBZHZXRDbGFzc1JlbW92aW5nU2lnbmFsBWV2ZXJ5BnJhbmRvbQlIZWFydGJlYXQHX3JlZHJhdwlkaWRVcGRhdGUIZGlkTW91bnQKRG9DbGVhbmluZwt3aWxsVW5tb3VudARnYW1lClJ1blNlcnZpY2UKR2V0U2VydmljZRFDb2xsZWN0aW9uU2VydmljZQdQbGF5ZXJzEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUOTWFuaWZlc3RCaW5kZXIDU3RkBE1haWQISW50ZXJ2YWwFUm9hY3QKQmFzZU9iamVjdA1jcmVhdGVFbGVtZW50B19faW5kZXgNUHVyZUNvbXBvbmVudARDQ1RWBmV4dGVuZAxkZWZhdWx0UHJvcHMAGAsBAQAAABP7AQAAUgMAALwBARAAAAAAnwEDAqQCAgAAABBAUgMBAJ8CAgRRAgYA+wcAAFIJAABSCgYAvAcHFwMAAACfBwQBbgL5/wIAAICCAAEABAMBAwIEAAAQQAMDAA0EARgAAAAAAAEAAAAAAQAAAAAA/wADDgAAAAAIAQEAAAAQ+wEAAFICAACfAQIBpAEBAAAAAEC8AgBHAgAAAJ8CAgCfAQAEUQEDAPsGAABSBwUAnwYCAW4B/P8CAACAggABAAMDAgQAAABAAwUAEwYBGAAAAAEAAAAAAAABAAD/AAMUAAAAAAQBAAAAACxvAwAAvAEA/gEAAACfAQMCKwEjAG8DAgC8AQD+AQAAAJ8BAwIrAR4AbwMDALwBAP4BAAAAnwEDAisBGQBvAwQAvAEA/gEAAACfAQMCKwEUAG8DBQC8AQD+AQAAAJ8BAwIrAQ8AbwMGALwBAP4BAAAAnwEDAisBCgBvAwcAvAEA/gEAAACfAQMCKwEFAG8DCAC8AQD+AQAAAJ8BAwIOAQIAqQEBAIIBAgCpAQAAggECAAkDBwMIAwkDCgMLAwwDDQMOAw8AKhABGAAAAAAAAQAAAAABAAAAAAEAAAAAAQAAAAABAAAAAAEAAAAAAQAAAAACAAIALAAAAAALAgMAAABAvAIAOgAAAACfAgICKwIBAIIAAQBvBQEAvAMA/gIAAACfAwMCDgMMAE0FAroDAAAAvAMBAwQAAACfAwMCDgMGAPsEAADGBQAAagUEA7wEA1AFAAAAnwQCAbwDAqEGAAAAnwMCATABAiQHAAAA+wMBAFIEAgCfAwIBbwUIALwDAv4CAAAAnwMDAg4DBgCpAwEAMAMCRQkAAAD7AwAAagADAmUACQBvBQoAvAMC/gIAAACfAwMCDgMEAKQDDgANMLDAMAMCJg8AAACkAxEAAAAAQbwEAGgSAAAAnwQCAJ8DAARRAwQA+wgCAFIJBwBSCgIAnwgDAW4D+/8CAACAggICABMDEQMSAwgDEwMUAxUDFgMXAwcDGAMPAxkDGgMbBA0wsMADHAMCBAAAAEEDHQA5HgEYAAAAAQECAAAAAAEAAAAAAQEAAAEAAAMAAAEAAQAAAQAAAAABAAABAAABAAAAAAEAAAACAAAAAAAAAQAAAP8AAzoAAAAABAEDAAAACvsBAABSAgAAnwECAisBAQCCAAEA+wEBAFICAAD7AwIAnwEDAYIAAQAAAFMfARgAAAAAAQIAAAABVAAAAAAPAQMAAABO/wEEAAAAAAD7BAAAnj0BBAQAAABSAwEApAIBAAAAAECfAgMBMAABSQIAAAD7AwEATQID7wMAAACfAgECMAIBwQQAAACpAgAAMAIBKAUAAACMAgAAMAIBvwYAAACkAggAAAxwgG8DCQCfAgIC/wMAAAAAAADABAoA2QUBABIAAwASAgIAEgAFANkGAgASAAQAEgAFABIAAgCkBwwAAACwQLwIAGgNAAAAnwgCAJ8HAARRBwkAUgwEAFINCwCfDAICKwwBAGUABABSDAUAUg0LAFIOAgCfDAMBbgf2/wIAAIBNBwHBBAAAAE0JAGsOAAAAUgsGALwJCccPAAAAnwkDALwHB/0QAAAAnwcAATACAQQRAAAAMAMBKRIAAABNBwHBBAAAAFIJAgC8Bwf9EAAAAJ8HAwGCAQIAEwMgBAAAAEADIQMiAyMDJAMlAyYEAAxwgAMnBgIDAgQAALBAAx0DKAMpAyoDKwMsAwIDBBwiARgAAAEAAAAAAAACAAEAAAAAAAEAAAEAAAUAAAABAAEPAAAAGgAAAAYAAAAAAAD7AAAAAQIAAAACAAMAAAAAAAAAAAAAAQABAAEAAAAAAAIdAAAAAAcBAAAAAA2kAQEAAAAAQE0CACkCAAAAnwECBBcBBABNBgWFAwAAADAGBIUDAAAAbgH7/wIAAACCAAEABAMtBAAAAEADLAMuAGMvARgAAAAAAAABAAAA/wADZAAAAAAEAQAAAAANTQEAwQAAAAC8AQFQAQAAAJ8BAgGBPQAFAgAAAFICAABvAwIApAEEAAAAMECfAQMBggABAAUDIwMVAAMgBAAAMEAAaBUBGAAAAAAAAQAAAAAAAAFpAAAAAAMBAgAAABn7AgAATQEC0AAAAACfAQECMAEAJQEAAAD7AgAATQEC0AAAAACfAQECMAEApAIAAAD7AgAATQEC0AAAAACfAQECMAEANgMAAAD7AgEATQEC7wQAAACfAQECMAEAwQUAAACCAAEABgMwAzEDMgMzAyIDIwBxNAEYAAAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAXIAAAAADwECAAAAngL7AQAAbwIAAOIDCQCMBAAAMAQDjgEAAABNBgAHCgAAAE0FBoILAAAAKwUCAIwEAQBlAAEAjAQAADAEAzoCAAAApAQOAAA0wIBvBQ8AjAYAAIwHAACfBAQCMAQDnwMAAABNBQAHCgAAAE0EBQ8QAAAAMAQDLwQAAABNBQAHCgAAAE0EBdsRAAAAMAQDOwUAAABNBQAHCgAAAE0EBSASAAAAMAQDAAYAAACkBBQAADQwgW8FFQBvBhUAnwQDAjAEA+gHAAAAqQQBADAEA7MIAAAA4gQcAPsFAABvBhYA4gceAKQIIAAANPCBbwkhAIwKAACfCAMCMAgHTx0AAACfBQMCMAUE9BYAAAD7BQAAbwYXAOIHJQCkCA4AADTAgIwJAQCMCgAAjAsAAJ8IBAIwCAekIgAAAIwIAgAwCAcYIwAAAE0JAAcKAAAATQgJ4yYAAAAwCAfwJAAAAJ8FAwIwBQRtFwAAAPsFAABvBicA4gcoAE0JAAcKAAAATQgJiSkAAAAwCAdpGAAAAJ8FAwIwBQRpGAAAAPsFAABvBhkA/wcEAAAAAACMCAEAMAgHOgIAAACkCCsAADSggowJAQCMCgAAjAsBAIwMAACfCAUCMAgHLwQAAABNCAAlLAAAADAIB0gtAAAAjAgBADAIBw0uAAAATQoABwoAAABNCQqCCwAAAFYICQAwCAeALwAAAPsJAQBNCAndMAAAAE0JAKQxAAAAagkHCOIIMwD7CQAAbwoWAOILHgCkDCAAADTwgW8NIQCMDgAAnwwDAjAMC08dAAAAnwkDAjAJCPQWAAAA+wkAAG8KMgD/CwMAAAAAAE0NAAcKAAAATQwNgTQAAAAwDAthNQAAAE0NAAcKAAAATQwNwTYAAAAwDAuFNwAAAPsNAQBNDA3dMAAAAE0NACUsAAAAag0LDJ8JAwIwCQhZMgAAAJ8FBAIwBQR0GQAAAPsFAABvBjgA/wcEAAAAAACMCAEAMAgHOgIAAABvCDkAMAgHqToAAABvCBUAMAgHozsAAACkCCsAADSggm8JPACMCgAAbws8AIwMAACfCAUCMAgHLwQAAACkCCsAADSggm8JFQCMCgAAbwsVAIwMAACfCAUCMAgHOwUAAACkCBQAADQwgW8JFQBvChUAnwgDAjAIB+gHAAAAjAgKADAIBw0uAAAA+wkBAE0ICd0wAAAATQkANj0AAABqCQcI4gg+APsJAABvChYA4gseAKQMIAAANPCBbw0hAIwOAACfDAMCMAwLTx0AAACfCQMCMAkI9BYAAACfBQQCMAUEuBoAAAD7BQAAbwYAAOIHPwBNCQAHCgAAAE0ICadAAAAAMAgHOgIAAACkCA4AADTAgIwJAQCMCgEAjAsBAJ8IBAIwCAefAwAAAKQIKwAANKCCjAkBAIwKAQCMCwEAnwgEAjAIBy8EAAAAjAgUADAIBw0uAAAATQoABwoAAABNCQqnQAAAAEcJAgAAAACAqQgAAakIAQAwCAeALwAAAJ8FAwIwBQRHGwAAAJ8BBACCAQAAQQM1AzYDNwM4AzkDOgM7AzwDPQUIAQIDBAUGBwgDPgM/A0ADIgQANMCAApqZmZmZmdk/A0EDQgNDA0QEADQwgQIAAAAAAADgPwNFA0YDRwNIA0kDSgUGFhcYGRobA0sFAR0DTAQANPCBAgAAAAAAAJA/A00DTgNPBQMiIyQDUANRBQEYA1IDUwQANKCCAzEDVANVA1YDVwMyA1gFAhYyA1kDWgNbAy4DXANdA14DXwKamZmZmZnxPwMzBQEWBQUCAwQuLwNgAHdhARgAAAABAAABAAAAAAAAAAAAAQAAAAAAAAABAAAAAAABAAAAAAABAAAAAAABAAAAAAAAAQAAAQEAAAEAAAAAAAD/AAADAAABAAAAAAAAAAEAAAEAAAAAAP0AAAUAAAEAAAAAAP8AAAMAAAABAAABAAAAAAAAAAABAAAAAQAAAQAAAAAAAAEAAAAAAAEBAAABAAAAAAAA/wAAAwAAAAEAAAAAAAEAAAAAAAEAAAAAAP0AAPUAABEAAAABAAABAAABAAABAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAQAAAQAAAAAAAQEAAAEAAAAAAAD/AAD2AAAOAAABAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAQAAAAAAAAAAAPsAAMwAeQAAAAAKAQAAAAAcTQEApAAAAAC8AQHTAQAAAJ8BAgKkAgMAAAAgQLwDAWgEAAAAnwMCAJ8CAARRAg0AbwkFALwHBv4GAAAAnwcDAisHCABvCQcAvAcG/gYAAACfBwMCKwcDALwHBlAIAAAAnwcCAW4C8v8CAACAggABAAkDMgNiAwIEAAAgQAMdA0UDCANYAxUAtgFjARgAAAAAAAEAAAAAAAABAAAAAAAAAAAAAQAA/gAFtwAAAAADAQEAAAAG+wIAAE0BAu8AAAAAUgIAAJ8BAgCCAQAAAQMiAN8BAAEYAAAAAAAA4AAAAAAEAQMAAAYDAAAFAQcN+wIAAE0BAu8AAAAAUgIAAJ8BAgL7AgEAagECAE0CAQQBAAAA+wMCADADAiQCAAAAggABAAMDIgMrAxcA6wFkARgAAAAAAAEAAQAAAAAB7AAAAAAEAQEAAAYDAAAFAQcK+wIAAIcBAgAOAQMAvAIBUAAAAACfAgIB+wIAAMYDAABqAwIAggABAAEDFQDwAWUBGAAAAQEAAAIAAAHxAAAAAAUBAwAAAA9NAQATAAAAAPsDAABNAgPvAQAAAFIDAQCfAgIC+wMBAGoCAwFNAwIEAgAAAPsEAgAwBAMkAwAAAIIAAQAEA2YDIgMrAxcA+gEAARgPAPEAAAAAAQABAAAAAA7sAAAAAAUBAQAAAAxNAQATAAAAAPsDAACHAgMBDgIDALwDAlABAAAAnwMCAfsDAADGBAAAagQDAYIAAQACA2YDFQD9AQABGA0A8wABAQAAAgAACvEAAAAABwABAAAADvsAAADGAQAAxgIAAGQAAwC8BQRQAAAAAJ8FAgFuAPz/AgAAAKQAAwAACBCA+wEAAJ8AAgGCAAEABAMVA2cDaAQACBCAAIACAAEYAAAAAAEAAP8AAwAAAAEBAQAAABIAAwAAAGKkAAIAAAQAgJ8AAQL7AQAAxgIAAMYDAABkAVgATQcFSQMAAABNBgebBAAAAA4GRwBNCAY7BQAAAPsKAQBNCQqRBgAAACYHCAlNCAcHBwAAAPsLAQBNCgtoCAAAALwICCsJAAAAnwgDAqkJAABNCgeqCgAAAPsNAgBNDA0HCwAAAE0LDHUMAAAAYAoZAAsAAAD7EAIATQ8QBwsAAABNDg+JDgAAAPsRAgBNEBEHCwAAAE0PEIEPAAAACQ0ODz4MDQ27FgwCpAsSAABEAIGfCwICuwkLAqQKFAAATACBnwoCArcKAgAIAAAAqQkAAakJAQBNCgUoFQAAAPEJFAAKAAAAMAkFKBUAAAAwAAW/FgAAAA4JDgD7DAIATQsMBwsAAABNCgu3FwAAAA4KCAD7DAIATQsMBwsAAABNCgu3FwAAAE0LBUkDAAAAnwoCAU0HBSgVAAAAKwcGAE0IBb8WAAAAJgcACIwIAQBgBwQACAAAALwHBSYYAAAAnwcCAW4Bp/8CAAAAggABABkDaQNqBAAEAIADIQNrAzoDbANtA24DbwNwAz4DcQIAAAAAAAAAQANSA1kDcgNzBABEAIEDdAQATACBAyQDJQN1Ay8AhwIAARgAAAABAAAAAQAAAAEBAAAAAAACAAAAAAAAAAEAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAQABAAEBAAAAAAABAAAAAAAAAAcAAAAAAAAAAAEAAOkAGggBAAAABwACAAAAFqQDAwAACBCAnwMBAlsCAwD7AwAAQwECA7sJAQKkAAYAABRAgJ8AAgL7AQEApAIJAAAgcIBvAwoAjAQAAFsGAAuVBQYKjAYAAJ8CBQIwAgE7DAAAAIIAAQANAgAAAAAAAIBAA2kDagQACBCAA3IDdAQAFECAA1MDIgQAIHCAAgAAAAAAAOA/ApqZmZmZmak/AzoApwIAARgAAAAAAAAAAAAAAQAAAAAAAAAAAAABKAEAAAAYAQgAAADuAbwBAOcAAAAAnwECAfsCAABNAQLvAQAAAJ8BAQJNAgDBAgAAADABApEDAAAATQIApAQAAAC8AgLTBQAAAJ8CAgJNBAAHBgAAAE0DBHUHAAAATQUABwYAAABNBAXBCAAAAIwHAgAJBgcDTQsABwYAAABNCguBCgAAAD4JCgm7FgkCpAgNAAAwsICfCAICuxsIAqQHDwAAOLCAnwcCAgkFBgdNCAAHBgAAAE0HCIkQAAAACQYFBzQ2BgYFAwAAUggGAFIJBQBSCgMApAcSAAAEEIGfBwQC/wgAAAEAAACkCRQAAAAwQW8LFQC8CQkDFgAAAJ8JAwDFCAkAAQAAAKQJGAAAAHBB+woBALwKCqsZAAAAnwoCAJ8JAARRCQsATQ4NaRoAAAAODggATRANaRoAAACeNAgEEAAAAFIPCACkDh0AAHCwgZ8OAwFuCfT/AgAAgKQJHwAABOCBnwkBAqQKIwAihADCMAoJVyQAAAAwCAl9JQAAAKQKFAAAADBBpA0nAAAEYIKMDgAAjA8AAE0SB5spAAAAORESAFsQESifDQQCCQwEDVINBwBSDgkAvAoKLyoAAACfCgUCpAsYAAAAcEFSDAoAnwsCBFELFQC8EA86KwAAAJ8QAgIOEBEA+xECAFISEACfEQIBpBEYAAAAcEG8EhBHLAAAAJ8SAgCfEQAEUREDAPsWAgBSFxUAnxYCAW4R/P8CAACAMAIQJC0AAABuC+r/AgAAgPsMAwBNCwzvAQAAAG8MGgDiDS8Abw4uADAODWYuAAAAwA4wABICBACfCwQCvAwLHDEAAACfDAIB/wwAAAAAAADZDQEAEgIFABIADAASAAIA2Q4CABIADAC8DwvQMgAAAJ8PAgRkDwwATRQTEzMAAAD7FgUATRUW7wEAAABSFhQAnxUCAmoVDBRNFhUENAAAADACFiQtAAAAbg/z/wIAAAC8DwsHNQAAAJ8PAgLZEQMAEgIFABIADAASAAIAvA8PxzYAAACfDwMBvA8LZzcAAACfDwIC2REEABIADAC8Dw/HNgAAAJ8PAwHZEQUAEgAMALwPAf04AAAAnw8DAfsSBgBNERLEOQAAAG8SOgCfEQIC2RMGABIADAASAAQAEgAAALwREcc2AAAAnxEDALwPAf04AAAAnw8AAU0PADY7AAAAvA8P0wUAAACfDwICpBE+AAD0sICfEQECWxARPPsUBwBNExT9PwAAANkVBwASABAAEgAPALwTE8c2AAAAnxMDALwRAf04AAAAnxEAAYIAAQBAA2MDIgMjA3YDMgNiAz4DcQNbAgAAAAAAAABAA1kDcgNzBAAwsIADdwQAOLCAA1IDeAQABBCBA3kEAAAwQQN6AxQDAgQAAHBBA3sDfANnA30EAHCwgQN+BAAE4IEDGQN/A4ABBCKEAMIDgQEDggEDLgQABGCCAgAAAAAAAOA/A4MBA4QBAxEDBQMXA4UBBQEuBgsDhgEDhwEDZgMrA4gBAykDiQEDKgOKAQKamZmZmZm5PwMzAgAAAAAAAIBAA4sBBAD0sIADjAEICwwNDg8QERK+AY0BAQYAAAABAAAAAQAAAAIAAAAAAQAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAABAAAAAAAAAAEAAQAAAAAAAAACqwAAAAAAAAEAAAEAAAAAAAAA/gAFAAABAAAAAQABAAAAAAAAAAAAAAAAAAAAAAEAAAAAAQAAAT0AAAEAAAAAAP8BAAD/AMQA/AAIAAAAAAEAAAEA/gUAAAIABwAAAAUABwAAAAEA9AAAAAABAQAAAAkAAwAAAAAAAAAAAAMAAAAYAAAAAwAAAAAHAAAAAAAAAAAAAAAAAAAeAAAAAAEAAAABAAAAAAAAAAAAAAAEvwAAAFX///8BAAAA6AAAAAAHAgAAAAAUTQYABwAAAABNBQbBAQAAAE0EBZECAAAATQYBwQEAAABNBQaRAgAAACYDBAVNAgOqAwAAAG8DBABgAwQAAgAAALwCAHIFAAAAnwICAYIAAQAGAz4DWwNsA3ACmpmZmZmZuT8DjQEArAKOAQEYAAAAAAAAAAAAAAAAAAAAAAEAAAItAQAAAAMBAAAAAAS8AQByAAAAAJ8BAgGCAAEAAQONAQCxAo8BARgAAAABMgEAAAADAQAAAAAGTQEAwQAAAAC8AQFRAQAAAJ8BAgGCAAEAAgMjA5ABALQCkQEBGAAAAAAAATUBAAAAEAAAAQIAfKMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQEAAAAAQG8DBAC8AQEWAwAAAJ8BAwKkAgEAAAAAQG8EBQC8AgIWAwAAAJ8CAwKkAwEAAAAAQG8FBgC8AwMWAwAAAJ8DAwKkBAgAAABwQE0FA4kJAAAAnwQCAqQFCAAAAHBATQcDoQoAAABNBgd2CwAAAJ8FAgKkBggAAABwQE0IA6EKAAAATQcIrAwAAACfBgICpAcIAAAAcEBNCAMhDQAAAJ8HAgKkCAgAAABwQE0KA6EKAAAATQkKSw4AAACfCAICTQkHyg8AAADAChAAEgABAMALEQASAAoA/wwDAAAAAAAwDAxuEgAAAMANEwASAAwAEgAFABIACgAwDQzvFAAAAMANFQAwDQwmFgAAAMANFwAwDQxQGAAAAE0NB/gZAAAAbw8aALwNDZwbAAAAnw0DAuIOHQCpDwEAMA8O4xwAAAAwDg2SHgAAAMAOHwASAAcAEgAFADAODRMgAAAAwA4hABIACQASAAcAMA4NgCIAAADADiMAMA4N5yQAAADADiUAEgAFABIAAgASAAoAEgAEABIACAASAAwAEgAGABIAAAAwDg1yJgAAAMAOJwAwDg2OKAAAAMAOKQAwDg1qKgAAAMAOKwAwDg00LAAAAIINAgAtA5IBBAAAAEADkwEDlAEDlQEDlgEDlwEDmAEEAABwQAOZAQOaAQObAQOcAQOdAQOeAQOfAQYABgEDoAEGBQMiBgYDLwYHAxUDoQEDogEDowEDUAUBHAOkAQYIAzQGCQNhBgoDYwYTA40BBhQDjgEGFQOPAQYWA5EBDAABBQYHCAkKExQVFgEAAQUAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAABAPoAAAAAAQAAAAAAAAEAAAAAAQAAAAAAAAEAAgAGAAYA7gACAAAAAABHAAAFAAAFAAAAAAABAQAA/wADAAAAAAajAAAAPwAACAAAAAAAAAAAAABuAAAFAAADAAADAQAAAAYAAAATAAAAXQAAAAAXezFsoTF4P41J9QY1PRmyuO0COFe0M045Wg1z8rHXTJ9cNWbtMpgoCw==

-- Decompiled by Krnl

local v_u_1 = game:GetService("RunService")
local v_u_2 = game:GetService("CollectionService")
local v_u_3 = game:GetService("Players")
local v4 = game:GetService("ReplicatedStorage")
local v_u_5 = require(v4.ManifestBinder)
local v_u_6 = require(v4.Std.Maid)
local v_u_7 = require(v4.Std.Interval)
local v_u_8 = require(v4.Roact)
local v_u_9 = require(v4.Std.BaseObject)
local v_u_10 = v_u_8.createElement
local function v_u_14(p11)
	-- upvalues: (copy) v_u_2
	local v12 = v_u_2:GetTags(p11)
	for _, v13 in ipairs(v12) do
		v_u_2:RemoveTag(p11, v13)
	end
end
local v_u_15 = {}
v_u_15.__index = v_u_15
function v_u_15.new(p16)
	-- upvalues: (copy) v_u_15, (copy) v_u_6, (copy) v_u_14
	local v17 = {}
	local v18 = v_u_15
	setmetatable(v17, v18)
	v17.character = p16
	v17._maid = v_u_6.new()
	v17.onScreen = false
	v17.lastOnScreenChanged = 0
	local v_u_19 = Instance.new("Model")
	local v_u_20 = {}
	local function v_u_22(p21)
		return (p21:IsA("BasePart") or (p21:IsA("Shirt") or (p21:IsA("Pants") or (p21:IsA("CharacterMesh") or (p21:IsA("WrapTarget") or (p21:IsA("Decal") or (p21:IsA("Accessory") or p21:IsA("Humanoid")))))))) and true or false
	end
	local function v_u_28(p23, p24)
		-- upvalues: (copy) v_u_20, (ref) v_u_14, (copy) v_u_28
		local v25 = p23:Clone()
		if v25 then
			local v26 = p23:IsA("CharacterAppearance") and p24:FindFirstChild(v25.Name)
			if v26 then
				v_u_20[v26] = nil
				v26:Destroy()
			end
			v25:ClearAllChildren()
			v25.Parent = p24
			v_u_14(v25)
			if v25:IsA("BasePart") then
				v25.Anchored = true
				v_u_20[v25] = p23
			elseif v25:IsA("Humanoid") then
				v25.DisplayDistanceType = Enum.HumanoidDisplayDistanceType.None
			end
			for _, v27 in ipairs(p23:GetChildren()) do
				v_u_28(v27, v25)
			end
			return v25
		end
	end
	local function v30(p29)
		-- upvalues: (copy) v_u_22, (copy) v_u_28, (copy) v_u_19
		if v_u_22(p29) then
			v_u_28(p29, v_u_19)
		end
	end
	for _, v31 in ipairs(p16:GetChildren()) do
		if v_u_22(v31) then
			v_u_28(v31, v_u_19)
		end
	end
	v17._maid:GiveTask(p16.ChildAdded:Connect(v30))
	v17.characterClone = v_u_19
	v17.cloneRef = v_u_20
	v17._maid:GiveTask(v_u_19)
	return v17
end
function v_u_15.Update(p32)
	for v33, v34 in pairs(p32.cloneRef) do
		v33.CFrame = v34.CFrame
	end
end
function v_u_15.Destroy(p35)
	p35._maid:Destroy()
	setmetatable(p35, nil)
end
local v36 = v_u_8.PureComponent:extend("CCTV")
v36.defaultProps = {
	["active"] = true
}
function v36.init(p37)
	-- upvalues: (copy) v_u_8, (copy) v_u_6
	p37.cameraRef = v_u_8.createRef()
	p37.viewportRef = v_u_8.createRef()
	p37.fuzzRef = v_u_8.createRef()
	p37._maid = v_u_6.new()
end
function v36.render(p38)
	-- upvalues: (copy) v_u_10, (copy) v_u_8
	local v39 = v_u_10
	local v40 = {
		["BorderSizePixel"] = 0,
		["BackgroundTransparency"] = p38.props.disabled and 0 or 1,
		["BackgroundColor3"] = Color3.new(0.4, 0, 0),
		["Size"] = p38.props.size,
		["Position"] = p38.props.position,
		["LayoutOrder"] = p38.props.layoutOrder,
		["AnchorPoint"] = Vector2.new(0.5, 0.5),
		["ClipsDescendants"] = true
	}
	local v41 = {
		["UICorner"] = v_u_10("UICorner", {
			["CornerRadius"] = UDim.new(0.015625, 0)
		}),
		["UIStroke"] = v_u_10("UIStroke", {
			["Color"] = Color3.new(1, 0, 0),
			["Thickness"] = 2,
			["Enabled"] = p38.props.active
		}),
		["AspectRatio"] = v_u_10("UIAspectRatioConstraint", {
			["AspectRatio"] = p38.props.aspectRatio
		}),
		["ViewportFrame"] = v_u_10("ViewportFrame", {
			["BackgroundTransparency"] = 1,
			["Size"] = UDim2.new(1, 0, 1, 0),
			["CurrentCamera"] = p38.cameraRef,
			["ZIndex"] = 1,
			["Visible"] = not p38.props.disabled,
			[v_u_8.Ref] = p38.viewportRef
		}, {
			["UICorner"] = v_u_10("UICorner", {
				["CornerRadius"] = UDim.new(0.015625, 0)
			}),
			["Camera"] = v_u_10("Camera", {
				["FieldOfView"] = p38.props.fieldOfView,
				["CFrame"] = p38.props.cameraCFrame,
				[v_u_8.Ref] = p38.cameraRef
			})
		}),
		["Fuzz"] = v_u_10("ImageLabel", {
			["BackgroundTransparency"] = 1,
			["Image"] = "rbxassetid://8260530429",
			["ImageTransparency"] = 0.5,
			["Size"] = UDim2.new(1.1, 0, 1.1, 0),
			["Position"] = UDim2.new(0.5, 0, 0.5, 0),
			["AnchorPoint"] = Vector2.new(0.5, 0.5),
			["ZIndex"] = 10,
			[v_u_8.Ref] = p38.fuzzRef
		}, {
			["UICorner"] = v_u_10("UICorner", {
				["CornerRadius"] = UDim.new(0.015625, 0)
			})
		}),
		["Flash"] = v_u_10("Frame", {
			["BackgroundTransparency"] = p38.props.flash,
			["BackgroundColor3"] = Color3.new(1, 1, 1),
			["Size"] = UDim2.new(1, 1, 1),
			["ZIndex"] = 20,
			["Visible"] = p38.props.flash ~= nil
		})
	}
	return v39("Frame", v40, v41)
end
function v36._clear(p42)
	local v43 = p42.viewportRef:getValue()
	for _, v44 in ipairs(v43:GetChildren()) do
		if not (v44:IsA("UICorner") or v44:IsA("Camera")) then
			v44:Destroy()
		end
	end
end
function v36._redraw(p_u_45)
	-- upvalues: (copy) v_u_6, (copy) v_u_3, (copy) v_u_14, (copy) v_u_5, (copy) v_u_9, (copy) v_u_15, (copy) v_u_7, (copy) v_u_1
	p_u_45:_clear()
	local v46 = v_u_6.new()
	p_u_45._maid.canvasMaid = v46
	local v_u_47 = p_u_45.viewportRef:getValue()
	local v48 = p_u_45.props.distance
	local v_u_49 = p_u_45.props.cameraCFrame
	local v50 = 2 * v48
	local v51 = p_u_45.props.fieldOfView / 2
	local v52 = math.rad(v51)
	local v53 = v50 * math.tan(v52)
	local v54 = v53 * p_u_45.props.aspectRatio
	local v55 = Vector3.new(v54, v53, v48)
	local v56 = { workspace:FindFirstChild("Items") }
	for _, v57 in ipairs(v_u_3:GetPlayers()) do
		if v57.Character then
			local v58 = v57.Character
			table.insert(v56, v58)
		end
	end
	local v59 = OverlapParams.new()
	v59.FilterType = Enum.RaycastFilterType.Blacklist
	v59.FilterDescendantsInstances = v56
	local v60 = workspace:GetPartBoundsInBox(v_u_49 * CFrame.new(0, 0, -v55.z * 0.5), v55, v59)
	for _, v61 in ipairs(v60) do
		local v62 = v61:Clone()
		if v62 then
			v_u_14(v62)
			for _, v63 in ipairs(v62:GetDescendants()) do
				v_u_14(v63)
			end
			v62.Parent = v_u_47
		end
	end
	local v65 = v_u_5.new("Character", {
		["HumanoidRootPart"] = "HumanoidRootPart"
	}, function(p64)
		-- upvalues: (ref) v_u_9
		return v_u_9.new(p64)
	end)
	v65:Start()
	local v_u_66 = {}
	for _, v67 in v65:GetAll() do
		local v68 = v67.obj
		local v69 = v_u_15.new(v68)
		v_u_66[v68] = v69
		v69.characterClone.Parent = v_u_47
	end
	v65:GetClassAddedSignal():Connect(function(p70)
		-- upvalues: (ref) v_u_15, (copy) v_u_66, (copy) v_u_47
		local v71 = p70.obj
		local v72 = v_u_15.new(v71)
		v_u_66[v71] = v72
		v72.characterClone.Parent = v_u_47
	end)
	v65:GetClassRemovingSignal():Connect(function(p73)
		-- upvalues: (copy) v_u_66
		local v74 = p73.obj
		local v75 = v_u_66[v74]
		if v75 then
			v75:Destroy()
		end
		v_u_66[v74] = nil
	end)
	v46:GiveTask(function()
		-- upvalues: (copy) v_u_66
		for _, v76 in v_u_66 do
			v76:Destroy()
		end
		table.clear(v_u_66)
	end)
	v46:GiveTask(v_u_7.every(0.1):Connect(function()
		-- upvalues: (copy) v_u_66, (copy) v_u_49, (copy) p_u_45
		local v77 = os.clock()
		for _, v78 in v_u_66 do
			local v79 = v78.character.PrimaryPart
			if v79 then
				local v80 = v79.Position - v_u_49.p
				local v81 = v80.Unit:Dot(v_u_49.LookVector)
				local v82
				if v80.Magnitude < p_u_45.props.distance then
					local v83 = p_u_45.props.aspectRatio * p_u_45.props.fieldOfView / 2
					local v84 = math.rad(v83)
					v82 = math.cos(v84) < v81
				else
					v82 = false
				end
				if v82 ~= v78.onScreen then
					v78.onScreen = v82
					v78.lastOnScreenChanged = v77
					if v82 and p_u_45.props.onCharacterEnter then
						p_u_45.props.onCharacterEnter(v78.character)
					end
				end
			end
			if v78.onScreen or v77 - v78.lastOnScreenChanged < 1 then
				v78:Update()
			end
		end
	end))
	local v_u_85 = p_u_45.fuzzRef:getValue()
	local v_u_86 = math.random() * 512
	v46:GiveTask(v_u_1.Heartbeat:Connect(function()
		-- upvalues: (copy) v_u_86, (copy) v_u_85
		local v87 = os.clock() * 512 + v_u_86
		local v88 = math.cos(v87)
		v_u_85.Position = UDim2.new(0.5, 0, v88 * 0.05 + 0.5, 0)
	end))
end
function v36.didUpdate(p89, p90)
	if (p89.props.cameraCFrame.p - p90.cameraCFrame.p).Magnitude > 0.1 then
		p89:_redraw()
	end
end
function v36.didMount(p91)
	p91:_redraw()
end
function v36.willUnmount(p92)
	p92._maid:DoCleaning()
end
return v36
