-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgONAQNuZXcFX21haWQFaW5kZXgIc2V0U3RhdGUSX3VwZGF0ZUNhbWVyYVBhcnRzDWNyZWF0ZUJpbmRpbmcFZmxhc2gLdXBkYXRlRmxhc2gEaW5pdAJvcwVjbG9jawRtYXRoA3NpbglIZWFydGJlYXQHQ29ubmVjdAZfZmxhc2gFcHJvcHMJY2FtZXJhVGFnCUdldFRhZ2dlZAtjYW1lcmFQYXJ0cw5jYW1lcmFQYXJ0TWFpZAZpcGFpcnMMQ0NUVkRpc2FibGVkGUdldEF0dHJpYnV0ZUNoYW5nZWRTaWduYWwIR2l2ZVRhc2sFc3RhdGUDR2V0BFNwb3QQb25DaGFyYWN0ZXJFbnRlcgZDRnJhbWUEU2l6ZQFaCENDVFZOYW1lDEdldEF0dHJpYnV0ZQZhY3RpdmUEc2l6ZQhwb3NpdGlvbghkaXN0YW5jZQthc3BlY3RSYXRpbwxjYW1lcmFDRnJhbWULZmllbGRPZlZpZXcLbGF5b3V0T3JkZXIIZGlzYWJsZWQFVURpbTIFRnJhbWUWQmFja2dyb3VuZFRyYW5zcGFyZW5jeQ9Cb3JkZXJTaXplUGl4ZWwQQmFja2dyb3VuZENvbG9yMwhQb3NpdGlvbgtMYXlvdXRPcmRlcgtBbmNob3JQb2ludAZDb2xvcjMHVmVjdG9yMgdQYWRkaW5nCFVJQ29ybmVyC0FzcGVjdFJhdGlvBUNsb3NlBE1haW4EU2lkZQlVSVBhZGRpbmcLUGFkZGluZ0xlZnQMUGFkZGluZ1JpZ2h0ClBhZGRpbmdUb3ANUGFkZGluZ0JvdHRvbQRVRGltDENvcm5lclJhZGl1cxdVSUFzcGVjdFJhdGlvQ29uc3RyYWludAtJbWFnZUJ1dHRvbhdyYnhhc3NldGlkOi8vNDkzMzE0Mzc4MQVJbWFnZQZaSW5kZXgKU2VsZWN0YWJsZQVFdmVudBBNb3VzZUJ1dHRvbjFEb3duDG9uQ2xpY2tDbG9zZQZDYW1lcmEGTnVtYmVyBVRpdGxlCVRleHRMYWJlbApUZXh0Q29sb3IzClRleHRTY2FsZWQEVGV4dARGb250CSUwMmQvJTAyZAZmb3JtYXQERW51bQtMdWNraWVzdEd1eQ5UZXh0WEFsaWdubWVudARMZWZ0BW1lcmdlCkxpc3RMYXlvdXQETmV4dARQcmV2DFVJTGlzdExheW91dBNIb3Jpem9udGFsQWxpZ25tZW50EVZlcnRpY2FsQWxpZ25tZW50CVNvcnRPcmRlcg1GaWxsRGlyZWN0aW9uBkNlbnRlcghWZXJ0aWNhbApUZXh0QnV0dG9uAAZyZW5kZXILZ2V0Um9vdFBhcnQLTG9jYWxQbGF5ZXIJQ2hhcmFjdGVyCU1hZ25pdHVkZQ5leHBpcmVEaXN0YW5jZRZHZXRJbnN0YW5jZUFkZGVkU2lnbmFsGEdldEluc3RhbmNlUmVtb3ZlZFNpZ25hbAtPYmplY3RMb2NhbAlQbGF5ZXJHdWkGVm9sdW1lBkxvb3BlZAVldmVyeQhkaWRNb3VudApEb0NsZWFuaW5nC3dpbGxVbm1vdW50BGdhbWUKUnVuU2VydmljZQpHZXRTZXJ2aWNlB1BsYXllcnMRQ29sbGVjdGlvblNlcnZpY2URUmVwbGljYXRlZFN0b3JhZ2UHcmVxdWlyZQNTdGQOQ2hhcmFjdGVyVXRpbHMERXpVaQpEaWN0aW9uYXJ5CEludGVydmFsBUF1ZGlvBE1haWQFUm9hY3QNY3JlYXRlRWxlbWVudAZzY3JpcHQGUGFyZW50BENDVFYMQ2FtZXJhQmluZGVyDVB1cmVDb21wb25lbnQGVmlld2VyBmV4dGVuZAAPBQECAAAAGvsCAABNAQLvAAAAAJ8BAQIwAQDBAQAAAOIDAwCMBAEAMAQDAgIAAAC8AQAqBAAAAJ8BAwG8AQCZBQAAAJ8BAgH7AgEATQECMQYAAACMAgEAnwECAzABAKcHAAAAMAIAYAgAAACCAAEACQMBAwIDAwUBAgMEAwUDBgMHAwgAEgkBGAAAAAAAAAEBAAD/AAADAAABAAAAAAAAAAABEwAAAAAHAAIAAAAepAACAAAEAICfAAEC+wMAACYCAAM+AQIDjAIBAGACCAABAAAAjAEBAPsDAQBNAgPBBAAAAMYDAAAwAwKnBQAAAG8FBwCVBgEDCQQFBj4DBAa7GAMCpAIKAAAkgICfAgIC+wQBAE0DBGALAAAA9QQMAp8DAgGCAAEADQMKAwsEAAQAgAIAAAAAAADQPwMCAwcCAAAAAAAA9D8CGC1EVPshCUADDAMNBAAkgIADCAIAAAAAAADwPwAdAAEYAAAAAQAAAQAAAQEAAAAAAAIAAAAAAAAAAQAAAAABHgAAAAAGAQEAAAARpAECAAAEAICfAQECTQIAwQMAAAD7BAAATQME/QQAAADZBQAAEgABABIAAAC8AwPHBQAAAJ8DAwIwAwKnBgAAAIIAAQAHAwoDCwQABACAAwIDDgMPAwcBARoQARgAAAACAAAAAAAAAAAAAAAAChsAAAAAAgABAAAABfsAAAC8AACZAAAAAJ8AAgGCAAEAAQMFADAAARgAAAAAATEAAAAADQECAAAAKvsBAABNBAAHAAAAAE0DBEgBAAAAvAEBBQIAAACfAQMC4gQEADABBHYDAAAAvAIAKgUAAACfAgMB+wMBAE0CA+8GAAAAnwIBAk0DAMEHAAAAMAIDUQgAAACkAwoAAACQQFIEAQCfAwIEUQMMAG8MCwC8CgcWDAAAAJ8KAwLZDAAAEgAAALwKCscNAAAAnwoDALwIAv0OAAAAnwgAAW4D8/8CAACAggABAA8DEQMSAxMDFAUBAwMEAwEDAgMVAxYEAACQQAMXAxgDDwMZAQMoBQEYAAAAAAAAAAABAQD/AAADAAAAAQAAAAEAAAAAAQAAAAAAAAAAAAAA/wAFKQAAAAAIAQIAAAAY+wEAAPsGAQBNBQYYAAAAAE0EBXYBAAAA+wcBAE0GBxgAAAAATQUGAgIAAACHAwQFvAEBfwMAAACfAQMCUgQAALwCARAEAAAAnwIDAfsCAQC8AgKzBQAAAJ8CAgGCAAEABgMaAxQDAwMbAxwDEACGAR0BGAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAYcAAAAACgACAAAAE/sAAADiAgEA+wkAAE0ICRgDAAAATQcIAgAAAACVBgcCeAUGAvsHAQAcBgcAzwQFBpUDBAIwAwICAAAAALwAACoEAAAAnwADAYIAAQAFAwMFAQACAAAAAAAA8D8DGgMEANIBAAEYAAABAAAAAAAAAAAAAAAA/wAAA9MAAAAACgACAAAAE/sAAADiAgEA+wkAAE0ICRgDAAAATQcIAgAAAAB4BgcCeAUGAvsHAQAcBgcAzwQFBpUDBAIwAwICAAAAALwAACoEAAAAnwADAYIAAQAFAwMFAQACAAAAAAAA8D8DGgMEAO0BAAEYAAABAAAAAAAAAAAAAAAA/wAAA+4AAAAAGgEFAAAIAAABAxTpAwKHB00CABgAAAAATQECdgEAAAAOAQcATQMAGAAAAABNAgN2AQAAABwBAgANAQIAAgAAgIIAAQD/AQAAAAAAAP8CAAAAAAAA/wMAAAAAAACMBgEATQgAGAAAAABNBwh2AQAAABwEBwCMBQEAqAQjAE0JABgAAAAATQgJdgEAAACHBwgGTQkHhQMAAACkCgUAABAwgIwLAACMDAAATRAHLwcAAABNDxB7CAAAADkODwBbDQ4GnwoEAgkICQpqCAEGbwoJALwIBxIKAAAAnwgDAmoIAgZvCwsAvAkHEgoAAACfCQMCKgkCAAEAAACpCAABqQgBAGoIAwaLBN3//wQAAAAAAACMBwEAjAUDAIwGAQCoBT4ATQ0AGAAAAABNDA0CDQAAAEMLDAd4CgsMHAsBAM8JCguVCAkM+wkAAPsKAQDiCxcAqQwAADAMC+MOAAAApAwZAAAQgIGMDQEAjA4AAIwPAQCMEAAAnwwFAjAMCw8PAAAApAwZAAAQgIFvDQYAjA4AAG8PBgCMEAAAnwwFAjAMC9sQAAAATQ0ABxoAAABNDA11EQAAADAMC3URAAAATQ0ABxoAAABNDA2JEgAAADAMC4kSAAAAhwwBCDAMC8ETAAAATQ0ABxoAAABNDA2BFAAAADAMC4EUAAAAMAcLIBUAAACHDAMIMAwLghYAAACfCQMCagkECIsFwv/7BQAAbwYbAOIHIgCMCAAAMAgHOhwAAACMCAAAMAgHjh0AAACkCCQAABAwgm8JJQBvCiUAbwslAJ8IBAIwCAefHgAAAE0JAAcaAAAATQgJDw8AAAAwCAcvBwAAAE0JAAcaAAAATQgJ2xAAAAAwCAc7HwAAAE0JAAcaAAAATQgJIBUAAAAwCAcAIAAAAKQIJwAAEGCCbwkGAG8KBgCfCAMCMAgH6CEAAADiCC4A+wkAAG8KLwDiCzQApAw2AAAQUINvDTcAjA4AAJ8MAwIwDAu+MAAAAKQMNgAAEFCDbw03AIwOAACfDAMCMAwLvjEAAACkDDYAABBQg28NOACMDgAAnwwDAjAMCzEyAAAApAw2AAAQUINvDTgAjA4AAJ8MAwIwDAvsMwAAAJ8JAwIwCQjdKAAAAPsJAABvCikA4gs6AKQMNgAAEFCDbw03AIwOAACfDAMCMAwLTzkAAACfCQMCMAkI9CkAAAD7CQAAbwo7AOILPABvDD0AMAwLaSoAAACfCQMCMAkIaSoAAAD7CQAAbwo+AP8LBAAAAAAAjAwBADAMCzocAAAAbww/ADAMC6lAAAAApAwnAAAQYIJvDUEAbw5BAJ8MAwIwDAvoIQAAAIwMAwAwDAsNQgAAAKQMGQAAEICBjA0AAIwOAACMDwAAnwwEAjAMCzsfAAAApAwZAAAQgIFvDSUAjA4AAG8PJQCMEAAAnwwFAjAMCy8HAAAAqQwBADAMCyRDAAAA+w4CAE0NDjZEAAAATQwNYUUAAABNDgAHGgAAAE0NDv9GAAAAag0LDOIMPAD7DQAAbw47AOIPPACMEAEAMBAPaSoAAACfDQMCMA0MaSoAAACfCQQCMAkIYysAAAD7CQAAbwobAOILRwCMDAEAMAwLOhwAAACkDBkAABCAgW8NSACMDgAAjA8BAIwQAACfDAUCMAwLLwcAAADiDEwA+w0AAG8OLwDiD00ApBA2AAAQUINvETcAjBIAAJ8QAwIwEA++MQAAAJ8NAwIwDQzdKAAAAPsNAAD7DgEA4g9QAKQQGQAAEICBjBEBAIwSAACMEwEAjBQAAJ8QBQIwEA8PDwAAAKQQGQAAEICBbxEGAIwSAABvEwYAjBQAAJ8QBQIwEA/bEAAAAE0RAAcaAAAATRARdREAAAAwEA91EQAAAE0RAAcaAAAATRARiRIAAAAwEA+JEgAAAE0SABgAAAAATRESAg0AAACHEAERMBAPwRMAAABNEQAHGgAAAE0QEYEUAAAAMBAPgRQAAABNEgAYAAAAAE0REgINAAAAhxADETAQD4IWAAAATRAAp04AAAAwEA+nTgAAANkQAAASAgMAEgAAADAQD7dPAAAAnw0DAjANDFlJAAAA+w0AAG8OGwDiD1EAjBAAADAQD44dAAAApBAkAAAQMIKMEQAAjBIAAIwTAACfEAQCMBAPnx4AAACMEAEAMBAPOhwAAACkEBkAABCAgW8RUgCMEgAAjBMBAIwUAACfEAUCMBAPLwcAAACkECcAABBggowRAQCMEgEAnxADAjAQD+ghAAAApBAZAAAQgIFvEVMAjBIAAG8TUwCMFAAAnxAFAjAQDzsfAAAAjBADADAQDw1CAAAA4hBUAPsRAABvEjsA4hM8AIwUAwAwFBNpKgAAAJ8RAwIwERBpKgAAAPsRAABvElUA4hNaAIwUAQAwFBM6HAAAAKQUGQAAEICBjBUBAIwWAACMFwEAjBgAAJ8UBQIwFBMvBwAAAKQUJwAAEGCCbxUGAG8WBgCfFAMCMBQT6CEAAACkFBkAABCAgW8VBgCMFgAAbxdBAIwYAACfFAUCMBQTOx8AAACkFCQAABAwgowVAQCMFgEAjBcBAJ8UBAIwFBNzVgAAAKkUAQAwFBPeVwAAAG8UWwBNFwAYAAAAAE0WFwINAAAAHBcBALwUFI1cAAAAnxQEAjAUE/VYAAAApBRfAF5k0cUwFBM5WQAAAJ8RAwIwERC6SwAAAJ8NBAIwDQwASgAAAPsNAABvDhsA4g9RAIwQAAAwEA+OHQAAAKQQJAAAEDCCjBEAAIwSAACMEwAAnxAEAjAQD58eAAAAjBABADAQDzocAAAApBAZAAAQgIFvEQYAjBIAAIwTAQCMFAAAnxAFAjAQDy8HAAAApBAnAAAQYIKMEQAAjBIAAJ8QAwIwEA/oIQAAAKQQGQAAEICBbxFgAIwSAABvE2AAjBQAAJ8QBQIwEA87HwAAAIwQAwAwEA8NQgAAAOIQVAD7EQAAbxI7AOITPACMFAgAMBQTaSoAAACfEQMCMBEQaSoAAAD7EQAAbxJVAOITYgCMFAEAMBQTOhwAAACkFBkAABCAgYwVAQCMFgAAjBcBAIwYAACfFAUCMBQTLwcAAACkFCcAABBggm8VBgBvFgYAnxQDAjAUE+ghAAAApBQZAAAQgIFvFQYAjBYAAG8XQQCMGAAAnxQFAjAUEzsfAAAApBQkAAAQMIKMFQEAjBYBAIwXAQCfFAQCMBQTc1YAAACpFAEAMBQT3lcAAABNFgAYAAAAAE0VFgINAAAAhxQCFTAUE/VYAAAApBRfAF5k0cUwFBM5WQAAAKQUZABjhNHFMBQTe2EAAACfEQMCMBEQuksAAACfDQQCMA0MuksAAACfCQQCMAkIWiwAAAD7CQAAbwobAOILZQCMDAEAMAwLOhwAAACkDBkAABCAgW8NUgCMDgAAjA8BAIwQAACfDAUCMAwLLwcAAACkDBkAABCAgW8NSACMDgAAjA8AAIwQAACfDAUCMAwLOx8AAAD7DQQATQwNH2YAAADiDWoA+w4AAG8PawDiEHAApBFyAHGw0cUwERBibAAAAKQRcwBxtNHFMBEQeG0AAACkEXQAILjRxTARELluAAAApBF2AHW80cUwERBRbwAAAKQRNgAAEFCDbxJ3AIwTAACfEQMCMBEQ3SgAAACfDgMCMA4NLmcAAAD7DgAAbw94AP8QBAAAAAAAjBEAADAREDocAAAAjBEAADAREI4dAAAApBEkAAAQMIJvEnkAbxN5AG8UeQCfEQQCMBEQnx4AAACkERkAABCAgYwSAQCMEwAAjBQBAIwVAACfEQUCMBEQLwcAAACMEWQAMBEQACAAAABvEXoAMBEQ9VgAAAD7EwIATRITNkQAAABNERJhRQAAANkSAQASAAAAEgABAGoSEBHiEVQA+xIAAG8TOwDiFDwAjBUGADAVFGkqAAAAnxIDAjASEWkqAAAA+xIAAG8TVQDiFFoAjBUBADAVFDocAAAApBUZAAAQgIGMFgEAjBcAAIwYAQCMGQAAnxUFAjAVFC8HAAAApBUnAAAQYIJvFgYAbxcGAJ8VAwIwFRToIQAAAKQVGQAAEICBbxYGAIwXAABvGHsAjBkAAJ8VBQIwFRQ7HwAAAKQVJAAAEDCCjBYBAIwXAQCMGAEAnxUEAjAVFHNWAAAAqRUBADAVFN5XAAAAbxVoADAVFPVYAAAApBVfAF5k0cUwFRQ5WQAAAJ8SAwIwEhG6SwAAAJ8OBAIwDg3zaAAAAPsOAABvD3gA/xAEAAAAAACMEQAAMBEQOhwAAACMEQAAMBEQjh0AAACkESQAABAwgm8SeQBvE3kAbxR5AJ8RBAIwERCfHgAAAKQRGQAAEICBjBIBAIwTAACMFAEAjBUAAJ8RBQIwERAvBwAAAIwRZQAwERAAIAAAAG8RegAwERD1WAAAAPsTAgBNEhM2RAAAAE0REmFFAAAA2RICABIAAAASAAEAahIQEeIRVAD7EgAAbxM7AOIUPACMFQYAMBUUaSoAAACfEgMCMBIRaSoAAAD7EgAAbxNVAOIUWgCMFQEAMBUUOhwAAACkFRkAABCAgYwWAQCMFwAAjBgBAIwZAACfFQUCMBUULwcAAACkFScAABBggm8WBgBvFwYAnxUDAjAVFOghAAAApBUZAAAQgIFvFgYAjBcAAG8YewCMGQAAnxUFAjAVFDsfAAAApBUkAAAQMIKMFgEAjBcBAIwYAQCfFQQCMBUUc1YAAACpFQEAMBUU3lcAAABvFWkAMBUU9VgAAACkFV8AXmTRxTAVFDlZAAAAnxIDAjASEbpLAAAAnw4EAjAODXtpAAAAUg4EAJ8MAwCfCQACMAkI0i0AAACfBQQAggUAAHwDGgMUAgAAAAAAAAAAAx4DAQQAEDCAAgAAAAAAAOA/Ax8DIAMhAyIDFwIAAAAAAADwPwMDAyMDJAMlAyYDJwMoAykDKgMrBQkODxAREhMUFRYDLAQAEICBAxEDLQMuAy8DMAMxAzIDMwUHHB0eBx8gIQM0BAAQMIICmpmZmZmZuT8DNQQAEGCCAzYDNwM4AzkDOgM7BQYoKSorLC0DPAM9Az4DPwNABQQwMTIzA0EEABBQgwIAAAAAAACQPwIzMzMzMzOhPwNCBQE5A0MFASoCMzMzMzMzAUADRANFA0YCMzMzMzMz4z8DRwNIA0kDSgNLBQIcBwKamZmZmZnpPwNMA00DTgUEKElKSwUBMQMHAx0FCQ8QERITFBZOTwUHHR4cByEfQgKamZmZmZnJPwJcj8L1KFzvPwUCKksDTwNQA1EDUgNTBQgcByEfVldYWQNUA1UDVgNXBF5k0cUCexSuR+F6lD8DWAUJHAchH1ZXWFlhA1kEY4TRxQUDHAcfA1oDWwNcA10FA2doaQNeA18DYANhA2IFBWxtbm8oA2MEcbDRxQRxtNHFBCC40cUDZAR1vNHFAmq8dJMYBJY/A2UCMzMzMzMz0z8DZgLNzMzMzMzkPwMFBgc1ZwEYAAAAAAAAAAAAAAAAAQIAAQABAAEAAAAAAAAAAQAAAAABAAAAAAAAAAAAAAAAAAABAAAAAAEAAAAAAAAAAPwIAAEAAAABAAAAAAAAAAABAAABAAABAAAAAAAAAAABAAAAAAAAAAABAAAAAAABAAAAAAABAAABAAAAAAABAAEAAPcA/g4AAAEAAAEAAAEAAAAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAAEBAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAA/AAABgAAAQAAAAAAAP8AAAMAAAEAAP8AAAMAAAABAAABAAABAAAAAAAAAQAAAQAAAAAAAAABAAAAAAAAAAABAAABAAAAAAAAAAAAAQEAAAEAAP8AAPYAAA4AAAEAAAEAAAAAAAAAAAEBAAABAAAAAAAA/wAAAwAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAAEAAAAAAAEAAAAAAAABAAAAAQAAAAD3AAAPAAABAAABAAAAAAAAAAEAAAEAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAABAAABAQAAAQAA/wAAAwAAAQAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAQAAAQAAAAAAAAAAAAABAAAA+AAA9AAAFwAAAQAAAQAAAAAAAAABAAABAAAAAAAAAAABAAAAAAAAAQAAAAAAAAAAAQAAAQEAAAEAAP8AAAMAAAEAAAEAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAABAAAAAAAAAAEAAAEAAAAAAAABAAAAAQAAAPcAAPQAANMAAEYBAQEAAAEAAAAAAAAAAAEAAAAAAAAAAAIAAAABAAABAAAAAQAAAAEAAAABAAAAAQAAAAAAAPsAAAcAAAABAAABAAABAAAAAAAAAAEAAAAAAAAAAAEAAAEAAAEAAAAAAAAAAAUBAAABAAD/AAADAAABAAABAAAAAAAAAAABAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAABAAABAAABAAAA+AAA8AAAGwAAAAEAAAEAAAEAAAAAAAAAAQAAAAAAAAAAAQAAAQAAAQAAAAAAAAAABQEAAAEAAP8AAAMAAAEAAAEAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAABAAAAAAAAAAEAAAEAAAEAAAD4AADwAAAbwvkAAJcANgAAAAACAAEAAAAF+wAAALwAAJkAAAAAnwACAYIAAQABAwUAiAIAARgAAAAAAQkBAAAAAgABAAAABfsAAAC8AACZAAAAAJ8AAgGCAAEAAQMFAIsCAAEYAAAAAAEMAQAAAAQABQAAACj7AQEATQABGwAAAAD7AwIATQIDMQEAAABNAQJpAgAAAJ8AAgLeAAAA+wAAAA4AFQD7AwAATQIDOwMAAAD7AwMAJgECA00AAaoEAAAA+wMEAE0CAwcFAAAATQEC5wYAAABgAQ4AAAAAAPsDBABNAgMHBQAAAE0BAv8HAAAAnwEBAYIAAQD7AgQATQECBwUAAABNAAH/BwAAAJ8AAQGCAAEACANoA2kDagMxA2sDEQNsA0sAmAIAARgAAAAAAAAAAAAAAQABAAAAAAAAAQAAAAAAAAEAAAAAAAADAAAAAAACGQEAAAAIAQUAAABpTQEAYAAAAACMAgEAnwECAU0BAMEBAAAA+wMAAE0GAAcCAAAATQUGSAMAAAC8AwNeBAAAAJ8DAwLZBQAAEgAAALwDA8cFAAAAnwMDALwBAf0GAAAAnwEAAU0BAMEBAAAA+wMAAE0GAAcCAAAATQUGSAMAAAC8AwPcBwAAAJ8DAwLZBQEAEgAAALwDA8cFAAAAnwMDALwBAf0GAAAAnwEAAfsCAQBNAQIxCAAAAA4BFwD7AgIATQEC0QkAAAD7BAEATQMEMQgAAABNAgOZCgAAAG8DCwDiBA4AbwUPADAFBEsMAAAAqQUBADAFBLUNAAAAnwEEAk0CAMEBAAAAUgQBALwCAv0GAAAAnwIDAU0CAAcCAAAATQEC5xAAAAAOASAA+wIDAE0BAhsRAAAA+wQBAE0DBDEIAAAATQIDaRIAAACfAQICDgEVAE0CATsTAAAATQMAwQEAAAD7BgQATQUGxBQAAACMBgEAnwUCAtkHAgASAQH/EgIDABICAQASAAIAEgAAALwFBccFAAAAnwUDALwDA/0GAAAAnwMAAcEBAACCAAEAFQMIAwIDEQMSA20DDwMZA24DaQNvA3ACAAD4N1/fAEIDcQNyBQIMDQIzMzMzMzPjPwNsA2gDagMxA3MDCQoLhQJ0ARgAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAwAAAAIAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAwAAAAABAAAAAAAAAAABAQABAAAAAAAAAAAAAAAAAAAAAAAAAA0GAQAAAAMBAAAAAAZNAQDBAAAAALwBAVEBAAAAnwECAYIAAQACAwIDdQCmAnYBGAAAAAAAAScBAAAAEQAAAQIAf6MAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQEAAAAAQG8DBAC8AQEWAwAAAJ8BAwKkAgEAAAAAQG8EBQC8AgIWAwAAAJ8CAwKkAwEAAAAAQG8FBgC8AwMWAwAAAJ8DAwKkBAgAAABwQE0GA6EJAAAATQUGlgoAAACfBAICpAUIAAAAcEBNBwMtCwAAAE0GB6kMAAAAnwUCAqQGCAAAAHBATQgDoQkAAABNBwisDQAAAJ8GAgKkBwgAAABwQE0JA6EJAAAATQgJ0g4AAACfBwICpAgIAAAAcEBNCgOhCQAAAE0JCnYPAAAAnwgCAqQJCAAAAHBATQoDIRAAAACfCQICTQoJyhEAAACkCwgAAABwQKQOEwAAACBBTQ0OJBQAAABNDA2PFQAAAJ8LAgKkDAgAAABwQKQQEwAAACBBTQ8QJBQAAABNDg8kFAAAAE0NDpYWAAAAnwwCAk0NCfgXAAAAbw8YALwNDZwZAAAAnw0DAsAOGgASAAgAEgAJADAODRMbAAAAwA4cABIAAAAwDg2zHQAAAMAOHgASAAIAEgAIADAODZkfAAAAwA4gABIACgASAAsAEgAJABIADAASAAUAMA4NgCEAAADADiIAEgACABIAAQASAAcAEgAEABIABgAwDg1qIwAAAMAOJAAwDg00JQAAAIINAgAmA3cEAAAAQAN4A3kDegN7A3wDfQQAAHBAA34DfwOAAQOBAQOCAQODAQOEAQOFAQOGAQOHAQQAACBBA4gBA4kBA4oBA4sBA4wBA40BBgADCQYCAxAGBAMFBggDZwYMA3QGDQN2BgACBAgMDQEAAQQAAQAAAAAAAQAAAAAAAQAA/QAAAQAAAAAAAQAAAAAAAP4AAAAAAAABAAAAAAAAAQD+AAAAAAEAAAAAAAABAAAA/gEAAgAAAAAAAAAAAQAAAPwAAAAAAAACAAAAAAABAAD9AAgAAAAOAAAAAA0AAAAA3QAA0AAAAAAAAAAhAAADAQAAAAMAAAADAAAAAgAAAAIAAAAEAAAAAwAAACMAAAAADlAodCM4TtUqYuwet4gZ7hgz0gbqeAZJaTh2qzbSwdn0byQ+/DMwNHE=

-- Decompiled by Krnl

local v_u_1 = game:GetService("RunService")
local v_u_2 = game:GetService("Players")
local v_u_3 = game:GetService("CollectionService")
local v4 = game:GetService("ReplicatedStorage")
local v_u_5 = require(v4.Std.CharacterUtils)
local v_u_6 = require(v4.EzUi.Dictionary)
local v_u_7 = require(v4.Std.Interval)
local v_u_8 = require(v4.Std.Audio)
local v_u_9 = require(v4.Std.Maid)
local v_u_10 = require(v4.Roact)
local v_u_11 = v_u_10.createElement
local v_u_12 = require(script.Parent.CCTV)
local v_u_13 = require(script.Parent.Parent.CameraBinder)
local v14 = v_u_10.PureComponent:extend("Viewer")
function v14.init(p15)
	-- upvalues: (copy) v_u_9, (copy) v_u_10
	p15._maid = v_u_9.new()
	p15:setState({
		["index"] = 1
	})
	p15:_updateCameraParts()
	local v16, v17 = v_u_10.createBinding(1)
	p15.flash = v16
	p15.updateFlash = v17
end
function v14._flash(p_u_18)
	-- upvalues: (copy) v_u_1
	local v_u_19 = os.clock()
	p_u_18._maid.flash = v_u_1.Heartbeat:Connect(function()
		-- upvalues: (copy) v_u_19, (copy) p_u_18
		local v20 = (os.clock() - v_u_19) / 0.25
		if v20 > 1 then
			p_u_18._maid.flash = nil
			v20 = 1
		end
		local v21 = 3.141592653589793 * (v20 + 0.25) / 1.25
		local v22 = math.sin(v21)
		p_u_18.updateFlash(1 - v22)
	end)
end
function v14._updateCameraParts(p_u_23)
	-- upvalues: (copy) v_u_3, (copy) v_u_9
	local v24 = v_u_3:GetTagged(p_u_23.props.cameraTag)
	p_u_23:setState({
		["cameraParts"] = v24
	})
	local v25 = v_u_9.new()
	p_u_23._maid.cameraPartMaid = v25
	for _, v26 in ipairs(v24) do
		v25:GiveTask(v26:GetAttributeChangedSignal("CCTVDisabled"):Connect(function()
			-- upvalues: (copy) p_u_23
			p_u_23:_updateCameraParts()
		end))
	end
end
function v14.render(p_u_27)
	-- upvalues: (copy) v_u_11, (copy) v_u_12, (copy) v_u_10, (copy) v_u_13, (copy) v_u_6
	if p_u_27.state.cameraParts and #p_u_27.state.cameraParts ~= 0 then
		local v_u_28 = {}
		local v29 = {}
		local v30 = {}
		for v31 = 1, #p_u_27.state.cameraParts do
			local v32 = p_u_27.state.cameraParts[v31]
			v_u_28[v31] = v32.CFrame * CFrame.new(0, 0, -v32.Size.Z * 0.5)
			v29[v31] = v32:GetAttribute("CCTVName")
			v30[v31] = v32:GetAttribute("CCTVDisabled") == true
		end
		local v33 = {}
		for v34 = 1, 3 do
			local v35 = (p_u_27.state.index + v34 - 1) % #v_u_28 + 1
			v33[v35] = v_u_11(v_u_12, {
				["active"] = false,
				["size"] = UDim2.new(1, 0, 1, 0),
				["position"] = UDim2.new(0.5, 0, 0.5, 0),
				["distance"] = p_u_27.props.distance,
				["aspectRatio"] = p_u_27.props.aspectRatio,
				["cameraCFrame"] = v_u_28[v35],
				["fieldOfView"] = p_u_27.props.fieldOfView,
				["layoutOrder"] = v34,
				["disabled"] = v30[v35]
			})
		end
		local v36 = v_u_11
		local v37 = {
			["BackgroundTransparency"] = 0,
			["BorderSizePixel"] = 0,
			["BackgroundColor3"] = Color3.new(0.1, 0.1, 0.1),
			["Size"] = p_u_27.props.size,
			["Position"] = p_u_27.props.position,
			["LayoutOrder"] = p_u_27.props.layoutOrder,
			["AnchorPoint"] = Vector2.new(0.5, 0.5)
		}
		local v39 = {
			["Padding"] = v_u_11("UIPadding", {
				["PaddingLeft"] = UDim.new(0.015625, 0),
				["PaddingRight"] = UDim.new(0.015625, 0),
				["PaddingTop"] = UDim.new(0.03359375, 0),
				["PaddingBottom"] = UDim.new(0.03359375, 0)
			}),
			["UICorner"] = v_u_11("UICorner", {
				["CornerRadius"] = UDim.new(0.015625, 0)
			}),
			["AspectRatio"] = v_u_11("UIAspectRatioConstraint", {
				["AspectRatio"] = 2.15
			}),
			["Close"] = v_u_11("ImageButton", {
				["BackgroundTransparency"] = 1,
				["Image"] = "rbxassetid://4933143781",
				["AnchorPoint"] = Vector2.new(0.6, 0.6),
				["ZIndex"] = 3,
				["Position"] = UDim2.new(0, 0, 0),
				["Size"] = UDim2.new(0.1, 0, 0.1, 0),
				["Selectable"] = true,
				[v_u_10.Event.MouseButton1Down] = p_u_27.props.onClickClose
			}, {
				["AspectRatio"] = v_u_11("UIAspectRatioConstraint", {
					["AspectRatio"] = 1
				})
			}),
			["Main"] = v_u_11("Frame", {
				["BackgroundTransparency"] = 1,
				["Size"] = UDim2.new(0.8, 0, 1, 0)
			}, {
				["Padding"] = v_u_11("UIPadding", {
					["PaddingRight"] = UDim.new(0.015625, 0)
				}),
				["Camera"] = v_u_11(v_u_12, {
					["size"] = UDim2.new(1, 0, 1, 0),
					["position"] = UDim2.new(0.5, 0, 0.5, 0),
					["distance"] = p_u_27.props.distance,
					["aspectRatio"] = p_u_27.props.aspectRatio,
					["cameraCFrame"] = v_u_28[p_u_27.state.index],
					["fieldOfView"] = p_u_27.props.fieldOfView,
					["disabled"] = v30[p_u_27.state.index],
					["flash"] = p_u_27.flash,
					["onCharacterEnter"] = function(p38)
						-- upvalues: (ref) v_u_13, (copy) p_u_27
						v_u_13:Get(p_u_27.state.cameraParts[p_u_27.state.index]):Spot(p38)
						p_u_27:_flash()
					end
				}),
				["Number"] = v_u_11("Frame", {
					["BorderSizePixel"] = 0,
					["BackgroundColor3"] = Color3.new(0, 0, 0),
					["BackgroundTransparency"] = 1,
					["Size"] = UDim2.new(0.2, 0, 1, 0),
					["AnchorPoint"] = Vector2.new(1, 1),
					["Position"] = UDim2.new(0.98, 0, 0.98, 0),
					["ZIndex"] = 3
				}, {
					["AspectRatio"] = v_u_11("UIAspectRatioConstraint", {
						["AspectRatio"] = 3
					}),
					["Title"] = v_u_11("TextLabel", {
						["BackgroundTransparency"] = 1,
						["Size"] = UDim2.new(1, 0, 1, 0),
						["AnchorPoint"] = Vector2.new(0.5, 0.5),
						["Position"] = UDim2.new(0.5, 0, 0.6, 0),
						["TextColor3"] = Color3.new(1, 1, 1),
						["TextScaled"] = true,
						["Text"] = ("%02d/%02d"):format(p_u_27.state.index, #v_u_28),
						["Font"] = Enum.Font.LuckiestGuy
					})
				}),
				["Title"] = v_u_11("Frame", {
					["BorderSizePixel"] = 0,
					["BackgroundColor3"] = Color3.new(0, 0, 0),
					["BackgroundTransparency"] = 1,
					["Size"] = UDim2.new(0.5, 0, 1, 0),
					["AnchorPoint"] = Vector2.new(0, 0),
					["Position"] = UDim2.new(0.02, 0, 0.02, 0),
					["ZIndex"] = 3
				}, {
					["AspectRatio"] = v_u_11("UIAspectRatioConstraint", {
						["AspectRatio"] = 8
					}),
					["Title"] = v_u_11("TextLabel", {
						["BackgroundTransparency"] = 1,
						["Size"] = UDim2.new(1, 0, 1, 0),
						["AnchorPoint"] = Vector2.new(0.5, 0.5),
						["Position"] = UDim2.new(0.5, 0, 0.6, 0),
						["TextColor3"] = Color3.new(1, 1, 1),
						["TextScaled"] = true,
						["Text"] = v29[p_u_27.state.index],
						["Font"] = Enum.Font.LuckiestGuy,
						["TextXAlignment"] = Enum.TextXAlignment.Left
					})
				})
			}),
			["Side"] = v_u_11("Frame", {
				["BackgroundTransparency"] = 1,
				["Size"] = UDim2.new(0.2, 0, 1, 0),
				["Position"] = UDim2.new(0.8, 0, 0, 0)
			}, v_u_6.merge({
				["ListLayout"] = v_u_11("UIListLayout", {
					["HorizontalAlignment"] = Enum.HorizontalAlignment.Center,
					["VerticalAlignment"] = Enum.VerticalAlignment.Center,
					["SortOrder"] = Enum.SortOrder.LayoutOrder,
					["FillDirection"] = Enum.FillDirection.Vertical,
					["Padding"] = UDim.new(0.0215, 0)
				}),
				["Next"] = v_u_11("TextButton", {
					["BackgroundTransparency"] = 0,
					["BorderSizePixel"] = 0,
					["BackgroundColor3"] = Color3.new(0.3, 0.3, 0.3),
					["Size"] = UDim2.new(1, 0, 1, 0),
					["LayoutOrder"] = 100,
					["Text"] = "",
					[v_u_10.Event.MouseButton1Down] = function()
						-- upvalues: (copy) p_u_27, (copy) v_u_28
						p_u_27:setState({
							["index"] = (p_u_27.state.index + 1 - 1) % #v_u_28 + 1
						})
					end
				}, {
					["AspectRatio"] = v_u_11("UIAspectRatioConstraint", {
						["AspectRatio"] = 6
					}),
					["Title"] = v_u_11("TextLabel", {
						["BackgroundTransparency"] = 1,
						["Size"] = UDim2.new(1, 0, 1, 0),
						["AnchorPoint"] = Vector2.new(0.5, 0.5),
						["Position"] = UDim2.new(0.5, 0, 0.65, 0),
						["TextColor3"] = Color3.new(1, 1, 1),
						["TextScaled"] = true,
						["Text"] = "Next",
						["Font"] = Enum.Font.LuckiestGuy
					})
				}),
				["Prev"] = v_u_11("TextButton", {
					["BackgroundTransparency"] = 0,
					["BorderSizePixel"] = 0,
					["BackgroundColor3"] = Color3.new(0.3, 0.3, 0.3),
					["Size"] = UDim2.new(1, 0, 1, 0),
					["LayoutOrder"] = 101,
					["Text"] = "",
					[v_u_10.Event.MouseButton1Down] = function()
						-- upvalues: (copy) p_u_27, (copy) v_u_28
						p_u_27:setState({
							["index"] = (p_u_27.state.index - 1 - 1) % #v_u_28 + 1
						})
					end
				}, {
					["AspectRatio"] = v_u_11("UIAspectRatioConstraint", {
						["AspectRatio"] = 6
					}),
					["Title"] = v_u_11("TextLabel", {
						["BackgroundTransparency"] = 1,
						["Size"] = UDim2.new(1, 0, 1, 0),
						["AnchorPoint"] = Vector2.new(0.5, 0.5),
						["Position"] = UDim2.new(0.5, 0, 0.65, 0),
						["TextColor3"] = Color3.new(1, 1, 1),
						["TextScaled"] = true,
						["Text"] = "Prev",
						["Font"] = Enum.Font.LuckiestGuy
					})
				})
			}, v33))
		}
		return v36("Frame", v37, v39)
	end
end
function v14.didMount(p_u_40)
	-- upvalues: (copy) v_u_3, (copy) v_u_2, (copy) v_u_8, (copy) v_u_5, (copy) v_u_7
	p_u_40.updateFlash(1)
	p_u_40._maid:GiveTask(v_u_3:GetInstanceAddedSignal(p_u_40.props.cameraTag):Connect(function()
		-- upvalues: (copy) p_u_40
		p_u_40:_updateCameraParts()
	end))
	p_u_40._maid:GiveTask(v_u_3:GetInstanceRemovedSignal(p_u_40.props.cameraTag):Connect(function()
		-- upvalues: (copy) p_u_40
		p_u_40:_updateCameraParts()
	end))
	if v_u_2.LocalPlayer then
		local v41 = v_u_8.ObjectLocal(v_u_2.LocalPlayer.PlayerGui, 9058379519, {
			["Volume"] = 0.6,
			["Looped"] = true
		})
		p_u_40._maid:GiveTask(v41)
	end
	local v_u_42 = p_u_40.props.expireDistance and v_u_5.getRootPart(v_u_2.LocalPlayer.Character)
	if v_u_42 then
		local v_u_43 = v_u_42.Position
		p_u_40._maid:GiveTask(v_u_7.every(1):Connect(function()
			-- upvalues: (ref) v_u_42, (ref) v_u_5, (ref) v_u_2, (copy) v_u_43, (copy) p_u_40
			v_u_42 = v_u_5.getRootPart(v_u_2.LocalPlayer.Character)
			if v_u_42 then
				if (v_u_42.Position - v_u_43).Magnitude > p_u_40.props.expireDistance then
					p_u_40.props.onClickClose()
					return
				end
			else
				p_u_40.props.onClickClose()
			end
		end))
	end
end
function v14.willUnmount(p44)
	p44._maid:DoCleaning()
end
return v14
