-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMcBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplDUNBUlRfVEFHX05BTUUMR0VNX1RBR19OQU1FDVdPT0RfVEFHX05BTUUXR0VNX0NPTExFQ1RfUkVNT1RFX05BTUUOU1BJS0VfVEFHX05BTUUYTVVTSUNfRU5BQkxFRF9WQUxVRV9OQU1FFk1VU0lDX1RSQUNLX1ZBTFVFX05BTUUbU1RBVFVTX0NIQU5HRURfQVRfQVRUUl9OQU1FFkJSQU5DSF9TV0lUQ0hfVEFHX05BTUUZQlJBTkNIX1NXSVRDSF9SRU1PVEVfTkFNRQ9DT09MRE9XTl9QRVJJT0QOVElNRU9VVF9QRVJJT0QIVG9tYkNhcnQHVG9tYkdlbQhUb21iV29vZA5Ub21iR2VtQ29sbGVjdAlUb21iU3Bpa2UJVG9tYk11c2ljDVRvbWJUcmFja0FvckIaVG9tYlJvYmJlcnlTdGF0dXNDaGFuZ2VkQXQQVG9tYkJyYW5jaFN3aXRjaAABBQAAAQIAN6MAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DAKEGAAAATQIDGAcAAACfAQICTQIBAAgAAADiAxUAbwQWADAEA0YJAAAAbwQXADAEAzwKAAAAbwQYADAEA24LAAAAbwQZADAEA+oMAAAAbwQaADAEAx0NAAAAbwQbADAEA5AOAAAAbwQcADAEA9cPAAAAbwQdADAEA4UQAAAAbwQeADAEA6ARAAAAbwQeADAEAzQSAAAAjASkATAEA3UTAAAAjATCATAEA08UAAAAnwICAIICAAAfAwEEAAAAQAMCAwMDBAQAAEBAAwUDBgMHAwgDCQMKAwsDDAMNAw4DDwMQAxEDEgMTBQwJCgsMDQ4PEBESExQDFAMVAxYDFwMYAxkDGgMbAxwAAQABGAABAAAAAAABAAAAAAAAAgAAAQAAAQAAAQAAAQAAAQAAAgAAAQAAAQAAAgAAAQAAAgAAAQAA8QABAAAAAABlj6B9AHW87FdLyums5ID0Lb5x5Q/2YoPc8UdRB9uzNuMrQWVc22ze

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Std.TableUtils).requireValidIndexAndFreeze({
	["CART_TAG_NAME"] = "TombCart",
	["GEM_TAG_NAME"] = "TombGem",
	["WOOD_TAG_NAME"] = "TombWood",
	["GEM_COLLECT_REMOTE_NAME"] = "TombGemCollect",
	["SPIKE_TAG_NAME"] = "TombSpike",
	["MUSIC_ENABLED_VALUE_NAME"] = "TombMusic",
	["MUSIC_TRACK_VALUE_NAME"] = "TombTrackAorB",
	["STATUS_CHANGED_AT_ATTR_NAME"] = "TombRobberyStatusChangedAt",
	["BRANCH_SWITCH_TAG_NAME"] = "TombBranchSwitch",
	["BRANCH_SWITCH_REMOTE_NAME"] = "TombBranchSwitch",
	["COOLDOWN_PERIOD"] = 420,
	["TIMEOUT_PERIOD"] = 450
})
