-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgM7DU9uQ2xpZW50RXZlbnQEZHJhdwdDb25uZWN0EURpc3BsYXlEYW1hZ2VEcmF3B2FuZFRoZW4EaW5pdApyZWFsRGFtYWdlAm9zBWNsb2NrD2ZpcnN0RGFtYWdlVGltZQVwcmludBhyZWFsIGRhbWFnZSwgdGltZSwgZHBzOiAKZGlzcGxheURQUwlhcnJvd3NHdWkHRGVzdHJveQxiaWxsYm9hcmRHdWkKaXNIZWFkc2hvdAppc1dhbGxiYW5nD2lzVmVoaWNsZURhbWFnZRJkaWRQb3BWZWhpY2xlVGlyZXMtVmVoaWNsZSBkYW1hZ2UgY2Fubm90IGJlIGhlYWRzaG90IG9yIHdhbGxiYW5nBmFzc2VydCtOb24tdmVoaWNsZSBkYW1hZ2UgY2Fubm90IHBvcCB2ZWhpY2xlIHRpcmVzBkFycm93cwhSZXNvdXJjZQpJdGVtU3lzdGVtBkRhbWFnZQVDbG9uZQpBcmNoaXZhYmxlBlBhcmVudA9EYW1hZ2VCaWxsYm9hcmQHcHJvbWlzZRB0b3RhbERhbWFnZURlYWx0BG1hdGgFZmxvb3IERW1pdAlUZXh0TGFiZWwIdG9zdHJpbmcEVGV4dCVWRUhJQ0xFX1RJUkVfUE9QX0RBTUFHRV9ESVNQTEFZX0NPTE9SClRleHRDb2xvcjMcVkVISUNMRV9EQU1BR0VfRElTUExBWV9DT0xPUgZDb2xvcjMDbmV3EFRleHRTdHJva2VDb2xvcjMdSEVBRFNIT1RfREFNQUdFX0RJU1BMQVlfQ09MT1IdV0FMTEJBTkdfREFNQUdFX0RJU1BMQVlfQ09MT1IcREVGQVVMVF9EQU1BR0VfRElTUExBWV9DT0xPUgZjYW5jZWwFZGVsYXkEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUDU3RkB1Byb21pc2UMd2FpdEZvckNoaWxkD0d1blN5c3RlbUNvbnN0cwRHYW1lAAYFAQEAAAAJTQEAjAAAAAD7BAAATQMEtAEAAAC8AQHHAgAAAJ8BAwGCAAEAAwMBAwIDAwAKAAEYAAAAAAAAAAABCwAAAAADAAMAAAAK+wAAAPsBAQBvAgAAnwADAsACAQASAgIAvAAAtQIAAACfAAMBggABAAMDBAYAAwUBAAkGARgAAAAAAAAAAAADCgAAAAAIAAIAAAAb+wAAAE0BAEwAAAAA+wIBAEMBAQIwAQBMAAAAAKQBAwAACBCAnwEBAvsDAABNAgNWBAAAACYAAQKkAQYAAABQQG8CBwD7BAAATQMETAAAAABSBAAA+wcAAE0GB0wAAAAA7AUGAJ8BBQGCAAEACAMHAwgDCQQACBCAAwoDCwQAAFBAAwwAMQ0BGAAAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAAAATIAAAAAAwADAAAAEfsBAABNAAHpAAAAALwAAFABAAAAnwACAfsBAABNAAEHAgAAALwAAFABAAAAnwACAfsAAQD7AQIAxgIAAGoCAAGCAAEAAwMOAw8DEABTAAEYAAAAAAAAAQAAAAAAAQAAAAFUAAAAABAEBAAAAIsCUgQDACsEAgD/BAAAAAAAAFIDBABNBAMDAAAAAE0FA5QBAAAATQYDWQIAAABNBwNoAwAAAA4GDgCpCQAARwQFAAAAAIBHBQIAAAAAAKkJAAGpCQEAgQEJBAQAAABvCgQApAgGAAAAUECfCAMBZQAKAEcHAgAAAAAAqQkAAakJAQCBAQkEBwAAAG8KBwCkCAYAAABQQJ8IAwH7CQAAhwgJAKkJAAArCDsA+w4BAE0NDmIJAAAATQwN8AoAAABNCwwPCwAAAE0KC9gIAAAAvAsKOgwAAACfCwICUgoLAKkLAAAwCwpuDQAAADABCiQOAAAA+w8BAE0OD2IJAAAATQ0O8AoAAABNDA0PCwAAAE0LDFYPAAAAvAwLOgwAAACfDAICUgsMAKkMAAAwDAtuDQAAADABCyQOAAAA4gwWAMYNAAAwDQwSEAAAADAKDOkRAAAAMAsMBxIAAACMDQAAMA0M9hMAAACkDRkAAGBwgZ8NAQIwDQxWFAAAAIwNAAAwDQxMFQAAAFIIDAD7DAAAaggMAKkJAQDZCgAAEgEI/xIAAgBNDAj2EwAAAJUOAhq7DA4CpA0dAABwsIGfDQICQwsMDTALCPYTAAAATQsI6REAAACMDQUAvAsLVh4AAACfCwMBTQwIBxIAAABNCwyaHwAAAE0NCPYTAAAAuz8NAqQMIQAAAABCnwwCAjAMC/UiAAAATQ0IBxIAAABNDA2aHwAAAE0LDJofAAAATQ4IBxIAAABNDQ6aHwAAAE0MDfUiAAAAMAwL9SIAAAAOBj4ADgcKAE0MCAcSAAAATQsMmh8AAAD7DQIATQwNAyMAAAAwDAtzJAAAAGUACgAOCQkATQwIBxIAAABNCwyaHwAAAPsNAgBNDA21JQAAADAMC3MkAAAATQwIBxIAAABNCwyaHwAAAKQMKAAAnGCCjA0AAIwOAACMDwAAnwwEAjAMC6QpAAAATQ0IBxIAAABNDA2aHwAAAE0LDJofAAAApAwoAACcYIKMDQAAjA4AAIwPAACfDAQCMAwLcyQAAABNDQgHEgAAAE0MDZofAAAATQsMmh8AAACkDCgAAJxggowNAACMDgAAjA8AAJ8MBAIwDAukKQAAAGUAHwAOBAoATQwIBxIAAABNCwyaHwAAAPsNAgBNDA0SKgAAADAMC3MkAAAAZQAUAA4FCgBNDAgHEgAAAE0LDJofAAAA+w0CAE0MDeMrAAAAMAwLcyQAAABlAAkATQwIBxIAAABNCwyaHwAAAPsNAgBNDA1YLAAAADAMC3MkAAAATQsIEhAAAAAOCwgATQsIEhAAAAC8CwuBLQAAAJ8LAgHGCwAAMAsIEhAAAAD7DAMATQsMvi4AAACMDAEAnwsCAtkNAQASAQj/EgIAABIAAAC8Cwu1LwAAAJ8LAwIwCwgSEAAAAMEIAACCAAEAMAMRAxIDEwMUAxUDFgQAAFBAAxcDGAMZAxoDGwMcAx0DHgMfAyADDgMQAyEDCgMHBQYQERITFBUDCAMJBABgcIECAAAAAAAA4D8DIgMjBABwsIEDJAMlAyYEAAAAQgMnAygDKQMqAysDLAQAnGCCAy0DLgMvAzADMQMyAwUCAgMOAgEYAAAAAAABAAEAAQABAAEBAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAACAAEBAQAAAAAAAAAAAQAAAAEAAAEAAgAAAAAAAAAAAQAAAAEAAAEAAgEAAAEAAQABAAABAAAAAAEAAAACAAECAAAGAAAAAAAAAAAAAQAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAACAQEAAAAAAAAAAAABAQAAAAAAAAAAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAACAQAAAAAAAAAAAAEBAAAAAAAAAAAAAgAAAAAAAAAABAAAAQAAAAABAAACAAAAAAAAAAAAAAAAAAUADwAAAAAHAAABAgAwowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAoQYAAABNAgNyBwAAAJ8BAgKkAgUAAABAQE0EAKEGAAAATQME8wgAAACfAgICpAMFAAAAQEBNBgC9CgAAAE0FBvALAAAATQQFSQkAAACfAwIC/wQAAAAAAAD/BQIAAAAAAMAGDAASAAIAEgAAABIABQAwBgUTDQAAAMAGDgASAAQAEgAAABIAAwASAAEAMAYFtA8AAACCBQIAEAMzBAAAAEADNAM1AzYEAABAQAM3AzgDOQM6AzsDGgYBAwYGBAMCAgEEAQABGAABAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAIAAQABAAAAAAAFAAAAAAAASwEAAAAABekOj8rPn3/n28rlXiBKVLgChymG7h4ovV8OP99PxUIj8mnReCmeUW8=

-- Decompiled by Krnl

local v_u_1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v_u_1.Std.Promise)
local v_u_3 = require(v_u_1.Std.waitForChild)
local v_u_4 = require(v_u_1.Game.ItemSystem.GunSystemConsts)
local v_u_5 = {}
local v_u_26 = {
	["init"] = function()
		-- upvalues: (copy) v_u_3, (copy) v_u_1, (copy) v_u_26
		v_u_3(v_u_1, "DisplayDamageDraw"):andThen(function(p6)
			-- upvalues: (ref) v_u_26
			p6.OnClientEvent:Connect(v_u_26.draw)
		end)
	end,
	["draw"] = function(p_u_7, p8, p9, p10)
		-- upvalues: (copy) v_u_5, (copy) v_u_1, (copy) v_u_4, (copy) v_u_2
		local v11 = p10 or {}
		local v12 = v11.isHeadshot
		local v13 = v11.isWallbang
		local v14 = v11.isVehicleDamage
		local v15 = v11.didPopVehicleTires
		if v14 then
			local v16
			if v12 == nil then
				v16 = v13 == nil
			else
				v16 = false
			end
			assert(v16, "Vehicle damage cannot be headshot or wallbang")
		else
			local v17 = v15 == nil
			assert(v17, "Non-vehicle damage cannot pop vehicle tires")
		end
		local v_u_18 = v_u_5[p_u_7]
		local v19
		if v_u_18 then
			v19 = false
		else
			local v20 = v_u_1.Resource.ItemSystem.Damage.Arrows:Clone()
			v20.Archivable = false
			v20.Parent = p8
			local v21 = v_u_1.Resource.ItemSystem.Damage.DamageBillboard:Clone()
			v21.Archivable = false
			v21.Parent = p8
			v_u_18 = {
				["promise"] = nil,
				["arrowsGui"] = v20,
				["billboardGui"] = v21,
				["totalDamageDealt"] = 0,
				["firstDamageTime"] = os.clock(),
				["realDamage"] = 0
			}
			v_u_5[p_u_7] = v_u_18
			v19 = true
		end
		local v22 = v_u_18.totalDamageDealt
		local v23 = p9 + 0.5
		v_u_18.totalDamageDealt = v22 + math.floor(v23)
		v_u_18.arrowsGui:Emit(5)
		local v24 = v_u_18.billboardGui.TextLabel
		local v25 = v_u_18.totalDamageDealt
		v24.Text = tostring(v25)
		v_u_18.billboardGui.TextLabel.TextLabel.Text = v_u_18.billboardGui.TextLabel.Text
		if v14 then
			if v15 then
				v_u_18.billboardGui.TextLabel.TextColor3 = v_u_4.VEHICLE_TIRE_POP_DAMAGE_DISPLAY_COLOR
			elseif v19 then
				v_u_18.billboardGui.TextLabel.TextColor3 = v_u_4.VEHICLE_DAMAGE_DISPLAY_COLOR
			end
			v_u_18.billboardGui.TextLabel.TextStrokeColor3 = Color3.new(0, 0, 0)
			v_u_18.billboardGui.TextLabel.TextLabel.TextColor3 = Color3.new(0, 0, 0)
			v_u_18.billboardGui.TextLabel.TextLabel.TextStrokeColor3 = Color3.new(0, 0, 0)
		elseif v12 then
			v_u_18.billboardGui.TextLabel.TextColor3 = v_u_4.HEADSHOT_DAMAGE_DISPLAY_COLOR
		elseif v13 then
			v_u_18.billboardGui.TextLabel.TextColor3 = v_u_4.WALLBANG_DAMAGE_DISPLAY_COLOR
		else
			v_u_18.billboardGui.TextLabel.TextColor3 = v_u_4.DEFAULT_DAMAGE_DISPLAY_COLOR
		end
		if v_u_18.promise then
			v_u_18.promise:cancel()
			v_u_18.promise = nil
		end
		v_u_18.promise = v_u_2.delay(1):andThen(function()
			-- upvalues: (ref) v_u_18, (ref) v_u_5, (copy) p_u_7
			v_u_18.arrowsGui:Destroy()
			v_u_18.billboardGui:Destroy()
			v_u_5[p_u_7] = nil
		end)
	end
}
return v_u_26
