-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNHB1ZlY3RvcjMDbmV3BFVuaXQhUmF5SWdub3JlTm9uQ29sbGlkZVdpdGhJZ25vcmVMaXN0CU1hZ25pdHVkZQNEb3QSQ2FsY3VsYXRlQ29uc3RhbnRzDHNldG1ldGF0YWJsZQpSb2NrZXRQYXJ0BkNGcmFtZQZBbmdsZXMIUm90YXRpb24IUmVzb3VyY2UFQ2xvbmUKQ2FuQ29sbGlkZQhBbmNob3JlZAl3b3Jrc3BhY2UGUGFyZW50BFBhcnQGT3JpZ2luDk9yaWdpblZlbG9jaXR5BlRhcmdldApEcm9wUGVyaW9kCklnbm9yZUxpc3QERmlyZQdFbmFibGVkC09iamVjdExvY2FsDFRpbWVQb3NpdGlvbgZWb2x1bWUFUGl0Y2gLRW1pdHRlclNpemUGSWduaXRlCkdldE5vd1N5bmMHRXhwbG9kZQRtYXRoA21pbgRMZXJwCUhlYXJ0YmVhdApMb29rVmVjdG9yAXAHQ29ubmVjdAdSdW50aW1lB0FuaW1hdGUHRGVzdHJveQVkZWxheQxUcmFuc3BhcmVuY3kISW5zdGFuY2UJRXhwbG9zaW9uBEVudW0NRXhwbG9zaW9uVHlwZQlOb0NyYXRlcnMZRGVzdHJveUpvaW50UmFkaXVzUGVyY2VudAhQb3NpdGlvbgVTb3VuZBVyYnhhc3NldGlkOi8vNTUyMjQ3NjYHU291bmRJZARQbGF5CkRpc2Nvbm5lY3QNTGF1bmNoTWlzc2lsZQdyZXF1aXJlA1N0ZAVBdWRpbwRUaW1lBk1vZHVsZQRJbml0BGdhbWUKUnVuU2VydmljZQpHZXRTZXJ2aWNlEVJlcGxpY2F0ZWRTdG9yYWdlB1JheUNhc3QHX19pbmRleAALEgUBAAAHAAABCAcRATCQAwMAUgUEACsFAgD/BQAAAAAAAFIEBQAJBwEDQwYAB4wIAABvCwEACQoLAwkJCgOMCgAATDYAAqQHBAAADCCAnwcEAkMFBgcmBwIFTQYHBwUAAAD7CAAATQcIyAYAAABSCAUAUgkGAIwK5wNSCwQAnwcFAyYKCAVNCQqqBwAAAFIMBgC8CgErCAAAAJ8KAwIJDwoKjBG4CwkQEQlDDg8QBA0OCiYMDQo+CwwJUgwFAFINAwBSDgsAUg8IAIIMBQALAgAAAAAAANA/AmdmZmZmhljAAwEDAgQADCCAAwMDBAMFAwYCAAAAAABwl0ACAAAAAAAA4D8AEQcBGAABAAAAAAEAAAAAAAAAAAAAAAEAAAEAAAAAAAAAAQAAAQAAAAIAAAAAAAABAAAAABIAAAAACwYCAAAAP/8HBAAAAAAA+wgAAJ49BwMIAAAApAYBAAAAAECfBgMCKwMBAG8DAgCkBwUAABAwgIwIAACMCQAAjAoAAJ8HBAIwBwY4BgAAAPADCQACAACApAcFAAAQMICMCAAAbwkHAIwKAACfBwQCMAcGOAYAAAD7CQEATQgJYggAAACHBwgDvAcHOgkAAACfBwICqQgAADAIB9MKAAAAqQgBADAIB0ULAAAApAgNAAAAwEAwCAckDgAAAE0JBjgGAAAACQgACTAIB4UDAAAAMAcGRA8AAAAwAAZDEAAAADABBn4RAAAAMAIGLBIAAAAwBAYFEwAAADAFBsoUAAAAggYCABUDCAQAAABAAwkDCgMLBAAQMIADDAIYLURU+yEJQAMNAw4DDwMQAxEEAADAQAMSAxMDFAMVAxYDFwMYACECARgAAAAAAAAAAAIBAgAAAAAAAAABAAEAAAAAAAAAAgAAAAAAAAEAAAEAAAEAAAABAAAAAAEAAgABAAEAAQABAAIiAAAAAAUAAgAAACr7AgAATQECRAAAAABNAAHdAQAAAKkBAQAwAQDwAgAAAPsBAQBNAAHRAwAAAPsCAABNAQJEAAAAAG8CBADiAwcAbwQIADAEA8YFAAAAbwQIADAEA0sGAAAAnwAEAfsBAQBNAAHRAwAAAPsCAABNAQJEAAAAAG8CCQDiAwwAbwQNADAEA0sGAAAAbwQNADAEAwAKAAAAjAQZADAEA4MLAAAAnwAEAYIAAQAOAxMDGQMaAxsCAAAAVXSp1EEDHAMdBQIFBgIAAAAAAADgPwIAALiDit8AQgMeAx8FAwYKCwIzMzMzMzPjPwBHIAEYAAAAAAAAAAACAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAABSAAAAAANAA0AAAcAAAEIBzwBa/sBAABNAAEyAAAAAJ8AAQL7AgEAJgEAAvsDAgAmAgAD3gACACYDAQL7BAMAYAMGAAQAAAD7AwMAfQMDAAEAAAD7AwQAnwMBASYDAQL7BQMA+wYFAEMEBQZgAwoABAAAAPsEAwD7BQUAQwMEBX0DBQABAAAA+wMGALwDA+QBAAAAnwMCAfsDAwBgAR0AAwAAAG8FAgAJBAUBCQMEAfsFBgBNBAVEAwAAAPsJBgBNCAlDBAAAAPsKBgBNCQo4BQAAAAkHCAn7CQcACQgJAUMGBwiMCAAAjAoAADQ2CAQDCgAAUgkDAKQHCAAAHGCAnwcEAkMFBgcwBQSFCQAAAIIAAQD7BAMA+wUFAEMDBAVgASYAAwAAAPsDAwAmAQEDjAXuAgkEBQEJAwQB+wQIAPsGCQBbCAEKgRMIBAsAAABvCQsApAcOAAA0wICfBwMCvAQEXw8AAACfBAQC+wYGAE0FBkQDAAAApAkQAAAckID7CgoAUgsEAJ8JAwL7CgsAQwgJCvsLDAD7DAkACQoLDAkJCgFDBwgJ+wkJAAkICQNDBgcIMAYFhQkAAACCAAEAEQMhAyICZ2ZmZmaGWMADEwMUAwwDAQMCBAAcYIADCgIAAAAAAAAkQAIAAAAAAADwPwMjAyQEADTAgAMlBAAckIAATSYBGAAAAAABAAEAAQEAAAAAAAABAAIAAAAAAAAAAAAAAQAAAAIAAAEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAEAAgAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACTgAAAAAQAgUAAABDUgIBACsCBAD7AwAATQIDMgAAAACfAgECUgECAE0CAH4BAAAATQUAQwIAAABNBgA4AwAAAAkEBQZNAwRoBAAAAPsEAQBNBgBDAgAAAE0FBpEFAAAAUgYCAE0HACwGAAAATQgABQcAAABNCQDKCAAAAJ8EBgVNCgAsBgAAACYJCgRNCAkHCQAAAFILCAC8CQIrCgAAAJ8JAwJ4CgEL2QsAABIAAAASAgIA2QwBABICAAASAQH/EgEK/xIABQASAAsAEgAGABIAAAASAAIAEgADABIACAASAgMAEgAEABIACQD7DgQATQ0O/QwAAABSDwwAvA0Nxw0AAACfDQMCMA0AeA4AAADBAQAAggABAA8DIQMVAxQDDAMnAygDFgMXAxgDAwMGAhEREREREaE/AyYDKQMqAgIDOisBGAAAAAAAAAAEAAEAAAAAAAACAAAAAAAAAAAAAAAAAQAAAAABAAAAAgEAAAYAAAAAAAAAAAAAAAAAFgAAAAAAAAAAAQA7AAAAAAIAAQAAAAX7AAAAvAAAUAAAAACfAAIBggABAAEDLABmAAEYAAAAAAFnAAAAAAUBAAAAAD6kAQEAAAAAQIwCAgDZAwAAEgAAAJ8BAwFNAQBEAgAAAIwCAQAwAgHZAwAAAE0BAEQCAAAAqQIAADACAdMEAAAATQIARAIAAABNAQLdBQAAAKkCAAAwAgHwBgAAAKQBCQAAIHCAbwIKAJ8BAgKkAg4ADTCwwDACAaoMAAAAjAIAADACAUMPAAAATQMARAIAAABNAgM7EAAAADACATsQAAAApAISAAAAEEEwAgEkEwAAAKQCCQAAIHCAbwMUAJ8CAgJvAxUAMAMCfBYAAABNAwBEAgAAADADAiQTAAAAbwMXADADAksYAAAAvAMC7hkAAACfAwIBggABABoDLQQAAABAAxMDLgMPAxkDGgMvAwIEACBwgAMwAzEDMgMzBA0wsMADNAM1AxEEAAAQQQMSAzYDNwM4ApqZmZmZmek/Ax0DOQEFZSIBGAAAAAAAAAQAAAAAAQAAAAABAAAAAAAAAgAAAAEAAAABAAABAAAAAAABAAAAAgAAAAEAAAEAAAABAAABAAABZgAAAAADAQAAAAARTQEARAAAAAC8AQFQAQAAAJ8BAgHGAQAAMAEARAAAAABNAQB4AgAAALwBARoDAAAAnwECAcYBAAAwAQB4AgAAAIIAAQAEAxMDLAMqAzoAeiwBGAAAAAAAAQAAAQAAAAABAAABewAAAAAOBwEAAAAP+wgAAE0HCO8AAAAAUggAAFIJAQBSCgIAUgsEAFIMBQBSDQYAnwcHAlIKAwC8CAfCAQAAAJ8IAwGCAAEAAgMCAysAhAE7ARgAAAAAAAAAAAAAAQAAAAGFAAAAAAQABAAAABhMNgACpAACAAAEAICfAAEC3gAAAKQABAAAADBA+wMCAE0CA6EFAAAATQEC0gYAAACfAAIC3gABAKQABAAAADBA+wMCAE0CA0AIAAAATQECSgcAAACfAAIC3gADAIIAAQAJAwEDAgQABACAAzwEAAAwQAM9Az4DPwNAAIgBQQEYAAAAAAABAAAAAAAAAAABAAAAAAAAAAABiQAAAAALAAABAgBAowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBAQAAAABAbwMEALwBARYDAAAAnwEDAsYCAACkAwYAAABQQE0FAUAIAAAATQQFMgcAAACfAwICxgQAAMAFCQASAAMAxgYAAP8HBAAAAAAAMAcHbgoAAADACAsAEgAHABIAAQAwCAfvDAAAANkIAgASAQT/EgAFABIBAv8SAQb/EgAAADAIB8INAAAAwAgOADAIB+QPAAAAwAgQADAIB1ARAAAAwAgSABIABwDZCQYAEgEG/xIBAv8SAAEAEgEE/+IKFgAwBQotEwAAADAICjIUAAAAMAkKcxUAAADBAgAAggoCABcDQgQAAABAA0MDRANFAzwEAABQQANGA0AGAANHBgEDAgMrBgYDIgYHAywGCAMHAzsDQQUDExQVBwABBAYHCAkBAAEYAAMAAAAAAAEAAAAAAAEBAAAAAAAAAQkADQEAAQABAAAAABkAAAAAAAAAKwAAFQAACgAEAAAAAAUBAAEAAQAAAAEAAAAACi6gDu7vzdvOHGRkehNqH+281pZKuqttuptIlryfjX34Y9XZIkSs0Uw=

-- Decompiled by Krnl

local v_u_1 = game:GetService("RunService")
local v_u_2 = game:GetService("ReplicatedStorage")
local v_u_3 = nil
local v_u_4 = require(v_u_2.Module.RayCast)
local v_u_5 = nil
local function v_u_19(p6, p7, p8, p9, p10)
	-- upvalues: (copy) v_u_4
	local v11 = p9 or 0.25
	local v12 = p6 + p7 * v11
	local v13 = -98.10000000000001 * v11 * v11
	local v14 = v12 + Vector3.new(0, v13, 0)
	local v15 = (p8 - v14).Unit
	local _, v16 = v_u_4.RayIgnoreNonCollideWithIgnoreList(v14, v15, 999, p10 or {})
	local v17 = (v16 - v14).Magnitude
	local v18 = p7:Dot(v15)
	return v14, v11, ((v18 * v18 + 3000 * v17) ^ 0.5 - v18) / 1500, v16
end
local v_u_20 = nil
local v_u_21 = {}
v_u_21.__index = v_u_21
function v_u_21.new(p22, p23, p24, p25, p26, p27)
	-- upvalues: (copy) v_u_21, (copy) v_u_2
	local v28 = v_u_21
	local v29 = setmetatable({}, v28)
	local v30 = p25 or "RocketPart"
	v29.Rotation = CFrame.Angles(0, 0, 0)
	if v30 == "RocketPart" then
		v29.Rotation = CFrame.Angles(0, 3.141592653589793, 0)
	end
	local v31 = v_u_2.Resource[v30]:Clone()
	v31.CanCollide = false
	v31.Anchored = true
	v31.Parent = workspace
	v31.CFrame = p22 * v29.Rotation
	v29.Part = v31
	v29.Origin = p22
	v29.OriginVelocity = p23
	v29.Target = p24
	v29.DropPeriod = p26
	v29.IgnoreList = p27
	return v29
end
function v_u_21.Animate(p_u_32, p33)
	-- upvalues: (ref) v_u_5, (copy) v_u_19, (ref) v_u_3, (ref) v_u_20, (copy) v_u_1
	local v_u_34 = p33 or v_u_5.GetNowSync()
	local v_u_35 = p_u_32.OriginVelocity
	local v_u_36 = (p_u_32.Origin * p_u_32.Rotation).LookVector
	local v_u_37, v_u_38, v_u_39, _ = v_u_19(p_u_32.Origin.p, v_u_35, p_u_32.Target, p_u_32.DropPeriod, p_u_32.IgnoreList)
	local v_u_40 = (p_u_32.Target - v_u_37).Unit
	local v_u_41 = v_u_35:Dot(v_u_40)
	local v_u_42 = v_u_34 - 0.03333333333333333
	local function v_u_43()
		-- upvalues: (copy) p_u_32, (ref) v_u_3
		p_u_32.Part.Fire.Enabled = true
		v_u_3.ObjectLocal(p_u_32.Part, 1386598740, {
			["TimePosition"] = 0.5,
			["Volume"] = 0.5
		})
		v_u_3.ObjectLocal(p_u_32.Part, 9058734199, {
			["Volume"] = 0.6,
			["Pitch"] = 0.6,
			["EmitterSize"] = 25
		})
	end
	local function v54()
		-- upvalues: (ref) v_u_5, (ref) v_u_34, (ref) v_u_42, (copy) v_u_38, (copy) v_u_43, (copy) v_u_39, (copy) p_u_32, (copy) v_u_35, (copy) v_u_36, (copy) v_u_40, (ref) v_u_20, (copy) v_u_37, (copy) v_u_41
		local v44 = v_u_5.GetNowSync()
		local v45 = v44 - v_u_34
		local v46 = v44 - v_u_42
		v_u_42 = v44
		if v45 - v46 < v_u_38 and v_u_38 <= v45 then
			v_u_43()
		end
		if v45 - v46 < v_u_38 + v_u_39 and v_u_38 + v_u_39 <= v45 then
			p_u_32:Explode()
		end
		if v45 < v_u_38 then
			local v47 = -98.10000000000001 * v45 * v45
			p_u_32.Part.CFrame = p_u_32.Origin * p_u_32.Rotation + v_u_35 * v45 + Vector3.new(0, v47, 0)
		elseif v45 < v_u_38 + v_u_39 then
			local v48 = v45 - v_u_38
			local v49 = 750 * v48 * v48
			local v50 = v_u_36
			local v51 = v_u_40
			local v52 = v48 * 10
			local v53 = v50:Lerp(v51, (math.min(v52, 1)))
			p_u_32.Part.CFrame = CFrame.new(v_u_20, v53) + v_u_37 + v_u_41 * v_u_40 * v48 + v_u_40 * v49
		end
	end
	p_u_32.Runtime = v_u_1.Heartbeat:Connect(v54)
end
function v_u_21.Explode(p_u_55)
	delay(2, function()
		-- upvalues: (copy) p_u_55
		p_u_55:Destroy()
	end)
	p_u_55.Part.Transparency = 1
	p_u_55.Part.CanCollide = false
	p_u_55.Part.Fire.Enabled = false
	local v56 = Instance.new("Explosion")
	v56.ExplosionType = Enum.ExplosionType.NoCraters
	v56.DestroyJointRadiusPercent = 0
	v56.Position = p_u_55.Part.Position
	v56.Parent = workspace
	local v57 = Instance.new("Sound")
	v57.SoundId = "rbxassetid://55224766"
	v57.Parent = p_u_55.Part
	v57.Volume = 0.8
	v57:Play()
end
function v_u_21.Destroy(p58)
	p58.Part:Destroy()
	p58.Part = nil
	p58.Runtime:Disconnect()
	p58.Runtime = nil
end
return {
	["CalculateConstants"] = v_u_19,
	["LaunchMissile"] = function(p59, p60, p61, p62, p63, p64, p65)
		-- upvalues: (copy) v_u_21
		v_u_21.new(p59, p60, p61, p63, p64, p65):Animate(p62)
	end,
	["Init"] = function()
		-- upvalues: (ref) v_u_20, (ref) v_u_3, (copy) v_u_2, (ref) v_u_5
		v_u_20 = Vector3.new()
		v_u_3 = require(v_u_2.Std.Audio)
		v_u_5 = require(v_u_2.Module.Time)
	end
}
