-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgN2CW1hZ25pdHVkZQR1bml0A1JheQNuZXcJd29ya3NwYWNlCkNhbkNvbGxpZGUFdGFibGUGaW5zZXJ0BWZwb3IyCElzRmx5aW5nEEh1bWFub2lkUm9vdFBhcnQGQ0ZyYW1lBkFuZ2xlcwtSb3RWZWxvY2l0eQF5BG1hdGgFY2xhbXAKTG9va1ZlY3RvcgNEb3QDYWJzAVgKbG9va1ZlY3RvcgFaB1ZlY3RvcjMIVmVsb2NpdHkDbWF4BEd5cm8IUG9zaXRpb24GUGFyZW50CFZlaGljbGVzDklzRGVzY2VuZGFudE9mD1VwZGF0ZVBhcmFjaHV0ZQVwcmludBVBbHJlYWR5IGhhcyBwYXJhY2h1dGUJQ2hhcmFjdGVyCEh1bWFub2lkDkZpbmRGaXJzdENoaWxkC1ByaW1hcnlQYXJ0DVBsYXRmb3JtU3RhbmQDU2l0BEVudW0RSHVtYW5vaWRTdGF0ZVR5cGUQUGxhdGZvcm1TdGFuZGluZwtDaGFuZ2VTdGF0ZQlQYXJhY2h1dGUEVHlwZQhJbnN0YW5jZQhCb2R5R3lybwlNYXhUb3JxdWUMQm9keVZlbG9jaXR5CE1heEZvcmNlC09iamVjdExvY2FsCFJvb3RQYXJ0CUhlYXJ0YmVhdAdDb25uZWN0BExvb3AMUmF3UGFyYWNodXRlB0Rlc3Ryb3kKRGlzY29ubmVjdARGaXJlEFJhd1BhcmFjaHV0ZVN0b3AIcjRiYjV6czMKRmlyZVNlcnZlcgFnBnhieGd1eQNzdWIHcmV2ZXJzZQAFNjhlZDMNUGFyYWNodXRlU3RvcAR0aWNrB1N0YXJ0ZWQMVXBkYXRlR2xpZGVyEkFscmVhZHkgaGFzIGdsaWRlcgZHbGlkZXIJUmF3R2xpZGVyCUdldHRpbmdVcA1SYXdHbGlkZXJTdG9wAW8HZ2tkY3EwagZidHVtNG8JczM4amlnOTVzBmFvZHVtbQFiAXAIYWZiNXlxMzUGYWNzZmQzBGI2NmsKR2xpZGVyU3RvcA1nanVkZTg2Ynh1aGQ1ATMIZ3hiNjhlZDMIdGJzYjVvcG4IdXo2NnhibnUBawhvZGt1aXVkYghwNWJzYjY2awVFdmVudAJlbQdyZXF1aXJlBnNjcmlwdA5EZWZhdWx0QWN0aW9ucw1vbkp1bXBQcmVzc2VkBEluaXQEZ2FtZQpSdW5TZXJ2aWNlCkdldFNlcnZpY2UQVXNlcklucHV0U2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQNTdGQFQXVkaW8GU2lnbmFsB1BsYXllcnMLTG9jYWxQbGF5ZXINQ3VycmVudENhbWVyYRtGaW5kUGFydE9uUmF5V2l0aElnbm9yZUxpc3QST25QYXJhY2h1dGVTdG9wcGVkD09uR2xpZGVyU3RvcHBlZAATEgICAQAAQqMCAABNAgHKAAAAAE0BAScBAAAAUgMAAIwEAAD/BQAAAAAAAN0GAADFBQYAAQAAAMYGAAD7BwAA+wgAAIwJAADGCgAAlQkJAqQLBQAAEDCAUgwDACYOAgQJDQEOnwsDAvsMAQCkDQcAAABgQFIOCwBSDwUAqRAAAKkRAQCfDAYEUgYMAFIHDQBSCA4AUgwGAA4MAgBNDAbTCAAAAFIKDAArCgcAnjQFBQYAAABSDQUAUg4GAKQMCwAAKJCAnwwDASYMAAdNBAzKAAAAAFIDBwArCggAJgwCBG8NDADUDAUADQAAAIwMBAC3DAIACQAAAEgA1P8rBgMACQsBAkMHAAv7CAAAggYEAA0DAQMCAgAAAAAAAPA/AwMDBAQAEDCAAwUEAABgQAMGAwcDCAQAKJCAAvyp8dJNYlA/ABAJARgAAQABAAEBAQAAAAABAAABAQIBAAAAAAABAAAAAAAAAAAAAAEAAAAAAQEAAAAAAAACAAABAQAAAAAAAAAAAQEAAAIQAAAAAAIAAQAAAAb7AQAARwECAAAAAICpAAABqQABAIIAAgAAADMKARgAAAAAAAA0AAAAAA0ABAAAEwAABAgIOQEICUIBCAdDAQgIQwFu+wEAAE0AAWYAAAAA+wIBAE0BAoUBAAAApAIDAAAIEIBvAwQAjAQAAIwFAACfAgQCCQEBAk0EAKoFAAAATQMEmAYAAACMBPz/jAUEAEwuAAKkAgkAACBwgJ8CBAJNBAFoCgAAAG8GCwC8BAQrDAAAAJ8EAwK7AgQCpAMOAAA0cICfAwICTQYBaAoAAABNBQZ5DwAAAIwGAABNCAFIEAAAAE0HCHsRAAAATDYAAqQEFAAATCCBnwQEAvsGAABNBQaFFQAAAFsIBBZvChcAnhIKBAMAAABSCwMApAkZAABgcICfCQMCCQcICYwKAACMDAAANDYKBAMMAABSCwMApAkUAABMIIGfCQQCWwgJGkMGBwgwBgWFFQAAAPsGAABNBQbYGwAAAKQHHAAATBCATDYAAqQIFAAATCCBnwgBAk0JAUgQAAAAnwcDAqQIHAAATBCAjAkAAIwKAABbCwIdnwgEAgkGBwgwBgWFAQAAAPsFAgBNBgA7HgAAAG8HHwBNCAAkIAAAAJ8FBAMOBQoApAoiAAAAEEJNCQqiIwAAALwHBa0kAAAAnwcDAisHAgD7BwMAnwcBAYIAAQAlAwsDDAMNBAAIEIACmpmZmZmZyT8DDgMPAxADEQQAIHCAAxIHAAAAAAAAgD8AAAAAAAAAAAMTAxQEADRwgAMVAxYDFwMYAwQEAEwggQMZAgAAAAAAAE5AAgAAAAAAAOA/AxoEAGBwgAIAAAAAAABEwAMbBABMEIACAAAAAAAAwD8DHAcAAAAAAACAwAAAAAAAAAAAAx0DBQQAABBCAx4DHwA2IAEYAAAAAwAAAQAAAAAAAAEAAAAAAAAAAAABAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAABAAAAAAAAAAABAAI3AAAAAAoABgAAAHP7AAAADgAGAKQAAQAAAABAbwECAJ8AAgGpAAAAggACAPsBAQBNAAFpAwAAACsAAgCpAQAAggECAG8DBAC8AQADBQAAAJ8BAwIrAQIAqQIAAIICAgBNAgCbBgAAACsCAgCpAwAAggMCAE0DAfsHAAAADgMCAKkDAACCAwIATQMB9AgAAAAOAwIAqQMAAIIDAgCpAwEAMAMB+wcAAACkBQwACyiQwLwDASENAAAAnwMDAf8DAAAAAAAA3gMAAPsDAABvBA4AMAQDEQ8AAACkAxIAAEQAgW8EEwCfAwICbwQUADAEA6MVAAAA+wYCAE0FBoUWAAAApAYYAABcYIFvBxkAjAgAAIwJAACfBgQCCQQFBjAEA4UWAAAAMAIDJBoAAACkBBIAAEQAgW8FGwCfBAICbwUcADAFBDMdAAAAbwUeADAFBIUfAAAAMAIEJBoAAAD7BQAAMAMF2CAAAAD7BQAAMAQFhR8AAAD7BQAAMAIFZiEAAAD7BQAAMAEFAQQAAAD7BgMATQUG0SIAAABNBgFGIwAAAG8HJACfBQMB+wUAAPsHBABNBgf9JQAAAPsIBQC8BgbHJgAAAJ8GAwIwBgU5JwAAAKkFAQCCBQIAKAMhBAAAAEADIgMjAyQDJQMmAycDKAMpAyoDKwQLKJDAAywDLQMuAy8DBAQARACBAzAHAEAcRgBAHEYAQBxGAAAAAAMxAwwDDQQAXGCBApqZmZmZmck/Ax0DMgcAJHRJACR0SQAkdEkAAAAAAzMHAAAAAAAAgL8AAAAAAAAAAAMZAxsDCwM0AzUCAABwZ2+y8EEDNgM3AzgARzkBGAAAAQAAAAEAAgAAAQEAAgAAAAEBAAIAAQEAAgAAAQACAAABAAMAAAEAAAAAAgAAAQAAAAIAAAABAAABAAAAAAAAAAAAAAABAAIAAAABAAABAAABAAIAAAEAAAEAAAEAAAIAAAAAAAACAAAAAAAAAAAAAQBIAAAAAAIAAgAAACv7AAAAKwACAKkAAACCAAIA+wEAAE0AAREAAAAA8AADAAEAAACpAAAAggACAPsBAABNAAHYAgAAALwAAFADAAAAnwACAfsBAABNAAGFBAAAALwAAFADAAAAnwACAfsBAABNAAE5BQAAALwAABoGAAAAnwACAfsBAABNAAEBBwAAAKkBAAAwAQD7CAAAAMYAAADeAAAA+wABALwAAN0JAAAAnwACAakAAQCCAAIACgMuAy0DGwM6AxkDOAM7AyQDJwM8AHk9ARgAAAEAAgAAAAABAAIAAAAAAAEAAAAAAAEAAAAAAAIAAAAAAAEAAQAAAAEAegAAAAAEAAIAAAAL+wAAAJ8AAQIrAAIAqQEAAIIBAgD7AQEAbwMAALwBAWsBAAAAnwEDAYIAAQACAz4DPwCJAS0BGAAAAQEAAgAAAAABigAAAAAMAAMAAAcAAAEDCDICRvsBAAArAQIAqQAAAGUAJgD7AgAATQECEQAAAADwAQMAAQAAAKkAAABlAB8A+wIAAE0BAtgCAAAAvAEBUAMAAACfAQIB+wIAAE0BAoUEAAAAvAEBUAMAAACfAQIB+wIAAE0BAjkFAAAAvAEBGgYAAACfAQIB+wIAAE0BAgEHAAAAqQIAADACAfsIAAAAxgEAAN4BAAD7AQEAvAEB3QkAAACfAQIBqQABACsAAgCpAQAAggECAPsBAgBvBAoAbwgLAIwKAgCMCwMAvAgI8AwAAACfCAQCvAgImw0AAACfCAICvAgImw0AAACfCAICvAgImw0AAACfCAICUgUIAG8GDgBvBw8AcwMEB7wBAWsQAAAAnwEDAYIAAQARAy4DLQMbAzoDGQM4AzsDJAMnAzwDQANBA0IDQwNEA0UDPwCQAUYBGAAAAQACAAAAAAEAAgAAAAAAAQAAAAAAAQAAAAAAAgAAAAAAAQABAAAAAQsBAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF6AAAAAAwABAAAEwAABAgHNQEICD4BCAY/AQgHPwF1+wEAAE0AAWYAAAAA+wIBAE0BAoUBAAAApAIDAAAIEIBvAwQAjAQAAIwFAACfAgQCCQEBAk0EAUgFAAAAbwYGALwEBCsHAAAAnwQDAowF//9vBggATC4AAqQDCwAAKJCAnwMEArsCAwKkAg0AADCQgJ8CAgJNBQFIBQAAAE0EBXkOAAAAjAUAAE0HAUgFAAAATQYHew8AAABMNgACpAMSAABEAIGfAwQC+wUAAE0EBYUTAAAAWwcDFG8JFQCeEgkEAgAAAFIKAgCkCBcAAFiQgJ8IAwIJBgcIjAkAAIwLAAA0NgkEAgsAAFIKAgCkCBIAAEQAgZ8IBAJbBwgYQwUGBzAFBIUTAAAA+wUAAE0EBdgZAAAApAYaAABEEIBMNgACpAcSAABEAIGfBwECTQkBSAUAAABbCAkbnwYDAqQHAwAACBCAbwgcAIwJAACMCgAAnwcEAgkFBgcwBQSFAQAAAPsEAgBNBQA7HQAAAG8GHgBNBwAkHwAAAJ8EBAMOBBQApAkhAAAAAEJNCAmiIgAAALwGBK0jAAAAnwYDAisGDACkByUAAABAQp8HAQL7CQAATQgJsyYAAAAmBgcIjAcBAGAHAwAGAAAA+wYDAJ8GAQGCAAEAJwMLAwwDDQQACBCAApqZmZmZmck/AxYHAAAAAAAAgD8AAAAAAAAAAAMTArgehetRuK6/AxADEQQAKJCAAxQEADCQgAMVAxcDGAMEBABEAIEDGQIAAAAAAABOQALNzMzMzMzsPwMaBABYkIACAAAAAACAVsADGwQARBCAAgAAAAAAAPA/AlBp6zHHKP6/AxwHAAAAAAAAQMAAAAAAAAAAAAMdAwUEAAAAQgMeAx8DRwQAAEBCA0gAlwFJARgAAAADAAABAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAABAAKYAAAAAAoABQAAAHL7AAAADgAGAKQAAQAAAABAbwECAJ8AAgGpAAAAggACAPsBAQBNAAFpAwAAACsAAgCpAQAAggECAG8DBAC8AQADBQAAAJ8BAwIrAQIAqQIAAIICAgBNAgCbBgAAACsCAgCpAwAAggMCAE0DAfsHAAAADgMCAKkDAACCAwIATQMB9AgAAAAOAwIAqQMAAIIDAgCpAwEAMAMB+wcAAACkBQwACyiQwLwDASENAAAAnwMDAf8DAAAAAAAA3gMAAPsDAABvBA4AMAQDEQ8AAACkAxIAAEQAgW8EEwCfAwICbwQUADAEA6MVAAAA+wYCAE0FBoUWAAAApAYYAABcYIFvBxkAjAgAAIwJAACfBgQCCQQFBjAEA4UWAAAAMAIDJBoAAACkBBIAAEQAgW8FGwCfBAICbwUcADAFBDMdAAAAbwUeADAFBIUfAAAAMAIEJBoAAAD7BQAAMAMF2CAAAAD7BQAAMAQFhR8AAAD7BQAAMAIFZiEAAAD7BQAAMAEFAQQAAAD7BQAApAYjAAAAIEKfBgECMAYFsyQAAAD7BQAA+wcDAE0GB/0lAAAA+wgEALwGBscmAAAAnwYDAjAGBTknAAAAqQUBAIIFAgAoAyEEAAAAQANKAyMDJAMlAyYDJwMoAykDKgMrBAsokMADLANLAy4DLwMEBABEAIEDMAcAAIB/AACAfwAAgH8AAAAAAzEDDAMNBABcYIECGC1EVPsh+b8DHQMyBwAkdEkAJHRJACR0SQAAAAADMwcAAAAAAACAvwAAAAAAAAAAAxkDGwMLA0cEAAAgQgNIAzYDNwM4AKcBTAEYAAABAAAAAQACAAABAQACAAAAAQEAAgABAQACAAABAAIAAAEAAwAAAQAAAAACAAABAAAAAgAAAAEAAAEAAAAAAAAAAAAAAAEAAgAAAAEAAAEAAAEAAgAAAQAAAQAAAQAAAQAAAAAAAgAAAAAAAAAAAAIAqAAAAAADAAIAAAAz+wAAACsAAgCpAAAAggACAPsBAABNAAERAAAAAPAAAwABAAAAqQAAAIIAAgD7AQAATQAB2AIAAAC8AABQAwAAAJ8AAgH7AQAATQABhQQAAAC8AABQAwAAAJ8AAgH7AQAATQABOQUAAAC8AAAaBgAAAJ8AAgH7AQAATQABAQcAAACpAQAAMAEA+wgAAAD7AQAATQABAQcAAACkAgwACyiQwLwAACENAAAAnwADAcYAAADeAAAA+wABALwAAN0OAAAAnwACAakAAQCCAAIADwMuA0sDGwM6AxkDOAM7AyQDJwMpAyoDTQQLKJDAAywDPADZAU4BGAAAAQACAAAAAAEAAgAAAAAAAQAAAAAAAQAAAAAAAgAAAAAAAQAAAAAAAAABAAEAAAABANoAAAAAFQACAAATAAAEAxEKAgMRIgIDETQCAxFMAlr7AAAAnwABAisAAgCpAQAAggECAPsBAQBvBAAAbxEBAIwTAgCMFAMAvBER8AIAAACfEQQCvBERmwMAAACfEQICvBERmwMAAACfEQICvBERmwMAAACfEQICvBERmwMAAACfEQICvBERmwMAAACfEQICUgURAG8GBABvBwQAbxEFAIwTAwCMFAMAvBER8AIAAACfEQQCvBERmwMAAACfEQICvBERmwMAAACfEQICvBERmwMAAACfEQICUggRAG8JBABvCgQAbxEGAIwTBQCMFAUAvBER8AIAAACfEQQCvBERmwMAAACfEQICvBERmwMAAACfEQICvBERmwMAAACfEQICvBERmwMAAACfEQICvBERmwMAAACfEQICUgsRAG8MBABvDQQAbxEHAIwTAwCMFAQAvBER8AIAAACfEQQCvBERmwMAAACfEQICUg4RAG8PBABvEAgAcwMEELwBAWsJAAAAnwEDAYIAAQAKA08DUANCA0MDRANRA1IDUwNUAz8A6gFLARgAAAEBAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHrAAAAAA8AAgAACwAAAgMLCgIDCxYCMPsAAACfAAECKwACAKkBAACCAQIA+wEBAG8EAABvCwEAjA0DAIwOBAC8CwvwAgAAAJ8LBAK8CwubAwAAAJ8LAgJSBQsAbwYEAG8HBABvCwUAjA0DAIwOAwC8CwvwAgAAAJ8LBAK8CwubAwAAAJ8LAgK8CwubAwAAAJ8LAgK8CwubAwAAAJ8LAgK8CwubAwAAAJ8LAgK8CwubAwAAAJ8LAgJSCAsAbwkEAG8KBgBzAwQKvAEBawcAAACfAQMBggABAAgDVQNWA0IDQwNEA1cDWAM/APEBWQEYAAABAQACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8gAAAAANAAIAAAcAAAEDCQkCI/sAAACfAAECKwAfAPsBAQBvBAAAbwUBAG8JAgCMCwQAjAwJALwJCfADAAAAnwkEArwJCZsEAAAAnwkCArwJCZsEAAAAnwkCArwJCZsEAAAAnwkCArwJCZsEAAAAnwkCArwJCZsEAAAAnwkCAlIGCQBvBwEAbwgFAHMDBAi8AQFrBgAAAJ8BAwGCAAEABwNAA0QDWgNCA0MDWwM/APoBPgEYAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL7AAAAAAIAAgAAACj7AAAAKwABAIIAAQD7AQAATQABEQAAAADwAAIAAQAAAIIAAQD7AQAATQAB2AIAAAC8AABQAwAAAJ8AAgH7AQAATQABhQQAAAC8AABQAwAAAJ8AAgH7AQAATQABOQUAAAC8AAAaBgAAAJ8AAgH7AQAATQABAQcAAACpAQAAMAEA+wgAAADGAAAA3gAAAPsAAQC8AADdCQAAAJ8AAgGCAAEACgMuAy0DGwM6AxkDOAM7AyQDJwM8AIACXAEYAAABAgAAAAABAgAAAAAAAQAAAAAAAQAAAAAAAgAAAAAAAQABAAAAfHoAAAAADwACAAALAAACAwsIAgMLGgIu+wAAAJ8AAQIrACoA+wEBAG8EAABvCwEAjA0CAIwOBQC8CwvwAgAAAJ8LBAK8CwubAwAAAJ8LAgK8CwubAwAAAJ8LAgK8CwubAwAAAJ8LAgJSBQsAbwYEAG8HBABvCwUAjA0DAIwOBAC8CwvwAgAAAJ8LBAK8CwubAwAAAJ8LAgK8CwubAwAAAJ8LAgK8CwubAwAAAJ8LAgJSCAsAbwkEAG8KBgBzAwQKvAEBawcAAACfAQMBggABAAgDVQNdA0IDQwNEA14DXwM/AIMCYAEYAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgQBAAAAAQABAAAAA/sAAACfAAEBggABAAAAiQJhARgAAAEKAQAAAAIAAgAAAAr7AAAADgAHAPsBAABNAAERAAAAAPAAAwABAACA+wABAJ8AAQGCAAEAAgMuA0sAjgIAARgAAAEAAAAAAQADDwEAAAAFAQgAAAAvTQEANgAAAABNAgDfAQAAAN4BAADeAgEA2QEAABICAgASAgAA+wIBADABApwCAAAA2QEBABICAwASAgQA+wIBADABAiMDAAAA2QECABICBQASAgAA+wIBADABAlYEAAAAwAEFABICBgD7AgEAMAEC7AYAAACkAQgAAABwQKQECgAAAJBATQMEJAsAAABNAgMaDAAAAJ8BAgJNAgEkDQAAANkEBAASAgMAEgIHALwCAscOAAAAnwIDAYIAAQAPA2IDYwM+A1wDYAYPA2EDZAQAAHBAA2UEAACQQAMdA2YDZwM3BQwNDg8Q+AFoARgAAAAAAAABAAAAAAAGAAAAAAADAAAAAAAGAAAAAAQAAAAAAAAAAAEAAAAAAAAAB/kAAAAAGwAAAQIAjAGjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIBAAAAAEBvBAUAvAICFgMAAACfAgMCpAMHAAAAYEBNBQKhCAAAAE0EBdIJAAAAnwMCAqQEBwAAAGBATQYCoQgAAABNBQYfCgAAAJ8EAgKkBQEAAAAAQG8HCwC8BQUWAwAAAJ8FAwJNBgUxDAAAAKQIDgAAANBATQcISA8AAADGCAAAxgkAAMYKAACkCxIAAEQAgaQNDgAAANBATQwNRxMAAADAChQAEgALABIADADGCwAAxgwAAMYNAADGDgAATQ8E7xEAAACfDwECTRAE7xEAAACfEAECxhEAANkSAQASARH/2RMCABIBEf8SAAcAEgEK/xIBDP/ZFAMAEgER/xIABgASAAcAEgADABIAAAASABMA2RUEABIBEf8SAA8A2QsFABIAFAASAQj/2QwGABIBEf8SAA8AEgEI/9kWBwASARH/EgAHABIBCv8SAQ7/2RcIABIBEf8SAAYAEgAHABIAAAASABYA2RgJABIBEf8SABAA2Q0KABIAFwASAQj/2Q4LABIAGAASAQj/2RkMABIBCP8SAQn/EgAUABIBEf8SAA8AEgAXABIAGAASAQ7/4hodADAZGnMVAAAAMAsalBYAAAAwDBq2FwAAADANGmMYAAAAMA4aBhkAAAAwEhqSGgAAADAPGgobAAAAMBAauBwAAADBCAAAghoCAB4DaQQAAABAA2oDawNsA20DZAQAAGBAA24DbwNwA3EDcgMFBAAA0EADcwMYAwQEAEQAgQN0BgADaAMtA0YDSwNZAwoDdQN2BQgVFhcYGRobHA0AAQIDBAUGBwgJCgsRAQABBgABAAAAAAABAAAAAAABAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAEAAQAAAAEAAgIAAQAAAAEAABwAAQACAADSAAACAQADAAAAABEAAAAAAAAyAAAQAAAHAAAABwAAAAAQAAAAAAAyAAARAAAHAAAHAAAAAAAAAAAeAQABAAEAFwABAAEAAgABAAAAAQAAAC8AAADqAAAAABK9bn0wWmxur4+qF6RPQIRzX+HaovCehY1czV33oTw2Tk5qqmjGv6jo

-- Decompiled by Krnl

local v_u_1 = game:GetService("RunService")
game:GetService("UserInputService")
local v2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v2.Std.Audio)
local v4 = require(v2.Std.Signal)
local v_u_5 = game:GetService("Players").LocalPlayer
local v_u_6 = workspace.CurrentCamera
local v_u_7 = nil
local v_u_8 = nil
local v_u_9 = Vector3.new
local v_u_10 = workspace.FindPartOnRayWithIgnoreList
local function v_u_23(p11, p12, ...)
	-- upvalues: (copy) v_u_9, (copy) v_u_10
	local v13 = p12.magnitude
	local v14 = p12.unit
	local v15 = p11
	local v16 = 0
	local v17 = 0
	local v18 = { ... }
	while true do
		v16 = v16 + 1
		local v19 = Ray.new(p11, v14 * (v13 - v17))
		local v20, v21
		v20, p11, v21 = v_u_10(workspace, v19, v18, false, true)
		local v22
		if v20 then
			v22 = v20.CanCollide
		else
			v22 = v20
		end
		if not v22 then
			table.insert(v18, v20)
		end
		v17 = (v15 - p11).magnitude
		if v22 or (v13 - v17 <= 0.001 or v16 > 4) then
			if not v20 then
				p11 = v15 + v14 * v13
				v21 = v_u_9
			end
			return v20, p11, v21
		end
	end
end
local v_u_24 = nil
local v_u_25 = nil
local v_u_26 = v4.new()
local v_u_27 = v4.new()
local v_u_28 = nil
local function v29()
	-- upvalues: (ref) v_u_28
	return v_u_28 ~= nil
end
local function v_u_40()
	-- upvalues: (ref) v_u_28, (copy) v_u_6, (ref) v_u_23, (ref) v_u_24
	local v30 = v_u_28.HumanoidRootPart
	local v31 = v_u_6.CFrame * CFrame.Angles(0.2, 0, 0)
	local v32 = v30.RotVelocity.y
	local v33 = math.clamp(v32, -4, 4)
	local v34 = v31.LookVector:Dot(Vector3.new(0, 1, 0))
	local v35 = math.abs(v34)
	local v36 = v31.LookVector.X
	local v37 = v31.lookVector.Z
	local v38 = Vector3.new(v36, 0, v37)
	v_u_28.Velocity.Velocity = v38 * 60 * math.max(0.5, v35) + Vector3.new(0, v35, 0) * -40
	v_u_28.Gyro.CFrame = CFrame.new(Vector3.new(), v31.lookVector) * CFrame.new(0, 0, v33 * 0.125)
	local v39, _ = v_u_23(v30.Position, Vector3.new(0, -4, 0), v30.Parent)
	if v39 and not v39:IsDescendantOf(workspace.Vehicles) then
		v_u_24()
	end
end
local function v_u_46()
	-- upvalues: (ref) v_u_28, (copy) v_u_5, (copy) v_u_6, (copy) v_u_3, (copy) v_u_1, (copy) v_u_40
	if v_u_28 then
		print("Already has parachute")
		return false
	end
	local v41 = v_u_5.Character
	if not v41 then
		return false
	end
	local v42 = v41:FindFirstChild("Humanoid")
	if not v42 then
		return false
	end
	local v43 = v41.PrimaryPart
	if not v43 then
		return false
	end
	if v42.PlatformStand then
		return false
	end
	if v42.Sit then
		return false
	end
	v42.PlatformStand = true
	v42:ChangeState(Enum.HumanoidStateType.PlatformStanding)
	v_u_28 = {
		["Type"] = "Parachute"
	}
	local v44 = Instance.new("BodyGyro")
	v44.MaxTorque = Vector3.new(10000, 10000, 10000)
	v44.CFrame = v_u_6.CFrame * CFrame.Angles(0.2, 0, 0)
	v44.Parent = v43
	local v45 = Instance.new("BodyVelocity")
	v45.MaxForce = Vector3.new(1000000, 1000000, 1000000)
	v45.Velocity = Vector3.new(0, -1, 0)
	v45.Parent = v43
	v_u_28.Gyro = v44
	v_u_28.Velocity = v45
	v_u_28.HumanoidRootPart = v43
	v_u_28.Humanoid = v42
	v_u_3.ObjectLocal(v42.RootPart, 4482070135)
	v_u_28.Loop = v_u_1.Heartbeat:Connect(v_u_40)
	return true
end
local function v47()
	-- upvalues: (copy) v_u_46, (ref) v_u_7
	if not v_u_46() then
		return false
	end
	v_u_7:FireServer("r4bb5zs3")
end
v_u_24 = function()
	-- upvalues: (ref) v_u_28, (copy) v_u_26, (ref) v_u_7
	local v48
	if v_u_28 and v_u_28.Type == "Parachute" then
		v_u_28.Gyro:Destroy()
		v_u_28.Velocity:Destroy()
		v_u_28.Loop:Disconnect()
		v_u_28.Humanoid.PlatformStand = false
		v_u_28 = nil
		v_u_26:Fire()
		v48 = true
	else
		v48 = false
	end
	if not v48 then
		return false
	end
	v_u_7:FireServer("g" .. ("xbxguy"):sub(2, 3):reverse():reverse():reverse() .. "68ed3")
end
local function v_u_58()
	-- upvalues: (ref) v_u_28, (copy) v_u_6, (ref) v_u_23, (ref) v_u_25
	local v49 = v_u_28.HumanoidRootPart
	local v50 = v_u_6.CFrame * CFrame.Angles(0.2, 0, 0)
	local v51 = v50.lookVector:Dot(Vector3.new(0, 1, 0))
	local v52 = math.clamp(v51, -1, -0.06)
	local v53 = math.abs(v52)
	local v54 = v50.lookVector.X
	local v55 = v50.lookVector.Z
	local v56 = Vector3.new(v54, 0, v55)
	v_u_28.Velocity.Velocity = v56 * 60 * math.max(0.9, v53) + Vector3.new(0, v53, 0) * -90
	v_u_28.Gyro.CFrame = CFrame.new(Vector3.new(), v50.lookVector * 1) * CFrame.Angles(-1.8849555921538759, 0, 0)
	local v57, _ = v_u_23(v49.Position, Vector3.new(0, -3, 0), v49.Parent)
	if v57 and (not v57:IsDescendantOf(workspace.Vehicles) and tick() - v_u_28.Started > 1) then
		v_u_25()
	end
end
local function v_u_64()
	-- upvalues: (ref) v_u_28, (copy) v_u_5, (copy) v_u_6, (copy) v_u_1, (copy) v_u_58
	if v_u_28 then
		print("Already has glider")
		return false
	end
	local v59 = v_u_5.Character
	if not v59 then
		return false
	end
	local v60 = v59:FindFirstChild("Humanoid")
	if not v60 then
		return false
	end
	local v61 = v59.PrimaryPart
	if not v61 then
		return false
	end
	if v60.PlatformStand then
		return false
	end
	if v60.Sit then
		return false
	end
	v60.PlatformStand = true
	v60:ChangeState(Enum.HumanoidStateType.PlatformStanding)
	v_u_28 = {
		["Type"] = "Glider"
	}
	local v62 = Instance.new("BodyGyro")
	v62.MaxTorque = Vector3.new(inf, inf, inf)
	v62.CFrame = v_u_6.CFrame * CFrame.Angles(-1.5707963267948966, 0, 0)
	v62.Parent = v61
	local v63 = Instance.new("BodyVelocity")
	v63.MaxForce = Vector3.new(1000000, 1000000, 1000000)
	v63.Velocity = Vector3.new(0, -1, 0)
	v63.Parent = v61
	v_u_28.Gyro = v62
	v_u_28.Velocity = v63
	v_u_28.HumanoidRootPart = v61
	v_u_28.Humanoid = v60
	v_u_28.Started = tick()
	v_u_28.Loop = v_u_1.Heartbeat:Connect(v_u_58)
	return true
end
local function v_u_65()
	-- upvalues: (ref) v_u_28, (copy) v_u_27
	if not v_u_28 then
		return false
	end
	if v_u_28.Type ~= "Glider" then
		return false
	end
	v_u_28.Gyro:Destroy()
	v_u_28.Velocity:Destroy()
	v_u_28.Loop:Disconnect()
	v_u_28.Humanoid.PlatformStand = false
	v_u_28.Humanoid:ChangeState(Enum.HumanoidStateType.GettingUp)
	v_u_28 = nil
	v_u_27:Fire()
	return true
end
local function v66()
	-- upvalues: (copy) v_u_64, (ref) v_u_7
	if not v_u_64() then
		return false
	end
	v_u_7:FireServer("o" .. ("gkdcq0j"):sub(2, 3):reverse():reverse():reverse():reverse():reverse() .. "" .. "" .. ("btum4o"):sub(3, 3):reverse():reverse():reverse() .. "" .. "" .. ("s38jig95s"):sub(5, 5):reverse():reverse():reverse():reverse():reverse() .. "" .. "" .. ("aodumm"):sub(3, 4):reverse() .. "b")
end
v_u_25 = function()
	-- upvalues: (copy) v_u_65, (ref) v_u_7
	if not v_u_65() then
		return false
	end
	v_u_7:FireServer("p" .. ("afb5yq35"):sub(3, 4):reverse() .. "" .. "" .. ("acsfd3"):sub(3, 3):reverse():reverse():reverse():reverse():reverse() .. "b66k")
end
return {
	["Init"] = function(p67)
		-- upvalues: (ref) v_u_7, (ref) v_u_8, (copy) v_u_46, (ref) v_u_28, (copy) v_u_26, (copy) v_u_64, (copy) v_u_65, (ref) v_u_25
		local v68 = p67.Event
		local v69 = p67.em
		v_u_7 = v68
		v_u_8 = v69
		function v_u_8.r4bb5zs3()
			-- upvalues: (ref) v_u_46, (ref) v_u_7
			if not v_u_46() then
				v_u_7:FireServer("g" .. "" .. ("gjude86bxuhd5"):sub(4, 9):reverse():reverse():reverse():reverse():reverse() .. "3")
			end
		end
		function v_u_8.gxb68ed3()
			-- upvalues: (ref) v_u_28, (ref) v_u_26
			if v_u_28 then
				if v_u_28.Type == "Parachute" then
					v_u_28.Gyro:Destroy()
					v_u_28.Velocity:Destroy()
					v_u_28.Loop:Disconnect()
					v_u_28.Humanoid.PlatformStand = false
					v_u_28 = nil
					v_u_26:Fire()
				end
			else
				return
			end
		end
		function v_u_8.odkuiudb()
			-- upvalues: (ref) v_u_64, (ref) v_u_7
			if not v_u_64() then
				v_u_7:FireServer("p" .. ("tbsb5opn"):sub(2, 5):reverse():reverse():reverse() .. "" .. "" .. ("uz66xbnu"):sub(3, 4):reverse():reverse():reverse() .. "k")
			end
		end
		function v_u_8.p5bsb66k()
			-- upvalues: (ref) v_u_65
			v_u_65()
		end
		require(script.Parent.DefaultActions).onJumpPressed:Connect(function()
			-- upvalues: (ref) v_u_28, (ref) v_u_25
			if v_u_28 and v_u_28.Type == "Glider" then
				v_u_25()
			end
		end)
	end,
	["Parachute"] = v47,
	["ParachuteStop"] = v_u_24,
	["Glider"] = v66,
	["GliderStop"] = v_u_25,
	["IsFlying"] = v29,
	["OnParachuteStopped"] = v_u_26,
	["OnGliderStopped"] = v_u_27
}
