-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNHDHNldG1ldGF0YWJsZQNuZXcETWFpZBRPblJvY2tldFF1ZXVlRW1wdGllZBBPblJvY2tldEV4cGxvZGVkBVNldHVwBlJvY2tldAhSZXNvdXJjZQpJdGVtU3lzdGVtC1Byb2plY3RpbGVzBUNsb25lBkNGcmFtZQdWZWN0b3IzCXdvcmtzcGFjZQZQYXJlbnQIQWRkU21va2ULT2JqZWN0TG9jYWwMbml0cm9faWduaXRlBVBpdGNoDFRpbWVQb3NpdGlvbgZWb2x1bWUKbml0cm9fbG9vcAZMb29wZWQLRW1pdHRlclNpemUKQ3JlYXRlUGFydApSb2NrZXRGaXJlC1JvY2tldFNtb2tlBmFzc2VydApMaXN0Um9ja2V0BXRhYmxlBmluc2VydAZMYXVuY2gGVXBkYXRlCkRpc2Nvbm5lY3QHRGVzdHJveQdDb25uZWN0Cklnbm9yZUxpc3QJSGVhcnRiZWF0CEdpdmVUYXNrBHRpY2sKTGFzdFVwZGF0ZSFSYXlJZ25vcmVOb25Db2xsaWRlV2l0aElnbm9yZUxpc3QIVmVsb2NpdHkMVHJhbnNwYXJlbmN5BGdhbWUGRGVicmlzB0FkZEl0ZW0EbmV4dAtHZXRDaGlsZHJlbgVTb3VuZANJc0EHRmFkZU91dA9QYXJ0aWNsZUVtaXR0ZXIHRW5hYmxlZAlFeHBsb2RlQXQGcmVtb3ZlBEZpcmUJZXhwbG9kZUF0ClJ1blNlcnZpY2UKR2V0U2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQdyZXF1aXJlA1N0ZAZTaWduYWwHUmF5Q2FzdAZNb2R1bGUOUm9ja2V0TGF1bmNoZXITUm9ja2V0TGF1bmNoZXJVdGlscwVBdWRpbxJleHBsb3Npb25fbGFyZ2VfMDIHX19pbmRleAAMBAADAAAAH/8AAwAAAAAA+wMAAJ49AAQDAAAAUgIAAKQBAQAAAABAnwEDAfsCAQBNAQLvAgAAAJ8BAQIwAQB2AwAAAPsCAgBNAQLvAgAAAJ8BAQIwAQDVBAAAAPsCAgBNAQLvAgAAAJ8BAQIwAQAtBQAAALwBAJkGAAAAnwECAYIAAgAHAwEEAAAAQAMCAwMDBAMFAwYAEgIBGAAAAQAAAAAAAAEAAAAAAAEAAAAAAAEAAAAAAAIAAAITAAAAAAkDAwAAAEn7BwAATQYHYgEAAABNBQbwAgAAAE0EBQ8DAAAATQMEAAAAAAC8AwM6BAAAAJ8DAgKkBQcAABhQgEw2AAKkBgkAABiAgJ8GAQJSBwIAnwUDAkMEBQEwBAOFBQAAAKQECwAAAKBAMAQDJAwAAABSBgMAvAQA/w0AAACfBAMB+wUBAE0EBdEOAAAAUgUDAPsHAgBNBgdLDwAAAOIHEwBvCBQAMAgHABAAAABvCBUAMAgHxhEAAABvCBYAMAgHSxIAAACfBAQB+wUBAE0EBdEOAAAAUgUDAPsHAgBNBgeeFwAAAOIHGABvCBUAMAgHABAAAACMCAEAMAgHSxIAAACfBAQCqQUBADAFBLUZAAAAjAUZADAFBIMaAAAAMAMEJAwAAACCAwIAGwMHAwgDCQMKAwsDDAMCBAAYUIADDQQAGICAAw4EAACgQAMPAxADEQMSAxMDFAMVBQMQERICZmZmZmZm5j8CMzMzMzMz4z8CMzMzMzMz0z8DFgUCEBIDFwMYAB0ZARgAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAACAAAAAgAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAQAAAQAAAQACHgAAAAAIAgEAAAAd+wYAAE0FBmIBAAAATQQF8AIAAABNAwQPAwAAAE0CA+kAAAAAvAICOgQAAACfAgICMAECJAUAAAD7BwAATQYHYgEAAABNBQbwAgAAAE0EBQ8DAAAATQMEWwYAAAC8AwM6BAAAAJ8DAgIwAQMkBQAAAIIAAQAHAxoDCAMJAwoDCwMPAxsALRABGAAAAAAAAAAAAAAAAAEAAQAAAAAAAAAAAAAAAQABLgAAAAAJBAAAAAAluwEBA1IFAQCkBAEAAAAAQJ8EAgG7AQIDUgUCAKQEAQAAAABAnwQCAbsBAwNSBQMApAQBAAAAAECfBAIBUgYBAFIHAgC8BAAIAgAAAJ8EBAL/BQAABQAAAPYBBQD2AgUB9gMFAvYEBQOMBgYA9gYFBE0HAC8DAAAAnjQHBAUAAABSCAUApAYGAAAUQICfBgMBggABAAcDHAQAAABAAxkDHQMeAx8EABRAgAAzIAEYAAAAAAABAAAAAAEAAAAAAwAAAAACAAEBAQEBAAEAAAAAAAAAATQAAAAAAgABAAAABfsAAAC8AAAmAAAAAJ8AAgGCAAEAAQMhAEcAARgAAAAAAUgAAAAAAgACAAAAG/sAAAC8AAAaAAAAAJ8AAgHGAAAA3gAAAPsBAQBNAAHVAQAAALwAAFACAAAAnwACAfsAAQDGAQAAMAEA1QEAAAD7AQEATQABLQMAAAC8AABQAgAAAJ8AAgH7AAEAxgEAADABAC0DAAAAggABAAQDIgMEAyMDBQBOAAEYAAAAAAEAAQAAAAAAAQAAAAEAAAAAAAEAAAABTwAAAAADAAIAAAAs+wIAAE0BAi8AAAAAHAABAIwBAABgAQsAAAAAAPsBAABNAAHVAQAAANkCAAASAgEAEgIAALwAAMcCAAAAnwADAYIAAQD7AAEAvAAAGgMAAACfAAIBxgAAAN4AAQD7AQAATQAB1QEAAAC8AABQBAAAAJ8AAgH7AAAAxgEAADABANUBAAAA+wEAAE0AAS0FAAAAvAAAUAQAAACfAAIB+wAAAMYBAAAwAQAtBQAAAIIAAQAGAx0DBAMkAyIDIwMFAQVLAAEYAAAAAAAAAAIAAAAAAAAAAAAJAAAAAQABAAAAAAABAAAAAQAAAAAAAQAAAAJMAAAAAAUBAQAAABr/AQAAAAAAADABAC8AAAAA/wEAAAAAAAAwAQDKAQAAAPsCAABNAQL9AgAAANkDAAASAAAAvAEBxwMAAACfAQMCTQIAdgQAAADZBAEAEgAAABIBAf+8AgL9BQAAAJ8CAwHBAQAAggABAAYDHQMlAyYDJAMDAycCBAZDBgEYAAAAAAEAAAACAAAAAAAAAAQAAAAAAAAAFABEAAAAABgBAgAAAIkBpAEBAAAAAECfAQECTQMABAIAAADKAgMBJgMBAjABAAQCAAAATQUALwMAAAAcBAUAUgcEAIwFAQCMBv//qAVrAE0JAC8DAAAAhwgJBxMJCAATCggBEwsIAhMMCAMTDQgEjA4AAGAOLAANAAAACQ4LA8YPAADGEAAAxhEAAMYSAABHDxEAAAAAgPsUAABNExTIBAAAAFIUCQBSFQoAUhYOAE0XAMoFAAAAnxMFBVIPEwBSEBQAUhEVAFISFgBHDwIAAAAAAIwNAACkFAgAABxggEw2AAKkFQoAAByQgJ8VAQJSFgoAnxQDAkMTFBAwEwyFBgAAAAkTCgswEwyFCwAAAPYQCAD2CggB9gsIAiYTDQP2EwgEZQA0AIwOAQAwDgzZDAAAAKQPDgAAANBATQ4PnQ8AAABSEAwAjBEBALwODngQAAAAnw4EAaQOEgAAABBBvA8MaBMAAACfDwIDFw4UAG8VFAC8ExL+FQAAAJ8TAwIOEwcA+xQBAE0TFKEWAAAAUhQSAG8VFwCfEwMBZQAIAG8VGAC8ExL+FQAAAJ8TAwIOEwMAqRMAADATEvAZAAAAbg7r/wIAAABSEAkAvA4AOBoAAACfDgMBxg4AAPYOCAOkDh0AAHCwgU0PAC8DAAAAUhAHAJ8OAwGLBZX/jAUAAGAFCwAEAAAATQYALwMAAAAcBQYADQUGAB4AAIBNBQDVHwAAALwFBd0gAAAAnwUCAYIAAQAhAygEAAAAQAMpAx0DKgMlAwwDAgQAHGCAAw0EAByQgAMrAywDLQQAANBAAy4DLwMwBAAAEEEDMQMyAzMDNAIzMzMzMzPTPwM1AzYDNwMeAzgEAHCwgQIAAAAAAAAAAAMEAzkAYCEBGAAAAAEAAAEBAAIAAAEAAAABAAABAAAAAAEAAAEBAAAAAQACAAAAAAAAAAAAAAAAAQABBAAAAAAAAAAAAAABAAACAQECAQACAAABAAAAAAAAAAABAAAAAAABAAAAAAEAAAAAAAABAAAAAAEAAPwABwAAAAEAAQAAAAAA3SkAAAAAAAAAAQAAAAACYQAAAAAFAgEAAAAM+wMAAE0CAxgAAAAAUgMBAJ8CAgFNAgAtAQAAAFIEAQC8AgLdAgAAAJ8CAwGCAAEAAwM6AwUDOQCUATcBGAAAAAAAAQAAAAAAAZUAAAAAAwEAAAAACU0BAHYAAAAAvAEBUAEAAACfAQIBxgEAADABAHYAAAAAggABAAIDAwMjAJgBIwEYAAAAAAABAAABmQAAAAAKAAABAgBiowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBAQAAAABAbwMEALwBARYDAAAAnwEDAqQCBgAAAFBATQQBoQcAAABNAwQfCAAAAJ8CAgKkAwYAAABQQE0FAaEHAAAATQQFdgkAAACfAwICpAQGAAAAUEBNBgFACwAAAE0FBjIKAAAAnwQCAqQFBgAAAFBATQcB0wwAAABNBgfFDQAAAJ8FAgKkBgYAAABQQE0IAaEHAAAATQcI0g4AAACfBgIC4gcSAG8IEwAwCAfiDwAAAG8IFAAwCAeeEAAAAG8IFQAwCAdLEQAAAP8IBQAAAAAAMAgIbhYAAADACRcAEgAIABIAAwASAAIAMAkI7xgAAADACRkAEgABABIABgASAAcAMAkICBoAAADACRsAEgABADAJCP8cAAAAwAkdADAJCGQeAAAAwAkfABIAAAAwCQiZIAAAAMAJIQASAAQAEgAGADAJCCYiAAAAwAkjABIABQAwCQg4JAAAAMAJJQAwCQhQJgAAAIIIAgAnAy0EAAAAQAM7AzwDPQM+BAAAUEADPwNAAwMDQQNCA0MDRANFA0YDFgMSBQMPEBECAADgLbht4EECAAC4g4rfAEICAAAAVXSp1EEDRwYAAwIGAQMZBgIDEAYDAyAGBwMGBggDIQYJAzcGCgMjCAABAgMHCAkKAQABGAABAAAAAAABAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAIBAAABAAABAAADAAEAAQAAAAAACwAAAAAAEAAAAAYAABAAAAAdAAAAADQAAAAEAAAEAQAAAAALI2qBQdeP48YRruvVPg+OEfaPV/0FGvFIal280uFhK2Mq10mpn/qL8w==

-- Decompiled by Krnl

local v_u_1 = game:GetService("RunService")
local v_u_2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v_u_2.Std.Signal)
local v_u_4 = require(v_u_2.Std.Maid)
local v_u_5 = require(v_u_2.Module.RayCast)
local v_u_6 = require(v_u_2.RocketLauncher.RocketLauncherUtils)
local v_u_7 = require(v_u_2.Std.Audio)
local v_u_8 = {
	["explosion_large_02"] = 2205008239,
	["nitro_loop"] = 9058734199,
	["nitro_ignite"] = 1386598740
}
local v_u_9 = {}
v_u_9.__index = v_u_9
function v_u_9.new()
	-- upvalues: (copy) v_u_9, (copy) v_u_4, (copy) v_u_3
	local v10 = {}
	local v11 = v_u_9
	setmetatable(v10, v11)
	v10.Maid = v_u_4.new()
	v10.OnRocketQueueEmptied = v_u_3.new()
	v10.OnRocketExploded = v_u_3.new()
	v10:Setup()
	return v10
end
function v_u_9.CreatePart(p12, p13, p14)
	-- upvalues: (copy) v_u_2, (copy) v_u_7, (copy) v_u_8
	local v15 = v_u_2.Resource.ItemSystem.Projectiles.Rocket:Clone()
	v15.CFrame = CFrame.new(Vector3.new(), p14) + p13
	v15.Parent = workspace
	p12:AddSmoke(v15)
	v_u_7.ObjectLocal(v15, v_u_8.nitro_ignite, {
		["Pitch"] = 0.7,
		["TimePosition"] = 0.6,
		["Volume"] = 0.3
	})
	local v16 = v_u_7.ObjectLocal(v15, v_u_8.nitro_loop, {
		["Pitch"] = 0.6,
		["Volume"] = 1
	})
	v16.Looped = true
	v16.EmitterSize = 25
	v16.Parent = v15
	return v15
end
function v_u_9.AddSmoke(_, p17)
	-- upvalues: (copy) v_u_2
	v_u_2.Resource.ItemSystem.Projectiles.RocketFire:Clone().Parent = p17
	v_u_2.Resource.ItemSystem.Projectiles.RocketSmoke:Clone().Parent = p17
end
function v_u_9.Launch(p18, p19, p20, p21)
	assert(p19)
	assert(p20)
	assert(p21)
	local v22 = {
		p19,
		p20,
		p21,
		p18:CreatePart(p19, p20),
		6
	}
	local v23 = p18.ListRocket
	table.insert(v23, v22)
end
function v_u_9.Setup(p_u_24)
	-- upvalues: (copy) v_u_1
	p_u_24.ListRocket = {}
	p_u_24.IgnoreList = {}
	local v_u_25 = v_u_1.Heartbeat:Connect(function()
		-- upvalues: (copy) p_u_24
		p_u_24:Update()
	end)
	p_u_24.Maid:GiveTask(function()
		-- upvalues: (copy) p_u_24, (ref) v_u_25
		if #p_u_24.ListRocket > 0 then
			p_u_24.OnRocketQueueEmptied:Connect(function()
				-- upvalues: (ref) v_u_25, (ref) p_u_24
				v_u_25:Disconnect()
				v_u_25 = nil
				p_u_24.OnRocketQueueEmptied:Destroy()
				p_u_24.OnRocketQueueEmptied = nil
				p_u_24.OnRocketExploded:Destroy()
				p_u_24.OnRocketExploded = nil
			end)
		else
			v_u_25:Disconnect()
			v_u_25 = nil
			p_u_24.OnRocketQueueEmptied:Destroy()
			p_u_24.OnRocketQueueEmptied = nil
			p_u_24.OnRocketExploded:Destroy()
			p_u_24.OnRocketExploded = nil
		end
	end)
end
function v_u_9.Update(p26)
	-- upvalues: (copy) v_u_5, (copy) v_u_7
	local v27 = tick()
	local v28 = v27 - (p26.LastUpdate or v27)
	p26.LastUpdate = v27
	local v29 = #p26.ListRocket
	for v30 = v29, 1, -1 do
		local v31 = p26.ListRocket[v30]
		local v32 = v31[1]
		local v33 = v31[2]
		local v34 = v31[3]
		local v35 = v31[4]
		local v36 = v31[5]
		if v36 > 0 then
			local v37 = v34 * v28
			local v38
			if nil == nil then
				local v39, v40, v41
				v39, v38, v40, v41 = v_u_5.RayIgnoreNonCollideWithIgnoreList(v32, v33, v37, p26.IgnoreList)
				if v39 ~= nil then
					v36 = 0
				end
			else
				v38 = nil
			end
			v35.CFrame = CFrame.new(Vector3.new(), v33) + v38
			v35.Velocity = v33 * v34
			v31[1] = v38
			v31[2] = v33
			v31[3] = v34
			v31[5] = v36 - v28
		else
			v35.Transparency = 1
			game.Debris:AddItem(v35, 1)
			local v42 = next
			local v43, v44 = v35:GetChildren()
			for _, v45 in v42, v43, v44 do
				if v45:IsA("Sound") then
					v_u_7.FadeOut(v45, 0.3)
				elseif v45:IsA("ParticleEmitter") then
					v45.Enabled = false
				end
			end
			p26:ExplodeAt(v32)
			v31[4] = nil
			table.remove(p26.ListRocket, v30)
		end
	end
	if v29 > 0 and #p26.ListRocket == 0 then
		p26.OnRocketQueueEmptied:Fire()
	end
end
function v_u_9.ExplodeAt(p46, p47)
	-- upvalues: (copy) v_u_6
	v_u_6.explodeAt(p47)
	p46.OnRocketExploded:Fire(p47)
end
function v_u_9.Destroy(p48)
	p48.Maid:Destroy()
	p48.Maid = nil
end
return v_u_9
