-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMvDHNldG1ldGF0YWJsZQNuZXcFX21haWQNX3NwcmluZ0FjdGl2ZQZDb2xvcjMHZnJvbVJHQgxfdGFyZ2V0Q29sb3IJX2NyZWF0ZUZ4CEluc3RhbmNlCkJsdXJFZmZlY3QEU2l6ZQdFbmFibGVkBGdhbWUITGlnaHRpbmcKR2V0U2VydmljZQZQYXJlbnQFX2JsdXIIR2l2ZVRhc2sVQ29sb3JDb3JyZWN0aW9uRWZmZWN0EF9jb2xvckNvcnJlY3Rpb24JU2NyZWVuR3VpDklnbm9yZUd1aUluc2V0CVBsYXllckd1aQVGcmFtZQVVRGltMhBCYWNrZ3JvdW5kQ29sb3IzB1Zpc2libGULX2NvbG9yRnJhbWUJU2V0VGFyZ2V0CVNldEFjdGl2ZQZVcGRhdGUEbWF0aANhYnMDbWF4DFRyYW5zcGFyZW5jeQpTYXR1cmF0aW9uBGxlcnAJVGludENvbG9yB0Rlc3Ryb3kHUGxheWVycwtMb2NhbFBsYXllchFSZXBsaWNhdGVkU3RvcmFnZQdyZXF1aXJlA1N0ZAZTcHJpbmcETWFpZAdfX2luZGV4AAYGAAMAAAAl/wADAAAAAAD7AwAAnj0ABAMAAABSAgAApAEBAAAAAECfAQMB+wIBAE0BAu8CAAAAnwEBAjABAMEDAAAA+wICAE0BAu8CAAAAjAIAAIwDAABvBAQAjAUBAJ8BBQIwAQDYBQAAAKQBCAAAHGCAjAL/AIwD/wCMBP8AnwEEAjABAPsJAAAAvAEAXAoAAACfAQIBggACAAsDAQQAAABAAwIDAwKamZmZmZnpPwMEAwUDBgQAHGCAAwcDCAALAgEYAAABAAAAAAAAAgAAAAAAAQAAAAAAAAAAAAIAAAAAAAAAAwAAAgwAAAAACgEBAAAAXqQBAgAABACAbwIDAJ8BAgKMAgAAMAIBLwQAAACpAgAAMAIB8AUAAACkAgcAAABgQG8ECAC8AgIWCQAAAJ8CAwIwAgEkCgAAADABANMLAAAATQIAwQwAAABNBADTCwAAALwCAv0NAAAAnwIDAaQCAgAABACAbwMOAJ8CAgKpAwAAMAMC8AUAAACkAwcAAABgQG8FCAC8AwMWCQAAAJ8DAwIwAwIkCgAAADACAIwPAAAATQMAwQwAAABNBQCMDwAAALwDA/0NAAAAnwMDAaQDAgAABACAbwQQAJ8DAgKpBAEAMAQDBREAAAD7BQAATQQFmRIAAAAwBAMkCgAAAE0EAMEMAAAAUgYDALwEBP0NAAAAnwQDAaQEAgAABACAbwUTAJ8EAgKkBRUAAARAgYwGAQCMBwAAjAgBAIwJAACfBQUCMAUELwQAAABNBQD7FgAAADAFBJ8XAAAAqQUAADAFBIAYAAAAMAMEJAoAAAAwBACFGQAAAIIAAQAaAwkDAgQABACAAwoDCwMMAw0EAABgQAMOAw8DEAMRAwMDEgMTAxQDFQMWAxcDGAMZBAAEQIEDBwMaAxsDHAAZCAEYAAAAAAEAAAEAAAEAAAAAAAAAAQABAAAAAAAAAgAAAAEAAAEAAAAAAAAAAQABAAAAAAAAAgAAAAEAAAEAAAAAAQAAAAAAAgAAAAEAAAAAAAAAAAEAAAABAAABAAEAARoAAAAABQIAAAAACk0CANgAAAAADgECAIwEAQBlAAEAjAQAALwCApcBAAAAnwIDAYIAAQACAwQDHQAzHgEYAAAAAAAAAAAAATQAAAAACwEAAAAAY00BANgAAAAAvAEBJgEAAACfAQIDbwQCANQEAgABAAAAqQMAAakDAQAOAycAjAUAAFsKAQU+CQoEeAgJA7sCCAKkBwgAABxggJ8HAgL1BgMHnhIFAwYAAACkBAoAACRggJ8EAwJNBQDTCwAAAFsGBAwwBgUvDQAAAFsGAQ71BQMGbwYPAGAFBwAGAAAATQYAhRAAAACpBwEAMAcGgBEAAABlAAUATQYAhRAAAACpBwAAMAcGgBEAAABNBgCFEAAAADAFBtkSAAAATQUA0wsAAABNBAXwEwAAAPEEBQADAAAATQQA0wsAAAAwAwTwEwAAAG8FAgC3BQIAAQAAAKkEAAGpBAEADgQWAIwGAQAJBQYBTQYAjBQAAAAwBQaKFQAAAKQGGAAAXGCBjAcBAIwIAQCMCQEAnwYEAk0IAPsZAAAAUgkBALwGBr8aAAAAnwYEAk0HAIwUAAAAMAYHLBsAAABNBgCMFAAAAE0FBvATAAAA8QUFAAQAAABNBQCMFAAAADAEBfATAAAAggABABwDBAMfAvyp8dJNYlA/AgAAAAAAAPA/ApqZmZmZmck/AgAAAAAAAABAAyADIQQAHGCAAyIEACRggAMRAgAAAAAAAC5AAwsCexSuR+F6hD8CK4cW2c737z8DHAMbAyMDDAMUAyQDBQMCBABcYIEDBwMlAyYANh8BGAAAAAAAAgAAAAABAgAAAAAAAAAAAAAAAAABAAAAAAIAAQAAAQAAAAAAAgAAAAACAAAAAgAAAAAAAQAAAAMAAAAAAQEAAQAAAAEAAAAAAAAAAAAAAAEAAAACAAAAAAABAAAAAjcAAAAABQEAAAAAEE0BAMEAAAAAxgIAADACAMEAAAAAvAIBUAEAAACfAgIBgT0ABQIAAABSAwAAbwQCAKQCBAAAADBAnwIDAYIAAQAFAwMDJwADAQQAADBAAFYnARgAAAEAAAEAAAEAAAAAAAABVwAAAAAHAAABAgA1owAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAk0BADEEAAAApAIBAAAAAEBvBAUAvAICFgMAAACfAgMCpAMHAAAAYEBNBQKhCAAAAE0EBSIJAAAAnwMCAqQEBwAAAGBATQYCoQgAAABNBQZ2CgAAAJ8EAgL/BQQAAAAAADAFBW4LAAAAwAYMABIABQASAAQAEgADADAGBe8NAAAAwAYOABIAAQAwBgVcDwAAAMAGEAAwBgVZEQAAAMAGEgAwBgUmEwAAAMAGFAAwBgVQFQAAAIIFAgAWAw0EAAAAQAMoAw8DKQMqAysEAABgQAMsAy0DLgMvBgADAgYBAwgGAgMeBgMDHwYEAycFAAECAwQBAAEYAAEAAAAAAAEAAQAAAAAAAQAAAAAAAAEAAAAAAAACAAEAAgAAAAAADgAAABoAAAMAACAAAAcBAAAAAAVeO3HCxloxPWz/G1a/qo6j0vloKK6IWxKRvoVo4DxX1dSgzDL1G3Pn

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players").LocalPlayer
local v2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v2.Std.Spring)
local v_u_4 = require(v2.Std.Maid)
local v_u_5 = {}
v_u_5.__index = v_u_5
function v_u_5.new()
	-- upvalues: (copy) v_u_5, (copy) v_u_4, (copy) v_u_3
	local v6 = {}
	local v7 = v_u_5
	setmetatable(v6, v7)
	v6._maid = v_u_4.new()
	v6._springActive = v_u_3.new(0, 0, 0.8, 1)
	v6._targetColor = Color3.fromRGB(255, 255, 255)
	v6:_createFx()
	return v6
end
function v_u_5._createFx(p8)
	-- upvalues: (copy) v_u_1
	local v9 = Instance.new("BlurEffect")
	v9.Size = 0
	v9.Enabled = false
	v9.Parent = game:GetService("Lighting")
	p8._blur = v9
	p8._maid:GiveTask(p8._blur)
	local v10 = Instance.new("ColorCorrectionEffect")
	v10.Enabled = false
	v10.Parent = game:GetService("Lighting")
	p8._colorCorrection = v10
	p8._maid:GiveTask(p8._colorCorrection)
	local v11 = Instance.new("ScreenGui")
	v11.IgnoreGuiInset = true
	v11.Parent = v_u_1.PlayerGui
	p8._maid:GiveTask(v11)
	local v12 = Instance.new("Frame")
	v12.Size = UDim2.new(1, 0, 1, 0)
	v12.BackgroundColor3 = p8._targetColor
	v12.Visible = false
	v12.Parent = v11
	p8._colorFrame = v12
end
function v_u_5.SetActive(p13, p14)
	p13._springActive:SetTarget(p14 and 1 or 0)
end
function v_u_5.Update(p15)
	local v16, _ = p15._springActive:Update()
	local v17 = v16 >= 0.001
	if v17 then
		local v18 = v16 * 2 / 0.2 - 1
		local v19 = 1 - math.abs(v18)
		local v20 = math.max(0, v19)
		p15._blur.Size = v20 * 15
		local v21 = 1 - v16 * 0.01
		if v21 < 0.999 then
			p15._colorFrame.Visible = true
		else
			p15._colorFrame.Visible = false
		end
		p15._colorFrame.Transparency = v21
	end
	if p15._blur.Enabled ~= v17 then
		p15._blur.Enabled = v17
	end
	local v22 = v16 > 0.001
	if v22 then
		local v23 = 1 * v16
		p15._colorCorrection.Saturation = v23
		local v24 = Color3.new(1, 1, 1):lerp(p15._targetColor, v16)
		p15._colorCorrection.TintColor = v24
	end
	if p15._colorCorrection.Enabled ~= v22 then
		p15._colorCorrection.Enabled = v22
	end
end
function v_u_5.Destroy(p25)
	local v26 = p25._maid
	p25._maid = nil
	v26:Destroy()
	setmetatable(p25, nil)
end
return v_u_5
