-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMpDkVhc2VfSW5PdXRRdWFkBmFzc2VydAxzZXRtZXRhdGFibGUFTW9kZWwFRG9vcjEGQ0ZyYW1lB0Rvb3IxQ0YFRG9vcjIHRG9vcjJDRgNuZXcIT25PcGVuZWQEQW5pbQZJc09wZW4HRGVzdHJveQZVcGRhdGULT25Db21wbGV0ZWQHQ29ubmVjdApPbkNhbmNlbGVkBE1haWQNUmVuZGVyU3RlcHBlZAhHaXZlVGFzawpUcmFuc2l0aW9uB1NlcU9wZW4ET3BlbghTZXFDbG9zZQVDbG9zZQRTaXplAVoGQW5nbGVzB0ludmVyc2ULU2V0RG9vck9wZW4ERmlyZQRnYW1lClJ1blNlcnZpY2UKR2V0U2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQdyZXF1aXJlA1N0ZAZTaWduYWwGTW9kdWxlB19faW5kZXgADQYBAAAAAA1vAgAAYAAFAAIAAACMAwIACQIDAAkBAgArAQUAjAQCAHgFAAIJAwQFCQIDAPUBAQKCAQIAAwIAAAAAAADgPwIAAAAAAADwvwIAAAAAAAAAQAAHAQEYAAAAAAAAAAAAAAAAAAgAAAAABQECAAAAMEcAAgAAAACAqQIAAakCAQC7AQICpAEBAAAAAECfAQIB/wEEAAAAAAD7BAAAnj0BBAQAAABSAwEApAIDAAAAIECfAgMBMAABOwQAAABNBAE7BAAAAE0DBFQFAAAATQIDhQYAAAAwAgGEBwAAAE0EATsEAAAATQMEpQgAAABNAgOFBgAAADACAWMJAAAA+wMBAE0CA+8KAAAAnwIBAjACAVALAAAAxgIAADACAQ4MAAAAqQIAADACATENAAAAggECAA4DAgQAAABAAwMEAAAgQAMEAwUDBgMHAwgDCQMKAwsDDAMNAA0KARgAAAAAAAAAAAIAAQAAAAAAAAIAAQAAAAAAAAABAAAAAAAAAAIAAAAAAAEAAAEAAAIOAAAAAAIAAQAAAAv7AQAATQABDgAAAAC8AABQAQAAAJ8AAgH7AAAAxgEAADABAA4AAAAAggABAAIDDAMOACMAARgAAAAAAAABAAAAASQAAAAAAgABAAAAC/sBAABNAAEOAAAAALwAAFABAAAAnwACAfsAAADGAQAAMAEADgAAAACCAAEAAgMMAw4AJwABGAAAAAAAAAEAAAABKAAAAAAEAAIAAAAL+wEAAE0AAQ4AAAAAvAAAJgEAAACfAAIC+wEBAPsCAABSAwAAnwEDAYIAAQACAwwDDwArAAEYAAAAAAAAAQAAAAEsAAAAAAgDAgAAADSQAQEATQMADgEAAABHAwYAAAAAAE0DAA4BAAAAvAMDUAIAAACfAwIB+wQAAE0DBO8DAAAAUgQBAJ8DAgIwAwAOAQAAAE0EAA4BAAAATQMEzwQAAADZBQAAEgAAALwDA8cFAAAAnwMDAU0EAA4BAAAATQMEwQYAAADZBQEAEgAAALwDA8cFAAAAnwMDAU0EAA4BAAAATQMEdgcAAAD7BgEATQUGzwgAAADZBwIAEgAAABIAAgC8BQXHBQAAAJ8FAwC8AwP9CQAAAJ8DAAGCAAEACgIAAAAAAAAYQAMMAw4DCgMQAxEDEgMTAxQDFQMCAwQdFgEYAAEAAAABAAAAAAIAAAAAAAABAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABB4AAAAABgIAAAAACqkCAQAwAgAxAAAAAFIEAQBNBQBiAQAAALwCAGkCAAAAnwIEAIICAAADAw0DFwMWADAYARgAAAABAAAAAAAAMQAAAAAGAgAAAAAKqQIAADACADEAAAAAUgQBAE0FAH4BAAAAvAIAaQIAAACfAgQAggIAAAMDDQMZAxYANBoBGAAAAAEAAAAAAAA1AAAAAA4CAAAAAD9NAgA7AAAAAE0DAlQBAAAApAQEAAAMIICMBQAAjAYAAE0KAy8GAAAATQkKewcAAAA5CAkAWwcIBZ8EBAJNCACECAAAAAkHCASkCAoAACQggFsKAQtbCQoFjAoAAIwLAACfCAQCCQYHCLwHBNoMAAAAnwcCAgkFBgcwBQOFAgAAAE0FAqUNAAAApAYEAAAMIICMBwAAjAgAAE0MBS8GAAAATQsMewcAAAA5CgsAWwkKBZ8GBAJNCgBjDgAAAAkJCgakCgoAACQggFsMAQtbCwwFjAwAAIwNAACfCgQCCQgJCrwJBtoMAAAAnwkCAgkHCAkwBwWFAgAAAIIAAQAPAwQDBQMGAwoEAAwggAIAAAAAAADgPwMbAxwDBwMdBAAkIIACGC1EVPshCUADHgMIAwkAOB8BGAAAAQABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAgABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAATkAAAAABwIAAAAAGQ0BBgAAAACATQIAUAEAAAC8AgLdAgAAAJ8CAgFSAgEAbwMDAGACBQADAAAAjAQCAAkDBAIJAQMCKwEFAIwFAgB4BgIFCQQFBgkDBAL1AQQDUgQBALwCAC0GAAAAnwIDAYIAAQAHAgAAAAAAAPA/AwsDIAIAAAAAAADgPwIAAAAAAADwvwIAAAAAAAAAQAMfAEIXARg7AAEAAAAAAsIAAAAAAAAAAAAAAD8AAAABCAAAAAAHAgAAAAAS9QIAAW8DAQBgAgUAAwAAAIwEAgAJAwQCCQEDAisBBQCMBQIAeAYCAwkEBQYJAwQC9QECA1IEAQC8AgAtBAAAAJ8CAwGCAAEABQIAAAAAAADwPwIAAAAAAADgPwIAAAAAAADwvwIAAAAAAAAAQAMfAEkZARhCvgAAAAAAAAAAAAAAQwAAAAEIAAAAAAMBAAAAABVNAQAOAAAAAEcBCQAAAAAATQEADgAAAAC8AQFQAQAAAJ8BAgHGAQAAMAEADgAAAABNAQBQAgAAALwBAVABAAAAnwECAcYBAAAwAQBQAgAAAIIAAQADAwwDDgMLAE0OARgAAAAAAQAAAAABAAACAAAAAAEAAAFOAAAAAAcAAAECAD2jAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIGAAAAUEBNBAGhBwAAAE0DBB8IAAAAnwICAqQDBgAAAFBATQUBQAoAAABNBAUOCQAAAJ8DAgLABAsA/wUFAAAAAAAwBQVuDAAAAMAGDQASAAUAEgACADAGBe8OAAAAwAYPABIAAwASAAAAMAYFaRAAAADABhEAMAYFFhIAAADABhMAMAYFYxQAAADABhUAMAYFLRYAAADABhcAMAYFYhgAAADABhkAMAYFfhoAAADABhsAMAYFUBwAAACCBQIAHQMhBAAAAEADIgMjAyQDJQQAAFBAAyYDJwMMAygGAAMpBgEDCgYFAxYGBgMYBgcDGgYIAx8GCQMXBgoDGQYLAw4JAAEFBgcICQoLAQABGAABAAAAAAABAAAAAAABAAAAAAAAAQAAAAAAAAIEAAEAAQAAAAAQAAAAABMAAAQAAAQAAAoAAAcAAAQAAAgBAAAAAAztTp3AVtSDWd+K91SNcvdMSjwLkCzscDrbOlwxYeAs1pGnYVuXeKF+

-- Decompiled by Krnl

local v_u_1 = game:GetService("RunService")
local v2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v2.Std.Signal)
local v_u_4 = require(v2.Module.Anim)
local v_u_5 = {}
v_u_5.__index = v_u_5
function v_u_5.new(p6)
	-- upvalues: (copy) v_u_5, (copy) v_u_3
	local v7 = p6 ~= nil
	assert(v7)
	local v8 = {}
	local v9 = v_u_5
	setmetatable(v8, v9)
	v8.Model = p6
	v8.Door1CF = v8.Model.Door1.CFrame
	v8.Door2CF = v8.Model.Door2.CFrame
	v8.OnOpened = v_u_3.new()
	v8.Anim = nil
	v8.IsOpen = false
	return v8
end
function v_u_5.Transition(p_u_10, p11, p_u_12)
	-- upvalues: (copy) v_u_4, (copy) v_u_1
	local v13 = p11 or 6
	if p_u_10.Anim ~= nil then
		p_u_10.Anim:Destroy()
	end
	p_u_10.Anim = v_u_4.new(v13)
	p_u_10.Anim.OnCompleted:Connect(function()
		-- upvalues: (copy) p_u_10
		p_u_10.Anim:Destroy()
		p_u_10.Anim = nil
	end)
	p_u_10.Anim.OnCanceled:Connect(function()
		-- upvalues: (copy) p_u_10
		p_u_10.Anim:Destroy()
		p_u_10.Anim = nil
	end)
	p_u_10.Anim.Maid:GiveTask(v_u_1.RenderStepped:Connect(function()
		-- upvalues: (copy) p_u_10, (copy) p_u_12
		p_u_12(p_u_10, (p_u_10.Anim:Update()))
	end))
end
function v_u_5.Open(p14, p15)
	p14.IsOpen = true
	return p14:Transition(p15, p14.SeqOpen)
end
function v_u_5.Close(p16, p17)
	p16.IsOpen = false
	return p16:Transition(p17, p16.SeqClose)
end
function v_u_5.SetDoorOpen(p18, p19)
	local v20 = p18.Model
	local v21 = v20.Door1
	local v22 = CFrame.new(0, 0, -v21.Size.Z * 0.5)
	v21.CFrame = p18.Door1CF * v22 * CFrame.Angles(p19 * 3.141592653589793 * 0.5, 0, 0) * v22:Inverse()
	local v23 = v20.Door2
	local v24 = CFrame.new(0, 0, -v23.Size.Z * 0.5)
	v23.CFrame = p18.Door2CF * v24 * CFrame.Angles(p19 * 3.141592653589793 * 0.5, 0, 0) * v24:Inverse()
end
function v_u_5.SeqOpen(p25, p26)
	if p26 == 1 then
		p25.OnOpened:Fire()
	end
	p25:SetDoorOpen(p26 < 0.5 and 2 * p26 * p26 or -1 - 2 * (p26 - 2) * p26)
end
function v_u_5.SeqClose(p27, p28)
	local v29 = 1 - p28
	p27:SetDoorOpen(v29 < 0.5 and 2 * v29 * v29 or -1 - 2 * (v29 - 2) * v29)
end
function v_u_5.Destroy(p30)
	if p30.Anim ~= nil then
		p30.Anim:Destroy()
		p30.Anim = nil
	end
	p30.OnOpened:Destroy()
	p30.OnOpened = nil
end
return v_u_5
