-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMkDHNldG1ldGF0YWJsZQNuZXcFX21haWQEX29iagVMaWdodA5GaW5kRmlyc3RDaGlsZBZGaW5kRmlyc3RDaGlsZFdoaWNoSXNBB0VuYWJsZWQERW51bQhNYXRlcmlhbAROZW9uDVNtb290aFBsYXN0aWMIU2V0VmFsdWUHRGVzdHJveQhfZW5hYmxlZAtTdHJlZXRsaWdodAdfYmluZGVyE0dldENsYXNzQWRkZWRTaWduYWwHQ29ubmVjdAVTdGFydARpbml0BmlwYWlycwZHZXRBbGwEd2FpdARtYXRoBnJhbmRvbQpTZXRFbmFibGVkB0ZsaWNrZXIEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUDU3RkBkJpbmRlcgRNYWlkB19faW5kZXgACAUBAgAAABL/AQIAAAAAAPsEAACePQEEBAAAAFIDAQCkAgEAAAAAQJ8CAwH7AwEATQID7wIAAACfAgECMAIBwQMAAAAwAAFuBAAAAIIBAgAFAwEEAAAAQAMCAwMDBAAJAgEYAAABAAAAAAAAAgAAAAAAAQACCgAAAAAHAgAAAAAWTQIAbgAAAABvBAEAvAICAwIAAACfAgMCbwUBAKkGAQC8AwJUAwAAAJ8DBAIwAQPwBAAAAA4BAwCkAwgABxhQwCsDAgCkAwoACRhQwDADAi0GAAAAggABAAsDBAMFAwYDBwMIAwkDCgMLBAcYUMADDAQJGFDAABINARgAAAAAAAABAAAAAAAAAQAAAAAAAAABEwAAAAAFAQAAAAAQTQEAwQAAAADGAgAAMAIAwQAAAAC8AgFQAQAAAJ8CAgGBPQAFAgAAAFIDAABvBAIApAIEAAAAMECfAgMBggABAAUDAwMOAAMBBAAAMEAAFw4BGAAAAQAAAQAAAQAAAAAAAAEYAAAAAAUBAQAAAAf7BAAATQMEqwAAAAC8AQD/AQAAAJ8BAwGCAAEAAgMPAw0AIwABGAAAAAAAAAEkAAAAAAQAAwAAABX7AQAATQAB7wAAAABvAQEA+wIBAJ8AAwL7AQIAMAABpQIAAAC8AQAHAwAAAJ8BAgLAAwQAEgICALwBAccFAAAAnwEDAbwBABwGAAAAnwECAYIAAQAHAwIDEAMRAxIGAwMTAxQBAyAVARgAAAAAAAABAAABAAAAAAAAAAMAAAEhAAAAAAkBAQAAAB77AQAAMAABqwAAAACkAQIAAAAQQPsDAABNAgOlAwAAALwCAtAEAAAAnwICAJ8BAARRAQ4ATQYF/wUAAAAOBgQAUggAALwGBf8FAAAAnwYDAaQGBwAAAGBApAgLAAAokICfCAECWwcICJ8GAgFuAfH/AgAAgIIAAQAMAw8DFgQAABBAAxEDFwMNAxgEAABgQAKamZmZmZm5PwMZAxoEACiQgAAoGwEYAAAAAQAAAAAAAAAAAAEAAAEAAAACAAAAAAAA/AAGKQAAAAAMAAEAAAAuqQABAIwDAQCMAQoAjAIBAKgBFgBWAAAApAQBAAAAAED7BgAATQUGpQIAAAC8BQXQAwAAAJ8FAgCfBAAEUQQEAFILAAC8CQj/BAAAAJ8JAwFuBPv/AgAAgKQEBgAAAFBAbwUHAJ8EAgGLAer/pAEBAAAAAED7AwAATQIDpQIAAAC8AgLQAwAAAJ8CAgCfAQAEUQEGAPsJAABNCAmrCAAAALwGBf8EAAAAnwYDAW4B+f8CAACAggABAAkDFgQAAABAAxEDFwMNAxgEAABQQAKamZmZmZnJPwMPADEcARgAAQAAAAEBAAAAAAAAAAAAAQAAAP8AAwAAAPsHAAAAAAAAAAAAAQAAAAAA/wADMgAAAAAGAAABAgA4owAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAoQYAAABNAgN/BwAAAJ8BAgKkAgUAAABAQE0EAKEGAAAATQMEdggAAACfAgIC/wMDAAAAAAAwAwNuCQAAAMAECgASAAMAEgACADAEA+8LAAAAwAQMADAEA/8NAAAAwAQOADAEA1APAAAA/wQEAAAAAACpBQAAMAUEqxAAAADABREAEgABABIAAwASAAQAMAUEExIAAADABRMAEgAEADAFBJ4UAAAAwAUVABIABAAwBQRpFgAAAIIEAgAXAx0EAAAAQAMeAx8DIAQAAEBAAyEDIgMjAyQGAAMCBgEDDQYCAw4DDwYEAxUGBQMbBgYDHAYAAQIEBQYBAAEYAAEAAAAAAAEAAAAAAAABAAAAAAAAAgABAAIAAAAACQAABQAABwABAAABAAAAAAAIAAAACQAAAA0BAAAAAAccBMVe3UR4Gi7Ar8r7lv0cGxLsANhIhBQc/vHM+6gBPcvIam8aiXkb

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.Binder)
local v_u_3 = require(v1.Std.Maid)
local v_u_4 = {}
v_u_4.__index = v_u_4
function v_u_4.new(p5)
	-- upvalues: (copy) v_u_4, (copy) v_u_3
	local v6 = {}
	local v7 = v_u_4
	setmetatable(v6, v7)
	v6._maid = v_u_3.new()
	v6._obj = p5
	return v6
end
function v_u_4.SetValue(p8, p9)
	local v10 = p8._obj:FindFirstChild("Light")
	v10:FindFirstChildWhichIsA("Light", true).Enabled = p9
	v10.Material = p9 and Enum.Material.Neon or Enum.Material.SmoothPlastic
end
function v_u_4.Destroy(p11)
	local v12 = p11._maid
	p11._maid = nil
	v12:Destroy()
	setmetatable(p11, nil)
end
local v_u_20 = {
	["_enabled"] = false,
	["init"] = function()
		-- upvalues: (copy) v_u_2, (copy) v_u_4, (copy) v_u_20
		local v13 = v_u_2.new("Streetlight", v_u_4)
		v_u_20._binder = v13
		v13:GetClassAddedSignal():Connect(function(p14)
			-- upvalues: (ref) v_u_20
			p14:SetValue(v_u_20._enabled)
		end)
		v13:Start()
	end,
	["SetEnabled"] = function(p15)
		-- upvalues: (copy) v_u_20
		v_u_20._enabled = p15
		for _, v16 in ipairs(v_u_20._binder:GetAll()) do
			if v16.SetValue then
				v16:SetValue(p15)
			end
			wait(math.random() * 0.1)
		end
	end,
	["Flicker"] = function()
		-- upvalues: (copy) v_u_20
		local v17 = true
		for _ = 1, 10 do
			v17 = not v17
			for _, v18 in ipairs(v_u_20._binder:GetAll()) do
				v18:SetValue(v17)
			end
			wait(0.2)
		end
		for _, v19 in ipairs(v_u_20._binder:GetAll()) do
			v19:SetValue(v_u_20._enabled)
		end
	end
}
return v_u_20
