-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMLBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplCFRBR19OQU1FG05FVFdPUktfT1dORVJfSURfVkFMVUVfTkFNRQlPd25lZFBhcnQOTmV0d29ya093bmVySWQAAQUAAAECABmjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CAxgHAAAAnwECAk0CAQAIAAAA4gMLAG8EDAAwBAO0CQAAAG8EDQAwBAPwCgAAAJ8CAgCCAgAADgMBBAAAAEADAgMDAwQEAABAQAMFAwYDBwMIAwkFAgkKAwoDCwABAAEYAAEAAAAAAAEAAAAAAAABAAABAAABAAD+AAEAAAAAAMlhilfsM5XN+6Xgw9Va0SkIZ2q4aaxtsT2X05UgmJ6Yk3Q9bKMgKG8=

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Std.TableUtils).requireValidIndexAndFreeze({
	["TAG_NAME"] = "OwnedPart",
	["NETWORK_OWNER_ID_VALUE_NAME"] = "NetworkOwnerId"
})
