-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMLBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplCFRBR19OQU1FEUVOR0lORV9TT1VORF9OQU1FCFZvbHRCaWtlC0VuZ2luZVNvdW5kAAEFAAABAgAZowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAoQYAAABNAgMYBwAAAJ8BAgJNAgEACAAAAOIDCwBvBAwAMAQDtAkAAABvBA0AMAQDIwoAAACfAgIAggIAAA4DAQQAAABAAwIDAwMEBAAAQEADBQMGAwcDCAMJBQIJCgMKAwsAAQABGAABAAAAAAABAAAAAAAAAQAAAQAAAQAA/gABAAAAAADOFxGiLb+PM/zTezZiMAQItSQ4N5iZHrErxWpovaLv40NoJ+7ZCRHh

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
return require(v1.Std.TableUtils).requireValidIndexAndFreeze({
	["TAG_NAME"] = "VoltBike",
	["ENGINE_SOUND_NAME"] = "EngineSound"
})
