-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNRBmFzc2VydAxzZXRtZXRhdGFibGUDR3VpA25ldwRNYWlkDUNvbm5lY3RQbGF5ZXIPQ29ubmVjdFN0YXRpb25zB0VuYWJsZWQEVGV4dAMlRCsEZmluZAAEZ3N1YglJc1BsYXlpbmcIU3RvcFNvbmcOUGxheUN1c3RvbVNvbmcQVXBkYXRlUGxheUJ1dHRvbgRCYXNzB1NldEJhc3MGVm9sdW1lCVNldFZvbHVtZQlDb250YWluZXIGUGxheWVyBExlZnQGVG9nZ2xlBlNvbmdJZAdUZXh0Qm94GEdldFByb3BlcnR5Q2hhbmdlZFNpZ25hbAdDb25uZWN0CEdpdmVUYXNrEE1vdXNlQnV0dG9uMURvd24NT25Tb25nU3RhcnRlZA1PblNvbmdTdG9wcGVkC09uU29uZ0VuZGVkBVJpZ2h0ClNsaWRlckJhc3MOT25WYWx1ZUNoYW5nZWQIU2V0VmFsdWUMU2xpZGVyVm9sdW1lBE5hbWUIUGxheWxpc3QTUGxheVJhbmRvbVNvbmdBZnRlcg5QbGF5UmFuZG9tU29uZwtPcGVuU2lkZWJhcghTdGF0aW9ucxFDb250YWluZXJTdGF0aW9ucwZpcGFpcnMLR2V0Q2hpbGRyZW4FRnJhbWUDSXNBBkJ1dHRvbgptUmFkaW9MaXN0B0Rlc3Ryb3kLR2V0UGxheWxpc3QIUG9wdWxhdGUST25SZWZyZXNoUmVxdWVzdGVkBFN0b3AIdG9udW1iZXIbQ2hlY2tPclByb21wdFN0ZXJlb0dhbWVwYXNzFUdldExvY2FsVmVoaWNsZVBhY2tldAZQbGF5SWQUSXNQbGF5aW5nVGhpcmRQZXJzb24JUGFzc2VuZ2VyCVRleHRMYWJlbAVQQVVTRQRQTEFZBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZAtSYWRpb0NvbmZpZwZzY3JpcHQGUGFyZW50CVJhZGlvTGlzdAtSYWRpb1BsYXllcgpSYWRpb1V0aWxzBlNsaWRlcgdWZWhpY2xlDFZlaGljbGVVdGlscwdfX2luZGV4ABIFAQIAAAAiuwEAA1ICAACkAQEAAAAAQJ8BAgH/AQIAAAAAAPsEAACePQEEBAAAAFIDAQCkAgMAAAAgQJ8CAwEwAAEfBAAAAPsDAQBNAgPvBQAAAJ8CAQIwAgF2BgAAALwCAb8HAAAAnwICAbwCASgIAAAAnwICAU0CAR8EAAAAqQMBADADAvAJAAAAggECAAoDAQQAAABAAwIEAAAgQAMDAwQDBQMGAwcDCAAQBAEYAAAAAAACAAEAAAAAAAACAAEAAAAAAAIAAAEAAAEAAAAAAhEAAAAABQABAAAAFPsBAABNAAH1AAAAAG8CAQC8AABWAgAAAJ8AAwIOAAsA+wAAAPsCAABNAQL1AAAAAG8DAQBvBAMAvAEBzAQAAACfAQQCMAEA9QAAAACCAAEABQMJAwoDCwMMAw0AIwABGAAAAAAAAAAAAQAAAAAAAAAAAAACJAAAAAACAAIAAAAP+wEAAE0AAZwAAAAAnwABAg4ABQD7AAEAvAAAqwEAAACfAAIBggABAPsAAQC8AABTAgAAAJ8AAgGCAAEAAwMOAw8DEAAoAAEYAAAAAAABAAAAAAIAAAACKQAAAAACAAEAAAAF+wAAALwAANwAAAAAnwACAYIAAQABAxEALwABGAAAAAABMAAAAAACAAEAAAAF+wAAALwAANwAAAAAnwACAYIAAQABAxEAMgABGAAAAAABMwAAAAACAAEAAAAF+wAAALwAANwAAAAAnwACAYIAAQABAxEANQABGAAAAAABNgAAAAADAQIAAAAJ+wEAADAAAQQAAAAA+wIBAE0BAgwBAAAAUgIAAJ8BAgGCAAEAAgMSAxMAOwABGAAAAAIAAAAAATwAAAAAAwECAAAACfsBAAAwAAFLAAAAAPsCAQBNAQIdAQAAAFICAACfAQIBggABAAIDFAMVAEMAARgAAAACAAAAAAFEAAAAAAoBAwAAAIsBTQMAHwAAAABNAgNvAQAAAE0BAvkCAAAATQMBxgMAAABNAgOsBAAAAE0FAcYDAAAATQQF7QUAAABNAwRcBgAAAE0EAHYHAAAAbwgIALwGA5QJAAAAnwYDAtkIAAASAAMAvAYGxwoAAACfBgMAvAQE/QsAAACfBAABTQQAdgcAAABNBgJhDAAAANkIAQASAgAAEgAAALwGBscKAAAAnwYDALwEBP0LAAAAnwQAAU0EAHYHAAAA+wcAAE0GB44NAAAA2QgCABIAAAC8BgbHCgAAAJ8GAwC8BAT9CwAAAJ8EAAFNBAB2BwAAAPsHAABNBgdVDgAAANkIAwASAAAAvAYGxwoAAACfBgMAvAQE/QsAAACfBAABTQQAdgcAAAD7BwAATQYHsw8AAADZCAQAEgAAALwGBscKAAAAnwYDALwEBP0LAAAAnwQAAfsFAQBNBAXvEAAAAE0GAQURAAAATQUGyxIAAACfBAICTQUAdgcAAABSBwQAvAUF/QsAAACfBQMBTQUEOhMAAADABxQAEgICABICAAC8BQXHCgAAAJ8FAwH7CAIATQcIBBUAAAC8BQT/FgAAAJ8FAwH7BgEATQUG7xAAAABNBwEFEQAAAE0GB0UXAAAAnwUCAk0GBToTAAAAwAgYABICAgASAgAAvAYGxwoAAACfBgMB+wkCAE0ICUsZAAAAvAYF/xYAAACfBgMBTQYAdgcAAABSCAUAvAYG/QsAAACfBgMBggABABoDAwMWAxcDGAMZAxoDGwMFAwkDHAMdAx4DHwMgAyEDIgMEAyMDJAMlBgYDEgMmAycGBwMUBwECAwQFBgcfBgEYAAAAAAAAAQAAAAEAAAAAAAEAAAAAAAAAAAAAAAAABQAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAQAAAAAAAAAAQAAAAAAAQAAAAAAAAAFAAAAAAACAAAAAAAAAAEAAAAAAAAABQAAAAAAAQAAAAAAASAAAAAABQAEAAAAFvsBAABNAAG6AAAAAPsBAQAwAAFKAQAAAPsBAgCpAgEAMAIBtAIAAAD7AgIATQEC6QMAAACfAQEB+wEDAPsEAQBNAwRKAQAAALwBAXsEAAAAnwEDAYIAAQAFAygDKQMqAysDLABQAAEYAAAAAQAAAQAAAAEAAAABAAAAAAAAAVIAAAAADQECAAAAMk0EAB8AAAAATQMEbwEAAABNAgNQAgAAAE0BApADAAAApAIFAAAAQEC8AwFoBgAAAJ8DAgCfAgAEUQIWAG8JBwC8Bwb+CAAAAJ8HAwIOBxEATQcGrAkAAABNCAB2CgAAAE0KB2ELAAAA2QwAABIABgASAgAAEgIBABIAAAC8CgrHDAAAAJ8KAwC8CAj9DQAAAJ8IAAFuAun/AgAAgPsDAABNAgNKDgAAAA4CBgD7BQAATQQFSg4AAAC8AgB7DwAAAJ8CAwGCAAEAEAMDAxYDLQMuAy8EAABAQAMwAzEDMgMzAwUDHwMdAx4DKQMsAQlLBwEYAAAAAAAAAAABAAAAAAAAAQAAAAABAAEAAAAAAAAAAAAAAAAAAP0ADQAAAAEAAAAAAAJMAAAAAAMAAgAAAAb7AAAA+wIBALwAAHsAAAAAnwADAYIAAQABAywAZQABGAAAAAAAAWYAAAAABwICAAAAME0CAD8AAAAARwIJAAAAAABNAgA/AAAAALwCAlABAAAAnwICAcYCAAAwAgA/AAAAAPsDAABNAgPvAgAAAE0DAB8DAAAAnwICAjACAD8AAAAATQIAPwAAAAD7BQEATQQFoAQAAABSBQEAnwQCALwCAhkFAAAAnwIAAU0DAD8AAAAATQIDdgYAAABNBQA/AAAAAE0EBXkHAAAA2QYAABIAAAASAAEAvAQExwgAAACfBAMAvAIC/QkAAACfAgABggABAAoDNAM1AwQDAwM2AzcDBQM4Ax0DHgELXiwBGAAAAAABAAAAAAEAAAIAAAAAAAAAAQAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAA18AAAAAAwEBAAAABfsCAABNAQL6AAAAAJ8BAQGCAAEAAQM5AGkPARgAAAAAAWoAAAAACgEEAAAASE0DAB8AAAAATQIDbwEAAABNAQL5AgAAAE0EAcYDAAAATQME7QQAAABNAgNcBQAAAE0EAvUGAAAAuz4EAqQDCAAAAHBAnwMCAkcDDwAAAACA+wUAAE0EBUoJAAAARwQKAAAAAAD7BAEAqQUBADAFBLQKAAAA+wUBAE0EBekLAAAAnwQBAYIAAQC7AQMDUgUDAKQEDQAAAMBAnwQCAfsFAgBNBAXADgAAAJ8EAQIrBAIAqQQAAIIEAgD7BQMATQQFhw8AAACfBAEC+wUBAKkGAQAwBgW0CgAAAPsGAQBNBQYdEAAAAFIGAwDGBwAA+wkBAE0ICYIRAAAAnwgBAisIBgCpCAAARwQEAAAAAABNCQQxEgAAAFYICQCfBQQBggABABMDAwMWAxcDGAMaAxsDCQM6BAAAcEADKQMqAysDAQQAAMBAAzsDPAM9Az4DPwBsEAEYAAAAAAAAAQAAAAAAAgAAAAAAAQABAAAAAAEAAAABAAAAAQMAAAAAAQAAAAABAAIAAAABAAAAAQAAAQEBAAAAAAAAAAAAAP0FbQAAAAAHAQEAAAAXTQMAHwAAAABNAgNvAQAAAE0BAvkCAAAATQMBxgMAAABNAgOsBAAAAE0DApoFAAAA+wYAAE0FBpwGAAAAnwUBAg4FAgBvBAcAZQABAG8ECAAwBAP1CQAAAIIAAQAKAwMDFgMXAxgDGQNAAw4DQQNCAwkAhAERARgAAAAAAAABAAAAAQAAAAAAAAAAAAAAAYUAAAAAAwEAAAAAHE0BAB8AAAAAqQIAADACAfABAAAAxgEAADABAB8AAAAATQEAPwIAAAAOAQgATQEAPwIAAAC8AQFQAwAAAJ8BAgHGAQAAMAEAPwIAAABNAQB2BAAAALwBAVADAAAAnwECAcYBAAAwAQB2BAAAAIIAAQAFAwMDCAM0AzUDBQCJATUBGAAAAAAAAQAAAQAAAQAAAAABAAACAAAAAAEAAAGKAAAAAAoAAAECAG6jAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwChBgAAAE0CA3YHAAAAnwECAqQCBQAAAEBApAUKAAAAkEBNBAUkCwAAAE0DBCYIAAAAnwICAqQDBQAAAEBApAYKAAAAkEBNBQYkCwAAAE0EBSoMAAAAnwMCAqQEBQAAAEBApAcKAAAAkEBNBgckCwAAAE0FBngNAAAAnwQCAqQFBQAAAEBApAgKAAAAkEBNBwgkCwAAAE0GB8wOAAAAnwUCAqQGBQAAAEBApAkKAAAAkEBNCAkkCwAAAE0HCH8PAAAAnwYCAqQHBQAAAEBATQkAjRAAAABNCAltEQAAAJ8HAgL/CAUAAAAAADAICG4SAAAAwAkTABIACAASAAEAMAkI7xQAAADACRUAEgAEABIABgASAAIAMAkIvxYAAADACRcAEgACABIABAAwCQgoGAAAAMAJGQASAAMAEgAEADAJCHsaAAAAwAkbABIABAAwCQirHAAAAMAJHQASAAIAEgAEABIABQASAAcAMAkIUx4AAADACR8AEgAEADAJCNwgAAAAwAkhADAJCFAiAAAAgggCACMDQwQAAABAA0QDRQNGBAAAQEADRwMFA0gDSQQAAJBAA0oDSwNMA00DTgNPA1ADUQYAAwQGCAMGBgoDBwYMAywGDQMPBg4DEAYPAxEGEAM1CAAICgwNDg8QAQABGAADAAAAAAABAAAAAAAAAgAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAIAAQABAAAAAA8AAAAAACwAAAAAEwAAAAALAAAAAwAAAAAAABgAAAAFAAAKAQAAAAARufH7753WQKaLNZF7LOcqNodaUbFDgbvQDrUZmmSy8i+NZAZkE2sytA==

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(v1.Std.Maid)
local v_u_3 = require(script.Parent.RadioConfig)
local v_u_4 = require(script.Parent.RadioList)
local v_u_5 = require(script.Parent.RadioPlayer)
local v_u_6 = require(script.Parent.RadioUtils)
local v_u_7 = require(script.Parent.Slider)
local v_u_8 = require(v1.Vehicle.VehicleUtils)
local v_u_9 = {}
v_u_9.__index = v_u_9
function v_u_9.new(p10)
	-- upvalues: (copy) v_u_9, (copy) v_u_2
	assert(p10)
	local v11 = {}
	local v12 = v_u_9
	setmetatable(v11, v12)
	v11.Gui = p10
	v11.Maid = v_u_2.new()
	v11:ConnectPlayer()
	v11:ConnectStations()
	v11.Gui.Enabled = true
	return v11
end
function v_u_9.ConnectPlayer(p_u_13)
	-- upvalues: (copy) v_u_5, (copy) v_u_7, (copy) v_u_3
	local v14 = p_u_13.Gui.Container.Player
	local v15 = v14.Left.Toggle
	local v_u_16 = v14.Left.SongId.TextBox
	p_u_13.Maid:GiveTask(v_u_16:GetPropertyChangedSignal("Text"):Connect(function()
		-- upvalues: (copy) v_u_16
		if v_u_16.Text:find("%D+") then
			v_u_16.Text = v_u_16.Text:gsub("%D+", "")
		end
	end))
	p_u_13.Maid:GiveTask(v15.MouseButton1Down:Connect(function()
		-- upvalues: (ref) v_u_5, (copy) p_u_13
		if v_u_5.IsPlaying() then
			p_u_13:StopSong()
		else
			p_u_13:PlayCustomSong()
		end
	end))
	p_u_13.Maid:GiveTask(v_u_5.OnSongStarted:Connect(function()
		-- upvalues: (copy) p_u_13
		p_u_13:UpdatePlayButton()
	end))
	p_u_13.Maid:GiveTask(v_u_5.OnSongStopped:Connect(function()
		-- upvalues: (copy) p_u_13
		p_u_13:UpdatePlayButton()
	end))
	p_u_13.Maid:GiveTask(v_u_5.OnSongEnded:Connect(function()
		-- upvalues: (copy) p_u_13
		p_u_13:UpdatePlayButton()
	end))
	local v17 = v_u_7.new(v14.Right.SliderBass)
	p_u_13.Maid:GiveTask(v17)
	v17.OnValueChanged:Connect(function(p18)
		-- upvalues: (ref) v_u_3, (ref) v_u_5
		v_u_3.Bass = p18
		v_u_5.SetBass(p18)
	end)
	v17:SetValue(v_u_3.Bass)
	local v19 = v_u_7.new(v14.Right.SliderVolume)
	v19.OnValueChanged:Connect(function(p20)
		-- upvalues: (ref) v_u_3, (ref) v_u_5
		v_u_3.Volume = p20
		v_u_5.SetVolume(p20)
	end)
	v19:SetValue(v_u_3.Volume)
	p_u_13.Maid:GiveTask(v19)
end
function v_u_9.ConnectStations(p_u_21)
	-- upvalues: (copy) v_u_3, (copy) v_u_5
	local v22 = p_u_21.Gui.Container.Stations.ContainerStations
	for _, v_u_23 in ipairs(v22:GetChildren()) do
		if v_u_23:IsA("Frame") then
			local v24 = v_u_23.Button
			p_u_21.Maid:GiveTask(v24.MouseButton1Down:Connect(function()
				-- upvalues: (copy) v_u_23, (ref) v_u_3, (ref) v_u_5, (copy) p_u_21
				v_u_3.Playlist = v_u_23.Name
				v_u_5.PlayRandomSongAfter = true
				v_u_5.PlayRandomSong()
				p_u_21:OpenSidebar(v_u_3.Playlist)
			end))
		end
	end
	if v_u_3.Playlist then
		p_u_21:OpenSidebar(v_u_3.Playlist)
	end
end
function v_u_9.OpenSidebar(p_u_25, p_u_26)
	-- upvalues: (copy) v_u_4, (copy) v_u_5
	if p_u_25.mRadioList ~= nil then
		p_u_25.mRadioList:Destroy()
		p_u_25.mRadioList = nil
	end
	p_u_25.mRadioList = v_u_4.new(p_u_25.Gui)
	p_u_25.mRadioList:Populate(v_u_5.GetPlaylist(p_u_26))
	p_u_25.mRadioList.Maid:GiveTask(p_u_25.mRadioList.OnRefreshRequested:Connect(function()
		-- upvalues: (copy) p_u_25, (copy) p_u_26
		p_u_25:OpenSidebar(p_u_26)
	end))
end
function v_u_9.StopSong(_)
	-- upvalues: (copy) v_u_5
	v_u_5.Stop()
end
function v_u_9.PlayCustomSong(p27)
	-- upvalues: (copy) v_u_3, (copy) v_u_5, (copy) v_u_6, (copy) v_u_8
	local v28 = p27.Gui.Container.Player.Left.SongId.TextBox.Text
	local v29 = tonumber(v28)
	if v29 == nil and v_u_3.Playlist ~= nil then
		v_u_5.PlayRandomSongAfter = true
		v_u_5.PlayRandomSong()
	else
		assert(v29)
		if not v_u_6.CheckOrPromptStereoGamepass() then
			return false
		end
		local v30 = v_u_8.GetLocalVehiclePacket()
		v_u_5.PlayRandomSongAfter = true
		local v31 = v_u_5.PlayId
		local v32 = nil
		local v33 = v_u_5.IsPlayingThirdPerson()
		if not v33 then
			if v30 == nil then
				v33 = false
			else
				v33 = not v30.Passenger
			end
		end
		v31(v29, v32, v33)
	end
end
function v_u_9.UpdatePlayButton(p34)
	-- upvalues: (copy) v_u_5
	p34.Gui.Container.Player.Left.Toggle.TextLabel.Text = v_u_5.IsPlaying() and "PAUSE" or "PLAY"
end
function v_u_9.Destroy(p35)
	p35.Gui.Enabled = false
	p35.Gui = nil
	if p35.mRadioList then
		p35.mRadioList:Destroy()
		p35.mRadioList = nil
	end
	p35.Maid:Destroy()
	p35.Maid = nil
end
return v_u_9
