-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMrBUNsb3NlA25ldwNHdWkETWFpZAlDb250YWluZXIQTW91c2VCdXR0b24xRG93bgdDb25uZWN0CEdpdmVUYXNrCHB1c2hIaWRlB0Rlc3Ryb3kTUGxheVJhbmRvbVNvbmdBZnRlcg5QbGF5UmFuZG9tU29uZxBVcGRhdGVQbGF5QnV0dG9uClN0YXJ0ZXJHdWkIUmFkaW9HdWkORmluZEZpcnN0Q2hpbGQJUGxheWVyR3VpBlBhcmVudAZXaW5kb3cRR2V0T25PcGVuZWRTaWduYWwRR2V0T25DbG9zZWRTaWduYWwHRW5hYmxlZARPcGVuC09uU29uZ0VuZGVkFGdldENlbnRlcldpbmRvd0dyb3VwA0FkZARJbml0BklzT3BlbgZUb2dnbGUEZ2FtZQdQbGF5ZXJzCkdldFNlcnZpY2ULTG9jYWxQbGF5ZXIRUmVwbGljYXRlZFN0b3JhZ2UHcmVxdWlyZQZNb2R1bGUIR2FtZVV0aWwER2FtZQxBY3Rpb25CdXR0b24TQWN0aW9uQnV0dG9uU2VydmljZQdSYWRpb1VJBnNjcmlwdAtSYWRpb1BsYXllcgAKAgABAAAABfsBAABNAAFjAAAAAJ8AAQGCAAEAAQMBABcAARgAAAAAARgAAAAABwAEAAAAJ/sBAQBNAAHvAAAAAPsCAgBNAQIfAQAAAJ8AAgLeAAAA+wEAAE0AAXYCAAAA+wYAAE0FBh8BAAAATQQFbwMAAABNAwRjBAAAAE0CA2EFAAAAwAQGABICAgC8AgLHBwAAAJ8CAwC8AAD9CAAAAJ8AAAH7AQAATQABdgIAAAD7AwMATQIDjwkAAACfAgEAvAAA/QgAAACfAAABggABAAoDAgMDAwQDBQMBAwYGAAMHAwgDCQEAFQABGAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAARYAAAAAAgABAAAAB/sAAAC8AABQAAAAAJ8AAgHGAAAA3gAAAIIAAQABAwoAHAABGAAAAAABAAEdAAAAAAIAAgAAABD7AQAATQABtAAAAAAOAAsA+wEAAE0AAekBAAAAnwABAfsAAQBHAAUAAAAAAPsAAQC8AADcAgAAAJ8AAgGCAAEAAwMLAwwDDQAlAAEYAAAAAAEAAAABAAABAAAAAyYAAAAABgAIAAAAUfsBAABNAAELAAAAAG8CAQC8AAADAgAAAJ8AAwL7AgEATQECmQMAAAAwAQAkBAAAAPsBAgAwAAEfBQAAAPsBAgD7AwMATQID7wYAAACfAgECMAIBZQcAAADGAQAA+wMCAE0CA2UHAAAAvAICLAgAAACfAgIC2QQAABIBAf8SAgQAEgICABICBQC8AgLHCQAAAJ8CAwH7AwIATQIDZQcAAAC8AgJ1CgAAAJ8CAgLZBAEAEgEB/7wCAscJAAAAnwIDAfsEAgBNAwQfBQAAAE0CA/ALAAAADgIGAPsDAgBNAgNlBwAAALwCAhYMAAAAnwICAfsDBgBNAgOzDQAAANkEAgASAgYAEgEB/7wCAscJAAAAnwIDAfsDBwBNAgPgDgAAAJ8CAQL7BQIATQQFZQcAAAC8AgJfDwAAAJ8CAwHBAQAAggABABADDgMPAxADEQMSAwMDAgMTAxQDBwMVAxYDFwMYAxkDGgMBAgMPGwEYAAAAAAAAAAEAAAAAAQAAAQAAAAAAAAEBAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAABQAAAAAAAQAAAAAAAwAAAAAAAAAACQAAAAAAAAAAAAEAEAAAAAACAAEAAAAH+wEAAE0AAWUAAAAAvAAAFgEAAACfAAIAggAAAAIDEwMXADAXARgAAAAAAAAAMQAAAAACAAEAAAAH+wEAAE0AAWUAAAAAvAAAYwEAAACfAAIAggAAAAIDEwMBADMBARgAAAAAAAAANAAAAAACAAEAAAAH+wEAAE0AAWUAAAAAvAAAMQEAAACfAAIAggAAAAIDEwMcADYcARgAAAAAAAAANwAAAAACAAEAAAAP+wEAAE0AATEAAAAAnwABAg4ABQD7AQAATQABYwEAAACfAAEBggABAPsBAABNAAEWAgAAAJ8AAQGCAAEAAwMcAwEDFwA5HQEYAAAAAAABAAAAAAIAAAACOgAAAAALAAABAgBWowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAk0BADEEAAAApAIBAAAAAEBvBAUAvAICFgMAAACfAgMCpAMHAAAAYEBNBgJACQAAAE0FBmUIAAAATQQFZQgAAACfAwICpAQHAAAAYEBNBgK9CwAAAE0FBj0KAAAAnwQCAqQFBwAAAGBATQcClAwAAABNBgdiDQAAAJ8FAgKkBgcAAABgQKQJEAAAAPBATQgJJBEAAABNBwgwDgAAAJ8GAgKkBwcAAABgQKQKEAAAAPBATQkKJBEAAABNCAl4EgAAAJ8HAgL/CAQAAAAAAMAJEwASAAIAEgABABIACAASAAMAEgAGABIABQASAAcAEgAEADAJCHMUAAAAwAkVABIACAAwCQgWFgAAAMAJFwASAAgAMAkIYxgAAADACRkAEgAIADAJCDEaAAAAwAkbABIACAAwCQisHAAAAIIIAgAdAx4EAAAAQAMfAyADIQMiAyMEAABgQAMTAyQDJQMmAycDKAMpAyoEAADwQAMSAysGBAMbBgUDFwYGAwEGBwMcBggDHQUEBQYHCAEAARgAAwAAAAAAAQABAAAAAAABAAAAAAAAAAABAAAAAAAAAQAAAAAAAAIAAAAAAAAAAAEAAAAAAAAAAAIAAQAAAAAAAAAAAAAhAAAAAwAAAAMAAAADAAAACAEAAAAACR4RP43LE4DCLNVVGSqOJiGwsfDi2kW1KYvJfPBh9RMC8C+EVGCKKo4=

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players").LocalPlayer
local v_u_2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v_u_2.Module.Window.Window)
local v_u_4 = require(v_u_2.Game.GameUtil)
local v_u_5 = require(v_u_2.ActionButton.ActionButtonService)
local v_u_6 = require(script.Parent.RadioUI)
local v_u_7 = require(script.Parent.RadioPlayer)
local v_u_10 = {
	["Init"] = function()
		-- upvalues: (copy) v_u_2, (copy) v_u_1, (copy) v_u_10, (copy) v_u_3, (copy) v_u_6, (copy) v_u_5, (copy) v_u_7, (copy) v_u_4
		local v8 = v_u_2.StarterGui:FindFirstChild("RadioGui")
		v8.Parent = v_u_1.PlayerGui
		v_u_10.Gui = v8
		v_u_10.Window = v_u_3.new()
		local v_u_9 = nil
		v_u_10.Window:GetOnOpenedSignal():Connect(function()
			-- upvalues: (ref) v_u_9, (ref) v_u_6, (ref) v_u_10, (ref) v_u_5
			v_u_9 = v_u_6.new(v_u_10.Gui)
			v_u_9.Maid:GiveTask(v_u_9.Gui.Container.Close.MouseButton1Down:Connect(function()
				-- upvalues: (ref) v_u_10
				v_u_10.Close()
			end))
			v_u_9.Maid:GiveTask(v_u_5.pushHide())
		end)
		v_u_10.Window:GetOnClosedSignal():Connect(function()
			-- upvalues: (ref) v_u_9
			v_u_9:Destroy()
			v_u_9 = nil
		end)
		if v_u_10.Gui.Enabled then
			v_u_10.Window:Open()
		end
		v_u_7.OnSongEnded:Connect(function()
			-- upvalues: (ref) v_u_7, (ref) v_u_9
			if v_u_7.PlayRandomSongAfter then
				v_u_7.PlayRandomSong()
				if v_u_9 ~= nil then
					v_u_9:UpdatePlayButton()
				end
			end
		end)
		v_u_4.getCenterWindowGroup():Add(v_u_10.Window)
	end,
	["Open"] = function()
		-- upvalues: (copy) v_u_10
		return v_u_10.Window:Open()
	end,
	["Close"] = function()
		-- upvalues: (copy) v_u_10
		return v_u_10.Window:Close()
	end,
	["IsOpen"] = function()
		-- upvalues: (copy) v_u_10
		return v_u_10.Window:IsOpen()
	end,
	["Toggle"] = function()
		-- upvalues: (copy) v_u_10
		if v_u_10.IsOpen() then
			v_u_10.Close()
		else
			v_u_10.Open()
		end
	end
}
return v_u_10
