-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMQCHZieG0yY3E5DU9uQ2xpZW50RXZlbnQHQ29ubmVjdAJlbRdGSVJFV09SS19GWF9SRU1PVEVfTkFNRQdhbmRUaGVuBGluaXQEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUGc2NyaXB0BlBhcmVudBJSb2JiZXJ5Qm9udXNDb25zdHMDU3RkDHdhaXRGb3JDaGlsZAAEAgABAAAABvsBAABNAAEGAAAAAIwBCgCfAAIBggABAAEDAQAKAAEYAAAAAAABCwAAAAAEAQEAAAAITQEAjAAAAADZAwAAEgIAALwBAccBAAAAnwEDAYIAAQACAwIDAwEACQABGAAAAAAAAAADCgAAAAAGAQMAAAAOTQEA3wAAAAD7AgAA+wMBAPsFAgBNBAUqAQAAAJ8CAwLZBAAAEgABALwCArUCAAAAnwIDAYIAAQADAwQDBQMGAQEHBwEYAAABAAAAAAAAAAAAAAUIAAAAAAUAAAECACCjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQECkBAcAAABgQE0DBCQIAAAATQIDhwkAAACfAQICpAIFAAAAQEBNBAChCgAAAE0DBPMLAAAAnwICAv8DAQAAAAAAwAQMABIAAgASAAAAEgABADAEAxMNAAAAggMCAA4DCAQAAABAAwkDCgMLBAAAQEADDAQAAGBAAw0DDgMPAxAGAgMHAQIBAAEYAAEAAAAAAAEAAAAAAAAAAAEAAAAAAAACAAEAAAAAAAgBAAAAAAPC8pI/YnrwbPA2+KtY4qK/qiUSkWnPz+19VyY+bi5JLT4KEaZgqQTE

-- Decompiled by Krnl

local v_u_1 = game:GetService("ReplicatedStorage")
local v_u_2 = require(script.Parent.RobberyBonusConsts)
local v_u_3 = require(v_u_1.Std.waitForChild)
return {
	["init"] = function(p4)
		-- upvalues: (copy) v_u_3, (copy) v_u_1, (copy) v_u_2
		local v_u_5 = p4.em
		v_u_3(v_u_1, v_u_2.FIREWORK_FX_REMOTE_NAME):andThen(function(p6)
			-- upvalues: (copy) v_u_5
			p6.OnClientEvent:Connect(function()
				-- upvalues: (ref) v_u_5
				v_u_5.vbxm2cq9(10)
			end)
		end)
	end
}
