-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMfElJPQkJFUllfVkFMVUVfTkFNRQl3b3Jrc3BhY2ULRk9MREVSX05BTUUHYW5kVGhlbgZfc2V0dXAEd2FybgVjYXRjaARpbml0EG9uUnVubmluZ0NoYW5nZWQERmlyZQVWYWx1ZQdDaGFuZ2VkB0Nvbm5lY3QVb25WZWhpY2xlTW9kZWxDaGFuZ2VkEl92ZWhpY2xlTW9kZWxWYWx1ZRJSVU5OSU5HX1ZBTFVFX05BTUUYVkVISUNMRV9NT0RFTF9WQUxVRV9OQU1FD2dldFZlaGljbGVNb2RlbARnYW1lEVJlcGxpY2F0ZWRTdG9yYWdlCkdldFNlcnZpY2UHcmVxdWlyZQNTdGQGU2lnbmFsDHdhaXRGb3JDaGlsZAdSb2JiZXJ5DVJvYmJlcnlDb25zdHMQTW9uZXlUcnVja0NvbnN0cwZzY3JpcHQGUGFyZW50A25ldwAJBQECAAAACPsBAABSAgAA+wQBAE0DBN0AAAAAjAQeAJ8BBACCAQAAAQMBAA8AARgAAAAAAAAAABAAAAAABAAEAAAAGvsAAACkAQEAAAAAQPsDAQBNAgOmAgAAAIwDHgCfAAQCwAIDABICAAASAgIAvAAAtQQAAACfAAMC+wMDAE0CA0IFAAAAvAAAtQQAAACfAAMCpAIHAAAAYEC8AAAZCAAAAJ8AAwGCAAEACQMCBAAAAEADAwYAAwQDBQMGBAAAYEADBwEADQgBGAAAAAAAAAAAAQAAAAAAAwAAAAAAAQAAAAABDgAAAAAEAQEAAAAI+wIAAE0BAhQAAAAAUgMAALwBAd0BAAAAnwEDAYIAAQACAwkDCgAZAAEYAAAAAAAAAAEaAAAAAAQBAQAAABD7AgAATQECFAAAAABNAwDsAQAAALwBAd0CAAAAnwEDAU0BAIUDAAAAwAMEABICAAC8AQHHBQAAAJ8BAwGCAAEABgMJAwsDCgMMBgIDDQECFwABGAAAAAAAAAAAAQAAAAAAAAMYAAAAAAQBAQAAAAj7AgAATQECfgAAAABSAwAAvAEB3QEAAACfAQMBggABAAIDDgMKACIAARgAAAAAAAAAASMAAAAABAEBAAAAE/sBAAAwAAGLAAAAAPsCAABNAQJ+AQAAAE0DAOwCAAAAvAEB3QMAAACfAQMBTQEAhQQAAADAAwUAEgIAALwBAccGAAAAnwEDAYIAAQAHAw8DDgMLAwoDDAYEAw0BBB8AARgAAAABAAAAAAAAAAEAAAAAAAADIAAAAAAFAQMAAAAj+wEAAFICAAD7BAEATQMElQAAAACMBB4AnwEEAsADAQASAgIAvAEBtQIAAACfAQMCpAMEAAAAMEC8AQEZBQAAAJ8BAwH7AQAAUgIAAPsEAQBNAwSZBgAAAIwEHgCfAQQCwAMHABICAgC8AQG1AgAAAJ8BAwKkAwQAAAAwQLwBARkFAAAAnwEDAYIAAQAIAxAGAwMEAwYEAAAwQAMHAxEGBQIDBRUFARgAAAAAAAAAAQAAAAAGAAAAAAEAAAAAAAABAAAAAAcAAAAAARYAAAAAAwABAAAACvsBAABNAAGLAAAAAA4ABQD7AgAATQECiwAAAABNAAHsAQAAAIIAAgACAw8DCwAoEgEYAAAAAAAAAAAAACkAAAAACAAAAQIARqMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DAKEGAAAATQIDHwcAAACfAQICpAIFAAAAQEBNBAChBgAAAE0DBPMIAAAAnwICAqQDBQAAAEBATQUABAkAAABNBAVYCgAAAJ8DAgKkBAUAAABAQKQHDQAAAMBATQYHJA4AAABNBQaOCwAAAJ8EAgL/BQQAAAAAAE0GAe8PAAAAnwYBAjAGBRQQAAAATQYB7w8AAACfBgECMAYFfhEAAADGBgAAMAYFixIAAADABhMAEgACABIAAwASAAQAEgAFADAGBRMUAAAAwAYVABIAAgASAAQAEgAFADAGBUIWAAAAwAYXABIABQAwBgV/GAAAAIIFAgAZAxMEAAAAQAMUAxUDFgQAAEBAAxcDGAMZAxoDGwMcAx0EAADAQAMeAx8DCQMOAw8GAQMIBgYDBQYHAxIDAQYHAQABGAABAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAACAAAAAAAAAAACAAEAAAAAAQAAAAABAAABAAAAAAAACAAAAAAAEwAAAAMBAAAAAAj9fVpBNPp4lM+5MNW8GOaDztxh/OW5CtImQWJOLXDIPZMCadj9XtxT

-- Decompiled by Krnl

local v1 = game:GetService("ReplicatedStorage")
local v2 = require(v1.Std.Signal)
local v_u_3 = require(v1.Std.waitForChild)
local v_u_4 = require(v1.Robbery.RobberyConsts)
local v_u_5 = require(script.Parent.MoneyTruckConsts)
local v_u_13 = {
	["onRunningChanged"] = v2.new(),
	["onVehicleModelChanged"] = v2.new(),
	["_vehicleModelValue"] = nil,
	["init"] = function()
		-- upvalues: (copy) v_u_3, (copy) v_u_4, (copy) v_u_5, (copy) v_u_13
		v_u_3(workspace, v_u_4.FOLDER_NAME, 30):andThen(function(p6)
			-- upvalues: (ref) v_u_3, (ref) v_u_5
			return v_u_3(p6, v_u_5.ROBBERY_VALUE_NAME, 30)
		end):andThen(v_u_13._setup):catch(warn)
	end,
	["_setup"] = function(p7)
		-- upvalues: (copy) v_u_3, (copy) v_u_5, (copy) v_u_13
		v_u_3(p7, v_u_5.RUNNING_VALUE_NAME, 30):andThen(function(p8)
			-- upvalues: (ref) v_u_13
			v_u_13.onRunningChanged:Fire(p8.Value)
			p8.Changed:Connect(function(p9)
				-- upvalues: (ref) v_u_13
				v_u_13.onRunningChanged:Fire(p9)
			end)
		end):catch(warn)
		v_u_3(p7, v_u_5.VEHICLE_MODEL_VALUE_NAME, 30):andThen(function(p10)
			-- upvalues: (ref) v_u_13
			v_u_13._vehicleModelValue = p10
			v_u_13.onVehicleModelChanged:Fire(p10.Value)
			p10.Changed:Connect(function(p11)
				-- upvalues: (ref) v_u_13
				v_u_13.onVehicleModelChanged:Fire(p11)
			end)
		end):catch(warn)
	end,
	["getVehicleModel"] = function()
		-- upvalues: (copy) v_u_13
		local v12 = v_u_13._vehicleModelValue
		if v12 then
			v12 = v_u_13._vehicleModelValue.Value
		end
		return v12
	end
}
return v_u_13
