-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNBB191cGRhdGUJSGVhcnRiZWF0B0Nvbm5lY3QIR2l2ZVRhc2sDbmV3DHNldG1ldGF0YWJsZQRtYWlkEG9ic2VydmVBdHRyaWJ1dGURQk9STl9BVF9BVFRSX05BTUUHVmVjdG9yMw1fbGFzdFBvc2l0aW9uCXdvcmtzcGFjZRBHZXRTZXJ2ZXJUaW1lTm93C0dldER1cmF0aW9uBG1hdGgDY29zDUdldFBvc2l0aW9uQXQDb2JqBkNGcmFtZQZBbmdsZXMHUGl2b3RUbwNtYXgGRW5naW5lDFRyYW5zcGFyZW5jeQVXaW5ncwNtaW4Jc2V0T3JpZ2luCVNldE9yaWdpbglnZXRPcmlnaW4JR2V0T3JpZ2luCXNldFRhcmdldAlTZXRUYXJnZXQJZ2V0VGFyZ2V0CUdldFRhcmdldAhzZXRTcGVlZAhTZXRTcGVlZAhnZXRTcGVlZAhHZXRTcGVlZAtzZXRUeXBlRW51bQtTZXRUeXBlRW51bQtnZXRUeXBlRW51bQtHZXRUeXBlRW51bQlzZXRCb3JuQXQJU2V0Qm9ybkF0CWdldEJvcm5BdAlHZXRCb3JuQXQRc3BlZWQgbXVzdCBiZSA+IDAGYXNzZXJ0CU1hZ25pdHVkZQ1nZXRQb3NpdGlvbkF0C0RSSUZUX1dJRFRIBGdhbWUKUnVuU2VydmljZQpHZXRTZXJ2aWNlEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUDU3RkCkJhc2VPYmplY3QGQmluZGVyD1J4SW5zdGFuY2VVdGlscwVQbGFuZQtQbGFuZUNvbnN0cwpQbGFuZVV0aWxzB19faW5kZXgIVEFHX05BTUUAEQMAAgAAAAb7AAAA+wIBALwAAAMAAAAAnwADAYIAAQABAwEAFwABGAAAAAAAARgAAAAABwICAAAADysAAQCCAAEA+wUAAE0EBf0AAAAA2QYAABICAQASAAAAvAQExwEAAACfBAMAvAIB/QIAAACfAgABggABAAMDAgMDAwQBABMAARgAAQIAAAAAAAAAAAAAAAMUAAAAAAgBBQAAACP7AgAATQEC7wAAAABSAgAAnwECAvsEAQCePQEEBAAAAFIDAQCkAgIAAAAQQJ8CAwFNAgEWAwAAAPsFAgBNBAWCBAAAAFIFAAD7BwMATQYHKAUAAADZBwAAEgIEABIAAQCfBAQAvAIC/QYAAACfAgABTDYAAqQCCAAAAHCAnwIBAjACAfwJAAAAggECAAoDBQMGBAAAEEADBwMIAwkDBAMKBAAAcIADCwEBDwUBGAAAAAAAAQAAAAAAAAIAAAAAAAAAAAAAAAAAAAAJAAAAAAACEAAAAAAQAgAAAABfpAIBAAAAAEC8AgK3AgAAAJ8CAgImAwIBvAQAyQMAAACfBAICuwkDA1IGAwCkBQYAABRAgJ8FAgJSCAMAvAYA6wcAAACfBgMCTQcAEwgAAACkCwsAACiQgFIMBgBNDQD8DAAAAJ8LAwKkDA4AADSQgIwNAABvDg8AjA8AAJ8MBAIJCgsMpAsOAAA0kICMDAAAjA0AAFsOBRCfCwQCCQkKC7wHB8IRAAAAnwcDATAGAPwMAAAAjAcBAGADFwAHAAAAjAgAAHgLAxM+CgsS9QkSCp4SCAMJAAAApAcVAABQQICfBwMCTQkAEwgAAABNCAlmFgAAADAHCNkXAAAATQkAEwgAAABNCAkCGAAAADAHCNkXAAAAggABAHgHBBJgBxYAAwAAAIwIAQAmCwMElQoLEj4JChKeEwgDCQAAAKQHGgAAZECAnwcDAk0JABMIAAAATQgJZhYAAAAwBwjZFwAAAE0JABMIAAAATQgJAhgAAAAwBwjZFwAAAIIAAQAbAwwEAAAAQAMNAw4DDwMQBAAUQIADEQMSAxMDBQQAKJCAAwsDFAQANJCAAhgtRFT7IQlAApqZmZmZmdk/AxUCAAAAAAAA8D8CAAAAAAAAAAADFgQAUECAAxcDGAMZAxoEAGRAgAAgAQEYAAAAAAABAQAAAgAAAAABAAAAAQABAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAMAAwAAAQAAAAAAAAAAAQAAAAAAAQAAAAAAAAEAAAEAAAAAAAAAAAEAAAAAAAEAAAAAAAIiAAAAAAUCAQAAAAj7AwAATQID7wAAAABNAwATAQAAAFIEAQCfAgMAggIAAAIDGwMSADgcARgAAAAAAAAAADkAAAAAAwEBAAAAB/sCAABNAQL7AAAAAE0CABMBAAAAnwECAIIBAAACAx0DEgA7HgEYAAAAAAAAADwAAAAABQIBAAAACPsDAABNAgP3AAAAAE0DABMBAAAAUgQBAJ8CAwCCAgAAAgMfAxIAPiABGAAAAAAAAAAAPwAAAAADAQEAAAAH+wIAAE0BAvsAAAAATQIAEwEAAACfAQIAggEAAAIDIQMSAEEiARgAAAAAAAAAQgAAAAAFAgEAAAAI+wMAAE0CAxUAAAAATQMAEwEAAABSBAEAnwIDAIICAAACAyMDEgBEJAEYAAAAAAAAAABFAAAAAAMBAQAAAAf7AgAATQECYQAAAABNAgATAQAAAJ8BAgCCAQAAAgMlAxIARyYBGAAAAAAAAABIAAAAAAUCAQAAAAj7AwAATQIDBQAAAABNAwATAQAAAFIEAQCfAgMAggIAAAIDJwMSAEooARgAAAAAAAAAAEsAAAAAAwEBAAAAB/sCAABNAQIJAAAAAE0CABMBAAAAnwECAIIBAAACAykDEgBNKgEYAAAAAAAAAE4AAAAABQIBAAAACPsDAABNAgMvAAAAAE0DABMBAAAAUgQBAJ8CAwCCAgAAAgMrAxIAUCwBGAAAAAAAAAAAUQAAAAADAQEAAAAH+wIAAE0BAiMAAAAATQIAEwEAAACfAQIAggEAAAIDLQMSAFMuARgAAAAAAAAAVAAAAAAHAQAAAAAZvAEAGwAAAACfAQICvAIAmwEAAACfAgICvAMAQQIAAACfAwICjAYAALcGAgADAAAAqQUAAakFAQCBAQUEAwAAAG8GAwCkBAUAAABAQJ8EAwEmBAIBTQUEqgYAAADsBgUDggYCAAcDHgMiAyYDLwMwBAAAQEADMQBWDgEYAAAAAQAAAQAAAQAAAAAAAAAAAAABAQABAFcAAAAACwICAAAAGbwCABsAAAAAnwICAisCAQCCAAEAvAMAmwEAAACfAwICKwMBAIIAAQC8BADJAgAAAJ8EAgL7BgAATQUGywMAAABSBgEAUgcCAFIIAwD7CgEATQkKGgQAAABSCgQAnwUGAIIFAAAFAx4DIgMOAzIDMwBfEQEYAAAAAQECAAABAQIAAAEAAAAAAAAAAAAAAGAAAAAACwAAAQIAfaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQEAAAAAQG8DBAC8AQEWAwAAAJ8BAwKkAgYAAABQQE0EAaEHAAAATQMESwgAAACfAgICpAMGAAAAUEBNBQGhBwAAAE0EBX8JAAAAnwMCAqQEBgAAAFBATQYBoQcAAABNBQZSCgAAAJ8EAgKkBQYAAABQQE0HAbYLAAAATQYHOAwAAACfBQICpAYGAAAAUEBNCAG2CwAAAE0HCM0NAAAAnwYCAv8HBQAAAAAAMAcHbg4AAACePQcFAgAAAFIJBwBSCgIApAgQAAAA8ECfCAMBwAgRABIAAgASAAcAEgAEABIABQASAAAAMAgH7xIAAADACBMAMAgHAxQAAADACBUAEgAGADAIBw8WAAAAwAgXABIABgAwCAcbGAAAAMAIGQASAAYAMAgHlxoAAADACBsAEgAGADAIB5scAAAAwAgdABIABgAwCAd1HgAAAMAIHwASAAYAMAgHQSAAAADACCEAEgAGADAIByUiAAAAwAgjABIABgAwCAcpJAAAAMAIJQASAAYAMAgHzyYAAADACCcAEgAGADAIB8MoAAAAwAgpADAIB8kqAAAAwAgrABIABgASAAUAMAgH6ywAAABNCAPvEgAAAE0JBbQtAAAAUgoHAJ8IAwCCCAAALgM0BAAAAEADNQM2AzcDOAQAAFBAAzkDOgM7AzwDPQM+Az8DQAMGBAAA8EAGAgMFBgMDAQYEAxwGBQMeBgYDIAYHAyIGCAMkBgkDJgYKAygGCwMqBgwDLAYNAy4GDgMOBg8DEQNBDgIDBAUGBwgJCgsMDQ4PAQABGAABAAAAAAABAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAACAAAAAAAAAQAAAAAAAAIAAQABAAAAAAAAAgAAAAAAAAARAAAYAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAACQAAAAANAAAAAAAAAQAAAAAQ+XQNTsr4cmXLsGfaF4aDkg7oyB0iIMabV+S6rJ9OM3HlL7KCVQ7q1A==

-- Decompiled by Krnl

local v_u_1 = game:GetService("RunService")
local v2 = game:GetService("ReplicatedStorage")
local v_u_3 = require(v2.Std.BaseObject)
local v4 = require(v2.Std.Binder)
local v_u_5 = require(v2.Std.RxInstanceUtils)
local v_u_6 = require(v2.Plane.PlaneConsts)
local v_u_7 = require(v2.Plane.PlaneUtils)
local v_u_8 = {}
v_u_8.__index = v_u_8
setmetatable(v_u_8, v_u_3)
function v_u_8.new(p9)
	-- upvalues: (copy) v_u_3, (copy) v_u_8, (copy) v_u_5, (copy) v_u_6, (copy) v_u_1
	local v_u_10 = v_u_3.new(p9)
	local v11 = v_u_8
	setmetatable(v_u_10, v11)
	v_u_10.maid:GiveTask(v_u_5.observeAttribute(p9, v_u_6.BORN_AT_ATTR_NAME, function(p_u_12, p13)
		-- upvalues: (ref) v_u_1, (copy) v_u_10
		if p_u_12 then
			p13:GiveTask(v_u_1.Heartbeat:Connect(function()
				-- upvalues: (ref) v_u_10, (copy) p_u_12
				v_u_10:_update(p_u_12)
			end))
		end
	end))
	v_u_10._lastPosition = Vector3.new()
	return v_u_10
end
function v_u_8._update(p14, p15)
	local v16 = workspace:GetServerTimeNow() - p15
	local v17 = p14:GetDuration()
	local v18 = math.cos(v16)
	local v19 = p14:GetPositionAt(v16)
	p14.obj:PivotTo(CFrame.new(v19, p14._lastPosition) * CFrame.Angles(0, 3.141592653589793, 0) * CFrame.Angles(0, 0, v18 * 0.4))
	p14._lastPosition = v19
	if v16 < 1 then
		local v20 = 1 - (v16 - 0) / 1
		local v21 = math.max(0, v20)
		p14.obj.Engine.Transparency = v21
		p14.obj.Wings.Transparency = v21
	elseif v17 - 1 < v16 then
		local v22 = (v16 - v17 + 1) / 1
		local v23 = math.min(1, v22)
		p14.obj.Engine.Transparency = v23
		p14.obj.Wings.Transparency = v23
	end
end
function v_u_8.SetOrigin(p24, p25)
	-- upvalues: (copy) v_u_7
	return v_u_7.setOrigin(p24.obj, p25)
end
function v_u_8.GetOrigin(p26)
	-- upvalues: (copy) v_u_7
	return v_u_7.getOrigin(p26.obj)
end
function v_u_8.SetTarget(p27, p28)
	-- upvalues: (copy) v_u_7
	return v_u_7.setTarget(p27.obj, p28)
end
function v_u_8.GetTarget(p29)
	-- upvalues: (copy) v_u_7
	return v_u_7.getTarget(p29.obj)
end
function v_u_8.SetSpeed(p30, p31)
	-- upvalues: (copy) v_u_7
	return v_u_7.setSpeed(p30.obj, p31)
end
function v_u_8.GetSpeed(p32)
	-- upvalues: (copy) v_u_7
	return v_u_7.getSpeed(p32.obj)
end
function v_u_8.SetTypeEnum(p33, p34)
	-- upvalues: (copy) v_u_7
	return v_u_7.setTypeEnum(p33.obj, p34)
end
function v_u_8.GetTypeEnum(p35)
	-- upvalues: (copy) v_u_7
	return v_u_7.getTypeEnum(p35.obj)
end
function v_u_8.SetBornAt(p36, p37)
	-- upvalues: (copy) v_u_7
	return v_u_7.setBornAt(p36.obj, p37)
end
function v_u_8.GetBornAt(p38)
	-- upvalues: (copy) v_u_7
	return v_u_7.getBornAt(p38.obj)
end
function v_u_8.GetDuration(p39)
	local v40 = p39:GetOrigin()
	local v41 = p39:GetTarget()
	local v42 = p39:GetSpeed()
	local v43 = v42 > 0
	assert(v43, "speed must be > 0")
	return (v41 - v40).Magnitude / v42
end
function v_u_8.GetPositionAt(p44, p45)
	-- upvalues: (copy) v_u_7, (copy) v_u_6
	local v46 = p44:GetOrigin()
	if v46 then
		local v47 = p44:GetTarget()
		if v47 then
			local v48 = p44:GetDuration()
			return v_u_7.getPositionAt(p45, v46, v47, v_u_6.DRIFT_WIDTH, v48)
		end
	end
end
return v4.new(v_u_6.TAG_NAME, v_u_8)
