-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNqBkNGcmFtZRJQb2ludFRvT2JqZWN0U3BhY2UBWARTaXplBG1hdGgFY2xhbXABWQFaB1ZlY3RvcjMDbmV3EmNsb3Nlc3RQb2ludFRvUGFydAtfc3R1Y2tWYWx1ZQVWYWx1ZQtPYmplY3RMb2NhbARfb2JqC1ByaW1hcnlQYXJ0DFRpbWVQb3NpdGlvbhJSb2xsT2ZmTWF4RGlzdGFuY2USUm9sbE9mZk1pbkRpc3RhbmNlBlZvbHVtZQZMb29wZWQMc2V0bWV0YXRhYmxlBV9tYWlkBG1haWQDb2JqEVNUSUNLX1JFTU9URV9OQU1FDFdhaXRGb3JDaGlsZAxfc3RpY2tSZW1vdGUUREVUT05BVEVfUkVNT1RFX05BTUUPX2RldG9uYXRlUmVtb3RlEFNUVUNLX1ZBTFVFX05BTUUYR2V0UHJvcGVydHlDaGFuZ2VkU2lnbmFsB0Nvbm5lY3QIR2l2ZVRhc2sVQ1JFQVRPUl9JRF9WQUxVRV9OQU1FD19jcmVhdG9ySWRWYWx1ZRRERVRPTkFURURfVkFMVUVfTkFNRQ9fZGV0b25hdGVkVmFsdWURX2xvY2FsbHlEZXRvbmF0ZWQNX2xvY2FsbHlTdHVjawhHZXRTdHVjaxFHZXRQbGF5ZXJCeVVzZXJJZApHZXRDcmVhdG9yCkZpcmVTZXJ2ZXIFZGVsYXkHYW5kVGhlbghEZXRvbmF0ZQxHZXREZXRvbmF0ZWQGYXNzZXJ0CFZlbG9jaXR5C1NldFZlbG9jaXR5C1JvdFZlbG9jaXR5DlNldFJvdFZlbG9jaXR5BmF0dGFjaAtJc0xpc3RlbmluZwdEZXN0cm95DklzRGVzY2VuZGFudE9mCkNhbkNvbGxpZGUNUmF5Y2FzdFBhcmFtcxpGaWx0ZXJEZXNjZW5kYW50c0luc3RhbmNlcwRFbnVtEVJheWNhc3RGaWx0ZXJUeXBlCVdoaXRlbGlzdApGaWx0ZXJUeXBlCFBvc2l0aW9uCXdvcmtzcGFjZQRVbml0B1JheWNhc3QGTm9ybWFsBkFuZ2xlcwZyYW5kb20NVG9PYmplY3RTcGFjZQhBbmNob3JlZAZpcGFpcnMKR2V0UGxheWVycwlDaGFyYWN0ZXIKX3RlbXBKb2ludAhJbnN0YW5jZQ5XZWxkQ29uc3RyYWludA5URU1QX1dFTERfTkFNRQROYW1lBVBhcnQwBVBhcnQxBlBhcmVudAdUb3VjaGVkD0xpc3RlbkZvckF0dGFjaARnYW1lB1BsYXllcnMKR2V0U2VydmljZQtMb2NhbFBsYXllcg1DdXJyZW50Q2FtZXJhEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUGc2NyaXB0B0M0VXRpbHMDU3RkBE1haWQFQXVkaW8JQ2FtU2hha2VyBEdhbWUKQmFzZU9iamVjdAdQcm9taXNlCEM0Q29uc3RzB19faW5kZXgCQzQLX19DbGFzc05hbWUAEAwCAAAABwAAAQgIQQFDTQIBhQAAAABSBQAAvAMCxgEAAACfAwMCTQUDeQIAAABNCQEvBAAAAE0ICXkCAAAAOQcIAFsGBwNNCQEvBAAAAE0ICXkCAAAAWwcIA0wuAAKkBAcAABhQgJ8EBAJNBgN4CAAAAE0KAS8EAAAATQkKeAgAAAA5CAkAWwcIA00KAS8EAAAATQkKeAgAAABbCAkDTC4AAqQFBwAAGFCAnwUEAk0HA3sJAAAATQsBLwQAAABNCgt7CQAAADkJCgBbCAkDTQsBLwQAAABNCgt7CQAAAFsJCgNMLgACpAYHAAAYUICfBgQCNDYEBgUGAABSCQQAUgoFAFILBgCkCAwAACyggJ8IBAIJBwIIggcCAA0DAQMCAwMCAAAAAAAA4D8DBAMFAwYEABhQgAMHAwgDCQMKBAAsoIAADwsBGAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAQAAAAAAUAAgAAACz7AgAATQECKgAAAABNAAHsAQAAAA4AJQD7AQEATQAB0QIAAAD7AwAATQIDbgMAAABNAQKbBAAAAG8CBQDiAwcAbwQIADAEA8YGAAAAnwAEAfsBAQBNAAHRAgAAAPsDAABNAgNuAwAAAE0BApsEAAAAbwIJAOIDDgCMBBgAMAQDKgoAAACMBAgAMAQDbwsAAABvBA8AMAQDSwwAAACpBAEAMAQDtQ0AAACfAAQBggABABADDAMNAw4DDwMQAgAA0O4QffZBAxEFAQYCmpmZmZmZuT8CAAAgIhN99kEDEgMTAxQDFQUECgsMDQIzMzMzMzPTPwAtAAEYAAAAAAAAAgAAAAAAAAAAAAAAAAADAAABAAAAAAEBAAAAAAAAAAAAAAAA/QYuAAAAAAoBBQAAAFf7AgAATQEC7wAAAABSAgAAnwECAvsEAQCePQEEBAAAAFIDAQCkAgIAAAAQQJ8CAwH7AwIATQID7wAAAACfAgECMAIBwQMAAABNAgHBAwAAADACARYEAAAAMAABbgUAAAAwAAETBgAAAPsFAwBNBAXrBwAAALwCANMIAAAAnwIDAjACASQJAAAA+wYDAE0FBvIKAAAAvAMA0wgAAACfAwMCMAMBkwsAAAD7BwMATQYHdwwAAAC8BADTCAAAAJ8EAwIwBAEqDQAAAE0FAcEDAAAATQcBKg0AAABvCQ4AvAcHlA8AAACfBwMC2QkAABIAAQASAgQAvAcHxxAAAACfBwMAvAUF/REAAACfBQAB+wgDAE0HCDwSAAAAvAUA0wgAAACfBQMCMAUB3RMAAAD7CQMATQgJRBQAAAC8BgDTCAAAAJ8GAwIwBgF8FQAAAKkHAAAwBwF9FgAAAIIBAgAXAwoDFgQAABBAAxcDGAMPAxkDGgMbAxwDHQMeAx8DDAMNAyADIQMiAyMDJAMlAyYDJwEBHAoBGAAAAAAAAQAAAAAAAAIAAAAAAAEAAAABAAEAAgAAAAAAAQACAAAAAAABAAIAAAAAAAEAAQAAAAAAAAAAAAAAAAAAAAAOAAAAAAABAAIAAAAAAAEAAgAAAh0AAAAAAwEAAAAACE0BAKEAAAAAKwEEAE0CACoBAAAATQEC7AIAAACCAQIAAwMoAwwDDQBFKQEYAAAAAAAAAABGAAAAAAUBAQAAAApNAgDdAAAAAE0BAuwBAAAA+wIAAFIEAQC8AgJhAgAAAJ8CAwKCAgIAAwMkAw0DKgBIKwEYAAAAAAEAAAAAAUkAAAAABAABAAAACfsAAAD7AwAATQIDfAAAAABNAQLsAQAAADABAH0CAAAAggABAAMDJgMNAycAUgABGAAAAAAAAAAAAVMAAAAABAEBAAAAE00BAJMAAAAAvAEBawEAAACfAQIBqQEBADABAH0CAAAA+wIAAE0BAr4DAAAAjAIBAJ8BAgLZAwAAEgAAALwBAbUEAAAAnwEDAYIAAQAFAx4DLAMnAy0DLgEFTS8BGAAAAAAAAQAAAwAAAAAAAAAAAANOAAAAAAMBAAAAAAhNAQB9AAAAACsBBABNAgB8AQAAAE0BAuwCAAAAggECAAMDJwMmAw0AVjABGAAAAAAAAAAAVwAAAAAEAgAAAAAPRwECAAAAAICpAwABqQMBALsBAwKkAgEAAAAAQJ8CAgFNAwBuAgAAAE0CA5sDAAAAMAEChQQAAACCAAEABQMxBAAAAEADDwMQAzIAWTMBGAAAAAAAAAAAAQAAAAEAAVoAAAAABAIAAAAAD0cBAgAAAACAqQMAAakDAQC7AQMCpAIBAAAAAECfAgIBTQMAbgIAAABNAgObAwAAADABAqoEAAAAggABAAUDMQQAAABAAw8DEAM0AF41ARgAAAAAAAAAAAEAAAABAAFfAAAAAAQBAAAAAAlNAwDBAAAAAE0CA3QBAAAARwICAAAAAICpAQABqQEBAIIBAgACAxcDNgBjNwEYAAAAAAAAAAAAZAAAAAAEAAEAAAAJ+wAAAPsDAABNAgMqAAAAAE0BAuwBAAAAMAEAoQIAAACCAAEAAwMMAw0DKABzAAEYAAAAAAAAAAABdAAAAAACAAEAAAAF+wAAALwAAFAAAAAAnwACAYIAAQABAzgAngEAARgAAAAAAZ8AAAAADwEFAAAAugH7BAAATQMEbgAAAAC8AQCtAQAAAJ8BAwIOAQEAggABAE0BANMCAAAAKwEBAIIAAQD7AQAAqQIBADACAaEDAAAA+wIAAE0BAsEEAAAAxgIAADACAXQFAAAA+wIBAE0BAr4GAAAAjAIBAJ8BAgLZAwAAEgIAALwBAbUHAAAAnwEDAaQBCgAAJICAnwEBAv8CAAABAAAAUgMAAMUCAwIBAAAAMAIBfQsAAACkAg8ADjTAwDACAVcQAAAA+wQAAE0DBG4AAAAATQIDmxEAAAD7BAIATQUCOxIAAABSBgAAnwQDAk0FAjsSAAAAJgMEBcYEAACkBRQAAAAwQU0IAjsSAAAATQoDBxYAAABbCQoVJgcICU0JAwcWAAAAWwgJF1IJAQC8BQXCGAAAAJ8FBQIOBSIApAgaAAAkkIFMNgACpAkcAAAksIGfCQECTQoFEB0AAACfCAMCpAkfAAB4kIGMCgAAjAsAAKQOJAAAjCCCnw4BAlsNDiFbDA0gnwkEAgkHCAlNCAU7EgAAAEMGBwgwBgKFGQAAAE0GAoUZAAAATQgAhRkAAAC8BgZGJQAAAJ8GAwJSBAYAZQAIAE0GAoUZAAAATQgAhRkAAAC8BgZGJQAAAJ8GAwJSBAYATQYARSYAAAAOBhIApAcoAAAAcEL7CAMAvAgIqykAAACfCAIAnwcABFEHCABNDgtpKgAAALwMAK0BAAAAnwwDAg4MAgCpBgAAZQACAG4H9/8CAACADgYEAKkHAQAwBwJFJgAAAGUAIQD7CgAATQkKFisAAABWCAkAuwEIAqQHLQAAAMBCnwcCAaQHLwAAJOCCbwgwAJ8HAgL7CQQATQgJ8jEAAAAwCAe6MgAAADACBzwzAAAAMAAHsTQAAAAwAgckNQAAAPsJAQBNCAm+BgAAAG8JNgCfCAIC2QoBABIABwC8CAi1BwAAAJ8IAwH7CAAATQcIJDcAAABSCQAAUgoEALwHB2s4AAAAnwcEAYIAAQA5Aw8DOQM6AygDFwM2Ay0DLgM7AwoEACSAgAM8Az0DPgM/BA40wMADQAMQA0EDQgQAADBBAgAAAAAAABRAA0MCAAAAAAAAJEADRAMBBAAkkIEDCQQAJLCBA0UDRgQAeJCBAhgtRFT7IQlAAgAAAAAAAABAAwUDRwQAjCCCA0gDSQNKBAAAcEIDSwNMA00DMQQAAMBCA04EACTgggNPA1ADUQNSA1MDVAKamZmZmZm5PwMcAywCCwxqAAEYAAAAAAAAAAECAAABAgAAAAEAAAAAAAEAAAAAAAAAAAAEAAABAAAAAAAAAQAAAAIAAAAAAQAAAAAAAAACAgAAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAEAAAAAAAAAAAAAAQAA/gADAAAAAAAAAAACAAAAAAAAAAMAAQEAAAAAAAAAAQAAAAAAAQH9AAgBAAAAAgAAAAAAAAABAAAAAQAAAAABAAEAAQACAAAAAAAAAAAAEQAAAAAAAAABawAAAAAFAQQAAAAZvAEA1wAAAACfAQICDgEBAIIAAQBNAQDBAQAAAE0EAG4CAAAATQMEmwMAAABNAgMsBAAAANkEAAASAAAAEgIAABICAQASAgIAEgIDALwCAscFAAAAnwIDAjACAXQGAAAAggABAAcDKQMXAw8DEANVAyEDNgENZlYBGAAAAAABAgAAAAAAAAAAAAAAAAAAAAAAAEdnAAAAABAAAAECAIABowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAk0BADEEAAAApAMGAAAAUEBNAgNIBwAAAKQDAQAAAABAbwUIALwDAxYDAAAAnwMDAqQECgAAAJBApAcMAAAAsEBNBgckDQAAAE0FBpgOAAAAnwQCAqQFCgAAAJBATQcDoQ8AAABNBgd2EAAAAJ8FAgKkBgoAAACQQE0IA6EPAAAATQcI0hEAAACfBgICpAcKAAAAkEBNCgO9EwAAAE0JCuASAAAATQgJ4BIAAACfBwICpAgKAAAAkEBNCgOhDwAAAE0JCksUAAAAnwgCAqQJCgAAAJBATQsDoQ8AAABNCgtyFQAAAJ8JAgKkCgoAAACQQKQNDAAAALBATQwNJA0AAABNCwycFgAAAJ8KAgLACxcA/wwFAAAAAAAwDAxuGAAAAG8NGQAwDQzlGgAAAJ49DAUIAAAAUg4MAFIPCACkDRwAAACwQZ8NAwHADR0AEgAIABIADAASAAUAEgAKABIABgAwDQzvHgAAAMANHwAwDQzXIAAAAMANIQASAAAAMA0M/SIAAADADSMAEgAJADANDNckAAAAwA0lADANDNcmAAAAwA0nADANDPEoAAAAwA0pADANDHIqAAAAwA0rADANDDgsAAAAwA0tABIACQASAAsAEgAAABIACgAwDQyVLgAAAIIMAgAvA1cEAAAAQANYA1kDWgNCBAAAUEADWwNcA10EAACQQANeBAAAsEADVANfA2ADYQNiA2MDZANlA2YDZwYAA2gDaQNqAxYEAACwQQYCAwoGAwMpBgQDKwYGAy8GBwMwBggDMwYJAzUGCgM3Bg4DVgoAAgMEBgcICQoOAQABGAABAAAAAAABAAEAAAABAAAAAAABAAAAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAEAAAAAAAABAAAAAAAAAgAAAAAAAAAAAgkAAQABAAABAAAAAAAAAQAAAAAAAAApAAADAAAABQAAAAkAAAMAAAUAAAUAAAMAAAAAAABMAQAAAAAPH8Ga8u5yBHAtBfBm4jC24h1M/vy+5Hz7a8ab1hsaybeEUbru1IelGg==

-- Decompiled by Krnl

local v_u_1 = game:GetService("Players")
local _ = v_u_1.LocalPlayer
local _ = workspace.CurrentCamera
local v2 = game:GetService("ReplicatedStorage")
require(script.Parent.C4Utils)
local v_u_3 = require(v2.Std.Maid)
local v_u_4 = require(v2.Std.Audio)
require(v2.Game.CamShaker.CamShaker)
local v_u_5 = require(v2.Std.BaseObject)
local v_u_6 = require(v2.Std.Promise)
local v_u_7 = require(script.Parent.C4Consts)
local function v_u_24(p8, p9)
	local v10 = p9.CFrame
	local v11 = v10:PointToObjectSpace(p8)
	local v12 = v11.X
	local v13 = -p9.Size.X * 0.5
	local v14 = p9.Size.X * 0.5
	local v15 = math.clamp(v12, v13, v14)
	local v16 = v11.Y
	local v17 = -p9.Size.Y * 0.5
	local v18 = p9.Size.Y * 0.5
	local v19 = math.clamp(v16, v17, v18)
	local v20 = v11.Z
	local v21 = -p9.Size.Z * 0.5
	local v22 = p9.Size.Z * 0.5
	local v23 = math.clamp(v20, v21, v22)
	return v10 * Vector3.new(v15, v19, v23)
end
local v_u_25 = {}
v_u_25.__index = v_u_25
v_u_25.__ClassName = "C4"
setmetatable(v_u_25, v_u_5)
function v_u_25.new(p26)
	-- upvalues: (copy) v_u_5, (copy) v_u_25, (copy) v_u_3, (copy) v_u_7, (copy) v_u_4
	local v_u_27 = v_u_5.new(p26)
	local v28 = v_u_25
	setmetatable(v_u_27, v28)
	v_u_27._maid = v_u_3.new()
	v_u_27.maid = v_u_27._maid
	v_u_27._obj = p26
	v_u_27.obj = p26
	v_u_27._stickRemote = p26:WaitForChild(v_u_7.STICK_REMOTE_NAME)
	v_u_27._detonateRemote = p26:WaitForChild(v_u_7.DETONATE_REMOTE_NAME)
	v_u_27._stuckValue = p26:WaitForChild(v_u_7.STUCK_VALUE_NAME)
	v_u_27._maid:GiveTask(v_u_27._stuckValue:GetPropertyChangedSignal("Value"):Connect(function()
		-- upvalues: (copy) v_u_27, (ref) v_u_4
		if v_u_27._stuckValue.Value then
			v_u_4.ObjectLocal(v_u_27._obj.PrimaryPart, 6036721389, {
				["TimePosition"] = 0.1
			})
			v_u_4.ObjectLocal(v_u_27._obj.PrimaryPart, 6036730402, {
				["RollOffMaxDistance"] = 24,
				["RollOffMinDistance"] = 8,
				["Volume"] = 0.3,
				["Looped"] = true
			})
		end
	end))
	v_u_27._creatorIdValue = p26:WaitForChild(v_u_7.CREATOR_ID_VALUE_NAME)
	v_u_27._detonatedValue = p26:WaitForChild(v_u_7.DETONATED_VALUE_NAME)
	v_u_27._locallyDetonated = false
	return v_u_27
end
function v_u_25.GetStuck(p29)
	return p29._locallyStuck or p29._stuckValue.Value
end
function v_u_25.GetCreator(p30)
	-- upvalues: (copy) v_u_1
	return v_u_1:GetPlayerByUserId(p30._creatorIdValue.Value)
end
function v_u_25.Detonate(p_u_31)
	-- upvalues: (copy) v_u_6
	p_u_31._detonateRemote:FireServer()
	p_u_31._locallyDetonated = true
	v_u_6.delay(1):andThen(function()
		-- upvalues: (copy) p_u_31
		p_u_31._locallyDetonated = p_u_31._detonatedValue.Value
	end)
end
function v_u_25.GetDetonated(p32)
	return p32._locallyDetonated or p32._detonatedValue.Value
end
function v_u_25.SetVelocity(p33, p34)
	local v35 = p34 ~= nil
	assert(v35)
	p33._obj.PrimaryPart.Velocity = p34
end
function v_u_25.SetRotVelocity(p36, p37)
	local v38 = p37 ~= nil
	assert(v38)
	p36._obj.PrimaryPart.RotVelocity = p37
end
function v_u_25.IsListening(p39)
	return p39._maid.attach ~= nil
end
function v_u_25.ListenForAttach(p_u_40)
	-- upvalues: (copy) v_u_6, (copy) v_u_24, (copy) v_u_1, (copy) v_u_7
	if not p_u_40:GetStuck() then
		p_u_40._maid.attach = p_u_40._obj.PrimaryPart.Touched:Connect(function(p41)
			-- upvalues: (copy) p_u_40, (ref) v_u_6, (ref) v_u_24, (ref) v_u_1, (ref) v_u_7
			if p41:IsDescendantOf(p_u_40._obj) then
				return
			end
			if not p41.CanCollide then
				return
			end
			p_u_40._locallyStuck = true
			p_u_40._maid.attach = nil
			v_u_6.delay(1):andThen(function()
				-- upvalues: (ref) p_u_40
				p_u_40._locallyStuck = p_u_40._stuckValue.Value
			end)
			local v42 = RaycastParams.new()
			v42.FilterDescendantsInstances = { p41 }
			v42.FilterType = Enum.RaycastFilterType.Whitelist
			local v43 = p_u_40._obj.PrimaryPart
			local v44 = v_u_24(v43.Position, p41) - v43.Position
			local v45 = workspace:Raycast(v43.Position - v44.Unit * 5, v44.Unit * 10, v42)
			local v46
			if v45 then
				v43.CFrame = CFrame.new(Vector3.new(), v45.Normal) * CFrame.Angles(0, 0, math.random() * 2 * 3.141592653589793) + v45.Position
				v46 = v43.CFrame:ToObjectSpace(p41.CFrame)
			else
				v46 = v43.CFrame:ToObjectSpace(p41.CFrame)
			end
			local v47 = p41.Anchored
			if v47 then
				for _, v48 in ipairs(v_u_1:GetPlayers()) do
					if p41:IsDescendantOf(v48.Character) then
						v47 = false
						break
					end
				end
			end
			if v47 then
				v43.Anchored = true
			else
				local v49 = not p_u_40._tempJoint
				assert(v49)
				local v_u_50 = Instance.new("WeldConstraint")
				v_u_50.Name = v_u_7.TEMP_WELD_NAME
				v_u_50.Part0 = v43
				v_u_50.Part1 = p41
				v_u_50.Parent = v43
				v_u_6.delay(0.1):andThen(function()
					-- upvalues: (copy) v_u_50
					v_u_50:Destroy()
				end)
			end
			p_u_40._stickRemote:FireServer(p41, v46)
		end)
	end
end
return v_u_25
