-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgM/BF9vYmoLUHJpbWFyeVBhcnQIQW5jaG9yZWQGQ0ZyYW1lA25ldxRTZXRQcmltYXJ5UGFydENGcmFtZQRoaWRlCkdldENyZWF0b3IQeWllbGRGb3JQcm9wZXJ0eQNvYmoFX21haWQPX2NyZWF0b3JJZFZhbHVlBVZhbHVlGEdldFByb3BlcnR5Q2hhbmdlZFNpZ25hbAdDb25uZWN0CEdpdmVUYXNrD2V4cGxvc2lvblZpc3VhbAlDaGFyYWN0ZXIISHVtYW5vaWQORmluZEZpcnN0Q2hpbGQIUm9vdFBhcnQIUG9zaXRpb24JTWFnbml0dWRlBHRhc2sFc3Bhd24IeThxcW5hbHAERW51bQ5SZW5kZXJQcmlvcml0eQZDYW1lcmEFU3RhcnQHUHJlc2V0cwlFeHBsb3Npb24FU2hha2UFZGVsYXkEU3RvcAthbmRUaGVuQ2FsbAxBc3NlbWJseU1hc3MEVW5pdAxBcHBseUltcHVsc2UCZW0TR2V0Q2xhc3NBZGRlZFNpZ25hbBpQTEFZX0VYUExPU0lPTl9SRU1PVEVfTkFNRQ1PbkNsaWVudEV2ZW50EEM0RXhwbG9kZWRSZW1vdGUEaW5pdARnYW1lB1BsYXllcnMKR2V0U2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQtMb2NhbFBsYXllcgdyZXF1aXJlBEdhbWUJQ2FtU2hha2VyA1N0ZAdQcm9taXNlBnNjcmlwdAZQYXJlbnQIQzRDb25zdHMHQzRVdGlscw9SeEluc3RhbmNlVXRpbHMIQzRCaW5kZXIJd29ya3NwYWNlDUN1cnJlbnRDYW1lcmEACAcBAAAAABNNAgBuAAAAAE0BApsBAAAAqQIBADACAUUCAAAATQEAbgAAAACkAwUAABAwgIwEAACMBZz/jAYAAJ8DBAC8AQFmBgAAAJ8BAAGCAAEABwMBAwIDAwMEAwUEABAwgAMGABIHARgAAAAAAAAAAQAAAAAAAAAAAAABEwAAAAAHAAIAAAAb+wAAALwAAP0AAAAAnwACAvsBAQCaABQAAQAAAPsAAABNAgBuAQAAAE0BApsCAAAAqQIBADACAUUDAAAATQEAbgEAAACkAwYAABRAgIwEAACMBZz/jAYAAJ8DBAC8AQFmBwAAAJ8BAAGCAAEACAMIAwEDAgMDAwQDBQQAFECAAwYAGwABGAkAAAAAAAAB9gAAAAAAAAEAAAAAAAAAAAAACxMAAAAABwECAAAAMfsCAABNAQIPAAAAAE0CABMBAAAAbwMCAJ8BAwG8AQD9AwAAAJ8BAgL7AgEAmgETAAIAAABNAgBuBAAAAE0BApsCAAAAqQIBADACAUUFAAAATQEAbgQAAACkAwgAABxggIwEAACMBZz/jAYAAJ8DBAC8AQFmCQAAAJ8BAAFNAQDBCgAAAE0DAN0LAAAAbwUMALwDA5QNAAAAnwMDAtkFAAASAAAAEgIBALwDA8cOAAAAnwMDALwBAf0PAAAAnwEAAYIAAQAQAwkDCgMCAwgDAQMDAwQDBQQAHGCAAwYDCwMMAw0DDgMPAxABARYAARgEAAAAAAAAAQAAAAAA+wAAAAAAAAEAAAAAAAAAAAAABwAAAAAAAAAAAAAAAAAAAAAFEwAAAAAEAgEAAAAG+wMAAE0CA6sAAAAAUgMAAJ8CAgGCAAEAAQMRACMAARgAAAAAAAEkAAAAAAUBAQAAAAj7AQAA+wQAAE0DBIUAAAAACQIDADACAYUAAAAAggABAAEDBAA1AAEYAAAAAAAAAAE2AAAAABEFBQAAAE0rAgEAjAIYACsDAQCMA4AA+wYAAE0FBmkAAAAAbwcBALwFBQMCAAAAnwUDAk0GBUYDAAAATQgGOwQAAAAmBwgATQgHqgUAAABgCDkAAQAAAKQICAAAHGCA+woBAE0JClIJAAAAnwgCAfsJAgBNCAnvCgAAAKQLDwAONMDATQoL7BAAAACVCQoLwAoRABICAwCfCAMCvAkIHBIAAACfCQIB+w0CAE0MDVITAAAATQsMlhQAAAC8CQiMFQAAAJ8JAwH7CgQATQkKvhYAAACMCgIAnwkCAk0LCPoXAAAAUgwIALwJCaEYAAAAnwkEASsEEABNCweqBQAAAOwKCwH1CRkKJgwDAgkLDAlDCgsCTQ8GlRoAAABNEAcHGwAAAAkODxAJDQ4KvAsGChwAAACfCwMBggABAB0DEgMTAxQDFQMWAxcDGAMZBAAcYIADGgMFAgAAAAAAAABAAxsDHAMdBA40wMADDQYEAx4DHwMgAyEDIgMjAyQCAAAAAAAA8D8DJQMmAycBBCcAARgAAQIBAgAAAAAAAAEAAQAAAwAAAAEAAAAAAAEAAAAAAAAAAAAABAAAAQAAAAAAAAABAAAAAAAAAAAAAAIBAAAAAQAAAgAAAAAAAAAAAygAAAAACAEJAAAAME0BAN8AAAAA+wIAALwCAhwBAAAAnwICAcACAgD7AwAAvAMDBwMAAACfAwICwAUEABICAQASAgIAvAMDxwUAAACfAwMB+wMDAPsGBABNBQbEBgAAALwDAwMHAAAAnwMDAk0EA4wIAAAAwAYJABICBQC8BATHBQAAAJ8EAwH7BAMAbwYKALwEBAMHAAAAnwQDAk0FBIwIAAAA2QcDABICAgASAAEAEgIGABICBwASAggAvAUFxwUAAACfBQMBggABAAsDKAMeBgADKQYCAw8DKgMUAysGAwMsBAACAwUOLQEYAAABAAAAAgQAAAAAAAAAAAAMAAAAAAAAAQAAAAAAAAMAAAAAAQAAAAAAAAAAAAAeDwAAAAAMAAABAgBUowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBAQAAAABAbwMEALwBARYDAAAAnwEDAk0CADEFAAAApAMHAAAAYEBNBgG9CAAAAE0FBuAJAAAATQQF4AkAAACfAwICpAQHAAAAYEBNBgGhCgAAAE0FBnILAAAAnwQCAqQFBwAAAGBApAgNAAAAwEBNBwgkDgAAAE0GB5wPAAAAnwUCAqQGBwAAAGBApAkNAAAAwEBNCAkkDgAAAE0HCJgQAAAAnwYCAqQHBwAAAGBATQkBoQoAAABNCAlSEQAAAJ8HAgKkCAcAAABgQKQLDQAAAMBATQoLJA4AAABNCQp6EgAAAJ8IAgKkChQAAAAwQU0JCkgVAAAA/woBAAAAAADACxYAEgAIABIABwASAAIAEgABABIABQASAAYAEgADABIACQASAAQAMAsKExcAAACCCgIAGAMuBAAAAEADLwMwAzEDMgMzBAAAYEADNAM1AzYDNwM4BAAAwEADOQM6AzsDPAM9Az4EAAAwQQM/BgYDLQEGAQABGAABAAAAAAABAAAAAAABAAEAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAQAAAAAAAAAAAQAAAAIAAQAAAAAAAAAAAAAAOAEAAAAAB+VoNDPh5OUM16xep3PEMElPjtQPPVmRoEL7g7JA7Q8RpRnMCuTBiws=

-- Decompiled by Krnl

local v1 = game:GetService("Players")
local v_u_2 = game:GetService("ReplicatedStorage")
local v_u_3 = v1.LocalPlayer
local v_u_4 = require(v_u_2.Game.CamShaker.CamShaker)
local v_u_5 = require(v_u_2.Std.Promise)
local v_u_6 = require(script.Parent.C4Consts)
local v_u_7 = require(script.Parent.C4Utils)
local v_u_8 = require(v_u_2.Std.RxInstanceUtils)
local v_u_9 = require(script.Parent.C4Binder)
local v_u_10 = workspace.CurrentCamera
return {
	["init"] = function(p11)
		-- upvalues: (copy) v_u_9, (copy) v_u_8, (copy) v_u_3, (copy) v_u_2, (copy) v_u_6, (copy) v_u_7, (copy) v_u_4, (copy) v_u_10, (copy) v_u_5
		local v_u_12 = p11.em
		v_u_9:Start()
		v_u_9:GetClassAddedSignal():Connect(function(p_u_13)
			-- upvalues: (ref) v_u_8, (ref) v_u_3
			v_u_8.yieldForProperty(p_u_13.obj, "PrimaryPart")
			if p_u_13:GetCreator() == v_u_3 then
				p_u_13._obj.PrimaryPart.Anchored = true
				p_u_13._obj:SetPrimaryPartCFrame(CFrame.new(0, -100, 0))
			end
			p_u_13._maid:GiveTask(p_u_13._creatorIdValue:GetPropertyChangedSignal("Value"):Connect(function()
				-- upvalues: (copy) p_u_13, (ref) v_u_3
				if p_u_13:GetCreator() == v_u_3 then
					local v14 = p_u_13
					v14._obj.PrimaryPart.Anchored = true
					v14._obj:SetPrimaryPartCFrame(CFrame.new(0, -100, 0))
				end
			end))
		end)
		v_u_2:FindFirstChild(v_u_6.PLAY_EXPLOSION_REMOTE_NAME).OnClientEvent:Connect(function(p15, _)
			-- upvalues: (ref) v_u_7
			v_u_7.explosionVisual(p15)
		end)
		v_u_2:FindFirstChild("C4ExplodedRemote").OnClientEvent:Connect(function(p16, p17, p18, p19, p20)
			-- upvalues: (ref) v_u_3, (copy) v_u_12, (ref) v_u_4, (ref) v_u_10, (ref) v_u_5
			local v21 = p18 or 24
			local v22 = p19 or 128
			local v23 = v_u_3.Character:FindFirstChild("Humanoid").RootPart
			local v24 = v23.Position - p16
			if v24.Magnitude < p17 then
				task.spawn(v_u_12.y8qqnalp)
				local v26 = v_u_4.new(Enum.RenderPriority.Camera.Value + 2, function(p25)
					-- upvalues: (ref) v_u_10
					v_u_10.CFrame = v_u_10.CFrame * p25
				end)
				v26:Start()
				v26:Shake(v_u_4.Presets.Explosion)
				v_u_5.delay(2):andThenCall(v26.Stop, v26)
				if not p20 then
					local v27 = 1 - v24.Magnitude / p17
					local v28 = (v22 - v21) * v27 + v21
					v23:ApplyImpulse(v23.AssemblyMass * v24.Unit * v28)
				end
			end
		end)
	end
}
